# -*- coding: utf-8 -*-
"""🧱 Basis Frans — Op school, thuis en in de stad.

Deel 1: de klas, het materiaal en wat de leerkracht zegt.
Deel 2: het huis, de stad en de weg vragen.

De zinnetjes uit deel 1 zijn precies die welke een leerkracht Frans de hele
les gebruikt. Wie ze herkent, volgt de les al half mee.
"""
from reken import mk, invul, won, WOORD

DEEL1 = [
    mk("Wat betekent l'école?", ["de school", "de les", "de klas"],
       "L'école is de school. De les is le cours of la leçon, de klas is la classe.", WOORD),
    mk("Wat betekent le cahier?", ["het schrift", "het boek", "de kaft"],
       "Le cahier is het schrift, le livre het boek.", WOORD),
    mk("Wat betekent le crayon?", ["het potlood", "de balpen", "het krijt"],
       "Le crayon is het potlood, le stylo de balpen en la craie het krijt.", WOORD),
    mk("Wat betekent la gomme?", ["de gom", "de lijm", "het elastiek"],
       "La gomme is de gom. Lijm is la colle.", WOORD),
    mk("Wat betekent le professeur?", ["de leerkracht", "de directeur", "de professor aan de universiteit"],
       "In Frankrijk is le professeur gewoon de leerkracht, ook in het lager onderwijs. Kort gezegd: le prof.", WOORD),
    mk("Wat betekent Ouvrez vos livres ?", ["Open jullie boeken", "Sluit jullie boeken", "Breng jullie boeken mee"],
       "Ouvrir is openen, fermer is sluiten. Fermez vos livres is dus boeken dicht.", WOORD),
    mk("Wat betekent Écoutez bien ?", ["Luister goed", "Schrijf goed", "Lees goed"],
       "Écouter is luisteren, écrire is schrijven en lire is lezen. Écouter en écrire lijken op elkaar: let op.", WOORD),
    mk("Wat betekent Répétez, s'il vous plaît ?", ["Herhaal alstublieft", "Antwoord alstublieft", "Zwijg alstublieft"],
       "Répéter is herhalen. Antwoorden is répondre.", WOORD),
    mk("Wat betekent la récréation?", ["de speeltijd", "de vakantie", "de turnles"],
       "La récréation is de speeltijd, kortweg la récré. De vakantie is les vacances.", WOORD),
    mk("Wat betekent les devoirs?", ["het huiswerk", "de taken op school", "de plichten van de leerkracht"],
       "Les devoirs is huiswerk. Het werkwoord devoir betekent moeten, dus huiswerk is letterlijk wat moet.", WOORD),
    mk("Wat betekent Je ne sais pas ?", ["Ik weet het niet", "Ik begrijp het niet", "Ik kan het niet"],
       "Savoir is weten, comprendre is begrijpen, pouvoir is kunnen. Drie verschillende zinnen dus.", WOORD),
    mk("Wat betekent Comment dit-on ... en français ?", ["Hoe zeg je ... in het Frans?", "Wat betekent ... in het Frans?", "Spreek je Frans?"],
       "Dit het handigste zinnetje van de les: je vraagt er een woord mee dat je niet kent.", WOORD),
    mk("Wat betekent une erreur?", ["een fout", "een oefening", "een vraag"],
       "Une erreur is een fout, une faute ook. Een oefening is un exercice.", WOORD),
    won("Le professeur gebruik je in Frankrijk ook voor een leerkracht in de lagere school.", True,
        "Waar, al zeggen ze voor de allerkleinsten ook le maître of la maîtresse.", True),
    won("Le livre betekent het schrift.", False,
        "Niet waar. Le livre is het boek, le cahier is het schrift.", False),
    won("Les vacances staat altijd in het meervoud.", True,
        "Waar: je zegt les grandes vacances voor de zomervakantie, nooit la vacance.", True),
    won("Un exercice is in het Frans een fout.", False,
        "Niet waar, un exercice is een oefening. Een fout is une erreur of une faute.", False),
    invul("Vertaal het boek naar het Frans, zonder lidwoord.", "livre",
          "Le livre. Een boekwinkel is une librairie, en dus geen bibliotheek.", WOORD),
    invul("Vertaal de school naar het Frans, zonder lidwoord.", "école",
          "L'école. Het is vrouwelijk: une grande école.", WOORD),
    invul("Vul aan: Je ne ... pas. (ik weet het niet, één woord op de puntjes)", "sais",
          "Je ne sais pas, van savoir, weten. De ontkenning zit in twee stukken: ne vóór het werkwoord en pas erachter.", WOORD),
]

DEEL2 = [
    mk("Wat betekent la maison?", ["het huis", "de kamer", "de straat"],
       "La maison is het huis. Thuis is à la maison.", WOORD),
    mk("Wat betekent la cuisine?", ["de keuken", "de koekjes", "de kast"],
       "La cuisine is zowel de keuken als de kookkunst: la cuisine française.", WOORD),
    mk("Wat betekent la chambre?", ["de slaapkamer", "de kamer in het algemeen", "de kelder"],
       "La chambre is de slaapkamer. Een gewone kamer is une pièce, en de kelder is la cave.", WOORD),
    mk("Wat betekent le jardin?", ["de tuin", "de garage", "het park"],
       "Le jardin is de tuin. Een openbaar park heet ook un jardin public.", WOORD),
    mk("Wat betekent la rue?", ["de straat", "het plein", "de weg buiten de stad"],
       "La rue is de straat, la place het plein en la route de weg buiten de bebouwing.", WOORD),
    mk("Wat betekent la gare?", ["het station", "de garage", "het veer"],
       "La gare is het treinstation. De garage is le garage, en een bushalte is un arrêt de bus.", WOORD),
    mk("Wat betekent l'hôpital?", ["het ziekenhuis", "het hotel", "het gemeentehuis"],
       "L'hôpital is het ziekenhuis, l'hôtel het hotel. Het dakje staat er waar vroeger een s stond: hospital.", WOORD),
    mk("Wat vraag je met Où est la gare ?", ["Waar is het station?", "Wanneer vertrekt de trein?", "Hoe ver is het station?"],
       "Où is waar. Hoe ver is c'est loin ?", WOORD),
    mk("Wat betekent à droite?", ["rechts", "links", "rechtdoor"],
       "À droite is rechts, à gauche is links en tout droit is rechtdoor. Droite en droit lijken op elkaar maar zijn niet hetzelfde.", WOORD),
    mk("Wat betekent tout droit?", ["rechtdoor", "helemaal rechts", "helemaal juist"],
       "Tout droit is rechtdoor. Continuez tout droit betekent ga rechtdoor verder.", WOORD),
    mk("Wat betekent C'est loin ?", ["Is het ver?", "Is het dichtbij?", "Is het open?"],
       "Loin is ver, près is dichtbij. C'est tout près is het is vlakbij.", WOORD),
    mk("Wat betekent la voiture?", ["de auto", "de fiets", "de bus"],
       "La voiture is de auto, le vélo de fiets en le bus de bus.", WOORD),
    mk("Wat betekent Je vais à l'école à pied ?", ["Ik ga te voet naar school", "Ik ga met de fiets naar school", "Ik loop op school"],
       "À pied is te voet. Met de fiets is à vélo, met de auto en voiture.", WOORD),
    won("À gauche betekent rechts.", False,
        "Niet waar. À gauche is links, à droite is rechts.", False),
    won("Een bushalte heet in het Frans un arrêt de bus.", True,
        "Waar. Arrêter is stoppen, dus un arrêt is een halte.", True),
    won("La cave is in het Frans een grot in de rotsen.", False,
        "Niet waar. La cave is de kelder; een grot is une grotte.", False),
    won("L'hôtel en l'hôpital hebben allebei een dakje op de o omdat daar vroeger een s stond.", True,
        "Waar: hostel en hospital. Dat dakje is het grafje van een verdwenen s, ook in forêt en île.", True),
    invul("Vertaal het huis naar het Frans, zonder lidwoord.", "maison",
          "La maison. Thuis is à la maison.", WOORD),
    invul("Vertaal links naar het Frans, zonder à ervoor.", "gauche",
          "Gauche. Tournez à gauche betekent sla links af.", WOORD),
    invul("Vertaal de fiets naar het Frans, zonder lidwoord.", "vélo",
          "Le vélo. Een deftiger woord is la bicyclette, maar niemand zegt dat nog.", WOORD),
]
