# -*- coding: utf-8 -*-
"""🧱 Basis Nederlands — Meervoud, verkleinwoord, hoofdletters en leestekens.

Deel 1: het meervoud en het verkleinwoord, met de open en gesloten lettergreep.
Deel 2: hoofdletters, leestekens en een paar woorden die iedereen door elkaar
haalt (hun en hen laten we bewust liggen; dat hoort niet bij een opfrissing
van de basis).
"""
from reken import mk, invul, won, WOORD

DEEL1 = [
    mk("Wat is het meervoud van boek?", ["boeken", "boekken", "boeks"],
       "De meeste woorden krijgen -en. Een s krijgen vooral woorden op -e, -el, -em, -en, -er en op een klinker: tafels, meisjes, auto's.", WOORD),
    mk("Wat is het meervoud van tafel?", ["tafels", "tafelen", "tafells"],
       "Woorden op -el, -em, -en en -er krijgen een s: tafels, bezems, wagens, bakkers.", WOORD),
    mk("Wat is het meervoud van auto?", ["auto's", "autos", "autoos"],
       "Na een losse klinker komt er een apostrof voor de s, anders zou je autos lezen met een korte o: auto's, foto's, oma's.", WOORD),
    mk("Wat is het meervoud van bus?", ["bussen", "busen", "busses"],
       "De u klinkt kort, dus je verdubbelt de s om dat zo te houden. Anders zou je buzen lezen.", WOORD),
    mk("Wat is het meervoud van raam?", ["ramen", "ramens", "raamen"],
       "In ramen staat de a in een open lettergreep (ra-men) en klinkt hij al lang. Eén a volstaat dus.", WOORD),
    mk("Waarom schrijf je bussen met dubbele s maar ramen met één a?", ["om de klank van de klinker gelijk te houden", "omdat bus korter is dan raam", "dat is willekeurig, je moet het leren"],
       "Een korte klinker houd je kort door de medeklinker te verdubbelen. Een lange klinker in een open lettergreep heeft maar één letter nodig.", WOORD),
    mk("Wat is het meervoud van kind?", ["kinderen", "kinden", "kinds"],
       "Een handvol woorden krijgt -eren: kinderen, eieren, bladeren, volkeren. Die moet je kennen.", WOORD),
    mk("Wat is het verkleinwoord van boom?", ["boompje", "boomtje", "boomje"],
       "Na een m komt -pje: boompje, bloempje, raampje.", WOORD),
    mk("Wat is het verkleinwoord van bal?", ["balletje", "baltje", "balje"],
       "Na een korte klinker plus l, m, n of r komt -etje, met verdubbeling: balletje, mannetje, kommetje.", WOORD),
    mk("Wat is het verkleinwoord van koning?", ["koninkje", "koningje", "koningetje"],
       "Na -ing wordt het -kje, en de g verdwijnt: koninkje, woninkje, ringetje is dan weer de uitzondering omdat ring kort is.", WOORD),
    mk("Wat is het meervoud van ei?", ["eieren", "eien", "eis"],
       "Eieren, met -eren. Net als kinderen en bladeren.", WOORD),
    mk("Wat is het meervoud van museum?", ["musea of museums", "museumen", "museumn"],
       "Woorden uit het Latijn houden vaak hun oude meervoud: musea, maar museums mag ook.", WOORD),
    mk("Wat is het verkleinwoord van huis?", ["huisje", "huistje", "huizetje"],
       "Na de meeste medeklinkers komt gewoon -je: huisje, boekje, kastje.", WOORD),
    won("Woorden die op -el of -er eindigen, krijgen in het meervoud een s.", True,
        "Waar: tafels, wandelaars, bakkers, sleutels. Dat scheelt een hoop twijfelen.", True),
    won("Na een losse klinker schrijf je het meervoud met een apostrof: oma's.", True,
        "Waar, anders verandert de klank: omas zou je lezen als o-mas. Hetzelfde bij foto's en menu's.", True),
    won("Het meervoud van kind is kinden.", False,
        "Niet waar, het is kinderen. Een kleine groep woorden krijgt -eren.", False),
    won("Elk woord krijgt in het verkleinwoord gewoon -je erachter.", False,
        "Niet waar. Na een m komt -pje, na -ing komt -kje, en na een korte klinker met l, m, n of r komt -etje.", False),
    invul("Wat is het meervoud van kat?", "katten",
          "De a klinkt kort, dus verdubbel je de t: katten. Anders zou je katen lezen.", WOORD),
    invul("Wat is het meervoud van foto?", "foto's",
          "Na een losse klinker komt een apostrof voor de s: foto's.", WOORD),
    invul("Wat is het verkleinwoord van raam?", "raampje",
          "Na een m komt -pje: raampje.", WOORD),
]

DEEL2 = [
    mk("Welk woord krijgt een hoofdletter?", ["België", "maandag", "zomer"],
       "Landen, steden, talen en namen krijgen een hoofdletter. Dagen, maanden en seizoenen niet.", WOORD),
    mk("Hoe schrijf je de naam van de taal die we hier spreken?", ["Nederlands", "nederlands", "NEDERLANDS"],
       "Talen krijgen een hoofdletter in het Nederlands: Nederlands, Frans, Engels. In het Frans juist niet.", WOORD),
    mk("Welke zin is juist geschreven?", ["Volgende maandag ga ik naar Antwerpen.", "Volgende Maandag ga ik naar antwerpen.", "volgende maandag ga ik naar Antwerpen."],
       "Een zin begint met een hoofdletter, een stad krijgt er een, een weekdag niet.", WOORD),
    mk("Waar hoort een vraagteken?", ["achter een vraag", "achter elke lange zin", "achter een uitroep"],
       "Een vraag krijgt een vraagteken, een uitroep een uitroepteken, en de rest een punt.", WOORD),
    mk("Welke zin heeft de komma op de juiste plaats?", ["Als het regent, blijven we thuis.", "Als het regent blijven, we thuis.", "Als, het regent blijven we thuis."],
       "De komma staat tussen de twee stukken van de zin, niet middenin een stuk. Lees de zin hardop: waar je even stopt, hoort de komma.", WOORD),
    mk("Wat zet je rond woorden die iemand letterlijk zegt?", ["aanhalingstekens", "haakjes", "een streepje"],
       "Hij zei: Ik kom morgen. Met aanhalingstekens laat je zien dat het de woorden van iemand anders zijn.", WOORD),
    mk("Welke zin is juist?", ["Ik heb appels, peren en bananen gekocht.", "Ik heb appels peren, en bananen gekocht.", "Ik heb, appels peren en bananen gekocht."],
       "In een opsomming staat een komma tussen de delen, en voor en meestal geen komma.", WOORD),
    mk("Hoe schrijf je het woord ik midden in een zin?", ["met een kleine letter", "altijd met een hoofdletter", "met een hoofdletter als het over jezelf gaat"],
       "Anders dan in het Engels krijgt ik geen hoofdletter: vandaag ga ik naar huis.", WOORD),
    mk("Welke schrijfwijze is juist?", ["een fietspad", "een fiets pad", "een fiets-pad"],
       "Een samenstelling schrijf je in het Nederlands aan elkaar: fietspad, voetbalploeg, computerscherm. Los schrijven is een Engelse gewoonte.", WOORD),
    mk("Welke schrijfwijze is juist?", ["handdoek", "handoek", "hand doek"],
       "Hand plus doek wordt handdoek, met twee d's. Je schrijft gewoon de twee woorden volledig achter elkaar.", WOORD),
    mk("Wanneer gebruik je een uitroepteken?", ["bij een uitroep of een bevel", "aan het einde van elke zin", "bij een vraag"],
       "Pas op! Kom hier! Gebruik het spaarzaam, anders roept je tekst de hele tijd.", WOORD),
    mk("Welke zin is juist?", ["Weet jij hoe laat het is?", "Weet jij hoe laat het is.", "weet jij hoe laat het is?"],
       "Hoofdletter vooraan en een vraagteken achteraan, want het is een vraag.", WOORD),
    mk("Hoe schrijf je de naam van een maand?", ["met een kleine letter: januari", "met een hoofdletter: Januari", "allebei mag"],
       "Maanden en dagen krijgen in het Nederlands geen hoofdletter. In het Engels wel, en daar komt de verwarring vandaan.", WOORD),
    won("Talen krijgen in het Nederlands een hoofdletter.", True,
        "Waar: Nederlands, Frans, Duits, Engels. Ook al staat het midden in de zin.", True),
    won("Samenstellingen schrijf je in het Nederlands aan elkaar.", True,
        "Waar: fietspad, keukentafel, zomervakantie. Twijfel je, dan hoor je het aan de klemtoon: die ligt op het eerste deel.", True),
    won("Dagen van de week krijgen een hoofdletter.", False,
        "Niet waar: maandag, dinsdag, woensdag, allemaal met een kleine letter.", False),
    won("Achter een vraag mag ook een punt staan.", False,
        "Niet waar, een vraag krijgt een vraagteken. Alleen bij een vraag die eigenlijk geen antwoord verwacht, zie je soms een punt, maar dat is uitzonderlijk.", False),
    invul("Vul aan met het juiste woord: Ik spreek ... en Frans. (de taal die we hier spreken, met de juiste hoofdletter)", "Nederlands",
          "Talen krijgen een hoofdletter, ook midden in de zin.", WOORD),
    invul("Schrijf als één woord: voetbal + ploeg", "voetbalploeg",
          "Samenstellingen schrijf je aan elkaar. Voetbal ploeg los schrijven is een veelgemaakte fout.", WOORD),
    invul("Welk leesteken hoort achter: Hoe heet jij", "vraagteken",
          "Het is een vraag, dus een vraagteken: Hoe heet jij?", WOORD),
]
