# -*- coding: utf-8 -*-
"""🧱 Basis Nederlands — Woordsoorten: welk woord doet wat.

Deel 1: lidwoord, zelfstandig naamwoord, bijvoeglijk naamwoord, werkwoord.
Deel 2: voornaamwoorden, telwoord, voorzetsel en voegwoord.

Dit is het fundament onder alles wat daarna komt: wie de persoonsvorm niet
kan aanwijzen, kan de d- of t-regel niet toepassen, hoe goed hij ze ook
uit het hoofd kent.
"""
from reken import mk, invul, won, WOORD

DEEL1 = [
    mk("Welk woord is het lidwoord in: De hond blaft?", ["de", "hond", "blaft"],
       "Het Nederlands heeft maar drie lidwoorden: de, het en een. Ze staan vóór een zelfstandig naamwoord.", WOORD),
    mk("Hoeveel lidwoorden heeft het Nederlands?", ["drie: de, het en een", "twee: de en het", "vier: de, het, een en geen"],
       "De, het en een. Geen is er geen: dat is een ontkennend woord.", WOORD),
    mk("Welk woord is het zelfstandig naamwoord in: een grote tafel?", ["tafel", "een", "grote"],
       "Een zelfstandig naamwoord is een woord voor een ding, een dier, een persoon of een gedachte. Je kan er de, het of een voor zetten.", WOORD),
    mk("Wat is een zelfstandig naamwoord?", ["een woord voor een ding, dier, persoon of gedachte", "een woord dat zegt hoe iets is", "een woord dat zegt wat iemand doet"],
       "Hoe iets is, zegt een bijvoeglijk naamwoord. Wat iemand doet, zegt een werkwoord.", WOORD),
    mk("Welk woord is het bijvoeglijk naamwoord in: de rode fiets?", ["rode", "de", "fiets"],
       "Een bijvoeglijk naamwoord zegt hoe iets is en staat meestal vlak vóór het zelfstandig naamwoord.", WOORD),
    mk("Waarover zegt een bijvoeglijk naamwoord iets?", ["over een zelfstandig naamwoord", "over een werkwoord", "over een lidwoord"],
       "Een snelle fiets: snel hoort bij fiets. Zegt een woord iets over het werkwoord, dan heet het een bijwoord: hij fietst snel.", WOORD),
    mk("Welk woord is het werkwoord in: Sara leest een boek?", ["leest", "Sara", "boek"],
       "Een werkwoord zegt wat er gebeurt of hoe iets is. Je kan het vervoegen: ik lees, jij leest, wij lezen.", WOORD),
    mk("Welk van deze woorden is een werkwoord?", ["zwemmen", "zwembad", "zwemmer"],
       "Zwemmen is het werkwoord. Een zwembad en een zwemmer zijn dingen of personen, dus zelfstandige naamwoorden.", WOORD),
    mk("Wat voor woord is snel in: Hij loopt snel?", ["een bijwoord, het hoort bij loopt", "een bijvoeglijk naamwoord, het hoort bij hij", "een werkwoord"],
       "Snel zegt hier hóe hij loopt, dus het hoort bij het werkwoord. In een snelle loper hoort het bij loper en is het een bijvoeglijk naamwoord.", WOORD),
    mk("Bij welk woord hoort mooie in: het mooie lied?", ["bij lied", "bij het", "bij geen enkel woord"],
       "Mooie zegt hoe het lied is. Daarom staat het er vlak voor, tussen het lidwoord en het zelfstandig naamwoord.", WOORD),
    mk("Welk woord is het lidwoord in: Een jongen fietst naar huis?", ["een", "jongen", "naar"],
       "Een is hier lidwoord. Naar is een voorzetsel en jongen een zelfstandig naamwoord.", WOORD),
    mk("Welke woordsoorten staan er in: De kat slaapt?", ["lidwoord, zelfstandig naamwoord, werkwoord", "lidwoord, werkwoord, bijvoeglijk naamwoord", "twee zelfstandige naamwoorden en een werkwoord"],
       "De is lidwoord, kat is zelfstandig naamwoord, slaapt is werkwoord. Een hele zin met maar drie woorden.", WOORD),
    mk("Welk woord hoort niet in dit rijtje: boom, huis, lopen, fiets?", ["lopen", "boom", "fiets"],
       "Boom, huis en fiets zijn zelfstandige naamwoorden, dingen dus. Lopen is een werkwoord.", WOORD),
    won("Een lidwoord staat altijd vóór een zelfstandig naamwoord.", True,
        "Waar, al kan er nog iets tussen staan: de oude boom. Een lidwoord op zichzelf bestaat niet.", True),
    won("Het woord het is niet altijd een lidwoord.", True,
        "Waar. In het boek is het een lidwoord, in het regent verwijst het naar niets en is het een voornaamwoord.", True),
    won("Elk woord dat op -en eindigt is een werkwoord.", False,
        "Niet waar. Boeken, tekeningen en kinderen eindigen ook op -en en zijn zelfstandige naamwoorden in het meervoud.", False),
    won("Een bijvoeglijk naamwoord zegt iets over het werkwoord.", False,
        "Niet waar, het zegt iets over een zelfstandig naamwoord. Over het werkwoord gaat een bijwoord.", False),
    invul("Welk lidwoord hoort bij boek: de of het?", "het",
          "Het boek. Of het de of het is, moet je per woord weten; er is geen regel voor.", WOORD),
    invul("Schrijf het werkwoord uit deze zin: De hond blaft hard.", "blaft",
          "Blaft zegt wat de hond doet. Hard zegt hóe hij blaft en is dus een bijwoord.", WOORD),
    invul("Schrijf het bijvoeglijk naamwoord uit deze zin: Ik zie een groene deur.", "groene",
          "Groene zegt hoe de deur is. Zonder lidwoord zou je zeggen: de deur is groen, zonder e.", WOORD),
]

DEEL2 = [
    mk("Wat zijn ik, jij en hij voor woorden?", ["persoonlijke voornaamwoorden", "bezittelijke voornaamwoorden", "lidwoorden"],
       "Ze vervangen een naam: in plaats van Sara leest zeg je zij leest.", WOORD),
    mk("Welk woord is een bezittelijk voornaamwoord in: Zij leest haar boek?", ["haar", "zij", "boek"],
       "Een bezittelijk voornaamwoord zegt van wie iets is: mijn, jouw, zijn, haar, ons, hun.", WOORD),
    mk("Welk woord is het voorzetsel in: De kat zit op de stoel?", ["op", "zit", "stoel"],
       "Een voorzetsel zegt waar of wanneer iets is: op, onder, naast, voor, na, tijdens.", WOORD),
    mk("Hoe herken je een voorzetsel makkelijk?", ["je kan het invullen in: de kat zit ... de doos", "het staat altijd vooraan in de zin", "het eindigt altijd op -en"],
       "Op, in, onder, naast, achter, voor: ze passen er allemaal in. Dat trucje werkt voor bijna alle voorzetsels van plaats.", WOORD),
    mk("Welk woord is het voegwoord in: Ik lees en hij schrijft?", ["en", "ik", "schrijft"],
       "Een voegwoord plakt twee stukken aan elkaar: en, of, maar, want, omdat, als.", WOORD),
    mk("Welk woord is het telwoord in: Drie kinderen spelen buiten?", ["drie", "kinderen", "buiten"],
       "Een telwoord zegt hoeveel. Dat kan een getal zijn, maar ook veel, weinig of enkele.", WOORD),
    mk("Welk van deze woorden is een voorzetsel?", ["onder", "onderweg", "ondergaan"],
       "Onder is een voorzetsel. Onderweg is een bijwoord en ondergaan is een werkwoord.", WOORD),
    mk("Wat voor woord is mijn in: mijn jas?", ["een bezittelijk voornaamwoord", "een persoonlijk voornaamwoord", "een bijvoeglijk naamwoord"],
       "Het zegt van wie de jas is. Het persoonlijke voornaamwoord zou ik zijn.", WOORD),
    mk("In welke zin staat een voegwoord?", ["Ik blijf thuis want het regent", "De bal ligt onder de tafel", "Mijn fiets is nieuw"],
       "Want verbindt twee zinnen. Onder is een voorzetsel en mijn een bezittelijk voornaamwoord.", WOORD),
    mk("Wat voor woord is hem in: Ik zie hem?", ["een persoonlijk voornaamwoord", "een bezittelijk voornaamwoord", "een zelfstandig naamwoord"],
       "Hem vervangt een naam, net als hij. Hij hoort bij wie iets doet, hem bij wie iets ondergaat.", WOORD),
    mk("Welk woord kan twee zinnen verbinden?", ["maar", "mooi", "muur"],
       "Maar is een voegwoord: ik wou komen maar ik was ziek. Mooi en muur verbinden niets.", WOORD),
    mk("Wat voor woord hoort op de puntjes: De bal ligt ... de tafel?", ["een voorzetsel", "een werkwoord", "een lidwoord"],
       "Onder, op, naast, achter: allemaal voorzetsels. Dat is precies het trucje om er een te herkennen.", WOORD),
    mk("Naar wie verwijst wij in: Wij gaan zwemmen?", ["naar meer mensen, met jezelf erbij", "naar meer mensen, zonder jezelf", "naar één persoon"],
       "Wij is ik plus iemand anders. Zonder jezelf erbij zou je zij zeggen.", WOORD),
    won("Want en omdat zijn allebei voegwoorden.", True,
        "Waar. Ze zeggen allebei een reden, maar de zin erna krijgt een andere woordvolgorde: want ik ben ziek, omdat ik ziek ben.", True),
    won("Een telwoord hoeft geen cijfer te zijn.", True,
        "Waar. Veel, weinig, enkele en alle zeggen ook hoeveel, en het zijn ook telwoorden.", True),
    won("Jij is een bezittelijk voornaamwoord.", False,
        "Niet waar, jij is persoonlijk. Het bezittelijke is jouw: jouw jas.", False),
    won("Een voorzetsel staat altijd aan het begin van een zin.", False,
        "Niet waar. Het staat vóór het woord waar het bij hoort, en dat kan overal in de zin zijn: de kat slaapt onder het bed.", False),
    invul("Schrijf het voorzetsel uit deze zin: De poes slaapt onder het bed.", "onder",
          "Onder zegt waar de poes ligt. Het is een lidwoord en bed een zelfstandig naamwoord.", WOORD),
    invul("Schrijf het voegwoord uit deze zin: Ik eet een appel en jij een peer.", "en",
          "En plakt de twee stukken aan elkaar. Zonder voegwoord zouden het twee losse zinnen zijn.", WOORD),
    invul("Welk persoonlijk voornaamwoord gebruik je als je over jezelf praat?", "ik",
          "Ik. Praat je over jezelf samen met anderen, dan is het wij.", WOORD),
]
