# -*- coding: utf-8 -*-
"""🧱 Basis — Wiskundewoorden.

Dit hoofdstuk gaat over de woorden zelf, dus vakjargon valt niet te vermijden.
Wel opent deel 1 met een som die je ziet, zodat een kind eerst iets herkent
voor het het woord erbij moet zoeken.

Deel 1: welk getal heet hoe, en eenvoudige opdrachten met die woorden.
Deel 2: de deling met rest, en terugrekenen (wat was het deeltal?).
"""
from fractions import Fraction as F
from reken import mk, invul, won, enige, WOORD

DEEL1 = [
    mk("12 + 5 = 17. Hoe heet de 17?", ["De som", "Het verschil", "Het product"],
       "De uitkomst van een optelling heet de som. 12 en 5 zijn de termen.",
       WOORD),
    mk("4 × 6 = 24. Hoe heet de 24?", ["Het product", "De som", "Het quotiënt"],
       "De uitkomst van een vermenigvuldiging heet het product. 4 en 6 zijn de factoren.",
       WOORD),
    mk("17 − 5 = 12. Hoe heet de 12?", ["Het verschil", "De som", "De rest"],
       "De uitkomst van een aftrekking heet het verschil: zoveel liggen 17 en 5 uit elkaar.",
       WOORD),
    mk("24 : 6 = 4. Hoe heet de 4?", ["Het quotiënt", "Het product", "De deler"],
       "De uitkomst van een deling heet het quotiënt.",
       WOORD),
    mk("In de breuk 3/4: hoe heet de 3?", ["De teller", "De noemer", "De breukstreep"],
       "Het getal boven de breukstreep is de teller. Die telt hoeveel stukken je neemt.",
       WOORD),
    mk("In de breuk 3/4: hoe heet de 4?", ["De noemer", "De teller", "De deler"],
       "Het getal onder de breukstreep is de noemer. Die zegt in hoeveel gelijke stukken het geheel verdeeld is.",
       WOORD),
    won("In 4 × 6 = 24 zijn 4 en 6 de factoren.", True,
        "Waar. De getallen die je vermenigvuldigt heten factoren.",
        True),
    invul("Wat is de som van 8 en 7?", "15",
          "Som betekent optellen: 8 + 7 = 15.",
          8 + 7),
    invul("Wat is het product van 6 en 7?", "42",
          "Product betekent vermenigvuldigen: 6 × 7 = 42.",
          6 * 7),
    invul("Wat is het verschil tussen 20 en 8?", "12",
          "Verschil betekent aftrekken: 20 − 8 = 12.",
          20 - 8),
    mk("24 : 6 = 4. Hoe heet de 24?", ["Het deeltal", "De deler", "Het quotiënt"],
       "Het deeltal is het getal dat verdeeld wordt: 24.",
       WOORD),
    mk("24 : 6 = 4. Hoe heet de 6?", ["De deler", "Het deeltal", "De factor"],
       "De deler is het getal waardoor je deelt: 6.",
       WOORD),
    won("Bij 12 + 5 heten 12 en 5 de factoren.", False,
        "Niet waar. Bij optellen heten ze termen. Factoren zijn de getallen bij vermenigvuldigen.",
        False),
    mk("Wat is het quotiënt van 30 en 5?", ["6", "25", "150"],
       "Quotiënt betekent delen: 30 : 5 = 6. 25 is het verschil en 150 het product.",
       F(30, 5)),
    mk("Je verdeelt 13 snoepjes over 4 kinderen. Elk krijgt er 3. Hoeveel blijven er over?", ["1", "3", "4"],
       "4 kinderen × 3 snoepjes = 12. Van de 13 blijft er 1 over. Dat is de rest.",
       13 % 4),
    mk("13 : 4 = 3 rest 1. Hoe heet de 1?", ["De rest", "Het quotiënt", "De deler"],
       "Wat overblijft na een deling heet de rest.",
       WOORD),
    won("De breukstreep betekent gedeeld door.", True,
        "Waar. 3/4 is hetzelfde als 3 : 4.",
        True),
    mk("Welke breuk heeft teller 2 en noemer 5?", ["2/5", "5/2", "2/7"],
       "De teller staat boven, de noemer onder: 2/5.",
       f"{2}/{5}"),
    won("In 9 − 4 = 5 heet 9 de aftrekker.", False,
        "Niet waar. 9 is het aftrektal: daar trek je iets van af. 4 is de aftrekker.",
        False),
    invul("Wat is de teller van de breuk 7/9?", "7",
          "De teller staat boven de breukstreep: 7.",
          7),
]

DEEL2 = [
    mk("Wat is de som van 3,5 en 1,5?", ["5", "2", "5,25"],
       "Som betekent optellen: 3,5 + 1,5 = 5. Het verschil zou 2 zijn.",
       F(7, 2) + F(3, 2)),
    invul("Wat is het product van 12 en 5?", "60",
          "Product betekent vermenigvuldigen: 12 × 5 = 60.",
          12 * 5),
    mk("Wat is het verschil tussen 100 en 37?", ["63", "137", "73"],
       "Verschil betekent aftrekken: 100 − 37 = 63. 137 is de som.",
       100 - 37),
    mk("Wat is het quotiënt van 56 en 8?", ["7", "48", "64"],
       "Quotiënt betekent delen: 56 : 8 = 7.",
       F(56, 8)),
    mk("Bereken 23 : 5. Wat is de rest?", ["3", "4", "5"],
       "5 past 4 keer in 23, want 4 × 5 = 20. Er blijft 23 − 20 = 3 over.",
       23 % 5),
    mk("Bereken 23 : 5. Wat is het quotiënt?", ["4", "3", "5"],
       "5 past 4 keer in 23 (4 × 5 = 20). Het quotiënt is 4, de rest 3.",
       23 // 5),
    invul("Bereken 38 : 6. Wat is de rest?", "2",
          "6 past 6 keer in 38, want 6 × 6 = 36. Er blijft 38 − 36 = 2 over.",
          38 % 6),
    mk("Bij een deling is de deler 7. Welke rest kan niet?", ["8", "6", "0"],
       "De rest is altijd kleiner dan de deler. Blijven er 8 over, dan kan je nog een groepje van 7 maken.",
       enige([8, 6, 0], lambda r: r >= 7)),
    won("De rest van een deling kan groter zijn dan de deler.", False,
        "Niet waar. Is wat overblijft even groot als de deler of groter, dan kan je nog een keer delen.",
        False),
    mk("Het quotiënt is 5, de deler 4 en de rest 3. Wat was het deeltal?", ["23", "20", "12"],
       "Quotiënt × deler + rest = deeltal: 5 × 4 + 3 = 23.",
       5 * 4 + 3),
    invul("Het quotiënt is 6, de deler 7 en de rest 2. Wat is het deeltal?", "44",
          "Quotiënt × deler + rest = deeltal: 6 × 7 + 2 = 44.",
          6 * 7 + 2),
    mk("Het product is 36 en één factor is 4. Wat is de andere factor?", ["9", "32", "40"],
       "4 × ? = 36. Reken terug met delen: 36 : 4 = 9.",
       F(36, 4)),
    mk("De som is 50 en één term is 18. Wat is de andere term?", ["32", "68", "42"],
       "18 + ? = 50. Reken terug met aftrekken: 50 − 18 = 32.",
       50 - 18),
    mk("Het aftrektal is 40 en het verschil is 15. Wat is de aftrekker?", ["25", "55", "15"],
       "40 − ? = 15. Dan is de aftrekker 40 − 15 = 25. Controle: 40 − 25 = 15.",
       40 - 15),
    won("Een deling gaat op als de rest 0 is.", True,
        "Waar. Er blijft niets over, zoals bij 20 : 5 = 4.",
        True),
    mk("Welke deling gaat op?", ["42 : 6", "43 : 6", "44 : 6"],
       "42 staat in de tafel van 6 (7 × 6 = 42), dus daar blijft niets over.",
       enige(["42 : 6", "43 : 6", "44 : 6"], lambda s: int(s.split(":")[0]) % 6 == 0)),
    mk("Hoe lees je 3/8?", ["Drie achtste", "Acht derde", "Drie en acht"],
       "Eerst de teller, dan de noemer met -de of -ste erachter: drie achtste.",
       WOORD),
    won("Bij een deling mag je deeltal en deler van plaats wisselen.", False,
        "Niet waar. 12 : 3 = 4, maar 3 : 12 = 0,25. Bij optellen en vermenigvuldigen mag het wel.",
        F(12, 3) == F(3, 12)),
    mk("Welk woord hoort bij 'maal'?", ["Product", "Som", "Verschil"],
       "Maal is vermenigvuldigen, en de uitkomst daarvan heet het product.",
       WOORD),
    mk("Je verdeelt 50 knikkers over zakjes van 8. Hoeveel zakjes worden vol, en hoeveel knikkers blijven over?",
       ["6 zakjes, 2 over", "6 zakjes, 8 over", "7 zakjes, 2 over"],
       "6 × 8 = 48, dus 6 volle zakjes. 50 − 48 = 2 knikkers over. 50 : 8 = 6 rest 2.",
       f"{50 // 8} zakjes, {50 % 8} over"),
]
