"""Pittige hoofdstukken bij Engels 🌱 Start.

Engels is een taalvak: invulantwoorden worden streng vergeleken
(zie lib/taalvak.ts). Elk invulantwoord is daarom één woord dat maar op
één manier geschreven kan worden.
"""

NIVEAU = "start"
VAK = "Engels"
BESTAND = "start-engels-pittig.json"

WOORDEN = [
    {
        "type": "meerkeuze",
        "vraag": "Wat betekent “It is raining cats and dogs”?",
        "opties": [
            "het giet",
            "er lopen veel dieren op straat buiten",
            "het is prachtig weer om te wandelen",
            "de dieren moeten binnen blijven vandaag",
        ],
        "antwoord": 0,
        "uitleg": "Een uitdrukking vertaal je nooit woord voor woord. Deze betekent gewoon: het regent heel hard.",
    },
    {
        "type": "invultekst",
        "vraag": "Wat is het meervoud van child? Antwoord met één Engels woord.",
        "antwoord": "children",
        "uitleg": "Child is onregelmatig: geen childs maar children. Zo ook man/men, woman/women, foot/feet, tooth/teeth.",
    },
    {
        "type": "waarofniet",
        "vraag": "Het Engelse woord actually betekent eigenlijk, niet actueel.",
        "antwoord": True,
        "uitleg": "Klopt. Actually is een valse vriend: het lijkt op actueel maar betekent eigenlijk. Actueel is current.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Welk woord betekent niet hetzelfde als de andere drie?",
        "opties": [
            "tired",
            "exhausted",
            "sleepy",
            "worn out",
        ],
        "antwoord": 3,
        "uitleg": "Tired, exhausted en sleepy gaan alle drie over moe zijn van jezelf. Worn out kan dat ook, maar wordt vooral gezegd van versleten spullen.",
    },
    {
        "type": "invultekst",
        "vraag": "Vul in: my brother’s daughter is my ... Antwoord met één Engels woord.",
        "antwoord": "niece",
        "uitleg": "De dochter van je broer is je nicht: niece. De zoon van je broer is je nephew.",
    },
    {
        "type": "waarofniet",
        "vraag": "In het Engels schrijf je de namen van de dagen en de maanden met een hoofdletter.",
        "antwoord": True,
        "uitleg": "Klopt: Monday, Tuesday, January, July. In het Nederlands net niet, daar blijft maandag klein.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Wat betekent “to borrow”?",
        "opties": [
            "lenen van iemand",
            "iets uitlenen aan iemand anders",
            "iets voorgoed weggeven zonder iets terug",
            "iets kopen in een gewone winkel",
        ],
        "antwoord": 0,
        "uitleg": "To borrow is lenen van iemand, to lend is uitlenen aan iemand. Can I borrow your pen? Yes, I will lend it to you.",
    },
    {
        "type": "invultekst",
        "vraag": "Wat is het tegenovergestelde van expensive? Antwoord met één Engels woord.",
        "antwoord": "cheap",
        "uitleg": "Expensive is duur, cheap is goedkoop. Een ander woord is inexpensive, maar cheap is het gewone woord.",
    },
    {
        "type": "waarofniet",
        "vraag": "Het Engelse woord eventually betekent eventueel.",
        "antwoord": False,
        "uitleg": "Niet waar, dat is nog een valse vriend. Eventually betekent uiteindelijk. Eventueel is possibly.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Je hebt honger en je zegt: “I could eat a horse.” Wat bedoel je?",
        "opties": [
            "je hebt enorme honger",
            "je vindt paardenvlees erg lekker",
            "je bent een goede ruiter geworden",
            "je wil graag naar een boerderij gaan",
        ],
        "antwoord": 0,
        "uitleg": "Alweer een uitdrukking. Je zegt dat je zo veel honger hebt dat je een paard zou opeten.",
    },
    {
        "type": "invultekst",
        "vraag": "Vul in: the opposite of always is ... Antwoord met één Engels woord.",
        "antwoord": "never",
        "uitleg": "Always is altijd, never is nooit. Daartussen: sometimes, often, usually.",
    },
    {
        "type": "waarofniet",
        "vraag": "Fifty en fifteen zijn twee manieren om hetzelfde getal te zeggen.",
        "antwoord": False,
        "uitleg": "Niet waar: fifteen is 15 en fifty is 50. Je hoort het verschil aan de klemtoon: fifTEEN achteraan, FIFty vooraan.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Welk woord hoort bij het weer?",
        "opties": [
            "cloudy",
            "cloudless mountains far away",
            "clover in the green field",
            "clothes hanging on a line",
        ],
        "antwoord": 0,
        "uitleg": "Cloudy is bewolkt, van cloud: wolk. De andere drie lijken erop maar gaan over iets anders.",
    },
    {
        "type": "invultekst",
        "vraag": "Wat is het meervoud van mouse (het dier)? Antwoord met één Engels woord.",
        "antwoord": "mice",
        "uitleg": "Onregelmatig: one mouse, two mice. Voor de muis van een computer zegt men tegenwoordig ook mouses.",
    },
    {
        "type": "waarofniet",
        "vraag": "Voor 21 zeg je in het Engels one and twenty, net als eenentwintig in het Nederlands.",
        "antwoord": False,
        "uitleg": "Niet waar, het Engels draait het niet om: twenty-one. Wel bijzonder: voor 1200 mag je twelve hundred zeggen.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Wat is een winkel waar je brood koopt?",
        "opties": [
            "a bakery",
            "a butcher with meat and sausages",
            "a library full of books to read",
            "a grocery for fruit and vegetables",
        ],
        "antwoord": 0,
        "uitleg": "A bakery is een bakkerij. Let op library: dat is een bibliotheek, geen boekenwinkel.",
    },
    {
        "type": "invultekst",
        "vraag": "Vul in: a baby cat is a ... Antwoord met één Engels woord.",
        "antwoord": "kitten",
        "uitleg": "Een jonge kat is a kitten, een jonge hond a puppy, een jong paard a foal.",
    },
    {
        "type": "waarofniet",
        "vraag": "Het woord homework krijgt in het Engels nooit een s.",
        "antwoord": True,
        "uitleg": "Klopt. Homework is ontelbaar, net als information, advice en furniture. Je zegt a lot of homework, geen homeworks.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Wat betekent “once in a blue moon”?",
        "opties": [
            "heel zelden",
            "elke maand op dezelfde dag opnieuw",
            "wanneer het volle maan is buiten",
            "altijd wanneer het donker wordt",
        ],
        "antwoord": 0,
        "uitleg": "Een blue moon is een zeldzame tweede volle maan in één maand. De uitdrukking betekent dus: bijna nooit.",
    },
    {
        "type": "invultekst",
        "vraag": "Wat is het tegenovergestelde van to remember? Antwoord met één Engels woord.",
        "antwoord": "forget",
        "uitleg": "To remember is onthouden of zich herinneren, to forget is vergeten. Verleden tijd: forgot.",
    },
]

VOORSTELLEN = [
    {
        "type": "meerkeuze",
        "vraag": "Iemand vraagt “How do you do?”. Wat antwoord je?",
        "opties": [
            "How do you do?",
            "I am doing my homework right now",
            "I do it every day after school",
            "Yes, I do that quite often actually",
        ],
        "antwoord": 0,
        "uitleg": "How do you do is geen echte vraag maar een heel formele begroeting. Je herhaalt ze gewoon.",
    },
    {
        "type": "invultekst",
        "vraag": "Vul in: I ... from Belgium. Antwoord met één Engels woord.",
        "antwoord": "am",
        "uitleg": "Bij I hoort am: I am from Belgium. Bij he, she, it hoort is, bij you, we en they hoort are.",
    },
    {
        "type": "waarofniet",
        "vraag": "Je schrijft het woord I in het Engels altijd met een hoofdletter, ook midden in een zin.",
        "antwoord": True,
        "uitleg": "Klopt, altijd: yesterday I went home. Alleen bij I is dat zo, niet bij you of he.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Hoe vraag je beleefd naar iemands leeftijd?",
        "opties": [
            "How old are you?",
            "How many years do you have?",
            "What is your number of years?",
            "How much old are you now?",
        ],
        "antwoord": 0,
        "uitleg": "In het Engels bén je een leeftijd, je hébt ze niet: I am eleven. “How many years do you have” is vertaald Nederlands.",
    },
    {
        "type": "invultekst",
        "vraag": "Vul in: this is my sister. ... name is Emma. Antwoord met één Engels woord.",
        "antwoord": "her",
        "uitleg": "Bij een meisje of vrouw hoort her, bij een jongen of man his. Het gaat om wie iets bezit, niet om het ding zelf.",
    },
    {
        "type": "waarofniet",
        "vraag": "In het Engels zeg je I have twelve years om te zeggen dat je twaalf bent.",
        "antwoord": False,
        "uitleg": "Niet waar. Je zegt I am twelve, of voluit I am twelve years old.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Welke vraag past bij het antwoord “I live in Hasselt”?",
        "opties": [
            "Where do you live?",
            "How do you live over there?",
            "When are you living in that city?",
            "Why do you live in a town?",
        ],
        "antwoord": 0,
        "uitleg": "Where vraagt naar een plaats. How vraagt hoe, when wanneer, why waarom.",
    },
    {
        "type": "invultekst",
        "vraag": "Vul in: my father and my mother are my ... Antwoord met één Engels woord.",
        "antwoord": "parents",
        "uitleg": "Parents zijn de ouders. Let op: parents zijn niet de familieleden in het algemeen, dat is relatives.",
    },
    {
        "type": "waarofniet",
        "vraag": "Nice to meet you zeg je de eerste keer dat je iemand ontmoet.",
        "antwoord": True,
        "uitleg": "Klopt. Zie je die persoon later terug, dan zeg je nice to see you again.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Wat betekent “What do you do?” aan een volwassene gevraagd?",
        "opties": [
            "wat is je beroep",
            "wat ben je op dit moment aan het doen",
            "wat ga je later nog allemaal doen",
            "wat doe je het liefst in je vrije tijd",
        ],
        "antwoord": 0,
        "uitleg": "What do you do vraagt naar je werk. Wil je weten wat iemand nu doet, dan vraag je what are you doing.",
    },
    {
        "type": "invultekst",
        "vraag": "Vul in: I have got two brothers, but I ... got any sisters. Antwoord met twee Engelse woorden.",
        "antwoord": "have not",
        "uitleg": "In een ontkennende zin komt not achter have: I have not got. Verkort is dat haven’t got.",
    },
    {
        "type": "waarofniet",
        "vraag": "Je voornaam heet in het Engels je surname.",
        "antwoord": False,
        "uitleg": "Niet waar, surname is je achternaam, net als last name. Je voornaam is je first name of given name.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Hoe stel je je zus voor aan een vriend?",
        "opties": [
            "This is my sister.",
            "Here you have my sister there.",
            "That one over there is a sister.",
            "She is being my sister right now.",
        ],
        "antwoord": 0,
        "uitleg": "Iemand voorstellen doe je met this is. Bij iets verder weg zeg je that is.",
    },
    {
        "type": "invultekst",
        "vraag": "Vul in: ... old is your brother? Antwoord met één Engels woord.",
        "antwoord": "how",
        "uitleg": "How old vraagt naar de leeftijd. How past voor veel woorden: how tall, how many, how often.",
    },
    {
        "type": "waarofniet",
        "vraag": "Je mag in een formele brief beginnen met Dear Mr Smith.",
        "antwoord": True,
        "uitleg": "Klopt, dat is de gewone formele aanhef. Ken je de naam niet, dan schrijf je Dear Sir or Madam.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Iemand zegt “I am an only child”. Wat betekent dat?",
        "opties": [
            "hij heeft geen broers of zussen",
            "hij is het enige kind in de hele klas",
            "hij is nog maar een heel klein kind",
            "hij is het jongste kind van het gezin",
        ],
        "antwoord": 0,
        "uitleg": "An only child is een enig kind. Het jongste kind is the youngest.",
    },
    {
        "type": "invultekst",
        "vraag": "Vul in: my hobby is football. I ... playing football. Antwoord met één Engels woord.",
        "antwoord": "like",
        "uitleg": "Na like komt een werkwoord met -ing of met to: I like playing, I like to play. Allebei is juist.",
    },
    {
        "type": "waarofniet",
        "vraag": "Bye is formeler dan goodbye.",
        "antwoord": False,
        "uitleg": "Niet waar, het is net andersom. Bye en see you zijn losjes, goodbye is netter.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Welke zin over je beste vriendin is juist?",
        "opties": [
            "She is my best friend.",
            "She is my more best friend.",
            "She is my most good friend.",
            "She is my gooder friend there.",
        ],
        "antwoord": 0,
        "uitleg": "Good wordt onregelmatig vergeleken: good, better, best. Dus nooit gooder of most good.",
    },
    {
        "type": "invultekst",
        "vraag": "Vul in: nice to ... you. Zeg je bij een eerste ontmoeting. Antwoord met één Engels woord.",
        "antwoord": "meet",
        "uitleg": "To meet is ontmoeten. Nice to meet you bij de eerste keer, nice to see you als je elkaar al kent.",
    },
]

TOBE = [
    {
        "type": "invultekst",
        "vraag": "Vul in: they ... not at home yesterday. Antwoord met één Engels woord.",
        "antwoord": "were",
        "uitleg": "Yesterday is verleden tijd. Bij they hoort were, bij I, he, she en it hoort was.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Welke zin met has got is juist?",
        "opties": [
            "She has got a new bike.",
            "She have got a new bike today.",
            "She has get a new bike already.",
            "She have a got new bike now.",
        ],
        "antwoord": 0,
        "uitleg": "Bij she, he en it wordt have altijd has. Daarachter blijft got gewoon staan.",
    },
    {
        "type": "waarofniet",
        "vraag": "De verkorte vorm van I am not is I amn’t.",
        "antwoord": False,
        "uitleg": "Niet waar, die bestaat niet. Je schrijft I’m not. Bij he is it he isn’t, bij they are it they aren’t.",
    },
    {
        "type": "invultekst",
        "vraag": "Vul in: there ... three apples on the table. Antwoord met één Engels woord.",
        "antwoord": "are",
        "uitleg": "Three apples is meervoud, dus there are. Bij één ding is het there is.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Hoe maak je een vraag van “He was at school”?",
        "opties": [
            "Was he at school?",
            "Did he was at school?",
            "Does he was at school?",
            "He was at school?",
        ],
        "antwoord": 0,
        "uitleg": "Bij to be zet je het werkwoord vooraan. Je hebt geen do of did nodig; dat is net het verschil met andere werkwoorden.",
    },
    {
        "type": "waarofniet",
        "vraag": "In het Engels zeg je I have hungry.",
        "antwoord": False,
        "uitleg": "Niet waar, dat is I am hungry. In het Engels bén je honger, dorst, koud en bang, met to be.",
    },
    {
        "type": "invultekst",
        "vraag": "Vul in: we ... got a dog and two cats. Antwoord met één Engels woord.",
        "antwoord": "have",
        "uitleg": "Bij we, you, they en I hoort have. Alleen bij he, she en it wordt het has.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Welke zin betekent dat de man oud is?",
        "opties": [
            "He is old.",
            "He has old age here.",
            "He was being old then.",
            "He is having old years.",
        ],
        "antwoord": 0,
        "uitleg": "Een eigenschap zeg je met is plus het bijvoeglijk naamwoord. De andere drie zijn geen Engels.",
    },
    {
        "type": "waarofniet",
        "vraag": "Was is de verleden tijd van is.",
        "antwoord": True,
        "uitleg": "Klopt: he is wordt he was. In het meervoud wordt are dan were.",
    },
    {
        "type": "invultekst",
        "vraag": "Vul in: my sister ... got long hair. Antwoord met één Engels woord.",
        "antwoord": "has",
        "uitleg": "My sister is she, en bij she hoort has. Vergeet die s niet.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Welke zin is een goede ontkenning van “We were late”?",
        "opties": [
            "We were not late.",
            "We did not were late.",
            "We not were late then.",
            "We were no late at all.",
        ],
        "antwoord": 0,
        "uitleg": "Bij to be komt not er gewoon achter: were not, verkort weren’t. Ook hier geen did.",
    },
    {
        "type": "waarofniet",
        "vraag": "There is gebruik je ook als er meer dan één ding is.",
        "antwoord": False,
        "uitleg": "Niet waar, dan wordt het there are. There is hoort bij één ding. Let op: there betekent hier niet daar.",
    },
    {
        "type": "invultekst",
        "vraag": "Vul in: I ... born in Belgium. Antwoord met één Engels woord.",
        "antwoord": "was",
        "uitleg": "Geboren worden staat in het Engels in de verleden tijd van to be: I was born. Nooit I am born.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Wat betekent “I have had enough”?",
        "opties": [
            "ik heb er genoeg van",
            "ik heb nog niet genoeg gehad",
            "ik heb er nooit genoeg van gehad",
            "ik zal er genoeg van krijgen",
        ],
        "antwoord": 0,
        "uitleg": "Have had is de voltooide tijd van have. Twee keer een vorm van have naast elkaar is normaal in het Engels.",
    },
    {
        "type": "waarofniet",
        "vraag": "Het Engels gebruikt bij to be geen do of does in een vraag.",
        "antwoord": True,
        "uitleg": "Klopt: Are you ready, niet Do you are ready. To be is daarin een uitzondering op de andere werkwoorden.",
    },
    {
        "type": "invultekst",
        "vraag": "Vul in: how many brothers ... you got? Antwoord met één Engels woord.",
        "antwoord": "have",
        "uitleg": "Bij you hoort have: have you got. Bij he zou het has he got zijn.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Welke zin met been klopt niet?",
        "opties": [
            "It have been a long day.",
            "It has been a long day.",
            "They have been here before.",
            "She has been to London.",
        ],
        "antwoord": 0,
        "uitleg": "Bij it hoort has, niet have. De drie andere zinnen zijn wel juist.",
    },
    {
        "type": "waarofniet",
        "vraag": "In “there are a lot of people” staat are juist, want people is meervoud.",
        "antwoord": True,
        "uitleg": "Klopt. People is het meervoud van person en krijgt altijd are, nooit is.",
    },
    {
        "type": "invultekst",
        "vraag": "Vul in: yesterday the shops ... closed. Antwoord met één Engels woord.",
        "antwoord": "were",
        "uitleg": "The shops is meervoud en yesterday is verleden tijd: were.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Welke verkorting hoort bij she is?",
        "opties": [
            "she’s",
            "she’re",
            "shes",
            "she’is",
        ],
        "antwoord": 0,
        "uitleg": "Het weggelaten stukje wordt een apostrof: she is wordt she’s. Let op: she’s kan ook she has betekenen.",
    },
]

TEGENWOORDIGE = [
    {
        "type": "invultekst",
        "vraag": "Vul in: he ... to school every day. Antwoord met één Engels woord.",
        "antwoord": "goes",
        "uitleg": "Bij he, she en it komt er een s bij. Na een o wordt dat es: go wordt goes.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Welke zin met does not is juist?",
        "opties": [
            "She does not like fish.",
            "She do not likes fish today.",
            "She does not likes fish at all.",
            "She not does like fish either.",
        ],
        "antwoord": 0,
        "uitleg": "Staat er does, dan zit de s daar al in. Het werkwoord blijft dus kaal: does not like.",
    },
    {
        "type": "waarofniet",
        "vraag": "Na does verdwijnt de s van het werkwoord.",
        "antwoord": True,
        "uitleg": "Klopt. He plays wordt does he play, en niet does he plays. Eén s per zin is genoeg.",
    },
    {
        "type": "invultekst",
        "vraag": "Vul in: she ... her homework right now. Antwoord met twee Engelse woorden.",
        "antwoord": "is doing",
        "uitleg": "Right now betekent op dit moment, dus is plus -ing. Voor iets dat elke dag gebeurt zou je she does zeggen.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Wanneer gebruik je I am reading in plaats van I read?",
        "opties": [
            "als je op dit moment aan het lezen bent",
            "als je elke avond een half uur leest",
            "als je gisteren gelezen hebt",
            "als je morgen gaat lezen",
        ],
        "antwoord": 0,
        "uitleg": "De vorm met -ing gaat over nu, op dit moment. I read gaat over een gewoonte.",
    },
    {
        "type": "waarofniet",
        "vraag": "Bij I, you, we en they komt er in de tegenwoordige tijd ook een s aan het werkwoord.",
        "antwoord": False,
        "uitleg": "Niet waar, die s is er alleen bij he, she en it: I play, you play, but he plays.",
    },
    {
        "type": "invultekst",
        "vraag": "Vul in: my brother ... television every evening. Antwoord met twee Engelse woorden.",
        "antwoord": "watches television",
        "uitleg": "Na ch, sh, s, x of o komt er es bij: watch wordt watches. En televison blijft staan zoals het is.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Welke vraag is juist?",
        "opties": [
            "Where does he live?",
            "Where does he lives?",
            "Where do he live there?",
            "Where he does live now?",
        ],
        "antwoord": 0,
        "uitleg": "Bij he hoort does, en daarna blijft het werkwoord kaal. Het vraagwoord staat helemaal vooraan.",
    },
    {
        "type": "waarofniet",
        "vraag": "Werkwoorden die eindigen op een medeklinker plus y krijgen ies: study wordt studies.",
        "antwoord": True,
        "uitleg": "Klopt: study wordt studies, fly wordt flies. Staat er een klinker voor de y, dan blijft het gewoon een s: play wordt plays.",
    },
    {
        "type": "invultekst",
        "vraag": "Vul in: we usually ... at seven o’clock. Antwoord met twee Engelse woorden.",
        "antwoord": "get up",
        "uitleg": "To get up is opstaan. Bij we komt er geen s bij, dus get up blijft zoals het is.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Wat betekent “She is always losing her keys”?",
        "opties": [
            "ze verliest haar sleutels aan één stuk door",
            "ze verliest haar sleutels nu meteen",
            "ze is haar sleutels ooit één keer verloren",
            "ze gaat haar sleutels verliezen",
        ],
        "antwoord": 0,
        "uitleg": "Always plus -ing zegt dat iets keer op keer gebeurt, meestal met een zucht erbij.",
    },
    {
        "type": "waarofniet",
        "vraag": "Je kan zeggen I am knowing the answer.",
        "antwoord": False,
        "uitleg": "Niet waar. Werkwoorden als know, like, want en understand gaan niet in de -ing-vorm. Je zegt I know the answer.",
    },
    {
        "type": "invultekst",
        "vraag": "Vul in: ... your sister play the piano? Antwoord met één Engels woord.",
        "antwoord": "does",
        "uitleg": "Your sister is she, dus does. Bij your parents zou het do zijn.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Welk woord past niet bij de tegenwoordige tijd van een gewoonte?",
        "opties": [
            "right now",
            "every day",
            "usually",
            "on Mondays",
        ],
        "antwoord": 0,
        "uitleg": "Right now wijst op dit moment, en dan gebruik je de vorm met -ing. De drie andere horen bij een gewoonte.",
    },
    {
        "type": "waarofniet",
        "vraag": "In een gewone mededeling hoort er altijd een do of does bij: I do play football.",
        "antwoord": False,
        "uitleg": "Niet waar, gewoon I play football. Do en does horen in vragen en ontkenningen thuis, of als je iets extra wil benadrukken.",
    },
    {
        "type": "invultekst",
        "vraag": "Vul in: look, it ... outside! Antwoord met twee Engelse woorden.",
        "antwoord": "is raining",
        "uitleg": "Het gebeurt op dit moment, dus is plus -ing. Bij rain verdubbelt er niets.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Welke ontkenning bij my friends klopt?",
        "opties": [
            "My friends do not play tennis.",
            "My friends does not play tennis.",
            "My friends do not plays tennis.",
            "My friends not do play tennis.",
        ],
        "antwoord": 0,
        "uitleg": "My friends is meervoud, dus do. En na do blijft het werkwoord kaal.",
    },
    {
        "type": "waarofniet",
        "vraag": "Bij een werkwoord dat eindigt op een korte klinker plus één medeklinker verdubbelt die medeklinker voor -ing: sit wordt sitting.",
        "antwoord": True,
        "uitleg": "Klopt: sit wordt sitting, run wordt running, swim wordt swimming. Zo blijft de klinker kort klinken.",
    },
    {
        "type": "invultekst",
        "vraag": "Wat is de -ing-vorm van to make? Antwoord met één Engels woord.",
        "antwoord": "making",
        "uitleg": "Eindigt een werkwoord op een stille e, dan valt die weg: make wordt making, write wordt writing.",
    },
    {
        "type": "meerkeuze",
        "vraag": "“I live in Genk” en “I am living in Genk”. Wat is het verschil?",
        "opties": [
            "de tweede klinkt tijdelijk",
            "de eerste gaat over vroeger",
            "de tweede gaat over de toekomst",
            "er is geen enkel verschil",
        ],
        "antwoord": 0,
        "uitleg": "I live is gewoon waar je woont. I am living klinkt alsof het maar voor even is, bijvoorbeeld tijdens een verbouwing.",
    },
]

ZINNEN = [
    {
        "type": "meerkeuze",
        "vraag": "Welke woordvolgorde is juist?",
        "opties": [
            "I often go to the cinema.",
            "I go often to the cinema.",
            "Often I to the cinema go.",
            "I go to the cinema often very.",
        ],
        "antwoord": 0,
        "uitleg": "Woorden als often, always en never staan voor het werkwoord. Bij to be staan ze er net achter: I am often tired.",
    },
    {
        "type": "invultekst",
        "vraag": "Vul in: there isn’t ... milk left. Antwoord met één Engels woord.",
        "antwoord": "any",
        "uitleg": "In een ontkennende zin gebruik je any, in een gewone mededeling some: there is some milk left.",
    },
    {
        "type": "waarofniet",
        "vraag": "In het meervoud krijgt een Engels bijvoeglijk naamwoord een s: two reds cars.",
        "antwoord": False,
        "uitleg": "Niet waar, het blijft altijd hetzelfde: two red cars. Alleen het zelfstandig naamwoord krijgt de s.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Welke vraag met many of much is juist?",
        "opties": [
            "How many books do you have?",
            "How much books do you have?",
            "How many book do you have?",
            "How much of books have you?",
        ],
        "antwoord": 0,
        "uitleg": "Kan je het tellen, dan many plus meervoud. Kan je het niet tellen (water, time, money), dan much.",
    },
    {
        "type": "invultekst",
        "vraag": "Vul in: this book is ... than that one. Antwoord met twee Engelse woorden.",
        "antwoord": "more interesting",
        "uitleg": "Bij een lang bijvoeglijk naamwoord zet je more ervoor in plaats van -er: more interesting, niet interestinger.",
    },
    {
        "type": "waarofniet",
        "vraag": "Een dubbele ontkenning zoals I don’t know nothing is goed Engels.",
        "antwoord": False,
        "uitleg": "Niet waar. In verzorgd Engels ontken je maar één keer: I don’t know anything, of I know nothing.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Waar zet je het woord yesterday meestal?",
        "opties": [
            "aan het einde van de zin",
            "tussen het onderwerp en het werkwoord",
            "altijd na het lijdend voorwerp maar voor het werkwoord",
            "altijd tussen het werkwoord en het lijdend voorwerp",
        ],
        "antwoord": 0,
        "uitleg": "Tijdsbepalingen staan meestal achteraan: I saw him yesterday. Vooraan mag ook, met een komma: Yesterday, I saw him.",
    },
    {
        "type": "invultekst",
        "vraag": "Vul in: the book ... I read was great. Antwoord met één Engels woord.",
        "antwoord": "that",
        "uitleg": "Bij dingen gebruik je that of which, bij mensen who. Which kan ook, maar that is het gewoonste.",
    },
    {
        "type": "waarofniet",
        "vraag": "Tussen het werkwoord en het lijdend voorwerp mag je gerust iets zetten: I like very much this book.",
        "antwoord": False,
        "uitleg": "Niet waar. Het lijdend voorwerp komt meteen na het werkwoord: I like this book very much.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Welke zin over iets geven klopt?",
        "opties": [
            "She gave me a book.",
            "She gave to me a book.",
            "She gave a book me.",
            "She me gave a book then.",
        ],
        "antwoord": 0,
        "uitleg": "Eerst aan wie, dan wat: she gave me a book. Wil je het omdraaien, dan komt er to bij: she gave a book to me.",
    },
    {
        "type": "invultekst",
        "vraag": "Vul in: if it rains tomorrow, we ... stay home. Antwoord met twee Engelse woorden.",
        "antwoord": "will stay",
        "uitleg": "Na if staat de tegenwoordige tijd, ook al gaat het over morgen. In het andere deel van de zin komt will.",
    },
    {
        "type": "waarofniet",
        "vraag": "Na if gebruik je in het Engels nooit will.",
        "antwoord": True,
        "uitleg": "Klopt, in dit soort zinnen niet: if it rains, en niet if it will rain. De will hoort in het andere deel thuis.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Welke zin is een goede vraag?",
        "opties": [
            "What time did you arrive?",
            "What time you arrived?",
            "What time did you arrived?",
            "What time you did arrive?",
        ],
        "antwoord": 0,
        "uitleg": "Did staat voor het onderwerp en het werkwoord blijft kaal: did you arrive, niet did you arrived.",
    },
    {
        "type": "invultekst",
        "vraag": "Wat is de vergrotende trap van good? Antwoord met één Engels woord.",
        "antwoord": "better",
        "uitleg": "Good, better, best is onregelmatig, net als bad, worse, worst. Nooit gooder of more good.",
    },
    {
        "type": "waarofniet",
        "vraag": "Een Engelse zin moet altijd een onderwerp hebben, ook als het over het weer gaat.",
        "antwoord": True,
        "uitleg": "Klopt. Je zegt it is raining, met it als onderwerp, terwijl het Nederlands gewoon het regent zegt.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Welke zin met tall klopt niet?",
        "opties": [
            "He is more tall than me.",
            "He is taller than me.",
            "He is the tallest in his class.",
            "He is as tall as his brother.",
        ],
        "antwoord": 0,
        "uitleg": "Tall is een kort woord en krijgt -er: taller. More gebruik je bij langere woorden zoals more difficult.",
    },
    {
        "type": "invultekst",
        "vraag": "Vul in: I would like ... cup of tea. Antwoord met één Engels woord.",
        "antwoord": "a",
        "uitleg": "Cup begint met een medeklinkerklank, dus a cup. An gebruik je voor een klinkerklank: an apple, an hour.",
    },
    {
        "type": "waarofniet",
        "vraag": "Je schrijft an hour, ook al begint hour met een h.",
        "antwoord": True,
        "uitleg": "Klopt. De h van hour hoor je niet, dus je hoort een klinker: an hour. Het gaat om de klank, niet om de letter.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Welke zin heeft de juiste volgorde?",
        "opties": [
            "I bought a nice old wooden table.",
            "I bought a wooden old nice table.",
            "I bought an old wooden nice table.",
            "I bought a wooden nice old table.",
        ],
        "antwoord": 0,
        "uitleg": "Engelse bijvoeglijke naamwoorden hebben een vaste volgorde: eerst je mening (nice), dan leeftijd (old), dan materiaal (wooden).",
    },
    {
        "type": "invultekst",
        "vraag": "Vul in: there are ... apples in the bowl. Antwoord met één Engels woord.",
        "antwoord": "some",
        "uitleg": "In een gewone mededeling gebruik je some. In een vraag of een ontkenning wordt het any.",
    },
]

SCHOOL = [
    {
        "type": "invultekst",
        "vraag": "Vul in: the lesson starts ... nine o’clock. Antwoord met één Engels woord.",
        "antwoord": "at",
        "uitleg": "Bij een uur hoort at, bij een dag on en bij een maand of jaar in: at nine, on Monday, in May.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Welk woord hoort niet op school thuis?",
        "opties": [
            "a platform",
            "a blackboard",
            "a classroom",
            "a timetable",
        ],
        "antwoord": 0,
        "uitleg": "A platform is een perron in een station. De drie andere hoor je elke dag op school.",
    },
    {
        "type": "waarofniet",
        "vraag": "Een timetable is een lessenrooster.",
        "antwoord": True,
        "uitleg": "Klopt, en ook een dienstregeling van de trein. Het is letterlijk een tabel met tijden.",
    },
    {
        "type": "invultekst",
        "vraag": "Vul in: I go to school ... bike. Antwoord met één Engels woord.",
        "antwoord": "by",
        "uitleg": "Bij een vervoermiddel hoort by: by bike, by bus, by car. Te voet is de uitzondering: on foot.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Wat betekent “to hand in your homework”?",
        "opties": [
            "je huiswerk afgeven",
            "je huiswerk met de hand schrijven",
            "je huiswerk aan iemand uitlenen",
            "je huiswerk opnieuw beginnen",
        ],
        "antwoord": 0,
        "uitleg": "To hand in is binnenbrengen of afgeven. Let op: hand out betekent net uitdelen.",
    },
    {
        "type": "waarofniet",
        "vraag": "Je zegt in het Engels on Monday, niet at Monday.",
        "antwoord": True,
        "uitleg": "Klopt: bij dagen en data hoort on. At is voor een uur en in voor een maand of jaar.",
    },
    {
        "type": "invultekst",
        "vraag": "Hoe noem je de grote pauze op school in het Engels? Antwoord met één Engels woord.",
        "antwoord": "break",
        "uitleg": "The break is de pauze. In Amerika hoor je ook recess, maar break is het gewone woord.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Welke zin vraagt beleefd om hulp?",
        "opties": [
            "Could you help me, please?",
            "Help me now right away.",
            "You must help me with this.",
            "I want that you help me here.",
        ],
        "antwoord": 0,
        "uitleg": "Could you plus please is de beleefde vorm. Must en want klinken als een bevel.",
    },
    {
        "type": "waarofniet",
        "vraag": "A library is een boekenwinkel.",
        "antwoord": False,
        "uitleg": "Niet waar, dat is een bibliotheek. Een boekenwinkel is a bookshop of a bookstore. Een klassieke valse vriend.",
    },
    {
        "type": "invultekst",
        "vraag": "Vul in: the bus stops ... front of the school. Antwoord met één Engels woord.",
        "antwoord": "in",
        "uitleg": "In front of betekent voor of vooraan. De tegenhanger is behind: achter.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Wat betekent “to miss the bus”?",
        "opties": [
            "de bus niet halen",
            "de bus missen zoals je een vriend mist",
            "de verkeerde bus nemen",
            "op de bus wachten",
        ],
        "antwoord": 0,
        "uitleg": "To miss betekent allebei: iets niet halen én iemand missen. Hier is het de bus die je voor je neus zag wegrijden.",
    },
    {
        "type": "waarofniet",
        "vraag": "A crossroads is een zebrapad.",
        "antwoord": False,
        "uitleg": "Niet waar, a crossroads is een kruispunt. Een zebrapad is a zebra crossing.",
    },
    {
        "type": "invultekst",
        "vraag": "Vul in: turn ... at the traffic lights. Antwoord met één Engels woord.",
        "antwoord": "left",
        "uitleg": "Left is links, right is rechts, en rechtdoor is straight on.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Welk vak is science?",
        "opties": [
            "wetenschappen",
            "aardrijkskunde",
            "geschiedenis",
            "lichamelijke opvoeding",
        ],
        "antwoord": 0,
        "uitleg": "Science is wetenschappen. Aardrijkskunde is geography, geschiedenis history en turnen PE.",
    },
    {
        "type": "waarofniet",
        "vraag": "De dagen van de week schrijf je in het Engels met een kleine letter, net als in het Nederlands.",
        "antwoord": False,
        "uitleg": "Niet waar, in het Engels krijgen ze een hoofdletter: I have gym on Tuesday, niet tuesday.",
    },
    {
        "type": "invultekst",
        "vraag": "Hoe noem je het bord waarop de leerkracht schrijft? Antwoord met één Engels woord.",
        "antwoord": "blackboard",
        "uitleg": "The blackboard, of tegenwoordig vaker the whiteboard. Het bord aan de muur met mededelingen is a noticeboard.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Wat zeg je als je te laat binnenkomt?",
        "opties": [
            "Sorry I am late.",
            "Sorry I am too late now.",
            "Sorry for my late arriving.",
            "Sorry that I come too late.",
        ],
        "antwoord": 0,
        "uitleg": "In het Engels zeg je gewoon late. Too late betekent dat het al voorbij is en er niets meer aan te doen valt.",
    },
    {
        "type": "waarofniet",
        "vraag": "A pupil en a student betekenen allebei een leerling.",
        "antwoord": True,
        "uitleg": "Klopt, allebei mag. Pupil hoor je vaker voor de lagere school, student vanaf het secundair.",
    },
    {
        "type": "invultekst",
        "vraag": "Vul in: I always walk ... school in the morning. Antwoord met één Engels woord.",
        "antwoord": "to",
        "uitleg": "To wijst de richting aan: walk to school, go to bed. Zonder to zou de zin niet af zijn.",
    },
    {
        "type": "meerkeuze",
        "vraag": "Wat is a rubber in Brits Engels?",
        "opties": [
            "een gom",
            "een liniaal om mee te meten",
            "een map voor je bladen",
            "een schrift met lijntjes",
        ],
        "antwoord": 0,
        "uitleg": "In Groot-Brittannië is a rubber een gom; in Amerika zegt men an eraser. Een liniaal is a ruler.",
    },
]

HOOFDSTUKKEN = [
    ("Woorden voor elke dag", WOORDEN),
    ("Mezelf voorstellen", VOORSTELLEN),
    ("To be en to have", TOBE),
    ("De tegenwoordige tijd", TEGENWOORDIGE),
    ("Zinnen bouwen", ZINNEN),
    ("Op school en onderweg", SCHOOL),
]
