# -*- coding: utf-8 -*-
"""Het heelal: ontstaan, afstanden en observatie.

Uit de vakfiche aardrijkskunde van de 3de graad dubbele finaliteit (2027):
oriëntatie met aardas, poolster en zenit, de observatietechnieken, de sferen
van het systeem aarde, het ontstaan en de evolutie van het heelal, en de
afstandsmaten.

Deel 1 is het ontstaan en de opbouw van het heelal, met de afstandsmaten.
Deel 2 is oriënteren en observeren: aardas, poolster, zenit, telescopen,
satellieten en de gps.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Hoe noemt men de theorie over het ontstaan van het heelal?",
         opties=["de oerknal",
                 "de theorie van de zwaartekracht",
                 "de theorie van de platentektoniek",
                 "de theorie van het uitdijende zonnestelsel"],
         antwoord=0,
         uitleg="De oerknal of Big Bang, ongeveer 13,8 miljard jaar geleden. Sindsdien dijt het heelal uit."),
    dict(type="meerkeuze",
         vraag="Wat betekent een uitdijend heelal?",
         opties=["de sterrenstelsels gaan uit elkaar",
                 "de sterrenstelsels komen naar elkaar toe",
                 "het heelal blijft precies even groot",
                 "het heelal draait rond één middelpunt"],
         antwoord=0,
         uitleg="De afstanden tussen de sterrenstelsels worden groter. Daardoor zien we hun licht naar het rood verschuiven."),
    dict(type="invultekst",
         vraag="Hoeveel miljard jaar oud is het heelal ongeveer? Vul het getal in.",
         antwoord=["13,8", "13.8", "14"],
         uitleg="Ongeveer 13,8 miljard jaar. De aarde is veel jonger: 4,6 miljard jaar."),
    dict(type="meerkeuze",
         vraag="Welke afstandsmaten noemt de fiche voor het heelal?",
         opties=["het lichtjaar",
                 "de astronomische eenheid",
                 "de kilometer",
                 "de zeemijl"],
         antwoord=[0, 1, 2],
         uitleg="Lichtjaar en astronomische eenheid, en de kilometer voor het dichtste werk. Een zeemijl gebruikt men op zee."),
    dict(type="waarofniet",
         vraag="Een lichtjaar is een maat van afstand, niet van tijd.",
         antwoord=True,
         uitleg="Het is de afstand die licht in één jaar aflegt: ongeveer 9.500 miljard kilometer."),
    dict(type="meerkeuze",
         vraag="Wat is één astronomische eenheid?",
         opties=["de afstand aarde-zon",
                 "de afstand aarde-maan",
                 "de afstand zon-Jupiter",
                 "de omtrek van de baan van de aarde"],
         antwoord=0,
         uitleg="Eén AE is ongeveer 150 miljoen kilometer. Je gebruikt ze voor afstanden binnen het zonnestelsel."),
    dict(type="meerkeuze",
         vraag="Welke volgorde gaat van klein naar groot?",
         opties=["planetenstelsel, galaxie, cluster, supercluster",
                 "cluster, supercluster, galaxie, planetenstelsel",
                 "galaxie, planetenstelsel, supercluster, cluster",
                 "supercluster, cluster, planetenstelsel, galaxie"],
         antwoord=0,
         uitleg="Een planetenstelsel zit in een sterrenstelsel, sterrenstelsels vormen een cluster, clusters een supercluster."),
    dict(type="invultekst",
         vraag="Hoe noem je ons eigen sterrenstelsel? Eén woord.",
         antwoord=["Melkweg", "melkweg", "Melkwegstelsel"],
         uitleg="De Melkweg. Ons zonnestelsel ligt daarin in de Orionarm."),
    dict(type="meerkeuze",
         vraag="Waar ligt ons zonnestelsel volgens de fiche?",
         opties=["in de Orionarm",
                 "in de kern van de Melkweg",
                 "aan de rand van de Lokale Groep",
                 "buiten elk sterrenstelsel"],
         antwoord=0,
         uitleg="In de Orionarm van het Melkwegstelsel, dat deel is van de Lokale Groep en die van de Lokale Supercluster."),
    dict(type="waarofniet",
         vraag="De Melkweg is het enige sterrenstelsel in het heelal.",
         antwoord=False,
         uitleg="Er zijn honderden miljarden sterrenstelsels. De dichtste grote buur is de Andromedanevel."),
    dict(type="meerkeuze",
         vraag="Hoe is het zonnestelsel ontstaan?",
         opties=["uit een wolk gas en stof",
                 "uit een stuk van een andere planeet",
                 "uit het licht van de eerste sterren",
                 "uit een inslag van een grote komeet"],
         antwoord=0,
         uitleg="Een wolk gas en stof trok samen onder haar eigen zwaartekracht. In het midden ontstond de zon, in de schijf eromheen de planeten."),
    dict(type="meerkeuze",
         vraag="Welke delen van het heelal noemt de fiche bij naam?",
         opties=["galaxie",
                 "cluster",
                 "supercluster",
                 "atmosfeer"],
         antwoord=[0, 1, 2],
         uitleg="Planetenstelsels, galaxieën of sterrenstelsels, clusters en superclusters. De atmosfeer hoort bij een planeet."),
    dict(type="invultekst",
         vraag="Hoe noem je de sfeer van het systeem aarde die uit lucht bestaat? Eén woord.",
         antwoord=["atmosfeer"],
         uitleg="De atmosfeer. De andere drie zijn de geosfeer, de hydrosfeer en de biosfeer."),
    dict(type="meerkeuze",
         vraag="Wat is het verschil tussen een ster en een planeet?",
         opties=["een ster maakt zelf licht",
                 "een planeet maakt zelf licht",
                 "een ster draait om een planeet",
                 "een ster is kleiner dan een planeet"],
         antwoord=0,
         uitleg="In een ster smelt waterstof samen, en dat geeft licht. Een planeet weerkaatst enkel licht."),
    dict(type="waarofniet",
         vraag="Een maan draait rond een planeet en niet rechtstreeks rond de zon.",
         antwoord=True,
         uitleg="Onze maan draait rond de aarde, en samen draaien ze rond de zon. Jupiter heeft tientallen manen."),
    dict(type="meerkeuze",
         vraag="Waarom zie je de sterren van een ver sterrenstelsel zoals ze lang geleden waren?",
         opties=["hun licht is er jaren over gedaan",
                 "ze bewegen trager dan onze zon",
                 "ze zijn intussen niet veranderd",
                 "de atmosfeer vertraagt hun licht"],
         antwoord=0,
         uitleg="Licht van een stelsel op twee miljoen lichtjaar is twee miljoen jaar oud. Verder kijken is dus verder terugkijken in de tijd."),
    dict(type="meerkeuze",
         vraag="Hoe is de aarde na haar ontstaan in lagen geraakt?",
         opties=["het zwaarste zonk naar het midden",
                 "het lichtste zonk naar het midden",
                 "de lagen ontstonden door inslagen",
                 "de lagen ontstonden door de rotatie"],
         antwoord=0,
         uitleg="IJzer en nikkel zonken naar de kern, lichter materiaal bleef boven. Uit het ontgaste materiaal ontstond de eerste atmosfeer."),
    dict(type="waarofniet",
         vraag="De eerste atmosfeer van de aarde had dezelfde samenstelling als de lucht van nu.",
         antwoord=False,
         uitleg="Ze bestond uit waterdamp, koolstofdioxide en stikstof, zonder zuurstof. Die zuurstof kwam veel later, van de eerste fotosynthese."),
    dict(type="meerkeuze",
         vraag="Hoeveel kilometer legt licht in één seconde af?",
         opties=["300.000",
                 "3.000",
                 "30 miljoen",
                 "150 miljoen"],
         antwoord=0,
         uitleg="Bijna 300.000 kilometer per seconde. Van de zon naar de aarde doet licht er zo acht minuten over."),
    dict(type="meerkeuze",
         vraag="Welke maten zijn een afstand?",
         opties=["het lichtjaar",
                 "de kilometer",
                 "de astronomische eenheid",
                 "de kilometer per uur"],
         antwoord=[0, 1, 2],
         uitleg="Neptunus staat op dertig astronomische eenheden, en voor een ander sterrenstelsel neem je lichtjaren. Kilometer per uur is een snelheid."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is de aardas?",
         opties=["de lijn waarrond de aarde draait",
                 "de baan van de aarde rond de zon",
                 "de lijn van de evenaar",
                 "de grens tussen dag en nacht"],
         antwoord=0,
         uitleg="De aardas loopt van de Noordpool naar de Zuidpool. Ze staat scheef op het eclipticavlak, onder 23 graden 27."),
    dict(type="meerkeuze",
         vraag="Waarom lijkt de poolster stil te staan?",
         opties=["ze staat bijna in het verlengde van de aardas",
                 "ze staat veel dichter bij ons dan andere sterren",
                 "ze draait even snel mee als de aarde zelf",
                 "ze is veel helderder dan alle andere sterren"],
         antwoord=0,
         uitleg="De andere sterren lijken rond haar te draaien. Daarom wijst ze het noorden aan op het noordelijk halfrond."),
    dict(type="invultekst",
         vraag="Hoe noem je het punt recht boven je hoofd? Eén woord.",
         antwoord=["zenit"],
         uitleg="Het zenit. Staat de zon in je zenit, dan valt ze loodrecht in en is er geen schaduw."),
    dict(type="meerkeuze",
         vraag="Welke observatietechnieken noemt de fiche?",
         opties=["de satelliet",
                 "de optische telescoop",
                 "de radiotelescoop",
                 "de seismograaf"],
         antwoord=[0, 1, 2],
         uitleg="Satelliet, optische telescoop en radiotelescoop. Een seismograaf meet aardbevingen, niet de ruimte."),
    dict(type="waarofniet",
         vraag="Een radiotelescoop werkt ook bij bewolkt weer en bij daglicht.",
         antwoord=True,
         uitleg="Radiogolven gaan door de wolken. Een optische telescoop heeft een heldere, donkere nacht nodig."),
    dict(type="meerkeuze",
         vraag="Waarom staan grote telescopen vaak hoog in de bergen?",
         opties=["er is minder lucht en minder licht",
                 "er waait meer wind om de lens te koelen",
                 "ze staan daar dichter bij de sterren",
                 "de zwaartekracht is daar iets kleiner"],
         antwoord=0,
         uitleg="Minder atmosfeer en geen lichtvervuiling geven een scherper beeld. Een droge lucht helpt ook, en daarom staan ze vaak in woestijnen."),
    dict(type="meerkeuze",
         vraag="Waarvoor gebruik je een satelliet boven de aarde?",
         opties=["om het weer te volgen",
                 "om bosbranden op te sporen",
                 "om signalen door te sturen",
                 "om aardbevingen te voorspellen"],
         antwoord=[0, 1, 2],
         uitleg="De fiche noemt weersvoorspelling, communicatie en de opvolging van bosbranden. Aardbevingen voorspellen kan niemand."),
    dict(type="invultekst",
         vraag="Hoe noem je het systeem van satellieten waarmee je je plaats op aarde bepaalt? Drie letters.",
         antwoord=["gps", "GPS"],
         uitleg="Gps, van global positioning system. Het Europese stelsel heet Galileo."),
    dict(type="meerkeuze",
         vraag="Hoe weet een gps-toestel waar het staat?",
         opties=["uit de tijd die signalen onderweg zijn",
                 "uit de hoek waaronder het de zon ziet",
                 "uit het magneetveld van de aarde",
                 "uit het zendmast waarmee het verbinding heeft"],
         antwoord=0,
         uitleg="Het toestel meet hoe lang de signalen van verschillende satellieten onderweg waren, en rekent daaruit zijn afstand tot elk van hen."),
    dict(type="waarofniet",
         vraag="Eén satelliet volstaat om je plaats op aarde te bepalen.",
         antwoord=False,
         uitleg="Je hebt er minstens drie nodig, en vier als je ook de hoogte wil. Elke satelliet geeft maar één afstand."),
    dict(type="meerkeuze",
         vraag="Wat is poollicht?",
         opties=["licht van deeltjes uit de zon",
                 "licht van de maan op het ijs",
                 "licht van sterren boven de pool",
                 "licht van de zon op poolnacht"],
         antwoord=0,
         uitleg="Deeltjes van de zon botsen op de hoge atmosfeer bij de polen. De fiche noemt het als gevolg van de zonneactiviteit."),
    dict(type="meerkeuze",
         vraag="Wat is de zonnecyclus?",
         opties=["de schommeling van de zonneactiviteit",
                 "de baan van de zon door de Melkweg",
                 "de dagelijkse gang van de zon",
                 "de levensloop van de zon als ster"],
         antwoord=0,
         uitleg="De zonneactiviteit zwelt aan en neemt af in ongeveer elf jaar. Bij veel activiteit zie je meer zonnevlekken en meer poollicht."),
    dict(type="invultekst",
         vraag="Hoe noem je de donkere plekken op de zon? Eén woord.",
         antwoord=["zonnevlekken", "zonnevlek"],
         uitleg="Zonnevlekken. Ze zijn koeler dan de rest van het oppervlak en volgen de zonnecyclus."),
    dict(type="meerkeuze",
         vraag="Welke sferen raken elkaar aan een rivieroever?",
         opties=["de hydrosfeer",
                 "de geosfeer",
                 "de biosfeer",
                 "de Kuipergordel"],
         antwoord=[0, 1, 2],
         uitleg="Water, bodem en leven komen er samen, en de lucht erboven hoort er ook bij. De Kuipergordel ligt voorbij Neptunus."),
    dict(type="waarofniet",
         vraag="De atmosfeer beschermt de aarde tegen kleine meteoroïden, want die verbranden erin.",
         antwoord=True,
         uitleg="Door de wrijving met de lucht gloeien ze op: dat zie je als een vallende ster. Zonder atmosfeer zou elk steentje insloegen."),
    dict(type="meerkeuze",
         vraag="Waarom gebruikt men in de ruimte een telescoop zoals Hubble?",
         opties=["hij staat boven de atmosfeer",
                 "hij staat dichter bij de sterren",
                 "hij kan sneller bewegen",
                 "hij kost minder dan een grote spiegel"],
         antwoord=0,
         uitleg="Zonder atmosfeer trilt het beeld niet en gaat er geen straling verloren. Daarom ziet een ruimtetelescoop scherper."),
    dict(type="meerkeuze",
         vraag="Welke richting wijst de aardas op het noordelijk halfrond aan?",
         opties=["het noorden",
                 "het oosten",
                 "het zuiden",
                 "het westen"],
         antwoord=0,
         uitleg="Het verlengde van de aardas wijst naar de poolster, en die staat in het noorden. Op het zuidelijk halfrond zie je haar niet."),
    dict(type="waarofniet",
         vraag="De zon staat in Hasselt een paar keer per jaar in het zenit.",
         antwoord=False,
         uitleg="Dat kan alleen tussen de keerkringen. In België komt de zon nooit hoger dan ongeveer drieënzestig graden boven de horizon."),
    dict(type="meerkeuze",
         vraag="Waarvoor is een optische telescoop beter dan een radiotelescoop?",
         opties=["om planeten te bekijken",
                 "om door wolken te kijken",
                 "om bij dag te werken",
                 "om radiogolven te meten"],
         antwoord=0,
         uitleg="Een optische telescoop vangt zichtbaar licht, en daar zie je oppervlakken mee. Een radiotelescoop vangt radiogolven uit verre stelsels."),
    dict(type="meerkeuze",
         vraag="Wat zie je met een optische telescoop niet?",
         opties=["radiogolven",
                 "de ringen van Saturnus",
                 "de kraters van de maan",
                 "de manen van Jupiter"],
         antwoord=0,
         uitleg="Radiogolven zijn onzichtbaar licht, en daarvoor dient een radiotelescoop. De andere drie zie je met een gewone telescoop."),
]
