# -*- coding: utf-8 -*-
"""Vulkanen en aardbevingen.

Uit de vakfiche aardrijkskunde van de 3de graad dubbele finaliteit (2027): de
gevolgen van de platentektoniek, de delen van een vulkaan, het vergelijken van
strato- en schildvulkanen, de begrippen caldera, magma en lava, lapilli,
vulkanische bommen en as, de Ring of Fire, het hypocentrum en het epicentrum,
de schaal van Richter en de momentmagnitudeschaal, en de gevolgen zoals
tsunami's en lahars.

Deel 1 zijn de vulkanen.
Deel 2 zijn de aardbevingen en hun gevolgen.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is het verschil tussen magma en lava?",
         opties=["lava is magma aan de oppervlakte",
                 "magma is lava aan de oppervlakte",
                 "magma is koud en lava is warm",
                 "lava bevat meer gas dan magma"],
         antwoord=0,
         uitleg="Zolang het gesmolten gesteente in de aarde zit, heet het magma. Buiten noemt men het lava."),
    dict(type="meerkeuze",
         vraag="Wat is een caldera?",
         opties=["een ingestorte vulkaankrater",
                 "een gang waarlangs magma stijgt",
                 "een laag as rond een vulkaan",
                 "een stroom modder langs een helling"],
         antwoord=0,
         uitleg="Na een zware uitbarsting loopt de magmakamer leeg en zakt de top in. Zo ontstond de baai van Santorini."),
    dict(type="invultekst",
         vraag="Hoe noem je de gang waarlangs magma naar boven komt? Eén woord.",
         antwoord=["schoorsteen", "pijp", "vulkaanpijp"],
         uitleg="De schoorsteen of vulkaanpijp. Onderaan zit de magmakamer, bovenaan de krater."),
    dict(type="meerkeuze",
         vraag="Welke stoffen komen er bij een uitbarsting vrij?",
         opties=["lava",
                 "vulkanische as",
                 "gassen",
                 "water uit de zee"],
         antwoord=[0, 1, 2],
         uitleg="De fiche noemt ook lapilli en vulkanische bommen. Zeewater komt er niet uit, al kan een vulkaan onder water liggen."),
    dict(type="waarofniet",
         vraag="Lapilli zijn de grootste brokken die een vulkaan wegslingert.",
         antwoord=False,
         uitleg="Lapilli zijn juist de kleine steentjes, van twee tot vierenzestig millimeter. De grootste brokken heten vulkanische bommen."),
    dict(type="meerkeuze",
         vraag="Wat kenmerkt een schildvulkaan?",
         opties=["flauwe hellingen en vloeibare lava",
                 "steile hellingen en dikke lava",
                 "een krater zonder lava",
                 "een uitbarsting met veel as"],
         antwoord=0,
         uitleg="Dunne lava loopt ver uit en bouwt een breed, laag schild. Mauna Loa op Hawaï is er het grootste voorbeeld van."),
    dict(type="meerkeuze",
         vraag="Wat kenmerkt een stratovulkaan?",
         opties=["lagen van as en lava om elkaar",
                 "één dikke laag vloeibare lava",
                 "een brede, lage koepel",
                 "een krater onder de zeespiegel"],
         antwoord=0,
         uitleg="Stratum betekent laag. Dikke lava verstopt de schoorsteen, en dan volgt een explosieve uitbarsting met veel as."),
    dict(type="invultekst",
         vraag="Hoe noem je de kring van vulkanen rond de Stille Oceaan? Drie woorden in het Engels.",
         antwoord=["Ring of Fire", "ring of fire"],
         uitleg="De Ring of Fire. Daar duikt de Pacifische plaat rondom onder de omliggende platen."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over een stratovulkaan zijn juist?",
         opties=["hij is steil",
                 "hij barst explosief uit",
                 "hij staat vaak bij een subductiezone",
                 "hij geeft enkel vloeibare lava"],
         antwoord=[0, 1, 2],
         uitleg="De Vesuvius en de Fuji zijn stratovulkanen. Vloeibare lava hoort juist bij een schildvulkaan."),
    dict(type="waarofniet",
         vraag="Een vulkaan kan ook midden op een plaat liggen, ver van elke plaatgrens.",
         antwoord=True,
         uitleg="Dat gebeurt boven een hotspot, zoals op Hawaï en IJsland. De mantelpluim smelt de plaat van onderaf door."),
    dict(type="meerkeuze",
         vraag="Waarom is vulkanische as gevaarlijk voor vliegtuigen?",
         opties=["ze smelt in de motoren",
                 "ze maakt de vleugels zwaarder",
                 "ze verstoort de radio",
                 "ze doet de ruiten bevriezen"],
         antwoord=0,
         uitleg="As is fijn gemalen glas en steen. In een hete motor smelt ze en zet ze zich vast, en dan valt de motor stil."),
    dict(type="meerkeuze",
         vraag="Waar ligt de magmakamer van een vulkaan?",
         opties=["onder de vulkaan",
                 "in de krater",
                 "in de aswolk",
                 "op de helling"],
         antwoord=0,
         uitleg="De magmakamer is een voorraad gesmolten gesteente in de korst. Van daar stijgt het magma door de schoorsteen naar de krater."),
    dict(type="invultekst",
         vraag="Hoe noem je de brokken gesteente, groter dan vierenzestig millimeter, die een vulkaan wegslingert? Twee woorden.",
         antwoord=["vulkanische bommen", "bommen"],
         uitleg="Vulkanische bommen. Ze kunnen honderden meter ver vliegen en wegen soms tonnen."),
    dict(type="meerkeuze",
         vraag="Waarom is een uitbarsting met veel gas explosiever?",
         opties=["het gas kan niet weg door dikke lava",
                 "het gas maakt de lava vloeibaarder",
                 "het gas koelt de lava af",
                 "het gas maakt de krater breder"],
         antwoord=0,
         uitleg="In dikke, stroperige lava blijft het gas opgesloten tot de druk de top wegblaast. In dunne lava ontsnapt het rustig."),
    dict(type="waarofniet",
         vraag="Een vulkaan die duizend jaar niet uitbrak, is zeker gedoofd.",
         antwoord=False,
         uitleg="Men noemt zo'n vulkaan sluimerend, niet gedoofd. De Vesuvius zweeg eeuwen en begroef in het jaar 79 toch Pompeï."),
    dict(type="meerkeuze",
         vraag="Welke vulkaan ligt in Italië, bij Napels?",
         opties=["de Vesuvius",
                 "de Etna",
                 "de Fuji",
                 "de Krakatau"],
         antwoord=0,
         uitleg="De Vesuvius bij Napels. De Etna ligt op Sicilië, de Fuji in Japan en de Krakatau in Indonesië."),
    dict(type="meerkeuze",
         vraag="Wat is een lahar?",
         opties=["een modderstroom van as en water",
                 "een stroom gloeiende lava op een helling",
                 "een wolk van hete gassen en as",
                 "een golf in de oceaan na een beving"],
         antwoord=0,
         uitleg="As en smeltwater of regen vormen samen een stroom die zich als beton gedraagt. Lahars hebben al hele dorpen bedolven."),
    dict(type="waarofniet",
         vraag="Een grote uitbarsting kan het klimaat van de hele aarde een paar jaar afkoelen.",
         antwoord=True,
         uitleg="De aërosolen in de stratosfeer weerkaatsen zonlicht. Na de Pinatubo in 1991 lag de gemiddelde temperatuur een half graadje lager."),
    dict(type="meerkeuze",
         vraag="Waarom wonen er toch mensen op de hellingen van een vulkaan?",
         opties=["de bodem is er heel vruchtbaar",
                 "er is er nooit gevaar",
                 "het is er altijd koeler",
                 "de grond is er goedkoper dan elders"],
         antwoord=0,
         uitleg="Vulkanische as levert mineralen en maakt de grond rijk. Rond de Etna en op Java wonen daardoor miljoenen mensen."),
    dict(type="meerkeuze",
         vraag="Welke delen horen bij een vulkaan?",
         opties=["de krater",
                 "de schoorsteen",
                 "de magmakamer",
                 "het epicentrum"],
         antwoord=[0, 1, 2],
         uitleg="Het epicentrum hoort bij een aardbeving: het is het punt aan de oppervlakte boven de haard."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is het hypocentrum van een aardbeving?",
         opties=["het punt in de diepte waar ze begint",
                 "het punt aan de oppervlakte erboven",
                 "de plaats met de meeste schade",
                 "de plaats waar de eerste golf aankomt"],
         antwoord=0,
         uitleg="Het hypocentrum of de haard zit in de diepte. Het punt recht erboven, aan de oppervlakte, heet het epicentrum."),
    dict(type="meerkeuze",
         vraag="Waar is de schade bij een aardbeving meestal het grootst?",
         opties=["rond het epicentrum",
                 "op honderd kilometer afstand",
                 "aan de rand van de plaat",
                 "op de dichtste bergtop"],
         antwoord=0,
         uitleg="Daar is de weg naar de oppervlakte het kortst. Een beving dicht onder de grond doet meer schade dan een diepe."),
    dict(type="invultekst",
         vraag="Hoe noem je het punt aan de oppervlakte recht boven de haard? Eén woord.",
         antwoord=["epicentrum"],
         uitleg="Het epicentrum. Epi betekent op of boven, en het hypocentrum ligt eronder."),
    dict(type="meerkeuze",
         vraag="Welke schalen gebruikt men voor de sterkte van een aardbeving?",
         opties=["de schaal van Richter",
                 "de momentmagnitudeschaal",
                 "de schaal van Mercalli",
                 "de schaal van Beaufort"],
         antwoord=[0, 1, 2],
         uitleg="De fiche noemt Richter en de momentmagnitudeschaal. Mercalli meet de ondervonden schade, en Beaufort is voor wind."),
    dict(type="waarofniet",
         vraag="Een beving van 7 op de schaal van Richter is tien keer sterker dan een van 6.",
         antwoord=True,
         uitleg="De schaal is logaritmisch: elke eenheid is tien keer meer uitslag. In energie is het zelfs ongeveer tweeëndertig keer meer."),
    dict(type="meerkeuze",
         vraag="Waarmee meet men de golven van een aardbeving?",
         opties=["met een seismograaf",
                 "met een barometer",
                 "met een thermometer",
                 "met een anemometer"],
         antwoord=0,
         uitleg="Een seismograaf tekent het seismogram. Een barometer meet druk, een anemometer wind."),
    dict(type="meerkeuze",
         vraag="Waarom gaan bij een beving zwakke huizen het eerst stuk?",
         opties=["ze kunnen niet meebewegen",
                 "ze zijn te zwaar gebouwd",
                 "ze staan te dicht bij elkaar",
                 "ze hebben geen kelder"],
         antwoord=0,
         uitleg="Metselwerk zonder wapening scheurt bij de eerste schok. Daarom staat er in Japan staal en flexibel beton."),
    dict(type="invultekst",
         vraag="Hoe noem je de grafiek die een seismograaf tekent? Eén woord.",
         antwoord=["seismogram"],
         uitleg="Het seismogram. Uit het verschil in aankomsttijd van de golven leid je de afstand tot de haard af."),
    dict(type="meerkeuze",
         vraag="Hoe ontstaat een tsunami?",
         opties=["de zeebodem schokt plots omhoog",
                 "de wind duwt het water op",
                 "de maan trekt het water weg",
                 "een schip veroorzaakt een golf"],
         antwoord=0,
         uitleg="Een beving of een onderzeese aardverschuiving tilt de hele waterkolom op. Op volle zee is de golf laag, bij de kust groeit ze snel."),
    dict(type="waarofniet",
         vraag="Een tsunami is een heel hoge golf, al midden op de oceaan.",
         antwoord=False,
         uitleg="Midden op zee is ze soms maar een halve meter hoog, maar honderden kilometer lang. Pas in ondiep water loopt ze op tot tientallen meter."),
    dict(type="meerkeuze",
         vraag="Wat is een voorteken van een tsunami aan de kust?",
         opties=["de zee trekt plots terug",
                 "de zee wordt plots warm",
                 "de wind valt helemaal weg",
                 "de lucht wordt plots donker"],
         antwoord=0,
         uitleg="Soms komt de dalende kant van de golf eerst. Wie dan naar de blootgelegde bodem gaat kijken, staat precies verkeerd."),
    dict(type="meerkeuze",
         vraag="Waar komen de meeste aardbevingen voor?",
         opties=["aan de plaatgrenzen",
                 "midden in de continenten",
                 "op de polen",
                 "onder de ijskappen"],
         antwoord=0,
         uitleg="Daar schuiven de platen langs, over of naar elkaar toe. De Ring of Fire tekent zich op een bevingenkaart meteen af."),
    dict(type="invultekst",
         vraag="Hoe noem je de modderstroom van as en water na een uitbarsting? Eén woord.",
         antwoord=["lahar"],
         uitleg="Een lahar, een Indonesisch woord. Hij kan tientallen kilometer ver stromen, ook jaren na een uitbarsting."),
    dict(type="meerkeuze",
         vraag="Welke gevolgen kan een aardbeving hebben?",
         opties=["instortende gebouwen",
                 "een tsunami",
                 "aardverschuivingen",
                 "een uitdijend heelal"],
         antwoord=[0, 1, 2],
         uitleg="De fiche noemt ook de lahars bij een uitbarsting. Het uitdijende heelal heeft er niets met te maken."),
    dict(type="waarofniet",
         vraag="In België komen helemaal geen aardbevingen voor.",
         antwoord=False,
         uitleg="Rond Luik en in de Roerdalslenk beweegt de korst, en in 1983 was er bij Luik een beving van 4,9. Zware bevingen zijn hier wel uitzonderlijk."),
    dict(type="meerkeuze",
         vraag="Waarom kan men aardbevingen niet voorspellen op dag en uur?",
         opties=["de spanning breekt onvoorspelbaar",
                 "de toestellen zijn niet nauwkeurig",
                 "de haard ligt te diep om te meten",
                 "er zijn te weinig meetstations"],
         antwoord=0,
         uitleg="Men weet wel waar het risico hoog is en hoe vaak er gemiddeld een beving komt. Het precieze moment waarop het gesteente breekt, blijft onvoorspelbaar."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over de schaal van Richter zijn juist?",
         opties=["een 2 voel je niet",
                 "elke eenheid is tien keer meer",
                 "schade begint rond een 5",
                 "de schaal stopt bij een 10"],
         antwoord=[0, 1, 2],
         uitleg="De schaal heeft geen bovengrens: de zwaarste gemeten beving haalde 9,5. Onder de drie voel je een beving zelden."),
    dict(type="waarofniet",
         vraag="Een naschok komt na de hoofdschok en is meestal zwakker.",
         antwoord=True,
         uitleg="Het gesteente rond de breuk zoekt daarna een nieuw evenwicht. Naschokken kunnen weken duren en zijn gevaarlijk voor beschadigde gebouwen."),
    dict(type="meerkeuze",
         vraag="Welke plaatgrens geeft de zwaarste bevingen?",
         opties=["een subductiezone",
                 "een oceanische rug",
                 "een hotspot",
                 "een continentaal plat"],
         antwoord=0,
         uitleg="Daar wringt een hele plaat onder een andere, en dat laat de grootste breuken los. De beving van Sumatra in 2004 haalde 9,1."),
    dict(type="meerkeuze",
         vraag="Waarom staan er in Japan huizen op rubberen blokken?",
         opties=["ze bewegen dan mee met de bodem",
                 "ze staan dan hoger boven het water",
                 "ze worden dan beter geïsoleerd",
                 "ze zijn dan goedkoper te bouwen"],
         antwoord=0,
         uitleg="Zo'n demping laat het gebouw zacht meeschommelen in plaats van te scheuren. Het heet seismische isolatie."),
]
