# -*- coding: utf-8 -*-
"""Neerslag en de waterkringloop.

Uit de vakfiche aardrijkskunde van de 3de graad dubbele finaliteit (2027): de
hydrologische cyclus, hoe condensatie tot wolken en neerslag leidt, het
verband tussen luchtvochtigheid en neerslag (relatieve en absolute vochtigheid,
dauwpunt), de factoren die de neerslagverdeling op aarde bepalen (druk,
zeestromen, ligging ten opzichte van de zee, reliëf met stijgingsregens en
regenschaduw, de ITCZ met convectieregens, fronten met frontale regens) en het
lezen van een kaart met isohyeten.

Deel 1 is de waterkringloop, de vochtigheid en het ontstaan van een wolk.
Deel 2 zijn de soorten regen en de neerslagverdeling op aarde.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is de hydrologische cyclus?",
         opties=["de kringloop van het water",
                 "de omloop van de aarde om de zon",
                 "de kringloop van de koolstof",
                 "de beweging van de zeestromen"],
         antwoord=0,
         uitleg="Verdamping, condensatie, neerslag en afvoer, en dan opnieuw. Er komt geen water bij en er gaat er geen verloren."),
    dict(type="meerkeuze",
         vraag="Wat gebeurt er bij condensatie?",
         opties=["waterdamp wordt vloeibaar",
                 "water wordt waterdamp",
                 "water wordt ijs",
                 "ijs wordt waterdamp"],
         antwoord=0,
         uitleg="Condensatie is de omgekeerde beweging van verdamping. Het gebeurt als vochtige lucht afkoelt tot haar dauwpunt."),
    dict(type="invultekst",
         vraag="Hoe noem je de temperatuur waarbij lucht met haar vocht verzadigd raakt? Eén woord.",
         antwoord=["dauwpunt"],
         uitleg="Het dauwpunt. Koelt de lucht daaronder af, dan slaat het vocht neer als dauw, mist of wolken."),
    dict(type="meerkeuze",
         vraag="Welke stappen horen bij de hydrologische cyclus?",
         opties=["verdamping",
                 "condensatie",
                 "neerslag",
                 "verwering"],
         antwoord=[0, 1, 2],
         uitleg="Verdamping, condensatie, neerslag, infiltratie en afstroming. Verwering is het stukmaken van gesteente, en dat hoort bij de geosfeer."),
    dict(type="waarofniet",
         vraag="Warme lucht kan meer waterdamp bevatten dan koude lucht.",
         antwoord=True,
         uitleg="Daarom is het in de tropen benauwd en krijg je bij afkoeling meteen condensatie. Op een koude ruit zie je hetzelfde gebeuren."),
    dict(type="meerkeuze",
         vraag="Wat is de relatieve luchtvochtigheid?",
         opties=["hoeveel vocht er zit tegenover het maximum",
                 "hoeveel gram water er in een kubieke meter zit",
                 "hoeveel regen er in een jaar valt",
                 "hoeveel water er uit de zee verdampt"],
         antwoord=0,
         uitleg="Honderd procent betekent verzadigd. De absolute vochtigheid is wel het aantal gram water per kubieke meter lucht."),
    dict(type="meerkeuze",
         vraag="Waarom ontstaat er een wolk als lucht opstijgt?",
         opties=["de lucht koelt af en het vocht condenseert",
                 "de lucht warmt op en neemt meer vocht op",
                 "de lucht droogt uit op grote hoogte",
                 "de lucht wordt samengeperst door de druk"],
         antwoord=0,
         uitleg="Hoger is de druk lager, de lucht zet uit en koelt daardoor af. Onder het dauwpunt slaat het vocht neer op kleine deeltjes."),
    dict(type="invultekst",
         vraag="Hoe noem je het water dat uit de grond verdampt via de bladeren van planten? Eén woord.",
         antwoord=["transpiratie", "verdamping"],
         uitleg="Transpiratie. Samen met de verdamping uit water en bodem noemt men dat evapotranspiratie."),
    dict(type="meerkeuze",
         vraag="Welke vormen van neerslag bestaan er?",
         opties=["regen",
                 "sneeuw",
                 "hagel",
                 "mist"],
         antwoord=[0, 1, 2],
         uitleg="Regen, sneeuw, hagel en ijzel vallen naar beneden, en dat is neerslag. Mist is een wolk aan de grond en valt niet."),
    dict(type="waarofniet",
         vraag="Een wolk bestaat uit waterdamp.",
         antwoord=False,
         uitleg="Waterdamp is onzichtbaar. Een wolk bestaat uit piepkleine druppeltjes of ijskristallen, en juist daarom zie je ze."),
    dict(type="meerkeuze",
         vraag="Waarop condenseert waterdamp in de lucht?",
         opties=["op kleine deeltjes stof of zout",
                 "op de wind die eroverheen waait",
                 "op de ozonlaag hoog in de lucht",
                 "op niets, het gebeurt uit zichzelf"],
         antwoord=0,
         uitleg="Die deeltjes heten condensatiekernen. Zonder zo'n kern moet lucht veel verder afkoelen voor er een druppel ontstaat."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over het water op aarde zijn juist?",
         opties=["bijna al het water is zout",
                 "zoet water is maar drie procent",
                 "het meeste zoete water zit in ijs",
                 "het water op aarde neemt elk jaar toe"],
         antwoord=[0, 1, 2],
         uitleg="Ruim zevenennegentig procent is zeewater, en van het zoete water zit het grootste deel in ijskappen en gletsjers. De totale hoeveelheid blijft gelijk."),
    dict(type="invultekst",
         vraag="Hoe noem je het insijpelen van regenwater in de bodem? Eén woord.",
         antwoord=["infiltratie"],
         uitleg="Infiltratie. Op verharde grond kan het water niet infiltreren, en dan stroomt het meteen af."),
    dict(type="meerkeuze",
         vraag="Wat gebeurt er met regenwater op een verharde oprit?",
         opties=["het stroomt af naar de riool",
                 "het sijpelt in de bodem",
                 "het verdampt meteen volledig",
                 "het blijft er altijd op staan"],
         antwoord=0,
         uitleg="Verharding haalt de infiltratie weg. Daardoor komt het water in één keer in de riool en de beek, met wateroverlast als gevolg."),
    dict(type="waarofniet",
         vraag="Mist is hetzelfde verschijnsel als een wolk, maar aan de grond.",
         antwoord=True,
         uitleg="Allebei bestaan ze uit zwevende druppeltjes. Bij ons ontstaat mist vaak in een heldere nacht, als de grond afkoelt tot onder het dauwpunt."),
    dict(type="meerkeuze",
         vraag="Waarom is de lucht boven een woestijn droog?",
         opties=["de lucht daalt er en warmt op",
                 "de lucht stijgt er en koelt af",
                 "er waait te veel wind",
                 "de bodem is er te warm voor wolken"],
         antwoord=0,
         uitleg="Dalende lucht warmt op, en warme lucht kan meer vocht bevatten. De relatieve vochtigheid zakt, en dan vormt zich geen wolk."),
    dict(type="meerkeuze",
         vraag="Waarin meet men de neerslag?",
         opties=["in millimeter",
                 "in graden",
                 "in hectopascal",
                 "in Beaufort"],
         antwoord=0,
         uitleg="Eén millimeter neerslag is één liter per vierkante meter. Graden horen bij de temperatuur, hectopascal bij de druk."),
    dict(type="waarofniet",
         vraag="Bij ons valt de meeste regen in de zomer, omdat het dan warmer is.",
         antwoord=False,
         uitleg="Bij ons valt het hele jaar neerslag, met in de herfst en de winter de meeste. Zomerbuien zijn wel heviger, maar korter."),
    dict(type="meerkeuze",
         vraag="Wat is ijzel?",
         opties=["regen die op koude grond bevriest",
                 "sneeuw die smelt en weer bevriest",
                 "hagel die uit een onweerswolk valt",
                 "mist die aan de takken blijft hangen"],
         antwoord=0,
         uitleg="De druppel is vloeibaar tot ze de grond raakt, en dan vormt ze een glasheldere laag. Daardoor is ijzel veel gevaarlijker dan sneeuw."),
    dict(type="meerkeuze",
         vraag="Waarom hagelt het vooral bij een zwaar onweer?",
         opties=["de wolk is heel hoog en koud",
                 "de wolk hangt heel laag",
                 "de lucht is heel droog",
                 "de wind waait heel hard"],
         antwoord=0,
         uitleg="In een torenhoge onweerswolk wordt een druppel door de opstijgende lucht telkens weer omhooggeslingerd, en zo groeit er een laagje ijs omheen."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat lees je af op een kaart met isohyeten?",
         opties=["de neerslag",
                 "de temperatuur",
                 "de luchtdruk",
                 "de windrichting"],
         antwoord=0,
         uitleg="Een isohyeet verbindt punten met dezelfde neerslaghoeveelheid. Isothermen horen bij de temperatuur, isobaren bij de druk."),
    dict(type="meerkeuze",
         vraag="Wat is een stijgingsregen?",
         opties=["regen aan de loefzijde van een berg",
                 "regen uit een onweerswolk in de zomer",
                 "regen aan een front tussen luchtmassa's",
                 "regen die 's nachts aan de kust valt"],
         antwoord=0,
         uitleg="De lucht moet over het reliëf omhoog, koelt af en geeft haar vocht af. Men noemt het ook een orografische regen."),
    dict(type="invultekst",
         vraag="Hoe noem je de droge zijde achter een bergketen? Eén woord.",
         antwoord=["regenschaduw"],
         uitleg="De regenschaduw, aan de lijzijde. De lucht is daar haar vocht al kwijt, en bij het dalen warmt ze op en droogt ze verder uit."),
    dict(type="meerkeuze",
         vraag="Welke soorten regen noemt de fiche?",
         opties=["stijgingsregens",
                 "convectieregens",
                 "frontale regens",
                 "zeeregens boven de oceaan"],
         antwoord=[0, 1, 2],
         uitleg="Stijgingsregens bij reliëf, convectieregens aan de ITCZ en frontale regens aan een front. Een zeeregen bestaat niet als term."),
    dict(type="waarofniet",
         vraag="Een convectieregen valt vooral in de namiddag, na een warme voormiddag.",
         antwoord=True,
         uitleg="De zon verwarmt de grond, warme lucht stijgt op en de bui barst los. In de tropen gebeurt dat bijna elke dag rond hetzelfde uur."),
    dict(type="meerkeuze",
         vraag="Wat is een front?",
         opties=["de grens tussen twee luchtmassa's",
                 "de grens tussen zee en land",
                 "de grens tussen dag en nacht",
                 "de grens tussen twee klimaatzones"],
         antwoord=0,
         uitleg="Aan een front schuift warme lucht over koude of duwt koude lucht warme omhoog. In beide gevallen stijgt lucht op en valt er neerslag."),
    dict(type="meerkeuze",
         vraag="Welke lucht stijgt op aan een warmtefront?",
         opties=["de warme lucht",
                 "de koude lucht",
                 "de droge lucht",
                 "de lucht boven de zee"],
         antwoord=0,
         uitleg="Warme lucht is lichter en schuift zachtjes over de koude. Dat geeft lang aanhoudende, rustige regen."),
    dict(type="invultekst",
         vraag="Hoe noem je de zone waar convectieregens het hele jaar vallen, met drie letters?",
         antwoord=["ITCZ", "itcz"],
         uitleg="De intertropische convergentiezone. Daar ligt het tropisch regenwoud, met meer dan tweeduizend millimeter per jaar."),
    dict(type="meerkeuze",
         vraag="Welke factoren bepalen volgens de fiche de neerslagverdeling?",
         opties=["de luchtdruk",
                 "de zeestromen",
                 "het reliëf",
                 "de lengteligging"],
         antwoord=[0, 1, 2],
         uitleg="Druk, zeestromen, ligging ten opzichte van de zee, reliëf, de ITCZ en de fronten. De lengteligging zegt op zich niets over neerslag."),
    dict(type="waarofniet",
         vraag="Een koude zeestroom langs een kust maakt die kust juist natter.",
         antwoord=False,
         uitleg="Boven koud water verdampt er weinig, dus wordt de kust droger. Zo ontstonden de Atacama en de Namibwoestijn, pal aan de oceaan."),
    dict(type="meerkeuze",
         vraag="Waarom valt er in het binnenland van Azië zo weinig regen?",
         opties=["de zee ligt er heel ver weg",
                 "de zon staat er altijd laag",
                 "er waait er nooit wind",
                 "de bodem is er te hard"],
         antwoord=0,
         uitleg="Zeelucht is haar vocht al kwijt voor ze zo diep in het continent komt. Dat is de reden achter de Gobiwoestijn."),
    dict(type="meerkeuze",
         vraag="Waar valt de meeste neerslag op aarde?",
         opties=["rond de evenaar",
                 "rond de keerkringen",
                 "op de polen",
                 "midden in de continenten"],
         antwoord=0,
         uitleg="Aan de ITCZ stijgt vochtige lucht het hele jaar op. Rond de keerkringen daalt ze juist, en daar liggen de woestijnen."),
    dict(type="invultekst",
         vraag="Hoeveel millimeter neerslag valt er in België gemiddeld per jaar? Vul het getal in honderden in, bijvoorbeeld 800.",
         antwoord=["800", "850", "900"],
         uitleg="Rond de achthonderd millimeter, meer in de Ardennen en minder in het noorden. Dat is verspreid over ongeveer tweehonderd dagen."),
    dict(type="meerkeuze",
         vraag="Waarom valt er in de Ardennen meer regen dan in Limburg?",
         opties=["de lucht moet daar omhoog",
                 "de Ardennen liggen zuidelijker",
                 "de bodem houdt er meer water",
                 "er staan er meer bossen"],
         antwoord=0,
         uitleg="Het reliëf duwt de zeelucht omhoog, en stijgende lucht geeft regen. In de Hoge Venen valt meer dan 1.400 millimeter per jaar."),
    dict(type="waarofniet",
         vraag="De polen zijn nat gebied, want er ligt veel ijs.",
         antwoord=False,
         uitleg="De poolgebieden zijn koude woestijnen: er valt minder dan tweehonderd millimeter per jaar. Het ijs blijft liggen omdat het niet smelt, niet omdat er veel valt."),
    dict(type="meerkeuze",
         vraag="Wat is een moesson?",
         opties=["een wind die van seizoen omkeert",
                 "een storm boven warm zeewater",
                 "een lange droogteperiode",
                 "een regen aan een koufront"],
         antwoord=0,
         uitleg="In de zomer waait hij van de zee naar het warme land en brengt hij zware regen, in de winter omgekeerd. India leeft op dat ritme."),
    dict(type="meerkeuze",
         vraag="Welke gebieden zijn droog door hun hoge luchtdruk?",
         opties=["de Sahara",
                 "de Kalahari",
                 "de woestijnen van Australië",
                 "het Amazonewoud"],
         antwoord=[0, 1, 2],
         uitleg="Ze liggen alle drie rond een keerkring, in het subtropisch maximum. Het Amazonewoud ligt aan de ITCZ, met lage druk en veel regen."),
    dict(type="waarofniet",
         vraag="Bij ons komt de meeste neerslag van fronten uit het westen.",
         antwoord=True,
         uitleg="De depressies van de Atlantische Oceaan brengen hun warmte- en koufronten mee. Daarom wisselt het weer bij ons zo vaak."),
    dict(type="meerkeuze",
         vraag="Wat gebeurt er met lucht die over een bergketen weer naar beneden zakt?",
         opties=["ze warmt op en droogt uit",
                 "ze koelt af en wordt vochtiger",
                 "ze blijft precies gelijk",
                 "ze valt stil tegen de helling"],
         antwoord=0,
         uitleg="Dat is de föhn. In de Alpendalen aan de lijzijde kan het daardoor plots tien graden warmer worden."),
    dict(type="meerkeuze",
         vraag="Wat betekent het als de isohyeten dicht bij elkaar liggen?",
         opties=["de neerslag verandert snel",
                 "de neerslag is overal gelijk",
                 "de temperatuur verandert snel",
                 "de luchtdruk is er hoog"],
         antwoord=0,
         uitleg="Zoals bij alle iso-lijnen: dicht bij elkaar betekent een snelle verandering over korte afstand. Dat gebeurt vaak aan de rand van een bergketen."),
]
