# -*- coding: utf-8 -*-
"""Verstedelijking en het ruimtelijk beleid.

Uit de vakfiche aardrijkskunde van de 3de graad dubbele finaliteit (2027):
de verstedelijkingsprocessen (urbanisatie, suburbanisatie, rurbanisatie,
re-urbanisatie, desurbanisatie), het ruimtelijk beleid in Vlaanderen vanaf de
jaren zestig (het gewestplan, het RSV en het BRV) en de gevolgen van de manier
waarop wij onze ruimte innemen: ruimtebeslag, versnippering, lintbebouwing,
verharding, het hitte-eiland, de woontypologieën, sociale segregatie, de
afwatering en de mobiliteit.

Deel 1 zijn de processen en de woonvormen.
Deel 2 is het beleid en de gevolgen.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is urbanisatie?",
         opties=["de stad groeit aan",
                 "de stad loopt stilaan leeg",
                 "het platteland groeit aan",
                 "de dorpen worden steden"],
         antwoord=0,
         uitleg="Mensen trekken naar de stad en het aandeel stedelingen stijgt. In Europa gebeurde dat vooral tijdens de industrialisatie."),
    dict(type="meerkeuze",
         vraag="Wat is suburbanisatie?",
         opties=["mensen trekken naar de rand",
                 "mensen trekken naar het centrum",
                 "mensen trekken naar het buitenland",
                 "mensen blijven waar ze wonen"],
         antwoord=0,
         uitleg="De stadsrand groeit sneller dan de kern. Een huis met een tuin en een auto maakten dat mogelijk."),
    dict(type="invultekst",
         vraag="Hoe noem je het terugkeren van mensen naar de stadskern? Eén woord.",
         antwoord=["re-urbanisatie", "reurbanisatie"],
         uitleg="Re-urbanisatie. Vernieuwde wijken, studenten en kleinere gezinnen brengen de kern weer vol."),
    dict(type="meerkeuze",
         vraag="Welke processen horen bij de verstedelijking?",
         opties=["urbanisatie",
                 "suburbanisatie",
                 "rurbanisatie",
                 "glaciatie"],
         antwoord=[0, 1, 2],
         uitleg="Glaciatie is het werk van gletsjers en hoort bij het landschap. De drie andere gaan over waar mensen wonen."),
    dict(type="waarofniet",
         vraag="Bij desurbanisatie verliest de stad bewoners aan verder gelegen gebieden.",
         antwoord=True,
         uitleg="Niet enkel de rand maar de hele stadsregio loopt dan leeg. Dat gebeurde in oude industriesteden waar het werk verdween."),
    dict(type="meerkeuze",
         vraag="Wat is rurbanisatie?",
         opties=["het platteland wordt stedelijk",
                 "de stad wordt groener aangelegd",
                 "boeren verhuizen naar de stad",
                 "akkers worden weer bos"],
         antwoord=0,
         uitleg="Stedelingen gaan op het platteland wonen en nemen hun stedelijke leefwijze mee. Het dorp verliest dan zijn landelijk karakter."),
    dict(type="invultekst",
         vraag="Hoe noem je de bebouwing die als een lange band langs een weg staat? Eén woord.",
         antwoord=["lintbebouwing", "lintbebouwig"],
         uitleg="Lintbebouwing. Typisch Vlaams, en duur: elk lint vraagt riolering, kabels en een bus die langs alle huizen rijdt."),
    dict(type="meerkeuze",
         vraag="Welke woonvorm neemt per gezin de meeste ruimte in?",
         opties=["een vrijstaande woning",
                 "een appartement in de stad",
                 "een rijhuis in een straat",
                 "een halfopen bebouwing"],
         antwoord=0,
         uitleg="Een vrijstaande woning heeft aan vier zijden plaats nodig. Een appartementsgebouw stapelt gezinnen op dezelfde grond."),
    dict(type="meerkeuze",
         vraag="Wat is urban sprawl?",
         opties=["uitgesmeerde stedelijke bebouwing",
                 "een stad met heel hoge gebouwen",
                 "een dorp zonder winkels",
                 "een stad zonder groen"],
         antwoord=0,
         uitleg="De bebouwing kruipt in dunne lagen over het landschap, zonder duidelijke grens. Vlaanderen is daarvan een schoolvoorbeeld in Europa."),
    dict(type="waarofniet",
         vraag="Vlaanderen is een van de dunst bebouwde gebieden van Europa.",
         antwoord=False,
         uitleg="Net omgekeerd: ruim een zesde van de oppervlakte is ingenomen door wonen, werken en wegen. Dat is veel meer dan het Europese gemiddelde."),
    dict(type="meerkeuze",
         vraag="Waarom trokken gezinnen vanaf de jaren zestig naar de stadsrand?",
         opties=["de auto en de bouwgrond",
                 "het openbaar vervoer",
                 "de hoge huurprijzen in de rand",
                 "het werk dat naar de rand ging"],
         antwoord=0,
         uitleg="Iedereen kreeg een auto en bouwgrond buiten de stad was goedkoop. De wet De Taeye hielp mensen bovendien aan een eigen huis."),
    dict(type="invultekst",
         vraag="Hoe noem je het verschijnsel dat een stad warmer is dan haar omgeving? Twee woorden.",
         antwoord=["hitte-eiland", "hitte eiland", "stedelijk hitte-eiland"],
         uitleg="Het hitte-eiland. Steen en asfalt slaan warmte op en geven ze 's nachts weer af."),
    dict(type="meerkeuze",
         vraag="Wat is ruimtebeslag?",
         opties=["de grond die de mens inneemt",
                 "de grond die verhard is",
                 "de grond in eigendom van de staat",
                 "de grond die nog vrij is"],
         antwoord=0,
         uitleg="Alles wat niet meer voor natuur of landbouw dient: woningen, tuinen, wegen, bedrijven. Verharding is daarvan maar een deel."),
    dict(type="meerkeuze",
         vraag="Welke gevolgen heeft een versnipperd landschap voor dieren?",
         opties=["ze kunnen niet meer doortrekken",
                 "hun gebied wordt te klein",
                 "ze komen vaker onder een auto",
                 "ze vinden meer voedsel"],
         antwoord=[0, 1, 2],
         uitleg="Wegen en bebouwing knippen de natuur in stukken. Een ecoduct of een natuurbrug probeert dat weer aan elkaar te hangen."),
    dict(type="waarofniet",
         vraag="Een tuin met gras telt niet mee bij het ruimtebeslag.",
         antwoord=False,
         uitleg="Een tuin hoort bij de woonkavel en telt dus mee. Verharding is een smaller begrip: enkel wat met beton, asfalt of klinkers bedekt is."),
    dict(type="meerkeuze",
         vraag="Wat is sociale segregatie in een stad?",
         opties=["groepen wonen apart van elkaar",
                 "de stad is in wijken verdeeld",
                 "de stad heeft veel nieuwkomers",
                 "de huizen zijn er te duur"],
         antwoord=0,
         uitleg="Arm en rijk, of groepen van andere herkomst, komen in andere wijken terecht. Dat gaat vaak samen met het verschil in woningprijzen."),
    dict(type="meerkeuze",
         vraag="Wat is gentrificatie?",
         opties=["een arme wijk wordt duur",
                 "een duur centrum loopt leeg",
                 "een wijk wordt gesloopt",
                 "een wijk krijgt meer groen"],
         antwoord=0,
         uitleg="Vernieuwing trekt kapitaalkrachtiger bewoners aan en de prijzen stijgen. De oude bewoners kunnen hun wijk dan niet meer betalen."),
    dict(type="waarofniet",
         vraag="Een appartement verbruikt per gezin meestal minder energie dan een vrijstaande woning.",
         antwoord=True,
         uitleg="Minder buitenmuren betekent minder warmteverlies. Bovendien liggen appartementen vaker dicht bij winkels en openbaar vervoer."),
    dict(type="meerkeuze",
         vraag="Welke woonvormen zijn woontypologieën?",
         opties=["een rijhuis",
                 "een appartement",
                 "halfopen bebouwing",
                 "een ecoduct"],
         antwoord=[0, 1, 2],
         uitleg="Een woontypologie is een soort woning: vrijstaand, halfopen, rijhuis of appartement. Een ecoduct is een natuurbrug over een weg."),
    dict(type="meerkeuze",
         vraag="Waar in een stad vind je het vaakst appartementsgebouwen?",
         opties=["in de kern",
                 "aan de rand bij de velden",
                 "in de verkavelingen",
                 "in de industriezone"],
         antwoord=0,
         uitleg="Waar de grond het duurst is, wordt in de hoogte gebouwd. Verder van de kern verschijnen de rijhuizen en daarna de vrijstaande woningen."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat regelde het gewestplan vanaf de jaren zeventig?",
         opties=["de bestemming van elk perceel",
                 "hoeveel een huis mag kosten",
                 "wie welke grond mag kopen",
                 "hoe hoog een gebouw mag zijn"],
         antwoord=0,
         uitleg="Elke kleur op de kaart is een bestemming: woonzone, industrie, landbouw, natuur. Er werd toen veel meer woongebied ingekleurd dan nodig."),
    dict(type="invultekst",
         vraag="Hoe noem je het plan dat het gewestplan opvolgde, met drie letters?",
         antwoord=["RSV", "rsv"],
         uitleg="Het Ruimtelijk Structuurplan Vlaanderen, uit 1997. Het wou de groei bundelen in de steden en het buitengebied open houden."),
    dict(type="meerkeuze",
         vraag="Wat wil het Beleidsplan Ruimte Vlaanderen?",
         opties=["geen open ruimte meer innemen",
                 "overal hoger bouwen",
                 "alle verkavelingen slopen",
                 "meer bouwgrond inkleuren"],
         antwoord=0,
         uitleg="Het BRV wil het ruimtebeslag tegen 2040 niet meer laten groeien. Dat noemen ze de bouwshift: bouwen waar al bebouwd is."),
    dict(type="waarofniet",
         vraag="Het gewestplan kleurde minder woongebied in dan er nodig was.",
         antwoord=False,
         uitleg="Juist veel meer: er is nog altijd onbebouwd woongebied over. Die overmaat is precies wat de bouwshift nu probeert bij te sturen."),
    dict(type="meerkeuze",
         vraag="Welke maatregelen horen bij duurzaam ruimtegebruik?",
         opties=["intensiever gebruiken wat er is",
                 "oude gebouwen hergebruiken",
                 "functies verweven in één gebied",
                 "nieuwe verkavelingen in het veld"],
         antwoord=[0, 1, 2],
         uitleg="Intensivering, hergebruik en verweving staan letterlijk in het BRV. Een nieuwe verkaveling in open ruimte doet juist het omgekeerde."),
    dict(type="invultekst",
         vraag="Hoe noem je de omslag naar bouwen binnen het bestaande ruimtebeslag? Eén woord.",
         antwoord=["bouwshift", "betonstop"],
         uitleg="De bouwshift, vroeger de betonstop genoemd. Niet dat er niet meer gebouwd wordt, maar niet meer in de open ruimte."),
    dict(type="meerkeuze",
         vraag="Wat is verweving van functies?",
         opties=["wonen en werken door elkaar",
                 "elke functie in een eigen zone",
                 "een wijk met enkel woningen",
                 "een bedrijvenpark buiten de stad"],
         antwoord=0,
         uitleg="Winkels, scholen, werk en wonen dicht bij elkaar. Dat spaart ruimte en verkeer, want je hoeft niet voor alles de auto te nemen."),
    dict(type="meerkeuze",
         vraag="Waarom geeft verharding wateroverlast?",
         opties=["regen zakt niet in de bodem",
                 "regen verdampt veel sneller",
                 "de riolen staan altijd droog",
                 "er valt meer regen op beton"],
         antwoord=0,
         uitleg="Het water loopt snel naar de riool en de beek in plaats van te infiltreren. Daardoor is er tegelijk overstroming en droogte."),
    dict(type="waarofniet",
         vraag="Een wadi houdt regenwater tijdelijk vast zodat het kan infiltreren.",
         antwoord=True,
         uitleg="Een ondiepe groene kom die bij een bui vol loopt en traag leegloopt. Zo komt het water in de grond in plaats van in de riool."),
    dict(type="meerkeuze",
         vraag="Waarom is lintbebouwing duur voor de gemeenschap?",
         opties=["nutsleidingen moeten verder",
                 "de huizen zijn er groter",
                 "de grond is er duurder",
                 "de bewoners betalen minder"],
         antwoord=0,
         uitleg="Riolering, kabels, wegen, post en de bus moeten elk huis apart bereiken. Per woning kost dat een veelvoud van een rijhuis in de kern."),
    dict(type="invultekst",
         vraag="Hoe noem je het opdelen van natuur in losse stukken door wegen en bebouwing? Eén woord.",
         antwoord=["versnippering", "fragmentatie"],
         uitleg="Versnippering. Vlaanderen heeft een van de dichtste wegennetten van Europa, en dus veel snippers."),
    dict(type="meerkeuze",
         vraag="Welke gevolgen heeft het hitte-eiland in de stad?",
         opties=["warmere nachten",
                 "meer gezondheidsklachten",
                 "meer koeling nodig",
                 "minder luchtvervuiling"],
         antwoord=[0, 1, 2],
         uitleg="Vooral ouderen en zieken hebben het zwaar in een hittegolf. De luchtkwaliteit wordt bij hitte juist slechter, niet beter."),
    dict(type="meerkeuze",
         vraag="Welke ingreep koelt een straat het meest af?",
         opties=["bomen planten",
                 "de straat zwart asfalteren",
                 "de voortuinen betegelen",
                 "de stoep breder maken"],
         antwoord=0,
         uitleg="Schaduw en verdamping werken samen. Ontharden helpt ook, maar tegels leggen of zwart asfalt maakt het juist warmer."),
    dict(type="waarofniet",
         vraag="Hoe dichter de bebouwing, hoe meer kilometers mensen met de auto rijden.",
         antwoord=False,
         uitleg="Omgekeerd: in een dichte kern liggen school, winkel en werk dichtbij en loont openbaar vervoer. Een verspreide bebouwing dwingt tot autorijden."),
    dict(type="meerkeuze",
         vraag="Wat is een nodaliteit of knooppuntwaarde?",
         opties=["hoe goed een plek ontsloten is",
                 "hoeveel mensen er in de buurt wonen",
                 "hoeveel groen er ligt",
                 "hoe duur de grond er is"],
         antwoord=0,
         uitleg="Een plek dicht bij een station of een goede buslijn haalt een hoge score. Het BRV wil juist daar bijkomende woningen."),
    dict(type="meerkeuze",
         vraag="Wat is tijdelijk ruimtegebruik?",
         opties=["leegstand even nuttig gebruiken",
                 "een gebouw na tien jaar slopen",
                 "een park in de zomer sluiten",
                 "een weg tijdelijk afzetten"],
         antwoord=0,
         uitleg="Een leeg pand of een braakliggend terrein krijgt intussen een buurttuin, een pop-up of ateliers. Het BRV noemt het als een van de hefbomen."),
    dict(type="waarofniet",
         vraag="Een ecoduct is een brug of tunnel waarlangs dieren een weg kunnen oversteken.",
         antwoord=True,
         uitleg="Het hangt twee stukken natuur weer aan elkaar. In Vlaanderen liggen er onder meer over de E314 en de E19."),
    dict(type="meerkeuze",
         vraag="Welke kernkwaliteiten staan in het BRV?",
         opties=["nabijheid",
                 "veerkracht",
                 "een gezonde leefomgeving",
                 "zo veel mogelijk vrije grond bebouwen"],
         antwoord=[0, 1, 2],
         uitleg="Samen met een eigen identiteit horen die bij de tien kernkwaliteiten van het Beleidsplan Ruimte Vlaanderen. Vrije grond bebouwen gaat er juist tegen in."),
    dict(type="meerkeuze",
         vraag="Waarom is een kernversterking goed voor de open ruimte?",
         opties=["er wordt in de kern bijgebouwd",
                 "de kern wordt autovrij",
                 "de kern krijgt meer parkeerplaats",
                 "de kern wordt afgebroken"],
         antwoord=0,
         uitleg="Elke woning in de kern is er een die niet in het veld komt. Daarom hangen kernversterking en de bouwshift aan elkaar."),
    dict(type="meerkeuze",
         vraag="Met welk instrument van de Vlaamse overheid bekijk je de bestemming van een perceel?",
         opties=["Geopunt",
                 "een klimatogram",
                 "een seismograaf",
                 "een stratigrafische kaart"],
         antwoord=0,
         uitleg="Geopunt legt luchtfoto's, bestemmingsplannen en overstromingskaarten over elkaar. De andere drie horen bij klimaat, aardbevingen en gesteenten."),
]
