# -*- coding: utf-8 -*-
"""Het landschap lezen en duurzaam met de ruimte omgaan.

Uit de vakfiche aardrijkskunde van de 3de graad dubbele finaliteit (2027):
een landschap analyseren met satellietbeelden in ware en in valse kleuren,
met luchtfoto's, oude kaarten, bodemkaarten, hoogtemodellen en geologische
doorsnedes, en met Geopunt als instrument; en daarnaast het duurzame
ruimtegebruik met de 5 P's, de duurzame ontwikkelingsdoelen van de Verenigde
Naties en het systeemdenken.

Deel 1 is het landschap lezen.
Deel 2 is duurzaam met de ruimte omgaan.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat zie je op een satellietbeeld in ware kleuren?",
         opties=["wat je oog ook zou zien",
                 "enkel de warmte van het oppervlak",
                 "enkel de hoogte van het landschap",
                 "enkel de bebouwing en de wegen"],
         antwoord=0,
         uitleg="Groen blijft groen en water blijft blauw. Een valsekleurenbeeld geeft andere kleuren, want het toont straling die het oog niet ziet."),
    dict(type="meerkeuze",
         vraag="Hoe verschijnt gezonde plantengroei op een valsekleurenbeeld?",
         opties=["rood",
                 "altijd helemaal zwart",
                 "altijd donkerblauw gekleurd",
                 "altijd wit zoals sneeuw"],
         antwoord=0,
         uitleg="Bladgroen weerkaatst veel infrarood, en dat wordt als rood weergegeven. Hoe feller het rood, hoe gezonder de vegetatie."),
    dict(type="invultekst",
         vraag="Welk instrument van de Vlaamse overheid legt kaarten en luchtfoto's over elkaar? Eén woord.",
         antwoord=["Geopunt", "geopunt"],
         uitleg="Geopunt. Je kan er een perceel opzoeken en de bestemming, de bodem en de overstromingskans naast elkaar leggen."),
    dict(type="meerkeuze",
         vraag="Welke lagen kan je in Geopunt over elkaar leggen?",
         opties=["luchtfoto's",
                 "het bestemmingsplan",
                 "de overstromingskaart",
                 "de uurregeling van de bus"],
         antwoord=[0, 1, 2],
         uitleg="Precies door die lagen te combineren zie je waarom iets ergens ligt. De bussen staan op de website van De Lijn, niet in Geopunt."),
    dict(type="waarofniet",
         vraag="Een topografische kaart toont de hoogte met hoogtelijnen.",
         antwoord=True,
         uitleg="Elke lijn verbindt punten van gelijke hoogte. Liggen de lijnen dicht bij elkaar, dan is de helling steil."),
    dict(type="meerkeuze",
         vraag="Wat is een geologische doorsnede?",
         opties=["een kijk in de ondergrond",
                 "een kaart van de bodemsoorten",
                 "een foto van een steengroeve",
                 "een plan van een gebouw"],
         antwoord=0,
         uitleg="Je ziet de gesteentelagen zoals ze onder elkaar liggen, met hun plooien en breuken. Een bodemkaart blijft aan de oppervlakte."),
    dict(type="meerkeuze",
         vraag="Waaraan herken je een natuurlijke rivier op een luchtfoto?",
         opties=["aan de bochten",
                 "aan de rechte lijn door het veld",
                 "aan de kleur van de akkers",
                 "aan de rij bomen op de heuvel"],
         antwoord=0,
         uitleg="Meanders zijn het handschrift van een rivier die zelf mag kiezen. Een kaarsrechte waterloop is door de mens getrokken."),
    dict(type="invultekst",
         vraag="Hoe noem je de lijnen op een kaart die punten van gelijke hoogte verbinden? Eén woord.",
         antwoord=["hoogtelijnen", "hoogtelijn", "isohypsen"],
         uitleg="Hoogtelijnen, of isohypsen. Hun afstand verraadt de steilte van het terrein."),
    dict(type="waarofniet",
         vraag="Op een luchtfoto van vijftig jaar oud kan je zien hoeveel bebouwing erbij kwam.",
         antwoord=True,
         uitleg="Twee foto's van dezelfde plek naast elkaar zijn de duidelijkste les over ruimtebeslag. Geopunt heeft reeksen die tot 1971 teruggaan."),
    dict(type="meerkeuze",
         vraag="Welke bronnen gebruik je bij een landschapsanalyse?",
         opties=["een luchtfoto",
                 "een oude kaart",
                 "een veldbezoek",
                 "een klimatogram van Rome"],
         antwoord=[0, 1, 2],
         uitleg="Je legt het beeld van boven, de geschiedenis en je eigen ogen naast elkaar. Een klimatogram van Rome zegt niets over dit landschap."),
    dict(type="waarofniet",
         vraag="Een valsekleurenbeeld heeft verkeerde kleuren om de kijker te misleiden.",
         antwoord=False,
         uitleg="De kleuren zijn niet verkeerd maar vertaald: ze tonen infrarood dat het oog niet kan zien. Zo zie je of plantengroei gezond is."),
    dict(type="meerkeuze",
         vraag="Wat betekent systeemdenken bij een landschap?",
         opties=["alles hangt aan elkaar",
                 "elk onderdeel apart bekijken",
                 "enkel naar de natuur kijken",
                 "enkel de mens bestuderen"],
         antwoord=0,
         uitleg="Bodem, water, reliëf, planten en mensen werken op elkaar in. Verander je één ding, dan verschuift de rest mee."),
    dict(type="meerkeuze",
         vraag="Wat is een digitaal hoogtemodel?",
         opties=["een hoogtekaart",
                 "een model van het weer",
                 "een kaart van de wegen",
                 "een foto uit een vliegtuig"],
         antwoord=0,
         uitleg="Elke vierkante meter heeft er een hoogte, gemeten met laser uit een vliegtuig. Daarmee zie je zelfs oude akkerranden en loopgraven."),
    dict(type="waarofniet",
         vraag="Rechte percelen en brede wegen wijzen op een eeuwenoud landschap.",
         antwoord=False,
         uitleg="Rechte lijnen zijn jong: ze komen van een herverkaveling of een verkaveling. Een oud landschap heeft kronkelwegen en percelen in alle vormen."),
    dict(type="meerkeuze",
         vraag="Waarvoor dient een profiel door een landschap?",
         opties=["de hoogte in beeld brengen",
                 "de bevolking in beeld brengen",
                 "de temperatuur meten op het veld",
                 "de bodemsoort bepalen in het labo"],
         antwoord=0,
         uitleg="Je tekent het terrein van de zijkant, zoals je het zou zien als je het doormidden zaagde. Zo worden heuvels en valleien meteen duidelijk."),
    dict(type="meerkeuze",
         vraag="Wat lees je af uit een bodemkaart?",
         opties=["de bodemsoort",
                 "de hoogte van het terrein",
                 "de leeftijd van de gebouwen",
                 "de richting van de wind"],
         antwoord=0,
         uitleg="Zand, leem, klei of een mengvorm, met de vochtigheid erbij. Boeren en bouwers kijken er allebei naar."),
    dict(type="meerkeuze",
         vraag="Hoe herken je een verkaveling op een luchtfoto?",
         opties=["aan de gelijke huizen",
                 "aan de kronkelende rivier",
                 "aan de lange rechte akkers",
                 "aan het grote bos errond"],
         antwoord=0,
         uitleg="Dezelfde huizen, dezelfde tuinen, dezelfde straatbreedte, alles in één keer gebouwd. Vaak met een doodlopende straat of een lus."),
    dict(type="meerkeuze",
         vraag="Welke vragen horen bij een landschapsanalyse?",
         opties=["wat zie ik?",
                 "waarom ligt het hier?",
                 "hoe is het zo geworden?",
                 "wie woont er het langst?"],
         antwoord=[0, 1, 2],
         uitleg="Beschrijven, verklaren en de geschiedenis erbij halen. Wie er het langst woont, verandert niets aan het landschap zelf."),
    dict(type="meerkeuze",
         vraag="Wat is een orthofoto?",
         opties=["een rechtgezette luchtfoto",
                 "een foto van de ondergrond",
                 "een tekening van een landschap",
                 "een foto genomen vanaf de grond"],
         antwoord=0,
         uitleg="Het perspectief is eruit gerekend, zodat je op de foto echt kan meten. Daarom liggen orthofoto's onder de kaarten van Geopunt."),
    dict(type="invultekst",
         vraag="Welke straling vangt een valsekleurenbeeld op die ons oog niet ziet? Eén woord.",
         antwoord=["infrarood", "infraroodstraling"],
         uitleg="Infrarood. Planten weerkaatsen het sterk, en daarom worden ze rood op het beeld."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Welke P's horen bij de 5 P's van duurzame ontwikkeling?",
         opties=["people",
                 "planet",
                 "peace",
                 "petroleum"],
         antwoord=[0, 1, 2],
         uitleg="De vijf zijn people, planet, prosperity, peace en partnership. Petroleum is aardolie en hoort er net niet bij."),
    dict(type="meerkeuze",
         vraag="Hoeveel duurzame ontwikkelingsdoelen stelden de Verenigde Naties op?",
         opties=["zeventien",
                 "vijf in totaal",
                 "honderd in totaal",
                 "drie in totaal"],
         antwoord=0,
         uitleg="Zeventien doelen voor 2030, van geen armoede tot partnerschap. Ze hangen aan elkaar: aan één doel werken raakt vaak de andere."),
    dict(type="invultekst",
         vraag="Hoe noem je de zeventien doelen van de Verenigde Naties, met drie letters?",
         antwoord=["SDG", "sdg", "SDGs"],
         uitleg="De SDG's, de Sustainable Development Goals. In het Nederlands de duurzame ontwikkelingsdoelstellingen."),
    dict(type="waarofniet",
         vraag="De duurzame ontwikkelingsdoelen gelden enkel voor arme landen.",
         antwoord=False,
         uitleg="Ze gelden voor alle landen, ook voor België. Rijke landen hebben werk aan hun uitstoot, hun afval en hun ongelijkheid."),
    dict(type="meerkeuze",
         vraag="Wat betekent duurzaam omgaan met de ruimte?",
         opties=["ook voor later ruimte laten",
                 "alle open ruimte nu bebouwen",
                 "zo veel mogelijk grond kopen",
                 "elke zone een eigen functie geven"],
         antwoord=0,
         uitleg="Wat je nu volbouwt, kan een volgende generatie niet meer anders gebruiken. Daarom zuinig met grond, en hergebruiken wat er al staat."),
    dict(type="meerkeuze",
         vraag="Welk duurzaam ontwikkelingsdoel gaat over de steden?",
         opties=["duurzame steden",
                 "schoon water en sanitair",
                 "waardig werk en groei",
                 "leven in het water"],
         antwoord=0,
         uitleg="Doel elf: duurzame steden en gemeenschappen. Het gaat over wonen, vervoer, groen en veiligheid in de stad."),
    dict(type="meerkeuze",
         vraag="Welke doelen raken het klimaat?",
         opties=["klimaatactie",
                 "duurzame energie",
                 "leven op het land",
                 "gendergelijkheid"],
         antwoord=[0, 1, 2],
         uitleg="Energie, klimaat en de natuur op het land hangen aan elkaar vast. Gendergelijkheid is een doel op zich, maar niet een klimaatdoel."),
    dict(type="waarofniet",
         vraag="Een maatregel kan goed zijn voor het ene doel en slecht voor het andere.",
         antwoord=True,
         uitleg="Een windpark in een natuurgebied helpt het klimaat en schaadt de biodiversiteit. Juist daarom moet je de doelen samen bekijken."),
    dict(type="meerkeuze",
         vraag="Wat is intensivering van ruimtegebruik?",
         opties=["meer doen op dezelfde plek",
                 "meer plek innemen per gezin",
                 "een nieuwe zone aansnijden",
                 "een gebouw volledig slopen"],
         antwoord=0,
         uitleg="Een extra verdieping, een school die in het weekend een zaal wordt, een dak met zonnepanelen. Zo groeit het gebruik zonder dat het ruimtebeslag groeit."),
    dict(type="invultekst",
         vraag="Hoe noem je het opnieuw gebruiken van een leegstaand gebouw? Eén woord.",
         antwoord=["hergebruik", "herbestemming"],
         uitleg="Hergebruik of herbestemming. Een oude fabriek wordt lofts, een kerk wordt een bibliotheek."),
    dict(type="meerkeuze",
         vraag="Wat is een brownfield?",
         opties=["een oud bedrijfsterrein",
                 "een pas ingericht woonpark",
                 "een akker naast de snelweg",
                 "een natuurgebied in de stad"],
         antwoord=0,
         uitleg="Verlaten en vaak vervuild, maar wel al ingenomen ruimte. Zo'n terrein opruimen en opnieuw gebruiken spaart open ruimte uit."),
    dict(type="waarofniet",
         vraag="Verdichten betekent dat er meer mensen op dezelfde oppervlakte wonen.",
         antwoord=True,
         uitleg="Meer woningen per hectare, bijvoorbeeld door in de hoogte te bouwen. Dat kan goed uitvallen als er genoeg groen en licht bij blijft."),
    dict(type="meerkeuze",
         vraag="Wat zet je in een systeemdenkschema met pijlen?",
         opties=["de verbanden",
                 "de hoogtelijnen",
                 "de jaartallen op een rij",
                 "de namen van de landen"],
         antwoord=0,
         uitleg="Elke pijl is een oorzaak die naar een gevolg wijst. Kom je bij je vertrekpunt terug, dan heb je een terugkoppeling gevonden."),
    dict(type="meerkeuze",
         vraag="Welke gevolgen heeft het aansnijden van open ruimte?",
         opties=["minder landbouwgrond",
                 "meer versnippering",
                 "meer verharding",
                 "meer ruimte voor natuur"],
         antwoord=[0, 1, 2],
         uitleg="Elke hectare die je bebouwt, verdwijnt als veld of als natuur. Meer ruimte voor natuur is precies wat er niet gebeurt."),
    dict(type="waarofniet",
         vraag="De bouwshift wil dat er in Vlaanderen niets meer gebouwd wordt.",
         antwoord=False,
         uitleg="Er mag gebouwd worden, maar binnen wat al ingenomen is. Dus bijbouwen in de kern in plaats van een nieuwe verkaveling in het veld."),
    dict(type="meerkeuze",
         vraag="Wie beslist in Vlaanderen over de bestemming van de grond?",
         opties=["de overheid",
                 "de eigenaar van de grond",
                 "de bouwfirma zelf",
                 "de buren van het perceel"],
         antwoord=0,
         uitleg="De gemeente, de provincie en Vlaanderen samen, via hun plannen en vergunningen. Een eigenaar mag niet zomaar bouwen wat hij wil."),
    dict(type="meerkeuze",
         vraag="Waarom hoort mobiliteit bij het ruimtelijk beleid?",
         opties=["wonen bepaalt je verkeer",
                 "verkeer heeft niets met wonen te maken",
                 "de auto bepaalt de bestemming",
                 "een trein rijdt overal even vaak"],
         antwoord=0,
         uitleg="Wie ver van alles woont, moet voor elke boodschap de weg op. Daarom gaan bouwen en verplaatsen in hetzelfde plan."),
    dict(type="invultekst",
         vraag="Hoe noem je het weghalen van beton en asfalt zodat regen weer in de grond kan? Eén woord.",
         antwoord=["ontharden", "ontharding"],
         uitleg="Ontharden. Tegels uit een voortuin, beton van een oude oprit: het water kan weer infiltreren en de plek koelt af."),
    dict(type="meerkeuze",
         vraag="Wat is een voorbeeld van verweven ruimtegebruik?",
         opties=["een winkel onder woningen",
                 "een bedrijvenzone op zich",
                 "een woonwijk zonder winkels",
                 "een school buiten het dorp"],
         antwoord=0,
         uitleg="Functies boven en naast elkaar in plaats van elk in een eigen zone. Dat spaart ruimte en verkeer uit."),
    dict(type="meerkeuze",
         vraag="Waarom is een landschap een systeem?",
         opties=["de delen werken op elkaar in",
                 "elk deel staat op zichzelf",
                 "het landschap verandert nooit",
                 "de mens staat erbuiten"],
         antwoord=0,
         uitleg="Een bos kappen verandert de bodem, het water en het klimaat ter plaatse. Daarom bekijk je een ingreep nooit los van de rest."),
]
