# -*- coding: utf-8 -*-
"""Luchtdruk en winden.

Uit de vakfiche aardrijkskunde van de 3de graad dubbele finaliteit (2027): hoe
hoge en lage drukkernen ontstaan (cycloon, anticycloon, depressie, minimum,
maximum), de algemene luchtcirculatie met haar circulatiecellen en drukgordels,
de ITCZ, de straalstroom, het corioliseffect, de land- en zeewinden, en het
lezen van een kaart met isobaren.

Deel 1 is de luchtdruk en de algemene luchtcirculatie.
Deel 2 zijn de winden zelf: passaten, straalstroom, land- en zeewind, en de
isobaren op een kaart.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is een depressie?",
         opties=["een gebied met lage luchtdruk",
                 "een gebied met hoge luchtdruk",
                 "een gebied zonder enige wind",
                 "een gebied met veel zonneschijn"],
         antwoord=0,
         uitleg="Een depressie of minimum is een lagedrukkern. Men noemt ze ook een cycloon, en ze brengt wolken en neerslag."),
    dict(type="meerkeuze",
         vraag="Wat is een anticycloon?",
         opties=["een hogedrukgebied",
                 "een lagedrukgebied",
                 "een tropische storm",
                 "een front tussen twee luchtmassa's"],
         antwoord=0,
         uitleg="Een anticycloon of maximum. De lucht daalt erin, en dalende lucht geeft droog en helder weer."),
    dict(type="invultekst",
         vraag="In welke eenheid geeft men de luchtdruk op een weerkaart? Eén woord.",
         antwoord=["hectopascal", "hPa", "millibar"],
         uitleg="In hectopascal. De gemiddelde druk op zeeniveau is 1013 hectopascal."),
    dict(type="meerkeuze",
         vraag="Welke namen horen bij een lagedrukgebied?",
         opties=["depressie",
                 "cycloon",
                 "minimum",
                 "anticycloon"],
         antwoord=[0, 1, 2],
         uitleg="De fiche noemt cycloon, anticycloon, depressie, minimum en maximum. De anticycloon is juist de hoge druk."),
    dict(type="waarofniet",
         vraag="Wind waait altijd van hoge naar lage luchtdruk.",
         antwoord=True,
         uitleg="Het drukverschil is de motor. Door het corioliseffect waait hij niet rechtstreeks, maar schuin rond de kernen."),
    dict(type="meerkeuze",
         vraag="Waarom ontstaat er lage druk waar lucht opstijgt?",
         opties=["er blijft minder lucht boven de grond",
                 "de lucht wordt er zwaarder gemaakt",
                 "de lucht koelt er sneller af",
                 "de wind blaast de lucht er weg"],
         antwoord=0,
         uitleg="Opstijgende lucht drukt minder op de grond. Daalt de lucht, dan stapelt ze zich op en krijg je hoge druk."),
    dict(type="meerkeuze",
         vraag="Waar ligt het equatoriaal minimum?",
         opties=["rond de evenaar",
                 "rond de keerkringen",
                 "rond de poolcirkels",
                 "boven de polen"],
         antwoord=0,
         uitleg="De sterke zon verwarmt de lucht er, ze stijgt op en dat geeft lage druk. Men noemt die zone ook de ITCZ."),
    dict(type="invultekst",
         vraag="Hoe noem je de zone waar de passaten van beide halfronden samenkomen, met drie letters?",
         antwoord=["ITCZ", "itcz"],
         uitleg="De intertropische convergentiezone. Ze schuift met de zon mee naar het noorden en het zuiden."),
    dict(type="meerkeuze",
         vraag="Welke drukgordels noemt de fiche?",
         opties=["het equatoriaal minimum",
                 "het subtropisch maximum",
                 "het subpolair minimum",
                 "het tropisch maximum"],
         antwoord=[0, 1, 2],
         uitleg="Equatoriaal minimum, subtropisch maximum, subpolair minimum en polair maximum. Een tropisch maximum staat niet in de rij."),
    dict(type="waarofniet",
         vraag="Het subtropisch maximum ligt rond de keerkringen, en daar liggen de grote woestijnen.",
         antwoord=True,
         uitleg="De lucht die aan de evenaar opsteeg, daalt daar weer neer. Dalende lucht geeft geen regen, en zo ontstonden de Sahara en de Kalahari."),
    dict(type="meerkeuze",
         vraag="Wat is een thermische drukgordel?",
         opties=["een gordel die van temperatuur komt",
                 "een gordel die van de rotatie komt",
                 "een gordel die van de bergen komt",
                 "een gordel die van de zeestromen komt"],
         antwoord=0,
         uitleg="Het equatoriaal minimum en het polair maximum zijn thermisch: warmte of koude maakt ze. Het subtropisch maximum is dynamisch."),
    dict(type="meerkeuze",
         vraag="Welke circulatiecellen heeft elk halfrond?",
         opties=["de Hadleycel",
                 "de Ferrelcel",
                 "de poolcel",
                 "de Coriolliscel"],
         antwoord=[0, 1, 2],
         uitleg="Drie cellen per halfrond, en samen verdelen ze de warmte van de evenaar naar de polen. Een Coriolliscel bestaat niet."),
    dict(type="invultekst",
         vraag="Hoe noem je een gebied met hoge luchtdruk, met één woord dat met max begint?",
         antwoord=["maximum"],
         uitleg="Een maximum, ook anticycloon genoemd. Een laag gebied is een minimum of een depressie."),
    dict(type="meerkeuze",
         vraag="Welk weer hoort bij een hogedrukgebied in de zomer?",
         opties=["zonnig en droog",
                 "bewolkt en nat",
                 "stormachtig en koud",
                 "nevelig en regenachtig"],
         antwoord=0,
         uitleg="In een maximum daalt de lucht, warmt ze op en lost de bewolking op. In de winter kan dalende lucht wel mist of inversie geven."),
    dict(type="waarofniet",
         vraag="In het centrum van een depressie daalt de lucht naar beneden.",
         antwoord=False,
         uitleg="In een depressie stijgt de lucht op, en dat geeft wolken en regen. Dalen doet ze in een hogedrukgebied."),
    dict(type="meerkeuze",
         vraag="Waarom schuift de ITCZ in de loop van het jaar op?",
         opties=["de zenitale zonnestand verschuift",
                 "de zeestromen veranderen van richting",
                 "de aardas verandert van hoek",
                 "de passaten worden sterker"],
         antwoord=0,
         uitleg="De zon staat in juni boven de Kreeftskeerkring en in december boven de Steenbokskeerkring. De ITCZ volgt haar, met wat vertraging."),
    dict(type="meerkeuze",
         vraag="Wat gebeurt er met de luchtdruk als de lucht opwarmt?",
         opties=["ze daalt",
                 "ze stijgt",
                 "ze blijft gelijk",
                 "ze wordt onmeetbaar"],
         antwoord=0,
         uitleg="Warme lucht is lichter en stijgt op. Daardoor drukt ze minder op de grond, en dus is de druk er lager."),
    dict(type="waarofniet",
         vraag="De gemiddelde luchtdruk op zeeniveau is ongeveer 500 hectopascal.",
         antwoord=False,
         uitleg="Hij is ongeveer 1013 hectopascal. Alles onder 1000 is op een weerkaart al een flinke depressie, boven 1030 een stevig maximum."),
    dict(type="meerkeuze",
         vraag="Waarom regent het zo veel in het tropisch regenwoud?",
         opties=["de lucht stijgt er voortdurend op",
                 "de zeestromen zijn er koud",
                 "de lucht daalt er voortdurend",
                 "er waaien er sterke passaten"],
         antwoord=0,
         uitleg="Aan de ITCZ stijgt warme, vochtige lucht op, koelt af en geeft haar vocht af. Dat zijn de convectieregens, bijna elke namiddag."),
    dict(type="meerkeuze",
         vraag="Wat betekent convergentie van lucht?",
         opties=["lucht komt samen",
                 "lucht gaat uit elkaar",
                 "lucht koelt af",
                 "lucht droogt uit"],
         antwoord=0,
         uitleg="Convergeren is samenkomen. Komt lucht aan de grond samen, dan moet ze omhoog, en dat geeft wolken."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat lees je af op een kaart met isobaren?",
         opties=["de luchtdruk",
                 "de temperatuur",
                 "de neerslag",
                 "de luchtvochtigheid"],
         antwoord=0,
         uitleg="Een isobaar verbindt punten met dezelfde luchtdruk. Uit de afstand tussen de lijnen lees je de windkracht af."),
    dict(type="meerkeuze",
         vraag="Wat betekenen isobaren die dicht bij elkaar liggen?",
         opties=["harde wind",
                 "zwakke wind",
                 "veel neerslag",
                 "hoge temperatuur"],
         antwoord=0,
         uitleg="Hoe sneller de druk verandert over een afstand, hoe harder het waait. Ver uiteen liggende isobaren betekenen zwakke wind."),
    dict(type="invultekst",
         vraag="Hoe noem je de lijnen op een weerkaart die punten met dezelfde luchtdruk verbinden? Eén woord.",
         antwoord=["isobaren", "isobaar"],
         uitleg="Isobaren. Isothermen horen bij de temperatuur, isohyeten bij de neerslag."),
    dict(type="meerkeuze",
         vraag="Welke winden noemt de fiche?",
         opties=["de passaten",
                 "de straalstroom",
                 "de land- en zeewinden",
                 "de moessonregens"],
         antwoord=[0, 1, 2],
         uitleg="Passaatwinden, de straalstroom en de land- en zeewinden staan in de lijst. Een moesson is een windstelsel, maar geen regen."),
    dict(type="waarofniet",
         vraag="De passaten waaien van het subtropisch maximum naar de evenaar.",
         antwoord=True,
         uitleg="Van hoge naar lage druk, en door het corioliseffect buigen ze af: bij ons uit het noordoosten, op het zuidelijk halfrond uit het zuidoosten."),
    dict(type="meerkeuze",
         vraag="Wat is de straalstroom?",
         opties=["een sterke wind hoog in de troposfeer",
                 "een warme zeestroom in de Atlantische Oceaan",
                 "een rivier van lucht aan het aardoppervlak",
                 "een stroom van deeltjes uit de zon"],
         antwoord=0,
         uitleg="Hij waait op tien kilometer hoogte van west naar oost, met soms meer dan driehonderd kilometer per uur. Hij stuurt onze depressies."),
    dict(type="meerkeuze",
         vraag="Waarom vliegt een vliegtuig van Brussel naar New York langer dan terug?",
         opties=["het vliegt tegen de straalstroom in",
                 "het moet hoger klimmen op de heenreis",
                 "de aarde draait de andere kant op",
                 "de afstand is op de heenreis groter"],
         antwoord=0,
         uitleg="De straalstroom waait van west naar oost. Op de terugweg heb je hem in de rug, en dan scheelt dat een uur."),
    dict(type="invultekst",
         vraag="Hoe noem je de wind die 's avonds van het land naar de zee waait? Twee woorden.",
         antwoord=["landwind", "de landwind"],
         uitleg="De landwind. Overdag waait de zeewind, van de koelere zee naar het warme land."),
    dict(type="meerkeuze",
         vraag="Waarom waait er in de namiddag aan de kust een zeewind?",
         opties=["het land is warmer dan de zee",
                 "de zee is warmer dan het land",
                 "het land is vochtiger dan de zee",
                 "de zee heeft een hogere golfslag"],
         antwoord=0,
         uitleg="Boven het warme land stijgt lucht op, en van de zee stroomt koelere lucht toe. 's Nachts keert het om, want dan koelt het land sneller af."),
    dict(type="waarofniet",
         vraag="Een wind wordt genoemd naar de richting waarheen hij waait.",
         antwoord=False,
         uitleg="Hij wordt genoemd naar waar hij vandaan komt. Een noordenwind komt uit het noorden en waait naar het zuiden."),
    dict(type="meerkeuze",
         vraag="In welke zin draait de wind rond een depressie op het noordelijk halfrond?",
         opties=["tegen de klok in",
                 "met de klok mee",
                 "recht naar het midden toe",
                 "recht van het midden weg"],
         antwoord=0,
         uitleg="Het corioliseffect buigt de instromende lucht naar rechts af. Rond een hogedrukgebied draait ze wel met de klok mee."),
    dict(type="meerkeuze",
         vraag="Waarom buigt de wind op aarde af?",
         opties=["door de rotatie van de aarde",
                 "door de bergen op zijn weg",
                 "door de wrijving met het water",
                 "door het verschil in temperatuur"],
         antwoord=0,
         uitleg="Dat is het corioliseffect. Het is sterker naar de polen toe en zo goed als nul op de evenaar."),
    dict(type="invultekst",
         vraag="Op welke schaal geeft men de windkracht? Eén woord.",
         antwoord=["Beaufort", "beaufort"],
         uitleg="De schaal van Beaufort, van nul tot twaalf. Twaalf Beaufort is een orkaan."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over onze zuidwestenwind zijn juist?",
         opties=["hij komt over de oceaan",
                 "hij brengt zachte lucht",
                 "hij brengt vaak regen",
                 "hij komt het minst voor"],
         antwoord=[0, 1, 2],
         uitleg="Hij is bij ons de meest voorkomende wind, en een oostenwind brengt juist droge continentale lucht."),
    dict(type="waarofniet",
         vraag="In het oog van een tropische cycloon is het bijna windstil.",
         antwoord=True,
         uitleg="Rond dat oog woedt de zwaarste wind, maar in het midden daalt de lucht en is de hemel vaak open. Wie het oog ziet passeren, krijgt de storm nog een tweede keer."),
    dict(type="meerkeuze",
         vraag="Wat is een orkaan of tropische cycloon?",
         opties=["een storm boven warm zeewater",
                 "een storm boven een koude oceaan",
                 "een storm boven een bergketen",
                 "een storm boven een woestijn"],
         antwoord=0,
         uitleg="Hij heeft zeewater van minstens zesentwintig graden nodig als brandstof. Daarom komt hij niet voor op de evenaar zelf: daar is het corioliseffect nul."),
    dict(type="meerkeuze",
         vraag="Welke gevolgen heeft een stevige depressie bij ons?",
         opties=["veel wind",
                 "veel bewolking",
                 "neerslag",
                 "nachtvorst"],
         antwoord=[0, 1, 2],
         uitleg="Nachtvorst krijg je juist bij hoge druk, met een heldere en windstille nacht."),
    dict(type="waarofniet",
         vraag="De wind aan het aardoppervlak waait precies langs de isobaren.",
         antwoord=False,
         uitleg="Hoog in de lucht bijna wel, maar aan de grond remt de wrijving de wind af. Daardoor waait hij schuin over de isobaren naar de lage druk toe."),
    dict(type="meerkeuze",
         vraag="Waarom is er in de Hadleycel een opstijgende en een dalende tak?",
         opties=["lucht stijgt warm op en daalt koud neer",
                 "lucht stijgt koud op en daalt warm neer",
                 "de aarde draait de lucht rond",
                 "de zeestromen duwen de lucht omhoog"],
         antwoord=0,
         uitleg="Aan de evenaar stijgt warme lucht op, boven de keerkringen daalt de afgekoelde lucht weer neer. Zo sluit de kring."),
    dict(type="meerkeuze",
         vraag="Welke drukgordel ligt rond zestig graden breedte?",
         opties=["het subpolair minimum",
                 "het subtropisch maximum",
                 "het equatoriaal minimum",
                 "het polair maximum"],
         antwoord=0,
         uitleg="Daar botsen zachte lucht uit het westen en koude poollucht, en dat geeft lage druk en veel depressies. Onze weersystemen komen daarvandaan."),
]
