# -*- coding: utf-8 -*-
"""De atmosfeer en de temperatuur op aarde.

Uit de vakfiche aardrijkskunde van de 3de graad dubbele finaliteit (2027): de
lagen van de atmosfeer (troposfeer, stratosfeer, mesosfeer) met hun
temperatuur, dichtheid en luchtdruk, de stralingsbalans, en de factoren die de
temperatuurverdeling op aarde veroorzaken, met het lezen van een kaart met
isothermen.

Deel 1 is de opbouw en de samenstelling van de atmosfeer, met de
stralingsbalans.
Deel 2 zijn de factoren die de temperatuur bepalen, en de isothermen.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="In welke laag van de atmosfeer speelt het weer zich af?",
         opties=["de troposfeer",
                 "de stratosfeer",
                 "de mesosfeer",
                 "de thermosfeer"],
         antwoord=0,
         uitleg="De troposfeer is de onderste laag, tot ongeveer tien à twaalf kilometer. Daar zitten de wolken en bijna alle waterdamp."),
    dict(type="meerkeuze",
         vraag="Welke laag ligt boven de troposfeer?",
         opties=["de stratosfeer",
                 "de mesosfeer",
                 "de hydrosfeer",
                 "de lithosfeer"],
         antwoord=0,
         uitleg="Troposfeer, stratosfeer, mesosfeer: zo noemt de fiche ze. De hydrosfeer en de lithosfeer zijn geen lagen van de atmosfeer."),
    dict(type="invultekst",
         vraag="Welk gas maakt ongeveer 78 procent van de lucht uit? Eén woord.",
         antwoord=["stikstof"],
         uitleg="Stikstof. Zuurstof is eenentwintig procent, en de rest is argon, koolstofdioxide en waterdamp."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over de troposfeer zijn juist?",
         opties=["de temperatuur daalt met de hoogte",
                 "de luchtdruk daalt met de hoogte",
                 "bijna alle waterdamp zit erin",
                 "de ozonlaag zit er helemaal in"],
         antwoord=[0, 1, 2],
         uitleg="De ozonlaag zit in de stratosfeer. In de troposfeer daalt de temperatuur ongeveer zes graden per kilometer."),
    dict(type="waarofniet",
         vraag="In de stratosfeer stijgt de temperatuur met de hoogte.",
         antwoord=True,
         uitleg="De ozonlaag neemt daar ultraviolet licht op, en dat verwarmt de lucht. Daarom is de stratosfeer stabiel en vliegen vliegtuigen er graag."),
    dict(type="meerkeuze",
         vraag="Waar zit de ozonlaag?",
         opties=["in de stratosfeer",
                 "in de troposfeer",
                 "in de mesosfeer",
                 "net boven het aardoppervlak"],
         antwoord=0,
         uitleg="Op ongeveer vijftien tot dertig kilometer hoogte. Ze houdt het schadelijkste ultraviolet tegen."),
    dict(type="meerkeuze",
         vraag="Wat gebeurt er met de luchtdruk als je hoger gaat?",
         opties=["hij daalt",
                 "hij stijgt",
                 "hij blijft gelijk",
                 "hij schommelt per laag"],
         antwoord=0,
         uitleg="Hoger liggen er minder luchtmoleculen boven je. Daarom is op een berg de lucht dunner en adem je zwaarder."),
    dict(type="invultekst",
         vraag="Hoe noem je de laag die ultraviolet licht tegenhoudt? Eén woord.",
         antwoord=["ozonlaag", "ozon"],
         uitleg="De ozonlaag, in de stratosfeer. Ozon is een molecule van drie zuurstofatomen."),
    dict(type="meerkeuze",
         vraag="Wat beschrijft de stralingsbalans?",
         opties=["wat de aarde krijgt en weer uitstraalt",
                 "de hoeveelheid regen per jaar op een plaats",
                 "de sterkte van de wind op tien meter hoogte",
                 "de hoeveelheid ozon boven een gebied"],
         antwoord=0,
         uitleg="Wat de aarde van de zon ontvangt, moet ze op de lange duur ook weer uitstralen. Verstoor je die balans, dan verandert het klimaat."),
    dict(type="waarofniet",
         vraag="De atmosfeer wordt vooral van bovenaf verwarmd, rechtstreeks door de zon.",
         antwoord=False,
         uitleg="Het zonlicht gaat grotendeels door de lucht heen en verwarmt de grond. Die grond verwarmt dan de lucht erboven, en daarom daalt de temperatuur met de hoogte."),
    dict(type="meerkeuze",
         vraag="Wat is albedo?",
         opties=["het deel van het licht dat weerkaatst wordt",
                 "het deel van de lucht dat uit zuurstof bestaat",
                 "de snelheid waarmee lucht opwarmt",
                 "de hoogte waarop wolken ontstaan"],
         antwoord=0,
         uitleg="Verse sneeuw weerkaatst tot negentig procent, een donkere oceaan maar een paar procent. Daarom warmt een ontdooiend poolgebied sneller op."),
    dict(type="meerkeuze",
         vraag="Welke gassen houden warmtestraling van de aarde tegen?",
         opties=["koolstofdioxide",
                 "methaan",
                 "waterdamp",
                 "stikstof"],
         antwoord=[0, 1, 2],
         uitleg="Dat zijn de broeikasgassen. Stikstof en zuurstof doen daar niet aan mee, al vormen ze bijna de hele atmosfeer."),
    dict(type="invultekst",
         vraag="Hoe noem je het natuurlijke vasthouden van warmte door de atmosfeer? Twee woorden.",
         antwoord=["broeikaseffect", "het broeikaseffect"],
         uitleg="Het broeikaseffect. Zonder hem zou het op aarde gemiddeld achttien graden onder nul zijn."),
    dict(type="meerkeuze",
         vraag="Hoeveel graden daalt de temperatuur gemiddeld per kilometer hoogte in de troposfeer?",
         opties=["ongeveer zes",
                 "ongeveer één",
                 "ongeveer twintig",
                 "ongeveer vijftig"],
         antwoord=0,
         uitleg="Vandaar dat er op de Alpen sneeuw ligt terwijl het in de vallei zacht is. Men noemt dat de temperatuurgradiënt."),
    dict(type="waarofniet",
         vraag="De dichtheid van de lucht is het grootst net boven het aardoppervlak.",
         antwoord=True,
         uitleg="Het gewicht van de hele atmosfeer perst de onderste lucht samen. De helft van alle lucht zit onder vijf en een halve kilometer."),
    dict(type="meerkeuze",
         vraag="Waarom is het op een berg kouder dan in de vallei, hoewel je dichter bij de zon zit?",
         opties=["de lucht is er dunner en koelt sneller af",
                 "de zon staat er lager boven de horizon",
                 "er valt er altijd meer neerslag",
                 "de berg geeft zijn warmte sneller door"],
         antwoord=0,
         uitleg="Het stukje dichter bij de zon is niets op honderdvijftig miljoen kilometer. Wat telt is dat de verwarmde grond ver onder je ligt."),
    dict(type="meerkeuze",
         vraag="Welke lagen van de atmosfeer noemt de fiche?",
         opties=["de troposfeer",
                 "de stratosfeer",
                 "de mesosfeer",
                 "de hydrosfeer"],
         antwoord=[0, 1, 2],
         uitleg="Die drie, van onder naar boven. Daarboven liggen nog de thermosfeer en de exosfeer, en de hydrosfeer is het water, geen luchtlaag."),
    dict(type="waarofniet",
         vraag="Zuurstof maakt ongeveer de helft van de lucht uit.",
         antwoord=False,
         uitleg="Zuurstof is eenentwintig procent. Stikstof is achtenzeventig procent, en samen is dat al bijna de hele atmosfeer."),
    dict(type="meerkeuze",
         vraag="Waarom branden meteoroïden op in de atmosfeer?",
         opties=["door de wrijving met de lucht",
                 "door de hitte van de zon",
                 "door de zwaartekracht van de aarde",
                 "door de straling in de ozonlaag"],
         antwoord=0,
         uitleg="Bij tientallen kilometer per seconde wordt de lucht voor de brok samengeperst en wordt het gloeiend heet. Dat gebeurt vooral in de mesosfeer."),
    dict(type="meerkeuze",
         vraag="Wat zou er met de temperatuur gebeuren zonder atmosfeer?",
         opties=["veel grotere verschillen tussen dag en nacht",
                 "een gelijkmatige temperatuur over de hele aarde",
                 "een warmere nacht en een koelere dag",
                 "geen enkel verschil met nu"],
         antwoord=0,
         uitleg="Op de maan, zonder atmosfeer, is het in de zon ruim honderd graden en in de schaduw ver onder nul. De lucht verdeelt en buffert de warmte."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat lees je af op een kaart met isothermen?",
         opties=["de temperatuur",
                 "de luchtdruk",
                 "de neerslag",
                 "de windsnelheid"],
         antwoord=0,
         uitleg="Een isotherm verbindt punten met dezelfde temperatuur. Isobaren horen bij de luchtdruk, isohyeten bij de neerslag."),
    dict(type="meerkeuze",
         vraag="Welke factor volgt rechtstreeks uit de aardrevolutie en de rotatie?",
         opties=["de breedteligging",
                 "de hoogteligging",
                 "de bewolking",
                 "de bodemsoort"],
         antwoord=0,
         uitleg="Breedte, invalshoek, tijdstip van de dag en tijdstip in het jaar volgen uit de bewegingen van de aarde. Hoogte en bodem zijn geografisch of lokaal."),
    dict(type="invultekst",
         vraag="Hoe noem je de lijnen op een kaart die punten met dezelfde temperatuur verbinden? Eén woord.",
         antwoord=["isothermen", "isotherm"],
         uitleg="Isothermen. Staan ze dicht bij elkaar, dan verandert de temperatuur snel over een korte afstand."),
    dict(type="meerkeuze",
         vraag="Welke factoren noemt de fiche als geografisch?",
         opties=["de hoogteligging",
                 "de zeestromen",
                 "de ligging ten opzichte van de zee",
                 "de helling van een akker"],
         antwoord=[0, 1, 2],
         uitleg="De helling hoort bij de lokale factoren, samen met vegetatie, bodem, bewolking en windrichting."),
    dict(type="waarofniet",
         vraag="Water warmt trager op en koelt trager af dan land.",
         antwoord=True,
         uitleg="Daarom is het aan de kust in de zomer koeler en in de winter zachter. Dat heet een maritiem klimaat."),
    dict(type="meerkeuze",
         vraag="Waarom is het in Oostende in juli koeler dan in Hasselt?",
         opties=["de zee koelt de lucht af",
                 "Oostende ligt hoger dan Hasselt",
                 "Oostende ligt noordelijker",
                 "er is aan de kust meer bewolking"],
         antwoord=0,
         uitleg="De Noordzee is in de zomer koeler dan het land, en de zeewind brengt die koelte mee. In januari is het aan de kust juist zachter."),
    dict(type="meerkeuze",
         vraag="Wat doet de Noord-Atlantische Drift met het klimaat van West-Europa?",
         opties=["hij maakt het zachter",
                 "hij maakt het kouder",
                 "hij maakt het droger",
                 "hij verandert er niets aan"],
         antwoord=0,
         uitleg="Die warme zeestroom brengt water uit de Golf van Mexico mee. Daardoor is het bij ons veel zachter dan op dezelfde breedte in Canada."),
    dict(type="invultekst",
         vraag="Hoe noem je het klimaat van een plaats dicht bij de zee, met kleine temperatuurverschillen? Eén woord.",
         antwoord=["maritiem", "zeeklimaat"],
         uitleg="Een maritiem klimaat of zeeklimaat. Ver van de zee krijg je een landklimaat of continentaal klimaat."),
    dict(type="meerkeuze",
         vraag="Welke lokale factoren noemt de fiche?",
         opties=["de vegetatie",
                 "de bodem",
                 "de bewolking",
                 "de breedteligging"],
         antwoord=[0, 1, 2],
         uitleg="Helling, vegetatie, bodem, bewolking en windrichting zijn lokaal. De breedteligging volgt uit de bewegingen van de aarde."),
    dict(type="waarofniet",
         vraag="Een bewolkte nacht is kouder dan een heldere nacht.",
         antwoord=False,
         uitleg="Wolken houden de warmtestraling van de grond tegen, als een deken. Vorst krijg je juist bij een heldere, windstille nacht."),
    dict(type="meerkeuze",
         vraag="Waarom staat de hoogste temperatuur van de dag niet om twaalf uur?",
         opties=["de grond moet eerst opwarmen",
                 "de zon staat dan nog niet hoog",
                 "de lucht is dan nog te droog",
                 "de wind is dan het sterkst"],
         antwoord=0,
         uitleg="De zon staat rond het middaguur het hoogst, maar de grond blijft daarna nog warmte afgeven. De top valt pas in de namiddag."),
    dict(type="meerkeuze",
         vraag="Waarom is een zuidhelling in België warmer dan een noordhelling?",
         opties=["de zon valt er steiler op",
                 "de wind komt er minder bij",
                 "de bodem is er droger",
                 "de bewolking is er dunner"],
         antwoord=0,
         uitleg="Op het noordelijk halfrond staat de zon in het zuiden. Daarom staan wijngaarden in onze streken op zuidhellingen."),
    dict(type="invultekst",
         vraag="Hoe noem je het klimaat ver van de zee, met hete zomers en strenge winters? Eén woord.",
         antwoord=["continentaal", "landklimaat"],
         uitleg="Een continentaal klimaat of landklimaat. Moskou heeft het, en het ligt niet veel noordelijker dan Kopenhagen."),
    dict(type="meerkeuze",
         vraag="Welke factoren maken de jaarschommeling van de temperatuur klein?",
         opties=["dicht bij de zee liggen",
                 "dicht bij de evenaar liggen",
                 "een warme zeestroom langs de kust",
                 "ver in het binnenland liggen"],
         antwoord=[0, 1, 2],
         uitleg="Een eiland op de evenaar heeft de kleinste schommeling van allemaal. Ver in het binnenland krijg je juist hete zomers en strenge winters."),
    dict(type="waarofniet",
         vraag="Op een kaart met isothermen zie je de isothermen in januari bij ons meer noord-zuid lopen dan in juli.",
         antwoord=True,
         uitleg="In de winter beslist de afstand tot de zachte oceaan, en die loopt in West-Europa van west naar oost. In de zomer weegt de breedte zwaarder."),
    dict(type="meerkeuze",
         vraag="Wat is een temperatuurinversie?",
         opties=["koude lucht onder warme lucht",
                 "warme lucht onder koude lucht",
                 "lucht zonder enige waterdamp",
                 "lucht die heel snel opstijgt"],
         antwoord=0,
         uitleg="Normaal is de lucht onderaan het warmst. Bij een inversie ligt koude lucht in een vallei gevangen, met mist en smog als gevolg."),
    dict(type="meerkeuze",
         vraag="Waarom is het in de Sahara 's nachts vaak koud?",
         opties=["er is geen waterdamp in de lucht",
                 "er waait altijd een koude wind",
                 "de bodem is er te hard",
                 "de zon gaat er vroeger onder"],
         antwoord=0,
         uitleg="Waterdamp is het sterkste natuurlijke broeikasgas. In droge lucht ontsnapt de warmte van de dag ongehinderd naar de ruimte."),
    dict(type="waarofniet",
         vraag="De hoogste gemeten temperaturen op aarde liggen op de evenaar.",
         antwoord=False,
         uitleg="Ze liggen in de woestijnen rond de keerkringen, zoals de Sahara en Death Valley. Op de evenaar zorgen de wolken en de regen voor afkoeling."),
    dict(type="meerkeuze",
         vraag="Wat betekent het als de isothermen op een kaart dicht bij elkaar liggen?",
         opties=["de temperatuur verandert snel",
                 "de temperatuur is overal gelijk",
                 "er valt veel neerslag",
                 "de luchtdruk is er hoog"],
         antwoord=0,
         uitleg="Hoe dichter de lijnen, hoe sterker het verschil over korte afstand. Bij isobaren wijst dat op harde wind."),
    dict(type="meerkeuze",
         vraag="Welke stad heeft op dezelfde breedte de zachtste winter?",
         opties=["een kuststad in Ierland",
                 "een stad in het midden van Rusland",
                 "een stad in het binnenland van Canada",
                 "een stad hoog in de bergen van Europa"],
         antwoord=0,
         uitleg="De oceaan en de warme zeestroom houden de winter zacht. Op dezelfde breedte vriest het in Canada en Rusland veel harder."),
]
