# -*- coding: utf-8 -*-
"""De bewegingen van de aarde.

Uit de vakfiche aardrijkskunde van de 3de graad dubbele finaliteit (2027): de
aardrotatie met haar gevolgen (corioliseffect, dagboog, uurgordels, zonnetijd
en conventionele tijd, zomer- en wintertijd, datumgrens, afplatting) en de
aardrevolutie met de hare (dagbogen op 21/3, 21/6, 23/9 en 22/12, de stand van
de aardas, aphelium en perihelium, de zenitale zonnestand, de schrikkeldag en
het verband met de klimaatgordels).

Deel 1 is de rotatie: de aarde om haar as.
Deel 2 is de revolutie: de aarde om de zon, en de seizoenen die eruit volgen.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="In welke zin draait de aarde om haar as?",
         opties=["van west naar oost",
                 "van oost naar west",
                 "van noord naar zuid",
                 "van zuid naar noord"],
         antwoord=0,
         uitleg="Daarom komt de zon in het oosten op. Van boven de Noordpool gezien draait de aarde tegen de klok in."),
    dict(type="meerkeuze",
         vraag="Hoe lang duurt één aardrotatie?",
         opties=["24 uur",
                 "12 uur",
                 "365 dagen",
                 "28 dagen"],
         antwoord=0,
         uitleg="Vierentwintig uur ten opzichte van de zon. Ten opzichte van de sterren is het vier minuten korter."),
    dict(type="invultekst",
         vraag="Hoeveel graden lengte draait de aarde in één uur? Vul het getal in.",
         antwoord=["15", "vijftien"],
         uitleg="Driehonderdzestig graden gedeeld door vierentwintig uur is vijftien graden per uur. Daarom is elke uurgordel vijftien graden breed."),
    dict(type="meerkeuze",
         vraag="Welke gevolgen heeft de aardrotatie?",
         opties=["de afwisseling van dag en nacht",
                 "het afbuigen van de winden",
                 "de afplatting aan de polen",
                 "de afwisseling van de seizoenen"],
         antwoord=[0, 1, 2],
         uitleg="De seizoenen komen van de revolutie en de scheve aardas, niet van de rotatie."),
    dict(type="waarofniet",
         vraag="Door het corioliseffect buigen winden op het noordelijk halfrond naar rechts af.",
         antwoord=True,
         uitleg="Op het zuidelijk halfrond buigen ze naar links. Daardoor draait een depressie bij ons tegen de klok in."),
    dict(type="meerkeuze",
         vraag="Waar is de omtreksnelheid van de aardrotatie het grootst?",
         opties=["op de evenaar",
                 "op de polen",
                 "op de keerkringen",
                 "op de poolcirkels"],
         antwoord=0,
         uitleg="Op de evenaar moet een punt in vierentwintig uur veertigduizend kilometer afleggen, dus bijna 1.700 kilometer per uur. Op de pool is dat nul."),
    dict(type="meerkeuze",
         vraag="Wat is de dagboog?",
         opties=["de weg die de zon aan de hemel aflegt",
                 "de lijn tussen dag en nacht op aarde",
                 "de hoek van de aardas met de baan",
                 "de tijd tussen twee zonsopgangen"],
         antwoord=0,
         uitleg="Een hoge dagboog betekent een lange dag en een hoge zon. Hoe hoog hij staat, hangt af van je breedte en van de datum."),
    dict(type="invultekst",
         vraag="Hoeveel uurgordels heeft de aarde? Vul het getal in.",
         antwoord=["24", "vierentwintig"],
         uitleg="Vierentwintig, elk van vijftien graden. In de praktijk volgen ze de landsgrenzen, en sommige landen wijken een half uur af."),
    dict(type="meerkeuze",
         vraag="Wat is de conventionele tijd?",
         opties=["de tijd van je uurgordel",
                 "de tijd volgens de stand van de zon",
                 "de tijd op de nulmeridiaan",
                 "de tijd die je horloge achterloopt"],
         antwoord=0,
         uitleg="Heel België heeft dezelfde klok, terwijl de zonnetijd in Oostende en in Hasselt een paar minuten verschilt."),
    dict(type="waarofniet",
         vraag="In België loopt de klok in de winter gelijk met de zonnetijd van de nulmeridiaan.",
         antwoord=True,
         uitleg="Onze wintertijd is die van Greenwich plus één uur, en we liggen rond vier graden oost. Dat is bijna de tijd van de meridiaan van vijftien graden."),
    dict(type="meerkeuze",
         vraag="Hoe laat is het in New York als het in Brussel twaalf uur is, in de winter?",
         opties=["zes uur in de ochtend",
                 "zes uur in de avond",
                 "twaalf uur, net als hier",
                 "negen uur in de ochtend"],
         antwoord=0,
         uitleg="New York ligt zes uurgordels naar het westen. Naar het westen trek je af, naar het oosten tel je bij."),
    dict(type="meerkeuze",
         vraag="Waar ligt de datumgrens ongeveer?",
         opties=["op 180 graden lengte",
                 "op de nulmeridiaan",
                 "op de evenaar",
                 "op de poolcirkel"],
         antwoord=0,
         uitleg="Ze volgt grofweg de 180ste meridiaan, met bochten om eilandengroepen heel te houden. Ga je er naar het westen over, dan sla je een dag over."),
    dict(type="invultekst",
         vraag="Hoe noem je het verschijnsel dat winden op aarde afbuigen? Eén woord.",
         antwoord=["corioliseffect", "coriolis"],
         uitleg="Het corioliseffect, naar de Franse wiskundige Coriolis. Het komt van de rotatie van de aarde."),
    dict(type="meerkeuze",
         vraag="Waarom is de aarde aan de polen platter?",
         opties=["door haar snelle rotatie",
                 "door het gewicht van het poolijs",
                 "door de aantrekking van de maan",
                 "door de botsing van de platen"],
         antwoord=0,
         uitleg="De rotatie duwt de massa naar buiten, en dat is op de evenaar het sterkst. De diameter is daar eenenveertig kilometer groter."),
    dict(type="waarofniet",
         vraag="Bij ons zet men de klok in de lente een uur achteruit.",
         antwoord=False,
         uitleg="In de lente gaat de klok een uur vooruit, naar de zomertijd. In het najaar gaat ze weer achteruit."),
    dict(type="meerkeuze",
         vraag="Hoe stellen we vast dat de aarde om haar as draait?",
         opties=["aan de slinger van Foucault",
                 "aan de stand van de poolster",
                 "aan de omloop van de maan",
                 "aan de hoogte van de zon in juni"],
         antwoord=0,
         uitleg="Het slingervlak van Foucault lijkt te draaien, terwijl in werkelijkheid de vloer onder hem meedraait."),
    dict(type="meerkeuze",
         vraag="Wat gebeurt er met de tijd als je naar het oosten reist?",
         opties=["de klok gaat vooruit",
                 "de klok gaat achteruit",
                 "de klok blijft gelijk",
                 "de datum springt een dag terug"],
         antwoord=0,
         uitleg="Het oosten ziet de zon eerder. Daarom is het in Moskou al later op de dag dan bij ons."),
    dict(type="waarofniet",
         vraag="Een depressie draait op het noordelijk halfrond met de klok mee.",
         antwoord=False,
         uitleg="Door het corioliseffect draait ze bij ons tegen de klok in. Een hogedrukgebied draait wel met de klok mee."),
    dict(type="meerkeuze",
         vraag="Welke begrippen horen bij de aardrotatie?",
         opties=["het corioliseffect",
                 "de uurgordels",
                 "de datumgrens",
                 "het perihelium"],
         antwoord=[0, 1, 2],
         uitleg="Het perihelium is het punt van de baan waar de aarde het dichtst bij de zon staat, en dat hoort bij de revolutie."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over de aardrotatie zijn juist?",
         opties=["ze duurt 24 uur",
                 "ze gaat van west naar oost",
                 "ze is het snelst op de evenaar",
                 "ze veroorzaakt de seizoenen"],
         antwoord=[0, 1, 2],
         uitleg="Een punt op de evenaar legt in één etmaal veertigduizend kilometer af, de omtrek van de aarde. De seizoenen komen van de scheve aardas."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is de aardrevolutie?",
         opties=["de omloop om de zon",
                 "de draaiing om de eigen as",
                 "de schommeling van de aardas",
                 "de omloop van de maan om de aarde"],
         antwoord=0,
         uitleg="Eén revolutie duurt 365,25 dagen. De draaiing om de eigen as is de rotatie."),
    dict(type="meerkeuze",
         vraag="Waarom hebben we seizoenen?",
         opties=["de aardas staat scheef",
                 "de aarde staat soms dichter bij de zon",
                 "de zon straalt niet altijd even hard",
                 "de aarde draait soms sneller om haar as"],
         antwoord=0,
         uitleg="De aardas staat 23 graden 27 scheef, en daardoor valt de zon een half jaar schuiner in op het noorden en een half jaar op het zuiden."),
    dict(type="invultekst",
         vraag="Onder welke hoek staat de aardas scheef op het eclipticavlak? Vul het aantal graden in als geheel getal.",
         antwoord=["23", "23,5", "66"],
         uitleg="Drieëntwintig graden zevenentwintig, vaak afgerond op 23,5. Ten opzichte van het vlak zelf is dat 66 graden 33."),
    dict(type="meerkeuze",
         vraag="Welke data noemt de fiche uitdrukkelijk?",
         opties=["21 juni",
                 "22 december",
                 "21 maart",
                 "1 januari"],
         antwoord=[0, 1, 2],
         uitleg="22/12, 21/3, 21/6 en 23/9: de twee zonnewenden en de twee nachteveningen. Nieuwjaar heeft geen astronomische betekenis."),
    dict(type="waarofniet",
         vraag="Op 21 maart en 23 september zijn dag en nacht overal op aarde ongeveer even lang.",
         antwoord=True,
         uitleg="Dat is de equinox of nachtevening. De zon staat dan loodrecht boven de evenaar."),
    dict(type="meerkeuze",
         vraag="Wat gebeurt er op 21 juni op het noordelijk halfrond?",
         opties=["de langste dag",
                 "de kortste dag",
                 "de koudste dag",
                 "de dag met de laagste zon"],
         antwoord=0,
         uitleg="De zomerzonnewende: de zon staat loodrecht boven de Kreeftskeerkring. Op het zuidelijk halfrond is het dan de kortste dag."),
    dict(type="meerkeuze",
         vraag="Wat is de poolnacht?",
         opties=["een etmaal zonder zonsopgang",
                 "een nacht zonder enige wolk",
                 "een nacht met poollicht",
                 "een nacht van zes maanden op de evenaar"],
         antwoord=0,
         uitleg="Binnen de poolcirkel komt de zon in de winter dagen tot maanden niet op. In de zomer gaat ze er niet onder: de middernachtzon."),
    dict(type="invultekst",
         vraag="Hoe noem je het punt van de baan waar de aarde het verst van de zon staat? Eén woord.",
         antwoord=["aphelium", "afelium"],
         uitleg="Het aphelium, begin juli. Het perihelium, het dichtste punt, valt begin januari: onze winter is dus niet de verste stand."),
    dict(type="meerkeuze",
         vraag="Welke begrippen horen bij de revolutie?",
         opties=["de zonnewende",
                 "de nachtevening",
                 "het eclipticavlak",
                 "de uurgordel"],
         antwoord=[0, 1, 2],
         uitleg="De uurgordel hoort bij de rotatie, want die komt van de draaiing om de as."),
    dict(type="waarofniet",
         vraag="De aarde staat in de zomer van het noordelijk halfrond het dichtst bij de zon.",
         antwoord=False,
         uitleg="Juist omgekeerd: begin januari staan we het dichtst bij de zon. De seizoenen komen van de scheve aardas, niet van de afstand."),
    dict(type="meerkeuze",
         vraag="Waarom is er een schrikkeldag?",
         opties=["een jaar duurt 365,25 dagen",
                 "een jaar duurt 364 dagen",
                 "de aarde draait trager in de winter",
                 "de maand februari is te kort"],
         antwoord=0,
         uitleg="Dat kwart dag spaart men vier jaar op, tot één extra dag. Daarom is 29 februari er maar elke vier jaar."),
    dict(type="meerkeuze",
         vraag="Wat betekent het dat de zon in het zenit staat?",
         opties=["ze staat loodrecht boven je",
                 "ze staat in het oosten",
                 "ze staat op haar laagste punt",
                 "ze staat net onder de horizon"],
         antwoord=0,
         uitleg="Dat kan enkel tussen de keerkringen gebeuren. In België komt de zon nooit hoger dan ongeveer drieënzestig graden."),
    dict(type="invultekst",
         vraag="Hoe noem je de hoogste stand van de zon op een dag? Eén woord.",
         antwoord=["culminatie", "culminatiehoogte", "culminatiepunt"],
         uitleg="De culminatie, rond het middaguur van de zonnetijd. De culminatiehoogte hangt af van je breedte en van de datum."),
    dict(type="meerkeuze",
         vraag="Waarom is het aan de evenaar het hele jaar warm?",
         opties=["de zon staat er altijd hoog",
                 "de evenaar ligt dichter bij de zon",
                 "er waait er nooit wind",
                 "de dagen zijn er veel langer"],
         antwoord=0,
         uitleg="De zonnestralen vallen er steil in, en dan verdeelt dezelfde energie zich over een klein oppervlak. De daglengte blijft er het hele jaar twaalf uur."),
    dict(type="waarofniet",
         vraag="Hoe steiler de zonnestralen invallen, hoe meer ze een oppervlak opwarmen.",
         antwoord=True,
         uitleg="Schuine stralen spreiden dezelfde energie over een groter stuk grond. Daarom is het in de polaire klimaten koud."),
    dict(type="meerkeuze",
         vraag="Welke klimaatgordel ligt tussen de keerkring en de poolcirkel?",
         opties=["de gematigde",
                 "de tropische",
                 "de polaire",
                 "de equatoriale"],
         antwoord=0,
         uitleg="Tussen de keerkringen liggen de tropische klimaten, binnen de poolcirkels de polaire, en daartussen de gematigde."),
    dict(type="meerkeuze",
         vraag="Wat is de daglengte op de Noordpool op 22 december?",
         opties=["nul uur",
                 "twaalf uur",
                 "vierentwintig uur",
                 "zes uur"],
         antwoord=0,
         uitleg="Dan is het daar poolnacht: de zon komt helemaal niet op. Op 21 juni is het er vierentwintig uur licht."),
    dict(type="waarofniet",
         vraag="In Hasselt zijn dag en nacht op 21 juni precies even lang.",
         antwoord=False,
         uitleg="Op 21 juni is het bij ons zestien uur licht. Even lang zijn ze op 21 maart en 23 september."),
    dict(type="meerkeuze",
         vraag="Waarom is het op het zuidelijk halfrond zomer als het bij ons winter is?",
         opties=["de aardas helt dan naar de zon toe",
                 "de aarde staat dan verder van de zon",
                 "de zon draait dan onder de evenaar",
                 "de rotatie keert dan van zin om"],
         antwoord=0,
         uitleg="De as blijft het hele jaar in dezelfde richting staan. Daardoor helt het zuiden een half jaar naar de zon toe, en het noorden het andere half jaar."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over de aardrevolutie zijn juist?",
         opties=["ze duurt 365,25 dagen",
                 "de aardas blijft scheef staan",
                 "ze geeft ons de seizoenen",
                 "ze geeft ons dag en nacht"],
         antwoord=[0, 1, 2],
         uitleg="De aarde legt dertig kilometer per seconde af in haar baan. Dag en nacht komen van de rotatie, niet van de revolutie."),
]
