# -*- coding: utf-8 -*-
"""Woordvelden: kunst, geschiedenis, literatuur en de samenleving.

Vier van de zestien woordvelden van de vakfiche Engels van de 3de graad
dubbele finaliteit (2027): kunst, cultuur en geschiedenis; literatuur;
politiek en maatschappij. Niveau ERK A2+.

Deel 1 is kunst, cultuur, geschiedenis en literatuur.
Deel 2 is politiek en de samenleving.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat betekent a painting?",
         opties=["een schilderij",
                 "een beeldhouwwerk",
                 "een tekening",
                 "een foto"],
         antwoord=0,
         uitleg="Van to paint, schilderen. Een beeld is a sculpture en een tekening a drawing."),
    dict(type="meerkeuze",
         vraag="Welke woorden horen bij een museum?",
         opties=["an exhibition",
                 "a gallery",
                 "an entrance fee",
                 "a referee"],
         antwoord=[0, 1, 2],
         uitleg="Een tentoonstelling, een zaal of galerie en de inkomprijs. A referee is een scheidsrechter."),
    dict(type="invultekst",
         vraag="Hoe zeg je eeuw in het Engels? Eén woord.",
         antwoord=["century"],
         uitleg="A century. The nineteenth century is de negentiende eeuw, dus de jaren 1800."),
    dict(type="meerkeuze",
         vraag="Wat betekent a novel?",
         opties=["een roman",
                 "iets heel nieuws",
                 "een kortverhaal",
                 "een gedichtenbundel"],
         antwoord=0,
         uitleg="A novel is een roman; een kortverhaal is a short story. Als bijvoeglijk naamwoord betekent novel wel nieuw of ongewoon."),
    dict(type="waarofniet",
         vraag="An author is in het Engels de schrijver van een boek.",
         antwoord=True,
         uitleg="Author of writer. De schrijver van een toneelstuk heet a playwright."),
    dict(type="meerkeuze",
         vraag="Wat is in het Engels a chapter?",
         opties=["een hoofdstuk",
                 "een bladzijde",
                 "een alinea",
                 "een voorwoord"],
         antwoord=0,
         uitleg="Een boek is in chapters verdeeld. Een bladzijde is a page."),
    dict(type="meerkeuze",
         vraag="Welke woorden horen bij het theater?",
         opties=["a stage",
                 "an audience",
                 "a performance",
                 "a kettle"],
         antwoord=[0, 1, 2],
         uitleg="Het podium, het publiek en de voorstelling. A kettle is een waterkoker."),
    dict(type="invultekst",
         vraag="Hoe zeg je beeldhouwwerk in het Engels? Eén woord.",
         antwoord=["sculpture", "statue"],
         uitleg="A sculpture, of a statue als het een beeld van een persoon is. De kunstenaar is a sculptor."),
    dict(type="meerkeuze",
         vraag="Wat betekent fiction?",
         opties=["verzonnen verhalen",
                 "boeken over de echte wereld",
                 "boeken met tekeningen",
                 "boeken voor de school"],
         antwoord=0,
         uitleg="Fiction is verzonnen, non-fiction gaat over de werkelijkheid. Een bibliotheek verdeelt haar boeken zo."),
    dict(type="waarofniet",
         vraag="A biography is het verhaal van iemands leven.",
         antwoord=True,
         uitleg="Schrijft iemand over zijn eigen leven, dan heet het an autobiography. Bio komt van het Griekse woord voor leven."),
    dict(type="meerkeuze",
         vraag="Wat is in het Engels an heir?",
         opties=["een erfgenaam",
                 "een haarstylist",
                 "een luchtballon",
                 "een eigenaar"],
         antwoord=0,
         uitleg="Let op de uitspraak: de h is stom, je zegt air. De troonopvolger is the heir to the throne."),
    dict(type="meerkeuze",
         vraag="Wat betekent an empire?",
         opties=["een rijk",
                 "een leger",
                 "een opstand",
                 "een verdrag"],
         antwoord=0,
         uitleg="The Roman Empire is het Romeinse Rijk. De keizer is the emperor."),
    dict(type="waarofniet",
         vraag="A rhyme is in het Engels een ritme in de muziek.",
         antwoord=False,
         uitleg="A rhyme is een rijm, zoals in een gedicht of een liedje. Het ritme is the rhythm, met twee h's."),
    dict(type="meerkeuze",
         vraag="Welke woorden horen bij geschiedenis?",
         opties=["a war",
                 "a treaty",
                 "a revolution",
                 "a saucer"],
         antwoord=[0, 1, 2],
         uitleg="Een oorlog, een verdrag en een revolutie. A saucer is een schoteltje onder een tas."),
    dict(type="meerkeuze",
         vraag="Wat betekent ancient?",
         opties=["heel oud",
                 "heel groot",
                 "heel ver",
                 "heel duur"],
         antwoord=0,
         uitleg="Ancient Greece is het oude Griekenland. Modern is modern en recent is recent."),
    dict(type="waarofniet",
         vraag="A conductor is in het Engels een componist.",
         antwoord=False,
         uitleg="A conductor is de dirigent van een orkest, of de conducteur op een trein. Een componist is a composer."),
    dict(type="meerkeuze",
         vraag="Wat is in het Engels a plot in een verhaal, naast de verhaallijn?",
         opties=["een complot",
                 "een hoofdstuk",
                 "een beschrijving",
                 "een personage"],
         antwoord=0,
         uitleg="A plot betekent ook een samenzwering: the plot to kill the king. De verhaallijn en het complot delen hetzelfde woord."),
    dict(type="meerkeuze",
         vraag="Wat betekent to rehearse?",
         opties=["repeteren",
                 "opvoeren",
                 "toejuichen",
                 "nalezen"],
         antwoord=0,
         uitleg="A rehearsal is een repetitie. De voorstelling zelf is the performance."),
    dict(type="invultekst",
         vraag="Hoe zeg je publiek in het Engels, als je de zaal bedoelt? Eén woord.",
         antwoord=["audience", "crowd"],
         uitleg="The audience zit te kijken of te luisteren. A crowd is eerder een menigte op straat."),
    dict(type="meerkeuze",
         vraag="Wat is in het Engels a masterpiece?",
         opties=["een meesterwerk",
                 "een kopie van een werk",
                 "een stuk van een beeld",
                 "een werk van een leerling"],
         antwoord=0,
         uitleg="Letterlijk samengesteld uit master en piece, net als bij ons. Een kopie is a copy of a replica."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat betekent an election?",
         opties=["een verkiezing",
                 "een vergadering",
                 "een wetsvoorstel",
                 "een betoging"],
         antwoord=0,
         uitleg="To elect is verkiezen. Je stem heet your vote, en stemmen is to vote."),
    dict(type="meerkeuze",
         vraag="Welke woorden horen bij de politiek?",
         opties=["a party",
                 "a minister",
                 "parliament",
                 "a bargain"],
         antwoord=[0, 1, 2],
         uitleg="Een partij, een minister en het parlement. A bargain is een koopje en hoort bij geld. Let op: a party is ook een feest."),
    dict(type="invultekst",
         vraag="Hoe zeg je wet in het Engels? Eén woord.",
         antwoord=["law", "act"],
         uitleg="A law. Een wet die het parlement goedkeurt heet ook an act."),
    dict(type="meerkeuze",
         vraag="Wat is in het Engels a citizen?",
         opties=["een burger",
                 "een inwoner van een stad",
                 "iemand uit het buitenland",
                 "iemand zonder papieren"],
         antwoord=0,
         uitleg="A Belgian citizen is een Belgische staatsburger. Citizenship is de nationaliteit."),
    dict(type="waarofniet",
         vraag="The Prime Minister is in het Verenigd Koninkrijk de regeringsleider.",
         antwoord=True,
         uitleg="De koning of koningin is het staatshoofd, de premier leidt de regering. In de VS is de president allebei."),
    dict(type="meerkeuze",
         vraag="Wat betekent to protest?",
         opties=["betogen",
                 "stemmen",
                 "vergaderen",
                 "beslissen"],
         antwoord=0,
         uitleg="A protest of a demonstration is een betoging. Een staking is a strike."),
    dict(type="meerkeuze",
         vraag="Welke woorden gaan over de samenleving?",
         opties=["poverty",
                 "equality",
                 "charity",
                 "a receipt"],
         antwoord=[0, 1, 2],
         uitleg="Armoede, gelijkheid en een goed doel. A receipt is een kassabon."),
    dict(type="invultekst",
         vraag="Hoe zeg je belasting in het Engels? Eén woord.",
         antwoord=["tax", "taxes"],
         uitleg="Tax, in het meervoud taxes. Income tax is de belasting op je inkomen."),
    dict(type="meerkeuze",
         vraag="Wat betekent a refugee?",
         opties=["een vluchteling",
                 "een toerist",
                 "een reiziger",
                 "een werknemer"],
         antwoord=0,
         uitleg="Van to take refuge, zijn toevlucht zoeken. Asiel aanvragen is to apply for asylum."),
    dict(type="waarofniet",
         vraag="A council is in het Engels een gemeenteraad.",
         antwoord=True,
         uitleg="The city council beslist over de stad. Council housing zijn de sociale woningen."),
    dict(type="meerkeuze",
         vraag="Wat is in het Engels a charity?",
         opties=["een goed doel",
                 "een bank",
                 "een verzekering",
                 "een ziekenhuis"],
         antwoord=0,
         uitleg="Een organisatie die geld inzamelt om te helpen. A charity shop verkoopt tweedehands spullen voor dat doel."),
    dict(type="meerkeuze",
         vraag="Wat betekent to volunteer?",
         opties=["vrijwillig helpen",
                 "zich inschrijven",
                 "zich verzekeren",
                 "zich verdedigen"],
         antwoord=0,
         uitleg="A volunteer is een vrijwilliger. Voluntary work is vrijwilligerswerk."),
    dict(type="waarofniet",
         vraag="A trade union is in het Engels een handelsbeurs.",
         antwoord=False,
         uitleg="Een trade union is een vakbond. Een handelsbeurs is a trade fair."),
    dict(type="meerkeuze",
         vraag="Welke woorden horen bij het recht?",
         opties=["a judge",
                 "a court",
                 "a lawyer",
                 "a landlord"],
         antwoord=[0, 1, 2],
         uitleg="Een rechter, een rechtbank en een advocaat. A landlord verhuurt een huis."),
    dict(type="meerkeuze",
         vraag="Wat betekent discrimination?",
         opties=["ongelijke behandeling",
                 "een duidelijk verschil",
                 "een goede keuze",
                 "een eerlijke verdeling"],
         antwoord=0,
         uitleg="Iemand slechter behandelen om wie hij is. Het Engelse to discriminate kan ook neutraal onderscheiden betekenen, maar niet in dit woordveld."),
    dict(type="waarofniet",
         vraag="A majority betekent in het Engels een minderheid.",
         antwoord=False,
         uitleg="A majority is de meerderheid, a minority de minderheid. Major betekent groot of belangrijk."),
    dict(type="meerkeuze",
         vraag="Wat is in het Engels the media?",
         opties=["de pers en de omroepen",
                 "de scholen van een land",
                 "de partijen in een parlement",
                 "de winkels van een stad"],
         antwoord=0,
         uitleg="Kranten, radio, televisie en het internet. Het woord is een meervoud: the media are, één kanaal is a medium."),
    dict(type="meerkeuze",
         vraag="Wat betekent a survey?",
         opties=["een enquête",
                 "een verkiezing",
                 "een vergadering",
                 "een wet"],
         antwoord=0,
         uitleg="Mensen vragen wat ze denken. Een opiniepeiling is a poll."),
    dict(type="meerkeuze",
         vraag="Wat is in het Engels a border control?",
         opties=["een grenscontrole",
                 "een controle op school",
                 "een controle bij de dokter",
                 "een controle van de rekening"],
         antwoord=0,
         uitleg="Aan de grens worden je papieren nagekeken. Border is de grens tussen twee landen."),
    dict(type="meerkeuze",
         vraag="Wat betekent human rights?",
         opties=["de mensenrechten",
                 "de rechten van een land",
                 "de rechten van een firma",
                 "de rechten van een school"],
         antwoord=0,
         uitleg="De rechten die elke mens heeft. The Universal Declaration of Human Rights is van 1948."),
]
