# -*- coding: utf-8 -*-
"""Woordvelden: wetenschap, techniek, sport en taalbeschouwing.

De laatste van de zestien woordvelden van de vakfiche Engels van de 3de graad
dubbele finaliteit (2027): wetenschap, informatica en technologie; sport en
vrije tijd; taal en taalbeschouwing. Niveau ERK A2+.

Deel 1 is wetenschap, informatica en techniek, met sport en vrije tijd.
Deel 2 is taal en taalbeschouwing: woordvorming, valse vrienden en het
verschil tussen het Brits en het Amerikaans.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat betekent research?",
         opties=["onderzoek",
                 "een uitvinding",
                 "een proefopstelling",
                 "een verslag"],
         antwoord=0,
         uitleg="Research is ontelbaar: a lot of research, nooit researches. Een onderzoeker is a researcher."),
    dict(type="meerkeuze",
         vraag="Welke woorden horen bij een computer?",
         opties=["a keyboard",
                 "a screen",
                 "a file",
                 "a shelf"],
         antwoord=[0, 1, 2],
         uitleg="Een toetsenbord, een scherm en een bestand. A shelf is een rek in de kast."),
    dict(type="invultekst",
         vraag="Hoe zeg je uitvinding in het Engels? Eén woord.",
         antwoord=["invention"],
         uitleg="An invention, van to invent. De uitvinder is the inventor."),
    dict(type="meerkeuze",
         vraag="Wat is in het Engels a device?",
         opties=["een toestel",
                 "een programma",
                 "een advies",
                 "een verdeling"],
         antwoord=0,
         uitleg="Een gsm, een tablet of een laptop is a device. Advies is advice, met een c."),
    dict(type="waarofniet",
         vraag="To download en to upload zijn in het Engels het omgekeerde van elkaar.",
         antwoord=True,
         uitleg="Down is naar je toestel toe, up is ervan weg naar het internet. Allebei gewoon overgenomen in het Nederlands."),
    dict(type="meerkeuze",
         vraag="Wat betekent a password?",
         opties=["een wachtwoord",
                 "een gebruikersnaam",
                 "een mailadres",
                 "een bijlage"],
         antwoord=0,
         uitleg="Letterlijk samengesteld, net als bij ons. De gebruikersnaam is your username."),
    dict(type="meerkeuze",
         vraag="Welke woorden horen bij sport?",
         opties=["a pitch",
                 "a referee",
                 "a draw",
                 "a tenant"],
         antwoord=[0, 1, 2],
         uitleg="Een speelveld, een scheidsrechter en een gelijkspel. A tenant is een huurder."),
    dict(type="invultekst",
         vraag="Hoe zeg je wedstrijd in het Engels, als je een voetbalmatch bedoelt? Eén woord.",
         antwoord=["match", "game"],
         uitleg="A match, of a game in het Amerikaans. Een toernooi is a tournament."),
    dict(type="meerkeuze",
         vraag="Wat betekent to score a goal?",
         opties=["een doelpunt maken",
                 "een doel verdedigen",
                 "een doel verplaatsen",
                 "een doel afkeuren"],
         antwoord=0,
         uitleg="To score is scoren, a goal is een doel of een doelpunt. De doelman is the goalkeeper."),
    dict(type="waarofniet",
         vraag="A draw betekent in het voetbal een gelijkspel.",
         antwoord=True,
         uitleg="It was a draw: het was gelijk. To draw betekent ook tekenen, dus kijk naar de zin eromheen."),
    dict(type="meerkeuze",
         vraag="Wat is in het Engels a laboratory?",
         opties=["een labo",
                 "een werkplaats",
                 "een bibliotheek",
                 "een fabriek"],
         antwoord=0,
         uitleg="Afgekort a lab. Een bibliotheek is a library, een bekende valse vriend met laboratorium."),
    dict(type="meerkeuze",
         vraag="Wat betekent an experiment?",
         opties=["een proef",
                 "een ervaring",
                 "een voorbeeld",
                 "een bewijs"],
         antwoord=0,
         uitleg="To carry out an experiment is een proef uitvoeren. Een ervaring is experience."),
    dict(type="waarofniet",
         vraag="A battery betekent in het Engels een lader voor je gsm.",
         antwoord=False,
         uitleg="A battery is de batterij of de accu zelf; de lader is the charger. Mijn gsm is leeg wordt my battery is dead."),
    dict(type="meerkeuze",
         vraag="Welke woorden horen bij vrije tijd?",
         opties=["a board game",
                 "a jigsaw",
                 "a hike",
                 "a plaster"],
         antwoord=[0, 1, 2],
         uitleg="Een gezelschapsspel, een puzzel en een wandeltocht. A plaster is een pleister."),
    dict(type="meerkeuze",
         vraag="Wat betekent a screenshot?",
         opties=["een beeld van je scherm",
                 "een barst in je scherm",
                 "een film op je scherm",
                 "een foto met je gsm"],
         antwoord=0,
         uitleg="To take a screenshot is een schermafbeelding maken. Shot betekent hier opname."),
    dict(type="waarofniet",
         vraag="A spreadsheet is in het Engels een laken voor een bed.",
         antwoord=False,
         uitleg="Een spreadsheet is een rekenblad op de computer. Een laken is a sheet, maar dan a bed sheet."),
    dict(type="meerkeuze",
         vraag="Wat is in het Engels a gadget?",
         opties=["een handig toestelletje",
                 "een groot werktuig",
                 "een stuk gereedschap",
                 "een onderdeel van een motor"],
         antwoord=0,
         uitleg="Klein, slim en meestal elektronisch. Gereedschap is tools, en één stuk is a tool."),
    dict(type="meerkeuze",
         vraag="Wat betekent to charge a phone?",
         opties=["een gsm opladen",
                 "een gsm herstellen",
                 "een gsm kopen",
                 "een gsm opbellen"],
         antwoord=0,
         uitleg="The charger is de lader. To charge betekent ook aanrekenen: they charge five pounds."),
    dict(type="invultekst",
         vraag="Hoe zeg je schaakspel in het Engels? Eén woord.",
         antwoord=["chess"],
         uitleg="Chess, altijd zonder lidwoord: to play chess. Dammen is draughts, in de VS checkers."),
    dict(type="meerkeuze",
         vraag="Wat is in het Engels a vaccine?",
         opties=["een vaccin",
                 "een pleister",
                 "een pijnstiller",
                 "een hoestsiroop"],
         antwoord=0,
         uitleg="To vaccinate is inenten. Let op de uitspraak: de laatste lettergreep klinkt als -seen."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat betekent het voorvoegsel un- in unhealthy?",
         opties=["niet",
                 "heel erg",
                 "opnieuw",
                 "vooraf"],
         antwoord=0,
         uitleg="Un- maakt een woord ontkennend: happy wordt unhappy, healthy wordt unhealthy. Opnieuw is re-, zoals in to rewrite."),
    dict(type="meerkeuze",
         vraag="Welke woorden beginnen met een ontkennend voorvoegsel?",
         opties=["impossible",
                 "disagree",
                 "unfair",
                 "rebuild"],
         antwoord=[0, 1, 2],
         uitleg="Im-, dis- en un- maken het omgekeerde. Re- betekent opnieuw, dus rebuild is heropbouwen."),
    dict(type="invultekst",
         vraag="Welk achtervoegsel maakt van slow het bijwoord slowly? Vul het achtervoegsel in.",
         antwoord=["-ly", "ly"],
         uitleg="Het achtervoegsel -ly maakt van een bijvoeglijk naamwoord een bijwoord: luckily, happily, carefully."),
    dict(type="meerkeuze",
         vraag="Wat betekent het Engelse woord eventually?",
         opties=["uiteindelijk",
                 "eventueel",
                 "misschien",
                 "af en toe"],
         antwoord=0,
         uitleg="Een bekende valse vriend. Eventueel is possibly of if necessary."),
    dict(type="waarofniet",
         vraag="Het Engelse actually betekent eigenlijk, niet actueel.",
         antwoord=True,
         uitleg="Actually is in werkelijkheid of eigenlijk. Actueel is current of topical."),
    dict(type="meerkeuze",
         vraag="Wat betekent to control in het Engels?",
         opties=["besturen",
                 "nakijken",
                 "verbeteren",
                 "afrekenen"],
         antwoord=0,
         uitleg="Nog een valse vriend: to control is beheersen of besturen. Nakijken is to check."),
    dict(type="meerkeuze",
         vraag="Welke woordparen worden vaak verward?",
         opties=["its en it's",
                 "their en there",
                 "your en you're",
                 "big en small"],
         antwoord=[0, 1, 2],
         uitleg="Ze klinken gelijk maar betekenen iets anders. Its is bezittelijk, it's is it is."),
    dict(type="invultekst",
         vraag="Welke vorm schrijf je in deze zin: The dog wagged ... tail. Vul het woord in.",
         antwoord=["its"],
         uitleg="Its zonder apostrof is bezittelijk. It's met apostrof betekent it is of it has."),
    dict(type="meerkeuze",
         vraag="Wat is het Amerikaanse woord voor het Britse autumn?",
         opties=["fall",
                 "spring",
                 "summer",
                 "season"],
         antwoord=0,
         uitleg="In de VS zeggen ze fall, naar de vallende bladeren. Autumn wordt daar wel begrepen."),
    dict(type="waarofniet",
         vraag="Colour en color zijn allebei juist, maar in een andere variant van het Engels.",
         antwoord=True,
         uitleg="Colour is Brits, color Amerikaans. Zo ook favourite en favorite, centre en center."),
    dict(type="meerkeuze",
         vraag="Wat betekent het achtervoegsel -less in careless?",
         opties=["zonder",
                 "vol van",
                 "opnieuw",
                 "heel erg"],
         antwoord=0,
         uitleg="Careless is zonder zorg, dus onzorgvuldig. Careful met -ful is net het omgekeerde."),
    dict(type="meerkeuze",
         vraag="Wat betekent sympathetic in het Engels?",
         opties=["meelevend",
                 "sympathiek",
                 "vrolijk",
                 "verlegen"],
         antwoord=0,
         uitleg="Nog een valse vriend: sympathetic is begripvol of meelevend. Sympathiek is nice of likeable."),
    dict(type="waarofniet",
         vraag="Het Amerikaanse woord voor een lift is a lorry.",
         antwoord=False,
         uitleg="In de VS zeggen ze an elevator; a lorry is het Britse woord voor een vrachtwagen, in de VS a truck."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn samenstellingen?",
         opties=["homework",
                 "football",
                 "sunglasses",
                 "quickly"],
         antwoord=[0, 1, 2],
         uitleg="Twee woorden samen tot één nieuw woord. Quickly is een afleiding met het achtervoegsel -ly."),
    dict(type="meerkeuze",
         vraag="Wat betekent to make sense?",
         opties=["logisch zijn",
                 "iets voelen",
                 "iets ruiken",
                 "iets uitvinden"],
         antwoord=0,
         uitleg="That makes sense: dat klopt, dat is logisch. Een vaste uitdrukking met make."),
    dict(type="waarofniet",
         vraag="Het Engelse library betekent boekhandel.",
         antwoord=False,
         uitleg="A library is een bibliotheek; een boekhandel is a bookshop of a bookstore. Een klassieke valse vriend."),
    dict(type="meerkeuze",
         vraag="Wat is het Britse woord voor het Amerikaanse cookie?",
         opties=["a biscuit",
                 "a cake",
                 "a pie",
                 "a bun"],
         antwoord=0,
         uitleg="A biscuit is Brits voor een koekje. In de VS is a biscuit juist een soort zacht broodje."),
    dict(type="meerkeuze",
         vraag="Wat betekent het achtervoegsel -ful in helpful?",
         opties=["vol van",
                 "zonder",
                 "half",
                 "tegen"],
         antwoord=0,
         uitleg="Helpful is behulpzaam, useful is nuttig. Met -less wordt het net het omgekeerde: useless."),
    dict(type="meerkeuze",
         vraag="Wat betekent to realise in het Engels?",
         opties=["beseffen",
                 "verwezenlijken",
                 "ontdekken",
                 "voorspellen"],
         antwoord=0,
         uitleg="I didn't realise: ik besefte het niet. Realiseren in de zin van uitvoeren is to carry out of to achieve."),
    dict(type="meerkeuze",
         vraag="Wat is in het Engels a synonym?",
         opties=["een woord met dezelfde betekenis",
                 "een woord met het omgekeerde",
                 "een woord uit een andere taal",
                 "een woord dat niet bestaat"],
         antwoord=0,
         uitleg="Big en large zijn synoniemen. Het omgekeerde heet an antonym."),
]
