# -*- coding: utf-8 -*-
"""Zinsbouw, zinsdelen en de voorwaardelijke bijzin.

Uit de grammaticalijst van de vakfiche Engels van de 3de graad dubbele
finaliteit (2027): de bouw van enkelvoudige en samengestelde zinnen met
nevenschikking en onderschikking, de frequente voegwoorden en de soorten
zinnen, bevestigend, ontkennend, vragend, bevelend en uitroepend (deel 1), en
de zinsdelen met de congruentie tussen onderwerp en persoonsvorm, plus de
voorwaardelijke bijzinnen zero en first (deel 2). Niveau ERK A2+.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is de gewone woordorde van een Engelse mededelende zin?",
         opties=["onderwerp, werkwoord, rest",
                 "werkwoord, onderwerp, rest",
                 "rest, werkwoord, onderwerp",
                 "onderwerp, rest, werkwoord"],
         antwoord=0,
         uitleg="She reads a book every evening. Het Engels houdt het onderwerp en de persoonsvorm veel strakker bij elkaar dan het Nederlands."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn nevenschikkende voegwoorden?",
         opties=["and",
                 "but",
                 "so",
                 "because"],
         antwoord=[0, 1, 2],
         uitleg="Ze verbinden twee gelijkwaardige delen. Because is onderschikkend: het maakt een bijzin."),
    dict(type="invultekst",
         vraag="Welk voegwoord geeft een reden en begint met b? Eén woord.",
         antwoord=["because"],
         uitleg="Because plus een hele zin: because it was raining. Because of plus een naamwoord: because of the rain."),
    dict(type="meerkeuze",
         vraag="Welke zin is een uitroepende zin?",
         opties=["What a lovely day!",
                 "It is a lovely day.",
                 "Is it a lovely day?",
                 "Have a lovely day."],
         antwoord=0,
         uitleg="De fiche noemt de uitroepende zin apart. What a of How begint er een: How beautiful!"),
    dict(type="waarofniet",
         vraag="Een bevelende zin in het Engels heeft geen onderwerp.",
         antwoord=True,
         uitleg="Open the window. Je spreekt de persoon rechtstreeks aan, dus you blijft weg."),
    dict(type="meerkeuze",
         vraag="Wat is onderschikking in een zin?",
         opties=["een bijzin bij een hoofdzin",
                 "twee hoofdzinnen naast elkaar",
                 "twee werkwoorden na elkaar",
                 "twee onderwerpen in één zin"],
         antwoord=0,
         uitleg="I stayed home because I was ill: de tweede helft kan niet alleen staan. Bij nevenschikking kan dat wel."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn onderschikkende voegwoorden?",
         opties=["although",
                 "while",
                 "if",
                 "and"],
         antwoord=[0, 1, 2],
         uitleg="Ze beginnen een bijzin die niet alleen kan staan. And verbindt twee gelijkwaardige delen."),
    dict(type="invultekst",
         vraag="Welk voegwoord kondigt een tegenstelling aan en betekent nochtans of echter, met zeven letters?",
         antwoord=["however"],
         uitleg="However staat vaak vooraan met een komma erachter: However, we went anyway. But staat tussen de twee delen."),
    dict(type="meerkeuze",
         vraag="Welke zin is een ontkennende zin?",
         opties=["I don't like coffee.",
                 "I like coffee.",
                 "Do you like coffee?",
                 "Drink your coffee."],
         antwoord=0,
         uitleg="Don't maakt de zin ontkennend. De vier soorten zinnen van de fiche staan hier naast elkaar."),
    dict(type="waarofniet",
         vraag="Je mag in het Engels twee ontkenningen in één zin zetten.",
         antwoord=False,
         uitleg="I don't know nothing is fout; het moet I don't know anything zijn. In liedjes hoor je het wel, maar niet op een examen."),
    dict(type="meerkeuze",
         vraag="Welke zin is juist samengesteld?",
         opties=["It rained, so we stayed in.",
                 "It rained, so stayed we in.",
                 "It rained, we stayed so in.",
                 "So it rained, stayed we in."],
         antwoord=0,
         uitleg="Na so blijft de gewone orde: onderwerp, werkwoord. In het Nederlands zou het werkwoord naar voren schuiven."),
    dict(type="meerkeuze",
         vraag="Welke vorm past: ... the door, please.",
         opties=["Close",
                 "Closes",
                 "Closing",
                 "To close"],
         antwoord=0,
         uitleg="Een bevel gebruikt de infinitief zonder to en zonder onderwerp. Please maakt het vriendelijker."),
    dict(type="waarofniet",
         vraag="Yet kan in het Engels geen voegwoord zijn.",
         antwoord=False,
         uitleg="Yet kondigt juist een tegenstelling aan: he was tired, yet he kept walking. De fiche noemt het naast but, and, however en so."),
    dict(type="meerkeuze",
         vraag="Welke zin is een vragende zin?",
         opties=["Did she call you?",
                 "She called you.",
                 "Call her back.",
                 "She didn't call."],
         antwoord=0,
         uitleg="Did komt vooraan, en daarna de gewone orde. Een vraagteken alleen maakt van een mededeling nog geen correcte vraag."),
    dict(type="meerkeuze",
         vraag="Welke vorm past: He is tired, ... he will finish the work.",
         opties=["but",
                 "and so",
                 "because",
                 "while"],
         antwoord=0,
         uitleg="De twee helften staan tegenover elkaar, dus but. Because zou een reden geven en dat past hier niet."),
    dict(type="waarofniet",
         vraag="In het Engels staat de persoonsvorm in een bijzin op dezelfde plaats als in een hoofdzin.",
         antwoord=True,
         uitleg="I know that she lives here, niet that she here lives. Dat is anders dan in het Nederlands, waar het werkwoord naar achteren gaat."),
    dict(type="meerkeuze",
         vraag="Welke zin drukt een gevolg uit?",
         opties=["It was late, so we left.",
                 "It was late, but we left.",
                 "It was late because we left.",
                 "It was late while we left."],
         antwoord=0,
         uitleg="So kondigt het gevolg aan. Because zou de reden geven, en de laatste twee kloppen niet in betekenis."),
    dict(type="meerkeuze",
         vraag="Waar kan een bijwoord van tijd in een Engelse zin staan?",
         opties=["achteraan",
                 "vooraan, met een komma",
                 "voor het onderwerp",
                 "tussen werkwoord en lijdend voorwerp"],
         antwoord=[0, 1, 2],
         uitleg="I saw her yesterday, of Yesterday, I saw her. Tussen het werkwoord en het lijdend voorwerp mag het niet: I saw yesterday her is fout."),
    dict(type="invultekst",
         vraag="Welk voegwoord gebruik je voor een voorwaarde, met twee letters?",
         antwoord=["if"],
         uitleg="If it rains, we stay home. Unless betekent het omgekeerde: tenzij."),
    dict(type="meerkeuze",
         vraag="Welke zin is bevestigend?",
         opties=["The shop is open.",
                 "Is the shop open?",
                 "The shop isn't open.",
                 "Open the shop."],
         antwoord=0,
         uitleg="Een bevestigende of mededelende zin stelt iets vast. De drie andere zijn vragend, ontkennend en bevelend."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is het onderwerp in de zin My little sister plays the violin?",
         opties=["my little sister",
                 "plays",
                 "the violin",
                 "the violin plays"],
         antwoord=0,
         uitleg="Het onderwerp doet wat de persoonsvorm zegt. Je vindt het door te vragen: wie speelt?"),
    dict(type="meerkeuze",
         vraag="Welke zinsdelen noemt de fiche?",
         opties=["het onderwerp",
                 "de persoonsvorm",
                 "het lijdend voorwerp",
                 "het bijvoeglijk naamwoord"],
         antwoord=[0, 1, 2],
         uitleg="Onderwerp, persoonsvorm, lijdend voorwerp en meewerkend voorwerp. Een bijvoeglijk naamwoord is een woordsoort, geen zinsdeel."),
    dict(type="invultekst",
         vraag="Hoe noem je het zinsdeel dat de handeling ondergaat, met twee woorden beginnend met lijdend?",
         antwoord=["lijdend voorwerp"],
         uitleg="Het lijdend voorwerp, in het Engels the direct object. In I read a book is a book het lijdend voorwerp."),
    dict(type="meerkeuze",
         vraag="Wat is het meewerkend voorwerp in She gave her brother a present?",
         opties=["her brother",
                 "a present",
                 "she",
                 "gave"],
         antwoord=0,
         uitleg="Het cadeau is het lijdend voorwerp, de broer de ontvanger. Je kan het ook schrijven als: she gave a present to her brother."),
    dict(type="waarofniet",
         vraag="Congruentie betekent dat het werkwoord bij het onderwerp past.",
         antwoord=True,
         uitleg="She works, they work. De fiche noemt het congruentie tussen onderwerp en persoonsvorm."),
    dict(type="meerkeuze",
         vraag="Welke zin heeft de juiste congruentie?",
         opties=["My friends live nearby.",
                 "My friends lives nearby.",
                 "My friend live nearby.",
                 "My friends living nearby."],
         antwoord=0,
         uitleg="Friends is meervoud, dus live zonder s. Bij één friend zou het lives zijn."),
    dict(type="meerkeuze",
         vraag="Welke zinnen hebben de juiste congruentie?",
         opties=["Everybody is here.",
                 "The news is good.",
                 "The people are waiting.",
                 "My parents is at home."],
         antwoord=[0, 1, 2],
         uitleg="Everybody en news zijn enkelvoud, people is meervoud. De laatste moet my parents are zijn."),
    dict(type="invultekst",
         vraag="Vul in: The team ... playing well this season. Eén woord.",
         antwoord=["is", "are"],
         uitleg="In het Brits mag team allebei: the team is of the team are. In het Amerikaans blijft het is."),
    dict(type="meerkeuze",
         vraag="Hoe vorm je een zero conditional?",
         opties=["if plus present, present",
                 "if plus present, will",
                 "if plus will, present",
                 "if plus past, would"],
         antwoord=0,
         uitleg="If you heat water, it boils. Een zero conditional geldt altijd: het is een vaste regel."),
    dict(type="waarofniet",
         vraag="In een first conditional staat will achter if.",
         antwoord=False,
         uitleg="Na if komt de present simple: if it rains, we will stay home. Will staat in de andere helft van de zin."),
    dict(type="meerkeuze",
         vraag="Welke zin is een first conditional?",
         opties=["If I see her, I will tell her.",
                 "If I will see her, I tell her.",
                 "If I saw her, I would tell her.",
                 "If I see her, I told her."],
         antwoord=0,
         uitleg="Na if een present simple, daarna will. De derde zin is een second conditional, en die staat niet in deze fiche."),
    dict(type="meerkeuze",
         vraag="Welke zin is een zero conditional?",
         opties=["If you press this, the light goes on.",
                 "If you press this, the light will go.",
                 "If you pressed this, the light went.",
                 "If you will press this, the light goes."],
         antwoord=0,
         uitleg="Twee keer een present simple, want het gebeurt altijd zo. Dat is het verschil met de first conditional."),
    dict(type="waarofniet",
         vraag="Een voorwaardelijke bijzin kan vooraan of achteraan de zin staan.",
         antwoord=True,
         uitleg="If it rains, we stay home of we stay home if it rains. Staat ze vooraan, dan komt er een komma achter."),
    dict(type="meerkeuze",
         vraag="Welke vorm past: If you ... hard, you will pass.",
         opties=["work",
                 "will work",
                 "worked",
                 "would work"],
         antwoord=0,
         uitleg="Na if een present simple, ook al gaat de zin over de toekomst. Will staat in de tweede helft."),
    dict(type="meerkeuze",
         vraag="Wat is de persoonsvorm in The children were playing outside?",
         opties=["were",
                 "playing",
                 "the children",
                 "outside"],
         antwoord=0,
         uitleg="De persoonsvorm is het werkwoord dat met het onderwerp meebuigt: were bij een meervoud. Playing is het deelwoord."),
    dict(type="waarofniet",
         vraag="Na unless zet je in het Engels nog een ontkenning.",
         antwoord=False,
         uitleg="Unless betekent zelf al tenzij: we will go unless it rains. Unless it doesn't rain zou het omgekeerde zeggen van wat je bedoelt."),
    dict(type="meerkeuze",
         vraag="Welke zin heeft het lijdend voorwerp op de juiste plaats?",
         opties=["I bought a book yesterday.",
                 "I bought yesterday a book.",
                 "Yesterday bought I a book.",
                 "A book I bought yesterday."],
         antwoord=0,
         uitleg="Het lijdend voorwerp volgt het werkwoord onmiddellijk. Een tijdsbepaling schuift erna, niet ertussen."),
    dict(type="meerkeuze",
         vraag="Welke woorden kunnen een voorwaarde inleiden?",
         opties=["if",
                 "unless",
                 "as long as",
                 "however"],
         antwoord=[0, 1, 2],
         uitleg="Als, tenzij en zolang. However kondigt een tegenstelling aan en geen voorwaarde."),
    dict(type="invultekst",
         vraag="Vul in: If the weather ... nice tomorrow, we will cycle. Gebruik to be. Eén woord.",
         antwoord=["is"],
         uitleg="Na if een present simple: if the weather is nice. Will be zou fout zijn in het if-deel."),
    dict(type="meerkeuze",
         vraag="Welke zin heeft de juiste orde met een bijzin?",
         opties=["She said that she was tired.",
                 "She said that she tired was.",
                 "She said that was she tired.",
                 "She said she tired was."],
         antwoord=0,
         uitleg="In een Engelse bijzin blijft de orde onderwerp, werkwoord, rest. In het Nederlands schuift het werkwoord naar achteren, en dat is de klassieke valkuil."),
]
