# -*- coding: utf-8 -*-
"""De verleden tijden.

Uit de grammaticalijst van de vakfiche Engels van de 3de graad dubbele
finaliteit (2027): de past simple van regelmatige en frequente onregelmatige
werkwoorden (deel 1) en de past continuous, met het samenspel van de twee
(deel 2). De past perfect staat niet in deze fiche, dus die zit er ook niet
in. Niveau ERK A2+.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is de past simple van to work?",
         opties=["worked",
                 "worket",
                 "workd",
                 "was working"],
         antwoord=0,
         uitleg="Een regelmatig werkwoord krijgt -ed. Je hoort er soms een t in, maar je schrijft altijd -ed."),
    dict(type="meerkeuze",
         vraag="Welke past simples zijn onregelmatig?",
         opties=["went",
                 "bought",
                 "took",
                 "played"],
         antwoord=[0, 1, 2],
         uitleg="Go, buy en take gaan hun eigen weg. Play volgt de regel: played."),
    dict(type="invultekst",
         vraag="Wat is de past simple van to read? Eén woord.",
         antwoord=["read"],
         uitleg="Read blijft read in de spelling, maar je spreekt het uit als red. Readed bestaat niet."),
    dict(type="meerkeuze",
         vraag="Welke spelling is juist in de past simple?",
         opties=["stopped",
                 "stoped",
                 "stopt",
                 "stoppd"],
         antwoord=0,
         uitleg="Een korte klinker voor één consonant verdubbelt die consonant: stop wordt stopped, plan wordt planned."),
    dict(type="waarofniet",
         vraag="De past simple van to be heeft twee vormen: was en were.",
         antwoord=True,
         uitleg="I was, he was, maar you were, we were, they were. Dat is het enige werkwoord met twee vormen in de past simple."),
    dict(type="meerkeuze",
         vraag="Hoe maak je de ontkenning van She went home?",
         opties=["She did not go home",
                 "She did not went home",
                 "She not went home",
                 "She goed not home"],
         antwoord=0,
         uitleg="Did neemt de verleden tijd over, en het hoofdwerkwoord gaat terug naar de infinitief. Verkort: she didn't go."),
    dict(type="meerkeuze",
         vraag="Welke vraag in de past simple is juist?",
         opties=["Did you see the film?",
                 "Did you saw the film?",
                 "Saw you the film?",
                 "Do you saw the film?"],
         antwoord=0,
         uitleg="Did staat vooraan en het hoofdwerkwoord blijft in de infinitief. Een dubbele verleden tijd is altijd fout."),
    dict(type="invultekst",
         vraag="Wat is de past simple van to buy? Eén woord.",
         antwoord=["bought"],
         uitleg="Buy, bought, bought. Let op de gh die je niet uitspreekt: je hoort bot."),
    dict(type="meerkeuze",
         vraag="Welke vorm past: We ... to Paris last summer.",
         opties=["went",
                 "have gone",
                 "go",
                 "are going"],
         antwoord=0,
         uitleg="Last summer is afgesloten, dus de past simple. Een present perfect kan niet bij een afgesloten tijd."),
    dict(type="waarofniet",
         vraag="De past simple van to think is thinked.",
         antwoord=False,
         uitleg="Think, thought, thought. De rijtjes van de onregelmatige werkwoorden moet je gewoon kennen."),
    dict(type="meerkeuze",
         vraag="Welke past simples zijn juist gespeld?",
         opties=["studied",
                 "carried",
                 "played",
                 "stoped"],
         antwoord=[0, 1, 2],
         uitleg="Een y na een consonant wordt ied: studied, carried. Na een klinker blijft hij: played. Stop verdubbelt zijn p: stopped."),
    dict(type="meerkeuze",
         vraag="Welke rijtjes van drie zijn juist?",
         opties=["drink, drank, drunk",
                 "sing, sang, sung",
                 "swim, swam, swum",
                 "bring, brang, brung"],
         antwoord=[0, 1, 2],
         uitleg="Die drie volgen hetzelfde patroon. Bring is anders: bring, brought, brought."),
    dict(type="waarofniet",
         vraag="Je zegt in het Engels I didn't knew the answer.",
         antwoord=False,
         uitleg="Na didn't komt de infinitief: I didn't know. Didn't draagt de verleden tijd al."),
    dict(type="meerkeuze",
         vraag="Welke vorm past: He ... the window and then left.",
         opties=["closed",
                 "has closed",
                 "closes",
                 "was closing"],
         antwoord=0,
         uitleg="Twee afgesloten handelingen na elkaar staan in de past simple. And then zet ze op een rij."),
    dict(type="meerkeuze",
         vraag="Wat is de past simple van to have?",
         opties=["had",
                 "haved",
                 "has",
                 "haded"],
         antwoord=0,
         uitleg="Have, had, had. We had a lovely day."),
    dict(type="waarofniet",
         vraag="Ago hoort in het Engels bij de past simple.",
         antwoord=True,
         uitleg="Three years ago, a week ago: een afgesloten tijd. Daarom nooit I have seen her three years ago."),
    dict(type="meerkeuze",
         vraag="Welke vorm past: She ... me a lovely card for my birthday.",
         opties=["sent",
                 "sended",
                 "has sent",
                 "sends"],
         antwoord=0,
         uitleg="Send, sent, sent. Sended bestaat niet."),
    dict(type="meerkeuze",
         vraag="Welke vorm past: ... you at home yesterday evening?",
         opties=["Were",
                 "Was",
                 "Did",
                 "Have"],
         antwoord=0,
         uitleg="Bij you hoort were, ook in het enkelvoud. Bij I, he, she en it wordt het was."),
    dict(type="invultekst",
         vraag="Wat is de past simple van to take? Eén woord.",
         antwoord=["took"],
         uitleg="Take, took, taken. Took is de verleden tijd en taken het voltooid deelwoord."),
    dict(type="meerkeuze",
         vraag="Welke vorm past: The shop ... at six, so we were too late.",
         opties=["closed",
                 "close",
                 "closing",
                 "has closed"],
         antwoord=0,
         uitleg="Een afgesloten feit in het verleden, dus de past simple. De tweede zin staat in dezelfde tijd: were."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Hoe vorm je de past continuous?",
         opties=["was of were plus -ing",
                 "did plus -ing achteraan",
                 "had plus -ing",
                 "have plus -ing"],
         antwoord=0,
         uitleg="I was working, they were working. Met had krijg je de past perfect, en die hoort niet bij deze fiche."),
    dict(type="meerkeuze",
         vraag="Welke vorm past: At eight o'clock last night I ... dinner.",
         opties=["was cooking",
                 "cooked",
                 "cook",
                 "have cooked"],
         antwoord=0,
         uitleg="Op dat ogenblik was het bezig, dus de past continuous. Een past simple zou het als één afgesloten feit zien."),
    dict(type="invultekst",
         vraag="Vul in: They ... football when it started to rain. Gebruik to play in de past continuous. Twee woorden.",
         antwoord=["were playing"],
         uitleg="Were playing: de lange handeling eromheen. De korte handeling erin staat in de past simple."),
    dict(type="meerkeuze",
         vraag="Welke tijd hoort bij de lange handeling in een zin met while?",
         opties=["de past continuous",
                 "de past simple",
                 "de present simple",
                 "de present perfect"],
         antwoord=0,
         uitleg="While I was reading, the phone rang. De lange handeling is continuous, de korte simple."),
    dict(type="waarofniet",
         vraag="In de zin While we were waiting, the bus arrived staat arrived in de past simple.",
         antwoord=True,
         uitleg="Wachten duurde, de bus kwam op één moment. Dat is precies het samenspel van de twee verleden tijden."),
    dict(type="meerkeuze",
         vraag="Welke vorm past: I ... TV when you called.",
         opties=["was watching",
                 "watched",
                 "watch",
                 "have watched"],
         antwoord=0,
         uitleg="Het kijken was al bezig toen het telefoontje kwam. Dus was watching, en called in de past simple."),
    dict(type="meerkeuze",
         vraag="Welke zinnen in de past continuous zijn juist?",
         opties=["She was reading.",
                 "They were sleeping.",
                 "It was getting dark.",
                 "We was walking."],
         antwoord=[0, 1, 2],
         uitleg="De eerste drie hebben de juiste vorm van to be. De laatste moet we were walking zijn."),
    dict(type="invultekst",
         vraag="Welk voegwoord gebruik je voor de lange handeling in een verleden tijd, met vijf letters en beginnend met w?",
         antwoord=["while", "whilst"],
         uitleg="While: while I was cooking. Voor de korte handeling gebruik je when: when the phone rang."),
    dict(type="meerkeuze",
         vraag="Welke vorm past: What ... you ... when the lights went out?",
         opties=["were doing",
                 "did doing",
                 "have doing",
                 "was doing"],
         antwoord=0,
         uitleg="Bij you hoort were. Went out staat in de past simple, want dat was het ene moment."),
    dict(type="waarofniet",
         vraag="Twee handelingen die samen bezig waren, zet je in de past simple.",
         antwoord=False,
         uitleg="Allebei in de past continuous: while I was cooking, she was setting the table. De past simple is voor de korte gebeurtenis."),
    dict(type="meerkeuze",
         vraag="Welke zinnen zetten de achtergrond van een verhaal?",
         opties=["It was raining.",
                 "The sun was shining.",
                 "The wind was blowing.",
                 "She opened the door."],
         antwoord=[0, 1, 2],
         uitleg="De achtergrond staat in de past continuous: het was al bezig en bleef duren. She opened the door is een gebeurtenis in de past simple."),
    dict(type="meerkeuze",
         vraag="Welke werkwoorden staan zelden in de past continuous?",
         opties=["to know",
                 "to believe",
                 "to want",
                 "to run"],
         antwoord=[0, 1, 2],
         uitleg="Werkwoorden van weten, vinden en willen staan niet in een continuous. To run kan dat wel: he was running."),
    dict(type="waarofniet",
         vraag="Je zegt in het Engels I was knowing him well.",
         antwoord=False,
         uitleg="To know staat niet in de continuous: I knew him well. Dat geldt ook voor to like, to want en to believe."),
    dict(type="meerkeuze",
         vraag="Welke vorm past: She fell ... she was running down the stairs.",
         opties=["while",
                 "during",
                 "when she fell",
                 "and then"],
         antwoord=0,
         uitleg="While hoort bij de lange handeling in de continuous. During staat voor een naamwoord: during the lesson."),
    dict(type="meerkeuze",
         vraag="Welke vorm past: They ... in the garden all afternoon.",
         opties=["were working",
                 "was working",
                 "work",
                 "have worked"],
         antwoord=0,
         uitleg="All afternoon is een duur in een afgesloten verleden, dus de past continuous met were."),
    dict(type="waarofniet",
         vraag="Een verhaal in het Engels zet de achtergrond vaak in de past continuous.",
         antwoord=True,
         uitleg="It was raining and the wind was blowing. Daarna komen de gebeurtenissen in de past simple."),
    dict(type="meerkeuze",
         vraag="Welke vorm past: I was reading a book ... the fire went out.",
         opties=["when",
                 "while",
                 "during",
                 "because of"],
         antwoord=0,
         uitleg="When hoort bij de korte handeling in de past simple. While zou bij een tweede lange handeling horen."),
    dict(type="meerkeuze",
         vraag="Wat is de past continuous van He writes a letter?",
         opties=["He was writing a letter",
                 "He wrote a letter",
                 "He has written a letter",
                 "He did write a letter"],
         antwoord=0,
         uitleg="Was plus writing, met de stomme e van write weggelaten. De andere drie zijn andere tijden."),
    dict(type="invultekst",
         vraag="Vul in: It ... when I woke up. Gebruik to snow in de past continuous. Twee woorden.",
         antwoord=["was snowing"],
         uitleg="Was snowing: het sneeuwde al en bleef sneeuwen. Woke up is de korte handeling in de past simple."),
    dict(type="meerkeuze",
         vraag="Welke vorm past: We ... for the train when it began to rain.",
         opties=["were waiting",
                 "waited",
                 "wait",
                 "have waited"],
         antwoord=0,
         uitleg="Het wachten was bezig, de regen begon op één moment. Zo verdelen de twee verleden tijden het werk."),
]
