# -*- coding: utf-8 -*-
"""Schrijven, spreken en je beleving bij een tekst.

Uit de vakfiche Engels 2 van de 3de graad dubbele finaliteit (2027): de
vereisten waaraan je tekst of je spreekopdracht moet voldoen (taakvoltooiing,
woordenschat, grammatica, tekststructuur, register, lay-out, spelling,
lichaamstaal, spreektempo en uitspraak) en de strategieën die de fiche
opsomt (deel 1). Deel 2 is de literatuurbeleving: je verwoordt schriftelijk
je eigen beleving en interpretatie bij een literaire tekst, en de manieren om
iemand iets te vragen, uit te leggen of te overtuigen.

Spreken en het gesprek zelf zitten hier niet in: daarvoor heb je geluid en een
gesprekspartner nodig. Wat je erover moet weten, staat er wel.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is een schrijfplan?",
         opties=["een lijstje kernwoorden",
                 "de volledige tekst in het klad",
                 "een lijst van je spelfouten",
                 "de tekst van iemand anders"],
         antwoord=0,
         uitleg="De fiche raadt aan om eerst met kernwoorden te plannen. Zo vergeet je niets en loopt je tekst van zichzelf."),
    dict(type="meerkeuze",
         vraag="Waaruit bestaat een goede lay-out van een tekst?",
         opties=["een titel",
                 "alinea's",
                 "witruimte tussen de delen",
                 "zo veel mogelijk kleuren"],
         antwoord=[0, 1, 2],
         uitleg="De fiche vraagt dat de opbouw herkenbaar is: titel en alinea's. Kleur maakt een tekst niet duidelijker."),
    dict(type="invultekst",
         vraag="Hoe noem je de stukjes waarin je een tekst verdeelt, met een witregel ertussen? Eén woord.",
         antwoord=["alinea's", "alineas", "alinea"],
         uitleg="Alinea's, in het Engels paragraphs. Eén gedachte per alinea leest het makkelijkst."),
    dict(type="meerkeuze",
         vraag="Wat betekent taakvoltooiing bij een schrijfopdracht?",
         opties=["je doel is bereikt",
                 "je tekst heeft geen fouten",
                 "je tekst is zo lang mogelijk",
                 "je hebt mooie woorden gebruikt"],
         antwoord=0,
         uitleg="Je boodschap komt over, de inhoud is volledig en ter zake, en je respecteert de opgegeven lengte. Zo staat het in de vereisten."),
    dict(type="waarofniet",
         vraag="Je moet de opgegeven lengte van een schrijfopdracht respecteren.",
         antwoord=True,
         uitleg="Dat staat uitdrukkelijk bij taakvoltooiing. Veel te kort of veel te lang kost punten, ook als de taal goed is."),
    dict(type="meerkeuze",
         vraag="Wat doe je volgens de fiche als je niet weet hoe je iets moet formuleren?",
         opties=["het zeggen met wat je al kent",
                 "de opdracht maar overslaan",
                 "het in het Nederlands schrijven",
                 "een heel lange zin proberen"],
         antwoord=0,
         uitleg="Laat je niet ontmoedigen, zegt de fiche: bereik je doel met de woorden en structuren die je wel kent. Dat is een strategie, niet een noodoplossing."),
    dict(type="meerkeuze",
         vraag="Welke hulpmiddelen mag je bij het schrijfexamen gebruiken?",
         opties=["een online woordenboek",
                 "een spellingcontrole",
                 "je eigen schrijfplan op het blad",
                 "je samenvatting van thuis"],
         antwoord=[0, 1, 2],
         uitleg="Het woordenboek en de spellingcontrole staan op de website van de Examencommissie. Cursusmateriaal of een samenvatting meebrengen is examenfraude."),
    dict(type="invultekst",
         vraag="Welk Engels woord zet je volgens de fiche vaak in een vraag om hoffelijk te klinken? Eén woord.",
         antwoord=["please"],
         uitleg="Please, en daarbij voldoende thank you. De fiche noemt die twee letterlijk bij de strategieën."),
    dict(type="meerkeuze",
         vraag="Wat doe je als je je gesprekspartner niet begrepen hebt?",
         opties=["vragen om te herhalen",
                 "gewoon ja antwoorden",
                 "het gesprek beëindigen",
                 "in het Nederlands verdergaan"],
         antwoord=0,
         uitleg="Could you repeat that, please? of Could you speak more slowly? Vragen om herhaling is een strategie, geen zwakte."),
    dict(type="waarofniet",
         vraag="Volgens de fiche moet je schrijfopdracht helemaal foutloos zijn.",
         antwoord=False,
         uitleg="De eis is dat spelfouten en fouten tegen leestekens het tekstbegrip niet in de weg staan. Foutloos hoeft dus niet, duidelijk wel."),
    dict(type="meerkeuze",
         vraag="Welke tekststructuur verwacht de fiche?",
         opties=["inleiding, midden en slot",
                 "enkel een inleiding",
                 "een rij losse zinnen",
                 "een opsomming zonder tekst"],
         antwoord=0,
         uitleg="Met duidelijke tekstverbanden, onder meer door signaalwoorden. Zo kan een lezer je gedachtegang volgen."),
    dict(type="meerkeuze",
         vraag="Wat doe je als laatste met je tekst voor je hem inlevert?",
         opties=["nalezen",
                 "nog een alinea bijschrijven",
                 "de titel weglaten",
                 "alles in het net herschrijven"],
         antwoord=0,
         uitleg="Lees je tekst grondig na: is de communicatie helder, gepast en vlot? Dat staat als laatste strategie in de fiche."),
    dict(type="waarofniet",
         vraag="Je lichaamstaal telt mee bij een spreekopdracht.",
         antwoord=True,
         uitleg="De vereisten noemen lichaamstaal, spreektempo, vlotheid, uitspraak en intonatie. Je gezicht en je handen horen dus bij je boodschap."),
    dict(type="meerkeuze",
         vraag="Wat vraag je je af voor je begint te schrijven?",
         opties=["waarom schrijf ik?",
                 "voor wie is dit?",
                 "welk kanaal gebruik ik?",
                 "hoeveel tijd heb ik nog?"],
         antwoord=[0, 1, 2],
         uitleg="Dat is het communicatiemodel uit de fiche. De klok nakijken helpt wel bij je planning, maar hoort niet bij het model."),
    dict(type="waarofniet",
         vraag="Een gesprek moet je volgens de fiche altijd op voorhand kunnen voorbereiden.",
         antwoord=False,
         uitleg="De fiche zegt dat je zowel voorbereid als onvoorbereid aan een gesprek moet kunnen deelnemen. Je moet het ook kunnen beginnen, gaande houden en beëindigen."),
    dict(type="meerkeuze",
         vraag="Wat betekent een gepast register in een mail aan een onbekende?",
         opties=["neutraal en hoffelijk",
                 "zo kort als het kan",
                 "met veel afkortingen",
                 "in spreektaal met emoji"],
         antwoord=0,
         uitleg="Neutraal of informeel, afhankelijk van de lezer, zegt de fiche. Aan een onbekende blijf je dus beter aan de neutrale kant."),
    dict(type="meerkeuze",
         vraag="Welke woorden houden een tekst aan elkaar?",
         opties=["first",
                 "however",
                 "finally",
                 "pizza"],
         antwoord=[0, 1, 2],
         uitleg="Signaalwoorden maken de tekstverbanden zichtbaar. De fiche vraagt ze uitdrukkelijk bij tekststructuur en samenhang."),
    dict(type="meerkeuze",
         vraag="Hoe begin je een informele mail aan een vriend?",
         opties=["Hi Tom,",
                 "Dear Sir or Madam,",
                 "To whom it may concern,",
                 "Yours faithfully,"],
         antwoord=0,
         uitleg="Hi of Hello met de voornaam. De twee middelste zijn formeel en de laatste is een afsluiting, geen begroeting."),
    dict(type="meerkeuze",
         vraag="Waarmee sluit je een formele Engelse mail af als je de naam van de lezer kent?",
         opties=["Yours sincerely",
                 "Lots of love",
                 "Bye for now",
                 "Cheers mate"],
         antwoord=0,
         uitleg="Yours sincerely bij een bekende naam, Yours faithfully na Dear Sir or Madam. De andere drie horen bij vrienden."),
    dict(type="invultekst",
         vraag="Hoe noem je het soort taalgebruik dat past bij je lezer: formeel of informeel? Eén woord.",
         antwoord=["register"],
         uitleg="Het register. De fiche eist een gepast register en gepaste beleefdheidsconventies."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is literatuurbeleving volgens de fiche?",
         opties=["zeggen wat een tekst bij je doet",
                 "een gedicht vanbuiten leren",
                 "de schrijver zijn leven uitleggen",
                 "de fouten in een tekst zoeken"],
         antwoord=0,
         uitleg="Je verwoordt in het Engels je eigen beleving en interpretatie. Waarom raakt deze tekst je, of waarom juist niet?"),
    dict(type="meerkeuze",
         vraag="Welke vragen horen bij literatuurbeleving?",
         opties=["waarom spreekt dit me aan?",
                 "wie van de personages lijkt op mij?",
                 "welk gevoel roept dit op?",
                 "hoeveel bladzijden heeft het boek?"],
         antwoord=[0, 1, 2],
         uitleg="De fiche noemt die drie zelf als voorbeelden. Het aantal bladzijden zegt niets over je beleving."),
    dict(type="invultekst",
         vraag="Hoe zeg je verhaal in het Engels? Eén woord.",
         antwoord=["story", "a story", "tale"],
         uitleg="A story, of a short story voor een kortverhaal. A tale klinkt wat ouder en sprookjesachtiger."),
    dict(type="meerkeuze",
         vraag="Wat kan de fiche je bij een verhaal vragen te doen?",
         opties=["zelf een einde verzinnen",
                 "het verhaal letterlijk kopiëren",
                 "de schrijver een mail sturen",
                 "elke spelfout verbeteren"],
         antwoord=0,
         uitleg="Je verzint een einde bij een verhaal: dat staat er letterlijk. Zo laat je zien hoe je het verhaal gelezen hebt."),
    dict(type="waarofniet",
         vraag="Bij literatuurbeleving mag je zeggen dat een tekst je niet aanspreekt.",
         antwoord=True,
         uitleg="Het gaat om jouw beleving, niet om het juiste antwoord. Je moet wel uitleggen waarom, en dat in het Engels."),
    dict(type="meerkeuze",
         vraag="Hoe begin je in het Engels je mening over een boek?",
         opties=["I liked it because",
                 "The book has 300 pages",
                 "It was published in 2019",
                 "The writer lives in Leeds"],
         antwoord=0,
         uitleg="Een mening begint bij jou en krijgt een reden mee. De drie andere zinnen zijn feiten over het boek."),
    dict(type="meerkeuze",
         vraag="Wat betekent to identify with a character?",
         opties=["je in een personage herkennen",
                 "een personage een naam geven",
                 "een personage natekenen",
                 "een personage uit het verhaal halen"],
         antwoord=0,
         uitleg="Je herkent jezelf in wat het personage doet of voelt. De fiche noemt dat als een manier om je beleving te verwoorden."),
    dict(type="invultekst",
         vraag="Hoe zeg je gedicht in het Engels? Eén woord.",
         antwoord=["poem", "a poem"],
         uitleg="A poem, en een dichter is a poet. De fiche noemt een gedicht bij de literaire teksten."),
    dict(type="meerkeuze",
         vraag="Welke zinnen geven informatie aan iemand?",
         opties=["Take a warm sleeping bag.",
                 "The campsite opens in May.",
                 "You can book online.",
                 "What time is it?"],
         antwoord=[0, 1, 2],
         uitleg="Drie tips over kamperen, precies het voorbeeld uit de fiche. De laatste zin vraagt juist informatie."),
    dict(type="waarofniet",
         vraag="Je mening geven en iemand overtuigen is in de fiche hetzelfde.",
         antwoord=False,
         uitleg="Het staan er als twee aparte dingen. Bij een mening zeg je wat je vindt; bij overtuigen wil je dat de ander meegaat."),
    dict(type="meerkeuze",
         vraag="Welke zinnen horen bij overtuigen?",
         opties=["This is cheaper.",
                 "It saves time.",
                 "You should try it.",
                 "What is your name?"],
         antwoord=[0, 1, 2],
         uitleg="Drie zinnen die een argument of een aanbeveling geven. De laatste vraagt enkel informatie en overtuigt niemand."),
    dict(type="meerkeuze",
         vraag="Wat is in het Engels a plot?",
         opties=["de verhaallijn",
                 "de plaats van het verhaal",
                 "het hoofdpersonage",
                 "de schrijver van het boek"],
         antwoord=0,
         uitleg="De plot is wat er in het verhaal gebeurt, in welke orde. De plaats en de tijd zijn the setting."),
    dict(type="waarofniet",
         vraag="A character is in het Engels een personage in een verhaal.",
         antwoord=True,
         uitleg="The main character is het hoofdpersonage. Character betekent ook karakter, dus kijk naar de zin eromheen."),
    dict(type="meerkeuze",
         vraag="Wat is in het Engels the setting van een verhaal?",
         opties=["waar en wanneer",
                 "wie het verhaal vertelt",
                 "hoe het verhaal eindigt",
                 "waarom het geschreven is"],
         antwoord=0,
         uitleg="De plaats en de tijd waarin het verhaal zich afspeelt. Wie vertelt, is the narrator."),
    dict(type="meerkeuze",
         vraag="Welke zin vraagt om informatie?",
         opties=["Could you tell me the time?",
                 "The shop opens at nine.",
                 "I think the shop is too small.",
                 "Please close the door."],
         antwoord=0,
         uitleg="Could you tell me is de hoffelijke manier om iets te vragen. De tweede geeft informatie, de derde een mening, de vierde een bevel."),
    dict(type="waarofniet",
         vraag="Bij een uitleg mag je volgens de fiche geen voorbeeld geven.",
         antwoord=False,
         uitleg="Een voorbeeld is juist het handigste wat er is: for example of for instance maakt een uitleg meteen duidelijk."),
    dict(type="meerkeuze",
         vraag="Wat betekent a review?",
         opties=["een recensie",
                 "een samenvatting",
                 "een voorwoord",
                 "een vervolg"],
         antwoord=0,
         uitleg="Iemand geeft er zijn oordeel over een boek, een film of een hotel. Een samenvatting is a summary."),
    dict(type="meerkeuze",
         vraag="Hoe vertel je in het Engels over je vakantieplannen?",
         opties=["I am going to Spain in July.",
                 "I went to Spain last year.",
                 "Spain is a big country.",
                 "Do you like Spain?"],
         antwoord=0,
         uitleg="Plannen zet je in de toekomende tijd, met going to of will. De fiche geeft vakantieplannen zelf als voorbeeld van iets vertellen."),
    dict(type="meerkeuze",
         vraag="Wat is in het Engels a vlog?",
         opties=["een dagboek in beeld",
                 "een brief aan een krant",
                 "een lied met een verhaal",
                 "een boek over een reis"],
         antwoord=0,
         uitleg="Een video blog. De fiche noemt een vlog bij de narratieve teksten en vraagt dat je er een kijkersvraag in kan beantwoorden."),
    dict(type="meerkeuze",
         vraag="Wat doe je als je merkt dat je gesprekspartner je niet begrijpt?",
         opties=["het anders zeggen",
                 "harder beginnen praten",
                 "het gesprek stilleggen",
                 "net hetzelfde herhalen"],
         antwoord=0,
         uitleg="Herhaal je boodschap of formuleer ze op een andere manier, zegt de fiche. Precies hetzelfde nog eens zeggen helpt zelden."),
]
