# -*- coding: utf-8 -*-
"""Woordvelden: school en werk, geld en verkeer.

Drie van de zestien woordvelden van de vakfiche Engels van de 3de graad
dubbele finaliteit (2027): opleiding, school- en beroepsleven; economie en
consumptie; transport en verkeer. Niveau ERK A2+.

Deel 1 is school, opleiding en werk.
Deel 2 is geld, kopen en het verkeer.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat betekent a subject op school?",
         opties=["een vak",
                 "een leerling",
                 "een lokaal",
                 "een boek"],
         antwoord=0,
         uitleg="My favourite subject is history. In de grammatica betekent subject ook onderwerp van de zin."),
    dict(type="meerkeuze",
         vraag="Welke woorden horen bij school?",
         opties=["a timetable",
                 "a report",
                 "homework",
                 "a trolley"],
         antwoord=[0, 1, 2],
         uitleg="Een lessenrooster, een rapport en huiswerk. A trolley is een winkelkar."),
    dict(type="invultekst",
         vraag="Hoe zeg je leerkracht in het Engels? Eén woord.",
         antwoord=["teacher", "a teacher"],
         uitleg="A teacher. Het hoofd van de school is the headteacher of the principal."),
    dict(type="meerkeuze",
         vraag="Wat betekent to pass an exam?",
         opties=["slagen",
                 "een examen missen",
                 "een examen uitstellen",
                 "een examen afnemen"],
         antwoord=0,
         uitleg="To pass is slagen, to fail is niet slagen. Een examen afleggen is to take of to sit an exam."),
    dict(type="waarofniet",
         vraag="Homework is in het Engels een ontelbaar woord.",
         antwoord=True,
         uitleg="Je zegt a lot of homework, nooit homeworks. Work, advice en information werken net zo."),
    dict(type="meerkeuze",
         vraag="Wat is in het Engels a degree?",
         opties=["een diploma",
                 "een vak op school",
                 "een les van een uur",
                 "een klas vol leerlingen"],
         antwoord=0,
         uitleg="A university degree is een universitair diploma. Degree betekent ook graad, zoals bij temperatuur."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn beroepen?",
         opties=["a plumber",
                 "a nurse",
                 "a shop assistant",
                 "a timetable"],
         antwoord=[0, 1, 2],
         uitleg="Een loodgieter, een verpleegkundige en een winkelbediende. A timetable is een uurrooster."),
    dict(type="invultekst",
         vraag="Hoe zeg je loon in het Engels, als je het maandloon bedoelt? Eén woord.",
         antwoord=["salary", "wage", "pay"],
         uitleg="A salary is een vast maandloon, a wage eerder een uur- of weekloon. Pay is het ruimere woord."),
    dict(type="meerkeuze",
         vraag="Wat betekent to apply for a job?",
         opties=["solliciteren",
                 "ontslag nemen",
                 "overwerken",
                 "promotie maken"],
         antwoord=0,
         uitleg="An application is een sollicitatie, en an applicant is de kandidaat. Je schrijft a letter of application."),
    dict(type="waarofniet",
         vraag="A trainee is in het Engels iemand die opgeleid wordt.",
         antwoord=True,
         uitleg="To train betekent opleiden of trainen. Een stage heet a work placement of an internship."),
    dict(type="meerkeuze",
         vraag="Wat is in het Engels a CV?",
         opties=["een overzicht van je loopbaan",
                 "een brief van je werkgever",
                 "een contract voor een job",
                 "een attest van de school"],
         antwoord=0,
         uitleg="Curriculum vitae. In de VS zeggen ze a resume."),
    dict(type="meerkeuze",
         vraag="Wat betekent a deadline?",
         opties=["een uiterste datum",
                 "een verloren dag",
                 "een lange pauze",
                 "een vaste afspraak"],
         antwoord=0,
         uitleg="Wanneer iets klaar moet zijn. To meet a deadline is hem halen, to miss a deadline niet."),
    dict(type="waarofniet",
         vraag="To be made redundant betekent in het Engels promotie krijgen.",
         antwoord=False,
         uitleg="Het betekent juist je job verliezen omdat hij wegvalt. Promotie krijgen is to get a promotion."),
    dict(type="meerkeuze",
         vraag="Welke woorden horen bij werk zoeken?",
         opties=["an interview",
                 "a vacancy",
                 "an application",
                 "a canteen"],
         antwoord=[0, 1, 2],
         uitleg="Een gesprek, een openstaande plaats en een sollicitatie. A canteen is het refter of het bedrijfsrestaurant."),
    dict(type="meerkeuze",
         vraag="Wat betekent a part-time job?",
         opties=["deeltijds werk",
                 "werk voor één dag",
                 "werk in het weekend",
                 "werk zonder loon"],
         antwoord=0,
         uitleg="Tegenover a full-time job. Vakantiewerk is a summer job of a holiday job."),
    dict(type="waarofniet",
         vraag="A colleague is in het Engels iemand van je school.",
         antwoord=False,
         uitleg="A colleague is een collega op het werk. Iemand van je school is a classmate of a schoolmate."),
    dict(type="meerkeuze",
         vraag="Wat is in het Engels a break at school?",
         opties=["een pauze",
                 "een vak",
                 "een toets",
                 "een straf"],
         antwoord=0,
         uitleg="The lunch break is de middagpauze. Break betekent ook breken, dus kijk naar de zin eromheen."),
    dict(type="meerkeuze",
         vraag="Wat betekent to take notes?",
         opties=["nota's nemen",
                 "briefjes meenemen",
                 "een boek lenen",
                 "een test afleggen"],
         antwoord=0,
         uitleg="Notes zijn je aantekeningen. Een bankbiljet is ook a note, maar dan a ten-pound note."),
    dict(type="invultekst",
         vraag="Hoe zeg je werkloos in het Engels? Eén woord.",
         antwoord=["unemployed", "jobless"],
         uitleg="Unemployed, met het voorvoegsel un-. De werkloosheid is unemployment."),
    dict(type="meerkeuze",
         vraag="Wat betekent a skill?",
         opties=["een vaardigheid",
                 "een diploma",
                 "een job",
                 "een werkplek"],
         antwoord=0,
         uitleg="Wat je kan, niet wat je weet. Language skills zijn je talenkennis."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat betekent a bargain?",
         opties=["een koopje",
                 "een rekening",
                 "een lening",
                 "een boete"],
         antwoord=0,
         uitleg="Iets goedkoop kopen. To bargain is onderhandelen over de prijs."),
    dict(type="meerkeuze",
         vraag="Welke woorden horen bij geld?",
         opties=["a loan",
                 "interest",
                 "savings",
                 "a crossing"],
         antwoord=[0, 1, 2],
         uitleg="Een lening, rente en spaargeld. A crossing is een oversteekplaats."),
    dict(type="invultekst",
         vraag="Hoe zeg je korting in het Engels? Eén woord.",
         antwoord=["discount", "reduction"],
         uitleg="A discount, of a reduction. Een koopjesperiode is the sales."),
    dict(type="meerkeuze",
         vraag="Wat is in het Engels a receipt?",
         opties=["een kassabon",
                 "een recept om te koken",
                 "een briefje van de dokter",
                 "een lijst van je aankopen"],
         antwoord=0,
         uitleg="Let op: een recept om te koken is a recipe. Receipt heeft een p die je niet uitspreekt."),
    dict(type="waarofniet",
         vraag="To afford something betekent dat je het kan betalen.",
         antwoord=True,
         uitleg="I cannot afford a new bike: ik kan me geen nieuwe fiets veroorloven. Het staat bijna altijd bij can of cannot."),
    dict(type="meerkeuze",
         vraag="Wat betekent to pay in cash?",
         opties=["cash betalen",
                 "met de kaart betalen",
                 "later betalen",
                 "in schijven betalen"],
         antwoord=0,
         uitleg="Cash is contant geld. Met de kaart is to pay by card."),
    dict(type="meerkeuze",
         vraag="Welke woorden horen bij het verkeer?",
         opties=["a roundabout",
                 "a traffic jam",
                 "a pedestrian",
                 "a saucepan"],
         antwoord=[0, 1, 2],
         uitleg="Een rotonde, een file en een voetganger. A saucepan is een kookpot."),
    dict(type="invultekst",
         vraag="Hoe zeg je rijbewijs in het Engels? Twee woorden.",
         antwoord=["driving licence", "driving license", "driver's license"],
         uitleg="A driving licence in het Verenigd Koninkrijk, a driver's license in de VS. Let op de c en de s."),
    dict(type="meerkeuze",
         vraag="Wat is in het Engels petrol?",
         opties=["benzine",
                 "diesel",
                 "olie voor de motor",
                 "water voor de ruitenwissers"],
         antwoord=0,
         uitleg="Petrol in het Verenigd Koninkrijk, gas of gasoline in de VS. Een tankstation is a petrol station."),
    dict(type="waarofniet",
         vraag="A zebra crossing is in het Engels een dierentuin voor zebra's.",
         antwoord=False,
         uitleg="Het is een zebrapad: de witte strepen om over te steken. Een dierentuin is a zoo."),
    dict(type="meerkeuze",
         vraag="Wat betekent a fine in het verkeer?",
         opties=["een boete",
                 "een waarschuwing",
                 "een controle",
                 "een omleiding"],
         antwoord=0,
         uitleg="Fine betekent ook goed of fijn, maar in het verkeer is het een geldboete. To fine someone is iemand beboeten."),
    dict(type="meerkeuze",
         vraag="Wat is in het Engels a motorway?",
         opties=["een snelweg",
                 "een brug over de rivier",
                 "een straat in het centrum",
                 "een weg voor fietsers"],
         antwoord=0,
         uitleg="Motorway in het Verenigd Koninkrijk, highway of freeway in de VS. In Vlaanderen zijn dat de wegen met een E ervoor."),
    dict(type="waarofniet",
         vraag="A pavement is in het Verenigd Koninkrijk het wegdek voor de auto's.",
         antwoord=False,
         uitleg="In het Verenigd Koninkrijk is the pavement het voetpad; in de VS heet dat the sidewalk en betekent pavement wel het wegdek."),
    dict(type="meerkeuze",
         vraag="Welke woorden horen bij een winkel?",
         opties=["a till",
                 "a queue",
                 "a shelf",
                 "a helmet"],
         antwoord=[0, 1, 2],
         uitleg="De kassa, de rij en het rek. A helmet is een valhelm."),
    dict(type="meerkeuze",
         vraag="Wat betekent to refund?",
         opties=["terugbetalen",
                 "geld opzijzetten",
                 "iets komen ruilen",
                 "geld gaan lenen"],
         antwoord=0,
         uitleg="A refund is het geld dat je terugkrijgt. Ruilen is to exchange."),
    dict(type="waarofniet",
         vraag="VAT is in het Engels de belasting op de toegevoegde waarde.",
         antwoord=True,
         uitleg="Value added tax, bij ons de btw. Prices include VAT staat op veel rekeningen."),
    dict(type="meerkeuze",
         vraag="Wat is in het Engels a customer?",
         opties=["een klant",
                 "een verkoper",
                 "een leverancier",
                 "een eigenaar"],
         antwoord=0,
         uitleg="The customer is always right. De klantendienst is customer service."),
    dict(type="meerkeuze",
         vraag="Wat betekent to commute?",
         opties=["pendelen",
                 "verhuizen",
                 "carpoolen",
                 "ruilen van job"],
         antwoord=0,
         uitleg="Elke dag heen en terug naar je werk. Een pendelaar is a commuter."),
    dict(type="meerkeuze",
         vraag="Wat is in het Engels a lorry?",
         opties=["een vrachtwagen",
                 "een bestelwagen",
                 "een aanhangwagen",
                 "een ziekenwagen"],
         antwoord=0,
         uitleg="Lorry in het Verenigd Koninkrijk, truck in de VS. Een bestelwagen is a van."),
    dict(type="meerkeuze",
         vraag="Wat betekent rush hour?",
         opties=["het spitsuur",
                 "een snelle rit",
                 "een uur korting",
                 "een haastige maaltijd"],
         antwoord=0,
         uitleg="De uren waarin iedereen naar of van het werk rijdt. Dan staan de files, the traffic jams."),
]
