# -*- coding: utf-8 -*-
"""De tegenwoordige tijden en de present perfect.

Uit de grammaticalijst van de vakfiche Engels van de 3de graad dubbele
finaliteit (2027): there is en there are, de present simple, de present
continuous en de emphatic do (deel 1), en de present perfect simple en de
present perfect continuous (deel 2). Niveau ERK A2+.

De fiche geeft zelf het voorbeeld dat het verschil met het Nederlands laat
zien: "Ik woon sinds 2020 in Antwerpen" wordt I have lived in Antwerp since
2020, met een present perfect en niet met een present simple.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Welke vorm hoort bij he in de present simple?",
         opties=["works",
                 "work",
                 "working",
                 "worked"],
         antwoord=0,
         uitleg="Bij he, she en it komt er een s bij: he works. Bij I, you, we en they niet."),
    dict(type="meerkeuze",
         vraag="Welke zinnen in de present simple zijn juist?",
         opties=["She lives in Ghent.",
                 "They play tennis.",
                 "He watches TV.",
                 "It rain a lot here."],
         antwoord=[0, 1, 2],
         uitleg="De eerste drie hebben de juiste uitgang. De laatste moet it rains zijn."),
    dict(type="invultekst",
         vraag="Vul in: My brother ... to school by bus. Gebruik to go in de present simple. Eén woord.",
         antwoord=["goes"],
         uitleg="Na o komt -es: goes, does. Zo ook na s, x, ch en sh: watches, washes."),
    dict(type="meerkeuze",
         vraag="Welke vorm past: Listen! The baby ...",
         opties=["is crying",
                 "cries",
                 "cry",
                 "has cried"],
         antwoord=0,
         uitleg="Het gebeurt nu, op dit moment, dus de present continuous. Listen! en Look! zijn vaste aanwijzers."),
    dict(type="waarofniet",
         vraag="De present simple gebruik je voor iets dat gewoonlijk gebeurt.",
         antwoord=True,
         uitleg="I always take the train. Woorden als always, usually, often en every day horen erbij."),
    dict(type="meerkeuze",
         vraag="Hoe maak je de ontkenning van She plays the piano?",
         opties=["She does not play",
                 "She not plays",
                 "She do not plays",
                 "She plays not"],
         antwoord=0,
         uitleg="In de present simple gebruik je do of does, en het hoofdwerkwoord blijft zonder s. Verkort: she doesn't play."),
    dict(type="meerkeuze",
         vraag="Welke zinnen gebruiken there is of there are juist?",
         opties=["There is a cat in the garden.",
                 "There are two chairs here.",
                 "There is some milk left.",
                 "There are a problem."],
         antwoord=[0, 1, 2],
         uitleg="There is bij enkelvoud en bij ontelbare woorden, there are bij meervoud. De laatste moet there is a problem zijn."),
    dict(type="invultekst",
         vraag="Vul in: ... there any eggs in the fridge? Eén woord.",
         antwoord=["Are", "are"],
         uitleg="Eggs is meervoud, dus are there. Bij enkelvoud wordt het is there."),
    dict(type="meerkeuze",
         vraag="Waarvoor gebruik je de emphatic do?",
         opties=["om iets te benadrukken",
                 "om een vraag te stellen",
                 "om te ontkennen",
                 "om een bevel te geven"],
         antwoord=0,
         uitleg="I do like your new coat! De fiche noemt dit uitdrukkelijk: do om iets te benadrukken."),
    dict(type="waarofniet",
         vraag="Je zegt in het Engels I am knowing the answer.",
         antwoord=False,
         uitleg="Werkwoorden van weten, vinden en houden van staan niet in de continuous: I know the answer. Zo ook I like, I believe, I want."),
    dict(type="meerkeuze",
         vraag="Welke vorm past: We ... for a new flat at the moment.",
         opties=["are looking",
                 "look",
                 "looks",
                 "have looked"],
         antwoord=0,
         uitleg="At the moment wijst naar iets dat nu bezig is. Dus de present continuous met are."),
    dict(type="meerkeuze",
         vraag="Hoe vorm je de present continuous?",
         opties=["to be plus -ing",
                 "to have plus -ing",
                 "to do plus -ing",
                 "to will plus -ing"],
         antwoord=0,
         uitleg="I am working, she is working, they are working. Met to have krijg je de present perfect."),
    dict(type="waarofniet",
         vraag="Bij een vast uurrooster gebruik je in het Engels de present simple.",
         antwoord=True,
         uitleg="The train leaves at six. Ook voor de toekomst, als er een rooster achter zit: the shop opens tomorrow."),
    dict(type="meerkeuze",
         vraag="Welke vorm past: What ... you ... now?",
         opties=["are doing",
                 "do do",
                 "does doing",
                 "have done"],
         antwoord=0,
         uitleg="What are you doing now? De vorm van to be komt voor het onderwerp en -ing erachter."),
    dict(type="meerkeuze",
         vraag="Welke spelling is juist bij -ing?",
         opties=["swimming",
                 "swiming",
                 "swimmming",
                 "swimeing"],
         antwoord=0,
         uitleg="Een korte klinker voor één consonant verdubbelt die consonant: swim wordt swimming, run wordt running."),
    dict(type="waarofniet",
         vraag="De zin He don't like coffee is juist Engels.",
         antwoord=False,
         uitleg="Bij he, she en it is het doesn't: he doesn't like coffee. Don't hoort bij I, you, we en they."),
    dict(type="meerkeuze",
         vraag="Welke vorm past: The sun ... in the east.",
         opties=["rises",
                 "is rising",
                 "has risen",
                 "rise"],
         antwoord=0,
         uitleg="Een algemene waarheid staat in de present simple. Is rising zou over dit ogenblik gaan."),
    dict(type="meerkeuze",
         vraag="Welke -ing-vormen zijn juist gespeld?",
         opties=["writing",
                 "making",
                 "swimming",
                 "runing"],
         antwoord=[0, 1, 2],
         uitleg="Een stomme e valt weg: write wordt writing, make wordt making. Een korte klinker verdubbelt de consonant: swim wordt swimming en run wordt running, dus runing is fout."),
    dict(type="invultekst",
         vraag="Vul in: She ... a letter right now. Gebruik to write in de present continuous. Twee woorden.",
         antwoord=["is writing"],
         uitleg="Is writing: een vorm van to be plus het werkwoord op -ing, met de e van write weggelaten."),
    dict(type="meerkeuze",
         vraag="Welke vorm past: I ... think you are right.",
         opties=["do",
                 "am",
                 "have",
                 "will"],
         antwoord=0,
         uitleg="I do think you are right legt nadruk op je instemming. Dat is de emphatic do uit de fiche."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Hoe vorm je de present perfect simple?",
         opties=["to have plus voltooid deelwoord",
                 "to be plus voltooid deelwoord",
                 "to do plus de infinitief",
                 "to have plus de infinitief"],
         antwoord=0,
         uitleg="I have finished, she has finished. Het voltooid deelwoord is de derde vorm van het werkwoord."),
    dict(type="meerkeuze",
         vraag="Welke vorm past: I ... in Antwerp since 2020.",
         opties=["have lived",
                 "live",
                 "lived",
                 "am living"],
         antwoord=0,
         uitleg="Dit is het voorbeeld uit de fiche zelf. Begint iets in het verleden en duurt het nog, dan staat er een present perfect."),
    dict(type="invultekst",
         vraag="Welk woord hoort bij een present perfect als je een beginpunt noemt: for of since? Eén woord.",
         antwoord=["since"],
         uitleg="Since bij een beginpunt: since 2020, since Monday. For bij een duur: for three years."),
    dict(type="meerkeuze",
         vraag="Welke woorden horen bij de present perfect?",
         opties=["already",
                 "yet",
                 "ever",
                 "yesterday"],
         antwoord=[0, 1, 2],
         uitleg="Already, yet, ever, never en just horen erbij. Yesterday is afgesloten en vraagt een past simple."),
    dict(type="waarofniet",
         vraag="Bij yesterday gebruik je in het Engels de past simple.",
         antwoord=True,
         uitleg="I saw her yesterday, niet I have seen her yesterday. Een afgesloten tijd vraagt de past simple."),
    dict(type="meerkeuze",
         vraag="Welke vorm past: ... you ever been to Scotland?",
         opties=["Have",
                 "Are",
                 "Did",
                 "Do"],
         antwoord=0,
         uitleg="Ever hoort bij de present perfect: have you ever been. Je vraagt naar een ervaring, zonder te zeggen wanneer."),
    dict(type="meerkeuze",
         vraag="Wat is het voltooid deelwoord van to see?",
         opties=["seen",
                 "saw",
                 "seed",
                 "seeing"],
         antwoord=0,
         uitleg="See, saw, seen. Saw is de past simple en seen het voltooid deelwoord."),
    dict(type="invultekst",
         vraag="Wat is het voltooid deelwoord van to write? Eén woord.",
         antwoord=["written"],
         uitleg="Write, wrote, written. I have written a letter."),
    dict(type="meerkeuze",
         vraag="Welke vorm past: She ... her keys, so she cannot get in.",
         opties=["has lost",
                 "lost",
                 "loses",
                 "is losing"],
         antwoord=0,
         uitleg="Het gevolg geldt nu nog, dus de present perfect. Een past simple zou het verhaal in het verleden laten."),
    dict(type="waarofniet",
         vraag="De present perfect continuous legt de nadruk op hoe lang iets al bezig is.",
         antwoord=True,
         uitleg="I have been waiting for an hour. De gewone present perfect kijkt meer naar het resultaat."),
    dict(type="meerkeuze",
         vraag="Welke vorm past: It ... all morning, so the streets are wet.",
         opties=["has been raining",
                 "is raining right now",
                 "rains",
                 "rained"],
         antwoord=0,
         uitleg="All morning is een duur die tot nu loopt, dus de present perfect continuous. De gevolgen zie je nu."),
    dict(type="meerkeuze",
         vraag="Hoe vorm je de present perfect continuous?",
         opties=["have been plus -ing",
                 "have plus -ing",
                 "am been plus -ing",
                 "had been plus -ing"],
         antwoord=0,
         uitleg="I have been working, he has been working. Met had been wordt het een past perfect, en die staat niet in deze fiche."),
    dict(type="waarofniet",
         vraag="Je zegt in het Engels I have seen him last week.",
         antwoord=False,
         uitleg="Last week is afgesloten, dus I saw him last week. De present perfect verdraagt geen afgesloten tijdsbepaling."),
    dict(type="meerkeuze",
         vraag="Welke woorden passen bij for in een present perfect?",
         opties=["three years",
                 "a long time",
                 "two weeks",
                 "last Monday"],
         antwoord=[0, 1, 2],
         uitleg="For geeft een duur: for three years. Last Monday is een beginpunt dat bij een past simple hoort."),
    dict(type="meerkeuze",
         vraag="Welke woorden passen in I have ... finished my homework?",
         opties=["just",
                 "already",
                 "nearly",
                 "yesterday"],
         antwoord=[0, 1, 2],
         uitleg="Just, already en nearly horen bij de present perfect. Yesterday is een afgesloten tijd en vraagt een past simple."),
    dict(type="waarofniet",
         vraag="Already staat in het Engels altijd achteraan de zin.",
         antwoord=False,
         uitleg="Already staat meestal voor het hoofdwerkwoord: I have already finished. Yet staat wel achteraan: I haven't finished yet."),
    dict(type="meerkeuze",
         vraag="Wat is het voltooid deelwoord van to go?",
         opties=["gone",
                 "went",
                 "goed",
                 "going"],
         antwoord=0,
         uitleg="Go, went, gone. Let op het verschil: he has gone to London betekent dat hij daar nog is, he has been to London dat hij er geweest is."),
    dict(type="meerkeuze",
         vraag="Welke vorm past: How long ... you known her?",
         opties=["have",
                 "do",
                 "are",
                 "did"],
         antwoord=0,
         uitleg="How long plus present perfect vraagt naar een duur die nog loopt. To know staat niet in de continuous."),
    dict(type="invultekst",
         vraag="Vul in: She ... never ... to Spain. Gebruik to be in de present perfect. Twee woorden.",
         antwoord=["has been"],
         uitleg="She has never been to Spain. Het voltooid deelwoord van to be is been."),
    dict(type="meerkeuze",
         vraag="Welke vorm past: They ... in this house for twenty years.",
         opties=["have lived",
                 "live",
                 "lived",
                 "are living"],
         antwoord=0,
         uitleg="For twenty years loopt tot nu, dus de present perfect. In het Nederlands zeggen we gewoon: ze wonen hier twintig jaar."),
]
