# -*- coding: utf-8 -*-
"""Een Franse tekst lezen.

Uit de vakfiche Frans 1 van de 3de graad dubbele finaliteit (2027), ERK A2+:
het onderwerp, de hoofdgedachte en de hoofdpunten van een tekst bepalen en de
informatie selecteren die je nodig hebt (deel 1), en de leesstrategieën die de
fiche opsomt: verwijswoorden zoals ils en y, signaalwoorden zoals d'abord, puis
en par contre, de visuele hulpmiddelen, hoofd- en bijzaken, en de betekenis van
een onbekend woord uit de context halen (deel 2).

Elke leesvraag staat op een echt Frans tekstje. Een vraag over lezen zonder
tekst is geen leesvraag.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Lees: \"Le vélo revient en ville. Dans beaucoup de communes, on construit de nouvelles pistes cyclables.\" Wat is het onderwerp?",
         opties=["de fiets in de stad",
                 "het weer in de zomer",
                 "de prijs van de benzine",
                 "de bus en de tram"],
         antwoord=0,
         uitleg="Het onderwerp zeg je in enkele woorden: de fiets in de stad. Pistes cyclables zijn fietspaden."),
    dict(type="meerkeuze",
         vraag="Lees: \"Le vélo revient en ville. Dans beaucoup de communes, on construit de nouvelles pistes cyclables.\" Wat is de hoofdgedachte?",
         opties=["steden maken plaats voor de fiets",
                 "de auto wordt binnenkort verboden",
                 "fietsen worden elk jaar duurder",
                 "er zijn te weinig bussen in de stad"],
         antwoord=0,
         uitleg="De hoofdgedachte zeg je in één zin. De tweede zin is een hoofdpunt dat die gedachte ondersteunt."),
    dict(type="invultekst",
         vraag="Lees: \"Le musée est ouvert du mardi au dimanche.\" Op welke dag is het museum gesloten? Eén woord in het Frans.",
         antwoord=["lundi", "le lundi"],
         uitleg="Van mardi tot dimanche is open, dus lundi blijft over. Dat is informatie selecteren."),
    dict(type="meerkeuze",
         vraag="Lees: \"Notre magasin ouvre le 3 mai. Il sera ouvert de 9 h à 18 h, sauf le dimanche.\" Welke informatie staat in de tekst?",
         opties=["de openingsdatum",
                 "de openingsuren",
                 "de sluitingsdag",
                 "het adres van de winkel"],
         antwoord=[0, 1, 2],
         uitleg="De datum, de uren en sauf le dimanche staan er letterlijk. Over het adres zegt de tekst niets."),
    dict(type="waarofniet",
         vraag="Het onderwerp van een tekst verwoord je in enkele woorden.",
         antwoord=True,
         uitleg="Het onderwerp is kort, de hoofdgedachte is een volle zin. De hoofdpunten zijn alles wat die zin ondersteunt."),
    dict(type="meerkeuze",
         vraag="Lees: \"En France, le repas de midi est souvent le plus important de la journée.\" Waarover zegt deze zin iets?",
         opties=["over het middagmaal",
                 "over de eetgewoontes",
                 "over de dagindeling",
                 "over de manier van groeten"],
         antwoord=[0, 1, 2],
         uitleg="Le repas de midi is het middagmaal, en de zin zegt welke plaats het in de dag inneemt. De fiche vraagt uitdrukkelijk dat je zulke eetgewoontes uit een tekst haalt."),
    dict(type="meerkeuze",
         vraag="Lees: \"D'abord, faites bouillir l'eau. Puis, ajoutez les pâtes.\" Wat doe je als tweede?",
         opties=["de pasta erbij doen",
                 "het water laten koken",
                 "de pasta proeven",
                 "tien minuten wachten"],
         antwoord=0,
         uitleg="D'abord en puis wijzen de orde aan. Ajoutez les pâtes is de tweede stap."),
    dict(type="invultekst",
         vraag="Lees: \"Le concert commence à vingt heures.\" Hoe laat begint het concert? Vul het getal in.",
         antwoord=["20", "8", "twintig"],
         uitleg="Vingt heures is twintig uur, dus acht uur 's avonds. Het Frans gebruikt op uitnodigingen bijna altijd de 24-urenklok."),
    dict(type="meerkeuze",
         vraag="Lees: \"Au Québec, les collègues se tutoient souvent, même au bureau.\" Wat merk je hier op?",
         opties=["ze tutoyeren elkaar snel",
                 "ze werken heel lange dagen",
                 "ze spreken nooit Frans op het werk",
                 "ze dragen een uniform"],
         antwoord=0,
         uitleg="De fiche geeft dit voorbeeld zelf: in Franstalig Canada gaan collega's weinig formeel met elkaar om. In Frankrijk is vouvoyeren op het werk gewoner."),
    dict(type="waarofniet",
         vraag="De hoofdpunten van een tekst ondersteunen de hoofdgedachte.",
         antwoord=True,
         uitleg="Zo staat het in de fiche. Eerst zoek je de hoofdgedachte, en daarna wat haar schraagt."),
    dict(type="meerkeuze",
         vraag="Lees: \"La bibliothèque sera fermée pendant deux semaines. Vous pouvez rendre vos livres dans la boîte près de la porte.\" Waar laat je je boeken?",
         opties=["in de bus bij de deur",
                 "bij de buren thuis",
                 "in een andere stad",
                 "op de stoep"],
         antwoord=0,
         uitleg="Dans la boîte près de la porte. De drie andere opties staan nergens in de tekst."),
    dict(type="meerkeuze",
         vraag="Welke vragen stel je jezelf voor je een Franse tekst leest?",
         opties=["wat weet ik hier al over?",
                 "waarover zou dit gaan?",
                 "wat zegt de titel?",
                 "hoeveel woorden staan er?"],
         antwoord=[0, 1, 2],
         uitleg="Die drie horen bij de leesstrategieën van de fiche. Woorden tellen helpt je niet verder."),
    dict(type="meerkeuze",
         vraag="Lees: \"Marie est arrivée en retard: son train avait du retard de vingt minutes.\" Waarom was Marie te laat?",
         opties=["de trein had vertraging",
                 "ze was zich gaan verslapen",
                 "ze had de bus gemist",
                 "ze moest nog inkopen doen"],
         antwoord=0,
         uitleg="Du retard betekent vertraging. Alleen die oorzaak staat in de tekst."),
    dict(type="waarofniet",
         vraag="Je mag bij het lezen de titel en de foto's overslaan.",
         antwoord=False,
         uitleg="De fiche noemt die visuele hulpmiddelen juist als een strategie. Ze zeggen vaak al waarover de tekst gaat."),
    dict(type="meerkeuze",
         vraag="Lees: \"Merci d'éteindre votre téléphone. Il est interdit de manger dans la salle.\" Wat mag hier niet?",
         opties=["eten in de zaal",
                 "je jas meebrengen",
                 "met twee komen",
                 "naar het toilet gaan"],
         antwoord=0,
         uitleg="Il est interdit de manger. Over de drie andere dingen zegt de tekst niets."),
    dict(type="invultekst",
         vraag="Lees: \"Il y a plus de six cents élèves dans notre école.\" Hoeveel leerlingen zijn er ongeveer? Vul het getal in.",
         antwoord=["600", "zeshonderd"],
         uitleg="Six cents is zeshonderd. Plus de betekent meer dan."),
    dict(type="meerkeuze",
         vraag="Lees: \"Notre boulangerie déménage dans la rue de la Gare. Nous serons fermés les 3 et 4 juin.\" Wat is de hoofdgedachte?",
         opties=["de bakkerij verhuist",
                 "de bakkerij stopt helemaal",
                 "de straat wordt heraangelegd",
                 "de bakkerij verkoopt nieuw brood"],
         antwoord=0,
         uitleg="Déménager is verhuizen. De twee sluitingsdagen zijn een hoofdpunt dat erbij hoort."),
    dict(type="meerkeuze",
         vraag="Lees: \"Sophie habite à Namur depuis 2021. Elle y travaille dans un hôpital.\" Sinds wanneer woont Sophie in Namen?",
         opties=["sinds 2021",
                 "sinds haar geboorte",
                 "sinds enkele weken",
                 "al meer dan dertig jaar"],
         antwoord=0,
         uitleg="Depuis 2021. Let op: het Frans gebruikt daarbij de présent, waar het Engels een present perfect zou nemen."),
    dict(type="waarofniet",
         vraag="Lees: \"L'hôtel a une piscine et un jardin. Le petit déjeuner n'est pas compris.\" Het ontbijt zit bij de prijs.",
         antwoord=False,
         uitleg="N'est pas compris hoort juist bij le petit déjeuner. Het zwembad en de tuin noemt de tekst wel als voorzieningen."),
    dict(type="meerkeuze",
         vraag="Lees: \"Notre équipe a perdu le match, mais tout le monde a bien joué.\" Welke toon heeft deze tekst?",
         opties=["positief",
                 "heel verdrietig",
                 "boos op de spelers",
                 "zakelijk en koel"],
         antwoord=0,
         uitleg="Mais draait de zin om: ondanks de nederlaag is het verhaal positief. Signaalwoorden verraden vaak de toon."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Lees: \"Mes parents ont acheté une maison en Provence. Ils veulent y vivre plus tard.\" Naar wie verwijst ils?",
         opties=["de ouders",
                 "de inwoners van de Provence",
                 "de kinderen",
                 "de vorige eigenaars"],
         antwoord=0,
         uitleg="Een verwijswoord zoekt zijn woord in de vorige zin. Mes parents is het enige meervoud dat past."),
    dict(type="meerkeuze",
         vraag="Lees: \"Mes parents ont acheté une maison en Provence. Ils veulent y vivre plus tard.\" Naar wat verwijst y?",
         opties=["de plaats",
                 "het huis van de buren",
                 "de prijs",
                 "de tijd"],
         antwoord=0,
         uitleg="Y vervangt een plaatsbepaling: en Provence. De fiche noemt y uitdrukkelijk als verwijswoord."),
    dict(type="invultekst",
         vraag="Welk Frans signaalwoord van twee woorden kondigt een tegenstelling aan en begint met par?",
         antwoord=["par contre"],
         uitleg="Par contre zet twee dingen tegenover elkaar, net als mais en cependant."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn Franse signaalwoorden van orde?",
         opties=["d'abord",
                 "puis",
                 "enfin",
                 "parce que"],
         antwoord=[0, 1, 2],
         uitleg="Eerst, dan en ten slotte. Parce que geeft een reden en is dus een ander soort signaalwoord."),
    dict(type="waarofniet",
         vraag="Signaalwoorden helpen je de gedachtegang van een Franse tekst te volgen.",
         antwoord=True,
         uitleg="Daarom noemt de fiche ze bij de leesstrategieën. Mais kondigt een tegenstelling aan, donc een gevolg, d'abord een eerste stap."),
    dict(type="meerkeuze",
         vraag="Lees: \"La soupe était trop salée, donc j'ai bu beaucoup d'eau.\" Wat betekent donc?",
         opties=["dus",
                 "hoewel",
                 "voordat",
                 "zodra"],
         antwoord=0,
         uitleg="Donc geeft het gevolg aan. Als signaalwoord wijst het altijd vooruit."),
    dict(type="meerkeuze",
         vraag="Lees: \"Le chemin était glissant à cause de la pluie, donc nous marchions lentement.\" Wat betekent glissant?",
         opties=["glad",
                 "heel breed",
                 "erg lang",
                 "pas aangelegd"],
         antwoord=0,
         uitleg="De regen en het trage stappen wijzen de weg. Zo leid je de betekenis uit de context af."),
    dict(type="invultekst",
         vraag="Lees: \"Elle était malheureuse.\" Welk Frans woord betekent het omgekeerde van malheureuse? Eén woord.",
         antwoord=["heureuse", "heureux"],
         uitleg="Het voorvoegsel mal- maakt het woord negatief. Zo kan je de betekenis uit de vorm afleiden."),
    dict(type="meerkeuze",
         vraag="Welke visuele hulpmiddelen gebruik je bij een Franse leestekst?",
         opties=["de titel",
                 "de tussentitels",
                 "de foto of de grafiek",
                 "het formaat van het blad"],
         antwoord=[0, 1, 2],
         uitleg="Ze vertellen al veel voor je de eerste zin leest. Het formaat zegt niets over de inhoud."),
    dict(type="waarofniet",
         vraag="Je moet elk onbekend Frans woord in een tekst opzoeken.",
         antwoord=False,
         uitleg="De fiche zegt dat je eerst beslist of het woord echt nodig is. In 120 minuten heb je geen tijd voor meer."),
    dict(type="meerkeuze",
         vraag="Wat vraag je je af bij het communicatiemodel?",
         opties=["van wie is de tekst?",
                 "waarom is hij gemaakt?",
                 "voor wie is hij bedoeld?",
                 "hoeveel bladzijden heeft hij?"],
         antwoord=[0, 1, 2],
         uitleg="Zender, bedoeling en publiek: die drie vragen staan in de fiche."),
    dict(type="meerkeuze",
         vraag="Lees: \"Notre école compte 800 élèves. Le plus vieux bâtiment date de 1912.\" Wat is hier een bijzaak?",
         opties=["het jaartal 1912",
                 "de school zelf",
                 "het aantal leerlingen",
                 "het onderwerp"],
         antwoord=0,
         uitleg="De leeftijd van het gebouw is een detail. Hoofd- en bijzaken scheiden is een strategie uit de fiche."),
    dict(type="meerkeuze",
         vraag="Lees: \"Bien qu'il pleuve, les enfants jouent dehors.\" Wat betekent bien que?",
         opties=["hoewel",
                 "daarom",
                 "zodat",
                 "nadat"],
         antwoord=0,
         uitleg="Bien que kondigt een tegenstelling aan, net als mais en par contre. De regen houdt de kinderen niet binnen."),
    dict(type="waarofniet",
         vraag="Je kennis van het Nederlands of het Engels kan je helpen om een Frans woord te begrijpen.",
         antwoord=True,
         uitleg="Table, information en problème lijken op onze woorden. Let wel op valse vrienden: une pièce is een kamer of een stuk, geen pees."),
    dict(type="meerkeuze",
         vraag="Lees: \"Ma tante est vétérinaire. Elle soigne les animaux malades.\" Wat betekent vétérinaire?",
         opties=["dierenarts",
                 "verpleegster",
                 "iemand van het asiel",
                 "een boer met vee"],
         antwoord=0,
         uitleg="De tweede zin legt het woord uit: ze zorgt voor zieke dieren. Vaak staat de uitleg er gewoon naast."),
    dict(type="waarofniet",
         vraag="Het Franse signaalwoord enfin kondigt een nieuwe reden aan.",
         antwoord=False,
         uitleg="Enfin sluit een rij stappen af: ten slotte. Een reden kondig je aan met parce que of car."),
    dict(type="invultekst",
         vraag="Lees: \"Les jumelles sont nées à Liège. Elles habitent maintenant à Gand.\" Naar wie verwijst elles? Eén woord in het Frans.",
         antwoord=["jumelles", "les jumelles"],
         uitleg="Elles is vrouwelijk meervoud en zoekt les jumelles, de tweelingzussen. Liège en Gand zijn steden."),
    dict(type="meerkeuze",
         vraag="Lees: \"Ce pain est bon marché, savoureux et facile à faire. Essayez-le!\" Wat wil de schrijver?",
         opties=["je overtuigen",
                 "je iets uitleggen in stappen",
                 "een verhaal vertellen",
                 "een mening weergeven"],
         antwoord=0,
         uitleg="Drie voordelen en een aansporing in de imperatief: dat is een persuasieve tekst."),
    dict(type="meerkeuze",
         vraag="Lees: \"À cause de la tempête, le bateau n'est pas parti.\" Wat is de oorzaak?",
         opties=["de storm",
                 "een staking",
                 "een defect",
                 "te weinig reizigers"],
         antwoord=0,
         uitleg="À cause de noemt de oorzaak. De drie andere redenen staan niet in de zin."),
    dict(type="meerkeuze",
         vraag="Lees: \"Grâce à ses amis, il a trouvé un travail.\" Wat betekent grâce à?",
         opties=["dankzij",
                 "ondanks",
                 "zonder",
                 "tegen"],
         antwoord=0,
         uitleg="Grâce à is positief, à cause de eerder negatief. De fiche noemt allebei bij de voorzetselgroepen."),
]
