# -*- coding: utf-8 -*-
"""De Franstalige wereld: gewoontes, landen en reizen.

De vakfiche Frans 1 van de 3de graad dubbele finaliteit (2027) vraagt dat je
overeenkomsten en verschillen kan aangeven tussen je eigen cultuur en culturen
waarin Frans gesproken wordt: het dagelijkse leven, de leefomstandigheden,
gewoontes, sociale verhoudingen, waarden en normen, lichaamstaal en sociale
conventies (deel 1). Deel 2 is het woordveld reizen en landen.

Alleen algemeen bekende gewoontes staan erin. Een gewoonte verzinnen om een
vraag te kunnen maken, zou de leerling iets verkeerd leren.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is la bise?",
         opties=["een kus op de wang",
                 "een handdruk",
                 "een knuffel",
                 "een hoofdknik"],
         antwoord=0,
         uitleg="Faire la bise is zoenen bij een begroeting. Het aantal kussen hangt van de streek af."),
    dict(type="meerkeuze",
         vraag="Op welke dag viert Frankrijk zijn nationale feestdag?",
         opties=["14 juli",
                 "21 juli",
                 "1 mei",
                 "11 november"],
         antwoord=0,
         uitleg="Le quatorze juillet, naar de bestorming van de Bastille in 1789. 21 juli is onze eigen nationale feestdag."),
    dict(type="invultekst",
         vraag="Hoe noem je het lange witte brood dat typisch Frans is? Eén woord in het Frans.",
         antwoord=["baguette", "une baguette", "la baguette"],
         uitleg="Une baguette, bij de boulanger. Un pain is het gewone woord voor brood."),
    dict(type="meerkeuze",
         vraag="Welke landen hebben het Frans als officiële taal?",
         opties=["België",
                 "Zwitserland",
                 "Canada",
                 "Portugal"],
         antwoord=[0, 1, 2],
         uitleg="Ook Luxemburg, Senegal en nog tientallen landen. In Portugal spreekt men Portugees."),
    dict(type="waarofniet",
         vraag="In het Frans spreek je een onbekende volwassene aan met vous.",
         antwoord=True,
         uitleg="Tutoyeren doe je bij vrienden, familie en leeftijdsgenoten. Een onbekende of iemand in een winkel krijgt vous."),
    dict(type="meerkeuze",
         vraag="Wat is la rentrée?",
         opties=["het begin van het schooljaar",
                 "het einde van de vakantie",
                 "de terugkeer van een reis",
                 "de ingang van een gebouw"],
         antwoord=0,
         uitleg="La rentrée scolaire, begin september. Het woord dekt ook het hele weer-aan-de-slag-gaan van het land."),
    dict(type="meerkeuze",
         vraag="Wat is le bac in Frankrijk?",
         opties=["het eindexamen",
                 "een vak op school",
                 "een schooljaar",
                 "een diploma van de hogeschool"],
         antwoord=0,
         uitleg="Le baccalauréat, het examen aan het einde van het secundair. Het geeft toegang tot de universiteit."),
    dict(type="invultekst",
         vraag="Hoe heet de snelle trein van Frankrijk, met drie letters?",
         antwoord=["TGV", "tgv"],
         uitleg="Le TGV, train à grande vitesse. Hij rijdt onder meer van Brussel naar Parijs."),
    dict(type="meerkeuze",
         vraag="Welke munt gebruikt men in Zwitserland?",
         opties=["de frank",
                 "de euro",
                 "de dollar",
                 "het pond"],
         antwoord=0,
         uitleg="De Zwitserse frank. Frankrijk, België en Luxemburg gebruiken wel de euro."),
    dict(type="waarofniet",
         vraag="In het Frans zeg je bonjour voor je iemand iets vraagt.",
         antwoord=True,
         uitleg="De fiche noemt dat uitdrukkelijk bij de strategieën. Zonder bonjour klinkt een vraag onbeschoft."),
    dict(type="meerkeuze",
         vraag="Wat zijn les soldes?",
         opties=["de koopjes",
                 "de belastingen",
                 "de lonen",
                 "de rekeningen"],
         antwoord=0,
         uitleg="Les soldes zijn de koopjesperiodes, in Frankrijk op vaste data. Un solde met de in het enkelvoud is wel een saldo."),
    dict(type="meerkeuze",
         vraag="Welke taal is naast het Frans officieel in heel Canada?",
         opties=["het Engels",
                 "het Spaans van Amerika",
                 "het Duits van Europa",
                 "het Italiaans van Europa"],
         antwoord=0,
         uitleg="Canada heeft het Frans en het Engels als officiële talen. In de provincie Québec is het Frans wel de enige officiële taal."),
    dict(type="waarofniet",
         vraag="Brussel is officieel enkel Franstalig.",
         antwoord=False,
         uitleg="Brussel is tweetalig: Nederlands en Frans. Wallonië is wel Franstalig, met een Duitstalige gemeenschap in het oosten."),
    dict(type="meerkeuze",
         vraag="Welke steden liggen in Wallonië?",
         opties=["Luik",
                 "Namen",
                 "Charleroi",
                 "Gent"],
         antwoord=[0, 1, 2],
         uitleg="Liège, Namur en Charleroi. Namen is de hoofdstad van het Waalse Gewest. Gent ligt in Vlaanderen."),
    dict(type="meerkeuze",
         vraag="Welke Franse woorden horen bij een maaltijd?",
         opties=["l'apéritif",
                 "l'entrée",
                 "le dessert",
                 "le périphérique"],
         antwoord=[0, 1, 2],
         uitleg="Het drankje voor het eten, het voorgerecht en het nagerecht. Le périphérique is de ringweg rond Parijs."),
    dict(type="waarofniet",
         vraag="Het Frans wordt in Afrika nergens gesproken.",
         antwoord=False,
         uitleg="Het is er juist een belangrijke taal: Senegal, Ivoorkust, Congo, Marokko en nog veel meer landen. De meeste Franstaligen ter wereld wonen in Afrika."),
    dict(type="meerkeuze",
         vraag="Wat is la Francophonie?",
         opties=["de Franstalige wereld",
                 "een school in Parijs",
                 "een krant in Québec",
                 "een feest in Wallonië"],
         antwoord=0,
         uitleg="Alle landen en streken waar Frans gesproken wordt, en de organisatie die hen samenbrengt."),
    dict(type="meerkeuze",
         vraag="Hoe noemt men in Frankrijk de ringweg rond Parijs?",
         opties=["le périphérique",
                 "le métro",
                 "le quartier",
                 "le boulevard"],
         antwoord=0,
         uitleg="Le périphérique, kortweg le périph. Le métro is de ondergrondse en un quartier een wijk."),
    dict(type="invultekst",
         vraag="Hoe noem je het middagmaal in het Frans? Twee woorden.",
         antwoord=["le déjeuner", "déjeuner", "dejeuner"],
         uitleg="Le déjeuner. Let op: in België en Zwitserland hoor je ook le dîner voor het middagmaal."),
    dict(type="meerkeuze",
         vraag="Wat betekent lichaamstaal in een gesprek?",
         opties=["wat je zegt zonder woorden",
                 "de woorden die je kiest",
                 "de toon van je stem",
                 "de taal van het land"],
         antwoord=0,
         uitleg="Je houding, je handen, je blik. De fiche noemt lichaamstaal uitdrukkelijk bij de socioculturele aspecten."),
]

DEEL2 = [
    dict(type="invultekst",
         vraag="Hoe zeg je vliegtuig in het Frans? Eén woord.",
         antwoord=["avion", "un avion", "l'avion"],
         uitleg="Un avion. Het vliegveld is l'aéroport."),
    dict(type="meerkeuze",
         vraag="Wat betekent les bagages?",
         opties=["de bagage",
                 "de koffers van de trein",
                 "de reiskosten",
                 "de reisgenoten"],
         antwoord=0,
         uitleg="Les bagages staan in het Frans meestal in het meervoud. Une valise is één koffer."),
    dict(type="meerkeuze",
         vraag="Welke Franse woorden horen bij reizen?",
         opties=["un billet",
                 "une valise",
                 "un passeport",
                 "une poêle"],
         antwoord=[0, 1, 2],
         uitleg="Een ticket, een koffer en een paspoort. Une poêle is een pan en hoort in de keuken."),
    dict(type="meerkeuze",
         vraag="Wat is un aller-retour?",
         opties=["heen en terug",
                 "een enkele rit",
                 "een ticket met korting",
                 "een nachttrein"],
         antwoord=0,
         uitleg="Un aller-retour is heen en terug, un aller simple enkel heen."),
    dict(type="waarofniet",
         vraag="Un voyage en un trajet betekenen in het Frans niet precies hetzelfde.",
         antwoord=True,
         uitleg="Un voyage is de reis als geheel, un trajet het stuk weg dat je aflegt. Un séjour is het verblijf."),
    dict(type="meerkeuze",
         vraag="Wat is une station balnéaire?",
         opties=["een badplaats",
                 "een bergdorp",
                 "een camping",
                 "een vissershaven"],
         antwoord=0,
         uitleg="Balnéaire komt van baden. Une station de ski is dan weer een skioord."),
    dict(type="invultekst",
         vraag="Hoe zeg je grens in het Frans, als je de grens tussen twee landen bedoelt? Eén woord.",
         antwoord=["frontière", "frontiere", "la frontière"],
         uitleg="La frontière. Je steekt hem over: passer la frontière."),
    dict(type="meerkeuze",
         vraag="Wat betekent réserver une chambre?",
         opties=["een kamer boeken",
                 "een kamer opruimen",
                 "een kamer verlaten",
                 "een kamer schilderen"],
         antwoord=0,
         uitleg="Réserver is reserveren of boeken. Een kamer is une chambre, een zaal une salle."),
    dict(type="meerkeuze",
         vraag="Welke Franse woorden zijn vervoermiddelen?",
         opties=["un car",
                 "un ferry",
                 "le métro",
                 "un gîte"],
         antwoord=[0, 1, 2],
         uitleg="Een reisbus, een veerboot en de metro. Un gîte is een vakantiehuisje. Let op: un car is een bus, une voiture een auto."),
    dict(type="waarofniet",
         vraag="Je zegt in het Frans je vais avec le train.",
         antwoord=False,
         uitleg="Het is je vais en train, met en. Zo ook en bus, en voiture, en avion, maar à pied en à vélo."),
    dict(type="meerkeuze",
         vraag="Welke Franse woorden horen bij een probleem op reis?",
         opties=["un retard",
                 "une grève",
                 "une déviation",
                 "un souvenir"],
         antwoord=[0, 1, 2],
         uitleg="Een vertraging, een staking en een omleiding. Un souvenir is een aandenken, en ook een herinnering."),
    dict(type="meerkeuze",
         vraag="Wat is un séjour?",
         opties=["een verblijf",
                 "een vertrek",
                 "een aankomst",
                 "een terugreis"],
         antwoord=0,
         uitleg="Un séjour de trois jours is een verblijf van drie dagen. Le départ is het vertrek en l'arrivée de aankomst."),
    dict(type="invultekst",
         vraag="Hoe zeg je landschap in het Frans? Eén woord.",
         antwoord=["paysage", "un paysage", "le paysage"],
         uitleg="Un paysage. Un beau paysage is een mooi landschap."),
    dict(type="waarofniet",
         vraag="Een inwoner van Zwitserland is in het Frans un Suisse.",
         antwoord=True,
         uitleg="Un Suisse, une Suissesse, en het bijvoeglijk naamwoord is suisse met kleine letter. Volkeren krijgen in het Frans een hoofdletter, hun taal en bijvoeglijke naamwoord niet."),
    dict(type="meerkeuze",
         vraag="Wat is la campagne, als je over een streek spreekt?",
         opties=["het platteland",
                 "de kust",
                 "de bergen",
                 "het stadscentrum"],
         antwoord=0,
         uitleg="À la campagne is op het platteland. Let op: une campagne is ook een campagne, zoals in reclame."),
    dict(type="meerkeuze",
         vraag="Wat betekent à l'étranger?",
         opties=["in het buitenland",
                 "bij vreemden thuis",
                 "op een vreemd uur",
                 "in de buurt"],
         antwoord=0,
         uitleg="Partir à l'étranger is naar het buitenland gaan. Un étranger is een buitenlander of een onbekende."),
    dict(type="meerkeuze",
         vraag="Wat is une visite guidée?",
         opties=["een bezoek met gids",
                 "een wandeling alleen",
                 "een reis per trein",
                 "een bezoek aan familie"],
         antwoord=0,
         uitleg="Guidée komt van un guide, een gids. Un guide is ook het reisboek."),
    dict(type="waarofniet",
         vraag="Un touriste en un voyageur zijn in het Frans precies hetzelfde.",
         antwoord=False,
         uitleg="Un touriste komt kijken en gaat weer naar huis; un voyageur is gewoon iemand die reist, en het woord staat ook op de borden in de trein."),
    dict(type="meerkeuze",
         vraag="Wat betekent un hébergement?",
         opties=["een verblijfplaats",
                 "een reisgezelschap",
                 "een vergoeding",
                 "een wegenkaart"],
         antwoord=0,
         uitleg="Waar je slaapt: un hôtel, une auberge de jeunesse, un gîte. Héberger is onderdak geven."),
    dict(type="meerkeuze",
         vraag="Wat is une chambre d'hôtes?",
         opties=["een kamer bij mensen thuis",
                 "een kamer in een hotel",
                 "een kamer in een jeugdherberg",
                 "een kamer op een camping"],
         antwoord=0,
         uitleg="Het Franse equivalent van een bed and breakfast. Un hôte is zowel de gastheer als de gast, dus let op de zin eromheen."),
]
