# -*- coding: utf-8 -*-
"""Woordvelden: kunst, geschiedenis, literatuur en de samenleving.

Drie van de zestien woordvelden van de vakfiche Frans van de 3de graad dubbele
finaliteit (2027): kunst, cultuur en geschiedenis; literatuur; politiek en
maatschappij. Niveau ERK A2+.

Deel 1 is kunst, cultuur, geschiedenis en literatuur.
Deel 2 is politiek en de samenleving.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is un tableau, als je over kunst spreekt?",
         opties=["een schilderij",
                 "een beeldhouwwerk",
                 "een tekening",
                 "een foto"],
         antwoord=0,
         uitleg="Un tableau is een schilderij, maar ook een bord in de klas en een tabel. Kijk naar de zin eromheen."),
    dict(type="meerkeuze",
         vraag="Welke Franse woorden horen bij een museum?",
         opties=["une exposition",
                 "une salle",
                 "le prix d'entrée",
                 "un arbitre"],
         antwoord=[0, 1, 2],
         uitleg="Een tentoonstelling, een zaal en de inkomprijs. Un arbitre is een scheidsrechter."),
    dict(type="invultekst",
         vraag="Hoe zeg je eeuw in het Frans? Twee woorden.",
         antwoord=["un siècle", "siècle", "le siècle", "siecle"],
         uitleg="Un siècle. Le dix-neuvième siècle is de negentiende eeuw, dus de jaren 1800."),
    dict(type="meerkeuze",
         vraag="Wat betekent un roman?",
         opties=["een roman",
                 "een Romein",
                 "een kortverhaal",
                 "een gedichtenbundel"],
         antwoord=0,
         uitleg="Un roman is een boek, geen Romein: dat is un Romain. Een kortverhaal is une nouvelle."),
    dict(type="waarofniet",
         vraag="Un auteur is in het Frans de schrijver van een boek.",
         antwoord=True,
         uitleg="Un auteur of un écrivain. De schrijver van een toneelstuk is un dramaturge."),
    dict(type="meerkeuze",
         vraag="Wat is un chapitre?",
         opties=["een hoofdstuk",
                 "een bladzijde",
                 "een alinea",
                 "een voorwoord"],
         antwoord=0,
         uitleg="Een boek is in chapitres verdeeld. Een bladzijde is une page."),
    dict(type="meerkeuze",
         vraag="Welke Franse woorden horen bij het theater?",
         opties=["la scène",
                 "le public",
                 "une pièce",
                 "une bouilloire"],
         antwoord=[0, 1, 2],
         uitleg="Het podium, het publiek en een toneelstuk. Une bouilloire is een waterkoker. Let op: une pièce is ook een kamer of een muntstuk."),
    dict(type="invultekst",
         vraag="Hoe zeg je beeldhouwwerk in het Frans? Twee woorden.",
         antwoord=["une sculpture", "sculpture", "une statue"],
         uitleg="Une sculpture, of une statue als het een beeld van een persoon is. De kunstenaar is un sculpteur."),
    dict(type="meerkeuze",
         vraag="Wat is la fiction in een bibliotheek?",
         opties=["de verzonnen verhalen",
                 "de boeken over de echte wereld",
                 "de boeken met tekeningen",
                 "de boeken voor de school"],
         antwoord=0,
         uitleg="Tegenover les documentaires of la non-fiction. Een bibliotheek verdeelt haar boeken zo."),
    dict(type="waarofniet",
         vraag="Une biographie is het verhaal van iemands leven.",
         antwoord=True,
         uitleg="Schrijft iemand over zijn eigen leven, dan is het une autobiographie. Bio komt van het Griekse woord voor leven."),
    dict(type="meerkeuze",
         vraag="Wat is un héritier?",
         opties=["een erfgenaam",
                 "een haarstylist",
                 "een luchtballon",
                 "een eigenaar"],
         antwoord=0,
         uitleg="Van hériter, erven. Un héritage is een erfenis, maar ook een erfgoed."),
    dict(type="meerkeuze",
         vraag="Wat betekent un empire?",
         opties=["een rijk",
                 "een leger",
                 "een opstand",
                 "een verdrag"],
         antwoord=0,
         uitleg="L'Empire romain is het Romeinse Rijk. De keizer is l'empereur."),
    dict(type="waarofniet",
         vraag="Une rime is in het Frans het ritme in de muziek.",
         antwoord=False,
         uitleg="Une rime is een rijm, zoals in een gedicht. Het ritme is le rythme."),
    dict(type="meerkeuze",
         vraag="Welke Franse woorden horen bij geschiedenis?",
         opties=["une guerre",
                 "un traité",
                 "une révolution",
                 "une soucoupe"],
         antwoord=[0, 1, 2],
         uitleg="Een oorlog, een verdrag en een revolutie. Une soucoupe is een schoteltje."),
    dict(type="meerkeuze",
         vraag="Wat betekent ancien voor een naamwoord?",
         opties=["vroeger of oud",
                 "heel groot",
                 "heel ver",
                 "heel duur"],
         antwoord=0,
         uitleg="Mon ancienne école is mijn vroegere school. Staat ancien achter het naamwoord, dan betekent het oud of antiek."),
    dict(type="waarofniet",
         vraag="Un chef d'orchestre is in het Frans een componist.",
         antwoord=False,
         uitleg="Un chef d'orchestre is de dirigent. Een componist is un compositeur."),
    dict(type="meerkeuze",
         vraag="Wat is une intrigue in een verhaal?",
         opties=["de verhaallijn",
                 "de plaats van het verhaal",
                 "het hoofdpersonage",
                 "de schrijver"],
         antwoord=0,
         uitleg="L'intrigue is wat er gebeurt en in welke orde. Het hoofdpersonage is le personnage principal."),
    dict(type="meerkeuze",
         vraag="Wat betekent répéter, als je over theater spreekt?",
         opties=["repeteren",
                 "opvoeren",
                 "toejuichen",
                 "nalezen"],
         antwoord=0,
         uitleg="Une répétition is een repetitie. Répéter betekent ook gewoon herhalen."),
    dict(type="invultekst",
         vraag="Hoe zeg je publiek in het Frans, als je de zaal bedoelt? Twee woorden.",
         antwoord=["le public", "public", "un public"],
         uitleg="Le public zit te kijken of te luisteren. Une foule is een menigte op straat."),
    dict(type="meerkeuze",
         vraag="Wat is un chef-d'oeuvre?",
         opties=["een meesterwerk",
                 "een kopie",
                 "een stuk van een beeld",
                 "een werk van een leerling"],
         antwoord=0,
         uitleg="Letterlijk het hoofd van het werk. Een kopie is une copie of une réplique."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat betekent une élection?",
         opties=["een verkiezing",
                 "een vergadering",
                 "een wetsvoorstel",
                 "een betoging"],
         antwoord=0,
         uitleg="Élire is verkiezen. Je stem is ta voix, en stemmen is voter."),
    dict(type="meerkeuze",
         vraag="Welke Franse woorden horen bij de politiek?",
         opties=["un parti",
                 "un ministre",
                 "le parlement",
                 "une affaire"],
         antwoord=[0, 1, 2],
         uitleg="Een partij, een minister en het parlement. Let op: un parti is een partij, une partie een deel."),
    dict(type="invultekst",
         vraag="Hoe zeg je wet in het Frans? Twee woorden.",
         antwoord=["une loi", "loi", "la loi"],
         uitleg="Une loi. Respecter la loi is de wet naleven."),
    dict(type="meerkeuze",
         vraag="Wat is un citoyen?",
         opties=["een burger",
                 "een inwoner van een stad",
                 "iemand uit het buitenland",
                 "iemand zonder papieren"],
         antwoord=0,
         uitleg="La citoyenneté is het burgerschap. Un habitant is een inwoner."),
    dict(type="waarofniet",
         vraag="Le premier ministre is in België de regeringsleider.",
         antwoord=True,
         uitleg="De koning is het staatshoofd, de eerste minister leidt de regering. In Frankrijk staat de president boven de premier."),
    dict(type="meerkeuze",
         vraag="Wat betekent manifester?",
         opties=["betogen",
                 "stemmen",
                 "vergaderen",
                 "beslissen"],
         antwoord=0,
         uitleg="Une manifestation is een betoging. Een staking is une grève."),
    dict(type="meerkeuze",
         vraag="Welke Franse woorden gaan over de samenleving?",
         opties=["la pauvreté",
                 "l'égalité",
                 "la solidarité",
                 "un ticket"],
         antwoord=[0, 1, 2],
         uitleg="Armoede, gelijkheid en solidariteit. Un ticket is een kaartje."),
    dict(type="invultekst",
         vraag="Hoe zeg je belasting in het Frans? Twee woorden.",
         antwoord=["un impôt", "impôt", "les impôts", "impot"],
         uitleg="Un impôt, in het meervoud les impôts. Une taxe is een heffing op iets bepaalds."),
    dict(type="meerkeuze",
         vraag="Wat betekent un réfugié?",
         opties=["een vluchteling",
                 "een toerist",
                 "een reiziger",
                 "een werknemer"],
         antwoord=0,
         uitleg="Van se réfugier, zijn toevlucht zoeken. Asiel aanvragen is demander l'asile."),
    dict(type="waarofniet",
         vraag="Le conseil communal is in het Frans de gemeenteraad.",
         antwoord=True,
         uitleg="In Frankrijk zegt men le conseil municipal. De burgemeester is le bourgmestre in België en le maire in Frankrijk."),
    dict(type="meerkeuze",
         vraag="Wat is une association caritative?",
         opties=["een goed doel",
                 "een bank",
                 "een verzekering",
                 "een ziekenhuis"],
         antwoord=0,
         uitleg="Une organisation die geld inzamelt om te helpen. Une asbl is de Belgische vereniging zonder winstoogmerk."),
    dict(type="meerkeuze",
         vraag="Wat betekent faire du bénévolat?",
         opties=["vrijwillig helpen",
                 "zich inschrijven",
                 "zich verzekeren",
                 "zich verdedigen"],
         antwoord=0,
         uitleg="Un bénévole is een vrijwilliger. Let op: un volontaire is eerder iemand die zich aanmeldt."),
    dict(type="waarofniet",
         vraag="Un syndicat is in het Frans een handelsbeurs.",
         antwoord=False,
         uitleg="Un syndicat is een vakbond. Een handelsbeurs is un salon of une foire commerciale."),
    dict(type="meerkeuze",
         vraag="Welke Franse woorden horen bij het recht?",
         opties=["un juge",
                 "un tribunal",
                 "un avocat",
                 "un propriétaire"],
         antwoord=[0, 1, 2],
         uitleg="Een rechter, een rechtbank en een advocaat. Un propriétaire is een eigenaar. Let op: un avocat is ook een avocado."),
    dict(type="meerkeuze",
         vraag="Wat betekent la discrimination?",
         opties=["ongelijke behandeling",
                 "een duidelijk verschil",
                 "een goede keuze",
                 "een eerlijke verdeling"],
         antwoord=0,
         uitleg="Iemand slechter behandelen om wie hij is. Het omgekeerde is l'égalité des chances."),
    dict(type="waarofniet",
         vraag="Une majorité betekent in het Frans een minderheid.",
         antwoord=False,
         uitleg="Une majorité is de meerderheid, une minorité de minderheid. Majeur betekent groot of belangrijk."),
    dict(type="meerkeuze",
         vraag="Wat zijn les médias?",
         opties=["de pers en de omroepen",
                 "de scholen van een land",
                 "de partijen in een parlement",
                 "de winkels van een stad"],
         antwoord=0,
         uitleg="Kranten, radio, televisie en het internet. Eén kanaal is un média."),
    dict(type="meerkeuze",
         vraag="Wat is un sondage?",
         opties=["een opiniepeiling",
                 "een verkiezing",
                 "een vergadering",
                 "een wet"],
         antwoord=0,
         uitleg="Mensen vragen wat ze denken. Une enquête is een enquête of een onderzoek."),
    dict(type="meerkeuze",
         vraag="Wat is le contrôle à la frontière?",
         opties=["de grenscontrole",
                 "een controle op school",
                 "een controle bij de dokter",
                 "een controle van de rekening"],
         antwoord=0,
         uitleg="Aan de grens worden je papieren nagekeken. Let op: le contrôle betekent in het Frans ook gewoon een toets."),
    dict(type="meerkeuze",
         vraag="Wat betekent les droits de l'homme?",
         opties=["de mensenrechten",
                 "de rechten van een land",
                 "de rechten van een firma",
                 "de rechten van een school"],
         antwoord=0,
         uitleg="De rechten die elke mens heeft. De Déclaration universelle des droits de l'homme is van 1948."),
]
