# -*- coding: utf-8 -*-
"""Lidwoorden, aanwijzers, bezitters en getallen.

De determinanten van de vakfiche Frans 2 van de 3de graad dubbele finaliteit
(2027): article défini, indéfini, contracté en partitif, het gebruik van de na
een hoeveelheid en na een ontkenning, ce en cette, mon en ma, quel, quelques,
en de hoofd- en rangtelwoorden. Niveau ERK A2+.

Deel 1 zijn de lidwoorden.
Deel 2 zijn de aanwijzers, de bezitters en de getallen.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Welk lidwoord hoort bij maison?",
         opties=["la",
                 "le",
                 "les",
                 "l'"],
         antwoord=0,
         uitleg="Une maison is vrouwelijk, dus la maison. Een woord op -son is meestal vrouwelijk."),
    dict(type="meerkeuze",
         vraag="Hoe zeg je naar de bakker in het Frans?",
         opties=["à la boulangerie",
                 "à le boulangerie",
                 "au boulangerie",
                 "de la boulangerie"],
         antwoord=0,
         uitleg="À plus la blijft à la. Enkel à plus le wordt au en à plus les wordt aux."),
    dict(type="invultekst",
         vraag="Vul het samengetrokken lidwoord in: Je vais ... cinéma.",
         antwoord=["au"],
         uitleg="À plus le cinéma wordt au cinéma. Je vais aux toilettes, met aux voor een meervoud."),
    dict(type="meerkeuze",
         vraag="Welke zin met een partitief lidwoord is juist?",
         opties=["Je bois de l'eau.",
                 "Je bois de eau.",
                 "Je bois du eau.",
                 "Je bois des eau."],
         antwoord=0,
         uitleg="Voor een klinker wordt du of de la altijd de l'. Je mange du pain, de la soupe, des frites."),
    dict(type="waarofniet",
         vraag="Na een ontkenning wordt du, de la of des in het Frans de of d'.",
         antwoord=True,
         uitleg="Je mange du pain wordt je ne mange pas de pain. Na être blijft het wel: ce n'est pas du pain."),
    dict(type="meerkeuze",
         vraag="Welke zin is juist na een hoeveelheid?",
         opties=["beaucoup de livres",
                 "beaucoup des livres",
                 "beaucoup les livres",
                 "beaucoup du livres"],
         antwoord=0,
         uitleg="Na beaucoup, peu, assez, trop en un kilo komt enkel de. Un litre de lait, trop de bruit."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn in het Frans mannelijk?",
         opties=["le fromage",
                 "le village",
                 "le voyage",
                 "le table"],
         antwoord=[0, 1, 2],
         uitleg="Woorden op -age zijn meestal mannelijk. Maar het is la table, want table is vrouwelijk."),
    dict(type="invultekst",
         vraag="Vul in met het juiste lidwoord: Elle a ... vélo. (zij heeft een fiets)",
         antwoord=["un"],
         uitleg="Un vélo, want vélo is mannelijk. Bij een vrouwelijk woord is het une: une voiture."),
    dict(type="meerkeuze",
         vraag="Hoe zeg je ik kom van het station?",
         opties=["Je viens de la gare.",
                 "Je viens du gare.",
                 "Je viens de gare.",
                 "Je viens des gare."],
         antwoord=0,
         uitleg="La gare is vrouwelijk, dus de la gare. De plus le wordt du: je viens du magasin."),
    dict(type="waarofniet",
         vraag="Les is in het Frans het meervoud van le én van la.",
         antwoord=True,
         uitleg="Les livres en les maisons. Het onbepaalde meervoud is des: des livres, des maisons."),
    dict(type="meerkeuze",
         vraag="Welke zin is juist bij een beroep?",
         opties=["Elle est infirmière.",
                 "Elle est une infirmière.",
                 "Elle est l'infirmière.",
                 "Elle est de l'infirmière."],
         antwoord=0,
         uitleg="Na être valt het lidwoord weg bij een beroep. Met een bijvoeglijk naamwoord komt het terug: c'est une bonne infirmière."),
    dict(type="meerkeuze",
         vraag="Welke zin is juist bij een algemene uitspraak?",
         opties=["J'aime le chocolat.",
                 "J'aime du chocolat.",
                 "J'aime de chocolat.",
                 "J'aime un chocolat."],
         antwoord=0,
         uitleg="Spreek je in het algemeen, dan staat er le, la of les. Wil je er wat van, dan is het du chocolat."),
    dict(type="waarofniet",
         vraag="Voor een landnaam gebruikt het Frans nooit een lidwoord.",
         antwoord=False,
         uitleg="Juist omgekeerd: la France, le Portugal, les Pays-Bas. Enkel bij een eiland of een stad valt het soms weg."),
    dict(type="meerkeuze",
         vraag="Welke zinnen hebben een partitief lidwoord nodig?",
         opties=["Je veux ... lait.",
                 "Il achète ... viande.",
                 "Nous prenons ... frites.",
                 "Elle est ... élève."],
         antwoord=[0, 1, 2],
         uitleg="Du lait, de la viande, des frites: een onbepaalde hoeveelheid. Bij elle est une élève hoort geen partitief."),
    dict(type="meerkeuze",
         vraag="Wat is het meervoud van un journal?",
         opties=["des journaux",
                 "des journals",
                 "des journales",
                 "des journalles"],
         antwoord=0,
         uitleg="Woorden op -al krijgen -aux: un animal geeft des animaux, un cheval geeft des chevaux."),
    dict(type="waarofniet",
         vraag="Het Franse woord eau is mannelijk, zoals l' laat vermoeden.",
         antwoord=False,
         uitleg="Eau is vrouwelijk: de l'eau fraîche, met een e achter frais. L' verbergt het geslacht, want l'homme is wel mannelijk."),
    dict(type="meerkeuze",
         vraag="Hoe zeg je de boeken van de leerlingen?",
         opties=["les livres des élèves",
                 "les livres de les élèves",
                 "les livres du élèves",
                 "les livres de élèves"],
         antwoord=0,
         uitleg="De plus les wordt des. Ook à plus les wordt aux: je parle aux élèves."),
    dict(type="meerkeuze",
         vraag="Voor welke woorden wordt le of la tot l'?",
         opties=["école",
                 "hôtel",
                 "ami",
                 "maison"],
         antwoord=[0, 1, 2],
         uitleg="Voor een klinker of een stomme h wordt le of la altijd l': l'école, l'hôtel, l'ami. Maison begint met een m, dus la maison."),
    dict(type="invultekst",
         vraag="Vul in: Je n'ai pas ... frères. (ik heb geen broers)",
         antwoord=["de", "d'"],
         uitleg="Des frères wordt na een ontkenning pas de frères. Voor een klinker is het d': pas d'amis."),
    dict(type="meerkeuze",
         vraag="Welke zin is juist bij een lichaamsdeel?",
         opties=["J'ai mal à la tête.",
                 "J'ai mal à ma tête.",
                 "J'ai mal de la tête.",
                 "J'ai mal une tête."],
         antwoord=0,
         uitleg="Bij een lichaamsdeel kiest het Frans het bepaald lidwoord, niet de bezitter. Je me lave les mains."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Welke aanwijzer hoort bij livre?",
         opties=["ce",
                 "cette",
                 "ces",
                 "cet"],
         antwoord=0,
         uitleg="Ce livre, want livre is mannelijk. Begint het woord met een klinker, dan wordt het cet: cet enfant."),
    dict(type="meerkeuze",
         vraag="Welke zin met cette is juist?",
         opties=["cette semaine",
                 "cette livre",
                 "cette ami",
                 "cette garçon"],
         antwoord=0,
         uitleg="Cette staat enkel voor een vrouwelijk woord: cette semaine, cette maison."),
    dict(type="invultekst",
         vraag="Vul de juiste aanwijzer in: ... arbre est vieux.",
         antwoord=["cet"],
         uitleg="Arbre is mannelijk en begint met een klinker, dus cet arbre. Zonder klinker is het ce: ce jardin."),
    dict(type="meerkeuze",
         vraag="Hoe zeg je mijn zus in het Frans?",
         opties=["ma soeur",
                 "mon soeur",
                 "mes soeur",
                 "ma soeurs"],
         antwoord=0,
         uitleg="De bezitter volgt het woord erna, niet de spreker. Ma soeur, mon frère, mes parents."),
    dict(type="waarofniet",
         vraag="In het Frans is het mon amie, ook al is amie vrouwelijk.",
         antwoord=True,
         uitleg="Voor een klinker wordt ma altijd mon, om de klank: mon amie, mon école, mon histoire."),
    dict(type="meerkeuze",
         vraag="Hoe zeg je hun huis in het Frans?",
         opties=["leur maison",
                 "leurs maison",
                 "son maison",
                 "ses maison"],
         antwoord=0,
         uitleg="Leur bij één ding, leurs bij meer dingen: leurs maisons. Son is van hem of van haar."),
    dict(type="meerkeuze",
         vraag="Welke vormen van quel zijn juist geschreven?",
         opties=["quel jour",
                 "quelle heure",
                 "quels livres",
                 "quelle garçon"],
         antwoord=[0, 1, 2],
         uitleg="Quel past zich aan: quel, quelle, quels, quelles. Bij garçon hoort quel, zonder le."),
    dict(type="invultekst",
         vraag="Vul in: ... est ton âge? (hoe oud ben je)",
         antwoord=["quel"],
         uitleg="Quel est ton âge. Het Frans vraagt naar welk, niet naar hoe oud."),
    dict(type="meerkeuze",
         vraag="Wat betekent quelques?",
         opties=["enkele",
                 "elke",
                 "alle",
                 "geen"],
         antwoord=0,
         uitleg="Quelques amis zijn enkele vrienden. Elke is chaque, alle is tous of toutes."),
    dict(type="waarofniet",
         vraag="Chaque staat in het Frans altijd bij een meervoud.",
         antwoord=False,
         uitleg="Chaque staat altijd bij een enkelvoud: chaque jour, chaque élève. Tous les jours is dan weer meervoud."),
    dict(type="meerkeuze",
         vraag="Hoe schrijf je 80 in het Frans?",
         opties=["quatre-vingts",
                 "quatre-vingt",
                 "octante",
                 "huitante"],
         antwoord=0,
         uitleg="Quatre-vingts met een s, maar quatre-vingt-un zonder. In Zwitserland zegt men wel huitante."),
    dict(type="meerkeuze",
         vraag="Hoe schrijf je 71 in Frankrijk?",
         opties=["soixante et onze",
                 "septante et un",
                 "septante-un",
                 "soixante-dix-un"],
         antwoord=0,
         uitleg="Soixante et onze, dus zestig en elf. In België is het septante et un."),
    dict(type="waarofniet",
         vraag="Het Franse woord mille krijgt een s in deux milles.",
         antwoord=False,
         uitleg="Mille krijgt nooit een s. Cent wel: deux cents, maar deux cent dix zonder s, omdat er nog een getal achter staat."),
    dict(type="meerkeuze",
         vraag="Welke rangtelwoorden zijn juist?",
         opties=["premier",
                 "deuxième",
                 "neuvième",
                 "unième"],
         antwoord=[0, 1, 2],
         uitleg="Eerste is premier of première, daarna komt -ième. Alleen is het nooit unième, wel vingt et unième."),
    dict(type="meerkeuze",
         vraag="Hoe schrijf je de vijfde in het Frans?",
         opties=["cinquième",
                 "cinqième",
                 "cinquème",
                 "cinqueième"],
         antwoord=0,
         uitleg="Er komt een u bij: cinq geeft cinquième. Bij neuf wordt de f een v: neuvième."),
    dict(type="waarofniet",
         vraag="Ces is in het Frans het meervoud van ce én van cette.",
         antwoord=True,
         uitleg="Ces livres en ces maisons. Het meervoud maakt geen verschil tussen mannelijk en vrouwelijk."),
    dict(type="meerkeuze",
         vraag="Hoe zeg je jullie school in het Frans?",
         opties=["votre école",
                 "vos école",
                 "ton école",
                 "notre école"],
         antwoord=0,
         uitleg="Votre bij één ding, vos bij meer: vos écoles. Notre en nos zijn van ons."),
    dict(type="meerkeuze",
         vraag="Welke bezitters kunnen voor parents staan?",
         opties=["mes parents",
                 "nos parents",
                 "leurs parents",
                 "ma parents"],
         antwoord=[0, 1, 2],
         uitleg="Bij een meervoud horen mes, tes, ses, nos, vos en leurs. Ma en mon horen bij een enkelvoud."),
    dict(type="meerkeuze",
         vraag="Hoe zeg je in het Frans dat er geen enkel brood meer is?",
         opties=["Il n'y a plus de pain.",
                 "Il n'y a plus du pain.",
                 "Il y a plus de pain.",
                 "Il n'y a plus le pain."],
         antwoord=0,
         uitleg="Na ne ... plus wordt du gewoon de, net als na pas. Ne ... plus betekent niet meer."),
    dict(type="meerkeuze",
         vraag="Wat betekent le premier janvier?",
         opties=["1 januari",
                 "de eerste week van januari",
                 "de eerste maandag van januari",
                 "eind januari"],
         antwoord=0,
         uitleg="Enkel de eerste van de maand krijgt een rangtelwoord. Daarna is het le deux janvier, le trois janvier."),
]
