# -*- coding: utf-8 -*-
"""Woordvelden: school en werk, geld en verkeer.

Drie van de zestien woordvelden van de vakfiche Frans van de 3de graad dubbele
finaliteit (2027): opleiding, school- en beroepsleven; economie en consumptie;
transport en verkeer. Niveau ERK A2+.

Deel 1 is school, opleiding en werk.
Deel 2 is geld, kopen en het verkeer.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat betekent une matière op school?",
         opties=["een vak",
                 "een leerling",
                 "een lokaal",
                 "een boek"],
         antwoord=0,
         uitleg="Ma matière préférée est l'histoire. Une matière betekent ook materie of stof."),
    dict(type="meerkeuze",
         vraag="Welke Franse woorden horen bij school?",
         opties=["un horaire",
                 "un bulletin",
                 "les devoirs",
                 "un caddie"],
         antwoord=[0, 1, 2],
         uitleg="Een uurrooster, een rapport en het huiswerk. Un caddie is een winkelkar."),
    dict(type="invultekst",
         vraag="Hoe zeg je leerkracht in het Frans? Twee woorden.",
         antwoord=["un professeur", "professeur", "un enseignant", "une enseignante"],
         uitleg="Un professeur, kortweg un prof. De directeur is le directeur."),
    dict(type="meerkeuze",
         vraag="Wat betekent réussir un examen?",
         opties=["slagen",
                 "een examen missen",
                 "een examen uitstellen",
                 "een examen afnemen"],
         antwoord=0,
         uitleg="Réussir is slagen, échouer of rater is niet slagen. Een examen afleggen is passer un examen."),
    dict(type="waarofniet",
         vraag="Passer un examen betekent in het Frans een examen afleggen, niet slagen.",
         antwoord=True,
         uitleg="Een klassieke valse vriend. Slagen is réussir, en je peux passer un examen et le rater."),
    dict(type="meerkeuze",
         vraag="Wat is un diplôme?",
         opties=["een diploma",
                 "een vak op school",
                 "een les van een uur",
                 "een klas vol leerlingen"],
         antwoord=0,
         uitleg="Met de accent circonflexe op de o. Un certificat is een attest."),
    dict(type="meerkeuze",
         vraag="Welke Franse woorden zijn beroepen?",
         opties=["un plombier",
                 "un infirmier",
                 "un vendeur",
                 "un horaire"],
         antwoord=[0, 1, 2],
         uitleg="Een loodgieter, een verpleger en een verkoper. Un horaire is een uurrooster."),
    dict(type="invultekst",
         vraag="Hoe zeg je loon in het Frans? Twee woorden.",
         antwoord=["le salaire", "salaire", "un salaire"],
         uitleg="Le salaire. Un salarié is iemand die in loondienst werkt."),
    dict(type="meerkeuze",
         vraag="Wat betekent postuler pour un emploi?",
         opties=["solliciteren",
                 "ontslag nemen",
                 "overwerken",
                 "promotie maken"],
         antwoord=0,
         uitleg="Une candidature is een sollicitatie en un candidat de kandidaat. Je schrijft une lettre de motivation."),
    dict(type="waarofniet",
         vraag="Un stagiaire is in het Frans iemand die stage doet.",
         antwoord=True,
         uitleg="Un stage is een stage, en un stagiaire de stagiair. Let op: in het Engels is a stage een podium."),
    dict(type="meerkeuze",
         vraag="Wat is un CV?",
         opties=["een overzicht van je loopbaan",
                 "een brief van je werkgever",
                 "een contract voor een job",
                 "een attest van de school"],
         antwoord=0,
         uitleg="Un curriculum vitae. In Frankrijk hoort er traditioneel une lettre de motivation bij."),
    dict(type="meerkeuze",
         vraag="Wat betekent une date limite?",
         opties=["een uiterste datum",
                 "een verloren dag",
                 "een lange pauze",
                 "een vaste afspraak"],
         antwoord=0,
         uitleg="Wanneer iets klaar moet zijn. Respecter la date limite is hem halen."),
    dict(type="waarofniet",
         vraag="Être licencié betekent in het Frans promotie krijgen.",
         antwoord=False,
         uitleg="Het betekent juist ontslagen worden. Promotie krijgen is obtenir une promotion."),
    dict(type="meerkeuze",
         vraag="Welke Franse woorden horen bij werk zoeken?",
         opties=["un entretien",
                 "une offre d'emploi",
                 "une candidature",
                 "une cantine"],
         antwoord=[0, 1, 2],
         uitleg="Een gesprek, een vacature en een sollicitatie. Une cantine is het refter."),
    dict(type="meerkeuze",
         vraag="Wat betekent un travail à temps partiel?",
         opties=["deeltijds werk",
                 "werk voor één dag",
                 "werk in het weekend",
                 "werk zonder loon"],
         antwoord=0,
         uitleg="Tegenover un travail à temps plein. Vakantiewerk is un job d'été."),
    dict(type="waarofniet",
         vraag="Un collègue is in het Frans iemand van je school.",
         antwoord=False,
         uitleg="Un collègue is een collega op het werk. Iemand van je klas is un camarade de classe."),
    dict(type="meerkeuze",
         vraag="Wat is la récréation?",
         opties=["de pauze",
                 "een vak",
                 "een toets",
                 "een straf"],
         antwoord=0,
         uitleg="La récré, de speeltijd of de pauze. La pause de midi is de middagpauze."),
    dict(type="meerkeuze",
         vraag="Wat betekent prendre des notes?",
         opties=["nota's nemen",
                 "briefjes meenemen",
                 "een boek lenen",
                 "een test afleggen"],
         antwoord=0,
         uitleg="Les notes zijn je aantekeningen, maar une note is ook een cijfer of een rekening. Kijk naar de zin eromheen."),
    dict(type="invultekst",
         vraag="Hoe zeg je werkloos in het Frans? Twee woorden.",
         antwoord=["au chômage", "chômage", "sans emploi", "chomage"],
         uitleg="Être au chômage. Un chômeur is een werkloze."),
    dict(type="meerkeuze",
         vraag="Wat betekent une compétence?",
         opties=["een vaardigheid",
                 "een diploma",
                 "een job",
                 "een werkplek"],
         antwoord=0,
         uitleg="Wat je kan, niet wat je weet. Les compétences linguistiques zijn je talenkennis."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat betekent une bonne affaire?",
         opties=["een koopje",
                 "een rekening",
                 "een lening",
                 "een boete"],
         antwoord=0,
         uitleg="Iets goedkoop kopen. Une affaire is ook een zaak of een kwestie."),
    dict(type="meerkeuze",
         vraag="Welke Franse woorden horen bij geld?",
         opties=["un prêt",
                 "les intérêts",
                 "l'épargne",
                 "un passage"],
         antwoord=[0, 1, 2],
         uitleg="Een lening, rente en spaargeld. Un passage is een doorgang of een oversteek."),
    dict(type="invultekst",
         vraag="Hoe zeg je korting in het Frans? Twee woorden.",
         antwoord=["une réduction", "réduction", "un rabais", "reduction"],
         uitleg="Une réduction of un rabais. De koopjesperiode is les soldes."),
    dict(type="meerkeuze",
         vraag="Wat is un ticket de caisse?",
         opties=["een kassabon",
                 "een recept om te koken",
                 "een briefje van de dokter",
                 "een lijst van je aankopen"],
         antwoord=0,
         uitleg="La caisse is de kassa. Let op: une recette is een recept om te koken."),
    dict(type="waarofniet",
         vraag="Se permettre quelque chose betekent in het Frans dat je het kan betalen.",
         antwoord=True,
         uitleg="Je ne peux pas me permettre un nouveau vélo. Letterlijk zich iets toestaan, maar het gaat over geld."),
    dict(type="meerkeuze",
         vraag="Wat betekent payer en espèces?",
         opties=["cash betalen",
                 "met de kaart betalen",
                 "later betalen",
                 "in schijven betalen"],
         antwoord=0,
         uitleg="En espèces is met contant geld. Met de kaart is payer par carte."),
    dict(type="meerkeuze",
         vraag="Welke Franse woorden horen bij het verkeer?",
         opties=["un rond-point",
                 "un embouteillage",
                 "un piéton",
                 "une casserole"],
         antwoord=[0, 1, 2],
         uitleg="Een rotonde, een file en een voetganger. Une casserole is een kookpot."),
    dict(type="invultekst",
         vraag="Hoe zeg je rijbewijs in het Frans? Vul in: le permis de ...",
         antwoord=["conduire"],
         uitleg="Le permis de conduire. Un permis alleen is een vergunning."),
    dict(type="meerkeuze",
         vraag="Wat is l'essence?",
         opties=["benzine",
                 "diesel",
                 "olie voor de motor",
                 "water voor de ruiten"],
         antwoord=0,
         uitleg="Faire le plein d'essence is voltanken. Een tankstation is une station-service."),
    dict(type="waarofniet",
         vraag="Un passage pour piétons is in het Frans een pad voor dieren.",
         antwoord=False,
         uitleg="Het is een zebrapad, voor voetgangers. Un piéton is een voetganger."),
    dict(type="meerkeuze",
         vraag="Wat is une amende in het verkeer?",
         opties=["een boete",
                 "een waarschuwing",
                 "een controle",
                 "een omleiding"],
         antwoord=0,
         uitleg="Payer une amende is een boete betalen. Une déviation is een omleiding."),
    dict(type="meerkeuze",
         vraag="Wat is une autoroute?",
         opties=["een snelweg",
                 "een brug",
                 "een straat in het centrum",
                 "een weg voor fietsers"],
         antwoord=0,
         uitleg="In België zijn dat de wegen met een E ervoor. In Frankrijk moet je er tol betalen: le péage."),
    dict(type="waarofniet",
         vraag="Le trottoir is in het Frans de rijweg voor de auto's.",
         antwoord=False,
         uitleg="Le trottoir is het voetpad, vandaar ook ons woord trottoir. De rijweg is la chaussée."),
    dict(type="meerkeuze",
         vraag="Welke Franse woorden horen bij een winkel?",
         opties=["la caisse",
                 "la file",
                 "le rayon",
                 "le casque"],
         antwoord=[0, 1, 2],
         uitleg="De kassa, de rij en het rek of de afdeling. Un casque is een helm."),
    dict(type="meerkeuze",
         vraag="Wat betekent rembourser?",
         opties=["terugbetalen",
                 "sparen",
                 "iets komen ruilen",
                 "geld gaan lenen"],
         antwoord=0,
         uitleg="Un remboursement is een terugbetaling. Ruilen is échanger."),
    dict(type="waarofniet",
         vraag="La TVA is in het Frans de belasting op de toegevoegde waarde.",
         antwoord=True,
         uitleg="Taxe sur la valeur ajoutée, bij ons de btw. Prix TVA comprise staat op veel rekeningen."),
    dict(type="meerkeuze",
         vraag="Wat is un client?",
         opties=["een klant",
                 "een verkoper",
                 "een leverancier",
                 "een eigenaar"],
         antwoord=0,
         uitleg="Le service clientèle is de klantendienst. Un fournisseur is een leverancier."),
    dict(type="meerkeuze",
         vraag="Wat betekent faire la navette?",
         opties=["pendelen",
                 "verhuizen",
                 "carpoolen",
                 "van job veranderen"],
         antwoord=0,
         uitleg="Elke dag heen en terug naar je werk. Een pendelaar is un navetteur in België, un banlieusard in Frankrijk."),
    dict(type="meerkeuze",
         vraag="Wat is un camion?",
         opties=["een vrachtwagen",
                 "een bestelwagen",
                 "een aanhangwagen",
                 "een ziekenwagen"],
         antwoord=0,
         uitleg="Un camion. Een bestelwagen is une camionnette."),
    dict(type="meerkeuze",
         vraag="Wat betekent l'heure de pointe?",
         opties=["het spitsuur",
                 "een snelle rit",
                 "een uur korting",
                 "een haastige maaltijd"],
         antwoord=0,
         uitleg="De uren waarin iedereen naar of van het werk rijdt. Dan staan de files, les embouteillages."),
]
