# -*- coding: utf-8 -*-
"""Zinsbouw, zinsdelen en congruentie.

Van de vakfiche Frans 2 van de 3de graad dubbele finaliteit (2027): de soorten
zinnen, de nevenschikkende en onderschikkende voegwoorden, de betrekkelijke
bijzin, de congruentie tussen onderwerp en persoonsvorm en tussen
bijvoeglijk en zelfstandig naamwoord, en de zinsdelen sujet, verbe, COD en
COI. Niveau ERK A2+.

Deel 1 zijn de soorten zinnen en de voegwoorden.
Deel 2 zijn de zinsdelen en de congruentie.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Welke zin is een vraagzin?",
         opties=["Tu viens avec nous?",
                 "Tu viens avec nous.",
                 "Viens avec nous!",
                 "Quelle chance!"],
         antwoord=0,
         uitleg="Een vraagzin eindigt op een vraagteken. Het Frans kan ook est-ce que vooraan zetten of de volgorde omwisselen."),
    dict(type="meerkeuze",
         vraag="Welke manieren om een vraag te stellen bestaan in het Frans?",
         opties=["est-ce que vooraan",
                 "de volgorde omwisselen",
                 "enkel de stem omhoog",
                 "pas achteraan zetten"],
         antwoord=[0, 1, 2],
         uitleg="Est-ce que tu viens, viens-tu, of tu viens met een vraagtoon. Pas hoort bij een ontkenning."),
    dict(type="invultekst",
         vraag="Welk voegwoord betekent maar in het Frans?",
         antwoord=["mais"],
         uitleg="Mais verbindt twee gelijke delen: il est petit mais fort."),
    dict(type="meerkeuze",
         vraag="Welke zin is een bevelzin?",
         opties=["Ferme la porte!",
                 "Tu fermes la porte.",
                 "Tu fermes la porte?",
                 "La porte est fermée."],
         antwoord=0,
         uitleg="Bij een bevel staat het werkwoord vooraan en valt het onderwerp weg."),
    dict(type="waarofniet",
         vraag="Een Franse ontkenning heeft twee delen: ne en pas.",
         antwoord=True,
         uitleg="Je ne sais pas. Soms is het tweede deel anders: plus, jamais, rien of personne."),
    dict(type="meerkeuze",
         vraag="Welk voegwoord betekent omdat?",
         opties=["parce que",
                 "pour que",
                 "bien que",
                 "pendant que"],
         antwoord=0,
         uitleg="Parce qu'il pleut. Car betekent ook want, maar staat tussen twee hoofdzinnen."),
    dict(type="meerkeuze",
         vraag="Welke voegwoorden verbinden twee gelijke delen?",
         opties=["et",
                 "ou",
                 "mais",
                 "quand"],
         antwoord=[0, 1, 2],
         uitleg="En, of en maar zetten twee hoofdzinnen naast elkaar. Quand maakt er een bijzin van."),
    dict(type="invultekst",
         vraag="Vul het voegwoord in: Je reste à la maison ... il pleut. (omdat)",
         antwoord=["parce qu'", "parce que", "car"],
         uitleg="Parce qu'il pleut, met een weglatingsteken voor de klinker. Car il pleut kan ook."),
    dict(type="meerkeuze",
         vraag="Wat is een uitroepzin in het Frans?",
         opties=["Quelle belle journée!",
                 "C'est une belle journée.",
                 "Est-ce une belle journée?",
                 "Regarde cette journée."],
         antwoord=0,
         uitleg="Quel of comme vooraan en een uitroepteken achteraan: quelle chance, comme c'est beau."),
    dict(type="waarofniet",
         vraag="Si leidt in het Frans altijd een vraagzin in.",
         antwoord=False,
         uitleg="Si leidt een voorwaarde in: si tu viens, je serai content. Een vraag begint met est-ce que of een vraagwoord."),
    dict(type="meerkeuze",
         vraag="Welke zin bevat een betrekkelijke bijzin?",
         opties=["La fille qui chante est ma soeur.",
                 "La fille chante et danse très bien.",
                 "La fille chante bien.",
                 "Quelle fille chante?"],
         antwoord=0,
         uitleg="Qui chante zegt iets over la fille. Zo'n bijzin begint met qui, que, dont of où."),
    dict(type="meerkeuze",
         vraag="Wat betekent le voegwoord donc?",
         opties=["dus",
                 "want",
                 "maar",
                 "of"],
         antwoord=0,
         uitleg="Il pleut, donc je reste ici. Donc geeft een gevolg."),
    dict(type="waarofniet",
         vraag="Een Franse bijzin met quand staat altijd achteraan de zin.",
         antwoord=False,
         uitleg="Hij kan ook vooraan: quand je rentre, je mange. Dan komt er een komma achter."),
    dict(type="meerkeuze",
         vraag="Welke woorden kunnen een Franse ontkenning afmaken?",
         opties=["jamais",
                 "rien",
                 "plus",
                 "toujours"],
         antwoord=[0, 1, 2],
         uitleg="Ne ... jamais, ne ... rien, ne ... plus. Toujours is juist het omgekeerde: altijd."),
    dict(type="meerkeuze",
         vraag="Welke zin is juist met pour que?",
         opties=["Je parle lentement pour qu'il comprenne.",
                 "Je parle lentement pour qu'il comprend.",
                 "Je parle lentement pour il comprend.",
                 "Je parle lentement pour comprendre il."],
         antwoord=0,
         uitleg="Na pour que volgt de subjonctif. Is het onderwerp hetzelfde, dan zeg je pour plus een infinitief."),
    dict(type="waarofniet",
         vraag="Car en parce que betekenen in het Frans bijna hetzelfde.",
         antwoord=True,
         uitleg="Beide betekenen want of omdat. Car hoort vooral in schrijftaal, parce que hoor je overal."),
    dict(type="meerkeuze",
         vraag="Wat is de plaats van het werkwoord in een Franse mededelende zin?",
         opties=["achter het onderwerp",
                 "altijd vooraan",
                 "altijd achteraan",
                 "voor het onderwerp"],
         antwoord=0,
         uitleg="Sujet, verbe, complément: Marie mange une pomme. Dat is de gewone orde."),
    dict(type="meerkeuze",
         vraag="Welke zin is een wenszin?",
         opties=["Si seulement il faisait beau!",
                 "Il fait beau aujourd'hui.",
                 "Est-ce qu'il fait beau?",
                 "Fais beau temps!"],
         antwoord=0,
         uitleg="Si seulement plus de imparfait drukt een wens uit: als het maar mooi weer was."),
    dict(type="invultekst",
         vraag="Welk voegwoord betekent terwijl of tijdens dat?",
         antwoord=["pendant que"],
         uitleg="Pendant que je travaille. Alleen pendant staat voor een naamwoord: pendant la nuit."),
    dict(type="meerkeuze",
         vraag="Welke zin bevat twee hoofdzinnen?",
         opties=["Je mange et je bois.",
                 "Je mange quand j'ai faim.",
                 "Je mange parce que j'ai faim.",
                 "Je mange ce que tu veux."],
         antwoord=0,
         uitleg="Et zet twee gelijke delen naast elkaar. De drie andere hebben een bijzin."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is het sujet in Marie mange une pomme?",
         opties=["Marie",
                 "mange",
                 "une pomme",
                 "pomme"],
         antwoord=0,
         uitleg="Het sujet doet iets. Je vindt het door qui est-ce qui te vragen: wie eet."),
    dict(type="meerkeuze",
         vraag="Wat is het COD in Marie mange une pomme?",
         opties=["une pomme",
                 "Marie",
                 "mange",
                 "er is geen COD"],
         antwoord=0,
         uitleg="Het COD is het lijdend voorwerp. Je vindt het met quoi of qui achter het werkwoord."),
    dict(type="invultekst",
         vraag="Hoe heet het zinsdeel na à in je parle à Marie? Drie letters.",
         antwoord=["COI", "coi"],
         uitleg="Het complément d'objet indirect staat achter een voorzetsel, meestal à of de."),
    dict(type="meerkeuze",
         vraag="Welke zinnen hebben een COI?",
         opties=["Je téléphone à ma mère.",
                 "Je parle à mon prof.",
                 "Je pense à mes amis.",
                 "Je regarde la télé."],
         antwoord=[0, 1, 2],
         uitleg="À plus een persoon of een ding geeft een COI. Regarder neemt een COD zonder voorzetsel."),
    dict(type="waarofniet",
         vraag="Een Frans COD staat achter het werkwoord zonder voorzetsel.",
         antwoord=True,
         uitleg="Je vois le train. Staat er à of de voor, dan is het een COI: je parle au prof."),
    dict(type="meerkeuze",
         vraag="Welke zin heeft een COD én een COI?",
         opties=["Je donne un livre à Paul.",
                 "Je donne un livre.",
                 "Je parle à Paul.",
                 "Je pense souvent à Paul."],
         antwoord=0,
         uitleg="Un livre is het COD, à Paul het COI. Donner vraagt dikwijls beide."),
    dict(type="meerkeuze",
         vraag="Welke werkwoorden vragen in het Frans een COI met à?",
         opties=["téléphoner",
                 "parler",
                 "ressembler",
                 "regarder"],
         antwoord=[0, 1, 2],
         uitleg="Téléphoner à, parler à, ressembler à. Regarder neemt een COD: je regarde la télé, zonder à."),
    dict(type="invultekst",
         vraag="Vul de juiste vorm in: Les enfants ... contents. (être)",
         antwoord=["sont"],
         uitleg="Les enfants is meervoud, dus sont. En contents krijgt een s, want het hoort bij een meervoud."),
    dict(type="meerkeuze",
         vraag="Welke zin klopt qua congruentie?",
         opties=["Mes soeurs sont grandes.",
                 "Mes soeurs est grandes.",
                 "Mes soeurs sont grand.",
                 "Ma soeurs sont grandes."],
         antwoord=0,
         uitleg="Het werkwoord volgt het onderwerp, en het bijvoeglijk naamwoord volgt het naamwoord in geslacht en getal."),
    dict(type="waarofniet",
         vraag="Een Frans bijvoeglijk naamwoord bij een meervoud krijgt geen s.",
         antwoord=False,
         uitleg="Het krijgt wel een s: des livres intéressants, des filles contentes. Het volgt het naamwoord."),
    dict(type="meerkeuze",
         vraag="Welke vorm hoort bij het onderwerp les élèves et le prof?",
         opties=["travaillent",
                 "travaille",
                 "travailles",
                 "travaillons"],
         antwoord=0,
         uitleg="Twee onderwerpen samen geven een meervoud, dus -ent. Zoek altijd eerst het hele onderwerp."),
    dict(type="meerkeuze",
         vraag="Welk zinsdeel is hier een bepaling van tijd: demain je vais à Paris?",
         opties=["demain",
                 "je",
                 "vais",
                 "à Paris"],
         antwoord=0,
         uitleg="Demain zegt wanneer. À Paris zegt waar, dus dat is een bepaling van plaats."),
    dict(type="waarofniet",
         vraag="In het Frans staat een bepaling van tijd altijd achteraan de zin.",
         antwoord=False,
         uitleg="Ze kan ook vooraan: demain, je vais à Paris. Dan komt er meestal een komma achter, net als in het Nederlands."),
    dict(type="meerkeuze",
         vraag="Welke zinnen hebben een werkwoord dat niet bij het onderwerp past?",
         opties=["Les enfants joue.",
                 "Ma soeur jouent.",
                 "Nous joue.",
                 "Vous jouez."],
         antwoord=[0, 1, 2],
         uitleg="Les enfants jouent, ma soeur joue, nous jouons. Enkel vous jouez klopt."),
    dict(type="meerkeuze",
         vraag="Waar staat het voornaamwoord dat een COD vervangt?",
         opties=["voor het werkwoord",
                 "achter het werkwoord",
                 "helemaal vooraan",
                 "helemaal achteraan"],
         antwoord=0,
         uitleg="Je le vois, je la mange, je les connais. Enkel bij een bevel komt het erachter."),
    dict(type="waarofniet",
         vraag="Het Franse on vraagt een werkwoord in het enkelvoud.",
         antwoord=True,
         uitleg="On parle, on est, on va. De betekenis is we of men, maar de vorm is enkelvoud."),
    dict(type="meerkeuze",
         vraag="Welke zin heeft een juiste woordorde met twee voorwerpen?",
         opties=["Il me donne le livre.",
                 "Il donne me le livre.",
                 "Il le me donne pas.",
                 "Il donne le livre me."],
         antwoord=0,
         uitleg="Me, te, nous en vous staan voor le, la en les. Beide staan voor het werkwoord."),
    dict(type="meerkeuze",
         vraag="Welk zinsdeel ontbreekt in il donne à son frère?",
         opties=["het COD",
                 "het COI",
                 "het sujet",
                 "het werkwoord"],
         antwoord=0,
         uitleg="Donner vraagt ook een COD: il donne un cadeau à son frère. Zonder dat is de zin onvolledig."),
    dict(type="invultekst",
         vraag="Vul de juiste vorm in: Ma soeur et moi ... au cinéma. (aller)",
         antwoord=["allons"],
         uitleg="Ma soeur et moi is hetzelfde als nous, dus allons. Et toi zou vous geven."),
    dict(type="meerkeuze",
         vraag="Welke zin is juist bij een onderwerp met beaucoup de?",
         opties=["Beaucoup d'élèves sont absents.",
                 "Beaucoup d'élèves est absent.",
                 "Beaucoup d'élèves sont absent.",
                 "Beaucoup d'élève sont absents."],
         antwoord=0,
         uitleg="Het werkwoord volgt élèves, dus meervoud. Absents krijgt daarom ook een s."),
]
