# -*- coding: utf-8 -*-
"""Tekstsoorten en de bedoeling van een Franse tekst.

Uit de vakfiche Frans 1 van de 3de graad dubbele finaliteit (2027) komen de zes
soorten teksten die je moet kunnen begrijpen: informatief, persuasief,
opiniërend, prescriptief, narratief en literair (deel 1). Deel 2 gaat over het
verschil tussen een feit en een mening, de bedoeling van de schrijver, voor wie
de tekst bedoeld is, het register met de vous-vorm, en de opbouw van een tekst.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is een informatieve Franse tekst?",
         opties=["een tekst die je iets leert",
                 "een tekst die je wil overtuigen",
                 "een tekst met iemands mening",
                 "een tekst die een verhaal vertelt"],
         antwoord=0,
         uitleg="Un article de journal, une interview, un journal télévisé of een mail aan een klant. De fiche noemt die vier als voorbeelden."),
    dict(type="meerkeuze",
         vraag="Welke Franse teksten zijn persuasief?",
         opties=["une publicité",
                 "une campagne de sécurité",
                 "un tract pour un concert",
                 "une notice de médicament"],
         antwoord=[0, 1, 2],
         uitleg="Persuasief wil je overtuigen of beïnvloeden. Une notice legt uit wat je moet doen en is dus prescriptief."),
    dict(type="invultekst",
         vraag="Hoe noem je een tekst die uitlegt wat of hoe je iets moet doen? Eén woord.",
         antwoord=["prescriptief", "prescriptieve"],
         uitleg="Prescriptief: une recette, une notice, een instructiefilmpje of de veiligheidsvoorschriften van een bedrijf."),
    dict(type="meerkeuze",
         vraag="Lees: \"Mélangez la farine et les oeufs. Ajoutez le lait.\" Welke tekstsoort is dit?",
         opties=["prescriptief",
                 "een verhalende tekst",
                 "een tekst met een mening",
                 "een literaire tekst"],
         antwoord=0,
         uitleg="Twee bevelende zinnen die stap na stap zeggen wat je moet doen. Une recette, dus prescriptief."),
    dict(type="waarofniet",
         vraag="Een boekrecensie is een opiniërende tekst.",
         antwoord=True,
         uitleg="Iemand geeft er zijn mening. Ook een hotelbeoordeling en een reactie op sociale media horen daarbij."),
    dict(type="meerkeuze",
         vraag="Lees: \"L'été dernier, nous avons fait le tour de la Bretagne à vélo. Le troisième jour, il a plu sans arrêt.\" Welke tekstsoort is dit?",
         opties=["narratief",
                 "een tekst die overtuigt",
                 "een tekst met instructies",
                 "een informatieve tekst"],
         antwoord=0,
         uitleg="Un récit de voyage vertelt wat er gebeurde, in de orde waarin het gebeurde. Dat is narratief."),
    dict(type="meerkeuze",
         vraag="Welke Franse teksten noemt de fiche literair?",
         opties=["un poème",
                 "une chanson",
                 "une bande dessinée",
                 "un règlement"],
         antwoord=[0, 1, 2],
         uitleg="Ook een cartoon, een kortverhaal en een fragment uit een roman. Un règlement zegt wat je moet doen en is prescriptief."),
    dict(type="invultekst",
         vraag="Hoe noem je een tekst waarin iemand zijn mening geeft? Eén woord.",
         antwoord=["opiniërend", "opinierend", "opiniërende"],
         uitleg="Opiniërend. Je herkent het aan woorden als je pense, à mon avis, excellent of affreux."),
    dict(type="meerkeuze",
         vraag="Lees: \"Deux pour le prix d'un! Offre valable jusqu'à dimanche.\" Welke tekstsoort is dit?",
         opties=["persuasief",
                 "een verhalende tekst",
                 "een informatieve tekst",
                 "een literaire tekst"],
         antwoord=0,
         uitleg="Een aanbieding wil je tot kopen aanzetten. Het uitroepteken en de korte termijn horen bij reclame."),
    dict(type="waarofniet",
         vraag="Un podcast kan een narratieve tekst zijn.",
         antwoord=True,
         uitleg="De fiche noemt un podcast, un vlog, un récit de voyage en een getuigenis over een eerste werkdag. Narratief gaat over de vorm, niet over het kanaal."),
    dict(type="meerkeuze",
         vraag="Lees: \"Le chien de ma rue connaît mes pas. Il m'attend comme un petit point d'interrogation gris.\" Welke tekstsoort is dit?",
         opties=["literair",
                 "een tekst met instructies",
                 "een tekst met een mening",
                 "een informatieve tekst"],
         antwoord=0,
         uitleg="Een beeld als un petit point d'interrogation gris dient de schoonheid van de tekst. Dat is literair."),
    dict(type="meerkeuze",
         vraag="Lees: \"La Belgique compte onze millions d'habitants et trois langues officielles.\" Welke tekstsoort is dit?",
         opties=["informatief",
                 "een tekst die overtuigt",
                 "een tekst met een mening",
                 "een verhalende tekst"],
         antwoord=0,
         uitleg="Twee feiten, zonder mening en zonder aansporing. Zo'n zin komt uit een leerboek of een krant."),
    dict(type="waarofniet",
         vraag="Une bande dessinée hoort bij de informatieve teksten.",
         antwoord=False,
         uitleg="De fiche zet een strip bij de literaire teksten, samen met een lied, een gedicht en een cartoon. Ze spelen in op emoties."),
    dict(type="meerkeuze",
         vraag="Lees: \"J'ai passé trois nuits dans cet hôtel. Les chambres étaient propres, mais le petit déjeuner était décevant.\" Welke tekstsoort is dit?",
         opties=["opiniërend",
                 "een tekst met instructies",
                 "een informatieve tekst",
                 "een literaire tekst"],
         antwoord=0,
         uitleg="Een hotelbeoordeling waarin iemand zegt wat hij ervan vond. Propre en décevant zijn waardeoordelen."),
    dict(type="meerkeuze",
         vraag="Waaraan herken je een prescriptieve Franse tekst?",
         opties=["aan de imperatief",
                 "aan d'abord en puis",
                 "aan het stappenplan",
                 "aan à mon avis"],
         antwoord=[0, 1, 2],
         uitleg="Imperatieven, signaalwoorden van orde en een rij stappen. À mon avis kondigt juist een mening aan."),
    dict(type="waarofniet",
         vraag="Une interview is volgens de fiche een literaire tekst.",
         antwoord=False,
         uitleg="Een interview staat bij de informatieve teksten, net als een krantenartikel en het nieuws. Literair zijn een gedicht, een lied of een strip."),
    dict(type="meerkeuze",
         vraag="Lees: \"Comment changer un pneu de vélo en cinq étapes.\" Wat verwacht je in deze tekst?",
         opties=["instructies",
                 "de mening van een fietser",
                 "een verhaal over een reis",
                 "feiten over de fietshandel"],
         antwoord=0,
         uitleg="Comment plus een infinitief kondigt een handleiding aan. De titel verraadt de tekstsoort."),
    dict(type="meerkeuze",
         vraag="Lees: \"Votez pour Hanna! Elle écoute les élèves.\" Wat wil deze tekst?",
         opties=["overtuigen",
                 "iets uitleggen in stappen",
                 "informatie geven",
                 "een verhaal vertellen"],
         antwoord=0,
         uitleg="Een oproep met een uitroepteken en een argument erbij. Een verkiezingsaffiche is altijd persuasief."),
    dict(type="meerkeuze",
         vraag="Lees: \"Il était une fois un boulanger qui ne pouvait pas dormir.\" Welke tekstsoort is dit?",
         opties=["literair",
                 "een tekst met instructies",
                 "een informatieve tekst",
                 "een tekst met een mening"],
         antwoord=0,
         uitleg="Il était une fois is de opening van een verhaal. Een kortverhaal of een romanfragment staat bij de literaire teksten."),
    dict(type="meerkeuze",
         vraag="Welke tekstsoort is het nieuws op de radio?",
         opties=["informatief",
                 "een tekst die overtuigt",
                 "een tekst met een mening",
                 "een literaire tekst"],
         antwoord=0,
         uitleg="Het nieuws geeft informatie over een onderwerp. Een commentaar ná het nieuws is wel opiniërend."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Lees: \"Paris compte plus de deux millions d'habitants.\" Is dit een feit of een mening?",
         opties=["een feit",
                 "een mening van de schrijver",
                 "een voorspelling",
                 "een vraag aan de lezer"],
         antwoord=0,
         uitleg="Een getal dat je kan nakijken is een feit. Zodra er beau, meilleur of affreux in staat, wordt het een mening."),
    dict(type="meerkeuze",
         vraag="Lees: \"Paris est la plus belle ville du monde.\" Is dit een feit of een mening?",
         opties=["een mening",
                 "een feit dat je kan nakijken",
                 "een instructie",
                 "een vraag aan de lezer"],
         antwoord=0,
         uitleg="La plus belle kan niemand bewijzen. Een superlatief over smaak is altijd een mening."),
    dict(type="invultekst",
         vraag="Welke twee Franse woorden volgen op à mon, als je in mijn opinie bedoelt? Vul in: à mon ...",
         antwoord=["avis"],
         uitleg="À mon avis. Je pense que en je trouve que doen hetzelfde werk."),
    dict(type="meerkeuze",
         vraag="Welke woorden verraden een mening in een Franse tekst?",
         opties=["je pense",
                 "le meilleur",
                 "affreux",
                 "en 1912"],
         antwoord=[0, 1, 2],
         uitleg="Een gedachte, een waardering en een gevoelswoord. Een jaartal is een feit."),
    dict(type="waarofniet",
         vraag="Een Franse tekst kan feiten en meningen door elkaar bevatten.",
         antwoord=True,
         uitleg="Een recensie noemt vaak eerst de feiten en geeft daarna het oordeel. Als lezer houd je die twee apart."),
    dict(type="meerkeuze",
         vraag="Lees: \"Madame, Monsieur, je vous écris au sujet de votre annonce.\" Voor wie is deze tekst bedoeld?",
         opties=["een onbekende",
                 "een vriend",
                 "een familielid",
                 "een klasgenoot"],
         antwoord=0,
         uitleg="Madame, Monsieur en de vous-vorm wijzen op iemand met wie je geen nauwe band hebt. De fiche vraagt dat je dat publiek kan bepalen."),
    dict(type="meerkeuze",
         vraag="Lees: \"Salut! Ça te dit, une pizza ce soir?\" Welk register is dit?",
         opties=["informeel",
                 "neutraal en zakelijk",
                 "heel formeel",
                 "ouderwets"],
         antwoord=0,
         uitleg="Salut en de tu-vorm horen bij vrienden. In een mail aan een onbekende zou je Bonjour en vous gebruiken."),
    dict(type="invultekst",
         vraag="Welk Frans woord zeg je volgens de fiche altijd eerst als je een onbekende iets vraagt? Eén woord.",
         antwoord=["bonjour"],
         uitleg="Bonjour. Dat staat letterlijk bij de strategieën: zonder bonjour klinkt een vraag onbeschoft in het Frans."),
    dict(type="meerkeuze",
         vraag="Uit welke drie delen bestaat een goed opgebouwde tekst?",
         opties=["inleiding",
                 "midden",
                 "slot",
                 "voetnoot"],
         antwoord=[0, 1, 2],
         uitleg="Inleiding, midden en slot: zo staat het bij de vereisten in de fiche. Een voetnoot hoort er niet verplicht bij."),
    dict(type="waarofniet",
         vraag="Volgens de fiche gebruik je de vous-vorm in een mail aan een volwassene die je niet goed kent.",
         antwoord=True,
         uitleg="Dat staat letterlijk bij de strategieën, samen met de conditionnel de politesse: je voudrais in plaats van je veux."),
    dict(type="meerkeuze",
         vraag="Lees: \"Ne vous appuyez pas contre les portes.\" Waar vind je zo'n tekst?",
         opties=["op de trein",
                 "in een roman",
                 "in een recensie",
                 "in een brief aan een vriend"],
         antwoord=0,
         uitleg="Een waarschuwing in de gebiedende wijs met de vous-vorm. Zulke bordjes hangen in het openbaar vervoer."),
    dict(type="meerkeuze",
         vraag="Lees: \"Notre magasin sera fermé le 21 juillet.\" Wat is de bedoeling van deze tekst?",
         opties=["informeren",
                 "de lezer overtuigen",
                 "een mening geven",
                 "een verhaal vertellen"],
         antwoord=0,
         uitleg="Eén mededeling, zonder aansporing en zonder oordeel. De bedoeling is de tweede vraag van het communicatiemodel."),
    dict(type="waarofniet",
         vraag="Een gepast register betekent dat je in het Frans altijd zo formeel mogelijk schrijft.",
         antwoord=False,
         uitleg="Gepast betekent passend bij de lezer: formeel of informeel, zegt de fiche. Aan een vriend schrijf je gewoon tu."),
    dict(type="meerkeuze",
         vraag="Welke woorden passen in een formele Franse mail?",
         opties=["Je voudrais",
                 "Merci d'avance",
                 "Cordialement",
                 "Bisous"],
         antwoord=[0, 1, 2],
         uitleg="De eerste drie zijn hoffelijk en neutraal. Bisous schrijf je enkel aan familie of goede vrienden."),
    dict(type="meerkeuze",
         vraag="Lees: \"Je suis vraiment désolé d'avoir oublié ton anniversaire!\" Wat doet de schrijver?",
         opties=["zich verontschuldigen",
                 "iemand uitnodigen",
                 "iemand bedanken",
                 "informatie vragen"],
         antwoord=0,
         uitleg="Désolé, nog versterkt met vraiment. De fiche noemt dat bij de alledaagse sociale contacten."),
    dict(type="waarofniet",
         vraag="Je veux un café klinkt in het Frans hoffelijker dan je voudrais un café.",
         antwoord=False,
         uitleg="Net omgekeerd: je voudrais is de conditionnel de politesse en klinkt veel vriendelijker. De fiche noemt die vorm uitdrukkelijk."),
    dict(type="meerkeuze",
         vraag="Lees: \"Tu voudrais venir à ma fête samedi?\" Wat doet de schrijver?",
         opties=["uitnodigen",
                 "zich verontschuldigen",
                 "bedanken",
                 "iets uitleggen"],
         antwoord=0,
         uitleg="Tu voudrais venir is een hoffelijke uitnodiging. Met de vous-vorm wordt het vous voudriez venir."),
    dict(type="meerkeuze",
         vraag="Lees: \"Merci beaucoup pour ton aide hier.\" Wat doet de schrijver?",
         opties=["bedanken",
                 "uitnodigen",
                 "een mening geven",
                 "iets voorstellen"],
         antwoord=0,
         uitleg="Merci beaucoup pour plus een naamwoord. Formeler: je vous remercie de votre aide."),
    dict(type="meerkeuze",
         vraag="Wat is het kanaal van een tekst in het communicatiemodel?",
         opties=["de mail of de blog",
                 "de taal van de tekst",
                 "de lengte van de tekst",
                 "de mening van de schrijver"],
         antwoord=0,
         uitleg="Het kanaal is de weg die je boodschap neemt: een mail, een blogbericht, een gesprek. De fiche vraagt die vraag bij het schrijfplan."),
    dict(type="meerkeuze",
         vraag="Lees: \"On se retrouve à la gare à six heures?\" Wat doet de schrijver?",
         opties=["iets voorstellen",
                 "zich verontschuldigen",
                 "bedanken",
                 "een mening geven"],
         antwoord=0,
         uitleg="On se retrouve met een vraagteken is een voorstel. Ook dat hoort bij de alledaagse sociale contacten."),
]
