# -*- coding: utf-8 -*-
"""Woordvelden: dagelijks leven, eten en drinken, wonen.

Drie van de zestien woordvelden van de vakfiche Frans van de 3de graad dubbele
finaliteit (2027). Niveau ERK A2+, dus frequente woorden, woordcombinaties en
vaste uitdrukkingen.

Deel 1 is het dagelijkse en sociale leven, met eten en drinken.
Deel 2 is wonen en het huishouden.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat betekent un parent in het Frans?",
         opties=["een familielid",
                 "enkel een vader",
                 "enkel een moeder",
                 "een vriend van school"],
         antwoord=0,
         uitleg="Les parents zijn de ouders, maar un parent kan ook een verwant zijn. Un ami is een vriend."),
    dict(type="meerkeuze",
         vraag="Welke Franse woorden duiden familie aan?",
         opties=["une tante",
                 "un neveu",
                 "un cousin",
                 "un locataire"],
         antwoord=[0, 1, 2],
         uitleg="Een tante, een neefje en een kozijn. Un locataire is een huurder."),
    dict(type="invultekst",
         vraag="Hoe zeg je ontbijt in het Frans? Twee woorden.",
         antwoord=["le petit déjeuner", "petit déjeuner", "petit dejeuner"],
         uitleg="Le petit déjeuner. Let op: le déjeuner alleen is in Frankrijk het middagmaal."),
    dict(type="meerkeuze",
         vraag="Wat betekent faire la grasse matinée?",
         opties=["uitslapen",
                 "vet eten 's morgens",
                 "poetsen in de voormiddag",
                 "vroeg opstaan"],
         antwoord=0,
         uitleg="Een vaste uitdrukking voor lang blijven liggen. Letterlijk vertalen levert onzin op."),
    dict(type="waarofniet",
         vraag="In het Frans zeg je faire une erreur en niet donner une erreur.",
         antwoord=True,
         uitleg="Faire hoort bij maken of doen: faire une erreur, faire la vaisselle, faire les courses. Donner is geven."),
    dict(type="meerkeuze",
         vraag="Wat is un goûter?",
         opties=["een vieruurtje",
                 "een warme maaltijd",
                 "een drankje bij het eten",
                 "een tafel in een café"],
         antwoord=0,
         uitleg="Le goûter is het hapje in de namiddag, vooral voor kinderen. Goûter als werkwoord betekent proeven."),
    dict(type="meerkeuze",
         vraag="Welke Franse woorden zijn dranken?",
         opties=["le thé",
                 "le jus",
                 "le cidre",
                 "le poivre"],
         antwoord=[0, 1, 2],
         uitleg="Thee, sap en cider. Le poivre is peper en hoort bij de kruiden."),
    dict(type="invultekst",
         vraag="Hoe zeg je avondmaal in het Frans? Twee woorden.",
         antwoord=["le dîner", "dîner", "le souper", "diner"],
         uitleg="Le dîner in Frankrijk. In België en Zwitserland hoor je le souper voor de avondmaaltijd."),
    dict(type="meerkeuze",
         vraag="Wat betekent épicé?",
         opties=["pikant",
                 "heel koud",
                 "zonder zout",
                 "net gebakken"],
         antwoord=0,
         uitleg="Un plat épicé is een pikant gerecht. Les épices zijn de specerijen."),
    dict(type="waarofniet",
         vraag="Une entrée is in het Frans een voorgerecht.",
         antwoord=True,
         uitleg="Une entrée, un plat principal, un dessert: zo loopt een Franse maaltijd. Une entrée is ook een ingang."),
    dict(type="meerkeuze",
         vraag="Wat betekent à emporter?",
         opties=["om mee te nemen",
                 "om hier te eten",
                 "om te betalen",
                 "om te delen"],
         antwoord=0,
         uitleg="Sur place ou à emporter? vraagt men in de zaak: hier eten of meenemen?"),
    dict(type="meerkeuze",
         vraag="Wat betekent s'entendre bien avec quelqu'un?",
         opties=["goed overeenkomen",
                 "iemand goed horen",
                 "met iemand meerijden",
                 "iemand iets uitleggen"],
         antwoord=0,
         uitleg="Je m'entends bien avec ma soeur. Letterlijk zou het zich goed horen zijn, maar het betekent overeenkomen."),
    dict(type="waarofniet",
         vraag="Een raad geven is in het Frans donner un conseiller.",
         antwoord=False,
         uitleg="Het is donner un conseil. Un conseiller is de persoon die raad geeft, een raadgever."),
    dict(type="meerkeuze",
         vraag="Welke Franse woorden horen bij een feest?",
         opties=["un cadeau",
                 "une bougie",
                 "un invité",
                 "une armoire"],
         antwoord=[0, 1, 2],
         uitleg="Een cadeau, een kaars en een genodigde. Une armoire is een kleerkast."),
    dict(type="meerkeuze",
         vraag="Wat is un loisir?",
         opties=["een vrijetijdsbesteding",
                 "een vak op school",
                 "een deel van je werk",
                 "een kamer in het huis"],
         antwoord=0,
         uitleg="Les loisirs zijn de hobby's en de vrije tijd. Le temps libre is de vrije tijd zelf."),
    dict(type="waarofniet",
         vraag="Je zegt in het Frans je vais au cinéma avec le bus.",
         antwoord=False,
         uitleg="Het moet en bus zijn. Avec gebruik je voor personen en dingen die je meeneemt: avec ma soeur, avec un parapluie."),
    dict(type="meerkeuze",
         vraag="Wat is un voisin?",
         opties=["een buur",
                 "een huisgenoot",
                 "een huisbaas",
                 "een voorbijganger"],
         antwoord=0,
         uitleg="Un voisin, une voisine. De buurt is le quartier of le voisinage."),
    dict(type="meerkeuze",
         vraag="Wat betekent faire la vaisselle?",
         opties=["afwassen",
                 "je handen wassen",
                 "de was ophangen",
                 "zich klaarmaken"],
         antwoord=0,
         uitleg="La vaisselle is de vaat. De was doen is faire la lessive."),
    dict(type="invultekst",
         vraag="Hoe zeg je lepel in het Frans? Twee woorden.",
         antwoord=["une cuillère", "cuillère", "cuiller", "une cuiller"],
         uitleg="Une cuillère. Een vork is une fourchette en een mes un couteau."),
    dict(type="meerkeuze",
         vraag="Wat betekent en avoir assez de quelque chose?",
         opties=["er genoeg van hebben",
                 "er honger van krijgen",
                 "ergens goed in zijn",
                 "er trots op zijn"],
         antwoord=0,
         uitleg="J'en ai assez de ce temps: ik ben dit weer beu. Let op het woordje en, dat naar iets terugverwijst."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is une maison jumelée?",
         opties=["een halfopen woning",
                 "een vrijstaande woning",
                 "een rijhuis in het midden",
                 "een huis op een boerderij"],
         antwoord=0,
         uitleg="Jumelé komt van jumeau, tweeling: twee huizen aan elkaar. Vrijstaand is une maison quatre façades."),
    dict(type="meerkeuze",
         vraag="Welke Franse woorden noemen een ruimte in een huis?",
         opties=["le couloir",
                 "le grenier",
                 "la cave",
                 "le camion"],
         antwoord=[0, 1, 2],
         uitleg="De gang, de zolder en de kelder. Un camion is een vrachtwagen."),
    dict(type="invultekst",
         vraag="Hoe zeg je zolder in het Frans? Twee woorden.",
         antwoord=["le grenier", "grenier", "un grenier"],
         uitleg="Le grenier. Daar bewaren mensen hun oude spullen."),
    dict(type="meerkeuze",
         vraag="Wat betekent le loyer?",
         opties=["de huur",
                 "een lening",
                 "een verzekering",
                 "een belasting"],
         antwoord=0,
         uitleg="Louer un appartement is een appartement huren, en le loyer is het geld dat je betaalt. De eigenaar is le propriétaire."),
    dict(type="waarofniet",
         vraag="Un appartement is in het Frans een appartement.",
         antwoord=True,
         uitleg="Met twee p's en één t, anders dan bij ons. Un immeuble is het gebouw waarin het ligt."),
    dict(type="meerkeuze",
         vraag="Wat is le rez-de-chaussée?",
         opties=["het gelijkvloers",
                 "de eerste verdieping",
                 "de kelder",
                 "de tuin"],
         antwoord=0,
         uitleg="Daarboven begint le premier étage. Een lift is un ascenseur."),
    dict(type="meerkeuze",
         vraag="Welke Franse woorden horen bij het huishouden?",
         opties=["un aspirateur",
                 "une bouilloire",
                 "un robinet",
                 "une cravate"],
         antwoord=[0, 1, 2],
         uitleg="Een stofzuiger, een waterkoker en een kraan. Une cravate is een das."),
    dict(type="invultekst",
         vraag="Hoe zeg je gordijn in het Frans? Twee woorden.",
         antwoord=["un rideau", "rideau", "le rideau"],
         uitleg="Un rideau, in het meervoud des rideaux met een x. Een rolluik is un volet."),
    dict(type="meerkeuze",
         vraag="Wat is une tâche ménagère?",
         opties=["een klusje in huis",
                 "een vlek op het tapijt",
                 "een kamer in het huis",
                 "een huurcontract"],
         antwoord=0,
         uitleg="Les tâches ménagères zijn de huishoudelijke karweien. Let op het accent: une tache zonder accent is een vlek."),
    dict(type="waarofniet",
         vraag="Les meubles staat in het Frans altijd in het enkelvoud.",
         antwoord=False,
         uitleg="Les meubles is een gewoon meervoud: les meubles sont neufs. Eén meubel is un meuble. Het Engelse furniture is wel ontelbaar."),
    dict(type="meerkeuze",
         vraag="Wat is une poubelle?",
         opties=["een vuilnisbak",
                 "een bezem",
                 "een emmer",
                 "een doek"],
         antwoord=0,
         uitleg="Mettre à la poubelle is weggooien. Een emmer is un seau en een bezem un balai."),
    dict(type="meerkeuze",
         vraag="Wat betekent déménager?",
         opties=["verhuizen",
                 "een huis bouwen",
                 "een huis verkopen",
                 "een huis opruimen"],
         antwoord=0,
         uitleg="Nous déménageons le mois prochain. Emménager is er juist intrekken."),
    dict(type="meerkeuze",
         vraag="Welke Franse woorden horen bij een tuin?",
         opties=["la pelouse",
                 "la haie",
                 "la terrasse",
                 "l'escalier"],
         antwoord=[0, 1, 2],
         uitleg="Het grasveld, de haag en het terras. Un escalier is een trap en staat binnen."),
    dict(type="waarofniet",
         vraag="In het Frans zeg je à la maison als je thuis bedoelt.",
         antwoord=True,
         uitleg="Je suis à la maison, of chez moi. Rentrer à la maison is naar huis gaan."),
    dict(type="meerkeuze",
         vraag="Wat is un locataire?",
         opties=["een huurder",
                 "een eigenaar",
                 "een makelaar",
                 "een bouwer"],
         antwoord=0,
         uitleg="Tegenover le propriétaire, de eigenaar. Louer kan zowel huren als verhuren betekenen."),
    dict(type="meerkeuze",
         vraag="Wat betekent douillet?",
         opties=["gezellig en warm",
                 "heel groot",
                 "pas gebouwd",
                 "erg duur"],
         antwoord=0,
         uitleg="Un lit douillet is een behaaglijk bed. Voor een gezellige kamer hoor je ook une pièce agréable."),
    dict(type="meerkeuze",
         vraag="Wat is une chaudière?",
         opties=["een ketel",
                 "een koelkast",
                 "een ventilator",
                 "een wasmachine"],
         antwoord=0,
         uitleg="De ketel die je huis verwarmt. Een koelkast is un frigo en een wasmachine une machine à laver."),
    dict(type="waarofniet",
         vraag="Une villa is in het Frans een klein huisje op het platteland.",
         antwoord=False,
         uitleg="Une villa is juist een groot vrijstaand huis. Een klein huisje op het platteland is une chaumière of un gîte."),
    dict(type="meerkeuze",
         vraag="Wat betekent ranger sa chambre?",
         opties=["zijn kamer opruimen",
                 "zijn kamer poetsen",
                 "zijn kamer verven",
                 "zijn kamer verlaten"],
         antwoord=0,
         uitleg="Ranger is op zijn plaats zetten. Poetsen met water en zeep is nettoyer."),
    dict(type="meerkeuze",
         vraag="Wat zijn les toilettes in het Frans?",
         opties=["het toilet",
                 "de gang",
                 "het bad",
                 "de kelder"],
         antwoord=0,
         uitleg="Les toilettes staan in het meervoud. De badkamer is la salle de bains."),
]
