# -*- coding: utf-8 -*-
"""Woordvelden: gezondheid, natuur en duurzaamheid.

Drie van de zestien woordvelden van de vakfiche Frans van de 3de graad dubbele
finaliteit (2027): gezondheid en psychologie, natuur en dieren, en milieu en
duurzaamheid. Niveau ERK A2+.

Deel 1 is gezondheid en gevoelens.
Deel 2 is natuur, dieren en het milieu.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat betekent j'ai mal à la gorge?",
         opties=["ik heb keelpijn",
                 "ik heb een gebroken arm",
                 "ik heb koorts",
                 "ik heb rugpijn"],
         antwoord=0,
         uitleg="Avoir mal à plus het lichaamsdeel. Hoofdpijn is j'ai mal à la tête en buikpijn j'ai mal au ventre."),
    dict(type="meerkeuze",
         vraag="Welke Franse woorden zijn klachten bij een dokter?",
         opties=["la toux",
                 "la fièvre",
                 "une allergie",
                 "un portefeuille"],
         antwoord=[0, 1, 2],
         uitleg="Hoest, koorts en een allergie. Un portefeuille is een portefeuille met geld in."),
    dict(type="invultekst",
         vraag="Hoe zeg je apotheek in het Frans? Twee woorden.",
         antwoord=["la pharmacie", "pharmacie", "une pharmacie"],
         uitleg="La pharmacie, en de apotheker is le pharmacien. Daar haal je je médicaments."),
    dict(type="meerkeuze",
         vraag="Wat betekent guérir?",
         opties=["genezen",
                 "ziek worden",
                 "zich laten inenten",
                 "pijn hebben"],
         antwoord=0,
         uitleg="Elle est guérie: ze is genezen. La guérison is de genezing."),
    dict(type="waarofniet",
         vraag="Une ordonnance is in het Frans een voorschrift van de dokter.",
         antwoord=True,
         uitleg="Met dat papier haal je je medicijnen bij de apotheker. In Québec zegt men une prescription."),
    dict(type="meerkeuze",
         vraag="Wat is un médecin généraliste?",
         opties=["een huisarts",
                 "een tandarts",
                 "een ziekenhuis",
                 "een verpleegkundige"],
         antwoord=0,
         uitleg="Le généraliste tegenover le spécialiste. Een tandarts is le dentiste."),
    dict(type="meerkeuze",
         vraag="Welke Franse woorden gaan over gevoelens?",
         opties=["nerveux",
                 "seul",
                 "fier",
                 "bondé"],
         antwoord=[0, 1, 2],
         uitleg="Nerveus, alleen en trots. Bondé betekent overvol en zegt niets over een gevoel."),
    dict(type="invultekst",
         vraag="Hoe zeg je koorts in het Frans? Twee woorden.",
         antwoord=["la fièvre", "fièvre", "de la fièvre", "fievre"],
         uitleg="Avoir de la fièvre is koorts hebben. De thermometer is le thermomètre."),
    dict(type="meerkeuze",
         vraag="Wat betekent être stressé?",
         opties=["gespannen zijn",
                 "heel moe zijn",
                 "verkouden zijn",
                 "verveeld zijn"],
         antwoord=0,
         uitleg="Le stress is overgenomen uit het Engels. Verveeld is s'ennuyer en moe fatigué."),
    dict(type="waarofniet",
         vraag="Je zegt in het Frans j'ai une douleur dans ma tête voor hoofdpijn.",
         antwoord=False,
         uitleg="Een Franstalige zegt j'ai mal à la tête. Une douleur bestaat wel, maar niet in die zin."),
    dict(type="meerkeuze",
         vraag="Wat is un pansement?",
         opties=["een pleister",
                 "een spuit",
                 "een zalf",
                 "een pil"],
         antwoord=0,
         uitleg="Un pansement of un sparadrap. Een zalf is une pommade en een spuit une piqûre."),
    dict(type="meerkeuze",
         vraag="Wat betekent une alimentation équilibrée?",
         opties=["gevarieerd eten",
                 "zo weinig mogelijk eten",
                 "enkel groenten eten",
                 "drie keer per dag eten"],
         antwoord=0,
         uitleg="Équilibré betekent in evenwicht. Un régime is wel een dieet om te vermageren."),
    dict(type="waarofniet",
         vraag="Avoir le moral à zéro betekent in het Frans zich slecht voelen.",
         antwoord=True,
         uitleg="Le moral is je gemoed. Avoir le moral betekent dus goedgezind zijn."),
    dict(type="meerkeuze",
         vraag="Welke Franse woorden horen bij het ziekenhuis?",
         opties=["une opération",
                 "une ambulance",
                 "un infirmier",
                 "une tondeuse"],
         antwoord=[0, 1, 2],
         uitleg="Een operatie, een ziekenwagen en een verpleger. Une tondeuse is een grasmachine of een tondeuse."),
    dict(type="meerkeuze",
         vraag="Wat betekent prendre du poids?",
         opties=["bijkomen",
                 "vermageren",
                 "iets optillen",
                 "zich wegen"],
         antwoord=0,
         uitleg="Letterlijk gewicht nemen. Vermageren is perdre du poids of maigrir."),
    dict(type="waarofniet",
         vraag="La santé mentale gaat in het Frans over je lichaam.",
         antwoord=False,
         uitleg="La santé mentale is je geestelijke gezondheid; je lichaam is la santé physique. De fiche zet psychologie uitdrukkelijk bij dit woordveld."),
    dict(type="meerkeuze",
         vraag="Wat is un bilan de santé?",
         opties=["een controle bij de dokter",
                 "een rekening van het ziekenhuis",
                 "een bezoek aan een zieke",
                 "een briefje voor school"],
         antwoord=0,
         uitleg="Un bilan is een balans of een stand van zaken. Een doktersattest is un certificat médical."),
    dict(type="meerkeuze",
         vraag="Wat betekent épuisé?",
         opties=["uitgeput",
                 "opgewonden",
                 "ontspannen",
                 "verbaasd"],
         antwoord=0,
         uitleg="Sterker dan fatigué: helemaal op. Épuisé betekent ook uitverkocht, bij een boek."),
    dict(type="invultekst",
         vraag="Hoe zeg je slaap in het Frans, als je het naamwoord bedoelt? Twee woorden.",
         antwoord=["le sommeil", "sommeil", "du sommeil"],
         uitleg="Le sommeil. Avoir sommeil betekent slaap hebben, en dormir is slapen."),
    dict(type="meerkeuze",
         vraag="Wat betekent prendre soin de soi?",
         opties=["goed voor jezelf zorgen",
                 "iets gemakkelijk vinden",
                 "iets snel afwerken",
                 "iets meenemen"],
         antwoord=0,
         uitleg="Prends soin de toi! zegt men bij een afscheid of aan iemand die ziek is."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat betekent la faune sauvage?",
         opties=["de wilde dieren",
                 "een wild feest",
                 "een wilde rivier",
                 "een wild bos"],
         antwoord=0,
         uitleg="La faune zijn de dieren, la flore de planten. Een natuurgebied is une réserve naturelle."),
    dict(type="meerkeuze",
         vraag="Welke Franse woorden zijn dieren?",
         opties=["un hérisson",
                 "un hibou",
                 "un écureuil",
                 "un érable"],
         antwoord=[0, 1, 2],
         uitleg="Een egel, een uil en een eekhoorn. Un érable is een esdoorn, dus een boom."),
    dict(type="invultekst",
         vraag="Hoe zeg je boom in het Frans? Twee woorden.",
         antwoord=["un arbre", "arbre", "l'arbre"],
         uitleg="Un arbre. Een bos is une forêt en een tak une branche."),
    dict(type="meerkeuze",
         vraag="Wat betekent les déchets?",
         opties=["het afval",
                 "de glasbak",
                 "de vuilniswagen",
                 "de papierzak"],
         antwoord=0,
         uitleg="Les déchets staan in het meervoud. Les ordures en les poubelles gaan over hetzelfde."),
    dict(type="waarofniet",
         vraag="Recycler betekent in het Frans hergebruiken.",
         antwoord=True,
         uitleg="Le recyclage is de verwerking van afval tot nieuw materiaal. Réutiliser is iets gebruiken zoals het is."),
    dict(type="meerkeuze",
         vraag="Wat betekent la sécheresse?",
         opties=["de droogte",
                 "een overstroming",
                 "een storm op zee",
                 "een koude winter"],
         antwoord=0,
         uitleg="Van sec, droog. Een overstroming is une inondation."),
    dict(type="meerkeuze",
         vraag="Welke Franse woorden horen bij het milieu?",
         opties=["la pollution",
                 "les émissions",
                 "le gaspillage",
                 "les meubles"],
         antwoord=[0, 1, 2],
         uitleg="Vervuiling, uitstoot en verspilling. Les meubles zijn de meubels en horen bij wonen."),
    dict(type="invultekst",
         vraag="Hoe zeg je milieu in het Frans, als je de natuur rond ons bedoelt? Twee woorden.",
         antwoord=["l'environnement", "environnement", "le milieu"],
         uitleg="L'environnement, met twee n's in het midden. Milieu bestaat ook in het Frans, maar betekent eerder het midden."),
    dict(type="meerkeuze",
         vraag="Wat betekent les énergies renouvelables?",
         opties=["hernieuwbare energie",
                 "energie uit steenkool",
                 "energie uit aardgas",
                 "energie uit kernsplitsing"],
         antwoord=0,
         uitleg="Wind, zon en water raken niet op. De andere drie zijn dat juist niet."),
    dict(type="waarofniet",
         vraag="Le climat en le temps betekenen in het Frans hetzelfde.",
         antwoord=False,
         uitleg="Le temps is het weer van vandaag, le climat het gemiddelde over jaren. Le temps betekent ook de tijd."),
    dict(type="meerkeuze",
         vraag="Wat is une espèce?",
         opties=["een soort",
                 "een kudde",
                 "een nest",
                 "een kooi"],
         antwoord=0,
         uitleg="Une espèce menacée is een bedreigde soort. En espèces betekent wel contant, met geld."),
    dict(type="meerkeuze",
         vraag="Wat betekent disparaître?",
         opties=["verdwijnen",
                 "wegtrekken",
                 "in slaap gaan",
                 "van kleur veranderen"],
         antwoord=0,
         uitleg="Une espèce disparue is een uitgestorven soort. Paraître is verschijnen, dis- maakt het omgekeerd."),
    dict(type="waarofniet",
         vraag="Een boom die zijn bladeren verliest noem je in het Frans un conifère.",
         antwoord=False,
         uitleg="Un conifère is juist een naaldboom die groen blijft. Een boom die zijn blad verliest is un arbre à feuilles caduques."),
    dict(type="meerkeuze",
         vraag="Welke Franse woorden gaan over het weer?",
         opties=["une averse",
                 "une brise",
                 "un orage",
                 "un trottoir"],
         antwoord=[0, 1, 2],
         uitleg="Een regenbui, een briesje en een onweer. Un trottoir is het voetpad."),
    dict(type="meerkeuze",
         vraag="Wat is l'empreinte carbone?",
         opties=["de koolstofvoetafdruk",
                 "een voetspoor in de sneeuw",
                 "een zwarte vlek",
                 "een merk op een boom"],
         antwoord=0,
         uitleg="Une empreinte is een afdruk, ook van een vinger. Het begrip is letterlijk vertaald, net als bij ons."),
    dict(type="waarofniet",
         vraag="Un ruisseau is in het Frans een beek.",
         antwoord=True,
         uitleg="Kleiner dan une rivière, en une rivière is kleiner dan un fleuve, dat in de zee uitmondt."),
    dict(type="meerkeuze",
         vraag="Wat is une récolte?",
         opties=["een oogst",
                 "een ploeg",
                 "een schuur",
                 "een tractor"],
         antwoord=0,
         uitleg="Récolter is oogsten. De gewassen op het veld zijn les cultures."),
    dict(type="meerkeuze",
         vraag="Wat betekent durable?",
         opties=["duurzaam",
                 "houdbaar in de koelkast",
                 "vol te houden met moeite",
                 "goedkoop in het gebruik"],
         antwoord=0,
         uitleg="Le développement durable is duurzame ontwikkeling. Het komt van durer: duren."),
    dict(type="meerkeuze",
         vraag="Wat is une inondation?",
         opties=["een overstroming",
                 "een hittegolf",
                 "een aardbeving",
                 "een lawine"],
         antwoord=0,
         uitleg="Van inonder, overstromen. Een hittegolf is une canicule en een aardbeving un séisme."),
    dict(type="meerkeuze",
         vraag="Wat betekent abattre un arbre?",
         opties=["een boom omhakken",
                 "een boom planten",
                 "een boom verzorgen",
                 "een boom verplaatsen"],
         antwoord=0,
         uitleg="La déforestation is het kappen van hele bossen. Planten is planter."),
]
