# -*- coding: utf-8 -*-
"""Argumentatie, feiten en meningen, en drogredenen — dubbele finaliteit.

De fiche vraagt: feiten en meningen onderscheiden, stelling en standpunt
bepalen, argumenten en tegenargumenten herkennen, de conclusie weergeven,
drogredenen herkennen, en de soorten argumentatie kennen (vergelijking, oorzaak
en gevolg, wetenschappelijk onderzoek, cijfers en statistieken, een autoriteit).
"""

DEEL1 = [
    dict(
        type="meerkeuze",
        vraag="Wat is een feit?",
        opties=[
            "een uitspraak die je kan nagaan",
            "een uitspraak waar de meeste mensen het mee eens zijn",
            "een uitspraak van iemand met gezag",
            "een uitspraak zonder cijfers erin",
        ],
        antwoord=0,
        uitleg="Controleerbaar, met een bron of een meting. Of het klopt is een tweede vraag.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is een mening?",
        opties=[
            "een uitspraak die een standpunt of waardering bevat",
            "een uitspraak die altijd onjuist is",
            "een uitspraak die niemand kan begrijpen",
            "een uitspraak zonder enig argument",
        ],
        antwoord=0,
        uitleg="Je kan ze niet nagaan, enkel beargumenteren. 'Dit is de beste film van het jaar' is zo'n uitspraak.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is een stelling in een argumentatieve tekst?",
        opties=[
            "de bewering die de schrijver wil verdedigen",
            "het eerste argument van de schrijver",
            "het besluit dat de lezer zelf trekt",
            "de vraag waarmee de tekst begint",
        ],
        antwoord=0,
        uitleg="Alles in de tekst staat in dienst van die ene bewering: de school moet later beginnen, de taks moet weg.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je een reden die een stelling ondersteunt?",
        antwoord=["een argument", "argument"],
        uitleg="Een tegenargument pleit tegen de stelling.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke uitspraak is een feit?",
        opties=[
            "de bibliotheek sluit om achttien uur",
            "de bibliotheek sluit veel te vroeg",
            "de bibliotheek is het mooiste gebouw van de stad",
            "de bibliotheek zou langer open moeten blijven",
        ],
        antwoord=0,
        uitleg="Het sluitingsuur staat aan de deur. De drie andere uitspraken zijn waarderingen of eisen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke uitspraken zijn meningen?",
        opties=[
            "de nieuwe brug is veel te duur geweest",
            "de stad had het geld beter aan scholen besteed",
            "de brug kostte achttien miljoen euro",
            "de brug werd in maart geopend",
        ],
        antwoord=[0, 1],
        uitleg="Te duur en beter besteed zijn waarderingen. Het bedrag en de datum zijn na te gaan.",
    ),
    dict(
        type="waarofniet",
        vraag="Een feit en een mening kunnen in dezelfde zin staan.",
        antwoord=True,
        uitleg="'De brug kostte achttien miljoen, veel te veel voor zo'n klein dorp': eerst het feit, dan het oordeel.",
    ),
    dict(
        type="waarofniet",
        vraag="Een mening is minder waard dan een feit en hoort niet in een goede tekst.",
        antwoord=False,
        uitleg="In een opiniestuk is de mening het punt. Ze moet alleen als mening te herkennen zijn.",
    ),
    dict(
        type="waarofniet",
        vraag="Een tekst die zijn stelling nergens uitspreekt, kan toch een standpunt hebben.",
        antwoord=True,
        uitleg="Door de keuze van woorden, voorbeelden en getuigen kan een tekst sturen zonder één eis te formuleren.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is een tweezijdige argumentatie?",
        opties=[
            "een tekst die ook de tegenargumenten behandelt",
            "een tekst die twee stellingen tegelijk verdedigt",
            "een tekst met twee schrijvers",
            "een tekst met twee besluiten",
        ],
        antwoord=0,
        uitleg="Door de tegenargumenten te noemen en te weerleggen wordt een betoog sterker, niet zwakker.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke soorten argumentatie bestaan er?",
        opties=[
            "argumentatie op basis van vergelijking",
            "argumentatie op basis van cijfers en statistieken",
            "argumentatie op basis van spelling",
            "argumentatie op basis van tekstlengte",
        ],
        antwoord=[0, 1],
        uitleg="Verder nog: oorzaak en gevolg, wetenschappelijk onderzoek, en een beroep op een autoriteit.",
    ),
    dict(
        type="meerkeuze",
        vraag="'In Nederland werkt het ook, dus bij ons zal het werken.' Welke soort argumentatie is dat?",
        opties=[
            "argumentatie op basis van vergelijking",
            "argumentatie op basis van cijfers",
            "argumentatie op basis van een autoriteit",
            "argumentatie op basis van onderzoek",
        ],
        antwoord=0,
        uitleg="Ze is maar zo sterk als de gelijkenis tussen de twee gevallen. Daar zit meestal de zwakte.",
    ),
    dict(
        type="meerkeuze",
        vraag="'Negen op de tien tandartsen raden dit aan.' Welke soort argumentatie is dat?",
        opties=[
            "een beroep op een autoriteit, met een cijfer erbij",
            "argumentatie op basis van een vergelijking",
            "argumentatie op basis van oorzaak en gevolg",
            "een tweezijdige argumentatie",
        ],
        antwoord=0,
        uitleg="De vraag is dan: welke tandartsen, hoeveel werden er gevraagd, en door wie betaald?",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je het besluit dat een schrijver uit zijn argumenten trekt?",
        antwoord=["de conclusie", "conclusie", "het besluit"],
        uitleg="Ze staat meestal in het slot van de tekst.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarom is 'veel mensen vinden dat' zelden een sterk argument?",
        opties=[
            "omdat een grote groep zich ook kan vergissen",
            "omdat mensen geen meningen mogen hebben",
            "omdat je nooit kan weten hoeveel mensen er zijn",
            "omdat een mening geen argument mag zijn",
        ],
        antwoord=0,
        uitleg="Dat heet een beroep op de massa. Het zegt iets over populariteit, niet over juistheid.",
    ),
    dict(
        type="waarofniet",
        vraag="Een cijfer in een tekst is altijd een feit en dus altijd juist.",
        antwoord=False,
        uitleg="Een cijfer is controleerbaar, en dus ook te weerleggen. Verkeerde cijfers bestaan.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een tekst stelt: 'Sinds de camera's er staan, zijn er minder inbraken.' Welke soort argumentatie is dat?",
        opties=[
            "argumentatie op basis van oorzaak en gevolg",
            "argumentatie op basis van een vergelijking",
            "een beroep op een autoriteit",
            "een tweezijdige argumentatie",
        ],
        antwoord=0,
        uitleg="Pas op: dat na elkaar gebeurt, hoeft niet door elkaar te gebeuren. Misschien daalden de inbraken overal.",
    ),
    dict(
        type="waarofniet",
        vraag="Wie een stelling verdedigt, moet ook zeggen wat zijn tegenstanders beweren.",
        antwoord=False,
        uitleg="Het moet niet, maar het helpt wel: een weerlegd tegenargument maakt het betoog geloofwaardiger.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is het verschil tussen een stelling en een standpunt?",
        opties=[
            "een stelling is de bewering, een standpunt de kant die je kiest",
            "een stelling is korter dan een standpunt",
            "een stelling staat vooraan, een standpunt achteraan",
            "er is geen verschil, het zijn twee woorden voor hetzelfde",
        ],
        antwoord=0,
        uitleg="In de praktijk liggen ze dicht bij elkaar: het standpunt is je positie tegenover de stelling.",
    ),
    dict(
        type="waarofniet",
        vraag="Een argumentatieve tekst kan ook feiten bevatten.",
        antwoord=True,
        uitleg="De sterkste argumenten steunen juist op feiten: cijfers, onderzoek, voorbeelden.",
    ),
]

DEEL2 = [
    dict(
        type="meerkeuze",
        vraag="Wat is een drogreden?",
        opties=[
            "een argument dat alleen lijkt te kloppen",
            "een argument dat in een vreemde taal staat",
            "een argument dat uit cijfers bestaat",
            "een argument zonder bronvermelding",
        ],
        antwoord=0,
        uitleg="Het werkt op het gevoel of op de vorm van een redenering, niet op de inhoud.",
    ),
    dict(
        type="meerkeuze",
        vraag="'Jij hebt daar geen verstand van, dus je ongelijk is duidelijk.' Welke drogreden is dat?",
        opties=[
            "een aanval op de persoon",
            "een beroep op de massa",
            "een verkeerde vergelijking",
            "een cirkelredenering",
        ],
        antwoord=0,
        uitleg="Wie de persoon aanvalt, laat het argument zelf ongemoeid. Dat heet ad hominem.",
    ),
    dict(
        type="meerkeuze",
        vraag="'Als we dit toelaten, staan we morgen voor de afgrond.' Welke drogreden is dat?",
        opties=[
            "het hellend vlak",
            "een aanval op de persoon",
            "een cirkelredenering",
            "een beroep op gezag",
        ],
        antwoord=0,
        uitleg="De ene stap wordt zonder bewijs aan een ramp gekoppeld.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je een argument dat alleen lijkt te kloppen?",
        antwoord=["een drogreden", "drogreden"],
        uitleg="Het is een redenering met een gat erin dat je niet meteen ziet.",
    ),
    dict(
        type="meerkeuze",
        vraag="'Dat is zo omdat het nu eenmaal zo is.' Welke drogreden is dat?",
        opties=[
            "een cirkelredenering",
            "een hellend vlak",
            "een beroep op de massa",
            "een verkeerde vergelijking",
        ],
        antwoord=0,
        uitleg="Het argument is de stelling zelf, in andere woorden. Er komt niets bij.",
    ),
    dict(
        type="waarofniet",
        vraag="Een drogreden kan overtuigend klinken en toch niets bewijzen.",
        antwoord=True,
        uitleg="Dat is net het probleem: ze werkt. Daarom moet je ze kunnen benoemen.",
    ),
    dict(
        type="waarofniet",
        vraag="Wie een drogreden gebruikt, heeft daarmee bewezen dat zijn stelling fout is.",
        antwoord=False,
        uitleg="Een slecht argument voor iets dat toch waar is, bestaat. Het argument sneuvelt, de stelling niet.",
    ),
    dict(
        type="waarofniet",
        vraag="'Iedereen doet het' is een geldig argument in een betoog.",
        antwoord=False,
        uitleg="Dat is een beroep op de massa. Hoeveel mensen iets doen, zegt niets over of het goed is.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke uitspraken over tegenargumenten kloppen?",
        opties=[
            "ze pleiten tegen de stelling van de schrijver",
            "een schrijver kan ze noemen om ze te weerleggen",
            "ze maken een betoog altijd zwakker",
            "ze mogen alleen in het slot staan",
        ],
        antwoord=[0, 1],
        uitleg="Een betoog dat de tegenkant verzwijgt, valt om zodra de lezer er zelf aan denkt.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een opiniestuk eindigt met: 'Daarom moet de stad de fietspaden verbreden.' Wat is dat?",
        opties=[
            "de conclusie van het betoog",
            "een tegenargument",
            "een feit over de stad",
            "een drogreden",
        ],
        antwoord=0,
        uitleg="Ze volgt uit de argumenten en formuleert wat er moet gebeuren.",
    ),
    dict(
        type="meerkeuze",
        vraag="Hoe beoordeel je een argument dat op onderzoek steunt?",
        opties=[
            "je kijkt wie het onderzoek deed en hoe groot het was",
            "je neemt het over, want onderzoek is altijd juist",
            "je verwerpt het, want onderzoek is altijd betaald",
            "je kijkt enkel of er een cijfer in staat",
        ],
        antwoord=0,
        uitleg="Opdrachtgever, aantal deelnemers en methode beslissen hoe zwaar het weegt.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je een argument dat de persoon aanvalt in plaats van zijn redenering?",
        antwoord=["een persoonlijke aanval", "ad hominem", "persoonlijke aanval"],
        uitleg="Het is de bekendste drogreden in debatten en in reacties online.",
    ),
    dict(
        type="waarofniet",
        vraag="Bij een luistertekst herken je dezelfde argumentatiesoorten als bij een leestekst.",
        antwoord=True,
        uitleg="In een debat of een podcast werken vergelijkingen, cijfers en gezagsargumenten precies zo.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke stappen zet je bij het beoordelen van een argumentatieve tekst?",
        opties=[
            "je bepaalt eerst de stelling van de schrijver",
            "je zoekt de argumenten en de tegenargumenten",
            "je telt de woorden en de alinea's",
            "je verbetert de spelling van de tekst",
        ],
        antwoord=[0, 1],
        uitleg="Daarna geef je de conclusie weer en kijk je of de argumenten die conclusie dragen.",
    ),
    dict(
        type="meerkeuze",
        vraag="'Deze maatregel werkt, want de minister zegt het.' Wat is het probleem?",
        opties=[
            "gezag alleen is geen bewijs",
            "een minister mag niets zeggen over maatregelen",
            "het argument bevat geen cijfers",
            "de zin bevat geen signaalwoord",
        ],
        antwoord=0,
        uitleg="Een beroep op een autoriteit kan sterk zijn als die deskundig én onafhankelijk is. Hier is hij belanghebbend.",
    ),
    dict(
        type="waarofniet",
        vraag="Een vergelijking blijft even sterk als argument, ook wanneer de twee gevallen sterk van elkaar verschillen.",
        antwoord=False,
        uitleg="Hoe minder de gevallen op elkaar lijken, hoe minder het ene over het andere zegt. Daarom is de eerste vraag bij zo'n argument altijd of die twee wel genoeg op elkaar lijken.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een reclametekst zegt: 'Tachtig procent van de gebruikers is tevreden.' Welke vraag stel je?",
        opties=[
            "hoeveel gebruikers werden er bevraagd, en door wie?",
            "waarom is het geen honderd procent?",
            "staat dat cijfer ook in andere reclame?",
            "hoe lang bestaat het product al?",
        ],
        antwoord=0,
        uitleg="Tachtig procent van tien mensen is iets anders dan van tienduizend. En wie vraagt, bepaalt wat men antwoordt.",
    ),
    dict(
        type="waarofniet",
        vraag="Een tekst kan een juiste conclusie hebben op basis van zwakke argumenten.",
        antwoord=True,
        uitleg="Daarom beoordeel je de argumenten en de conclusie apart. Een slecht betoog voor een goed idee bestaat.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat doe je als een tekst feiten en meningen door elkaar gebruikt zonder onderscheid?",
        opties=[
            "je scheidt ze zelf en noemt welk deel wat is",
            "je verwerpt de hele tekst als onbruikbaar",
            "je neemt alles over als feit",
            "je neemt alles over als mening",
        ],
        antwoord=0,
        uitleg="Dat is precies wat er van je gevraagd wordt bij het beoordelen van een argumentatieve tekst.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een debat gaat over een nieuwe taks. Eén spreker zegt enkel dat de tegenstander rijk is. Wat ontbreekt?",
        opties=[
            "een argument over de taks zelf",
            "een conclusie aan het einde",
            "een signaalwoord in zijn betoog",
            "een cijfer over de opbrengst",
        ],
        antwoord=0,
        uitleg="Hij valt de persoon aan. Over de taks heeft hij nog niets gezegd.",
    ),
]
