# -*- coding: utf-8 -*-
"""Genres, fictie en non-fictie, en je eigen leeservaring — dubbele finaliteit.

De fiche vraagt: fictie en non-fictie onderscheiden, de courante genres kennen
(roman, novelle, kortverhaal, jeugdroman, strip, graphic novel, toneel, poezie,
non-fictie), weten waarin ze verschillen, en je eigen leeservaring verwoorden en
onderbouwen. Geen literatuurgeschiedenis en geen stromingen.
"""

DEEL1 = [
    dict(
        type="meerkeuze",
        vraag="Wat is fictie?",
        opties=[
            "een verhaal dat door de schrijver bedacht is",
            "een verhaal dat in een vreemde taal geschreven is",
            "een verhaal dat niet in een boek is uitgegeven",
            "een verhaal dat zich in de toekomst afspeelt",
        ],
        antwoord=0,
        uitleg="Fictie mag naar de werkelijkheid verwijzen, maar ze is niet het verslag ervan.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is non-fictie?",
        opties=[
            "een tekst die de werkelijkheid wil weergeven",
            "een tekst zonder enige vorm van opbouw",
            "een tekst die korter is dan honderd bladzijden",
            "een tekst die enkel voor scholen geschreven is",
        ],
        antwoord=0,
        uitleg="Een biografie, een reisverhaal, een handboek, een journalistiek boek.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke genres horen bij fictie?",
        opties=[
            "de roman en de novelle",
            "het kortverhaal en de jeugdroman",
            "de biografie en het handboek",
            "het jaarverslag en het nieuwsbericht",
        ],
        antwoord=[0, 1],
        uitleg="Ook toneel, poezie, de strip en de graphic novel kunnen fictie zijn.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je een tekst die de werkelijkheid wil weergeven in plaats van ze te bedenken?",
        antwoord=["non-fictie", "nonfictie"],
        uitleg="Het is geen genre, maar een hele groep genres.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is het verschil tussen een roman en een novelle?",
        opties=[
            "een novelle is korter en heeft minder verhaallijnen dan een roman",
            "een novelle is altijd waargebeurd en een roman nooit",
            "een novelle wordt in afleveringen uitgegeven en een roman niet",
            "een novelle heeft geen personages en een roman wel",
        ],
        antwoord=0,
        uitleg="De grens is niet scherp. Een novelle draait meestal om één lijn en één wending.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat kenmerkt een kortverhaal?",
        opties=[
            "het is kort en draait vaak om één enkel moment",
            "het is bedoeld voor kinderen tot twaalf jaar",
            "het wordt altijd in de tegenwoordige tijd verteld",
            "het wordt altijd samen met tekeningen uitgegeven",
        ],
        antwoord=0,
        uitleg="Er is weinig ruimte, dus elke zin moet dienen. Vaak staat het in een bundel met andere verhalen.",
    ),
    dict(
        type="waarofniet",
        vraag="Een boek over een echte gebeurtenis kan toch fictie zijn.",
        antwoord=True,
        uitleg="Zodra de schrijver gesprekken en gedachten bedenkt, is het een roman en geen verslag.",
    ),
    dict(
        type="waarofniet",
        vraag="Een graphic novel is hetzelfde als een stripverhaal voor kinderen.",
        antwoord=False,
        uitleg="Ze gebruikt dezelfde middelen, maar ze is doorgaans langer en voor een ouder publiek.",
    ),
    dict(
        type="waarofniet",
        vraag="Poezie hoeft niet te rijmen om poezie te zijn.",
        antwoord=True,
        uitleg="Veel moderne gedichten rijmen niet. Het ritme, de regelval en de beeldtaal doen het werk.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is kenmerkend voor een toneeltekst?",
        opties=[
            "de tekst bestaat haast volledig uit dialoog en regieaanwijzingen",
            "de tekst wordt altijd in de verleden tijd geschreven",
            "de tekst heeft nooit meer dan drie personages",
            "de tekst bevat per bladzijde één beschrijving",
        ],
        antwoord=0,
        uitleg="Wat een verteller in een roman zou zeggen, moet hier uit de mond van personages komen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke middelen gebruikt een strip die een roman niet heeft?",
        opties=[
            "tekstballonnen en de indeling in kaders",
            "het wit tussen de kaders, waarin tijd verstrijkt",
            "een verteller die de gedachten weergeeft",
            "een opbouw in hoofdstukken met tussenkoppen",
        ],
        antwoord=[0, 1],
        uitleg="De lezer vult zelf in wat er tussen twee kaders gebeurde. Dat is het eigenste middel van de strip.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is een jeugdroman?",
        opties=[
            "een roman die geschreven is voor jonge lezers",
            "een roman waarin alle personages jong zijn",
            "een roman die door een jonge schrijver gemaakt is",
            "een roman die korter is dan tweehonderd bladzijden",
        ],
        antwoord=0,
        uitleg="Het gaat om het beoogde publiek, niet om de leeftijd van de schrijver of van de personages.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je een kort verhaal dat vaak om één enkel moment draait?",
        antwoord=["een kortverhaal", "kortverhaal"],
        uitleg="Het staat meestal in een bundel samen met andere.",
    ),
    dict(
        type="meerkeuze",
        vraag="Je leest een boek waarin een echte politicus bedachte gesprekken voert. Wat is dat?",
        opties=[
            "fictie, want de gesprekken zijn verzonnen",
            "non-fictie, want de politicus heeft echt bestaan",
            "een biografie, want er staat een echte persoon in",
            "een reportage, want er wordt over de politiek verteld",
        ],
        antwoord=0,
        uitleg="Zodra er iets bedacht is, is het fictie. Dat het op feiten steunt, verandert dat niet.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarom zou je een genre willen benoemen voor je een boek leest?",
        opties=[
            "omdat je dan weet wat je ongeveer mag verwachten",
            "omdat je het boek dan sneller kan uitlezen",
            "omdat het genre de kwaliteit van het boek bepaalt",
            "omdat je het boek dan niet hoeft te beoordelen",
        ],
        antwoord=0,
        uitleg="Verwachting hoort bij lezen. Een boek dat die verwachting breekt, kan je daarna net verrassen.",
    ),
    dict(
        type="waarofniet",
        vraag="Een boek hoort altijd tot precies één genre.",
        antwoord=False,
        uitleg="Een jeugdroman kan ook een detectiveverhaal zijn, en een graphic novel kan non-fictie brengen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat hoort bij het verwoorden van je leeservaring?",
        opties=[
            "zeggen wat het boek bij je losmaakte en waarom precies",
            "de verhaallijn van het boek volledig navertellen",
            "de beoordelingen van andere lezers samenvatten",
            "opzoeken welke prijzen het boek gekregen heeft",
        ],
        antwoord=0,
        uitleg="Je eigen ervaring is het vertrekpunt. De onderbouwing haal je uit het boek zelf.",
    ),
    dict(
        type="waarofniet",
        vraag="Een boek dat je niet graag las, kan je onmogelijk goed vinden.",
        antwoord=False,
        uitleg="Dat kan wel, en het gebeurt vaak: een boek kan sterk gemaakt zijn en jou toch niet liggen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Hoe maak je van 'ik vond het saai' een bruikbaar oordeel?",
        opties=[
            "je zegt welk deel je saai vond en wat er volgens jou ontbrak",
            "je zegt hoeveel bladzijden je gelezen hebt voor je stopte",
            "je zoekt een ander boek dat je wel graag las",
            "je zegt dat het boek niet voor jouw leeftijd is",
        ],
        antwoord=0,
        uitleg="Een oordeel wordt een gesprek zodra er een waarom bij staat.",
    ),
    dict(
        type="waarofniet",
        vraag="Non-fictie kan even meeslepend verteld zijn als een roman.",
        antwoord=True,
        uitleg="Een goed journalistiek boek gebruikt dezelfde middelen: spanning, personages, scènes.",
    ),
]

DEEL2 = [
    dict(
        type="meerkeuze",
        vraag="Een boek bestaat uit korte stukken met tekeningen en tekstballonnen, en is bedoeld voor volwassenen. Wat is dat?",
        opties=[
            "een graphic novel",
            "een jeugdroman met tekeningen erbij",
            "een novelle met illustraties van de schrijver",
            "een toneeltekst in beeldvorm uitgegeven",
        ],
        antwoord=0,
        uitleg="De middelen van de strip, de lengte en de ernst van een roman.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is een biografie?",
        opties=[
            "een boek over het leven van een echte persoon",
            "een boek dat iemand over zijn eigen leven schrijft",
            "een boek met de brieven van een bekende schrijver",
            "een boek dat het werk van een auteur bespreekt",
        ],
        antwoord=0,
        uitleg="Schrijft iemand over zijn eigen leven, dan heet het een autobiografie.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je een boek dat iemand over zijn eigen leven schrijft?",
        antwoord=["een autobiografie", "autobiografie"],
        uitleg="Een biografie wordt door iemand anders geschreven.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke vragen helpen je om een genre te bepalen?",
        opties=[
            "is dit bedacht of wil het de werkelijkheid weergeven?",
            "hoe wordt het verhaal gebracht: in tekst, in beeld of op een toneel?",
            "hoeveel exemplaren werden er van het boek verkocht?",
            "in welke taal werd het boek oorspronkelijk uitgegeven?",
        ],
        antwoord=[0, 1],
        uitleg="Met die twee vragen zit je er bijna altijd dicht bij.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is het verschil tussen een roman en een reportage over hetzelfde onderwerp?",
        opties=[
            "de roman mag bedenken wat de reportage moet kunnen aantonen",
            "de roman is langer en de reportage korter van opzet",
            "de roman heeft personages en de reportage geen mensen",
            "de roman wordt gedrukt en de reportage enkel online gezet",
        ],
        antwoord=0,
        uitleg="Een reportage die iets bedenkt, verliest haar grond. Een roman die niets bedenkt, verliest haar vrijheid.",
    ),
    dict(
        type="waarofniet",
        vraag="Een genre is een afspraak tussen schrijvers en lezers, niet een wet.",
        antwoord=True,
        uitleg="Daarom schuiven de grenzen en komen er nieuwe genres bij.",
    ),
    dict(
        type="waarofniet",
        vraag="Fictie heeft minder waarde dan non-fictie, omdat ze niet over de werkelijkheid gaat.",
        antwoord=False,
        uitleg="Een roman kan over de werkelijkheid iets zeggen wat geen verslag kan zeggen.",
    ),
    dict(
        type="waarofniet",
        vraag="Een gedicht moet altijd over gevoelens gaan.",
        antwoord=False,
        uitleg="Er bestaan gedichten over een stad, een machine of een politiek feit.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat doet de regelval in een gedicht?",
        opties=[
            "ze bepaalt waar de lezer even stilvalt",
            "ze geeft aan welk woord verkeerd gespeld is",
            "ze bepaalt het aantal strofen van het gedicht",
            "ze zegt in welke tijd het gedicht geschreven is",
        ],
        antwoord=0,
        uitleg="Een afgebroken regel kan een woord nadruk geven dat het in een gewone zin niet zou krijgen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Je ziet een toneelstuk en je leest daarna de toneeltekst. Wat is het grootste verschil?",
        opties=[
            "de opvoering voegt stem, beweging en decor aan de tekst toe",
            "de tekst heeft personages die in de opvoering ontbreken",
            "de opvoering volgt een andere verhaallijn dan de tekst",
            "de tekst is altijd langer dan wat er gespeeld wordt",
        ],
        antwoord=0,
        uitleg="De tekst is het plan. De opvoering is wat regisseur en acteurs ervan maken.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke vormen van non-fictie zijn er?",
        opties=[
            "de biografie en de autobiografie",
            "het reisverhaal en het journalistieke boek",
            "de novelle en het kortverhaal",
            "het toneelstuk en het gedicht",
        ],
        antwoord=[0, 1],
        uitleg="Ook een handboek, een essay en een historisch overzicht horen erbij.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een vriend vraagt of hij een boek moet lezen. Wat is een goed antwoord?",
        opties=[
            "wat je ervan vond, en voor wie je denkt dat het werkt",
            "hoeveel bladzijden het boek precies telt",
            "wat de achterflap over het boek beweert",
            "welke prijzen het boek al gewonnen heeft",
        ],
        antwoord=0,
        uitleg="Een aanbeveling is pas nuttig als ze bij een lezer past, en dat moet je kunnen zeggen.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je een tekst die haast volledig uit dialoog en regieaanwijzingen bestaat?",
        antwoord=["een toneeltekst", "toneeltekst", "een toneelstuk"],
        uitleg="Ze is geschreven om gespeeld te worden, niet om alleen gelezen te worden.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarom lezen twee mensen hetzelfde boek anders?",
        opties=[
            "omdat ze er met een andere ervaring aan beginnen",
            "omdat er verschillende uitgaven van het boek bestaan",
            "omdat het boek zijn thema niet duidelijk maakt",
            "omdat de een sneller leest dan de ander",
        ],
        antwoord=0,
        uitleg="Wat jou raakt, hangt samen met wat je zelf meebrengt. Dat is geen fout, dat is lezen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat doe je als een boek je niet ligt maar je er toch over moet spreken?",
        opties=[
            "je zegt wat niet werkte voor jou, en waar dat volgens jou aan ligt",
            "je zegt enkel dat het boek slecht geschreven is",
            "je leest de samenvatting en spreekt daarover",
            "je spreekt over een ander boek dat je wel graag las",
        ],
        antwoord=0,
        uitleg="Afkeer onderbouwen is even waardevol als bewondering onderbouwen, en vaak leerzamer.",
    ),
    dict(
        type="waarofniet",
        vraag="Een graphic novel kan ook non-fictie zijn.",
        antwoord=True,
        uitleg="Er bestaan graphic novels over een oorlog of een ziekte, met echte getuigenissen als grond.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat betekent het als iemand zegt dat een boek 'een genre doorbreekt'?",
        opties=[
            "het boek wijkt bewust af van wat de lezer verwacht",
            "het boek hoort tot geen enkel bestaand genre",
            "het boek is in een verkeerde reeks uitgegeven",
            "het boek bevat fouten tegen de regels van het genre",
        ],
        antwoord=0,
        uitleg="Het genre blijft het vertrekpunt. Wie het breekt, rekent erop dat je het kent.",
    ),
    dict(
        type="waarofniet",
        vraag="Wie een boek beoordeelt, moet het genre ervan meerekenen.",
        antwoord=True,
        uitleg="Een jeugdroman afrekenen op wat je van een dikke roman verwacht, is niet eerlijk.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke uitspraken over je eigen leeservaring zijn bruikbaar in een gesprek?",
        opties=[
            "het slot liet me onvoldaan, omdat één vraag open bleef",
            "ik herkende mezelf in het hoofdpersonage, vooral in zijn twijfel",
            "ik heb het boek in drie dagen uitgelezen",
            "het boek stond in de kast van mijn grootmoeder",
        ],
        antwoord=[0, 1],
        uitleg="Een bruikbare uitspraak zegt iets over het boek, niet enkel over de omstandigheden.",
    ),
    dict(
        type="waarofniet",
        vraag="Een bundel kortverhalen moet één doorlopende verhaallijn hebben.",
        antwoord=False,
        uitleg="De verhalen staan los van elkaar. Soms is er wel een gemeenschappelijk thema.",
    ),
]
