# -*- coding: utf-8 -*-
"""Tijd, ruimte, thema en spanningsopbouw — dubbele finaliteit.

De fiche vraagt bij literatuur: tijd en ruimte in een verhaal herkennen en zeggen
wat ze doen, het thema van een boek benoemen, en de opbouw van de spanning
volgen. Ook: je eigen leeservaring verwoorden en onderbouwen.
"""

DEEL1 = [
    dict(
        type="meerkeuze",
        vraag="Wat bedoelen we met de ruimte in een verhaal?",
        opties=[
            "de plaatsen waar het verhaal zich afspeelt",
            "de witruimte tussen de alinea's van het boek",
            "de hoeveelheid tekst die per personage gebruikt wordt",
            "het aantal bladzijden dat een hoofdstuk beslaat",
        ],
        antwoord=0,
        uitleg="Een afgelegen eiland, een flat, een schoolgang: de plaats doet mee met het verhaal.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat kan de ruimte doen met de sfeer van een verhaal?",
        opties=[
            "een gesloten ruimte kan beklemmend werken",
            "een weidse ruimte kan vrijheid of eenzaamheid oproepen",
            "de ruimte bepaalt hoeveel personages er zijn",
            "de ruimte bepaalt welk perspectief de schrijver kiest",
        ],
        antwoord=[0, 1],
        uitleg="De plaats is zelden toeval. Een schrijver kiest ze zoals een filmmaker een decor kiest.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is het thema van een boek?",
        opties=[
            "waar het boek ten diepste over gaat",
            "de plaats en de tijd van het verhaal",
            "de naam van het hoofdpersonage",
            "de volgorde waarin de gebeurtenissen staan",
        ],
        antwoord=0,
        uitleg="Verraad, schuld, opgroeien, macht. In één of twee woorden te noemen, maar niet in één zin af te doen.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je dat waar een boek ten diepste over gaat?",
        antwoord=["het thema", "thema"],
        uitleg="Het verhaal is wat er gebeurt, het thema is waarover dat gaat.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is het verschil tussen het onderwerp en het thema van een boek?",
        opties=[
            "het onderwerp is waarover het gaat, het thema wat de schrijver erover zegt",
            "het onderwerp staat in de titel, het thema op de achterflap",
            "het onderwerp is korter op te schrijven dan het thema",
            "er is geen verschil, het zijn twee namen voor hetzelfde gegeven",
        ],
        antwoord=0,
        uitleg="Twee boeken over een oorlog kunnen heel verschillende thema's hebben.",
    ),
    dict(
        type="meerkeuze",
        vraag="Hoe bouwt een schrijver spanning op?",
        opties=[
            "door informatie achter te houden voor de lezer",
            "door een gevaar aan te kondigen dat nog niet toeslaat",
            "door elk hoofdstuk even lang te maken als het vorige",
            "door alle personages in één hoofdstuk te beschrijven",
        ],
        antwoord=[0, 1],
        uitleg="Spanning zit in wat de lezer nog niet weet en wel vreest.",
    ),
    dict(
        type="waarofniet",
        vraag="De tijd waarin een verhaal speelt, kan het gedrag van de personages verklaren.",
        antwoord=True,
        uitleg="Wat in 1950 onmogelijk was voor een jonge vrouw, is dat vandaag niet meer.",
    ),
    dict(
        type="waarofniet",
        vraag="Spanning kan alleen in een thriller of een avonturenboek zitten.",
        antwoord=False,
        uitleg="Ook in een rustig familieverhaal kan je willen weten of iemand zijn geheim zal zeggen.",
    ),
    dict(
        type="waarofniet",
        vraag="Een boek kan meer dan één thema hebben.",
        antwoord=True,
        uitleg="Vaak is er een hoofdthema met daarnaast een of twee neventhema's.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is een cliffhanger?",
        opties=[
            "een hoofdstuk dat eindigt op het spannendste moment",
            "een hoofdstuk dat de vorige gebeurtenissen samenvat",
            "een hoofdstuk waarin de verteller verandert",
            "een hoofdstuk dat zich op een andere plaats afspeelt",
        ],
        antwoord=0,
        uitleg="Je moet doorlezen om te weten hoe het verder gaat. Dat is precies de bedoeling.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een boek speelt zich af in twee weken, maar beslaat vierhonderd bladzijden. Wat zegt dat?",
        opties=[
            "de schrijver neemt veel ruimte voor korte tijdspannes",
            "de schrijver heeft de tijdlijn van het boek fout geteld",
            "de schrijver slaat grote stukken tijd over",
            "de schrijver gebruikt enkel de tegenwoordige tijd",
        ],
        antwoord=0,
        uitleg="Verteltijd en vertelde tijd staan dan haast stil naast elkaar. Elk uur wordt uitgespeeld.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke middelen vertragen de tijd in een verhaal?",
        opties=[
            "een gedachte van een personage die een bladzijde beslaat",
            "een gedetailleerde beschrijving van één moment",
            "een sprong van tien jaar in één zin",
            "een opsomming van wat er dat jaar gebeurde",
        ],
        antwoord=[0, 1],
        uitleg="Wie versnelt, slaat over. Wie vertraagt, zoomt in.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is een tijdsprong in een verhaal?",
        opties=[
            "een stuk tijd dat de schrijver overslaat",
            "een hoofdstuk dat in de toekomst gezet is",
            "een fout in de chronologie van het verhaal",
            "een gebeurtenis die twee keer verteld wordt",
        ],
        antwoord=0,
        uitleg="'Drie jaar later' en je bent verder. De lezer vult de tussentijd zelf in.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je een hoofdstuk dat eindigt op het spannendste moment?",
        antwoord=["een cliffhanger", "cliffhanger"],
        uitleg="Het is het bekendste middel om een lezer door te laten lezen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een boek opent met een storm die het dorp bedreigt. Wat doet die opening?",
        opties=[
            "ze zet meteen een dreiging neer die het verhaal draagt",
            "ze legt uit waar het dorp precies ligt",
            "ze bewijst dat het verhaal waargebeurd is",
            "ze geeft het thema van het boek al weg",
        ],
        antwoord=0,
        uitleg="Een opening werkt als de eerste noot van een lied: ze zet de toonaard.",
    ),
    dict(
        type="waarofniet",
        vraag="De ruimte in een verhaal is enkel decor en heeft geen betekenis.",
        antwoord=False,
        uitleg="Een huis dat steeds kleiner lijkt te worden, zegt iets over wie erin woont.",
    ),
    dict(
        type="meerkeuze",
        vraag="Hoe kan je het thema van een boek achterhalen?",
        opties=[
            "je kijkt welke vraag in het hele boek terugkomt",
            "je leest de achterflap en neemt die over",
            "je telt welk woord het vaakst voorkomt",
            "je kijkt naar het beroep van het hoofdpersonage",
        ],
        antwoord=0,
        uitleg="Het thema zit in wat de personages steeds opnieuw moeten uitvechten.",
    ),
    dict(
        type="waarofniet",
        vraag="Een verhaal moet in de eigen tijd van de lezer spelen om te raken.",
        antwoord=False,
        uitleg="Een verhaal uit 1600 kan over iets gaan dat je vandaag nog zelf meemaakt.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarom zou een schrijver de spanning eerst laten dalen voor het slot?",
        opties=[
            "om de laatste wending harder te laten aankomen",
            "om de lezer te laten stoppen met lezen",
            "om bladzijden te kunnen uitsparen",
            "om een nieuw personage te kunnen invoeren",
        ],
        antwoord=0,
        uitleg="Na een rustig stuk voelt een schok groter. Spanning werkt met golven, niet met één rechte lijn.",
    ),
    dict(
        type="waarofniet",
        vraag="Je leeservaring onderbouwen betekent zeggen waaróm een boek je raakte.",
        antwoord=True,
        uitleg="Met iets uit het boek zelf: een scène, een personage, een zin die bleef staan.",
    ),
]

DEEL2 = [
    dict(
        type="meerkeuze",
        vraag="Een verhaal speelt volledig in één kamer. Welk effect ligt het meest voor de hand?",
        opties=[
            "de lezer voelt de beperking van de personages mee",
            "de lezer verliest het overzicht over de verhaallijn",
            "het verhaal wordt noodzakelijk korter dan anders",
            "het verhaal moet in de tegenwoordige tijd staan",
        ],
        antwoord=0,
        uitleg="Wat niet weg kan, moet het met elkaar uitvechten. Dat werkt ook op een toneel.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat doet een schrijver die het weer laat passen bij het gevoel van een personage?",
        opties=[
            "hij laat de ruimte de binnenkant van het personage spiegelen",
            "hij maakt een fout, want weer en gevoel staan los",
            "hij geeft informatie over het seizoen waarin het verhaal speelt",
            "hij vertraagt de tijd van het verhaal daarmee",
        ],
        antwoord=0,
        uitleg="Het is een oud middel, en het valt op zodra je het ziet.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je een stuk tijd dat een schrijver in één zin overslaat?",
        antwoord=["een tijdsprong", "tijdsprong"],
        uitleg="'Drie jaar later' en de lezer vult de tussentijd zelf in.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke vragen helpen je om de ruimte van een verhaal te beschrijven?",
        opties=[
            "welke plaatsen komen terug, en wat gebeurt daar steeds?",
            "is de ruimte open of gesloten, en wat doet dat met de personages?",
            "hoeveel plaatsen worden er in het boek genoemd?",
            "in welke stad werd het boek gedrukt en uitgegeven?",
        ],
        antwoord=[0, 1],
        uitleg="Het gaat niet om een lijst plaatsen, maar om wat die plaatsen met het verhaal doen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een boek over een verhuizing blijkt eigenlijk over afscheid nemen te gaan. Wat is afscheid nemen dan?",
        opties=[
            "het thema van het boek",
            "het onderwerp van het boek",
            "de verhaallijn van het boek",
            "het perspectief van het boek",
        ],
        antwoord=0,
        uitleg="De verhuizing is wat er gebeurt. Het afscheid is waar het over gaat.",
    ),
    dict(
        type="waarofniet",
        vraag="Een thema kan je zelden in één enkel woord samenvatten zonder iets te verliezen.",
        antwoord=True,
        uitleg="'Schuld' dekt niet hetzelfde als 'de schuld die een kind van zijn ouders overneemt'.",
    ),
    dict(
        type="waarofniet",
        vraag="Twee lezers die hetzelfde boek lezen, moeten tot hetzelfde thema komen.",
        antwoord=False,
        uitleg="Ze kunnen een ander thema aanwijzen en beide gelijk hebben, als ze het met het boek kunnen onderbouwen.",
    ),
    dict(
        type="waarofniet",
        vraag="Een spannend boek moet van begin tot eind even spannend blijven.",
        antwoord=False,
        uitleg="Zonder rust is er geen spanning meer. Een lezer heeft golven nodig om het verschil te voelen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is een voorafschaduwing?",
        opties=[
            "een detail dat vooruitwijst naar wat nog komt",
            "een terugblik naar iets dat al gebeurd is",
            "een hoofdstuk dat de verhaallijn samenvat",
            "een beschrijving van de ruimte in het begin",
        ],
        antwoord=0,
        uitleg="Bij een tweede lezing zie je ze pas allemaal. Dat is het plezier ervan.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een schrijver laat de lezer meer weten dan het hoofdpersonage. Wat levert dat op?",
        opties=[
            "spanning, want de lezer ziet het gevaar al aankomen",
            "verwarring, want de lezer verliest zijn houvast",
            "een tijdsprong, want de tijdlijn raakt verschoven",
            "een nieuw thema, want het boek verandert van onderwerp",
        ],
        antwoord=0,
        uitleg="Je wil het personage waarschuwen en dat kan niet. Daar zit precies de spanning.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke elementen horen bij de opbouw van de spanning?",
        opties=[
            "een gevaar dat zich aankondigt maar nog wacht",
            "een hoofdstuk dat op het spannendste moment afbreekt",
            "een lange beschrijving van de hoofdstad",
            "een lijst van alle personages vooraan het boek",
        ],
        antwoord=[0, 1],
        uitleg="Ook een tegenstander die sterker blijkt dan gedacht, en tijd die begint te dringen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat doet een deadline in een verhaal, bijvoorbeeld een trein die om zes uur vertrekt?",
        opties=[
            "ze zet de personages onder tijdsdruk en verhoogt de spanning",
            "ze bepaalt vanaf dat punt het thema van de rest van het boek",
            "ze maakt de verhaallijn moeilijker te volgen",
            "ze geeft aan dat het verhaal bijna afgelopen is",
        ],
        antwoord=0,
        uitleg="Tijdsdruk is het eenvoudigste en sterkste middel dat een schrijver heeft.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je een detail dat vooruitwijst naar wat later in het verhaal gebeurt?",
        antwoord=["een voorafschaduwing", "voorafschaduwing", "een vooruitwijzing"],
        uitleg="Het omgekeerde van een terugblik.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een boek speelt in een stad die niet bestaat. Wat is het gevolg?",
        opties=[
            "de schrijver kan de ruimte helemaal naar zijn verhaal vormen",
            "het verhaal kan daardoor voor geen enkele lezer geloofwaardig zijn",
            "de lezer kan het thema niet meer achterhalen",
            "de tijd van het verhaal blijft dan onbepaald",
        ],
        antwoord=0,
        uitleg="Hij is aan geen enkele echte straat gebonden. Dat geeft vrijheid en vraagt om samenhang.",
    ),
    dict(
        type="meerkeuze",
        vraag="Hoe onderbouw je dat een boek je raakte?",
        opties=[
            "je noemt een scène of een personage en zegt waarom precies die",
            "je zegt dat het boek goed geschreven is",
            "je vertelt het hele verhaal van de eerste tot de laatste bladzijde na",
            "je zoekt op wat andere lezers ervan vonden",
        ],
        antwoord=0,
        uitleg="Een leeservaring wordt pas een gesprek als je ze aan iets in het boek kan ophangen.",
    ),
    dict(
        type="waarofniet",
        vraag="Een verhaal kan spannend zijn zonder dat er iemand in gevaar is.",
        antwoord=True,
        uitleg="Een geheim dat uit kan komen, of een vraag die niet gesteld wordt, werkt even goed.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat betekent het als een verhaal in de tegenwoordige tijd staat?",
        opties=[
            "de gebeurtenissen lijken zich nu voor je ogen af te spelen",
            "het verhaal speelt zich af in het jaar van de uitgave",
            "de verteller is noodzakelijk een ik-verteller",
            "er kan dan geen terugblik in het boek staan",
        ],
        antwoord=0,
        uitleg="Het haalt de afstand weg. Wat er gebeurt, is nog niet voorbij.",
    ),
    dict(
        type="waarofniet",
        vraag="Het thema van een boek staat meestal met zoveel woorden in de tekst.",
        antwoord=False,
        uitleg="Je leidt het af uit wat terugkomt. Een boek dat zijn thema uitspreekt, klinkt vaak belerend.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke vragen horen bij een gesprek over het thema van een boek?",
        opties=[
            "welke vraag moet het hoofdpersonage steeds opnieuw beantwoorden?",
            "welke scène zou je aanwijzen als het hart van het boek?",
            "hoeveel hoofdstukken en bladzijden heeft het boek in totaal?",
            "in welk jaar schreef de auteur dit boek?",
        ],
        antwoord=[0, 1],
        uitleg="Het thema zit in de terugkerende vraag, niet in de gegevens van de uitgever.",
    ),
    dict(
        type="waarofniet",
        vraag="Verzwijgen is een van de sterkste middelen die een schrijver voor spanning heeft.",
        antwoord=True,
        uitleg="Wat de lezer niet weet, wil hij weten. Daarom houdt een schrijver informatie achter.",
    ),
]
