# -*- coding: utf-8 -*-
"""Semantiek: betekenisrelaties, gevoelswaarde en humor — dubbele finaliteit.

De fiche vraagt als ondersteunende kennis: betekenisrelaties tussen woorden
(synoniem, antoniem, homoniem, hyperoniem), letterlijk en figuurlijk taalgebruik,
beeldspraak en vaste uitdrukkingen, en humoristische middelen zoals woordspel,
overdrijving en ironie.
"""

DEEL1 = [
    dict(
        type="meerkeuze",
        vraag="Wat is een synoniem?",
        opties=[
            "een woord met bijna dezelfde betekenis als een ander",
            "een woord met precies de tegengestelde betekenis",
            "een woord met twee heel verschillende betekenissen",
            "een woord dat uit een andere taal overgenomen is",
        ],
        antwoord=0,
        uitleg="Bijna, zelden helemaal. Fiets en rijwiel duiden hetzelfde aan, maar klinken anders.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is een antoniem?",
        opties=[
            "een woord met de tegengestelde betekenis",
            "een woord met bijna dezelfde betekenis",
            "een woord dat hetzelfde klinkt als een ander",
            "een woord dat een hele groep aanduidt",
        ],
        antwoord=0,
        uitleg="Warm en koud, open en dicht, aanwezig en afwezig.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je een woord met bijna dezelfde betekenis als een ander?",
        antwoord=["een synoniem", "synoniem"],
        uitleg="Het tegengestelde heet een antoniem.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is een homoniem?",
        opties=[
            "een woord dat hetzelfde klinkt maar iets anders betekent",
            "een woord dat tot dezelfde woordsoort hoort als een ander",
            "een woord dat in meerdere talen voorkomt",
            "een woord dat uit twee delen samengesteld is",
        ],
        antwoord=0,
        uitleg="Een bank om op te zitten en een bank waar je geld haalt.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke woorden zijn homoniemen?",
        opties=[
            "bank, want je kan erop zitten en er geld halen",
            "slot, want het sluit een deur en het eindigt een verhaal",
            "huis, want het heeft meerdere kamers",
            "groot, want het heeft een tegenstelling",
        ],
        antwoord=[0, 1],
        uitleg="Twee betekenissen die niets met elkaar te maken hebben, in dezelfde vorm.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is een hyperoniem?",
        opties=[
            "een woord dat een hele groep aanduidt waar andere woorden in vallen",
            "een woord dat uit meer dan drie lettergrepen bestaat",
            "een woord dat extra nadruk geeft aan het woord ernaast",
            "een woord dat enkel in geschreven taal gebruikt wordt",
        ],
        antwoord=0,
        uitleg="Meubel is het hyperoniem van stoel, tafel en kast.",
    ),
    dict(
        type="waarofniet",
        vraag="Twee synoniemen zijn niet altijd in dezelfde zin uitwisselbaar.",
        antwoord=True,
        uitleg="Zuinig en gierig duiden hetzelfde gedrag aan, maar het ene is een verwijt.",
    ),
    dict(
        type="waarofniet",
        vraag="Elk woord heeft precies één betekenis.",
        antwoord=False,
        uitleg="Veel woorden hebben er meerdere. De zin beslist welke bedoeld is.",
    ),
    dict(
        type="waarofniet",
        vraag="Een woord kan zijn betekenis in de loop van de tijd veranderen.",
        antwoord=True,
        uitleg="Leuk betekende eerst lauw, en vrouw betekende eerst edele dame.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is figuurlijk taalgebruik?",
        opties=[
            "woorden gebruiken in een andere dan hun eigenlijke betekenis",
            "woorden gebruiken die in geen enkel woordenboek te vinden zijn",
            "woorden gebruiken die uit een vreemde taal komen",
            "woorden gebruiken die een beeld uit de natuur beschrijven",
        ],
        antwoord=0,
        uitleg="'Hij barstte in tranen uit': niemand barst echt.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke zinnen bevatten figuurlijk taalgebruik?",
        opties=[
            "de tijd vliegt voorbij",
            "hij heeft een zware dag achter zich",
            "de vogel vliegt over het dak",
            "de koffer is zwaar om te dragen",
        ],
        antwoord=[0, 1],
        uitleg="Tijd heeft geen vleugels en een dag weegt niets. Vogels en koffers zijn letterlijk.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is een metafoor?",
        opties=[
            "een beeld dat in de plaats van het bedoelde woord komt",
            "een vergelijking met het woordje als erin",
            "een woord dat een menselijke eigenschap aan een ding geeft",
            "een woord dat de klank van iets nabootst",
        ],
        antwoord=0,
        uitleg="'Die man is een leeuw.' Geen als, geen vergelijking: het beeld neemt de plaats over.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is personificatie?",
        opties=[
            "een ding of een begrip een menselijke eigenschap geven",
            "een persoon met een dier vergelijken",
            "een beeld gebruiken in plaats van het eigenlijke woord",
            "een naam gebruiken voor een hele groep",
        ],
        antwoord=0,
        uitleg="'De wind huilde de hele nacht.' Wind huilt niet, mensen huilen.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je het beeld in 'die man is een leeuw', zonder het woordje als?",
        antwoord=["een metafoor", "metafoor"],
        uitleg="Met als zou het een vergelijking zijn.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is een vaste uitdrukking?",
        opties=[
            "een groepje woorden met een betekenis die je niet uit de delen leest",
            "een zin die in zowat elke tekst opnieuw terugkomt",
            "een woord dat altijd op dezelfde plaats in de zin staat",
            "een zin die uit een gedicht of een lied overgenomen is",
        ],
        antwoord=0,
        uitleg="'De kat uit de boom kijken' gaat niet over katten of bomen.",
    ),
    dict(
        type="waarofniet",
        vraag="Een vaste uitdrukking kan je gewoon woord voor woord naar een andere taal overzetten.",
        antwoord=False,
        uitleg="Wie 'de kat uit de boom kijken' letterlijk vertaalt, wordt niet begrepen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is ironie?",
        opties=[
            "iets zeggen en het tegendeel bedoelen",
            "iets groter maken dan het is",
            "twee woorden met elkaar vergelijken",
            "een woord in een vreemde taal gebruiken",
        ],
        antwoord=0,
        uitleg="'Wat een prachtig weer' in een stortregen. De toon moet het verschil maken.",
    ),
    dict(
        type="waarofniet",
        vraag="Ironie in een geschreven tekst kan verkeerd begrepen worden.",
        antwoord=True,
        uitleg="De toon valt weg. Daarom plaatsen mensen er online soms een teken bij.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is een woordspeling?",
        opties=[
            "een grap die op twee betekenissen van hetzelfde woord berust",
            "een grap die uit een ander land is overgenomen en vertaald",
            "een grap die op een flinke overdrijving berust",
            "een grap die een bekende persoon bespot",
        ],
        antwoord=0,
        uitleg="Veel krantenkoppen zijn er een. Daarom zijn ze moeilijk te vertalen.",
    ),
    dict(
        type="waarofniet",
        vraag="Humor in taal werkt in elke cultuur op dezelfde manier.",
        antwoord=False,
        uitleg="Wat ergens een gewone grap is, valt elders stil of komt scherp aan.",
    ),
]

DEEL2 = [
    dict(
        type="meerkeuze",
        vraag="Wat is het hyperoniem van roos, tulp en madelief?",
        opties=[
            "bloem",
            "plant",
            "tuin",
            "kleur",
        ],
        antwoord=0,
        uitleg="Plant is ook een hyperoniem, maar een stap hoger: bloem ligt het dichtst bij de drie.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke woordparen zijn antoniemen?",
        opties=[
            "aanwezig en afwezig",
            "stijgen en dalen",
            "huis en woning",
            "bank en zetel",
        ],
        antwoord=[0, 1],
        uitleg="De twee laatste paren zijn synoniemen, geen tegenstellingen.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je een woord met de tegengestelde betekenis van een ander?",
        antwoord=["een antoniem", "antoniem", "een tegenstelling"],
        uitleg="Warm en koud, open en dicht.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is het verschil tussen een vergelijking en een metafoor?",
        opties=[
            "een vergelijking gebruikt het woordje als of zoals, een metafoor niet",
            "een vergelijking staat in de tegenwoordige tijd en een metafoor niet",
            "een vergelijking gaat over mensen en een metafoor over dingen",
            "er is geen verschil, het zijn twee namen voor hetzelfde beeld",
        ],
        antwoord=0,
        uitleg="'Hij vecht als een leeuw' is een vergelijking. 'Hij is een leeuw' is een metafoor.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke middelen horen bij beeldspraak?",
        opties=[
            "de metafoor en de vergelijking",
            "de personificatie",
            "de puntkomma en de dubbelepunt",
            "het voorvoegsel en het achtervoegsel",
        ],
        antwoord=[0, 1],
        uitleg="Leestekens en woorddelen zijn vorm, geen beeld.",
    ),
    dict(
        type="waarofniet",
        vraag="Beeldspraak hoort thuis in gedichten en komt in zakelijke teksten niet voor.",
        antwoord=False,
        uitleg="De economie krimpt, een partij verliest terrein: ook een nieuwsbericht staat er vol van.",
    ),
    dict(
        type="waarofniet",
        vraag="Een versleten metafoor valt de lezer nog altijd op.",
        antwoord=False,
        uitleg="De poot van een tafel of de hals van een fles leest niemand nog als een beeld.",
    ),
    dict(
        type="waarofniet",
        vraag="Twee beelden door elkaar gebruiken in één zin is meestal een fout.",
        antwoord=True,
        uitleg="'Dat schip is uit de hand gelopen' mengt twee beelden en wordt lachwekkend.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat betekent 'dat is een storm in een glas water'?",
        opties=[
            "er wordt veel drukte gemaakt om iets kleins",
            "er komt een heel groot probleem op ons af",
            "er wordt met opzet iets verborgen gehouden",
            "er wordt een moeilijke beslissing uitgesteld",
        ],
        antwoord=0,
        uitleg="De delen zeggen het niet: een vaste uitdrukking moet je als geheel kennen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is een overdrijving als stijlmiddel?",
        opties=[
            "iets veel groter voorstellen dan het is, om een effect te bereiken",
            "iets kleiner voorstellen dan het is, om vriendelijk te blijven",
            "iets zeggen en het tegendeel bedoelen",
            "iets met een beeld uit de natuur beschrijven",
        ],
        antwoord=0,
        uitleg="'Ik heb duizend keer gebeld.' Niemand neemt het letterlijk, en dat hoeft ook niet.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke middelen gebruiken schrijvers om humor te maken?",
        opties=[
            "woordspel op twee betekenissen",
            "overdrijving tot het ongeloofwaardige",
            "een opsomming van drie gelijkvormige delen",
            "een tussenkop boven elke alinea",
        ],
        antwoord=[0, 1],
        uitleg="Ook ironie en een onverwachte wending in de laatste woorden van een zin.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een reclame zegt 'onze prijzen zijn gevallen'. Wat gebeurt daar?",
        opties=[
            "een figuurlijk gebruik van vallen",
            "een letterlijk gebruik van vallen",
            "een vergelijking met het woordje als",
            "een personificatie van de prijzen",
        ],
        antwoord=0,
        uitleg="Prijzen vallen niet echt. Het beeld van dalen zit zo vast dat je het niet meer merkt.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je iets zeggen en het tegendeel bedoelen?",
        antwoord=["ironie", "ironisch"],
        uitleg="Zonder toon of context komt het vaak niet over.",
    ),
    dict(
        type="meerkeuze",
        vraag="Je komt het woord 'krimpen' tegen in een tekst over de economie. Wat doe je?",
        opties=[
            "je leest het figuurlijk, als een daling",
            "je leest het letterlijk, als kleiner worden van stof",
            "je zoekt het op als een vakterm uit de textiel",
            "je slaat het woord over en leest verder",
        ],
        antwoord=0,
        uitleg="Het beeld komt uit de stof en wordt nu voor cijfers gebruikt.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarom gebruiken schrijvers beeldspraak?",
        opties=[
            "om iets abstracts met iets vertrouwds te laten begrijpen",
            "om hun tekst wat langer en vollediger te maken",
            "om de spelling van moeilijke woorden te kunnen vermijden",
            "om helemaal geen vaktermen te hoeven gebruiken",
        ],
        antwoord=0,
        uitleg="Een economie die krimpt, snap je zonder één cijfer te zien.",
    ),
    dict(
        type="waarofniet",
        vraag="Een woord kan een andere gevoelswaarde krijgen in een andere zin.",
        antwoord=True,
        uitleg="'Ambitieus' is een compliment bij een plan en een verwijt bij een persoon.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat doe je als je in een tekst een uitdrukking niet begrijpt?",
        opties=[
            "je leest de hele zin en kijkt wat er logisch past",
            "je neemt de delen van de uitdrukking letterlijk",
            "je slaat de zin over en leest verder",
            "je vervangt de uitdrukking door een ander woord",
        ],
        antwoord=0,
        uitleg="De omringende zinnen geven bijna altijd de richting aan.",
    ),
    dict(
        type="waarofniet",
        vraag="Een tekst vol beelden is daarom een betere tekst.",
        antwoord=False,
        uitleg="Te veel beelden leiden af. Eén beeld dat klopt, werkt sterker dan vijf losse.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke uitspraken over betekenis kloppen?",
        opties=[
            "de zin beslist welke betekenis van een woord geldt",
            "een woord kan tegelijk een letterlijke en een figuurlijke betekenis hebben",
            "elk woord heeft in elke zin precies dezelfde betekenis",
            "een woordenboek geeft altijd de bedoelde betekenis van een woord",
        ],
        antwoord=[0, 1],
        uitleg="Een woordenboek geeft de mogelijkheden. Welke het is, moet jij uit de tekst halen.",
    ),
    dict(
        type="waarofniet",
        vraag="Een vaste uitdrukking mag je aanpassen om een grap te maken.",
        antwoord=True,
        uitleg="Krantenkoppen doen het voortdurend. De lezer herkent het origineel en ziet de draai.",
    ),
]
