# -*- coding: utf-8 -*-
"""Spreken en gesprekken voeren — dubbele finaliteit.

De fiche vraagt: een presentatie of uiteenzetting houden voor een publiek,
instructies en uitleg geven, een gesprek voeren met een doel (een afspraak
maken, iets vragen, overleggen, bemiddelen), beurten nemen en geven, en
samenvatten wat de ander zei.
"""

DEEL1 = [
    dict(
        type="meerkeuze",
        vraag="Wat doe je het eerst bij de voorbereiding van een presentatie?",
        opties=[
            "je bepaalt wat je publiek achteraf moet weten of doen",
            "je maakt de dia's die je bij je presentatie wil tonen",
            "je zoekt afbeeldingen die bij je onderwerp passen",
            "je schrijft je volledige tekst woord voor woord uit",
        ],
        antwoord=0,
        uitleg="Zonder dat ene doel wordt een presentatie een opsomming van alles wat je vond.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarmee begin je het best een presentatie?",
        opties=[
            "met iets dat de aandacht vangt en je onderwerp aankondigt",
            "met een verontschuldiging voor je eigen nervositeit",
            "met de volledige inhoudstafel van je hele presentatie",
            "met je naam, je klas en de datum van vandaag erbij",
        ],
        antwoord=0,
        uitleg="Een vraag, een cijfer of een kort voorval. De eerste dertig seconden beslissen veel.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je wat je publiek na je presentatie moet weten of doen?",
        antwoord=["je doel", "het doel", "je spreekdoel"],
        uitleg="Alles in je presentatie staat in dienst daarvan.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke middelen helpen je publiek je structuur te volgen?",
        opties=[
            "vooraf zeggen hoeveel punten je behandelt",
            "bij elk nieuw deel benoemen waar je nu bent",
            "zo veel dia's als je punten gebruiken",
            "elke dia in een andere kleur zetten",
        ],
        antwoord=[0, 1],
        uitleg="Een luisteraar kan niet terugbladeren. Jij moet hem vertellen waar hij is.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat doe je met een vraag uit het publiek die je niet kan beantwoorden?",
        opties=[
            "je zegt dat je het niet weet en hoe je het zal nazoeken",
            "je geeft een antwoord dat waarschijnlijk wel zal kloppen",
            "je zegt dat die vraag niet bij je onderwerp hoort",
            "je herhaalt wat je daarover eerder al gezegd hebt",
        ],
        antwoord=0,
        uitleg="Niet weten is geen schande. Een verzonnen antwoord kost je alles wat je tot dan opbouwde.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat kenmerkt goede mondelinge uitleg?",
        opties=[
            "je gaat van wat de ander kent naar wat nieuw is",
            "je laat de ander navertellen wat hij begrepen heeft",
            "je gebruikt zo veel vaktermen als je kent",
            "je spreekt zo snel als je kan om tijd te winnen",
        ],
        antwoord=[0, 1],
        uitleg="Pas als de ander het kan navertellen, weet je dat het overkwam.",
    ),
    dict(
        type="waarofniet",
        vraag="Een presentatie voorlezen werkt minder goed dan ze met steekwoorden brengen.",
        antwoord=True,
        uitleg="Wie voorleest, kijkt niet. Een publiek dat geen ogen krijgt, haakt af.",
    ),
    dict(
        type="waarofniet",
        vraag="Een spreker mag nooit stil vallen tijdens zijn presentatie.",
        antwoord=False,
        uitleg="Een stilte voor een belangrijk punt werkt juist. Alleen een lange, ongewilde stilte stoort.",
    ),
    dict(
        type="waarofniet",
        vraag="Een presentatie oefenen met een klok erbij verandert je tekst meestal nog.",
        antwoord=True,
        uitleg="Bijna iedereen heeft te veel. Je merkt dat pas als je het luidop doet.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat betekent beurten nemen in een gesprek?",
        opties=[
            "op het juiste moment spreken en de ander laten uitspreken",
            "evenveel woorden gebruiken als de ander voor je gebruikte",
            "elke vraag van de ander met een vraag terugkaatsen",
            "wachten tot iemand anders jou het woord geeft",
        ],
        antwoord=0,
        uitleg="Een vlot gesprek is een reeks beurten. Wie altijd neemt of altijd wacht, verstoort het.",
    ),
    dict(
        type="meerkeuze",
        vraag="Hoe laat je merken dat je luistert in een gesprek?",
        opties=[
            "je kijkt de ander aan en knikt af en toe",
            "je vat samen wat de ander zei voor je antwoordt",
            "je kijkt naar je telefoon maar hoort alles",
            "je onderbreekt zodra je het antwoord weet",
        ],
        antwoord=[0, 1],
        uitleg="Samenvatten is het sterkste signaal: het bewijst dat je het hebt.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat doe je als je in een gesprek iets niet begrepen hebt?",
        opties=[
            "je vraagt het na met je eigen woorden erbij",
            "je knikt en zoekt het later zelf op",
            "je wacht of het verderop duidelijk wordt",
            "je verandert van onderwerp",
        ],
        antwoord=0,
        uitleg="'Bedoel je dat...?' geeft de ander meteen de kans om bij te sturen.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je het kort weergeven van wat de ander zei, in je eigen woorden?",
        antwoord=["samenvatten", "parafraseren", "een samenvatting"],
        uitleg="Het bewijst dat je geluisterd hebt en het haalt misverstanden eruit.",
    ),
    dict(
        type="meerkeuze",
        vraag="Je belt om een afspraak te maken. Wat zeg je in je eerste zinnen?",
        opties=[
            "wie je bent en waarvoor je belt",
            "hoe lang je al probeert te bellen",
            "wat je al over het bedrijf weet",
            "welke dagen je volledig vrij hebt",
        ],
        antwoord=0,
        uitleg="De ander moet weten met wie hij spreekt en waarover. De rest komt daarna.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is het doel van overleg?",
        opties=[
            "samen tot een beslissing of een afspraak komen",
            "je eigen standpunt zo lang mogelijk verdedigen",
            "iedereen aan het woord laten zonder besluit",
            "noteren wat iedereen vindt over het onderwerp",
        ],
        antwoord=0,
        uitleg="Een overleg zonder afspraak op het einde is een gesprek geweest, geen overleg.",
    ),
    dict(
        type="waarofniet",
        vraag="Oogcontact met je publiek maakt je verhaal overtuigender.",
        antwoord=True,
        uitleg="Verdeel je blik over de zaal. Niet naar één punt en niet naar je dia's.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat doe je als twee mensen in een gesprek elkaar in de rede vallen?",
        opties=[
            "je vraagt om één voor één te spreken",
            "je spreekt zelf luider dan die twee",
            "je wacht tot het van zelf stopt",
            "je verlaat het gesprek",
        ],
        antwoord=0,
        uitleg="Iemand moet het doen. Eén zin is genoeg om de beurten te herstellen.",
    ),
    dict(
        type="waarofniet",
        vraag="In een discussie hoort je toon mee te verharden als de ander scherper wordt.",
        antwoord=False,
        uitleg="Wie rustig blijft, houdt het gesprek open. Scherp mag de inhoud zijn, niet de toon.",
    ),
    dict(
        type="meerkeuze",
        vraag="Hoe sluit je een presentatie af?",
        opties=[
            "met je kernboodschap en wat je van het publiek verwacht",
            "met een nieuw gegeven dat je eerder nog niet gaf",
            "met de vraag of iedereen alles gevolgd heeft",
            "met een verontschuldiging voor de lengte van je verhaal",
        ],
        antwoord=0,
        uitleg="Het laatste wat je zegt, blijft hangen. Gebruik die plaats voor je punt.",
    ),
    dict(
        type="waarofniet",
        vraag="Een goede spreker spreekt altijd zo snel als hij kan.",
        antwoord=False,
        uitleg="Een rustig tempo met pauzes geeft het publiek tijd om mee te gaan.",
    ),
]

DEEL2 = [
    dict(
        type="meerkeuze",
        vraag="Je hebt tien minuten en vijftien minuten stof. Wat doe je?",
        opties=[
            "je schrapt tot je kernboodschap overblijft",
            "je spreekt sneller om alles te kunnen zeggen",
            "je laat je slot weg en stopt gewoon vroeger",
            "je zet de rest op een extra dia",
        ],
        antwoord=0,
        uitleg="Wat je sneller zegt, komt niet aan. Wat je schrapt, mist niemand.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat doe je met zenuwen voor een presentatie?",
        opties=[
            "je oefent je eerste zinnen tot die vastzitten",
            "je leest je hele tekst nog een laatste keer door",
            "je vertelt het publiek dat je nerveus bent",
            "je begint zo snel mogelijk om het achter je te hebben",
        ],
        antwoord=0,
        uitleg="De eerste dertig seconden zijn het moeilijkst. Daarna neemt je verhaal het over.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je het beurtelings spreken en laten spreken in een gesprek?",
        antwoord=["beurten nemen", "beurtwisseling", "beurten"],
        uitleg="Wie altijd neemt of altijd wacht, verstoort het gesprek.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke vragen stel je in een gesprek om de ander verder te laten spreken?",
        opties=[
            "open vragen die met hoe of waarom beginnen",
            "vragen die doorgaan op wat de ander net zei",
            "vragen die met ja of nee te beantwoorden zijn",
            "vragen waarvan je het antwoord al kent",
        ],
        antwoord=[0, 1],
        uitleg="Een gesloten vraag levert één woord. Een open vraag levert een verhaal.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is het verschil tussen een open en een gesloten vraag?",
        opties=[
            "een open vraag vraagt een verhaal, een gesloten vraag een ja of een nee",
            "een open vraag is altijd langer dan een gesloten vraag",
            "een open vraag stel je enkel aan het begin van een gesprek",
            "een open vraag mag je in een examengesprek niet gebruiken",
        ],
        antwoord=0,
        uitleg="Beide zijn nuttig. Je kiest naargelang je iets wil weten of iets wil vastleggen.",
    ),
    dict(
        type="waarofniet",
        vraag="Een gesloten vraag is soms precies wat je nodig hebt.",
        antwoord=True,
        uitleg="Om een afspraak vast te leggen wil je een ja of een nee, geen verhaal.",
    ),
    dict(
        type="waarofniet",
        vraag="In een gesprek hoort wie het meest spreekt, het meest te bereiken.",
        antwoord=False,
        uitleg="Wie de goede vragen stelt en samenvat, stuurt het gesprek met minder woorden.",
    ),
    dict(
        type="waarofniet",
        vraag="Je kan een gesprek sturen zonder het grootste deel van de tijd te spreken.",
        antwoord=True,
        uitleg="Met vragen, samenvattingen en stiltes bepaal je waar het gesprek heen gaat.",
    ),
    dict(
        type="meerkeuze",
        vraag="Je bemiddelt tussen twee mensen die ruzie hebben. Wat doe je eerst?",
        opties=[
            "je laat elk zijn kant vertellen zonder onderbreking",
            "je zegt wie van de twee volgens jou gelijk heeft",
            "je stelt meteen zelf een oplossing voor hen voor",
            "je vraagt hen om de hele zaak te laten rusten",
        ],
        antwoord=0,
        uitleg="Wie nog niet gehoord is, luistert niet. Daarom komt het verhaal eerst.",
    ),
    dict(
        type="meerkeuze",
        vraag="Hoe maak je in een overleg een afspraak concreet?",
        opties=[
            "je noemt wie wat doet en tegen wanneer",
            "je noteert wat iedereen vond van het voorstel",
            "je herhaalt het doel van het overleg",
            "je stelt een nieuw overleg voor",
        ],
        antwoord=0,
        uitleg="Zonder naam en datum is een afspraak een intentie.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke middelen houden een moeilijk gesprek op gang?",
        opties=[
            "samenvatten wat de ander zei voor je reageert",
            "benoemen waar jullie het wel over eens zijn",
            "je standpunt luider herhalen dan daarvoor",
            "het gesprek afbreken zodra het scherp wordt",
        ],
        antwoord=[0, 1],
        uitleg="Wie zich gehoord weet, kan nog bewegen. Wie zich overschreeuwd weet, niet.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat doe je als je in een presentatie merkt dat het publiek afhaakt?",
        opties=[
            "je stelt een vraag of je kondigt je volgende punt aan",
            "je spreekt luider tot de aandacht weer terugkomt",
            "je slaat het hele middenstuk van je verhaal over",
            "je gaat verder zoals gepland en kijkt niet meer op",
        ],
        antwoord=0,
        uitleg="Een vraag of een nieuw kopje haalt de aandacht terug. Volume doet dat niet.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je een vraag die met ja of nee te beantwoorden is?",
        antwoord=["een gesloten vraag", "gesloten vraag"],
        uitleg="Het tegenovergestelde is een open vraag.",
    ),
    dict(
        type="meerkeuze",
        vraag="Je geeft iemand telefonisch een instructie. Wat doe je op het einde?",
        opties=[
            "je laat de ander de stappen terug zeggen",
            "je herhaalt alle stappen nog een keer zelf",
            "je vraagt of het duidelijk was",
            "je stuurt de instructie ook per mail",
        ],
        antwoord=0,
        uitleg="Op 'is het duidelijk?' antwoordt bijna iedereen ja. Navertellen laat zien wat echt aankwam.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarom werkt een voorbeeld goed in een mondelinge uitleg?",
        opties=[
            "de ander kan het nieuwe aan iets bekends ophangen",
            "de uitleg wordt er een stuk korter van",
            "de ander hoeft dan zelf geen vragen meer te stellen",
            "je kan de vaktermen dan helemaal weglaten",
        ],
        antwoord=0,
        uitleg="Eerst het voorbeeld, dan de regel: zo blijft het hangen.",
    ),
    dict(
        type="waarofniet",
        vraag="Een presentatie met dia's is altijd beter dan een presentatie zonder.",
        antwoord=False,
        uitleg="Dia's helpen als ze iets tonen dat je niet kan zeggen. Anders leiden ze af.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is het nut van een korte samenvatting midden in een lange uiteenzetting?",
        opties=[
            "wie de draad kwijt was, kan weer instappen",
            "de uiteenzetting wordt er korter van",
            "je publiek hoeft daarna niets meer te volgen",
            "je kan het laatste deel dan sneller doen",
        ],
        antwoord=0,
        uitleg="Een luisteraar die even wegviel, is zonder zo'n moment voor de rest verloren.",
    ),
    dict(
        type="waarofniet",
        vraag="Een presentatie houden en een gesprek voeren vragen hetzelfde van een spreker.",
        antwoord=False,
        uitleg="In een presentatie stuur jij alles. In een gesprek moet je ook ruimte laten en volgen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke uitspraken over mondelinge taalvaardigheid kloppen?",
        opties=[
            "wie zijn doel kent, kiest makkelijker wat hij weglaat",
            "luisteren is een even actieve vaardigheid als spreken",
            "een goede spreker heeft geen voorbereiding nodig",
            "een presentatie wordt sterker door meer inhoud erin te zetten",
        ],
        antwoord=[0, 1],
        uitleg="Meer inhoud maakt een presentatie zwakker. De keuze maakt ze sterk.",
    ),
    dict(
        type="waarofniet",
        vraag="Een spreker die zijn publiek kent, maakt andere keuzes dan een spreker die het niet kent.",
        antwoord=True,
        uitleg="Voorkennis, voorbeelden en vaktermen hangen volledig af van wie er zit.",
    ),
]
