# -*- coding: utf-8 -*-
"""🌍 Beyond dubbele finaliteit — Voedingsbestanddelen en etiketten.

Chemie, de kop "Voedingsbestanddelen" uit de vakfiche natuurwetenschappen 3DU.
Deel 1 gaat over de voedingsstoffen zelf: koolhydraten, vetten, eiwitten, water,
mineralen en vitaminen, hun bouw en hun functie in het lichaam, en waarom
zetmeel trager verteert dan glucose. Deel 2 gaat over het etiket: ingrediënten,
allergenen en energie, over de nutriscore en de ecoscore, en over kiezen op
basis van de samenstelling.
"""

DEEL1 = [
    dict(
        type="meerkeuze",
        vraag="Wat is het verschil tussen een voedingsstof en een voedingsmiddel?",
        opties=[
            "een voedingsmiddel is wat je eet, een voedingsstof zit erin",
            "een voedingsstof is wat je eet, een voedingsmiddel zit erin",
            "een voedingsstof komt enkel uit planten",
            "een voedingsmiddel bevat altijd maar één stof",
        ],
        antwoord=0,
        uitleg="Een appel is een voedingsmiddel; de koolhydraten, vitaminen en vezels erin zijn de voedingsstoffen. Bijna elk voedingsmiddel bevat er meerdere tegelijk.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke voedingsstoffen leveren energie? Er zijn er drie.",
        opties=[
            "koolhydraten",
            "vetten",
            "eiwitten",
            "water",
        ],
        antwoord=[0, 1, 2],
        uitleg="Koolhydraten, vetten en eiwitten leveren kilojoules. Water, mineralen en vitaminen zijn onmisbaar, maar leveren geen energie.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je een koolhydraat dat uit één suikermolecule bestaat, zoals glucose?",
        antwoord=["monosacharide", "een monosacharide", "monosaccharide"],
        uitleg="Mono betekent één. Glucose en fructose zijn monosachariden, en je lichaam kan ze meteen opnemen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is zetmeel?",
        opties=[
            "een lange keten van suikermoleculen",
            "een enkele suikermolecule",
            "een keten van aminozuren",
            "een vetzuur met een lange staart",
        ],
        antwoord=0,
        uitleg="Zetmeel is een polysacharide: honderden glucosemoleculen aan elkaar. Planten slaan hun energie zo op, in aardappelen, graan en rijst.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarom geeft zetmeel trager energie dan glucose?",
        opties=[
            "de lange keten moet eerst afgebroken worden",
            "zetmeel bevat minder energie per gram",
            "zetmeel lost helemaal niet op in water",
            "zetmeel wordt in de maag niet opgenomen",
        ],
        antwoord=0,
        uitleg="Je verteringssap moet de keten eerst knippen tot losse glucosemoleculen. Dat kost tijd, en daardoor komt de suiker geleidelijk in je bloed.",
    ),
    dict(
        type="waarofniet",
        vraag="Glucose en fructose komen sneller in je bloed dan zetmeel.",
        antwoord=True,
        uitleg="Ze zijn al losse moleculen en hoeven niet geknipt te worden. Daarom helpt fruit sneller tegen een energiedip dan een boterham.",
    ),
    dict(
        type="meerkeuze",
        vraag="Je gaat zo meteen een uur lopen. Wat eet je het best een paar uur vooraf?",
        opties=[
            "iets met zetmeel, zoals pasta of brood",
            "iets met veel losse suiker, zoals snoep",
            "iets met veel vet, zoals een portie frieten",
            "enkel een glas water zonder meer",
        ],
        antwoord=0,
        uitleg="Zetmeel geeft zijn glucose geleidelijk af, en dat houdt je energie lang op peil. Losse suiker geeft een korte piek en daarna weer een dip.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke voedingsmiddelen zijn rijk aan zetmeel? Er zijn er drie.",
        opties=[
            "aardappelen",
            "rijst",
            "brood",
            "olijfolie",
        ],
        antwoord=[0, 1, 2],
        uitleg="Aardappelen, rijst, pasta en brood zijn de klassieke zetmeelbronnen. Olijfolie bestaat zo goed als volledig uit vet.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waaruit bestaat een eiwit?",
        opties=[
            "uit aminozuren",
            "uit vetzuren",
            "uit suikermoleculen",
            "uit mineralen",
        ],
        antwoord=0,
        uitleg="Een eiwit is een keten aminozuren. Je lichaam breekt de eiwitten uit je voeding af tot losse aminozuren en bouwt daarmee zijn eigen eiwitten.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is de belangrijkste functie van eiwitten in het lichaam?",
        opties=[
            "ze bouwen en herstellen weefsels",
            "ze isoleren het lichaam tegen de kou",
            "ze vervoeren zuurstof naar de longen",
            "ze regelen het gehalte aan mineralen",
        ],
        antwoord=0,
        uitleg="Spieren, huid, haar, enzymen en antistoffen zijn allemaal eiwitten. Ze leveren wel energie, maar dat is niet waarvoor je lichaam ze eerst gebruikt.",
    ),
    dict(
        type="invultekst",
        vraag="Welke voedingsstof is de belangrijkste bouwstof van je spieren?",
        antwoord=["eiwitten", "eiwit", "proteïnen"],
        uitleg="Spierweefsel bestaat grotendeels uit eiwit. Daarom hoort er bij groeien en bij sporten voldoende eiwit in de voeding.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is kenmerkend voor een onverzadigd vetzuur?",
        opties=[
            "er zit minstens één dubbele binding in de keten",
            "de keten bevat alleen enkelvoudige bindingen",
            "de keten is altijd veel korter",
            "het bevat geen koolstofatomen",
        ],
        antwoord=0,
        uitleg="Door de dubbele binding krijgt de keten een knik, en passen de moleculen minder goed op elkaar. Daardoor is zo'n vet meestal vloeibaar bij kamertemperatuur.",
    ),
    dict(
        type="waarofniet",
        vraag="Verzadigde vetten zijn bij kamertemperatuur meestal vloeibaar.",
        antwoord=False,
        uitleg="Het is net omgekeerd: boter en kokosvet zijn vast, en de onverzadigde olijfolie en zonnebloemolie zijn vloeibaar. Dat verschil zie je gewoon aan tafel.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke voedingsmiddelen zijn rijk aan onverzadigde vetten? Er zijn er twee.",
        opties=[
            "olijfolie",
            "noten",
            "roomboter",
            "een kaantje spek",
        ],
        antwoord=[0, 1],
        uitleg="Plantaardige oliën, noten en vette vis leveren vooral onverzadigde vetten. Boter en vet vlees leveren vooral verzadigde.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarvoor dienen vetten in het lichaam? Er zijn er drie.",
        opties=[
            "energie opslaan",
            "het lichaam isoleren tegen de kou",
            "bepaalde vitaminen opnemen",
            "zuurstof door het bloed vervoeren",
        ],
        antwoord=[0, 1, 2],
        uitleg="Vet is de voorraadkast, de deken en het vervoermiddel voor de vitaminen A, D, E en K. Zuurstof vervoeren doet hemoglobine, een eiwit.",
    ),
    dict(
        type="waarofniet",
        vraag="Water levert geen energie, maar is toch onmisbaar.",
        antwoord=True,
        uitleg="Water levert geen kilojoules, maar zonder water werkt geen enkele reactie in je lichaam. Je lichaam bestaat er voor ongeveer zestig procent uit.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarvoor heb je calcium nodig?",
        opties=[
            "voor stevige botten en tanden",
            "voor het vervoer van zuurstof",
            "voor de aanmaak van vitamine C",
            "voor de isolatie tegen de kou",
        ],
        antwoord=0,
        uitleg="Calcium is een mineraal dat het skelet stevig maakt. Melkproducten, groene groenten en noten zijn er goede bronnen van.",
    ),
    dict(
        type="invultekst",
        vraag="Welk mineraal heb je nodig om hemoglobine te maken, de stof die zuurstof vervoert?",
        antwoord=["ijzer", "Fe", "het ijzer"],
        uitleg="Zonder ijzer kan je lichaam te weinig hemoglobine maken en krijg je bloedarmoede. Rood vlees, peulvruchten en groene groenten leveren het aan.",
    ),
    dict(
        type="waarofniet",
        vraag="Vitaminen leveren energie aan het lichaam.",
        antwoord=False,
        uitleg="Vitaminen leveren geen kilojoules. Ze zijn wel onmisbaar omdat ze reacties in je lichaam mogelijk maken, en je hebt er maar heel kleine hoeveelheden van nodig.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat laat de voedingsdriehoek zien?",
        opties=[
            "waarvan je veel mag eten en waarvan beter weinig",
            "hoeveel kilojoules elk voedingsmiddel bevat",
            "welke volgorde je bij een maaltijd aanhoudt",
            "welke stoffen samen in één gerecht passen",
        ],
        antwoord=0,
        uitleg="De driehoek zet voeding in zones: water en plantaardige voeding binnen de grote groep, sterk bewerkte producten in de restgroep buiten de driehoek.",
    ),
]

DEEL2 = [
    dict(
        type="meerkeuze",
        vraag="In welke volgorde staan de ingrediënten op een etiket?",
        opties=[
            "van het meest naar het minst aanwezige",
            "van het minst naar het meest aanwezige",
            "in alfabetische volgorde",
            "in de volgorde waarin ze toegevoegd zijn",
        ],
        antwoord=0,
        uitleg="Het eerste ingrediënt zit er het meest in. Staat suiker helemaal vooraan, dan weet je meteen hoeveel het product bevat.",
    ),
    dict(
        type="waarofniet",
        vraag="Staat suiker als eerste in de ingrediëntenlijst, dan bevat het product er veel van.",
        antwoord=True,
        uitleg="De lijst is geordend op hoeveelheid. Vooraan betekent dus dat er van die stof het meest in zit.",
    ),
    dict(
        type="meerkeuze",
        vraag="Hoe herken je de allergenen in een ingrediëntenlijst?",
        opties=[
            "ze staan in het vet of met hoofdletters",
            "ze staan altijd onderaan apart",
            "ze staan tussen haakjes achteraan",
            "ze staan nooit op het etiket vermeld",
        ],
        antwoord=0,
        uitleg="De wet verplicht de veertien bekendste allergenen, zoals gluten, melk, noten en soja, duidelijk te laten opvallen in de lijst.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarop slaat de energiewaarde op een etiket meestal?",
        opties=[
            "op honderd gram of honderd milliliter",
            "op de volledige verpakking",
            "op één gram van het product",
            "op de dagelijkse behoefte van een volwassene",
        ],
        antwoord=0,
        uitleg="Per honderd gram, zodat je producten eerlijk kan vergelijken. Daarnaast staat er soms ook de waarde per portie, en die portie is niet altijd wat jij opschept.",
    ),
    dict(
        type="invultekst",
        vraag="In welke eenheid staat de energiewaarde van voeding meestal op het etiket?",
        antwoord=["kilojoule", "kJ", "kilojoules"],
        uitleg="Kilojoule is de officiële eenheid; de kilocalorie staat er meestal naast. Eén kilocalorie is ongeveer 4,2 kilojoule.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat zegt de nutriscore?",
        opties=[
            "hoe gezond de samenstelling van een product is",
            "hoeveel het product op het milieu weegt",
            "hoe lang het product houdbaar is",
            "waar het product vandaan komt",
        ],
        antwoord=0,
        uitleg="De nutriscore weegt gunstige bestanddelen zoals vezels en eiwit tegen ongunstige zoals suiker, zout en verzadigd vet. Hij loopt van een groene A tot een rode E.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat telt mee in de ecoscore?",
        opties=[
            "de belasting van het milieu over de hele levenscyclus",
            "alleen de hoeveelheid suiker en zout",
            "alleen de prijs in de winkel",
            "alleen de houdbaarheidsdatum",
        ],
        antwoord=0,
        uitleg="De ecoscore kijkt naar de hele weg van het product: teelt, verwerking, verpakking en vervoer. Daarna komen er bonussen en malussen bij.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je de hele weg van een product, van grondstof tot afval?",
        antwoord=["levenscyclus", "de levenscyclus", "levensloop"],
        uitleg="De levenscyclus loopt van teelt of ontginning over productie en gebruik tot afval. De ecoscore rekent die hele weg mee.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat kan een bonus opleveren in de ecoscore? Er zijn er twee.",
        opties=[
            "een biologische teelt",
            "een goed recycleerbare verpakking",
            "transport met het vliegtuig",
            "een verpakking in meerdere lagen plastic",
        ],
        antwoord=[0, 1],
        uitleg="Bonussen gaan naar een gunstige teelt en een goede verpakking. Vliegtransport en moeilijk te sorteren verpakkingen geven juist een malus.",
    ),
    dict(
        type="waarofniet",
        vraag="Nutriscore en ecoscore meten hetzelfde.",
        antwoord=False,
        uitleg="De nutriscore gaat over jouw gezondheid, de ecoscore over het milieu. Een product kan een goede nutriscore hebben en toch zwaar wegen op het milieu.",
    ),
    dict(
        type="meerkeuze",
        vraag="Twee producten zijn even voedzaam. Het ene komt van hier, het andere is overgevlogen. Wat volgt daaruit?",
        opties=[
            "het product van hier haalt een betere ecoscore",
            "het product van hier haalt een betere nutriscore",
            "beide producten halen dezelfde ecoscore",
            "het overgevlogen product is altijd verser",
        ],
        antwoord=0,
        uitleg="Vliegtransport weegt zwaar in de levenscyclus. De nutriscore verandert er niet door, want de samenstelling blijft dezelfde.",
    ),
    dict(
        type="meerkeuze",
        vraag="Je hebt midden in de namiddag een energiedip. Wat helpt het snelst?",
        opties=[
            "een stuk fruit",
            "een handvol noten",
            "een boterham met kaas",
            "een glas water",
        ],
        antwoord=0,
        uitleg="Fruit bevat glucose en fructose, die meteen opgenomen worden. Noten en brood geven trager energie, en water geeft er helemaal geen.",
    ),
    dict(
        type="waarofniet",
        vraag="Een product met nutriscore A mag je in onbeperkte hoeveelheden eten.",
        antwoord=False,
        uitleg="De nutriscore vergelijkt producten binnen dezelfde groep en zegt niets over hoeveel je eet. De hoeveelheid blijft dus altijd meetellen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Op een etiket staat: suiker 32 g per 100 g. Wat betekent dat?",
        opties=[
            "bijna een derde van het product is suiker",
            "er zit 32 gram suiker in de verpakking",
            "je mag er 32 gram per dag van eten",
            "er zit 32 procent minder suiker in dan gewoonlijk",
        ],
        antwoord=0,
        uitleg="Per honderd gram betekent per honderd gram product. Tweeëndertig van die honderd gram is dus suiker, en dat is bijna een derde.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een pot van 250 gram bevat 32 gram suiker per 100 gram. Hoeveel suiker zit er in de hele pot?",
        opties=[
            "80 g",
            "32 g",
            "64 g",
            "128 g",
        ],
        antwoord=0,
        uitleg="Je rekent 32 maal 2,5, want 250 gram is twee en een halve keer honderd gram. Dat geeft tachtig gram suiker in de volledige pot.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je het systeem met de letters A tot E dat zegt hoe gezond de samenstelling is?",
        antwoord=["nutriscore", "de nutriscore", "nutri-score"],
        uitleg="De nutriscore staat vooraan op de verpakking, met een gekleurde letter van A tot E. Hij helpt vooral om twee producten uit dezelfde groep te vergelijken.",
    ),
    dict(
        type="waarofniet",
        vraag="Een etiket moet vermelden hoeveel energie, vet, koolhydraten, eiwit en zout het product bevat.",
        antwoord=True,
        uitleg="Die voedingswaardetabel is verplicht in Europa. Daardoor kan je producten op dezelfde manier naast elkaar leggen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarom staat op veel verpakkingen dat het product sporen van noten kan bevatten?",
        opties=[
            "in dezelfde fabriek worden ook noten verwerkt",
            "er zitten altijd een paar noten in het product",
            "noten verbeteren de houdbaarheid",
            "de wet verplicht die zin op elk etiket",
        ],
        antwoord=0,
        uitleg="Het is een waarschuwing voor onbedoelde vermenging via dezelfde machines. Voor wie zwaar allergisch is, is dat een echt risico.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke bestanddelen trekken de nutriscore naar beneden? Er zijn er drie.",
        opties=[
            "veel suiker",
            "veel zout",
            "veel verzadigd vet",
            "veel vezels",
        ],
        antwoord=[0, 1, 2],
        uitleg="Suiker, zout en verzadigd vet zijn de ongunstige punten. Vezels, eiwit, fruit en groenten tellen juist in de gunstige richting.",
    ),
    dict(
        type="waarofniet",
        vraag="De ecoscore van een product hangt mee af van zijn verpakking.",
        antwoord=True,
        uitleg="De verpakking hoort bij de levenscyclus. Een goed recycleerbare verpakking levert een bonus op, een moeilijk te sorteren verpakking een malus.",
    ),
]
