# -*- coding: utf-8 -*-
"""Samenhang en causaliteit.

Uit het onderdeel "Statistiek" van de bouwsteen Kansrekenen en statistiek,
vakfiche wiskunde 3 dubbele finaliteit: het verschil tussen samenhang en
causaliteit, de omwisseling van oorzaak en gevolg, de derde verborgen
variabele en samenhang die door toeval ontstaat.
"""

DEEL1 = [
    dict(
        type="meerkeuze",
        vraag="Wat betekent samenhang tussen twee variabelen?",
        opties=["ze veranderen samen", "de ene veroorzaakt de andere",
                "ze zijn allebei even groot", "ze hebben niets met elkaar te maken"],
        antwoord=0,
        uitleg="Samen veranderen zegt nog niet waarom. Dat laatste is precies de vraag bij causaliteit.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je het als de ene variabele de andere echt veroorzaakt?",
        antwoord=["causaliteit", "een causaal verband", "causaal verband"],
        uitleg="Dan is er niet alleen samenhang, maar ook een oorzaak en een gevolg.",
    ),
    dict(
        type="waarofniet",
        vraag="Samenhang betekent altijd dat er een oorzakelijk verband is.",
        antwoord=False,
        uitleg="Dat is de meest voorkomende denkfout in de statistiek. Samenhang is een aanwijzing, geen bewijs.",
    ),
    dict(
        type="meerkeuze",
        vraag="In de zomer worden er meer ijsjes verkocht en verdrinken er meer mensen. Wat is hier aan de hand?",
        opties=["een derde verborgen variabele, namelijk het warme weer", "ijsjes eten maakt mensen onvoorzichtig in het water", "verdrinkingen zorgen ervoor dat er meer ijsjes verkocht worden", "er is helemaal geen samenhang tussen die twee"],
        antwoord=0,
        uitleg="Warm weer drijft allebei omhoog. Zonder die derde variabele lijken ze oorzakelijk verbonden.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je een factor die twee variabelen allebei beïnvloedt, zodat ze samen bewegen zonder elkaar te veroorzaken?",
        antwoord=["een verborgen variabele", "verborgen variabele", "derde variabele"],
        uitleg="Soms heet ze ook een storende variabele. Ze zit niet in je gegevens, maar wel in de werkelijkheid.",
    ),
    dict(
        type="meerkeuze",
        vraag="Kinderen met grotere voeten lezen beter. Wat is de verborgen variabele?",
        opties=["de leeftijd", "het schoenmerk", "de school", "de lengte van het boek"],
        antwoord=0,
        uitleg="Oudere kinderen hebben grotere voeten én lezen beter. De voeten doen niets aan het lezen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Men stelt vast dat mensen met een hond meer bewegen. Welke mogelijkheid moet je ook overwegen?",
        opties=["mensen die graag bewegen, nemen vaker een hond", "een hond beweegt eigenlijk zelf niet zoveel", "veel bewegen zorgt ervoor dat er honden bijkomen", "er is geen samenhang tussen honden en beweging"],
        antwoord=0,
        uitleg="Dan zijn oorzaak en gevolg omgewisseld. Dat is een van de vier gevallen die je moet kunnen onderscheiden.",
    ),
    dict(
        type="waarofniet",
        vraag="Oorzaak en gevolg kunnen in een onderzoek omgewisseld lijken.",
        antwoord=True,
        uitleg="Uit de cijfers alleen zie je vaak niet wat eerst kwam. Daarvoor heb je kennis van de situatie nodig.",
    ),
    dict(
        type="meerkeuze",
        vraag="Het aantal films met een bepaalde acteur loopt jarenlang gelijk met de kaasconsumptie. Wat is de verklaring?",
        opties=["toeval", "de acteur eet veel kaas", "kaas maakt films populair", "een verborgen variabele"],
        antwoord=0,
        uitleg="Zoek je in genoeg reeksen, dan vind je altijd twee die toevallig samen op en neer gaan. Zonder verklaring is zo'n verband waardeloos.",
    ),
    dict(
        type="waarofniet",
        vraag="Een sterke samenhang kan zuiver door toeval ontstaan.",
        antwoord=True,
        uitleg="Zeker bij korte reeksen of als je in heel veel gegevens gaat zoeken tot er iets opvalt.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke vier gevallen moet je kunnen onderscheiden bij een statistisch verband?",
        opties=["causaliteit, omgewisselde causaliteit, een verborgen variabele en toeval", "optellen, aftrekken, vermenigvuldigen en delen van de gegevens", "het gemiddelde, de mediaan, de modus en de spreiding van de reeks", "de populatie, de steekproef, de variabele en het besluit van het onderzoek"],
        antwoord=0,
        uitleg="Pas als je de drie andere kan uitsluiten, mag je over een oorzaak spreken.",
    ),
    dict(
        type="meerkeuze",
        vraag="Hoe toon je het sterkst aan dat A werkelijk B veroorzaakt?",
        opties=["met een proef waarin je A verandert en de rest gelijk houdt", "door nog veel meer gegevens te verzamelen over A en B", "door een duidelijkere grafiek van het verband te maken", "door het aan een aantal experts voor te leggen"],
        antwoord=0,
        uitleg="Alleen een gecontroleerde proef kan een verborgen variabele uitsluiten. Waarnemen alleen volstaat niet.",
    ),
    dict(
        type="waarofniet",
        vraag="Twee variabelen die samenhangen, beïnvloeden elkaar altijd.",
        antwoord=False,
        uitleg="Bij een verborgen variabele of bij toeval bewegen ze samen zonder elkaar te beïnvloeden.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een krantenkop zegt: wie ontbijt haalt betere punten. Wat is de voorzichtige lezing?",
        opties=["ontbijten hangt samen met betere punten", "ontbijten veroorzaakt betere punten",
                "betere punten veroorzaken ontbijten", "er is geen verband"],
        antwoord=0,
        uitleg="Misschien speelt een rustiger gezinssituatie mee, en die zorgt voor allebei.",
    ),
    dict(
        type="waarofniet",
        vraag="Als twee grootheden samen stijgen, is er altijd een oorzakelijk verband.",
        antwoord=False,
        uitleg="Samen stijgen is samenhang. Voor een oorzaak heb je een mechanisme nodig dat uitlegt hoe het werkt.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een onderzoek vindt dat steden met meer brandweermannen meer brandschade hebben. Wat is de verborgen variabele?",
        opties=["de grootte van de stad", "het aantal brandweerwagens",
                "de kleur van de helmen", "het weer"],
        antwoord=0,
        uitleg="Grote steden hebben meer van allebei. De brandweer veroorzaakt de schade niet.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je een proef waarin je één factor verandert en al de rest gelijk houdt?",
        antwoord=["een gecontroleerde proef", "gecontroleerde proef", "experiment"],
        uitleg="Zo weet je dat een verschil in de uitkomst van die ene factor komt.",
    ),
    dict(
        type="meerkeuze",
        vraag="Men vindt een verband tussen slaaptekort en slechte punten. Welke vraag helpt om causaliteit te beoordelen?",
        opties=["is er een verklaring hoe slaaptekort het leren hindert", "hoeveel mensen hebben aan het onderzoek meegedaan", "wie heeft het onderzoek betaald en uitgevoerd", "in welk jaar is het onderzoek gevoerd"],
        antwoord=0,
        uitleg="Een plausibel mechanisme is een van de sterkste argumenten voor een oorzaak.",
    ),
    dict(
        type="waarofniet",
        vraag="Terecht of onterecht een causaal verband suggereren is iets wat je van een onderzoek moet kunnen beoordelen.",
        antwoord=True,
        uitleg="Dat is precies waar statistiek je kritisch maakt: niet de getallen controleren, maar de conclusie.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een reclame zegt: mensen die ons product gebruiken, zijn gezonder. Wat ontbreekt?",
        opties=["een vergelijking met een gelijkaardige groep zonder het product", "een steekproef met beduidend meer gebruikers erin", "een duidelijkere grafiek van de gezondheidswinst", "een product dat wat duurder uitvalt"],
        antwoord=0,
        uitleg="Zonder controlegroep kan het evengoed zijn dat gezonde mensen het product vaker kopen.",
    ),
]

DEEL2 = [
    dict(
        type="meerkeuze",
        vraag="In landen met meer tv-toestellen leven mensen langer. Wat is de meest waarschijnlijke verklaring?",
        opties=["rijkere landen hebben betere zorg én meer toestellen", "televisie kijken verlengt het leven van mensen", "wie lang leeft, koopt in de loop van zijn leven meer tv's", "het is zuiver toeval zonder enige verklaring"],
        antwoord=0,
        uitleg="De welvaart van een land is de verborgen variabele achter allebei.",
    ),
    dict(
        type="waarofniet",
        vraag="Een verband dat je niet kan verklaren, is daarom nog geen oorzaak.",
        antwoord=True,
        uitleg="Zonder mechanisme blijft het een waarneming. Het kan evengoed toeval of een verborgen variabele zijn.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een studie ziet dat wie meer water drinkt, minder hoofdpijn heeft. Welke omgekeerde verklaring is denkbaar?",
        opties=["wie hoofdpijn heeft, drinkt minder", "water drinken veroorzaakt hoofdpijn", "hoofdpijn maakt een mens dorstig", "er is geen verband tussen beide"],
        antwoord=0,
        uitleg="Bij hoofdpijn blijft men liggen en drinkt men minder. Dan is het gevolg de oorzaak geworden.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een gemeente zet meer verlichting en ziet de criminaliteit dalen. Wat moet je nog nagaan?",
        opties=["of de criminaliteit elders ook daalde", "of de lampen wit of geel licht geven", "hoeveel die lampen gekost hebben", "wie de lampen geplaatst heeft"],
        antwoord=0,
        uitleg="Daalde ze overal, dan was er iets anders aan de hand en is de verlichting niet de oorzaak.",
    ),
    dict(
        type="waarofniet",
        vraag="Een controlegroep zegt niets over een causaal verband.",
        antwoord=False,
        uitleg="Ze helpt juist wel: je vergelijkt met een groep die alles hetzelfde meemaakt behalve die ene factor.",
    ),
    dict(
        type="meerkeuze",
        vraag="Twee reeksen lopen tien jaar lang bijna perfect samen, maar niemand kan uitleggen waarom. Hoe noem je dat?",
        opties=["een toevallige samenhang", "een causaal verband",
                "een verborgen variabele", "een vertekende steekproef"],
        antwoord=0,
        uitleg="Zoek je in honderden reeksen, dan vind je zulke paren vanzelf. Daar is geen betekenis aan te geven.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je in een proef de groep die het middel niet krijgt?",
        antwoord=["de controlegroep", "controlegroep"],
        uitleg="Zonder zo'n groep weet je niet of het verschil van het middel komt of van iets anders.",
    ),
    dict(
        type="waarofniet",
        vraag="Een onderzoek dat alleen waarneemt, kan nooit met zekerheid een oorzaak aantonen.",
        antwoord=True,
        uitleg="Er blijft altijd een verborgen variabele mogelijk. Zekerder word je pas met een proef waarin je zelf iets verandert.",
    ),
    dict(
        type="meerkeuze",
        vraag="Men vindt dat scholen met meer computers betere resultaten halen. Welke verborgen variabele ligt voor de hand?",
        opties=["het budget van de school", "het merk van de computers",
                "de kleur van de lokalen", "de afstand tot de school"],
        antwoord=0,
        uitleg="Een rijkere school heeft meer computers én meer leerkrachten, kleinere klassen en meer materiaal.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een artikel kopt: koffie verlengt je leven. Het onderzoek was een bevraging. Wat is je besluit?",
        opties=["dit toont samenhang, geen oorzaak", "koffie is gezond voor iedereen", "koffie is ongezond voor iedereen", "het onderzoek is vervalst"],
        antwoord=0,
        uitleg="Een bevraging neemt waar. Wie koffie drinkt, verschilt mogelijk ook op andere manieren.",
    ),
    dict(
        type="waarofniet",
        vraag="Van samenhang spreek je alleen als allebei de variabelen omhoog gaan.",
        antwoord=False,
        uitleg="Ook als de ene omhoog gaat terwijl de andere omlaag gaat, bewegen ze samen. Dat heet een negatieve samenhang.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarom is het zinvol om bij een causale uitspraak naar de opzet van het onderzoek te vragen?",
        opties=["de opzet bepaalt wat je mag besluiten", "de opzet bepaalt het gemiddelde", "de opzet bepaalt wie de populatie is", "dat is alleen maar beleefdheid"],
        antwoord=0,
        uitleg="Een proef met controlegroep draagt veel verder dan een bevraging achteraf.",
    ),
    dict(
        type="waarofniet",
        vraag="Als A en B samenhangen, kan B evengoed de oorzaak van A zijn.",
        antwoord=True,
        uitleg="De cijfers zeggen niet in welke richting het loopt. Daarvoor heb je kennis van de situatie nodig.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een verzekeraar merkt dat rode auto's vaker ongevallen hebben. Welke verklaring is het meest waarschijnlijk?",
        opties=["wie rood kiest, rijdt misschien anders", "rood maakt een auto minder zichtbaar", "een ongeval doet de kleur rood lijken", "de kleur heeft invloed op de remweg"],
        antwoord=0,
        uitleg="De bestuurder is hier de verborgen variabele, niet de verf.",
    ),
    dict(
        type="invultekst",
        vraag="Vul aan: samenhang is geen bewijs van wat?",
        antwoord=["causaliteit", "oorzaak", "een oorzaak"],
        uitleg="Dat is de belangrijkste regel uit dit hoofdstuk, en de meest genegeerde in de krant.",
    ),
    dict(
        type="waarofniet",
        vraag="Een onderzoeker die een causaal verband suggereert, heeft daarmee altijd gelijk.",
        antwoord=False,
        uitleg="Je mag en moet beoordelen of hij dat terecht doet, door de drie andere verklaringen te overwegen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Twee variabelen hangen samen én er is een gecontroleerde proef die hetzelfde vindt. Wat besluit je?",
        opties=["een causaal verband is nu veel aannemelijker", "er is zeker geen verband tussen beide", "het gaat hier om zuiver toeval", "je kan hier nog niets uit besluiten"],
        antwoord=0,
        uitleg="De proef sluit de verborgen variabele uit, en dat is precies wat samenhang alleen niet kan.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is de beste houding bij een opvallende statistiek in de krant?",
        opties=["vragen hoe de gegevens verzameld zijn", "de uitkomst meteen geloven", "de uitkomst meteen afwijzen", "de getallen zelf natellen"],
        antwoord=0,
        uitleg="De opzet beslist of de conclusie draagt. De rekenkunde klopt meestal wel.",
    ),
    dict(
        type="waarofniet",
        vraag="Een verborgen variabele staat gewoon in de tabel van het onderzoek.",
        antwoord=False,
        uitleg="Ze is juist niet gemeten. Daarom moet je ze zelf bedenken vanuit je kennis van de situatie.",
    ),
    dict(
        type="meerkeuze",
        vraag="Men ziet dat leerlingen die veel huiswerk maken hogere punten halen. Welke verklaring is de voorzichtigste?",
        opties=["er is samenhang, en de richting is nog onduidelijk", "huiswerk maken veroorzaakt hoge punten", "hoge punten veroorzaken meer huiswerk maken", "er is geen enkel verband tussen beide"],
        antwoord=0,
        uitleg="Misschien maken gemotiveerde leerlingen meer huiswerk én studeren ze meer. Dan is motivatie de verborgen variabele.",
    ),
]
