# -*- coding: utf-8 -*-
"""Probleemoplossend denken: mathematiseren, heuristieken en rekenen met ICT.

Uit de bouwsteen "Probleemoplossend denken" van de vakfiche wiskunde,
3 dubbele finaliteit: de vier stappen, de heuristieken die ze opsomt, het
onderscheid tussen een vraagstuk en een probleem, tussen een opgave met en
zonder context, en waarvoor ICT op het examen gebruikt mag worden.
"""

DEEL1 = [
    dict(
        type="meerkeuze",
        vraag="Wat is de eerste van de vier stappen bij het oplossen van een probleem?",
        opties=["Begrijp het probleem.", "Maak een plan.", "Voer het plan uit.", "Reflecteer."],
        antwoord=0,
        uitleg="Pas als je weet wat er gevraagd wordt en wat je gegeven hebt, heeft een plan zin.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is de laatste van de vier stappen?",
        opties=["Reflecteer.", "Voer het plan uit.", "Maak een plan.", "Begrijp het probleem."],
        antwoord=0,
        uitleg="Na het rekenen kijk je terug: klopt het antwoord, en was dit een handige weg?",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je het omzetten van een concrete situatie naar wiskundetaal en wiskundige symbolen?",
        antwoord=["mathematiseren", "mathematiseren."],
        uitleg="Je vertaalt de situatie naar wiskunde. De omgekeerde weg, het antwoord terugvertalen naar de situatie, heet demathematiseren.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je het terugvertalen van een wiskundige uitkomst naar de situatie waar de opgave over ging?",
        antwoord=["demathematiseren", "demathematiseren."],
        uitleg="Je uitkomst is een getal; demathematiseren betekent dat je er een zin van maakt die de vraag beantwoordt.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een opgave die je kan oplossen met de leerstof van één hoofdstuk, heet wat?",
        opties=["een vraagstuk", "een probleem", "een heuristiek", "een model"],
        antwoord=0,
        uitleg="Een probleem is ruimer: dat hangt niet aan één hoofdstuk en vraagt dat je leerstof combineert.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een opgave die je niet aan één hoofdstuk kan koppelen en waarvoor je leerstof moet combineren, heet wat?",
        opties=["een probleem", "een vraagstuk", "een context", "een voorschrift"],
        antwoord=0,
        uitleg="Bij een probleem kies je zelf de strategie; bij een vraagstuk weet je uit welk hoofdstuk je moet putten.",
    ),
    dict(
        type="waarofniet",
        vraag="Een opgave zonder context is abstract en zuiver wiskundig.",
        antwoord=True,
        uitleg="Een opgave met context vertrekt juist wel van een situatie uit de wereld rondom je.",
    ),
    dict(
        type="waarofniet",
        vraag="Een opgave met context is altijd moeilijker dan een opgave zonder context.",
        antwoord=False,
        uitleg="Allebei kunnen makkelijk of moeilijk zijn. Het verschil zit in de verpakking, niet in de moeilijkheid.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je met één woord een oplossingsstrategie zoals een schets maken of terugrekenen?",
        antwoord=["heuristiek", "een heuristiek", "heuristieken"],
        uitleg="Een heuristiek is geen recept dat altijd werkt, maar een aanpak die vaak vooruithelpt.",
    ),
    dict(
        type="meerkeuze",
        vraag="Je weet hoeveel er na afloop overblijft en je zoekt hoeveel er in het begin was. Welke strategie past hier het best?",
        opties=["terugrekenen", "alle mogelijkheden opschrijven", "een variabele invoeren", "simuleren"],
        antwoord=0,
        uitleg="Je begint bij het einde en draait elke stap om: wat opgeteld werd, trek je weer af.",
    ),
    dict(
        type="meerkeuze",
        vraag="In een opgave staan veel getallen door elkaar. Welke strategie helpt het eerst?",
        opties=["de gegevens in een tabel ordenen", "meteen beginnen rekenen", "het antwoord gokken", "de opgave overschrijven"],
        antwoord=0,
        uitleg="Door de gegevens te ordenen zie je pas welke je hebt en welke je mist.",
    ),
    dict(
        type="meerkeuze",
        vraag="Je weet nog niet hoeveel er in de doos zit en noemt dat aantal x. Welke strategie is dat?",
        opties=["een variabele invoeren", "terugrekenen", "een schets maken", "reflecteren"],
        antwoord=0,
        uitleg="Met een variabele kan je over een onbekende rekenen alsof ze al gekend is.",
    ),
    dict(
        type="waarofniet",
        vraag="Een schets maken is een van de strategieën die je bij een vraagstuk mag gebruiken.",
        antwoord=True,
        uitleg="Een tekening, schets of tabel vertaalt het probleem naar een vorm waarin je het beter ziet.",
    ),
    dict(
        type="invultekst",
        vraag="Je splitst een moeilijke opgave in kleinere stukken die je apart oplost. Hoe heten die stukken?",
        antwoord=["deelproblemen", "deelproblemen.", "deelprobleem"],
        uitleg="Elk deelprobleem is op zich haalbaar; samen geven ze het antwoord op het geheel.",
    ),
    dict(
        type="meerkeuze",
        vraag="Je probeert een getal, kijkt of het klopt en past het dan aan. Hoe heet die strategie?",
        opties=["slim gissen en testen", "logisch redeneren", "demathematiseren", "een model opstellen"],
        antwoord=0,
        uitleg="Slim gissen is geen blind gokken: je gebruikt elke mislukte poging om je volgende schatting te verbeteren.",
    ),
    dict(
        type="waarofniet",
        vraag="Je mag op het examen een gsm gebruiken om te rekenen.",
        antwoord=False,
        uitleg="Een gsm of smartwatch in de examenruimte geldt als fraude. Wel mag je de rekenapps en een online rekentoestel op het scherm gebruiken.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarvoor mag je op het examen ICT gebruiken?",
        opties=["om een grafiek te tekenen", "om de opgave te laten vertalen", "om een antwoord op te zoeken", "om je samenvatting te lezen"],
        antwoord=0,
        uitleg="ICT dient om te rekenen, grafieken te tekenen en statistische kengetallen te berekenen, niet om de leerstof te vervangen.",
    ),
    dict(
        type="waarofniet",
        vraag="Bij een berekening in meerdere stappen rond je elk tussenresultaat eerst af op één cijfer.",
        antwoord=False,
        uitleg="Je werkt met zo nauwkeurig mogelijke tussenresultaten. Hoe vroeger je afrondt, hoe verder je eindantwoord kan afwijken.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe heet de stap waarin je achteraf nagaat of je antwoord klopt en of je aanpak handig was?",
        antwoord=["reflecteren", "reflectie", "de reflectie"],
        uitleg="Reflecteren hoort bij het oplossen zelf: een antwoord dat je niet gecontroleerd hebt, is nog geen antwoord.",
    ),
    dict(
        type="meerkeuze",
        vraag="Je berekent dat een auto 540 kilometer per uur rijdt. Wat doe je?",
        opties=["je gaat je berekening na, want dat kan niet", "je noteert het zo", "je rondt af naar 500", "je deelt door twee"],
        antwoord=0,
        uitleg="Reflecteren betekent ook dat je je uitkomst toetst aan de werkelijkheid. Een onmogelijke waarde wijst op een rekenfout.",
    ),
]

DEEL2 = [
    dict(
        type="meerkeuze",
        vraag="Wat is de tweede stap, meteen na het begrijpen van het probleem?",
        opties=["een plan maken", "het plan uitvoeren", "reflecteren", "het antwoord opschrijven"],
        antwoord=0,
        uitleg="Eerst beslis je hoe je het gaat aanpakken, pas daarna begin je te rekenen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een opgave vraagt hoeveel liter verf je nodig hebt voor een muur. Wat is hier de context?",
        opties=["de muur die je wil schilderen", "de vermenigvuldiging", "het getal dat je uitkomt", "de eenheid liter"],
        antwoord=0,
        uitleg="De context is de situatie uit de werkelijkheid waar de opgave van vertrekt.",
    ),
    dict(
        type="invultekst",
        vraag="Je uitkomst is 7,5. De vraag was hoeveel bussen er nodig zijn. Hoeveel bussen antwoord je?",
        antwoord=["8", "acht", "8 bussen"],
        uitleg="Je vertaalt de uitkomst terug naar de situatie. Een halve bus bestaat niet, en met zeven bussen raakt niet iedereen mee.",
    ),
    dict(
        type="waarofniet",
        vraag="Demathematiseren betekent dat je je uitkomst terugvertaalt naar de situatie van de opgave.",
        antwoord=True,
        uitleg="Een kaal getal is nog geen antwoord. Je zegt erbij waarover het gaat en in welke eenheid.",
    ),
    dict(
        type="meerkeuze",
        vraag="Je schrijft alle mogelijke combinaties netjes onder elkaar op. Wanneer is dat een goede strategie?",
        opties=["als er weinig mogelijkheden zijn", "als er duizenden mogelijkheden zijn", "altijd", "nooit"],
        antwoord=0,
        uitleg="Bij een klein aantal is opsommen zeker en snel. Bij een groot aantal zoek je beter naar een regel of een formule.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een probleem gaat over een figuur die links en rechts hetzelfde is. Welke eigenschap gebruik je dan slim?",
        opties=["de symmetrie", "de omtrek", "de schaal", "het gemiddelde"],
        antwoord=0,
        uitleg="Met symmetrie hoef je maar de helft uit te rekenen en verdubbel je daarna.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je een reeks getallen waarin je telkens hetzelfde ziet terugkeren, bijvoorbeeld 3, 6, 9, 12?",
        antwoord=["een patroon", "patroon", "regelmaat"],
        uitleg="Wie het patroon ziet, hoeft niet elke stap apart te berekenen. Hier komt er telkens drie bij.",
    ),
    dict(
        type="waarofniet",
        vraag="Een heuristiek is een stappenplan dat bij elk probleem altijd tot de oplossing leidt.",
        antwoord=False,
        uitleg="Een heuristiek is een aanpak die vaak helpt, maar geen garantie geeft. Soms moet je een andere proberen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Je speelt een kansspel honderd keer na om te zien hoe vaak je wint. Hoe heet die aanpak?",
        opties=["simuleren", "terugrekenen", "mathematiseren", "afronden"],
        antwoord=0,
        uitleg="Je voert het vraagstuk zelf uit en kijkt wat er gebeurt. Dat geeft een schatting die je daarna kan narekenen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Je wil weten of een formule klopt en probeert ze eerst met x = 0 en x = 1. Welke strategie is dat?",
        opties=["speciale gevallen gebruiken", "alle mogelijkheden opschrijven", "variabelen invoeren", "reflecteren"],
        antwoord=0,
        uitleg="Met een paar makkelijke waarden merk je snel of je formule onmogelijke uitkomsten geeft.",
    ),
    dict(
        type="waarofniet",
        vraag="Bij het examen krijg je kladpapier en een balpen.",
        antwoord=True,
        uitleg="Je mag ook naar een geodriehoek, een passer of een meetlat vragen als je die nodig hebt.",
    ),
    dict(
        type="invultekst",
        vraag="Met welk hulpmiddel op het scherm bereken je tijdens het examen statistische kengetallen?",
        antwoord=["rekenapps", "de rekenapps", "een rekenapp"],
        uitleg="De rekenapps staan via een link in het examen zelf. Het loont om er thuis al mee te oefenen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Je uitkomst is 0,333333… en de vraag vraagt twee cijfers na de komma. Wat noteer je?",
        opties=["0,33", "0,3", "0,34", "0,333"],
        antwoord=0,
        uitleg="Je rondt pas af op het einde, en precies zo nauwkeurig als gevraagd wordt.",
    ),
    dict(
        type="waarofniet",
        vraag="Een opgave zonder context kan nooit een probleem zijn.",
        antwoord=False,
        uitleg="Ook een zuiver wiskundige opgave kan leerstof uit verschillende hoofdstukken combineren.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat doe je het eerst als je een lange opgave leest en meteen vastloopt?",
        opties=["onderstrepen wat gegeven is en wat gevraagd wordt", "een willekeurige formule invullen", "de opgave overslaan", "het antwoord gokken"],
        antwoord=0,
        uitleg="Het probleem begrijpen is de eerste stap. Wie niet weet wat gevraagd wordt, kan geen plan maken.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je het getal of de letter die in een opgave een nog onbekende waarde voorstelt?",
        antwoord=["een variabele", "variabele", "onbekende"],
        uitleg="Door een variabele in te voeren kan je een verband opschrijven voor je de waarde kent.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een opgave geeft een tabel met de winst per aantal stuks. Welke voorstelling maakt het verloop het snelst zichtbaar?",
        opties=["een grafiek", "een lijst namen", "een cirkel", "een letter"],
        antwoord=0,
        uitleg="Een grafiek toont in één oogopslag of iets stijgt, daalt of een top bereikt.",
    ),
    dict(
        type="waarofniet",
        vraag="Op het examen is er giscorrectie, dus je verliest punten als je een fout antwoord geeft.",
        antwoord=False,
        uitleg="Er is geen giscorrectie. Een vraag onbeantwoord laten levert dus zeker niets op.",
    ),
    dict(
        type="meerkeuze",
        vraag="Het examen wiskunde duurt hoelang?",
        opties=["150 minuten", "90 minuten", "180 minuten", "60 minuten"],
        antwoord=0,
        uitleg="Je legt het af in het examencentrum in Brussel, op de computer, met gesloten vragen.",
    ),
    dict(
        type="invultekst",
        vraag="Hoeveel procent van het examen wiskunde gaat over kansrekenen en statistiek?",
        antwoord=["40", "40 %", "40 procent"],
        uitleg="De andere zestig procent gaat over analyse: machten, logaritmen, functies en groei.",
    ),
]
