# -*- coding: utf-8 -*-
"""Watererosie, gletsjers en wind.

Uit de vakfiche aardrijkskunde van de 3de graad doorstroomfinaliteit (2027),
onderdeel De geosfeer, rubrieken Watererosie, Glaciale erosie en Winderosie.

Deel 1 is de rivier: het stroombekken met zijn waterscheidingskam, bron en
monding, het Hjülströmdiagram, de boven-, midden- en benedenloop met hun
debiet, stroomsnelheid en verval, de dalvormen van V-dal tot vlakbodemdal, de
meanders met hun holle en bolle oever, het evenwichtsprofiel en de
differentiële en terugschrijdende erosie.
Deel 2 zijn het ijs en de wind: gletsjertong, gletsjerfront en ijskap, het
U-dal, de cirque, de morene, de zwerfkei en de fjord, de glacialen van het
pleistoceen, en daarna de eolische processen met duinen, paddenstoelrotsen,
löss en dekzanden.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is een stroombekken?",
         opties=["het hele gebied dat op één rivier afwatert",
                 "de brede monding van een rivier in de zee",
                 "het stuk van een rivier met het grootste verval",
                 "de kom waarin een bergmeer ligt"],
         antwoord=0,
         uitleg="Alle neerslag die in een stroombekken valt, komt uiteindelijk in dezelfde rivier terecht. Twee bekkens worden gescheiden door een waterscheidingskam."),
    dict(type="invultekst",
         vraag="Hoe heet de lijn die twee stroombekkens van elkaar scheidt? Eén woord.",
         antwoord=["waterscheidingskam", "waterscheiding", "de waterscheidingskam"],
         uitleg="De waterscheidingskam volgt de hoogste punten. Regen die aan de ene kant valt, gaat naar de ene rivier, regen aan de andere kant naar de andere."),
    dict(type="meerkeuze",
         vraag="Wat kenmerkt de bovenloop van een rivier?",
         opties=["een groot verval",
                 "een hoge stroomsnelheid",
                 "vooral verticale erosie",
                 "een groot debiet door veel zijrivieren"],
         antwoord=[0, 1, 2],
         uitleg="In de bovenloop is het hoogteverschil groot en het water snel, en snijdt de rivier zich in de diepte in. Het debiet is er nog klein, want er is weinig water verzameld."),
    dict(type="meerkeuze",
         vraag="Welke dalvorm hoort bij de bovenloop van een rivier?",
         opties=["het V-dal", "het vlakbodemdal",
                 "het U-dal van een gletsjer", "de alluviale vlakte"],
         antwoord=0,
         uitleg="In de bovenloop overheerst de verticale erosie. De rivier zaagt zich in en de wanden blijven steil: dat geeft een V-vormig dal."),
    dict(type="waarofniet",
         vraag="In de benedenloop van een rivier overheerst de sedimentatie.",
         antwoord=True,
         uitleg="Het verval is daar klein en het water stroomt traag, dus laat het zijn lading vallen. Zo ontstaan alluviale vlakten en een delta."),
    dict(type="invultekst",
         vraag="Hoe heet de vlakte die een rivier met haar eigen afzettingen opbouwt? Twee woorden.",
         antwoord=["alluviale vlakte", "de alluviale vlakte", "alluviale laagvlakte"],
         uitleg="Bij elke overstroming blijft een laagje slib achter. Dat maakt een alluviale vlakte vlak en heel vruchtbaar."),
    dict(type="meerkeuze",
         vraag="Wat lees je op een Hjülströmdiagram af?",
         opties=["wat een korrel bij welke snelheid doet",
                 "hoeveel water een rivier per seconde afvoert",
                 "hoe hoog het water bij een overstroming komt",
                 "hoe diep een dal in het gesteente is gesneden"],
         antwoord=0,
         uitleg="Het diagram zet de korrelgrootte tegen de stroomsnelheid. Daaruit lees je af of een deeltje wordt opgenomen, vervoerd of afgezet."),
    dict(type="meerkeuze",
         vraag="Welk deeltje heeft de hoogste stroomsnelheid nodig om opgenomen te worden?",
         opties=["een grove kei", "een zandkorrel",
                 "een siltdeeltje", "een kleideeltje"],
         antwoord=0,
         uitleg="Hoe groter en zwaarder, hoe meer energie er nodig is. Klei is wel een uitzondering: die deeltjes plakken zo sterk aan elkaar dat er ook veel kracht nodig is om ze los te maken."),
    dict(type="invultekst",
         vraag="Hoe heet de transportwijze waarbij korrels zwevend in het water worden meegevoerd? Eén woord.",
         antwoord=["suspensie", "in suspensie"],
         uitleg="Bij suspensie blijven de deeltjes zweven, bij saltatie huppelen ze over de bodem, en de grootste keien rollen of schuiven."),
    dict(type="meerkeuze",
         vraag="Hoe ontstaat een meander?",
         opties=["de rivier erodeert zijdelings in een vlak gebied",
                 "de rivier snijdt zich recht in de diepte in",
                 "een gletsjer schuurt een bocht in het dal",
                 "de wind blaast zand in een kromme rug"],
         antwoord=0,
         uitleg="Waar het verval klein is, gaat de erosie zijwaarts. De rivier slingert dan en maakt haar bochten steeds groter."),
    dict(type="meerkeuze",
         vraag="Wat gebeurt er in een meander?",
         opties=["de holle oever wordt uitgeschuurd",
                 "aan de bolle oever wordt zand afgezet",
                 "de bocht wordt doorheen de jaren groter",
                 "de rivier snijdt er diep in het gesteente"],
         antwoord=[0, 1, 2],
         uitleg="In de buitenbocht of holle oever stroomt het water snel en erodeert het; in de binnenbocht of bolle oever stroomt het traag en zet het af. Daardoor schuift de bocht op."),
    dict(type="waarofniet",
         vraag="Aan de holle oever van een meander wordt materiaal afgezet.",
         antwoord=False,
         uitleg="Net omgekeerd: aan de holle of buitenoever wordt geërodeerd, en aan de bolle of binnenoever wordt afgezet."),
    dict(type="meerkeuze",
         vraag="Wat is het evenwichtsprofiel van een rivier?",
         opties=["de lijn waar erosie en afzetting in balans zijn",
                 "de grens van het stroombekken op de kaart",
                 "de breedte die een rivier bij hoogwater haalt",
                 "de diepte waarop het grondwater zich bevindt"],
         antwoord=0,
         uitleg="Een rivier streeft naar een vlotte, holle lijn van bron naar monding. Watervallen en stroomversnellingen zijn de plaatsen waar dat profiel nog niet bereikt is."),
    dict(type="meerkeuze",
         vraag="Wat is differentiële erosie?",
         opties=["hard gesteente erodeert trager dan zacht",
                 "een rivier erodeert enkel in de winter",
                 "de erosie verschilt van jaar tot jaar",
                 "erosie stopt zodra er een dal gevormd is"],
         antwoord=0,
         uitleg="Omdat niet alle lagen even goed weerstaan, blijven de harde banken als ribbels of watervallen staan en worden de zachte uitgeschuurd. Zo krijgt het landschap zijn vorm."),
    dict(type="invultekst",
         vraag="Hoe heet de erosie waarbij een waterval zich stroomopwaarts terugwerkt? Eén woord.",
         antwoord=["terugschrijdende", "terugschrijdende erosie", "terugschrijdend"],
         uitleg="Het water holt de zachte laag onder de harde bank uit, de bank breekt af, en de waterval schuift een stukje naar achter. De Niagarawatervallen doen dat nog altijd."),
    dict(type="waarofniet",
         vraag="Een rivier vervoert haar materiaal enkel rollend over de bodem.",
         antwoord=False,
         uitleg="Ze vervoert het ook zwevend (suspensie) en huppelend (saltatie), en daarnaast reizen opgeloste stoffen onzichtbaar mee."),
    dict(type="meerkeuze",
         vraag="Welke dalvorm hoort bij een rivier die zich in een vlakte heeft ingesneden en nu zijdelings uitbreidt?",
         opties=["het vlakbodemdal", "het V-dal",
                 "het kloofdal", "de cirque"],
         antwoord=0,
         uitleg="Een vlakbodemdal heeft een brede, vlakke bodem met de rivier erin slingerend, en duidelijke dalwanden aan weerszijden."),
    dict(type="waarofniet",
         vraag="Een kloofdal ontstaat waar een rivier zich snel insnijdt in hard gesteente.",
         antwoord=True,
         uitleg="Komt het gebied omhoog, dan gaat de rivier zich dieper insnijden. Is het gesteente hard genoeg om steil te blijven staan, dan krijg je een smalle kloof."),
    dict(type="invultekst",
         vraag="Hoe heet de plaats waar een rivier in de zee of in een andere rivier uitkomt? Eén woord.",
         antwoord=["monding", "de monding"],
         uitleg="Bij de monding is het verval nul. Daar zet de rivier haar laatste lading af, en als de zee die niet wegvoert, bouwt ze een delta op."),
    dict(type="meerkeuze",
         vraag="Waarom overstroomt een rivier sneller als haar bekken verhard is?",
         opties=["het water kan niet infiltreren",
                 "het stroomt meteen naar de rivier",
                 "het debiet krijgt een scherpe piek",
                 "er valt meer regen boven verharding"],
         antwoord=[0, 1, 2],
         uitleg="Op beton kan niets de grond in, dus bereikt al het water in één keer de rivier in plaats van traag door de bodem te sijpelen. Op de hoeveelheid regen heeft verharding geen invloed."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Welke dalvorm maakt een gletsjer?",
         opties=["een U-dal", "een V-dal",
                 "een kloofdal", "een vlakbodemdal"],
         antwoord=0,
         uitleg="Een gletsjer vult de hele dalbodem en schuurt ook de wanden af. Dat geeft een brede trog met een vlakke bodem en steile wanden: een U-dal."),
    dict(type="invultekst",
         vraag="Hoe heet de kom hoog in de bergen waar een gletsjer begint? Eén woord.",
         antwoord=["cirque", "een cirque", "kaar"],
         uitleg="In een cirque of kaar hoopt de sneeuw zich op en wordt ze tot ijs samengeperst. Van daaruit kruipt de gletsjertong naar beneden."),
    dict(type="meerkeuze",
         vraag="Wat is een morene?",
         opties=["een hoop puin die een gletsjer achterlaat",
                 "een scheur in het oppervlak van het ijs",
                 "een kras die het ijs in het gesteente trekt",
                 "een meer dat achter een ijsdam ligt"],
         antwoord=0,
         uitleg="Een gletsjer sleept gesteente mee. Langs de zijkant ligt een zijmorene, vooraan een eindmorene en onder het ijs een grondmorene."),
    dict(type="meerkeuze",
         vraag="Wat is een zwerfkei?",
         opties=["een blok dat een gletsjer heeft meegebracht",
                 "een kei die door een rivier is rondgerold",
                 "een brok die van een rotswand is gevallen",
                 "een steen die door de wind is afgesleten"],
         antwoord=0,
         uitleg="Een zwerfkei bestaat uit gesteente dat honderden kilometer verder thuishoort. Dat verraadt hoe ver de ijskap ooit reikte."),
    dict(type="waarofniet",
         vraag="Een fjord is een door een gletsjer uitgeschuurd dal dat later door de zee is ondergelopen.",
         antwoord=True,
         uitleg="Het ijs sneed diep uit, tot onder het huidige zeeniveau. Toen het wegsmolt en de zeespiegel steeg, liep het dal vol: een diep, smal zeearm met steile wanden."),
    dict(type="meerkeuze",
         vraag="Welke sporen laat een gletsjer in het landschap achter?",
         opties=["een U-dal en een cirque", "morenen en zwerfkeien",
                 "gletsjerkrassen op het gesteente", "dolines en resurgenties"],
         antwoord=[0, 1, 2],
         uitleg="De fiche noemt zwerfkei, fjord, bergmeer, stuwwal, morene, gletsjerkras, gletsjerkloof, U-dal en cirque. Dolines en resurgenties horen bij karst."),
    dict(type="invultekst",
         vraag="Hoe heet het laagste, smeltende uiteinde van een gletsjer? Eén woord.",
         antwoord=["gletsjerfront", "front", "het gletsjerfront"],
         uitleg="Aan het gletsjerfront smelt het ijs even snel weg als het wordt aangevoerd. Trekt een gletsjer zich terug, dan smelt er meer dan er bijkomt."),
    dict(type="meerkeuze",
         vraag="Hoe ontstaat een gletsjerkras in het gesteente?",
         opties=["stenen in het ijs krassen over de bodem",
                 "het ijs bevriest vast aan het gesteente",
                 "smeltwater snijdt groeven in de rots",
                 "de wind schuurt met zand over de rots"],
         antwoord=0,
         uitleg="De grondmorene werkt als schuurpapier. De krassen wijzen allemaal in de richting waarin het ijs bewoog, en zo weet je nog eeuwen later welke kant het uit ging."),
    dict(type="waarofniet",
         vraag="Een gletsjer beweegt niet, hij smelt enkel ter plaatse weg.",
         antwoord=False,
         uitleg="Een gletsjer stroomt wel degelijk, traag naar beneden onder zijn eigen gewicht. Juist die beweging maakt de erosie en de krassen."),
    dict(type="meerkeuze",
         vraag="Wat is een stuwwal?",
         opties=["een rug die door een ijskap is opgeduwd",
                 "een dijk die mensen tegen water bouwden",
                 "een wal van zand die de wind opbouwde",
                 "een rand van lava rond een krater"],
         antwoord=0,
         uitleg="Een voortschuivende ijskap duwt de lagen voor zich op, zoals een bulldozer. In Nederland zijn de Utrechtse Heuvelrug en de Veluwe zo gevormd."),
    dict(type="invultekst",
         vraag="Hoe heet het geologische tijdvak van de laatste grote ijstijden? Eén woord.",
         antwoord=["pleistoceen", "het pleistoceen"],
         uitleg="Het pleistoceen liep van ongeveer 2,6 miljoen tot 11 700 jaar geleden. Het wisselde glacialen, dus koude ijstijden, af met warmere interglacialen."),
    dict(type="meerkeuze",
         vraag="Wat is een interglaciaal?",
         opties=["een warme periode tussen twee ijstijden",
                 "de koudste fase van een ijstijd",
                 "de rand van een ijskap in de zee",
                 "een meer tussen twee gletsjertongen"],
         antwoord=0,
         uitleg="Glacialen zijn de koude fasen, interglacialen de warme. Wij leven zelf in een interglaciaal, het holoceen."),
    dict(type="waarofniet",
         vraag="Tijdens de laatste ijstijd lag er een ijskap over België.",
         antwoord=False,
         uitleg="Het ijs kwam tot in Nederland en Noord-Duitsland, maar niet tot in België. Ons land had wel een poolwoestijnklimaat, en daarvan komen de löss en de dekzanden."),
    dict(type="meerkeuze",
         vraag="Welke transportwijzen gebruikt de wind?",
         opties=["suspensie van fijn stof", "saltatie van zandkorrels",
                 "rollen van de grofste korrels", "oplossing van kalk"],
         antwoord=[0, 1, 2],
         uitleg="De fiche noemt suspensie, saltatie en rollen. Oplossen gebeurt in water, niet in de wind."),
    dict(type="meerkeuze",
         vraag="Hoe ontstaat een paddenstoelrots?",
         opties=["zand schuurt vooral onderaan de rots weg",
                 "de top van de rots verweert door de zon",
                 "regenwater lost de voet van de rots op",
                 "een gletsjer heeft de rots rond geschuurd"],
         antwoord=0,
         uitleg="De wind draagt zand maar tot ongeveer een meter hoog. Daar wordt dus het hardst geschuurd, en zo krijgt de rots een smalle voet en een brede hoed."),
    dict(type="invultekst",
         vraag="Hoe heet het fijne, door de wind aangevoerde leem dat in Vlaanderen en Haspengouw ligt? Eén woord.",
         antwoord=["löss", "loess", "de löss"],
         uitleg="Löss waaide in de ijstijd uit de kale vlakten aan en bleef in onze streken liggen. Het geeft de vruchtbaarste akkerbodem van België."),
    dict(type="meerkeuze",
         vraag="Welke woestijnvormen ontstaan door winderosie?",
         opties=["de rotswoestijn", "de steenwoestijn",
                 "het duinengebied", "de karstvlakte"],
         antwoord=[0, 1, 2],
         uitleg="De wind blaast het fijne materiaal weg en laat steen en rots achter. Waar het zand wel blijft liggen, bouwt hij duinen. Karst is het werk van water in kalk."),
    dict(type="waarofniet",
         vraag="Winderosie werkt het sterkst in een droog gebied met weinig plantengroei.",
         antwoord=True,
         uitleg="Vochtige korrels plakken aan elkaar en wortels houden de bodem vast. Droog en kaal is dus de voorwaarde, en dat geldt ook voor een akker in het voorjaar."),
    dict(type="meerkeuze",
         vraag="Waarom plant men hagen en houtkanten rond akkers aan?",
         opties=["om de wind te breken",
                 "om het regenwater sneller af te voeren",
                 "om de akker in de zomer op te warmen",
                 "om de bodem dieper te kunnen ploegen"],
         antwoord=0,
         uitleg="Een haag remt de wind af, zodat hij de losse bovenlaag niet meer kan wegblazen. Wortels houden de grond bovendien op zijn plaats."),
    dict(type="meerkeuze",
         vraag="Waarom vinden we in de Kempen dekzanden en in Haspengouw löss?",
         opties=["het zand viel dichter bij de bron dan het fijne leem",
                 "de Kempen lagen onder een ijskap en Haspengouw niet",
                 "het leem is er door de zee aangevoerd",
                 "de bodem is er door de mens omgewoeld"],
         antwoord=0,
         uitleg="De wind voerde in de ijstijd materiaal uit het noorden aan. Het zwaardere zand bleef het eerst liggen, het fijne leem waaide verder naar het zuidoosten."),
]
