# -*- coding: utf-8 -*-
"""Gesteenten, mineralen en de geologische tijd.

Uit de vakfiche aardrijkskunde van de 3de graad doorstroomfinaliteit (2027),
onderdeel De geosfeer, rubrieken Gesteenten en Datering.

Deel 1 zijn de mineralen en gesteenten uit de bijlage van de fiche, de drie
groepen met hun deelgroepen, en de gesteentecyclus.
Deel 2 is de datering: superpositie, discordantievlak, hiaat en intrusie, het
fossiel en het gidsfossiel, de halveringstijd, de geologische tijdschaal met
haar massa-extincties, en de Caledonische, Hercynische en Alpiene plooiing.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Welke drie grote groepen gesteenten zijn er?",
         opties=["magmatische, sedimentaire en metamorfe",
                 "harde, zachte en korrelige gesteenten",
                 "zware, lichte en poreuze gesteenten",
                 "oude, jonge en versteende gesteenten"],
         antwoord=0,
         uitleg="Magmatische gesteenten komen uit gesmolten magma, sedimentaire uit afzetting, en metamorfe uit omvorming onder druk en warmte."),
    dict(type="meerkeuze",
         vraag="Waarom heeft graniet grote, goed zichtbare kristallen?",
         opties=["het magma koelde heel langzaam af",
                 "het magma koelde heel snel af in water",
                 "het is onder hoge druk samengeperst",
                 "het is uit losse korrels aan elkaar gekit"],
         antwoord=0,
         uitleg="Graniet is een dieptegesteente: het magma bleef in de korst en koelde over duizenden jaren af. Dan krijgen de kristallen tijd om te groeien."),
    dict(type="meerkeuze",
         vraag="Welke gesteenten zijn uitvloeiingsgesteenten?",
         opties=["basalt", "puimsteen", "obsidiaan", "graniet"],
         antwoord=[0, 1, 2],
         uitleg="Basalt, puimsteen en obsidiaan zijn aan het oppervlak uitgevloeid en snel afgekoeld, dus fijnkorrelig of glasachtig. Graniet is een dieptegesteente."),
    dict(type="invultekst",
         vraag="Welk vulkanisch gesteente is zo vol gasbellen dat het op water blijft drijven?",
         antwoord=["puimsteen", "puimsteen (pumice)", "pumice"],
         uitleg="Puimsteen schuimt op doordat gas uit de lava ontsnapt terwijl ze stijft. Daardoor zit het vol holtes en is het lichter dan water."),
    dict(type="meerkeuze",
         vraag="Waarom heeft obsidiaan geen kristallen?",
         opties=["de lava koelde te snel af om te kristalliseren",
                 "de lava was volledig vrij van mineralen",
                 "de kristallen zijn later weggeërodeerd",
                 "het is een sedimentair gesteente zonder korrels"],
         antwoord=0,
         uitleg="Obsidiaan is vulkanisch glas. De afkoeling ging zo snel dat de atomen zich niet meer in een kristalrooster konden plaatsen."),
    dict(type="waarofniet",
         vraag="Diamant en grafiet bestaan uit precies dezelfde stof.",
         antwoord=True,
         uitleg="Beide zijn zuivere koolstof. Alleen de ordening van de atomen verschilt, en daardoor is diamant het hardste mineraal en grafiet zo zacht dat je ermee kan schrijven."),
    dict(type="meerkeuze",
         vraag="Welke losse sedimenten noemt de vakfiche, van grof naar fijn?",
         opties=["grind, zand, silt, klei", "klei, silt, zand, grind",
                 "zand, grind, klei, silt", "silt, klei, grind, zand"],
         antwoord=0,
         uitleg="Grind is het grofst, dan zand, dan silt of leem, en klei is het fijnst. Hoe fijner het deeltje, hoe traag stromender het water waarin het neerzakt."),
    dict(type="meerkeuze",
         vraag="Uit welk los sediment ontstaat zandsteen?",
         opties=["uit zand", "uit klei", "uit grind", "uit kalkslib"],
         antwoord=0,
         uitleg="Door de druk van bovenliggende lagen en door kalk of kiezel als kit worden de zandkorrels aan elkaar geplakt. Dat heet diagenese."),
    dict(type="invultekst",
         vraag="Hoe heet het vastgeworden gesteente dat uit grind ontstaat?",
         antwoord=["conglomeraat", "een conglomeraat"],
         uitleg="In een conglomeraat zie je de ronde keien nog in een fijnere kit zitten. Rond gerolde keien verraden transport door water."),
    dict(type="meerkeuze",
         vraag="Welke gesteenten zijn organogeen, dus uit resten van leven ontstaan?",
         opties=["krijt", "steenkool", "kalksteen uit schelpen",
                 "steenzout uit een opgedroogde zee"],
         antwoord=[0, 1, 2],
         uitleg="Krijt komt van kalkskeletjes van plankton, steenkool van plantenresten en veel kalksteen van schelpen en koraal. Steenzout is een chemisch gesteente."),
    dict(type="meerkeuze",
         vraag="Hoe is steenkool ontstaan?",
         opties=["uit plantenresten in moerassen",
                 "uit schelpen op de bodem van een warme zee",
                 "uit afgekoelde lava in een diepe laag",
                 "uit zand dat door druk is samengeperst"],
         antwoord=0,
         uitleg="In de steenkooltijd, het Carboon, groeiden uitgestrekte moerasbossen. Hun resten raakten onder water en onder nieuwe lagen, en werden over miljoenen jaren steenkool."),
    dict(type="waarofniet",
         vraag="Mergel bestaat uit een mengsel van kalk en klei.",
         antwoord=True,
         uitleg="Vandaar dat mergel zachter is dan kalksteen en makkelijk te zagen valt. In Limburg zijn er hele gangenstelsels in uitgehouwen."),
    dict(type="meerkeuze",
         vraag="Welk metamorf gesteente ontstaat uit kalksteen?",
         opties=["marmer", "kwartsiet", "gneiss", "leisteen"],
         antwoord=0,
         uitleg="Onder druk en warmte hergroeien de kalkkristallen groter en dichter: dat is marmer. Kwartsiet komt uit zandsteen, leisteen uit kleisteen en gneiss uit graniet."),
    dict(type="invultekst",
         vraag="Welk metamorf gesteente ontstaat uit zandsteen?",
         antwoord=["kwartsiet", "kwarsiet"],
         uitleg="De kwartskorrels van het zandsteen groeien aan elkaar vast tot een heel hard gesteente. In de Ardennen vormt het de harde ruggen in het landschap."),
    dict(type="meerkeuze",
         vraag="Uit welk gesteente ontstaat leisteen?",
         opties=["uit kleisteen", "uit kalksteen",
                 "uit zandsteen", "uit basalt"],
         antwoord=0,
         uitleg="Onder zijdelingse druk gaan de plaatjes in de klei allemaal in dezelfde richting staan. Daardoor splijt leisteen in dunne platen, handig voor dakbedekking."),
    dict(type="waarofniet",
         vraag="Metamorfe gesteenten zijn gesmolten en weer afgekoeld.",
         antwoord=False,
         uitleg="Bij metamorfose blijft het gesteente vast. Smelt het wel, dan wordt het magma en krijg je na afkoeling een magmatisch gesteente."),
    dict(type="meerkeuze",
         vraag="Welke mineralen staan in de bijlage van de vakfiche?",
         opties=["pyriet en grafiet", "diamant en kwarts",
                 "veldspaat en biotiet", "marmer en gneiss"],
         antwoord=[0, 1, 2],
         uitleg="De fiche vraagt pyriet, grafiet, diamant, kwarts, veldspaat, biotiet en zout als mineralen. Marmer en gneiss zijn gesteenten, geen mineralen."),
    dict(type="waarofniet",
         vraag="Een gesteente is een natuurlijk mengsel van mineralen.",
         antwoord=True,
         uitleg="Een mineraal heeft één vaste samenstelling en kristalvorm. Graniet bijvoorbeeld is een mengsel van kwarts, veldspaat en biotiet."),
    dict(type="invultekst",
         vraag="Hoe heet de kringloop waarin gesteenten voortdurend in elkaar overgaan? Eén woord.",
         antwoord=["gesteentecyclus", "de gesteentecyclus", "gesteentenkringloop"],
         uitleg="Magma koelt af tot magmatisch gesteente, dat verweert en wordt afgezet tot sediment, dat onder druk metamorf wordt en ten slotte weer kan smelten."),
    dict(type="waarofniet",
         vraag="In de gesteentecyclus kan een metamorf gesteente nooit opnieuw sediment worden.",
         antwoord=False,
         uitleg="Het is een echte kringloop. Komt marmer aan het oppervlak, dan verweert het, worden de brokjes vervoerd en afgezet, en begint het verhaal opnieuw."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat zegt de wet van de superpositie?",
         opties=["de onderste laag is de oudste",
                 "de onderste laag is de jongste",
                 "de dikste laag is altijd de oudste",
                 "de hardste laag is altijd de jongste"],
         antwoord=0,
         uitleg="In een ongestoorde opeenvolging van lagen is elke laag jonger dan de laag eronder. Dat is de basis van het relatief dateren."),
    dict(type="waarofniet",
         vraag="De wet van de superpositie geldt niet meer als de lagen door plooiing of een breuk zijn omgekeerd.",
         antwoord=True,
         uitleg="Daarom moet je eerst nagaan of de opeenvolging ongestoord is. Een plooi kan lagen volledig op hun kop zetten."),
    dict(type="meerkeuze",
         vraag="Een gang magma snijdt dwars door een reeks aardlagen. Wat weet je dan?",
         opties=["de intrusie is jonger dan die lagen",
                 "de intrusie is ouder dan die lagen",
                 "de intrusie is even oud als de lagen",
                 "de lagen zijn na de intrusie gesmolten"],
         antwoord=0,
         uitleg="Wat ergens dóór gaat, moet er later gekomen zijn. Dat geldt ook voor een breuk die lagen doorsnijdt."),
    dict(type="invultekst",
         vraag="Hoe heet gesmolten gesteente dat in bestaande lagen binnendringt en daar afkoelt? Eén woord.",
         antwoord=["intrusie", "een intrusie"],
         uitleg="Een intrusie is altijd jonger dan het gesteente waar ze doorheen gaat. Dat is een van de regels van het relatief dateren."),
    dict(type="meerkeuze",
         vraag="Wat is een discordantievlak?",
         opties=["een oud erosievlak tussen twee lagenreeksen",
                 "een breuk waarlangs twee blokken schuiven",
                 "een laag met heel veel fossielen",
                 "de grens tussen korst en mantel"],
         antwoord=0,
         uitleg="Op een discordantievlak liggen jongere lagen op oudere die eerst geplooid en afgesleten waren. Daar ontbreekt dus een stuk geschiedenis."),
    dict(type="invultekst",
         vraag="Hoe heet een ontbrekend stuk in de opeenvolging van aardlagen? Eén woord.",
         antwoord=["hiaat", "een hiaat", "lacune"],
         uitleg="Een hiaat betekent dat er in die periode niets is afgezet, of dat wat er lag weer is weggeërodeerd. De tijd zit dan niet in de lagen."),
    dict(type="waarofniet",
         vraag="Een gesteente dat dagzoomt, ligt diep onder de grond verborgen.",
         antwoord=False,
         uitleg="Dagzomen betekent net dat het aan het oppervlak aan de dag komt, bijvoorbeeld in een groeve of een wegberm. Een stratigrafische kaart toont wat waar dagzoomt."),
    dict(type="meerkeuze",
         vraag="Wat is een fossiel?",
         opties=["een versteend overblijfsel van leven",
                 "een kristal uit een diepe magmakamer",
                 "een gat dat door water is uitgeschuurd",
                 "een laag as van een oude uitbarsting"],
         antwoord=0,
         uitleg="Een organisme raakt onder sediment bedekt, de zachte delen vergaan en de harde delen worden door mineralen vervangen. Ook een voetspoor of een afdruk kan een fossiel zijn."),
    dict(type="waarofniet",
         vraag="Fossielen bewaren het best in magmatisch gesteente, want dat is het hardst.",
         antwoord=False,
         uitleg="In magmatisch gesteente is alles gesmolten en in metamorf gesteente platgedrukt. Alleen in rustig afgezet sediment blijft een organisme gaaf."),
    dict(type="meerkeuze",
         vraag="Wat maakt een fossiel een goed gidsfossiel?",
         opties=["de soort leefde maar kort op aarde",
                 "de soort kwam over een groot gebied voor",
                 "de soort is makkelijk te herkennen",
                 "de soort was het grootste dier van haar tijd"],
         antwoord=[0, 1, 2],
         uitleg="Kort geleefd, wijd verspreid en herkenbaar: vind je zo'n fossiel in een laag, dan weet je meteen hoe oud die laag ongeveer is. Grootte speelt geen rol."),
    dict(type="meerkeuze",
         vraag="Waarvoor dient de halveringstijd bij het dateren?",
         opties=["om de ouderdom in jaren te berekenen",
                 "om de dikte van een laag te meten",
                 "om de hardheid van een mineraal te bepalen",
                 "om de diepte van een breuk te schatten"],
         antwoord=0,
         uitleg="Een radioactieve stof vervalt met een vaste halveringstijd. Uit de verhouding tussen wat er nog over is en wat vervallen is, volgt een absolute ouderdom in jaren."),
    dict(type="invultekst",
         vraag="Hoe heet het dateren waarbij je enkel zegt wat ouder of jonger is, zonder jaartal? Eén woord.",
         antwoord=["relatief", "relatieve datering", "relatief dateren"],
         uitleg="Relatief dateren werkt met superpositie, intrusies, discordanties en gidsfossielen. Absoluut dateren geeft een ouderdom in jaren, met radioactief verval."),
    dict(type="meerkeuze",
         vraag="Welke tijdperken staan in de juiste orde, van oud naar jong?",
         opties=["Paleozoïcum, Mesozoïcum, Cenozoïcum",
                 "Mesozoïcum, Paleozoïcum, Cenozoïcum",
                 "Cenozoïcum, Mesozoïcum, Paleozoïcum",
                 "Paleozoïcum, Cenozoïcum, Mesozoïcum"],
         antwoord=0,
         uitleg="Na het Precambrium volgt het Paleozoïcum met onder meer het Carboon, dan het Mesozoïcum met de dinosaurussen, en ten slotte het Cenozoïcum, waarin wij leven."),
    dict(type="meerkeuze",
         vraag="Waarop zijn de grenzen in de geologische tijdschaal vooral gebaseerd?",
         opties=["op grote omslagen in het leven op aarde",
                 "op even lange stukken van honderd miljoen jaar",
                 "op het aantal lagen dat bewaard is gebleven",
                 "op de dikte van de aardkorst in die tijd"],
         antwoord=0,
         uitleg="Massa-extincties en de opkomst van nieuwe groepen vormen de natuurlijke scheidslijnen. Daarom zijn de tijdvakken ook niet even lang."),
    dict(type="meerkeuze",
         vraag="Met welke gebeurtenis valt de grens tussen het Mesozoïcum en het Cenozoïcum samen?",
         opties=["het uitsterven van de dinosaurussen",
                 "het ontstaan van het supercontinent Pangea",
                 "de vorming van de eerste steenkoollagen",
                 "het begin van de laatste grote ijstijd"],
         antwoord=0,
         uitleg="Ongeveer 66 miljoen jaar geleden stierf driekwart van alle soorten uit, de grote dinosaurussen incluis. Dat maakt die grens goed herkenbaar in de lagen."),
    dict(type="waarofniet",
         vraag="Bij een massa-extinctie verdwijnen in korte tijd heel veel soorten tegelijk.",
         antwoord=True,
         uitleg="Dat gebeurde minstens vijf keer in de geschiedenis van de aarde. De zwaarste was aan het einde van het Perm, de bekendste aan het einde van het Krijt."),
    dict(type="invultekst",
         vraag="Hoe heet de plooiing die de Ardennen vormde?",
         antwoord=["Hercynische", "Hercynische plooiing", "Variscische"],
         uitleg="De Hercynische of Variscische plooiing speelde in het Carboon, ruim 300 miljoen jaar geleden. Erosie heeft het gebergte sindsdien tot een plateau afgesleten."),
    dict(type="meerkeuze",
         vraag="Welke plooiing vormde de Alpen en de Himalaya?",
         opties=["de Alpiene plooiing", "de Hercynische plooiing",
                 "de Caledonische plooiing", "de Variscische plooiing"],
         antwoord=0,
         uitleg="De Alpiene plooiing is de jongste en loopt nog door. Daarom zijn de Alpen hoog en steil, terwijl oudere gebergten afgevlakt zijn."),
    dict(type="meerkeuze",
         vraag="Welke gebergtevormingen noemt de vakfiche?",
         opties=["de Caledonische", "de Hercynische",
                 "de Alpiene", "de Pangeïsche"],
         antwoord=[0, 1, 2],
         uitleg="De fiche vraagt de Caledonische, de Hercynische en de Alpiene plooiing op de tijdschaal te situeren en aan de platentektoniek te koppelen."),
    dict(type="meerkeuze",
         vraag="Waarom zijn oude gebergten lager dan jonge?",
         opties=["de erosie heeft er veel langer op gewerkt",
                 "de opstuwing is er al lang gestopt",
                 "verwering heeft de toppen afgerond",
                 "ze zijn nooit even hoog opgestuwd geweest"],
         antwoord=[0, 1, 2],
         uitleg="Zodra de opstuwing stopt, breken verwering en erosie het gebergte af. De Caledonische en Hercynische gebergten waren ooit even hoog als de Alpen nu."),
]
