# -*- coding: utf-8 -*-
"""Klimaatverandering doorheen de geologische tijd.

Uit de vakfiche aardrijkskunde van de 3de graad doorstroomfinaliteit (2027),
onderdeel Klimaatverandering, rubriek Klimaatverandering vanuit geologisch
perspectief. Dat onderdeel weegt samen met de huidige klimaatverandering
15 % van het examen.

Deel 1 is de temperatuurcurve doorheen de geologische tijd: ijstijden en
warme perioden, en hoe we die uit het verleden kunnen aflezen.
Deel 2 zijn de natuurlijke oorzaken: de Milanković-variabelen met
excentriciteit, obliquiteit en precessie, aërosolen, vulkaanuitbarstingen, de
spreiding van de landmassa's en de invloed van het supercontinent Pangea.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat leert een temperatuurcurve doorheen de geologische tijd ons?",
         opties=["het klimaat is altijd al veranderd",
                 "het klimaat was vroeger altijd stabiel",
                 "de aarde koelt gestaag af sinds haar ontstaan",
                 "de temperatuur hangt enkel van de mens af"],
         antwoord=0,
         uitleg="De curve toont lange warme perioden en koude ijstijden die elkaar afwisselen. Dat de mens nu de oorzaak is van de huidige opwarming, maakt dat niet ongedaan."),
    dict(type="meerkeuze",
         vraag="Hoe weten we iets over het klimaat van miljoenen jaren geleden?",
         opties=["uit fossielen, ijskernen en sedimentlagen",
                 "uit oude weerkaarten en metingen",
                 "uit het dagboek van reizigers",
                 "uit de kleur van het huidige zeewater"],
         antwoord=0,
         uitleg="Fossielen zeggen welk leven er kon bestaan, ijskernen bevatten luchtbelletjes van toen, en in sedimentlagen zitten pollen en isotopen die de temperatuur verraden."),
    dict(type="invultekst",
         vraag="Waaruit halen wetenschappers luchtbelletjes van honderdduizenden jaren oud? Eén woord.",
         antwoord=["ijskernen", "ijskern", "uit ijskernen"],
         uitleg="In een ijskap valt elk jaar een laagje sneeuw. In het ijs van Antarctica zitten luchtbelletjes van meer dan 800 000 jaar oud, met de toenmalige CO2 erin."),
    dict(type="meerkeuze",
         vraag="Welke bronnen gebruiken we om vroegere klimaten te reconstrueren?",
         opties=["ijskernen uit de poolkappen",
                 "jaarringen van bomen",
                 "pollen in veen- en meerbodems",
                 "satellietbeelden uit de ruimte"],
         antwoord=[0, 1, 2],
         uitleg="IJskernen, jaarringen, pollen, koralen en isotopen in sedimenten reiken ver terug. Satellietbeelden bestaan pas sinds de jaren zestig."),
    dict(type="waarofniet",
         vraag="De aarde heeft periodes gekend waarin er aan de polen geen ijs lag.",
         antwoord=True,
         uitleg="In het Krijt was het zo warm dat er geen poolkappen waren en de zeespiegel veel hoger stond. Krokodilachtige dieren leefden toen tot in het poolgebied."),
    dict(type="meerkeuze",
         vraag="Wat is een glaciaal?",
         opties=["een koude periode binnen een ijstijdvak",
                 "een warme periode tussen twee ijstijden",
                 "een gletsjer die snel vooruitschuift",
                 "het smelten van een hele ijskap"],
         antwoord=0,
         uitleg="Glacialen zijn de koude fasen, interglacialen de warme. In het pleistoceen wisselden ze elkaar ongeveer elke honderdduizend jaar af."),
    dict(type="invultekst",
         vraag="Hoe heet het warme tijdvak waarin wij nu leven? Eén woord.",
         antwoord=["holoceen", "het holoceen"],
         uitleg="Het holoceen begon ongeveer 11 700 jaar geleden, na de laatste ijstijd. Het is dus een interglaciaal."),
    dict(type="meerkeuze",
         vraag="Hoeveel lager stond de zeespiegel tijdens de laatste ijstijd ongeveer?",
         opties=["ongeveer 120 meter lager", "ongeveer 12 meter lager",
                 "ongeveer 1 200 meter lager", "ongeveer even hoog als nu"],
         antwoord=0,
         uitleg="Al dat water zat vast in ijskappen. Daardoor lag de Noordzee droog en kon je van Engeland naar het vasteland wandelen."),
    dict(type="waarofniet",
         vraag="Tijdens de laatste ijstijd lag de Noordzee grotendeels droog.",
         antwoord=True,
         uitleg="Dat gebied heet Doggersland. Er zijn daar botten van mammoeten en werktuigen van mensen uit het water opgevist."),
    dict(type="meerkeuze",
         vraag="Welk bewijs toont aan dat het ijs ooit tot in Nederland reikte?",
         opties=["zwerfkeien en stuwwallen",
                 "löss en dekzanden in Haspengouw",
                 "kalkgrotten in de Ardennen",
                 "steenkoollagen in de Kempen"],
         antwoord=0,
         uitleg="Zwerfkeien uit Scandinavië en opgeduwde ruggen zoals de Veluwe liggen er nog. Löss en dekzanden komen van de wind in het koude, kale voorland."),
    dict(type="invultekst",
         vraag="Hoeveel jaar geleden eindigde de laatste ijstijd ongeveer? Schrijf het getal in duizenden jaren.",
         antwoord=["11700", "12000", "11 700", "12 000"],
         uitleg="Ongeveer 11 700 jaar geleden. Vanaf dan spreken we van het holoceen, het warme tijdvak waarin de landbouw en de eerste steden opkwamen."),
    dict(type="meerkeuze",
         vraag="Wat is de kleine ijstijd?",
         opties=["een koelere periode van ongeveer 1300 tot 1850",
                 "de laatste grote ijstijd van het pleistoceen",
                 "een ijstijd die enkel in Antarctica plaatsvond",
                 "de koudste week van een gemiddelde winter"],
         antwoord=0,
         uitleg="Tussen de veertiende en de negentiende eeuw was het in Europa merkelijk koeler. Toen vroren de kanalen dicht en schoven de alpengletsjers vooruit."),
    dict(type="waarofniet",
         vraag="De kleine ijstijd was een wereldwijde ijstijd met ijskappen tot in Frankrijk.",
         antwoord=False,
         uitleg="Het ging om een afkoeling van ongeveer een halve graad tot een graad, vooral op het noordelijk halfrond. Van ijskappen was geen sprake."),
    dict(type="meerkeuze",
         vraag="Wat was de jonge dryas?",
         opties=["een plotse terugval naar de koude",
                 "de warmste periode van het hele holoceen",
                 "de eerste ijstijd van het pleistoceen",
                 "een lange droogte in de hele Sahara"],
         antwoord=0,
         uitleg="Rond 12 000 jaar geleden werd het in enkele decennia weer bitter koud, vermoedelijk doordat smeltwater de thermohaliene circulatie verstoorde. Daarna warmde het even snel weer op."),
    dict(type="invultekst",
         vraag="Welke plotse opwarming van 56 miljoen jaar geleden wordt met de huidige vergeleken? Schrijf de afkorting.",
         antwoord=["PETM", "petm"],
         uitleg="Het Paleoceen-Eoceen Thermisch Maximum. Toen kwam er in korte tijd veel koolstof in de atmosfeer en steeg de temperatuur met vijf graden of meer."),
    dict(type="meerkeuze",
         vraag="Welke perioden uit het verleden noemt de vakfiche om met vandaag te vergelijken?",
         opties=["het PETM", "de jonge dryas",
                 "de kleine ijstijd", "het holoceen optimum"],
         antwoord=[0, 1, 2],
         uitleg="De fiche vraagt uitdrukkelijk de vergelijking met het PETM, de jonge dryas en de kleine ijstijd."),
    dict(type="waarofniet",
         vraag="Een klimaatverandering in het geologische verleden ging doorgaans veel sneller dan de huidige.",
         antwoord=False,
         uitleg="Het was net omgekeerd. Natuurlijke veranderingen namen duizenden tot miljoenen jaren, terwijl de huidige opwarming zich over een eeuw afspeelt."),
    dict(type="meerkeuze",
         vraag="Waarom is de snelheid van een klimaatverandering zo belangrijk?",
         opties=["soorten kunnen zich niet snel genoeg aanpassen",
                 "de temperatuur stijgt dan ook veel hoger",
                 "de zeespiegel daalt dan in plaats van te stijgen",
                 "de aarde kan zich dan sneller herstellen"],
         antwoord=0,
         uitleg="Bij een trage verandering kunnen soorten mee verschuiven of evolueren. Gaat het snel, dan lukt dat niet en volgt uitsterven."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over het klimaat in het verleden zijn juist?",
         opties=["het klimaat veranderde ook zonder de mens",
                 "er waren periodes zonder poolijs",
                 "er waren periodes met een veel lagere zeespiegel",
                 "de temperatuur was tot nu altijd stabiel"],
         antwoord=[0, 1, 2],
         uitleg="Het klimaat schommelde altijd, met warme periodes zonder ijs en koude met een veel lagere zeespiegel. Stabiel was het nooit."),
    dict(type="meerkeuze",
         vraag="Hoe lezen we de temperatuur van het verleden uit een ijskern af?",
         opties=["uit de verhouding van zuurstofisotopen",
                 "uit de dikte van elk jaarlaagje ijs",
                 "uit de kleur van het ijs op die diepte",
                 "uit het aantal gasbellen per laagje"],
         antwoord=0,
         uitleg="Zware en lichte zuurstofatomen verdampen niet even makkelijk. Hun verhouding in het ijs is daardoor een thermometer voor het jaar waarin die sneeuw viel."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat zijn de Milanković-variabelen?",
         opties=["schommelingen in de baan en de as",
                 "drie soorten broeikasgassen in de atmosfeer",
                 "drie modellen van het IPCC voor de toekomst",
                 "drie meetmethodes voor oude temperaturen"],
         antwoord=0,
         uitleg="Excentriciteit, obliquiteit en precessie veranderen hoeveel zonlicht waar en wanneer op aarde valt. Samen verklaren ze het ritme van de ijstijden."),
    dict(type="meerkeuze",
         vraag="Welke variabelen horen bij de cycli van Milanković?",
         opties=["de excentriciteit van de baan",
                 "de obliquiteit van de aardas",
                 "de precessie van de aardas",
                 "de dikte van de ozonlaag"],
         antwoord=[0, 1, 2],
         uitleg="De fiche noemt excentriciteit, obliquiteit en precessie. De ozonlaag staat daar niet bij."),
    dict(type="invultekst",
         vraag="Hoe heet de maat voor hoe uitgerekt de baan van de aarde is? Eén woord.",
         antwoord=["excentriciteit", "de excentriciteit"],
         uitleg="De excentriciteit schommelt over ongeveer honderdduizend jaar. Een meer uitgerekte baan vergroot het verschil tussen de seizoenen."),
    dict(type="meerkeuze",
         vraag="Wat verandert er bij de obliquiteit?",
         opties=["de hoek waaronder de aardas staat",
                 "de vorm van de baan rond de zon",
                 "de richting waarin de aardas wijst",
                 "de afstand van de maan tot de aarde"],
         antwoord=0,
         uitleg="De helling van de as schommelt tussen ongeveer 22 en 24,5 graden, over ongeveer 41 000 jaar. Een rechtere as geeft mildere seizoenen."),
    dict(type="waarofniet",
         vraag="Bij precessie verandert de richting waarin de aardas wijst, zoals bij een tollende tol.",
         antwoord=True,
         uitleg="Die beweging duurt ongeveer 26 000 jaar. Daardoor zal de poolster op termijn een andere ster zijn, en verschuiven de seizoenen in de baan."),
    dict(type="meerkeuze",
         vraag="Waarom veroorzaken de Milanković-cycli ijstijden?",
         opties=["de zomerzon op hoge breedten wordt zwakker",
                 "de aarde ontvangt in totaal veel minder energie",
                 "de zon zelf straalt dan minder sterk",
                 "de zeestromen keren dan van richting om"],
         antwoord=0,
         uitleg="Als de zomers op het noordelijk halfrond koeler worden, smelt de sneeuw van de winter niet volledig weg. Die blijft liggen, weerkaatst meer licht en zo groeit een ijskap aan."),
    dict(type="invultekst",
         vraag="Hoeveel jaar duurt de cyclus van de excentriciteit ongeveer? Schrijf het getal in duizenden.",
         antwoord=["100000", "100 000", "100.000"],
         uitleg="Ongeveer honderdduizend jaar, en net dat ritme vind je terug in de opeenvolging van glacialen en interglacialen in de ijskernen."),
    dict(type="meerkeuze",
         vraag="Wat is een aërosol?",
         opties=["een piepklein deeltje dat in de lucht zweeft",
                 "een gas dat warmte in de atmosfeer houdt",
                 "een laag ozon hoog in de stratosfeer",
                 "een stroom lucht hoog boven de polen"],
         antwoord=0,
         uitleg="Aërosolen zijn zwevende deeltjes, zoals stof, zeezout, roet en zwavelzuurdruppeltjes. Veel ervan weerkaatsen zonlicht en koelen dus af."),
    dict(type="meerkeuze",
         vraag="Welk effect heeft een zware vulkaanuitbarsting op het klimaat?",
         opties=["ze koelt de aarde een jaar of langer af",
                 "ze warmt de aarde tientallen jaren op",
                 "ze verandert niets aan het klimaat",
                 "ze verdikt de ozonlaag boven de polen"],
         antwoord=0,
         uitleg="Zwaveldeeltjes die in de stratosfeer terechtkomen, weerkaatsen zonlicht. Na de Pinatubo in 1991 lag de wereldtemperatuur ongeveer een half graadje lager."),
    dict(type="waarofniet",
         vraag="Een zware vulkaanuitbarsting warmt de aarde in de jaren erna op.",
         antwoord=False,
         uitleg="In de eerste jaren koelt ze juist af, door de zwaveldeeltjes die zonlicht weerkaatsen. Over miljoenen jaren heeft vulkanische CO2 het klimaat wel warmer gehouden."),
    dict(type="meerkeuze",
         vraag="Welke natuurlijke oorzaken van klimaatverandering noemt de vakfiche?",
         opties=["de Milanković-variabelen", "aërosolen en vulkanisme",
                 "de spreiding van de landmassa's", "het verbranden van steenkool"],
         antwoord=[0, 1, 2],
         uitleg="De fiche noemt de Milanković-variabelen, aërosolen, vulkaanuitbarstingen, de spreiding van de landmassa's en de invloed van Pangea. Steenkool verbranden is een menselijke oorzaak."),
    dict(type="meerkeuze",
         vraag="Hoe beïnvloedt de ligging van de continenten het klimaat?",
         opties=["ze bepaalt de banen van de zeestromen",
                 "ze verandert de helling van de aardas",
                 "ze bepaalt de hoeveelheid zonlicht op aarde",
                 "ze verandert de samenstelling van de kern"],
         antwoord=0,
         uitleg="Liggen de continenten zo dat het water vrij rond kan stromen, dan verdeelt dat de warmte anders dan wanneer ze een oceaan afsluiten. De opening van de Drake Passage koelde Antarctica sterk af."),
    dict(type="waarofniet",
         vraag="Een continent pal op een pool maakt het makkelijker om een ijskap te vormen.",
         antwoord=True,
         uitleg="Op land kan sneeuw zich jaar na jaar opstapelen, op open zee niet. Dat Antarctica op de zuidpool ligt, is een van de redenen voor haar dikke ijskap."),
    dict(type="meerkeuze",
         vraag="Welk klimaat hoorde bij het supercontinent Pangea?",
         opties=["een extreem continentaal klimaat in het binnenland",
                 "een vochtig zeeklimaat over het hele continent",
                 "een poolklimaat van kust tot kust",
                 "een klimaat zonder enig seizoenverschil"],
         antwoord=0,
         uitleg="Het binnenland van Pangea lag duizenden kilometer van elke kust. Daar was het bijzonder droog, met hete zomers en koude winters: grote woestijnen."),
    dict(type="invultekst",
         vraag="Hoe heet het supercontinent dat het klimaat van die tijd zo extreem maakte?",
         antwoord=["Pangea", "Pangaea"],
         uitleg="Pangea bracht alle landmassa's samen, en dat gaf een enorm droog binnenland en een gewijzigde zeestroming rond het geheel."),
    dict(type="meerkeuze",
         vraag="Wat is een terugkoppeling in het klimaatsysteem?",
         opties=["een gevolg dat de oorzaak versterkt of afremt",
                 "een meting die een vorige meting bevestigt",
                 "een model dat de toekomst voorspelt",
                 "een cyclus van precies honderd jaar"],
         antwoord=0,
         uitleg="Smelt ijs door de opwarming, dan komt er donker water bloot dat meer licht opslorpt, en dan warmt het nog sneller op. Dat is een versterkende terugkoppeling."),
    dict(type="waarofniet",
         vraag="Het smelten van zee-ijs werkt als een afremmende terugkoppeling op de opwarming.",
         antwoord=False,
         uitleg="Het werkt juist versterkend. Wit ijs weerkaatst veel licht, donker water slorpt het op, dus versnelt de opwarming als het ijs verdwijnt."),
    dict(type="meerkeuze",
         vraag="Waarom is CO2 in het geologische verleden zo belangrijk voor het klimaat?",
         opties=["het houdt warmtestraling in de atmosfeer",
                 "het weerkaatst het zonlicht naar de ruimte",
                 "het breekt de ozonlaag in de stratosfeer af",
                 "het doet de aardas sneller schommelen"],
         antwoord=0,
         uitleg="Koolstofdioxide laat zonlicht door maar houdt de warmtestraling van de aarde tegen. Perioden met veel CO2 in de lucht waren dan ook warme perioden."),
    dict(type="meerkeuze",
         vraag="Welke processen haalden in het verleden CO2 uit de atmosfeer?",
         opties=["de verwering van gesteente",
                 "het begraven van plantenresten als steenkool",
                 "het vastleggen van kalk door zeeorganismen",
                 "het uitbarsten van vulkanen"],
         antwoord=[0, 1, 2],
         uitleg="Verwering, begraven koolstof en kalkvorming halen koolstof uit de lucht. Vulkanen brengen er juist bij."),
    dict(type="meerkeuze",
         vraag="Hoe helpt kennis van het klimaat uit het verleden bij de huidige klimaatverandering?",
         opties=["ze laat zien hoe het systeem op CO2 reageert",
                 "ze voorspelt het weer van volgende maand",
                 "ze bewijst dat de mens er niets mee te maken heeft",
                 "ze geeft de zeespiegel van vandaag precies weer"],
         antwoord=0,
         uitleg="Door vroegere veranderingen te meten, weten we hoe gevoelig het klimaat is voor koolstof en hoe lang herstel duurt. Dat maakt de modellen voor de toekomst betrouwbaarder."),
]
