# -*- coding: utf-8 -*-
"""De huidige klimaatverandering.

Uit de vakfiche aardrijkskunde van de 3de graad doorstroomfinaliteit (2027),
onderdeel Klimaatverandering, rubriek De huidige klimaatverandering.

Deel 1 zijn de broeikasgassen, het versterkte broeikaseffect, de oorzaken van
de gewijzigde concentratie en de gevolgen die we al meten.
Deel 2 zijn de terugkoppelingen, de scenario's van het IPCC en wat we eraan
doen: adaptatie, mitigatie en klimaatneutraal worden.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat doet een broeikasgas in de atmosfeer?",
         opties=["het houdt warmtestraling tegen",
                 "het weerkaatst het zonlicht naar de ruimte",
                 "het maakt de atmosfeer zwaarder dan ervoor",
                 "het breekt de ozonlaag boven de polen af"],
         antwoord=0,
         uitleg="Zonlicht gaat er makkelijk door, maar de warmtestraling die de aarde uitzendt wordt opgeslorpt en weer naar alle kanten uitgezonden. Zo blijft een deel van de warmte hangen."),
    dict(type="meerkeuze",
         vraag="Welke gassen zijn broeikasgassen?",
         opties=["koolstofdioxide", "methaan", "waterdamp", "stikstofgas"],
         antwoord=[0, 1, 2],
         uitleg="CO2, methaan, waterdamp, lachgas en ozon houden warmte tegen. Stikstofgas vult drie vierde van de lucht maar doet dat niet."),
    dict(type="waarofniet",
         vraag="Zonder enig broeikaseffect zou het op aarde gemiddeld ver onder nul zijn.",
         antwoord=True,
         uitleg="Het natuurlijke broeikaseffect brengt ons van ongeveer achttien graden onder nul naar een gemiddelde van vijftien graden. Het probleem is niet het effect zelf maar dat wij het versterken."),
    dict(type="invultekst",
         vraag="Welk broeikasgas komt vooral vrij bij het verbranden van steenkool, olie en gas? Schrijf de formule.",
         antwoord=["CO2", "co2", "koolstofdioxide"],
         uitleg="Koolstofdioxide. Het is niet het sterkste broeikasgas per molecule, maar we stoten er zoveel van uit dat het de grootste bijdrage levert."),
    dict(type="meerkeuze",
         vraag="Waarom heet het versterkte broeikaseffect zo?",
         opties=["de mens verhoogt een bestaand effect",
                 "het effect is pas sinds 1850 ontstaan",
                 "het werkt enkel boven de industriegebieden",
                 "het is in de winter sterker dan in de zomer"],
         antwoord=0,
         uitleg="Het broeikaseffect bestond al voor er mensen waren. Door extra gassen uit te stoten versterken wij het, en dus stijgt de temperatuur."),
    dict(type="meerkeuze",
         vraag="Welke menselijke activiteiten verhogen de concentratie broeikasgassen?",
         opties=["fossiele brandstoffen verbranden",
                 "bossen kappen voor landbouw",
                 "veeteelt en rijstvelden",
                 "windmolens bouwen op zee"],
         antwoord=[0, 1, 2],
         uitleg="Verbranden brengt CO2 in de lucht, bossen kappen haalt een opslagplaats weg, en vee en rijstvelden geven methaan. Windmolens doen net het omgekeerde."),
    dict(type="meerkeuze",
         vraag="Waarom geeft veeteelt zoveel methaan?",
         opties=["koeien gisten hun voedsel in de maag",
                 "koeien ademen heel veel lucht uit",
                 "koeien warmen de bodem onder zich op",
                 "koeien drinken enorme hoeveelheden water"],
         antwoord=0,
         uitleg="In de pens van een rund breken bacteriën het gras af zonder zuurstof, en daarbij komt methaan vrij. Rijstvelden onder water doen iets gelijkaardigs in de bodem."),
    dict(type="invultekst",
         vraag="Hoeveel is de wereldtemperatuur ongeveer gestegen sinds het begin van de industrie? Schrijf het getal in graden.",
         antwoord=["1,2", "1.2", "1,3", "1.3"],
         uitleg="Iets meer dan een graad, ongeveer 1,2 tot 1,3 graden ten opzichte van de periode 1850 tot 1900. Dat klinkt klein, maar het is een gemiddelde over de hele planeet."),
    dict(type="waarofniet",
         vraag="De opwarming verloopt op elke plek van de aarde ongeveer even snel.",
         antwoord=False,
         uitleg="Het Noordpoolgebied warmt drie tot vier keer sneller op dan het wereldgemiddelde, en land warmt sneller op dan zee."),
    dict(type="meerkeuze",
         vraag="Waarom stijgt de zeespiegel door de opwarming?",
         opties=["landijs smelt en water zet uit",
                 "er valt meer regen boven de oceanen",
                 "de oceaanbodem komt langzaam omhoog",
                 "de rivieren voeren veel meer water aan"],
         antwoord=0,
         uitleg="Twee oorzaken samen: het ijs van Groenland, Antarctica en de gletsjers smelt, en warmer water neemt meer plaats in. Smeltend zee-ijs doet de zeespiegel niet stijgen, want dat dreef al."),
    dict(type="meerkeuze",
         vraag="Welke gevolgen van de huidige klimaatverandering meten we nu al?",
         opties=["een stijgende zeespiegel",
                 "gletsjers die terugtrekken",
                 "meer en langere hittegolven",
                 "een snellere draaiing van de aarde"],
         antwoord=[0, 1, 2],
         uitleg="De zeespiegel stijgt, gletsjers krimpen bijna overal, en hittegolven worden talrijker en heviger. De draaiing van de aarde heeft hier niets mee te maken."),
    dict(type="meerkeuze",
         vraag="Wat betekent de verzuring van de oceaan?",
         opties=["de zee neemt CO2 op en wordt zuurder",
                 "zuurregen valt rechtstreeks in de zee",
                 "het zoutgehalte van de zee neemt toe",
                 "de zee warmt sneller op dan het land"],
         antwoord=0,
         uitleg="Ongeveer een kwart van onze CO2 lost op in zeewater en vormt daar koolzuur. Daardoor daalt de zuurtegraad en krijgen koralen en schelpdieren het moeilijk om kalk te maken."),
    dict(type="waarofniet",
         vraag="Een warmere atmosfeer kan meer waterdamp bevatten, waardoor buien heviger kunnen uitvallen.",
         antwoord=True,
         uitleg="Per graad opwarming kan de lucht ongeveer zeven procent meer waterdamp dragen. Daardoor valt er bij een bui meer in één keer, met meer wateroverlast."),
    dict(type="meerkeuze",
         vraag="Waarom zegt een strenge winter niets over de opwarming?",
         opties=["één seizoen is nog geen klimaat",
                 "de winter warmt helemaal niet op",
                 "de opwarming geldt enkel voor de zomer",
                 "de metingen van de winter zijn onzeker"],
         antwoord=0,
         uitleg="Het klimaat is het gemiddelde over dertig jaar. Binnen die trend blijft er veel schommeling, dus een koude winter past er gewoon in."),
    dict(type="invultekst",
         vraag="Welke organisatie van de Verenigde Naties bundelt het klimaatonderzoek? Schrijf de afkorting.",
         antwoord=["IPCC", "ipcc"],
         uitleg="Het IPCC. Het doet zelf geen onderzoek maar leest alle studies samen en schrijft daar rapporten over, die de landen gebruiken om beleid te maken."),
    dict(type="meerkeuze",
         vraag="Welke uitspraak over de huidige klimaatverandering klopt?",
         opties=["de mens is de belangrijkste oorzaak",
                 "de zon straalt duidelijk sterker dan vroeger",
                 "de aardas is de afgelopen eeuw sterk gekanteld",
                 "vulkanen stoten meer CO2 uit dan de mens"],
         antwoord=0,
         uitleg="De metingen zijn duidelijk: de zon is niet sterker geworden, de Milanković-cycli werken op duizenden jaren, en vulkanen stoten per jaar een fractie uit van wat wij doen."),
    dict(type="waarofniet",
         vraag="De Milanković-cycli verklaren de opwarming van de laatste honderd jaar.",
         antwoord=False,
         uitleg="Die cycli werken op tienduizenden jaren en zouden nu eerder lichte afkoeling geven. De snelle opwarming van de laatste eeuw past er niet in."),
    dict(type="meerkeuze",
         vraag="Hoe weten we dat de extra CO2 van fossiele brandstoffen komt?",
         opties=["aan de verhouding van de koolstofisotopen",
                 "aan de kleur van de lucht boven de stad",
                 "aan de hoeveelheid zuurstof in het zeewater",
                 "aan de temperatuur van de bovenste bodemlaag"],
         antwoord=0,
         uitleg="Koolstof uit steenkool en olie heeft een eigen isotopenvingerafdruk: ze bevat bijna geen koolstof-14 en weinig koolstof-13. Net die mengeling zien we in de lucht toenemen."),
    dict(type="meerkeuze",
         vraag="Welk gevolg van de opwarming treft vooral de landbouw?",
         opties=["langere droogtes in de zomer",
                 "een hogere zeespiegel aan de kust",
                 "het smelten van het poolijs",
                 "de verzuring van de oceaan"],
         antwoord=0,
         uitleg="Droogte en hitte op het verkeerde moment doen de opbrengst dalen. De andere gevolgen zijn echt, maar raken de landbouw veel minder rechtstreeks."),
    dict(type="meerkeuze",
         vraag="Wat gebeurt er met de biodiversiteit door een snelle klimaatverandering?",
         opties=["soorten verschuiven of sterven uit",
                 "alle soorten passen zich snel aan",
                 "er komen overal meer soorten bij",
                 "de biodiversiteit blijft gelijk"],
         antwoord=0,
         uitleg="Wie kan, schuift op naar koelere streken of hoger de berg op. Wie niet snel genoeg kan of nergens heen kan, zoals koraal of een alpenplant, verdwijnt."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is een positieve terugkoppeling in het klimaatsysteem?",
         opties=["een gevolg dat de opwarming versterkt",
                 "een gevolg dat goed uitpakt voor de mens",
                 "een gevolg dat de opwarming afremt",
                 "een meting die een eerdere meting bevestigt"],
         antwoord=0,
         uitleg="Positief betekent hier versterkend, niet goed. Smeltend ijs legt donker water bloot dat meer zonlicht opslorpt, en dus warmt het nog sneller op."),
    dict(type="meerkeuze",
         vraag="Welke processen werken als een positieve, dus versterkende terugkoppeling?",
         opties=["het smelten van zee-ijs",
                 "het ontdooien van permafrost",
                 "meer waterdamp in een warmere lucht",
                 "meer plantengroei die CO2 opneemt"],
         antwoord=[0, 1, 2],
         uitleg="Smeltend ijs, ontdooiende permafrost die methaan vrijgeeft en extra waterdamp versterken de opwarming. Extra plantengroei neemt juist CO2 weg en remt dus af."),
    dict(type="invultekst",
         vraag="Hoe heet de altijd bevroren bodem die bij het ontdooien methaan vrijgeeft? Eén woord.",
         antwoord=["permafrost", "de permafrost"],
         uitleg="De permafrost in Siberië, Canada en Alaska. Er zit enorm veel oude plantenresten in, en die beginnen bij het ontdooien te rotten."),
    dict(type="meerkeuze",
         vraag="Waarom is een versterkende terugkoppeling zo zorgwekkend?",
         opties=["de opwarming gaat zichzelf voortzetten",
                 "ze maakt de metingen onbetrouwbaar",
                 "ze doet de zeespiegel plots zakken",
                 "ze gaat enkel op voor het poolgebied"],
         antwoord=0,
         uitleg="Zodra zo'n lus op gang komt, blijft hij doorlopen, ook als wij zouden stoppen met uitstoten. Daarom spreken wetenschappers over kantelpunten die je beter niet overschrijdt."),
    dict(type="waarofniet",
         vraag="Een negatieve terugkoppeling remt de opwarming af.",
         antwoord=True,
         uitleg="Negatief betekent hier afremmend. Een warmere aarde straalt bijvoorbeeld meer warmte naar de ruimte uit, en dat werkt tegen de opwarming in."),
    dict(type="meerkeuze",
         vraag="Wat is een IPCC-scenario?",
         opties=["een mogelijk verloop bij een bepaalde uitstoot",
                 "een voorspelling van het weer volgend jaar",
                 "een afspraak die alle landen ondertekenen",
                 "een meting van de uitstoot van vorig jaar"],
         antwoord=0,
         uitleg="Een scenario rekent uit wat er gebeurt als we veel of weinig blijven uitstoten. Het is geen voorspelling maar een doorrekening van een keuze."),
    dict(type="waarofniet",
         vraag="Hoe warm het tegen 2100 wordt, hangt vooral af van hoeveel we nog uitstoten.",
         antwoord=True,
         uitleg="Daarom rekent het IPCC meerdere scenario's door. In het laagste blijft de opwarming rond anderhalve graad, in het hoogste loopt ze op tot vier graden of meer."),
    dict(type="invultekst",
         vraag="Op welke opwarming in graden mikt het akkoord van Parijs als bovengrens? Schrijf het getal.",
         antwoord=["1,5", "1.5"],
         uitleg="Het akkoord wil de opwarming ruim onder twee graden houden en streeft naar anderhalve graad. We zitten nu al rond 1,2 graden."),
    dict(type="meerkeuze",
         vraag="Wat is mitigatie?",
         opties=["de oorzaak aanpakken en minder uitstoten",
                 "je aanpassen aan een warmer klimaat",
                 "de gevolgen in kaart brengen met modellen",
                 "de uitstoot van vorige jaren berekenen"],
         antwoord=0,
         uitleg="Mitigatie bestrijdt de oorzaak: minder broeikasgassen uitstoten of ze weer vastleggen. Je aanpassen aan wat er toch gebeurt, heet adaptatie."),
    dict(type="meerkeuze",
         vraag="Wat is adaptatie?",
         opties=["je aanpassen aan de gevolgen",
                 "de uitstoot van broeikasgassen verlagen",
                 "overschakelen op zon en wind",
                 "bossen aanplanten om CO2 vast te leggen"],
         antwoord=0,
         uitleg="Adaptatie is leven met wat er toch komt: dijken verhogen, schaduw in de stad, gewassen die droogte verdragen. De drie andere zijn mitigatie."),
    dict(type="meerkeuze",
         vraag="Welke maatregelen zijn voorbeelden van adaptatie?",
         opties=["dijken en kustbescherming verhogen",
                 "bomen planten tegen hitte in de stad",
                 "regenwater opvangen tegen droogte",
                 "windmolens bouwen op zee en op het land"],
         antwoord=[0, 1, 2],
         uitleg="Dijken, schaduw en wateropvang maken ons weerbaar tegen de gevolgen. Windmolens verlagen de uitstoot en horen dus bij mitigatie."),
    dict(type="meerkeuze",
         vraag="Welke maatregelen zijn voorbeelden van mitigatie?",
         opties=["minder vlees eten",
                 "overschakelen op zon en wind",
                 "woningen beter isoleren",
                 "airco plaatsen in elke klas"],
         antwoord=[0, 1, 2],
         uitleg="Minder vlees, hernieuwbare energie en isolatie verlagen de uitstoot. Airco maakt het binnen koeler maar verbruikt energie en is dus adaptatie."),
    dict(type="invultekst",
         vraag="Hoe noem je het wanneer een land evenveel broeikasgas vastlegt als het uitstoot? Twee woorden.",
         antwoord=["klimaatneutraal", "netto nul", "klimaatneutraliteit"],
         uitleg="Klimaatneutraal, ook netto nul genoemd. Je stoot dan nog uit, maar legt evenveel vast in bossen, bodem of opslag."),
    dict(type="waarofniet",
         vraag="Klimaatneutraal betekent dat er helemaal geen broeikasgas meer wordt uitgestoten.",
         antwoord=False,
         uitleg="Het betekent dat uitstoot en vastlegging in evenwicht zijn. Een deel van de uitstoot blijft, maar wordt elders gecompenseerd."),
    dict(type="meerkeuze",
         vraag="Waarom blijft de temperatuur nog even stijgen als we vandaag stoppen met uitstoten?",
         opties=["de oceaan reageert heel traag op warmte",
                 "de CO2 van vandaag valt pas later uiteen",
                 "het zonlicht neemt de komende jaren toe",
                 "de atmosfeer houdt de warmte eeuwig vast"],
         antwoord=0,
         uitleg="De oceaan heeft enorm veel warmte opgeslorpt en komt maar langzaam in evenwicht. Daarbovenop blijft CO2 eeuwen in de lucht hangen."),
    dict(type="meerkeuze",
         vraag="Waarom is klimaatverandering een kwestie van rechtvaardigheid?",
         opties=["wie het minst uitstoot wordt het hardst getroffen",
                 "elk land stoot precies hetzelfde uit",
                 "de rijkste landen worden het eerst getroffen",
                 "enkel de polen hebben er last van"],
         antwoord=0,
         uitleg="Landen in de Sahel, op lage eilanden en in Zuid-Azië hebben het minst bijgedragen en voelen de gevolgen het hardst. Zij hebben ook het minst geld om zich aan te passen."),
    dict(type="waarofniet",
         vraag="Adaptatie alleen volstaat als antwoord op de klimaatverandering.",
         antwoord=False,
         uitleg="Je kan je tot een zekere grens aanpassen, maar bij vier graden opwarming lukt dat niet meer. Daarom horen adaptatie en mitigatie samen."),
    dict(type="meerkeuze",
         vraag="Hoe helpt een bos tegen de klimaatverandering?",
         opties=["het legt koolstof vast in hout en bodem",
                 "het weerkaatst het zonlicht naar de ruimte",
                 "het haalt methaan rechtstreeks uit de lucht",
                 "het verlaagt de zeespiegel aan de kust"],
         antwoord=0,
         uitleg="Groeiende bomen halen CO2 uit de lucht en slaan de koolstof op in hout en bodem. Daarom is bossen kappen dubbel slecht: de opslag verdwijnt en de koolstof komt vrij."),
    dict(type="meerkeuze",
         vraag="Waarom is de huidige klimaatverandering anders dan die van het geologische verleden?",
         opties=["ze gaat veel sneller en komt van de mens",
                 "de temperatuur stijgt hoger dan ooit tevoren",
                 "er is nog nooit zoveel CO2 in de lucht geweest",
                 "er smelt voor het eerst ijs op aarde"],
         antwoord=0,
         uitleg="De aarde kende al warmere tijden met meer CO2, en ijs smolt al vaker. Nieuw zijn de snelheid, in een eeuw in plaats van duizenden jaren, en de oorzaak."),
    dict(type="meerkeuze",
         vraag="Wat kan jij zelf doen dat echt gewicht heeft?",
         opties=["minder met het vliegtuig en de wagen reizen",
                 "de lichten een uurtje per dag uitdoen",
                 "enkel nog koud water uit de kraan nemen",
                 "de verwarming één graad hoger zetten"],
         antwoord=0,
         uitleg="Vervoer, verwarming en voeding wegen het zwaarst in de uitstoot van een gezin. Een vliegreis minder of minder vlees weegt veel meer door dan een lamp uitdoen."),
]
