# -*- coding: utf-8 -*-
"""Platentektoniek en reliëfvorming.

Uit de vakfiche aardrijkskunde van de 3de graad doorstroomfinaliteit (2027),
onderdeel De geosfeer, rubriek Plaatbewegingen.

Deel 1 is het mechanisme: Pangea en Gondwana, de aanwijzingen voor de drift
van de continenten, de subductietrekkracht (slab pull) en de rugduwkracht
(ridge push), de mantelpluim en de hotspot, en de drie soorten
plaatbewegingen: divergentie, convergentie en de transforme beweging.
Deel 2 is het reliëf dat eruit volgt: de oceanische rug, de diepzeetrog, het
continentaal plat met zijn helling, de abyssale vlakte, de plooiings-, kust-
en continentale gebergten, de rift en de slenk, en de plooien met hun
synclines en anticlines.
"""

DEEL1 = [
    dict(type="invultekst",
         vraag="Hoe heette het supercontinent dat ongeveer 250 miljoen jaar geleden alle landmassa's samenbracht?",
         antwoord=["Pangea", "Pangaea"],
         uitleg="Pangea brak daarna in twee stukken: Laurazië in het noorden en Gondwana in het zuiden."),
    dict(type="meerkeuze",
         vraag="Welke continenten maakten deel uit van Gondwana?",
         opties=["Zuid-Amerika en Afrika", "Australië en Antarctica",
                 "India en Arabië", "Europa en Noord-Amerika"],
         antwoord=[0, 1, 2],
         uitleg="Gondwana was het zuidelijke deel van Pangea: Zuid-Amerika, Afrika, Australië, Antarctica, India en Arabië. Europa en Noord-Amerika vormden Laurazië."),
    dict(type="meerkeuze",
         vraag="Welke aanwijzing pleit voor de drift van de continenten?",
         opties=["dezelfde fossielen op twee verre continenten",
                 "de gelijke diepte van alle oceanen samen",
                 "het ontbreken van vulkanen op het land",
                 "de gelijke dikte van alle aardkorst"],
         antwoord=0,
         uitleg="Dezelfde fossielen, dezelfde gebergteketens en dezelfde gletsjersporen duiken op aan weerszijden van een oceaan. Dat kan alleen als die stukken ooit aan elkaar vast zaten."),
    dict(type="waarofniet",
         vraag="De kustlijnen van Zuid-Amerika en Afrika passen als twee stukken van een puzzel in elkaar.",
         antwoord=True,
         uitleg="Dat was voor Wegener al een eerste aanwijzing. De fossielen, de gesteenten en de gebergteketens die doorlopen, maakten het sluitend."),
    dict(type="meerkeuze",
         vraag="Wat is de subductietrekkracht of slab pull?",
         opties=["de duikende plaat trekt de rest mee",
                 "de wind duwt het water tegen de plaatrand aan",
                 "het magma duwt de platen vanonder omhoog",
                 "de aardrotatie sleurt de platen naar het westen"],
         antwoord=0,
         uitleg="Oceanische korst die begint te duiken, is zwaarder dan de mantel errond. Haar eigen gewicht trekt de rest van de plaat mee: dat is de sterkste motor van de platentektoniek."),
    dict(type="meerkeuze",
         vraag="Wat is de rugduwkracht of ridge push?",
         opties=["de hoge, warme rug duwt de plaat van zich af",
                 "het zeewater duwt de plaat naar de kust",
                 "de kern duwt het magma naar de korst",
                 "de hotspot duwt een gat in de plaat"],
         antwoord=0,
         uitleg="Bij een oceanische rug staat de korst hoger en is ze warm. Terwijl ze afkoelt en zakt, glijdt de plaat van die rug weg."),
    dict(type="invultekst",
         vraag="Hoe heet het proces waarbij een plaat onder een andere wegduikt?",
         antwoord=["subductie", "de subductie"],
         uitleg="Bij subductie duikt de zwaardere oceanische korst onder de lichtere plaat. In de diepte smelt ze, en dat levert het magma voor de vulkanen erboven."),
    dict(type="meerkeuze",
         vraag="Wat gebeurt er bij divergentie van twee platen?",
         opties=["ze bewegen van elkaar weg",
                 "ze schuiven langs elkaar heen",
                 "ze botsen frontaal op elkaar",
                 "ze blijven precies op hun plaats"],
         antwoord=0,
         uitleg="Bij divergentie wijken de platen uiteen en komt er magma naar boven. Zo wordt er nieuwe oceanische korst gemaakt: dat heet spreiding."),
    dict(type="meerkeuze",
         vraag="Wat gebeurt er bij een transforme beweging?",
         opties=["twee platen schuiven langs elkaar",
                 "twee platen wijken van elkaar weg",
                 "een plaat duikt onder een andere",
                 "een plaat scheurt in twee delen"],
         antwoord=0,
         uitleg="Bij een transforme of schuifbeweging maken de platen geen nieuwe korst en verdwijnt er ook geen. Ze haken wel aan elkaar vast, en dat geeft zware aardbevingen, zoals bij de San Andreasbreuk."),
    dict(type="waarofniet",
         vraag="Bij convergentie van twee continentale platen ontstaat een plooiingsgebergte.",
         antwoord=True,
         uitleg="Geen van beide is zwaar genoeg om te duiken, dus wordt de korst opgestuwd en geplooid. Zo zijn de Himalaya en de Alpen ontstaan."),
    dict(type="meerkeuze",
         vraag="Wat is een mantelpluim?",
         opties=["een opstijgende kolom mantelgesteente",
                 "een dikke laag sediment op de oceaanbodem",
                 "een scheur dwars door de hele aardkorst",
                 "een wolk vulkanische as hoog in de lucht"],
         antwoord=0,
         uitleg="Een mantelpluim stijgt vanuit de diepe mantel op. Waar ze de korst raakt, ontstaat een hotspot met vulkanisme, ook al zit die midden op een plaat."),
    dict(type="meerkeuze",
         vraag="Waarom vormt Hawaï een rij eilanden van verschillende ouderdom?",
         opties=["de plaat schuift over een vaste hotspot",
                 "de hotspot verplaatst zich onder de plaat",
                 "elke eeuw barst er een andere vulkaan uit",
                 "de zeespiegel wisselt er voortdurend"],
         antwoord=0,
         uitleg="De hotspot blijft staan, de Pacifische plaat beweegt. Elk nieuw eiland komt erboven, drijft dan verder weg en dooft uit."),
    dict(type="invultekst",
         vraag="Hoe heet een plek midden op een plaat waar een mantelpluim vulkanisme veroorzaakt? Eén woord.",
         antwoord=["hotspot", "een hotspot", "hot spot"],
         uitleg="Hawaï en IJsland zijn de bekendste hotspots. IJsland ligt bovendien op een oceanische rug, en dat verklaart haar vele vulkanen."),
    dict(type="meerkeuze",
         vraag="Welke soorten plaatbewegingen noemt de vakfiche?",
         opties=["divergentie", "convergentie",
                 "de transforme beweging", "de rotatiebeweging"],
         antwoord=[0, 1, 2],
         uitleg="De fiche noemt divergentie, convergentie, de transforme beweging en, als verticale beweging, de isostasie."),
    dict(type="meerkeuze",
         vraag="Hoe snel bewegen de tektonische platen ongeveer?",
         opties=["een paar centimeter per jaar", "een paar meter per jaar",
                 "een paar kilometer per eeuw", "een paar millimeter per eeuw"],
         antwoord=0,
         uitleg="Twee tot tien centimeter per jaar, ongeveer zo snel als je nagels groeien. Over miljoenen jaren levert dat wel duizenden kilometer op."),
    dict(type="waarofniet",
         vraag="Nieuwe oceanische korst wordt gemaakt in een diepzeetrog.",
         antwoord=False,
         uitleg="Ze wordt gemaakt aan een oceanische rug, waar magma opstijgt en afkoelt tot basalt. In een trog verdwijnt oude korst juist naar beneden."),
    dict(type="waarofniet",
         vraag="De aarde wordt groter doordat er aan de oceanische ruggen nieuwe korst bijkomt.",
         antwoord=False,
         uitleg="Wat aan een rug bijkomt, verdwijnt elders in een trog. De oppervlakte blijft dus gelijk: het is een kringloop, geen aangroei."),
    dict(type="meerkeuze",
         vraag="Welke begrippen noemt de vakfiche bij de plaatbewegingen?",
         opties=["Pangea en Gondwana", "mantelpluim en hotspot",
                 "riftster en subductie", "isohyeet en isobaar"],
         antwoord=[0, 1, 2],
         uitleg="De fiche somt Gondwana, Pangea, mantelpluim, hotspot, riftster en subductie op. Isohyeten en isobaren horen bij het weer."),
    dict(type="meerkeuze",
         vraag="Wat is een riftster?",
         opties=["een punt waar drie riftarmen samenkomen",
                 "een ster die door de dampkring valt",
                 "een vulkaan met drie kraters naast elkaar",
                 "een breuk die precies oost-west loopt"],
         antwoord=0,
         uitleg="Waar een mantelpluim de korst optilt, scheurt ze vaak in drie armen. De Afar-driehoek in Ethiopië is zo'n riftster."),
    dict(type="meerkeuze",
         vraag="Waarom is er vulkanisme boven een subductiezone?",
         opties=["de duikende plaat smelt in de diepte",
                 "de korst wordt er dunner door de botsing",
                 "het zeewater kookt er door de wrijving",
                 "de mantelpluim ligt er altijd onder"],
         antwoord=0,
         uitleg="De duikende plaat neemt water mee. Dat verlaagt het smeltpunt van het gesteente erboven, waardoor magma opstijgt en vulkanen vormt: de Ring of Fire."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Welke reliëfvorm hoort bij een divergente plaatgrens in de oceaan?",
         opties=["een oceanische rug", "een diepzeetrog",
                 "een plooiingsgebergte", "een abyssale vlakte"],
         antwoord=0,
         uitleg="Waar platen uiteenwijken, stijgt magma op en bouwt zich een onderzeese bergketen op: de Midatlantische Rug is er een van."),
    dict(type="meerkeuze",
         vraag="Welke reliëfvorm hoort bij een subductiezone?",
         opties=["een diepzeetrog", "een oceanische rug",
                 "een abyssale vlakte", "een continentaal plat"],
         antwoord=0,
         uitleg="Waar een plaat wegduikt, ontstaat de diepste insnijding op aarde. De Marianentrog gaat bijna elf kilometer diep."),
    dict(type="invultekst",
         vraag="Hoe heet de ondiepe, vlakke zoom rond een continent, tot ongeveer 200 meter diep? Twee woorden.",
         antwoord=["continentaal plat", "het continentaal plat", "continentale plat"],
         uitleg="Het continentaal plat is eigenlijk ondergelopen continent. Daarachter duikt de continentale helling steil naar de diepzee."),
    dict(type="meerkeuze",
         vraag="Wat ligt er tussen het continentaal plat en de abyssale vlakte?",
         opties=["de continentale helling", "de lange oceanische rug",
                 "de diepe zeetrog van een subductie", "de riftster van een pluim"],
         antwoord=0,
         uitleg="De continentale helling is de steile overgang van de ondiepe rand naar de diepe oceaanbodem."),
    dict(type="waarofniet",
         vraag="De abyssale vlakte is de uitgestrekte, vlakke bodem van de diepzee.",
         antwoord=True,
         uitleg="Ze ligt op vier tot zes kilometer diepte en is bedekt met een dikke laag fijn slib. Daardoor is ze een van de vlakste landschappen op aarde."),
    dict(type="meerkeuze",
         vraag="Hoe ontstaat een slenk of een rift op het land?",
         opties=["de korst wordt uitgerekt en zakt tussen breuken",
                 "twee continenten botsen frontaal op elkaar",
                 "een rivier snijdt zich diep in de vlakte",
                 "een gletsjer schuurt een brede trog uit"],
         antwoord=0,
         uitleg="Bij rekking breekt de korst en zakt een strook tussen twee breuken naar beneden. De Oost-Afrikaanse Slenk en de Rijnslenk zijn zo gevormd."),
    dict(type="invultekst",
         vraag="Hoe heet de grote slenk die door Oost-Afrika loopt? Drie woorden.",
         antwoord=["Oost-Afrikaanse Slenk", "de Oost-Afrikaanse Slenk", "Great Rift Valley"],
         uitleg="Daar scheurt het Afrikaanse continent langzaam in twee. Over miljoenen jaren kan er een nieuwe oceaan liggen."),
    dict(type="meerkeuze",
         vraag="Hoe is de Himalaya ontstaan?",
         opties=["India botste op de Euraziatische plaat",
                 "een mantelpluim duwde de korst omhoog",
                 "een oceanische plaat dook onder India",
                 "een gletsjer stuwde het gesteente op"],
         antwoord=0,
         uitleg="India schoof vanuit Gondwana naar het noorden en ramde Azië. Omdat geen van beide continentale platen kon duiken, werd de korst opgeplooid tot het hoogste gebergte op aarde."),
    dict(type="meerkeuze",
         vraag="Welk gebergte is een kustgebergte boven een subductiezone?",
         opties=["de Andes", "de Alpen", "de Oeral", "de Ardennen"],
         antwoord=0,
         uitleg="De Nazcaplaat duikt onder Zuid-Amerika. Dat stuwt de rand op tot de Andes, met een rij vulkanen erbovenop."),
    dict(type="waarofniet",
         vraag="De Ardennen zijn een jong, hoog plooiingsgebergte met scherpe toppen.",
         antwoord=False,
         uitleg="De Ardennen zijn een oud gebergte uit de Hercynische plooiing, al meer dan 300 miljoen jaar oud. Erosie heeft ze tot een afgerond plateau gesleten."),
    dict(type="meerkeuze",
         vraag="Welke reliëfvormen noemt de vakfiche bij de gevolgen van platentektoniek?",
         opties=["diepzeetrog en oceanische rug",
                 "continentaal plat en continentale helling",
                 "plooiingsgebergte en slenk",
                 "doline en verdwijngat"],
         antwoord=[0, 1, 2],
         uitleg="De fiche noemt onder meer diepzeetrog, oceanische rug, continentaal plat en helling, abyssale vlakte, plooiings-, kust- en continentaal gebergte, slenk en rift. Dolines horen bij karst."),
    dict(type="meerkeuze",
         vraag="Wat is een anticline?",
         opties=["een plooi met de bolle kant naar boven",
                 "een plooi met de holle kant naar boven",
                 "een breuk waarlangs een blok omhoog ging",
                 "een laag die horizontaal is blijven liggen"],
         antwoord=0,
         uitleg="Een anticline is een zadel: de lagen welven op. Een syncline is een trog: de lagen buigen naar beneden door."),
    dict(type="invultekst",
         vraag="Hoe heet een plooi waarbij de lagen een trog vormen, met de holle kant naar boven?",
         antwoord=["syncline", "een syncline", "synclinaal"],
         uitleg="In een syncline liggen de jongste lagen in het midden. In een anticline zijn dat net de oudste, want de top is er weg geërodeerd."),
    dict(type="waarofniet",
         vraag="In een geplooid gebergte liggen de gesteentelagen niet meer horizontaal.",
         antwoord=True,
         uitleg="Sedimenten worden horizontaal afgezet. Staan ze schuin of op hun kant, dan weet je dat er tektonische krachten op gewerkt hebben."),
    dict(type="meerkeuze",
         vraag="Wat is een caldera?",
         opties=["een grote krater na het instorten van een vulkaan",
                 "een smalle scheur waaruit lava stroomt",
                 "een meer dat door een gletsjer is uitgeschuurd",
                 "een heuvel van opgewaaid zand bij de kust"],
         antwoord=0,
         uitleg="Loopt de magmakamer leeg bij een zware uitbarsting, dan stort het dak in. Het reusachtige ketelvormige gat dat overblijft, heet een caldera."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over de ligging van aardbevingen en vulkanen zijn juist?",
         opties=["ze liggen vooral aan de plaatranden",
                 "samen tekenen ze de plaatgrenzen uit",
                 "de Ring of Fire is de bekendste gordel",
                 "ze liggen vooral rond de evenaar"],
         antwoord=[0, 1, 2],
         uitleg="Zet je alle bevingen op een wereldkaart, dan verschijnen de plaatgrenzen. De Ring of Fire rond de Stille Oceaan is de bekendste. Met de breedtegraad heeft het niets te maken."),
    dict(type="meerkeuze",
         vraag="Waarom heeft IJsland zoveel vulkanen en geisers?",
         opties=["het ligt op een rug én op een hotspot",
                 "het ligt midden in een diepe zeetrog",
                 "het ligt op een transforme breuk",
                 "het ligt op het continentaal plat"],
         antwoord=0,
         uitleg="De Midatlantische Rug komt er boven water, en er zit bovendien een mantelpluim onder. Twee bronnen van magma op één plek."),
    dict(type="meerkeuze",
         vraag="Welke reliëfvorm vind je waar een oceanische en een continentale plaat botsen?",
         opties=["een trog met een kustgebergte erlangs",
                 "een rug met een slenk in het midden",
                 "een vlakke abyssale bodem",
                 "een breed continentaal plat"],
         antwoord=0,
         uitleg="De oceanische plaat duikt onder en vormt een diepzeetrog, en de rand van het continent wordt opgestuwd tot een kustgebergte met vulkanen."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over een dwarsprofiel van het aardoppervlak zijn juist?",
         opties=["het toont de hoogte langs een gekozen lijn",
                 "je kan er reliëfvormen op benoemen",
                 "de ligging ervan lees je van een kaart af",
                 "het toont de bevolkingsdichtheid per gemeente"],
         antwoord=[0, 1, 2],
         uitleg="Een dwarsprofiel is een zijaanzicht langs een lijn op de kaart. Je leest er de hoogteverschillen op en benoemt de vormen. Over bevolking zegt het niets."),
    dict(type="waarofniet",
         vraag="De Stille Oceaan wordt elk jaar breder, terwijl de Atlantische Oceaan krimpt.",
         antwoord=False,
         uitleg="Net omgekeerd. Aan de Midatlantische Rug komt nieuwe korst bij, dus drijven Amerika en Europa uiteen. De Stille Oceaan is aan alle kanten omringd door subductiezones en krimpt."),
]
