# -*- coding: utf-8 -*-
"""Ruimtegebruik en verstedelijking in Vlaanderen.

Uit de vakfiche aardrijkskunde van de 3de graad doorstroomfinaliteit (2027),
onderdeel Ruimtelijke ordening, rubriek Verstedelijking en ruimtegebruik.

Deel 1 is de verstedelijking in fasen: urbanisatie, suburbanisatie,
rurbanisatie, desurbanisatie en re-urbanisatie, en de woontypologieën die
erbij horen.
Deel 2 zijn de gevolgen en het beleid: ruimtebeslag, verharding,
versnippering, lintbebouwing, het hitte-eiland, sociale segregatie en urban
sprawl, met het gewestplan, het RSV en het BRV.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is urbanisatie?",
         opties=["mensen trekken naar de stad",
                 "mensen verlaten de stad voor het platteland",
                 "mensen keren terug naar de stadskern",
                 "mensen verhuizen van dorp naar dorp"],
         antwoord=0,
         uitleg="Urbanisatie is de eerste fase: door de industrie is er werk in de stad, dus groeit de stadsbevolking snel aan."),
    dict(type="meerkeuze",
         vraag="Wat is suburbanisatie?",
         opties=["de stadsrand groeit aan",
                 "de stadskern wordt helemaal volgebouwd",
                 "het platteland loopt helemaal leeg",
                 "de dorpen krimpen tot kleine gehuchten"],
         antwoord=0,
         uitleg="Wie het kan betalen, verhuist naar de rand: rustiger, groener, een eigen tuin. Werken doen die mensen vaak nog in de stad, dus pendelen ze."),
    dict(type="invultekst",
         vraag="Hoe heet het naar de stad trekken van mensen? Eén woord.",
         antwoord=["urbanisatie", "verstedelijking"],
         uitleg="Urbanisatie. Wereldwijd woont sinds 2007 meer dan de helft van de mensen in een stad."),
    dict(type="meerkeuze",
         vraag="Wat is rurbanisatie?",
         opties=["stedelingen trekken naar het platteland",
                 "boeren verhuizen allemaal naar de stad",
                 "de stadsrand wordt landbouwgebied",
                 "dorpen worden aan de stad vastgebouwd"],
         antwoord=0,
         uitleg="Bij rurbanisatie gaan mensen verder weg wonen, in landelijke dorpen, maar nemen ze hun stedelijke manier van leven mee. Het dorp verliest zijn landbouwkarakter."),
    dict(type="waarofniet",
         vraag="Bij desurbanisatie verliest het stedelijk gebied als geheel inwoners.",
         antwoord=True,
         uitleg="Niet enkel de kern maar de hele agglomeratie krimpt, terwijl de bevolking verder uitzwermt. Dat zag je in de jaren zeventig en tachtig in veel Europese steden."),
    dict(type="meerkeuze",
         vraag="Wat is re-urbanisatie?",
         opties=["de stadskern trekt opnieuw bewoners aan",
                 "de stadsrand groeit nog verder aan",
                 "het platteland wordt opnieuw landbouwgebied",
                 "de stad verhuist naar een andere plaats"],
         antwoord=0,
         uitleg="Sinds de jaren negentig komen jonge gezinnen, studenten en ouderen terug naar de stad, onder meer door stadsvernieuwing en nabijheid van alles."),
    dict(type="meerkeuze",
         vraag="Welke fasen van verstedelijking volgen elkaar in deze orde op?",
         opties=["urbanisatie", "suburbanisatie",
                 "desurbanisatie en re-urbanisatie", "de-industrialisatie"],
         antwoord=[0, 1, 2],
         uitleg="Het model gaat van urbanisatie naar suburbanisatie, dan desurbanisatie en ten slotte re-urbanisatie. De-industrialisatie is iets anders, al hangt het ermee samen."),
    dict(type="invultekst",
         vraag="Hoe heet het dagelijks heen en weer reizen tussen woonplaats en werk? Eén woord.",
         antwoord=["pendelen", "pendel", "forenzen"],
         uitleg="Pendelen. Hoe verder iemand van zijn werk woont, hoe meer verkeer en uitstoot, en net dat maakt suburbanisatie zo duur voor de samenleving."),
    dict(type="meerkeuze",
         vraag="Welke woonvorm staat typisch in de twintigste-eeuwse gordel van een stad?",
         opties=["de rijwoning in een gesloten straat",
                 "de vrijstaande villa in een verkaveling",
                 "de hoeve met akkers eromheen",
                 "de hoogbouw van een woontoren"],
         antwoord=0,
         uitleg="De gordel rond de oude kern bestaat vooral uit rijwoningen uit het begin van de twintigste eeuw. Villa's staan verder in de rand, in verkavelingen."),
    dict(type="waarofniet",
         vraag="In Vlaanderen woont bijna iedereen in een appartement of een rijwoning.",
         antwoord=False,
         uitleg="Een groot deel woont juist in een vrijstaande woning of een halfopen bebouwing. Het ideaal van een eigen huis met een tuin zit hier diep, en daardoor is Vlaanderen heel verspreid bebouwd."),
    dict(type="meerkeuze",
         vraag="Wat is een verkaveling?",
         opties=["een grond opgedeeld in bouwpercelen",
                 "een gebied dat niet bebouwd mag worden",
                 "een straat met enkel appartementen",
                 "een plan voor een hele gemeente"],
         antwoord=0,
         uitleg="Bij een verkaveling wordt een stuk grond in loten verdeeld, met wegen en nutsleidingen erbij. Veel van de Vlaamse rand is zo volgebouwd."),
    dict(type="meerkeuze",
         vraag="Welke woontypologieën vind je in een Vlaamse stad en haar rand?",
         opties=["de rijwoning in de negentiende-eeuwse gordel",
                 "de vrijstaande woning in een verkaveling",
                 "het appartement in de stadskern",
                 "de iglo aan de rand van de stad"],
         antwoord=[0, 1, 2],
         uitleg="Rijwoningen, vrijstaande woningen in verkavelingen en appartementen in de kern zijn de drie grote typen. Elk type vraagt een heel andere hoeveelheid ruimte."),
    dict(type="meerkeuze",
         vraag="Waarom groeide de Vlaamse rand zo sterk in de twintigste eeuw?",
         opties=["goedkoop treinvervoer en later de wagen",
                 "de eigen woning werd aangemoedigd",
                 "er stond ruim woongebied op het plan",
                 "de stad verbood nieuwe woningen"],
         antwoord=[0, 1, 2],
         uitleg="De goedkope abonnementen op de buurtspoorwegen en later de wagen maakten het mogelijk ver van je werk te wonen. Daarbovenop moedigde de overheid de eigen woning aan en tekenden de gewestplannen heel ruim woongebied in."),
    dict(type="invultekst",
         vraag="Hoe noemen we het uitzwermen van bebouwing rond een stad, met een Engelse term van twee woorden?",
         antwoord=["urban sprawl", "sprawl"],
         uitleg="Urban sprawl: lage bebouwing die zich ver buiten de stad uitspreidt, met veel wegen, veel autoverkeer en weinig open ruimte ertussen."),
    dict(type="meerkeuze",
         vraag="Wat is sociale segregatie in een stad?",
         opties=["groepen wonen in gescheiden wijken",
                 "de stad groeit sneller dan het platteland",
                 "de huizen worden duurder dan vroeger",
                 "de bevolking van de stad veroudert sterk"],
         antwoord=0,
         uitleg="Mensen met eenzelfde inkomen, afkomst of leeftijd komen in dezelfde wijken terecht. Dat gebeurt meestal niet bewust, maar door prijzen en kansen op de woonmarkt."),
    dict(type="waarofniet",
         vraag="Gentrificatie maakt een volkswijk op de duur onbetaalbaar voor de oorspronkelijke bewoners.",
         antwoord=True,
         uitleg="Als een wijk opknapt en in de mode komt, stijgen de huur en de prijzen. Wie er al woonde, kan dat vaak niet volgen en moet verhuizen."),
    dict(type="meerkeuze",
         vraag="Welke groep trekt bij re-urbanisatie vaak als eerste naar de stad terug?",
         opties=["jonge mensen zonder kinderen",
                 "gezinnen met drie of meer kinderen",
                 "boeren en tuinders uit de streek",
                 "gepensioneerden uit de verkaveling"],
         antwoord=0,
         uitleg="Studenten en jonge werkenden zoeken nabijheid, uitgaan en openbaar vervoer. Krijgen ze kinderen, dan vertrekt een deel alsnog naar de rand."),
    dict(type="waarofniet",
         vraag="Vlaanderen bestaat uit enkele grote steden met daartussen nog bijna lege open ruimte.",
         antwoord=False,
         uitleg="Het is net omgekeerd: Vlaanderen is een nevelstad, met bebouwing verspreid over bijna het hele gebied en weinig echt grote open stukken."),
    dict(type="meerkeuze",
         vraag="Wat bedoelen we met de nevelstad Vlaanderen?",
         opties=["bebouwing ligt overal verspreid",
                 "er hangt vaak nevel boven de steden",
                 "de steden liggen allemaal aan de kust",
                 "de bevolking woont in enkele grote kernen"],
         antwoord=0,
         uitleg="Vlaanderen heeft geen scherpe grens tussen stad en platteland. De bebouwing ligt als een nevel over het hele gebied uitgesmeerd, langs wegen en in linten."),
    dict(type="meerkeuze",
         vraag="Waarom tekent een kaart van de nachtelijke lichten Vlaanderen zo helder?",
         opties=["de bebouwing en de wegen liggen overal",
                 "er staan hier meer lantaarns per inwoner",
                 "het is hier vaker bewolkt dan elders",
                 "de steden liggen hier dicht bij elkaar"],
         antwoord=0,
         uitleg="Op satellietbeelden bij nacht is de verspreide bebouwing en het dichte wegennet goed te zien. Het is een van de best verlichte gebieden ter wereld."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is ruimtebeslag?",
         opties=["de oppervlakte die de mens inneemt",
                 "de oppervlakte die onder beton zit",
                 "de oppervlakte die landbouw gebruikt",
                 "de oppervlakte die als natuur beschermd is"],
         antwoord=0,
         uitleg="Ruimtebeslag is alle grond die wonen, werken, vervoer en voorzieningen innemen, dus ook de tuin en de oprit. Niet alles daarvan is verhard."),
    dict(type="meerkeuze",
         vraag="Wat is verharding?",
         opties=["de grond is bedekt met beton of asfalt",
                 "de grond wordt harder door droogte",
                 "de grond is in gebruik door de mens",
                 "de grond wordt bewerkt met machines"],
         antwoord=0,
         uitleg="Verharde grond laat geen water door en warmt sterk op. Daardoor loopt het water bij een bui meteen naar de riool in plaats van in de bodem te zakken."),
    dict(type="invultekst",
         vraag="Hoeveel procent van Vlaanderen is ongeveer in gebruik door de mens? Schrijf het getal.",
         antwoord=["33", "32", "34"],
         uitleg="Ongeveer een derde van Vlaanderen is ruimtebeslag. Daarvan is zowat de helft echt verhard, en elke dag komt er nog een stuk bij."),
    dict(type="waarofniet",
         vraag="Verharding verhoogt het risico op wateroverlast na een zware bui.",
         antwoord=True,
         uitleg="Water dat niet in de bodem kan zakken, stroomt af naar de laagste plek. Daar komt het ineens samen en loopt het water de straat of de kelder in."),
    dict(type="meerkeuze",
         vraag="Wat is versnippering van de open ruimte?",
         opties=["de open ruimte valt in losse stukjes uiteen",
                 "de open ruimte wordt in één keer volgebouwd",
                 "de open ruimte wordt beschermd natuurgebied",
                 "de open ruimte wordt gebruikt voor landbouw"],
         antwoord=0,
         uitleg="Wegen, linten en losse gebouwen snijden het landschap in kleine stukken. Voor dieren zijn die stukken te klein en niet meer met elkaar verbonden."),
    dict(type="meerkeuze",
         vraag="Welke gevolgen heeft verspreide bebouwing in Vlaanderen?",
         opties=["duurdere leidingen en wegen per woning",
                 "meer autoverkeer en langere ritten",
                 "versnippering van natuur en landbouw",
                 "een lagere prijs voor bouwgrond"],
         antwoord=[0, 1, 2],
         uitleg="Hoe verspreider we wonen, hoe meer riool, kabel, weg en busrit per gezin, en hoe meer het landschap in stukken valt. Bouwgrond werd er niet goedkoper van."),
    dict(type="invultekst",
         vraag="Hoe heet bebouwing die als een lange rij langs een weg staat? Eén woord.",
         antwoord=["lintbebouwing", "lint", "linten"],
         uitleg="Lintbebouwing. Ze maakt lange leidingen nodig, snijdt velden van elkaar af en zorgt voor veel in- en uitritten op een drukke weg."),
    dict(type="meerkeuze",
         vraag="Waarom is lintbebouwing nadelig?",
         opties=["ze snijdt de open ruimte in stukken",
                 "ze staat altijd in overstromingsgebied",
                 "ze is verboden door Europese regels",
                 "ze levert te weinig woningen op"],
         antwoord=0,
         uitleg="Een lint vormt een lange barrière door het landschap en vraagt kilometers leiding en weg voor weinig woningen. Daarom wil het beleid vooral in de kernen bijbouwen."),
    dict(type="meerkeuze",
         vraag="Wat is het stedelijk hitte-eiland?",
         opties=["de stad is warmer dan haar omgeving",
                 "een park midden in een drukke stad",
                 "een eiland in de haven van een stad",
                 "een wijk waar airco verplicht is"],
         antwoord=0,
         uitleg="Beton en asfalt slaan warmte op en geven ze 's nachts af, en er is weinig groen om te verkoelen. In een zomernacht kan de stad enkele graden warmer zijn dan het platteland."),
    dict(type="waarofniet",
         vraag="Het verschil van het hitte-eiland is het grootst op een zomernacht.",
         antwoord=True,
         uitleg="Overdag schijnt de zon op beide, maar 's nachts koelt het platteland snel af terwijl de stad haar opgeslagen warmte blijft afgeven."),
    dict(type="meerkeuze",
         vraag="Welke maatregelen verzachten het hitte-eiland?",
         opties=["bomen planten in de straten",
                 "verharding wegnemen voor groen",
                 "water in de stad brengen",
                 "donkere dakbedekking kiezen"],
         antwoord=[0, 1, 2],
         uitleg="Bomen geven schaduw en verdampen water, ontharding en water koelen. Een donker dak doet het omgekeerde: dat slorpt juist meer zonnewarmte op."),
    dict(type="meerkeuze",
         vraag="Wat was het gewestplan?",
         opties=["de eerste kaart met bestemmingen per perceel",
                 "een plan om alle steden te vernieuwen",
                 "een Europese kaart van alle natuurgebieden",
                 "het plan dat nu het ruimtebeleid bepaalt"],
         antwoord=0,
         uitleg="De gewestplannen van de jaren zeventig kleurden elk perceel in: woongebied, industrie, landbouw, natuur. Er werd heel ruim woongebied ingetekend, en dat voelen we nu nog."),
    dict(type="invultekst",
         vraag="Welk plan volgde in 1997 op de gewestplannen? Schrijf de afkorting.",
         antwoord=["RSV", "rsv"],
         uitleg="Het Ruimtelijk Structuurplan Vlaanderen. Het wou de groei bundelen, met zestig procent van de nieuwe woningen in de steden en veertig op het platteland."),
    dict(type="meerkeuze",
         vraag="Wat wil het Beleidsplan Ruimte Vlaanderen?",
         opties=["het bijkomend ruimtebeslag naar nul brengen",
                 "elk jaar meer bouwgrond vrijgeven",
                 "alle open ruimte tot natuurgebied maken",
                 "alleen nog hoogbouw toelaten in Vlaanderen"],
         antwoord=0,
         uitleg="Het BRV wil dat er tegen 2040 geen open ruimte meer wordt aangesneden. Nieuwe woningen komen dan in de kernen, door te verdichten en te hergebruiken."),
    dict(type="waarofniet",
         vraag="Het BRV wil tegen 2040 helemaal geen nieuwe woningen meer bijbouwen.",
         antwoord=False,
         uitleg="Er mogen er nog bij, maar niet meer op nieuwe open ruimte. Ze moeten in de kernen komen, op grond die al in gebruik is."),
    dict(type="meerkeuze",
         vraag="Wat is de bouwshift?",
         opties=["bouwen in de kernen, niet in open ruimte",
                 "een verbod op bouwen in heel Vlaanderen",
                 "een verschuiving naar bouwen in hout",
                 "het bouwen van hoogbouw op het platteland"],
         antwoord=0,
         uitleg="De bouwshift, eerder betonstop genoemd, verschuift het bouwen naar plekken die al bebouwd zijn. Zo blijft de open ruimte open."),
    dict(type="meerkeuze",
         vraag="Welke kernkwaliteiten noemt het BRV voor een goede plek?",
         opties=["nabijheid van voorzieningen",
                 "een goed bereikbare ligging",
                 "ruimte voor water en groen",
                 "een zo groot mogelijk perceel"],
         antwoord=[0, 1, 2],
         uitleg="Nabijheid, bereikbaarheid, een gezonde leefomgeving en ruimte voor water en natuur zijn de kernkwaliteiten. Een groot perceel staat daar niet bij."),
    dict(type="waarofniet",
         vraag="Een gezin in een kern verbruikt meer ruimte en energie dan een gezin in een verkaveling.",
         antwoord=False,
         uitleg="Omgekeerd. In een kern is de woning kleiner, de leidingen korter en de afstand tot winkel of school te voet te doen."),
    dict(type="meerkeuze",
         vraag="Waarom is de bouwshift politiek zo moeilijk?",
         opties=["wie bouwgrond heeft, verliest waarde",
                 "er is in de kernen geen plaats meer vrij",
                 "Europa verbiedt het bijbouwen in kernen",
                 "er zijn te weinig bouwbedrijven voor"],
         antwoord=0,
         uitleg="Honderdduizenden percelen staan op het gewestplan als woongebied. Wie zo'n perceel niet meer mag volbouwen, wil daarvoor vergoed worden, en dat kost miljarden."),
    dict(type="meerkeuze",
         vraag="Welk begrip past bij een stad waar alles op wandelafstand ligt?",
         opties=["nabijheid",
                 "versnippering van het landschap",
                 "lintbebouwing langs de steenweg",
                 "ruimtebeslag per inwoner"],
         antwoord=0,
         uitleg="Nabijheid is een kernkwaliteit van het BRV: school, winkel, werk en halte dicht bij je woning. Dan heb je de wagen veel minder nodig."),
]
