# -*- coding: utf-8 -*-
"""Aardbevingen en vulkanisme.

Uit de vakfiche aardrijkskunde van de 3de graad doorstroomfinaliteit (2027),
onderdeel De geosfeer, rubriek Gevolgen van de platentektoniek.

Deel 1 zijn de aardbevingen: hypocentrum en epicentrum, de seismograaf en het
seismogram, de schaal van Richter en de momentmagnitudeschaal, en de gevolgen
zoals tsunami's.
Deel 2 is het vulkanisme: de delen van een vulkaan, het verschil tussen een
stratovulkaan en een schildvulkaan, magma en lava, lapilli, vulkanische
bommen en as, de Ring of Fire en de lahars.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is het hypocentrum van een aardbeving?",
         opties=["de plaats in de diepte waar de beving begint",
                 "het punt aan het oppervlak net boven de beving",
                 "de plaats waar de schade het grootst is",
                 "het meetstation dat de beving als eerste ziet"],
         antwoord=0,
         uitleg="Het hypocentrum of de haard ligt in de korst of de mantel. Het epicentrum is het punt aan het oppervlak er recht boven."),
    dict(type="invultekst",
         vraag="Hoe heet het punt aan het aardoppervlak recht boven de haard van een beving?",
         antwoord=["epicentrum", "het epicentrum"],
         uitleg="In het epicentrum komen de golven het eerst en het sterkst aan. Daar is de schade meestal het grootst."),
    dict(type="meerkeuze",
         vraag="Waarom beeft de aarde bij een tektonische aardbeving?",
         opties=["opgebouwde spanning komt plots vrij",
                 "het magma kookt in de kern van de aarde",
                 "de zwaartekracht van de maan trekt aan de korst",
                 "de korst zet uit door de warmte van de zon"],
         antwoord=0,
         uitleg="Platen haken aan elkaar vast en de spanning loopt op. Schiet het gesteente plots los, dan komt die energie vrij als golven."),
    dict(type="meerkeuze",
         vraag="Wat lees je af op een seismogram?",
         opties=["de bewegingen van de bodem in de tijd",
                 "de luchtdruk op het moment van de beving",
                 "de diepte van het grondwater ter plaatse",
                 "de dikte van de aardkorst onder het station"],
         antwoord=0,
         uitleg="Een seismogram is de uitdraai van een seismograaf: een lijn die uitslaat zodra de golven aankomen. Uit het tijdsverschil tussen de golfsoorten volgt de afstand tot de haard."),
    dict(type="waarofniet",
         vraag="Met metingen van drie seismische stations kan je het epicentrum van een beving bepalen.",
         antwoord=True,
         uitleg="Elk station levert een afstand, en dus een cirkel op de kaart. Waar drie cirkels elkaar snijden, ligt het epicentrum."),
    dict(type="meerkeuze",
         vraag="Wat geeft de schaal van Richter?",
         opties=["de kracht van een beving in de haard",
                 "de schade aan de gebouwen in een stad",
                 "de diepte waarop de beving ontstond",
                 "het aantal naschokken na de hoofdbeving"],
         antwoord=0,
         uitleg="Richter geeft de magnitude: de vrijgekomen energie, afgeleid uit de uitslag op het seismogram. De schade hangt ook van de bodem en de bouwwijze af."),
    dict(type="invultekst",
         vraag="Hoe heet de schaal die vandaag de magnitude van zware bevingen het best weergeeft? Schrijf de afkorting.",
         antwoord=["MMS", "mms", "momentmagnitudeschaal"],
         uitleg="De momentmagnitudeschaal of MMS. De schaal van Richter verzadigt bij heel zware bevingen en wordt daarom nog vooral voor lichtere bevingen gebruikt."),
    dict(type="meerkeuze",
         vraag="Een beving van magnitude 7 tegenover een van magnitude 6: wat is juist?",
         opties=["magnitude 7 maakt veel meer energie vrij",
                 "magnitude 7 maakt precies één keer meer energie vrij",
                 "magnitude 7 maakt even veel energie vrij",
                 "magnitude 7 maakt minder energie vrij"],
         antwoord=0,
         uitleg="De schaal is logaritmisch. Eén eenheid hoger betekent tien keer meer uitslag en ongeveer dertig keer meer energie."),
    dict(type="waarofniet",
         vraag="Een beving van magnitude 8 is twee keer zo sterk als een van magnitude 4.",
         antwoord=False,
         uitleg="De schaal is logaritmisch, niet lineair. Vier eenheden verschil is tienduizend keer meer uitslag en ruim een miljoen keer meer energie."),
    dict(type="meerkeuze",
         vraag="Hoe ontstaat een tsunami?",
         opties=["de zeebodem verschuift bij een beving",
                 "een storm duwt het water tegen de kust",
                 "de maan staat extra dicht bij de aarde",
                 "een rivier voert te veel water af"],
         antwoord=0,
         uitleg="Een verticale verschuiving van de zeebodem tilt de hele waterkolom op. Die golf loopt met honderden kilometer per uur over de oceaan en stuwt bij de kust hoog op."),
    dict(type="invultekst",
         vraag="Hoe heet de reusachtige zeegolf die na een onderzeese beving ontstaat? Eén woord.",
         antwoord=["tsunami", "een tsunami"],
         uitleg="Op volle zee is een tsunami maar enkele decimeter hoog, maar bij de kust loopt hij op tot tientallen meter."),
    dict(type="meerkeuze",
         vraag="Welke gevolgen kan een zware aardbeving hebben?",
         opties=["instortende gebouwen", "een tsunami aan de kust",
                 "aardverschuivingen op hellingen", "een ozongat boven de pool"],
         antwoord=[0, 1, 2],
         uitleg="Instorting, tsunami's, aardverschuivingen, branden en breuken in leidingen. Met de ozonlaag heeft een beving niets te maken."),
    dict(type="meerkeuze",
         vraag="Waarom is dezelfde beving in een arm land vaak dodelijker dan in een rijk land?",
         opties=["de gebouwen zijn er minder bevingsveilig",
                 "er is minder geld voor een waarschuwingssysteem",
                 "de hulpdiensten kunnen er minder snel ter plaatse zijn",
                 "de bevingen zijn er altijd zwaarder van magnitude"],
         antwoord=[0, 1, 2],
         uitleg="Bevingsveilig bouwen, waarschuwen en hulp organiseren kost allemaal geld. De magnitude zelf heeft niets met rijkdom te maken."),
    dict(type="waarofniet",
         vraag="Ook in België komen af en toe lichte aardbevingen voor.",
         antwoord=True,
         uitleg="Rond de Roerdalslenk en in het Luikse zijn er oude breuken die nog bewegen. De beving van Luik in 1983 haalde magnitude 4,6 en richtte echte schade aan."),
    dict(type="meerkeuze",
         vraag="Welke golven van een aardbeving komen het eerst aan bij een meetstation?",
         opties=["de P-golven", "de S-golven",
                 "de oppervlaktegolven", "alle golven samen"],
         antwoord=0,
         uitleg="P staat voor primair: de snelste golven, die ook door vloeistof gaan. De S-golven komen later en zijn vaak schadelijker."),
    dict(type="meerkeuze",
         vraag="Waarom kan een waarschuwingssysteem enkele seconden winnen voor een beving toeslaat?",
         opties=["de P-golven komen als eerste aan",
                 "de bodem begint uren eerder te trillen",
                 "dieren voelen een beving altijd vooraf aan",
                 "de luchtdruk daalt voor een beving begint"],
         antwoord=0,
         uitleg="Sensoren bij de haard vangen de P-golven op en sturen meteen een signaal. Dat gaat sneller dan de langzamere, schadelijke golven zelf."),
    dict(type="invultekst",
         vraag="Hoe heet een lichtere beving die na de hoofdbeving volgt? Eén woord.",
         antwoord=["naschok", "naschokken", "een naschok"],
         uitleg="Na een zware beving zoekt het gesteente in de omgeving een nieuw evenwicht. Dat geeft naschokken, die dagen tot maanden kunnen doorgaan."),
    dict(type="waarofniet",
         vraag="Wetenschappers kunnen de dag en het uur van een aardbeving nauwkeurig voorspellen.",
         antwoord=False,
         uitleg="Waar bevingen gebeuren en hoe vaak, is goed gekend. Het exacte moment niet, en daar is nog geen methode voor. Vandaar het belang van bouwvoorschriften."),
    dict(type="meerkeuze",
         vraag="Welke begrippen noemt de vakfiche bij de aardbevingen?",
         opties=["seismologie en seismogram", "seismograaf",
                 "hypocentrum en epicentrum", "doline en resurgentie"],
         antwoord=[0, 1, 2],
         uitleg="De fiche noemt seismologie, seismogram, seismograaf, hypocentrum, epicentrum, Richter en de MMS. Dolines en resurgenties horen bij karst."),
    dict(type="meerkeuze",
         vraag="Waarom beeft de grond in een zachte, opgevulde vallei harder dan op vast gesteente?",
         opties=["losse grond versterkt de golven",
                 "losse grond is zwaarder dan gesteente",
                 "op gesteente komen de golven nooit aan",
                 "losse grond geleidt de golven veel sneller"],
         antwoord=0,
         uitleg="In losse sedimenten worden de golven trager en groter van uitslag. Mexico-Stad, gebouwd op een oude meerbodem, is het bekendste voorbeeld."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is het verschil tussen magma en lava?",
         opties=["magma zit in de aarde, lava stroomt erbuiten",
                 "magma is koud en lava is heet",
                 "magma is vast en lava is gasvormig",
                 "magma komt uit de kern en lava uit de korst"],
         antwoord=0,
         uitleg="Het is dezelfde gesmolten stof. Zolang ze onder de grond zit, heet ze magma, en zodra ze uitvloeit, lava."),
    dict(type="invultekst",
         vraag="Hoe heet gesmolten gesteente dat nog in de aarde zit?",
         antwoord=["magma", "het magma"],
         uitleg="Magma verzamelt zich in een magmakamer. Stijgt de druk, dan perst het zich door de schoorsteen naar buiten en wordt het lava."),
    dict(type="meerkeuze",
         vraag="Welke delen horen bij een vulkaan?",
         opties=["de magmakamer", "de schoorsteen of pijp",
                 "de krater", "het epicentrum"],
         antwoord=[0, 1, 2],
         uitleg="Een vulkaan heeft een magmakamer, een schoorsteen, een krater en vaak zijschoorstenen. Een epicentrum hoort bij een aardbeving."),
    dict(type="meerkeuze",
         vraag="Wat kenmerkt een schildvulkaan?",
         opties=["flauwe hellingen en dunne lava",
                 "steile hellingen en dikke lava",
                 "een diepe caldera zonder krater",
                 "een kegel van enkel as en puin"],
         antwoord=0,
         uitleg="Dunne, basaltische lava loopt ver uit voor ze stijft. Daardoor bouwt een schildvulkaan zich breed en vlak op, zoals de Mauna Loa op Hawaï."),
    dict(type="meerkeuze",
         vraag="Wat kenmerkt een stratovulkaan?",
         opties=["afwisselende lagen lava en as",
                 "één enkele dikke laag basalt",
                 "een vlakke, brede koepel",
                 "een krater zonder enige kegel"],
         antwoord=0,
         uitleg="Een stratovulkaan wisselt laag na laag lava en as af, vandaar de naam. Dat geeft steile kegels zoals de Fuji of de Vesuvius, en vaak explosieve uitbarstingen."),
    dict(type="waarofniet",
         vraag="Een stratovulkaan barst gewoonlijk explosiever uit dan een schildvulkaan.",
         antwoord=True,
         uitleg="Zijn magma is taaier en houdt gas vast tot de druk te hoog wordt. Bij een schildvulkaan ontsnapt het gas makkelijk en vloeit de lava rustig weg."),
    dict(type="invultekst",
         vraag="Hoe heet de vulkaangordel rond de Stille Oceaan? Drie woorden in het Engels.",
         antwoord=["Ring of Fire", "ring of fire"],
         uitleg="De Ring of Fire volgt de subductiezones rond de Stille Oceaan. Daar liggen ongeveer driekwart van alle actieve vulkanen op aarde."),
    dict(type="meerkeuze",
         vraag="Wat zijn lapilli?",
         opties=["kleine steentjes die een vulkaan uitspuwt",
                 "de kleine scheurtjes in een lavastroom",
                 "de gassen die uit een krater ontsnappen",
                 "de druipstenen in een vulkanische grot"],
         antwoord=0,
         uitleg="Lapilli zijn uitgeworpen stukjes van enkele millimeter tot enkele centimeter. Wat groter is, heet een vulkanische bom, wat fijner is, vulkanische as."),
    dict(type="meerkeuze",
         vraag="Welk uitgeworpen materiaal is het grootst?",
         opties=["een vulkanische bom", "een stuk lapilli",
                 "een korrel vulkanische as", "een druppel nevel"],
         antwoord=0,
         uitleg="Van groot naar klein: vulkanische bommen, lapilli en as. Bommen kunnen zo groot zijn als een auto."),
    dict(type="waarofniet",
         vraag="Vulkanische as kan het luchtverkeer over een heel werelddeel stilleggen.",
         antwoord=True,
         uitleg="Fijne as smelt in een vliegtuigmotor en verstopt hem. Toen de IJslandse Eyjafjallajökull in 2010 uitbarstte, lag het Europese luchtverkeer dagen stil."),
    dict(type="meerkeuze",
         vraag="Wat is een lahar?",
         opties=["een modderstroom van as en water",
                 "een stroom gloeiende lava in een dal",
                 "een wolk gas boven een krater",
                 "een meer in een ingestorte caldera"],
         antwoord=0,
         uitleg="As vermengd met smeltwater of regen wordt een modderstroom die zich met hoge snelheid door de valleien stort. Lahars zijn vaak dodelijker dan de lava zelf."),
    dict(type="invultekst",
         vraag="Hoe heet een modderstroom van vulkanische as en water? Eén woord.",
         antwoord=["lahar", "een lahar", "lahars"],
         uitleg="Het woord komt uit het Indonesisch. Nevado del Ruiz in Colombia veroorzaakte in 1985 een lahar die een hele stad bedolf."),
    dict(type="meerkeuze",
         vraag="Waarom wonen er toch veel mensen op de flanken van een vulkaan?",
         opties=["de bodem is er heel vruchtbaar",
                 "er is aardwarmte te winnen",
                 "er komen veel toeristen op af",
                 "er gebeuren daar nooit aardbevingen"],
         antwoord=[0, 1, 2],
         uitleg="Verweerde vulkanische as geeft een rijke bodem, en daar komen aardwarmte en toerisme bij. Juist bij een vulkaan beeft de grond wel vaak."),
    dict(type="waarofniet",
         vraag="Een uitbarsting warmt het klimaat van de hele aarde voor een jaar of langer op.",
         antwoord=False,
         uitleg="Ze koelt juist af. Zwaveldeeltjes in de stratosfeer weerkaatsen zonlicht, en na de Pinatubo in 1991 lag de wereldgemiddelde temperatuur een half graadje lager."),
    dict(type="meerkeuze",
         vraag="Welke soorten vulkanen vergelijkt de vakfiche?",
         opties=["de stratovulkaan en de schildvulkaan",
                 "de kegelvulkaan en de spleetvulkaan",
                 "de koepelvulkaan en de caldera",
                 "de hotspotvulkaan en de riftvulkaan"],
         antwoord=0,
         uitleg="De fiche vraagt uitdrukkelijk om strato- en schildvulkanen te vergelijken: hun vorm, hun lava en hun manier van uitbarsten."),
    dict(type="meerkeuze",
         vraag="Welke vormen van uitgeworpen materiaal noemt de vakfiche?",
         opties=["lapilli", "vulkanische bommen",
                 "vulkanische as", "druipstenen"],
         antwoord=[0, 1, 2],
         uitleg="De fiche noemt lapilli, vulkanische bommen, vulkanische as, en daarnaast magma en lava. Druipstenen horen bij karst."),
    dict(type="waarofniet",
         vraag="Alle vulkanen liggen aan de rand van een tektonische plaat.",
         antwoord=False,
         uitleg="De meeste wel, maar een hotspotvulkaan zoals op Hawaï zit midden op een plaat, boven een mantelpluim."),
    dict(type="meerkeuze",
         vraag="Waarom is de lava van een schildvulkaan dunner van samenstelling?",
         opties=["ze bevat minder kiezelzuur",
                 "ze is veel kouder bij het uitvloeien",
                 "ze bevat veel meer waterdamp",
                 "ze stroomt door een bredere krater"],
         antwoord=0,
         uitleg="Basaltische lava heeft een lager gehalte aan silica en is daardoor veel vloeibaarder. Taaie, silicarijke lava hoort bij explosieve stratovulkanen."),
    dict(type="meerkeuze",
         vraag="Hoe kan aardwarmte op een vulkanisch eiland gebruikt worden?",
         opties=["om elektriciteit en warmte te maken",
                 "om de zeespiegel te laten dalen",
                 "om aardbevingen te voorkomen",
                 "om de lava naar de zee te leiden"],
         antwoord=0,
         uitleg="Heet water en stoom uit de ondergrond drijven turbines aan en verwarmen huizen. IJsland haalt daar een groot deel van zijn energie uit."),
    dict(type="meerkeuze",
         vraag="Waarom is een gloedwolk zo gevaarlijk?",
         opties=["ze schiet razendsnel de flank af",
                 "ze blijft dagenlang boven de krater hangen",
                 "ze bevat vooral koud water en modder",
                 "ze verspreidt zich enkel in de hoogte"],
         antwoord=0,
         uitleg="Een gloedwolk of pyroclastische stroom is een mengsel van gloeiend gas en as dat met honderden kilometer per uur de helling afschiet. Pompeï werd zo bedolven."),
]
