# -*- coding: utf-8 -*-
"""Klimaatgebieden, biomen en zeestromen.

Uit de vakfiche aardrijkskunde van de 3de graad doorstroomfinaliteit (2027),
onderdeel De atmosfeer, rubriek Weer en klimaat.

Deel 1 is de indeling van de klimaten op aarde aan de hand van temperatuur en
neerslag, het lezen van een klimatogram, en de biomen die daarbij horen:
tropisch regenwoud, savanne, woestijn, steppe, taiga, toendra en
poolwoestijn.
Deel 2 zijn de zeestromen: warme en koude stromen, hun invloed op het klimaat
van een plaats, de thermohaliene circulatie en wat er zou gebeuren als die
stilvalt.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Waarop is de klimaatindeling van de aarde gebaseerd?",
         opties=["op temperatuur en neerslag",
                 "op de hoogte boven de zeespiegel alleen",
                 "op de bevolkingsdichtheid van een gebied",
                 "op het soort gesteente in de ondergrond"],
         antwoord=0,
         uitleg="De verdeling van de temperatuur en van de neerslag over het jaar bepaalt het klimaat. Daar hangt dan weer de natuurlijke plantengroei aan vast."),
    dict(type="meerkeuze",
         vraag="Wat is het verschil tussen weer en klimaat?",
         opties=["weer is nu, klimaat is het gemiddelde over jaren",
                 "weer meet je op zee en klimaat op het land",
                 "weer gaat over regen en klimaat over temperatuur",
                 "weer geldt voor een land en klimaat voor een werelddeel"],
         antwoord=0,
         uitleg="Weer is de toestand van de atmosfeer op dit moment. Klimaat is het gemiddelde weerbeeld over dertig jaar, met de uitersten erbij."),
    dict(type="invultekst",
         vraag="Over hoeveel jaar wordt een klimaat gewoonlijk gemiddeld? Schrijf het getal.",
         antwoord=["30", "dertig"],
         uitleg="De afspraak is dertig jaar. Daardoor vallen losse uitschieters weg en zie je het echte patroon."),
    dict(type="meerkeuze",
         vraag="Wat lees je op een klimatogram af?",
         opties=["de temperatuur en de neerslag per maand",
                 "de luchtdruk en de windrichting per dag",
                 "de hoogte en de helling van het reliëf",
                 "de bevolking en het landgebruik per jaar"],
         antwoord=0,
         uitleg="Een klimatogram zet twaalf maanden naast elkaar, met de temperatuur als lijn en de neerslag als staven."),
    dict(type="waarofniet",
         vraag="Een klimatogram waarin de warmste maanden in juni en juli vallen, hoort bij het noordelijk halfrond.",
         antwoord=True,
         uitleg="Op het zuidelijk halfrond is het in december en januari zomer. De vorm van de temperatuurlijn verraadt dus op welk halfrond je zit."),
    dict(type="meerkeuze",
         vraag="Welk bioom hoort bij een klimaat met het hele jaar hoge temperaturen en veel neerslag?",
         opties=["het tropisch regenwoud", "de savanne met haar droge tijd",
                 "de taiga van het hoge noorden", "de toendra met permafrost"],
         antwoord=0,
         uitleg="Warm en nat het hele jaar geeft tropisch regenwoud, met een dicht bladerdak en verschillende lagen vegetatie."),
    dict(type="meerkeuze",
         vraag="Welk bioom hoort bij een warm klimaat met een duidelijke droge en een natte tijd?",
         opties=["de savanne", "het tropisch regenwoud",
                 "de poolwoestijn", "de taiga"],
         antwoord=0,
         uitleg="De savanne is een grasland met verspreide bomen. De regens komen als de ITCZ overtrekt, en daarna volgt een lange droogte."),
    dict(type="invultekst",
         vraag="Hoe heet het naaldbos van de koude, noordelijke streken? Eén woord.",
         antwoord=["taiga", "de taiga", "boreaal woud"],
         uitleg="De taiga of het boreale woud is een gordel van naaldbos door Canada, Scandinavië en Siberië. Naalden verliezen weinig water en overleven een lange winter."),
    dict(type="meerkeuze",
         vraag="Welk bioom ligt tussen de taiga en de poolwoestijn?",
         opties=["de toendra", "de savanne",
                 "de steppe", "het tropisch regenwoud"],
         antwoord=0,
         uitleg="Op de toendra is het te koud voor bomen. Er groeien mossen, korstmossen en dwergstruiken boven een permanent bevroren ondergrond."),
    dict(type="waarofniet",
         vraag="In een poolwoestijn valt veel neerslag, en daarom ligt er zoveel ijs.",
         antwoord=False,
         uitleg="Er valt juist bijna niets: koude lucht kan amper damp vasthouden. Antarctica krijgt minder neerslag dan de Sahara, maar wat er valt blijft eeuwen liggen."),
    dict(type="meerkeuze",
         vraag="Welke biomen noemt de vakfiche als voorbeeld?",
         opties=["de taiga", "de poolwoestijn", "de savanne",
                 "de mangrove van de Noordzee"],
         antwoord=[0, 1, 2],
         uitleg="De fiche noemt taiga, poolwoestijn, savanne en tropisch regenwoud. Mangrove groeit in de tropen, niet aan de Noordzee."),
    dict(type="meerkeuze",
         vraag="Wat kenmerkt het klimaat van België?",
         opties=["zachte winters voor onze breedte",
                 "koele zomers zonder lange hitte",
                 "neerslag in alle maanden van het jaar",
                 "een droge tijd van drie maanden"],
         antwoord=[0, 1, 2],
         uitleg="België heeft een gematigd zeeklimaat: de oceaan en de westenwinden dempen de uitersten en brengen het hele jaar neerslag. Een droge tijd hebben we niet."),
    dict(type="meerkeuze",
         vraag="Wat kenmerkt een mediterraan klimaat?",
         opties=["droge zomers en zachte, natte winters",
                 "natte zomers en droge, strenge winters",
                 "het hele jaar veel neerslag en warmte",
                 "het hele jaar droogte en grote hitte"],
         antwoord=0,
         uitleg="In de zomer schuift het subtropisch maximum over de Middellandse Zee en blijft het droog. In de winter komen de depressies er wel."),
    dict(type="invultekst",
         vraag="Hoe heet het droge grasland van de gematigde streken, zoals in Oekraïne? Eén woord.",
         antwoord=["steppe", "de steppe"],
         uitleg="De steppe ligt te ver van de zee voor bos, maar krijgt genoeg regen voor gras. In Noord-Amerika heet ze prairie."),
    dict(type="waarofniet",
         vraag="Twee plaatsen op dezelfde breedte hebben altijd hetzelfde klimaat.",
         antwoord=False,
         uitleg="De breedte geeft de zonnestand, maar de zee, de zeestromen, het reliëf en de hoogte spelen even sterk mee. Oostende en Winnipeg liggen ongeveer even noordelijk en hebben een heel ander klimaat."),
    dict(type="meerkeuze",
         vraag="Waarom groeien er in een woestijn zo weinig planten?",
         opties=["er valt te weinig neerslag",
                 "de zon is er te sterk voor bladgroen",
                 "de bodem is er altijd te zout",
                 "de nachten zijn er te koud om te groeien"],
         antwoord=0,
         uitleg="Het gebrek aan water is de grens. Plantjes die er wel groeien, slaan water op of hebben heel diepe wortels."),
    dict(type="meerkeuze",
         vraag="Welke klimaatgordels noemt de vakfiche bij de culminatiehoogte en de daglengte?",
         opties=["de polaire klimaten", "de gematigde klimaten",
                 "de tropische klimaten", "de continentale klimaten"],
         antwoord=[0, 1, 2],
         uitleg="De fiche legt het verband tussen culminatiehoogte, daglengte, breedte en temperatuur voor de polaire, de gematigde en de tropische klimaten."),
    dict(type="meerkeuze",
         vraag="Je ziet een klimatogram met twaalf maanden boven 25 °C en elke maand meer dan 150 mm regen. Welk bioom hoort daarbij?",
         opties=["het tropisch regenwoud", "de savanne",
                 "de steppe van Centraal-Azië", "het mediterrane maquis"],
         antwoord=0,
         uitleg="Warm en nat zonder droge maand is het klimaat van het tropisch regenwoud, zoals in het Amazonebekken of het Congobekken."),
    dict(type="invultekst",
         vraag="Hoe heet de permanent bevroren ondergrond van de toendra? Eén woord.",
         antwoord=["permafrost", "de permafrost"],
         uitleg="Permafrost is bodem die jaar na jaar bevroren blijft. Alleen de bovenste laag ontdooit in de zomer, en daardoor blijft het water aan de oppervlakte staan."),
    dict(type="waarofniet",
         vraag="In een continentaal klimaat is het verschil tussen de warmste en de koudste maand groter dan in een zeeklimaat.",
         antwoord=True,
         uitleg="Water werkt als een buffer. Ver van de zee ontbreekt die, en dan krijg je hete zomers en strenge winters, zoals in Siberië."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat zijn zeestromen?",
         opties=["grote, blijvende stromingen in de oceanen",
                 "de getijdenbewegingen langs een kust",
                 "de golven die door de wind gemaakt worden",
                 "de rivieren die in de zee uitmonden"],
         antwoord=0,
         uitleg="Zeestromen zijn vaste banen water die voortdurend in dezelfde richting lopen, gedreven door de wind en door verschillen in temperatuur en zoutgehalte."),
    dict(type="meerkeuze",
         vraag="Welke zeestroom brengt warm water tot bij West-Europa?",
         opties=["de Noord-Atlantische Drift", "de koude Labradorstroom",
                 "de Humboldtstroom langs Peru", "de Benguelastroom bij Namibië"],
         antwoord=0,
         uitleg="De Golfstroom gaat over in de Noord-Atlantische Drift. Die voert warm water uit de Golf van Mexico naar onze kusten."),
    dict(type="invultekst",
         vraag="Hoe heet de warme zeestroom die vanuit de Golf van Mexico vertrekt?",
         antwoord=["Golfstroom", "de Golfstroom"],
         uitleg="De Golfstroom en haar verlengde, de Noord-Atlantische Drift, zijn de reden dat onze winters zo zacht zijn."),
    dict(type="waarofniet",
         vraag="Zonder de Noord-Atlantische Drift zouden onze winters een stuk strenger zijn.",
         antwoord=True,
         uitleg="Op dezelfde breedte als Brussel ligt in Canada het gebied rond Labrador, met strenge winters. Het verschil zit in de warme stroom en de westenwind."),
    dict(type="meerkeuze",
         vraag="Wat doet een warme zeestroom met het klimaat van de kust erlangs?",
         opties=["hij maakt die kust zachter en vochtiger",
                 "hij maakt die kust kouder en droger",
                 "hij verandert daar helemaal niets aan",
                 "hij geeft er elke winter strenge vorst"],
         antwoord=0,
         uitleg="De lucht boven warm water warmt op en kan meer damp opnemen. Dat geeft zachte winters en meer neerslag."),
    dict(type="meerkeuze",
         vraag="Welke zeestromen zijn koude stromen?",
         opties=["de Labradorstroom", "de Humboldtstroom",
                 "de Benguelastroom", "de Golfstroom"],
         antwoord=[0, 1, 2],
         uitleg="Labrador, Humboldt en Benguela brengen koud water naar lagere breedten. De Golfstroom is net de bekendste warme stroom."),
    dict(type="meerkeuze",
         vraag="Waarom liggen er woestijnen pal aan de kust van Namibië en Peru?",
         opties=["een koude zeestroom houdt de lucht beneden",
                 "de zee is daar te ver weg om vocht te leveren",
                 "er waait daar nooit wind vanuit de zee landinwaarts",
                 "het reliëf houdt er alle regen van de oceaan tegen"],
         antwoord=0,
         uitleg="Koud water koelt de onderste lucht af. Die stijgt dan niet op, dus vormen zich geen regenwolken, hoewel er dikke nevelbanken zijn."),
    dict(type="invultekst",
         vraag="Hoe heet de wereldwijde kringloop van water die door temperatuur en zoutgehalte gedreven wordt? Twee woorden.",
         antwoord=["thermohaliene circulatie", "de thermohaliene circulatie"],
         uitleg="Thermo staat voor warmte en halien voor zout. Koud, zout water zinkt bij Groenland en komt elders weer boven: een band die alle oceanen verbindt."),
    dict(type="meerkeuze",
         vraag="Waar zinkt het water in de thermohaliene circulatie?",
         opties=["in de koude noordelijke Atlantische Oceaan",
                 "midden in de warme Golf van Mexico",
                 "net boven de evenaar in de Stille Oceaan",
                 "in de ondiepe Middellandse Zee"],
         antwoord=0,
         uitleg="Bij Groenland en IJsland koelt het water af en wordt het door ijsvorming zouter, dus zwaarder. Het zinkt en stroomt in de diepte zuidwaarts weg."),
    dict(type="waarofniet",
         vraag="Water wordt zwaarder als het kouder en zouter wordt.",
         antwoord=True,
         uitleg="Dat is net de motor van de thermohaliene circulatie: koud, zout water zinkt en trekt zo warm oppervlaktewater achter zich aan."),
    dict(type="meerkeuze",
         vraag="Wat zou er met West-Europa gebeuren als de thermohaliene circulatie stilvalt?",
         opties=["het zou er merkelijk kouder worden",
                 "het zou er veel warmer worden dan nu",
                 "er zou niets veranderen aan het klimaat",
                 "de getijden zouden er verdwijnen"],
         antwoord=0,
         uitleg="De aanvoer van warm oppervlaktewater zou wegvallen. Het zou bij ons kouder worden, met strengere winters, hoewel de aarde als geheel opwarmt."),
    dict(type="meerkeuze",
         vraag="Welke gevolgen kan het stilvallen van de thermohaliene circulatie hebben?",
         opties=["koudere winters in West-Europa",
                 "een verschuiving van de regengordels",
                 "minder zuurstof in het diepe water",
                 "het verdwijnen van eb en vloed"],
         antwoord=[0, 1, 2],
         uitleg="De fiche vraagt naar de mogelijke gevolgen: afkoeling bij ons, verschoven regenpatronen en minder diepwaterzuurstof. De getijden hangen van de maan af, niet van de stromen."),
    dict(type="waarofniet",
         vraag="Smeltwater van Groenland maakt het zeewater zouter en versterkt daardoor de circulatie.",
         antwoord=False,
         uitleg="Smeltwater is zoet, dus maakt het het oppervlaktewater lichter. Daardoor zinkt het minder makkelijk en kan de circulatie juist vertragen."),
    dict(type="meerkeuze",
         vraag="Wat drijft de zeestromen aan het oppervlak vooral aan?",
         opties=["de vaste winden boven de oceanen",
                 "de aantrekking van de maan",
                 "de rivieren die in de zee uitmonden",
                 "de warmte van de oceaanbodem"],
         antwoord=0,
         uitleg="De passaten en de westenwinden sleuren het bovenste water mee. Het corioliseffect buigt die stroom af, en zo ontstaan de grote kringen in elke oceaan."),
    dict(type="meerkeuze",
         vraag="In welke zin draaien de grote oceaankringen op het noordelijk halfrond?",
         opties=["met de klok mee", "tegen de klok in",
                 "van noord naar zuid heen en terug", "elke keer in een andere zin"],
         antwoord=0,
         uitleg="Door het corioliseffect buigt het water naar rechts af. Dat levert een kring met de klok mee, en op het zuidelijk halfrond net omgekeerd."),
    dict(type="invultekst",
         vraag="Hoe heet de koude zeestroom langs de kust van Peru en Chili?",
         antwoord=["Humboldtstroom", "de Humboldtstroom", "Humboldt"],
         uitleg="De Humboldtstroom voert koud water noordwaarts. Hij maakt de kust droog, maar levert door opwelling een van de rijkste visgronden ter wereld."),
    dict(type="meerkeuze",
         vraag="Wat is opwelling van zeewater?",
         opties=["koud, voedselrijk diepwater komt naar boven",
                 "warm oppervlaktewater zakt naar de bodem",
                 "zoet rivierwater mengt met het zeewater",
                 "zeewater verdampt sneller door de wind"],
         antwoord=0,
         uitleg="Waait de wind het oppervlaktewater van de kust weg, dan komt er diep water in de plaats. Dat is koud en vol voedingsstoffen, dus zitten daar de grote visscholen."),
    dict(type="waarofniet",
         vraag="Een zeestroom heeft nauwelijks invloed op de temperatuur van de kust erlangs.",
         antwoord=False,
         uitleg="Het verschil kan meerdere graden zijn. Havens in Noorwegen op 60° noorderbreedte blijven ijsvrij, terwijl op dezelfde breedte in Canada de zee dichtvriest."),
    dict(type="meerkeuze",
         vraag="Waarom is het bij ons in de winter zachter dan in Newfoundland, op dezelfde breedte?",
         opties=["de warme drift en de westenwind samen",
                 "wij liggen een stuk hoger boven de zee",
                 "er valt bij ons veel minder neerslag",
                 "de zon staat bij ons hoger aan de hemel"],
         antwoord=0,
         uitleg="Wij liggen aan de loefzijde van de Atlantische Oceaan: de westenwind voert lucht aan die boven de warme drift is opgewarmd. Newfoundland krijgt de koude Labradorstroom."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over zeestromen zijn juist?",
         opties=["ze vervoeren warmte van de evenaar naar de polen",
                 "ze beïnvloeden het klimaat van de kusten",
                 "ze worden afgebogen door het corioliseffect",
                 "ze veroorzaken het getij aan de kust"],
         antwoord=[0, 1, 2],
         uitleg="Zeestromen verplaatsen warmte, bepalen mee het kustklimaat en buigen af door de aardrotatie. Het getij komt van de maan en de zon."),
]
