# -*- coding: utf-8 -*-
"""De zon en ons zonnestelsel.

Uit de vakfiche aardrijkskunde van de 3de graad doorstroomfinaliteit (2027),
onderdeel Het heelal.

Deel 1 is de zon zelf: haar lagen van de kern tot de corona, de zonnevlekken
en protuberansen, de zonnecyclus, de zonnewind en het poollicht.
Deel 2 is de rest van het stelsel: de terrestrische planeten en de gasreuzen,
de dwergplaneten, de planetoïdengordel, de Kuipergordel en de Oortwolk, het
verschil tussen meteoroïde, meteoor en meteoriet, en de kometen.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="In welke laag van de zon komt de energie vrij?",
         opties=["in de kern", "in de corona",
                 "in de fotosfeer, aan het oppervlak", "in de chromosfeer"],
         antwoord=0,
         uitleg="In de kern smelten waterstofkernen samen tot helium. Die kernfusie levert alle energie van de zon."),
    dict(type="meerkeuze",
         vraag="Zet de lagen van de zon van binnen naar buiten. Wat is juist?",
         opties=["kern, stralingszone, convectiezone, fotosfeer",
                 "kern, convectiezone, stralingszone, chromosfeer",
                 "fotosfeer, kern, corona, stralingszone, mantel",
                 "corona, chromosfeer, kern, convectiezone, korst"],
         antwoord=0,
         uitleg="Van binnen naar buiten: kern, stralingszone, convectiezone, fotosfeer, chromosfeer en corona."),
    dict(type="invultekst",
         vraag="Hoe heet de laag van de zon die wij als het zichtbare oppervlak zien?",
         antwoord=["fotosfeer", "de fotosfeer"],
         uitleg="De fotosfeer is de dunne laag waaruit het zonlicht ontsnapt, met een temperatuur van ongeveer 5 500 °C."),
    dict(type="meerkeuze",
         vraag="Waarom zijn zonnevlekken donkerder dan de rest van de fotosfeer?",
         opties=["ze zijn koeler dan hun omgeving",
                 "ze liggen dieper in de zon dan de rest van het oppervlak",
                 "ze bestaan uit stof dat het licht van de zon tegenhoudt",
                 "ze zijn gaten waardoor je in de kern van de zon kijkt"],
         antwoord=0,
         uitleg="In een zonnevlek remt een sterk magneetveld de warmtestroom van beneden af. De vlek is daardoor zo'n 1 500 graden koeler, en dus donkerder."),
    dict(type="meerkeuze",
         vraag="Wat is een protuberans?",
         opties=["een boog van gas boven het zonsoppervlak",
                 "een donkere, koelere plek op het zonsoppervlak",
                 "de stroom deeltjes die de zon de ruimte in blaast",
                 "de buitenste, heel hete gaslaag van de zon"],
         antwoord=0,
         uitleg="Een protuberans is een reusachtige lus gas die langs magnetische veldlijnen boven de fotosfeer hangt. De donkere plek is een zonnevlek, de deeltjesstroom de zonnewind."),
    dict(type="waarofniet",
         vraag="De corona is veel heter dan de fotosfeer, hoewel ze verder van de kern ligt.",
         antwoord=True,
         uitleg="De fotosfeer is ongeveer 5 500 °C, de corona loopt op tot meer dan een miljoen graden. Hoe dat precies kan, is nog altijd niet volledig verklaard."),
    dict(type="invultekst",
         vraag="Hoeveel jaar duurt een zonnecyclus ongeveer? Schrijf enkel het getal.",
         antwoord=["11", "elf"],
         uitleg="Ongeveer elk jaar elf gaat de zonneactiviteit van een minimum naar een maximum en weer terug. Bij een maximum zijn er veel zonnevlekken."),
    dict(type="meerkeuze",
         vraag="Wat is de zonnewind?",
         opties=["een stroom geladen deeltjes die de zon uitzendt",
                 "de wind die op aarde door de warmte van de zon ontstaat",
                 "de beweging van heet gas in de convectiezone van de zon",
                 "de druk van het zonlicht op de staart van een komeet"],
         antwoord=0,
         uitleg="De zonnewind bestaat vooral uit protonen en elektronen die uit de corona ontsnappen en het hele zonnestelsel doorkruisen."),
    dict(type="meerkeuze",
         vraag="Hoe ontstaat het poollicht?",
         opties=["deeltjes van de zon botsen op gas hoog in de atmosfeer",
                 "het ijs van de poolkappen weerkaatst het licht van de maan",
                 "de zon staat in de zomer midden in de nacht boven de horizon",
                 "de magnetische polen van de aarde gloeien op in de winter"],
         antwoord=0,
         uitleg="Het magneetveld van de aarde leidt deeltjes van de zonnewind naar de poolstreken. Daar botsen ze op zuurstof en stikstof, die oplichten."),
    dict(type="waarofniet",
         vraag="Het poollicht is bij een zonneminimum vaker en verder van de polen te zien dan bij een maximum.",
         antwoord=False,
         uitleg="Net omgekeerd. Bij een maximum zijn er meer en sterkere deeltjesstromen, en dan schuift de ovaal met poollicht verder naar lagere breedten."),
    dict(type="meerkeuze",
         vraag="Welke gevolgen kan een sterke zonnestorm op aarde hebben?",
         opties=["storingen in satellieten en radioverkeer",
                 "poollicht dat ook in onze streken te zien is",
                 "spanningspieken in hoogspanningsnetten",
                 "een meetbaar warmere zomer op het noordelijk halfrond"],
         antwoord=[0, 1, 2],
         uitleg="Een zonnestorm verstoort satellieten, radioverkeer en stroomnetten, en levert poollicht tot op lagere breedten. Op het weer of de seizoenen heeft ze geen merkbaar effect."),
    dict(type="meerkeuze",
         vraag="Hoe is de zon ontstaan?",
         opties=["uit een samentrekkende wolk gas en stof",
                 "uit de botsing van twee kleinere, oudere sterren",
                 "uit het materiaal dat van de planeten overbleef",
                 "uit een stuk dat uit het centrum van de Melkweg kwam"],
         antwoord=0,
         uitleg="Een wolk gas en stof trok onder haar eigen zwaartekracht samen. In het hart werd het zo heet en dicht dat de kernfusie begon."),
    dict(type="meerkeuze",
         vraag="Wat bleef er van die wolk over nadat de zon ontstaan was?",
         opties=["een schijf gas en stof waaruit de planeten groeiden",
                 "een bol gas die de zon nu nog helemaal omhult",
                 "niets, de zon slorpte alle materie van de wolk op",
                 "twee kleinere sterren die later uit elkaar gedreven zijn"],
         antwoord=0,
         uitleg="Rond de jonge zon bleef een vlakke schijf over. Daarin klonterde stof samen tot steeds grotere brokken, en zo tot planeten."),
    dict(type="waarofniet",
         vraag="De planeten van ons zonnestelsel draaien allemaal in dezelfde zin rond de zon, en bijna in hetzelfde vlak.",
         antwoord=True,
         uitleg="Dat komt doordat ze alle uit dezelfde platte, draaiende schijf zijn ontstaan. Het is een sterke aanwijzing voor die ontstaanstheorie."),
    dict(type="meerkeuze",
         vraag="Welke verklaring geldt als de beste voor het ontstaan van onze maan?",
         opties=["een grote botsing sloeg materiaal uit de jonge aarde",
                 "de aarde heeft een voorbijtrekkende planetoïde ingevangen",
                 "de maan is samen met de aarde uit twee gelijke wolken gegroeid",
                 "de maan is een afgekoeld stuk van de zon zelf"],
         antwoord=0,
         uitleg="Volgens de inslagtheorie ramde een hemellichaam ter grootte van Mars de jonge aarde. Uit het weggeslagen puin vormde zich de maan."),
    dict(type="invultekst",
         vraag="Hoe heet de donkere, koelere plek op het oppervlak van de zon?",
         antwoord=["zonnevlek", "een zonnevlek", "zonnevlekken"],
         uitleg="Zonnevlekken komen en gaan met de zonnecyclus van elf jaar."),
    dict(type="meerkeuze",
         vraag="Welke lagen horen tot de buitenste atmosfeer van de zon?",
         opties=["de chromosfeer", "de corona", "de fotosfeer",
                 "de convectiezone"],
         antwoord=[0, 1, 2],
         uitleg="De fotosfeer, de chromosfeer en de corona vormen samen de buitenkant van de zon. De convectiezone ligt daaronder."),
    dict(type="waarofniet",
         vraag="Je kan de corona van de zon op elk moment van de dag met het blote oog zien.",
         antwoord=False,
         uitleg="De fotosfeer is zoveel helderder dat de corona wegvalt. Ze is alleen te zien tijdens een totale zonsverduistering, of met een speciaal instrument."),
    dict(type="meerkeuze",
         vraag="Hoe ontstonden de eerste geosfeer en atmosfeer van de aarde?",
         opties=["de aarde viel in lagen uiteen en gassen ontsnapten",
                 "de aarde kreeg haar korst en lucht kant-en-klaar van de zon mee",
                 "een komeet bracht in één inslag de hele korst en atmosfeer aan",
                 "de atmosfeer ontstond eerst, en de geosfeer veel later daaruit"],
         antwoord=0,
         uitleg="In de hete, jonge aarde zonken de zware stoffen naar het centrum en bleven de lichte boven: zo kwamen kern, mantel en korst. Vulkanisme blies waterdamp en gassen naar buiten, en dat werd de eerste atmosfeer."),
    dict(type="meerkeuze",
         vraag="Welke stoffen zaten in de eerste atmosfeer van de aarde?",
         opties=["waterdamp", "koolstofdioxide", "stikstof", "veel vrije zuurstof"],
         antwoord=[0, 1, 2],
         uitleg="Vulkanisme blies vooral waterdamp, koolstofdioxide en stikstof naar buiten. Vrije zuurstof kwam er pas veel later bij, door de fotosynthese."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Welke planeten zijn terrestrische planeten?",
         opties=["Mercurius", "Venus", "Mars", "Saturnus"],
         antwoord=[0, 1, 2],
         uitleg="De terrestrische of aardse planeten zijn Mercurius, Venus, de aarde en Mars: klein, rotsachtig en dicht bij de zon. Saturnus is een gasreus."),
    dict(type="meerkeuze",
         vraag="Wat kenmerkt de gasreuzen?",
         opties=["ze zijn groot en hebben geen vast oppervlak",
                 "ze liggen alle vier binnen de baan van de aarde",
                 "ze zijn kleiner en zwaarder dan de aardse planeten",
                 "ze hebben geen enkele maan die rond hen draait"],
         antwoord=0,
         uitleg="Jupiter, Saturnus, Uranus en Neptunus zijn veel groter dan de aarde, bestaan vooral uit gas en hebben elk een hele reeks manen."),
    dict(type="invultekst",
         vraag="Hoeveel planeten telt ons zonnestelsel? Schrijf het cijfer.",
         antwoord=["8", "acht"],
         uitleg="Acht: Mercurius, Venus, aarde, Mars, Jupiter, Saturnus, Uranus en Neptunus. Pluto geldt sinds 2006 als dwergplaneet."),
    dict(type="meerkeuze",
         vraag="Waar ligt de planetoïdengordel?",
         opties=["tussen Mars en Jupiter", "tussen de aarde en Mars",
                 "net buiten de baan van Neptunus", "tussen Mercurius en de zon"],
         antwoord=0,
         uitleg="De planetoïdengordel ligt tussen Mars en Jupiter. De zwaartekracht van Jupiter verhinderde dat daar ooit een planeet kon groeien."),
    dict(type="meerkeuze",
         vraag="Waar ligt de Kuipergordel?",
         opties=["voorbij de baan van Neptunus",
                 "net binnen de baan van Jupiter",
                 "tussen de aarde en de maan in",
                 "in het binnenste van de Oortwolk zelf"],
         antwoord=0,
         uitleg="De Kuipergordel is een ring van ijzige brokstukken voorbij Neptunus, met onder meer Pluto erin."),
    dict(type="waarofniet",
         vraag="De Oortwolk is een platte ring en ligt dichter bij de zon dan de Kuipergordel.",
         antwoord=False,
         uitleg="De Oortwolk is een bolvormige schil, en ze ligt duizenden keren verder dan de Kuipergordel. Ze is de bron van de kometen met heel lange omlooptijden."),
    dict(type="invultekst",
         vraag="Hoe noemen we een hemellichaam dat te klein is om een planeet te heten maar wel bolvormig is, zoals Pluto?",
         antwoord=["dwergplaneet", "een dwergplaneet", "dwergplaneten"],
         uitleg="Een dwergplaneet draait rond de zon en is bolvormig, maar heeft haar baan niet vrijgemaakt van ander puin. Pluto, Ceres en Eris zijn dwergplaneten."),
    dict(type="meerkeuze",
         vraag="Een brokstuk vliegt nog in de ruimte rond. Hoe heet het dan?",
         opties=["een meteoroïde", "een meteoor", "een meteoriet", "een komeet"],
         antwoord=0,
         uitleg="In de ruimte is het een meteoroïde, het lichtspoor in de atmosfeer is een meteoor, en wat de grond haalt is een meteoriet."),
    dict(type="meerkeuze",
         vraag="Je ziet 's nachts een vallende ster. Wat zie je eigenlijk?",
         opties=["een meteoor", "een meteoriet", "een komeet", "een planetoïde"],
         antwoord=0,
         uitleg="Een meteoor is het lichtspoor dat een brokstukje maakt terwijl het door de wrijving in de atmosfeer gloeiend heet wordt en verdampt."),
    dict(type="invultekst",
         vraag="Hoe heet een brokstuk uit de ruimte dat het aardoppervlak bereikt?",
         antwoord=["meteoriet", "een meteoriet", "meteorieten"],
         uitleg="Alleen het stuk dat de tocht door de atmosfeer overleeft en de grond raakt, heet een meteoriet."),
    dict(type="meerkeuze",
         vraag="Waaruit bestaat de kern van een komeet?",
         opties=["uit ijs, stof en steen", "uit vloeibaar gesteente",
                 "uit samengeperst zuiver ijzer", "uit gas zonder vaste deeltjes"],
         antwoord=0,
         uitleg="Een komeetkern is een vuile sneeuwbal: waterijs en bevroren gassen met stof en steen erdoor."),
    dict(type="meerkeuze",
         vraag="Wat gebeurt er met een komeet als ze de zon nadert?",
         opties=["er vormt zich een coma en een staart",
                 "ze koelt af en haar staart trekt zich helemaal in",
                 "ze valt onderweg in twee gelijke helften uiteen",
                 "ze wordt zwaarder door al het stof dat ze opveegt"],
         antwoord=0,
         uitleg="Door de warmte gaat het ijs rechtstreeks over in gas. Dat gas en het meegesleurde stof vormen een wolk rond de kern, de coma, en een lange staart."),
    dict(type="waarofniet",
         vraag="De staart van een komeet wijst altijd weg van de zon, ook als de komeet van de zon weg beweegt.",
         antwoord=True,
         uitleg="De zonnewind en de stralingsdruk blazen de staart weg van de zon. Op de terugweg loopt de komeet dus met haar staart vooruit."),
    dict(type="meerkeuze",
         vraag="Welke delen hoort een komeet te hebben als ze dicht bij de zon staat?",
         opties=["een kern", "een coma", "een staart", "een korst van basalt"],
         antwoord=[0, 1, 2],
         uitleg="De kern van ijs en stof, de coma eromheen en één of meer staarten. Basalt is een vulkanisch gesteente op aarde."),
    dict(type="waarofniet",
         vraag="Een komeet legt een sterk uitgerekte, elliptische baan af, geen cirkel zoals de planeten.",
         antwoord=True,
         uitleg="Daardoor komt ze soms heel dicht bij de zon, waar ze haar staart krijgt, en gaat ze daarna weer heel ver weg."),
    dict(type="meerkeuze",
         vraag="Welke planeet staat het verst van de zon?",
         opties=["Neptunus", "Uranus", "Saturnus", "Pluto"],
         antwoord=0,
         uitleg="Neptunus is de buitenste planeet. Pluto staat verder, maar is sinds 2006 een dwergplaneet."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over manen zijn juist?",
         opties=["een maan draait rond een planeet",
                 "de gasreuzen hebben er elk meerdere",
                 "Mercurius en Venus hebben er geen",
                 "elke maan heeft zelf ook een maan"],
         antwoord=[0, 1, 2],
         uitleg="Manen draaien rond planeten, de gasreuzen hebben er tientallen, en Mercurius en Venus hebben er geen enkele. Manen van manen kennen we niet."),
    dict(type="invultekst",
         vraag="Hoe heet de grootste planeet van ons zonnestelsel?",
         antwoord=["Jupiter"],
         uitleg="Jupiter heeft een doorsnede van ruim elf keer die van de aarde en weegt meer dan alle andere planeten samen."),
    dict(type="waarofniet",
         vraag="Een planetoïde en een dwergplaneet zijn precies hetzelfde.",
         antwoord=False,
         uitleg="Een dwergplaneet is door haar eigen zwaartekracht bolvormig geworden. Een planetoïde is kleiner en houdt een onregelmatige vorm."),
    dict(type="meerkeuze",
         vraag="Waarom zien we elk jaar rond dezelfde datum een zwerm vallende sterren?",
         opties=["de aarde kruist dan het stofspoor van een komeet",
                 "de zon stoot dan meer deeltjes de ruimte in",
                 "de maan staat dan tussen de aarde en de zon",
                 "de planetoïdengordel komt dan dichter bij de aarde"],
         antwoord=0,
         uitleg="Een komeet laat stof achter langs haar baan. Elk jaar op hetzelfde punt rijdt de aarde door die wolk, en dan branden veel deeltjes samen op."),
]
