# -*- coding: utf-8 -*-
"""Naamwoorden, lidwoorden, hoeveelheden en telwoorden.

Uit de grammaticalijst van de vakfiche Engels 1 van de 3de graad
doorstroomfinaliteit (2027): zelfstandige naamwoorden met hun getal, de
bezitsvormen, de bepaalde en onbepaalde lidwoorden, de quantifiers (much,
many, a lot, very) en de hoofd- en rangtelwoorden.

Deel 1 is het naamwoord zelf: meervoud, telbaar of niet, en de bezitsvorm.
Deel 2 zijn de lidwoorden, de hoeveelheden en de telwoorden.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is het meervoud van child?",
         opties=["children",
                 "childs",
                 "childes",
                 "childrens"],
         antwoord=0,
         uitleg="Children is een onregelmatig meervoud. Het heeft al een meervoudsvorm, dus childrens bestaat niet."),
    dict(type="meerkeuze",
         vraag="Wat is het meervoud van woman?",
         opties=["women",
                 "womans",
                 "womens",
                 "womanes"],
         antwoord=0,
         uitleg="Woman wordt women, man wordt men. Je hoort het verschil vooral in de eerste klinker."),
    dict(type="invultekst",
         vraag="Vul het meervoud in: one knife, two ___.",
         antwoord=["knives"],
         uitleg="Knife wordt knives: de f wordt een v. Zo ook life, wife, leaf en shelf."),
    dict(type="meerkeuze",
         vraag="Welke woorden hebben een onregelmatig meervoud?",
         opties=["foot",
                 "tooth",
                 "mouse",
                 "book"],
         antwoord=[0, 1, 2],
         uitleg="Feet, teeth en mice. Book wordt gewoon books."),
    dict(type="waarofniet",
         vraag="Information is in het Engels ontelbaar: je zegt nooit informations.",
         antwoord=True,
         uitleg="Information, advice, furniture, luggage en news zijn ontelbaar. Je zegt a piece of information."),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: « He gave me a good ___ »?",
         opties=["piece of advice",
                 "advices about it",
                 "advice tips for me",
                 "advisement on the matter"],
         antwoord=0,
         uitleg="Advice is ontelbaar, dus a piece of advice. Het werkwoord is to advise, met een s die als z klinkt."),
    dict(type="meerkeuze",
         vraag="Welke woorden staan in het Engels altijd in het meervoud?",
         opties=["scissors",
                 "trousers",
                 "glasses",
                 "luggage"],
         antwoord=[0, 1, 2],
         uitleg="Een schaar, een broek en een bril zijn in het Engels meervoud: a pair of scissors. Luggage is juist ontelbaar enkelvoud."),
    dict(type="invultekst",
         vraag="Vul de bezitsvorm in: the car of my brother wordt my ___ car.",
         antwoord=["brother's"],
         uitleg="De bezitsvorm van een enkelvoud krijgt 's: my brother's car. Bij een meervoud op s komt de apostrof erachter."),
    dict(type="meerkeuze",
         vraag="Welke bezitsvormen zijn juist geschreven?",
         opties=["the boy's bike",
                 "the boys' bikes",
                 "the children's room",
                 "the childrens' room"],
         antwoord=[0, 1, 2],
         uitleg="Eén jongen krijgt 's, meerdere jongens een apostrof achter de s, en children krijgt 's omdat het al meervoud is."),
    dict(type="waarofniet",
         vraag="Bij een meervoud dat al op een s eindigt, zet je de apostrof na die s: the teachers' room.",
         antwoord=True,
         uitleg="The teachers' room is de kamer van de leraren. The teacher's room is de kamer van één leraar."),
    dict(type="meerkeuze",
         vraag="Welke vorm gebruik je voor het bezit van een ding: het dak van het huis?",
         opties=["the roof of the house",
                 "the house's roof",
                 "the house roof's",
                 "the roof's house"],
         antwoord=0,
         uitleg="Bij dingen gebruik je of. De vorm met 's hou je voor mensen, dieren, landen en tijdsbepalingen."),
    dict(type="meerkeuze",
         vraag="Wat betekent a ten-minute walk?",
         opties=["een wandeling van tien minuten",
                 "een wandeling van tien kilometer",
                 "tien wandelingen van een minuut",
                 "een wandeling om tien uur"],
         antwoord=0,
         uitleg="In zo'n samenstelling blijft minute enkelvoud: a ten-minute walk, a five-year plan. Het streepje hoort erbij."),
    dict(type="invultekst",
         vraag="Vul het meervoud in: one person, two ___ (het gewone woord, niet persons).",
         antwoord=["people"],
         uitleg="People is het gewone meervoud van person. Persons hoor je enkel in juridische taal."),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: « The news ___ good »?",
         opties=["is",
                 "are",
                 "were",
                 "have been"],
         antwoord=0,
         uitleg="News eindigt op een s maar is enkelvoud: the news is good. Datzelfde geldt voor mathematics en physics."),
    dict(type="waarofniet",
         vraag="Het woord sheep krijgt in het meervoud een s: two sheeps.",
         antwoord=False,
         uitleg="Het blijft sheep: one sheep, two sheep. Zo ook fish, deer, aircraft en species."),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: « My hair ___ too long »?",
         opties=["is",
                 "are",
                 "were",
                 "have grown"],
         antwoord=0,
         uitleg="Hair is ontelbaar als het over het hele hoofd gaat: my hair is too long. Eén haar is a hair."),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: « The police ___ already arrived »?",
         opties=["have",
                 "has",
                 "is",
                 "was"],
         antwoord=0,
         uitleg="Police is meervoud in het Engels: the police have arrived. Eén agent is a police officer."),
    dict(type="waarofniet",
         vraag="Het meervoud van potato is potatos.",
         antwoord=False,
         uitleg="Het is potatoes, met een e. Zo ook tomatoes en heroes, maar photos en pianos krijgen die e niet."),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: « I bought two ___ of trousers »?",
         opties=["pairs",
                 "pair",
                 "pieces",
                 "couples"],
         antwoord=0,
         uitleg="Two pairs of trousers zijn twee broeken. Bij scissors, glasses en jeans gaat het net zo."),
    dict(type="meerkeuze",
         vraag="Wat is het meervoud van analysis?",
         opties=["analyses",
                 "analysises",
                 "analysis",
                 "analysisses"],
         antwoord=0,
         uitleg="Woorden op -is krijgen -es: analysis wordt analyses, crisis wordt crises, basis wordt bases."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: « She is ___ engineer »?",
         opties=["an",
                 "a",
                 "the one",
                 "some kind of"],
         antwoord=0,
         uitleg="An komt voor een klinkerklank: an engineer, an hour, an MP. A komt voor een consonantklank, ook voor a university."),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: « He plays ___ piano »?",
         opties=["the",
                 "a",
                 "an",
                 "some"],
         antwoord=0,
         uitleg="Bij een muziekinstrument staat the: to play the piano, the guitar. Bij een sport staat er geen lidwoord: to play football."),
    dict(type="invultekst",
         vraag="Vul in: « I go to school by ___ » (het vervoermiddel bus, zonder lidwoord erbij).",
         antwoord=["bus"],
         uitleg="By bus, by train, by car: geen lidwoord na by. Enkel to go on foot valt uit de rij."),
    dict(type="meerkeuze",
         vraag="In welke zinnen hoort er géén lidwoord?",
         opties=["I like ___ music.",
                 "She is at ___ school.",
                 "We had ___ lunch at one.",
                 "I saw ___ film you mentioned."],
         antwoord=[0, 1, 2],
         uitleg="Bij een algemeen begrip, bij school of work en bij de maaltijden staat er niets. In de laatste zin hoort the, want het is een bepaalde film."),
    dict(type="waarofniet",
         vraag="Voor a university staat a en niet an, hoewel het met een u begint.",
         antwoord=True,
         uitleg="Het gaat om de klank, niet om de letter: university begint met een j-klank. Daarom a university, maar an umbrella."),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: « How ___ money do you need »?",
         opties=["much",
                 "many",
                 "a lot",
                 "a number of"],
         antwoord=0,
         uitleg="Much bij ontelbare woorden, many bij telbare. Money is ontelbaar, dus how much money."),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: « There are too ___ cars in the city »?",
         opties=["many",
                 "much",
                 "a lot",
                 "a great deal of"],
         antwoord=0,
         uitleg="Cars is telbaar, dus too many cars. Too much traffic zou wel kloppen, want traffic is ontelbaar."),
    dict(type="invultekst",
         vraag="Vul in: « I have very ___ time left » (weinig, bij een ontelbaar woord).",
         antwoord=["little"],
         uitleg="Little bij ontelbaar, few bij telbaar: little time, few friends. A little en a few betekenen juist wel wat."),
    dict(type="meerkeuze",
         vraag="Welke woorden horen bij een telbaar naamwoord?",
         opties=["many",
                 "few",
                 "several",
                 "much"],
         antwoord=[0, 1, 2],
         uitleg="Many, few, several en a number of gaan met telbare woorden. Much hoort bij ontelbare."),
    dict(type="waarofniet",
         vraag="Er is geen verschil tussen few friends en a few friends.",
         antwoord=False,
         uitleg="Few friends is weinig vrienden, bijna geen. A few friends is enkele vrienden, en dat klinkt positief."),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: « Is there ___ milk left »?",
         opties=["any",
                 "some one",
                 "a few",
                 "a number of"],
         antwoord=0,
         uitleg="Any in een vraag en in een ontkenning, some in een gewone bevestiging. Bij een aanbod hoor je wel some: Would you like some tea?"),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: « He is the ___ person in the queue »?",
         opties=["third",
                 "three",
                 "threeth",
                 "thirdth"],
         antwoord=0,
         uitleg="Third is het rangtelwoord bij three. One, two, three worden first, second, third."),
    dict(type="invultekst",
         vraag="Schrijf het rangtelwoord bij twelve, in letters.",
         antwoord=["twelfth"],
         uitleg="Twelfth, met een f. Five wordt fifth, twelve wordt twelfth, twenty wordt twentieth."),
    dict(type="meerkeuze",
         vraag="Hoe lees je 1,500 in het Engels?",
         opties=["one thousand five hundred",
                 "one point five",
                 "fifteen hundredths of a unit",
                 "one and a half"],
         antwoord=0,
         uitleg="De komma scheidt in het Engels de duizenden, niet de decimalen. Anderhalf schrijf je 1.5, met een punt."),
    dict(type="waarofniet",
         vraag="Hundred, thousand en million blijven enkelvoud na een getal: two hundred people.",
         antwoord=True,
         uitleg="Two hundred, three thousand, four million. Zonder getal krijgen ze wel een s: hundreds of people."),
    dict(type="meerkeuze",
         vraag="Hoe zeg je de datum 3 mei in Brits Engels?",
         opties=["the third of May",
                 "the three of May",
                 "May the three",
                 "the May third day"],
         antwoord=0,
         uitleg="Brits Engels zegt the third of May, Amerikaans May third. Je schrijft 3 May of May 3."),
    dict(type="meerkeuze",
         vraag="Welke uitdrukkingen zeggen dat er veel van iets is?",
         opties=["a lot of",
                 "plenty of",
                 "a great deal of",
                 "hardly any"],
         antwoord=[0, 1, 2],
         uitleg="A lot of en plenty of gaan met beide soorten, a great deal of enkel met ontelbare. Hardly any is bijna niets."),
    dict(type="waarofniet",
         vraag="Je zegt the France om over het land te spreken.",
         antwoord=False,
         uitleg="Bij een landnaam staat er geen lidwoord: France, Belgium, England. Enkel een meervoud of een staatsvorm krijgt the: the Netherlands, the United Kingdom."),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: « She has ___ interesting job »?",
         opties=["an",
                 "a",
                 "the",
                 "some"],
         antwoord=0,
         uitleg="Het lidwoord hoort bij de eerste klank van wat erna komt. Interesting begint met een klinker, dus an interesting job."),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: « I have been waiting for ___ an hour »?",
         opties=["half",
                 "a half",
                 "the half",
                 "one half of"],
         antwoord=0,
         uitleg="Half an hour is een half uur, met het lidwoord na half. Een kwartier is a quarter of an hour."),
]
