# -*- coding: utf-8 -*-
"""Woorden voor kunst, literatuur, politiek en reizen.

Uit de woordenschatthema's van de vakfiche Engels 1 van de 3de graad
doorstroomfinaliteit (2027): kunst, cultuur en geschiedenis, literatuur,
politiek en maatschappij, reizen en landen. De fiche van Engels 2 vraagt
daarnaast dat je een literaire tekst kan beleven en erover kan schrijven.

Deel 1 is kunst, cultuur, geschiedenis en literatuur.
Deel 2 is politiek, maatschappij, reizen en landen.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is a novel?",
         opties=["een roman",
                 "een kort verhaal",
                 "een toneelstuk",
                 "een gedichtenbundel"],
         antwoord=0,
         uitleg="A novel is een roman. Een kort verhaal is a short story, en nieuw is het bijvoeglijke novel."),
    dict(type="meerkeuze",
         vraag="Welke soorten teksten schreef Shakespeare?",
         opties=["plays",
                 "sonnets",
                 "poems",
                 "novels"],
         antwoord=[0, 1, 2],
         uitleg="Toneelstukken, sonnetten en lange gedichten. De roman bestond in zijn tijd nog niet in die vorm, en a playwright is de toneelauteur."),
    dict(type="invultekst",
         vraag="Welk Engels woord betekent hoofdpersoon van een verhaal, en begint met een p? Eén woord.",
         antwoord=["protagonist"],
         uitleg="The protagonist is de hoofdpersoon. De tegenspeler is the antagonist, en alle personages samen zijn the characters."),
    dict(type="meerkeuze",
         vraag="Welke woorden benoemen een deel van een boek?",
         opties=["a chapter",
                 "a preface",
                 "an epilogue",
                 "a chorus"],
         antwoord=[0, 1, 2],
         uitleg="Een hoofdstuk, een voorwoord en een naschrift. A chorus is het refrein van een lied of het koor in een theater."),
    dict(type="waarofniet",
         vraag="The plot van een verhaal is de opeenvolging van wat er gebeurt.",
         antwoord=True,
         uitleg="The plot is de verhaallijn. The setting is waar en wanneer het speelt, en the theme is waarover het eigenlijk gaat."),
    dict(type="meerkeuze",
         vraag="Wat betekent the setting of a story?",
         opties=["waar en wanneer het speelt",
                 "wie het verhaal vertelt",
                 "waarover het verhaal gaat",
                 "hoe het verhaal eindigt"],
         antwoord=0,
         uitleg="The setting is de plaats en de tijd. Wie het vertelt is the narrator."),
    dict(type="meerkeuze",
         vraag="Wat is a narrator?",
         opties=["de verteller",
                 "de schrijver zelf",
                 "de hoofdpersoon",
                 "de uitgever van het boek"],
         antwoord=0,
         uitleg="The narrator is de stem die vertelt, en die is niet dezelfde als de schrijver. Een ik-verteller is a first-person narrator."),
    dict(type="invultekst",
         vraag="Welk Engels woord betekent gedicht? Eén woord.",
         antwoord=["poem"],
         uitleg="A poem, de dichter is a poet en de dichtkunst is poetry. Let op het verschil tussen poem en poet."),
    dict(type="meerkeuze",
         vraag="Welke woorden hoor je in een museum?",
         opties=["an exhibition",
                 "a guided tour",
                 "an audio guide",
                 "a fortnight"],
         antwoord=[0, 1, 2],
         uitleg="Een tentoonstelling, een rondleiding en een audiogids. A fortnight zijn twee weken."),
    dict(type="waarofniet",
         vraag="A library is in het Engels een boekwinkel.",
         antwoord=False,
         uitleg="A library is een bibliotheek, en een boekwinkel is a bookshop of a bookstore. Het is een klassieke valse vriend."),
    dict(type="meerkeuze",
         vraag="Wat betekent the book is set in Victorian London?",
         opties=["het boek speelt in Victoriaans Londen",
                 "het boek is in Londen uitgegeven",
                 "het boek is in Londen gekocht",
                 "het boek gaat over koningin Victoria"],
         antwoord=0,
         uitleg="To be set in is zich afspelen in. De Victoriaanse tijd is de regering van koningin Victoria, van 1837 tot 1901."),
    dict(type="meerkeuze",
         vraag="Wat is a sonnet?",
         opties=["een gedicht van veertien regels",
                 "een lied met een refrein",
                 "een verhaal in verzen",
                 "een korte scène in een toneelstuk"],
         antwoord=0,
         uitleg="Een sonnet heeft veertien regels. Shakespeare schreef er honderdvierenvijftig."),
    dict(type="invultekst",
         vraag="Welk Engels woord betekent eeuw? Eén woord.",
         antwoord=["century"],
         uitleg="A century. The nineteenth century is de negentiende eeuw, dus de jaren 1800."),
    dict(type="meerkeuze",
         vraag="Wat betekent an award-winning film?",
         opties=["een bekroonde film",
                 "een film met veel volk",
                 "een film van een grote studio",
                 "een film die net uitgekomen is"],
         antwoord=0,
         uitleg="An award is een prijs, dus award-winning is bekroond. De uitreiking heet the awards ceremony."),
    dict(type="waarofniet",
         vraag="A review is een stuk waarin iemand een boek of film beoordeelt.",
         antwoord=True,
         uitleg="A review is een recensie, en a reviewer of a critic schrijft ze. To review is beoordelen of herzien."),
    dict(type="meerkeuze",
         vraag="Wat is heritage?",
         opties=["erfgoed",
                 "een erfenis in geld",
                 "een koninklijke titel",
                 "een gebouw van de staat"],
         antwoord=0,
         uitleg="Heritage is erfgoed: gebouwen, tradities, taal. Een erfenis in geld is an inheritance."),
    dict(type="meerkeuze",
         vraag="Wat betekent the Middle Ages?",
         opties=["de middeleeuwen",
                 "de middelbare leeftijd",
                 "de oudheid",
                 "de nieuwe tijd"],
         antwoord=0,
         uitleg="The Middle Ages zijn de middeleeuwen, met een hoofdletter en in het meervoud. De middelbare leeftijd is middle age."),
    dict(type="waarofniet",
         vraag="Het woord work is in het Engels altijd ontelbaar, ook als het over de werken van een schrijver gaat.",
         antwoord=False,
         uitleg="The works of Dickens zijn zijn werken: daar is work wel telbaar. Werk in de zin van arbeid blijft ontelbaar."),
    dict(type="meerkeuze",
         vraag="Wat betekent the novel was adapted for the screen?",
         opties=["het boek werd verfilmd",
                 "het boek werd herschreven",
                 "het boek werd opnieuw uitgegeven",
                 "het boek werd vertaald naar het Engels"],
         antwoord=0,
         uitleg="An adaptation is een bewerking, en the screen is het witte doek. To adapt is aanpassen of bewerken."),
    dict(type="meerkeuze",
         vraag="Wat is a quotation?",
         opties=["een citaat",
                 "een samenvatting",
                 "een voetnoot",
                 "een titel van een kapittel"],
         antwoord=0,
         uitleg="A quotation of a quote is een citaat, letterlijk overgenomen woorden. To quote is citeren."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is the Prime Minister?",
         opties=["de eerste minister",
                 "de koning van het land",
                 "de voorzitter van het parlement",
                 "de burgemeester van de hoofdstad"],
         antwoord=0,
         uitleg="The Prime Minister is de eerste minister, de regeringsleider in het Verenigd Koninkrijk. Het staatshoofd is the monarch."),
    dict(type="meerkeuze",
         vraag="Wat is an MP in Groot-Brittannië?",
         opties=["een parlementslid",
                 "een minister in de regering",
                 "een ambtenaar van een ministerie",
                 "een lid van een gemeenteraad"],
         antwoord=0,
         uitleg="MP staat voor Member of Parliament, een lid van het House of Commons. Een minister is a minister of a secretary of state."),
    dict(type="invultekst",
         vraag="Welk Engels woord betekent verkiezing? Eén woord.",
         antwoord=["election"],
         uitleg="An election. To elect is verkiezen, en een stem is a vote."),
    dict(type="meerkeuze",
         vraag="Welke woorden hoor je bij verkiezingen?",
         opties=["a ballot",
                 "a turnout",
                 "a candidate",
                 "a headline"],
         antwoord=[0, 1, 2],
         uitleg="Een stembiljet, de opkomst en een kandidaat. A headline is een krantenkop."),
    dict(type="waarofniet",
         vraag="Het Britse parlement bestaat uit het House of Commons en het House of Lords.",
         antwoord=True,
         uitleg="Het House of Commons wordt verkozen, het House of Lords niet. Samen vormen ze het parlement in Westminster."),
    dict(type="meerkeuze",
         vraag="Wat betekent to go on strike?",
         opties=["gaan staken",
                 "een eis op tafel leggen",
                 "een vergadering beleggen",
                 "een klacht indienen bij de baas"],
         antwoord=0,
         uitleg="A strike is een staking, to go on strike is gaan staken. Een vakbond is a trade union."),
    dict(type="meerkeuze",
         vraag="Wat is a charity?",
         opties=["een goed doel",
                 "een belasting voor de armen",
                 "een gift van de overheid",
                 "een vereniging van gemeenten"],
         antwoord=0,
         uitleg="A charity is een organisatie voor een goed doel. A charity shop is een tweedehandswinkel die het geld daaraan geeft."),
    dict(type="invultekst",
         vraag="Welk Engels woord betekent armoede? Eén woord.",
         antwoord=["poverty"],
         uitleg="Poverty, van poor. Rijkdom is wealth, en ongelijkheid is inequality."),
    dict(type="meerkeuze",
         vraag="Welke woorden gaan over de samenleving?",
         opties=["equality",
                 "discrimination",
                 "integration",
                 "a timetable"],
         antwoord=[0, 1, 2],
         uitleg="Gelijkheid, discriminatie en integratie. A timetable is een uurrooster."),
    dict(type="waarofniet",
         vraag="A refugee is iemand die zijn land verlaten heeft uit vrije keuze, om te reizen.",
         antwoord=False,
         uitleg="A refugee is een vluchteling, iemand die moest vluchten. Wie uit vrije keuze verhuist, is a migrant of an expat."),
    dict(type="meerkeuze",
         vraag="Wat betekent to raise awareness?",
         opties=["mensen bewust maken",
                 "geld inzamelen",
                 "een wet laten aanpassen",
                 "een onderzoek laten uitvoeren"],
         antwoord=0,
         uitleg="Awareness is bewustzijn, to raise awareness is aandacht vragen voor iets. Geld inzamelen is to raise funds."),
    dict(type="meerkeuze",
         vraag="Wat is a bill in het parlement?",
         opties=["een wetsontwerp",
                 "een goedgekeurde wet",
                 "een verslag van een debat",
                 "een vraag aan een minister"],
         antwoord=0,
         uitleg="A bill is een wetsontwerp, en zodra het goedgekeurd is heet het an act. Datzelfde woord bill is ook een rekening."),
    dict(type="invultekst",
         vraag="Welk Engels woord betekent grens tussen twee landen? Eén woord.",
         antwoord=["border", "frontier"],
         uitleg="A border, en a frontier kan ook. De douane is customs, altijd met een s."),
    dict(type="meerkeuze",
         vraag="Wat betekent to go abroad?",
         opties=["naar het buitenland gaan",
                 "een reis boeken bij een kantoor",
                 "aan de kust gaan wonen",
                 "met het vliegtuig reizen"],
         antwoord=0,
         uitleg="Abroad is in of naar het buitenland, zonder voorzetsel: to live abroad. Aan boord is aboard, met één a."),
    dict(type="waarofniet",
         vraag="Great Britain en the United Kingdom betekenen precies hetzelfde.",
         antwoord=False,
         uitleg="Great Britain is het eiland met Engeland, Schotland en Wales. The United Kingdom telt Noord-Ierland erbij."),
    dict(type="meerkeuze",
         vraag="Welke landen horen bij het Verenigd Koninkrijk?",
         opties=["England",
                 "Scotland",
                 "Wales",
                 "the Republic of Ireland"],
         antwoord=[0, 1, 2],
         uitleg="Engeland, Schotland, Wales en Noord-Ierland. De Republiek Ierland is een apart land."),
    dict(type="meerkeuze",
         vraag="Wat is a bank holiday?",
         opties=["een wettelijke feestdag",
                 "een dag zonder bankverrichtingen",
                 "een vakantiedag van een werknemer",
                 "een dag waarop een bank sluit"],
         antwoord=0,
         uitleg="A bank holiday is in het Verenigd Koninkrijk een officiële feestdag, waarop ook de banken dicht zijn."),
    dict(type="waarofniet",
         vraag="To book a room betekent een kamer reserveren.",
         antwoord=True,
         uitleg="To book is reserveren of boeken, en a booking is de reservatie. Een boek is ook a book."),
    dict(type="meerkeuze",
         vraag="Wat betekent the hotel is fully booked?",
         opties=["het hotel is volzet",
                 "het hotel is net geopend",
                 "het hotel is helemaal verbouwd",
                 "het hotel is gesloten voor het seizoen"],
         antwoord=0,
         uitleg="Fully booked is volledig volgeboekt. Een kamer vrij hebben is to have a vacancy."),
    dict(type="meerkeuze",
         vraag="Wat is a sightseeing tour?",
         opties=["een stadsbezoek",
                 "een wandeling in de natuur",
                 "een reis met een reisgroep",
                 "een bezoek aan een museum"],
         antwoord=0,
         uitleg="Sightseeing is de bezienswaardigheden bekijken. The sights zijn die bezienswaardigheden zelf."),
]
