# -*- coding: utf-8 -*-
"""Voornaamwoorden en betrekkelijke bijzinnen.

Uit de grammaticalijst van de vakfiche Engels 1 van de 3de graad
doorstroomfinaliteit (2027): persoonlijke, aanwijzende, bezittelijke,
vragende, betrekkelijke, onbepaalde en wederkerende voornaamwoorden, en de
relative clauses met that, who, whose, which, when, where en why.

De fiche zegt er uitdrukkelijk bij waarom: persoonlijke voornaamwoorden
verwijzen naar wat in een vorige zin stond, en zonder dat je weet waarnaar,
begrijp je de samenhang van een tekst niet.

Deel 1 zijn de voornaamwoorden zelf.
Deel 2 zijn de vragende voornaamwoorden en de betrekkelijke bijzinnen.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: « ___ gave the book to me »?",
         opties=["She",
                 "Her",
                 "Hers",
                 "Herself"],
         antwoord=0,
         uitleg="Als onderwerp staat she. Her is het lijdend of meewerkend voorwerp: I gave the book to her."),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: « My parents sent ___ a card »?",
         opties=["us",
                 "we",
                 "ours",
                 "ourselves"],
         antwoord=0,
         uitleg="Us is de voorwerpsvorm bij we. Daarom they sent us a card, en niet they sent we."),
    dict(type="invultekst",
         vraag="Vul het bezittelijke voornaamwoord in: « This bike is not mine, it is ___ » (van hem).",
         antwoord=["his"],
         uitleg="His is zowel mijn bezittelijke bepaling als mijn bezittelijk voornaamwoord: his bike, it is his."),
    dict(type="meerkeuze",
         vraag="Welke vormen zijn bezittelijke voornaamwoorden die alleen staan?",
         opties=["mine",
                 "yours",
                 "theirs",
                 "their"],
         antwoord=[0, 1, 2],
         uitleg="Mine, yours, his, hers, ours en theirs staan alleen. Their hoort altijd bij een naamwoord: their house."),
    dict(type="waarofniet",
         vraag="Je schrijft het bezittelijke its zonder apostrof.",
         antwoord=True,
         uitleg="Its betekent zijn of haar: the dog wagged its tail. It's met apostrof is it is of it has."),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: « He hurt ___ while cooking »?",
         opties=["himself",
                 "him",
                 "his",
                 "he"],
         antwoord=0,
         uitleg="Als de dader en het voorwerp dezelfde zijn, staat er een wederkerend voornaamwoord: himself. Zo ook myself, yourself en themselves."),
    dict(type="meerkeuze",
         vraag="Wat betekent I did it myself?",
         opties=["ik deed het zelf",
                 "ik deed het alleen",
                 "ik deed het voor mezelf",
                 "ik deed het met iemand"],
         antwoord=0,
         uitleg="Myself versterkt hier het onderwerp: ik en niemand anders. Helemaal alleen is by myself of on my own."),
    dict(type="invultekst",
         vraag="Vul het wederkerende voornaamwoord in: « They built the house ___ » (zelf, met zijn allen).",
         antwoord=["themselves"],
         uitleg="Themselves. Bij een meervoud eindigt het op -selves: ourselves, yourselves, themselves."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn onbepaalde voornaamwoorden?",
         opties=["somebody",
                 "nothing",
                 "everyone",
                 "which"],
         antwoord=[0, 1, 2],
         uitleg="Ze wijzen niet iemand of iets bepaalds aan. Which is vragend of betrekkelijk."),
    dict(type="waarofniet",
         vraag="Everybody krijgt een werkwoord in het meervoud: everybody are here.",
         antwoord=False,
         uitleg="Everybody is enkelvoud: everybody is here. Datzelfde geldt voor somebody, nobody en everything."),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: « ___ books on the shelf are mine »?",
         opties=["These",
                 "This",
                 "That",
                 "Those one"],
         antwoord=0,
         uitleg="Bij een meervoud dichtbij staat these, verder weg those. Bij een enkelvoud is het this of that."),
    dict(type="meerkeuze",
         vraag="Wat is het verschil tussen this en that?",
         opties=["this is dichtbij, that is verder weg",
                 "this is verder weg, that is dichtbij",
                 "this is meervoud, that is enkelvoud",
                 "this hoort bij personen, that bij dingen"],
         antwoord=0,
         uitleg="This en these zijn dichtbij, that en those verder weg, in ruimte of in tijd."),
    dict(type="invultekst",
         vraag="Vul in: « I like this shirt, but I prefer ___ one over there » (dat, verder weg).",
         antwoord=["that"],
         uitleg="That one over there. Bij een meervoud zou het those ones zijn, of gewoon those."),
    dict(type="meerkeuze",
         vraag="Waar verwijst they naar in « The results arrived. They were better than expected »?",
         opties=["naar de resultaten",
                 "naar de onderzoekers",
                 "naar de verwachtingen",
                 "naar niets in de tekst"],
         antwoord=0,
         uitleg="They vervangt the results. De fiche vraagt dat je zo'n verwijzing kan volgen, want zonder haar valt de tekst uiteen."),
    dict(type="waarofniet",
         vraag="In het Engels gebruik je they ook voor één persoon van wie je het geslacht niet zegt.",
         antwoord=True,
         uitleg="If a student forgets their book, they can borrow one. Dat gebruik is in het Engels al eeuwen gewoon."),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: « Between you and ___, I think he is wrong »?",
         opties=["me",
                 "I",
                 "myself",
                 "mine"],
         antwoord=0,
         uitleg="Na een voorzetsel staat de voorwerpsvorm: between you and me. Between you and I is een veelgemaakte fout."),
    dict(type="meerkeuze",
         vraag="Welke onbepaalde voornaamwoorden krijgen een werkwoord in het enkelvoud?",
         opties=["nobody",
                 "everything",
                 "somebody",
                 "both"],
         antwoord=[0, 1, 2],
         uitleg="Nobody knows, everything is ready, somebody has called. Both en several zijn meervoud: both are here."),
    dict(type="waarofniet",
         vraag="There en their en they're betekenen alle drie hetzelfde.",
         antwoord=False,
         uitleg="There is daar, their is hun en they're is they are. Ze klinken gelijk, en daarom staan ze zo vaak verkeerd."),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: « We enjoyed ___ at the party »?",
         opties=["ourselves",
                 "us",
                 "ours",
                 "we"],
         antwoord=0,
         uitleg="To enjoy oneself is zich amuseren, en dus staat er een wederkerend voornaamwoord. We enjoyed us bestaat niet."),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: « Is this bag ___ »?",
         opties=["yours",
                 "your",
                 "you",
                 "yourself"],
         antwoord=0,
         uitleg="Alleenstaand wordt your tot yours: is this bag yours? Met een naamwoord erbij is het your bag."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: « ___ is at the door »?",
         opties=["Who",
                 "Whom",
                 "Whose",
                 "Which"],
         antwoord=0,
         uitleg="Who vraagt naar het onderwerp. Whom is de voorwerpsvorm, en die klinkt in spreektaal erg formeel."),
    dict(type="meerkeuze",
         vraag="Welke vraag vraagt naar een bezitter?",
         opties=["Whose coat is this?",
                 "Who is this?",
                 "Which coat is this?",
                 "What coat is this?"],
         antwoord=0,
         uitleg="Whose vraagt van wie iets is. Let op het verschil met who's, dat who is betekent."),
    dict(type="invultekst",
         vraag="Vul het vraagwoord in: « ___ of these two do you prefer? » (welke van de twee).",
         antwoord=["Which", "which"],
         uitleg="Which gebruik je bij een beperkte keuze, what bij een open vraag: what do you want to eat?"),
    dict(type="meerkeuze",
         vraag="Welke vraagwoorden bestaan in het Engels?",
         opties=["whose",
                 "whom",
                 "which",
                 "whomst"],
         antwoord=[0, 1, 2],
         uitleg="Who, whom, whose, which en what. Whomst bestaat niet, het is een grap op het internet."),
    dict(type="waarofniet",
         vraag="Who's betekent who is of who has, en whose betekent van wie.",
         antwoord=True,
         uitleg="Who's coming? is wie komt er. Whose bag is this? is van wie die zak is."),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: « The man ___ lives next door is a doctor »?",
         opties=["who",
                 "which",
                 "whose",
                 "what"],
         antwoord=0,
         uitleg="Bij een persoon staat who of that, bij een ding which of that. Whose is van wie."),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: « The book ___ I bought is excellent »?",
         opties=["that",
                 "who",
                 "whose",
                 "what"],
         antwoord=0,
         uitleg="Bij een ding staat that of which. In een beperkende bijzin zoals deze mag that zelfs wegvallen: the book I bought."),
    dict(type="invultekst",
         vraag="Vul in: « That is the woman ___ son won the prize » (van wie de zoon).",
         antwoord=["whose"],
         uitleg="Whose legt een bezit. Het geldt ook bij dingen: the house whose roof is red."),
    dict(type="meerkeuze",
         vraag="Welke betrekkelijke woorden staan in de lijst van de fiche?",
         opties=["when",
                 "where",
                 "why",
                 "how"],
         antwoord=[0, 1, 2],
         uitleg="That, who, whose, which, when, where en why. How staat er niet bij als betrekkelijk woord: the way she did it."),
    dict(type="waarofniet",
         vraag="In « the day when we met » verwijst when naar een tijdstip.",
         antwoord=True,
         uitleg="When hoort bij een tijd, where bij een plaats en why bij een reden: the reason why he left."),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: « This is the town ___ I grew up »?",
         opties=["where",
                 "when",
                 "which",
                 "whose"],
         antwoord=0,
         uitleg="Where hoort bij een plaats. Je kan ook zeggen: the town in which I grew up, en dat klinkt formeler."),
    dict(type="meerkeuze",
         vraag="In welke zin mag het betrekkelijke woord weggelaten worden?",
         opties=["The film I saw was long.",
                 "The man who called is here.",
                 "The town where I live is small.",
                 "The woman whose car broke down waited."],
         antwoord=0,
         uitleg="Je mag het weglaten als het betrekkelijke woord het voorwerp van de bijzin is. Als het het onderwerp is, zoals who called, moet het blijven staan."),
    dict(type="invultekst",
         vraag="Vul in: « The reason ___ he left is unclear » (de reden waarom).",
         antwoord=["why"],
         uitleg="The reason why. In spreektaal hoor je ook the reason that of gewoon the reason he left."),
    dict(type="meerkeuze",
         vraag="Wat is het verschil tussen « My brother, who lives in Spain, called » en « My brother who lives in Spain called »?",
         opties=["met komma's heb ik één broer",
                 "met komma's heb ik meer broers",
                 "er is helemaal geen verschil",
                 "met komma's is de zin fout gebouwd"],
         antwoord=0,
         uitleg="Komma's maken de bijzin een extraatje: er is één broer, en hij woont toevallig in Spanje. Zonder komma's onderscheidt de bijzin hem van andere broers."),
    dict(type="waarofniet",
         vraag="In een uitbreidende bijzin tussen komma's mag je that gebruiken.",
         antwoord=False,
         uitleg="Tussen komma's staat which of who, nooit that. My car, which is new, broke down."),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: « The people ___ I work with are kind »?",
         opties=["whom",
                 "whose",
                 "which",
                 "what"],
         antwoord=0,
         uitleg="Na een voorzetsel hoort whom: the people with whom I work. In spreektaal laat men het gewoon weg."),
    dict(type="meerkeuze",
         vraag="Welke zinnen met een betrekkelijke bijzin zijn juist?",
         opties=["The book that I read was good.",
                 "The book which I read was good.",
                 "The book I read was good.",
                 "The book what I read was good."],
         antwoord=[0, 1, 2],
         uitleg="Bij een ding kan that of which, en in een beperkende bijzin mag het woord ook wegvallen. What is er altijd fout."),
    dict(type="waarofniet",
         vraag="Who en which kunnen in het Engels door elkaar gebruikt worden.",
         antwoord=False,
         uitleg="Who hoort bij personen en which bij dingen en dieren. That kan bij beide, in een beperkende bijzin."),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: « She asked me ___ I wanted »?",
         opties=["what",
                 "that",
                 "which",
                 "whose"],
         antwoord=0,
         uitleg="In een afhankelijke vraag blijft het vraagwoord staan: she asked me what I wanted. De woordorde wordt wel die van een gewone zin."),
    dict(type="meerkeuze",
         vraag="Welke zin is juist gebouwd?",
         opties=["The man that I met was kind.",
                 "The man what I met was kind.",
                 "The man which I met was kind.",
                 "The man whose I met was kind."],
         antwoord=0,
         uitleg="Bij een persoon staat that, who of whom. What is in die plaats fout, en which hoort bij dingen."),
]
