# -*- coding: utf-8 -*-
"""Woorden voor wetenschap, techniek en taal.

Uit de woordenschatthema's van de vakfiche Engels 1 van de 3de graad
doorstroomfinaliteit (2027): wetenschap, informatica en technologie, en taal
en taalbeschouwing. Dat laatste thema gaat over de taal zelf: hoe woorden
gebouwd zijn, en hoe je de betekenis van een onbekend woord afleidt.

Deel 1 is wetenschap, informatica en technologie.
Deel 2 is taal en taalbeschouwing.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is research?",
         opties=["onderzoek",
                 "een onderzoeker",
                 "een verslag van een proef",
                 "een vraag aan een onderzoeker"],
         antwoord=0,
         uitleg="Research is onderzoek, en het is ontelbaar: a lot of research, niet researches. De onderzoeker is a researcher."),
    dict(type="meerkeuze",
         vraag="Wat is a survey?",
         opties=["een enquête",
                 "een proef in een labo",
                 "een verslag van een reis",
                 "een overzicht van een vakgebied"],
         antwoord=0,
         uitleg="A survey is een enquête of een bevraging. To survey is ook overzien of opmeten."),
    dict(type="invultekst",
         vraag="Welk Engels woord betekent proef of experiment? Eén woord.",
         antwoord=["experiment", "trial"],
         uitleg="An experiment, en bij geneesmiddelen zegt men a trial. To carry out an experiment is een proef uitvoeren."),
    dict(type="meerkeuze",
         vraag="Welke woorden hoor je bij een wetenschappelijk onderzoek?",
         opties=["evidence",
                 "a sample",
                 "a hypothesis",
                 "a headline"],
         antwoord=[0, 1, 2],
         uitleg="Bewijs, een steekproef en een hypothese. A headline is een krantenkop."),
    dict(type="waarofniet",
         vraag="Evidence is in het Engels ontelbaar: je zegt a piece of evidence, niet an evidence.",
         antwoord=True,
         uitleg="Evidence is bewijsmateriaal in het algemeen. Veel bewijs is a lot of evidence of strong evidence."),
    dict(type="meerkeuze",
         vraag="Wat betekent the findings of a study?",
         opties=["de resultaten",
                 "de opzet van het onderzoek",
                 "de vragen van het onderzoek",
                 "de kosten van het onderzoek"],
         antwoord=0,
         uitleg="Findings zijn de bevindingen of resultaten, van to find. De opzet is the design of the method."),
    dict(type="meerkeuze",
         vraag="Wat is a device?",
         opties=["een toestel",
                 "een onderdeel van een motor",
                 "een programma op een computer",
                 "een handleiding bij een machine"],
         antwoord=0,
         uitleg="A device is een toestel of een apparaat: a mobile device. Een programma is an application of software."),
    dict(type="invultekst",
         vraag="Welk Engels woord betekent uitvinding? Eén woord.",
         antwoord=["invention"],
         uitleg="An invention, van to invent. De uitvinder is an inventor, en een octrooi is a patent."),
    dict(type="meerkeuze",
         vraag="Welke woorden horen bij een computer?",
         opties=["a keyboard",
                 "a screen",
                 "a hard drive",
                 "a drawer"],
         antwoord=[0, 1, 2],
         uitleg="Een toetsenbord, een scherm en een harde schijf. A drawer is een schuif in een kast."),
    dict(type="waarofniet",
         vraag="To download betekent een bestand naar de server sturen.",
         antwoord=False,
         uitleg="To download is binnenhalen, naar je eigen toestel. Naar de server sturen is to upload."),
    dict(type="meerkeuze",
         vraag="Wat is a password?",
         opties=["een wachtwoord",
                 "een gebruikersnaam",
                 "een beveiligde verbinding",
                 "een code die je per sms krijgt"],
         antwoord=0,
         uitleg="A password is een wachtwoord. De code per sms hoort bij two-factor authentication."),
    dict(type="meerkeuze",
         vraag="Wat betekent the system crashed?",
         opties=["het systeem viel uit",
                 "het systeem werd gehackt",
                 "het systeem werd vernieuwd",
                 "het systeem werd afgesloten"],
         antwoord=0,
         uitleg="To crash is vastlopen of uitvallen. Een botsing met een auto is ook a crash."),
    dict(type="invultekst",
         vraag="Welk Engels woord betekent programmatuur, het tegengestelde van hardware? Eén woord.",
         antwoord=["software"],
         uitleg="Software, en het is ontelbaar: a piece of software. Hardware zijn de toestellen zelf."),
    dict(type="meerkeuze",
         vraag="Wat is a breakthrough?",
         opties=["een doorbraak",
                 "een mislukte proef",
                 "een nieuw vakgebied",
                 "een fout in een onderzoek"],
         antwoord=0,
         uitleg="A breakthrough is een doorbraak in het onderzoek. To break through is doorbreken."),
    dict(type="waarofniet",
         vraag="Data wordt in wetenschappelijk Engels vaak als meervoud behandeld: the data show…",
         antwoord=True,
         uitleg="Data is het meervoud van datum, en in vakteksten staat er the data show. In spreektaal hoor je ook the data shows."),
    dict(type="meerkeuze",
         vraag="Wat betekent artificial intelligence?",
         opties=["kunstmatige intelligentie",
                 "menselijke intelligentie",
                 "een slim toestel in huis",
                 "een programma dat rekent"],
         antwoord=0,
         uitleg="Artificial is kunstmatig, van art. Men kort het af als AI."),
    dict(type="meerkeuze",
         vraag="Wat is a backup?",
         opties=["een veiligheidskopie",
                 "een tweede toestel",
                 "een herstelde verbinding",
                 "een nieuwe versie van een programma"],
         antwoord=0,
         uitleg="A backup is een reservekopie, to back up is er een maken. Zonder backup is een crash onherstelbaar."),
    dict(type="waarofniet",
         vraag="A chemist is in Groot-Brittannië altijd iemand die scheikunde studeerde.",
         antwoord=False,
         uitleg="A chemist is zowel een scheikundige als een apotheker, en the chemist's is de apotheek zelf."),
    dict(type="meerkeuze",
         vraag="Wat betekent to run a test?",
         opties=["een test uitvoeren",
                 "een test voorbereiden",
                 "een test afbreken",
                 "een test laten nakijken"],
         antwoord=0,
         uitleg="To run is hier uitvoeren of laten lopen: to run a programme, to run a test. Lopen is ook to run."),
    dict(type="meerkeuze",
         vraag="Welke woorden benoemen een gevaar op het internet?",
         opties=["phishing",
                 "a scam",
                 "malware",
                 "a browser"],
         antwoord=[0, 1, 2],
         uitleg="Een valse mail die je gegevens vist, een zwendel en schadelijke software. A browser is gewoon je webbrowser."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is a prefix?",
         opties=["een voorvoegsel",
                 "een achtervoegsel",
                 "een stam van een woord",
                 "een uitgang van een werkwoord"],
         antwoord=0,
         uitleg="Een prefix staat vooraan: un-, re-, dis-, pre-. Achteraan staat a suffix."),
    dict(type="meerkeuze",
         vraag="Wat doet het voorvoegsel un- in unhappy?",
         opties=["het maakt het woord ontkennend",
                 "het maakt het woord sterker",
                 "het maakt er een werkwoord van",
                 "het maakt er een meervoud van"],
         antwoord=0,
         uitleg="Un- ontkent: happy wordt unhappy. Andere ontkennende voorvoegsels zijn in-, im-, dis- en non-."),
    dict(type="invultekst",
         vraag="Welk achtervoegsel maakt van het werkwoord to teach de persoon die het doet: teach__?",
         antwoord=["er", "-er"],
         uitleg="Het achtervoegsel -er: teacher, writer, worker. Soms is het -or, zoals in actor en inventor."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn met een achtervoegsel gebouwd?",
         opties=["careless",
                 "happiness",
                 "readable",
                 "rewrite"],
         antwoord=[0, 1, 2],
         uitleg="De achtervoegsels -less, -ness en -able. In rewrite staat re- vooraan, en dat is een voorvoegsel."),
    dict(type="waarofniet",
         vraag="Het achtervoegsel -less maakt een woord ontkennend: careless is zonder zorg.",
         antwoord=True,
         uitleg="Careless is onzorgvuldig, hopeless is hopeloos, useless is onbruikbaar. Het betekent zonder."),
    dict(type="meerkeuze",
         vraag="Wat betekent unemployment, als je het in delen leest?",
         opties=["werkloosheid",
                 "een nieuwe baan",
                 "een opzegtermijn",
                 "een vaste benoeming"],
         antwoord=0,
         uitleg="Employ is in dienst nemen, -ment maakt er een naamwoord van en un- ontkent het. Zo bouw je een onbekend woord uit zijn delen."),
    dict(type="meerkeuze",
         vraag="Wat is a false friend in de taalkunde?",
         opties=["een woord dat bedriegt met zijn vorm",
                 "een woord dat in twee talen hetzelfde betekent",
                 "een woord dat je in een examen nooit mag gebruiken",
                 "een woord dat uit een andere taal overgenomen is"],
         antwoord=0,
         uitleg="Een valse vriend: eventually betekent uiteindelijk, niet eventueel. Actually betekent eigenlijk, niet actueel."),
    dict(type="invultekst",
         vraag="Welk Engels woord betekent uiteindelijk, en wordt vaak verward met eventueel? Eén woord.",
         antwoord=["eventually"],
         uitleg="Eventually is uiteindelijk. Eventueel is possibly of if necessary."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn valse vrienden tussen het Nederlands en het Engels?",
         opties=["actually",
                 "eventually",
                 "library",
                 "table"],
         antwoord=[0, 1, 2],
         uitleg="Actually is eigenlijk, eventually is uiteindelijk en a library is een bibliotheek. A table is gewoon een tafel."),
    dict(type="waarofniet",
         vraag="Een synonym is een woord met de tegengestelde betekenis.",
         antwoord=False,
         uitleg="Een synonym heeft dezelfde of bijna dezelfde betekenis. Het tegengestelde is an antonym."),
    dict(type="meerkeuze",
         vraag="Wat is an idiom?",
         opties=["een vaste uitdrukking",
                 "een regel van de grammatica",
                 "een woord uit een andere taal",
                 "een manier van spreken in een streek"],
         antwoord=0,
         uitleg="An idiom is een uitdrukking die je niet woord per woord kan vertalen: it's raining cats and dogs. Een streektaal is a dialect."),
    dict(type="meerkeuze",
         vraag="Wat betekent to raise cattle, als je weet dat to raise opheffen betekent?",
         opties=["vee houden",
                 "vee verkopen",
                 "vee verplaatsen",
                 "vee vervoeren met een wagen"],
         antwoord=0,
         uitleg="To raise heeft meer betekenissen: opheffen, grootbrengen, kweken. De context beslist welke."),
    dict(type="invultekst",
         vraag="Welk Engels woord van vier letters betekent de klank waarmee je een woord uitspreekt, en rijmt op bound?",
         antwoord=["sound"],
         uitleg="Sound. De uitspraak zelf is the pronunciation, van to pronounce."),
    dict(type="meerkeuze",
         vraag="Wat is het verschil tussen its en it's?",
         opties=["its is bezittelijk, it's is it is",
                 "its is it is, it's is bezittelijk",
                 "ze betekenen precies hetzelfde",
                 "its hoort bij personen, it's bij dingen"],
         antwoord=0,
         uitleg="Its betekent zijn of haar, zonder apostrof. It's is de samentrekking van it is of it has."),
    dict(type="waarofniet",
         vraag="Brits en Amerikaans Engels spellen sommige woorden anders: colour en color.",
         antwoord=True,
         uitleg="Brits -our en Amerikaans -or, en ook centre tegen center en travelled tegen traveled. Kies één van de twee en hou die aan."),
    dict(type="meerkeuze",
         vraag="Wat betekent a loanword?",
         opties=["een woord uit een andere taal",
                 "een woord dat verdwenen is",
                 "een woord met twee betekenissen",
                 "een woord uit de spreektaal"],
         antwoord=0,
         uitleg="Een leenwoord: het Engels nam croissant uit het Frans, en het Nederlands nam computer uit het Engels."),
    dict(type="meerkeuze",
         vraag="Welke woorden benoemen een manier van spreken?",
         opties=["formal",
                 "informal",
                 "slang",
                 "silent"],
         antwoord=[0, 1, 2],
         uitleg="Formeel, informeel en straattaal. Silent betekent stil, en een silent letter is een letter die je niet uitspreekt."),
    dict(type="waarofniet",
         vraag="In het Engels spreek je in know en write elke letter uit.",
         antwoord=False,
         uitleg="De k van know en de w van write zijn silent letters. Ook de b van lamb en de h van hour zwijgen."),
    dict(type="meerkeuze",
         vraag="Wat is een context clue?",
         opties=["een aanwijzing in de zin eromheen",
                 "een uitleg in het woordenboek",
                 "een voetnoot bij een tekst",
                 "een vertaling onder de tekst"],
         antwoord=0,
         uitleg="De zin eromheen verraadt vaak wat een onbekend woord betekent. Dat gaat sneller dan opzoeken, en de fiche vraagt dat je het kan."),
    dict(type="meerkeuze",
         vraag="Wat betekent the word is spelt with a double l?",
         opties=["het woord heeft twee l'en",
                 "het woord heeft een lange l",
                 "het woord begint met een l",
                 "het woord eindigt op een l"],
         antwoord=0,
         uitleg="To spell is spellen, en spelt is het Britse deelwoord ervan. In Amerika schrijft men spelled."),
]
