# -*- coding: utf-8 -*-
"""Woordvelden: de mens, gezondheid, eten en wonen.

Uit de vakfiche Frans van de 3de graad doorstroomfinaliteit (2027). De fiche
geeft vijftien thema's waaruit het examen woordenschat kan halen; dit thema
dekt Dagelijks leven en sociaal leven, Eten en drinken, Gezondheid en
psychologie, Wonen, en Sport en vrije tijd.

Deel 1 zijn de mens, het lichaam, de gezondheid en de psychologie.
Deel 2 zijn eten en drinken, wonen, en sport en vrije tijd.

Op B1+ gaat het niet meer om losse woordjes maar om woordcombinaties en
uitdrukkingen, dus die staan hier ook.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat betekent « je me sens mal à l'aise » ?",
         opties=["ik voel me niet op mijn gemak",
                 "ik heb pijn aan mijn linkerhand",
                 "ik ben verkouden sinds gisteren",
                 "ik heb te veel gegeten vandaag"],
         antwoord=0,
         uitleg="Être à l'aise is op je gemak zijn; mal à l'aise is het omgekeerde. Het gaat om een gevoel, niet om een lichamelijke klacht."),
    dict(type="invultekst",
         vraag="Welk Frans woord betekent gezondheid? Eén woord.",
         antwoord=["santé", "la santé"],
         uitleg="La santé. Je hoort het ook als toost: à ta santé of kortweg santé, bij ons gezondheid."),
    dict(type="meerkeuze",
         vraag="Je gaat naar de dokter. Welke zin zeg je?",
         opties=["J'ai mal à la tête depuis deux jours.",
                 "Je suis une tête depuis deux jours.",
                 "Ma tête a mal depuis deux jours.",
                 "Il y a mal de tête chez moi."],
         antwoord=0,
         uitleg="Avoir mal à + lichaamsdeel is de vaste vorm: j'ai mal au dos, j'ai mal aux dents. Je zegt niet ma tête a mal."),
    dict(type="meerkeuze",
         vraag="Welke uitdrukkingen gaan over niet in orde zijn?",
         opties=["être fatigué", "avoir de la fièvre", "tomber malade", "être en pleine forme"],
         antwoord=[0, 1, 2],
         uitleg="Moe zijn, koorts hebben en ziek worden. Être en pleine forme betekent net in topvorm zijn."),
    dict(type="waarofniet",
         vraag="« Il est en pleine forme » betekent dat iemand zich uitstekend voelt.",
         antwoord=True,
         uitleg="La forme is de conditie. Être en pleine forme is in topvorm zijn; het omgekeerde is ne pas être en forme."),
    dict(type="meerkeuze",
         vraag="Wat is une ordonnance bij de dokter?",
         opties=["een voorschrift",
                 "een afspraak voor later",
                 "een onderzoek in het ziekenhuis",
                 "een rekening van de behandeling"],
         antwoord=0,
         uitleg="Une ordonnance is het papiertje waarmee je medicijnen gaat halen bij de apotheek, la pharmacie."),
    dict(type="invultekst",
         vraag="Welk Frans woord betekent apotheek? Eén woord.",
         antwoord=["pharmacie", "la pharmacie"],
         uitleg="La pharmacie. De apotheker is le pharmacien of la pharmacienne."),
    dict(type="meerkeuze",
         vraag="Wat betekent « se remettre » als het over gezondheid gaat?",
         opties=["herstellen van iets",
                 "opnieuw ziek worden",
                 "zich laten onderzoeken",
                 "een afspraak uitstellen"],
         antwoord=0,
         uitleg="Se remettre d'une grippe is bekomen van een griep. Remettre alleen betekent iets terugleggen of uitstellen, dus let op het wederkerende se."),
    dict(type="waarofniet",
         vraag="« Elle est enrhumée » betekent dat zij verkouden is.",
         antwoord=True,
         uitleg="Un rhume is een verkoudheid, en être enrhumé betekent er een hebben. Niet te verwarren met la grippe, de griep."),
    dict(type="meerkeuze",
         vraag="Welk woord beschrijft iemand die snel zenuwachtig wordt?",
         opties=["stressé",
                 "détendu en calme",
                 "heureux en souriant",
                 "fatigué na een lange dag"],
         antwoord=0,
         uitleg="Stressé betekent gestresseerd. Détendu is ontspannen, dus net het tegenovergestelde."),
    dict(type="invultekst",
         vraag="Welk Frans woord betekent vermoeidheid? Eén woord.",
         antwoord=["fatigue", "la fatigue"],
         uitleg="La fatigue. Het bijvoeglijk naamwoord is fatigué, en fatigant betekent vermoeiend: let op dat verschil."),
    dict(type="meerkeuze",
         vraag="Wat is het verschil tussen fatigué en fatigant?",
         opties=["de eerste is moe, de tweede vermoeiend",
                 "de eerste is vrouwelijk, de tweede mannelijk",
                 "de eerste is een werkwoord, de tweede niet",
                 "er is geen verschil tussen die twee"],
         antwoord=0,
         uitleg="Je suis fatigué betekent ik ben moe; ce travail est fatigant betekent dit werk is vermoeiend. Verwissel je ze, dan zeg je iets anders."),
    dict(type="meerkeuze",
         vraag="Welke woorden horen bij gevoelens?",
         opties=["la joie", "la tristesse", "la colère", "la facture"],
         antwoord=[0, 1, 2],
         uitleg="Vreugde, verdriet en woede. Une facture is een rekening en hoort bij geld."),
    dict(type="waarofniet",
         vraag="Het Franse woord « sensible » betekent verstandig.",
         antwoord=False,
         uitleg="Sensible betekent gevoelig. Verstandig is raisonnable. Het is een van de bekendste valse vrienden met het Engels."),
    dict(type="meerkeuze",
         vraag="Wat betekent « avoir le moral » ?",
         opties=["goed in je vel zitten",
                 "een goede moraal hebben",
                 "veel geduld hebben",
                 "ergens moraal uit halen"],
         antwoord=0,
         uitleg="Le moral is het gemoed. J'ai le moral betekent ik voel me goed; je n'ai pas le moral is het omgekeerde."),
    dict(type="invultekst",
         vraag="Welk Frans woord betekent slapen? Eén woord, de infinitief.",
         antwoord=["dormir"],
         uitleg="Dormir. S'endormir is in slaap vallen, se réveiller is wakker worden en se lever is opstaan."),
    dict(type="meerkeuze",
         vraag="Welke woorden beschrijven een dagelijkse routine?",
         opties=["se lever tôt",
                 "prendre une douche",
                 "se coucher vers dix heures",
                 "faire le tour du monde"],
         antwoord=[0, 1, 2],
         uitleg="Opstaan, een douche nemen en gaan slapen horen bij elke dag. Een wereldreis is geen routine."),
    dict(type="meerkeuze",
         vraag="Wat betekent « il s'entend bien avec sa sœur » ?",
         opties=["hij kan goed overweg met zijn zus",
                 "hij hoort zijn zus goed roepen",
                 "hij is het eens met zijn zus",
                 "hij spreekt vaak met zijn zus"],
         antwoord=0,
         uitleg="S'entendre bien avec quelqu'un is goed opschieten met iemand. Entendre alleen betekent horen, dus het wederkerende se verandert alles."),
    dict(type="waarofniet",
         vraag="« Un voisin » betekent in het Frans een neef.",
         antwoord=False,
         uitleg="Un voisin is een buur; een neef is un cousin. Le voisinage is de buurt."),
    dict(type="meerkeuze",
         vraag="Wat betekent « rendre service à quelqu'un » ?",
         opties=["iemand een dienst bewijzen",
                 "iemand een rekening sturen",
                 "iemand iets teruggeven",
                 "iemand in dienst nemen"],
         antwoord=0,
         uitleg="Rendre service betekent helpen. Een vraag erom is tu peux me rendre un service, kan je me een dienst doen."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is une boulangerie?",
         opties=["een bakkerij",
                 "een slagerij",
                 "een apotheek",
                 "een kruidenier"],
         antwoord=0,
         uitleg="Une boulangerie verkoopt brood, une pâtisserie gebak, une boucherie vlees en une épicerie kruidenierswaren."),
    dict(type="invultekst",
         vraag="Welk Frans woord betekent slagerij? Eén woord.",
         antwoord=["boucherie", "la boucherie"],
         uitleg="Une boucherie. De slager is le boucher. Bij de charcuterie koop je dan weer vleeswaren en worst."),
    dict(type="meerkeuze",
         vraag="Welke woorden horen op een Franse menukaart?",
         opties=["l'entrée", "le plat du jour", "la carte des vins", "le dentifrice"],
         antwoord=[0, 1, 2],
         uitleg="Voorgerecht, dagschotel en wijnkaart. Le dentifrice is tandpasta."),
    dict(type="meerkeuze",
         vraag="Wat vraag je als je in een restaurant wil afrekenen?",
         opties=["L'addition, s'il vous plaît.",
                 "La facture, s'il vous plaît.",
                 "Le ticket, s'il vous plaît.",
                 "Le compte, s'il vous plaît."],
         antwoord=0,
         uitleg="In een restaurant is het l'addition. Une facture krijg je van een bedrijf, en un ticket is een kassabonnetje."),
    dict(type="waarofniet",
         vraag="« Je suis plein » is in het Frans de gewone manier om te zeggen dat je genoeg gegeten hebt.",
         antwoord=False,
         uitleg="Dat zeg je beter niet: het klinkt als dronken zijn. Je zegt j'ai assez mangé of c'était délicieux, merci."),
    dict(type="meerkeuze",
         vraag="Wat betekent « c'est bon » tegenover « c'est bien » ?",
         opties=["bon over smaak, bien over kwaliteit",
                 "bon over kwaliteit, bien over smaak",
                 "beide betekenen precies hetzelfde",
                 "bon is formeel, bien is spreektaal"],
         antwoord=0,
         uitleg="Ce gâteau est bon gaat over de smaak; ce film est bien gaat over hoe goed het is. Verwisseld klinkt het vreemd."),
    dict(type="invultekst",
         vraag="Welk Frans woord betekent ontbijten, als werkwoord van twee woorden? Begin met prendre.",
         antwoord=["prendre le petit-déjeuner", "petit déjeuner", "déjeuner"],
         uitleg="Prendre le petit-déjeuner. In België en Zwitserland zegt men ook gewoon déjeuner voor ontbijten."),
    dict(type="meerkeuze",
         vraag="Wat is un immeuble?",
         opties=["een gebouw met appartementen",
                 "een vrijstaand huis met tuin",
                 "een stuk grond om te bouwen",
                 "een kamer in een studentenhuis"],
         antwoord=0,
         uitleg="Un immeuble is een flatgebouw. Un appartement is de woning erin, une maison een huis en un terrain een stuk grond."),
    dict(type="meerkeuze",
         vraag="Welke woorden horen bij wonen?",
         opties=["le loyer", "le propriétaire", "le locataire", "le conducteur"],
         antwoord=[0, 1, 2],
         uitleg="De huur, de eigenaar en de huurder. Le conducteur is de bestuurder van een voertuig."),
    dict(type="invultekst",
         vraag="Welk Frans woord betekent de huur die je maandelijks betaalt? Eén woord.",
         antwoord=["loyer", "le loyer"],
         uitleg="Le loyer. Louer is huren of verhuren, un locataire is de huurder en un propriétaire de eigenaar."),
    dict(type="meerkeuze",
         vraag="Wat betekent « un studio » in een Franse woningadvertentie?",
         opties=["een woning met één kamer",
                 "een opnamestudio voor muziek",
                 "een huis met twee verdiepingen",
                 "een kamer in een hotel"],
         antwoord=0,
         uitleg="Un studio is een eenkamerappartement. Un deux-pièces heeft een aparte slaapkamer, un trois-pièces twee."),
    dict(type="waarofniet",
         vraag="In een Franse advertentie betekent « T3 » een woning met drie kamers naast de keuken en het bad.",
         antwoord=True,
         uitleg="T staat voor type: T1 is een studio, T3 heeft drie pièces, meestal een woonkamer en twee slaapkamers. Keuken en bad tellen niet mee."),
    dict(type="meerkeuze",
         vraag="Wat betekent « faire le ménage » ?",
         opties=["het huis poetsen",
                 "het huishouden plannen",
                 "een gezin stichten",
                 "de boodschappen doen"],
         antwoord=0,
         uitleg="Faire le ménage is schoonmaken. Faire les courses is boodschappen doen, en faire la vaisselle is de vaat doen."),
    dict(type="waarofniet",
         vraag="« Faire la grasse matinée » betekent het huis poetsen.",
         antwoord=False,
         uitleg="Het betekent uitslapen. Het huishouden doe je met faire le ménage, faire la vaisselle en faire la lessive."),
    dict(type="invultekst",
         vraag="Welk Frans woord betekent uitslapen, in de uitdrukking « faire la … matinée » ?",
         antwoord=["grasse"],
         uitleg="Faire la grasse matinée, letterlijk de vette ochtend maken. Het betekent lang in bed blijven liggen."),
    dict(type="meerkeuze",
         vraag="Wat betekent « s'entraîner » ?",
         opties=["trainen voor een sport",
                 "de trein nemen naar het werk",
                 "iemand opleiden voor een job",
                 "zich laten meeslepen door anderen"],
         antwoord=0,
         uitleg="S'entraîner is trainen. Un entraîneur is een trainer en un entraînement een training. Met de trein heeft het niets te maken."),
    dict(type="waarofniet",
         vraag="« Faire du vélo » betekent in het Frans fietsen.",
         antwoord=True,
         uitleg="Faire du + sport is de gewone vorm: faire du vélo, faire du foot, faire de la natation. Bij een balsport hoor je ook jouer au foot."),
    dict(type="meerkeuze",
         vraag="Wanneer gebruik je jouer à en wanneer faire de bij een sport?",
         opties=["jouer à bij een spel met een bal",
                 "jouer à bij elke sport zonder bal",
                 "faire de enkel bij ploegsporten",
                 "er is geen regel, het is willekeurig"],
         antwoord=0,
         uitleg="Jouer au tennis, jouer au foot, jouer aux cartes: iets met een spelelement. Faire de la natation, faire du vélo, faire du judo: een bezigheid."),
    dict(type="meerkeuze",
         vraag="Welke woorden horen bij vrije tijd?",
         opties=["un loisir", "une sortie", "un spectacle", "un salaire"],
         antwoord=[0, 1, 2],
         uitleg="Een bezigheid, een uitstap en een voorstelling. Un salaire is een loon en hoort bij werk."),
    dict(type="meerkeuze",
         vraag="Wat betekent « ça me dit » in « un ciné ce soir, ça te dit ? » ?",
         opties=["heb je daar zin in?",
                 "wat zeg je daarvan?",
                 "wat betekent dat?",
                 "heb je dat al gezien?"],
         antwoord=0,
         uitleg="Ça te dit betekent heb je daar zin in. Het antwoord is oui, ça me dit, of non, ça ne me dit rien."),
]
