# -*- coding: utf-8 -*-
"""Ethiek: basisbegrippen en vier benaderingen.

Het eerste van vier thema's over ethiek. De fiche vraagt hier:

    goed handelen uitleggen met de basisbegrippen waarden en normen, moreel
        universalisme en moreel relativisme, vrije wil en cultuurrelativisme
    uitleggen wat een moreel dilemma of een ethische vraag is
    twee benaderingen binnen de ethiek uitleggen: de descriptieve en de
        normatieve, met onder die laatste gevolgenethiek, plichtethiek,
        deugdethiek en zorgethiek
    het is-ought probleem van David Hume uitleggen

De vier normatieve benaderingen krijgen hier elk hun plaats in het overzicht;
de drie thema's die volgen gaan er dieper op in.

Deel 1 zijn de basisbegrippen en het morele dilemma.
Deel 2 zijn de twee benaderingen, de vier richtingen in de normatieve ethiek,
en het is-ought probleem.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is het verschil tussen een waarde en een norm?",
         opties=["een waarde is wat je belangrijk vindt, een norm is de regel die eruit volgt",
                 "een waarde is een regel van de wet, een norm is wat je zelf belangrijk vindt",
                 "een waarde geldt voor iedereen, een norm geldt enkel voor jou alleen",
                 "een waarde kan je meten in geld, een norm kan je nooit in geld meten"],
         antwoord=0,
         uitleg="Eerlijkheid is een waarde; je mag niet spieken is de norm die erbij hoort. "
                "Dezelfde waarde kan in twee landen andere normen opleveren."),
    dict(type="meerkeuze",
         vraag="Welke rij geeft een waarde met de bijhorende norm?",
         opties=["respect, en dus: je laat iemand uitspreken",
                 "je laat iemand uitspreken, en dus: respect",
                 "respect, en dus: eerlijkheid in alles wat je zegt",
                 "je laat iemand uitspreken, en dus: je valt niemand in de rede"],
         antwoord=0,
         uitleg="De waarde komt eerst en is algemeen; de norm is het concrete gedrag dat eruit "
                "volgt."),
    dict(type="meerkeuze",
         vraag="Wat zegt het moreel universalisme?",
         opties=["er zijn morele regels die voor alle mensen en overal gelden",
                 "er zijn morele regels die per cultuur en per tijd verschillen",
                 "er zijn geen morele regels, want iedereen beslist voor zichzelf",
                 "er zijn morele regels, maar enkel voor wie ze zelf heeft aanvaard"],
         antwoord=0,
         uitleg="Universeel wil zeggen: voor iedereen. Folteren is fout, waar en wanneer dan ook, "
                "is zo'n universalistische uitspraak."),
    dict(type="meerkeuze",
         vraag="Wat zegt het moreel relativisme?",
         opties=["wat goed is, hangt af van wie het zegt of van welke groep het komt",
                 "wat goed is, staat vast en geldt voor alle mensen tegelijk",
                 "wat goed is, kan door onderzoek voor eens en altijd vastgesteld worden",
                 "wat goed is, wordt uiteindelijk door de wet van een land beslist"],
         antwoord=0,
         uitleg="Relatief wil zeggen: in verhouding tot iets. Bij het relativisme is er geen "
                "standpunt van waaruit je alle anderen kan beoordelen."),
    dict(type="meerkeuze",
         vraag="Wat zegt het cultuurrelativisme?",
         opties=["morele opvattingen horen bij een cultuur en zijn niet van buitenaf te beoordelen",
                 "morele opvattingen zijn in elke cultuur op de keper beschouwd hetzelfde",
                 "morele opvattingen van de eigen cultuur zijn beter dan die van andere",
                 "morele opvattingen hangen enkel af van wat een individu er zelf van vindt"],
         antwoord=0,
         uitleg="Het is de culturele vorm van het relativisme. De lastige vraag die erbij hoort: "
                "mag je dan nog iets afkeuren dat elders gewoonte is?"),
    dict(type="meerkeuze",
         vraag="Wat is het bekendste bezwaar tegen het cultuurrelativisme?",
         opties=["je kan dan geen enkel onrecht in een andere cultuur meer afkeuren",
                 "je kan dan geen enkel verschil tussen culturen meer vaststellen",
                 "je kan dan geen enkele waarde in je eigen cultuur meer verdedigen",
                 "je kan dan geen enkele wet meer maken die in je eigen land geldt"],
         antwoord=0,
         uitleg="Wie zegt dat je een cultuur niet van buitenaf mag beoordelen, haalt daarmee ook "
                "de grond onder elke kritiek op onrecht weg."),
    dict(type="meerkeuze",
         vraag="Waarom hoort de vrije wil bij de basisbegrippen van de ethiek?",
         opties=["zonder keuzevrijheid valt er niemand nog verantwoordelijk te stellen",
                 "zonder keuzevrijheid bestaan er geen waarden en normen meer",
                 "zonder keuzevrijheid is elke cultuur precies even goed als de andere",
                 "zonder keuzevrijheid kan je nog altijd bepalen wat goed handelen is"],
         antwoord=0,
         uitleg="Verwijten dat iemand anders had moeten handelen, heeft alleen zin als hij anders "
                "kón handelen. Daarom hangt de ethiek aan dit begrip vast."),
    dict(type="meerkeuze",
         vraag="Wat is een moreel dilemma?",
         opties=["een keuze waarbij elke mogelijkheid iets van waarde kost",
                 "een keuze tussen iets dat duidelijk goed is en iets dat duidelijk fout is",
                 "een keuze die je uitstelt omdat je niet genoeg informatie hebt",
                 "een keuze waarover de mensen om je heen van mening verschillen"],
         antwoord=0,
         uitleg="Het pijnlijke zit erin dat er geen schone uitweg is. Ook de beste keuze laat iets "
                "achter dat je eigenlijk niet wou opgeven."),
    dict(type="meerkeuze",
         vraag="Wat kenmerkt een ethische vraag?",
         opties=["ze gaat over wat je zou moeten doen en niet over wat er feitelijk gebeurt",
                 "ze gaat over wat er feitelijk gebeurt en niet over wat je zou moeten doen",
                 "ze is met voldoende onderzoek altijd eenduidig te beantwoorden",
                 "ze kan enkel gesteld worden door iemand die filosofie gestudeerd heeft"],
         antwoord=0,
         uitleg="Hoeveel mensen liegen is een feitenvraag. Of liegen hier mag, is een ethische "
                "vraag."),
    dict(type="meerkeuze",
         vraag="Je moet beslissen of je een vriend verraadt om iemand anders te beschermen. Wat "
               "voor vraag is dat?",
         opties=["een moreel dilemma, want welke kant je kiest, iets van waarde gaat eraan",
                 "een feitenvraag, want je moet enkel nagaan wat er precies gebeurd is",
                 "geen ethische vraag, want vriendschap is een privézaak van jullie twee",
                 "geen echt dilemma, want trouw aan een vriend weegt altijd het zwaarst"],
         antwoord=0,
         uitleg="Twee waarden die tegen elkaar in gaan en geen uitweg waarbij je beide behoudt: "
                "dat is de vorm van een dilemma."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over universalisme en relativisme kloppen?",
         opties=["het universalisme neemt regels aan die overal gelden",
                 "het relativisme maakt kritiek op een andere cultuur lastig",
                 "beide standpunten zeggen hetzelfde met andere woorden",
                 "het universalisme ontkent dat er culturele verschillen bestaan"],
         antwoord=[0, 1],
         uitleg="De eerste twee. Een universalist kan de verschillen gerust vaststellen; hij vindt "
                "alleen dat sommige regels daar niet van afhangen."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over waarden en normen kloppen?",
         opties=["dezelfde waarde kan in twee landen andere normen opleveren",
                 "een norm is concreter dan de waarde waaruit ze volgt",
                 "waarden en normen zijn twee woorden voor precies hetzelfde",
                 "een waarde is altijd een regel die ergens opgeschreven staat"],
         antwoord=[0, 1],
         uitleg="De eerste twee. Respect voor ouderen is overal een waarde; hoe je dat hoort te "
                "laten zien, verschilt."),
    dict(type="waarofniet",
         vraag="Een norm is concreter dan de waarde waaruit ze volgt.",
         antwoord=True,
         uitleg="Waar. Eerlijkheid is de waarde, je mag niet spieken de norm."),
    dict(type="waarofniet",
         vraag="Volgens het moreel universalisme verschilt goed en kwaad per cultuur.",
         antwoord=False,
         uitleg="Niet waar. Dat is net het relativisme. Het universalisme houdt vast aan regels "
                "die overal gelden."),
    dict(type="waarofniet",
         vraag="Bij een moreel dilemma kost elke mogelijke keuze iets van waarde.",
         antwoord=True,
         uitleg="Waar. Daarin verschilt een dilemma van een moeilijke maar duidelijke keuze."),
    dict(type="waarofniet",
         vraag="Een ethische vraag is een vraag naar wat er feitelijk gebeurt.",
         antwoord=False,
         uitleg="Niet waar. Ze gaat over wat zou moeten, niet over wat is."),
    dict(type="invultekst",
         vraag="Hoe noem je wat je belangrijk vindt, zoals eerlijkheid of vrijheid?",
         antwoord=["een waarde", "waarde", "waarden"],
         uitleg="De concrete regel die eruit volgt, is de norm."),
    dict(type="invultekst",
         vraag="Hoe noem je de concrete regel die uit een waarde volgt?",
         antwoord=["een norm", "norm", "normen"],
         uitleg="Je mag niet spieken is de norm bij de waarde eerlijkheid."),
    dict(type="invultekst",
         vraag="Hoe heet het standpunt dat morele regels overal en voor iedereen gelden? Moreel ...",
         antwoord=["universalisme"],
         uitleg="Universeel: voor iedereen."),
    dict(type="invultekst",
         vraag="Hoe heet een keuze waarbij elke mogelijkheid iets van waarde kost? Een moreel ...",
         antwoord=["dilemma"],
         uitleg="Er is geen uitweg waarbij je alles behoudt."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat doet de descriptieve ethiek?",
         opties=["ze beschrijft welke morele opvattingen mensen er feitelijk op nahouden",
                 "ze bepaalt welke morele opvattingen mensen zouden moeten aanhouden",
                 "ze bewijst welke van alle morele opvattingen de enige juiste is",
                 "ze bestrijdt elke morele opvatting die niet wetenschappelijk is"],
         antwoord=0,
         uitleg="Beschrijven, niet voorschrijven. Welk deel van de bevolking abortus aanvaardt, is "
                "descriptieve ethiek."),
    dict(type="meerkeuze",
         vraag="Wat doet de normatieve ethiek?",
         opties=["ze zoekt een antwoord op de vraag wat je zou moeten doen",
                 "ze zoekt een antwoord op de vraag wat mensen feitelijk doen",
                 "ze zoekt een antwoord op de vraag hoe moraal is ontstaan",
                 "ze zoekt een antwoord op de vraag welke wetten een land heeft"],
         antwoord=0,
         uitleg="Normatief komt van norm: ze stelt de regel zelf ter discussie en niet alleen wat "
                "mensen erover denken."),
    dict(type="meerkeuze",
         vraag="Welke vier richtingen horen bij de normatieve ethiek volgens deze fiche?",
         opties=["gevolgenethiek, plichtethiek, deugdethiek en zorgethiek",
                 "gevolgenethiek, plichtethiek, descriptieve ethiek en zorgethiek",
                 "deugdethiek, zorgethiek, cultuurrelativisme en universalisme",
                 "plichtethiek, deugdethiek, rechtsethiek en beroepsethiek"],
         antwoord=0,
         uitleg="Vier antwoorden op dezelfde vraag, elk met een ander aanknopingspunt: het gevolg, "
                "de plicht, de persoon, de relatie."),
    dict(type="meerkeuze",
         vraag="Waarnaar kijkt de gevolgenethiek om te beslissen of een daad goed is?",
         opties=["naar wat de daad teweegbrengt",
                 "naar de regel die bij de daad hoort",
                 "naar het karakter van wie de daad stelt",
                 "naar de relatie tussen wie zorgt en wie zorg krijgt"],
         antwoord=0,
         uitleg="De uitkomst beslist. Daarom heet ze ook wel het utilitarisme: het gaat om het nut "
                "van wat volgt."),
    dict(type="meerkeuze",
         vraag="Waarnaar kijkt de plichtethiek?",
         opties=["naar de regel of de plicht die je in deze situatie bindt",
                 "naar het gevolg dat je daad in de wereld zal hebben",
                 "naar de deugd die je door deze daad verder ontwikkelt",
                 "naar de zorg die deze ene mens op dit moment nodig heeft"],
         antwoord=0,
         uitleg="Sommige dingen doe je niet, hoe goed de uitkomst ook zou uitvallen. Dat is de "
                "kern van de plichtethiek."),
    dict(type="meerkeuze",
         vraag="Waarnaar kijkt de deugdethiek?",
         opties=["naar wat voor mens je door je handelen wordt",
                 "naar het gevolg dat je handelen voor anderen heeft",
                 "naar de regel die op dit geval van toepassing is",
                 "naar wat de wet in dit geval van je verlangt"],
         antwoord=0,
         uitleg="Haar vraag is niet wat moet ik doen maar wat voor mens wil ik zijn. Het goede "
                "handelen volgt dan uit een goed karakter."),
    dict(type="meerkeuze",
         vraag="Waarnaar kijkt de zorgethiek?",
         opties=["naar de concrete mens die voor je staat en wat die nodig heeft",
                 "naar de algemene regel die voor alle mensen tegelijk geldt",
                 "naar de som van het geluk dat je daad in de wereld oplevert",
                 "naar de deugden die een mens in zijn leven moet ontwikkelen"],
         antwoord=0,
         uitleg="Ze vertrekt niet van een regel of een berekening maar van de band tussen mensen "
                "die van elkaar afhankelijk zijn."),
    dict(type="meerkeuze",
         vraag="Een arts twijfelt over een zware behandeling. Welke vraag stelt de gevolgenethiek?",
         opties=["wat levert deze behandeling de patiënt per saldo op?",
                 "welke regel bindt mij hier, los van de uitkomst?",
                 "wat voor arts word ik als ik dit beslis?",
                 "wat heeft deze mens in deze relatie van mij nodig?"],
         antwoord=0,
         uitleg="Elke benadering stelt bij dezelfde beslissing een andere vraag. Dit is die van de "
                "gevolgen."),
    dict(type="meerkeuze",
         vraag="Wat is het is-ought probleem van David Hume?",
         opties=["uit wat is, volgt niet zonder meer wat zou moeten",
                 "uit wat zou moeten, volgt niet zonder meer wat is",
                 "uit wat is, volgt altijd meteen wat zou moeten",
                 "uit wat is, valt niets over de werkelijkheid af te leiden"],
         antwoord=0,
         uitleg="Een beschrijving en een voorschrift zijn twee soorten uitspraken. Tussen beide "
                "zit een stap die je apart moet verdedigen."),
    dict(type="meerkeuze",
         vraag="Welke uitspraak maakt de sprong die Hume aanwijst?",
         opties=["mensen eten al duizenden jaren vlees, dus mogen we dat blijven doen",
                 "mensen eten al duizenden jaren vlees, en dat is in de meeste landen nog zo",
                 "wij zouden minder vlees moeten eten dan wij vandaag gewoon zijn",
                 "de helft van de bevolking eet volgens dat onderzoek minder vlees"],
         antwoord=0,
         uitleg="Het woordje dus doet het werk. Dat iets zo is of zo was, zegt op zich niet dat "
                "het zo mag blijven."),
    dict(type="meerkeuze",
         vraag="Hoe gebruikt men het is-ought probleem als kritiek op de gevolgenethiek?",
         opties=["dat mensen naar geluk streven, bewijst niet dat geluk de maatstaf moet zijn",
                 "dat mensen naar geluk streven, bewijst dat geluk de maatstaf moet zijn",
                 "dat geluk de maatstaf is, bewijst dat mensen naar geluk streven",
                 "dat mensen naar geluk streven, valt niet vast te stellen of te meten"],
         antwoord=0,
         uitleg="De gevolgenethiek vertrekt van een vaststelling over mensen en maakt daar een "
                "norm van. Precies daar wijst Hume de sprong aan."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over de descriptieve en de normatieve ethiek kloppen?",
         opties=["de descriptieve beschrijft, de normatieve schrijft voor",
                 "de descriptieve kan onderzoek gebruiken, bijvoorbeeld een bevraging",
                 "de descriptieve beslist welke morele opvatting de juiste is",
                 "de normatieve beperkt zich tot het meten van wat mensen vinden"],
         antwoord=[0, 1],
         uitleg="De eerste twee. Het is-ought probleem zegt juist dat je van de eerste niet "
                "zomaar naar de tweede kan oversteken."),
    dict(type="waarofniet",
         vraag="De descriptieve ethiek beschrijft welke morele opvattingen mensen hebben.",
         antwoord=True,
         uitleg="Waar. Ze velt zelf geen oordeel over die opvattingen."),
    dict(type="waarofniet",
         vraag="De gevolgenethiek beoordeelt een daad op de regel die erbij hoort.",
         antwoord=False,
         uitleg="Niet waar. Dat doet de plichtethiek. De gevolgenethiek kijkt naar de uitkomst."),
    dict(type="waarofniet",
         vraag="De deugdethiek vraagt vooral wat voor mens je wil zijn.",
         antwoord=True,
         uitleg="Waar. Het goede handelen volgt daar uit een goed karakter."),
    dict(type="waarofniet",
         vraag="Volgens het is-ought probleem volgt uit wat is zonder meer wat zou moeten.",
         antwoord=False,
         uitleg="Niet waar. Juist omgekeerd: die stap is niet vanzelfsprekend en moet apart "
                "verdedigd worden."),
    dict(type="invultekst",
         vraag="Welke benadering beschrijft enkel welke moraal mensen hebben? De ... ethiek",
         antwoord=["descriptieve"],
         uitleg="Beschrijven, niet voorschrijven."),
    dict(type="invultekst",
         vraag="Welke benadering gaat over wat je zou moeten doen? De ... ethiek",
         antwoord=["normatieve"],
         uitleg="Normatief komt van norm."),
    dict(type="invultekst",
         vraag="Welke filosoof wijst op de sprong van is naar ought?",
         antwoord=["Hume", "David Hume"],
         uitleg="Dezelfde Hume als bij het empirisme en de inductie."),
    dict(type="invultekst",
         vraag="Welke richting binnen de normatieve ethiek beoordeelt een daad op haar uitkomst? "
               "De ...",
         antwoord=["gevolgenethiek", "gevolgethiek"],
         uitleg="Ook het utilitarisme genoemd."),
]
