# -*- coding: utf-8 -*-
"""Ethiek en geluk.

Het vierde en laatste thema over ethiek. De fiche vraagt de link tussen goed
en juist handelen en geluk, en daarna een analyse en vergelijking van visies
op geluk. De lijst van de fiche:

    Aristoteles
    Epicurus
    Immanuel Kant
    Jeremy Bentham
    Arthur Schopenhauer
    Emmanuel Levinas
    Dirk De Wachter
    Oosterse wijsheden
    Stoïcisme

Bij "Oosterse wijsheden" noemt de fiche geen school en geen tekst. De vragen
blijven daarom bij wat algemeen vaststaat: dat lijden er met verlangen en
vasthouden verbonden wordt, en dat matigheid en aandacht er de weg uit zijn.
Bij Dirk De Wachter staat hier wat hij als psychiater bekend heeft gemaakt:
dat verdriet bij een leven hoort en dat de druk om altijd gelukkig te zijn
mensen ongelukkig maakt.

Deel 1 is de link tussen goed handelen en geluk, met Aristoteles, Epicurus,
het stoïcisme en de oosterse wijsheden.
Deel 2 zijn Kant, Bentham, Schopenhauer, Levinas en De Wachter, en de
vergelijking.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is de link tussen goed handelen en geluk bij de meeste klassieke filosofen?",
         opties=["goed leven en gelukkig leven vallen bij hen grotendeels samen",
                 "goed leven en gelukkig leven staan bij hen volledig los van elkaar",
                 "goed leven leidt bij hen altijd tot ongeluk en opoffering",
                 "gelukkig leven leidt bij hen altijd tot slecht handelen"],
         antwoord=0,
         uitleg="Wie goed leeft, leeft volgens hen ook goed voor zichzelf. Dat de twee kunnen "
                "botsen, is een latere gedachte."),
    dict(type="meerkeuze",
         vraag="Wat betekent geluk bij Aristoteles?",
         opties=["bloeien: je leven goed en volledig leven volgens de deugd",
                 "een aangenaam gevoel dat zo lang mogelijk moet duren",
                 "het ontbreken van pijn en van elke vorm van onrust",
                 "de gemoedsrust die je vindt door alles te aanvaarden"],
         antwoord=0,
         uitleg="Geluk is bij hem geen stemming maar een manier van leven, die je over een heel "
                "leven beoordeelt en niet over één dag."),
    dict(type="meerkeuze",
         vraag="Waarom is geluk bij Aristoteles geen kwestie van één goede dag?",
         opties=["het gaat om een heel leven dat als geheel geslaagd is",
                 "het gaat om een gevoel dat elke dag opnieuw moet opkomen",
                 "het gaat om het geluk van de groep en niet van één mens",
                 "het gaat om een beslissing die je één keer in je leven neemt"],
         antwoord=0,
         uitleg="Eén zwaluw maakt de lente niet. Je beoordeelt een leven zoals je een verhaal "
                "beoordeelt: in zijn geheel."),
    dict(type="meerkeuze",
         vraag="Wat is geluk volgens Epicurus?",
         opties=["de rust die overblijft als pijn en onrust weg zijn",
                 "zoveel genot verzamelen als er maar te krijgen is",
                 "zoveel bezit verwerven dat je niemand nodig hebt",
                 "een leven lang bezig zijn met de zorg voor anderen"],
         antwoord=0,
         uitleg="Hij wordt vaak als een genotzoeker voorgesteld, maar zijn genot is sober: geen "
                "pijn, geen angst, geen honger, en goede vrienden."),
    dict(type="meerkeuze",
         vraag="Welke raad past bij Epicurus?",
         opties=["beperk je verlangens tot wat je echt nodig hebt",
                 "vermeerder je verlangens zodat je altijd iets te wensen hebt",
                 "vul je dagen met zoveel feesten als je maar kan",
                 "onderdruk elk gevoel van genot dat in je opkomt"],
         antwoord=0,
         uitleg="Wie weinig nodig heeft, is moeilijk ongelukkig te maken. Daar zit zijn hele "
                "levenskunst in."),
    dict(type="meerkeuze",
         vraag="Wat is geluk volgens het stoïcisme?",
         opties=["gemoedsrust, door te scheiden wat in je macht ligt van wat niet",
                 "genot, zolang je het met maat en met vrienden geniet",
                 "bloeien, door je deugden je leven lang te oefenen",
                 "verbondenheid, door je verdriet met iemand te delen"],
         antwoord=0,
         uitleg="Hetzelfde onderscheid als bij hun visie op vrijheid: je oordeel is van jou, de "
                "gebeurtenis niet."),
    dict(type="meerkeuze",
         vraag="Wat hebben Epicurus en het stoïcisme met elkaar gemeen?",
         opties=["beiden zoeken geluk in rust en in minder afhankelijkheid van wat je overkomt",
                 "beiden zoeken geluk in zoveel genot als je maar kan verzamelen",
                 "beiden zoeken geluk in de zorg voor wie van jou afhankelijk is",
                 "beiden vinden dat geluk voor een mens niet te bereiken valt"],
         antwoord=0,
         uitleg="De weg verschilt, de richting niet: minder aan de haak van het geluk dat van "
                "buiten moet komen."),
    dict(type="meerkeuze",
         vraag="Wat verbinden oosterse wijsheden met het lijden van de mens?",
         opties=["het verlangen en het vasthouden aan wat niet blijft",
                 "het gebrek aan bezit en aan maatschappelijk aanzien",
                 "het ontbreken van een vaste regel om naar te handelen",
                 "het tekort aan kennis over hoe de wereld in elkaar zit"],
         antwoord=0,
         uitleg="Alles verandert; wie zich vastklampt aan wat verdwijnt, lijdt. Vandaar de nadruk "
                "op matigheid, aandacht en loslaten."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over Aristoteles en Epicurus kloppen?",
         opties=["beiden verbinden goed leven met een geslaagd leven voor jezelf",
                 "Epicurus legt meer gewicht bij het ontbreken van pijn en onrust",
                 "Aristoteles ziet geluk als een stemming van de dag",
                 "Epicurus raadt aan om zoveel genot als mogelijk op te zoeken"],
         antwoord=[0, 1],
         uitleg="De eerste twee. Aristoteles kijkt naar een heel leven; Epicurus kijkt naar wat je "
                "rust in de weg staat."),
    dict(type="meerkeuze",
         vraag="Je mist een promotie en bent er dagen ondersteboven van. Welke raad komt uit het "
               "stoïcisme?",
         opties=["de beslissing lag niet in jouw macht; je oordeel erover wel",
                 "beperk je verlangens tot wat je lichaam echt nodig heeft",
                 "deel je verdriet met iemand, want daarin zit verbondenheid",
                 "bekijk wat de beslissing voor het geluk van allen oplevert"],
         antwoord=0,
         uitleg="Elk van de vier past bij een andere filosoof uit dit thema. Deze is stoïcijns."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over geluk in de klassieke filosofie kloppen?",
         opties=["geluk wordt er eerder als een manier van leven dan als een gevoel bekeken",
                 "goed handelen en gelukkig zijn worden er met elkaar verbonden",
                 "geluk wordt er gemeten in het bezit dat iemand bijeenbrengt",
                 "geluk wordt er beschouwd als iets dat je volledig overkomt"],
         antwoord=[0, 1],
         uitleg="De eerste twee. Daarom hoort het geluk bij de ethiek en niet bij de psychologie "
                "van de goede dag."),
    dict(type="meerkeuze",
         vraag="Waarom is geluk een ethische vraag en niet alleen een gevoelskwestie?",
         opties=["het gaat over hoe je je leven zou moeten inrichten en waarom",
                 "het gaat over wat mensen op een gegeven dag toevallig voelen",
                 "het gaat over wat met een vragenlijst te meten valt",
                 "het gaat over wat de wet van een land hierover voorschrijft"],
         antwoord=0,
         uitleg="Zodra je vraagt wat een geslaagd leven is, ben je aan het nadenken over wat "
                "zou moeten en niet over wat nu eenmaal zo is."),
    dict(type="waarofniet",
         vraag="Geluk bij Aristoteles is een manier van leven en niet een stemming.",
         antwoord=True,
         uitleg="Waar. Daarom beoordeelt hij het over een heel leven."),
    dict(type="waarofniet",
         vraag="Epicurus raadt aan om zoveel genot te verzamelen als mogelijk.",
         antwoord=False,
         uitleg="Niet waar. Zijn genot is sober: geen pijn, geen angst en goede vrienden."),
    dict(type="waarofniet",
         vraag="Het stoïcisme zoekt geluk in gemoedsrust.",
         antwoord=True,
         uitleg="Waar, door te scheiden wat in je macht ligt van wat niet in je macht ligt."),
    dict(type="waarofniet",
         vraag="Oosterse wijsheden verbinden het lijden vooral met een tekort aan bezit.",
         antwoord=False,
         uitleg="Niet waar. Zij verbinden het met verlangen en met vasthouden aan wat niet blijft."),
    dict(type="invultekst",
         vraag="Hoe noemt men het geluk bij Aristoteles, dat bloeien betekent?",
         antwoord=["eudaimonia", "bloeien"],
         uitleg="Een geslaagd leven volgens de deugd, niet een goed gevoel van de dag."),
    dict(type="invultekst",
         vraag="Welke filosoof uit de oudheid ziet geluk als het ontbreken van pijn en onrust?",
         antwoord=["Epicurus"],
         uitleg="Zijn genot is sober, met vriendschap als een van de grootste goederen."),
    dict(type="invultekst",
         vraag="Welke stroming zoekt geluk in gemoedsrust door te aanvaarden wat je niet in de "
               "hand hebt?",
         antwoord=["het stoïcisme", "stoïcisme", "de Stoa"],
         uitleg="Hetzelfde onderscheid dat zij bij vrijheid maken."),
    dict(type="invultekst",
         vraag="Waarmee verbinden oosterse wijsheden het lijden van de mens?",
         antwoord=["verlangen", "met verlangen", "het verlangen"],
         uitleg="En met het vasthouden aan wat niet blijft."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Welke plaats heeft geluk in de ethiek van Immanuel Kant?",
         opties=["geluk is geen maatstaf voor moraal; je plicht doe je om de plicht",
                 "geluk is de enige maatstaf voor moraal die telt",
                 "geluk is de maatstaf, zolang het om het geluk van allen gaat",
                 "geluk is de maatstaf, zolang je er zelf voor gewerkt hebt"],
         antwoord=0,
         uitleg="Een daad die je stelt omdat ze jou gelukkig maakt, is bij hem niet moreel. Wel "
                "verdient wie zijn plicht doet volgens hem geluk."),
    dict(type="meerkeuze",
         vraag="Waarom kan geluk bij Kant geen grondslag voor de moraal zijn?",
         opties=["wat iemand gelukkig maakt, verschilt van mens tot mens",
                 "geluk komt bij mensen nu eenmaal zelden of nooit voor",
                 "geluk is iets dat je met een vragenlijst niet kan meten",
                 "geluk hoort bij het lichaam en moraal hoort bij de geest"],
         antwoord=0,
         uitleg="Een moreel gebod moet voor allen gelden. Iets dat bij ieder anders uitvalt, kan "
                "die algemene wet niet dragen."),
    dict(type="meerkeuze",
         vraag="Welke plaats heeft geluk bij Jeremy Bentham?",
         opties=["geluk is net wél de maatstaf, en het is in principe optelbaar",
                 "geluk is geen maatstaf, want de plicht gaat voor",
                 "geluk is een bijzaak naast de deugd van wie handelt",
                 "geluk is onbereikbaar, want elk verlangen komt terug"],
         antwoord=0,
         uitleg="Hij staat daarmee recht tegenover Kant. Genot min pijn, voor zoveel mensen als "
                "mogelijk: dat is bij hem de hele rekening."),
    dict(type="meerkeuze",
         vraag="Wat is het bezwaar tegen geluk als optelsom?",
         opties=["een getal zegt niet wie van de betrokkenen de prijs betaalt",
                 "een getal zegt niets over hoeveel mensen er betrokken zijn",
                 "geluk valt bij niemand ooit in enige mate vast te stellen",
                 "geluk van anderen hoeft in de moraal nooit mee te tellen"],
         antwoord=0,
         uitleg="Hetzelfde bezwaar als bij de gevolgenethiek: de som verbergt de verdeling."),
    dict(type="meerkeuze",
         vraag="Hoe kijkt Arthur Schopenhauer naar geluk?",
         opties=["geluk is hoogstens het tijdelijk ontbreken van gemis",
                 "geluk is het vaste resultaat van een deugdzaam leven",
                 "geluk is de som van genot min pijn in een mensenleven",
                 "geluk is de verantwoordelijkheid die je voor een ander opneemt"],
         antwoord=0,
         uitleg="Bij hem drijft de wil ons van verlangen naar verlangen. Vervuld verlangen laat "
                "verveling achter, onvervuld verlangen pijn."),
    dict(type="meerkeuze",
         vraag="Waarom noemt men de visie van Schopenhauer pessimistisch?",
         opties=["het verlangen komt bij hem altijd terug, dus blijft geluk kortstondig",
                 "het verlangen verdwijnt bij hem volledig zodra je het eenmaal stilt",
                 "hij ontkent dat mensen ooit iets kunnen verlangen",
                 "hij vindt dat geluk voor iedereen even gemakkelijk te bereiken is"],
         antwoord=0,
         uitleg="Niet dat er nooit iets goed is, maar dat het nooit blijft. Mededogen en kunst "
                "geven bij hem verlichting."),
    dict(type="meerkeuze",
         vraag="Waar ligt geluk volgens Emmanuel Levinas?",
         opties=["niet in jezelf, maar in de verantwoordelijkheid voor de ander",
                 "niet in de ander, maar in de rust die je bij jezelf vindt",
                 "in de som van het genot dat jij in je leven bijeenbrengt",
                 "in de deugden die je door jarenlange oefening opbouwt"],
         antwoord=0,
         uitleg="Zijn hele ethiek begint bij de ander. Een leven dat alleen om jezelf draait, "
                "loopt bij hem dood."),
    dict(type="meerkeuze",
         vraag="Wat is de boodschap van Dirk De Wachter over geluk?",
         opties=["verdriet en tegenslag horen bij een leven en mogen er zijn",
                 "verdriet is een ziekte die altijd behandeld moet worden",
                 "geluk is een plicht waaraan iedereen hard moet werken",
                 "geluk komt enkel voor bij wie het financieel goed heeft"],
         antwoord=0,
         uitleg="Zijn kritiek richt zich op de druk om altijd gelukkig te moeten zijn. Die druk "
                "maakt volgens hem juist ongelukkig."),
    dict(type="meerkeuze",
         vraag="Waarin zoekt De Wachter wel geluk?",
         opties=["in verbondenheid met anderen en in kleine, gewone dingen",
                 "in prestaties waarmee je het ver kan brengen",
                 "in het volledig vermijden van elk verdriet",
                 "in de berekening van wat je het meeste oplevert"],
         antwoord=0,
         uitleg="Iemand die naar je vraagt en bij wie je terechtkan: daar legt hij het gewicht."),
    dict(type="meerkeuze",
         vraag="Welke twee visies uit dit thema staan het verst van elkaar?",
         opties=["Bentham, voor wie geluk de maatstaf is, en Kant, voor wie dat niet zo is",
                 "Aristoteles en Epicurus, want beiden spreken over het goede leven",
                 "Levinas en De Wachter, want beiden spreken over de ander",
                 "het stoïcisme en de oosterse wijsheden, want beide spreken over rust"],
         antwoord=0,
         uitleg="Bij de andere drie paren liggen de visies juist dicht bij elkaar."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over de visies op geluk kloppen?",
         opties=["sommige filosofen zoeken geluk binnen de mens, andere bij de ander",
                 "voor de ene is geluk de maatstaf van moraal, voor de andere niet",
                 "alle genoemde filosofen vinden geluk de maatstaf van de moraal",
                 "alle genoemde filosofen zien geluk als een gevoel van de dag"],
         antwoord=[0, 1],
         uitleg="De eerste twee. Daarin zit het hele verschil dat de fiche je laat vergelijken."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over Schopenhauer en De Wachter kloppen?",
         opties=["beiden nemen afstand van de belofte van een leven zonder verdriet",
                 "De Wachter zoekt een uitweg in verbondenheid, Schopenhauer niet daar",
                 "beiden vinden dat geluk eenvoudig te bereiken is",
                 "beiden rekenen geluk uit als genot min pijn"],
         antwoord=[0, 1],
         uitleg="De eerste twee. Dezelfde nuchterheid over het verdriet, een ander antwoord erop."),
    dict(type="waarofniet",
         vraag="Volgens Kant is geluk de maatstaf waaraan je moraal moet afmeten.",
         antwoord=False,
         uitleg="Niet waar. Bij hem doe je je plicht om de plicht; geluk maakt een daad niet "
                "moreel."),
    dict(type="waarofniet",
         vraag="Voor Bentham is geluk in principe optelbaar.",
         antwoord=True,
         uitleg="Waar. Genot min pijn, voor zoveel mensen als mogelijk."),
    dict(type="waarofniet",
         vraag="Schopenhauer ziet geluk als een blijvende toestand die je kan bereiken.",
         antwoord=False,
         uitleg="Niet waar. Bij hem is het hoogstens het tijdelijk ontbreken van gemis."),
    dict(type="waarofniet",
         vraag="Dirk De Wachter vindt dat verdriet bij een mensenleven hoort.",
         antwoord=True,
         uitleg="Waar. De druk om altijd gelukkig te zijn is volgens hem een deel van het "
                "probleem."),
    dict(type="invultekst",
         vraag="Welke filosoof vindt dat geluk geen grondslag voor de moraal kan zijn?",
         antwoord=["Kant", "Immanuel Kant"],
         uitleg="Je plicht doe je om de plicht, niet om wat ze je oplevert."),
    dict(type="invultekst",
         vraag="Welke filosoof wil geluk optellen als genot min pijn?",
         antwoord=["Bentham", "Jeremy Bentham"],
         uitleg="Hij staat daarmee recht tegenover Kant."),
    dict(type="invultekst",
         vraag="Welke filosoof noemt geluk hoogstens het tijdelijk ontbreken van gemis?",
         antwoord=["Schopenhauer", "Arthur Schopenhauer"],
         uitleg="De wil drijft ons bij hem van verlangen naar verlangen."),
    dict(type="invultekst",
         vraag="Welke Vlaamse psychiater schrijft dat verdriet bij het leven hoort?",
         antwoord=["Dirk De Wachter", "De Wachter"],
         uitleg="Hij neemt het op tegen de druk om altijd gelukkig te moeten zijn."),
]
