# -*- coding: utf-8 -*-
"""Gevolgenethiek en plichtethiek.

Het tweede thema over ethiek. De fiche vraagt voor de gevolgenethiek de
bijdrage van Jeremy Bentham en Peter Singer, en de kritiek op grond van het
is-ought probleem van David Hume. Voor de plichtethiek vraagt ze Immanuel
Kant als grondlegger, met de categorische imperatief, het moreel
universalisme en de hypothetische imperatief, daarnaast Emmanuel Levinas, een
vergelijking van beide visies, en de kritiek op Kant.

Van Bentham staat hier het grootste geluk voor het grootste aantal en het
afwegen van genot en pijn; van Singer dat ook dieren meetellen omdat zij
kunnen lijden; van Kant de twee imperatieven en de mens die nooit louter een
middel mag zijn; van Levinas het gelaat van de ander. Niets daarvan is een
citaat; het zijn de kernideeën waarom deze vier in dit debat genoemd worden.

Let op bij het bouwen: het is-ought probleem komt ook in het thema over de
basisbegrippen voor. De vragen hier zijn anders gesteld, want het bouwscript
weigert twee keer dezelfde vraagtekst.

Deel 1 is de gevolgenethiek.
Deel 2 is de plichtethiek.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Welke andere naam heeft de gevolgenethiek?",
         opties=["het utilitarisme",
                 "het universalisme, want de gevolgen gelden voor iedereen",
                 "het relativisme, want elk gevolg valt anders uit",
                 "het rationalisme, want je moet de gevolgen berekenen"],
         antwoord=0,
         uitleg="Van het Latijnse utilitas: nut. Wat een daad opbrengt, beslist of ze goed is."),
    dict(type="meerkeuze",
         vraag="Wat is de stelregel van Jeremy Bentham?",
         opties=["streef naar het grootste geluk voor het grootste aantal mensen",
                 "streef naar het grootste geluk voor jezelf en je naasten",
                 "streef naar de regel waarvan je wil dat iedereen ze volgt",
                 "streef naar het karakter dat van jou een goed mens maakt"],
         antwoord=0,
         uitleg="Bentham geldt als de grondlegger van het utilitarisme. Niemands geluk weegt bij "
                "hem van tevoren zwaarder dan dat van een ander."),
    dict(type="meerkeuze",
         vraag="Hoe wil Bentham een daad beoordelen?",
         opties=["door het genot en de pijn die ze oplevert tegen elkaar af te wegen",
                 "door te kijken of ze volgens de wet van het land toegelaten is",
                 "door te kijken of ze uit een goede bedoeling is voortgekomen",
                 "door te kijken welke deugd ze bij de handelende mens versterkt"],
         antwoord=0,
         uitleg="Hij wil moraal rekenbaar maken: tel het genot op, trek de pijn af, en kijk wat "
                "er overblijft. Dat is ook meteen waar de kritiek begint."),
    dict(type="meerkeuze",
         vraag="Wat voegt Peter Singer aan de gevolgenethiek toe?",
         opties=["ook dieren tellen mee, want ook zij kunnen lijden",
                 "ook ongeboren mensen tellen mee, want ook zij zullen leven",
                 "enkel mensen tellen mee, want enkel zij kunnen nadenken",
                 "enkel wie zelf meerekent, telt mee in de berekening"],
         antwoord=0,
         uitleg="Zijn vertrekpunt is het vermogen om te lijden, niet het behoren tot onze soort. "
                "Daarmee wordt de kring van wie meetelt veel ruimer."),
    dict(type="meerkeuze",
         vraag="Hoe noemt Singer het vooroordeel dat enkel de eigen soort meetelt?",
         opties=["soortisme",
                 "universalisme, want hij trekt de regel naar alle wezens door",
                 "relativisme, want elke soort heeft haar eigen moraal",
                 "egoïsme, want je denkt eerst en vooral aan jezelf"],
         antwoord=0,
         uitleg="Hij vergelijkt het met andere vormen van willekeurig onderscheid: wie telt mee, "
                "en op welke grond beslis je dat?"),
    dict(type="meerkeuze",
         vraag="Een maatregel maakt tien mensen heel gelukkig en één mens diep ongelukkig. Wat "
               "zegt een strenge gevolgenethiek?",
         opties=["de som is positief, dus de maatregel is te verdedigen",
                 "de som doet niet mee, want één mens mag je nooit schaden",
                 "de maatregel is fout, want geluk valt nooit op te tellen",
                 "de maatregel is fout, want tien tegen één is geen eerlijke verhouding"],
         antwoord=0,
         uitleg="En precies dat is het zwakke punt dat critici aanwijzen: de ene die eraan gaat, "
                "verdwijnt in het totaal."),
    dict(type="meerkeuze",
         vraag="Welk bezwaar wordt tegen de gevolgenethiek gemaakt?",
         opties=["een minderheid kan erin geofferd worden aan het geluk van de meerderheid",
                 "ze kan nooit rekening houden met het geluk van wie er ook bij betrokken is",
                 "ze verbiedt elke daad die iemand ooit pijn zou kunnen doen",
                 "ze beoordeelt enkel de bedoeling en nooit de uitkomst"],
         antwoord=0,
         uitleg="Het klassieke bezwaar. Een optelsom vertelt niet wie de rekening betaalt."),
    dict(type="meerkeuze",
         vraag="Welk praktisch bezwaar wordt tegen de gevolgenethiek gemaakt?",
         opties=["je kent de gevolgen van je daad vooraf niet volledig",
                 "je kent de regel die op je daad past vooraf nooit",
                 "je kent je eigen bedoelingen vooraf nooit helemaal",
                 "je kent de wet van je land vooraf meestal niet goed"],
         antwoord=0,
         uitleg="Wie op de uitkomst moet afgaan, moet de toekomst inschatten. Dat lukt nooit "
                "helemaal."),
    dict(type="meerkeuze",
         vraag="Hoe raakt de kritiek van David Hume aan de gevolgenethiek?",
         opties=["de vaststelling dat mensen geluk zoeken, levert nog geen norm op",
                 "de vaststelling dat mensen geluk zoeken, levert meteen een norm op",
                 "de norm dat geluk telt, levert een vaststelling over mensen op",
                 "de vaststelling dat mensen geluk zoeken, is niet te onderzoeken"],
         antwoord=0,
         uitleg="Tussen de beschrijving en het voorschrift ligt een stap die apart verdedigd moet "
                "worden. Hume wijst die stap aan."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over Bentham en Singer kloppen?",
         opties=["beiden beoordelen een daad op haar gevolgen",
                 "Singer trekt de kring van wie meetelt breder dan de mens",
                 "Bentham beoordeelt een daad op de regel die erbij hoort",
                 "Singer verlaat de gevolgenethiek en kiest voor de plichtethiek"],
         antwoord=[0, 1],
         uitleg="De eerste twee. Singer blijft binnen dezelfde benadering en verandert wie er in "
                "de rekening meegaat."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over de gevolgenethiek kloppen?",
         opties=["ze maakt de uitkomst beslissend en niet de bedoeling",
                 "ze laat zich moeilijk toepassen zonder de toekomst in te schatten",
                 "ze verbiedt op voorhand bepaalde daden, hoe de uitkomst ook is",
                 "ze is de oudste benadering binnen de hele ethiek"],
         antwoord=[0, 1],
         uitleg="De eerste twee. Dat zij geen daad op voorhand uitsluit, is net wat haar van de "
                "plichtethiek onderscheidt."),
    dict(type="meerkeuze",
         vraag="Waarom noemt men de gevolgenethiek een onpartijdige benadering?",
         opties=["het geluk van elke betrokkene weegt in de rekening even zwaar",
                 "het geluk van wie de daad stelt, weegt altijd het zwaarst",
                 "de rechter die oordeelt, mag geen partij zijn in de zaak",
                 "er wordt geen rekening gehouden met het geluk van mensen"],
         antwoord=0,
         uitleg="Jouw geluk telt niet zwaarder omdat het het jouwe is. Dat is een sterke kant van "
                "de benadering, en tegelijk een koude."),
    dict(type="waarofniet",
         vraag="Jeremy Bentham geldt als de grondlegger van het utilitarisme.",
         antwoord=True,
         uitleg="Waar. Het grootste geluk voor het grootste aantal is zijn stelregel."),
    dict(type="waarofniet",
         vraag="Peter Singer vindt dat enkel mensen meetellen in de morele afweging.",
         antwoord=False,
         uitleg="Niet waar. Voor hem telt wie kan lijden, en dat zijn ook dieren."),
    dict(type="waarofniet",
         vraag="De gevolgenethiek beoordeelt een daad op wat ze teweegbrengt.",
         antwoord=True,
         uitleg="Waar. Vandaar de naam, en vandaar ook het bezwaar over de minderheid."),
    dict(type="waarofniet",
         vraag="Volgens de gevolgenethiek staan bepaalde daden vooraf vast als verboden.",
         antwoord=False,
         uitleg="Niet waar. Dat is de plichtethiek. Hier beslist de uitkomst."),
    dict(type="invultekst",
         vraag="Welke andere naam heeft de gevolgenethiek? Het ...",
         antwoord=["utilitarisme"],
         uitleg="Van utilitas: nut."),
    dict(type="invultekst",
         vraag="Welke filosoof formuleerde het grootste geluk voor het grootste aantal?",
         antwoord=["Bentham", "Jeremy Bentham"],
         uitleg="De grondlegger van het utilitarisme."),
    dict(type="invultekst",
         vraag="Welke filosoof rekent dieren mee omdat ook zij kunnen lijden?",
         antwoord=["Singer", "Peter Singer"],
         uitleg="Zijn maatstaf is het vermogen om te lijden, niet de soort."),
    dict(type="invultekst",
         vraag="Welk woord gebruikt Singer voor het voortrekken van de eigen soort?",
         antwoord=["soortisme", "speciesisme"],
         uitleg="Hij zet het naast andere vormen van willekeurig onderscheid."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is het vertrekpunt van de plichtethiek?",
         opties=["sommige daden zijn goed of fout, los van wat ze opleveren",
                 "sommige daden zijn goed of fout, afhankelijk van wat ze opleveren",
                 "sommige daden zijn goed of fout, afhankelijk van je gevoel erover",
                 "sommige daden zijn goed of fout, afhankelijk van je cultuur"],
         antwoord=0,
         uitleg="Daarom heet ze plichtethiek: de plicht geldt ook wanneer de uitkomst je niet "
                "bevalt."),
    dict(type="meerkeuze",
         vraag="Wat is de categorische imperatief van Immanuel Kant?",
         opties=["handel enkel volgens een regel waarvan je kan willen dat ze voor allen geldt",
                 "handel enkel volgens een regel die jou op dat moment het meeste voordeel oplevert",
                 "handel enkel volgens een regel die in jouw land ook de wet is",
                 "handel enkel volgens een regel die je gevoel je op dat moment ingeeft"],
         antwoord=0,
         uitleg="Categorisch wil zeggen: onvoorwaardelijk. De toets is of je regel een algemene "
                "wet kan worden zonder zichzelf op te heffen."),
    dict(type="meerkeuze",
         vraag="Wat is een hypothetische imperatief?",
         opties=["een gebod dat enkel geldt als je een bepaald doel wil bereiken",
                 "een gebod dat voor alle mensen onvoorwaardelijk geldt",
                 "een gebod dat nog bewezen moet worden voor het geldt",
                 "een gebod dat enkel in bijzondere gevallen van toepassing is"],
         antwoord=0,
         uitleg="Wil je je examen halen, dan moet je studeren. Zo'n gebod verdwijnt zodra je het "
                "doel laat vallen, en daarom is het bij Kant geen morele plicht."),
    dict(type="meerkeuze",
         vraag="Welke tweede formulering geeft Kant van zijn imperatief?",
         opties=["behandel een mens nooit louter als een middel voor jouw doel",
                 "behandel een mens zoals hij jou ook behandeld heeft",
                 "behandel een mens zoals de wet van je land voorschrijft",
                 "behandel een mens zo dat er zoveel mogelijk geluk uit volgt"],
         antwoord=0,
         uitleg="Een mens is geen instrument. Daarom kan het bij Kant nooit goed zijn om iemand "
                "te gebruiken, ook niet voor een mooi doel."),
    dict(type="meerkeuze",
         vraag="Waarom wordt Kant een moreel universalist genoemd?",
         opties=["zijn regel moet voor alle mensen gelden om een morele regel te zijn",
                 "zijn regel geldt enkel voor wie ze zelf uitdrukkelijk aanvaard heeft",
                 "zijn regel verschilt per cultuur en per tijdvak",
                 "zijn regel geldt enkel binnen de wet van een bepaald land"],
         antwoord=0,
         uitleg="De toets van de algemene wet zit al in zijn imperatief: wat niet voor allen kan "
                "gelden, is geen plicht."),
    dict(type="meerkeuze",
         vraag="Wat staat bij Emmanuel Levinas centraal?",
         opties=["het gelaat van de ander, dat mij aanspreekt en verantwoordelijk maakt",
                 "de algemene wet, die ik met mijn rede kan vinden en toetsen",
                 "de som van het geluk, die ik voor alle betrokkenen moet berekenen",
                 "het karakter, dat ik door jarenlange gewoonte moet vormen"],
         antwoord=0,
         uitleg="Bij hem komt de plicht niet uit een regel maar uit de ontmoeting. De ander gaat "
                "aan mijn afweging vooraf."),
    dict(type="meerkeuze",
         vraag="Wat hebben Kant en Levinas met elkaar gemeen?",
         opties=["bij beiden is de plicht onvoorwaardelijk en geen afweging van gevolgen",
                 "bij beiden volgt de plicht uit een berekening van het geluk",
                 "bij beiden hangt de plicht af van de cultuur waarin je leeft",
                 "bij beiden is de plicht pas geldig zodra je er zelf mee hebt ingestemd"],
         antwoord=0,
         uitleg="Dat is waarom ze bij dezelfde benadering staan. Het verschil zit in waar die "
                "plicht vandaan komt."),
    dict(type="meerkeuze",
         vraag="Waarin verschillen Kant en Levinas?",
         opties=["Kant vertrekt van een algemene regel, Levinas van de ander die voor je staat",
                 "Kant vertrekt van de ander die voor je staat, Levinas van een algemene regel",
                 "Kant rekent de gevolgen mee en Levinas doet dat niet",
                 "Levinas rekent de gevolgen mee en Kant doet dat niet"],
         antwoord=0,
         uitleg="Een regel die je met je rede toetst, tegenover een beroep dat van een concrete "
                "mens uitgaat."),
    dict(type="meerkeuze",
         vraag="Welke kritiek wordt op de plichtethiek van Kant gemaakt?",
         opties=["ze is zo streng dat ze ook in uitzonderlijke gevallen geen leugen toelaat",
                 "ze is zo los dat zowat elke daad er wel ergens mee te verdedigen valt",
                 "ze rekent te veel met gevoelens en te weinig met de rede",
                 "ze laat de gevolgen van een daad volledig de beslissing bepalen"],
         antwoord=0,
         uitleg="Het bekende voorbeeld: liegen tegen iemand die je vriend komt zoeken om hem kwaad "
                "te doen. Een regel zonder uitzondering botst daar met ons gevoel voor wat juist "
                "is."),
    dict(type="meerkeuze",
         vraag="Welke tweede kritiek krijgt Kant?",
         opties=["zijn imperatief zegt welke vorm een regel moet hebben, maar niet wat te doen",
                 "zijn imperatief laat elke uitzondering toe die je er zelf bij wil bedenken",
                 "zijn imperatief geldt enkel voor wie in dezelfde cultuur leeft",
                 "zijn imperatief maakt van het geluk de maatstaf van alles"],
         antwoord=0,
         uitleg="Het is een toets en geen lijst. Of je regel de toets doorstaat, moet je zelf "
                "uitmaken, en dat laat ruimte voor discussie."),
    dict(type="meerkeuze",
         vraag="Je belooft iets, en nakomen blijkt nadelig uit te vallen. Wat zegt de plichtethiek?",
         opties=["de belofte bindt je, ook als ze nadelig uitvalt",
                 "de belofte vervalt zodra ze nadelig uitvalt",
                 "de belofte bindt je alleen als anderen het zien",
                 "de belofte bindt je alleen als je er iets voor terugkrijgt"],
         antwoord=0,
         uitleg="Het verschil met de gevolgenethiek in één voorbeeld: de uitkomst verandert de "
                "plicht niet."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over gevolgenethiek en plichtethiek kloppen?",
         opties=["ze kunnen bij hetzelfde geval tot een tegengesteld besluit komen",
                 "de gevolgenethiek kijkt vooruit, de plichtethiek kijkt naar de regel",
                 "ze komen bij elk geval tot precies hetzelfde besluit",
                 "beide beoordelen een daad uitsluitend op haar uitkomst"],
         antwoord=[0, 1],
         uitleg="De eerste twee. Juist omdat ze kunnen botsen, zijn morele dilemma's zo lastig."),
    dict(type="waarofniet",
         vraag="Categorisch bij Kant betekent: onvoorwaardelijk.",
         antwoord=True,
         uitleg="Waar. Een categorische imperatief geldt zonder als-dan."),
    dict(type="waarofniet",
         vraag="Een hypothetische imperatief geldt onvoorwaardelijk voor alle mensen.",
         antwoord=False,
         uitleg="Niet waar. Die hangt af van een doel dat je wil bereiken, en vervalt met dat doel."),
    dict(type="waarofniet",
         vraag="Volgens Kant mag je een mens nooit louter als middel gebruiken.",
         antwoord=True,
         uitleg="Waar. Dat is de tweede formulering van zijn imperatief."),
    dict(type="waarofniet",
         vraag="Bij Levinas komt de plicht uit een algemene regel die de rede opstelt.",
         antwoord=False,
         uitleg="Niet waar. Bij hem komt ze uit de ontmoeting met het gelaat van de ander."),
    dict(type="invultekst",
         vraag="Hoe heet de onvoorwaardelijke regel van Kant? De ... imperatief",
         antwoord=["categorische"],
         uitleg="Categorisch: zonder voorwaarde."),
    dict(type="invultekst",
         vraag="Hoe heet een gebod dat enkel geldt als je een bepaald doel wil? De ... imperatief",
         antwoord=["hypothetische"],
         uitleg="Wil je dit bereiken, dan moet je dat doen. Bij Kant is dat geen morele plicht."),
    dict(type="invultekst",
         vraag="Welke filosoof geldt als de grondlegger van de plichtethiek?",
         antwoord=["Kant", "Immanuel Kant"],
         uitleg="Zijn categorische imperatief is er het hart van."),
    dict(type="invultekst",
         vraag="Welke filosoof spreekt over het gelaat van de ander?",
         antwoord=["Levinas", "Emmanuel Levinas"],
         uitleg="De verantwoordelijkheid ontstaat bij hem in de ontmoeting."),
]
