# -*- coding: utf-8 -*-
"""De functies van justitie, de rechtspraak en de deontologie.

Het derde thema over recht. De fiche vraagt:

    de functies van justitie herkennen en benoemen: preventie, veiligheid,
        ordehandhaving, conflictbeslechting en bestraffing
    de belangrijkste principes van de hedendaagse rechtspraak: vermoeden van
        onschuld, onafhankelijkheid en onpartijdigheid van de rechters,
        openbaarheid, en hoor en wederhoor
    het verschil tussen deontologie in de welzijnssector en wetgeving
    aspecten van een deontologische code: beroepsgeheim, discretieplicht en
        meldingsplicht, en die herkennen in actuele casussen
    reflecteren over de rol van justitie bij veranderende maatschappelijke
        normen, bij het regelen van ons dagelijks leven en bij meer
        rechtvaardigheid en gelijkheid

Dit thema is voor de richting welzijnswetenschappen het meest praktische van
de acht: een hulpverlener komt het beroepsgeheim en de discretieplicht in zijn
werk elke week tegen. De vragen blijven bij wat algemeen geldt en noemen geen
artikelnummers.

Deel 1 zijn de functies van justitie en de principes van de rechtspraak.
Deel 2 is de deontologie in de welzijnssector.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Welke vijf functies van justitie noemt de fiche?",
         opties=["preventie, veiligheid, ordehandhaving, conflictbeslechting en bestraffing",
                 "preventie, veiligheid, opvoeding, vergelding en schadeherstel voor het slachtoffer",
                 "wetgeving, bestuur, rechtspraak, controle en bemiddeling",
                 "politie, parket, rechtbank, gevangenis en reclassering"],
         antwoord=0,
         uitleg="Vijf taken naast elkaar. Straffen is er maar één van, en zeker niet de eerste."),
    dict(type="meerkeuze",
         vraag="Wat betekent de functie preventie?",
         opties=["voorkomen dat er misdrijven en conflicten ontstaan",
                 "een dader straffen zodat hij het niet opnieuw doet",
                 "een conflict tussen twee burgers beslechten",
                 "de orde op straat herstellen na een incident"],
         antwoord=0,
         uitleg="Dat de wet bestaat en dat overtredingen gevolgen hebben, houdt al veel mensen "
                "tegen. Dat werk is onzichtbaar, maar het is er."),
    dict(type="meerkeuze",
         vraag="Wat betekent de functie conflictbeslechting?",
         opties=["een geschil tussen partijen met een beslissing afsluiten",
                 "een dader een passende straf opleggen voor wat hij gedaan heeft",
                 "de orde op straat herstellen na een betoging",
                 "voorkomen dat er nieuwe geschillen ontstaan"],
         antwoord=0,
         uitleg="Zonder rechter zou een geschil blijven duren of met geweld eindigen. Daarom hoort "
                "beslechten bij de kerntaken."),
    dict(type="meerkeuze",
         vraag="Wat is het vermoeden van onschuld?",
         opties=["je bent onschuldig tot een rechter je schuld heeft vastgesteld",
                 "je bent schuldig tot je je eigen onschuld hebt bewezen",
                 "je bent onschuldig zolang de politie je niet verhoord heeft",
                 "je bent onschuldig zolang de pers je naam niet genoemd heeft"],
         antwoord=0,
         uitleg="Het bewijs moet van wie vervolgt komen, niet van wie beschuldigd wordt. Twijfel "
                "valt in het voordeel van de beklaagde uit."),
    dict(type="meerkeuze",
         vraag="Wat betekent hoor en wederhoor?",
         opties=["elke partij krijgt de kans om op de argumenten van de andere te antwoorden",
                 "elke partij moet door twee verschillende rechters gehoord worden",
                 "elke getuige moet twee keer in de rechtszaal komen verklaren",
                 "elke beslissing moet door een hoger rechtscollege herhaald worden"],
         antwoord=0,
         uitleg="Zonder dat kan een rechter maar één kant van een verhaal kennen, en dat is per "
                "definitie te weinig."),
    dict(type="meerkeuze",
         vraag="Wat betekent openbaarheid van de rechtspraak?",
         opties=["een zitting en een uitspraak zijn in beginsel voor iedereen toegankelijk",
                 "elk dossier van het parket kan door iedereen worden opgevraagd",
                 "elke rechter moet zijn beslissing in de krant laten publiceren",
                 "elke burger mag bij de beraadslaging van de rechters aanwezig zijn"],
         antwoord=0,
         uitleg="Wat in het openbaar gebeurt, is te controleren. In het belang van een kind of "
                "van de privacy kan een zitting wel met gesloten deuren plaatsvinden."),
    dict(type="meerkeuze",
         vraag="Een krant noemt een verdachte al een dader voor zijn proces. Welk principe staat "
               "onder druk?",
         opties=["het vermoeden van onschuld", "de openbaarheid",
                 "het hoor en wederhoor", "de territoriale bevoegdheid"],
         antwoord=0,
         uitleg="Dit is wat men trial by media noemt, en het staat in de fiche bij de actuele "
                "thema's."),
    dict(type="meerkeuze",
         vraag="Welke rol speelt justitie bij veranderende maatschappelijke normen?",
         opties=["ze volgt die veranderingen en legt ze geleidelijk in regels vast",
                 "ze houdt elke verandering in de samenleving tegen",
                 "ze beslist in de plaats van het parlement welke normen gelden",
                 "ze staat volledig buiten wat er in de samenleving verandert"],
         antwoord=0,
         uitleg="Wat vroeger strafbaar was, is dat vandaag soms niet meer, en omgekeerd. Recht en "
                "samenleving bewegen samen, al loopt het recht meestal achter."),
    dict(type="meerkeuze",
         vraag="Welke rol speelt justitie in ons dagelijks leven?",
         opties=["ze regelt stil veel meer dan je merkt, van huren tot erven",
                 "ze komt enkel in beeld bij een misdrijf en nergens anders",
                 "ze bemoeit zich niet met afspraken tussen burgers onderling",
                 "ze geldt alleen voor wie ooit met de politie te maken heeft gehad"],
         antwoord=0,
         uitleg="Een huurcontract, een aankoop, een scheiding, een nalatenschap: het recht zit in "
                "duizend gewone dingen zonder dat er een rechter aan te pas komt."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over de functies van justitie kloppen?",
         opties=["bestraffen is maar één van de vijf functies",
                 "preventie werkt al doordat de regel bestaat en gevolgen heeft",
                 "conflictbeslechting komt enkel in strafzaken voor",
                 "veiligheid is de enige functie die de fiche noemt"],
         antwoord=[0, 1],
         uitleg="De eerste twee. Conflictbeslechting is net typisch voor het burgerlijk recht."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over de principes van de rechtspraak kloppen?",
         opties=["openbaarheid is de regel, met uitzonderingen voor bijzondere belangen",
                 "het vermoeden van onschuld legt de bewijslast bij wie vervolgt",
                 "hoor en wederhoor betekent dat elke zaak twee keer behandeld wordt",
                 "de onpartijdigheid van een rechter hangt af van het soort zaak"],
         antwoord=[0, 1],
         uitleg="De eerste twee. Hoor en wederhoor gaat over antwoorden kunnen geven, niet over "
                "een tweede behandeling."),
    dict(type="meerkeuze",
         vraag="Hoe draagt justitie bij aan meer rechtvaardigheid en gelijkheid?",
         opties=["ze behandelt iedereen volgens dezelfde regels, ongeacht wie hij is",
                 "ze geeft de zwakste partij in een geschil altijd gelijk",
                 "ze zorgt dat iedereen in de samenleving hetzelfde inkomen heeft",
                 "ze laat elke burger zijn eigen rechter kiezen"],
         antwoord=0,
         uitleg="Gelijkheid voor de wet is de belofte. Dat die in de praktijk niet altijd uitkomt, "
                "is precies waarover de fiche je laat nadenken."),
    dict(type="waarofniet",
         vraag="Bestraffen is maar een van de vijf functies van justitie.",
         antwoord=True,
         uitleg="Waar. Preventie, veiligheid, ordehandhaving en conflictbeslechting staan er "
                "naast."),
    dict(type="waarofniet",
         vraag="Het vermoeden van onschuld betekent dat je je onschuld moet bewijzen.",
         antwoord=False,
         uitleg="Niet waar. Het bewijs moet komen van wie vervolgt; twijfel valt in jouw voordeel "
                "uit."),
    dict(type="waarofniet",
         vraag="Hoor en wederhoor betekent dat elke partij op de andere kan antwoorden.",
         antwoord=True,
         uitleg="Waar. Een rechter die maar één kant hoort, weet te weinig."),
    dict(type="waarofniet",
         vraag="Een zitting kan nooit met gesloten deuren plaatsvinden.",
         antwoord=False,
         uitleg="Niet waar. Openbaarheid is de regel, maar het belang van een kind of de privacy "
                "kan een uitzondering rechtvaardigen."),
    dict(type="invultekst",
         vraag="Welk principe zegt dat je onschuldig bent tot een rechter anders beslist? Het "
               "vermoeden van ...",
         antwoord=["onschuld"],
         uitleg="De bewijslast ligt bij wie vervolgt."),
    dict(type="invultekst",
         vraag="Welk principe geeft elke partij de kans om op de andere te antwoorden? Hoor en ...",
         antwoord=["wederhoor"],
         uitleg="Zonder dat kent een rechter maar één kant van het verhaal."),
    dict(type="invultekst",
         vraag="Welke functie van justitie wil misdrijven voorkomen? De ...",
         antwoord=["preventie"],
         uitleg="Het werk dat je niet ziet omdat het lukt."),
    dict(type="invultekst",
         vraag="Welke functie van justitie sluit een geschil tussen partijen af? De ...",
         antwoord=["conflictbeslechting"],
         uitleg="Typisch voor het burgerlijk recht."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is deontologie?",
         opties=["de beroepsregels die een beroepsgroep voor zichzelf opstelt",
                 "de wetten die een parlement voor alle burgers maakt",
                 "de rechtspraak over geschillen binnen een beroep",
                 "de leer over wat goed handelen in het algemeen is"],
         antwoord=0,
         uitleg="Elke beroepsgroep heeft eigen vragen. Een hulpverlener, een arts en een advocaat "
                "hebben elk hun code."),
    dict(type="meerkeuze",
         vraag="Wat is het belangrijkste verschil tussen deontologie en wetgeving?",
         opties=["een wet geldt voor iedereen, een code geldt binnen een beroep",
                 "een wet geldt binnen een beroep, een code geldt voor iedereen",
                 "een wet is strenger dan een code, in elk geval en altijd",
                 "een wet is door een beroepsgroep gemaakt en een code door het parlement"],
         antwoord=0,
         uitleg="Een wet komt van de wetgever en bindt elke burger. Een code komt van het beroep "
                "zelf en zegt hoe je je werk hoort te doen."),
    dict(type="meerkeuze",
         vraag="Wat kan er gebeuren als iemand zijn deontologische code schendt?",
         opties=["hij kan door zijn beroepsorde of zijn werkgever gesanctioneerd worden",
                 "hij kan nooit ergens op aangesproken worden, want het is geen wet",
                 "hij krijgt altijd meteen een gevangenisstraf van een rechter",
                 "hij moet verplicht van beroep veranderen"],
         antwoord=0,
         uitleg="Een code is geen strafwet, maar hij is ook niet zonder gevolgen. Soms valt "
                "hetzelfde gedrag onder beide, zoals bij het beroepsgeheim."),
    dict(type="meerkeuze",
         vraag="Wat is het beroepsgeheim?",
         opties=["wat iemand je in vertrouwen vertelt, mag je niet verder vertellen",
                 "wat je op je werk hoort, mag je enkel aan je collega's vertellen",
                 "wat je op je werk hoort, mag je na een jaar wel vertellen",
                 "wat je cliënt je vertelt, moet je altijd aan de politie melden"],
         antwoord=0,
         uitleg="Zonder die zekerheid durft niemand hulp te zoeken. Daarom staat het voor "
                "sommige beroepen ook in de wet, met een straf erop."),
    dict(type="meerkeuze",
         vraag="Wat is de discretieplicht?",
         opties=["de plicht om terughoudend te zijn over alles wat je op je werk verneemt",
                 "de plicht om elk gesprek met een cliënt schriftelijk vast te leggen",
                 "de plicht om je cliënt te melden wat je over hem weet",
                 "de plicht om zware feiten aan het parket te signaleren"],
         antwoord=0,
         uitleg="Ruimer dan het beroepsgeheim en minder streng: ze gaat ook over wat je toevallig "
                "hoort over een collega of een dossier dat niet het jouwe is."),
    dict(type="meerkeuze",
         vraag="Wat is de meldingsplicht?",
         opties=["in bepaalde ernstige situaties moet je spreken in plaats van zwijgen",
                 "in alle situaties moet je alles aan je overste doorgeven",
                 "in geen enkele situatie mag je iets doorgeven",
                 "in bepaalde situaties mag je een dossier weigeren"],
         antwoord=0,
         uitleg="Wie een kind in acuut gevaar ziet en niets doet, kan zich niet achter het "
                "beroepsgeheim verschuilen. Hulp weigeren aan iemand in groot gevaar is strafbaar."),
    dict(type="meerkeuze",
         vraag="Een hulpverlener hoort van een kind dat het thuis geslagen wordt en dat het "
               "vanavond opnieuw dreigt te gebeuren. Wat is hier aan de orde?",
         opties=["de meldingsplicht, want er is ernstig en dreigend gevaar",
                 "enkel het beroepsgeheim, dus zwijgen is de enige weg",
                 "enkel de discretieplicht, dus het mag onder collega's blijven",
                 "niets bijzonders, want het is een zaak van het gezin alleen"],
         antwoord=0,
         uitleg="Het beroepsgeheim is geen vrijgeleide om weg te kijken. Bij ernstig en dreigend "
                "gevaar mag en moet een hulpverlener spreken."),
    dict(type="meerkeuze",
         vraag="Een medewerker vertelt op een feestje over het dossier van een cliënt, zonder "
               "diens naam. Wat is hier aan de orde?",
         opties=["de discretieplicht, want ook zonder naam hoort dit er niet",
                 "niets, want zonder naam kan niemand weten over wie het gaat",
                 "de meldingsplicht, want hij geeft informatie door",
                 "de openbaarheid, want iedereen mag het weten"],
         antwoord=0,
         uitleg="Details maken een mens vaak herkenbaar, ook zonder zijn naam. En wie dit hoort, "
                "weet voortaan dat je over je cliënten praat."),
    dict(type="meerkeuze",
         vraag="Waarom bestaat het beroepsgeheim?",
         opties=["zonder die zekerheid zou niemand nog durven om hulp te vragen",
                 "zonder die zekerheid zou een hulpverlener te veel werk hebben",
                 "zonder die zekerheid zou de politie niets meer te doen hebben",
                 "zonder die zekerheid zou een dossier niet bij te houden zijn"],
         antwoord=0,
         uitleg="Het geheim beschermt niet de hulpverlener maar wie hulp zoekt. Dat is het hele "
                "punt ervan."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over het beroepsgeheim en de discretieplicht kloppen?",
         opties=["het beroepsgeheim is strenger en voor sommige beroepen in de wet opgenomen",
                 "de discretieplicht is ruimer en gaat over alles wat je op je werk verneemt",
                 "beide verbieden je om ooit iets aan iemand te melden",
                 "beide staan voor elk beroep in de strafwet opgeschreven"],
         antwoord=[0, 1],
         uitleg="De eerste twee. Het beroepsgeheim kent uitzonderingen, en net die maken de "
                "casussen zo moeilijk."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over deontologie en wetgeving kloppen?",
         opties=["dezelfde handeling kan tegelijk tegen de code en tegen de wet ingaan",
                 "een code zegt hoe je je werk hoort te doen binnen je beroep",
                 "een code vervangt de wet voor wie dat beroep uitoefent",
                 "wie zich aan de code houdt, staat automatisch buiten de wet"],
         antwoord=[0, 1],
         uitleg="De eerste twee. Een code komt bovenop de wet en nooit in haar plaats."),
    dict(type="meerkeuze",
         vraag="Waarom is een deontologische code nooit een lijst met kant-en-klare antwoorden?",
         opties=["plichten kunnen in één situatie tegen elkaar in gaan",
                 "een code wordt elk jaar helemaal opnieuw geschreven",
                 "een code geldt enkel voor wie hem ondertekend heeft",
                 "een code heeft geen enkel gevolg voor wie hem schendt"],
         antwoord=0,
         uitleg="Zwijgen en melden kunnen elkaar in dezelfde casus tegenspreken. Daarom vraagt een "
                "code altijd nog een afweging."),
    dict(type="waarofniet",
         vraag="Een deontologische code komt van de beroepsgroep zelf en niet van het parlement.",
         antwoord=True,
         uitleg="Waar. Daarin verschilt ze van een wet."),
    dict(type="waarofniet",
         vraag="De discretieplicht is strenger dan het beroepsgeheim.",
         antwoord=False,
         uitleg="Niet waar. Ze is ruimer maar minder streng; het beroepsgeheim is het strengst."),
    dict(type="waarofniet",
         vraag="Het beroepsgeheim beschermt in de eerste plaats wie hulp zoekt.",
         antwoord=True,
         uitleg="Waar. Zonder die zekerheid durft niemand nog iets te vertellen."),
    dict(type="waarofniet",
         vraag="Bij ernstig en dreigend gevaar moet een hulpverlener altijd blijven zwijgen.",
         antwoord=False,
         uitleg="Niet waar. Dan geldt de meldingsplicht, en hulp weigeren aan iemand in groot "
                "gevaar is strafbaar."),
    dict(type="invultekst",
         vraag="Hoe heet de plicht om niet verder te vertellen wat iemand je in vertrouwen zei? "
               "Het ...",
         antwoord=["beroepsgeheim"],
         uitleg="Voor sommige beroepen staat het ook in de wet."),
    dict(type="invultekst",
         vraag="Hoe heet de plicht om terughoudend te zijn over alles wat je op je werk verneemt? "
               "De ...",
         antwoord=["discretieplicht"],
         uitleg="Ruimer dan het beroepsgeheim, en minder streng."),
    dict(type="invultekst",
         vraag="Hoe heet de plicht om bij ernstig gevaar te spreken? De ...",
         antwoord=["meldingsplicht"],
         uitleg="Het beroepsgeheim is geen vrijgeleide om weg te kijken."),
    dict(type="invultekst",
         vraag="Hoe noem je de beroepsregels van een beroepsgroep? De ...",
         antwoord=["deontologie", "deontologische code"],
         uitleg="Ze komt van het beroep zelf en komt bovenop de wet."),
]
