# -*- coding: utf-8 -*-
"""Cultuur en natuur: mens, dier en machine.

Het tweede van vier thema's over wijsgerige antropologie. De fiche vraagt
vier dingen:

    waarom bepaalde eigenschappen exclusief menselijk kunnen zijn, met
        emoties en rede als mogelijke eigenschappen
    reflecteren over emoties vanuit de naturalistische, de cultureel en
        historische en de cognitieve benadering
    de basisideeën van filosofen over het verschil tussen mens en dier:
        Aristoteles, René Descartes, Friedrich Nietzsche
    reflecteren over het verschil tussen mens en machine op basis van
        bewustzijn: Julien Offray de La Mettrie en Dick Swaab

Van die vijf denkers geeft de fiche enkel de namen. Daarom blijft hier bij
elke naam alleen staan wat hij in dít debat heeft bijgedragen en wat algemeen
bekend is: Aristoteles de mens als redelijk dier, Descartes het dier zonder
denkende geest, Nietzsche de mens die geen plaats boven de natuur krijgt,
La Mettrie de mens als machine, Swaab het bewustzijn als werk van de
hersenen. Er is geen citaat, geen boektitel en geen experiment aan een naam
gehangen die de fiche niet noemt.

Deel 1 zijn de exclusief menselijke eigenschappen en de drie benaderingen
van emoties.
Deel 2 zijn mens en dier, en mens en machine.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat betekent het als je zegt dat een eigenschap exclusief menselijk is?",
         opties=["die eigenschap komt bij mensen voor en bij geen enkel ander wezen",
                 "die eigenschap komt bij alle mensen voor, en bij sommige dieren ook wel",
                 "die eigenschap komt bij mensen vaker voor dan bij de meeste dieren",
                 "die eigenschap is bij mensen beter ontwikkeld dan bij dieren en machines"],
         antwoord=0,
         uitleg="Exclusief wil zeggen: uitsluitend. Niet meer, niet beter, maar alleen bij ons."),
    dict(type="meerkeuze",
         vraag="Welke twee eigenschappen noemt de fiche als mogelijk exclusief menselijk?",
         opties=["emoties en rede",
                 "taal en techniek, net als bij de meeste gereedschapsmakers",
                 "pijn en plezier, de twee gevoelens die alles in beweging zetten",
                 "groei en voortplanting, twee kenmerken van alles wat leeft"],
         antwoord=0,
         uitleg="Emoties en rede. Let op het woordje mogelijk: juist of een van die twee écht "
                "alleen bij ons voorkomt, is de vraag van dit thema."),
    dict(type="meerkeuze",
         vraag="Waarom is het moeilijk om emoties exclusief menselijk te noemen?",
         opties=["ook dieren vertonen angst, woede en wat op rouw lijkt",
                 "emoties zijn bij mensen onderling te verschillend om te vergelijken",
                 "emoties zijn niet te meten en dus ook niet te bespreken in de filosofie",
                 "emoties komen bij mensen pas voor na de puberteit en bij dieren nooit"],
         antwoord=0,
         uitleg="Wie een hond in paniek heeft gezien, kan moeilijk beweren dat emoties alleen bij "
                "mensen bestaan. Daarom schuift de discussie naar de vraag of wij ze anders "
                "ervaren."),
    dict(type="meerkeuze",
         vraag="Welk argument wordt gebruikt om de rede wél exclusief menselijk te noemen?",
         opties=["mensen kunnen over hun eigen denken nadenken en redenen afwegen",
                 "mensen kunnen leren van wat hun vorige poging heeft opgeleverd",
                 "mensen kunnen werktuigen gebruiken om bij hun voedsel te komen",
                 "mensen kunnen samenwerken in groepen die groter zijn dan een gezin"],
         antwoord=0,
         uitleg="De andere drie kennen we ook bij dieren. Nadenken over je eigen denken en je "
                "redenen tegen elkaar afwegen is wat men typisch menselijk noemt."),
    dict(type="meerkeuze",
         vraag="Wat zegt de naturalistische benadering van emoties?",
         opties=["emoties zijn aangeboren en lichamelijk, en komen overal ter wereld voor",
                 "emoties worden geleerd en verschillen per cultuur en per tijdvak",
                 "emoties ontstaan uit het oordeel dat je over een situatie velt",
                 "emoties bestaan niet echt; het zijn namen die wij aan gedrag geven"],
         antwoord=0,
         uitleg="Natuur, dus: emoties horen bij ons lichaam, zijn er van bij de geboorte en zijn "
                "bij alle mensen in grote lijnen hetzelfde."),
    dict(type="meerkeuze",
         vraag="Wat zegt de cultureel en historische benadering van emoties?",
         opties=["welke emoties je voelt en toont, leer je van je omgeving en je tijd",
                 "welke emoties je voelt, ligt vast in je lichaam en verandert niet",
                 "welke emoties je voelt, volgt uit hoe je een situatie beoordeelt",
                 "welke emoties je voelt, kan niemand ooit van buitenaf vaststellen"],
         antwoord=0,
         uitleg="Deze benadering kijkt naar verschillen: wat in de ene cultuur of de ene eeuw "
                "gepast is om te voelen en te tonen, is dat elders niet."),
    dict(type="meerkeuze",
         vraag="Wat zegt de cognitieve benadering van emoties?",
         opties=["een emotie hangt samen met wat je over een situatie denkt",
                 "een emotie hangt samen met wat je lichaam aangeboren meebrengt",
                 "een emotie hangt samen met wat je cultuur je heeft aangeleerd",
                 "een emotie hangt samen met hoeveel slaap je die nacht hebt gehad"],
         antwoord=0,
         uitleg="Cognitie is kennen en denken. Verander je oordeel over wat er gebeurt en de "
                "emotie verandert mee."),
    dict(type="meerkeuze",
         vraag="Je schrikt van een harde knal, en je lacht als blijkt dat het een ballon was. "
               "Welke benadering verklaart dat omslaan het best?",
         opties=["de cognitieve benadering, want je oordeel over de situatie veranderde",
                 "de naturalistische benadering, want je schrik was aangeboren",
                 "de cultureel en historische benadering, want lachen is aangeleerd",
                 "geen van de drie, want schrikken is geen echte emotie"],
         antwoord=0,
         uitleg="Het geluid bleef hetzelfde; wat veranderde, was wat je erover dacht. Dat is "
                "precies waar de cognitieve benadering op wijst."),
    dict(type="meerkeuze",
         vraag="In het ene land huilen mensen luid op een begrafenis, in het andere hoort stilte. "
               "Welke benadering verklaart dat het best?",
         opties=["de cultureel en historische benadering",
                 "de naturalistische benadering",
                 "de cognitieve benadering",
                 "geen van de drie benaderingen"],
         antwoord=0,
         uitleg="Het verdriet is hetzelfde, de manier om het te laten zien is geleerd. Dat is het "
                "terrein van de cultureel en historische benadering."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over de drie benaderingen kloppen?",
         opties=["ze kunnen elkaar aanvullen in plaats van elkaar uit te sluiten",
                 "de naturalistische benadering legt het meeste gewicht bij het lichaam",
                 "alle drie ontkennen dat emoties met het lichaam te maken hebben",
                 "alle drie zeggen dat emoties volledig vastliggen bij de geboorte"],
         antwoord=[0, 1],
         uitleg="De eerste twee. Dat een emotie lichamelijk begint, dat je leert hoe je ze toont "
                "en dat je oordeel meespeelt, kan alle drie tegelijk waar zijn."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over de verhouding tussen natuur en cultuur kloppen?",
         opties=["ons lichaam legt grenzen vast waarbinnen cultuur van alles mogelijk maakt",
                 "wat natuur is en wat cultuur, valt bij mensen moeilijk uit elkaar te halen",
                 "cultuur bij mensen staat volledig los van alles wat lichamelijk is",
                 "alles wat mensen doen is natuur, want wij zijn nu eenmaal dieren"],
         antwoord=[0, 1],
         uitleg="De eerste twee. De scherpe tweedeling natuur tegenover cultuur houdt bij de mens "
                "nergens helemaal stand."),
    dict(type="meerkeuze",
         vraag="Waarom is de vraag naar exclusief menselijke eigenschappen een filosofische vraag?",
         opties=["ze gaat niet alleen over feiten maar ook over wat de mens tot mens maakt",
                 "ze is nog nooit onderzocht door iemand uit de natuurwetenschappen",
                 "ze kan enkel beantwoord worden door iemand die filosofie studeerde",
                 "ze hangt helemaal af van de mening die jij er zelf toevallig over hebt"],
         antwoord=0,
         uitleg="Vaststellen wat dieren kunnen, is onderzoek. Beslissen wat van die verschillen "
                "echt telt, is een vraag over begrippen en waarden."),
    dict(type="waarofniet",
         vraag="Exclusief menselijk wil zeggen: bij de mens sterker ontwikkeld dan bij dieren.",
         antwoord=False,
         uitleg="Niet waar. Exclusief is uitsluitend: bij de mens en bij geen enkel ander wezen."),
    dict(type="waarofniet",
         vraag="De naturalistische benadering ziet emoties als aangeboren en lichamelijk.",
         antwoord=True,
         uitleg="Waar. Daarom verwacht ze dezelfde basisemoties bij mensen over de hele wereld."),
    dict(type="waarofniet",
         vraag="Volgens de cognitieve benadering staat een emotie los van wat je denkt.",
         antwoord=False,
         uitleg="Niet waar. Juist omgekeerd: je oordeel over de situatie bepaalt mee welke emotie "
                "je voelt."),
    dict(type="waarofniet",
         vraag="De drie benaderingen van emoties kunnen elkaar aanvullen.",
         antwoord=True,
         uitleg="Waar. Lichaam, cultuur en oordeel kunnen alle drie meespelen in één emotie."),
    dict(type="invultekst",
         vraag="Welke benadering ziet emoties als aangeboren en lichamelijk? De ...",
         antwoord=["naturalistische benadering", "naturalistische"],
         uitleg="Natuur: emoties horen bij ons lichaam en komen overal voor."),
    dict(type="invultekst",
         vraag="Welke benadering zegt dat je leert welke emoties je mag tonen? De ...",
         antwoord=["culturele benadering", "cultureel-historische", "culturele"],
         uitleg="De cultureel en historische benadering kijkt naar verschillen tussen culturen en "
                "tijdvakken."),
    dict(type="invultekst",
         vraag="Welke benadering verbindt een emotie met je oordeel over de situatie? De ...",
         antwoord=["cognitieve benadering", "cognitieve"],
         uitleg="Cognitie is kennen en denken."),
    dict(type="invultekst",
         vraag="Welke eigenschap wordt naast emoties genoemd als mogelijk exclusief menselijk?",
         antwoord=["de rede", "rede"],
         uitleg="De rede: kunnen nadenken over je eigen denken en je redenen afwegen."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Hoe onderscheidt Aristoteles de mens van het dier?",
         opties=["de mens is een dier dat over rede beschikt",
                 "de mens is een dier dat zijn omgeving met werktuigen verandert",
                 "de mens is een dier zonder instincten en daarom vrij in zijn keuzes",
                 "de mens is geen dier, want hij heeft een onsterfelijke ziel gekregen"],
         antwoord=0,
         uitleg="Bij Aristoteles hoort de mens volop bij de dieren, maar is hij het dier met rede. "
                "Het verschil is een verschil binnen de natuur, niet erbuiten."),
    dict(type="meerkeuze",
         vraag="Waarom past dat onderscheid bij zijn visie op lichaam en ziel?",
         opties=["de rede hoort bij wat de mens is, niet bij iets dat los van hem bestaat",
                 "de rede komt van buiten de natuur in het lichaam terecht",
                 "de rede is een aparte stof die in de hersenen van de mens zit",
                 "de rede bestaat enkel bij mensen die er zelf voor gekozen hebben"],
         antwoord=0,
         uitleg="Bij Aristoteles is de ziel de vorm van het lichaam. De rede is dus geen vreemde "
                "gast in het lichaam, maar een kenmerk van dit soort wezen."),
    dict(type="meerkeuze",
         vraag="Hoe ziet René Descartes het verschil tussen mens en dier?",
         opties=["een dier werkt als een machine, de mens heeft daarnaast een denkende geest",
                 "een dier en de mens zijn beide machines, zonder verschil tussen hen",
                 "een dier heeft net als de mens een denkende geest, maar een veel kleinere",
                 "een dier heeft een ziel en de mens niet, want de mens heeft de rede"],
         antwoord=0,
         uitleg="Dat volgt uit zijn dualisme: wie geen denkende werkelijkheid heeft, blijft "
                "uitgebreide stof, en stof werkt mechanisch."),
    dict(type="meerkeuze",
         vraag="Welk bezwaar wordt tegen de visie van Descartes op dieren gemaakt?",
         opties=["wie een dier van pijn ziet kermen, kan het moeilijk een machine noemen",
                 "machines bestonden in zijn tijd nog niet, dus kon hij er niets over zeggen",
                 "hij had zelf geen huisdier en kon er dus niet over meespreken",
                 "dieren hebben wel hersenen, en hersenen heeft een machine nooit"],
         antwoord=0,
         uitleg="Het klassieke bezwaar gaat over gevoel. Als een dier niets ervaart, waarom "
                "gedraagt het zich dan precies zoals een wezen dat pijn heeft?"),
    dict(type="meerkeuze",
         vraag="Wat is de inzet van Friedrich Nietzsche in dit debat?",
         opties=["hij weigert de mens een ereplaats boven de natuur te geven",
                 "hij bewijst dat de rede de mens boven elk dier verheft",
                 "hij toont aan dat dieren precies hetzelfde denken als mensen",
                 "hij laat zien dat de mens een machine is zonder bewustzijn"],
         antwoord=0,
         uitleg="Nietzsche keert zich tegen het vleiende zelfbeeld waarin de mens door zijn rede "
                "buiten en boven de natuur staat. De mens hoort er helemaal bij."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over Aristoteles, Descartes en Nietzsche kloppen?",
         opties=["Descartes zet de scherpste grens tussen mens en dier",
                 "Nietzsche zet de mens het dichtst bij de rest van de natuur",
                 "alle drie vinden dat dieren precies hetzelfde zijn als mensen",
                 "alle drie noemen de rede het enige verschil dat echt bestaat"],
         antwoord=[0, 1],
         uitleg="De eerste twee. Aristoteles staat ertussen: een verschil binnen de natuur, geen "
                "kloof."),
    dict(type="meerkeuze",
         vraag="Wat is de stelling van Julien Offray de La Mettrie?",
         opties=["de mens is een machine; voor zijn denken is geen aparte ziel nodig",
                 "de mens is geen machine, want zijn ziel bestuurt zijn lichaam",
                 "de mens is een machine, maar enkel zijn lichaam en niet zijn geest",
                 "de mens lijkt op een machine, maar bezit daarnaast een onsterfelijke ziel"],
         antwoord=0,
         uitleg="La Mettrie trekt het mechanische beeld dat Descartes voor dieren gebruikte, door "
                "tot bij de mens zelf. Dat is een materialistische visie."),
    dict(type="meerkeuze",
         vraag="Wat is de stelling van Dick Swaab?",
         opties=["wat wij ons zelf noemen, is het werk van onze hersenen",
                 "onze hersenen zijn een werktuig dat onze geest gebruikt",
                 "ons bewustzijn bestaat los van ons lichaam en overleeft het",
                 "onze hersenen kunnen bewustzijn nooit voortbrengen of verklaren"],
         antwoord=0,
         uitleg="Swaab staat in deze fiche voor de visie dat bewustzijn hersenwerk is: wij zijn "
                "ons brein."),
    dict(type="meerkeuze",
         vraag="Waarom staan La Mettrie en Swaab in hetzelfde rijtje?",
         opties=["beiden verklaren de mens vanuit stof, zonder een aparte geest aan te nemen",
                 "beiden verdedigen dat de mens een onsterfelijke ziel bezit",
                 "beiden vinden dat machines nooit bewustzijn kunnen hebben",
                 "beiden leefden in dezelfde eeuw en hebben elkaars boeken goed gekend"],
         antwoord=0,
         uitleg="De een spreekt over een machine, de ander over hersenen, maar de richting is "
                "dezelfde: geest hoeft niet van een andere orde te zijn. Ze leefden eeuwen apart."),
    dict(type="meerkeuze",
         vraag="Waarom gebruikt men bewustzijn als maatstaf om mens en machine te onderscheiden?",
         opties=["een machine kan gedrag tonen, maar of ze iets ervaart is de echte vraag",
                 "een machine kan nooit sneller rekenen dan een mens dat kan",
                 "een machine heeft geen stroom nodig en een mens wel voedsel",
                 "een machine kan geen enkele taak overnemen van een mens"],
         antwoord=0,
         uitleg="Wat een machine kán, schuift voortdurend op. Of er iets is dat het is om die "
                "machine te zijn, is de vraag die blijft."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over het debat mens en machine kloppen?",
         opties=["gedrag dat op bewustzijn lijkt, bewijst nog niet dat er bewustzijn is",
                 "de vraag of een machine iets ervaart is van buitenaf moeilijk te beslechten",
                 "zodra een machine een gesprek kan voeren, heeft ze bewustzijn",
                 "de vraag is al beslecht sinds er machines bestaan die kunnen praten"],
         antwoord=[0, 1],
         uitleg="De eerste twee. Dat is precies de reden waarom dit een filosofische vraag blijft "
                "en niet alleen een technische."),
    dict(type="meerkeuze",
         vraag="Iemand zegt: mijn keuze voor dit bericht zat al in mijn hersenen voor ik het wist. "
               "Bij welke denker uit dit thema sluit dat aan?",
         opties=["bij Dick Swaab", "bij Aristoteles",
                 "bij Friedrich Nietzsche", "bij geen van hen"],
         antwoord=0,
         uitleg="Wie zichzelf met zijn hersenen laat samenvallen, spreekt in de lijn van Swaab."),
    dict(type="waarofniet",
         vraag="Volgens Aristoteles is de mens een dier dat over rede beschikt.",
         antwoord=True,
         uitleg="Waar. Het verschil met het dier is bij hem een verschil binnen de natuur."),
    dict(type="waarofniet",
         vraag="Volgens Descartes hebben dieren naast hun lichaam ook een denkende geest.",
         antwoord=False,
         uitleg="Niet waar. Bij Descartes werkt een dier mechanisch; de denkende geest houdt hij "
                "voor de mens."),
    dict(type="waarofniet",
         vraag="Nietzsche wil de mens juist niet boven de natuur plaatsen.",
         antwoord=True,
         uitleg="Waar. Hij keert zich tegen het zelfbeeld waarin de rede ons buiten de natuur zet."),
    dict(type="waarofniet",
         vraag="La Mettrie heeft een aparte, onstoffelijke ziel nodig om de mens te verklaren.",
         antwoord=False,
         uitleg="Niet waar. Zijn stelling is net dat het zonder kan: de mens als machine."),
    dict(type="invultekst",
         vraag="Welke filosoof noemt de mens een dier met rede?",
         antwoord=["Aristoteles"],
         uitleg="Bij hem hoort de mens bij de dieren, met de rede als zijn kenmerk."),
    dict(type="invultekst",
         vraag="Welke filosoof beschouwt een dier als een machine zonder denkende geest?",
         antwoord=["Descartes", "René Descartes"],
         uitleg="Dat volgt uit zijn dualisme: zonder denkende werkelijkheid blijft er stof over."),
    dict(type="invultekst",
         vraag="Welke denker verdedigt de mens als een machine?",
         antwoord=["La Mettrie", "de La Mettrie"],
         uitleg="La Mettrie trekt het mechanische beeld door tot bij de mens zelf."),
    dict(type="invultekst",
         vraag="Welke denker staat voor de stelling dat wij ons brein zijn?",
         antwoord=["Swaab", "Dick Swaab"],
         uitleg="Bij Swaab is bewustzijn het werk van de hersenen."),
]
