# -*- coding: utf-8 -*-
"""De scheiding der machten en de rechterlijke macht.

Het tweede thema over recht. De fiche vraagt:

    het begrip scheiding der machten uitleggen als belangrijk principe
    de politieke instituties en hun functie benoemen: wetgevende macht met de
        parlementen, uitvoerende macht met de regeringen, rechterlijke macht
        met de hoven en rechtbanken
    het belang van de scheiding der machten voor een democratische samenleving
    de controle en het evenwicht tussen de drie machten
    de onafhankelijkheid en de onpartijdigheid van de rechterlijke macht
    schendingen van de scheiding der machten

De voorbeelden hieronder zijn Belgisch, want dat is het land waarin het examen
afgelegd wordt: het federale parlement, de regeringen, de hoven en
rechtbanken, het Grondwettelijk Hof en de Raad van State.

Deel 1 zijn de drie machten, hun instellingen en waarom ze gescheiden zijn.
Deel 2 zijn de controle en het evenwicht, de rechterlijke macht en de
schendingen.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat betekent de scheiding der machten?",
         opties=["wetten maken, wetten uitvoeren en recht spreken liggen in verschillende handen",
                 "wetten maken, wetten uitvoeren en recht spreken liggen bij dezelfde instelling",
                 "elke provincie krijgt haar eigen wetten, regering en rechtbanken",
                 "elke burger mag kiezen door welke macht hij bestuurd wil worden"],
         antwoord=0,
         uitleg="Drie taken, drie plaatsen. Zo kan niemand tegelijk de regel maken, hem toepassen "
                "en over zijn eigen fouten oordelen."),
    dict(type="meerkeuze",
         vraag="Welke filosoof wordt met de scheiding der machten verbonden?",
         opties=["Montesquieu", "Immanuel Kant",
                 "Jean-Paul Sartre", "Thomas van Aquino"],
         antwoord=0,
         uitleg="Hij werkte de gedachte uit in de 18de eeuw, in dezelfde eeuw als de Verlichting "
                "waaruit onze grondwet komt."),
    dict(type="meerkeuze",
         vraag="Welke instelling hoort bij de wetgevende macht?",
         opties=["het parlement", "de regering",
                 "de rechtbank van eerste aanleg", "de politie"],
         antwoord=0,
         uitleg="Het parlement maakt de wetten. In België zijn er meerdere parlementen: het "
                "federale en die van de gemeenschappen en gewesten."),
    dict(type="meerkeuze",
         vraag="Welke instelling hoort bij de uitvoerende macht?",
         opties=["de regering", "het parlement",
                 "het Hof van Cassatie", "het Grondwettelijk Hof"],
         antwoord=0,
         uitleg="De regering en haar administratie voeren uit wat het parlement beslist heeft."),
    dict(type="meerkeuze",
         vraag="Welke instellingen horen bij de rechterlijke macht?",
         opties=["de hoven en de rechtbanken", "de regeringen en hun ministeries",
                 "de parlementen en hun commissies", "de politie en de gemeentebesturen"],
         antwoord=0,
         uitleg="Zij passen de wet toe op een concreet geschil en spreken recht."),
    dict(type="meerkeuze",
         vraag="Wat is de functie van de wetgevende macht?",
         opties=["de wetten maken en de regering controleren",
                 "de wetten uitvoeren en het land besturen",
                 "de wetten toepassen op een concreet geschil",
                 "de wetten toetsen aan de grondwet"],
         antwoord=0,
         uitleg="Het parlement heeft twee taken: wetten maken, en de regering op haar werk "
                "nakijken."),
    dict(type="meerkeuze",
         vraag="Wat is de functie van de rechterlijke macht?",
         opties=["de wet toepassen op een concreet geschil en recht spreken",
                 "de wet maken en aanpassen waar ze niet meer past",
                 "de wet uitvoeren en het dagelijkse bestuur verzorgen",
                 "de wet aan de bevolking uitleggen en bekendmaken"],
         antwoord=0,
         uitleg="Zij schrijft geen regels en bestuurt niet; zij beslecht wat er in één zaak uit de "
                "wet volgt."),
    dict(type="meerkeuze",
         vraag="Waarom is de scheiding der machten belangrijk in een democratie?",
         opties=["ze voorkomt dat alle macht in dezelfde handen terechtkomt",
                 "ze zorgt dat beslissingen sneller genomen kunnen worden",
                 "ze zorgt dat iedereen in het land hetzelfde denkt",
                 "ze maakt verkiezingen overbodig voor de burgers"],
         antwoord=0,
         uitleg="Macht die zichzelf controleert, controleert niets. Daarom is traagheid hier geen "
                "fout maar een bedoeling."),
    dict(type="meerkeuze",
         vraag="Een minister wil dat een rechter een bepaalde straf oplegt. Wat is hier aan de "
               "hand?",
         opties=["de uitvoerende macht grijpt in de rechterlijke macht in",
                 "de rechterlijke macht grijpt in de uitvoerende macht in",
                 "de wetgevende macht controleert de regering, zoals het hoort",
                 "niets, want een minister staat boven een rechter"],
         antwoord=0,
         uitleg="Een rechter mag van niemand uit een andere macht een bevel krijgen over hoe hij "
                "oordeelt."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over de drie machten kloppen?",
         opties=["het parlement maakt de wetten, de regering voert ze uit",
                 "de hoven en rechtbanken passen de wet toe op een concreet geschil",
                 "de regering maakt de wetten en het parlement voert ze uit",
                 "de rechterlijke macht mag nieuwe wetten schrijven"],
         antwoord=[0, 1],
         uitleg="De eerste twee. Dat is de kern van de verdeling: maken, uitvoeren, toepassen."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over de scheiding der machten kloppen?",
         opties=["ze is een van de principes van een democratische rechtsstaat",
                 "ze bestaat om macht te begrenzen en niet om bestuur te versnellen",
                 "ze betekent dat de drie machten niets met elkaar te maken hebben",
                 "ze betekent dat elke macht de andere twee kan afzetten"],
         antwoord=[0, 1],
         uitleg="De eerste twee. De machten raken elkaar wel degelijk: daar gaat de controle en "
                "het evenwicht over."),
    dict(type="meerkeuze",
         vraag="Waarom spreekt men van een scheiding en niet van een afzondering?",
         opties=["de machten houden elkaar in het oog en werken op elkaar in",
                 "de machten hebben helemaal geen contact met elkaar nodig",
                 "de machten worden door dezelfde personen uitgeoefend",
                 "de machten zijn alleen in naam van elkaar gescheiden"],
         antwoord=0,
         uitleg="Het parlement controleert de regering, de rechter toetst het bestuur. Elkaar in "
                "het oog houden hoort bij het ontwerp."),
    dict(type="waarofniet",
         vraag="De wetgevende macht wordt in België uitgeoefend door de parlementen.",
         antwoord=True,
         uitleg="Waar. Het federale parlement en de parlementen van de gemeenschappen en "
                "gewesten."),
    dict(type="waarofniet",
         vraag="De regering hoort bij de rechterlijke macht.",
         antwoord=False,
         uitleg="Niet waar. De regering is de uitvoerende macht; de rechterlijke macht zijn de "
                "hoven en rechtbanken."),
    dict(type="waarofniet",
         vraag="De scheiding der machten bestaat om te voorkomen dat alle macht bij één instantie "
               "ligt.",
         antwoord=True,
         uitleg="Waar. Macht die zichzelf controleert, controleert niets."),
    dict(type="waarofniet",
         vraag="De rechterlijke macht mag zelf nieuwe wetten schrijven.",
         antwoord=False,
         uitleg="Niet waar. Zij past de wet toe; schrijven is het werk van het parlement."),
    dict(type="invultekst",
         vraag="Welke macht maakt de wetten? De ... macht",
         antwoord=["wetgevende"],
         uitleg="Uitgeoefend door de parlementen."),
    dict(type="invultekst",
         vraag="Welke macht voert de wetten uit? De ... macht",
         antwoord=["uitvoerende"],
         uitleg="Uitgeoefend door de regeringen en hun administratie."),
    dict(type="invultekst",
         vraag="Welke macht spreekt recht? De ... macht",
         antwoord=["rechterlijke"],
         uitleg="Uitgeoefend door de hoven en rechtbanken."),
    dict(type="invultekst",
         vraag="Welke filosoof uit de 18de eeuw werkte de scheiding der machten uit?",
         antwoord=["Montesquieu"],
         uitleg="Zijn gedachte ligt aan de basis van onze staatsinrichting."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Hoe controleert het parlement de regering?",
         opties=["met vragen, met onderzoek en met haar stem over de begroting",
                 "met een vonnis waarin het de regering veroordeelt",
                 "met een bevel aan een rechter om de regering te berechten",
                 "met de benoeming van de rechters die de regering beoordelen"],
         antwoord=0,
         uitleg="Zonder de steun van het parlement geraakt een regering niet aan haar geld en "
                "niet aan haar wetten. Dat is haar sterkste middel."),
    dict(type="meerkeuze",
         vraag="Welke rol heeft het Grondwettelijk Hof in dat evenwicht?",
         opties=["het toetst of een wet met de grondwet in overeenstemming is",
                 "het toetst of een vonnis van een rechtbank juist beslist is",
                 "het toetst of een regering haar begroting goed heeft opgemaakt",
                 "het toetst of een verkiezing correct is verlopen in een gemeente"],
         antwoord=0,
         uitleg="Zo staat ook de wetgever zelf onder toezicht: een meerderheid kan niet alles wat "
                "ze wil in een wet zetten."),
    dict(type="meerkeuze",
         vraag="Welke rol heeft de Raad van State?",
         opties=["hij kan beslissingen van het bestuur nakijken en vernietigen",
                 "hij kan wetten van het parlement vernietigen",
                 "hij kan vonnissen van een strafrechter volledig herzien",
                 "hij kan ministers uit de regering ontslaan"],
         antwoord=0,
         uitleg="Wie zich door een beslissing van de overheid onrecht aangedaan voelt, kan daar "
                "terecht. Zo is het bestuur zelf aan het recht gebonden."),
    dict(type="meerkeuze",
         vraag="Wat bedoelt men met controle en evenwicht tussen de machten?",
         opties=["elke macht heeft middelen om de andere twee binnen hun grenzen te houden",
                 "elke macht heeft precies evenveel ambtenaren en middelen in dienst",
                 "elke macht beslist over een gelijk aantal onderwerpen",
                 "elke macht mag de andere twee naar believen afzetten"],
         antwoord=0,
         uitleg="Geen gelijke grootte maar wederzijdse rem: controleren, toetsen, weigeren. "
                "Daardoor blijft er geen macht zonder tegengewicht."),
    dict(type="meerkeuze",
         vraag="Waarom worden rechters in België niet verkozen?",
         opties=["een rechter die stemmen moet halen, wordt afhankelijk van wat populair is",
                 "een rechter moet door de regering benoemd worden om te kunnen werken",
                 "een rechter moet zijn ambt van zijn ouders kunnen overnemen",
                 "een rechter moet door zijn collega's gekozen worden om onpartijdig te zijn"],
         antwoord=0,
         uitleg="Zijn benoeming loopt via een onafhankelijke instelling die op bekwaamheid "
                "selecteert, juist om hem buiten de politiek te houden."),
    dict(type="meerkeuze",
         vraag="Waarom is de vaste benoeming van een rechter belangrijk?",
         opties=["wie niet afgezet kan worden, kan onbevangen tegen de macht in oordelen",
                 "wie niet afgezet kan worden, hoeft de wet niet meer te volgen",
                 "wie niet afgezet kan worden, kan sneller uitspraak doen",
                 "wie niet afgezet kan worden, hoeft zijn vonnis verder niet te motiveren"],
         antwoord=0,
         uitleg="Een rechter die zijn plaats kan verliezen door een onwelkom vonnis, is geen "
                "onafhankelijke rechter."),
    dict(type="meerkeuze",
         vraag="Waarom moet een rechter zijn vonnis motiveren?",
         opties=["zo kan iedereen nagaan waarop zijn beslissing berust",
                 "zo kan de regering zijn beslissing nog wijzigen",
                 "zo kan het parlement de wet achteraf aanpassen",
                 "zo kan hij zich tegen een klacht verdedigen"],
         antwoord=0,
         uitleg="Een gemotiveerd vonnis is te controleren en in beroep aan te vechten. Dat hoort "
                "bij een eerlijk proces."),
    dict(type="meerkeuze",
         vraag="Een parlement stemt een wet die één lopende rechtszaak in het voordeel van één "
               "partij beslecht. Wat is hier aan de hand?",
         opties=["de wetgevende macht grijpt in een zaak van de rechterlijke macht in",
                 "de wetgevende macht doet precies waarvoor ze bestaat",
                 "de rechterlijke macht grijpt in een zaak van de wetgevende macht in",
                 "de uitvoerende macht controleert de wetgevende macht"],
         antwoord=0,
         uitleg="Een wet is algemeen. Wie er een beslissing in één dossier van maakt, neemt het "
                "werk van de rechter over."),
    dict(type="meerkeuze",
         vraag="Een regering weigert een vonnis uit te voeren dat haar niet past. Wat is hier aan "
               "de hand?",
         opties=["een schending van de scheiding der machten en van de rechtsstaat",
                 "een normale toepassing van de controle op de rechterlijke macht",
                 "een geldige manier om in beroep te gaan tegen dat vonnis",
                 "een kwestie van deontologie binnen de administratie"],
         antwoord=0,
         uitleg="De weg tegen een vonnis is het beroep, niet het negeren. Daarom staat de niet-"
                "uitvoering van vonnissen in de lijst van actuele thema's."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over schendingen van de scheiding der machten kloppen?",
         opties=["een minister die een rechter onder druk zet, is er een voorbeeld van",
                 "een regering die een vonnis niet uitvoert, is er een voorbeeld van",
                 "een parlement dat de regering ondervraagt, is er een voorbeeld van",
                 "een rechter die zijn vonnis motiveert, is er een voorbeeld van"],
         antwoord=[0, 1],
         uitleg="De eerste twee. De twee andere zijn juist voorbeelden van hoe het systeem hoort "
                "te werken."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over de rechterlijke macht kloppen?",
         opties=["haar onafhankelijkheid is beschermd door de manier waarop rechters benoemd worden",
                 "zij kan beslissingen van het bestuur en van de wetgever laten toetsen",
                 "zij staat onder het gezag van de minister van Justitie",
                 "zij kan de regering naar huis sturen na een onwelkom vonnis"],
         antwoord=[0, 1],
         uitleg="De eerste twee. De minister organiseert justitie als dienst, maar beslist nooit "
                "hoe een rechter moet oordelen."),
    dict(type="meerkeuze",
         vraag="Waarom kan een burger zijn eigen overheid voor de rechter brengen?",
         opties=["omdat ook de overheid aan het recht gebonden is en haar daden toetsbaar zijn",
                 "omdat de rechter in een geschil altijd de burger moet volgen",
                 "omdat de overheid geen eigen advocaten in dienst mag hebben",
                 "omdat het parlement elk geschil met de overheid eerst moet goedkeuren"],
         antwoord=0,
         uitleg="Gelijk krijgen is niet gegarandeerd. Dat een onafhankelijke rechter ernaar kijkt, "
                "wel."),
    dict(type="waarofniet",
         vraag="Het Grondwettelijk Hof kan nagaan of een wet met de grondwet overeenstemt.",
         antwoord=True,
         uitleg="Waar. Zo staat ook de wetgever onder toezicht."),
    dict(type="waarofniet",
         vraag="Rechters worden in België door de bevolking verkozen.",
         antwoord=False,
         uitleg="Niet waar. Hun benoeming loopt via een onafhankelijke instelling die op "
                "bekwaamheid selecteert."),
    dict(type="waarofniet",
         vraag="Een regering die een vonnis niet uitvoert, schendt de scheiding der machten.",
         antwoord=True,
         uitleg="Waar. De weg tegen een vonnis is het beroep en niet het negeren."),
    dict(type="waarofniet",
         vraag="De minister van Justitie mag een rechter zeggen welke straf hij moet opleggen.",
         antwoord=False,
         uitleg="Niet waar. Hij organiseert de dienst, maar raakt niet aan het oordeel zelf."),
    dict(type="invultekst",
         vraag="Welk hof toetst of een wet met de grondwet overeenstemt? Het ... Hof",
         antwoord=["Grondwettelijk", "grondwettelijk"],
         uitleg="Zo blijft ook een meerderheid in het parlement begrensd."),
    dict(type="invultekst",
         vraag="Welke instelling kan beslissingen van het bestuur vernietigen? De Raad van ...",
         antwoord=["State", "state"],
         uitleg="Daar kan je terecht tegen een beslissing van de overheid."),
    dict(type="invultekst",
         vraag="Hoe noemt men de wederzijdse rem die de drie machten op elkaar hebben? Controle "
               "en ...",
         antwoord=["evenwicht"],
         uitleg="Geen gelijke grootte, maar middelen om elkaar binnen de grenzen te houden."),
    dict(type="invultekst",
         vraag="Welke macht wordt uitgeoefend door de hoven en rechtbanken? De ... macht",
         antwoord=["rechterlijke"],
         uitleg="Zij past de wet toe op een concreet geschil."),
]
