# -*- coding: utf-8 -*-
"""De democratische rechtsstaat en haar principes.

Het eerste van acht thema's over recht. De fiche vraagt:

    het begrip democratische rechtsstaat uitleggen
    het verband met de waarden van de westerse maatschappij uitleggen
    de belangrijkste principes herkennen en benoemen: het meerderheids-
        principe, een constitutie of grondwet, de scheiding der machten, een
        onafhankelijke en onpartijdige rechtspraak, en fundamentele rechten
        en vrijheden

De scheiding der machten krijgt een eigen thema, want de fiche werkt die met
instellingen, evenwicht en schendingen apart uit. Hier staat ze als een van de
vijf principes.

Deel 1 is het begrip, de westerse waarden, het meerderheidsprincipe en de
grondwet.
Deel 2 zijn de fundamentele rechten en vrijheden, de onafhankelijke
rechtspraak en de vijf principes samen.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is een rechtsstaat?",
         opties=["een staat waarin ook de overheid zelf aan het recht gebonden is",
                 "een staat waarin de overheid het recht mag veranderen zoals ze wil",
                 "een staat waarin enkel de burgers aan de wetten gebonden zijn",
                 "een staat waarin de rechters de wetten mogen schrijven"],
         antwoord=0,
         uitleg="Dat is de kern: wie de macht uitoefent, staat niet boven de wet. Een burger kan "
                "zijn eigen overheid voor de rechter brengen."),
    dict(type="meerkeuze",
         vraag="Wat voegt het woord democratisch daaraan toe?",
         opties=["de macht komt van het volk, dat zijn vertegenwoordigers verkiest",
                 "de macht komt van de rechters, die het volk vertegenwoordigen",
                 "de macht komt van de grondwet, die niemand nog kan wijzigen",
                 "de macht komt van de regering, die het volk moet gehoorzamen"],
         antwoord=0,
         uitleg="Rechtsstaat en democratie zijn twee dingen. Een staat kan netjes wetten volgen "
                "zonder verkiezingen, en verkiezingen houden zonder zich aan het recht te houden."),
    dict(type="meerkeuze",
         vraag="Met welke waarden van de westerse maatschappij hangt de democratische rechtsstaat "
               "samen?",
         opties=["vrijheid, gelijkheid en de waardigheid van elke mens",
                 "orde, gehoorzaamheid en de eenheid van het volk",
                 "welvaart, groei en de bescherming van ondernemingen",
                 "traditie, geloof en de autoriteit van wie regeert"],
         antwoord=0,
         uitleg="Die waarden komen uit de Verlichting en staan ook aan het begin van onze "
                "grondwet en van de mensenrechten."),
    dict(type="meerkeuze",
         vraag="Wat zegt het meerderheidsprincipe?",
         opties=["een beslissing geldt als de meerderheid ze steunt",
                 "een beslissing geldt enkel als iedereen ze steunt",
                 "een beslissing geldt als de regering ze goedkeurt",
                 "een beslissing geldt als een rechter ze aanvaardt"],
         antwoord=0,
         uitleg="Zo komt er een beslissing zonder dat iedereen het eens moet zijn. De keerzijde "
                "is dat een meerderheid een minderheid kan overstemmen."),
    dict(type="meerkeuze",
         vraag="Waarom mag een meerderheid niet alles beslissen?",
         opties=["grondrechten beschermen de minderheid tegen de wil van de meerderheid",
                 "een meerderheid vergist zich nu eenmaal altijd in haar keuzes",
                 "de regering mag elke beslissing van de meerderheid naast zich leggen",
                 "een rechter mag elke beslissing van de meerderheid overdoen"],
         antwoord=0,
         uitleg="Daarom is het meerderheidsprincipe maar één van de vijf principes. Zonder "
                "grondrechten wordt een meerderheid een macht zonder grens."),
    dict(type="meerkeuze",
         vraag="Wat is een constitutie?",
         opties=["de grondwet: de hoogste wet, die de macht afbakent",
                 "de verzameling van alle wetten die een land ooit maakte",
                 "het reglement waarmee een regering haar werk organiseert",
                 "het verdrag waarmee landen afspraken met elkaar maken"],
         antwoord=0,
         uitleg="Alle andere wetten moeten ermee in overeenstemming zijn. Ze zegt ook wie welke "
                "macht heeft en waar die stopt."),
    dict(type="meerkeuze",
         vraag="Waarom staat een grondwet boven de gewone wetten?",
         opties=["ze legt de spelregels vast waaraan de wetgever zelf gebonden is",
                 "ze is nu eenmaal het oudste wetboek van een land",
                 "ze is door de rechters geschreven in plaats van door het parlement",
                 "ze kan door een gewone meerderheid snel aangepast worden"],
         antwoord=0,
         uitleg="En precies daarom is ze moeilijker te wijzigen dan een gewone wet: een "
                "meerderheid van vandaag mag de spelregels niet in haar eigen voordeel omgooien."),
    dict(type="meerkeuze",
         vraag="Welke vijf principes noemt de fiche voor een democratische rechtsstaat?",
         opties=["meerderheid, grondwet, scheiding der machten, onafhankelijke rechtspraak en "
                 "grondrechten",
                 "meerderheid, grondwet, vrije markt, onafhankelijke pers en grondrechten",
                 "verkiezingen, regering, parlement, politie en rechtbanken",
                 "vrijheid, gelijkheid, broederlijkheid, orde en veiligheid"],
         antwoord=0,
         uitleg="Vijf principes die elkaar dragen. Valt er één weg, dan verzwakken de andere mee."),
    dict(type="meerkeuze",
         vraag="Een land houdt verkiezingen, maar de winnaar kan rechters afzetten die hem "
               "tegenspreken. Wat mankeert daar?",
         opties=["de rechtsstaat, want de macht is niet meer aan het recht gebonden",
                 "de democratie, want er zijn geen verkiezingen gehouden",
                 "niets, want de meerderheid heeft nu eenmaal beslist",
                 "het meerderheidsprincipe, want de winnaar heeft de meerderheid"],
         antwoord=0,
         uitleg="Verkiezingen alleen maken geen rechtsstaat. Wie de rechter kan wegsturen, staat "
                "boven de wet."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over rechtsstaat en democratie kloppen?",
         opties=["het zijn twee verschillende dingen die elkaar aanvullen",
                 "een staat kan democratisch zijn en toch de rechtsstaat uithollen",
                 "rechtsstaat en democratie betekenen precies hetzelfde",
                 "een rechtsstaat veronderstelt altijd verkiezingen"],
         antwoord=[0, 1],
         uitleg="De eerste twee. Daarom staan de twee woorden in de fiche naast elkaar en niet "
                "door elkaar."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over de grondwet kloppen?",
         opties=["ze is moeilijker te wijzigen dan een gewone wet",
                 "andere wetten moeten met haar in overeenstemming zijn",
                 "ze bevat alle wetten van een land bij elkaar",
                 "ze wordt door de regering alleen vastgelegd"],
         antwoord=[0, 1],
         uitleg="De eerste twee. Haar taak is de macht afbakenen, niet alle regels van het land "
                "bevatten."),
    dict(type="meerkeuze",
         vraag="Waarom hoort een onafhankelijke rechtspraak bij een rechtsstaat?",
         opties=["enkel een rechter die niemand hoeft te plezieren, kan de overheid terechtwijzen",
                 "enkel een rechter die de regering volgt, kan haar wetten goed toepassen",
                 "enkel een rechter die verkozen is, kan namens het volk oordelen",
                 "enkel een rechter die snel beslist, kan het vertrouwen bewaren"],
         antwoord=0,
         uitleg="Zonder onafhankelijkheid blijft van de regel dat de overheid aan het recht "
                "gebonden is niets over."),
    dict(type="waarofniet",
         vraag="In een rechtsstaat is ook de overheid aan het recht gebonden.",
         antwoord=True,
         uitleg="Waar. Dat is precies wat het woord rechtsstaat betekent."),
    dict(type="waarofniet",
         vraag="Een grondwet is gemakkelijker te wijzigen dan een gewone wet.",
         antwoord=False,
         uitleg="Niet waar. Juist moeilijker, zodat een meerderheid de spelregels niet zomaar "
                "kan omgooien."),
    dict(type="waarofniet",
         vraag="Volgens het meerderheidsprincipe geldt een beslissing die de meerderheid steunt.",
         antwoord=True,
         uitleg="Waar. En de grondrechten begrenzen wat die meerderheid mag beslissen."),
    dict(type="waarofniet",
         vraag="Rechtsstaat en democratie zijn twee woorden voor hetzelfde.",
         antwoord=False,
         uitleg="Niet waar. Het ene gaat over gebondenheid aan het recht, het andere over wie de "
                "macht geeft."),
    dict(type="invultekst",
         vraag="Hoe heet de hoogste wet van een land, die de macht afbakent?",
         antwoord=["de grondwet", "grondwet", "de constitutie"],
         uitleg="Alle andere wetten moeten ermee in overeenstemming zijn."),
    dict(type="invultekst",
         vraag="Hoe heet het principe dat een beslissing geldt als de meerderheid ze steunt? Het "
               "...",
         antwoord=["meerderheidsprincipe"],
         uitleg="Eén van de vijf principes van een democratische rechtsstaat."),
    dict(type="invultekst",
         vraag="Hoe noem je een staat waarin ook de overheid aan het recht gebonden is?",
         antwoord=["een rechtsstaat", "rechtsstaat", "de rechtsstaat"],
         uitleg="Zonder dat kan een burger zijn overheid nergens aanspreken."),
    dict(type="invultekst",
         vraag="Uit welke periode komen de waarden vrijheid en gelijkheid die onze rechtsstaat "
               "dragen? De ...",
         antwoord=["Verlichting", "verlichting"],
         uitleg="Dezelfde periode waarin de filosofie de rede centraal zette."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat zijn fundamentele rechten en vrijheden?",
         opties=["rechten die elke mens heeft en die de overheid moet eerbiedigen",
                 "rechten die de overheid uitdeelt aan wie ze verdient",
                 "rechten die enkel gelden voor wie de nationaliteit van het land heeft",
                 "rechten die een meerderheid altijd kan afschaffen"],
         antwoord=0,
         uitleg="Ze staan in de grondwet en in verdragen zoals het Europees Verdrag voor de "
                "Rechten van de Mens, juist zodat een meerderheid er niet aan kan raken."),
    dict(type="meerkeuze",
         vraag="Welke van deze vier is een fundamentele vrijheid?",
         opties=["de vrijheid van meningsuiting",
                 "de vrijheid om een rechter te kiezen die je zaak behandelt",
                 "de vrijheid om een wet naast je neer te leggen",
                 "de vrijheid om zonder bewijs iemand te laten opsluiten"],
         antwoord=0,
         uitleg="Vrijheid van meningsuiting, van vereniging, van godsdienst en het recht op een "
                "eerlijk proces horen in die rij."),
    dict(type="meerkeuze",
         vraag="Mogen fundamentele rechten beperkt worden?",
         opties=["ja, binnen grenzen die de wet vastlegt en een rechter kan toetsen",
                 "nee, nooit, in geen enkele omstandigheid",
                 "ja, wanneer de regering dat op haar eigen gezag nodig blijkt te vinden",
                 "ja, zodra een meerderheid van de bevolking het wil"],
         antwoord=0,
         uitleg="Vrijheid van meningsuiting dekt geen laster. Maar de beperking moet in de wet "
                "staan, een doel dienen en toetsbaar zijn."),
    dict(type="meerkeuze",
         vraag="Wat betekent onpartijdigheid bij een rechter?",
         opties=["hij heeft geen belang bij de uitkomst en geen band met de partijen",
                 "hij staat los van de regering en van het parlement",
                 "hij beslist altijd ergens in het midden tussen de twee partijen",
                 "hij volgt de mening van de meerderheid van de bevolking"],
         antwoord=0,
         uitleg="Onpartijdigheid gaat over de zaak zelf; onafhankelijkheid gaat over zijn plaats "
                "tegenover de andere machten. Twee verschillende eisen."),
    dict(type="meerkeuze",
         vraag="Wat betekent onafhankelijkheid bij een rechter?",
         opties=["hij kan oordelen zonder bevel of druk van de andere machten",
                 "hij kan oordelen zonder zich aan de wet te houden",
                 "hij kan oordelen zonder ooit naar de partijen te hoeven luisteren",
                 "hij kan oordelen zonder zijn beslissing te motiveren"],
         antwoord=0,
         uitleg="Hij is wel aan de wet gebonden. Zijn onafhankelijkheid betekent dat niemand hem "
                "kan voorschrijven hoe hij die wet moet toepassen."),
    dict(type="meerkeuze",
         vraag="Een rechter moet oordelen over een zaak van zijn eigen zus. Wat is hier het "
               "probleem?",
         opties=["zijn onpartijdigheid, want hij heeft een band met een partij",
                 "zijn onafhankelijkheid, want de regering kan hem beïnvloeden",
                 "de openbaarheid, want niemand mag die zaak zien",
                 "het meerderheidsprincipe, want niemand heeft hierover gestemd"],
         antwoord=0,
         uitleg="Hij hoort zich uit de zaak terug te trekken. Niet omdat hij zeker partijdig zou "
                "zijn, maar omdat de schijn al genoeg is."),
    dict(type="meerkeuze",
         vraag="Waarom dragen de vijf principes elkaar?",
         opties=["valt er één weg, dan verliezen de andere hun kracht",
                 "ze zijn alle vijf in dezelfde wet opgeschreven",
                 "ze gelden elk voor een andere groep van burgers",
                 "ze kunnen alle vijf los van elkaar afgeschaft worden"],
         antwoord=0,
         uitleg="Grondrechten zonder onafhankelijke rechter zijn tekst op papier; een grondwet "
                "zonder scheiding der machten geeft niemand tegengewicht."),
    dict(type="meerkeuze",
         vraag="Een regering schort tijdens een crisis de vrije pers op. Wat is hier aan de orde?",
         opties=["een fundamentele vrijheid, en of de beperking door de wet gedekt is",
                 "het meerderheidsprincipe, want de regering heeft de meerderheid",
                 "de deontologie, want journalisten hebben eigen beroepsregels",
                 "de territoriale bevoegdheid, want het geldt in het hele land"],
         antwoord=0,
         uitleg="Zo'n maatregel is niet meteen onwettig, maar hij moet in de wet staan, een "
                "legitiem doel dienen en door een rechter te toetsen zijn."),
    dict(type="meerkeuze",
         vraag="Waarom staat het recht op een eerlijk proces bij de grondrechten?",
         opties=["zonder eerlijk proces zijn al je andere rechten niet te verdedigen",
                 "zonder eerlijk proces kan de regering helemaal geen wetten meer maken",
                 "zonder eerlijk proces vervalt het meerderheidsprincipe",
                 "zonder eerlijk proces kan een land geen grondwet hebben"],
         antwoord=0,
         uitleg="Een recht dat je nergens kan laten gelden, is geen recht. Daarom hangen de "
                "grondrechten en de rechtspraak aan elkaar."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over de grondrechten kloppen?",
         opties=["ze beschermen ook een minderheid tegen de wil van de meerderheid",
                 "ze staan in de grondwet en in internationale verdragen",
                 "ze kunnen door een gewone meerderheid afgeschaft worden",
                 "ze gelden enkel tegenover andere burgers en niet tegenover de overheid"],
         antwoord=[0, 1],
         uitleg="De eerste twee. Juist tegenover de overheid hebben ze hun hele bestaansreden."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over onafhankelijkheid en onpartijdigheid kloppen?",
         opties=["onafhankelijkheid gaat over de verhouding met de andere machten",
                 "onpartijdigheid gaat over de verhouding met de partijen in de zaak",
                 "beide woorden betekenen in het recht precies hetzelfde",
                 "een onafhankelijke rechter mag de wet naast zich leggen"],
         antwoord=[0, 1],
         uitleg="De eerste twee. Een rechter kan onafhankelijk zijn van de regering en toch "
                "partijdig in één zaak."),
    dict(type="meerkeuze",
         vraag="Waarom noemt men een rechtsstaat ook een bescherming van de burger?",
         opties=["hij kan zich op het recht beroepen tegen wie macht over hem heeft",
                 "hij hoeft zich dan zelf niet aan de wetten te houden",
                 "hij krijgt dan altijd gelijk in een geschil met de overheid",
                 "hij mag dan zelf beslissen welke wetten op hem van toepassing zijn"],
         antwoord=0,
         uitleg="Gelijk krijgen is niet gegarandeerd; gehoord worden door een onafhankelijke "
                "rechter wel."),
    dict(type="waarofniet",
         vraag="Fundamentele rechten mogen nooit in enige mate beperkt worden.",
         antwoord=False,
         uitleg="Niet waar. Beperkingen zijn mogelijk, maar enkel binnen grenzen die de wet "
                "vastlegt en een rechter kan toetsen."),
    dict(type="waarofniet",
         vraag="Onpartijdigheid betekent dat een rechter geen belang heeft bij de uitkomst.",
         antwoord=True,
         uitleg="Waar, en ook geen band met de partijen. Anders trekt hij zich terug."),
    dict(type="waarofniet",
         vraag="Een onafhankelijke rechter mag de wet naast zich neerleggen.",
         antwoord=False,
         uitleg="Niet waar. Hij is aan de wet gebonden; niemand mag hem voorschrijven hoe hij ze "
                "toepast."),
    dict(type="waarofniet",
         vraag="Grondrechten beschermen ook een minderheid tegen de meerderheid.",
         antwoord=True,
         uitleg="Waar. Dat is hun belangrijkste taak in een democratie."),
    dict(type="invultekst",
         vraag="Hoe heet de eis dat een rechter geen band heeft met de partijen in de zaak? De ...",
         antwoord=["onpartijdigheid"],
         uitleg="Een rechter die zijn zus moet beoordelen, trekt zich terug."),
    dict(type="invultekst",
         vraag="Hoe heet de eis dat een rechter geen bevel krijgt van de andere machten? De ...",
         antwoord=["onafhankelijkheid"],
         uitleg="Hij blijft wel aan de wet gebonden."),
    dict(type="invultekst",
         vraag="Welk grondrecht laat je al je andere rechten verdedigen? Het recht op een ...",
         antwoord=["eerlijk proces"],
         uitleg="Een recht dat je nergens kan laten gelden, is geen recht."),
    dict(type="invultekst",
         vraag="Hoe noem je de rechten die elke mens heeft en die de overheid moet eerbiedigen? "
               "De ... rechten",
         antwoord=["fundamentele", "grondrechten"],
         uitleg="Ze staan in de grondwet en in internationale verdragen."),
]
