# -*- coding: utf-8 -*-
"""Tekstsoorten en de bedoeling van een tekst.

Uit de vakfiche Frans 1 van de 3de graad doorstroomfinaliteit (2027): de
zeven tekstsoorten die je moet kunnen begrijpen — informatief, persuasief,
opiniërend, prescriptief, argumentatief, narratief en literair — met de
voorbeelden die de fiche zelf geeft.

Deel 1 is het herkennen van de soort en van de bedoeling van de schrijver.
Deel 2 is het verschil tussen een feit en een mening, de toon en het register,
en het lezen van een tekst met een bedoeling die niet meteen zichtbaar is.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Welke soort tekst wil je vooral informatie geven?",
         opties=["een informatieve tekst",
                 "een persuasieve tekst",
                 "een prescriptieve tekst",
                 "een narratieve tekst"],
         antwoord=0,
         uitleg="Een informatieve tekst brengt je iets bij over een onderwerp. De fiche noemt als voorbeeld een krantenartikel, een interview of een aankondiging."),
    dict(type="meerkeuze",
         vraag="Lees: « Mélangez la farine et le beurre, puis laissez reposer la pâte 30 minutes. » Welke soort tekst is dit?",
         opties=["een prescriptieve tekst",
                 "een argumentatieve tekst",
                 "een opiniërende tekst",
                 "een literaire tekst"],
         antwoord=0,
         uitleg="Prescriptief betekent voorschrijvend: de tekst zegt wat je moet doen. Een recept, een bijsluiter of een gebruiksaanwijzing is dat."),
    dict(type="invultekst",
         vraag="Hoe noemen we een tekst die je van iets wil overtuigen of je gedrag wil veranderen? Eén woord.",
         antwoord=["persuasief", "persuasieve", "overtuigend"],
         uitleg="Persuasief. Een reclamespot of een campagne tegen te snel rijden wil je iets doen of laten, niet alleen iets vertellen."),
    dict(type="meerkeuze",
         vraag="Lees: « Ce restaurant est une véritable déception : service lent et plats froids. Je ne le recommande pas. » Welke soort tekst is dit?",
         opties=["een opiniërende tekst",
                 "een informatieve tekst",
                 "een prescriptieve tekst",
                 "een narratieve tekst"],
         antwoord=0,
         uitleg="Iemand geeft zijn mening. Een hotelbeoordeling, een boekrecensie of een reactie op sociale media is opiniërend."),
    dict(type="waarofniet",
         vraag="Een argumentatieve tekst voert argumenten aan om een stelling te ondersteunen.",
         antwoord=True,
         uitleg="Dat is net het verschil met een opiniërende tekst: hier wordt het standpunt onderbouwd. Een betoog, een essay of een debat hoort erbij."),
    dict(type="meerkeuze",
         vraag="Welke teksten zijn volgens de fiche narratief?",
         opties=["een reisverslag", "een getuigenis", "een videoblog", "een bijsluiter"],
         antwoord=[0, 1, 2],
         uitleg="Narratief betekent verhalend: feiten en gebeurtenissen na elkaar. Een bijsluiter zegt wat je moet doen en is dus prescriptief."),
    dict(type="meerkeuze",
         vraag="Lees: « Et soudain, le silence. La pluie avait cessé de tomber sur les toits de la ville endormie. » Welke soort tekst is dit?",
         opties=["een literaire tekst",
                 "een informatieve tekst",
                 "een argumentatieve tekst",
                 "een prescriptieve tekst"],
         antwoord=0,
         uitleg="De tekst wil niet informeren of overtuigen maar een beeld en een gevoel oproepen. Een gedicht, een lied of een romanfragment is literair."),
    dict(type="invultekst",
         vraag="Hoe noem je een tekst die feiten en gebeurtenissen verhalend weergeeft? Eén woord.",
         antwoord=["narratief", "narratieve", "verhalend"],
         uitleg="Narratief, van het Latijnse narrare, vertellen. Een podcast met een getuigenis of een reisverslag is zo'n tekst."),
    dict(type="meerkeuze",
         vraag="Lees: « Roulez moins vite. Chaque année, la vitesse tue 300 personnes sur nos routes. » Wat is de bedoeling?",
         opties=["je gedrag veranderen",
                 "je alleen maar informeren",
                 "een verhaal vertellen",
                 "een mening weergeven"],
         antwoord=0,
         uitleg="De cijfers staan er om je te overtuigen, niet om je kennis bij te brengen. Zo'n campagnetekst is persuasief."),
    dict(type="waarofniet",
         vraag="Een reclamespot is een informatieve tekst, want hij geeft informatie over een product.",
         antwoord=False,
         uitleg="Hij geeft informatie, maar met de bedoeling je iets te doen kopen. De bedoeling bepaalt de soort, dus is hij persuasief."),
    dict(type="meerkeuze",
         vraag="Welke teksten zijn volgens de fiche informatief?",
         opties=["een krantenartikel", "een interview", "een nieuwsitem", "een gedicht"],
         antwoord=[0, 1, 2],
         uitleg="Een krantenartikel, een documentaire, een interview, een nieuwsitem en een aankondiging zijn informatief. Een gedicht is literair."),
    dict(type="meerkeuze",
         vraag="Lees: « Avis aux habitants : la collecte des déchets est reportée à jeudi. » Welke soort tekst is dit?",
         opties=["een informatieve mededeling",
                 "een persuasieve campagne",
                 "een opiniërende reactie",
                 "een argumentatief betoog"],
         antwoord=0,
         uitleg="Een avis is een bericht of aankondiging. Het brengt een feit mee: het ophalen is naar donderdag verschoven."),
    dict(type="invultekst",
         vraag="Welk Frans woord betekent een aankondiging of mededeling, zoals in « avis aux habitants »?",
         antwoord=["avis", "un avis", "een avis"],
         uitleg="Un avis. Let op: avis betekent óók mening, zoals in à mon avis, naar mijn mening. De context beslist."),
    dict(type="meerkeuze",
         vraag="Lees: « À mon avis, l'école devrait commencer plus tard. Les adolescents dorment trop peu. » Wat doet de schrijver hier?",
         opties=["een mening met een reden geven",
                 "een feit zonder uitleg melden",
                 "een stap voor stap uitleggen",
                 "een verhaal navertellen"],
         antwoord=0,
         uitleg="À mon avis kondigt een mening aan, en de tweede zin geeft er een argument bij. Zo schuift de tekst van opiniërend naar argumentatief."),
    dict(type="waarofniet",
         vraag="Een strip en een cartoon horen volgens de fiche bij de literaire teksten.",
         antwoord=True,
         uitleg="De fiche noemt bij literaire teksten uitdrukkelijk een lied, een gedicht, een cartoon, een strip, een kortverhaal en een romanfragment."),
    dict(type="meerkeuze",
         vraag="Waaraan herken je snel een prescriptieve tekst?",
         opties=["aan de imperatief",
                 "aan de stappen in volgorde",
                 "soms aan een infinitief",
                 "aan de vele beeldspraak"],
         antwoord=[0, 1, 2],
         uitleg="Mélangez, ajoutez, laissez reposer: gebiedende wijs en een vaste volgorde. Soms staat er in plaats daarvan een infinitief: mélanger, ajouter."),
    dict(type="meerkeuze",
         vraag="Lees: « Interdire les voitures en ville ? Trois raisons de ne pas le faire. » Welke soort tekst volgt hier?",
         opties=["een argumentatieve tekst",
                 "een prescriptieve tekst",
                 "een narratieve tekst",
                 "een informatieve tekst"],
         antwoord=0,
         uitleg="De titel kondigt drie redenen aan bij een standpunt. Dat is een betoog, dus een argumentatieve tekst."),
    dict(type="waarofniet",
         vraag="Eén tekst kan maar tot één van de zeven tekstsoorten horen.",
         antwoord=False,
         uitleg="Een krantenartikel kan informeren en tegelijk een standpunt verdedigen. Je kijkt naar wat er overweegt, niet naar een vakje."),
    dict(type="meerkeuze",
         vraag="Lees: « Chers voyageurs, veuillez composter votre billet avant de monter. » Wat moet je doen?",
         opties=["je ticket afstempelen",
                 "je ticket aan de controleur geven",
                 "je ticket online bestellen",
                 "je ticket bij de uitgang weggooien"],
         antwoord=0,
         uitleg="Composter betekent afstempelen in het gele toestel op het perron. Veuillez + infinitief is de beleefde vorm van een opdracht."),
    dict(type="meerkeuze",
         vraag="Lees: « Ce documentaire montre comment vivent les derniers bergers des Pyrénées. » Wat is de bedoeling?",
         opties=["je iets laten zien en bijbrengen",
                 "je iets doen kopen in een winkel",
                 "je stem vragen bij een verkiezing",
                 "je een oefening laten uitvoeren"],
         antwoord=0,
         uitleg="Een documentaire informeert. De fiche noemt hem met zoveel woorden bij de informatieve teksten."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is het verschil tussen een feit en een mening?",
         opties=["een feit kan je nagaan",
                 "een feit is altijd belangrijker",
                 "een mening staat nooit in een krant",
                 "een mening is altijd onjuist"],
         antwoord=0,
         uitleg="Een feit kan je controleren, een mening niet: die kan je alleen delen of niet delen. Een goede tekst onderbouwt zijn mening met feiten."),
    dict(type="meerkeuze",
         vraag="Lees: « Le musée a accueilli 120 000 visiteurs. C'est un succès incroyable. » Welke uitspraken zijn juist?",
         opties=["de eerste zin is een feit",
                 "de tweede zin is een mening",
                 "het cijfer kan je nagaan",
                 "beide zinnen zijn een mening"],
         antwoord=[0, 1, 2],
         uitleg="Het bezoekersaantal is te controleren, het woord incroyable is een beoordeling. Dus niet beide zinnen zijn een mening."),
    dict(type="invultekst",
         vraag="Welke Franse uitdrukking van drie woorden kondigt een persoonlijke mening aan en betekent naar mijn mening?",
         antwoord=["à mon avis", "a mon avis", "selon moi"],
         uitleg="À mon avis, of selon moi. Ook je trouve que en il me semble que kondigen een mening aan."),
    dict(type="meerkeuze",
         vraag="Welke uitdrukking kondigt een feit aan en geen mening?",
         opties=["il est prouvé que", "je trouve que", "il me semble que", "selon moi"],
         antwoord=0,
         uitleg="Il est prouvé que betekent het is bewezen dat. De drie andere zijn persoonlijk en kondigen juist een mening aan."),
    dict(type="waarofniet",
         vraag="In een krantenartikel kan naast feiten ook de mening van de journalist staan.",
         antwoord=True,
         uitleg="Vaak staat die in een aparte rubriek, een editorial of een chronique, maar ook in een gewoon artikel sluipt een beoordeling binnen door de woordkeuze."),
    dict(type="meerkeuze",
         vraag="Lees: « Monsieur le Directeur, je me permets de vous écrire au sujet de… » Wat zegt deze aanhef over de tekst?",
         opties=["het is een formele brief",
                 "het is een bericht aan een vriend",
                 "het is een verhaal in een boek",
                 "het is een reclameboodschap"],
         antwoord=0,
         uitleg="Monsieur le Directeur en je me permets de zijn formeel. In een berichtje aan een vriend schrijf je salut en tu."),
    dict(type="meerkeuze",
         vraag="Waaraan merk je dat een Franse tekst formeel is?",
         opties=["aan de vous-vorm",
                 "aan de volledige zinnen",
                 "aan vaste beleefdheidsformules",
                 "aan de vele uitroeptekens"],
         antwoord=[0, 1, 2],
         uitleg="Vouvoyeren, volledige zinnen en formules als veuillez agréer wijzen op een formele tekst. Uitroeptekens wijzen eerder op het omgekeerde."),
    dict(type="invultekst",
         vraag="Welke vorm gebruik je in het Frans tegen een onbekende volwassene: tu of vous?",
         antwoord=["vous"],
         uitleg="Vous. Tutoyeren doe je met vrienden, familie en jongeren van je eigen leeftijd. Een onbekende tutoyeren klinkt onbeschoft."),
    dict(type="meerkeuze",
         vraag="Lees: « Salut ! T'as vu le match hier soir ? C'était dingue ! » Wat valt op aan deze taal?",
         opties=["het is spreektaal",
                 "het is formele schrijftaal",
                 "het is literaire taal",
                 "het is ambtelijke taal"],
         antwoord=0,
         uitleg="T'as in plaats van tu as, en dingue voor wauw: dat is gesproken, informeel Frans. In een examenopdracht schrijf je zo niet."),
    dict(type="waarofniet",
         vraag="Het Franse woord dingue past goed in een formele brief.",
         antwoord=False,
         uitleg="Dingue is spreektaal voor gek of wild. In een formele brief gebruik je bijvoorbeeld remarquable of impressionnant."),
    dict(type="meerkeuze",
         vraag="Lees: « Ce téléphone ? Le meilleur de tous les temps, à un prix imbattable ! » Wat verraadt de bedoeling?",
         opties=["de overdreven superlatieven",
                 "het vraagteken in de eerste zin",
                 "de lengte van de twee zinnen",
                 "het woord téléphone zelf"],
         antwoord=0,
         uitleg="Le meilleur de tous les temps en imbattable zijn geen metingen maar verkooppraat. Zulke superlatieven zijn het kenmerk van reclame."),
    dict(type="meerkeuze",
         vraag="Waarom is het nuttig te weten voor wie een tekst bedoeld is?",
         opties=["het verklaart de toon en de woordkeuze",
                 "het zegt wie de tekst geschreven heeft",
                 "het bepaalt de lengte van de tekst",
                 "het geeft de datum van de tekst"],
         antwoord=0,
         uitleg="Een tekst voor jongeren klinkt anders dan een tekst voor de overheid. De doelgroep verklaart waarom er tu of vous staat en welke woorden er vallen."),
    dict(type="invultekst",
         vraag="Hoe noem je in het Frans de lezer of hoorder voor wie een tekst bedoeld is? Eén woord.",
         antwoord=["destinataire", "le destinataire", "public"],
         uitleg="Le destinataire, de bestemmeling. Bij een brief staat hij bovenaan; bij een artikel moet je hem uit de toon afleiden."),
    dict(type="meerkeuze",
         vraag="Lees: « Le gouvernement aurait décidé de reporter la réforme. » Wat zegt de conditionnel hier?",
         opties=["het is nog niet bevestigd",
                 "het is zeker gebeurd",
                 "het zal nooit gebeuren",
                 "het gebeurde lang geleden"],
         antwoord=0,
         uitleg="Journalisten gebruiken de conditionnel voor niet-bevestigd nieuws: het zou beslist zijn. Een belangrijk signaal bij het lezen van een krant."),
    dict(type="waarofniet",
         vraag="Een tekst met veel cijfers en bronvermeldingen is daarom automatisch objectief.",
         antwoord=False,
         uitleg="Je kan met echte cijfers een eenzijdig verhaal brengen, door te kiezen welke je noemt. Je kijkt dus ook naar wat er níét staat."),
    dict(type="meerkeuze",
         vraag="Lees: « Vous êtes nombreux à nous avoir écrit. Voici nos réponses. » Welke soort tekst volgt hierna?",
         opties=["antwoorden op lezersvragen",
                 "een verhaal over een reis",
                 "een recept met stappen",
                 "een gedicht over de zee"],
         antwoord=0,
         uitleg="De aanhef kondigt een rubriek met vragen en antwoorden aan. Zo'n inleidend zinnetje zegt je al wat voor tekst er komt."),
    dict(type="meerkeuze",
         vraag="Welke elementen helpen je de soort van een tekst te bepalen?",
         opties=["de titel en de tussentitels",
                 "de plaats waar hij verscheen",
                 "de werkwoordstijden erin",
                 "het aantal letters per woord"],
         antwoord=[0, 1, 2],
         uitleg="Een titel, het medium en de tijden zeggen veel: imperatief wijst op een voorschrift, passé simple op een verhaal. De woordlengte zegt niets."),
    dict(type="waarofniet",
         vraag="De passé simple kom je in het Frans vooral tegen in verhalende en literaire teksten.",
         antwoord=True,
         uitleg="Il arriva, elle partit: die tijd staat in romans en sprookjes. In gesproken Frans en in een mail gebruik je de passé composé."),
    dict(type="meerkeuze",
         vraag="Lees: « Comment réussir son entretien d'embauche en cinq étapes. » Wat belooft deze titel?",
         opties=["een stappenplan",
                 "een persoonlijk verhaal",
                 "een opiniestuk",
                 "een nieuwsbericht"],
         antwoord=0,
         uitleg="Comment … en cinq étapes kondigt een werkwijze aan. Un entretien d'embauche is een sollicitatiegesprek."),
    dict(type="meerkeuze",
         vraag="Lees: « Ni l'un ni l'autre candidat ne convainc vraiment. » Wat vindt de schrijver?",
         opties=["geen van beide kandidaten overtuigt",
                 "beide kandidaten overtuigen hem",
                 "enkel de eerste kandidaat overtuigt",
                 "enkel de tweede kandidaat overtuigt"],
         antwoord=0,
         uitleg="Ni … ni … ne betekent noch … noch. Die dubbele ontkenning verandert de hele betekenis, dus lees ze aandachtig."),
]
