# -*- coding: utf-8 -*-
"""De verleden tijden en de accord van het deelwoord.

Uit de grammaticalijst van de vakfiche Frans van de 3de graad
doorstroomfinaliteit (2027): de passé composé, de imparfait, de
plus-que-parfait en de passé récent, en bij de congruentie het voltooid
deelwoord met être en met avoir.

Deel 1 zijn de vormen: het hulpwerkwoord kiezen, de deelwoorden van de
frequente onregelmatige werkwoorden, en de imparfait.
Deel 2 is het gebruik: wanneer passé composé en wanneer imparfait, de
plus-que-parfait, en de accord van het deelwoord, met het voorbeeld dat de
fiche zelf geeft.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Waaruit bestaat een passé composé?",
         opties=["een hulpwerkwoord plus een deelwoord",
                 "een werkwoord met de uitgang -ais",
                 "een werkwoord met de uitgang -rai",
                 "twee werkwoorden na elkaar zonder uitgang"],
         antwoord=0,
         uitleg="J'ai mangé, je suis parti: avoir of être in het présent, plus het voltooid deelwoord."),
    dict(type="invultekst",
         vraag="Vul in: Hier, j'… mangé au restaurant. Eén woord.",
         antwoord=["ai"],
         uitleg="J'ai mangé, met avoir. De meeste werkwoorden nemen avoir als hulpwerkwoord."),
    dict(type="meerkeuze",
         vraag="Welke werkwoorden nemen être als hulpwerkwoord in de passé composé?",
         opties=["aller", "venir", "partir", "manger"],
         antwoord=[0, 1, 2],
         uitleg="Een kleine groep van komen, gaan en blijven neemt être: aller, venir, partir, arriver, entrer, sortir, monter, descendre, naître, mourir, rester, tomber. Manger neemt avoir."),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: zij is naar Parijs gegaan?",
         opties=["Elle est allée à Paris.",
                 "Elle a allé à Paris.",
                 "Elle est allé à Paris.",
                 "Elle a allée à Paris."],
         antwoord=0,
         uitleg="Aller neemt être, en met être komt het deelwoord overeen met het onderwerp: elle est allée, ils sont allés."),
    dict(type="waarofniet",
         vraag="Elk wederkerend werkwoord neemt in de passé composé être als hulpwerkwoord.",
         antwoord=True,
         uitleg="Je me suis levé, elle s'est lavée, nous nous sommes vus. Nooit avoir, ook niet bij werkwoorden die anders avoir nemen."),
    dict(type="meerkeuze",
         vraag="Wat is het voltooid deelwoord van « prendre » ?",
         opties=["pris",
                 "prendu",
                 "prené",
                 "prendi"],
         antwoord=0,
         uitleg="J'ai pris le train. Ook comprendre en apprendre volgen dat: compris, appris."),
    dict(type="invultekst",
         vraag="Wat is het voltooid deelwoord van « faire » ? Eén woord.",
         antwoord=["fait"],
         uitleg="J'ai fait mes devoirs. Een van de deelwoorden die je gewoon moet kennen, net als mis van mettre en dit van dire."),
    dict(type="meerkeuze",
         vraag="Welke deelwoorden zijn juist?",
         opties=["vu van voir", "mis van mettre", "écrit van écrire", "savu van savoir"],
         antwoord=[0, 1, 2],
         uitleg="Voir geeft vu, mettre geeft mis, écrire geeft écrit. Savoir geeft su."),
    dict(type="meerkeuze",
         vraag="Welke uitgang hoort bij de imparfait voor nous?",
         opties=["-ions",
                 "-ons",
                 "-erons",
                 "-ames"],
         antwoord=0,
         uitleg="Nous parlions, nous faisions. De imparfait heeft -ais, -ais, -ait, -ions, -iez, -aient voor elk werkwoord."),
    dict(type="invultekst",
         vraag="Zet in de imparfait: Quand j'étais petit, je … souvent au parc. Van aller, derde persoon enkelvoud ik.",
         antwoord=["allais"],
         uitleg="J'allais. De stam komt van nous allons: haal -ons weg en zet de uitgang van de imparfait erbij."),
    dict(type="meerkeuze",
         vraag="Hoe vind je de stam van de imparfait?",
         opties=["uit de nous-vorm van het présent",
                 "uit de infinitief zonder uitgang",
                 "uit het voltooid deelwoord",
                 "uit de je-vorm van het présent"],
         antwoord=0,
         uitleg="Nous finissons geeft je finissais; nous faisons geeft je faisais. Être is de enige uitzondering: j'étais."),
    dict(type="waarofniet",
         vraag="Être is het enige werkwoord met een onregelmatige stam in de imparfait.",
         antwoord=True,
         uitleg="J'étais, tu étais, il était. Alle andere werkwoorden, ook avoir en faire, vormen de stam netjes uit de nous-vorm."),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: wij waren moe?",
         opties=["Nous étions fatigués.",
                 "Nous avions fatigués.",
                 "Nous étaient fatigués.",
                 "Nous sommes étions fatigués."],
         antwoord=0,
         uitleg="Nous étions is de imparfait van être. Moe zijn is être fatigué, niet avoir fatigué."),
    dict(type="meerkeuze",
         vraag="Wat is de passé récent in het Frans?",
         opties=["venir de plus een infinitief",
                 "aller plus een infinitief",
                 "être en train de plus infinitief",
                 "avoir plus een deelwoord"],
         antwoord=0,
         uitleg="Je viens de manger betekent ik heb net gegeten. Aller plus infinitief is de futur proche, en être en train de is de bezigheid van nu."),
    dict(type="waarofniet",
         vraag="« Elle vient de partir » betekent dat ze op het punt staat te vertrekken.",
         antwoord=False,
         uitleg="Het betekent dat ze net vertrokken is. Op het punt staan is elle va partir of elle est sur le point de partir."),
    dict(type="meerkeuze",
         vraag="Welke zinnen gebruiken een verleden tijd juist?",
         opties=["J'ai vu ce film hier.",
                 "Il faisait froid ce matin.",
                 "Nous venons de rentrer.",
                 "Je suis mangé une pomme."],
         antwoord=[0, 1, 2],
         uitleg="Manger neemt avoir: j'ai mangé une pomme. Je suis mangé zou betekenen dat jij opgegeten bent."),
    dict(type="waarofniet",
         vraag="« Je suis allé » en « j'ai allé » zijn beide juist.",
         antwoord=False,
         uitleg="Aller neemt altijd être: je suis allé. J'ai allé bestaat niet."),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: ze zijn gevallen?",
         opties=["Ils sont tombés.",
                 "Ils ont tombé.",
                 "Ils sont tombé.",
                 "Ils ont tombés."],
         antwoord=0,
         uitleg="Tomber neemt être, en het deelwoord komt overeen met ils: tombés met een s."),
    dict(type="meerkeuze",
         vraag="Hoe vorm je de plus-que-parfait?",
         opties=["avoir of être in de imparfait plus deelwoord",
                 "avoir of être in het présent plus deelwoord",
                 "een werkwoord met de uitgang -rais",
                 "twee deelwoorden achter elkaar"],
         antwoord=0,
         uitleg="J'avais mangé, j'étais parti. Het is dus de passé composé met het hulpwerkwoord in de imparfait."),
    dict(type="invultekst",
         vraag="Zet in de plus-que-parfait: Quand je suis arrivé, il … déjà parti. Eén woord, van être.",
         antwoord=["était"],
         uitleg="Il était déjà parti. Partir neemt être, en in de plus-que-parfait staat dat hulpwerkwoord in de imparfait."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Waarvoor gebruik je de passé composé?",
         opties=["voor een afgeronde gebeurtenis",
                 "voor een gewoonte in het verleden",
                 "voor de achtergrond van een verhaal",
                 "voor iets wat nog moet gebeuren"],
         antwoord=0,
         uitleg="Hier, j'ai rencontré Paul: één keer, afgerond. Een gewoonte of een achtergrond staat in de imparfait."),
    dict(type="meerkeuze",
         vraag="Waarvoor gebruik je de imparfait?",
         opties=["voor een gewoonte",
                 "voor een beschrijving",
                 "voor het decor van een verhaal",
                 "voor één afgeronde gebeurtenis"],
         antwoord=[0, 1, 2],
         uitleg="Quand j'étais petit, j'allais souvent… en il faisait beau, le soleil brillait. Eén afgeronde gebeurtenis staat juist in de passé composé."),
    dict(type="invultekst",
         vraag="Welke verleden tijd gebruik je voor « elke zomer gingen we naar de zee »? Eén woord.",
         antwoord=["imparfait", "de imparfait", "onvoltooid"],
         uitleg="De imparfait: chaque été, nous allions à la mer. Chaque été verraadt de herhaling."),
    dict(type="meerkeuze",
         vraag="Welke woorden kondigen meestal een imparfait aan?",
         opties=["souvent", "chaque jour", "toujours", "soudain"],
         antwoord=[0, 1, 2],
         uitleg="Herhaling vraagt de imparfait. Soudain, tout à coup en une fois kondigen juist een passé composé aan."),
    dict(type="waarofniet",
         vraag="In « il lisait quand le téléphone a sonné » staat de achtergrond in de imparfait.",
         antwoord=True,
         uitleg="Lisait is de bezigheid die aan de gang was, a sonné is de gebeurtenis die erin valt. Dat is het klassieke samenspel van de twee tijden."),
    dict(type="meerkeuze",
         vraag="Welke tijd hoort in « soudain, quelqu'un … à la porte » (frapper)?",
         opties=["a frappé, passé composé",
                 "frappait, imparfait",
                 "avait frappé, plus-que-parfait",
                 "frappera, futur simple"],
         antwoord=0,
         uitleg="Soudain kondigt een plotse gebeurtenis aan, en die staat in de passé composé."),
    dict(type="meerkeuze",
         vraag="Waarvoor gebruik je de plus-que-parfait?",
         opties=["voor wat nog eerder gebeurde",
                 "voor wat net gebeurd is",
                 "voor een gewoonte van toen",
                 "voor een plan dat niet doorging"],
         antwoord=0,
         uitleg="Quand je suis arrivé, il était déjà parti: zijn vertrek ligt vóór mijn aankomst. Het is het verleden van het verleden."),
    dict(type="invultekst",
         vraag="Welke tijd staat in « il avait déjà mangé » ? Eén woord.",
         antwoord=["plus-que-parfait", "plusqueparfait", "voltooid"],
         uitleg="De plus-que-parfait: avoir of être in de imparfait plus het deelwoord. Hij had al gegeten voor er iets anders gebeurde."),
    dict(type="meerkeuze",
         vraag="Met welk hulpwerkwoord komt het deelwoord overeen met het onderwerp?",
         opties=["met être",
                 "met avoir",
                 "met beide altijd",
                 "met geen van beide"],
         antwoord=0,
         uitleg="Elle est partie, ils sont venus. Met avoir gebeurt dat niet, tenzij het lijdend voorwerp vooraan staat."),
    dict(type="waarofniet",
         vraag="Met avoir komt het deelwoord overeen met het onderwerp van de zin.",
         antwoord=False,
         uitleg="Nooit: elle a mangé, ils ont mangé. Alleen een lijdend voorwerp dat vóór het werkwoord staat, vraagt een accord: la pomme qu'elle a mangée."),
    dict(type="meerkeuze",
         vraag="Waarom blijft het deelwoord in « elle nous a téléphoné » onveranderd?",
         opties=["nous is hier een COI",
                 "nous staat na het werkwoord",
                 "téléphoner neemt être",
                 "elle is een vrouwelijk onderwerp"],
         antwoord=0,
         uitleg="Dat voorbeeld staat in de fiche zelf. Téléphoner à quelqu'un geeft een meewerkend voorwerp, en met een COI is er geen accord."),
    dict(type="meerkeuze",
         vraag="Welke zin vraagt een accord van het deelwoord?",
         opties=["La lettre que j'ai écrite est partie.",
                 "J'ai écrit une lettre hier soir.",
                 "Elle leur a écrit la semaine dernière.",
                 "Nous avons écrit à nos cousins."],
         antwoord=0,
         uitleg="Que verwijst naar la lettre, een lijdend voorwerp dat vóór het werkwoord staat, dus écrite. In de drie andere staat het erna of is het een COI."),
    dict(type="invultekst",
         vraag="Vul aan: Les photos que j'ai … sont belles, van prendre. Eén woord.",
         antwoord=["prises"],
         uitleg="Prises, want que verwijst naar les photos, vrouwelijk meervoud, en dat staat vóór het werkwoord."),
    dict(type="waarofniet",
         vraag="Bij een wederkerend werkwoord komt het deelwoord overeen met het voornaamwoord als dat het lijdend voorwerp is.",
         antwoord=True,
         uitleg="Elle s'est lavée: se is lijdend voorwerp, dus lavée. Maar elle s'est lavé les mains blijft onveranderd, want dan is les mains het lijdend voorwerp."),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: ze heeft haar handen gewassen?",
         opties=["Elle s'est lavé les mains.",
                 "Elle s'est lavée les mains.",
                 "Elle a lavé ses mains se.",
                 "Elle s'a lavé les mains."],
         antwoord=0,
         uitleg="Les mains is hier het lijdend voorwerp en staat erachter, dus geen accord. Zonder les mains wordt het elle s'est lavée."),
    dict(type="meerkeuze",
         vraag="Welke tijden passen in een verhaal over je vakantie?",
         opties=["passé composé voor wat gebeurde",
                 "imparfait voor het weer en het decor",
                 "plus-que-parfait voor wat eerder was",
                 "futur simple voor wat gebeurde"],
         antwoord=[0, 1, 2],
         uitleg="De drie verleden tijden werken samen. De futur simple hoort in een verhaal over het verleden niet thuis."),
    dict(type="waarofniet",
         vraag="In gesproken Frans en in een mail gebruik je voor het verleden meestal de passé simple.",
         antwoord=False,
         uitleg="Daar gebruik je de passé composé. De passé simple staat in romans en sprookjes: il entra, elle partit."),
    dict(type="meerkeuze",
         vraag="Lees: « Je n'ai pas compris ce qu'il a dit. » Welke tijd staat er twee keer?",
         opties=["de passé composé",
                 "de imparfait",
                 "de plus-que-parfait",
                 "de futur simple"],
         antwoord=0,
         uitleg="Ai compris en a dit zijn beide passé composé. In de ontkenning staan ne en pas rond het hulpwerkwoord, niet rond het deelwoord."),
    dict(type="meerkeuze",
         vraag="Waar staan ne en pas in een passé composé?",
         opties=["rond het hulpwerkwoord",
                 "rond het deelwoord",
                 "beide voor het hulpwerkwoord",
                 "beide achter het deelwoord"],
         antwoord=0,
         uitleg="Je n'ai pas mangé, il n'est pas venu. Het deelwoord blijft buiten de ontkenning."),
    dict(type="meerkeuze",
         vraag="Lees: « Il avait travaillé toute la nuit, alors il était épuisé. » Welk verband zie je?",
         opties=["de eerste zin verklaart de tweede",
                 "de tweede gebeurde eerst",
                 "de twee gebeurden samen",
                 "er is geen verband tussen beide"],
         antwoord=0,
         uitleg="Hij had de hele nacht gewerkt, dus was hij uitgeput. De plus-que-parfait zet de oorzaak vóór het gevolg in de tijd."),
]
