# -*- coding: utf-8 -*-
"""Présent, futur, conditionnel, subjonctif en de gérondif.

Uit de grammaticalijst van de vakfiche Frans van de 3de graad
doorstroomfinaliteit (2027): het onderscheid tussen wijzen en tijden, en de
indicatif présent, de futur proche en de futur simple, de impératif présent,
de subjonctif présent, de conditionnel présent en passé, het participe
présent en de gérondif. De fiche geeft er zelf twee voorbeelden bij: de
conditionnel passé om spijt uit te drukken (j'aurais dû) en de gérondif om
twee gelijktijdige handelingen aan te geven.

Deel 1 zijn het présent, de impératif en de toekomst.
Deel 2 zijn de conditionnel, de subjonctif, het participe présent en de
gérondif.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is het verschil tussen een wijs en een tijd?",
         opties=["een wijs zegt hoe, een tijd zegt wanneer",
                 "een wijs zegt wanneer, een tijd zegt hoe",
                 "een wijs bestaat enkel in het verleden",
                 "er is geen verschil, het is hetzelfde"],
         antwoord=0,
         uitleg="De wijs zegt met welke houding je iets brengt: vaststellen (indicatif), bevelen (impératif), wensen (subjonctif), veronderstellen (conditionnel). Binnen een wijs kies je dan een tijd."),
    dict(type="meerkeuze",
         vraag="Welke werkwoorden zijn de frequente semi-auxiliaires die de fiche noemt?",
         opties=["vouloir en pouvoir", "devoir en savoir", "aller en venir", "manger en boire"],
         antwoord=[0, 1, 2],
         uitleg="De fiche noemt aller, venir, savoir, vouloir, faire, devoir en pouvoir. Ze staan voor een infinitief: je veux partir, je dois travailler."),
    dict(type="invultekst",
         vraag="Vul in: Nous … à l'école à pied, van aller in het présent.",
         antwoord=["allons"],
         uitleg="Nous allons. Aller is onregelmatig: je vais, tu vas, il va, nous allons, vous allez, ils vont."),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: zij kunnen niet komen?",
         opties=["Ils ne peuvent pas venir.",
                 "Ils ne peuvent pas venent.",
                 "Ils ne pouvent pas venir.",
                 "Ils ne peut pas venir."],
         antwoord=0,
         uitleg="Pouvoir geeft ils peuvent, en na een semi-auxiliaire volgt altijd een infinitief: venir."),
    dict(type="waarofniet",
         vraag="Na vouloir, pouvoir en devoir volgt in het Frans een infinitief.",
         antwoord=True,
         uitleg="Je veux partir, tu peux rester, il doit étudier. Er staat geen de of à tussen, in tegenstelling tot essayer de of commencer à."),
    dict(type="meerkeuze",
         vraag="Wat is een onpersoonlijk werkwoord?",
         opties=["een werkwoord dat enkel il bij zich heeft",
                 "een werkwoord zonder lijdend voorwerp",
                 "een werkwoord dat enkel in het meervoud staat",
                 "een werkwoord zonder voltooid deelwoord"],
         antwoord=0,
         uitleg="Il pleut, il neige, il faut, il y a. Dat il verwijst naar niets of niemand; je kan het niet vervangen door een naam."),
    dict(type="invultekst",
         vraag="Welk onpersoonlijk Frans werkwoord van twee woorden betekent het moet of men moet?",
         antwoord=["il faut", "falloir"],
         uitleg="Il faut, van falloir. Il faut partir betekent we moeten gaan, en il faut que vraagt een subjonctif."),
    dict(type="meerkeuze",
         vraag="Hoe vorm je de impératif van « parler » voor tu?",
         opties=["parle, zonder s en zonder tu",
                 "parles, met de s van tu",
                 "tu parle, met het voornaamwoord",
                 "parlez, dat is dezelfde vorm"],
         antwoord=0,
         uitleg="Bij een werkwoord op -er valt de s weg: parle, mange, écoute. Bij de andere blijft ze: finis, prends, viens."),
    dict(type="meerkeuze",
         vraag="Welke bevelen zijn juist gevormd?",
         opties=["Écoute bien !", "Finis ton assiette !", "Prenons le bus.", "Manges ta soupe !"],
         antwoord=[0, 1, 2],
         uitleg="Bij -er-werkwoorden valt de s weg in de tu-vorm: mange ta soupe. De nous-vorm van de impératif bestaat ook: prenons."),
    dict(type="waarofniet",
         vraag="In een Frans bevel zet je het persoonlijk voornaamwoord voor het werkwoord.",
         antwoord=False,
         uitleg="Je laat het juist weg: viens ici, niet tu viens ici. Er zijn drie vormen, voor tu, nous en vous, elk zonder voornaamwoord."),
    dict(type="meerkeuze",
         vraag="Hoe vorm je de futur proche?",
         opties=["aller plus een infinitief",
                 "venir de plus een infinitief",
                 "être plus een voltooid deelwoord",
                 "een stam plus de uitgang -rai"],
         antwoord=0,
         uitleg="Je vais manger, nous allons partir. Het is de toekomst die dichtbij of al geregeld is."),
    dict(type="invultekst",
         vraag="Zet in de futur proche: Demain, je … travailler. Twee woorden.",
         antwoord=["vais travailler", "vais"],
         uitleg="Je vais travailler. Aller in het présent plus de infinitief; het hulpwerkwoord verandert, de infinitief nooit."),
    dict(type="meerkeuze",
         vraag="Welke uitgang hoort bij de futur simple voor je?",
         opties=["-rai",
                 "-rais",
                 "-ais",
                 "-rons"],
         antwoord=0,
         uitleg="Je parlerai, je finirai. De uitgangen zijn -rai, -ras, -ra, -rons, -rez, -ront, en ze komen achter de infinitief."),
    dict(type="meerkeuze",
         vraag="Welke stammen van de futur simple zijn juist?",
         opties=["j'irai van aller",
                 "je serai van être",
                 "j'aurai van avoir",
                 "je allerai van aller"],
         antwoord=[0, 1, 2],
         uitleg="Aller, être en avoir hebben een eigen stam: ir-, ser-, aur-. Ook faire (fer-), venir (viendr-) en pouvoir (pourr-) zijn onregelmatig."),
    dict(type="waarofniet",
         vraag="De futur simple en de conditionnel présent hebben dezelfde stam.",
         antwoord=True,
         uitleg="Je serai tegenover je serais, j'irai tegenover j'irais. Alleen de uitgang verschilt: die van de conditionnel is die van de imparfait."),
    dict(type="meerkeuze",
         vraag="Welke tijd staat in « quand j'aurai fini, je t'appellerai » ?",
         opties=["de futur antérieur en de futur simple",
                 "de passé composé en de futur simple",
                 "de conditionnel en de imparfait",
                 "de subjonctif en de impératif"],
         antwoord=0,
         uitleg="J'aurai fini is de futur antérieur: wat af zal zijn voor het andere gebeurt. In het Nederlands zeg je als ik klaar ben."),
    dict(type="invultekst",
         vraag="Zet in de futur simple: Demain, il … beau, van faire. Eén woord.",
         antwoord=["fera"],
         uitleg="Il fera beau. Faire heeft de stam fer-: je ferai, tu feras, il fera."),
    dict(type="waarofniet",
         vraag="Na « quand » gebruikt het Frans voor de toekomst de tegenwoordige tijd, zoals het Nederlands.",
         antwoord=False,
         uitleg="Het Frans zet er wel een toekomende tijd: quand je serai grand, waar wij zeggen als ik groot ben. Dat is een klassieke fout."),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: als ik groot ben, word ik dokter?",
         opties=["Quand je serai grand, je serai médecin.",
                 "Quand je suis grand, je suis médecin.",
                 "Quand je serais grand, je serai médecin.",
                 "Quand je sois grand, je serai médecin."],
         antwoord=0,
         uitleg="Na quand staat in het Frans de futur simple als het over de toekomst gaat. Serais is conditionnel en sois is subjonctif."),
    dict(type="meerkeuze",
         vraag="Wat betekent « être en train de » plus een infinitief?",
         opties=["juist bezig zijn met iets",
                 "iets net gedaan hebben",
                 "iets gaan doen straks",
                 "iets moeten doen van iemand"],
         antwoord=0,
         uitleg="Je suis en train de lire betekent ik ben aan het lezen. Het Frans heeft geen eigen vorm voor onze aan het, dus gebruikt het deze uitdrukking."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Waarvoor gebruik je de conditionnel présent?",
         opties=["voor een hoffelijke vraag of een veronderstelling",
                 "voor een afgeronde gebeurtenis in het verleden",
                 "voor een bevel aan iemand die je kent",
                 "voor een gewoonte uit je kindertijd"],
         antwoord=0,
         uitleg="Je voudrais un café is hoffelijk; si j'avais le temps, je viendrais is een veronderstelling. Journalisten gebruiken hem ook voor niet-bevestigd nieuws."),
    dict(type="invultekst",
         vraag="Zet in de conditionnel: Je … un café, s'il vous plaît, van vouloir. Eén woord.",
         antwoord=["voudrais"],
         uitleg="Je voudrais. Dat is de conditionnel de politesse die de fiche noemt: veel hoffelijker dan je veux."),
    dict(type="meerkeuze",
         vraag="Welke zinnen met si zijn juist gebouwd?",
         opties=["Si j'ai le temps, je viendrai.",
                 "Si j'avais le temps, je viendrais.",
                 "Si j'avais eu le temps, je serais venu.",
                 "Si j'aurais le temps, je viendrais."],
         antwoord=[0, 1, 2],
         uitleg="Na si staat nooit een conditionnel. De drie patronen zijn si + présent met futur, si + imparfait met conditionnel présent, en si + plus-que-parfait met conditionnel passé."),
    dict(type="waarofniet",
         vraag="Na si mag in het Frans geen conditionnel staan.",
         antwoord=True,
         uitleg="Si j'aurais is altijd fout; het moet si j'avais zijn. Het is een van de bekendste fouten, ook bij moedertaalsprekers."),
    dict(type="meerkeuze",
         vraag="Waarvoor gebruik je de conditionnel passé?",
         opties=["om spijt uit te drukken over vroeger",
                 "om een gewoonte van toen te schetsen",
                 "om een bevel hoffelijker te maken",
                 "om een plan voor morgen te melden"],
         antwoord=0,
         uitleg="J'aurais dû partir plus tôt, tu aurais pu me le dire. De fiche geeft net die twee voorbeelden."),
    dict(type="invultekst",
         vraag="Vul aan: J'… dû partir plus tôt, ik had vroeger moeten gaan. Eén woord.",
         antwoord=["aurais"],
         uitleg="J'aurais dû. Avoir in de conditionnel plus het deelwoord dû: de vaste manier om spijt te zeggen."),
    dict(type="meerkeuze",
         vraag="Wat betekent « tu aurais pu me prévenir » ?",
         opties=["je had me kunnen verwittigen",
                 "je kan me nog altijd verwittigen",
                 "je zal me moeten verwittigen",
                 "je verwittigde me altijd netjes"],
         antwoord=0,
         uitleg="Conditionnel passé van pouvoir: het had gekund maar is niet gebeurd. Zo klinkt een verwijt in het Frans."),
    dict(type="meerkeuze",
         vraag="Na welke uitdrukkingen volgt een subjonctif?",
         opties=["il faut que", "je veux que", "je suis content que", "il m'a dit que"],
         antwoord=[0, 1, 2],
         uitleg="Noodzaak, wil en gevoel vragen de subjonctif. Il m'a dit que vraagt de indicatif, want het is een vaststelling. Dat voorbeeld staat in de fiche."),
    dict(type="waarofniet",
         vraag="Na « après que » staat in het Frans een subjonctif.",
         antwoord=False,
         uitleg="Daar staat een indicatif: après qu'il est parti. Het is avant que dat een subjonctif vraagt: avant qu'il parte. De fiche noemt dat paar als voorbeeld."),
    dict(type="meerkeuze",
         vraag="Welke vorm is de subjonctif van « être » na il faut que je … ?",
         opties=["sois",
                 "suis",
                 "serai",
                 "étais"],
         antwoord=0,
         uitleg="Il faut que je sois à l'heure. Être is onregelmatig: sois, sois, soit, soyons, soyez, soient."),
    dict(type="invultekst",
         vraag="Vul in: Il faut que tu … tes devoirs, van faire, subjonctif. Eén woord.",
         antwoord=["fasses"],
         uitleg="Que tu fasses. Faire is onregelmatig in de subjonctif: fasse, fasses, fasse, fassions, fassiez, fassent."),
    dict(type="meerkeuze",
         vraag="Hoe vorm je de subjonctif van een regelmatig werkwoord?",
         opties=["uit de ils-vorm plus -e, -es, -e",
                 "uit de infinitief plus -rai",
                 "uit de nous-vorm plus -ais",
                 "uit het deelwoord plus -ant"],
         antwoord=0,
         uitleg="Ils finissent geeft que je finisse. Haal -ent van de ils-vorm en zet de uitgangen -e, -es, -e, -ions, -iez, -ent erbij."),
    dict(type="meerkeuze",
         vraag="Welke zinnen gebruiken de subjonctif juist?",
         opties=["Je veux qu'il vienne.",
                 "Bien qu'il soit tard, je reste.",
                 "Il faut que nous partions.",
                 "Je sais qu'il soit là."],
         antwoord=[0, 1, 2],
         uitleg="Wil, toegeving en noodzaak vragen de subjonctif. Savoir que is een vaststelling: je sais qu'il est là."),
    dict(type="waarofniet",
         vraag="Na « je pense que » staat in een bevestigende zin een subjonctif.",
         antwoord=False,
         uitleg="Daar staat de indicatif: je pense qu'il a raison. In de ontkenning kan het wel: je ne pense pas qu'il ait raison."),
    dict(type="meerkeuze",
         vraag="Waarvoor gebruik je de gérondif?",
         opties=["voor twee handelingen tegelijk",
                 "voor een handeling die net voorbij is",
                 "voor een bevel aan een groep",
                 "voor een wens die niet uitkwam"],
         antwoord=0,
         uitleg="Il chante en travaillant: hij zingt terwijl hij werkt. De fiche geeft net dat gebruik als voorbeeld."),
    dict(type="invultekst",
         vraag="Hoe vorm je de gérondif? Vul het voorzetsel in: … plus het participe présent. Eén woord.",
         antwoord=["en"],
         uitleg="En plus het participe présent: en mangeant, en lisant, en faisant. Zonder en is het alleen een participe présent."),
    dict(type="meerkeuze",
         vraag="Hoe vorm je het participe présent?",
         opties=["uit de nous-vorm plus -ant",
                 "uit de infinitief plus -ant",
                 "uit het deelwoord plus -ant",
                 "uit de ils-vorm plus -ant"],
         antwoord=0,
         uitleg="Nous finissons geeft finissant, nous faisons geeft faisant. Drie uitzonderingen: étant, ayant en sachant."),
    dict(type="meerkeuze",
         vraag="Wat betekent « en sortant, il a fermé la porte » ?",
         opties=["bij het buitengaan sloot hij de deur",
                 "nadat hij de deur sloot, ging hij buiten",
                 "hij sloot de deur om buiten te gaan",
                 "hij ging buiten zonder de deur te sluiten"],
         antwoord=0,
         uitleg="De gérondif zegt dat de twee handelingen samenvallen. Wil je een volgorde aangeven, dan gebruik je après être sorti."),
    dict(type="waarofniet",
         vraag="In « c'est un livre intéressant » is intéressant een participe présent dat als bijvoeglijk naamwoord gebruikt wordt.",
         antwoord=True,
         uitleg="Veel bijvoeglijke naamwoorden op -ant komen van een participe présent: intéressant, fatigant, amusant. Als bijvoeglijk naamwoord volgt het de accord: une histoire intéressante."),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: terwijl ze de krant las, dronk ze koffie?",
         opties=["En lisant le journal, elle buvait du café.",
                 "En lisait le journal, elle buvait du café.",
                 "En lire le journal, elle buvait du café.",
                 "En lu le journal, elle buvait du café."],
         antwoord=0,
         uitleg="En plus het participe présent lisant. De tweede handeling staat gewoon in de tijd van het verhaal, hier de imparfait."),
]
