# -*- coding: utf-8 -*-
"""Zinsbouw, indirecte rede en de passieve zin.

Uit de grammaticalijst van de vakfiche Frans van de 3de graad
doorstroomfinaliteit (2027): de soorten zinnen (mededelend, vragend,
bevelend, uitroepend, ontkennend, bevestigend), de enkelvoudige en de
samengestelde zin met neven- en onderschikking, de betrekkelijke bijzin, de
voorwaardelijke zinnen met si, de indirecte vraag en rede, de actieve en de
passieve zin, en de zinsdelen onderwerp, persoonsvorm, COD en COI.

Deel 1 zijn de soorten zinnen, de ontkenning en de vraagvorming.
Deel 2 zijn de samengestelde zin, de indirecte rede en de passieve zin.

De fiche noemt zelf twee gebruiken: de passieve zin in krantenartikels als de
handelende persoon onbekend of onbelangrijk is, en de indirecte rede om een
gesprek weer te geven, met de juiste tijden.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Welke zinsdelen moet je volgens de fiche kunnen aanwijzen?",
         opties=["het onderwerp",
                 "de persoonsvorm",
                 "het lijdend en het meewerkend voorwerp",
                 "de titel van de tekst"],
         antwoord=[0, 1, 2],
         uitleg="Sujet, verbe conjugué, COD en COI. Je hebt ze nodig om te weten of een deelwoord moet veranderen en welk voornaamwoord je kiest."),
    dict(type="meerkeuze",
         vraag="Wat is het lijdend voorwerp in « Marie lit un livre » ?",
         opties=["un livre",
                 "Marie",
                 "lit",
                 "er is geen lijdend voorwerp"],
         antwoord=0,
         uitleg="Marie is het onderwerp, lit de persoonsvorm, un livre het lijdend voorwerp. Je vervangt het door le: Marie le lit."),
    dict(type="invultekst",
         vraag="Welke afkorting gebruikt het Frans voor het lijdend voorwerp? Drie letters.",
         antwoord=["COD", "cod"],
         uitleg="Complément d'objet direct. Het meewerkend voorwerp is de COI, complément d'objet indirect, met à ervoor."),
    dict(type="meerkeuze",
         vraag="Welke drie manieren bestaan er in het Frans om een vraag te stellen?",
         opties=["met de stem omhoog",
                 "met est-ce que",
                 "met omkering van werkwoord en onderwerp",
                 "met een uitroepteken achteraan"],
         antwoord=[0, 1, 2],
         uitleg="Tu viens ? Est-ce que tu viens ? Viens-tu ? Van informeel naar formeel. Een uitroepteken maakt geen vraag."),
    dict(type="waarofniet",
         vraag="« Tu viens ? » is formeler dan « Viens-tu ? »",
         antwoord=False,
         uitleg="Het is net omgekeerd: de omkering met een streepje hoort bij schrijftaal en formeel spreken. In een gesprek hoor je vooral tu viens."),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: waar woon je, in schrijftaal?",
         opties=["Où habites-tu ?",
                 "Où tu habites-tu ?",
                 "Où est-ce que habites-tu ?",
                 "Où habite-tu ?"],
         antwoord=0,
         uitleg="Het vraagwoord vooraan, dan de omkering met een streepje. Ook mogelijk: où est-ce que tu habites."),
    dict(type="invultekst",
         vraag="Vul het ontbrekende woord in: … -ce que tu viens ce soir ? Eén woord.",
         antwoord=["est"],
         uitleg="Est-ce que. Het is één vast blokje dat je voor een gewone zin zet, en de woordorde erachter verandert niet."),
    dict(type="meerkeuze",
         vraag="Hoe maak je een gewone ontkenning in het Frans?",
         opties=["ne en pas rond de persoonsvorm",
                 "pas alleen voor het werkwoord",
                 "ne alleen achter het werkwoord",
                 "non voor de hele zin"],
         antwoord=0,
         uitleg="Je ne sais pas. In spreektaal valt de ne vaak weg: je sais pas, maar op papier schrijf je ze."),
    dict(type="meerkeuze",
         vraag="Welke ontkenningen zijn juist gevormd?",
         opties=["Je ne vois rien.",
                 "Il n'y a personne.",
                 "Elle ne vient jamais.",
                 "Je ne vois pas rien."],
         antwoord=[0, 1, 2],
         uitleg="Rien, personne en jamais vervangen pas; je zet ze er niet bij. Je ne vois pas rien is een dubbele ontkenning."),
    dict(type="waarofniet",
         vraag="« Je ne bois que de l'eau » betekent dat je helemaal geen water drinkt.",
         antwoord=False,
         uitleg="Ne … que betekent slechts: ik drink alleen water. Het is geen ontkenning maar een beperking, en dat verschil is groot."),
    dict(type="meerkeuze",
         vraag="Wat betekent « il ne reste plus rien » ?",
         opties=["er is niets meer over",
                 "er blijft nog iets over",
                 "er is nog genoeg over",
                 "er komt niets meer bij"],
         antwoord=0,
         uitleg="Ne … plus is niet meer, en rien is niets. Samen betekenen ze er is helemaal niets meer over."),
    dict(type="invultekst",
         vraag="Welk Frans woord betekent nooit, in « elle ne vient … » ? Eén woord.",
         antwoord=["jamais"],
         uitleg="Jamais staat achter het werkwoord, op de plaats van pas: elle ne vient jamais."),
    dict(type="meerkeuze",
         vraag="Welke soort zin is « Quelle belle journée ! » ?",
         opties=["een uitroepende zin",
                 "een vragende zin",
                 "een bevelende zin",
                 "een ontkennende zin"],
         antwoord=0,
         uitleg="Met quel of que maak je een uitroep: quelle belle journée, que c'est beau. Het uitroepteken hoort erbij."),
    dict(type="meerkeuze",
         vraag="Hoeveel soorten zinnen noemt de vakfiche?",
         opties=["zes", "drie", "vier", "tien"],
         antwoord=0,
         uitleg="Zes: déclarative, interrogative, impérative, exclamative, négative en affirmative. De lengte van een zin is geen soort."),
    dict(type="waarofniet",
         vraag="Een zin kan tegelijk vragend en ontkennend zijn.",
         antwoord=True,
         uitleg="Tu ne viens pas ? is beide. Let op het antwoord: op zo'n vraag betekent si ja, en oui gebruik je niet."),
    dict(type="meerkeuze",
         vraag="Hoe antwoord je bevestigend op « tu ne viens pas ? » ?",
         opties=["Si.",
                 "Oui.",
                 "Non.",
                 "Peut-être."],
         antwoord=0,
         uitleg="Na een ontkennende vraag gebruikt het Frans si om te zeggen dat het wel zo is. Oui hoort bij een gewone vraag."),
    dict(type="invultekst",
         vraag="Welk Frans woord van twee letters zeg je om een ontkennende vraag toch bevestigend te beantwoorden?",
         antwoord=["si"],
         uitleg="Si. Tu n'as pas faim ? Si, j'ai très faim. Het is iets dat het Nederlands niet heeft."),
    dict(type="meerkeuze",
         vraag="Waar staat een bijwoord van tijd zoals « souvent » meestal?",
         opties=["achter de persoonsvorm",
                 "helemaal vooraan de zin",
                 "tussen het onderwerp en de ne",
                 "achter het lijdend voorwerp"],
         antwoord=0,
         uitleg="Je vais souvent au cinéma. In een samengestelde tijd staat het tussen hulpwerkwoord en deelwoord: j'ai souvent vu."),
    dict(type="waarofniet",
         vraag="In een samengestelde tijd staat een bijwoord tussen het hulpwerkwoord en het deelwoord.",
         antwoord=True,
         uitleg="J'ai beaucoup travaillé, il a toujours dit la vérité. Dat is anders dan bij ons, waar het bijwoord vaak vooraan kan."),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: ik heb hem nooit gezien?",
         opties=["Je ne l'ai jamais vu.",
                 "Je ne l'ai vu jamais.",
                 "Je l'ai ne jamais vu.",
                 "Jamais je ne l'ai vu pas."],
         antwoord=0,
         uitleg="Ne en jamais staan rond het hulpwerkwoord, en het voornaamwoord l' staat daarvoor. Het deelwoord blijft achteraan."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is het verschil tussen nevenschikking en onderschikking?",
         opties=["nevenschikking zet gelijke delen naast elkaar",
                 "nevenschikking gebruikt altijd een komma",
                 "onderschikking kan enkel in het verleden",
                 "er is geen verschil tussen die twee"],
         antwoord=0,
         uitleg="Et, mais, ou, donc, car verbinden twee gelijkwaardige zinnen. Que, quand, parce que en si maken van de tweede een bijzin."),
    dict(type="meerkeuze",
         vraag="Welke voegwoorden zijn nevenschikkend?",
         opties=["et", "mais", "ou", "parce que"],
         antwoord=[0, 1, 2],
         uitleg="Et, ou, mais, donc, or, ni, car zijn nevenschikkend. Parce que onderschikt: het maakt een bijzin."),
    dict(type="invultekst",
         vraag="Welk Frans voegwoord van twee letters betekent of, zoals in « thé … café » ?",
         antwoord=["ou"],
         uitleg="Ou, zonder accent, betekent of. Où met accent betekent waar: dat verschil van één streepje verandert alles."),
    dict(type="meerkeuze",
         vraag="Welk voegwoord noemt de fiche als voorbeeld, en betekent want of echter?",
         opties=["or",
                 "ou",
                 "où",
                 "ora"],
         antwoord=0,
         uitleg="Or betekent nu, echter of welnu, en is typisch voor een argumentatieve tekst. De fiche noemt het samen met à moins que en pour que."),
    dict(type="waarofniet",
         vraag="Na « pour que » en « à moins que » volgt een subjonctif.",
         antwoord=True,
         uitleg="Pour qu'il comprenne, à moins qu'il vienne. De fiche noemt beide voegwoorden bij de onderschikking."),
    dict(type="meerkeuze",
         vraag="Wat is een indirecte vraag?",
         opties=["een vraag in een bijzin",
                 "een vraag zonder vraagteken",
                 "een vraag aan iemand anders",
                 "een vraag met est-ce que"],
         antwoord=0,
         uitleg="Je me demande s'il viendra. Er staat geen vraagteken, geen omkering en geen est-ce que meer."),
    dict(type="meerkeuze",
         vraag="Wat wordt « est-ce que » in een indirecte vraag?",
         opties=["si",
                 "que",
                 "qui",
                 "quand"],
         antwoord=0,
         uitleg="Est-ce qu'il vient ? wordt je demande s'il vient. Bij een vraagwoord blijft dat woord staan: je demande où il habite."),
    dict(type="invultekst",
         vraag="Zet om naar de indirecte rede: « Est-ce que tu viens ? » Il me demande … je viens. Eén woord.",
         antwoord=["si"],
         uitleg="Il me demande si je viens. Est-ce que wordt si, en de woordorde wordt die van een gewone zin."),
    dict(type="meerkeuze",
         vraag="Wat verandert er nog bij het omzetten naar de indirecte rede?",
         opties=["de persoon van het werkwoord",
                 "de bezittelijke voornaamwoorden",
                 "de tijd als de inleiding in het verleden staat",
                 "de betekenis van de boodschap"],
         antwoord=[0, 1, 2],
         uitleg="« Je viens avec mon frère » wordt il a dit qu'il venait avec son frère. De betekenis blijft net gelijk, dat is de bedoeling."),
    dict(type="waarofniet",
         vraag="Staat de inleiding in het verleden, dan schuift een présent in de indirecte rede naar de imparfait.",
         antwoord=True,
         uitleg="Il dit qu'il est malade wordt il a dit qu'il était malade. De fiche vraagt uitdrukkelijk dat je aan de juiste tijden denkt."),
    dict(type="meerkeuze",
         vraag="Zet om: « J'ai fini. » Hij zei dat hij klaar was. Welke vorm is juist?",
         opties=["Il a dit qu'il avait fini.",
                 "Il a dit qu'il a fini.",
                 "Il a dit qu'il finira.",
                 "Il a dit qu'il finissait."],
         antwoord=0,
         uitleg="Een passé composé schuift naar de plus-que-parfait als de inleiding in het verleden staat. Zo blijft de volgorde in de tijd kloppen."),
    dict(type="invultekst",
         vraag="Zet om: « Je viendrai demain. » Elle a dit qu'elle … le lendemain. Eén woord, van venir.",
         antwoord=["viendrait"],
         uitleg="Elle a dit qu'elle viendrait. Een futur simple wordt een conditionnel présent, en demain wordt le lendemain."),
    dict(type="meerkeuze",
         vraag="Wat wordt « demain » in de indirecte rede na een inleiding in het verleden?",
         opties=["le lendemain",
                 "hier",
                 "aujourd'hui",
                 "maintenant"],
         antwoord=0,
         uitleg="Ook de tijdwoorden schuiven: aujourd'hui wordt ce jour-là, hier wordt la veille, demain wordt le lendemain."),
    dict(type="meerkeuze",
         vraag="Hoe maak je van « le facteur apporte le courrier » een passieve zin?",
         opties=["Le courrier est apporté par le facteur.",
                 "Le courrier a apporté le facteur.",
                 "Le facteur est apporté le courrier.",
                 "Le courrier apporte par le facteur."],
         antwoord=0,
         uitleg="Het lijdend voorwerp wordt onderwerp, être plus het deelwoord vormt het werkwoord, en de oude handelende persoon komt na par."),
    dict(type="waarofniet",
         vraag="In een passieve Franse zin blijft het deelwoord altijd onveranderd.",
         antwoord=False,
         uitleg="Het komt overeen met het nieuwe onderwerp: la lettre est écrite, les lettres sont écrites. Het hulpwerkwoord is être, en met être is er altijd een accord."),
    dict(type="meerkeuze",
         vraag="Waarom gebruiken krantenartikels volgens de fiche vaak de passieve vorm?",
         opties=["de handelende persoon is onbekend of onbelangrijk",
                 "de passieve vorm is korter dan de actieve",
                 "de passieve vorm staat altijd in het verleden",
                 "de passieve vorm klinkt vriendelijker"],
         antwoord=0,
         uitleg="Trois personnes ont été blessées: wie het deed, weet men niet of doet niet mee. De fiche geeft net dat voorbeeld."),
    dict(type="invultekst",
         vraag="Welk voorzetsel van drie letters zet je in een passieve Franse zin voor de handelende persoon?",
         antwoord=["par"],
         uitleg="Par: le livre a été écrit par Zola. Bij een gevoel of een blijvende toestand gebruik je de: il est aimé de tous."),
    dict(type="meerkeuze",
         vraag="Welke zinnen staan in de passieve vorm?",
         opties=["Le pont a été construit en 1920.",
                 "La décision sera prise demain.",
                 "Ce livre est lu partout.",
                 "Il a construit un pont."],
         antwoord=[0, 1, 2],
         uitleg="Être plus een deelwoord, in welke tijd dan ook. De laatste zin is actief: hij doet de handeling zelf."),
    dict(type="waarofniet",
         vraag="Het Frans vermijdt « on » en gebruikt in spreektaal altijd de passieve vorm.",
         antwoord=False,
         uitleg="Het omgekeerde: on a volé mon vélo waar wij zeggen mijn fiets is gestolen. On met een actief werkwoord is in spreektaal gewoner dan de passieve vorm."),
    dict(type="meerkeuze",
         vraag="Lees: « On m'a dit que le musée était fermé. » Hoe zeg je dat in het Nederlands?",
         opties=["men heeft me gezegd dat het museum dicht was",
                 "ik heb gezegd dat het museum dicht was",
                 "het museum heeft me gezegd dat het dicht was",
                 "ik vroeg of het museum dicht was"],
         antwoord=0,
         uitleg="On is men of iemand. De bijzin staat in de imparfait omdat de inleiding in het verleden staat: dat is de indirecte rede."),
]
