# -*- coding: utf-8 -*-
"""Redeneren met historische bronnen.

Dit thema weegt een vijfde van het examen. Het is geen leerstof die je van
buiten leert maar een werkwijze: een onderzoekbare historische vraag opstellen,
en daarna het stappenplan van de bronnenanalyse uitvoeren.

De oefeningen hieronder beschrijven telkens een bron in plaats van er een te
citeren. Een verzonnen citaat in de mond van een echt persoon is geen bron maar
een vervalsing, en net dat is wat dit hoofdstuk een kind wil leren herkennen.

Deel 1: de historische vraag, de soorten bronnen en de context van de maker.
Deel 2: bruikbaarheid, betrouwbaarheid, representativiteit, presentatie, en het
vergelijken van bronnen.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Waaraan moet een onderzoekbare historische vraag voldoen?",
         opties=["ze is afgebakend in de tijd",
                 "ze is afgebakend in de ruimte",
                 "er bestaan bronnen om ze te beantwoorden",
                 "ze kan met ja of nee beantwoord worden"],
         antwoord=[0, 1, 2],
         uitleg="Een vraag die je met ja of nee afdoet, levert geen onderzoek op. De drie andere criteria maken een vraag net wél onderzoekbaar."),
    dict(type="meerkeuze",
         vraag="Welke vraag is het best afgebakend en dus het meest onderzoekbaar?",
         opties=["hoe veranderde het werk van vrouwen in de Gentse textielfabrieken tussen 1880 en 1900",
                 "hoe was het leven van de mensen vroeger in de hele wereld",
                 "was de industriële revolutie nu eigenlijk goed of slecht voor iedereen",
                 "wat gebeurde er allemaal in de negentiende eeuw op onze aardbol"],
         antwoord=0,
         uitleg="De eerste heeft een tijd, een plaats, een groep en een domein. De andere drie hebben geen van die vier."),
    dict(type="meerkeuze",
         vraag="Binnen welke maatschappelijke domeinen kan je een historische vraag afbakenen?",
         opties=["het politieke en het sociale domein",
                 "het economische domein",
                 "het culturele domein",
                 "het persoonlijke domein van de onderzoeker"],
         antwoord=[0, 1, 2],
         uitleg="De vier domeinen zijn politiek, sociaal, economisch en cultureel. Wat de onderzoeker zelf leuk vindt, is geen domein."),
    dict(type="meerkeuze",
         vraag="Wat is een primaire bron?",
         opties=["een bron die uit de onderzochte periode zelf stamt",
                 "een bron die door een historicus achteraf geschreven is",
                 "een bron die op school het meest gebruikt wordt",
                 "een bron die volgens de onderzoeker het belangrijkst is"],
         antwoord=0,
         uitleg="Een brief uit 1916 is primair, een handboek over de Eerste Wereldoorlog uit 2020 is secundair. Het gaat over wanneer, niet over hoe goed."),
    dict(type="waarofniet",
         vraag="Een secundaire bron is altijd minder waard dan een primaire bron.",
         antwoord=False,
         uitleg="Een secundaire bron overziet veel materiaal en zet het in verband. Primair en secundair zeggen iets over de afstand in tijd, niet over de kwaliteit."),
    dict(type="meerkeuze",
         vraag="Welke soorten bronnen onderscheid je naar vorm?",
         opties=["geschreven bronnen zoals brieven en kranten",
                 "materiële bronnen zoals gebouwen en gereedschap",
                 "audiovisuele bronnen zoals foto's en filmbeelden",
                 "digitale bronnen die op school gemaakt zijn"],
         antwoord=[0, 1, 2],
         uitleg="De vier vormen zijn geschreven, mondeling, materieel en audiovisueel. Mondeling zijn bijvoorbeeld getuigenissen die opgetekend werden."),
    dict(type="meerkeuze",
         vraag="Een archeoloog vindt bij een opgraving een stel munten uit de zestiende eeuw. Welke soort bron is dat?",
         opties=["een materiële primaire bron",
                 "een geschreven secundaire bron",
                 "een mondelinge primaire bron",
                 "een audiovisuele secundaire bron"],
         antwoord=0,
         uitleg="Een voorwerp uit de periode zelf. Munten vertellen bovendien veel: over de heerser, over handel en over de waarde van het geld."),
    dict(type="meerkeuze",
         vraag="Wat betekent standplaatsgebondenheid?",
         opties=["de maker van een bron kijkt vanuit zijn eigen positie, tijd en belangen",
                 "de bron is altijd bewaard gebleven op de plaats waar ze gemaakt werd",
                 "de bron mag alleen op de plaats van herkomst bestudeerd worden",
                 "de maker van een bron heeft de gebeurtenis zelf meegemaakt"],
         antwoord=0,
         uitleg="Een officier en een gewone soldaat zien dezelfde slag anders. Niet omdat een van beiden liegt, maar omdat ze ergens anders staan."),
    dict(type="waarofniet",
         vraag="Een ooggetuige van een gebeurtenis geeft altijd een objectief verslag van wat er gebeurde.",
         antwoord=False,
         uitleg="Hij ziet maar een stuk van het geheel, hij heeft belangen, en zijn geheugen schuift. Een ooggetuige is kostbaar én standplaatsgebonden."),
    dict(type="meerkeuze",
         vraag="Welke gegevens horen bij het contextualiseren van de maker van een bron?",
         opties=["zijn naam, beroep en afkomst",
                 "zijn maatschappelijke positie en zijn perspectief",
                 "of hij ooggetuige of tijdgenoot was",
                 "of de bron in een museum of in een archief ligt"],
         antwoord=[0, 1, 2],
         uitleg="Waar een bron vandaag bewaard wordt, zegt niets over de maker. De drie andere vertellen je vanuit welke hoek hij schreef."),
    dict(type="meerkeuze",
         vraag="Wat is een opdrachtgever van een bron?",
         opties=["degene die de bron liet maken en er dus een bedoeling mee had",
                 "degene die de bron vandaag in zijn verzameling bewaart",
                 "degene die de bron als eerste in een boek gepubliceerd heeft",
                 "degene over wie de bron handelt zonder ze zelf te maken"],
         antwoord=0,
         uitleg="Een vorst die zijn eigen portret bestelt, bepaalt hoe hij erop staat. Weten wie betaalde, is vaak even belangrijk als weten wie tekende."),
    dict(type="meerkeuze",
         vraag="Een affiche van een regering uit 1915 roept jonge mannen op om dienst te nemen. Wie is het doelpubliek?",
         opties=["jonge mannen die nog niet in het leger zitten",
                 "de soldaten die al aan het front vechten",
                 "de historici die de oorlog later bestuderen",
                 "de regeringen van de vijandelijke landen"],
         antwoord=0,
         uitleg="Het doelpubliek is wie de maker wilde bereiken, niet wie de bron vandaag leest. Dat onderscheid vergeet men gemakkelijk."),
    dict(type="meerkeuze",
         vraag="Wat is de bedoeling van zo'n wervingsaffiche?",
         opties=["mensen overtuigen en tot handelen aanzetten",
                 "de gebeurtenissen neutraal vastleggen voor later",
                 "de vijand informeren over de eigen troepensterkte",
                 "de kosten van de oorlog nauwkeurig verantwoorden"],
         antwoord=0,
         uitleg="Een propagandabron wil iets bereiken. Dat maakt ze niet waardeloos: ze is juist een uitstekende bron over wat men toen wilde doen geloven."),
    dict(type="waarofniet",
         vraag="Een bron die propaganda is, is daarom onbruikbaar voor een historicus.",
         antwoord=False,
         uitleg="Ze is een slechte bron over wat er écht gebeurde en een uitstekende bron over wat men wilde laten geloven. Alles hangt af van je vraag."),
    dict(type="meerkeuze",
         vraag="Wat bedoelt men met de mate van bewerking van een bron?",
         opties=["hoeveel er aan de bron veranderd is voor ze bij jou terechtkwam",
                 "hoe oud de bron is op het ogenblik dat je ze bestudeert",
                 "hoe lang een historicus aan het onderzoek gewerkt heeft",
                 "hoeveel bronnen er over hetzelfde onderwerp bewaard zijn"],
         antwoord=0,
         uitleg="Vertaald, ingekort, bijgesneden, van kleur veranderd. Elke bewerking kan de betekenis verschuiven, soms zonder dat iemand het wilde."),
    dict(type="waarofniet",
         vraag="Het eerste wat je bij een bronnenanalyse doet, is informatie verzamelen over de context van de bron.",
         antwoord=True,
         uitleg="Pas daarna lees of bekijk je de inhoud, en pas daarna interpreteer je. Wie meteen begint te lezen, leest alles in zijn eigen tijd."),
    dict(type="invultekst",
         vraag="Hoe noem je de drie vensters waarin je een bron plaatst: in de tijd, in de ruimte en in de maatschappelijke ...? Vul het laatste woord aan.",
         antwoord=["domeinen", "domein"],
         uitleg="Tijd, ruimte en maatschappelijke domeinen vormen samen het historisch referentiekader. Je gebruikt het bij elke bron opnieuw."),
    dict(type="meerkeuze",
         vraag="Van een foto is niet bekend wie ze maakte of wanneer. Wat doe je?",
         opties=["je noteert dat die contextgegevens ontbreken en houdt daar rekening mee",
                 "je laat de bron volledig buiten je onderzoek omdat ze waardeloos is",
                 "je gaat ervan uit dat de foto uit de periode van je onderzoek stamt",
                 "je kiest zelf een waarschijnlijke maker en een waarschijnlijk jaartal"],
         antwoord=0,
         uitleg="Stap één vraagt uitdrukkelijk welke contextgegevens ontbreken. Een gat in je informatie benoemen is iets anders dan het opvullen met een gok."),
    dict(type="meerkeuze",
         vraag="Een handboek geschiedenis uit 2015 beschrijft de Russische revolutie. Welke soort bron is dat?",
         opties=["een geschreven secundaire bron",
                 "een geschreven primaire bron",
                 "een materiële secundaire bron",
                 "een audiovisuele primaire bron"],
         antwoord=0,
         uitleg="Geschreven, en bijna een eeuw na de feiten gemaakt. Voor een onderzoek naar hoe men in 2015 over de revolutie dacht, zou ze wel primair zijn."),
    dict(type="waarofniet",
         vraag="Of een bron primair of secundair is, hangt mee af van de vraag die je stelt.",
         antwoord=True,
         uitleg="Een schoolboek uit 1950 is secundair voor de Eerste Wereldoorlog en primair voor een onderzoek naar wat men in 1950 aan kinderen leerde."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat beoordeel je als je naar de bruikbaarheid van een bron kijkt?",
         opties=["of de bron een antwoord geeft op jouw historische vraag",
                 "of de bron mooi genoeg is om in een werkstuk op te nemen",
                 "of de bron door een beroemde persoon gemaakt werd",
                 "of de bron in het Nederlands geschreven is"],
         antwoord=0,
         uitleg="Bruikbaarheid staat altijd in verhouding tot je vraag. Dezelfde bron kan voor de ene vraag goud waard zijn en voor de andere nutteloos."),
    dict(type="meerkeuze",
         vraag="Welke vragen stel je bij de bruikbaarheid van een bron?",
         opties=["geeft de bron rechtstreekse informatie over mijn onderwerp",
                 "geeft de bron onrechtstreekse informatie over mijn onderwerp",
                 "geeft de bron een volledig, een gedeeltelijk of geen antwoord",
                 "vind ik de bron zelf interessant om te lezen"],
         antwoord=[0, 1, 2],
         uitleg="Of jij een bron boeiend vindt, speelt geen rol. De drie andere vragen staan letterlijk in het stappenplan."),
    dict(type="meerkeuze",
         vraag="Welke elementen kunnen de betrouwbaarheid van een bron in vraag stellen?",
         opties=["de maker had er belang bij om de zaken anders voor te stellen",
                 "de maker schreef pas vele jaren na de gebeurtenis",
                 "de bron spreekt andere bronnen over hetzelfde tegen",
                 "de bron is in een vreemde taal opgesteld"],
         antwoord=[0, 1, 2],
         uitleg="Een bron in het Frans of het Duits is daarom niet minder betrouwbaar. De drie andere zijn wel degelijk redenen tot voorzichtigheid."),
    dict(type="meerkeuze",
         vraag="Wat versterkt de betrouwbaarheid van een bron?",
         opties=["andere, onafhankelijke bronnen vertellen hetzelfde",
                 "de bron is heel mooi bewaard gebleven in een archief",
                 "de bron is door veel mensen in een museum bekeken",
                 "de bron is heel oud en dus heel zeldzaam geworden"],
         antwoord=0,
         uitleg="Kruisen heet dat: wat twee bronnen onafhankelijk van elkaar zeggen, staat steviger. Ouderdom of schoonheid zegt daar niets over."),
    dict(type="waarofniet",
         vraag="Een bron die kort na de gebeurtenis gemaakt werd, is daarom altijd betrouwbaar.",
         antwoord=False,
         uitleg="Een krantenartikel van de dag zelf kan vol geruchten zitten, of met opzet gekleurd zijn. Nabijheid in tijd is één argument, geen bewijs."),
    dict(type="meerkeuze",
         vraag="Wat beoordeel je als je naar de representativiteit van een bron kijkt?",
         opties=["of de bron het standpunt van één mens weergeeft of van een hele groep",
                 "of de bron betrouwbaar genoeg is om te gebruiken",
                 "of de bron bewerkt of ingekort werd voordat ze gepubliceerd raakte",
                 "of de bron rechtstreeks over het onderwerp gaat"],
         antwoord=0,
         uitleg="Eén dagboek van één soldaat vertelt niet hoe alle soldaten dachten. De tweede, derde en vierde vraag horen bij de andere criteria."),
    dict(type="meerkeuze",
         vraag="Je onderzoekt hoe arbeiders in 1890 over hun werk dachten, en je hebt één brief van één arbeider. Wat is het probleem?",
         opties=["één brief is niet representatief voor een hele bevolkingsgroep",
                 "een brief is nooit een bruikbare bron voor een historicus",
                 "een brief uit 1890 is een secundaire bron over die periode",
                 "een brief heeft geen doelpubliek en is dus niet te gebruiken"],
         antwoord=0,
         uitleg="De brief blijft waardevol: hij toont dat iemand er zo over dacht. Hij toont niet dat iedereen er zo over dacht, en dat is het verschil."),
    dict(type="waarofniet",
         vraag="Van arme en ongeletterde groepen zijn er veel minder geschreven bronnen bewaard dan van rijke en machtige groepen.",
         antwoord=True,
         uitleg="Wie niet kon schrijven, liet weinig op papier na. Daardoor kijkt onze geschiedenis vaak vanzelf van bovenaf, en dat moet je bewust corrigeren."),
    dict(type="meerkeuze",
         vraag="Wat bedoelt men met de presentatie van een bron?",
         opties=["de manier waarop de bron aan jou getoond wordt, met of zonder bewerking",
                 "de mate waarin de bron de waarheid van de feiten weergeeft",
                 "de hoeveelheid informatie die de bron over het onderwerp bevat",
                 "de plaats waar de bron vandaag bewaard en aan het publiek getoond wordt"],
         antwoord=0,
         uitleg="Een ingekorte tekst, een bijgesneden foto, een vertaling: telkens staat er iemand tussen jou en de oorspronkelijke bron."),
    dict(type="meerkeuze",
         vraag="Een foto van een betoging wordt zo bijgesneden dat enkel de drukste hoek te zien is. Welk gevolg heeft dat?",
         opties=["de betoging lijkt veel groter dan ze in werkelijkheid was",
                 "de foto wordt daardoor automatisch een secundaire bron",
                 "de foto verliest zijn doelpubliek en zijn bedoeling",
                 "de foto wordt daardoor betrouwbaarder dan het origineel"],
         antwoord=0,
         uitleg="Er is niets vervalst en toch klopt het beeld niet meer. Daarom vraag je bij elke afbeelding of je het hele kader ziet."),
    dict(type="waarofniet",
         vraag="Een bron vertalen of inkorten kan de betekenis ervan verschuiven.",
         antwoord=True,
         uitleg="Elke keuze van een vertaler of samensteller is een keuze. Daarom vermeldt een goede bronvermelding altijd of een tekst bewerkt werd."),
    dict(type="meerkeuze",
         vraag="Waarom vergelijk je verschillende bronnen met elkaar?",
         opties=["om gelijkenissen en verschillen te vinden en zo tot een beter antwoord te komen",
                 "om de mooiste bron te kiezen voor in je eindwerk",
                 "om te bepalen welke van de bronnen het langst bewaard is gebleven in een archief",
                 "om het aantal bronnen te halen dat de leerkracht vraagt"],
         antwoord=0,
         uitleg="Waar twee bronnen hetzelfde zeggen, sta je sterk. Waar ze elkaar tegenspreken, begint het eigenlijke werk: waarom verschillen ze?"),
    dict(type="meerkeuze",
         vraag="Twee bronnen over dezelfde staking spreken elkaar tegen. Wat doe je?",
         opties=["je onderzoekt de standplaats en de bedoeling van elke maker",
                 "je kiest meteen de bron die het best bij je mening past",
                 "je besluit dat de staking nooit heeft plaatsgevonden",
                 "je laat beide bronnen weg uit je onderzoek"],
         antwoord=0,
         uitleg="Een tegenspraak is geen probleem maar een aanwijzing. Een krant van de werkgevers en een pamflet van de vakbond zien dezelfde staking anders."),
    dict(type="meerkeuze",
         vraag="Welke stappen horen bij het stappenplan voor bronnenanalyse?",
         opties=["de context van elke bron verzamelen",
                 "de inhoud van elke bron lezen of bekijken",
                 "elke bron interpreteren en beoordelen",
                 "een eigen bron maken over het onderwerp"],
         antwoord=[0, 1, 2],
         uitleg="Zelf een bron maken hoort bij geen enkele stap. De drie andere zijn precies stap één, twee en drie, en die volgorde telt."),
    dict(type="waarofniet",
         vraag="Je kan de inhoud van een bron goed beoordelen zonder iets over de maker te weten.",
         antwoord=False,
         uitleg="Dezelfde zin betekent iets anders in de mond van een slachtoffer, een dader of een toeschouwer. Daarom komt de context eerst."),
    dict(type="meerkeuze",
         vraag="Wat is het beoogde effect van een bron?",
         opties=["wat de maker bij zijn publiek wilde teweegbrengen",
                 "wat de bron vandaag bij een historicus teweegbrengt",
                 "hoeveel mensen de bron in haar eigen tijd gezien hebben",
                 "hoe lang de bron bewaard is kunnen blijven"],
         antwoord=0,
         uitleg="Angst aanjagen, trots opwekken, mensen tot dienstneming bewegen. Het beoogde effect is iets anders dan het effect dat ze echt had."),
    dict(type="meerkeuze",
         vraag="Een schilderij toont een veldslag met de eigen vorst heldhaftig in het midden. Wat besluit je?",
         opties=["de bron zegt vooral iets over hoe de vorst gezien wilde worden",
                 "de bron is een betrouwbaar verslag van het verloop van de slag",
                 "de bron is onbruikbaar en hoort niet in een onderzoek thuis",
                 "de bron is een primaire bron over de schilderkunst van vandaag"],
         antwoord=0,
         uitleg="Een vorst die zijn eigen overwinning laat schilderen, levert een uitstekende bron over beeldvorming en een zwakke over de slag zelf."),
    dict(type="invultekst",
         vraag="Hoe noem je het samen bekijken van meerdere onafhankelijke bronnen om te zien of ze elkaar bevestigen? Vul aan: bronnen ...",
         antwoord=["kruisen", "vergelijken"],
         uitleg="Bronnen kruisen of vergelijken. Wat twee onafhankelijke bronnen allebei zeggen, staat heel wat steviger dan wat er in één bron staat."),
    dict(type="waarofniet",
         vraag="Een historische vraag beantwoord je het best met bronnen uit één enkele hoek, zodat je verhaal consequent blijft.",
         antwoord=False,
         uitleg="Juist het omgekeerde: hoe meer verschillende hoeken, hoe vollediger je beeld. Een verhaal dat nergens wringt, heeft meestal bronnen weggelaten."),
    dict(type="meerkeuze",
         vraag="Wat is de laatste stap voor je een historische vraag beantwoordt?",
         opties=["de informatie uit de bronnen samenbrengen met je historische kennis",
                 "de bronnen op volgorde van grootte en lengte leggen",
                 "de mooiste bron uitkiezen en daar het antwoord letterlijk uit overnemen",
                 "nieuwe bronnen zoeken tot ze allemaal hetzelfde zeggen"],
         antwoord=0,
         uitleg="Bronnen alleen volstaan niet: je hebt de context nodig om ze te begrijpen. Daarom staan kennis en bronnenanalyse op het examen naast elkaar."),
]
