# -*- coding: utf-8 -*-
"""Modern imperialisme, Congo en China.

Het derde blok leerinhouden van de moderne tijd: het Europese imperialisme met
zijn voorwaarden en motieven, de wedloop om Afrika, Azië, de rol van de
Verenigde Staten, Japan en Rusland, en daarna het Belgische imperialisme in
Congo. De leerstof zet daar één niet-westerse samenleving naast, China, met
haar binnenlandse problemen en haar contacten met het Westen.

Deel 1 gaat over het verschijnsel zelf: hoe Europa de halve wereld kon bezetten
en waarom het dat deed.
Deel 2 gaat over twee gevallen van dichtbij: Congo onder Leopold II en onder
België, en China dat niet gekoloniseerd werd maar wel opengebroken. Beeldvorming
hoort daar uitdrukkelijk bij: hoe wij naar die geschiedenis kijken, is zelf
veranderd.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Rond 1880 begint Europa in enkele decennia bijna heel Afrika te bezetten. Hoe noemt men die periode?",
         opties=["het modern imperialisme", "de grote volksverhuizing", "de koloniale restauratie", "de tweede ontdekkingstijd"],
         antwoord=0,
         uitleg="Imperium betekent rijk. Modern imperialisme onderscheidt die golf van de oudere handelskolonies van de 16de en 17de eeuw."),
    dict(type="meerkeuze",
         vraag="Welke technische voorsprong maakte het Europese imperialisme mogelijk?",
         opties=["repeteergeweren en mitrailleurs",
                 "stoomschepen die rivieren op konden varen",
                 "kinine als bescherming tegen malaria",
                 "vliegtuigen om gebieden in kaart te brengen"],
         antwoord=[0, 1, 2],
         uitleg="Vliegtuigen bestonden nog niet. Wapens, stoomkracht en geneesmiddelen samen maakten het binnenland van Afrika plots bereikbaar."),
    dict(type="meerkeuze",
         vraag="Welk motief voor imperialisme is economisch van aard?",
         opties=["goedkope grondstoffen voor de eigen fabrieken",
                 "prestige tegenover de andere mogendheden",
                 "het verspreiden van het christelijk geloof",
                 "het in kaart brengen van onbekende streken"],
         antwoord=0,
         uitleg="Grondstoffen binnenhalen en producten kwijt kunnen, dat is de economische kant. De drie andere zijn politieke, religieuze en wetenschappelijke motieven."),
    dict(type="waarofniet",
         vraag="Europese mogendheden rechtvaardigden hun koloniën met het idee dat zij beschaving brachten.",
         antwoord=True,
         uitleg="De zogenaamde beschavingsmissie. Ze steunde op de overtuiging dat de eigen cultuur hoger stond, en dat idee werd met sociaal darwinisme van een wetenschappelijk kleedje voorzien."),
    dict(type="meerkeuze",
         vraag="Op welke conferentie spraken de Europese mogendheden in 1884 en 1885 de regels voor Afrika af?",
         opties=["de Conferentie van Berlijn", "het Congres van Wenen", "de Conferentie van Londen", "het Verdrag van Versailles"],
         antwoord=0,
         uitleg="Bismarck nodigde uit. Geen enkele Afrikaanse heerser zat mee aan tafel, terwijl het over hun grondgebied ging."),
    dict(type="meerkeuze",
         vraag="Welke regel sprak men op die conferentie af om aanspraak te maken op een gebied?",
         opties=["je moest het gebied werkelijk bezetten en besturen",
                 "je moest er als eerste geweest zijn",
                 "je moest de bevolking om toestemming vragen",
                 "je moest het gebied van een ander land kopen"],
         antwoord=0,
         uitleg="De regel van de effectieve bezetting. Juist daardoor ging de wedloop zo snel: wie treuzelde, verloor het gebied aan een ander."),
    dict(type="waarofniet",
         vraag="Tegen 1914 was vrijwel heel Afrika onder Europese mogendheden verdeeld.",
         antwoord=True,
         uitleg="Alleen Ethiopië en Liberia bleven zelfstandig. Ethiopië had de Italianen in 1896 bij Adwa verslagen."),
    dict(type="meerkeuze",
         vraag="Welke Europese landen hadden grote koloniën in Azië?",
         opties=["Groot-Brittannië in Indië",
                 "Frankrijk in Indochina",
                 "Nederland in de Indische archipel",
                 "Zweden in Japan"],
         antwoord=[0, 1, 2],
         uitleg="Zweden had geen koloniën in Azië, en Japan is nooit gekoloniseerd. Het werd zelf een koloniale mogendheid."),
    dict(type="meerkeuze",
         vraag="Wat deed Japan vanaf de Meiji-restauratie van 1868?",
         opties=["het moderniseerde snel en werd zelf een koloniale macht",
                 "het sloot zich volledig af van de buitenwereld",
                 "het werd een kolonie van de Verenigde Staten",
                 "het verdeelde zijn gebied onder Europese landen"],
         antwoord=0,
         uitleg="Japan nam westerse techniek en legerorganisatie over, versloeg China en Rusland, en lijfde Taiwan en Korea in."),
    dict(type="meerkeuze",
         vraag="Waarom was Rusland in de 19de eeuw in Oost-Azië aanwezig?",
         opties=["het breidde over land uit tot aan de Stille Oceaan",
                 "het zocht koloniën over zee zoals Groot-Brittannië",
                 "het kreeg gebieden toegewezen in Berlijn",
                 "het werd door China om bijstand gevraagd"],
         antwoord=0,
         uitleg="De Russische uitbreiding liep over Siberië naar Mantsjoerije, dus niet per schip. Dat botste uiteindelijk met Japan."),
    dict(type="waarofniet",
         vraag="De Verenigde Staten hielden zich in deze periode volledig buiten het imperialisme.",
         antwoord=False,
         uitleg="Ze namen de Filipijnen in 1898 over van Spanje en eisten in China een open deur voor hun handel."),
    dict(type="invultekst",
         vraag="Welke twee Afrikaanse staten bleven rond 1914 zelfstandig? Noem er één.",
         antwoord=["Ethiopie", "Ethiopië", "Liberia"],
         uitleg="Ethiopië en Liberia. Ethiopië versloeg Italië bij Adwa in 1896, Liberia was gesticht door vrijgelaten slaven uit Amerika."),
    dict(type="meerkeuze",
         vraag="Welke gevolgen had het Europese imperialisme voor de bezette gebieden?",
         opties=["grenzen die dwars door volkeren liepen",
                 "een economie die op uitvoer naar Europa werd afgestemd",
                 "gezagsstructuren die door de kolonisator werden vervangen",
                 "een snelle verspreiding van algemeen stemrecht"],
         antwoord=[0, 1, 2],
         uitleg="Stemrecht kwam er juist niet: de bevolking had geen politieke rechten. De eerste drie werken tot vandaag door."),
    dict(type="meerkeuze",
         vraag="Wat betekent het dat koloniale grenzen vaak met een lat getrokken lijken?",
         opties=["ze volgden Europese afspraken en geen bestaande samenlevingen",
                 "ze liepen altijd langs rivieren en bergen",
                 "ze werden door de lokale heersers bepaald",
                 "ze bleven na de onafhankelijkheid ongewijzigd"],
         antwoord=0,
         uitleg="Op de kaart in Berlijn was een rechte lijn de eenvoudigste oplossing. Dat verdeelde volkeren en zette andere samen in één staat."),
    dict(type="waarofniet",
         vraag="Het sociaal darwinisme paste het idee van de strijd om het bestaan toe op volkeren en gebruikte dat om overheersing goed te praten.",
         antwoord=True,
         uitleg="Darwin schreef over soorten in de natuur. Anderen rekten dat op tot een rangorde van volkeren, en dat was geen wetenschap maar een excuus."),
    dict(type="meerkeuze",
         vraag="Welke rol speelden missionarissen in de koloniën?",
         opties=["ze verspreidden het geloof en richtten scholen op",
                 "ze bestuurden de kolonie in naam van de koning",
                 "ze baatten de grote mijnen uit",
                 "ze onderhandelden de grenzen met andere landen"],
         antwoord=0,
         uitleg="Geloof en onderwijs gingen samen. Daardoor bepaalden zij in de praktijk mee wat een hele generatie leerde en dacht."),
    dict(type="meerkeuze",
         vraag="Wat is een invloedssfeer?",
         opties=["een gebied waar een mogendheid de dienst uitmaakt zonder het te besturen",
                 "een kolonie met een eigen gouverneur ter plaatse",
                 "een streek waar twee landen samen besturen",
                 "een handelspost die aan een bedrijf toebehoort"],
         antwoord=0,
         uitleg="China werd niet gekoloniseerd maar wel in zulke sferen verdeeld. Op papier bleef het zelfstandig, in de praktijk veel minder."),
    dict(type="invultekst",
         vraag="Welk geneesmiddel tegen malaria maakte het voor Europeanen mogelijk om het Afrikaanse binnenland in te trekken? Eén woord.",
         antwoord=["kinine", "chinine"],
         uitleg="Kinine, gewonnen uit de bast van de kinaboom. Zonder dat middel bleef Afrika voor Europeanen letterlijk dodelijk."),
    dict(type="waarofniet",
         vraag="Het modern imperialisme speelde zich enkel in het economische domein af.",
         antwoord=False,
         uitleg="Het is politiek, economisch, sociaal en cultureel tegelijk: macht, grondstoffen, rangorde tussen bevolkingsgroepen en een beschavingsidee."),
    dict(type="meerkeuze",
         vraag="Waarom spreekt men van een wedloop om Afrika?",
         opties=["de mogendheden bezetten gebieden uit schrik voor elkaar",
                 "er werden sportwedstrijden om gebieden gehouden",
                 "men zocht een weg naar de bron van de Nijl",
                 "men wilde het continent zo snel mogelijk in kaart brengen"],
         antwoord=0,
         uitleg="Elk gebied dat jij niet nam, viel in handen van je rivaal. Die logica joeg de bezetting in twintig jaar over het hele continent."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat was de Congo-Vrijstaat tussen 1885 en 1908?",
         opties=["het persoonlijke bezit van Leopold II",
                 "een gewone kolonie van de Belgische staat",
                 "een gebied onder bestuur van de Verenigde Naties",
                 "een zelfstandige staat met een Congolese koning"],
         antwoord=0,
         uitleg="Niet België maar de koning zelf was eigenaar. Het Belgische parlement had er al die jaren niets over te zeggen."),
    dict(type="invultekst",
         vraag="Welke ontdekkingsreiziger verkende Congo voor Leopold II en sloot er verdragen met lokale leiders? Schrijf zijn familienaam.",
         antwoord=["Stanley"],
         uitleg="Henry Morton Stanley. De verdragen die hij liet tekenen, werden in Berlijn als bewijs van bezit aanvaard."),
    dict(type="meerkeuze",
         vraag="Waarmee verdiende de Congo-Vrijstaat vooral geld?",
         opties=["rubber en ivoor", "katoen en thee", "steenkool en staal", "graan en vee"],
         antwoord=0,
         uitleg="De opkomst van de auto- en fietsband maakte rubber plots enorm waardevol, en dat bepaalde het hele bestuur van de kolonie."),
    dict(type="meerkeuze",
         vraag="Hoe werkte het rubberregime in de Congo-Vrijstaat?",
         opties=["dorpen moesten een vastgelegde hoeveelheid rubber leveren",
                 "wie te weinig leverde, werd zwaar gestraft",
                 "vrouwen en kinderen werden gegijzeld als drukmiddel",
                 "de bevolking kreeg een eerlijke prijs voor haar werk"],
         antwoord=[0, 1, 2],
         uitleg="Van een prijs was geen sprake: het was een opgelegde levering. Wie het quotum niet haalde, riskeerde verminking of de dood."),
    dict(type="waarofniet",
         vraag="De bevolking van Congo nam tijdens de Vrijstaat sterk af door geweld, honger en ziekte.",
         antwoord=True,
         uitleg="Historici verschillen over de cijfers, maar niet over de richting. Geweld, ontwrichte landbouw en epidemieën werkten op elkaar in."),
    dict(type="meerkeuze",
         vraag="Wie voerden rond 1900 campagne tegen het bewind in de Congo-Vrijstaat?",
         opties=["Edmund Dene Morel met zijn hervormingsbeweging",
                 "Roger Casement met zijn verslag voor de Britse regering",
                 "schrijvers zoals Mark Twain en Arthur Conan Doyle",
                 "de Belgische regering vanaf het eerste uur"],
         antwoord=[0, 1, 2],
         uitleg="De Belgische regering kwam pas in beweging toen de internationale druk te groot werd, en nam de kolonie in 1908 over."),
    dict(type="invultekst",
         vraag="In welk jaar nam de Belgische staat de kolonie van Leopold II over? Schrijf het jaartal.",
         antwoord=["1908"],
         uitleg="Vanaf dan heette het Belgisch Congo, en had het parlement in Brussel er wel zeggenschap over."),
    dict(type="meerkeuze",
         vraag="Welke drie machten bestuurden samen Belgisch Congo?",
         opties=["de staat met haar ambtenaren en leger",
                 "de kerk met haar missies en scholen",
                 "de grote bedrijven met hun mijnen en plantages",
                 "een verkozen Congolees parlement"],
         antwoord=[0, 1, 2],
         uitleg="Men noemt dat de koloniale drie-eenheid. Een Congolees parlement bestond niet: de bevolking had geen politieke rechten."),
    dict(type="meerkeuze",
         vraag="Wat betekent paternalisme in het koloniale bestuur?",
         opties=["men behandelt de bevolking als kinderen die men opvoedt",
                 "men laat het bestuur over aan lokale koningen",
                 "men geeft de bevolking stap voor stap stemrecht",
                 "men vraagt de bevolking om advies bij elke beslissing"],
         antwoord=0,
         uitleg="Pater betekent vader. Zo stelde men het ook voor: zorgen voor de bevolking, maar vooral beslissen in haar plaats."),
    dict(type="meerkeuze",
         vraag="Welke grondstoffen leverde Belgisch Congo?",
         opties=["koper uit Katanga", "diamant", "uranium", "steenkool voor de Belgische mijnen"],
         antwoord=[0, 1, 2],
         uitleg="Steenkool kwam uit België zelf. Het uranium van Shinkolobwe belandde later in de eerste Amerikaanse atoombommen."),
    dict(type="waarofniet",
         vraag="Het onderwijs in Belgisch Congo lag vooral in handen van de missies en bleef grotendeels bij lager onderwijs steken.",
         antwoord=True,
         uitleg="Pas kort voor de onafhankelijkheid studeerden de eerste Congolezen af aan een universiteit. Bestuursfuncties bleven al die tijd voor Belgen."),
    dict(type="meerkeuze",
         vraag="Hoe is de beeldvorming over Leopold II en Congo in België veranderd?",
         opties=["van koning-bouwer naar een veel kritischer blik",
                 "van omstreden naar algemeen bewonderd",
                 "ze is al honderd jaar onveranderd gebleven",
                 "ze was vanaf 1908 meteen kritisch"],
         antwoord=0,
         uitleg="Lang stonden vooral zijn gebouwen en parken in de schoolboeken. Onderzoek, getuigenissen en debat over standbeelden hebben dat beeld bijgesteld."),
    dict(type="waarofniet",
         vraag="Dat de blik op een koloniaal verleden verandert, betekent dat de feiten veranderen.",
         antwoord=False,
         uitleg="De feiten liggen vast; wat verandert, is welke feiten men belangrijk vindt en wiens getuigenis men meetelt. Dat is net wat beeldvorming is."),
    dict(type="meerkeuze",
         vraag="Welke dynastie regeerde China in de 19de eeuw?",
         opties=["de Qing-dynastie", "de Ming-dynastie", "de Han-dynastie", "de Tang-dynastie"],
         antwoord=0,
         uitleg="De Qing regeerden van 1644 tot 1912. In de 19de eeuw verzwakte hun gezag door opstanden en buitenlandse druk."),
    dict(type="meerkeuze",
         vraag="Met welke binnenlandse problemen kampte China in de 19de eeuw?",
         opties=["een sterk groeiende bevolking op te weinig grond",
                 "wijdverspreide corruptie in het bestuur",
                 "grote opstanden zoals die van de Taiping",
                 "een tekort aan arbeidskrachten in de landbouw"],
         antwoord=[0, 1, 2],
         uitleg="Aan mensen was er geen tekort, integendeel. De Taiping-opstand kostte miljoenen levens en verzwakte de staat jarenlang."),
    dict(type="meerkeuze",
         vraag="Waarover gingen de Opiumoorlogen tussen China en Groot-Brittannië?",
         opties=["over de Britse handel in opium die China wilde stoppen",
                 "over de grens tussen China en Brits-Indië",
                 "over het bezit van Taiwan",
                 "over de bescherming van missionarissen"],
         antwoord=0,
         uitleg="Britse handelaars voerden opium in om hun tekort op de theehandel te dekken. Toen China die handel verbood, volgde de oorlog."),
    dict(type="invultekst",
         vraag="Welke stad moest China in 1842 bij het Verdrag van Nanking aan Groot-Brittannië afstaan? Schrijf de naam.",
         antwoord=["Hongkong", "Hong Kong"],
         uitleg="Hongkong bleef Brits tot 1997. Het verdrag opende daarnaast vijf havens voor westerse handel."),
    dict(type="meerkeuze",
         vraag="Waarom noemt men de verdragen die China na de Opiumoorlogen tekende ongelijke verdragen?",
         opties=["ze legden enkel aan China verplichtingen op",
                 "ze golden maar voor één jaar",
                 "ze waren door beide partijen afgedwongen",
                 "ze werden nooit werkelijk uitgevoerd"],
         antwoord=0,
         uitleg="China gaf havens, gebieden en rechtsmacht weg en kreeg er niets voor terug. Westerlingen vielen er zelfs niet onder het Chinese recht."),
    dict(type="waarofniet",
         vraag="China werd in de 19de eeuw volledig gekoloniseerd zoals Congo.",
         antwoord=False,
         uitleg="China bleef formeel zelfstandig, maar werd wel in invloedssferen verdeeld. Dat verschil tussen vorm en werkelijkheid is net wat je moet kunnen uitleggen."),
    dict(type="meerkeuze",
         vraag="Welk gevolg hadden de westerse contacten voor het Chinese keizerrijk?",
         opties=["het gezag van de keizer verzwakte en in 1912 viel het rijk",
                 "het keizerrijk werd sterker door de nieuwe handel",
                 "China sloot zich volledig af van het buitenland",
                 "de keizer werd vervangen door een westerse gouverneur"],
         antwoord=0,
         uitleg="Verloren oorlogen, ongelijke verdragen en opstanden ondermijnden de Qing. Na de revolutie van 1911 werd China een republiek."),
]
