# -*- coding: utf-8 -*-
"""Dramatiek en theatertekens — 🌍 Beyond, Nederlands.

Naast de termenlijst van de vakfiche geschreven. Deel 1: de dramatische
vormen, van het abel spel tot spoken word. Deel 2: de theatertekens en de
opvoeringsanalyse, met monoloog, dialoog en polyloog.
"""

DEEL1 = [
    dict(
        type="meerkeuze",
        vraag="Wat kenmerkt een tragedie?",
        opties=[
            "de hoofdfiguur gaat onafwendbaar ten onder",
            "de hoofdfiguur trouwt op het einde",
            "de personages zijn allemaal dieren",
            "het stuk duurt nooit langer dan een uur",
        ],
        antwoord=0,
        uitleg="In een tragedie loopt het slecht af, en meestal is de held daar zelf mee de oorzaak van.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke vormen horen bij het middeleeuwse toneel?",
        opties=[
            "het abel spel",
            "het mirakelspel",
            "de moraliteit",
            "het episch theater",
        ],
        antwoord=[0, 1, 2],
        uitleg="Episch theater is twintigste-eeuws. De drie andere zijn middeleeuws, met respectievelijk een ernstig verhaal, een wonder en een les.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je een kort, grof komisch toneelstuk met veel verwarring en misverstanden? Antwoord met één woord.",
        antwoord=["klucht"],
        uitleg="De klucht mikt op de lach, met typen in plaats van uitgewerkte personages.",
    ),
    dict(
        type="waarofniet",
        vraag="Een komedie heet in het Nederlands ook een blijspel.",
        antwoord=True,
        uitleg="Een blijspel loopt goed af en lacht met de gebreken van de personages.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is een tragikomedie?",
        opties=[
            "een stuk waarin het tragische en het komische samengaan",
            "een stuk dat begint als komedie en stopt na één bedrijf",
            "een stuk dat tweemaal na elkaar wordt opgevoerd",
            "een stuk zonder enige vorm van dialoog",
        ],
        antwoord=0,
        uitleg="Je lacht en je slikt in hetzelfde stuk. Veel hedendaags theater zit in die hoek.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat kenmerkt het absurd theater?",
        opties=[
            "de wereld op het toneel heeft geen zinvolle logica",
            "de personages dragen altijd historische kostuums",
            "het stuk wordt volledig gezongen uitgevoerd",
            "het publiek speelt zelf een rol in het stuk",
        ],
        antwoord=0,
        uitleg="Gesprekken draaien in cirkels, er gebeurt niets, en net die zinloosheid is het onderwerp.",
    ),
    dict(
        type="waarofniet",
        vraag="Het mysteriespel was een wereldlijk toneelstuk zonder enig religieus onderwerp.",
        antwoord=False,
        uitleg="Het mysteriespel bracht net Bijbelse verhalen op het kerkplein, vaak met veel spelers en grote taferelen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is een moraliteit?",
        opties=[
            "een toneelstuk dat een zedenles uitbeeldt",
            "een toneelstuk over het leven van een heilige",
            "een toneelstuk dat met het gezag spot",
            "een toneelstuk zonder enig decor",
        ],
        antwoord=0,
        uitleg="De personages zijn vaak abstracte begrippen, zoals Deugd of Dood, die samen een les uitbeelden.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je de Italiaanse theatervorm met vaste typen en veel improvisatie? Vul aan: commedia dell'...",
        antwoord=["arte"],
        uitleg="De commedia dell'arte werkte met vaste maskers en typen, waarbinnen de spelers vrij improviseerden.",
    ),
    dict(
        type="waarofniet",
        vraag="Episch theater wil dat het publiek zich volledig in de personages inleeft.",
        antwoord=False,
        uitleg="Het doet net het omgekeerde: het doorbreekt de illusie zodat de toeschouwer blijft nadenken in plaats van meeleven.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke vormen zijn modern of hedendaags?",
        opties=[
            "de musical",
            "spoken word",
            "het absurd theater",
            "het abel spel",
        ],
        antwoord=[0, 1, 2],
        uitleg="Het abel spel is middeleeuws. De drie andere horen bij de twintigste en de eenentwintigste eeuw.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is spoken word?",
        opties=[
            "gesproken poëzie, gebracht voor een publiek",
            "een toneelstuk dat volledig geïmproviseerd wordt",
            "een stuk waarin niemand een woord zegt",
            "een vorm van toneel met enkel zang",
        ],
        antwoord=0,
        uitleg="De tekst is gemaakt om gehoord te worden. Ritme, stem en lichaam horen erbij.",
    ),
    dict(
        type="waarofniet",
        vraag="Een abel spel is een ernstig, wereldlijk toneelstuk uit de middeleeuwen.",
        antwoord=True,
        uitleg="Abel betekent kunstig. Het zijn de oudste ernstige, niet-religieuze toneelteksten in onze taal.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een stuk waarin een machtige figuur door zijn eigen trots ten val komt. Welke vorm is dat?",
        opties=[
            "de tragedie",
            "de klucht",
            "de musical",
            "het mirakelspel",
        ],
        antwoord=0,
        uitleg="De val van een groot personage door een eigen gebrek is de kern van de klassieke tragedie.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is het verschil tussen een klucht en een komedie?",
        opties=[
            "de klucht is grover en mikt enkel op de lach",
            "de komedie loopt slecht af en de klucht goed",
            "de klucht wordt gezongen en de komedie gespeeld",
            "er bestaat geen verschil tussen die twee",
        ],
        antwoord=0,
        uitleg="Een komedie kan iets te zeggen hebben over de mens; een klucht wil vooral dat je lacht.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je een toneelstuk waarin een heilige een wonder verricht? Antwoord met één woord.",
        antwoord=["mirakelspel"],
        uitleg="Een mirakel is een wonder. Zulke stukken hoorden bij het religieuze toneel van de middeleeuwen.",
    ),
    dict(
        type="waarofniet",
        vraag="Een musical is een toneelvorm waarin zang, dans en tekst samen het verhaal dragen.",
        antwoord=True,
        uitleg="De liedjes brengen het verhaal verder in plaats van het te onderbreken.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarom is dramatiek een aparte hoofdgroep naast epiek en lyriek?",
        opties=[
            "een toneeltekst is geschreven om gespeeld te worden",
            "een toneeltekst bevat altijd rijm",
            "een toneeltekst is korter dan een roman",
            "een toneeltekst heeft nooit een verteller nodig",
        ],
        antwoord=0,
        uitleg="De tekst is maar de helft; de opvoering maakt hem af. Daarom lees je een toneeltekst anders dan een roman.",
    ),
    dict(
        type="meerkeuze",
        vraag="In een stuk draagt een personage een masker met een vast, overdreven gezicht. Welke traditie roept dat op?",
        opties=[
            "de commedia dell'arte",
            "het episch theater",
            "het mysteriespel",
            "de musical",
        ],
        antwoord=0,
        uitleg="Vaste maskers voor vaste typen: de gierige oude man, de slimme knecht, de verliefde jongeling.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een klassiek drama wordt vaak verdeeld in?",
        opties=[
            "bedrijven en tonelen",
            "strofen en verzen",
            "hoofdstukken en alinea's",
            "coupletten en refreinen",
        ],
        antwoord=0,
        uitleg="Een bedrijf is een groot deel, een toneel of scène een kleiner stuk daarbinnen.",
    ),
]

DEEL2 = [
    dict(
        type="meerkeuze",
        vraag="Wat zijn theatertekens?",
        opties=[
            "alles op het toneel dat betekenis draagt",
            "de aanwijzingen die cursief in de tekst staan",
            "de leestekens in een toneeltekst",
            "de namen van de personages boven hun zinnen",
        ],
        antwoord=0,
        uitleg="Kostuum, licht, geluid, decor, een gebaar: alles wat de toeschouwer ziet of hoort, betekent iets.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke theatertekens horen bij de speler zelf?",
        opties=[
            "mimiek",
            "gestiek",
            "fysionomie",
            "belichting",
        ],
        antwoord=[0, 1, 2],
        uitleg="Belichting komt van buitenaf. Gezichtsuitdrukking, gebaren en lichaamsbouw horen bij de speler.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je het theaterteken dat gaat over de afstand tussen de spelers op het toneel? Antwoord met één woord.",
        antwoord=["proxemiek"],
        uitleg="Wie dicht bij elkaar staat of juist ver uit elkaar, vertelt daarmee iets over hun verhouding.",
    ),
    dict(
        type="waarofniet",
        vraag="Een schijnwerper die één personage uitlicht, kan zijn isolement uitdrukken.",
        antwoord=True,
        uitleg="Belichting is een theaterteken: wat in het licht staat en wat in het donker blijft, is een keuze met betekenis.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is mimiek?",
        opties=[
            "de uitdrukking op het gezicht",
            "de beweging van armen en handen",
            "de plaats die iemand inneemt op scène",
            "de kleding die een speler draagt",
        ],
        antwoord=0,
        uitleg="Mimiek is het spel van het gezicht. Gebaren heten gestiek.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat zijn paraverbale tekens?",
        opties=[
            "alles aan de stem behalve de woorden zelf",
            "de woorden die de personages uitspreken",
            "de voorwerpen die de spelers hanteren",
            "de aanwijzingen van de regisseur in de tekst",
        ],
        antwoord=0,
        uitleg="Toonhoogte, tempo, volume en pauzes: daarmee zegt een speler evenveel als met de woorden.",
    ),
    dict(
        type="waarofniet",
        vraag="Donkere kostuums kunnen de mentale toestand van een personage weerspiegelen.",
        antwoord=True,
        uitleg="Kostumering is een theaterteken. Kleur en snit zeggen iets over wie iemand is en hoe het met hem gaat.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een speler houdt tijdens het hele stuk een versleten koffer vast. Welk theaterteken is dat?",
        opties=[
            "een rekwisiet",
            "het decor",
            "de belichting",
            "de proxemiek",
        ],
        antwoord=0,
        uitleg="Rekwisieten zijn de voorwerpen die de spelers gebruiken. Een koffer die niet loslaat, draagt al snel betekenis.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je een toneeltekst waarin één personage alleen aan het woord is? Antwoord met één woord.",
        antwoord=["monoloog"],
        uitleg="Bij een monoloog spreekt er één; bij een dialoog twee; bij een polyloog meer dan twee.",
    ),
    dict(
        type="waarofniet",
        vraag="Een polyloog is een gesprek tussen meer dan twee personages.",
        antwoord=True,
        uitleg="Poly betekent veel. Zo'n scène vraagt van een regisseur dat hij de aandacht van het publiek stuurt.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat onderzoek je bij een opvoeringsanalyse?",
        opties=[
            "hoe de keuzes op scène de tekst betekenis geven",
            "of de acteurs hun tekst juist uit het hoofd kennen",
            "hoeveel kaartjes er voor de voorstelling verkocht zijn",
            "in welk jaar de toneeltekst geschreven werd",
        ],
        antwoord=0,
        uitleg="Dezelfde tekst kan twee heel verschillende voorstellingen opleveren. Een opvoeringsanalyse kijkt naar die keuzes.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke tekens horen bij de ruimte op het toneel?",
        opties=[
            "het decor",
            "de belichting",
            "de ruimtegestiek",
            "de fysionomie",
        ],
        antwoord=[0, 1, 2],
        uitleg="Fysionomie gaat over het lichaam van de speler zelf. De drie andere vormen samen de scenische ruimte.",
    ),
    dict(
        type="waarofniet",
        vraag="Sombere muziek onder een scène is geen theaterteken, want ze staat niet in de tekst.",
        antwoord=False,
        uitleg="Geluid en muziek zijn volwaardige theatertekens. Dat ze later toegevoegd zijn, maakt ze net tot een keuze van de makers.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een regisseur zet een klassiek stuk in een hedendaags kantoor. Wat doet die ingreep?",
        opties=[
            "ze legt een verband tussen toen en nu",
            "ze verandert de woorden van de tekst",
            "ze maakt het stuk korter in speelduur",
            "ze schrapt alle theatertekens",
        ],
        antwoord=0,
        uitleg="De tekst blijft, het kader verschuift. Daardoor ga je het stuk lezen als iets over je eigen tijd.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is gestiek?",
        opties=[
            "de gebaren die een speler maakt",
            "de uitdrukking op zijn gezicht",
            "de kleding die hij draagt",
            "het geluid dat hem begeleidt",
        ],
        antwoord=0,
        uitleg="Gestiek gaat over wat handen, armen en lichaam doen; mimiek over het gezicht.",
    ),
    dict(
        type="waarofniet",
        vraag="Een toneeltekst lezen is hetzelfde als een opvoering analyseren.",
        antwoord=False,
        uitleg="Bij een tekstanalyse kijk je naar wat er staat; bij een opvoeringsanalyse naar wat de makers ermee doen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Twee personages staan het hele stuk aan weerszijden van de scène en komen nooit dichterbij. Wat zegt dat?",
        opties=[
            "de afstand tussen hen wordt zichtbaar gemaakt",
            "de belichting is verkeerd ingesteld",
            "de spelers kennen hun tekst duidelijk niet goed",
            "het decor is te breed uitgevallen",
        ],
        antwoord=0,
        uitleg="Dat is proxemiek: de ruimte tussen mensen wordt een beeld van hun verhouding.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je de voorwerpen die spelers op scène hanteren? Antwoord met één woord.",
        antwoord=["rekwisieten"],
        uitleg="Een brief, een glas, een wapen: elk rekwisiet dat in beeld komt, draagt betekenis.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarom is een toneeltekst nooit helemaal af op papier?",
        opties=[
            "de opvoering voegt een hele laag tekens toe",
            "een toneeltekst bevat altijd te weinig woorden",
            "een toneeltekst mag niet gelezen worden",
            "een toneeltekst heeft geen vaste auteur",
        ],
        antwoord=0,
        uitleg="Licht, geluid, decor, lichaam en stem komen er pas bij in de zaal, en ze kunnen de tekst zelfs tegenspreken.",
    ),
    dict(
        type="meerkeuze",
        vraag="In een stuk richt een speler zich plots rechtstreeks tot de zaal. Bij welke traditie past dat?",
        opties=[
            "het episch theater",
            "het mysteriespel",
            "de commedia dell'arte",
            "het klassieke drama",
        ],
        antwoord=0,
        uitleg="Het episch theater doorbreekt de illusie met opzet, zodat de toeschouwer blijft nadenken.",
    ),
]
