# -*- coding: utf-8 -*-
"""Morfologie: samenstellingen, afleidingen en werkwoordstijden — 🌍 Beyond.

Naast de twee vakfiches geschreven. Deel 1: de bouw van woorden, met
samenstellingen, afleidingen, voor- en achtervoegsels, meervoud,
verkleinwoord en de tussenklank. Deel 2: stam, uitgang, verbuiging,
vervoeging en de zes werkwoordstijden.
"""

DEEL1 = [
    dict(
        type="meerkeuze",
        vraag="Wat is een samenstelling?",
        opties=[
            "een woord dat uit twee of meer woorden bestaat",
            "een woord met een voorvoegsel ervoor",
            "een woord met een achtervoegsel erachter geplakt",
            "een woord dat uit een vreemde taal overgenomen is",
        ],
        antwoord=0,
        uitleg="Tandarts, deurklink, boekenkast: twee zelfstandige woorden die samen een nieuw woord vormen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke woorden zijn afleidingen?",
        opties=[
            "vriendelijk",
            "onmogelijk",
            "werker",
            "huisdeur",
        ],
        antwoord=[0, 1, 2],
        uitleg="Huisdeur is een samenstelling van twee woorden. De drie andere zijn gevormd met een voor- of achtervoegsel.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je een deel dat vooraan aan een woord geplakt wordt, zoals on- of ver-? Antwoord met één woord.",
        antwoord=["voorvoegsel"],
        uitleg="Een voorvoegsel verandert de betekenis van het grondwoord zonder dat het zelf een woord is.",
    ),
    dict(
        type="waarofniet",
        vraag="Het achtervoegsel -heid maakt van een bijvoeglijk naamwoord een zelfstandig naamwoord.",
        antwoord=True,
        uitleg="Van vrij wordt vrijheid, van waar wordt waarheid. Het achtervoegsel verandert de woordsoort.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is de tussenklank in 'boekenkast'?",
        opties=[
            "de en tussen boek en kast",
            "de k aan het einde van boek",
            "de a in kast",
            "er is geen tussenklank",
        ],
        antwoord=0,
        uitleg="De tussenklank verbindt de twee delen van de samenstelling. In het schrift heet hij de tussenletter.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke woorden zijn verkleinwoorden?",
        opties=[
            "huisje",
            "bloempje",
            "koninkje",
            "huizen",
        ],
        antwoord=[0, 1, 2],
        uitleg="Huizen is een meervoud. De drie andere hebben het verkleinende achtervoegsel.",
    ),
    dict(
        type="waarofniet",
        vraag="Een verkleinwoord houdt in het Nederlands het lidwoord van het grondwoord.",
        antwoord=False,
        uitleg="Een verkleinwoord is altijd onzijdig: het blijft 'het huisje', ook al zeg je 'de tafel' en 'de bloem'.",
    ),
    dict(
        type="meerkeuze",
        vraag="Hoe vorm je het meervoud van 'kind'?",
        opties=[
            "kinderen",
            "kinds",
            "kinden",
            "kindes",
        ],
        antwoord=0,
        uitleg="Een kleine groep woorden vormt het meervoud op -eren: kind, blad, ei, lam, volk.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat betekent het voorvoegsel on- in 'onvriendelijk'?",
        opties=[
            "het keert de betekenis om",
            "het versterkt de betekenis",
            "het maakt er een verkleinwoord van",
            "het maakt er een meervoud van",
        ],
        antwoord=0,
        uitleg="On- ontkent: onmogelijk, oneerlijk, ongezond.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je een deel dat achteraan aan een woord wordt geplakt, zoals -heid of -baar? Antwoord met één woord.",
        antwoord=["achtervoegsel"],
        uitleg="Een achtervoegsel verandert vaak de woordsoort van het grondwoord.",
    ),
    dict(
        type="waarofniet",
        vraag="In een samenstelling kunnen ook drie woorden samengaan.",
        antwoord=True,
        uitleg="Kinderfietsbel of wereldkampioenschapsfinale: samenstellingen kunnen in het Nederlands blijven doorgroeien.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is het verschil tussen een samenstelling en een afleiding?",
        opties=[
            "een samenstelling bestaat uit zelfstandige woorden",
            "een samenstelling is altijd langer dan een afleiding",
            "een afleiding bevat altijd een werkwoord",
            "er bestaat geen verschil tussen die twee",
        ],
        antwoord=0,
        uitleg="Bij een afleiding is minstens één deel geen zelfstandig woord maar een voor- of achtervoegsel.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke woorden bevatten een tussenletter?",
        opties=[
            "pannenkoek",
            "zonnebloem",
            "koninginnendag",
            "tafelpoot",
        ],
        antwoord=[0, 1, 2],
        uitleg="Tafelpoot heeft geen verbindingsletter tussen de delen. De drie andere wel.",
    ),
    dict(
        type="waarofniet",
        vraag="Het meervoud van elk Nederlands woord wordt gevormd met -en of -s.",
        antwoord=False,
        uitleg="Er bestaan ook meervouden op -eren en onregelmatige vormen, zoals stad die steden wordt.",
    ),
    dict(
        type="meerkeuze",
        vraag="Hoe vorm je het verkleinwoord van 'koning'?",
        opties=[
            "koninkje",
            "koningje",
            "koningtje",
            "koningetje",
        ],
        antwoord=0,
        uitleg="Na de ng-klank wordt het achtervoegsel -kje en verdwijnt de g uit het schriftbeeld.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarom is het nuttig om de bouw van een woord te herkennen?",
        opties=[
            "je kan de betekenis vaak zelf afleiden",
            "je spreekt het woord dan vanzelf juist uit",
            "je weet dan uit welke taal het komt",
            "je kent dan meteen het meervoud",
        ],
        antwoord=0,
        uitleg="Wie ziet dat 'onverzoenlijk' uit on, verzoen en lijk bestaat, raadt de betekenis zonder woordenboek.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je de klank die twee delen van een samenstelling verbindt? Vul aan: de ...",
        antwoord=["tussenklank"],
        uitleg="In het schrift heet diezelfde verbinding de tussenletter.",
    ),
    dict(
        type="waarofniet",
        vraag="Het woord 'onvriendelijkheid' bevat zowel een voorvoegsel als een achtervoegsel.",
        antwoord=True,
        uitleg="On- staat vooraan, -lijk en -heid staan achteraan, en vriend is het grondwoord.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke woordsoort krijg je met het achtervoegsel -baar, zoals in 'leesbaar'?",
        opties=[
            "een bijvoeglijk naamwoord",
            "een zelfstandig naamwoord",
            "een werkwoord",
            "een bijwoord",
        ],
        antwoord=0,
        uitleg="Van het werkwoord lezen maakt -baar een bijvoeglijk naamwoord dat zegt dat iets gelezen kan worden.",
    ),
    dict(
        type="meerkeuze",
        vraag="Je ziet het woord 'onbereikbaarheid' voor het eerst. Hoe raad je de betekenis?",
        opties=[
            "je ontleedt het in zijn delen",
            "je kijkt naar de lengte van het woord",
            "je zoekt het meervoud ervan op",
            "je vertaalt het naar het Engels",
        ],
        antwoord=0,
        uitleg="On plus bereiken plus baar plus heid: de toestand van niet bereikt kunnen worden.",
    ),
]

DEEL2 = [
    dict(
        type="meerkeuze",
        vraag="Welke werkwoordstijden moet je kunnen onderscheiden?",
        opties=[
            "de onvoltooid tegenwoordige tijd",
            "de voltooid verleden tijd",
            "de onvoltooid toekomende tijd",
            "de voltooid toekomende verleden tijd",
        ],
        antwoord=[0, 1, 2],
        uitleg="De zes zijn: imperatief, ott, vtt, ovt, vvt en ottt. De vierde optie bestaat niet in die rij.",
    ),
    dict(
        type="meerkeuze",
        vraag="In welke tijd staat 'Hij had gewerkt'?",
        opties=[
            "de voltooid verleden tijd",
            "de voltooid tegenwoordige tijd",
            "de onvoltooid verleden tijd",
            "de onvoltooid tegenwoordige tijd",
        ],
        antwoord=0,
        uitleg="Een voltooide handeling in het verleden, met het hulpwerkwoord in de verleden tijd.",
    ),
    dict(
        type="invultekst",
        vraag="In welke tijd staat 'Hij heeft gewerkt'? Vul aan: de voltooid ... tijd.",
        antwoord=["tegenwoordige"],
        uitleg="Het hulpwerkwoord staat in de tegenwoordige tijd, dus het is de voltooid tegenwoordige tijd.",
    ),
    dict(
        type="waarofniet",
        vraag="'Loop!' staat in de gebiedende wijs of imperatief.",
        antwoord=True,
        uitleg="De imperatief geeft een bevel of een aansporing en bestaat uit de kale stam.",
    ),
    dict(
        type="meerkeuze",
        vraag="In welke tijd staat 'Hij zal morgen komen'?",
        opties=[
            "de onvoltooid toekomende tijd",
            "de onvoltooid tegenwoordige tijd",
            "de voltooid toekomende tijd",
            "de onvoltooid verleden tijd",
        ],
        antwoord=0,
        uitleg="Zullen plus een infinitief vormt de toekomende tijd, en de handeling is nog niet afgerond.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is de uitgang van een werkwoord?",
        opties=[
            "het deel dat na de stam komt bij het vervoegen",
            "het deel dat voor de stam komt bij het vervoegen",
            "de laatste letter van elk willekeurig woord",
            "het voltooid deelwoord van dat werkwoord",
        ],
        antwoord=0,
        uitleg="Werk plus en, werk plus te, werk plus t: telkens dezelfde stam met een andere uitgang.",
    ),
    dict(
        type="waarofniet",
        vraag="Verbuiging slaat op werkwoorden en vervoeging op naamwoorden.",
        antwoord=False,
        uitleg="Het is net omgekeerd: werkwoorden vervoeg je, naamwoorden en bijvoeglijke naamwoorden verbuig je.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke vormen staan in de onvoltooid verleden tijd?",
        opties=[
            "hij liep",
            "zij werkte",
            "wij dachten",
            "hij heeft gelopen",
        ],
        antwoord=[0, 1, 2],
        uitleg="De laatste is voltooid tegenwoordige tijd. De drie andere zijn onvoltooide verleden vormen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is een sterk werkwoord?",
        opties=[
            "een werkwoord dat in de verleden tijd van klinker verandert",
            "een werkwoord met een lange infinitief",
            "een werkwoord dat een bijzonder krachtige handeling uitdrukt",
            "een werkwoord dat enkel in bijzinnen staat",
        ],
        antwoord=0,
        uitleg="Zingen wordt zong en gezongen. Bij een zwak werkwoord blijft de klinker en komt er -te of -de bij.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je de vorm 'werk!' als bevel? Antwoord met één woord.",
        antwoord=["imperatief"],
        uitleg="De imperatief of gebiedende wijs bestaat uit de kale stam.",
    ),
    dict(
        type="waarofniet",
        vraag="Het werkwoord 'zijn' wordt in alle tijden volgens de gewone regels vervoegd.",
        antwoord=False,
        uitleg="Ben, is, was, waren, geweest: er valt weinig regel in te ontdekken. Het is het onregelmatigste werkwoord dat we hebben.",
    ),
    dict(
        type="meerkeuze",
        vraag="Hoe weet je of een zwak werkwoord -te of -de krijgt in de verleden tijd?",
        opties=[
            "je kijkt naar de laatste klank van de stam",
            "je kijkt naar de lengte van het werkwoord",
            "je kijkt naar het onderwerp van de zin",
            "je kijkt of het werkwoord scheidbaar is",
        ],
        antwoord=0,
        uitleg="Eindigt de stam op een scherpe medeklinker, dan komt er -te bij; anders -de.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke vormen zijn voltooide deelwoorden?",
        opties=[
            "gewerkt",
            "gelopen",
            "verwacht",
            "werken",
        ],
        antwoord=[0, 1, 2],
        uitleg="Werken is de infinitief. Verwacht krijgt geen ge omdat het voorvoegsel ver onbeklemtoond is.",
    ),
    dict(
        type="waarofniet",
        vraag="Een bijvoeglijk naamwoord krijgt in het Nederlands soms een extra e.",
        antwoord=True,
        uitleg="Een groot huis maar het grote huis. Die extra e is een verbuiging.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarom is het onderscheid tussen stam en uitgang belangrijk?",
        opties=[
            "de spelling van werkwoorden hangt ervan af",
            "de betekenis van de zin hangt ervan af",
            "de woordvolgorde hangt ervan af",
            "de keuze van het lidwoord hangt ervan af",
        ],
        antwoord=0,
        uitleg="Stam plus t, stam plus te, stam alleen: wie de stam niet vindt, spelt het werkwoord verkeerd.",
    ),
    dict(
        type="meerkeuze",
        vraag="In welke tijd staat 'Zij liepen naar huis'?",
        opties=[
            "de onvoltooid verleden tijd",
            "de voltooid verleden tijd",
            "de onvoltooid tegenwoordige tijd",
            "de voltooid tegenwoordige tijd",
        ],
        antwoord=0,
        uitleg="Het gebeurde in het verleden en de handeling wordt niet als afgerond voorgesteld.",
    ),
    dict(
        type="invultekst",
        vraag="Wat is de stam van het werkwoord 'antwoorden'? Antwoord met één woord.",
        antwoord=["antwoord"],
        uitleg="Antwoorden min en geeft antwoord. Bij hij komt daar nog een t bij.",
    ),
    dict(
        type="waarofniet",
        vraag="Een scheidbaar werkwoord valt in sommige zinnen uiteen in twee delen.",
        antwoord=True,
        uitleg="Opbellen wordt 'hij belt zijn moeder op'. Het voorvoegsel schuift naar achteren.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke tijd gebruik je om iets te vertellen wat nu bezig is?",
        opties=[
            "de onvoltooid tegenwoordige tijd",
            "de voltooid tegenwoordige tijd",
            "de onvoltooid verleden tijd",
            "de voltooid verleden tijd",
        ],
        antwoord=0,
        uitleg="Onvoltooid betekent nog niet afgerond, tegenwoordig betekent nu.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarom variëren goede schrijvers met werkwoordstijden?",
        opties=[
            "de tijd stuurt hoe de lezer de gebeurtenis plaatst",
            "een tekst moet alle zes de tijden bevatten",
            "variatie maakt de tekst automatisch korter",
            "de spellingregels verplichten die afwisseling",
        ],
        antwoord=0,
        uitleg="Een verhaal in de tegenwoordige tijd voelt nabij; in de verleden tijd voelt het afstandelijker en afgerond.",
    ),
]
