# -*- coding: utf-8 -*-
"""🌍 Beyond — Kracht en beweging.

Fysica, de kop "Kracht en beweging" uit de vakfiche natuurwetenschappen 3DO.
Deel 1 gaat over de drie bewegingen ERB, EVRB en ECB, en over hoe je ze aan
een x(t)-, v(t)- of a(t)-grafiek herkent. Deel 2 gaat over de drie wetten van
Newton, de soorten krachten en de resulterende kracht.
"""

DEEL1 = [
    dict(
        type="meerkeuze",
        vraag="Wat is kenmerkend voor een eenparig rechtlijnige beweging?",
        opties=[
            "de snelheid blijft gelijk en de baan is recht",
            "de snelheid groeit gelijkmatig aan op een rechte baan",
            "de snelheid blijft gelijk op een cirkelbaan",
            "de snelheid wisselt voortdurend van grootte",
        ],
        antwoord=0,
        uitleg="Bij een ERB is de versnelling nul. De resulterende kracht op het voorwerp is dan ook nul.",
    ),
    dict(
        type="invultekst",
        vraag="Met welke drie letters korten we een eenparig veranderlijke rechtlijnige beweging af?",
        antwoord=["EVRB", "evrb"],
        uitleg="De versnelling is daarbij constant maar niet nul. Is ze nul, dan heb je een ERB; gaat het over een cirkel, dan een ECB.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is er bij een eenparig cirkelvormige beweging voortdurend aan het veranderen?",
        opties=[
            "de richting van de snelheid",
            "de grootte van de snelheid",
            "de massa van het voorwerp",
            "de omtrek van de cirkel",
        ],
        antwoord=0,
        uitleg="De grootte van de snelheid blijft gelijk, maar de richting draait mee met de baan. Omdat snelheid een vector is, is er dus wel een versnelling.",
    ),
    dict(
        type="waarofniet",
        vraag="Bij een eenparig cirkelvormige beweging is er geen versnelling, want de snelheid verandert niet van grootte.",
        antwoord=False,
        uitleg="De richting van de snelheid verandert wel, en dat is al een verandering van de snelheidsvector. De versnelling wijst naar het middelpunt van de cirkel.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wanneer spreek je van een vertraagde beweging?",
        opties=[
            "als de versnelling tegen de bewegingszin in wijst",
            "als de versnelling juist in de bewegingszin wijst",
            "als de versnelling precies gelijk is aan nul",
            "als de baan van het voorwerp een cirkel wordt",
        ],
        antwoord=0,
        uitleg="Men spreekt dan ook van een negatieve versnelling. Wijst de versnelling mee met de beweging, dan versnelt het voorwerp.",
    ),
    dict(
        type="meerkeuze",
        vraag="Hoe ziet de x(t)-grafiek van een eenparig rechtlijnige beweging uit?",
        opties=[
            "een rechte schuine lijn",
            "een horizontale rechte lijn",
            "een parabool die steeds steiler wordt",
            "een golvende lijn op en neer",
        ],
        antwoord=0,
        uitleg="Elke seconde komt er dezelfde afstand bij, dus is de steilheid overal gelijk. Die steilheid is precies de snelheid.",
    ),
    dict(
        type="meerkeuze",
        vraag="Hoe ziet de v(t)-grafiek van een eenparig versnelde beweging uit?",
        opties=[
            "een rechte schuine lijn die stijgt",
            "een horizontale rechte lijn",
            "een parabool die naar beneden buigt",
            "een lijn die plots verspringt",
        ],
        antwoord=0,
        uitleg="Elke seconde komt er dezelfde snelheid bij, want de versnelling is constant. De a(t)-grafiek is dan een horizontale lijn.",
    ),
    dict(
        type="waarofniet",
        vraag="Op een v(t)-grafiek van een ERB is de lijn horizontaal.",
        antwoord=True,
        uitleg="De snelheid blijft gelijk, dus blijft de lijn op dezelfde hoogte. De a(t)-grafiek valt dan samen met de horizontale as.",
    ),
    dict(
        type="invultekst",
        vraag="Wat lees je af uit de steilheid van een x(t)-grafiek?",
        antwoord=["de snelheid", "snelheid"],
        uitleg="Hoe steiler de lijn, hoe sneller de beweging. Een horizontale lijn betekent dat het voorwerp stilstaat.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke uitspraken over een ERB zijn juist? Kruis alles aan wat juist is.",
        opties=[
            "de versnelling is nul",
            "de resulterende kracht is nul",
            "de x(t)-grafiek is een rechte schuine lijn",
            "de baan van het voorwerp is een cirkel",
        ],
        antwoord=[0, 1, 2],
        uitleg="Rechtlijnig betekent dat de baan een rechte is, geen cirkel. Dat de resulterende kracht nul is, volgt uit de eerste wet van Newton.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een auto rijdt met een constante snelheid van 50 km per uur op een rechte weg. Welke beweging is dat?",
        opties=["een ERB", "een EVRB", "een ECB", "een vertraagde beweging"],
        antwoord=0,
        uitleg="De snelheid verandert niet en de baan is recht, dus is het een ERB. De resulterende kracht op de auto is daarbij nul.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een steen valt van een toren. Welke beweging maakt hij, als je de luchtweerstand verwaarloost?",
        opties=[
            "een eenparig versnelde rechtlijnige beweging",
            "een eenparig rechtlijnige beweging met vaste snelheid",
            "een eenparig cirkelvormige beweging rond de toren",
            "een eenparig vertraagde rechtlijnige beweging",
        ],
        antwoord=0,
        uitleg="De zwaartekracht blijft gelijk, dus blijft de versnelling constant. De steen wint elke seconde dezelfde hoeveelheid snelheid.",
    ),
    dict(
        type="waarofniet",
        vraag="Een kind op een draaimolen die rond draait aan een vaste snelheid, maakt een eenparig cirkelvormige beweging.",
        antwoord=True,
        uitleg="De grootte van de snelheid blijft gelijk en de baan is een cirkel. Toch werkt er een kracht naar het midden, anders zou het kind rechtdoor gaan.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke kant op wijst de versnelling bij een eenparig cirkelvormige beweging?",
        opties=[
            "naar het middelpunt van de cirkel",
            "in de bewegingszin langs de baan",
            "van het middelpunt weg naar buiten",
            "recht naar beneden",
        ],
        antwoord=0,
        uitleg="Daarom moet er ook een kracht naar het midden werken, bijvoorbeeld door een koord of door wrijving. Houdt die kracht op, dan gaat het voorwerp rechtdoor.",
    ),
    dict(
        type="meerkeuze",
        vraag="Je ziet een x(t)-grafiek die een parabool vormt. Welke beweging is dat?",
        opties=["een EVRB", "een ERB", "een stilstand", "een ECB"],
        antwoord=0,
        uitleg="De lijn wordt steeds steiler, dus stijgt de snelheid gelijkmatig. Op de v(t)-grafiek wordt dat een rechte schuine lijn.",
    ),
    dict(
        type="waarofniet",
        vraag="Op een v(t)-grafiek van een vertraagde beweging stijgt de lijn.",
        antwoord=False,
        uitleg="De snelheid wordt elke seconde kleiner, dus zakt de lijn naar de as toe. De versnelling is dan negatief.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke uitspraken over de snelheidsvector zijn juist? Kruis alles aan wat juist is.",
        opties=[
            "ze ligt altijd langs de baan",
            "ze wijst in de zin van de beweging",
            "bij een cirkel raakt ze de cirkel in dat punt",
            "ze wijst altijd recht naar beneden",
        ],
        antwoord=[0, 1, 2],
        uitleg="Snelheid is een vector, dus heeft ze een grootte, een richting en een zin. Naar beneden wijst enkel de zwaartekracht.",
    ),
    dict(
        type="invultekst",
        vraag="Welke beweging heeft een rechte baan en een constante versnelling die niet nul is?",
        antwoord=["EVRB", "evrb"],
        uitleg="Dat is de eenparig veranderlijke rechtlijnige beweging. Ze kan versneld of vertraagd zijn, afhankelijk van de zin van de versnelling.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke uitspraken over de versnelling bij een EVRB zijn juist? Kruis alles aan wat juist is.",
        opties=[
            "ze blijft tijdens de beweging gelijk",
            "ze wijst mee met de beweging bij versnellen",
            "ze wijst tegen de beweging in bij vertragen",
            "ze is altijd gelijk aan nul",
        ],
        antwoord=[0, 1, 2],
        uitleg="Nul zou een ERB geven, geen EVRB. De grootte blijft gelijk, maar de zin bepaalt of het voorwerp sneller of trager gaat.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een trein remt gelijkmatig af tot stilstand op een recht spoor. Welke beweging is dat?",
        opties=[
            "een eenparig vertraagde rechtlijnige beweging",
            "een eenparig rechtlijnige beweging",
            "een eenparig cirkelvormige beweging",
            "een beweging zonder enige versnelling",
        ],
        antwoord=0,
        uitleg="De versnelling blijft constant maar wijst tegen de beweging in. Op de v(t)-grafiek zakt de lijn gelijkmatig naar nul.",
    ),
]

DEEL2 = [
    dict(
        type="meerkeuze",
        vraag="Wat zegt de eerste wet van Newton?",
        opties=[
            "zonder resulterende kracht blijft de snelheid van een lichaam gelijk",
            "de kracht is het product van massa en versnelling",
            "elke kracht heeft een even grote tegengestelde kracht",
            "een lichaam valt altijd met dezelfde versnelling",
        ],
        antwoord=0,
        uitleg="Die wet heet ook de traagheidswet. Een voorwerp blijft dus stilstaan of een ERB maken zolang er geen resulterende kracht op werkt.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe heet de eerste wet van Newton ook?",
        antwoord=["traagheidswet", "de traagheidswet"],
        uitleg="Traagheid is de neiging van een lichaam om zijn bewegingstoestand te houden. Daarom schuif je naar voren als een bus plots remt.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat zegt de tweede wet van Newton?",
        opties=[
            "de resulterende kracht is de massa maal de versnelling",
            "elke actie heeft een gelijke en tegengestelde reactie",
            "een lichaam zonder kracht blijft in rust of in een ERB",
            "de versnelling van een vallend lichaam is altijd gelijk",
        ],
        antwoord=0,
        uitleg="In formulevorm wordt dat F is gelijk aan m maal a, met kracht en versnelling als vectoren. De versnelling wijst dus in de zin van de resulterende kracht.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een vrachtwagen en een auto krijgen dezelfde kracht. Waarom versnelt de vrachtwagen minder?",
        opties=[
            "zijn massa is groter, en massa en versnelling zijn omgekeerd verbonden",
            "zijn motor is zwakker dan die van de auto",
            "er werkt op hem een grotere zwaartekracht naar voren",
            "zijn wielen hebben minder wrijving met de weg",
        ],
        antwoord=0,
        uitleg="Uit F is m maal a volgt dat a gelijk is aan F gedeeld door m. Bij een grotere massa wordt de versnelling bij dezelfde kracht dus kleiner.",
    ),
    dict(
        type="waarofniet",
        vraag="Verdubbel je de resulterende kracht op een voorwerp, dan verdubbelt de versnelling.",
        antwoord=True,
        uitleg="Kracht en versnelling zijn recht evenredig bij een vaste massa. Verdubbel je in de plaats daarvan de massa, dan halveert de versnelling.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe heet de derde wet van Newton ook?",
        antwoord=["actie-reactiewet", "actiereactiewet"],
        uitleg="Ze zegt dat twee lichamen even hard op elkaar duwen, in tegengestelde zin. Belangrijk daarbij is dat die twee krachten op verschillende lichamen werken.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke uitspraken over de actie-reactiewet zijn juist? Kruis alles aan wat juist is.",
        opties=[
            "de twee krachten zijn even groot",
            "de twee krachten hebben een tegengestelde zin",
            "de twee krachten werken op verschillende lichamen",
            "de twee krachten heffen elkaar op bij hetzelfde lichaam",
        ],
        antwoord=[0, 1, 2],
        uitleg="Juist omdat ze op twee verschillende lichamen werken, heffen ze elkaar niet op. Anders zou geen enkel voorwerp ooit versnellen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Je duwt tegen een muur. Welke kracht is de reactiekracht?",
        opties=[
            "de kracht waarmee de muur even hard tegen jou duwt",
            "de zwaartekracht die op jou werkt",
            "de wrijvingskracht van je schoenen op de vloer",
            "de normaalkracht van de vloer op jou",
        ],
        antwoord=0,
        uitleg="Actie en reactie vormen altijd een paar tussen dezelfde twee lichamen. De zwaartekracht en de normaalkracht zijn een ander paar krachten.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe heet de kracht waarmee een oppervlak loodrecht op een voorwerp duwt?",
        antwoord=["normaalkracht", "de normaalkracht"],
        uitleg="Op een vlakke tafel is ze even groot als de zwaartekracht, maar tegengesteld van zin. Op een helling staat ze loodrecht op de helling, niet recht naar boven.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke uitspraken over de wrijvingskracht zijn juist? Kruis alles aan wat juist is.",
        opties=[
            "ze wijst tegen de beweging in",
            "ze ontstaat tussen oppervlakken die over elkaar schuiven",
            "een auto moet ze overwinnen om zijn snelheid te houden",
            "ze staat altijd loodrecht op het oppervlak",
        ],
        antwoord=[0, 1, 2],
        uitleg="Loodrecht op het oppervlak staat de normaalkracht, niet de wrijvingskracht. Zonder wrijving zou een auto geen enkele kracht nodig hebben om door te rijden.",
    ),
    dict(
        type="waarofniet",
        vraag="Een boek dat stil op een tafel ligt, ondervindt geen enkele kracht.",
        antwoord=False,
        uitleg="Er werken wel krachten op: de zwaartekracht naar beneden en de normaalkracht naar boven. Ze zijn even groot, dus is de resulterende kracht nul.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke van deze vier zijn krachten? Kruis alles aan wat juist is.",
        opties=["de zwaartekracht", "de spankracht", "de veerkracht", "de magnetische flux"],
        antwoord=[0, 1, 2],
        uitleg="Er zijn er nog meer: de normaalkracht, de wrijvingskracht, de motorkracht, de stuwkracht en de gravitatiekracht. Flux is geen kracht maar hoort bij het magnetisch veld.",
    ),
    dict(
        type="meerkeuze",
        vraag="Hoe bepaal je de resulterende kracht op een lichaam?",
        opties=[
            "door alle krachtvectoren samen te tellen",
            "door de grootste kracht te kiezen",
            "door alle krachten van elkaar af te trekken",
            "door de krachten met de massa te vermenigvuldigen",
        ],
        antwoord=0,
        uitleg="Je telt vectoren op, dus met hun richting en zin erbij. Staan twee krachten tegenover elkaar, dan blijft het verschil over.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een kracht werkt schuin op een voorwerp. Wat doe je ermee in een oefening?",
        opties=[
            "je ontbindt ze in een x-component en een y-component",
            "je laat ze gewoon weg uit de berekening",
            "je verandert ze in een even grote verticale kracht",
            "je telt ze twee keer, een keer per richting",
        ],
        antwoord=0,
        uitleg="Zo kan je per richting apart optellen. Daarna bereken je in elke richting de versnelling met de tweede wet van Newton.",
    ),
    dict(
        type="waarofniet",
        vraag="Is de resulterende kracht op een lichaam nul, dan verandert zijn bewegingstoestand niet.",
        antwoord=True,
        uitleg="Dat is precies de eerste wet van Newton. Het lichaam blijft dus stilstaan of met dezelfde snelheid rechtdoor gaan.",
    ),
    dict(
        type="meerkeuze",
        vraag="Je kent de versnelling van een lichaam. Wat weet je dan over de resulterende kracht?",
        opties=[
            "ze wijst in dezelfde zin als de versnelling",
            "ze wijst tegen de versnelling in",
            "ze staat loodrecht op de versnelling",
            "ze is altijd gelijk aan nul",
        ],
        antwoord=0,
        uitleg="In F is m maal a zijn kracht en versnelling vectoren in dezelfde zin. De massa is een gewoon getal en verandert de richting dus niet.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een bus remt plots en de passagiers vallen naar voren. Welke wet verklaart dat?",
        opties=[
            "de eerste wet van Newton",
            "de tweede wet van Newton",
            "de derde wet van Newton",
            "de wet van Coulomb",
        ],
        antwoord=0,
        uitleg="Door hun traagheid willen de passagiers hun snelheid houden. De bus vertraagt wel, zij nog niet, dus bewegen zij ten opzichte van de bus naar voren.",
    ),
    dict(
        type="invultekst",
        vraag="Welke wet van Newton heb je nodig als je uit een kracht en een massa de versnelling wil berekenen?",
        antwoord=["de tweede", "tweede", "de tweede wet"],
        uitleg="Uit F is m maal a volgt a gelijk aan F gedeeld door m. De eerste wet gaat over het geval zonder resulterende kracht.",
    ),
    dict(
        type="waarofniet",
        vraag="Een raket komt vooruit omdat de uitgestoten gassen tegen de lucht achter de raket duwen.",
        antwoord=False,
        uitleg="De raket duwt de gassen naar achter en de gassen duwen even hard op de raket naar voor. Dat werkt ook in de ruimte, waar er geen lucht is.",
    ),
    dict(
        type="meerkeuze",
        vraag="Op een voorwerp van 4 kg werkt een resulterende kracht van 12 N. Hoe groot is de versnelling?",
        opties=[
            "3 meter per seconde kwadraat",
            "48 meter per seconde kwadraat",
            "16 meter per seconde kwadraat",
            "0,33 meter per seconde kwadraat",
        ],
        antwoord=0,
        uitleg="Je deelt de kracht door de massa, dus 12 gedeeld door 4. Vermenigvuldigen zou de kracht geven, niet de versnelling.",
    ),
]
