# -*- coding: utf-8 -*-
"""🌍 Beyond — Kunststoffen, nanomaterialen en duurzame chemie.

Chemie, de laatste drie koppen van het chemiedeel van de vakfiche
natuurwetenschappen 3DO samen in één thema. Deel 1 gaat over de kunststoffen,
hun reactietypes, hun monomeren en het verschil tussen thermoplast,
thermoharder en elastomeer, met de eerste vragen over nanomaterialen erbij.
Deel 2 gaat verder met de nanomaterialen en daarna over duurzame chemie, van
de Ladder van Lansink tot cradle to cradle en greenwashing.
"""

DEEL1 = [
    dict(
        type="invultekst",
        vraag="Hoe noem je de kleine molecule waaruit een kunststof opgebouwd wordt?",
        antwoord=["monomeer", "monomeren"],
        uitleg="Veel monomeren aan elkaar vormen een polymeer. Twee aan elkaar heet een dimeer.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welk reactietype gebruikt een dubbele binding om de monomeren aan elkaar te rijgen, zonder dat er iets vrijkomt?",
        opties=["polyadditie", "polycondensatie", "verbranding", "neutralisatie"],
        antwoord=0,
        uitleg="Bij polyadditie springt de dubbele binding open en haakt de molecule aan haar buur. Bij polycondensatie komt er telkens een kleine molecule vrij, meestal water.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat komt er bij een polycondensatie telkens vrij?",
        opties=[
            "een kleine molecule, meestal water",
            "een vrij elektron",
            "een stukje van de koolstofketen",
            "een halogeenatoom",
        ],
        antwoord=0,
        uitleg="Daarom heet het een condensatie: er valt iets af. PET en nylon worden op die manier gemaakt.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke kunststof is opgebouwd uit etheen?",
        opties=["PE", "PVC", "PS", "PET"],
        antwoord=0,
        uitleg="PE staat voor polyetheen, dus veel etheenmoleculen aan elkaar. PVC komt van chloroetheen en PS van styreen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke kunststoffen worden door polyadditie uit een monomeer met een dubbele binding gemaakt? Kruis alles aan wat juist is.",
        opties=["PE", "PP", "PVC", "PET"],
        antwoord=[0, 1, 2],
        uitleg="Polyetheen, polypropeen en polyvinylchloride komen van etheen, propeen en chloroetheen. PET wordt juist door polycondensatie gemaakt.",
    ),
    dict(
        type="invultekst",
        vraag="Welke kunststof zit in de antiaanbaklaag van een pan?",
        antwoord=["PTFE", "teflon"],
        uitleg="PTFE is polytetrafluoretheen, beter bekend als teflon. De fluoratomen maken het oppervlak heel glad en weinig reactief.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarvoor wordt PET vooral gebruikt?",
        opties=[
            "voor drankflessen en vezels voor kleding",
            "voor de buitenlaag van een elektriciteitskabel",
            "voor de isolatieplaten van een dak",
            "voor de koekjesverpakking als wit schuim",
        ],
        antwoord=0,
        uitleg="PET is sterk en doorzichtig, en je kan er ook polyestervezels van spinnen. Het witte schuim is PS en de isolatieplaten zijn meestal PUR.",
    ),
    dict(
        type="waarofniet",
        vraag="PA is de afkorting van polyester.",
        antwoord=False,
        uitleg="PA staat voor polyamide, beter bekend als nylon; polyester is PET. Nylon vind je in panty's, touwen, visdraad en tandwielen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is het kenmerk van een thermoplast?",
        opties=[
            "hij wordt bij opwarmen week en kan opnieuw gevormd worden",
            "hij verkoolt bij opwarmen zonder eerst week te worden",
            "hij springt na vervormen altijd in zijn oude vorm terug",
            "hij lost bij opwarmen op in water",
        ],
        antwoord=0,
        uitleg="De ketens liggen los naast elkaar en kunnen bij warmte over elkaar schuiven. Daardoor zijn thermoplasten de best recycleerbare kunststoffen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarom kan je een thermoharder niet opnieuw smelten?",
        opties=[
            "de ketens zitten met veel crosslinks aan elkaar vast",
            "de ketens zijn veel te kort om te bewegen",
            "de ketens bevatten te veel dubbele bindingen",
            "de ketens zijn met water aan elkaar gebonden",
        ],
        antwoord=0,
        uitleg="Die dwarsverbindingen maken van het hele voorwerp één groot netwerk. Daarom verkoolt een thermoharder bij warmte in de plaats van week te worden.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je de dwarsverbindingen tussen de ketens van een kunststof?",
        antwoord=["crosslinks", "crosslink"],
        uitleg="Veel crosslinks geven een thermoharder, enkele crosslinks een elastomeer. Zonder crosslinks krijg je een thermoplast.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is kenmerkend voor een elastomeer?",
        opties=[
            "hij vervormt onder een kracht en komt daarna terug",
            "hij smelt bij de kleinste opwarming helemaal weg",
            "hij blijft na een vervorming in zijn nieuwe vorm staan",
            "hij breekt al bij een kleine kracht in stukken",
        ],
        antwoord=0,
        uitleg="De weinige crosslinks houden de ketens samen maar laten ze toch uitrekken. Rubber van een elastiek of een autoband is daar het voorbeeld van.",
    ),
    dict(
        type="meerkeuze",
        vraag="Je hebt een soepele dichting nodig die na samenpersen terugkomt. Welk soort kunststof kies je?",
        opties=["een elastomeer", "een thermoharder", "een thermoplast", "een nanomateriaal"],
        antwoord=0,
        uitleg="Een elastomeer springt na de vervorming terug in vorm. Een thermoharder is stijf en een thermoplast blijft in de nieuwe vorm staan.",
    ),
    dict(
        type="waarofniet",
        vraag="Thermoplasten zijn makkelijker te recycleren dan thermoharders.",
        antwoord=True,
        uitleg="Je kan ze gewoon smelten en opnieuw vormgeven. Een thermoharder is één groot netwerk en kan je enkel vermalen of verbranden.",
    ),
    dict(
        type="meerkeuze",
        vraag="Hoe groot is een nanomateriaal ongeveer?",
        opties=[
            "tussen 1 en 100 nanometer",
            "tussen 1 en 100 micrometer",
            "tussen 1 en 100 millimeter",
            "tussen 1 en 100 picometer",
        ],
        antwoord=0,
        uitleg="Een nanometer is een miljardste van een meter. Een menselijke haar is daar ongeveer tienduizend keer dikker dan.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke uitspraken over de vorm van nanomaterialen zijn juist? Kruis alles aan wat juist is.",
        opties=[
            "een buckyball is een 0D-structuur",
            "een koolstofnanobuis is een 1D-structuur",
            "een laagje grafeen is een 2D-structuur",
            "een poeder van nanodeeltjes is een 1D-structuur",
        ],
        antwoord=[0, 1, 2],
        uitleg="Een bolletje is 0D, een buis is lang in één richting en dus 1D, een vlak is 2D. Een poeder dat een ruimte vult, reken je bij 3D.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je het nanomateriaal dat uit één laag koolstofatomen bestaat?",
        antwoord="grafeen",
        uitleg="Die ene laag is maar één atoom dik en toch heel sterk. Grafeen geleidt ook uitstekend elektriciteit en warmte.",
    ),
    dict(
        type="waarofniet",
        vraag="Bij een bottom-upproductie bouw je een nanomateriaal op uit atomen of moleculen.",
        antwoord=True,
        uitleg="Bij top-down ga je de andere kant op: je vertrekt van een groot stuk en maakt het kleiner, bijvoorbeeld door vermalen of etsen.",
    ),
    dict(
        type="waarofniet",
        vraag="Nanodeeltjes hebben een kleinere verhouding van oppervlak tot volume dan grote stukken van dezelfde stof.",
        antwoord=False,
        uitleg="Het is net omgekeerd: hoe kleiner het deeltje, hoe groter die verhouding. Juist daardoor zijn nanodeeltjes zo reactief.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke uitspraken over nanodeeltjes zijn juist? Kruis alles aan wat juist is.",
        opties=[
            "ze hebben een heel groot oppervlak per volume-eenheid",
            "ze zijn daardoor vaak veel reactiever",
            "hun smeltpunt kan lager liggen dan dat van een groot stuk",
            "ze hebben altijd dezelfde kleur als het grote stuk",
        ],
        antwoord=[0, 1, 2],
        uitleg="Die eerste drie zijn typische nano-eigenschappen. De kleur verandert juist vaak met de grootte van het deeltje.",
    ),
]

DEEL2 = [
    dict(
        type="meerkeuze",
        vraag="Waarom zit er nanotitaandioxide of nanozinkoxide in zonnecrème?",
        opties=[
            "het houdt UV-licht tegen en blijft toch doorzichtig",
            "het maakt de crème geurig en aangenaam zacht",
            "het laat de huid veel sneller bruin worden",
            "het doodt alle bacteriën op de huid af",
        ],
        antwoord=0,
        uitleg="In grote deeltjes zou dezelfde stof een witte laag geven. Zo klein verstrooit ze het zichtbare licht nauwelijks nog.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welk nanodeeltje wordt gebruikt voor zijn antibacteriële werking?",
        opties=["zilver", "goud", "koolstof", "titaan"],
        antwoord=0,
        uitleg="Zilvernanodeeltjes zitten onder meer in sportkleding en in wondverband. Goudnanodeeltjes gebruik je eerder voor de kleurstreep in een sneltest.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke eigenschappen van een nanomateriaal kunnen anders zijn dan die van het grote stuk? Kruis alles aan wat juist is.",
        opties=[
            "optische eigenschappen zoals een specifieke kleur",
            "elektrische eigenschappen",
            "mechanische eigenschappen zoals sterkte en hardheid",
            "de smaak van het materiaal",
        ],
        antwoord=[0, 1, 2],
        uitleg="Daarnaast staan er ook magnetische en biochemische eigenschappen bij. Smaak hoort er niet bij.",
    ),
    dict(
        type="waarofniet",
        vraag="Een nadeel van nanodeeltjes is dat ze diep in een lichaam of in het milieu kunnen terechtkomen.",
        antwoord=True,
        uitleg="Juist hun kleine afmeting laat hen door barrières glippen. Daarom is er veel onderzoek naar hun veiligheid op lange termijn.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je de economie die grondstoffen neemt, er iets van maakt en het daarna weggooit?",
        antwoord=["lineaire economie", "lineair"],
        uitleg="In het Engels heet dat take make waste, en in het Nederlands ook cradle to grave. Het tegendeel is de circulaire of keteneconomie.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is downcycling?",
        opties=[
            "afval verwerken tot iets van lagere kwaliteit",
            "afval verwerken tot iets van hogere waarde",
            "afval verbranden om energie te winnen",
            "afval ongewijzigd opnieuw gebruiken",
        ],
        antwoord=0,
        uitleg="Van een plastic fles bijvoorbeeld een vulmateriaal maken dat je niet meer tot fles kan verwerken. Bij upcycling krijgt het materiaal juist meer waarde.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je recyclage waarbij het nieuwe product méér waard is dan het oude?",
        antwoord=["upcycling", "upcyclen"],
        uitleg="Het tegendeel is downcycling, waarbij de kwaliteit zakt. Hergebruiken zonder iets te veranderen staat nog hoger op de ladder.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat staat er bovenaan de Ladder van Lansink?",
        opties=[
            "preventie, dus het afval vermijden",
            "recyclage van het materiaal",
            "verbranden met energieterugwinning",
            "storten op een stortplaats",
        ],
        antwoord=0,
        uitleg="Niets maken wat afval wordt, is de beste optie. Storten staat helemaal onderaan, als allerlaatste keuze.",
    ),
    dict(
        type="waarofniet",
        vraag="Op de Ladder van Lansink staat hergebruiken hoger dan recycleren.",
        antwoord=True,
        uitleg="Bij hergebruiken blijft het voorwerp zoals het is, dus kost het bijna geen energie. Recycleren vraagt eerst een hele verwerking.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is het kernidee van cradle to cradle?",
        opties=[
            "afval van het ene product is grondstof voor het volgende",
            "producten moeten zo lang mogelijk meegaan en dan gestort worden",
            "elk product moet verbrand worden om energie op te wekken",
            "producten moeten uit zo weinig verschillende stoffen bestaan",
        ],
        antwoord=0,
        uitleg="Van wieg tot wieg in plaats van van wieg tot graf. Je ontwerpt een product dus van het begin af aan zo dat het volledig opnieuw bruikbaar is.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke categorieën horen bij cradle to cradle? Kruis alles aan wat juist is.",
        opties=[
            "materiaalgezondheid",
            "productcirculariteit",
            "sociale rechtvaardigheid",
            "het reclamebudget van het bedrijf",
        ],
        antwoord=[0, 1, 2],
        uitleg="De vijf categorieën zijn materiaalgezondheid, productcirculariteit, luchtkwaliteit en klimaatbescherming, water- en grondgezondheid en sociale rechtvaardigheid.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat betekent biogebaseerd?",
        opties=[
            "gemaakt uit plantaardige of dierlijke grondstoffen",
            "door bacteriën en schimmels volledig af te breken",
            "geschikt om in een composthoop te verdwijnen",
            "gemaakt zonder ook maar enige uitstoot van CO2",
        ],
        antwoord=0,
        uitleg="Biogebaseerd zegt dus enkel iets over de grondstof, niet over het einde. Een biogebaseerde kunststof kan perfect even moeilijk afbreekbaar zijn als een gewone.",
    ),
    dict(
        type="waarofniet",
        vraag="Een biogebaseerde kunststof is altijd ook biodegradeerbaar.",
        antwoord=False,
        uitleg="Het zijn twee verschillende dingen: biogebaseerd gaat over waar de grondstof vandaan komt, biodegradeerbaar over of organismen de stof kunnen afbreken.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je een materiaal dat onder composteeromstandigheden volledig afbreekt?",
        antwoord=["composteerbaar", "composteerbare"],
        uitleg="Er horen voorwaarden bij, zoals een bepaalde temperatuur en een bepaalde tijd. Biodegradeerbaar is ruimer: dat zegt niet in welke omstandigheden.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarin verschilt groene waterstof van grijze waterstof?",
        opties=[
            "groene waterstof wordt met hernieuwbare stroom gemaakt",
            "groene waterstof bestaat uit heel andere atomen",
            "groene waterstof wordt rechtstreeks uit aardgas gemaakt",
            "groene waterstof brandt met een groengekleurde vlam",
        ],
        antwoord=0,
        uitleg="Het gas zelf is altijd hetzelfde; de kleur zegt hoe het gemaakt is. Grijs komt uit aardgas, blauw ook maar met afvang van de CO2.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is grijs water?",
        opties=[
            "licht vervuild water van bad, lavabo of wasmachine",
            "zuiver water dat je zonder risico kan drinken",
            "water dat rechtstreeks uit het toilet komt",
            "water met nanodeeltjes in opgelost",
        ],
        antwoord=0,
        uitleg="Wit water is drinkbaar water en zwart water komt uit het toilet. Grijs water kan je vaak nog gebruiken om door te spoelen of te kuisen.",
    ),
    dict(
        type="waarofniet",
        vraag="Een CO2-neutraal proces neemt meer CO2 op dan het uitstoot.",
        antwoord=False,
        uitleg="Neutraal betekent dat opname en uitstoot elkaar in evenwicht houden. Méér opnemen dan uitstoten heet CO2-negatief.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is greenwashing?",
        opties=[
            "een product duurzamer voorstellen dan het is",
            "een product met groene stroom produceren",
            "een product wassen voor het verpakt wordt",
            "een product uit gerecycleerde grondstof maken",
        ],
        antwoord=0,
        uitleg="Een groen blaadje op de verpakking zegt op zich niets. Daarom kijk je naar wat er precies beweerd wordt en of er bewijs bij staat.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarom zijn microplastics een probleem?",
        opties=[
            "ze blijven heel lang in het milieu en komen in de voedselketen",
            "ze lossen onmiddellijk op in het zeewater rond hen",
            "ze geven bij hun afbraak zuurstof vrij in het water",
            "ze zijn te groot om door dieren opgenomen te worden",
        ],
        antwoord=0,
        uitleg="Ze zijn zo klein dat ze overal terechtkomen, van plankton tot op ons bord. En plastic breekt in het milieu heel traag af.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke energievormen bekijk je als je de duurzaamheid van een proces beoordeelt? Kruis alles aan wat juist is.",
        opties=[
            "fossiele energie",
            "kernenergie",
            "hernieuwbare energie",
            "chemische reactie-energie",
        ],
        antwoord=[0, 1, 2],
        uitleg="Die drie gebruik je om te beoordelen hoe duurzaam een proces is. Reactie-energie hoort bij het energiediagram van een reactie, niet bij deze indeling.",
    ),
]
