# -*- coding: utf-8 -*-
"""🌍 Beyond — Organische stoffen.

Chemie, de kop "Organische stoffen" uit de vakfiche natuurwetenschappen 3DO,
met haar drie onderdelen classificatie, eigenschappen en toepassingen.
Deel 1 gaat over de stofklassen en hoe je ze aan een formule herkent.
Deel 2 gaat over de intermoleculaire krachten die het kookpunt en het
oplosgedrag bepalen, en over de concrete stoffen die de fiche opnoemt.
"""

DEEL1 = [
    dict(
        type="meerkeuze",
        vraag="Waaraan herken je een alkaan?",
        opties=[
            "het bevat enkel koolstof en waterstof, met enkelvoudige bindingen",
            "het bevat een dubbele binding tussen twee koolstofatomen",
            "het bevat een OH-groep aan een koolstofatoom",
            "het bevat een COOH-groep aan het einde van de keten",
        ],
        antwoord=0,
        uitleg="Alkanen zijn verzadigd: alle bindingen tussen de koolstofatomen zijn enkelvoudig. Een dubbele binding maakt er een alkeen van.",
    ),
    dict(
        type="invultekst",
        vraag="Tot welke stofklasse hoort een molecule met een dubbele binding tussen twee koolstofatomen?",
        antwoord=["alkenen", "alkeen"],
        uitleg="De uitgang -een verraadt de dubbele binding, zoals bij etheen. Bij enkel enkelvoudige bindingen heet het een alkaan, met de uitgang -aan.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke stofklasse heeft een OH-groep aan een koolstofketen?",
        opties=["de alcoholen", "de ethers", "de aldehyden", "de aminen"],
        antwoord=0,
        uitleg="Een alcohol eindigt op -ol, zoals ethanol. Bij een ether zit het zuurstofatoom tússen twee koolstofketens.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke stofklassen bevatten een zuurstofatoom in hun kenmerkende groep? Kruis alles aan wat juist is.",
        opties=["de alcoholen", "de carbonzuren", "de esters", "de aminen"],
        antwoord=[0, 1, 2],
        uitleg="Alcoholen hebben een OH, carbonzuren een COOH en esters een COO tussen twee ketens. Aminen hebben in de plaats daarvan een stikstofatoom.",
    ),
    dict(
        type="waarofniet",
        vraag="Een amine heeft net als een alcohol een OH-groep als kenmerkende groep.",
        antwoord=False,
        uitleg="De kenmerkende groep van een amine draait om stikstof, dus NH2, NH of N aan een koolstofketen. De OH-groep hoort bij de alcoholen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is het verschil tussen een aldehyde en een keton?",
        opties=[
            "bij een aldehyde staat de carbonylgroep aan het uiteinde van de keten",
            "bij een aldehyde zit er geen zuurstof in de molecule",
            "bij een keton staat de carbonylgroep aan het uiteinde van de keten",
            "bij een keton is er geen koolstofketen aanwezig",
        ],
        antwoord=0,
        uitleg="Allebei hebben ze een C met een dubbele binding naar O. Zit die groep binnenin de keten, dan is het een keton, zoals propanon.",
    ),
    dict(
        type="invultekst",
        vraag="Tot welke stofklasse hoort een stof met een COOH-groep?",
        antwoord=["carbonzuren", "carbonzuur"],
        uitleg="Azijnzuur en mierenzuur zijn de bekendste voorbeelden. Reageert een carbonzuur met een alcohol, dan krijg je een ester.",
    ),
    dict(
        type="meerkeuze",
        vraag="Tot welke stofklasse hoort CH3CH2OH?",
        opties=["de alcoholen", "de ethers", "de carbonzuren", "de alkanen"],
        antwoord=0,
        uitleg="De OH-groep hangt aan het einde van een keten van twee koolstofatomen. Deze stof is ethanol, de alcohol in drank.",
    ),
    dict(
        type="meerkeuze",
        vraag="Tot welke stofklasse hoort CH3COCH3?",
        opties=["de ketonen", "de aldehyden", "de esters", "de ethers"],
        antwoord=0,
        uitleg="De CO-groep zit tussen twee koolstofatomen, dus binnenin de keten. Deze stof is propanon, beter bekend als aceton.",
    ),
    dict(
        type="waarofniet",
        vraag="CHCl3 hoort bij de alcoholen.",
        antwoord=False,
        uitleg="Er zit geen OH-groep in, wel drie chlooratomen. Het is methaan met drie halogenen in de plaats van waterstof, dus een halogeenalkaan: chloroform.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is een skeletnotatie van een organische molecule?",
        opties=[
            "een tekening met lijnen, waarbij elke hoek een koolstofatoom is",
            "een tekening waarin elk atoom met zijn symbool staat",
            "een formule waarin alleen het aantal atomen staat",
            "een tekening van de molecule in drie dimensies",
        ],
        antwoord=0,
        uitleg="De koolstof- en waterstofatomen worden niet geschreven, enkel de lijnen tussen de atomen. Daardoor zie je de vorm van de keten meteen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is het verschil tussen een uitgebreide en een beknopte structuurformule?",
        opties=[
            "in de uitgebreide staat elke binding getekend, in de beknopte niet",
            "in de uitgebreide staan alleen de koolstofatomen",
            "in de beknopte staat de molecule in drie dimensies",
            "in de beknopte staan er meer atomen dan in de uitgebreide",
        ],
        antwoord=0,
        uitleg="De uitgebreide formule tekent elke streepje tussen twee atomen. De beknopte bundelt dat tot groepen, zoals CH3 en CH2.",
    ),
    dict(
        type="waarofniet",
        vraag="Twee stoffen met dezelfde brutoformule kunnen tot een andere stofklasse horen.",
        antwoord=True,
        uitleg="C2H6O kan ethanol zijn, een alcohol, of dimethylether, een ether. Daarom zegt een brutoformule alleen niet genoeg.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke formules horen bij een alkaan? Kruis alles aan wat juist is.",
        opties=["CH4", "C3H8", "C4H10", "CH2=CH2"],
        antwoord=[0, 1, 2],
        uitleg="Methaan, propaan en butaan zijn alkanen. CH2=CH2 is etheen, en de dubbele binding maakt dat een alkeen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Tot welke stofklasse hoort een stof met de groep COO tussen twee koolstofketens?",
        opties=["de esters", "de ethers", "de aldehyden", "de amiden"],
        antwoord=0,
        uitleg="Een ester ontstaat uit een carbonzuur en een alcohol. Esters geven veel vruchten en bloemen hun geur.",
    ),
    dict(
        type="invultekst",
        vraag="Tot welke stofklasse hoort een stof met een zuurstofatoom tussen twee koolstofketens?",
        antwoord=["ethers", "ether"],
        uitleg="Bij een ether zit de zuurstof midden in de molecule, zonder waterstof eraan. Hangt er wel een waterstof aan, dan heb je een alcohol.",
    ),
    dict(
        type="waarofniet",
        vraag="Een amide bevat zowel stikstof als zuurstof.",
        antwoord=True,
        uitleg="De amidegroep is een carbonylgroep met een stikstof ernaast. Zo zitten de bouwstenen van proteïnen aan elkaar.",
    ),
    dict(
        type="meerkeuze",
        vraag="Je krijgt de naam propaanzuur. Tot welke stofklasse hoort die stof?",
        opties=["de carbonzuren", "de alcoholen", "de ketonen", "de alkenen"],
        antwoord=0,
        uitleg="De uitgang -zuur wijst op een COOH-groep. Propaan geeft de keten van drie koolstofatomen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke uitgangen horen bij welke stofklasse? Kruis alles aan wat juist is.",
        opties=[
            "de uitgang -aan hoort bij de alkanen",
            "de uitgang -een hoort bij de alkenen",
            "de uitgang -ol hoort bij de alcoholen",
            "de uitgang -on hoort bij de aldehyden",
        ],
        antwoord=[0, 1, 2],
        uitleg="De eerste drie kloppen. De uitgang -on hoort bij de ketonen, zoals propanon; aldehyden eindigen op -al, zoals methanal.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarom noemen we alkanen verzadigde koolwaterstoffen?",
        opties=[
            "omdat er geen waterstofatomen meer bij kunnen",
            "omdat ze goed oplossen in water",
            "omdat ze altijd een OH-groep bevatten",
            "omdat ze bij kamertemperatuur vast zijn",
        ],
        antwoord=0,
        uitleg="Elk koolstofatoom heeft al zijn vier bindingen bezet. Een alkeen is onverzadigd, want aan de dubbele binding kan er nog waterstof bij.",
    ),
]

DEEL2 = [
    dict(
        type="meerkeuze",
        vraag="Welke intermoleculaire kracht werkt tussen alle moleculen, ook de apolaire?",
        opties=[
            "de londondispersiekracht",
            "de dipoolkracht",
            "de waterstofbrug",
            "de ionbinding",
        ],
        antwoord=0,
        uitleg="Die kracht komt van tijdelijke ladingsverschuivingen en bestaat dus altijd. Ze wordt sterker bij een grotere molecule.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe heet de sterkste intermoleculaire kracht, die ontstaat als waterstof aan zuurstof of stikstof hangt?",
        antwoord=["waterstofbrug", "waterstofbrugbinding"],
        uitleg="Water, alcoholen en carbonzuren vormen waterstofbruggen. Daarom hebben die stoffen een veel hoger kookpunt dan je aan hun massa zou denken.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarom stijgt het kookpunt van de alkanen als de keten langer wordt?",
        opties=[
            "de londondispersiekracht tussen de moleculen wordt sterker",
            "er ontstaan waterstofbruggen tussen de moleculen",
            "de moleculen worden polair door de lengte",
            "de moleculen gaan elkaar afstoten",
        ],
        antwoord=0,
        uitleg="Een langere molecule heeft meer contactoppervlak en een grotere molaire massa. Daardoor moet je meer energie geven om de moleculen los te krijgen.",
    ),
    dict(
        type="waarofniet",
        vraag="Een sterk vertakt alkaan heeft een hoger kookpunt dan een rechte keten met dezelfde formule.",
        antwoord=False,
        uitleg="Het is net omgekeerd. Een bolletje raakt zijn buren op minder plaatsen dan een uitgestrekte keten, en minder contact betekent een zwakkere dispersiekracht.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarom heeft ethanol een veel hoger kookpunt dan ethaan?",
        opties=[
            "ethanol vormt waterstofbruggen en ethaan niet",
            "ethanol is veel zwaarder dan ethaan",
            "ethaan is sterker vertakt dan ethanol",
            "ethaan bestaat uit grotere moleculen dan ethanol",
        ],
        antwoord=0,
        uitleg="De OH-groep van ethanol kan een waterstofbrug met een buurmolecule leggen. Die extra kracht moet je eerst verbreken voor het kan koken.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke stoffen zijn apolair? Kruis alles aan wat juist is.",
        opties=["wasbenzine", "CCl4", "een lang alkaan", "water"],
        antwoord=[0, 1, 2],
        uitleg="Die drie zijn de bekendste apolaire stoffen. Water is juist het schoolvoorbeeld van een polaire stof.",
    ),
    dict(
        type="waarofniet",
        vraag="Een apolaire stof lost goed op in water.",
        antwoord=False,
        uitleg="Gelijk lost op in gelijk: polair bij polair, apolair bij apolair. Daarom blijft olie als een laag op water liggen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarom mengt methanol wel met water en een lang alkaan niet?",
        opties=[
            "methanol kan waterstofbruggen met water leggen",
            "methanol is zwaarder dan water",
            "een lang alkaan is polairder dan methanol",
            "een lang alkaan heeft een OH-groep te veel",
        ],
        antwoord=0,
        uitleg="De OH-groep past bij de watermoleculen. Een alkaan heeft enkel koolstof en waterstof, dus niets om zich aan het water vast te hechten.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarom lost een alcohol met een heel lange keten bijna niet meer op in water?",
        opties=[
            "de lange apolaire staart weegt zwaarder door dan de OH-groep",
            "de OH-groep verdwijnt bij een lange keten",
            "de stof wordt door de lengte een alkaan",
            "lange moleculen kunnen geen dispersiekracht vormen",
        ],
        antwoord=0,
        uitleg="Hoe langer de staart, hoe meer de molecule op een alkaan lijkt. De ene OH-groep kan die hele apolaire keten niet meer meesleuren in het water.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je het bolletje dat zeepmoleculen rond een vetdruppel vormen?",
        antwoord=["micel", "micelle"],
        uitleg="De apolaire staarten steken in het vet en de polaire koppen naar het water. Daardoor kan de vetdruppel met het water meegespoeld worden.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke uitspraken over een zeepmolecule zijn juist? Kruis alles aan wat juist is.",
        opties=[
            "ze heeft een lange apolaire staart",
            "ze heeft een polaire kop",
            "ze kan vet en water met elkaar verbinden",
            "ze is over haar hele lengte polair",
        ],
        antwoord=[0, 1, 2],
        uitleg="Juist die twee kanten maken zeep bruikbaar. Was ze over haar hele lengte polair, dan zou ze niet in het vet kunnen gaan zitten.",
    ),
    dict(
        type="waarofniet",
        vraag="Een fosfolipide heeft net als zeep een polaire kop en apolaire staarten.",
        antwoord=True,
        uitleg="Een fosfolipide heeft er twee staarten in plaats van één. Daardoor vormt ze geen bolletje maar een dubbellaag, zoals in een celmembraan.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke stof is de hoofdbestanddeel van aardgas?",
        opties=["methaan", "propaan", "ethanol", "etheen"],
        antwoord=0,
        uitleg="Aardgas is vooral methaan, met de formule CH4. Propaan en butaan zijn de gassen in een gasfles of een aansteker.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke stof is azijnzuur?",
        opties=["CH3COOH", "HCOOH", "CH3OH", "HCHO"],
        antwoord=0,
        uitleg="Azijnzuur heet wetenschappelijk ethaanzuur. HCOOH is methaanzuur of mierenzuur, met één koolstofatoom minder.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe heet HCOOH met zijn gebruiksnaam?",
        antwoord=["mierenzuur", "mierezuur"],
        uitleg="Wetenschappelijk heet het methaanzuur. Het is het zuur dat mieren en brandnetels gebruiken om zich te verdedigen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke stof is brandspiritus?",
        opties=["methanol", "ethanol", "propanon", "methanal"],
        antwoord=0,
        uitleg="Methanol is CH3OH, met één koolstofatoom. Ethanol is de alcohol in drank; methanol is giftig en mag je niet drinken.",
    ),
    dict(
        type="waarofniet",
        vraag="Propanon is de wetenschappelijke naam van aceton.",
        antwoord=True,
        uitleg="Het is een keton met de formule CH3COCH3. Je vindt het onder meer in nagellakverwijderaar, want het lost veel stoffen goed op.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke stof is formol, dat gebruikt wordt om biologisch materiaal te bewaren?",
        opties=["methanal", "methanol", "methaanzuur", "methaan"],
        antwoord=0,
        uitleg="Methanal is een aldehyde met de formule HCHO. De namen lijken sterk op elkaar, dus kijk altijd naar de uitgang.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke uitspraken over etheen zijn juist? Kruis alles aan wat juist is.",
        opties=[
            "het is een alkeen",
            "het heeft een dubbele binding",
            "het is de bouwsteen van polyetheen",
            "het is een alcohol",
        ],
        antwoord=[0, 1, 2],
        uitleg="De dubbele binding maakt het een alkeen en laat toe de moleculen aan elkaar te rijgen tot polyetheen. Een alcohol is het niet, want er zit geen OH-groep in.",
    ),
    dict(
        type="meerkeuze",
        vraag="Je moet een vlek van een apolaire stof oplossen. Welk oplosmiddel kies je?",
        opties=["wasbenzine", "water", "een zoutoplossing", "azijn"],
        antwoord=0,
        uitleg="Wasbenzine is apolair, en gelijk lost op in gelijk. Water, zout water en azijn zijn alle drie polair en laten de vlek staan.",
    ),
]
