# -*- coding: utf-8 -*-
"""🌍 Beyond — Snelheid van een chemische reactie.

Chemie, de kop "Snelheid van een chemische reactie" uit de vakfiche
natuurwetenschappen 3DO. Deel 1 gaat over wat reactiesnelheid is, hoe je ze
aan een grafiek afleest en over het botsingsmodel met de vier factoren.
Deel 2 gaat over het energiediagram, exo- en endo-energetische reacties,
de Boltzmannverdeling en de katalysatoren, biokatalysatoren erbij.
"""

DEEL1 = [
    dict(
        type="meerkeuze",
        vraag="Hoe druk je de snelheid van een chemische reactie uit?",
        opties=[
            "als de verandering van een concentratie per tijdseenheid",
            "als de massa van het product dat ontstaan is",
            "als het verschil in temperatuur tussen begin en einde",
            "als het volume van het vat waarin de reactie gebeurt",
        ],
        antwoord=0,
        uitleg="Je kijkt hoeveel de concentratie van een reagens daalt of van een reactieproduct stijgt in een bepaalde tijd. Een massa of een volume alleen zegt niets over snelheid, want daar zit geen tijd in.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke manieren om de reactiesnelheid uit te drukken zijn juist? Kruis alles aan wat juist is.",
        opties=[
            "de afname van de concentratie van een reagens per seconde",
            "de toename van de concentratie van een product per seconde",
            "het aantal effectieve botsingen per seconde",
            "het aantal deeltjes dat in het vat aanwezig is",
        ],
        antwoord=[0, 1, 2],
        uitleg="De eerste twee zijn de gewone manier, de derde is het botsingsmodel. Het aantal deeltjes alleen is geen snelheid, want er staat geen tijd bij.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je een botsing die wél tot een reactie leidt?",
        antwoord="effectieve botsing",
        uitleg="De deeltjes moeten dan genoeg energie hebben en ook juist tegen elkaar botsen. Botsen ze zonder gevolg, dan heet dat een elastische of niet-effectieve botsing.",
    ),
    dict(
        type="waarofniet",
        vraag="Bij een elastische botsing ontstaat er een nieuwe stof.",
        antwoord=False,
        uitleg="Bij een elastische botsing stuiteren de deeltjes van elkaar weg zonder dat er iets verandert. Enkel een effectieve botsing levert nieuwe stoffen op.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is er nodig voor een effectieve botsing? Kruis alles aan wat juist is.",
        opties=[
            "de deeltjes hebben genoeg energie",
            "de deeltjes botsen met de juiste kant tegen elkaar",
            "de deeltjes botsen bij een lage temperatuur",
            "de deeltjes hebben allebei dezelfde massa",
        ],
        antwoord=[0, 1],
        uitleg="Zonder genoeg energie raken de deeltjes niet over de activeringsenergie, en met de verkeerde kant tegen elkaar gebeurt er ook niets. Een lage temperatuur maakt het juist minder waarschijnlijk.",
    ),
    dict(
        type="meerkeuze",
        vraag="Je leest een concentratie-tijdgrafiek van een reagens. Wat betekent een steile daling?",
        opties=[
            "de reactie gaat op dat moment snel",
            "de reactie gaat op dat moment traag",
            "de reactie is op dat moment gestopt",
            "er komt op dat moment reagens bij",
        ],
        antwoord=0,
        uitleg="Hoe steiler de lijn, hoe meer de concentratie per tijdseenheid verandert, dus hoe sneller de reactie. Een vlakke lijn betekent dat er niets meer verandert.",
    ),
    dict(
        type="waarofniet",
        vraag="De meeste reacties beginnen snel en worden daarna trager.",
        antwoord=True,
        uitleg="In het begin zijn er het meeste reagensdeeltjes, dus het meeste botsingen. Hoe meer reagens opgebruikt is, hoe minder botsingen en hoe trager de reactie.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke factoren uit de vier bekende versnellen een reactie als je ze verhoogt? Kruis alles aan wat juist is.",
        opties=[
            "de temperatuur",
            "de concentratie van de reagentia",
            "de verdelingsgraad van een vaste stof",
            "de massa van het reactievat",
        ],
        antwoord=[0, 1, 2],
        uitleg="Temperatuur, concentratie en verdelingsgraad zijn drie van de vier factoren; de vierde is de katalysator. Het vat zelf doet niet mee aan de reactie.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarom brandt zaagmeel sneller dan een dik blok van hetzelfde hout?",
        opties=[
            "omdat er veel meer contactoppervlak met de lucht is",
            "omdat zaagmeel uit een andere stof bestaat dan hout",
            "omdat zaagmeel bij een lagere temperatuur begint te branden",
            "omdat er in zaagmeel meer zuurstof opgeslagen zit",
        ],
        antwoord=0,
        uitleg="Dat is de verdelingsgraad. Hoe fijner je een vaste stof verdeelt, hoe meer deeltjes aan de buitenkant liggen en dus kunnen botsen met de zuurstof.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je de mate waarin een vaste stof fijn verdeeld is?",
        antwoord="verdelingsgraad",
        uitleg="Poeder heeft een hoge verdelingsgraad, één groot stuk een lage. Bij een hoge verdelingsgraad is het contactoppervlak veel groter.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarom gaat een reactie sneller bij een hogere temperatuur?",
        opties=[
            "de deeltjes bewegen sneller, dus botsen vaker en harder",
            "er komen door de warmte nieuwe deeltjes bij",
            "de activeringsenergie van de reactie daalt",
            "de deeltjes worden door de warmte kleiner",
        ],
        antwoord=0,
        uitleg="Twee dingen tellen samen: er zijn meer botsingen per seconde en een groter deel daarvan heeft genoeg energie. De activeringsenergie zelf blijft gelijk.",
    ),
    dict(
        type="waarofniet",
        vraag="Een hogere concentratie zorgt voor meer botsingen per seconde.",
        antwoord=True,
        uitleg="Zitten er meer deeltjes in hetzelfde volume, dan komen ze elkaar vaker tegen. Meer botsingen betekent ook meer effectieve botsingen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Je laat eenzelfde hoeveelheid kalk reageren met zuur, één keer als brokjes en één keer als poeder. Wat zie je?",
        opties=[
            "het poeder reageert sneller, maar geeft evenveel gas",
            "het poeder reageert sneller en geeft ook meer gas",
            "de brokjes reageren sneller omdat ze zwaarder zijn",
            "er is geen verschil, want het is dezelfde stof",
        ],
        antwoord=0,
        uitleg="De verdelingsgraad verandert alleen de snelheid, niet hoeveel er uiteindelijk reageert. Evenveel kalk geeft evenveel gas, enkel vlugger.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke rol speelt licht bij sommige reacties?",
        opties=[
            "het levert de energie om de reactie te doen starten",
            "het verlaagt altijd de temperatuur van het mengsel",
            "het zorgt dat er minder botsingen gebeuren",
            "het maakt van de reagentia een katalysator",
        ],
        antwoord=0,
        uitleg="Bij lichtgevoelige reacties neemt een deeltje energie uit het licht op. Daarom bewaar je waterstofperoxide in een bruine fles.",
    ),
    dict(
        type="waarofniet",
        vraag="Een reactie waarvan de concentratie-tijdgrafiek vlak loopt, is afgelopen of in evenwicht.",
        antwoord=True,
        uitleg="Een vlakke lijn betekent dat de concentraties niet meer veranderen. Dat kan zijn omdat alles opgebruikt is of omdat het evenwicht bereikt is.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat lees je van een snelheid-tijdgrafiek af dat je van een concentratie-tijdgrafiek niet rechtstreeks afleest?",
        opties=[
            "hoe snel de reactie op elk moment verloopt",
            "hoeveel reagens er in het begin aanwezig was",
            "welke stoffen er in het mengsel zitten",
            "bij welke temperatuur de proef gebeurde",
        ],
        antwoord=0,
        uitleg="Op een snelheid-tijdgrafiek staat de snelheid zelf op de verticale as. Op een concentratie-tijdgrafiek moet je daarvoor eerst naar de steilheid van de lijn kijken.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je een botsing waarbij de deeltjes gewoon van elkaar wegstuiteren?",
        antwoord=["elastische botsing", "niet-effectieve botsing"],
        uitleg="Zo'n botsing verandert niets aan de stoffen. Alleen botsingen met genoeg energie en de juiste stand leveren een reactie op.",
    ),
    dict(
        type="meerkeuze",
        vraag="Twee proeven verlopen met dezelfde stoffen, maar de ene gaat sneller. Welke uitleg kan dat niet verklaren?",
        opties=[
            "de reactievergelijking is in de ene proef anders",
            "de ene proef gebeurde bij een hogere temperatuur",
            "in de ene proef was de concentratie hoger",
            "in de ene proef zat er een katalysator bij",
        ],
        antwoord=0,
        uitleg="Dezelfde stoffen geven dezelfde reactievergelijking. De drie andere zijn echte factoren die de snelheid beïnvloeden.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat gebeurt er met de snelheid als je een gasmengsel in een kleiner vat perst?",
        opties=[
            "ze stijgt, want de concentratie wordt groter",
            "ze daalt, want er is minder plaats om te botsen",
            "ze blijft gelijk, want het aantal deeltjes verandert niet",
            "ze stopt, want de deeltjes kunnen niet meer bewegen",
        ],
        antwoord=0,
        uitleg="Evenveel deeltjes in een kleiner volume betekent een hogere concentratie, dus meer botsingen per seconde. Daarom versnelt de reactie.",
    ),
    dict(
        type="waarofniet",
        vraag="Je kan de snelheid van een reactie altijd zien aan hoeveel product er uiteindelijk ontstaat.",
        antwoord=False,
        uitleg="Hoeveel product er komt, hangt af van hoeveel reagens er was. Een trage en een snelle reactie kunnen op het einde precies hetzelfde opleveren.",
    ),
]

DEEL2 = [
    dict(
        type="meerkeuze",
        vraag="Wat is de activeringsenergie van een reactie?",
        opties=[
            "de energie die de deeltjes nodig hebben om te kunnen reageren",
            "de energie die bij de reactie in totaal vrijkomt of opgenomen wordt",
            "de energie van de reactieproducten op het einde van de reactie",
            "de energie die het reactievat aan de omgeving rond zich geeft",
        ],
        antwoord=0,
        uitleg="Op het energiediagram is dat de hoogte van de berg die je over moet. Hoe hoger die berg, hoe minder botsingen genoeg energie hebben.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe heet de onstabiele toestand bovenaan de berg in een energiediagram?",
        antwoord=["geactiveerd complex", "geactiveerde complex"],
        uitleg="Daar zijn de oude bindingen half los en de nieuwe half gelegd. Het geactiveerd complex heeft de hoogste inwendige energie van het hele verloop.",
    ),
    dict(
        type="meerkeuze",
        vraag="Hoe bepaal je op een energiediagram de reactie-energie?",
        opties=[
            "als het verschil tussen de energie van de producten en die van de reagentia",
            "als de hoogte van de top van het diagram boven de reagentia",
            "als de hoogte van de top van het diagram boven de producten",
            "als de som van de energie van de reagentia en van de producten",
        ],
        antwoord=0,
        uitleg="De reactie-energie is het hoogteverschil tussen begin en einde. De hoogte van de top boven de reagentia is de activeringsenergie.",
    ),
    dict(
        type="waarofniet",
        vraag="Bij een exo-energetische reactie liggen de producten lager dan de reagentia.",
        antwoord=True,
        uitleg="Het teveel aan energie gaat naar de omgeving, dus wordt het mengsel warmer. Op het diagram daalt de lijn van links naar rechts.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke uitspraken over een endo-energetische reactie zijn juist? Kruis alles aan wat juist is.",
        opties=[
            "de reactie neemt energie uit de omgeving op",
            "de producten hebben meer inwendige energie dan de reagentia",
            "de omgeving koelt tijdens de reactie af",
            "de reactie heeft geen activeringsenergie nodig",
        ],
        antwoord=[0, 1, 2],
        uitleg="Endo-energetisch betekent dat er energie naar binnen gaat. Een activeringsenergie is er altijd, ook bij endo-energetische reacties.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een reactie voelt duidelijk warm aan. Wat weet je dan?",
        opties=[
            "ze is exo-energetisch, dus exotherm",
            "ze is endo-energetisch, dus endotherm",
            "ze heeft een heel hoge activeringsenergie",
            "ze verloopt zonder geactiveerd complex",
        ],
        antwoord=0,
        uitleg="Warm aanvoelen betekent dat de reactie energie aan de omgeving geeft. De activeringsenergie kan daarbij nog hoog of laag zijn.",
    ),
    dict(
        type="waarofniet",
        vraag="Een reactie met een hoge activeringsenergie verloopt bij kamertemperatuur meestal traag.",
        antwoord=True,
        uitleg="Weinig deeltjes raken dan over de berg, dus zijn er weinig effectieve botsingen. Daarom moet je zo'n reactie vaak opwarmen om ze te zien gebeuren.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat doet een katalysator met een reactie?",
        opties=[
            "hij verlaagt de activeringsenergie van de reactie",
            "hij verhoogt de energie van de reactieproducten",
            "hij levert de ontbrekende reagentia aan",
            "hij maakt meer reactieproduct dan anders",
        ],
        antwoord=0,
        uitleg="Door de lagere berg hebben meer botsingen genoeg energie, dus gaat de reactie sneller. Hoeveel product er komt, verandert niet.",
    ),
    dict(
        type="waarofniet",
        vraag="Een katalysator wordt tijdens de reactie opgebruikt.",
        antwoord=False,
        uitleg="Hij doet mee aan tussenstappen maar komt er achteraf onveranderd uit. Daarom kan een kleine hoeveelheid heel lang blijven werken.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke uitspraken over het energiediagram met en zonder katalysator zijn juist? Kruis alles aan wat juist is.",
        opties=[
            "de top ligt met een katalysator lager",
            "de energie van de reagentia blijft dezelfde",
            "de energie van de producten blijft dezelfde",
            "de reactie-energie wordt met een katalysator groter",
        ],
        antwoord=[0, 1, 2],
        uitleg="Enkel de berg wordt lager. Begin en einde liggen even hoog als zonder katalysator, dus blijft de reactie-energie precies dezelfde.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je een katalysator die in een levend organisme werkt?",
        antwoord=["biokatalysator", "enzym"],
        uitleg="Enzymen zijn proteïnen die een reactie in het lichaam versnellen. Zonder hen zouden heel veel reacties in de cel veel te traag verlopen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarom zijn enzymen in het lichaam zo belangrijk?",
        opties=[
            "ze laten reacties bij lichaamstemperatuur snel genoeg verlopen",
            "ze verwarmen het lichaam tot boven de veertig graden",
            "ze zorgen dat een reactie meer product oplevert dan mogelijk",
            "ze vervangen de reagentia die het lichaam niet heeft",
        ],
        antwoord=0,
        uitleg="Opwarmen is in een cel geen optie, dus moet de berg lager. Daarom heeft bijna elke reactie in het lichaam haar eigen enzym.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat staat er op de horizontale as van een Boltzmannverdeling?",
        opties=[
            "de kinetische energie van de deeltjes",
            "de tijd die de reactie al bezig is",
            "de concentratie van de reagentia",
            "de massa van de botsende deeltjes",
        ],
        antwoord=0,
        uitleg="Verticaal staat hoeveel deeltjes die energie hebben. De activeringsenergie zet je als een streep op die as; alles rechts daarvan kan reageren.",
    ),
    dict(
        type="waarofniet",
        vraag="Bij een hogere temperatuur schuift de top van de Boltzmannverdeling naar rechts en wordt ze lager en breder.",
        antwoord=True,
        uitleg="De energie is dan over een breder gebied verspreid. Daardoor ligt er een veel groter deel van de oppervlakte rechts van de activeringsenergie.",
    ),
    dict(
        type="meerkeuze",
        vraag="Hoe zie je op een Boltzmannverdeling dat een reactie sneller zal gaan?",
        opties=[
            "er ligt een groter deel van de deeltjes rechts van de activeringsenergie",
            "de hele kromme ligt hoger boven de horizontale as",
            "de kromme is smaller geworden rond haar top",
            "de kromme begint verder van de oorsprong",
        ],
        antwoord=0,
        uitleg="Alleen die deeltjes hebben genoeg energie voor een effectieve botsing. Hoe groter dat stuk, hoe meer botsingen tot een reactie leiden.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een katalysator zet in de Boltzmannverdeling de streep van de activeringsenergie naar links. Wat volgt daaruit?",
        opties=[
            "meer deeltjes hebben genoeg energie om te reageren",
            "de deeltjes bewegen vanaf dan allemaal sneller",
            "er zijn minder botsingen per seconde nodig",
            "de temperatuur van het mengsel stijgt mee",
        ],
        antwoord=0,
        uitleg="De verdeling van de deeltjes zelf blijft gelijk; enkel de drempel zakt. Daardoor valt een groter deel van de deeltjes erboven.",
    ),
    dict(
        type="waarofniet",
        vraag="Een katalysator verandert de reactie-energie van een reactie.",
        antwoord=False,
        uitleg="De reactie-energie is het verschil tussen begin en einde, en die twee liggen even hoog als zonder katalysator. Enkel de activeringsenergie wordt kleiner.",
    ),
    dict(
        type="invultekst",
        vraag="Een reactie geeft warmte af aan de omgeving. Is ze exo- of endo-energetisch?",
        antwoord=["exo-energetisch", "exo", "exotherm"],
        uitleg="Energie gaat naar buiten, dus exo. Op het diagram liggen de producten lager dan de reagentia.",
    ),
    dict(
        type="meerkeuze",
        vraag="Van welke twee grootheden lees je de grootte af op een energiediagram van een reactie? Kruis alles aan wat juist is.",
        opties=[
            "de activeringsenergie",
            "de reactie-energie",
            "de tijd die de reactie duurt",
            "de concentratie van de producten",
        ],
        antwoord=[0, 1],
        uitleg="Op de verticale as staat energie, dus lees je hoogteverschillen af. Tijd en concentratie staan er niet op; die horen bij een concentratie-tijdgrafiek.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een proef verloopt te traag en je mag de stoffen niet opwarmen. Wat probeer je nog?",
        opties=[
            "een katalysator toevoegen of de stof fijner verdelen",
            "het reactievat in een groter vat overgieten",
            "wachten tot de concentratie vanzelf stijgt",
            "de reactie in het donker laten doorgaan",
        ],
        antwoord=0,
        uitleg="Van de vier factoren blijven de verdelingsgraad, de concentratie en de katalysator over. Een groter vat verlaagt de concentratie juist, dus dat vertraagt.",
    ),
]
