# -*- coding: utf-8 -*-
"""Woordenschat: school, beroepen, sport en vrije tijd.

Vijf woordvelden uit de vakfiche Engels 1ste graad A-stroom: onderwijs en
vorming, de professionele wereld (beroepen), sport en ontspanning,
communicatie en multimedia, en instructietaal.

Instructietaal krijgt hier bewust veel plaats. Op een digitaal examen staan de
opdrachten zelf in het Engels: tick, underline, match, complete. Wie die
woorden niet kent, verliest punten op een vraag die hij eigenlijk kan.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="In een opdracht staat: 'Tick the correct answer.' Wat moet je doen?",
         opties=["het juiste antwoord aankruisen", "het juiste antwoord schrappen",
                 "het antwoord in het Nederlands geven", "het antwoord luidop zeggen"],
         antwoord=0,
         uitleg="To tick = aankruisen, aanvinken. Correct = juist. Dit is instructietaal: de taal van de opdracht zelf."),
    dict(type="meerkeuze",
         vraag="In een opdracht staat: 'Underline the verbs in the text.' Wat moet je doen?",
         opties=["de werkwoorden onderstrepen", "de werkwoorden vertalen",
                 "de werkwoorden overschrijven", "de werkwoorden tellen"],
         antwoord=0,
         uitleg="To underline = onderstrepen, a verb = een werkwoord. Vergelijk: to circle (omcirkelen), to cross out (doorstrepen)."),
    dict(type="meerkeuze",
         vraag="Welke opdrachten vragen dat je iets aan elkaar koppelt of aanvult?",
         opties=["Match the words with the pictures.", "Complete the sentences.",
                 "Fill in the gaps.", "Read the text aloud."],
         antwoord=[0, 1, 2],
         uitleg="To match = koppelen, to complete = aanvullen, a gap = een leeg vakje. 'Read aloud' is luidop lezen en koppelt niets."),
    dict(type="invultekst",
         vraag="In een opdracht staat: 'Choose the ___ answer.' Welk Engels woord betekent 'juiste'?",
         antwoord="correct",
         uitleg="Correct = juist. 'Right' kan ook: choose the right answer."),
    dict(type="waarofniet",
         vraag="'Put the sentences in the right order' betekent dat je de zinnen in de juiste volgorde moet zetten.",
         antwoord=True,
         uitleg="Order = volgorde. Het is een van de vraagtypes die je op het digitale examen kan krijgen."),
    dict(type="meerkeuze",
         vraag="Je leest op je uurrooster: 'Maths, Geography, PE.' Welk vak is PE?",
         opties=["lichamelijke opvoeding", "plastische opvoeding",
                 "praktische economie", "Engelse poëzie"],
         antwoord=0,
         uitleg="PE staat voor physical education: lichamelijke opvoeding. Maths = wiskunde, Geography = aardrijkskunde."),
    dict(type="invultekst",
         vraag="Hoe noem je het vak wiskunde in Brits Engels? Eén woord, afgekort.",
         antwoord="maths",
         uitleg="Maths in Brits Engels, math in Amerikaans Engels. Voluit: mathematics."),
    dict(type="meerkeuze",
         vraag="Je leest: 'I got a good mark for my history test.' Wat is 'a mark'?",
         opties=["een punt of cijfer", "een merkteken op de bank",
                 "een handtekening", "een opmerking"],
         antwoord=0,
         uitleg="A mark = een punt of cijfer in Brits Engels. Amerikanen zeggen a grade."),
    dict(type="waarofniet",
         vraag="'Homework' staat in het Engels in het enkelvoud: je zegt 'my homework is difficult'.",
         antwoord=True,
         uitleg="Homework is ontelbaar, net als information en advice. 'Homeworks' bestaat niet."),
    dict(type="meerkeuze",
         vraag="Je leest: 'The headteacher spoke to the whole school.' Wie sprak er?",
         opties=["de directeur", "de leraar Engels",
                 "de klastitularis", "de schoolarts"],
         antwoord=0,
         uitleg="A headteacher = een directeur in Brits Engels. In de VS zeggen ze a principal. A teacher is een leerkracht."),
    dict(type="meerkeuze",
         vraag="Je leest: 'She works in a hospital and helps the doctors.' Wat is haar beroep waarschijnlijk?",
         opties=["verpleegkundige", "bakker", "boekhouder", "kapster"],
         antwoord=0,
         uitleg="A nurse = een verpleegkundige. De zin geeft je twee aanwijzingen: het ziekenhuis en de dokters."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn beroepen?",
         opties=["engineer", "plumber", "lawyer", "hobby"],
         antwoord=[0, 1, 2],
         uitleg="An engineer = een ingenieur, a plumber = een loodgieter, a lawyer = een advocaat. A hobby is geen beroep."),
    dict(type="invultekst",
         vraag="Hoe noem je iemand die brood bakt en verkoopt? Antwoord in het Engels, één woord.",
         antwoord="baker",
         uitleg="A baker = een bakker. Zijn winkel is a baker's of a bakery."),
    dict(type="waarofniet",
         vraag="'An actress' is in het Engels een vrouw die danst.",
         antwoord=False,
         uitleg="An actress is een actrice: ze speelt toneel of film. Een danseres is a dancer. Vandaag gebruiken veel mensen trouwens 'actor' voor iedereen."),
    dict(type="meerkeuze",
         vraag="Je leest: 'He plays the guitar in a band.' Wat doet hij?",
         opties=["hij speelt gitaar in een groep", "hij luistert naar muziek",
                 "hij zingt in een koor", "hij danst op een feest"],
         antwoord=0,
         uitleg="Let op het lidwoord bij instrumenten: to play THE guitar. Bij sporten valt het weg: to play football."),
    dict(type="waarofniet",
         vraag="Je zegt in het Engels 'I play the tennis' en 'I play piano'.",
         antwoord=False,
         uitleg="Net omgekeerd: bij sport zonder lidwoord (I play tennis) en bij een instrument met the (I play the piano)."),
    dict(type="meerkeuze",
         vraag="Je leest: 'We go swimming twice a week.' Welke sport doen ze?",
         opties=["zwemmen", "fietsen", "lopen", "schaatsen"],
         antwoord=0,
         uitleg="To go swimming = gaan zwemmen. Met 'to go' maak je veel sporten: go cycling, go running, go skating."),
    dict(type="invultekst",
         vraag="Vul aan: 'In summer we often go ___ in the sea.' Welk Engels woord betekent 'zwemmen'?",
         antwoord="swimming",
         uitleg="To go swimming = gaan zwemmen. Na 'go' komt bij sporten de -ing-vorm."),
    dict(type="meerkeuze",
         vraag="Je leest: 'Send me a message on my mobile.' Wat is 'a mobile' in Brits Engels?",
         opties=["een gsm", "een computer", "een brief", "een tablet"],
         antwoord=0,
         uitleg="A mobile of a mobile phone = een gsm in Brits Engels. Amerikanen zeggen a cell phone."),
    dict(type="meerkeuze",
         vraag="Je leest: 'Don't forget to switch off your phone in class.' Wat moet je doen?",
         opties=["je telefoon uitzetten", "je telefoon opladen",
                 "je telefoon meebrengen", "je telefoon afgeven"],
         antwoord=0,
         uitleg="To switch off = uitzetten. Don't forget to = vergeet niet om."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="In een opdracht staat: 'Write about 80 words.' Wat verwacht men?",
         opties=["een tekst van ongeveer 80 woorden", "precies 80 zinnen",
                 "een tekst over het getal 80", "80 losse woorden op een rij"],
         antwoord=0,
         uitleg="About = ongeveer. De fiche rekent de opgegeven lengte mee bij de taakvoltooiing, dus veel korter of langer kost punten."),
    dict(type="meerkeuze",
         vraag="In een opdracht staat: 'Answer in full sentences.' Wat betekent dat?",
         opties=["antwoord met hele zinnen", "antwoord met één woord",
                 "antwoord in het Nederlands", "antwoord met een tekening"],
         antwoord=0,
         uitleg="A full sentence = een volledige zin. Dus niet 'yes' maar 'Yes, I do'."),
    dict(type="invultekst",
         vraag="In een opdracht staat: 'Fill in the ___.' Welk Engels woord betekent hier 'de leegtes'? Meervoud.",
         antwoord="gaps",
         uitleg="A gap = een gaatje of een leeg vakje. Fill in the gaps = vul de leegtes in."),
    dict(type="waarofniet",
         vraag="'Cross out the wrong word' betekent dat je het foute woord moet omcirkelen.",
         antwoord=False,
         uitleg="To cross out = doorstrepen. Omcirkelen is to circle. Wrong = fout."),
    dict(type="meerkeuze",
         vraag="Welke opdrachten vragen dat je iets beslist over waar of niet waar?",
         opties=["True or false?", "Decide if the sentence is correct.",
                 "Tick true or false.", "Draw a picture."],
         antwoord=[0, 1, 2],
         uitleg="To decide = beslissen. Tekenen komt op een taalexamen niet voor als opdracht."),
    dict(type="meerkeuze",
         vraag="Je leest: 'Our class has twenty-four pupils.' Hoeveel leerlingen zijn er?",
         opties=["24", "20", "44", "14"],
         antwoord=0,
         uitleg="Twenty-four = vierentwintig. In het Engels zet je het tiental eerst, met een streepje ertussen."),
    dict(type="waarofniet",
         vraag="'A pupil' en 'a student' kunnen allebei een leerling of student aanduiden.",
         antwoord=True,
         uitleg="In Brits Engels is a pupil eerder een leerling op school en a student iemand aan de universiteit. Amerikanen zeggen bijna altijd student."),
    dict(type="meerkeuze",
         vraag="Je leest: 'The timetable changed after the holidays.' Wat veranderde er?",
         opties=["het uurrooster", "het schoolreglement",
                 "de leraar", "het klaslokaal"],
         antwoord=0,
         uitleg="A timetable = een uurrooster of dienstregeling. After the holidays = na de vakantie."),
    dict(type="invultekst",
         vraag="Hoe noem je in het Engels de plaats waar leerlingen tussen de lessen spelen? Eén woord.",
         antwoord="playground",
         uitleg="A playground = een speelplaats. Play = spelen, ground = grond, terrein."),
    dict(type="meerkeuze",
         vraag="Je leest een vacature: 'We are looking for a shop assistant.' Welk beroep is dat?",
         opties=["winkelbediende", "boekhouder", "chauffeur", "bewaker"],
         antwoord=0,
         uitleg="A shop assistant = een winkelbediende. To look for = zoeken."),
    dict(type="waarofniet",
         vraag="'A firefighter' is iemand die branden blust.",
         antwoord=True,
         uitleg="A firefighter = een brandweerman of -vrouw. Fire = vuur of brand, to fight = bestrijden."),
    dict(type="meerkeuze",
         vraag="Je leest: 'He works from nine to five in an office.' Wat weet je over zijn werk?",
         opties=["hij werkt overdag op kantoor", "hij werkt 's nachts thuis",
                 "hij werkt in het weekend", "hij werkt in de bouw"],
         antwoord=0,
         uitleg="An office = een kantoor. 'From nine to five' is de gewone kantoordag."),
    dict(type="meerkeuze",
         vraag="Welke woorden horen bij vrije tijd?",
         opties=["reading", "drawing", "gardening", "homework"],
         antwoord=[0, 1, 2],
         uitleg="Reading = lezen, drawing = tekenen, gardening = tuinieren. Huiswerk is geen vrije tijd."),
    dict(type="invultekst",
         vraag="Vul aan: 'My favourite ___ is playing chess.' Welk Engels woord betekent 'hobby'?",
         antwoord="hobby",
         uitleg="A hobby = een hobby. Chess = schaken. Favourite schrijf je in Brits Engels met -our-."),
    dict(type="meerkeuze",
         vraag="Je leest: 'The match ended in a draw.' Hoe eindigde de wedstrijd?",
         opties=["gelijkspel", "met een overwinning",
                 "met een verlies", "zonder einde"],
         antwoord=0,
         uitleg="A draw = een gelijkspel. To win = winnen, to lose = verliezen, a match = een wedstrijd."),
    dict(type="waarofniet",
         vraag="'To win' betekent verliezen en 'to lose' betekent winnen.",
         antwoord=False,
         uitleg="Precies omgekeerd: to win = winnen, to lose = verliezen. De winnaar is the winner, de verliezer the loser."),
    dict(type="meerkeuze",
         vraag="Je leest: 'Follow us on social media for more news.' Wat vraagt deze zin?",
         opties=["hen volgen op sociale media", "hen een mail sturen",
                 "hen opbellen", "hun winkel bezoeken"],
         antwoord=0,
         uitleg="To follow = volgen. Social media, to post, to share en to like zijn allemaal woorden uit het woordveld communicatie en multimedia."),
    dict(type="meerkeuze",
         vraag="Je leest: 'I downloaded the app yesterday.' Wat deed deze persoon?",
         opties=["de app binnengehaald", "de app verwijderd",
                 "de app gemaakt", "de app verkocht"],
         antwoord=0,
         uitleg="To download = downloaden, binnenhalen. Het omgekeerde is to upload: iets naar het internet sturen."),
    dict(type="invultekst",
         vraag="Welk Engels werkwoord betekent 'iets op het internet zetten'? Het tegengestelde van download.",
         antwoord="upload",
         uitleg="To upload = opladen naar het internet, to download = binnenhalen. Up is omhoog, down is omlaag."),
    dict(type="waarofniet",
         vraag="'To chat' betekent in het Engels ook gewoon babbelen, niet alleen typen op een scherm.",
         antwoord=True,
         uitleg="To chat = babbelen, kletsen. Het woord bestond al lang voor er computers waren."),
]
