# -*- coding: utf-8 -*-
"""Woordenschat: getallen, tijd, weer, reizen en landen.

Zeven woordvelden uit de vakfiche Engels 1ste graad A-stroom: cijfers,
gewichten, maten en hoeveelheden; dagen, maanden, seizoenen en feesten; uur en
plaats; het weer; transportmiddelen; vakantie en reizen; landen en
nationaliteiten.

Dit is de woordenschat waarmee je een dienstregeling, een weerbericht of een
reisverslag ontcijfert. Op het examen komt dat soort tekst geregeld terug.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Je leest: 'The train leaves at a quarter past eight.' Hoe laat vertrekt de trein?",
         opties=["8.15 uur", "7.45 uur", "8.45 uur", "8.30 uur"],
         antwoord=0,
         uitleg="A quarter past eight = kwart over acht. Past is erover, to is ervoor: a quarter to eight is kwart voor acht."),
    dict(type="meerkeuze",
         vraag="Je leest: 'It is ten to six.' Hoe laat is het?",
         opties=["5.50 uur", "6.10 uur", "10.06 uur", "6.50 uur"],
         antwoord=0,
         uitleg="Ten to six = tien voor zes, dus 5.50 uur. Bij 'to' tel je terug naar het volgende uur."),
    dict(type="invultekst",
         vraag="Hoe zeg je in het Engels 'half acht' (7.30 uur)? Vul aan: 'half past ___'.",
         antwoord="seven",
         uitleg="Half past seven = half acht. Opgepast: het Engels telt vanaf het uur dat geweest is, het Nederlands naar het uur dat komt."),
    dict(type="waarofniet",
         vraag="'Half past nine' is in het Nederlands half tien.",
         antwoord=True,
         uitleg="Half past nine = negen uur en een half = half tien. Wie dat verwart, komt een uur te vroeg of te laat."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn maanden?",
         opties=["August", "January", "October", "Sunday"],
         antwoord=[0, 1, 2],
         uitleg="August = augustus, January = januari, October = oktober. Sunday is een dag. Let op: maanden en dagen krijgen in het Engels een hoofdletter."),
    dict(type="invultekst",
         vraag="Welke maand komt na June? Antwoord in het Engels.",
         antwoord="july",
         uitleg="July = juli, na June (juni). De zomer: June, July, August."),
    dict(type="meerkeuze",
         vraag="Je leest: 'See you on Wednesday.' Welke dag is dat?",
         opties=["woensdag", "dinsdag", "donderdag", "zaterdag"],
         antwoord=0,
         uitleg="Wednesday = woensdag. Je spreekt de d niet uit: 'wensdee'. Tuesday is dinsdag, Thursday donderdag."),
    dict(type="waarofniet",
         vraag="In het Engels schrijf je de dagen en de maanden met een kleine letter.",
         antwoord=False,
         uitleg="Net niet: Monday, July, Christmas krijgen allemaal een hoofdletter. In het Nederlands schrijven we die wél klein."),
    dict(type="meerkeuze",
         vraag="Je leest een weerbericht: 'Tomorrow will be cloudy with some showers.' Wat voor weer wordt het?",
         opties=["bewolkt met buien", "zonnig en warm",
                 "koud met sneeuw", "mistig en droog"],
         antwoord=0,
         uitleg="Cloudy = bewolkt, a shower = een bui. Andere weerwoorden: sunny, rainy, windy, foggy, snowy."),
    dict(type="meerkeuze",
         vraag="Welke woorden beschrijven het weer?",
         opties=["windy", "foggy", "freezing", "crowded"],
         antwoord=[0, 1, 2],
         uitleg="Windy = winderig, foggy = mistig, freezing = ijskoud. Crowded = druk met mensen, en dat zegt niets over het weer."),
    dict(type="invultekst",
         vraag="Vul aan: 'Take an umbrella, it is ___ outside.' Welk Engels woord betekent hier 'aan het regenen'?",
         antwoord="raining",
         uitleg="It is raining = het regent. An umbrella = een paraplu. Bij weer dat nu bezig is, gebruik je de present continuous."),
    dict(type="meerkeuze",
         vraag="Je leest: 'The temperature will drop to five degrees.' Wat gebeurt er met de temperatuur?",
         opties=["ze daalt tot vijf graden", "ze stijgt tot vijf graden",
                 "ze blijft vijf graden", "ze valt weg"],
         antwoord=0,
         uitleg="To drop = dalen, vallen. Het tegengestelde is to rise: stijgen. A degree = een graad."),
    dict(type="meerkeuze",
         vraag="Je leest: 'We went to Rome by plane and came back by train.' Hoe reisden ze?",
         opties=["heen met het vliegtuig, terug met de trein",
                 "heen met de trein, terug met het vliegtuig",
                 "heen en terug met de bus",
                 "heen en terug met de auto"],
         antwoord=0,
         uitleg="By plane = met het vliegtuig, by train = met de trein. Let op de vaste uitdrukking: by bike, by car, by bus, maar on foot voor te voet."),
    dict(type="waarofniet",
         vraag="'On foot' betekent te voet, ook al staan er andere vervoermiddelen met 'by'.",
         antwoord=True,
         uitleg="By bike, by car, by bus, by train, by plane, maar on foot. De fiche noemt die voorzetsels bij de frequente prepositions."),
    dict(type="invultekst",
         vraag="Vul aan: 'I go to school ___ bike.' Welk kort Engels voorzetsel hoort hier?",
         antwoord="by",
         uitleg="By bike = met de fiets. Bij vervoermiddelen gebruik je 'by' zonder lidwoord: by bus, by car, by train."),
    dict(type="meerkeuze",
         vraag="Je leest: 'Our flight is delayed by two hours.' Wat is er aan de hand?",
         opties=["de vlucht heeft twee uur vertraging", "de vlucht is geannuleerd",
                 "de vlucht vertrekt twee uur vroeger", "de vlucht duurt twee uur"],
         antwoord=0,
         uitleg="A flight = een vlucht, delayed = vertraagd. Cancelled zou geannuleerd betekenen."),
    dict(type="meerkeuze",
         vraag="Welke woorden hoor je op een luchthaven?",
         opties=["boarding pass", "luggage", "gate", "platform"],
         antwoord=[0, 1, 2],
         uitleg="A boarding pass = een instapkaart, luggage = bagage, a gate = een gate. A platform is een perron, en dat hoort bij het station."),
    dict(type="meerkeuze",
         vraag="Je leest: 'She is from Scotland, so she is Scottish.' Wat is het verschil tussen die twee woorden?",
         opties=["Scotland is het land, Scottish de nationaliteit",
                 "Scotland is de taal, Scottish het land",
                 "Scotland is een stad, Scottish een streek",
                 "er is geen verschil tussen de twee"],
         antwoord=0,
         uitleg="Zo werkt het bij elk land: Spain wordt Spanish, France wordt French, Belgium wordt Belgian."),
    dict(type="invultekst",
         vraag="Iemand komt uit Spain. Wat is zijn nationaliteit in het Engels? Eén woord.",
         antwoord="spanish",
         uitleg="Spanish = Spaans. In het Engels schrijf je dat met een hoofdletter: Spanish."),
    dict(type="waarofniet",
         vraag="'Vacation' is het Britse woord voor vakantie en 'holiday' het Amerikaanse.",
         antwoord=False,
         uitleg="Omgekeerd: een Brit gaat 'on holiday', een Amerikaan 'on vacation'. In het Brits kan a holiday ook één feestdag zijn."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Je leest: 'The box weighs three kilos.' Hoe zwaar is de doos?",
         opties=["drie kilogram", "drie gram", "drie liter", "drie meter"],
         antwoord=0,
         uitleg="To weigh = wegen. Britten gebruiken daarnaast pounds en stones, Amerikanen pounds."),
    dict(type="meerkeuze",
         vraag="Je leest: 'It is about five miles from here.' Wat weet je?",
         opties=["het is een afstand", "het is een gewicht",
                 "het is een temperatuur", "het is een prijs"],
         antwoord=0,
         uitleg="A mile = ongeveer 1,6 kilometer. In het Verenigd Koninkrijk en de Verenigde Staten meet men afstanden in miles."),
    dict(type="invultekst",
         vraag="Hoeveel is 'a dozen'? Antwoord met een cijfer.",
         antwoord="12",
         uitleg="A dozen = een dozijn = twaalf. Je hoort het vooral bij eieren: a dozen eggs."),
    dict(type="waarofniet",
         vraag="'A hundred' is honderd en 'a thousand' is duizend.",
         antwoord=True,
         uitleg="En een miljoen is a million. Let op: in het Engels zeg je 'a hundred' of 'one hundred', nooit gewoon 'hundred' alleen."),
    dict(type="meerkeuze",
         vraag="Je leest: 'We need a few eggs and a little milk.' Waarom staat er twee keer iets anders?",
         opties=["eggs kan je tellen, milk niet", "milk is duurder dan eggs",
                 "few en little betekenen hetzelfde", "het is een schrijffout"],
         antwoord=0,
         uitleg="A few gebruik je bij telbare woorden (a few eggs), a little bij ontelbare (a little milk, a little time)."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn hoeveelheden die je bij ontelbare dingen gebruikt?",
         opties=["a little", "much", "a lot of", "many"],
         antwoord=[0, 1, 2],
         uitleg="A little, much en a lot of passen bij ontelbare woorden zoals water en time. Many hoort bij telbare: many books."),
    dict(type="meerkeuze",
         vraag="Je leest: 'The shop opens at noon.' Hoe laat is dat?",
         opties=["12 uur 's middags", "12 uur 's nachts",
                 "10 uur 's ochtends", "6 uur 's avonds"],
         antwoord=0,
         uitleg="Noon = de middag, 12 uur. Midnight is middernacht, 12 uur 's nachts."),
    dict(type="waarofniet",
         vraag="'Midnight' betekent in het Engels de middag.",
         antwoord=False,
         uitleg="Midnight = middernacht, dus 12 uur 's nachts. De middag is noon of midday."),
    dict(type="meerkeuze",
         vraag="Je leest: 'The film starts at 7 p.m.' Wanneer begint de film?",
         opties=["'s avonds om 7 uur", "'s ochtends om 7 uur",
                 "'s middags om 7 uur", "'s nachts om 7 uur"],
         antwoord=0,
         uitleg="P.m. staat voor post meridiem: na de middag. A.m. is ante meridiem: voor de middag."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn seizoenen?",
         opties=["spring", "summer", "winter", "weekend"],
         antwoord=[0, 1, 2],
         uitleg="Spring = lente, summer = zomer, winter = winter. Het vierde seizoen is autumn (Brits) of fall (Amerikaans)."),
    dict(type="invultekst",
         vraag="Welk seizoen komt na winter? Antwoord in het Engels.",
         antwoord="spring",
         uitleg="Spring = lente. De rij: winter, spring, summer, autumn."),
    dict(type="meerkeuze",
         vraag="Je leest: 'The meeting is on the third of May.' Welke datum is dat?",
         opties=["3 mei", "5 maart", "13 mei", "30 mei"],
         antwoord=0,
         uitleg="The third = de derde, May = mei. Bij data gebruik je rangtelwoorden: first, second, third, fourth."),
    dict(type="waarofniet",
         vraag="Bij een datum gebruik je in het Engels een rangtelwoord: 'the fifth of June', niet 'the five of June'.",
         antwoord=True,
         uitleg="De rangtelwoorden: first, second, third, fourth, fifth, en verder meestal met -th erachter, zoals twelfth en twentieth."),
    dict(type="meerkeuze",
         vraag="Je leest: 'We stayed in a small hotel near the beach.' Waar sliepen ze?",
         opties=["in een klein hotel bij het strand", "in een tent in het bos",
                 "bij familie in de stad", "in een huis aan een meer"],
         antwoord=0,
         uitleg="Near = dichtbij, the beach = het strand. To stay = verblijven, logeren."),
    dict(type="meerkeuze",
         vraag="Welke woorden hebben met een reis te maken?",
         opties=["a suitcase", "a passport", "a ticket", "a saucepan"],
         antwoord=[0, 1, 2],
         uitleg="A suitcase = een koffer, a passport = een paspoort, a ticket = een ticket. A saucepan is een kookpot."),
    dict(type="invultekst",
         vraag="Hoe noem je in het Engels het document dat je nodig hebt om naar een ander land te reizen? Eén woord.",
         antwoord="passport",
         uitleg="A passport = een paspoort. Op de luchthaven vraagt men: your passport, please."),
    dict(type="meerkeuze",
         vraag="Je leest op een station: 'The train to York departs from platform 4.' Waar moet je zijn?",
         opties=["op perron 4", "aan loket 4", "in wagon 4", "aan uitgang 4"],
         antwoord=0,
         uitleg="To depart = vertrekken, a platform = een perron. Het omgekeerde van depart is to arrive: aankomen."),
    dict(type="waarofniet",
         vraag="'Return ticket' betekent in Brits Engels een ticket heen en terug.",
         antwoord=True,
         uitleg="A return ticket = een retourtje. Een enkele reis is a single ticket in het Brits, a one-way ticket in het Amerikaans."),
    dict(type="meerkeuze",
         vraag="Je leest: 'Excuse me, how do I get to the museum?' Wat vraagt deze persoon?",
         opties=["de weg naar het museum", "de prijs van een ticket",
                 "de openingsuren", "de naam van de gids"],
         antwoord=0,
         uitleg="How do I get to...? = hoe raak ik bij...? Het antwoord bevat vaak: turn left, turn right, go straight on."),
    dict(type="meerkeuze",
         vraag="Je krijgt als antwoord: 'Go straight on and then turn left at the church.' Wat moet je doen?",
         opties=["rechtdoor en dan links bij de kerk",
                 "rechtdoor en dan rechts bij de kerk",
                 "links en dan rechtdoor tot de kerk",
                 "rechts en dan links voor de kerk"],
         antwoord=0,
         uitleg="Straight on = rechtdoor, to turn left = links afslaan, a church = een kerk. Right is rechts."),
]
