# -*- coding: utf-8 -*-
"""Grammatica: naamwoorden, lidwoorden en voornaamwoorden.

De eerste helft van de grammaticatabel uit de vakfiche Engels 1ste graad
A-stroom: zelfstandige naamwoorden (enkelvoud en meervoud), lidwoorden
(bepaald en onbepaald), determiners (aanwijzend, bezittelijk en vragend),
voornaamwoorden (persoonlijk, aanwijzend, bezittelijk en vragend), de plaats
van het persoonlijk voornaamwoord, hoofd- en rangtelwoorden, bijvoeglijke
naamwoorden met hun trappen van vergelijking, en de frequente voorzetsels.

De Engelse benamingen staan er met opzet bij: de fiche gebruikt ze, dus een
examenvraag kan dat ook.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is het meervoud van 'box'?",
         opties=["boxes", "boxs", "boxen", "boxies"],
         antwoord=0,
         uitleg="Na s, x, ch, sh en soms o komt -es: boxes, watches, dishes, buses. Anders gewoon -s."),
    dict(type="meerkeuze",
         vraag="Wat is het meervoud van 'baby'?",
         opties=["babies", "babys", "babyes", "babyies"],
         antwoord=0,
         uitleg="Een -y na een medeklinker wordt -ies: baby wordt babies, city wordt cities. Staat er een klinker voor, dan blijft de y: boy wordt boys."),
    dict(type="meerkeuze",
         vraag="Welke meervouden zijn onregelmatig?",
         opties=["children", "teeth", "mice", "tables"],
         antwoord=[0, 1, 2],
         uitleg="Child wordt children, tooth wordt teeth, mouse wordt mice. Table wordt gewoon tables."),
    dict(type="invultekst",
         vraag="Wat is het meervoud van 'man'? Eén Engels woord.",
         antwoord="men",
         uitleg="Man wordt men, woman wordt women. Let op de uitspraak van women: de eerste lettergreep klinkt als 'wi'."),
    dict(type="waarofniet",
         vraag="Het meervoud van 'knife' is 'knifes'.",
         antwoord=False,
         uitleg="Het is knives. Bij veel woorden op -f of -fe wordt dat -ves: leaf/leaves, wife/wives, life/lives."),
    dict(type="meerkeuze",
         vraag="Vul aan: 'I saw ___ elephant at the zoo.' Welk lidwoord hoort hier?",
         opties=["an", "a", "the", "geen lidwoord"],
         antwoord=0,
         uitleg="Voor een klinkerklank komt 'an': an elephant, an hour, an apple. Voor een medeklinkerklank 'a': a book, a university."),
    dict(type="waarofniet",
         vraag="Je zegt 'an university', want het woord begint met een u.",
         antwoord=False,
         uitleg="Het gaat om de klánk, niet om de letter. University begint met een joe-klank, dus: a university. Maar wel: an hour, want de h zwijgt."),
    dict(type="meerkeuze",
         vraag="Welk lidwoord is het bepaalde lidwoord (definite article) in het Engels?",
         opties=["the", "a", "an", "some"],
         antwoord=0,
         uitleg="The is bepaald: je weet over welk ding het gaat. A en an zijn onbepaald (indefinite): het maakt niet uit welke."),
    dict(type="meerkeuze",
         vraag="Vul aan: 'She is ___ teacher.' Welk lidwoord hoort hier?",
         opties=["a", "an", "the", "geen lidwoord"],
         antwoord=0,
         uitleg="Bij een beroep staat in het Engels altijd een lidwoord: she is a teacher, he is an engineer. In het Nederlands laten we dat weg."),
    dict(type="meerkeuze",
         vraag="Je wijst naar iets dat ver van je af ligt, en het zijn er meerdere. Welk aanwijzend woord gebruik je?",
         opties=["those", "these", "this", "that"],
         antwoord=0,
         uitleg="Dichtbij: this (enkelvoud) en these (meervoud). Veraf: that en those. Dat zijn de demonstratives."),
    dict(type="invultekst",
         vraag="Vul aan: '___ book here is mine.' Welk aanwijzend woord past bij één boek dat vlak bij je ligt?",
         antwoord="this",
         uitleg="This book = dit boek, dichtbij en enkelvoud. Meerdere boeken dichtbij: these books."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn bezittelijke determiners (possessive adjectives)?",
         opties=["my", "her", "their", "mine"],
         antwoord=[0, 1, 2],
         uitleg="My, your, his, her, its, our en their staan vóór een naamwoord: my book. Mine staat alleen: that book is mine."),
    dict(type="meerkeuze",
         vraag="Vul aan: 'This bag is ___.' Welk woord past hier, als de tas van mij is?",
         opties=["mine", "my", "me", "I"],
         antwoord=0,
         uitleg="Na het werkwoord staat het bezittelijk vóórnaamwoord: mine, yours, his, hers, ours, theirs. 'My' heeft altijd een naamwoord nodig."),
    dict(type="waarofniet",
         vraag="'It's' met een apostrof betekent 'it is', en 'its' zonder apostrof betekent 'van het'.",
         antwoord=True,
         uitleg="Zo is het, en het is een klassieke valstrik. The dog wagged its tail (van hem), maar It's raining (it is)."),
    dict(type="meerkeuze",
         vraag="Vul aan: 'Tom helped ___ with the homework.' Welk voornaamwoord past hier, als hij mij hielp?",
         opties=["me", "I", "my", "mine"],
         antwoord=0,
         uitleg="Na het werkwoord staat de objectvorm: me, you, him, her, it, us, them. Vóór het werkwoord staat de subjectvorm: I, you, he, she."),
    dict(type="waarofniet",
         vraag="In het Engels staat het persoonlijk voornaamwoord als lijdend voorwerp áchter het werkwoord: 'I saw him', niet 'I him saw'.",
         antwoord=True,
         uitleg="De fiche noemt dat de plaats van het persoonlijk voornaamwoord. In het Nederlands kan die plaats schuiven, in het Engels veel minder."),
    dict(type="meerkeuze",
         vraag="Vul aan: '___ is your favourite subject?' Welk vragend woord past hier?",
         opties=["What", "Who", "Where", "When"],
         antwoord=0,
         uitleg="What = wat, who = wie, where = waar, when = wanneer. Dat zijn de interrogative pronouns."),
    dict(type="invultekst",
         vraag="Vul aan: '___ bag is this?' Welk vragend woord vraagt naar de eigenaar?",
         antwoord="whose",
         uitleg="Whose = van wie. Verwar het niet met who's, dat 'who is' betekent."),
    dict(type="meerkeuze",
         vraag="Je leest: 'Which film do you prefer?' Waarnaar vraagt 'which'?",
         opties=["een keuze uit een beperkte groep", "de reden van iets",
                 "de plaats van iets", "het tijdstip van iets"],
         antwoord=0,
         uitleg="Which gebruik je als er een beperkte keuze is: which colour, red or blue? What is opener: what films do you like?"),
    dict(type="meerkeuze",
         vraag="Je leest: 'She lives in Belgium and goes to school by bus.' Welke voorzetsels staan er?",
         opties=["in en by", "on en at", "to en from", "of en for"],
         antwoord=0,
         uitleg="In Belgium, by bus: de fiche noemt precies die vaste combinaties bij de frequente prepositions."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is de vergrotende trap (comparative) van 'big'?",
         opties=["bigger", "more big", "biger", "biggest"],
         antwoord=0,
         uitleg="Korte bijvoeglijke naamwoorden krijgen -er, en bij één korte klinker verdubbelt de medeklinker: big wordt bigger, hot wordt hotter."),
    dict(type="meerkeuze",
         vraag="Wat is de overtreffende trap (superlative) van 'expensive'?",
         opties=["the most expensive", "the expensivest",
                 "more expensive", "the more expensive"],
         antwoord=0,
         uitleg="Lange bijvoeglijke naamwoorden krijgen more en most: more expensive, the most expensive. Korte krijgen -er en -est."),
    dict(type="invultekst",
         vraag="Wat is de vergrotende trap van 'good'? Eén Engels woord.",
         antwoord="better",
         uitleg="Good wordt better wordt the best. Onregelmatig, net als bad/worse/the worst en far/further/the furthest."),
    dict(type="meerkeuze",
         vraag="Welke trappen van vergelijking zijn onregelmatig?",
         opties=["good – better – best", "bad – worse – worst",
                 "far – further – furthest", "small – smaller – smallest"],
         antwoord=[0, 1, 2],
         uitleg="Small volgt gewoon de regel met -er en -est. De drie andere moet je uit het hoofd kennen."),
    dict(type="meerkeuze",
         vraag="Vul aan: 'This exercise is easier ___ the first one.' Welk woord hoort hier?",
         opties=["than", "as", "that", "then"],
         antwoord=0,
         uitleg="Bij een vergelijking hoort 'than': easier than, better than. 'Then' betekent dan in de tijd en is iets anders."),
    dict(type="waarofniet",
         vraag="Je zegt 'more better' om iets extra sterk te maken.",
         antwoord=False,
         uitleg="Nee, dat is dubbel. Het is gewoon better. Ofwel -er, ofwel more, nooit allebei."),
    dict(type="meerkeuze",
         vraag="Vul aan: 'She is ___ tall ___ her brother.' Welke woorden maken er een gelijkheid van?",
         opties=["as ... as", "than ... than", "so ... as", "more ... than"],
         antwoord=0,
         uitleg="As tall as = even groot als. Bij een verschil gebruik je taller than."),
    dict(type="meerkeuze",
         vraag="Waar staat een bijvoeglijk naamwoord in het Engels meestal?",
         opties=["vóór het naamwoord", "achter het naamwoord",
                 "achter het werkwoord", "helemaal vooraan de zin"],
         antwoord=0,
         uitleg="A red car, an interesting book: het bijvoeglijk naamwoord staat vooraan en verandert nooit van vorm, ook niet in het meervoud."),
    dict(type="waarofniet",
         vraag="Een bijvoeglijk naamwoord krijgt in het Engels een -s in het meervoud: 'reds cars'.",
         antwoord=False,
         uitleg="Nooit. Het is red cars, big houses, old friends. Alleen het naamwoord krijgt het meervoud."),
    dict(type="meerkeuze",
         vraag="Je leest: 'He came second in the race.' Wat voor woord is 'second' hier?",
         opties=["een rangtelwoord", "een hoofdtelwoord",
                 "een voorzetsel", "een voegwoord"],
         antwoord=0,
         uitleg="Rangtelwoorden (ordinal numbers) zeggen de plaats in een rij: first, second, third. Hoofdtelwoorden (cardinal numbers) tellen: one, two, three."),
    dict(type="invultekst",
         vraag="Wat is het rangtelwoord bij 'twelve'? Eén Engels woord.",
         antwoord="twelfth",
         uitleg="Twelve wordt twelfth. Let op de f. Andere lastige: five wordt fifth, nine wordt ninth, twenty wordt twentieth."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn rangtelwoorden?",
         opties=["first", "third", "twentieth", "fifteen"],
         antwoord=[0, 1, 2],
         uitleg="Fifteen is een hoofdtelwoord; het rangtelwoord daarvan is fifteenth."),
    dict(type="meerkeuze",
         vraag="Vul aan: 'The meeting is ___ Monday.' Welk voorzetsel hoort bij een dag?",
         opties=["on", "in", "at", "to"],
         antwoord=0,
         uitleg="At bij een uur (at six), on bij een dag of datum (on Monday), in bij een maand, seizoen of jaar (in May, in winter, in 2027)."),
    dict(type="invultekst",
         vraag="Vul aan: 'The lesson starts ___ nine o'clock.' Welk voorzetsel hoort bij een uur?",
         antwoord="at",
         uitleg="At nine o'clock. Het ezelsbruggetje: at voor een punt in de tijd, on voor een dag, in voor een langere periode."),
    dict(type="waarofniet",
         vraag="Je zegt 'on Monday' en 'in May'.",
         antwoord=True,
         uitleg="Dagen krijgen on, maanden krijgen in, uren krijgen at. Drie voorzetsels die je door elkaar haalt als je niet oplet."),
    dict(type="meerkeuze",
         vraag="Vul aan: 'The cat is ___ the table.' Welk voorzetsel betekent dat de kat erop zit?",
         opties=["on", "in", "under", "next to"],
         antwoord=0,
         uitleg="On = op, in = in, under = onder, next to = naast, between = tussen, behind = achter, in front of = voor."),
    dict(type="meerkeuze",
         vraag="Je leest: 'We walked to school on foot.' Welk voorzetsel hoort bij 'foot'?",
         opties=["on", "by", "with", "at"],
         antwoord=0,
         uitleg="On foot is de uitzondering: alle andere vervoerswijzen krijgen by. By bike, by car, by train, maar on foot."),
    dict(type="waarofniet",
         vraag="'Information' en 'advice' krijgen in het Engels geen meervouds-s.",
         antwoord=True,
         uitleg="Het zijn ontelbare woorden: much information, a piece of advice. 'Informations' en 'advices' bestaan niet."),
    dict(type="meerkeuze",
         vraag="Vul aan: 'Sarah and ___ went to the cinema.' Welk voornaamwoord past hier?",
         opties=["I", "me", "my", "mine"],
         antwoord=0,
         uitleg="Het is het onderwerp van de zin, dus de subjectvorm: Sarah and I. Als lijdend voorwerp zou het 'Sarah and me' zijn."),
    dict(type="meerkeuze",
         vraag="Je leest: 'Those books are theirs.' Wat betekent 'theirs'?",
         opties=["die van hen", "die van haar", "die van ons", "die van jou"],
         antwoord=0,
         uitleg="Theirs = van hen. De rij: mine, yours, his, hers, ours, theirs. Ze staan alleen, zonder naamwoord erachter."),
]
