# -*- coding: utf-8 -*-
"""Woordenschat: eten, wonen, kleding en dagelijkse dingen.

De woordvelden uit de vakfiche Frans 1ste graad A-stroom: eten en drinken,
woning (meubels, uitrusting), kleding en accessoires, kleuren, vormen en
materialen, dagelijkse bezigheden, dagelijkse en persoonlijke voorwerpen,
winkels en diensten.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat betekent 'le pain'?",
         opties=["het brood", "de pijn", "de pan", "het bord"],
         antwoord=0,
         uitleg="Le pain = het brood. Het klinkt als het Nederlandse 'pijn', maar betekent iets heel anders."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'le petit déjeuner'?",
         opties=["het ontbijt", "het kleine bord", "de kleine honger", "het tussendoortje"],
         antwoord=0,
         uitleg="Le petit déjeuner = het ontbijt, le déjeuner = het middagmaal, le dîner = het avondmaal."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn dranken?",
         opties=["l'eau", "le lait", "le jus d'orange", "le fromage"],
         antwoord=[0, 1, 2],
         uitleg="Water, melk en sinaasappelsap drink je. Le fromage is kaas."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'une pomme'?",
         opties=["een appel", "een aardappel", "een pomp", "een peer"],
         antwoord=0,
         uitleg="Une pomme = een appel. Une pomme de terre is een aardappel, letterlijk 'aardappel van de aarde'."),
    dict(type="invultekst",
         vraag="'Het water' schrijf je in het Frans als 'l'___'.",
         antwoord="eau",
         uitleg="L'eau = het water. Het is vrouwelijk: de l'eau fraîche."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'la maison'?",
         opties=["het huis", "de maand", "de meid", "de kamer"],
         antwoord=0,
         uitleg="La maison = het huis. Un appartement is een appartement."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn kamers of delen van een woning?",
         opties=["la cuisine", "la chambre", "la salle de bains", "la voiture"],
         antwoord=[0, 1, 2],
         uitleg="Keuken, slaapkamer en badkamer horen bij de woning. La voiture is de auto."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'la chambre'?",
         opties=["de slaapkamer", "de keuken", "de kelder", "de zolder"],
         antwoord=0,
         uitleg="La chambre = de slaapkamer. La cuisine is de keuken."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'la table'?",
         opties=["de tafel", "het tablet", "het schilderij", "de trap"],
         antwoord=0,
         uitleg="La table = de tafel, une chaise = een stoel."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn kledingstukken?",
         opties=["un pantalon", "une robe", "des chaussures", "une fenêtre"],
         antwoord=[0, 1, 2],
         uitleg="Broek, jurk en schoenen draag je. Une fenêtre is een raam."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'un manteau'?",
         opties=["een jas", "een hemd", "een trui", "een muts"],
         antwoord=0,
         uitleg="Un manteau = een jas of mantel. Un pull is een trui."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'rouge'?",
         opties=["rood", "groen", "geel", "grijs"],
         antwoord=0,
         uitleg="Rouge = rood. Vert is groen, jaune geel, gris grijs."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn kleuren?",
         opties=["bleu", "vert", "noir", "long"],
         antwoord=[0, 1, 2],
         uitleg="Blauw, groen en zwart zijn kleuren. 'Long' betekent lang."),
    dict(type="waarofniet",
         vraag="In het Frans staat de kleur meestal achter het naamwoord: 'une robe bleue'.",
         antwoord=True,
         uitleg="Bijna alle kleuren komen na het naamwoord, en ze passen zich aan: une robe bleue, un pull bleu."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'Je me lève à sept heures'?",
         opties=["Ik sta om zeven uur op.", "Ik ga om zeven uur slapen.",
                 "Ik eet om zeven uur.", "Ik vertrek om zeven uur."],
         antwoord=0,
         uitleg="Se lever = opstaan, en het is wederkerend: je me lève, tu te lèves."),
    dict(type="meerkeuze",
         vraag="Welke werkwoorden horen bij de dagelijkse bezigheden?",
         opties=["se lever", "se laver", "s'habiller", "neiger"],
         antwoord=[0, 1, 2],
         uitleg="Opstaan, zich wassen en zich aankleden doe je elke dag. 'Neiger' betekent sneeuwen."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'la boulangerie'?",
         opties=["de bakkerij", "de slagerij", "de apotheek", "de boekhandel"],
         antwoord=0,
         uitleg="Le pain koop je bij le boulanger, in la boulangerie."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'le supermarché'?",
         opties=["de supermarkt", "de markt op zondag", "het winkelcentrum", "de kruidenier"],
         antwoord=0,
         uitleg="Le marché is de markt, le supermarché de supermarkt."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'un sac'?",
         opties=["een tas", "een zak geld", "een jas", "een doos"],
         antwoord=0,
         uitleg="Un sac = een tas of zak. Un sac à dos is een rugzak."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'la clé'?",
         opties=["de sleutel", "de klas", "de kleur", "het klein"],
         antwoord=0,
         uitleg="La clé (of la clef) = de sleutel. Een dagelijks voorwerp dat vaak in teksten opduikt."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat betekent 'Je voudrais une baguette, s'il vous plaît'?",
         opties=["Ik zou graag een stokbrood willen, alstublieft.",
                 "Ik heb een stokbrood gekocht.",
                 "Waar is het stokbrood?",
                 "Het stokbrood is op."],
         antwoord=0,
         uitleg="Une baguette is een stokbrood. 'Je voudrais' is de beleefde manier om iets te bestellen."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'Ça coûte combien ?'",
         opties=["Hoeveel kost dat?", "Hoeveel heb je?", "Hoeveel wil je?", "Wat is dat?"],
         antwoord=0,
         uitleg="Coûter = kosten, combien = hoeveel. Ook 'C'est combien ?' kan."),
    dict(type="meerkeuze",
         vraag="Welke woorden hoor je in een winkel?",
         opties=["la caisse", "un client", "le prix", "le jardin"],
         antwoord=[0, 1, 2],
         uitleg="Kassa, klant en prijs horen bij een winkel. Le jardin is de tuin."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'Je fais les courses'?",
         opties=["Ik doe boodschappen.", "Ik loop een wedstrijd.",
                 "Ik ga naar school.", "Ik maak mijn huiswerk."],
         antwoord=0,
         uitleg="'Faire les courses' is een vaste uitdrukking voor boodschappen doen. Losse betekenis van 'course' is wel 'wedloop'."),
    dict(type="waarofniet",
         vraag="'Faire la cuisine' betekent koken.",
         antwoord=True,
         uitleg="La cuisine is de keuken én het koken. 'Faire la cuisine' = koken."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'la salle de séjour'?",
         opties=["de woonkamer", "de badkamer", "de eetkamer", "de gang"],
         antwoord=0,
         uitleg="La salle de séjour of le salon is de woonkamer. La salle à manger is de eetkamer."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn meubels?",
         opties=["une armoire", "un canapé", "un lit", "un escalier"],
         antwoord=[0, 1, 2],
         uitleg="Kast, zetel en bed zijn meubels. Un escalier is een trap en hoort bij het gebouw."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'Il est en bois'?",
         opties=["Hij is van hout.", "Hij is in het bos.",
                 "Hij is aan het drinken.", "Hij is bezig."],
         antwoord=0,
         uitleg="'En' + materiaal zegt waarvan iets gemaakt is: en bois (hout), en verre (glas), en plastique."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn materialen?",
         opties=["le bois", "le verre", "le métal", "le vert"],
         antwoord=[0, 1, 2],
         uitleg="Hout, glas en metaal zijn materialen. 'Le vert' is de kleur groen; let op het verschil met 'le verre'."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'rond'?",
         opties=["rond", "recht", "smal", "hoog"],
         antwoord=0,
         uitleg="Rond = rond, carré = vierkant. Vormen komen voor in beschrijvingen van voorwerpen."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'carré'?",
         opties=["vierkant", "rond", "lang", "plat"],
         antwoord=0,
         uitleg="Un carré is een vierkant. Une table carrée is een vierkante tafel."),
    dict(type="invultekst",
         vraag="'De schoenen' schrijf je in het Frans als 'les ___'.",
         antwoord="chaussures",
         uitleg="Les chaussures = de schoenen. Une chaussette is een sok."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'Il porte un jean et des baskets'?",
         opties=["Hij draagt een jeans en sportschoenen.",
                 "Hij draagt een jas en laarzen.",
                 "Hij koopt een jeans.",
                 "Hij wast zijn jeans."],
         antwoord=0,
         uitleg="Des baskets zijn sportschoenen. Porter = dragen."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'se brosser les dents'?",
         opties=["zijn tanden poetsen", "zijn haar borstelen",
                 "zich aankleden", "zich wassen"],
         antwoord=0,
         uitleg="Se brosser les dents = zijn tanden poetsen. Het is wederkerend: je me brosse les dents."),
    dict(type="meerkeuze",
         vraag="Welke zinnen beschrijven een dagelijkse bezigheid?",
         opties=["Je prends le bus.", "Je fais mes devoirs.",
                 "Je range ma chambre.", "Je suis né en Belgique."],
         antwoord=[0, 1, 2],
         uitleg="De bus nemen, huiswerk maken en je kamer opruimen doe je vaak. Geboren worden gebeurt één keer."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'le frigo'?",
         opties=["de koelkast", "de vriezer", "de oven", "de kast"],
         antwoord=0,
         uitleg="Le frigo is de spreektaalvorm van 'le réfrigérateur', de koelkast."),
    dict(type="waarofniet",
         vraag="'Le déjeuner' is in Frankrijk het ontbijt.",
         antwoord=False,
         uitleg="Niet juist. Le déjeuner is het middagmaal. Het ontbijt is le petit-déjeuner."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'C'est délicieux'?",
         opties=["Het is heerlijk.", "Het is duur.", "Het is warm.", "Het is klaar."],
         antwoord=0,
         uitleg="Délicieux = heerlijk, overheerlijk. Een compliment aan tafel."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'un portefeuille'?",
         opties=["een portefeuille", "een deur", "een blad papier", "een venster"],
         antwoord=0,
         uitleg="Un portefeuille = een portefeuille. Het is samengesteld uit 'porter' (dragen) en 'feuille' (blad)."),
    dict(type="meerkeuze",
         vraag="Welk voordeel heeft het om samenstellingen te herkennen, zoals 'porte-monnaie'?",
         opties=["Je kan de betekenis raden uit de delen: iets dat geld draagt, dus een portemonnee.",
                 "Samenstellingen zijn altijd mannelijk.",
                 "Ze staan altijd in het meervoud.",
                 "Ze hoeven geen lidwoord."],
         antwoord=0,
         uitleg="De fiche noemt dat een leesstrategie: leid de betekenis af uit de manier waarop een woord gevormd is."),
]
