# -*- coding: utf-8 -*-
"""Een foto of afbeelding beschrijven.

Uit de vakfiche Frans 1ste graad A-stroom, onderdeel "Schrijven, spreken en
interactie": je legt iemand iets uit "op basis van foto's of afbeeldingen", en
je verwoordt schriftelijk je eigen beleving bij een tekst of beeld.

Op het examen krijg je daar een schrijfkader bij. Dit hoofdstuk oefent de
bouwstenen van zo'n beschrijving: er is / er zijn, waar iets staat, wie wat
draagt en doet, en hoe je zegt wat je dénkt te zien.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Je moet een foto beschrijven in het Frans. Met welke zin begin je het best?",
         opties=["Sur la photo, il y a une famille à table.",
                 "Bonjour, je m'appelle Lotte.",
                 "J'aime beaucoup les photos.",
                 "La photo est finie."],
         antwoord=0,
         uitleg="Begin met wat er te zien is: 'Sur la photo, il y a…' betekent 'Op de foto is / zijn er…'. De andere zinnen zeggen niets over het beeld."),
    dict(type="invultekst",
         vraag="'Er is' en 'er zijn' vertaal je in het Frans allebei met ___.",
         antwoord="il y a",
         uitleg="'Il y a' verandert niet: il y a un chien (er is een hond), il y a trois enfants (er zijn drie kinderen)."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'à gauche'?",
         opties=["links", "rechts", "in het midden", "achteraan"],
         antwoord=0,
         uitleg="À gauche = links, à droite = rechts. Denk aan 'gauche' en 'gaucher' (linkshandig)."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'à droite'?",
         opties=["rechts", "links", "boven", "onder"],
         antwoord=0,
         uitleg="À droite = rechts. 'Droit' betekent ook 'recht'."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'au milieu'?",
         opties=["in het midden", "vooraan", "buiten", "naast"],
         antwoord=0,
         uitleg="Au milieu = in het midden. Handig om het derde punt van een foto te benoemen, naast links en rechts."),
    dict(type="waarofniet",
         vraag="'Au premier plan' betekent 'op de voorgrond'.",
         antwoord=True,
         uitleg="Au premier plan = op de voorgrond, à l'arrière-plan = op de achtergrond."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'à l'arrière-plan'?",
         opties=["op de achtergrond", "op de voorgrond", "aan de zijkant", "in de verte links"],
         antwoord=0,
         uitleg="Arrière betekent 'achter'. À l'arrière-plan is dus op de achtergrond."),
    dict(type="meerkeuze",
         vraag="Welke zinnen kan je gebruiken om te zeggen wat je op de foto ziet?",
         opties=["Sur la photo, je vois trois enfants.",
                 "Il y a un chien devant la maison.",
                 "Au milieu, il y a une table.",
                 "Je voudrais un café, s'il vous plaît."],
         antwoord=[0, 1, 2],
         uitleg="'Je voudrais un café' bestel je in een café; dat zegt niets over een foto. De drie andere zinnen beschrijven wel wat er te zien is."),
    dict(type="meerkeuze",
         vraag="Wat staat er in 'Sur la photo, il y a deux enfants'?",
         opties=["Op de foto staan twee kinderen.",
                 "Op de foto staat één kind.",
                 "De foto is van twee kinderen.",
                 "Twee kinderen nemen een foto."],
         antwoord=0,
         uitleg="Il y a deux enfants = er zijn twee kinderen. Wie de foto genomen heeft, staat er niet."),
    dict(type="meerkeuze",
         vraag="Hoe schrijf je dat een meisje een rode jas draagt?",
         opties=["Elle porte un manteau rouge.",
                 "Elle port un manteau rouge.",
                 "Elle porte une manteau rouge.",
                 "Elle porte un rouge manteau."],
         antwoord=0,
         uitleg="Porter = dragen, dus 'elle porte'. Manteau is mannelijk (un manteau) en de kleur staat achter het naamwoord: un manteau rouge."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'devant la maison'?",
         opties=["voor het huis", "achter het huis", "in het huis", "naast het huis"],
         antwoord=0,
         uitleg="Devant = voor, derrière = achter, dans = in, à côté de = naast."),
    dict(type="meerkeuze",
         vraag="Welke woorden zeggen wáár iets staat op de foto?",
         opties=["devant", "derrière", "à côté de", "parce que"],
         antwoord=[0, 1, 2],
         uitleg="Devant, derrière en à côté de geven een plaats aan. 'Parce que' betekent 'omdat' en geeft een reden."),
    dict(type="waarofniet",
         vraag="In 'Les enfants jouent dans le jardin' spelen de kinderen in de tuin.",
         antwoord=True,
         uitleg="Jouer = spelen, le jardin = de tuin, dans = in."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'Ils sont contents'?",
         opties=["Ze zijn blij.", "Ze zijn moe.", "Ze zijn boos.", "Ze zijn ziek."],
         antwoord=0,
         uitleg="Content = blij, tevreden. Bij meer dan één jongen of een gemengde groep wordt dat contents."),
    dict(type="meerkeuze",
         vraag="Je bent niet zeker wat de mensen op de foto doen. Hoe zeg je dat voorzichtig?",
         opties=["Je pense qu'ils mangent.",
                 "Ils mangent, c'est sûr.",
                 "Ils ne mangent pas.",
                 "Mangez !"],
         antwoord=0,
         uitleg="'Je pense que…' betekent 'ik denk dat…'. Zo zeg je wat je vermoedt zonder te beweren dat het zeker is."),
    dict(type="invultekst",
         vraag="'Ik zie' vertaal je in het Frans met 'je ___'.",
         antwoord="vois",
         uitleg="Voir = zien: je vois, tu vois, il voit. 'Je vois un chat' is 'ik zie een kat'."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'Il fait beau sur la photo'?",
         opties=["Het is mooi weer op de foto.",
                 "De foto is mooi.",
                 "Hij maakt een mooie foto.",
                 "Hij is knap op de foto."],
         antwoord=0,
         uitleg="'Il fait beau' is een vaste uitdrukking voor het weer: het is mooi weer. Over een foto zeg je 'la photo est belle'."),
    dict(type="meerkeuze",
         vraag="Welke zinnen horen bij het beschrijven van een persoon op een foto?",
         opties=["Elle a les cheveux longs.",
                 "Il porte des lunettes.",
                 "Elle a l'air fatiguée.",
                 "La photo coûte dix euros."],
         antwoord=[0, 1, 2],
         uitleg="Haar, een bril en hoe iemand eruitziet horen bij een persoon. Wat een foto kost, hoort er niet bij."),
    dict(type="waarofniet",
         vraag="'Elle a l'air triste' betekent 'ze ziet er verdrietig uit'.",
         antwoord=True,
         uitleg="'Avoir l'air' + bijvoeglijk naamwoord betekent 'eruitzien als'. Handig als je niet zeker weet hoe iemand zich voelt."),
    dict(type="meerkeuze",
         vraag="Waarom is 'il y a' zo handig bij een foto?",
         opties=["Het blijft hetzelfde bij één ding en bij meerdere dingen.",
                 "Het betekent hetzelfde als 'je suis'.",
                 "Je hoeft er geen lidwoord bij te zetten.",
                 "Het staat altijd achteraan de zin."],
         antwoord=0,
         uitleg="Il y a un chien, il y a trois chiens: de vorm verandert niet. Daarmee kan je bijna elke foto beginnen."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Je krijgt een schrijfkader bij de foto. Wat doe je daarmee?",
         opties=["Je volgt de onderdelen die het kader vraagt, punt per punt.",
                 "Je mag het negeren, het is maar een voorbeeld.",
                 "Je schrijft het kader letterlijk over.",
                 "Je vertaalt het kader naar het Nederlands."],
         antwoord=0,
         uitleg="Het kader zegt wat je beschrijving moet bevatten. Wie alle onderdelen behandelt, haalt de taakvoltooiing binnen; dat is de eerste vereiste van de fiche."),
    dict(type="meerkeuze",
         vraag="In welke volgorde bouw je een beschrijving het best op?",
         opties=["eerst het geheel, dan de details, dan wat je ervan vindt",
                 "eerst wat je ervan vindt, dan het geheel",
                 "eerst de details, dan of je de foto mooi vindt",
                 "de volgorde maakt niet uit"],
         antwoord=0,
         uitleg="Zeg eerst waar de foto over gaat, dan wat je precies ziet, en pas daarna je mening. Dat is dezelfde inleiding-midden-slot die de fiche bij tekststructuur vraagt."),
    dict(type="meerkeuze",
         vraag="Welke zin zegt het duidelijkst wáár iemand staat?",
         opties=["À gauche, il y a une femme avec un enfant.",
                 "Il y a une femme.",
                 "C'est une photo.",
                 "La femme est là."],
         antwoord=0,
         uitleg="'À gauche' zet de vrouw op een plaats in het beeld. 'Là' betekent 'daar' en zegt niets als je het beeld niet ziet."),
    dict(type="meerkeuze",
         vraag="Welke uitdrukkingen gebruik je om voorzichtig te zeggen wat je denkt?",
         opties=["Je pense que…", "Il me semble que…", "Peut-être que…", "C'est certain."],
         antwoord=[0, 1, 2],
         uitleg="Je pense que (ik denk dat), il me semble que (het lijkt me dat) en peut-être que (misschien) houden een slag om de arm. 'C'est certain' zegt net dat het zeker is."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'Ils ont l'air de s'amuser'?",
         opties=["Ze lijken zich te amuseren.",
                 "Ze amuseren zich zeker.",
                 "Ze willen zich amuseren.",
                 "Ze amuseren zich niet."],
         antwoord=0,
         uitleg="'Avoir l'air de' + infinitief betekent 'lijken te'. Je zegt wat je vermoedt, niet wat vaststaat."),
    dict(type="meerkeuze",
         vraag="Welke zin beschrijft een handeling die bezig is?",
         opties=["Un homme lit un journal.",
                 "Un homme a lu un journal.",
                 "Un homme lira un journal.",
                 "Un homme voudrait un journal."],
         antwoord=0,
         uitleg="Voor wat er op een foto gebeurt, gebruik je de tegenwoordige tijd: 'un homme lit' (een man leest). Een foto toont één moment."),
    dict(type="waarofniet",
         vraag="Bij het beschrijven van een foto gebruik je meestal de tegenwoordige tijd.",
         antwoord=True,
         uitleg="Een foto laat één moment zien, dus beschrijf je dat in het présent: il y a, elle porte, ils jouent."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'au fond'?",
         opties=["achteraan", "vooraan", "opzij", "bovenaan"],
         antwoord=0,
         uitleg="Au fond = achteraan, helemaal in de diepte van het beeld. Het lijkt op à l'arrière-plan."),
    dict(type="meerkeuze",
         vraag="Welke zinnen kan je gebruiken om de sfeer van een foto te beschrijven?",
         opties=["L'ambiance est joyeuse.",
                 "Tout le monde sourit.",
                 "La scène est calme.",
                 "La photo mesure dix centimètres."],
         antwoord=[0, 1, 2],
         uitleg="Sfeer gaat over hoe het aanvoelt: vrolijk, iedereen lacht, rustig. De afmeting van een afdruk hoort daar niet bij."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'Ils sont en train de préparer le repas'?",
         opties=["Ze zijn de maaltijd aan het klaarmaken.",
                 "Ze hebben de maaltijd klaargemaakt.",
                 "Ze gaan de maaltijd klaarmaken.",
                 "Ze willen de maaltijd klaarmaken."],
         antwoord=0,
         uitleg="'Être en train de' + infinitief zegt dat iets nét bezig is. Precies wat een foto toont."),
    dict(type="meerkeuze",
         vraag="Je moet uitleggen hoe je een gerecht klaarmaakt op basis van foto's. Welke woorden wijzen de stappen aan?",
         opties=["d'abord", "ensuite", "enfin", "pourtant"],
         antwoord=[0, 1, 2],
         uitleg="D'abord (eerst), ensuite (daarna) en enfin (ten slotte) zetten de stappen op een rij. 'Pourtant' betekent 'nochtans' en geeft een tegenstelling aan."),
    dict(type="invultekst",
         vraag="'Eerst' schrijf je in het Frans als 'd'___'.",
         antwoord="abord",
         uitleg="D'abord = eerst. Daarna komen ensuite, puis en enfin."),
    dict(type="meerkeuze",
         vraag="Waarom zet je er beter geen dingen bij die je niet ziet?",
         opties=["Je beschrijft dan niet meer de foto, en je uitleg klopt niet.",
                 "Het is verboden om te fantaseren.",
                 "Franse zinnen worden dan te lang.",
                 "Je mag maar vijf zinnen schrijven."],
         antwoord=0,
         uitleg="De opdracht vraagt wat er op het beeld staat. Wat je niet ziet, mag je wel voorzichtig vermoeden met 'je pense que', maar niet als feit neerzetten."),
    dict(type="meerkeuze",
         vraag="Welke zin zegt wat je van de foto vindt?",
         opties=["Cette photo me plaît parce qu'elle est joyeuse.",
                 "Il y a quatre personnes.",
                 "À droite, il y a un vélo.",
                 "La scène se passe dans un parc."],
         antwoord=0,
         uitleg="'Me plaît' betekent 'bevalt me', en 'parce que' geeft de reden. De andere drie zinnen beschrijven alleen."),
    dict(type="waarofniet",
         vraag="'Parce que' gebruik je om een reden te geven bij je mening.",
         antwoord=True,
         uitleg="Parce que = omdat. De vakfiche vraagt uitdrukkelijk dat je uitlegt wáárom iets je aanspreekt."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'La scène se passe à la plage'?",
         opties=["Het tafereel speelt zich af op het strand.",
                 "Ze gaan naar het strand.",
                 "Het strand is op de foto getekend.",
                 "Ze wandelen langs het strand."],
         antwoord=0,
         uitleg="'Se passer' betekent 'zich afspelen'. Zo zeg je in één zin waar het beeld genomen is."),
    dict(type="meerkeuze",
         vraag="Welke zinnen beschrijven een persoon van top tot teen?",
         opties=["Il est grand et mince.",
                 "Elle a les cheveux courts et bruns.",
                 "Il porte un jean et des baskets.",
                 "Il habite à Namur."],
         antwoord=[0, 1, 2],
         uitleg="Gestalte, haar en kleren zie je op een foto. Waar iemand woont, kan je er niet aan zien."),
    dict(type="meerkeuze",
         vraag="Wat is de beste vertaling van 'Op de achtergrond zie je een kerk'?",
         opties=["À l'arrière-plan, on voit une église.",
                 "Au premier plan, on voit une église.",
                 "Devant, on voit une église.",
                 "On voit une église à gauche."],
         antwoord=0,
         uitleg="Achtergrond = arrière-plan. 'On voit' betekent 'men ziet' en is een vlotte manier om te zeggen wat er te zien is."),
    dict(type="meerkeuze",
         vraag="Je hebt maar een beperkte lengte gekregen. Wat laat je dan als eerste vallen?",
         opties=["details die niets toevoegen, zoals elke kleur apart",
                 "het onderwerp van de foto",
                 "waar het tafereel zich afspeelt",
                 "je mening met een reden"],
         antwoord=0,
         uitleg="De fiche vraagt dat je de opgegeven lengte respecteert. Het onderwerp, de plaats en je mening met reden zijn de kern; losse details mag je schrappen."),
    dict(type="meerkeuze",
         vraag="Waarom oefen je het beschrijven van een foto ook voor het schriftelijke deel?",
         opties=["Je moet op het examen schriftelijk iets uitleggen op basis van foto's of afbeeldingen.",
                 "Op het examen krijg je alleen foto's te zien.",
                 "Foto's beschrijven telt mee voor het leesexamen.",
                 "Het vervangt de woordenschat."],
         antwoord=0,
         uitleg="De vakfiche zegt bij schrijven: 'je legt iemand iets uit', met als voorbeeld uitleggen hoe je een gerecht klaarmaakt op basis van foto's of afbeeldingen."),
]
