# -*- coding: utf-8 -*-
"""Woordenschat: school, beroepen, sport en vrije tijd.

De woordvelden uit de vakfiche Frans 1ste graad A-stroom: onderwijs en
vorming, instructietaal, professionele wereld (beroepen), sport en ontspanning,
communicatie en multimedia.

De instructietaal is de taal van de opdrachten zelf. Wie 'cochez' of 'reliez'
niet begrijpt, verliest punten op een vraag die hij inhoudelijk wel kent.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat betekent 'l'école'?",
         opties=["de school", "de klas", "de les", "de leerling"],
         antwoord=0,
         uitleg="L'école = de school. Une classe is een klas, un cours een les."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'un élève'?",
         opties=["een leerling", "een leerkracht", "een examen", "een boek"],
         antwoord=0,
         uitleg="Un élève = een leerling. Un professeur (of un prof) is een leerkracht."),
    dict(type="meerkeuze",
         vraag="Welke woorden horen bij de school?",
         opties=["un cahier", "un cartable", "la récréation", "la cuisine"],
         antwoord=[0, 1, 2],
         uitleg="Schrift, boekentas en speeltijd horen bij de school. La cuisine is de keuken."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'les devoirs'?",
         opties=["het huiswerk", "de plichten van de leerkracht",
                 "de examens", "de vakken"],
         antwoord=0,
         uitleg="Les devoirs = het huiswerk. 'Faire ses devoirs' is zijn huiswerk maken."),
    dict(type="invultekst",
         vraag="'Een boek' schrijf je in het Frans als 'un ___'.",
         antwoord="livre",
         uitleg="Un livre = een boek. Une livre (vrouwelijk) is een pond; het lidwoord maakt het verschil."),
    dict(type="meerkeuze",
         vraag="In een opdracht staat 'Cochez la bonne réponse'. Wat moet je doen?",
         opties=["Het juiste antwoord aankruisen.", "Het antwoord opschrijven.",
                 "De zin vertalen.", "De vraag herhalen."],
         antwoord=0,
         uitleg="Cocher = aankruisen. Dit is instructietaal: de taal van de opdracht zelf."),
    dict(type="meerkeuze",
         vraag="Wat vraagt 'Complétez la phrase'?",
         opties=["Vul de zin aan.", "Vertaal de zin.", "Lees de zin voor.", "Schrap de zin."],
         antwoord=0,
         uitleg="Compléter = aanvullen, une phrase = een zin."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn instructietaal in een opdracht?",
         opties=["Soulignez", "Reliez", "Entourez", "Bonjour"],
         antwoord=[0, 1, 2],
         uitleg="Onderlijn, verbind en omcirkel zeggen wat je moet doen. 'Bonjour' is een groet."),
    dict(type="waarofniet",
         vraag="'Reliez' betekent dat je twee dingen met elkaar moet verbinden.",
         antwoord=True,
         uitleg="Relier = verbinden. Je trekt een lijn tussen wat bij elkaar hoort."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'un métier'?",
         opties=["een beroep", "een meter", "een materiaal", "een methode"],
         antwoord=0,
         uitleg="Un métier = een beroep, een vak. 'Quel est ton métier ?' is 'wat is je beroep?'."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn beroepen?",
         opties=["un boulanger", "une infirmière", "un facteur", "un ordinateur"],
         antwoord=[0, 1, 2],
         uitleg="Bakker, verpleegster en postbode zijn beroepen. Un ordinateur is een computer."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'une infirmière'?",
         opties=["een verpleegster", "een lerares", "een winkelbediende", "een dokter"],
         antwoord=0,
         uitleg="Une infirmière = een verpleegster, un infirmier = een verpleger."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'Je joue au football'?",
         opties=["Ik voetbal.", "Ik kijk naar voetbal.",
                 "Ik speel met een bal.", "Ik hou van voetbal."],
         antwoord=0,
         uitleg="Jouer à + sport betekent die sport beoefenen: je joue au tennis, au basket."),
    dict(type="waarofniet",
         vraag="Bij een sport gebruik je 'jouer à', bij een muziekinstrument 'jouer de'.",
         antwoord=True,
         uitleg="Je joue au foot, maar je joue du piano. Dat verschil is een klassieke valkuil."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn sporten?",
         opties=["la natation", "le vélo", "le basket", "la lecture"],
         antwoord=[0, 1, 2],
         uitleg="Zwemmen, fietsen en basketbal zijn sporten. La lecture is het lezen."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'la natation'?",
         opties=["het zwemmen", "het wandelen", "het dansen", "het lopen"],
         antwoord=0,
         uitleg="Nager = zwemmen, la natation = het zwemmen. La marche is het wandelen."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'mon temps libre'?",
         opties=["mijn vrije tijd", "mijn lange tijd", "mijn werktijd", "mijn tijdschrift"],
         antwoord=0,
         uitleg="Libre = vrij. Le temps libre is de vrije tijd."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'un ordinateur'?",
         opties=["een computer", "een bestelling", "een agenda", "een rekenmachine"],
         antwoord=0,
         uitleg="Un ordinateur = een computer. Un portable kan een gsm of een laptop zijn."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'envoyer un message'?",
         opties=["een bericht sturen", "een bericht lezen",
                 "een bericht wissen", "een bericht bewaren"],
         antwoord=0,
         uitleg="Envoyer = sturen, un message = een bericht."),
    dict(type="meerkeuze",
         vraag="Waarom is instructietaal zo belangrijk op het examen?",
         opties=["Als je de opdracht niet begrijpt, verlies je punten op leerstof die je wel kent.",
                 "Instructietaal komt alleen in het luisterdeel voor.",
                 "Instructietaal is de moeilijkste woordenschat.",
                 "Instructietaal staat in het Nederlands."],
         antwoord=0,
         uitleg="De fiche zet instructietaal daarom bij de woordvelden die je moet kennen."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat vraagt 'Justifiez votre réponse'?",
         opties=["Leg uit waarom je dat antwoordt.", "Verbeter je antwoord.",
                 "Herhaal je antwoord.", "Vertaal je antwoord."],
         antwoord=0,
         uitleg="Justifier = verantwoorden. Je geeft dus een reden bij je antwoord, meestal met 'parce que'."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'Vrai ou faux ?'",
         opties=["Waar of niet waar?", "Goed of slecht?", "Veel of weinig?", "Eerst of daarna?"],
         antwoord=0,
         uitleg="Vrai = waar, faux = fout. Dit vraagtype komt op het examen voor."),
    dict(type="meerkeuze",
         vraag="Welke opdrachten vragen dat je zelf iets schrijft?",
         opties=["Rédigez un court texte.", "Complétez la phrase.",
                 "Répondez aux questions.", "Cochez la bonne case."],
         antwoord=[0, 1, 2],
         uitleg="Opstellen, aanvullen en antwoorden vragen eigen tekst. Een vakje aankruisen niet."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'un emploi du temps'?",
         opties=["een lessenrooster", "een werkaanbieding",
                 "een tijdschrift", "een examenrooster"],
         antwoord=0,
         uitleg="Un emploi du temps = een uurrooster. Un emploi alleen is een baan."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'la note'?",
         opties=["het punt of cijfer", "het briefje", "de nota", "het notitieboek"],
         antwoord=0,
         uitleg="Une bonne note is een goed punt. In een andere context kan 'note' ook nota of muzieknoot betekenen."),
    dict(type="waarofniet",
         vraag="'Une matière' kan een vak op school betekenen.",
         antwoord=True,
         uitleg="Ma matière préférée = mijn lievelingsvak. Het woord betekent ook 'stof' of 'materie'."),
    dict(type="meerkeuze",
         vraag="Welke woorden horen bij een beroep in de zorg of de winkel?",
         opties=["un vendeur", "un médecin", "un pharmacien", "un cahier"],
         antwoord=[0, 1, 2],
         uitleg="Verkoper, arts en apotheker zijn beroepen. Un cahier is een schrift."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'Il travaille dans un bureau'?",
         opties=["Hij werkt op een kantoor.", "Hij werkt in een winkel.",
                 "Hij werkt in een fabriek.", "Hij werkt thuis."],
         antwoord=0,
         uitleg="Un bureau is een kantoor én een bureau (het meubel). De context beslist."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'Je fais partie d'un club'?",
         opties=["Ik ben lid van een club.", "Ik richt een club op.",
                 "Ik verlaat een club.", "Ik bezoek een club."],
         antwoord=0,
         uitleg="'Faire partie de' = deel uitmaken van, lid zijn van."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'l'entraînement'?",
         opties=["de training", "de wedstrijd", "de rust", "de ploeg"],
         antwoord=0,
         uitleg="S'entraîner = trainen. Un match is een wedstrijd, une équipe een ploeg."),
    dict(type="meerkeuze",
         vraag="Welke woorden horen bij een sportwedstrijd?",
         opties=["une équipe", "un match", "gagner", "un cartable"],
         antwoord=[0, 1, 2],
         uitleg="Ploeg, wedstrijd en winnen horen bij sport. Un cartable is een boekentas."),
    dict(type="invultekst",
         vraag="'Winnen' schrijf je in het Frans als ___.",
         antwoord="gagner",
         uitleg="Gagner = winnen, perdre = verliezen."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'perdre'?",
         opties=["verliezen", "winnen", "spelen", "stoppen"],
         antwoord=0,
         uitleg="Perdre = verliezen. 'J'ai perdu mes clés' betekent dat je je sleutels kwijt bent."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'télécharger'?",
         opties=["downloaden", "opbellen", "uitzenden", "doorsturen"],
         antwoord=0,
         uitleg="Télécharger = downloaden. Un téléchargement is een download. Iets naar het internet zetten is 'téléverser'."),
    dict(type="waarofniet",
         vraag="'Un réseau social' is een sociaal netwerk.",
         antwoord=True,
         uitleg="Un réseau = een netwerk. Op sociale media reageer je op een discussie; dat is een van de schrijfopdrachten uit de fiche."),
    dict(type="meerkeuze",
         vraag="Welke woorden horen bij communicatie en multimedia?",
         opties=["un écran", "une application", "un mot de passe", "un fauteuil"],
         antwoord=[0, 1, 2],
         uitleg="Scherm, app en wachtwoord horen bij multimedia. Un fauteuil is een zetel."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'Je m'intéresse à la musique'?",
         opties=["Ik heb interesse in muziek.", "Ik maak muziek.",
                 "Ik studeer muziek.", "Ik hou niet van muziek."],
         antwoord=0,
         uitleg="'S'intéresser à' = zich interesseren voor. Wederkerend, dus je m'intéresse."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'un spectacle'?",
         opties=["een voorstelling", "een bril", "een uitzicht", "een spektakelstuk in een krant"],
         antwoord=0,
         uitleg="Un spectacle = een voorstelling of show. 'Des lunettes' zijn een bril."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'Quel est ton passe-temps préféré ?'",
         opties=["Wat is je favoriete tijdverdrijf?", "Wat is je lievelingsvak?",
                 "Wanneer heb je tijd?", "Wat doe je in de vakantie?"],
         antwoord=0,
         uitleg="Un passe-temps is een hobby, préféré betekent favoriet."),
    dict(type="meerkeuze",
         vraag="Je leest 'Répondez en français'. Wat mag je dan niet doen?",
         opties=["In het Nederlands antwoorden.", "Een korte zin schrijven.",
                 "Een woordenboek gebruiken.", "Je antwoord nalezen."],
         antwoord=0,
         uitleg="'En français' betekent in het Frans. Een antwoord in de verkeerde taal levert geen punten op, hoe juist het ook is."),
]
