# -*- coding: utf-8 -*-
"""Biologie: leven en ecologie — 🌱 Start, 5de en 6de leerjaar."""

VRAGEN = [
    dict(type="waarofniet",
         vraag="Planten maken hun voedsel met behulp van licht.",
         antwoord=True,
         uitleg="Daarvoor gebruiken ze ook water en koolstofdioxide."),
    dict(type="meerkeuze",
         vraag="Hoe noem je het proces waarbij planten suiker maken uit water, koolstofdioxide en licht?",
         opties=["verbranding", "fotosynthese", "vertering", "verdamping"],
         antwoord=1,
         uitleg="Foto betekent licht, synthese betekent samenstellen."),
    dict(type="meerkeuze",
         vraag="Wat is een voedselketen?",
         opties=["een rij winkels", "wie wat eet in de natuur", "een soort plant", "een deel van het skelet"],
         antwoord=1,
         uitleg="Bijvoorbeeld: gras wordt gegeten door een konijn, en het konijn door een vos."),
    dict(type="waarofniet",
         vraag="Een kikker is een zoogdier.",
         antwoord=False,
         uitleg="Een kikker is een amfibie: hij legt eieren in het water."),
    dict(type="meerkeuze",
         vraag="Wat hebben alle zoogdieren gemeen?",
         opties=["ze leggen eieren", "ze geven melk aan hun jongen", "ze hebben veren", "ze leven in het water"],
         antwoord=1,
         uitleg="Zoogdieren zogen hun jongen, daar komt de naam vandaan."),
    dict(type="meerkeuze",
         vraag="Hoe noem je de plaats waar een dier leeft, met alles wat het daar nodig heeft?",
         opties=["de leefomgeving", "de voedselketen", "het skelet", "de celkern"],
         antwoord=0,
         uitleg="In zijn leefomgeving vindt een dier voedsel, water en beschutting."),
    dict(type="waarofniet",
         vraag="Bijen helpen bij de bestuiving van bloemen.",
         antwoord=True,
         uitleg="Ze dragen stuifmeel van de ene bloem naar de andere."),
    dict(type="meerkeuze",
         vraag="Welk deel van de plant neemt water op uit de grond?",
         opties=["het blad", "de bloem", "de wortel", "de stengel"],
         antwoord=2,
         uitleg="De wortels halen water en voedingsstoffen uit de bodem."),
    dict(type="waarofniet",
         vraag="Een spin is een insect.",
         antwoord=False,
         uitleg="Een spin heeft acht poten; insecten hebben er zes."),
    dict(type="invultekst",
         vraag="Hoe noem je dieren die alleen planten eten?",
         antwoord="planteneters",
         uitleg="Vleeseters eten vlees, alleseters eten allebei."),
    dict(type="meerkeuze",
         vraag="Waarom laten bomen in de herfst hun bladeren vallen?",
         opties=["om water te sparen in de koude maanden", "omdat ze ziek zijn", "omdat het te warm wordt", "om lichter te worden"],
         antwoord=0,
         uitleg="Zonder bladeren verdampt de boom veel minder water in de winter."),
    dict(type="meerkeuze",
         vraag="Wat gebeurt er bij een metamorfose van rups tot vlinder?",
         opties=["het dier verandert helemaal van vorm", "het dier wordt alleen groter", "het dier verandert van kleur", "er verandert niets"],
         antwoord=0,
         uitleg="Via de pop verandert de rups volledig van lichaamsbouw."),
    dict(type="meerkeuze",
         vraag="Waarom zijn regenwormen goed voor de grond?",
         opties=["ze maken de grond los en luchtig", "ze eten plagen op", "ze maken water", "ze geven licht"],
         antwoord=0,
         uitleg="Door hun gangen komt er lucht en water bij de wortels."),
    dict(type="waarofniet",
         vraag="Zonder planten zou er geen zuurstof in de lucht zijn.",
         antwoord=True,
         uitleg="Planten geven zuurstof af bij de fotosynthese."),
    dict(type="invultekst",
         vraag="Hoe noem je het orgaan waarmee vissen ademen onder water?",
         antwoord="kieuwen",
         uitleg="Kieuwen halen zuurstof uit het water."),
]

# --- bijgekomen op 23 september 2026, om het hoofdstuk op 40 vragen te brengen ---

VRAGEN += [
    dict(type="meerkeuze",
         vraag="Wat is een producent in een voedselketen?",
         opties=["een plant, die zelf voedsel maakt uit licht", "een dier dat planten eet",
                 "een dier dat andere dieren eet", "een schimmel die dode resten afbreekt"],
         antwoord=0,
         uitleg="Een voedselketen begint altijd bij een producent: alleen planten maken hun eigen voedsel."),
    dict(type="meerkeuze",
         vraag="Hoe noem je dieren die zowel planten als dieren eten?",
         opties=["alleseters of omnivoren", "planteneters of herbivoren",
                 "vleeseters of carnivoren", "afbrekers"],
         antwoord=0,
         uitleg="De mens is er ook een. Een beer en een varken evengoed."),
    dict(type="invultekst",
         vraag="Hoe noem je met één woord de dieren die alleen vlees eten?",
         antwoord="carnivoren",
         uitleg="Een vos, een leeuw en een havik zijn carnivoren. Planteneters heten herbivoren."),
    dict(type="meerkeuze",
         vraag="Wat doen afbrekers zoals schimmels, bacteriën en pissebedden?",
         opties=["ze breken dode planten en dieren af tot voedingsstoffen in de bodem",
                 "ze eten levende planten op", "ze maken voedsel uit zonlicht",
                 "ze jagen op kleine dieren"],
         antwoord=0,
         uitleg="Zonder afbrekers zou een bos onder zijn eigen bladeren bedolven raken, en zou er geen voeding terugkomen in de grond."),
    dict(type="waarofniet",
         vraag="Een voedselweb is een geheel van voedselketens die in elkaar haken.",
         antwoord=True,
         uitleg="Klopt. In het echt eet bijna geen enkel dier maar één ding, dus de ketens lopen door elkaar."),
    dict(type="meerkeuze",
         vraag="Wat betekent biodiversiteit?",
         opties=["hoeveel verschillende soorten er in een gebied leven",
                 "hoeveel dieren er in totaal leven", "hoe groot een natuurgebied is",
                 "hoeveel bomen er staan"],
         antwoord=0,
         uitleg="Het gaat om de verscheidenheid, niet om het aantal. Honderd konijnen zijn minder divers dan tien verschillende soorten."),
    dict(type="waarofniet",
         vraag="Leven er in een gebied meer verschillende soorten, dan kan de natuur een tegenslag beter opvangen.",
         antwoord=True,
         uitleg="Klopt. Valt één soort weg, dan zijn er andere die haar taak kunnen overnemen. Bij weinig soorten stort de boel sneller in."),
    dict(type="invultekst",
         vraag="Hoe noem je een dier dat een ruggengraat heeft?",
         antwoord="gewerveld",
         uitleg="Zoogdieren, vogels, vissen, reptielen en amfibieën zijn gewervelde dieren. Insecten, spinnen en wormen niet."),
    dict(type="invultekst",
         vraag="Hoeveel poten heeft een insect? Antwoord met een getal.",
         antwoord="6",
         uitleg="Zes poten en drie lichaamsdelen: kop, borststuk en achterlijf."),
    dict(type="invultekst",
         vraag="Hoeveel poten heeft een spin? Antwoord met een getal.",
         antwoord="8",
         uitleg="Acht poten en twee lichaamsdelen. Daarom is een spin geen insect."),
    dict(type="waarofniet",
         vraag="Alle vogels kunnen vliegen.",
         antwoord=False,
         uitleg="Niet juist. Een struisvogel en een pinguïn zijn vogels, maar ze vliegen niet. De pinguïn gebruikt zijn vleugels om te zwemmen."),
    dict(type="meerkeuze",
         vraag="Wat hebben vogels dat geen enkele andere diergroep heeft?",
         opties=["veren", "vleugels", "een snavel", "eieren"],
         antwoord=0,
         uitleg="Vleermuizen en insecten hebben ook vleugels, en veel dieren leggen eieren. Veren heeft alleen een vogel."),
    dict(type="meerkeuze",
         vraag="Waaraan herken je een reptiel, zoals een hagedis of een slang?",
         opties=["een droge huid met schubben", "een vacht met haren",
                 "een natte, gladde huid", "veren"],
         antwoord=0,
         uitleg="Reptielen hebben schubben en zijn koudbloedig: ze warmen zich op in de zon."),
    dict(type="meerkeuze",
         vraag="Wat is bijzonder aan een amfibie, zoals een kikker of een salamander?",
         opties=["het leeft eerst in het water en later ook op het land",
                 "het leeft zijn hele leven onder water", "het heeft schubben",
                 "het is een zoogdier"],
         antwoord=0,
         uitleg="Amfibie betekent letterlijk 'dubbelleven'. De eitjes en de larven zitten in het water."),
    dict(type="invultekst",
         vraag="Hoe noem je de winterrust van een egel of een vleermuis?",
         antwoord="winterslaap",
         uitleg="Hun lichaam koelt af en hun hart klopt veel trager, zodat ze bijna geen voedsel nodig hebben."),
    dict(type="meerkeuze",
         vraag="Waarom trekken sommige vogels in de herfst naar het zuiden?",
         opties=["omdat er hier in de winter te weinig voedsel te vinden is",
                 "omdat ze de kou niet verdragen", "omdat ze daar geboren zijn",
                 "omdat ze de weg kwijt zijn"],
         antwoord=0,
         uitleg="Insecteneters vertrekken, want insecten verdwijnen in de winter. Vogels die zaden eten, kunnen blijven."),
    dict(type="meerkeuze",
         vraag="Wat is camouflage?",
         opties=["een kleur of vorm waardoor een dier opgaat in zijn omgeving",
                 "een geluid om soortgenoten te waarschuwen", "een geur om vijanden weg te jagen",
                 "een schuilplaats onder de grond"],
         antwoord=0,
         uitleg="Een sneeuwhaas wordt wit in de winter, een rups lijkt op een takje. Zo zien jager én prooi elkaar minder snel."),
    dict(type="meerkeuze",
         vraag="Wat gebeurt er bij de bestuiving van een bloem?",
         opties=["stuifmeel van de meeldraden komt op de stamper terecht",
                 "de bloem neemt water op uit de grond", "het blad maakt suiker uit licht",
                 "de bloem laat haar blaadjes vallen"],
         antwoord=0,
         uitleg="Pas daarna kunnen er zaadjes en vruchten groeien. Insecten en de wind brengen dat stuifmeel over."),
    dict(type="meerkeuze",
         vraag="Hoe verspreiden planten hun zaden?",
         opties=["met de wind, met water, of doordat dieren ze meenemen",
                 "alleen met de wind", "door ze zelf te verplaatsen",
                 "planten verspreiden hun zaden niet"],
         antwoord=0,
         uitleg="Een paardenbloem gebruikt de wind, een klit haakt vast in een vacht, en een vogel eet een bes en poept de pit verderop uit."),
    dict(type="invultekst",
         vraag="Welk gas geven planten af bij de fotosynthese?",
         antwoord="zuurstof",
         uitleg="Ze nemen koolstofdioxide op en geven zuurstof af. Precies omgekeerd aan wat wij bij het ademen doen."),
    dict(type="meerkeuze",
         vraag="Wat is een ecosysteem?",
         opties=["alles wat in één gebied samenleeft, samen met de bodem, het water en het weer",
                 "alleen de dieren van een gebied", "alleen de planten van een gebied",
                 "een gebied waar mensen niet mogen komen"],
         antwoord=0,
         uitleg="Een vijver, een bos en een duin zijn ecosystemen. Alles erin hangt aan elkaar vast."),
    dict(type="waarofniet",
         vraag="Schimmels zijn planten.",
         antwoord=False,
         uitleg="Niet juist. Schimmels vormen een eigen groep. Ze hebben geen bladgroen en maken dus geen eigen voedsel; ze halen het uit dode of levende resten."),
    dict(type="meerkeuze",
         vraag="Waarom laat een boswachter dood hout gewoon in het bos liggen?",
         opties=["omdat er insecten en schimmels in leven die het afbreken tot voeding voor de bodem",
                 "omdat opruimen te veel werk is", "omdat dood hout niet brandt",
                 "omdat het er mooi uitziet"],
         antwoord=0,
         uitleg="Een dode boom herbergt vaak meer leven dan een levende. Wat vergaat, voedt de volgende bomen."),
    dict(type="meerkeuze",
         vraag="Wat betekent het dat een diersoort uitsterft?",
         opties=["er leeft geen enkel dier van die soort meer, en dat is niet meer terug te draaien",
                 "de dieren zijn verhuisd naar een ander land", "de soort slaapt een winter over",
                 "er zijn er nog maar weinig van"],
         antwoord=0,
         uitleg="Uitgestorven is voorgoed. Daarom proberen mensen soorten te beschermen vóór het zover komt."),
    dict(type="meerkeuze",
         vraag="Wat kan je zelf doen om meer leven in je tuin te krijgen?",
         opties=["bloemen laten bloeien en een hoekje laten verwilderen",
                 "het gras elke week heel kort maaien", "alle insecten wegjagen",
                 "alles met tegels bedekken"],
         antwoord=0,
         uitleg="Een rommelig hoekje met bloemen, een takkenhoop en wat water is voor insecten en vogels meer waard dan een perfect gazon."),
]
