# -*- coding: utf-8 -*-
"""Commerciële documenten en de documentenstroom.

Van de vakfiche economie en bedrijfswetenschappen 2DU (2027): de
commerciële documenten herkennen en hun doel toelichten (prijsaanvraag,
offerte, bestelbon, orderbevestiging, leverbon, factuur, creditnota), ze
controleren op onderlinge overeenstemming en narekenen, ze zelf opstellen,
en de documentenstroom bij aankopen of verkopen schematisch voorstellen.

Deel 1 zijn de documenten.
Deel 2 is de stroom en de controle.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is een prijsaanvraag?",
         opties=["vragen wat iets kost",
                 "zeggen wat iets kost",
                 "bestellen bij iemand",
                 "leveren aan iemand"],
         antwoord=0,
         uitleg="De klant vraagt aan een of meer leveranciers wat ze voor iets rekenen."),
    dict(type="meerkeuze",
         vraag="Wat is een offerte?",
         opties=["een prijsvoorstel",
                 "een bestelling ervan",
                 "een levering ervan",
                 "een betaling ervan"],
         antwoord=0,
         uitleg="Het antwoord van de leverancier op een prijsaanvraag."),
    dict(type="meerkeuze",
         vraag="Wat is een bestelbon?",
         opties=["de klant bestelt",
                 "de leverancier levert",
                 "de klant betaalt",
                 "de bank schrijft"],
         antwoord=0,
         uitleg="De klant zet schriftelijk wat hij wil, in welke aantallen en aan welke prijs."),
    dict(type="meerkeuze",
         vraag="Wat is een orderbevestiging?",
         opties=["de leverancier bevestigt",
                 "de klant bestelt ervan",
                 "de bank betaalt ervan",
                 "de klant klaagt ervan"],
         antwoord=0,
         uitleg="Hij laat weten dat de bestelling binnen is en wanneer hij levert."),
    dict(type="invultekst",
         vraag="Welk document stuurt de leverancier als antwoord op een prijsaanvraag? Eén woord.",
         antwoord=["offerte", "een offerte", "prijsopgave"],
         uitleg="Een offerte."),
    dict(type="waarofniet",
         vraag="De leverbon gaat mee met de goederen.",
         antwoord=True,
         uitleg="Zo kan de ontvanger meteen nagaan of alles er is."),
    dict(type="waarofniet",
         vraag="Een leverbon vermeldt altijd de prijzen.",
         antwoord=False,
         uitleg="Een leverbon noemt vooral de aantallen; de bedragen staan op de factuur."),
    dict(type="meerkeuze",
         vraag="Wat is een leverbon?",
         opties=["wat er geleverd is",
                 "wat er betaald is",
                 "wat er bestelt is",
                 "wat er geboekt is"],
         antwoord=0,
         uitleg="De lijst van goederen die met de levering meekomt."),
    dict(type="meerkeuze",
         vraag="Wat is een factuur?",
         opties=["de vraag om te betalen",
                 "de vraag om te leveren",
                 "de vraag om een prijs",
                 "de vraag om een offerte"],
         antwoord=0,
         uitleg="Met de bedragen, de btw en de betalingsvoorwaarden erop."),
    dict(type="meerkeuze",
         vraag="Wat is een creditnota?",
         opties=["een factuur rechtzetten",
                 "een bestelling plaatsen",
                 "een levering melden",
                 "een prijs opvragen"],
         antwoord=0,
         uitleg="Bij een retour, een korting achteraf of een fout op de factuur."),
    dict(type="meerkeuze",
         vraag="Welke commerciële documenten noemt de vakfiche?",
         opties=["de prijsaanvraag en de offerte",
                 "de bestelbon en de orderbevestiging",
                 "de leverbon en de factuur",
                 "de loonfiche van de werknemer"],
         antwoord=[0, 1, 2],
         uitleg="En de creditnota. De loonfiche is een personeelsdocument."),
    dict(type="meerkeuze",
         vraag="Wie maakt de factuur?",
         opties=["de verkoper",
                 "de koper ervan",
                 "de bank ervan",
                 "de post ervan"],
         antwoord=0,
         uitleg="Voor hem is het een verkoopfactuur, voor de koper een aankoopfactuur."),
    dict(type="waarofniet",
         vraag="Een offerte bindt de leverancier aan zijn prijs zolang ze geldig is.",
         antwoord=True,
         uitleg="Daarom staat er een geldigheidsduur op."),
    dict(type="waarofniet",
         vraag="Een bestelbon en een factuur zijn hetzelfde document.",
         antwoord=False,
         uitleg="De bestelbon komt van de koper, de factuur van de verkoper."),
    dict(type="invultekst",
         vraag="Welk document stuurt een verkoper om een fout op een factuur recht te zetten? Hoogstens drie woorden.",
         antwoord=["creditnota", "een creditnota", "kredietnota"],
         uitleg="Een creditnota."),
    dict(type="meerkeuze",
         vraag="Wat is het doel van een orderbevestiging?",
         opties=["zekerheid geven",
                 "de prijs verhogen",
                 "de levering stoppen",
                 "de factuur boeken"],
         antwoord=0,
         uitleg="De klant weet dat zijn bestelling aangekomen is en wanneer ze komt."),
    dict(type="meerkeuze",
         vraag="Wat staat er verplicht op een factuur?",
         opties=["de datum en het nummer",
                 "de gegevens van beide partijen",
                 "de btw en het totaal",
                 "de naam van de chauffeur"],
         antwoord=[0, 1, 2],
         uitleg="En de omschrijving van de goederen of diensten."),
    dict(type="meerkeuze",
         vraag="Welk document vraagt de klant als hij eerst de prijs wil kennen?",
         opties=["een prijsaanvraag",
                 "een leverbon ervan",
                 "een creditnota ervan",
                 "een factuur ervan"],
         antwoord=0,
         uitleg="Vaak bij meerdere leveranciers, om te kunnen vergelijken."),
    dict(type="meerkeuze",
         vraag="Welke documenten gaan van de klant naar de leverancier?",
         opties=["de prijsaanvraag",
                 "de bestelbon",
                 "de klacht bij een fout",
                 "de factuur"],
         antwoord=[0, 1, 2],
         uitleg="De factuur komt de andere richting uit."),
    dict(type="invultekst",
         vraag="Welk document gaat mee met de goederen? Eén woord.",
         antwoord=["leverbon", "een leverbon", "leveringsbon"],
         uitleg="De leverbon."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is de documentenstroom bij een aankoop?",
         opties=["de volgorde van papieren",
                 "de prijs van de goederen",
                 "de route van de wagen",
                 "de winst van de zaak"],
         antwoord=0,
         uitleg="Welk document wanneer gemaakt wordt, en door wie."),
    dict(type="meerkeuze",
         vraag="Welk document komt eerst bij een aankoop?",
         opties=["de prijsaanvraag",
                 "de factuur ervan",
                 "de leverbon ervan",
                 "de creditnota ervan"],
         antwoord=0,
         uitleg="Eerst weten wat het kost, dan pas bestellen."),
    dict(type="meerkeuze",
         vraag="Welk document komt als laatste bij een aankoop?",
         opties=["de factuur",
                 "de offerte ervan",
                 "de bestelbon ervan",
                 "de prijsaanvraag"],
         antwoord=0,
         uitleg="Tenzij er nog een creditnota volgt omdat er iets terug moet."),
    dict(type="meerkeuze",
         vraag="Waarom vergelijk je de leverbon met de bestelbon?",
         opties=["om te zien of alles er is",
                 "om de prijs te verhogen",
                 "om de btw te berekenen",
                 "om reclame te maken"],
         antwoord=0,
         uitleg="Wat besteld werd, moet ook geleverd zijn, in dezelfde aantallen."),
    dict(type="invultekst",
         vraag="Hoe noem je het nagaan of twee documenten met elkaar kloppen? Eén woord.",
         antwoord=["controleren", "nakijken", "vergelijken"],
         uitleg="Controleren op onderlinge overeenstemming."),
    dict(type="waarofniet",
         vraag="Een factuur controleer je tegen de bestelbon en de leverbon.",
         antwoord=True,
         uitleg="Zo zie je of je betaalt voor wat je besteld hebt en ook gekregen hebt."),
    dict(type="waarofniet",
         vraag="Een factuur mag je zonder controle boeken en betalen.",
         antwoord=False,
         uitleg="Een fout die je niet opmerkt, betaal je zelf."),
    dict(type="meerkeuze",
         vraag="Wat doe je als de factuur een hoger bedrag vermeldt dan de offerte?",
         opties=["de leverancier contacteren",
                 "gewoon betalen ervan",
                 "de factuur wissen ervan",
                 "de goederen houden"],
         antwoord=0,
         uitleg="Je vraagt uitleg en zo nodig een creditnota."),
    dict(type="meerkeuze",
         vraag="Wat betekent documenten narekenen?",
         opties=["de bedragen nagaan",
                 "de kleuren nagaan",
                 "de namen nagaan",
                 "de datums wissen"],
         antwoord=0,
         uitleg="De aantallen maal de prijzen, de kortingen, de btw en het totaal."),
    dict(type="meerkeuze",
         vraag="Welke afdeling krijgt de factuur van de leverancier?",
         opties=["de boekhouding",
                 "de marketing ervan",
                 "de IT-afdeling ervan",
                 "de HR-afdeling ervan"],
         antwoord=0,
         uitleg="Zij boekt de factuur en volgt de betaling op."),
    dict(type="meerkeuze",
         vraag="Wat controleer je op een inkomende factuur?",
         opties=["de geleverde aantallen",
                 "de afgesproken prijzen",
                 "de berekening van de btw",
                 "de kleur van het logo"],
         antwoord=[0, 1, 2],
         uitleg="En of de kortingen uit de offerte er echt op staan."),
    dict(type="meerkeuze",
         vraag="Welke afdelingen zijn betrokken bij de documentenstroom van een aankoop?",
         opties=["aankoop, logistiek, boekhouding",
                 "enkel de boekhouding ervan",
                 "enkel de marketing ervan",
                 "enkel de IT-afdeling ervan"],
         antwoord=0,
         uitleg="De aankoop bestelt, de logistiek ontvangt, de boekhouding boekt en betaalt."),
    dict(type="waarofniet",
         vraag="Een goede controle van documenten voorkomt dat je te veel betaalt.",
         antwoord=True,
         uitleg="En ze voorkomt dat je een levering betaalt die nooit is aangekomen."),
    dict(type="waarofniet",
         vraag="De documentenstroom bij een verkoop is helemaal anders dan bij een aankoop.",
         antwoord=False,
         uitleg="Het zijn dezelfde documenten; enkel je rol wisselt van koper naar verkoper."),
    dict(type="invultekst",
         vraag="Welk document maakt de verkoper als de klant goederen terugstuurt? Hoogstens drie woorden.",
         antwoord=["creditnota", "een creditnota", "kredietnota"],
         uitleg="Een creditnota."),
    dict(type="meerkeuze",
         vraag="Wat is het doel van documenten controleren volgens de vakfiche?",
         opties=["kwaliteit afleveren",
                 "tijd verliezen ervan",
                 "papier sparen ervan",
                 "sneller verkopen"],
         antwoord=0,
         uitleg="Wie zijn documenten laat kloppen, levert werk af waarop de klant kan bouwen."),
    dict(type="meerkeuze",
         vraag="Wat hoort bij een correct opgesteld commercieel document?",
         opties=["de juiste gegevens",
                 "een duidelijke datum",
                 "een kloppende berekening",
                 "een mooie achtergrondkleur"],
         antwoord=[0, 1, 2],
         uitleg="En een nummer, zodat je het later terugvindt."),
    dict(type="meerkeuze",
         vraag="Wat zet je in een schema van de documentenstroom?",
         opties=["wie wat wanneer stuurt",
                 "hoeveel winst er is",
                 "wie het meest verdient",
                 "welke kleur elk heeft"],
         antwoord=0,
         uitleg="Met pijlen tussen de klant, de leverancier en de betrokken afdelingen."),
    dict(type="meerkeuze",
         vraag="Welk verband bestaat er tussen de documenten?",
         opties=["de offerte volgt op de prijsaanvraag",
                 "de bestelbon volgt op de offerte",
                 "de factuur volgt op de levering",
                 "de prijsaanvraag volgt op de factuur"],
         antwoord=[0, 1, 2],
         uitleg="De prijsaanvraag staat helemaal vooraan, niet achteraan."),
    dict(type="invultekst",
         vraag="Hoe noem je het overzicht van welke documenten in welke orde gaan? Eén woord.",
         antwoord=["documentenstroom", "de documentenstroom", "documentstroom"],
         uitleg="De documentenstroom."),
]
