# -*- coding: utf-8 -*-
"""Transport, expeditie en logistiek.

Van de vakfiche economie en bedrijfswetenschappen 2DU (2027): de
transportmodi wegvervoer, spoorvervoer, binnenscheepvaart, maritiem
vervoer, luchtvracht en pijpleiding met hun voor- en nadelen, de taken van
de afdeling expeditie en logistiek, het verschil tussen invoer, uitvoer en
doorvoer, en het nut van een pakbon en een CMR.

Deel 1 zijn de transportmodi.
Deel 2 is de afdeling expeditie en logistiek.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is een transportmodus?",
         opties=["een manier van vervoeren",
                 "een soort vrachtwagen",
                 "een soort factuur ervan",
                 "een soort voorraad ervan"],
         antwoord=0,
         uitleg="Over de weg, per spoor, over water, door de lucht of via een pijpleiding."),
    dict(type="meerkeuze",
         vraag="Wat is wegvervoer?",
         opties=["vervoer met vrachtwagens",
                 "vervoer met treinen",
                 "vervoer met schepen",
                 "vervoer met vliegtuigen"],
         antwoord=0,
         uitleg="De meest gebruikte modus voor korte en middellange afstanden."),
    dict(type="meerkeuze",
         vraag="Wat is het grote voordeel van wegvervoer?",
         opties=["tot aan de deur",
                 "het is altijd goedkoop",
                 "het is altijd snel",
                 "het is milieuvriendelijk"],
         antwoord=0,
         uitleg="Een vrachtwagen kan tot bij de klant rijden; een trein of een schip niet."),
    dict(type="meerkeuze",
         vraag="Wat is een nadeel van wegvervoer?",
         opties=["de files",
                 "de hoge capaciteit",
                 "de lage prijs ervan",
                 "de grote snelheid"],
         antwoord=0,
         uitleg="En de uitstoot per ton is hoger dan bij spoor of water."),
    dict(type="invultekst",
         vraag="Welke transportmodus vervoert goederen over water in het binnenland? Hoogstens drie woorden.",
         antwoord=["binnenscheepvaart", "binnenvaart", "scheepvaart"],
         uitleg="De binnenscheepvaart."),
    dict(type="waarofniet",
         vraag="Luchtvracht is snel maar duur.",
         antwoord=True,
         uitleg="Daarom gaat er vooral lichte, dringende of kostbare vracht mee."),
    dict(type="waarofniet",
         vraag="Maritiem vervoer is de snelste manier om goederen te vervoeren.",
         antwoord=False,
         uitleg="Een zeeschip is het traagst, maar het vervoert enorme volumes voor weinig geld."),
    dict(type="meerkeuze",
         vraag="Wat vervoert een pijpleiding?",
         opties=["vloeistof of gas",
                 "pakjes ervan",
                 "mensen ervan",
                 "wagens ervan"],
         antwoord=0,
         uitleg="Aardgas, aardolie of water, dag en nacht door zonder chauffeur."),
    dict(type="meerkeuze",
         vraag="Welke modus heeft de grootste capaciteit?",
         opties=["maritiem vervoer",
                 "luchtvracht ervan",
                 "wegvervoer ervan",
                 "koerierdienst"],
         antwoord=0,
         uitleg="Een groot containerschip neemt de lading van duizenden vrachtwagens mee."),
    dict(type="meerkeuze",
         vraag="Welke modus kies je voor een dringend klein pakje naar Japan?",
         opties=["luchtvracht",
                 "een zeeschip",
                 "een binnenschip",
                 "een pijpleiding"],
         antwoord=0,
         uitleg="Duur per kilo, maar in een dag ter plaatse."),
    dict(type="meerkeuze",
         vraag="Welke transportmodi noemt de vakfiche?",
         opties=["wegvervoer en spoorvervoer",
                 "binnenscheepvaart en maritiem vervoer",
                 "luchtvracht en pijpleiding",
                 "vervoer met de fiets of te voet"],
         antwoord=[0, 1, 2],
         uitleg="Zes modi in totaal."),
    dict(type="meerkeuze",
         vraag="Waarop vergelijk je de transportmodi?",
         opties=["snelheid en kosten",
                 "kleur en vorm ervan",
                 "naam en nummer ervan",
                 "merk en bouwjaar ervan"],
         antwoord=0,
         uitleg="En op bereikbaarheid, capaciteit, de aard van het product en het milieueffect."),
    dict(type="waarofniet",
         vraag="Spoorvervoer stoot per ton minder uit dan wegvervoer.",
         antwoord=True,
         uitleg="Daarom kiezen ondernemingen voor het spoor waar het kan."),
    dict(type="waarofniet",
         vraag="Elke transportmodus kan tot aan de deur van de klant leveren.",
         antwoord=False,
         uitleg="Een schip en een trein stoppen bij een terminal; de laatste kilometers gaan over de weg."),
    dict(type="invultekst",
         vraag="Welke transportmodus is het snelst over grote afstand? Eén woord.",
         antwoord=["luchtvracht", "vliegtuig", "lucht"],
         uitleg="Luchtvracht."),
    dict(type="meerkeuze",
         vraag="Waarom gebruikt men vaak meerdere modi na elkaar?",
         opties=["elk doet wat hij best kan",
                 "het is altijd goedkoper",
                 "de wet verplicht het ervan",
                 "het is altijd sneller"],
         antwoord=0,
         uitleg="Een container komt per schip aan en gaat met de trein of de vrachtwagen verder."),
    dict(type="meerkeuze",
         vraag="Waarop baseer je de keuze van een transportmiddel?",
         opties=["hoe dringend het is",
                 "wat het product nodig heeft",
                 "wat het mag kosten",
                 "welke kleur de wagen heeft"],
         antwoord=[0, 1, 2],
         uitleg="En of de bestemming wel per spoor of over water bereikbaar is."),
    dict(type="meerkeuze",
         vraag="Welke modus past bij vers fruit uit Spanje?",
         opties=["gekoeld wegvervoer",
                 "een pijpleiding ervan",
                 "een zeeschip ervan",
                 "een sleepboot ervan"],
         antwoord=0,
         uitleg="Snel genoeg en met koeling, zodat het fruit vers aankomt."),
    dict(type="meerkeuze",
         vraag="Wat is waar over maritiem vervoer?",
         opties=["het is traag",
                 "het is goedkoop per ton",
                 "het vervoert grote volumes",
                 "het rijdt tot aan de deur"],
         antwoord=[0, 1, 2],
         uitleg="Tot aan de deur geraakt enkel het wegvervoer."),
    dict(type="invultekst",
         vraag="Welke transportmodus gebruikt het spoor? Eén woord.",
         antwoord=["spoorvervoer", "trein", "per trein"],
         uitleg="Spoorvervoer."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is een taak van de afdeling expeditie en logistiek?",
         opties=["goederen ontvangen",
                 "lonen berekenen",
                 "reclame maken",
                 "facturen boeken"],
         antwoord=0,
         uitleg="Ontvangen, opslaan, picken, verzenden, transport plannen en voorraad beheren."),
    dict(type="meerkeuze",
         vraag="Wat is picken in een loods?",
         opties=["goederen uithalen",
                 "goederen inladen",
                 "goederen wegen",
                 "goederen tellen"],
         antwoord=0,
         uitleg="De artikels van een order uit de rekken halen en samenbrengen."),
    dict(type="meerkeuze",
         vraag="Wat is voorraadbeheer?",
         opties=["weten wat je hebt",
                 "weten wat je verkoopt",
                 "weten wat je verdient",
                 "weten wie je klant is"],
         antwoord=0,
         uitleg="En op tijd bijbestellen, zonder te veel in de rekken te laten staan."),
    dict(type="meerkeuze",
         vraag="Wat is een retour?",
         opties=["goederen die terugkomen",
                 "goederen die weggaan",
                 "goederen die verkocht zijn",
                 "goederen die geteld zijn"],
         antwoord=0,
         uitleg="De klant stuurt terug wat hij niet houdt; de logistiek handelt dat af."),
    dict(type="invultekst",
         vraag="Hoe noem je het uit de rekken halen van de goederen van een order? Eén woord.",
         antwoord=["picken", "orderpicken", "uithalen"],
         uitleg="Picken."),
    dict(type="waarofniet",
         vraag="Een te kleine voorraad kan een verkoop doen mislopen.",
         antwoord=True,
         uitleg="Wat je niet in huis hebt, kan je niet leveren."),
    dict(type="waarofniet",
         vraag="Een zo groot mogelijke voorraad is altijd het beste.",
         antwoord=False,
         uitleg="Voorraad kost plaats en geld en kan verouderen; te veel is even slecht als te weinig."),
    dict(type="meerkeuze",
         vraag="Wat is invoer?",
         opties=["goederen binnenbrengen",
                 "goederen uitvoeren",
                 "goederen doorvoeren",
                 "goederen weggooien"],
         antwoord=0,
         uitleg="Goederen komen uit het buitenland het land binnen."),
    dict(type="meerkeuze",
         vraag="Wat is uitvoer?",
         opties=["goederen buitenbrengen",
                 "goederen binnenhalen",
                 "goederen doorlaten",
                 "goederen opslaan"],
         antwoord=0,
         uitleg="Goederen gaan van hier naar een ander land."),
    dict(type="meerkeuze",
         vraag="Wat is doorvoer?",
         opties=["enkel passeren",
                 "hier blijven ervan",
                 "hier verkopen ervan",
                 "hier maken ervan"],
         antwoord=0,
         uitleg="De goederen gaan door het land zonder er verhandeld te worden."),
    dict(type="meerkeuze",
         vraag="Welke taken noemt de vakfiche voor expeditie en logistiek?",
         opties=["goederen ontvangen en opslaan",
                 "goederen picken en verzenden",
                 "transport plannen en voorraad beheren",
                 "lonen berekenen en uitbetalen"],
         antwoord=[0, 1, 2],
         uitleg="En de retour van goederen. Lonen zijn werk voor HR en de boekhouding."),
    dict(type="meerkeuze",
         vraag="Wat is een pakbon?",
         opties=["wat in de zending zit",
                 "wat de zending kost",
                 "wie de klant is ervan",
                 "wie de wagen rijdt"],
         antwoord=0,
         uitleg="De lijst van de inhoud, zodat de ontvanger kan nakijken of alles er is."),
    dict(type="waarofniet",
         vraag="Een CMR is een vrachtbrief voor internationaal wegvervoer.",
         antwoord=True,
         uitleg="Hij regelt wie waarvoor aansprakelijk is tijdens het transport."),
    dict(type="waarofniet",
         vraag="Een pakbon en een CMR zijn hetzelfde document.",
         antwoord=False,
         uitleg="De pakbon zegt wat erin zit; de CMR is de vervoersovereenkomst tussen de drie partijen."),
    dict(type="invultekst",
         vraag="Hoe noem je de vrachtbrief bij internationaal wegvervoer? Eén woord.",
         antwoord=["cmr", "de cmr", "vrachtbrief"],
         uitleg="De CMR."),
    dict(type="meerkeuze",
         vraag="Wie ondertekent een CMR?",
         opties=["de drie partijen",
                 "enkel de klant ervan",
                 "enkel de bank ervan",
                 "enkel de vervoerder"],
         antwoord=0,
         uitleg="De afzender, de vervoerder en de bestemmeling."),
    dict(type="meerkeuze",
         vraag="Wat staat er op een CMR?",
         opties=["de afzender en de bestemmeling",
                 "de aard van de goederen",
                 "het gewicht van de zending",
                 "het loon van de chauffeur"],
         antwoord=[0, 1, 2],
         uitleg="En de plaats en datum van inlading en van levering."),
    dict(type="meerkeuze",
         vraag="Wat is een eenvoudige logistieke taak?",
         opties=["een route opstellen",
                 "een factuur boeken",
                 "een loon berekenen",
                 "een vacature maken"],
         antwoord=0,
         uitleg="En volumes en gewichten berekenen, of een retour afhandelen."),
    dict(type="meerkeuze",
         vraag="Waarom is een goede logistiek belangrijk voor de hele onderneming?",
         opties=["de klant krijgt zijn levering op tijd",
                 "de voorraad kost niet te veel",
                 "de verkoop kan beloftes nakomen",
                 "de reclame wordt goedkoper"],
         antwoord=[0, 1, 2],
         uitleg="De prijs van reclame heeft met de logistiek niets te maken."),
    dict(type="invultekst",
         vraag="Welk document gaat bij een zending mee en zegt wat erin zit? Eén woord.",
         antwoord=["pakbon", "een pakbon", "paklijst"],
         uitleg="De pakbon."),
]
