# -*- coding: utf-8 -*-
"""Soorten ondernemingen en hun verplichtingen.

Van de vakfiche economie en bedrijfswetenschappen 2DU (2027): het verschil
tussen een natuurlijk persoon en een rechtspersoon, beperkte tegenover
onbeperkte aansprakelijkheid, en de vergelijking van de eenmanszaak, de
besloten vennootschap en de naamloze vennootschap op oprichtingsakte,
kapitaal, aantal oprichters, aansprakelijkheid, boekhouding,
overdraagbaarheid van de aandelen en fiscaliteit.

Deel 1 zijn de begrippen.
Deel 2 is de vergelijking van de drie vormen.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is een natuurlijk persoon?",
         opties=["een mens",
                 "een vennootschap",
                 "een vereniging",
                 "een gebouw ervan"],
         antwoord=0,
         uitleg="Een mens van vlees en bloed, met rechten en plichten."),
    dict(type="meerkeuze",
         vraag="Wat is een rechtspersoon?",
         opties=["een eigen juridische figuur",
                 "een mens van vlees en bloed",
                 "een werknemer ervan",
                 "een klant van de zaak"],
         antwoord=0,
         uitleg="Een vennootschap of een vzw: ze kan zelf eigenaar zijn, lenen en voor de rechter komen."),
    dict(type="meerkeuze",
         vraag="Wat is onbeperkte aansprakelijkheid?",
         opties=["ook je eigen bezit staat in",
                 "enkel de zaak staat in",
                 "niemand staat in ervan",
                 "de bank staat in ervan"],
         antwoord=0,
         uitleg="Een schuldeiser kan ook aan je woning of je spaargeld."),
    dict(type="meerkeuze",
         vraag="Wat is beperkte aansprakelijkheid?",
         opties=["enkel je inbreng staat in",
                 "ook je huis staat in ervan",
                 "alles van je staat in",
                 "niets staat ooit in"],
         antwoord=0,
         uitleg="Je verliest maximaal wat je in de vennootschap stopte."),
    dict(type="invultekst",
         vraag="Welke onderneming heeft geen eigen rechtspersoonlijkheid? Eén woord.",
         antwoord=["eenmanszaak", "de eenmanszaak"],
         uitleg="De eenmanszaak: de zaak en de persoon zijn één."),
    dict(type="waarofniet",
         vraag="Bij een eenmanszaak kan een schuldeiser ook aan het privévermogen.",
         antwoord=True,
         uitleg="Er is geen scheiding tussen de zaak en de persoon."),
    dict(type="waarofniet",
         vraag="Een bv is een natuurlijk persoon.",
         antwoord=False,
         uitleg="Een bv is een rechtspersoon, met een eigen vermogen los van de oprichters."),
    dict(type="meerkeuze",
         vraag="Wat betekent bv?",
         opties=["besloten vennootschap",
                 "beperkte vennootschap",
                 "bijzondere vennootschap",
                 "belastbare vennootschap"],
         antwoord=0,
         uitleg="Besloten, omdat de aandelen niet vrij verhandeld worden."),
    dict(type="meerkeuze",
         vraag="Wat betekent nv?",
         opties=["naamloze vennootschap",
                 "nieuwe vennootschap",
                 "nationale vennootschap",
                 "nuttige vennootschap"],
         antwoord=0,
         uitleg="Naamloos, omdat de aandeelhouders niet in de naam staan."),
    dict(type="meerkeuze",
         vraag="Wat is het voordeel van een eenmanszaak?",
         opties=["ze is snel opgericht",
                 "je bezit staat veilig",
                 "je betaalt geen belasting",
                 "je bent nooit aansprakelijk"],
         antwoord=0,
         uitleg="Geen notaris, geen kapitaal, weinig formaliteiten."),
    dict(type="meerkeuze",
         vraag="Waarop vergelijkt de vakfiche de ondernemingsvormen?",
         opties=["de aansprakelijkheid",
                 "de administratie",
                 "de fiscaliteit",
                 "de kleur van het logo"],
         antwoord=[0, 1, 2],
         uitleg="En ook op de oprichtingsakte, het kapitaal en de overdraagbaarheid van de aandelen."),
    dict(type="meerkeuze",
         vraag="Wat heeft een bv of een nv nodig bij de oprichting?",
         opties=["een notariële akte",
                 "enkel een handtekening",
                 "een brief aan de bank",
                 "een mail aan de stad"],
         antwoord=0,
         uitleg="De notaris maakt de akte op en die wordt bekendgemaakt."),
    dict(type="waarofniet",
         vraag="Een eenmanszaak kan zonder notaris opgericht worden.",
         antwoord=True,
         uitleg="Je schrijft je in bij een ondernemingsloket en vraagt een ondernemingsnummer aan."),
    dict(type="waarofniet",
         vraag="Voor een eenmanszaak is een notariële akte verplicht.",
         antwoord=False,
         uitleg="Die is enkel nodig bij een vennootschap zoals een bv of een nv."),
    dict(type="invultekst",
         vraag="Hoe noem je het bezit dat buiten de onderneming valt? Hoogstens drie woorden.",
         antwoord=["privévermogen", "privevermogen", "prive vermogen"],
         uitleg="Het privévermogen."),
    dict(type="meerkeuze",
         vraag="Waarom kiest iemand voor een vennootschap met beperkte aansprakelijkheid?",
         opties=["om zijn bezit te beschermen",
                 "om minder te moeten werken",
                 "om geen boekhouding te doen",
                 "om sneller te starten ervan"],
         antwoord=0,
         uitleg="Gaat de zaak slecht, dan blijft het privévermogen in principe buiten schot."),
    dict(type="meerkeuze",
         vraag="Wat is waar over een rechtspersoon?",
         opties=["hij heeft eigen bezit",
                 "hij kan zelf schulden hebben",
                 "hij blijft bestaan los van de oprichters",
                 "hij kan niet voor de rechter komen"],
         antwoord=[0, 1, 2],
         uitleg="Hij kan net wel dagvaarden en gedagvaard worden."),
    dict(type="meerkeuze",
         vraag="Wie betaalt personenbelasting op de winst?",
         opties=["de eenmanszaak",
                 "de bv ervan",
                 "de nv ervan",
                 "de vzw ervan"],
         antwoord=0,
         uitleg="De winst komt bij het inkomen van de zaakvoerder. Een bv en een nv betalen vennootschapsbelasting."),
    dict(type="meerkeuze",
         vraag="Wat geldt voor een eenmanszaak?",
         opties=["één eigenaar",
                 "onbeperkte aansprakelijkheid",
                 "geen rechtspersoonlijkheid",
                 "een minimumkapitaal"],
         antwoord=[0, 1, 2],
         uitleg="Er is geen kapitaal vereist om te starten."),
    dict(type="invultekst",
         vraag="Welke belasting betaalt een bv op haar winst? Hoogstens drie woorden.",
         antwoord=["vennootschapsbelasting", "de vennootschapsbelasting"],
         uitleg="De vennootschapsbelasting."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Hoeveel oprichters heeft een bv minimaal nodig?",
         opties=["één",
                 "twee ervan",
                 "drie ervan",
                 "zeven ervan"],
         antwoord=0,
         uitleg="Eén volstaat; een bv kan door één persoon opgericht worden."),
    dict(type="meerkeuze",
         vraag="Hoeveel oprichters heeft een nv minimaal nodig?",
         opties=["één",
                 "twee ervan",
                 "vijf ervan",
                 "tien ervan"],
         antwoord=0,
         uitleg="Sinds de hervorming van het vennootschapsrecht kan ook een nv alleen opgericht worden."),
    dict(type="meerkeuze",
         vraag="Wat vraagt de wet aan minimumkapitaal voor een bv?",
         opties=["geen vast bedrag",
                 "achttienduizend euro",
                 "éénenzestigduizend euro",
                 "duizend euro ervan"],
         antwoord=0,
         uitleg="Wel een toereikend aanvangsvermogen, dat je in een financieel plan verantwoordt."),
    dict(type="meerkeuze",
         vraag="Wat vraagt de wet aan minimumkapitaal voor een nv?",
         opties=["een vast bedrag",
                 "geen bedrag ervan",
                 "enkel een plan ervan",
                 "nooit iets ervan"],
         antwoord=0,
         uitleg="Een nv heeft wel nog een wettelijk minimumkapitaal; een bv niet."),
    dict(type="invultekst",
         vraag="Welke vennootschapsvorm heeft nog een wettelijk minimumkapitaal? Eén woord.",
         antwoord=["nv", "de nv", "naamloze vennootschap"],
         uitleg="De nv."),
    dict(type="waarofniet",
         vraag="De aandelen van een nv zijn in principe vrij overdraagbaar.",
         antwoord=True,
         uitleg="Daarom is de nv de vorm voor wie geld bij veel investeerders wil ophalen."),
    dict(type="waarofniet",
         vraag="De aandelen van een bv zijn even vrij overdraagbaar als die van een nv.",
         antwoord=False,
         uitleg="Een bv is besloten: de overdracht is beperkt, meestal met toestemming van de anderen."),
    dict(type="meerkeuze",
         vraag="Wat betekent het dat een bv besloten is?",
         opties=["aandelen gaan moeilijk weg",
                 "aandelen gaan vrij weg",
                 "er zijn geen aandelen",
                 "alles is openbaar ervan"],
         antwoord=0,
         uitleg="De aandeelhouders kiezen zelf wie erbij komt."),
    dict(type="meerkeuze",
         vraag="Welke boekhouding moet een bv voeren?",
         opties=["een dubbele boekhouding",
                 "een vereenvoudigde ervan",
                 "geen boekhouding ervan",
                 "enkel een kasboek ervan"],
         antwoord=0,
         uitleg="Met een jaarrekening die neergelegd wordt bij de Nationale Bank."),
    dict(type="meerkeuze",
         vraag="Welke boekhouding mag een kleine eenmanszaak voeren?",
         opties=["een vereenvoudigde",
                 "een dubbele ervan",
                 "geen enkele ervan",
                 "een dagelijkse ervan"],
         antwoord=0,
         uitleg="Onder een bepaalde omzetgrens volstaan drie dagboeken."),
    dict(type="meerkeuze",
         vraag="Wat moet een bv of nv jaarlijks doen?",
         opties=["een jaarrekening opmaken",
                 "die neerleggen bij de Nationale Bank",
                 "vennootschapsbelasting betalen",
                 "het kapitaal uitbetalen"],
         antwoord=[0, 1, 2],
         uitleg="Het kapitaal blijft in de vennootschap zitten."),
    dict(type="meerkeuze",
         vraag="Wie is aansprakelijk voor de schulden van een nv?",
         opties=["de vennootschap zelf",
                 "elke aandeelhouder ervan",
                 "de bank van de zaak",
                 "de klanten ervan"],
         antwoord=0,
         uitleg="De aandeelhouders riskeren enkel hun inbreng."),
    dict(type="waarofniet",
         vraag="Een aandeelhouder van een bv verliest maximaal zijn inbreng.",
         antwoord=True,
         uitleg="Dat is precies wat beperkte aansprakelijkheid betekent."),
    dict(type="waarofniet",
         vraag="Een zaakvoerder van een bv is altijd met zijn privévermogen aansprakelijk.",
         antwoord=False,
         uitleg="Normaal niet, tenzij hij een zware fout maakt of de vennootschap te licht liet starten."),
    dict(type="invultekst",
         vraag="Welke akte heeft een nv nodig bij de oprichting? Hoogstens drie woorden.",
         antwoord=["notariele akte", "notariële akte", "authentieke akte"],
         uitleg="Een notariële akte."),
    dict(type="meerkeuze",
         vraag="Welke ondernemingsvorm past bij wie alleen en klein wil beginnen?",
         opties=["de eenmanszaak",
                 "de nv ervan",
                 "de bv met vijf",
                 "een vzw ervan"],
         antwoord=0,
         uitleg="Snel, goedkoop en met weinig formaliteiten, maar wel met je bezit als risico."),
    dict(type="meerkeuze",
         vraag="Welke voordelen heeft een bv tegenover een eenmanszaak?",
         opties=["beperkte aansprakelijkheid",
                 "een eigen rechtspersoon",
                 "makkelijker partners erbij",
                 "minder administratie"],
         antwoord=[0, 1, 2],
         uitleg="De administratie is juist zwaarder: dubbele boekhouding en jaarrekening."),
    dict(type="meerkeuze",
         vraag="Wat is een nadeel van een eenmanszaak?",
         opties=["je bezit staat in",
                 "je betaalt meer btw",
                 "je mag niet verkopen",
                 "je kan niet lenen"],
         antwoord=0,
         uitleg="De onbeperkte aansprakelijkheid is het grootste nadeel."),
    dict(type="meerkeuze",
         vraag="Waarin verschilt een nv van een bv?",
         opties=["het minimumkapitaal",
                 "de overdraagbaarheid van de aandelen",
                 "de naam van de vorm",
                 "de aansprakelijkheid van de aandeelhouders"],
         antwoord=[0, 1, 2],
         uitleg="In beide gevallen is de aansprakelijkheid beperkt tot de inbreng."),
    dict(type="invultekst",
         vraag="Hoeveel personen kunnen vandaag een bv oprichten? Eén woord.",
         antwoord=["één", "1", "een"],
         uitleg="Eén."),
]
