# -*- coding: utf-8 -*-
"""Soorten klanten en het verkoopgesprek.

Van de vakfiche economie en bedrijfswetenschappen 2DU (2027): de soorten
klanten en hun koopmotieven herkennen, verkoopgesprekken observeren en
beoordelen, en de fasen van een verkoopgesprek: de aandacht van de klant
trekken, een behoefte ontwikkelen, argumenten geven, bezwaren weerleggen,
koopsignalen ontdekken en de aankoop afsluiten.

Deel 1 zijn de klanten en de koopmotieven.
Deel 2 zijn de fasen van het gesprek.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is een koopmotief?",
         opties=["de reden om te kopen",
                 "de prijs van het goed",
                 "de plaats van de winkel",
                 "de naam van de klant"],
         antwoord=0,
         uitleg="Waarom iemand dit product wil hebben."),
    dict(type="meerkeuze",
         vraag="Wat is een rationeel koopmotief?",
         opties=["een verstandige reden",
                 "een gevoel ervan",
                 "een gewoonte ervan",
                 "een impuls ervan"],
         antwoord=0,
         uitleg="De prijs, de kwaliteit, de garantie, het verbruik."),
    dict(type="meerkeuze",
         vraag="Wat is een emotioneel koopmotief?",
         opties=["een gevoelsreden",
                 "een rekensom ervan",
                 "een garantie ervan",
                 "een berekening ervan"],
         antwoord=0,
         uitleg="Status, mode, erbij willen horen, iets mooi vinden."),
    dict(type="meerkeuze",
         vraag="Wat is een twijfelende klant?",
         opties=["hij kan niet kiezen",
                 "hij weet alles al",
                 "hij koopt meteen",
                 "hij praat veel ervan"],
         antwoord=0,
         uitleg="Help hem met twee of drie duidelijke opties in plaats van tien."),
    dict(type="invultekst",
         vraag="Hoe noem je de reden waarom iemand iets koopt? Hoogstens drie woorden.",
         antwoord=["koopmotief", "een koopmotief", "motief"],
         uitleg="Het koopmotief."),
    dict(type="waarofniet",
         vraag="Een klant kan meerdere koopmotieven tegelijk hebben.",
         antwoord=True,
         uitleg="Een wagen kan tegelijk zuinig én mooi moeten zijn."),
    dict(type="waarofniet",
         vraag="Elke klant wil op dezelfde manier aangepakt worden.",
         antwoord=False,
         uitleg="Een stille klant en een veeleisende klant hebben een andere aanpak nodig."),
    dict(type="meerkeuze",
         vraag="Hoe ga je om met een stille klant?",
         opties=["open vragen stellen",
                 "zelf blijven praten",
                 "hem laten staan",
                 "de prijs verlagen"],
         antwoord=0,
         uitleg="Met een open vraag krijg je meer dan ja of nee terug."),
    dict(type="meerkeuze",
         vraag="Hoe ga je om met een veeleisende klant?",
         opties=["rustig en duidelijk",
                 "boos terug ervan",
                 "hem wegsturen ervan",
                 "zwijgen ervan"],
         antwoord=0,
         uitleg="Je neemt zijn vraag ernstig en zegt eerlijk wat kan en wat niet."),
    dict(type="meerkeuze",
         vraag="Hoe ga je om met een klant die veel weet?",
         opties=["zijn kennis erkennen",
                 "hem tegenspreken",
                 "hem verbeteren ervan",
                 "hem negeren ervan"],
         antwoord=0,
         uitleg="Bouw op wat hij al weet en vul aan waar hij iets mist."),
    dict(type="meerkeuze",
         vraag="Wat zijn rationele koopmotieven?",
         opties=["de prijs",
                 "de kwaliteit",
                 "de garantie",
                 "de kleur die in de mode is"],
         antwoord=[0, 1, 2],
         uitleg="Mode is een emotioneel motief."),
    dict(type="meerkeuze",
         vraag="Waarom is het nuttig het koopmotief te kennen?",
         opties=["je argumenten passen beter",
                 "je prijs wordt lager ervan",
                 "je voorraad wordt groter",
                 "je factuur wordt korter"],
         antwoord=0,
         uitleg="Wie om zuinigheid geeft, hoort iets anders dan wie om design geeft."),
    dict(type="waarofniet",
         vraag="Een goede verkoper luistert meer dan hij praat.",
         antwoord=True,
         uitleg="Zonder te weten wat de klant zoekt, is elk argument een gok."),
    dict(type="waarofniet",
         vraag="Een verkoper moet elke klant hetzelfde verhaal vertellen.",
         antwoord=False,
         uitleg="Hij past zijn argumenten aan het koopmotief van die klant aan."),
    dict(type="invultekst",
         vraag="Hoe noem je een koopmotief dat op gevoel berust? Eén woord.",
         antwoord=["emotioneel", "gevoelsmatig", "emotioneel motief"],
         uitleg="Een emotioneel koopmotief."),
    dict(type="meerkeuze",
         vraag="Wat doe je als een klant zegt dat hij enkel komt kijken?",
         opties=["je blijft beschikbaar",
                 "je dringt toch aan",
                 "je laat hem alleen",
                 "je sluit de winkel"],
         antwoord=0,
         uitleg="Je laat hem rondkijken en zegt dat je er bent als hij iets wil weten."),
    dict(type="meerkeuze",
         vraag="Wat hoort allemaal bij een emotioneel koopmotief?",
         opties=["status",
                 "mode",
                 "erbij willen horen",
                 "de garantie van twee jaar"],
         antwoord=[0, 1, 2],
         uitleg="De garantie is een rationeel motief."),
    dict(type="meerkeuze",
         vraag="Wat is het nut van een verkoopgesprek observeren?",
         opties=["eruit leren",
                 "tijd verliezen",
                 "niets ervan",
                 "de prijs zetten"],
         antwoord=0,
         uitleg="Je ziet wat werkte en wat je zelf anders zou doen."),
    dict(type="meerkeuze",
         vraag="Waarop beoordeel je een verkoopgesprek?",
         opties=["is er geluisterd",
                 "zijn de bezwaren weerlegd",
                 "is de behoefte gevonden",
                 "is er druk gezet op de klant"],
         antwoord=[0, 1, 2],
         uitleg="Druk zetten is geen teken van een goed gesprek."),
    dict(type="invultekst",
         vraag="Wat doet een goede verkoper vooral in het begin van het gesprek? Eén woord.",
         antwoord=["luisteren", "vragen", "vragen stellen"],
         uitleg="Luisteren en vragen stellen."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is de eerste fase van een verkoopgesprek?",
         opties=["de aandacht krijgen",
                 "de aankoop afsluiten",
                 "de bezwaren weerleggen",
                 "de factuur maken"],
         antwoord=0,
         uitleg="De aandacht van de klant trekken, of hem aandacht geven."),
    dict(type="meerkeuze",
         vraag="Wat komt na het trekken van de aandacht?",
         opties=["de behoefte ontwikkelen",
                 "de aankoop afsluiten",
                 "de factuur versturen",
                 "de klant wegsturen"],
         antwoord=0,
         uitleg="Je zoekt samen met de klant wat hij echt nodig heeft."),
    dict(type="meerkeuze",
         vraag="Wat doe je nadat je de behoefte kent?",
         opties=["argumenten geven",
                 "de aankoop afsluiten",
                 "de prijs verzwijgen",
                 "de winkel sluiten"],
         antwoord=0,
         uitleg="Argumenten die passen bij die behoefte, niet bij alle producten."),
    dict(type="meerkeuze",
         vraag="Wat is een bezwaar van een klant?",
         opties=["een tegenargument",
                 "een koopsignaal",
                 "een betaling ervan",
                 "een factuur ervan"],
         antwoord=0,
         uitleg="Te duur, te groot, of hij wil er nog over nadenken."),
    dict(type="invultekst",
         vraag="Hoe noem je het teken dat een klant wil kopen? Hoogstens drie woorden.",
         antwoord=["koopsignaal", "een koopsignaal", "koopsignalen"],
         uitleg="Een koopsignaal."),
    dict(type="waarofniet",
         vraag="Een bezwaar betekent vaak dat de klant geïnteresseerd is.",
         antwoord=True,
         uitleg="Wie helemaal niet wil kopen, neemt niet de moeite om tegen te spreken."),
    dict(type="waarofniet",
         vraag="Een bezwaar hoor je te negeren.",
         antwoord=False,
         uitleg="Je erkent het en geeft er een eerlijk antwoord op."),
    dict(type="meerkeuze",
         vraag="Wat is een koopsignaal?",
         opties=["de klant wil kopen",
                 "de klant gaat weg",
                 "de klant zwijgt ervan",
                 "de klant klaagt ervan"],
         antwoord=0,
         uitleg="Hij vraagt naar de levertijd, naar de garantie of naar de kleur die hij wil."),
    dict(type="meerkeuze",
         vraag="Wat is de laatste fase van een verkoopgesprek?",
         opties=["de aankoop afsluiten",
                 "de aandacht trekken",
                 "de behoefte zoeken",
                 "de bezwaren horen"],
         antwoord=0,
         uitleg="Je maakt de afspraak concreet en bevestigt wat er geleverd wordt."),
    dict(type="meerkeuze",
         vraag="Hoe weerleg je een bezwaar goed?",
         opties=["erkennen en antwoorden",
                 "meteen tegenspreken",
                 "er niet op ingaan",
                 "de klant uitlachen"],
         antwoord=0,
         uitleg="Je laat zien dat je het begrijpt en geeft er dan je antwoord op."),
    dict(type="meerkeuze",
         vraag="Welke fasen noemt de vakfiche in een verkoopgesprek?",
         opties=["de aandacht van de klant trekken",
                 "een behoefte ontwikkelen",
                 "argumenten geven",
                 "de factuur boeken in het journaal"],
         antwoord=[0, 1, 2],
         uitleg="En bezwaren weerleggen, koopsignalen ontdekken en afsluiten. Boeken is werk voor de boekhouding."),
    dict(type="meerkeuze",
         vraag="Wat doe je als je een koopsignaal ziet?",
         opties=["naar de afsluiting gaan",
                 "nog meer uitleggen",
                 "de prijs verhogen",
                 "een bezwaar maken"],
         antwoord=0,
         uitleg="De klant is er klaar voor; nog meer uitleg kan nieuwe twijfel wekken."),
    dict(type="waarofniet",
         vraag="Wie te lang doorpraat na een koopsignaal, kan de verkoop verliezen.",
         antwoord=True,
         uitleg="Elke extra uitleg kan een nieuwe twijfel oproepen."),
    dict(type="waarofniet",
         vraag="Argumenten geef je best voor je de behoefte kent.",
         antwoord=False,
         uitleg="Dan praat je over zaken waar de klant niets aan heeft."),
    dict(type="invultekst",
         vraag="Hoe noem je het antwoorden op wat een klant tegen de aankoop inbrengt? Hoogstens drie woorden.",
         antwoord=["bezwaren weerleggen", "weerleggen", "bezwaar weerleggen"],
         uitleg="Bezwaren weerleggen."),
    dict(type="meerkeuze",
         vraag="Wat is een open vraag in een verkoopgesprek?",
         opties=["ze vraagt om uitleg",
                 "ze vraagt ja of nee",
                 "ze vraagt een prijs",
                 "ze vraagt niets ervan"],
         antwoord=0,
         uitleg="Waarvoor gaat u het gebruiken? geeft meer terug dan Wil u dit?"),
    dict(type="meerkeuze",
         vraag="Wat hoort bij een goede afsluiting?",
         opties=["de afspraak bevestigen",
                 "de levering regelen",
                 "de klant bedanken",
                 "de klant onder druk zetten"],
         antwoord=[0, 1, 2],
         uitleg="Druk zetten levert een klant op die later afbelt."),
    dict(type="meerkeuze",
         vraag="Waarom stel je eerst vragen aan een klant?",
         opties=["om zijn behoefte te kennen",
                 "om tijd te winnen ervan",
                 "om de prijs te zetten",
                 "om de winkel te vullen"],
         antwoord=0,
         uitleg="Zonder behoefte is er niets om argumenten op te bouwen."),
    dict(type="meerkeuze",
         vraag="Wat doe je bij het bezwaar dat iets te duur is?",
         opties=["de waarde uitleggen",
                 "een alternatief tonen",
                 "vragen waarmee hij vergelijkt",
                 "de klant wegsturen"],
         antwoord=[0, 1, 2],
         uitleg="Soms vergelijkt hij met iets dat veel minder biedt."),
    dict(type="invultekst",
         vraag="Hoe noem je het laatste deel van het gesprek waarin de klant beslist? Hoogstens drie woorden.",
         antwoord=["afsluiting", "de afsluiting", "afsluiten"],
         uitleg="De afsluiting."),
]
