# -*- coding: utf-8 -*-
"""Spreken en gesprekken, en de klanken en de spelling van het Frans.

Uit de vakfiche Frans van de 2de graad dubbele finaliteit. Spreken en de twee
mondelinge interacties zijn samen 24 % van het examen, en er staan drie eigen
beoordelingsrijen bij: lichaamstaal, spreektempo en vlotheid, en uitspraak en
intonatie. Onderaan de grammaticalijst staat daarnaast een rij "fonologische
elementen en spelling": de uitspraak van klanken en klankencombinaties,
woordklemtoon, articulatie en intonatie, de relatie tussen klank- en
schriftbeeld, en de spelling van frequente woorden.

Het gesprek zelf kan een platform met tekstvragen niet nabootsen: dat vraagt
geluid en een gesprekspartner. Wat je erover moet wéten kan wel: hoe het
examenonderdeel verloopt, welke strategieën je mag gebruiken, waarop je
beoordeeld wordt, en hoe het Frans klinkt dat je op papier ziet staan.

Deel 1 gaat over de spreekopdracht, het gesprek en de strategieën. Deel 2 gaat
over de klanken, de klemtoon, de accenten en de spelling: welke letters hoor je
niet, waar hangt de uitspraak van een c of een g van af, en waarom verandert
een accent de betekenis van een woord.
"""

DEEL1 = [
    # --- Het examen zelf --------------------------------------------------
    dict(type="meerkeuze",
         vraag="Uit welke drie delen bestaat het examen Frans?",
         opties=["een spreekopdracht, een digitaal examen en een gesprek",
                 "een schriftelijk examen, een gesprek en een werkstuk",
                 "een leesproef, een luisterproef en een dictee",
                 "een digitaal examen en twee mondelinge gesprekken"],
         antwoord=0,
         uitleg="De spreekopdracht neem je thuis op, het digitale examen en het gesprek leg je af in het examencentrum in Brussel."),
    dict(type="meerkeuze",
         vraag="Waar en hoe neem je de spreekopdracht op?",
         opties=["thuis, en je dient ze in tot drie dagen voor je digitale examen",
                 "in het examencentrum, net voor het digitale examen",
                 "thuis, en je brengt ze op een usb-stick mee",
                 "in het examencentrum, samen met het gesprek"],
         antwoord=0,
         uitleg="De spreekopdracht neem je thuis op. Dien ze tijdig in: anders mag je niet deelnemen aan het examen in het centrum."),
    dict(type="meerkeuze",
         vraag="Hoelang duren het digitale examen en het gesprek?",
         opties=["150 minuten voor het digitale examen en 10 minuten voor het gesprek",
                 "120 minuten voor het digitale examen en 15 minuten voor het gesprek",
                 "150 minuten voor het digitale examen en 15 minuten voor het gesprek",
                 "90 minuten voor het digitale examen en 10 minuten voor het gesprek"],
         antwoord=0,
         uitleg="Het digitale examen duurt 150 minuten. Daarna krijg je 15 minuten voorbereidingstijd voor twee opdrachten, en het gesprek zelf duurt 10 minuten."),
    dict(type="waarofniet",
         vraag="Je krijgt voor de mondelinge opdrachten voorbereidingstijd, maar je moet ook spontaan kunnen reageren.",
         antwoord=True,
         uitleg="Vijftien minuten voorbereiding voor twee opdrachten. In het gesprek zelf moet je wel ingaan op wat je gesprekspartner zegt."),
    dict(type="meerkeuze",
         vraag="Wat krijg je van de examencommissie mee in het examenlokaal?",
         opties=["een balpen en kladpapier",
                 "een hoofdtelefoon",
                 "links naar het digitale woordenboek en de spellingcontrole",
                 "een eigen laptop om op te werken"],
         antwoord=[0, 1, 2],
         uitleg="De computer staat er al; een eigen laptop breng je niet mee. Je persoonlijke spullen gaan in een locker."),
    dict(type="waarofniet",
         vraag="Een samenvatting op papier bij je hebben in de examenruimte wordt als examenfraude beschouwd.",
         antwoord=True,
         uitleg="Gsm, smartwatch, cursusmateriaal en samenvattingen horen alle vier in de locker in de onthaalruimte."),
    # --- Het gesprek ------------------------------------------------------
    dict(type="meerkeuze",
         vraag="Wat is het verschil tussen een spreekopdracht en een gesprek?",
         opties=["Bij een spreekopdracht ben je alleen aan het woord; bij een gesprek moet je reageren.",
                 "Een spreekopdracht duurt langer dan een gesprek.",
                 "Een spreekopdracht doe je in het Nederlands, een gesprek in het Frans.",
                 "Bij een gesprek mag je alles vooraf uitschrijven en voorlezen."],
         antwoord=0,
         uitleg="Bij een gesprek verwachten we dat je een eenvoudig gesprek kan beginnen, gaande houden en beëindigen."),
    dict(type="meerkeuze",
         vraag="Met welke zinnen kan je in het Frans een gesprek beginnen?",
         opties=["Bonjour, je peux vous poser une question ?",
                 "Excusez-moi, vous avez une minute ?",
                 "Bonjour, je voudrais vous parler de mon stage.",
                 "Au revoir, bonne journée."],
         antwoord=[0, 1, 2],
         uitleg="Au revoir sluit een gesprek juist af. Beginnen, gaande houden en beëindigen zijn drie aparte dingen die je moet kunnen."),
    dict(type="meerkeuze",
         vraag="Je hebt niet begrepen wat je gesprekspartner zei. Wat doe je?",
         opties=["Je vraagt of hij het wil herhalen of trager wil spreken.",
                 "Je zegt oui en hoopt dat het klopt.",
                 "Je zwijgt tot hij zelf verder gaat met iets anders.",
                 "Je antwoordt in het Nederlands en gaat dan verder."],
         antwoord=0,
         uitleg="Vous pouvez répéter, s'il vous plaît ? of Pouvez-vous parler plus lentement ? Dat vragen is een strategie, geen zwakte."),
    dict(type="invultekst",
         vraag="Hoe vraag je in het Frans of iemand iets wil herhalen? Vul in: « Vous pouvez ..., s'il vous plaît ? » Schrijf één woord.",
         antwoord=["répéter"],
         uitleg="Répéter betekent herhalen."),
    dict(type="waarofniet",
         vraag="Je mag in een gesprek om de boodschap te laten herhalen, maar je mag niet vragen om trager te spreken.",
         antwoord=False,
         uitleg="Allebei mag: vraag om de boodschap te herhalen óf om trager te spreken. Dat staat uitdrukkelijk bij de strategieën."),
    dict(type="meerkeuze",
         vraag="Je hebt de indruk dat je gesprekspartner jóu niet begrijpt. Wat doe je?",
         opties=["Je herhaalt je boodschap, of je zegt ze op een andere manier.",
                 "Je spreekt luider en blijft bij dezelfde woorden.",
                 "Je stapt over op het Nederlands voor de rest van het gesprek.",
                 "Je stopt het gesprek en begint over iets anders."],
         antwoord=0,
         uitleg="Anders formuleren werkt vaak beter dan luider worden. Daarvoor heb je geen moeilijke woorden nodig."),
    dict(type="waarofniet",
         vraag="Onderbrekingen, valse starts en herformuleringen worden bij spreken als aanvaardbaar beoordeeld.",
         antwoord=True,
         uitleg="Zo staat de rij spreektempo en vlotheid: ze zijn aanvaardbaar. Je moet niet vloeiend klinken, je moet verstaanbaar blijven."),
    # --- De strategieën bij spreken ----------------------------------------
    dict(type="meerkeuze",
         vraag="Welke rol speelt lichaamstaal in een gesprek in het Frans?",
         opties=["Je gebruikt ze zelf om je boodschap over te brengen, en je leest ze bij de ander af.",
                 "Ze telt niet mee, want het examen gaat over taal.",
                 "Ze mag niet, want ze helpt je te veel vooruit.",
                 "Ze is alleen belangrijk bij de spreekopdracht thuis."],
         antwoord=0,
         uitleg="Lichaamstaal is een eigen beoordelingsrij bij spreken en mondelinge interactie: je gebruikt een gepaste lichaamstaal."),
    dict(type="meerkeuze",
         vraag="Welke drie beoordelingsrijen gelden alleen bij spreken en mondelinge interactie?",
         opties=["lichaamstaal",
                 "spreektempo en vlotheid",
                 "uitspraak en intonatie",
                 "spelling en leestekengebruik"],
         antwoord=[0, 1, 2],
         uitleg="Spelling en leestekengebruik horen bij schrijven. De andere vijf rijen gelden voor allebei."),
    dict(type="waarofniet",
         vraag="Bij de rij uitspraak en intonatie moet je klinken als een moedertaalspreker.",
         antwoord=False,
         uitleg="Je uitspraak is voldoende helder en belemmert het begrip van de boodschap niet. Een accent mag."),
    dict(type="meerkeuze",
         vraag="Je bereidt een spreekopdracht voor over je weekend. Hoe pak je dat aan?",
         opties=["Je maakt een spreekplan met kernwoorden en oefent luidop.",
                 "Je schrijft alles uit en leest het voor zonder op te kijken.",
                 "Je begint zonder voorbereiding, dat klinkt natuurlijker.",
                 "Je leert een tekst van het internet uit het hoofd."],
         antwoord=0,
         uitleg="Een plan met kernwoorden houdt je verhaal in de goede orde, en luidop oefenen helpt je uitspraak en je tempo."),
    dict(type="meerkeuze",
         vraag="Je spreekt met een volwassene die je niet kent. Welke twee dingen passen bij een gepaste toon?",
         opties=["de vous-vorm gebruiken",
                 "beginnen met bonjour",
                 "tutoyeren omdat dat vriendelijker klinkt",
                 "hem bij zijn voornaam noemen"],
         antwoord=[0, 1],
         uitleg="Tutoyeren en de voornaam gebruiken horen bij vrienden. Bij een onbekende volwassene blijf je bij vous."),
    dict(type="invultekst",
         vraag="Hoe vraag je in het Frans of iemand trager wil spreken? Vul in: « Pouvez-vous parler plus ... ? » Schrijf één woord.",
         antwoord=["lentement"],
         uitleg="Lentement betekent langzaam, traag. Het is lent met de uitgang -ment, zoals veel Franse bijwoorden."),
    dict(type="waarofniet",
         vraag="In een gesprek hoef je alleen je eigen verhaal af te maken; op wat de ander zegt, moet je niet ingaan.",
         antwoord=False,
         uitleg="Speel in op wat je gesprekspartner schrijft of zegt, toon interesse in de ander en toon respect. Een gesprek gaande houden is net dát."),
]

DEEL2 = [
    # --- Klanken en klankencombinaties -------------------------------------
    dict(type="meerkeuze",
         vraag="Welke Franse letters of lettergroepen klinken samen als één klank, zoals de oe in het Nederlandse 'boek'?",
         opties=["ou in bouche",
                 "ou in rouge",
                 "ou in tout",
                 "oi in trois"],
         antwoord=[0, 1, 2],
         uitleg="Ou klinkt als oe. Oi klinkt heel anders, ongeveer als wa: trois klinkt als 'trwa'."),
    dict(type="meerkeuze",
         vraag="Hoe klinkt de lettergroep oi in het Franse woord moi?",
         opties=["ongeveer als wa", "als oo", "als oe", "als ie"],
         antwoord=0,
         uitleg="Moi, trois, voiture: oi klinkt als wa. Daarom hoor je 'mwa'."),
    dict(type="meerkeuze",
         vraag="In welk van deze woorden hoor je de laatste letter niet?",
         opties=["petit", "sac", "avec", "film"],
         antwoord=0,
         uitleg="De slot-t van petit blijft stil. In sac, avec en film hoor je de laatste letter wel. Dat is de relatie tussen klank- en schriftbeeld: wat je ziet staan, zeg je niet altijd."),
    dict(type="waarofniet",
         vraag="De uitgang -ent van ils parlent hoor je niet.",
         antwoord=True,
         uitleg="Ils parlent klinkt precies als il parle. Je hoort het verschil tussen enkelvoud en meervoud daar niet, je ziet het."),
    dict(type="meerkeuze",
         vraag="Waarom klinkt de c anders in cent dan in car?",
         opties=["Voor e en i klinkt de c als een s, voor a, o en u als een k.",
                 "De c klinkt altijd als een s, behalve aan het einde van een woord.",
                 "Dat hangt af van de klemtoon in het woord.",
                 "Dat is een uitzondering die je per woord moet leren."],
         antwoord=0,
         uitleg="Cent en ciel klinken met een s, car en couleur met een k. Dezelfde regel geldt voor de g: gentil tegenover gare."),
    dict(type="meerkeuze",
         vraag="Waarvoor dient de cédille in het woord français?",
         opties=["Ze maakt van de c een s-klank, ook voor een a.",
                 "Ze geeft aan waar de klemtoon valt.",
                 "Ze maakt de a langer.",
                 "Ze toont dat het woord uit een andere taal komt."],
         antwoord=0,
         uitleg="Zonder cédille zou français met een k klinken. Ook in ça en in garçon doet ze dat."),
    dict(type="invultekst",
         vraag="Welk leesteken staat onder de c van garçon? Schrijf het woord.",
         antwoord=["cédille", "cedille"],
         uitleg="Une cédille. Ze staat alleen onder een c, en alleen voor a, o of u."),
    dict(type="waarofniet",
         vraag="De h aan het begin van het Franse woord heure spreek je uit.",
         antwoord=False,
         uitleg="De Franse h hoor je niet. Daarom zeg je l'heure en niet la heure."),
    # --- Accenten en spelling ----------------------------------------------
    dict(type="meerkeuze",
         vraag="Wat is het verschil tussen a en à in « Il a à faire »?",
         opties=["a is de persoonsvorm van avoir, à is een voorzetsel.",
                 "Ze betekenen hetzelfde; het accent is versiering.",
                 "a staat in het enkelvoud, à in het meervoud.",
                 "à wordt langer uitgesproken dan a."],
         antwoord=0,
         uitleg="Il a: hij heeft. À Bruxelles: in Brussel. Eén accent maakt er een ander woord van."),
    dict(type="meerkeuze",
         vraag="Welke woordparen verschillen alleen door een accent, en toch in betekenis?",
         opties=["ou en où",
                 "a en à",
                 "la en là",
                 "les en le"],
         antwoord=[0, 1, 2],
         uitleg="Ou is of, où is waar. La is het lidwoord, là betekent daar. Les en le verschillen niet door een accent maar door hun vorm: meervoud tegenover enkelvoud."),
    dict(type="meerkeuze",
         vraag="Hoe klinkt de é in été, en hoe de è in père?",
         opties=["de é gesloten, zoals in 'beek'; de è open, zoals in 'bed'",
                 "allebei precies hetzelfde",
                 "de é open, zoals in 'bed'; de è gesloten, zoals in 'beek'",
                 "de é kort en de è lang, maar met dezelfde klank"],
         antwoord=0,
         uitleg="Het accent aigu staat schuin naar rechts, het accent grave naar links. Ze zeggen je hoe open je de e moet zeggen."),
    dict(type="invultekst",
         vraag="Hoe heet het accent op de e van élève, dat schuin naar rechts staat? Vul in: « accent ... ». Schrijf één woord.",
         antwoord=["aigu"],
         uitleg="Accent aigu, zoals in été en in élève. Het accent grave helt naar de andere kant: père, très."),
    dict(type="waarofniet",
         vraag="Het verschil tussen een infinitief zoals aller en een voltooid deelwoord zoals allé zie je alleen aan het accent.",
         antwoord=True,
         uitleg="Aller en allé klinken bijna gelijk, maar aller is de infinitief en allé het voltooid deelwoord. Je moet het verschil kennen om de zin juist te lezen én te schrijven."),
    dict(type="meerkeuze",
         vraag="Waarom schrijf je l'ami en niet le ami?",
         opties=["Omdat het lidwoord samentrekt voor een klinker.",
                 "Omdat ami mannelijk is.",
                 "Omdat ami met een a begint en dat een korte klank is.",
                 "Omdat le alleen in het meervoud bestaat."],
         antwoord=0,
         uitleg="Le en la worden l' voor een klinker of een stille h: l'ami, l'école, l'heure."),
    # --- Klemtoon en intonatie ----------------------------------------------
    dict(type="meerkeuze",
         vraag="Waar valt in het Frans de klemtoon van een woord of woordgroep meestal?",
         opties=["op de laatste lettergreep",
                 "op de eerste lettergreep",
                 "op de voorlaatste lettergreep",
                 "dat wisselt per woord en moet je uit het hoofd leren"],
         antwoord=0,
         uitleg="Vergelijk het Nederlandse TE-le-foon met het Franse té-lé-PHONE. Dat is een van de dingen die je Frans Frans doet klinken."),
    dict(type="meerkeuze",
         vraag="Je zegt « Tu viens ? » als vraag. Wat doe je dan met je stem?",
         opties=["Je laat ze op het einde omhooggaan.",
                 "Je laat ze op het einde omlaaggaan.",
                 "Je houdt ze helemaal vlak.",
                 "Je spreekt luider dan bij een mededeling."],
         antwoord=0,
         uitleg="In het Frans kan je van een mededeling een vraag maken met je stem alleen. Dat is intonatie."),
    dict(type="waarofniet",
         vraag="Duidelijk articuleren betekent dat je elke klank goed vormt, ook aan het einde van een woord.",
         antwoord=True,
         uitleg="Articulatie staat samen met woordklemtoon en intonatie in de rij fonologische elementen. Slordig articuleren maakt een zin moeilijk te volgen, ook als de woorden juist zijn."),
    dict(type="meerkeuze",
         vraag="Welke dingen horen bij de rij fonologische elementen en spelling?",
         opties=["de uitspraak van klanken en klankencombinaties",
                 "woordklemtoon, articulatie en intonatie",
                 "de spelling van frequente woorden",
                 "de plaats van het bijvoeglijk naamwoord"],
         antwoord=[0, 1, 2],
         uitleg="De plaats van het bijvoeglijk naamwoord hoort bij de grammatica. De drie andere gaan over hoe het Frans klinkt en hoe je dat schrijft."),
    dict(type="invultekst",
         vraag="Welke letter schrijf je wel maar hoor je nooit aan het begin van een Frans woord, zoals in heure en hôtel? Schrijf de letter.",
         antwoord=["h"],
         uitleg="De Franse h is stil. Daarom schrijf je l'hôtel en un homme met een gebonden uitspraak."),
    dict(type="waarofniet",
         vraag="Omdat je een spellingcontrole mag gebruiken, hoef je de spelling van frequente Franse woorden niet te kennen.",
         antwoord=False,
         uitleg="Een spellingcontrole ziet niet dat je a schreef waar à moest staan, of ou waar où moest staan. Die keuzes blijven jouw werk."),
]
