# -*- coding: utf-8 -*-
"""Soorten zinnen, zinsdelen, voegwoorden en de overeenkomst.

Uit de grammaticalijst van de vakfiche Frans, 2de graad dubbele finaliteit,
ERK-niveau A2. Het laatste stuk van die lijst vraagt:

  * de soorten zinnen: mededelende, vragende, bevelende, uitroepende,
    ontkennende en bevestigende;
  * enkelvoudige en samengestelde zinnen;
  * de zinsdelen: onderwerp, persoonsvorm, lijdend voorwerp en meewerkend
    voorwerp;
  * de overeenkomst: onderwerp met persoonsvorm, naamwoord of voornaamwoord met
    bijvoeglijk naamwoord, en het voltooid deelwoord met être;
  * de frequente nevenschikkende en de zeer frequente onderschikkende
    voegwoorden, met mais, ensuite, donc en parce que als voorbeelden.

De fiche zegt er zelf iets bij dat je bij het schrijven kan gebruiken: je maakt
je tekst levendig door te variëren tussen verschillende soorten zinnen.

Deel 1 gaat over de soorten zinnen: hoe je een vraag stelt, hoe je ontkent, hoe
je uitroept. Deel 2 gaat over de zinsdelen, de voegwoorden en de overeenkomst.
"""

DEEL1 = [
    # --- De soorten zinnen -------------------------------------------------------
    dict(type="meerkeuze",
         vraag="Wat voor soort zin is « Tu viens avec nous ? »",
         opties=["een vragende zin",
                 "een mededelende zin",
                 "een bevelende zin",
                 "een uitroepende zin"],
         antwoord=0,
         uitleg="Une phrase interrogative. In het Frans kan een vraag precies op een mededeling lijken; dan maakt het vraagteken of je stem het verschil."),
    dict(type="meerkeuze",
         vraag="Wat voor soort zin is « Ferme la porte, s'il te plaît. »",
         opties=["een bevelende zin",
                 "een vragende zin",
                 "een uitroepende zin",
                 "een ontkennende zin"],
         antwoord=0,
         uitleg="Une phrase impérative: het werkwoord staat in de impératif en het onderwerp valt weg."),
    dict(type="meerkeuze",
         vraag="Welke zinnen zijn uitroepende zinnen?",
         opties=["Quelle belle journée !",
                 "Comme c'est beau !",
                 "Quel dommage !",
                 "Il fait beau aujourd'hui."],
         antwoord=[0, 1, 2],
         uitleg="Une phrase exclamative begint vaak met quel of comme en eindigt op een uitroepteken. De laatste zin is een gewone mededeling."),
    dict(type="invultekst",
         vraag="Hoe heet een zin die iets meedeelt, met de Franse term? Vul in: « une phrase ... ». Schrijf één woord.",
         antwoord=["déclarative"],
         uitleg="Une phrase déclarative. De vijf andere: interrogative, impérative, exclamative, négative en affirmative."),
    dict(type="waarofniet",
         vraag="Een bevestigende en een ontkennende zin zijn twee van de soorten zinnen in die lijst.",
         antwoord=True,
         uitleg="Une phrase affirmative en une phrase négative. Dezelfde zin kan allebei zijn: je viens tegenover je ne viens pas."),
    # --- De vraagvormen -------------------------------------------------------------
    dict(type="meerkeuze",
         vraag="Op welke drie manieren kan je in het Frans vragen « kom je? »",
         opties=["Tu viens ?",
                 "Est-ce que tu viens ?",
                 "Viens-tu ?",
                 "Que tu viens ?"],
         antwoord=[0, 1, 2],
         uitleg="Met je stem, met est-ce que, of door onderwerp en werkwoord te wisselen. De laatste vorm bestaat niet."),
    dict(type="meerkeuze",
         vraag="Welke vraagvorm klinkt het meest formeel?",
         opties=["Viens-tu ?",
                 "Tu viens ?",
                 "Est-ce que tu viens ?",
                 "Tu viens, oui ?"],
         antwoord=0,
         uitleg="De omgekeerde orde met een koppelteken hoor je vooral in geschreven en formeel Frans. Tu viens ? is de gewone spreektaal."),
    dict(type="invultekst",
         vraag="Welk Frans vraagwoord betekent 'waar'? Schrijf het woord met zijn accent.",
         antwoord=["où"],
         uitleg="Où est la gare ? Zonder accent is ou het woordje 'of'. Eén accent, twee heel verschillende woorden."),
    dict(type="meerkeuze",
         vraag="Welke Franse woorden zijn vraagwoorden?",
         opties=["quand",
                 "pourquoi",
                 "comment",
                 "parce que"],
         antwoord=[0, 1, 2],
         uitleg="Wanneer, waarom, hoe. Parce que is het antwoord op pourquoi: omdat."),
    dict(type="waarofniet",
         vraag="Op pourquoi antwoord je in het Frans met pour que.",
         antwoord=False,
         uitleg="Je antwoordt met parce que: Pourquoi tu restes ? — Parce qu'il pleut. Voor een klinker wordt het parce qu'."),
    # --- De ontkenning ----------------------------------------------------------------
    dict(type="meerkeuze",
         vraag="Hoe ontken je « Je mange »?",
         opties=["Je ne mange pas.",
                 "Je mange pas ne.",
                 "Ne je mange pas.",
                 "Je ne pas mange."],
         antwoord=0,
         uitleg="De ontkenning staat in twee stukken rond het vervoegde werkwoord: ne ... pas."),
    dict(type="meerkeuze",
         vraag="Wat wordt ne voor een klinker?",
         opties=["n'", "ne'", "n", "nee"],
         antwoord=0,
         uitleg="Je n'aime pas, il n'est pas là, elle n'a pas compris."),
    dict(type="invultekst",
         vraag="Vul in: « Je ... jamais au cinéma. » Zet aller in de je-vorm van de présent. Schrijf één woord.",
         antwoord=["vais"],
         uitleg="Je ne vais jamais au cinéma. Ne ... jamais werkt zoals ne ... pas: in twee stukken rond het werkwoord."),
    dict(type="meerkeuze",
         vraag="Welke Franse ontkenningen bestaan er naast ne ... pas?",
         opties=["ne ... jamais",
                 "ne ... rien",
                 "ne ... plus",
                 "ne ... beaucoup"],
         antwoord=[0, 1, 2],
         uitleg="Nooit, niets, niet meer. Beaucoup betekent veel en ontkent dus niets."),
    dict(type="waarofniet",
         vraag="In de passé composé staat de ontkenning rond het voltooid deelwoord: j'ai ne pas mangé.",
         antwoord=False,
         uitleg="Ze staat rond het hulpwerkwoord: je n'ai pas mangé, il n'est pas venu."),
    dict(type="meerkeuze",
         vraag="Hoe ontken je « Il y a du pain »?",
         opties=["Il n'y a pas de pain.",
                 "Il n'y a pas du pain.",
                 "Il y a ne pas de pain.",
                 "Il n'y a pas le pain."],
         antwoord=0,
         uitleg="Na een ontkenning wordt du, de la, des en un gewoon de: pas de pain."),
    # --- Enkelvoudige en samengestelde zinnen -------------------------------------------
    dict(type="meerkeuze",
         vraag="Welke zin is een samengestelde zin?",
         opties=["Je reste à la maison parce qu'il pleut.",
                 "Je reste à la maison.",
                 "Il pleut beaucoup aujourd'hui.",
                 "Ferme la fenêtre."],
         antwoord=0,
         uitleg="Een samengestelde zin heeft meer dan één persoonsvorm: je reste en il pleut. Het voegwoord parce que verbindt ze."),
    dict(type="meerkeuze",
         vraag="Hoeveel persoonsvormen heeft een enkelvoudige zin?",
         opties=["één", "twee", "geen", "minstens twee"],
         antwoord=0,
         uitleg="Eén persoonsvorm, dus één werkwoord dat vervoegd is. Een infinitief erbij maakt de zin niet samengesteld: je veux partir blijft enkelvoudig."),
    dict(type="invultekst",
         vraag="Welk Frans voegwoord betekent 'maar'? Schrijf één woord.",
         antwoord=["mais"],
         uitleg="Mais zet twee stukken tegenover elkaar: c'est cher, mais c'est bon."),
    dict(type="waarofniet",
         vraag="Een tekst wordt levendiger als je afwisselt tussen soorten zinnen.",
         antwoord=True,
         uitleg="Een vraag, een korte uitroep, een langere mededeling: dat leest beter dan tien gelijke zinnen op een rij."),
]

DEEL2 = [
    # --- De zinsdelen ------------------------------------------------------------------
    dict(type="meerkeuze",
         vraag="Wat is het onderwerp in « Mes parents travaillent à Namur »?",
         opties=["mes parents", "travaillent", "à Namur", "Namur"],
         antwoord=0,
         uitleg="Wie werkt? Mes parents. Het onderwerp is le sujet, en de persoonsvorm past zich eraan aan."),
    dict(type="meerkeuze",
         vraag="Wat is de persoonsvorm in « Hier, nous avons visité le musée »?",
         opties=["avons", "visité", "nous", "le musée"],
         antwoord=0,
         uitleg="De persoonsvorm, le verbe conjugué, is het werkwoord dat vervoegd is: avons. Visité is het voltooid deelwoord."),
    dict(type="invultekst",
         vraag="Hoe heet het zinsdeel dat antwoordt op 'wie of wat doet het?', met de Franse term? Schrijf één woord.",
         antwoord=["sujet"],
         uitleg="Le sujet. De persoonsvorm is le verbe conjugué."),
    dict(type="meerkeuze",
         vraag="Welke zinsdelen staan in « Je donne mon numéro à Lila »?",
         opties=["je is het onderwerp",
                 "mon numéro is het lijdend voorwerp",
                 "à Lila is het meewerkend voorwerp",
                 "donne is het lijdend voorwerp"],
         antwoord=[0, 1, 2],
         uitleg="Donne is de persoonsvorm. Wat geef ik? Mon numéro, het COD. Aan wie? À Lila, het COI."),
    dict(type="waarofniet",
         vraag="Een lijdend voorwerp in het Frans staat zonder voorzetsel, een meewerkend voorwerp met à.",
         antwoord=True,
         uitleg="Je regarde le film: geen voorzetsel, dus COD. Je parle à mon frère: met à, dus COI."),
    dict(type="meerkeuze",
         vraag="Hoe vind je het lijdend voorwerp in een Franse zin?",
         opties=["Je vraagt: wie of wat ondergaat de handeling?",
                 "Je kijkt naar het eerste woord van de zin.",
                 "Je zoekt het woord met een voorzetsel ervoor.",
                 "Je neemt altijd het laatste woord van de zin."],
         antwoord=0,
         uitleg="Je lis un livre: wat lees ik? Un livre. Het COD kan ook een voornaamwoord zijn: je le lis."),
    # --- De voegwoorden ---------------------------------------------------------------
    dict(type="meerkeuze",
         vraag="Welke Franse voegwoorden geven een gevolg of een reden?",
         opties=["donc",
                 "parce que",
                 "car",
                 "ensuite"],
         antwoord=[0, 1, 2],
         uitleg="Dus, omdat, want. Ensuite zegt alleen dat iets daarna komt, en geeft geen reden of gevolg."),
    dict(type="meerkeuze",
         vraag="Vul in: « Il pleut, ... je prends le bus. »",
         opties=["donc", "parce que", "mais", "ensuite"],
         antwoord=0,
         uitleg="Donc betekent dus: de regen is de reden, de bus het gevolg."),
    dict(type="invultekst",
         vraag="Vul in: « Je reste à la maison ... il pleut. » Welk voegwoord geeft een reden? Schrijf de twee woorden.",
         antwoord=["parce que", "parce qu'"],
         uitleg="Parce qu'il pleut: omdat het regent. Voor een klinker wordt que qu'."),
    dict(type="meerkeuze",
         vraag="Welk voegwoord zet twee stukken tegenover elkaar?",
         opties=["mais", "donc", "et", "ensuite"],
         antwoord=0,
         uitleg="C'est petit, mais c'est confortable. Mais is het voegwoord van de tegenstelling."),
    dict(type="waarofniet",
         vraag="Et, mais, donc en car zijn nevenschikkende voegwoorden: ze verbinden twee gelijkwaardige stukken.",
         antwoord=True,
         uitleg="Parce que en quand zijn onderschikkend: ze maken van het tweede stuk een bijzin."),
    dict(type="meerkeuze",
         vraag="Welke woorden maken van het tweede stuk een bijzin?",
         opties=["parce que",
                 "quand",
                 "si",
                 "et"],
         antwoord=[0, 1, 2],
         uitleg="Omdat, wanneer, als: die drie onderschikken. Et zet twee stukken gewoon naast elkaar."),
    dict(type="invultekst",
         vraag="Welk Frans voegwoord betekent 'wanneer' of 'toen'? Schrijf één woord.",
         antwoord=["quand"],
         uitleg="Quand j'étais petit, quand il arrive. Hetzelfde woord dient ook als vraagwoord: quand viens-tu ?"),
    dict(type="waarofniet",
         vraag="Signaalwoorden zoals d'abord, ensuite en enfin verbinden de delen van één zin, zoals een voegwoord.",
         antwoord=False,
         uitleg="Ze verbinden stukken van een tekst, niet de delen van één zin. Toch worden ze samen met de voegwoorden beoordeeld, in de rij tekststructuur en samenhang."),
    # --- De overeenkomst ----------------------------------------------------------------
    dict(type="meerkeuze",
         vraag="Wat is er mis met « Les élèves travaille bien »?",
         opties=["De persoonsvorm past niet bij het onderwerp: het moet travaillent zijn.",
                 "Les élèves moet enkelvoud zijn.",
                 "Bien moet voor het werkwoord staan.",
                 "Er is niets mis met die zin."],
         antwoord=0,
         uitleg="Dat is de overeenkomst tussen onderwerp en persoonsvorm. Les élèves is meervoud, dus travaillent."),
    dict(type="meerkeuze",
         vraag="Wat is er mis met « Ma sœur est content »?",
         opties=["Het bijvoeglijk naamwoord moet contente zijn.",
                 "Est moet sont zijn.",
                 "Ma moet mon zijn.",
                 "Er is niets mis met die zin."],
         antwoord=0,
         uitleg="Het bijvoeglijk naamwoord past zich aan het naamwoord aan: ma sœur est contente."),
    dict(type="invultekst",
         vraag="Vul in: « Elles sont ... hier. » Het werkwoord is arriver, in de passé composé met être. Schrijf één woord.",
         antwoord=["arrivées"],
         uitleg="Elles sont arrivées: met être past het voltooid deelwoord zich aan het onderwerp aan, hier vrouwelijk meervoud."),
    dict(type="meerkeuze",
         vraag="Welke zinnen hebben hun overeenkomst juist?",
         opties=["Mes amis sont partis.",
                 "Elle est née en 2010.",
                 "Nous nous sommes levés tôt.",
                 "Elles ont parties ensemble."],
         antwoord=[0, 1, 2],
         uitleg="Partir gaat met être, dus elles sont parties en niet elles ont parties. De drie andere zijn juist."),
    dict(type="waarofniet",
         vraag="Met avoir past het voltooid deelwoord zich aan het onderwerp aan.",
         antwoord=False,
         uitleg="Met avoir blijft het gelijk: elle a mangé, ils ont mangé. Alleen met être past het zich aan."),
    dict(type="meerkeuze",
         vraag="Welke drie soorten overeenkomst staan in die grammaticalijst?",
         opties=["onderwerp met persoonsvorm",
                 "naamwoord of voornaamwoord met bijvoeglijk naamwoord",
                 "het voltooid deelwoord met être",
                 "het bijwoord met het werkwoord"],
         antwoord=[0, 1, 2],
         uitleg="Een bijwoord verandert nooit van vorm, dus daar valt niets te laten overeenkomen."),
]
