# -*- coding: utf-8 -*-
"""Boodschappen doen en de tafel dekken.

Van de vakfiche gezondheid, zorg en welzijn 2DU (2027), bouwsteen oriënteren
op huishoudelijke taken: de principes om voedselverspilling tegen te gaan,
milieubewust en economisch winkelen, het opstellen van een boodschappenlijst,
en het dekken van de tafel voor het ontbijt, de broodlunch en de warme
maaltijd.

Deel 1 zijn de verspilling en de boodschappen.
Deel 2 is de tafel dekken.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Welke principes helpen tegen voedselverspilling?",
         opties=["maaltijden plannen",
                 "je koelkast organiseren",
                 "juiste porties serveren",
                 "alles in het groot kopen"],
         antwoord=[0, 1, 2],
         uitleg="In het groot kopen leidt juist tot verspilling als je het niet op tijd opkrijgt."),
    dict(type="meerkeuze",
         vraag="Waarom plan je je maaltijden vooraf?",
         opties=["je koopt niet te veel",
                 "je betaalt meer erbij",
                 "je kookt minder lekker",
                 "je hebt meer tijd nodig"],
         antwoord=0,
         uitleg="Wie weet wat hij gaat koken, koopt precies wat nodig is en gooit minder weg."),
    dict(type="meerkeuze",
         vraag="Waarvoor dient een koelbox bij het winkelen?",
         opties=["koude waren koel houden",
                 "de boodschappen wegen erbij",
                 "de prijzen vergelijken erbij",
                 "de tassen lichter maken erbij"],
         antwoord=0,
         uitleg="Zo blijft de koudeketen onderbroken van de winkel tot thuis."),
    dict(type="meerkeuze",
         vraag="Wat bedoelt men met gebruik jouw zintuigen?",
         opties=["kijken en ruiken",
                 "blind alles weggooien",
                 "enkel de datum lezen erbij",
                 "de verpakking wegen erbij"],
         antwoord=0,
         uitleg="Veel voedsel is na de THT-datum nog prima. Kijken, ruiken en proeven zegt meer dan de datum alleen."),
    dict(type="meerkeuze",
         vraag="Wat is een creatieve kok?",
         opties=["hij werkt met restjes",
                 "hij koopt altijd nieuw erbij",
                 "hij gooit de restjes weg erbij",
                 "hij kookt altijd hetzelfde erbij"],
         antwoord=0,
         uitleg="Van restjes groente maak je soep, van oud brood wentelteefjes."),
    dict(type="meerkeuze",
         vraag="Waarom serveer je juiste porties?",
         opties=["er blijft niets over",
                 "het bord lijkt voller erbij",
                 "het eten koelt trager af erbij",
                 "de gasten eten meer erbij"],
         antwoord=0,
         uitleg="Wat op het bord blijft liggen, gaat meestal de vuilnisbak in. Bijnemen kan altijd nog."),
    dict(type="meerkeuze",
         vraag="Waarmee hou je rekening bij een boodschappenlijst?",
         opties=["wat je al in huis hebt",
                 "het menu van de week",
                 "het aantal personen",
                 "de kleur van de tassen"],
         antwoord=[0, 1, 2],
         uitleg="Eerst kijken wat er al staat, dan het menu, dan het aantal eters."),
    dict(type="meerkeuze",
         vraag="Waarom maak je een boodschappenlijst?",
         opties=["je koopt gerichter",
                 "je blijft langer winkelen",
                 "je vergeet meer dingen",
                 "je betaalt altijd meer erbij"],
         antwoord=0,
         uitleg="Met een lijst koop je wat je nodig hebt en minder wat je niet nodig hebt."),
    dict(type="meerkeuze",
         vraag="Wat is een milieubewuste keuze bij het winkelen?",
         opties=["seizoensgroenten kopen",
                 "groenten van ver kopen",
                 "alles apart verpakt kopen",
                 "elke dag opnieuw winkelen"],
         antwoord=0,
         uitleg="Groenten van het seizoen en van dichtbij hebben minder transport en verwarming nodig."),
    dict(type="meerkeuze",
         vraag="Hoe winkel je milieubewust?",
         opties=["met een eigen tas",
                 "met een nieuwe plastic zak",
                 "met losse verpakkingen erbij",
                 "met de auto voor één brood"],
         antwoord=0,
         uitleg="Een herbruikbare draagtas en zo weinig mogelijk verpakking schelen meteen afval."),
    dict(type="meerkeuze",
         vraag="Wat is economisch handelen bij boodschappen?",
         opties=["prijzen vergelijken",
                 "promoties gebruiken",
                 "niet te veel kopen",
                 "altijd het duurste kopen"],
         antwoord=[0, 1, 2],
         uitleg="Kostenbewust kopen is vergelijken, gericht kiezen en niet meer kopen dan je opkrijgt."),
    dict(type="meerkeuze",
         vraag="Waarom is een promotie niet altijd voordelig?",
         opties=["je koopt meer dan nodig",
                 "de prijs is altijd hoger",
                 "het product is altijd slecht",
                 "de winkel is dan gesloten"],
         antwoord=0,
         uitleg="Drie halen, twee betalen is geen besparing als het derde pak bederft."),
    dict(type="meerkeuze",
         vraag="Wat doe je met groenten die al wat langer liggen?",
         opties=["er soep van maken",
                 "meteen weggooien erbij",
                 "in de vuilnisbak gooien",
                 "op het aanrecht laten liggen"],
         antwoord=0,
         uitleg="Soep, een ovenschotel of een wok redt groenten die er niet meer mooi uitzien."),
    dict(type="waarofniet",
         vraag="Voedselverspilling kost ook geld.",
         antwoord=True,
         uitleg="Alles wat je weggooit, heb je eerst betaald."),
    dict(type="waarofniet",
         vraag="Je hoeft niet te plannen om verspilling te vermijden.",
         antwoord=False,
         uitleg="Maaltijden en aankopen zorgvuldig plannen staat als eerste principe in het rijtje."),
    dict(type="waarofniet",
         vraag="Een eigen draagtas meenemen is een milieubewuste keuze.",
         antwoord=True,
         uitleg="Draagtassen en een koelbox staan uitdrukkelijk in het rijtje."),
    dict(type="waarofniet",
         vraag="Grote porties serveren helpt tegen verspilling.",
         antwoord=False,
         uitleg="Juist de goede porties serveren helpt. Wat op het bord blijft, gaat weg."),
    dict(type="invultekst",
         vraag="Hoe noem je het weggooien van eten dat nog goed was? Hoogstens drie woorden.",
         antwoord=["voedselverspilling", "verspilling", "voedselverlies"],
         uitleg="Voedselverspilling."),
    dict(type="invultekst",
         vraag="Wat neem je mee naar de winkel om koude waren koel te houden? Eén woord.",
         antwoord=["koelbox", "een koelbox", "koeltas"],
         uitleg="Een koelbox."),
    dict(type="invultekst",
         vraag="Wat maak je voor je gaat winkelen, zodat je niets vergeet? Hoogstens drie woorden.",
         antwoord=["boodschappenlijst", "een boodschappenlijst", "boodschappenlijstje"],
         uitleg="Een boodschappenlijst."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Waarom dek je de tafel mooi?",
         opties=["het nodigt uit",
                 "het gaat sneller erbij",
                 "het kost minder geld erbij",
                 "het is altijd verplicht erbij"],
         antwoord=0,
         uitleg="Een verzorgde tafel maakt van eten een rustig en aangenaam moment."),
    dict(type="meerkeuze",
         vraag="Welke maaltijden dek je bij een gezin?",
         opties=["het ontbijt",
                 "de warme maaltijd",
                 "de broodlunch",
                 "de koffiepauze"],
         antwoord=[0, 1, 2],
         uitleg="De gezinsmaaltijd is het ontbijt of de broodlunch, de warme maaltijd en het klassieke diner."),
    dict(type="meerkeuze",
         vraag="Aan welke kant leg je het mes?",
         opties=["rechts van het bord",
                 "links van het bord erbij",
                 "boven het bord erbij",
                 "onder het bord erbij"],
         antwoord=0,
         uitleg="Het mes ligt rechts, want je snijdt meestal met de rechterhand."),
    dict(type="meerkeuze",
         vraag="Aan welke kant leg je de vork?",
         opties=["links van het bord",
                 "rechts van het bord erbij",
                 "boven het bord erbij",
                 "onder het bord erbij"],
         antwoord=0,
         uitleg="De vork ligt links, tegenover het mes."),
    dict(type="meerkeuze",
         vraag="Waar staat het glas op een gedekte tafel?",
         opties=["rechtsboven het bord",
                 "linksboven het bord erbij",
                 "onder het bord erbij",
                 "naast de stoel erbij"],
         antwoord=0,
         uitleg="Het glas staat rechtsboven, aan de kant van het mes."),
    dict(type="meerkeuze",
         vraag="Hoe ligt de snijkant van het mes?",
         opties=["naar het bord toe",
                 "van het bord weg erbij",
                 "naar boven gericht erbij",
                 "naar de buur gericht erbij"],
         antwoord=0,
         uitleg="De snijkant wijst naar het bord. Zo wijst ze niet naar je buur."),
    dict(type="meerkeuze",
         vraag="Waar leg je het dessertbestek?",
         opties=["boven het bord",
                 "onder het bord erbij",
                 "links van de vork erbij",
                 "rechts van het mes erbij"],
         antwoord=0,
         uitleg="Het dessertbestek ligt boven het bord, klaar voor na de maaltijd."),
    dict(type="meerkeuze",
         vraag="Wat hoort bij een gedekte ontbijttafel?",
         opties=["een bord en een mes",
                 "enkel een soeplepel erbij",
                 "alleen een vork erbij",
                 "een wijnglas per persoon"],
         antwoord=0,
         uitleg="Voor een ontbijt of een broodlunch volstaan een bord, een mes en een tas of glas."),
    dict(type="meerkeuze",
         vraag="Waarom zet je niet meer bestek dan nodig?",
         opties=["het is onnodig werk",
                 "het staat chiquer erbij",
                 "het gaat sneller erbij",
                 "het is altijd verplicht"],
         antwoord=0,
         uitleg="Alles wat je dekt, moet je ook afwassen. Je dekt wat de maaltijd vraagt."),
    dict(type="meerkeuze",
         vraag="Waarmee dek je een tafel voor een warme maaltijd?",
         opties=["een bord",
                 "een mes",
                 "een vork",
                 "een boek"],
         antwoord=[0, 1, 2],
         uitleg="Bord, mes, vork en een glas. Een boek hoort niet op een gedekte tafel."),
    dict(type="meerkeuze",
         vraag="Waar ligt het servet?",
         opties=["op of naast het bord",
                 "onder de stoel erbij",
                 "boven het glas erbij",
                 "achter het bord erbij"],
         antwoord=0,
         uitleg="Het servet ligt op het bord of links ernaast, onder de vork."),
    dict(type="meerkeuze",
         vraag="Wat controleer je voor de gasten aanschuiven?",
         opties=["of alles proper is",
                 "of het bord warm is",
                 "of de stoel nieuw is",
                 "of de tafel groot is"],
         antwoord=0,
         uitleg="Propere borden, proper bestek en een propere tafel: dat merkt iedereen meteen."),
    dict(type="meerkeuze",
         vraag="Wat maakt een tafel aantrekkelijk?",
         opties=["een propere tafel",
                 "een nette schikking",
                 "een bloem of kaars",
                 "een vuile vaatdoek"],
         antwoord=[0, 1, 2],
         uitleg="Een vuile vaatdoek op tafel bederft meteen de hele indruk."),
    dict(type="waarofniet",
         vraag="Het mes ligt rechts van het bord.",
         antwoord=True,
         uitleg="Mes rechts, vork links."),
    dict(type="waarofniet",
         vraag="Het glas staat links van het bord.",
         antwoord=False,
         uitleg="Het glas staat rechtsboven, aan de kant van het mes."),
    dict(type="waarofniet",
         vraag="Een mooi gedekte tafel maakt de maaltijd aangenamer.",
         antwoord=True,
         uitleg="Daarom hoort het dekken van de tafel bij de maaltijdzorg."),
    dict(type="waarofniet",
         vraag="Bij een ontbijt dek je altijd met een soeplepel.",
         antwoord=False,
         uitleg="Je dekt wat de maaltijd vraagt. Bij een ontbijt is dat geen soeplepel."),
    dict(type="invultekst",
         vraag="Aan welke kant van het bord ligt de vork? Eén woord.",
         antwoord=["links", "aan links", "de linkerkant"],
         uitleg="Links."),
    dict(type="invultekst",
         vraag="Aan welke kant van het bord ligt het mes? Eén woord.",
         antwoord=["rechts", "aan rechts", "de rechterkant"],
         uitleg="Rechts."),
    dict(type="invultekst",
         vraag="Hoe noem je het doekje dat je op je schoot legt tijdens het eten? Eén woord.",
         antwoord=["servet", "een servet", "het servet"],
         uitleg="Een servet."),
]
