# -*- coding: utf-8 -*-
"""Gezondheid in kaart: Gordon en het ICF-schema.

Van de vakfiche gezondheid, zorg en welzijn 2DU (2027), bouwsteen gezondheid
en welzijn: de systematische aanpak om een probleem te herkennen en op te
lossen, de elf gezondheidspatronen van Gordon, en het ICF-schema met
gezondheidstoestand, ik en omgeving.

Deel 1 zijn de gezondheidspatronen van Gordon.
Deel 2 is het ICF-schema.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Waarvoor dienen de gezondheidspatronen van Gordon?",
         opties=["om iemand te leren kennen",
                 "om een ziekte te genezen ervan",
                 "om een medicijn te kiezen ervan",
                 "om de kostprijs te berekenen"],
         antwoord=0,
         uitleg="Met de elf patronen breng je het totale functioneren van een persoon in kaart."),
    dict(type="meerkeuze",
         vraag="Hoeveel patronen onderscheidt Gordon?",
         opties=["elf",
                 "tien patronen in totaal",
                 "twaalf patronen in totaal",
                 "zeven patronen in totaal"],
         antwoord=0,
         uitleg="Elf patronen, van gezondheidsbeleving tot waarden en levensopvatting."),
    dict(type="meerkeuze",
         vraag="Welke patronen horen bij Gordon?",
         opties=["slaap en rust",
                 "uitscheiding",
                 "rol en relatie",
                 "winst en verlies"],
         antwoord=[0, 1, 2],
         uitleg="Winst en verlies hoort bij een boekhouding, niet bij de patronen van Gordon."),
    dict(type="meerkeuze",
         vraag="Onder welk patroon valt wat iemand eet?",
         opties=["voeding en stofwisseling",
                 "slaap en rust van de dag",
                 "rol en relatie met anderen",
                 "waarden en levensopvatting"],
         antwoord=0,
         uitleg="Het patroon voeding en stofwisseling gaat over eten, drinken en wat het lichaam ermee doet."),
    dict(type="meerkeuze",
         vraag="Onder welk patroon valt naar het toilet gaan?",
         opties=["uitscheiding",
                 "slaap en rust erbij",
                 "zelfbeleving erbij",
                 "rol en relatie erbij"],
         antwoord=0,
         uitleg="Uitscheiding gaat over plassen, stoelgang en zweten."),
    dict(type="meerkeuze",
         vraag="Onder welk patroon valt hoe iemand over zichzelf denkt?",
         opties=["zelfbeleving",
                 "uitscheiding erbij",
                 "slaap en rust erbij",
                 "activiteiten erbij"],
         antwoord=0,
         uitleg="Zelfbeleving gaat over het zelfbeeld en het gevoel van eigenwaarde."),
    dict(type="meerkeuze",
         vraag="Onder welk patroon valt omgaan met een moeilijke periode?",
         opties=["stressverwerking",
                 "slaap en rust erbij",
                 "uitscheiding erbij",
                 "activiteiten erbij"],
         antwoord=0,
         uitleg="Stressverwerking gaat over hoe iemand spanning en tegenslag aanpakt."),
    dict(type="meerkeuze",
         vraag="Onder welk patroon vallen het geloof en de overtuigingen van iemand?",
         opties=["waarden en levensopvatting",
                 "de uitscheiding van het lichaam",
                 "de voeding en de stofwisseling",
                 "het patroon van slaap en rust"],
         antwoord=0,
         uitleg="Waarden en levensopvatting gaat over wat iemand belangrijk vindt in het leven."),
    dict(type="meerkeuze",
         vraag="Wat valt onder het patroon waarneming en cognitie?",
         opties=["zien",
                 "horen",
                 "onthouden",
                 "plassen"],
         antwoord=[0, 1, 2],
         uitleg="Plassen hoort bij uitscheiding. Waarneming en cognitie gaat over de zintuigen, het denken en het onthouden."),
    dict(type="meerkeuze",
         vraag="Wat levert een systematische aanpak op?",
         opties=["je vergeet minder",
                 "je werkt sneller",
                 "je kan het uitleggen",
                 "je hoeft niet te kijken"],
         antwoord=[0, 1, 2],
         uitleg="Een vaste werkwijze vervangt het kijken niet; ze zorgt dat je niets overslaat."),
    dict(type="meerkeuze",
         vraag="Wat is de eerste stap bij het oplossen van een probleem?",
         opties=["het probleem benoemen",
                 "meteen een oplossing kiezen",
                 "het probleem laten liggen",
                 "een ander laten beslissen"],
         antwoord=0,
         uitleg="Eerst vaststellen wat er precies aan de hand is, pas daarna zoeken naar een oplossing."),
    dict(type="meerkeuze",
         vraag="Waarom gebruik je een vast schema zoals dat van Gordon?",
         opties=["je kijkt naar het geheel",
                 "je werkt dan veel goedkoper",
                 "je hebt geen gesprek nodig",
                 "je kan de diagnose stellen"],
         antwoord=0,
         uitleg="Zonder schema kijk je enkel naar wat opvalt en mis je de rest van het functioneren."),
    dict(type="meerkeuze",
         vraag="Onder welk patroon valt hoe iemand zijn eigen gezondheid ziet?",
         opties=["gezondheidsbeleving",
                 "de rol en de relatie erbij",
                 "de slaap en de rust erbij",
                 "de uitscheiding van afval"],
         antwoord=0,
         uitleg="Gezondheidsbeleving en instandhouding: hoe iemand zijn gezondheid ervaart en wat hij ervoor doet."),
    dict(type="waarofniet",
         vraag="Gordon kijkt enkel naar het lichaam.",
         antwoord=False,
         uitleg="De patronen gaan ook over relaties, zelfbeeld, stress en waarden."),
    dict(type="waarofniet",
         vraag="De patronen van Gordon hangen met elkaar samen.",
         antwoord=True,
         uitleg="Verandert er iets in één patroon, dan voel je dat vaak in een ander."),
    dict(type="waarofniet",
         vraag="Slecht slapen kan het patroon activiteiten beïnvloeden.",
         antwoord=True,
         uitleg="Wie te weinig slaapt, beweegt en onderneemt doorgaans minder."),
    dict(type="waarofniet",
         vraag="Gordon gebruik je om een medische diagnose te stellen.",
         antwoord=False,
         uitleg="Een diagnose stelt een arts. Gordon brengt het functioneren in kaart."),
    dict(type="invultekst",
         vraag="Hoeveel gezondheidspatronen onderscheidt Gordon? Een getal.",
         antwoord=["11", "elf"],
         uitleg="Elf."),
    dict(type="invultekst",
         vraag="Hoe noem je bij Gordon het patroon over omgaan met spanning? Eén woord.",
         antwoord=["stressverwerking", "de stressverwerking"],
         uitleg="Stressverwerking."),
    dict(type="invultekst",
         vraag="Welk patroon van Gordon gaat over wat iemand belangrijk vindt in het leven? Hoogstens drie woorden.",
         antwoord=["waarden en levensopvatting", "levensopvatting", "waarden"],
         uitleg="Waarden en levensopvatting."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Waarvoor dient het ICF-schema?",
         opties=["om functioneren te bekijken",
                 "om een ziekte te benoemen erbij",
                 "om een medicijn te kiezen erbij",
                 "om een rekening op te maken"],
         antwoord=0,
         uitleg="Het ICF brengt het totale functioneren in kaart, met de persoon en de omgeving erbij."),
    dict(type="meerkeuze",
         vraag="Welke delen heeft de gezondheidstoestand in het ICF?",
         opties=["lichaam",
                 "doen",
                 "samen",
                 "geld"],
         antwoord=[0, 1, 2],
         uitleg="Lichaam, doen en samen. Geld hoort niet bij de gezondheidstoestand."),
    dict(type="meerkeuze",
         vraag="Welke vraag hoort bij lichaam in het ICF?",
         opties=["hoe werkt het lichaam",
                 "wie zijn de vrienden erbij",
                 "welk werk doet de persoon",
                 "hoeveel geld is er over"],
         antwoord=0,
         uitleg="Het deel lichaam gaat over de werking van de organen en de lichaamsfuncties."),
    dict(type="meerkeuze",
         vraag="Welke vraag hoort bij doen in het ICF?",
         opties=["wat doet iemand zelf",
                 "hoe werkt het lichaam erbij",
                 "wie woont er in de buurt erbij",
                 "hoeveel slaapt de persoon"],
         antwoord=0,
         uitleg="Het deel doen gaat over de activiteiten die iemand uitvoert, zoals zich wassen of koken."),
    dict(type="meerkeuze",
         vraag="Welke vraag hoort bij samen in het ICF?",
         opties=["doet iemand mee",
                 "hoe werkt de lever erbij",
                 "wat eet de persoon erbij",
                 "hoe lang slaapt iemand"],
         antwoord=0,
         uitleg="Het deel samen gaat over deelnemen aan de maatschappij: werken, school, vrije tijd."),
    dict(type="meerkeuze",
         vraag="Wat zijn persoonlijke factoren in het ICF?",
         opties=["leeftijd en karakter",
                 "de buurt waar je woont",
                 "de school in het dorp",
                 "het werk van je vader"],
         antwoord=0,
         uitleg="Persoonlijke factoren horen bij het ik: leeftijd, geslacht, karakter, achtergrond."),
    dict(type="meerkeuze",
         vraag="Wat hoort bij de omgeving in het ICF?",
         opties=["de woning",
                 "het karakter erbij",
                 "de leeftijd erbij",
                 "de erfelijkheid erbij"],
         antwoord=0,
         uitleg="De omgeving is alles buiten de persoon: de woning, het gezin, de buurt, de diensten."),
    dict(type="meerkeuze",
         vraag="Wat hoort bij de externe factoren in het ICF?",
         opties=["de woonplaats",
                 "het gezin",
                 "de school",
                 "het karakter"],
         antwoord=[0, 1, 2],
         uitleg="Het karakter is een persoonlijke factor; de andere drie liggen buiten de persoon."),
    dict(type="meerkeuze",
         vraag="Waarom kijkt het ICF ook naar de omgeving?",
         opties=["ze helpt of hindert",
                 "ze kost veel geld erbij",
                 "ze is altijd hetzelfde erbij",
                 "ze verandert nooit erbij"],
         antwoord=0,
         uitleg="Een lift of een behulpzame buur helpt; een trap of lawaai hindert."),
    dict(type="meerkeuze",
         vraag="Een kind in een rolstoel kan niet in de klas omdat er een trap is. Wat is die trap in het ICF?",
         opties=["een externe factor",
                 "een persoonlijke factor",
                 "een probleem van het lichaam",
                 "een keuze van het kind erbij"],
         antwoord=0,
         uitleg="De trap ligt in de omgeving. Het lichaam van het kind is niet het probleem, het gebouw is het."),
    dict(type="meerkeuze",
         vraag="Wat is het verschil tussen Gordon en het ICF?",
         opties=["Gordon heeft elf patronen",
                 "het ICF kijkt enkel naar geld",
                 "Gordon kijkt alleen naar ziekte",
                 "het ICF gaat over medicijnen"],
         antwoord=0,
         uitleg="Gordon werkt met elf patronen, het ICF met gezondheidstoestand, ik en omgeving."),
    dict(type="meerkeuze",
         vraag="Wat kan je met het ICF en met Gordon?",
         opties=["het functioneren bekijken",
                 "een plan opstellen",
                 "de sterktes zien",
                 "een diagnose stellen"],
         antwoord=[0, 1, 2],
         uitleg="Een diagnose stellen is werk van een arts. Beide schema's brengen het functioneren in kaart."),
    dict(type="meerkeuze",
         vraag="Wat betekent individuele achtergrond in het ICF?",
         opties=["wat iemand meemaakte",
                 "de trap in het gebouw erbij",
                 "de bus die niet rijdt erbij",
                 "het weer van die dag erbij"],
         antwoord=0,
         uitleg="De individuele achtergrond hoort bij het ik: opleiding, ervaringen, gewoonten."),
    dict(type="waarofniet",
         vraag="Het ICF kijkt alleen naar wat niet lukt.",
         antwoord=False,
         uitleg="Het ICF brengt ook in kaart wat wel lukt en wat de omgeving aan steun biedt."),
    dict(type="waarofniet",
         vraag="In het ICF hangen gezondheidstoestand, ik en omgeving samen.",
         antwoord=True,
         uitleg="De drie beïnvloeden elkaar. Daarom staan ze in één schema."),
    dict(type="waarofniet",
         vraag="Een aangepaste woning kan het functioneren verbeteren.",
         antwoord=True,
         uitleg="De omgeving kan een drempel wegnemen, zonder dat er aan het lichaam iets verandert."),
    dict(type="waarofniet",
         vraag="Persoonlijke factoren en externe factoren zijn hetzelfde.",
         antwoord=False,
         uitleg="Persoonlijke factoren zitten bij het ik, externe factoren in de omgeving."),
    dict(type="invultekst",
         vraag="Welk onderdeel van het ICF gaat over meedoen in de maatschappij? Eén woord.",
         antwoord=["samen", "het samen"],
         uitleg="Samen."),
    dict(type="invultekst",
         vraag="Welk onderdeel van het ICF gaat over de werking van de organen? Eén woord.",
         antwoord=["lichaam", "het lichaam"],
         uitleg="Lichaam."),
    dict(type="invultekst",
         vraag="Hoe noem je in het ICF de factoren buiten de persoon? Hoogstens drie woorden.",
         antwoord=["externe factoren", "de externe factoren", "omgeving"],
         uitleg="De externe factoren, samen de omgeving."),
]
