# -*- coding: utf-8 -*-
"""Kwaliteitsbewust handelen.

Van de vakfiche gezondheid, zorg en welzijn 2DU (2027), bouwsteen
kwaliteitsbewust handelen: de zeven factoren, respectvol en belevingsgericht
handelen, methodisch handelen met het OVUR-schema en de 5S-methode,
hygiënisch en veilig handelen met de gevarensymbolen, gevarentekens en het
etiket, ergonomisch handelen, duurzaam handelen met de Ladder van Lansink en
het sorteren van afval, en economisch handelen.

Deel 1 zijn de zeven factoren, respectvol en methodisch handelen.
Deel 2 zijn veilig, ergonomisch, duurzaam en economisch handelen.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Welke factoren horen bij kwaliteitsbewust handelen?",
         opties=["hygiënisch handelen",
                 "veilig handelen",
                 "ergonomisch handelen",
                 "winstgevend handelen"],
         antwoord=[0, 1, 2],
         uitleg="De zeven factoren zijn respectvol en belevingsgericht, methodisch, hygiënisch, veilig, ergonomisch, milieubewust en economisch."),
    dict(type="meerkeuze",
         vraag="Hoeveel factoren heeft kwaliteitsbewust handelen?",
         opties=["zeven",
                 "vijf factoren in totaal",
                 "acht factoren in totaal",
                 "drie factoren in totaal"],
         antwoord=0,
         uitleg="Zeven factoren. Samen bepalen ze of je werk kwaliteit heeft."),
    dict(type="meerkeuze",
         vraag="Wat is respectvol handelen?",
         opties=["respect tonen",
                 "enkel aan jezelf denken",
                 "zo snel mogelijk werken",
                 "alles alleen willen doen"],
         antwoord=0,
         uitleg="Respect voor jezelf, voor anderen en voor het materiaal waarmee je werkt."),
    dict(type="meerkeuze",
         vraag="Waarvoor heb je respect bij respectvol handelen?",
         opties=["voor jezelf",
                 "voor anderen",
                 "voor het materiaal",
                 "voor het weer"],
         antwoord=[0, 1, 2],
         uitleg="Drie richtingen: jezelf, de anderen en het materiaal."),
    dict(type="meerkeuze",
         vraag="Wat is belevingsgericht handelen?",
         opties=["kijken wat de ander voelt",
                 "je eigen plan volgen erbij",
                 "de regels strikt toepassen",
                 "de snelste weg kiezen erbij"],
         antwoord=0,
         uitleg="Je houdt rekening met de gevoelens, de noden, de wensen en de beperkingen van de ander."),
    dict(type="meerkeuze",
         vraag="Wat hoort bij de belevingswereld van iemand?",
         opties=["zijn wensen",
                 "de prijs van het product",
                 "de kleur van de muren erbij",
                 "het uur van de dag erbij"],
         antwoord=0,
         uitleg="De belevingswereld bestaat uit gevoelens, noden of behoeften, wensen en beperkingen."),
    dict(type="meerkeuze",
         vraag="Wat is methodisch handelen?",
         opties=["volgens een vast plan",
                 "zonder nadenken beginnen",
                 "elke keer anders werken",
                 "zo traag mogelijk werken"],
         antwoord=0,
         uitleg="Je werkt in een vaste orde, zodat je niets vergeet en het resultaat telkens goed is."),
    dict(type="meerkeuze",
         vraag="Wat is de eerste stap van het OVUR-schema?",
         opties=["oriënteren",
                 "voorbereiden erbij",
                 "uitvoeren erbij",
                 "reflecteren erbij"],
         antwoord=0,
         uitleg="Eerst oriënteren: wat is de opdracht precies? Daarna voorbereiden, uitvoeren en reflecteren."),
    dict(type="meerkeuze",
         vraag="Wat doe je bij de R van OVUR?",
         opties=["terugblikken",
                 "de taak uitvoeren erbij",
                 "het materiaal klaarzetten",
                 "de opdracht eerst lezen"],
         antwoord=0,
         uitleg="Reflecteren: ging het goed, wat zou je een volgende keer anders doen?"),
    dict(type="meerkeuze",
         vraag="Welke huishoudelijke taken zijn er?",
         opties=["maaltijdzorg",
                 "interieurzorg",
                 "linnenzorg",
                 "boekhouding"],
         antwoord=[0, 1, 2],
         uitleg="De drie huishoudelijke taken zijn maaltijdzorg, interieurzorg en linnenzorg."),
    dict(type="meerkeuze",
         vraag="Waarvoor dient de 5S-methode?",
         opties=["je werkpost schikken",
                 "de was sorteren erbij",
                 "de maaltijd bereiden erbij",
                 "de rekening betalen erbij"],
         antwoord=0,
         uitleg="De 5S-methode organiseert, inspecteert en onderhoudt je werkplek."),
    dict(type="meerkeuze",
         vraag="Wat betekent de eerste S van de 5S-methode?",
         opties=["scheiden",
                 "schoonmaken erbij",
                 "standhouden erbij",
                 "standaardiseren erbij"],
         antwoord=0,
         uitleg="Scheiden en schikken organiseren de werkplek, schoonmaken inspecteert, standhouden en standaardiseren onderhouden."),
    dict(type="meerkeuze",
         vraag="Wat betekent standaardiseren in de 5S-methode?",
         opties=["een vaste werkwijze maken",
                 "alles door elkaar leggen",
                 "het materiaal weggooien erbij",
                 "de werkpost leeg laten erbij"],
         antwoord=0,
         uitleg="Je legt de goede manier vast, zodat iedereen het telkens op dezelfde manier doet."),
    dict(type="waarofniet",
         vraag="Kwaliteitsbewust handelen gaat alleen over snelheid.",
         antwoord=False,
         uitleg="Snelheid staat niet eens in het rijtje. Het gaat over respect, methode, hygiëne, veiligheid, ergonomie, milieu en kosten."),
    dict(type="waarofniet",
         vraag="Het OVUR-schema eindigt met reflecteren.",
         antwoord=True,
         uitleg="Oriënteren, voorbereiden, uitvoeren, reflecteren."),
    dict(type="waarofniet",
         vraag="Bij de 5S-methode hoort ook schoonmaken.",
         antwoord=True,
         uitleg="Schoonmaken is de derde S en hoort bij het inspecteren van de werkplek."),
    dict(type="waarofniet",
         vraag="Respect voor materiaal hoort niet bij respectvol handelen.",
         antwoord=False,
         uitleg="Respect voor materiaal is net een van de drie richtingen."),
    dict(type="invultekst",
         vraag="Waarvoor staat de O van OVUR? Eén woord.",
         antwoord=["orienteren", "het orienteren"],
         uitleg="Oriënteren."),
    dict(type="invultekst",
         vraag="Waarvoor staat de U van OVUR? Eén woord.",
         antwoord=["uitvoeren", "het uitvoeren"],
         uitleg="Uitvoeren."),
    dict(type="invultekst",
         vraag="Hoe noem je de methode met vijf stappen om je werkpost te schikken? Hoogstens drie woorden.",
         antwoord=["5s-methode", "5s", "de 5s-methode"],
         uitleg="De 5S-methode."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is hygiënisch handelen?",
         opties=["kiemen tegenhouden",
                 "snel en goedkoop werken",
                 "alles mooi laten lijken erbij",
                 "zo weinig mogelijk poetsen"],
         antwoord=0,
         uitleg="Je werkt zo dat ziektekiemen zich niet kunnen verspreiden."),
    dict(type="meerkeuze",
         vraag="Hoe ziet een gevarensymbool eruit?",
         opties=["een ruit met een rand",
                 "een lange tekst erbij",
                 "een prijs op het etiket erbij",
                 "een streepjescode erbij"],
         antwoord=0,
         uitleg="Een gevarensymbool is een ruit met een rode rand en een zwart teken erin."),
    dict(type="meerkeuze",
         vraag="Welke soorten gevarentekens bestaan er?",
         opties=["verbodstekens",
                 "gebodstekens",
                 "waarschuwingstekens",
                 "rekentekens"],
         antwoord=[0, 1, 2],
         uitleg="De vierde soort zijn de reddingstekens. Rekentekens bestaan niet in de veiligheid."),
    dict(type="meerkeuze",
         vraag="Wat betekent een verbodsteken?",
         opties=["iets mag niet",
                 "iets is verplicht erbij",
                 "iets is een uitgang erbij",
                 "iets is een waarschuwing"],
         antwoord=0,
         uitleg="Een rode cirkel met een streep erdoor: dit mag je niet doen."),
    dict(type="meerkeuze",
         vraag="Wat betekent een gebodsteken?",
         opties=["iets is verplicht",
                 "iets mag niet erbij",
                 "iets is een uitgang erbij",
                 "iets is een gevaar erbij"],
         antwoord=0,
         uitleg="Een blauwe cirkel: dit moet je doen, bijvoorbeeld een veiligheidsbril dragen."),
    dict(type="meerkeuze",
         vraag="Wat is een reddingsteken?",
         opties=["het wijst de nooduitgang",
                 "het verbiedt het roken erbij",
                 "het verplicht een bril erbij",
                 "het waarschuwt voor zuur erbij"],
         antwoord=0,
         uitleg="Groene tekens wijzen de weg naar de nooduitgang, de verbanddoos of de AED."),
    dict(type="meerkeuze",
         vraag="Wat lees je af van een etiket?",
         opties=["het gebruik",
                 "de dosering",
                 "de gevarensymbolen",
                 "de naam van de winkel"],
         antwoord=[0, 1, 2],
         uitleg="Verder nog de gevarenaanduidingen en de veiligheidsaanduidingen."),
    dict(type="meerkeuze",
         vraag="Wat is ergonomie?",
         opties=["werken zonder schade",
                 "zo snel mogelijk werken",
                 "zo goedkoop mogelijk werken",
                 "zo weinig mogelijk bewegen"],
         antwoord=0,
         uitleg="Ergonomie stemt het werk af op het lichaam, zodat je er geen klachten van krijgt."),
    dict(type="meerkeuze",
         vraag="Hoe til je een zware doos?",
         opties=["met gebogen knieën",
                 "met een ronde rug erbij",
                 "met gestrekte benen erbij",
                 "met één hand ver vooruit"],
         antwoord=0,
         uitleg="Zak door je knieën, hou je rug recht en de last dicht bij je lichaam."),
    dict(type="meerkeuze",
         vraag="Waarmee hou je rekening bij het inrichten van een werkpost?",
         opties=["de reikwijdte",
                 "de kleur van de muur",
                 "de dag van de week erbij",
                 "de naam van het product"],
         antwoord=0,
         uitleg="Met de gebruiksfrequentie, de reikwijdte en de reikhoogte van wat je nodig hebt."),
    dict(type="meerkeuze",
         vraag="Wat is de Ladder van Lansink?",
         opties=["een rangorde voor afval",
                 "een ladder in de keuken erbij",
                 "een lijst met alle prijzen erbij",
                 "een schema voor de was erbij"],
         antwoord=0,
         uitleg="Ze zet de manieren om met afval om te gaan op een rij, van de beste naar de slechtste."),
    dict(type="meerkeuze",
         vraag="Wat staat bovenaan de Ladder van Lansink?",
         opties=["preventie",
                 "hergebruiken erbij",
                 "recycleren erbij",
                 "verbranden erbij"],
         antwoord=0,
         uitleg="Afval voorkomen is het beste. Pas daarna komen hergebruiken, recycleren en verbranden."),
    dict(type="meerkeuze",
         vraag="Welke afvalcategorieën bestaan er?",
         opties=["gft",
                 "pmd",
                 "restafval",
                 "grijsafval"],
         antwoord=[0, 1, 2],
         uitleg="Verder nog glas, papier en karton en kga. Grijsafval bestaat niet als categorie."),
    dict(type="waarofniet",
         vraag="Een bananenschil hoort bij het gft.",
         antwoord=True,
         uitleg="Gft staat voor groenten-, fruit- en tuinafval."),
    dict(type="waarofniet",
         vraag="Een batterij hoort bij het restafval.",
         antwoord=False,
         uitleg="Een batterij is klein gevaarlijk afval en hoort bij het kga."),
    dict(type="waarofniet",
         vraag="Kostenbewust handelen betekent zuinig omgaan met materiaal en tijd.",
         antwoord=True,
         uitleg="Economisch handelen let op de kosten van wat je gebruikt én van de tijd die je besteedt."),
    dict(type="waarofniet",
         vraag="Ergonomisch handelen gaat alleen over tillen.",
         antwoord=False,
         uitleg="Het gaat ook over je zithouding, je stahouding en de schikking van je werkpost."),
    dict(type="invultekst",
         vraag="Bij welke afvalsoort hoort een plastic fles? Eén woord.",
         antwoord=["pmd", "bij pmd", "het pmd"],
         uitleg="Bij het pmd."),
    dict(type="invultekst",
         vraag="Waar staat de afkorting kga voor? Hoogstens drie woorden.",
         antwoord=["klein gevaarlijk afval", "gevaarlijk afval"],
         uitleg="Klein gevaarlijk afval."),
    dict(type="invultekst",
         vraag="Hoe noem je de rangorde waarin afval voorkomen beter is dan recycleren? Hoogstens drie woorden.",
         antwoord=["ladder van lansink", "lansink", "de ladder"],
         uitleg="De Ladder van Lansink."),
]
