# -*- coding: utf-8 -*-
"""Linnenzorg: sorteren, wassen, drogen en strijken.

Van de vakfiche gezondheid, zorg en welzijn 2DU (2027), bouwsteen oriënteren
op huishoudelijke taken: de taken van de linnenzorg, de soorten vuil en de
vuilgraad van wasgoed, de Sinner-cirkel, het textiel- en het
onderhoudsetiket met de vijf groepen onderhoudsbehandelingen, de werkvolgorde
van de was, het sorteren, het wassen, het drogen en het strijken.

Deel 1 zijn de taken, het vuil en het onderhoudsetiket.
Deel 2 is methodisch wassen, drogen en strijken.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Welke taken horen bij linnenzorg?",
         opties=["de was sorteren",
                 "wassen en drogen",
                 "de strijk doen",
                 "de tafel dekken"],
         antwoord=[0, 1, 2],
         uitleg="De tafel dekken hoort bij de maaltijdzorg."),
    dict(type="meerkeuze",
         vraag="Wat hoort nog bij de linnenzorg?",
         opties=["klein verstelwerk",
                 "de vloer dweilen erbij",
                 "de maaltijd koken erbij",
                 "de planten begieten erbij"],
         antwoord=0,
         uitleg="Klein verstelwerk en de was kastklaar maken sluiten het rijtje af."),
    dict(type="meerkeuze",
         vraag="Welke gradaties van vuilgraad zijn er?",
         opties=["licht bevuild",
                 "normaal bevuild",
                 "sterk bevuild",
                 "half bevuild"],
         antwoord=[0, 1, 2],
         uitleg="De vierde gradatie is zeer sterk bevuild. Half bevuild bestaat niet."),
    dict(type="meerkeuze",
         vraag="Welke vuilgraad is er nog?",
         opties=["zeer sterk bevuild",
                 "heel licht bevuild erbij",
                 "bijna niet bevuild erbij",
                 "een beetje bevuild erbij"],
         antwoord=0,
         uitleg="Licht, normaal, sterk en zeer sterk bevuild."),
    dict(type="meerkeuze",
         vraag="Wat is een voorbeeld van sterk bevuild wasgoed?",
         opties=["een werkbroek met olie",
                 "een hemd van één dag",
                 "een handdoek van gisteren",
                 "een trui die ééns gedragen is"],
         antwoord=0,
         uitleg="Olie en aarde zijn ingedrongen vuil; dat vraagt meer product, warmte of tijd."),
    dict(type="meerkeuze",
         vraag="Wat is een textieletiket?",
         opties=["het zegt welke stof",
                 "het zegt hoeveel het kost",
                 "het zegt wie het maakte",
                 "het zegt waar het ligt erbij"],
         antwoord=0,
         uitleg="Het textieletiket geeft de samenstelling: katoen, wol, polyester."),
    dict(type="meerkeuze",
         vraag="Wat is een onderhoudsetiket?",
         opties=["het zegt hoe je wast",
                 "het zegt wat het kost erbij",
                 "het zegt wie het verkocht",
                 "het zegt hoe oud het is erbij"],
         antwoord=0,
         uitleg="Het onderhoudsetiket toont met symbolen hoe je wast, bleekt, droogt en strijkt."),
    dict(type="meerkeuze",
         vraag="Welke groepen onderhoudsbehandelingen zijn er?",
         opties=["wassen",
                 "bleken",
                 "drogen",
                 "vouwen"],
         antwoord=[0, 1, 2],
         uitleg="De vijf groepen zijn wassen, bleken, drogen, strijken en professionele reiniging."),
    dict(type="meerkeuze",
         vraag="Welke groepen horen er nog bij?",
         opties=["strijken en reiniging",
                 "naaien en verstellen",
                 "vouwen en opbergen",
                 "kopen en verkopen erbij"],
         antwoord=0,
         uitleg="Strijken en professionele reiniging vullen de vijf groepen aan."),
    dict(type="meerkeuze",
         vraag="Wat betekent een doorstreept symbool op een onderhoudsetiket?",
         opties=["het mag niet",
                 "het moet net wel erbij",
                 "het mag enkel koud erbij",
                 "het mag twee keer erbij"],
         antwoord=0,
         uitleg="Een kruis door een symbool betekent altijd: deze behandeling is verboden."),
    dict(type="meerkeuze",
         vraag="Wat betekent een getal in het wasteken?",
         opties=["de hoogste temperatuur",
                 "de duur van het programma",
                 "het aantal wasbeurten erbij",
                 "het gewicht van het stuk erbij"],
         antwoord=0,
         uitleg="Het getal in het kuipje is de hoogste temperatuur waarop je mag wassen. Koeler mag altijd."),
    dict(type="meerkeuze",
         vraag="Wat bepaalt het resultaat van het wassen?",
         opties=["de Sinner-cirkel",
                 "de kleur van de kuip",
                 "het merk van de trommel",
                 "de dag van de week erbij"],
         antwoord=0,
         uitleg="Tijd, chemie, temperatuur en mechanische handeling bepalen samen het resultaat."),
    dict(type="meerkeuze",
         vraag="Wat gebeurt er als je op een lagere temperatuur wast?",
         opties=["je hebt meer tijd nodig",
                 "de was wordt properder",
                 "het product werkt beter",
                 "de trommel draait sneller"],
         antwoord=0,
         uitleg="In de Sinner-cirkel vul je minder warmte aan met meer tijd, meer product of meer beweging."),
    dict(type="waarofniet",
         vraag="Een doorstreept strijkijzer betekent dat je niet mag strijken.",
         antwoord=True,
         uitleg="Een kruis door een symbool verbiedt die behandeling."),
    dict(type="waarofniet",
         vraag="Het onderhoudsetiket en het textieletiket zijn hetzelfde.",
         antwoord=False,
         uitleg="Het textieletiket zegt waaruit het stuk bestaat, het onderhoudsetiket hoe je het verzorgt."),
    dict(type="waarofniet",
         vraag="Zwaar bevuild wasgoed vraagt meer product of een hogere temperatuur.",
         antwoord=True,
         uitleg="Dat is de Sinner-cirkel: meer vuil vraagt meer van een van de vier factoren."),
    dict(type="waarofniet",
         vraag="Je mag elk kledingstuk op zestig graden wassen.",
         antwoord=False,
         uitleg="Het getal op het onderhoudsetiket is de bovengrens. Wol en zijde verdragen veel minder."),
    dict(type="invultekst",
         vraag="Hoe noem je het etiket dat zegt hoe je een kledingstuk moet wassen? Eén woord.",
         antwoord=["onderhoudsetiket", "het onderhoudsetiket", "wasetiket"],
         uitleg="Het onderhoudsetiket."),
    dict(type="invultekst",
         vraag="Hoeveel groepen onderhoudsbehandelingen zijn er? Een getal.",
         antwoord=["5", "vijf"],
         uitleg="Vijf: wassen, bleken, drogen, strijken en professionele reiniging."),
    dict(type="invultekst",
         vraag="Wat betekent een kruis door een symbool op het etiket? Hoogstens drie woorden.",
         antwoord=["het mag niet", "mag niet", "verboden"],
         uitleg="Het mag niet."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Waarop sorteer je wasgoed?",
         opties=["de kleur",
                 "het soort textiel",
                 "de wastemperatuur",
                 "de prijs van het stuk"],
         antwoord=[0, 1, 2],
         uitleg="De vierde is de vuilgraad. De prijs doet er bij het sorteren niet toe."),
    dict(type="meerkeuze",
         vraag="Wat is de eerste stap bij het doen van de was?",
         opties=["verzamelen en bewaren",
                 "meteen beginnen strijken",
                 "het wasgoed opbergen erbij",
                 "de machine leeg laten draaien"],
         antwoord=0,
         uitleg="Eerst verzamel en bewaar je het wasgoed, daarna sorteren en controleren."),
    dict(type="meerkeuze",
         vraag="Wat doe je na het sorteren?",
         opties=["controleren",
                 "meteen strijken erbij",
                 "meteen opbergen erbij",
                 "meteen verkopen erbij"],
         antwoord=0,
         uitleg="Controleren komt na het sorteren en voor het wassen."),
    dict(type="meerkeuze",
         vraag="Wat controleer je voor het wassen?",
         opties=["de zakken en de vlekken",
                 "de prijs van het stuk erbij",
                 "het merk van het hemd erbij",
                 "de kleur van de knopen erbij"],
         antwoord=0,
         uitleg="Lege zakken, gesloten ritsen en vlekken die je eerst moet behandelen."),
    dict(type="meerkeuze",
         vraag="Waarom sorteer je op kleur?",
         opties=["kleuren geven af",
                 "het staat netter erbij",
                 "het gaat sneller erbij",
                 "het kost minder geld erbij"],
         antwoord=0,
         uitleg="Een rode sok kleurt een hele witte was roze."),
    dict(type="meerkeuze",
         vraag="Waarom sorteer je op vuilgraad?",
         opties=["het vuil gaat over",
                 "de kleuren blijven mooi",
                 "de machine draait sneller",
                 "de trommel wordt properder"],
         antwoord=0,
         uitleg="Zwaar bevuild wasgoed vuilt de rest van de lading mee."),
    dict(type="meerkeuze",
         vraag="Wat doe je met een overladen trommel?",
         opties=["minder wasgoed insteken",
                 "meer product toevoegen",
                 "een hogere temperatuur kiezen",
                 "een hoger toerental kiezen"],
         antwoord=0,
         uitleg="In een volle trommel kan het wasgoed niet bewegen, en net die beweging wast."),
    dict(type="meerkeuze",
         vraag="Waarvan hangt het wasprogramma af?",
         opties=["het onderhoudsetiket",
                 "de dag van de week erbij",
                 "de kleur van de machine",
                 "het merk van het product"],
         antwoord=0,
         uitleg="Het etiket geeft de temperatuur en de behandeling; daarop kies je programma en toerental."),
    dict(type="meerkeuze",
         vraag="Wat is het toerental bij het wassen?",
         opties=["de snelheid bij het zwieren",
                 "de temperatuur van het water",
                 "de duur van het programma",
                 "de hoeveelheid wasproduct"],
         antwoord=0,
         uitleg="Hoe hoger het toerental, hoe droger de was uit de machine komt, maar ook hoe meer kreuken."),
    dict(type="meerkeuze",
         vraag="Wat lees je af van het onderhoudsetiket?",
         opties=["de wastemperatuur",
                 "of je mag bleken",
                 "of je mag strijken",
                 "de prijs van het stuk"],
         antwoord=[0, 1, 2],
         uitleg="En ook of het stuk in de droogtrommel mag en of het professioneel gereinigd moet worden."),
    dict(type="meerkeuze",
         vraag="Wat doe je met wasgoed dat niet in de droogtrommel mag?",
         opties=["aan een droogrek hangen",
                 "toch in de trommel steken",
                 "meteen weggooien erbij",
                 "op de verwarming leggen"],
         antwoord=0,
         uitleg="Wol en fijne stoffen krimpen in de droogtrommel. Laat ze aan de lucht drogen."),
    dict(type="meerkeuze",
         vraag="Hoe kies je de temperatuur van je strijkijzer?",
         opties=["volgens het etiket",
                 "zo heet mogelijk erbij",
                 "zo koud mogelijk erbij",
                 "volgens de kleur erbij"],
         antwoord=0,
         uitleg="De puntjes in het strijkijzersymbool geven aan hoe heet het mag."),
    dict(type="meerkeuze",
         vraag="Wat zie je aan een goed gestreken stuk?",
         opties=["geen kreuken",
                 "een nette vouwlijn",
                 "geen glimplekken",
                 "een bruine schroeiplek"],
         antwoord=[0, 1, 2],
         uitleg="Een schroeiplek betekent dat het strijkijzer te heet stond."),
    dict(type="waarofniet",
         vraag="Je sorteert wasgoed op kleur, soort textiel, temperatuur en vuilgraad.",
         antwoord=True,
         uitleg="Dat zijn de vier sorteercriteria."),
    dict(type="waarofniet",
         vraag="Een overvolle trommel wast beter.",
         antwoord=False,
         uitleg="Zonder beweging valt een factor van de Sinner-cirkel weg en wordt de was minder proper."),
    dict(type="waarofniet",
         vraag="Het strijken is de laatste stap in de werkvolgorde van de was.",
         antwoord=True,
         uitleg="Verzamelen, sorteren, controleren, wassen, drogen, kastklaar maken en strijken indien nodig."),
    dict(type="waarofniet",
         vraag="Elk kledingstuk mag in de droogtrommel.",
         antwoord=False,
         uitleg="Het onderhoudsetiket zegt het. Een doorstreept droogsymbool betekent niet in de trommel."),
    dict(type="invultekst",
         vraag="Welke stap komt na het verzamelen van het wasgoed? Eén woord.",
         antwoord=["sorteren", "het sorteren"],
         uitleg="Sorteren."),
    dict(type="invultekst",
         vraag="Wat doe je met het wasgoed na het sorteren en voor het wassen? Eén woord.",
         antwoord=["controleren", "het controleren", "nakijken"],
         uitleg="Controleren."),
    dict(type="invultekst",
         vraag="Hoe noem je de snelheid waarmee de machine het water uit de was zwiert? Eén woord.",
         antwoord=["toerental", "het toerental", "centrifugeren"],
         uitleg="Het toerental."),
]
