# -*- coding: utf-8 -*-
"""Voedselveiligheid en voedselhygiëne.

Van de vakfiche gezondheid, zorg en welzijn 2DU (2027), bouwsteen oriënteren
op huishoudelijke taken: bacteriën en schimmels met hun goede en slechte
kanten, de levensvoorwaarden van micro-organismen, de drie soorten
voedselbederf, de gevolgen van bedorven voedsel, kruisbesmetting en de
HACCP-richtlijnen bij voedselbereiding.

Deel 1 zijn de micro-organismen en het voedselbederf.
Deel 2 zijn kruisbesmetting en HACCP.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is voedselveiligheid?",
         opties=["eten zonder gevaar",
                 "eten dat goedkoop is erbij",
                 "eten dat lekker smaakt erbij",
                 "eten dat er mooi uitziet erbij"],
         antwoord=0,
         uitleg="Voedselveiligheid betekent dat je van het eten niet ziek kan worden."),
    dict(type="meerkeuze",
         vraag="Wat zijn micro-organismen?",
         opties=["kleine levende wezens",
                 "grote dode deeltjes erbij",
                 "soorten metalen in voeding",
                 "soorten stenen in de grond"],
         antwoord=0,
         uitleg="Micro-organismen zijn zo klein dat je ze niet met het blote oog ziet, zoals bacteriën en schimmels."),
    dict(type="meerkeuze",
         vraag="Wat hebben micro-organismen nodig om te groeien?",
         opties=["water",
                 "voedsel",
                 "een goede temperatuur",
                 "volledige duisternis"],
         antwoord=[0, 1, 2],
         uitleg="De vier levensvoorwaarden zijn water, voedsel, zuurstof en temperatuur. Donker hoeft niet."),
    dict(type="meerkeuze",
         vraag="Welke levensvoorwaarde hebben micro-organismen nog nodig?",
         opties=["zuurstof",
                 "geluid in de kamer erbij",
                 "licht van een lamp erbij",
                 "wind door het raam erbij"],
         antwoord=0,
         uitleg="Water, voedsel, zuurstof en temperatuur: haal er een weg en de groei stopt."),
    dict(type="meerkeuze",
         vraag="Wat is een positief effect van bacteriën?",
         opties=["ze maken yoghurt",
                 "ze bederven de melk erbij",
                 "ze maken mensen ziek erbij",
                 "ze doen voedsel rotten erbij"],
         antwoord=0,
         uitleg="Bacteriën maken yoghurt, kaas en zuurkool. Niet alle bacteriën zijn schadelijk."),
    dict(type="meerkeuze",
         vraag="Wat is een negatief effect van schimmels?",
         opties=["ze bederven voedsel",
                 "ze maken kaas lekkerder",
                 "ze helpen bij het bakken",
                 "ze maken brood luchtiger"],
         antwoord=0,
         uitleg="Schimmels op brood of confituur maken het voedsel oneetbaar en soms giftig."),
    dict(type="meerkeuze",
         vraag="Wat is fysisch bederf?",
         opties=["het voedsel droogt uit",
                 "een bacterie groeit erin",
                 "het vet wordt ranzig erbij",
                 "een made kruipt erin erbij"],
         antwoord=0,
         uitleg="Fysisch bederf komt van buitenaf: uitdrogen, bevriezen, kneuzen."),
    dict(type="meerkeuze",
         vraag="Wat is chemisch bederf?",
         opties=["het vet wordt ranzig",
                 "een muis knaagt eraan erbij",
                 "het brood wordt hard erbij",
                 "een schimmel groeit erop erbij"],
         antwoord=0,
         uitleg="Bij chemisch bederf verandert de stof zelf, bijvoorbeeld vet dat met zuurstof reageert."),
    dict(type="meerkeuze",
         vraag="Wat is biologisch bederf?",
         opties=["bederf door bacteriën",
                 "bederf door schimmels",
                 "bederf door insecten",
                 "bederf door uitdrogen"],
         antwoord=[0, 1, 2],
         uitleg="Biologisch bederf komt door micro-organismen of macro-organismen. Uitdrogen is fysisch."),
    dict(type="meerkeuze",
         vraag="Wat is een macro-organisme dat voedsel bederft?",
         opties=["een muis",
                 "een bacterie erbij",
                 "een schimmel erbij",
                 "een gistcel erbij"],
         antwoord=0,
         uitleg="Muizen, maden en insecten zijn macro-organismen: je ziet ze met het blote oog."),
    dict(type="meerkeuze",
         vraag="Wat kan er gebeuren als je bedorven voedsel eet?",
         opties=["je wordt misselijk",
                 "je slaapt veel beter erbij",
                 "je krijgt meer energie erbij",
                 "je verteert het gewoon erbij"],
         antwoord=0,
         uitleg="Misselijkheid, braken, diarree, een voedselinfectie of een voedselvergiftiging."),
    dict(type="meerkeuze",
         vraag="Wat is een voedselvergiftiging?",
         opties=["de gifstof maakt ziek",
                 "de bacterie groeit in je darm",
                 "het voedsel smaakt bitter erbij",
                 "het voedsel ziet er vies uit"],
         antwoord=0,
         uitleg="Bij een vergiftiging zit de gifstof al in het eten. Bij een infectie groeit de bacterie pas in je lichaam."),
    dict(type="meerkeuze",
         vraag="Welke klachten krijg je van bedorven voedsel?",
         opties=["braken",
                 "diarree",
                 "misselijkheid",
                 "beter zien"],
         antwoord=[0, 1, 2],
         uitleg="Bedorven voedsel tast de spijsvertering aan, niet het gezichtsvermogen."),
    dict(type="waarofniet",
         vraag="Alle bacteriën zijn slecht.",
         antwoord=False,
         uitleg="Bacteriën maken yoghurt en kaas, en in je darmen helpen ze bij de vertering."),
    dict(type="waarofniet",
         vraag="Micro-organismen groeien goed bij kamertemperatuur.",
         antwoord=True,
         uitleg="Daarom hoort bederfbaar voedsel in de koelkast en niet op het aanrecht."),
    dict(type="waarofniet",
         vraag="Een schimmel op confituur mag je er gewoon afscheppen.",
         antwoord=False,
         uitleg="De draden zitten dieper dan je ziet. Gooi de hele pot weg."),
    dict(type="waarofniet",
         vraag="Je kan voedselbederf niet altijd zien of ruiken.",
         antwoord=True,
         uitleg="Sommige bacteriën veranderen niets aan geur, kleur of smaak, en maken je toch ziek."),
    dict(type="invultekst",
         vraag="Hoe noem je het bederf dat door bacteriën en schimmels komt? Eén woord.",
         antwoord=["biologisch", "biologisch bederf"],
         uitleg="Biologisch bederf."),
    dict(type="invultekst",
         vraag="Hoe noem je de heel kleine levende wezens die je niet kan zien? Hoogstens drie woorden.",
         antwoord=["micro-organismen", "microorganismen", "micro organismen"],
         uitleg="Micro-organismen."),
    dict(type="invultekst",
         vraag="Welke levensvoorwaarde van micro-organismen pak je aan door in te vriezen? Eén woord.",
         antwoord=["temperatuur", "de temperatuur"],
         uitleg="De temperatuur."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is kruisbesmetting?",
         opties=["kiemen gaan over",
                 "voedsel wordt te koud erbij",
                 "de kleuren lopen door elkaar",
                 "het vet wordt ranzig erbij"],
         antwoord=0,
         uitleg="Kiemen gaan van het ene voedingsmiddel naar het andere, vaak via je handen, een mes of een plank."),
    dict(type="meerkeuze",
         vraag="Hoe voorkom je kruisbesmetting?",
         opties=["aparte snijplanken",
                 "dezelfde plank gebruiken",
                 "het mes niet afwassen erbij",
                 "alles samen klaarleggen erbij"],
         antwoord=0,
         uitleg="Rauw vlees krijgt zijn eigen plank en mes, en je wast je handen ertussen."),
    dict(type="meerkeuze",
         vraag="Wanneer was je je handen bij het koken?",
         opties=["na rauw vlees",
                 "voor je begint",
                 "na het toilet",
                 "na het afdrogen"],
         antwoord=[0, 1, 2],
         uitleg="Na het afdrogen zijn je handen net schoon; dan hoeft het niet opnieuw."),
    dict(type="meerkeuze",
         vraag="Wat is HACCP?",
         opties=["een reeks richtlijnen",
                 "een merk van koelkasten",
                 "een soort schoonmaakmiddel",
                 "een naam van een bacterie"],
         antwoord=0,
         uitleg="HACCP is een systeem van richtlijnen dat de gevaren bij voedselbereiding opspoort en afdekt."),
    dict(type="meerkeuze",
         vraag="Waarvoor dienen de HACCP-richtlijnen?",
         opties=["veilig voedsel bereiden",
                 "goedkoper koken erbij",
                 "sneller afwassen erbij",
                 "mooier opdienen erbij"],
         antwoord=0,
         uitleg="Ze zorgen dat er in geen enkele stap van de bereiding iets misgaat met de veiligheid."),
    dict(type="meerkeuze",
         vraag="Welke handelingen vallen onder HACCP?",
         opties=["boodschappen bewaren",
                 "hygiënisch werken",
                 "voedsel bereiden",
                 "de tafel versieren"],
         antwoord=[0, 1, 2],
         uitleg="HACCP loopt van het ontvangen van de boodschappen tot het afwassen en schoonmaken."),
    dict(type="meerkeuze",
         vraag="Wat doe je bij het ontvangen van boodschappen?",
         opties=["de datum controleren",
                 "de zak meteen wegzetten",
                 "de etiketten weggooien erbij",
                 "de koelkast opendoen erbij"],
         antwoord=0,
         uitleg="Kijk de houdbaarheidsdatum en de verpakking na, en berg koele waren meteen op."),
    dict(type="meerkeuze",
         vraag="Waarom werk je met propere handen in de keuken?",
         opties=["kiemen komen op het eten",
                 "het staat netter op de foto",
                 "het gaat sneller vooruit erbij",
                 "de smaak wordt beter erbij"],
         antwoord=0,
         uitleg="Je handen zijn de snelste weg waarlangs kiemen in het eten belanden."),
    dict(type="meerkeuze",
         vraag="Wat doe je met rauw vlees en groenten?",
         opties=["apart houden",
                 "samen op één plank",
                 "in dezelfde kom leggen",
                 "met hetzelfde mes snijden"],
         antwoord=0,
         uitleg="Groenten worden soms rauw gegeten, dus de kiemen van het vlees mogen er niet bij komen."),
    dict(type="meerkeuze",
         vraag="Wat doe je met restjes van gisteren?",
         opties=["goed verhitten",
                 "lauw opdienen erbij",
                 "koud opdienen erbij",
                 "twee keer opwarmen erbij"],
         antwoord=0,
         uitleg="Warm restjes door en door op, en warm ze maar één keer op."),
    dict(type="meerkeuze",
         vraag="Wat hoort bij persoonlijke hygiëne in de keuken?",
         opties=["een schorts dragen",
                 "de haren samenbinden",
                 "de juwelen afleggen",
                 "met je vingers proeven"],
         antwoord=[0, 1, 2],
         uitleg="Met je vingers proeven brengt juist kiemen in het eten."),
    dict(type="meerkeuze",
         vraag="Wat doe je na het bereiden van de maaltijd?",
         opties=["afruimen en afwassen",
                 "de keuken zo laten erbij",
                 "de pannen laten staan erbij",
                 "het vuil laten liggen erbij"],
         antwoord=0,
         uitleg="Afruimen, afwassen en schoonmaken zijn de laatste stappen van HACCP."),
    dict(type="meerkeuze",
         vraag="Waarom proef je niet met de lepel waarmee je roert?",
         opties=["je brengt kiemen in",
                 "de smaak verandert erbij",
                 "de lepel wordt te warm erbij",
                 "het eten wordt te zout erbij"],
         antwoord=0,
         uitleg="Via je mond komen kiemen op de lepel en zo in de hele pot."),
    dict(type="waarofniet",
         vraag="Rauw vlees en rauwe groenten snij je best op dezelfde plank.",
         antwoord=False,
         uitleg="Dat is net kruisbesmetting. Gebruik aparte planken."),
    dict(type="waarofniet",
         vraag="HACCP begint al bij het ontvangen van de boodschappen.",
         antwoord=True,
         uitleg="Het eerste punt in het rijtje is boodschappen ontvangen, daarna bewaren."),
    dict(type="waarofniet",
         vraag="Een snijplank van rauwe kip mag je zonder wassen hergebruiken.",
         antwoord=False,
         uitleg="Op rauwe kip zitten vaak salmonellabacteriën. De plank gaat eerst in heet water met zeep."),
    dict(type="waarofniet",
         vraag="Kruisbesmetting kan ook via je handen gebeuren.",
         antwoord=True,
         uitleg="Handen, messen, planken en keukenhanddoeken zijn de gewone wegen."),
    dict(type="invultekst",
         vraag="Hoe noem je het overdragen van kiemen van het ene voedingsmiddel naar het andere? Eén woord.",
         antwoord=["kruisbesmetting", "de kruisbesmetting"],
         uitleg="Kruisbesmetting."),
    dict(type="invultekst",
         vraag="Hoe noem je de richtlijnen voor een veilige voedselbereiding? Eén woord.",
         antwoord=["haccp", "de haccp", "haccp-richtlijnen"],
         uitleg="De HACCP-richtlijnen."),
    dict(type="invultekst",
         vraag="Wat doe je met je handen voor je begint te koken? Hoogstens drie woorden.",
         antwoord=["wassen", "handen wassen", "je wast ze"],
         uitleg="Wassen."),
]
