# -*- coding: utf-8 -*-
"""Ziek zijn en eerste hulp.

Van de vakfiche gezondheid, zorg en welzijn 2DU (2027), bouwsteen gezondheid
en welzijn: de symptomen van ziek zijn en het ondersteunen van een kind of
volwassene, de vaak voorkomende gezondheidsproblemen bij adolescenten, de zes
basisprincipes en de vier stappen van eerste hulp, de noodnummers, de
ongevallen en noodsituaties, en de zes stappen van reanimatie.

Deel 1 is ziek zijn.
Deel 2 is eerste hulp.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Welke symptomen wijzen erop dat een kind ziek is?",
         opties=["koorts",
                 "braken",
                 "geen zin om te spelen",
                 "een nieuwe jas"],
         antwoord=[0, 1, 2],
         uitleg="Een nieuwe jas zegt niets over gezondheid. De andere drie zijn symptomen van ziek zijn."),
    dict(type="meerkeuze",
         vraag="Wat is koorts?",
         opties=["een hoge temperatuur",
                 "een lage bloeddruk erbij",
                 "een snelle ademhaling erbij",
                 "een pijn in de buik erbij"],
         antwoord=0,
         uitleg="Het lichaam zet zijn temperatuur hoger om ziektekiemen te bestrijden."),
    dict(type="meerkeuze",
         vraag="Wat doe je eerst als een kind zich ziek voelt?",
         opties=["je vraagt hoe het voelt",
                 "je laat het maar doorgaan",
                 "je geeft meteen een pil erbij",
                 "je stuurt het naar de school"],
         antwoord=0,
         uitleg="Eerst kijken en vragen wat er is. Zo weet je wat het kind nodig heeft."),
    dict(type="meerkeuze",
         vraag="Hoe ondersteun je een kind met diarree?",
         opties=["je laat het veel drinken",
                 "je geeft het minder drinken",
                 "je laat het veel springen",
                 "je geeft het veel snoepjes"],
         antwoord=0,
         uitleg="Bij diarree verliest het lichaam veel vocht. Dat moet bijgevuld worden."),
    dict(type="meerkeuze",
         vraag="Waarom is vermoeidheid een symptoom?",
         opties=["het lichaam vecht",
                 "het kind is enkel lui erbij",
                 "het is nooit belangrijk erbij",
                 "het hoort bij elke dag erbij"],
         antwoord=0,
         uitleg="Het lichaam gebruikt zijn energie om beter te worden, dus er blijft minder over."),
    dict(type="meerkeuze",
         vraag="Wat betekent beperkt zijn in het zelfstandig functioneren?",
         opties=["het lukt niet alleen",
                 "het lukt juist heel goed",
                 "het kind is heel actief",
                 "het kind slaapt heel diep"],
         antwoord=0,
         uitleg="Wat iemand normaal zelf doet, zoals zich wassen of aankleden, lukt tijdelijk niet meer."),
    dict(type="meerkeuze",
         vraag="Welke gezondheidsproblemen komen vaak voor bij jongeren?",
         opties=["slaaptekort",
                 "rugklachten",
                 "stress en faalangst",
                 "een gebroken arm"],
         antwoord=[0, 1, 2],
         uitleg="Een gebroken arm is een ongeval, geen vaak voorkomend gezondheidsprobleem."),
    dict(type="meerkeuze",
         vraag="Wat kan een allergie uitlokken?",
         opties=["huisstofmijt",
                 "een warme trui erbij",
                 "een koude kamer erbij",
                 "een lange wandeling erbij"],
         antwoord=0,
         uitleg="Pollen, huisstofmijt en dierenhaar zijn de bekendste uitlokkers."),
    dict(type="meerkeuze",
         vraag="Hoe voorkom je gebitsproblemen?",
         opties=["twee keer per dag poetsen",
                 "elke dag veel snoep eten",
                 "nooit naar de tandarts gaan",
                 "enkel water op de tanden"],
         antwoord=0,
         uitleg="Twee keer per dag poetsen, weinig zoete dranken en jaarlijks naar de tandarts."),
    dict(type="meerkeuze",
         vraag="Hoe voorkom je rugklachten op school?",
         opties=["een goede houding",
                 "de boekentas op één schouder",
                 "een stoel zonder rugleuning",
                 "heel de dag stil blijven zitten"],
         antwoord=0,
         uitleg="Rechtop zitten, de tas op twee schouders en regelmatig even rechtstaan."),
    dict(type="meerkeuze",
         vraag="Wat helpt tegen slaaptekort?",
         opties=["op tijd gaan slapen",
                 "langer op de gsm kijken",
                 "in de namiddag koffie drinken",
                 "laat nog een film beginnen"],
         antwoord=0,
         uitleg="Een vast uur en geen scherm het laatste uur voor het slapen helpen het meest."),
    dict(type="meerkeuze",
         vraag="Wat helpt tegen faalangst?",
         opties=["op tijd beginnen leren",
                 "de toets ontlopen erbij",
                 "er met niemand over praten",
                 "alles de avond voordien doen"],
         antwoord=0,
         uitleg="Goed voorbereid zijn en erover praten nemen een groot deel van de spanning weg."),
    dict(type="meerkeuze",
         vraag="Hoe voorkom je overgewicht?",
         opties=["genoeg bewegen",
                 "gezond eten",
                 "water drinken",
                 "veel zitten"],
         antwoord=[0, 1, 2],
         uitleg="Veel zitten is net sedentair gedrag, en dat werkt overgewicht in de hand."),
    dict(type="waarofniet",
         vraag="Misselijkheid is een symptoom van ziek zijn.",
         antwoord=True,
         uitleg="Misselijkheid staat in het rijtje samen met braken, diarree, koorts en pijn."),
    dict(type="waarofniet",
         vraag="Een condoom helpt om een soa te voorkomen.",
         antwoord=True,
         uitleg="Een condoom is de belangrijkste bescherming tegen seksueel overdraagbare aandoeningen."),
    dict(type="waarofniet",
         vraag="Stress hoort er bij jongeren gewoon bij en vraagt geen aandacht.",
         antwoord=False,
         uitleg="Stress en faalangst staan in de fiche als gezondheidsproblemen die je kan voorkomen."),
    dict(type="waarofniet",
         vraag="Wie koorts heeft, moet vooral veel bewegen.",
         antwoord=False,
         uitleg="Bij koorts heeft het lichaam rust en vocht nodig."),
    dict(type="invultekst",
         vraag="Hoe noem je een verhoogde lichaamstemperatuur bij ziekte? Eén woord.",
         antwoord=["koorts", "de koorts"],
         uitleg="Koorts."),
    dict(type="invultekst",
         vraag="Welke allergie krijg je van stuifmeel in de lente? Hoogstens drie woorden.",
         antwoord=["hooikoorts", "pollenallergie", "allergie voor pollen"],
         uitleg="Hooikoorts, een allergie voor pollen."),
    dict(type="invultekst",
         vraag="Waar staat de afkorting soa voor? Hoogstens drie woorden.",
         antwoord=["seksueel overdraagbare aandoening", "seksueel overdraagbare aandoeningen"],
         uitleg="Een seksueel overdraagbare aandoening."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Welke basisprincipes horen bij eerste hulp?",
         opties=["blijf rustig",
                 "vermijd besmetting",
                 "zorg voor comfort",
                 "ga snel naar huis"],
         antwoord=[0, 1, 2],
         uitleg="Je blijft bij het slachtoffer. Verder nog: handel als hulpverlener, geef psychosociale hulp en denk aan de reacties achteraf."),
    dict(type="meerkeuze",
         vraag="Wat is de eerste stap in eerste hulp?",
         opties=["zorg voor veiligheid",
                 "geef meteen beademing",
                 "bel eerst je ouders erbij",
                 "vraag naar de naam erbij"],
         antwoord=0,
         uitleg="Eerst de plaats veilig maken, anders word je zelf het tweede slachtoffer."),
    dict(type="meerkeuze",
         vraag="Wat doe je na het beoordelen van het slachtoffer?",
         opties=["gespecialiseerde hulp roepen",
                 "het slachtoffer alleen laten",
                 "de wonde eerst fotograferen",
                 "naar huis gaan om te bellen"],
         antwoord=0,
         uitleg="De vier stappen zijn: veiligheid, toestand beoordelen, hulp roepen, verdere eerste hulp."),
    dict(type="meerkeuze",
         vraag="Welk noodnummer bel je voor een ziekenwagen?",
         opties=["112",
                 "101 voor de ziekenwagen",
                 "1733 voor de ziekenwagen",
                 "70 245 245 voor de wagen"],
         antwoord=0,
         uitleg="112 is het nummer voor de ziekenwagen en de brandweer."),
    dict(type="meerkeuze",
         vraag="Welk noodnummer bel je voor de politie?",
         opties=["101",
                 "112 voor enkel politie",
                 "1733 voor enkel politie",
                 "70 245 245 voor politie"],
         antwoord=0,
         uitleg="101 is het nummer van de politie."),
    dict(type="meerkeuze",
         vraag="Wie bel je bij een vergiftiging?",
         opties=["het antigifcentrum",
                 "de politie op 101 erbij",
                 "de brandweer op 112 erbij",
                 "de wachtpost op 1733 erbij"],
         antwoord=0,
         uitleg="Het antigifcentrum, op 70 245 245. Bij levensgevaar bel je eerst 112."),
    dict(type="meerkeuze",
         vraag="Wanneer bel je 1733?",
         opties=["voor de huisarts",
                 "voor een ziekenwagen erbij",
                 "voor de brandweer erbij",
                 "voor het antigifcentrum"],
         antwoord=0,
         uitleg="1733 is de huisarts of de huisartsenwachtpost, voor klachten die geen 112 vragen."),
    dict(type="meerkeuze",
         vraag="Wat doe je bij een zware bloeding?",
         opties=["je drukt de wonde dicht",
                 "je wacht tot het stopt erbij",
                 "je wast de wonde met zeep",
                 "je geeft iets te drinken erbij"],
         antwoord=0,
         uitleg="Druk de wonde dicht met een verband of je hand, en bel 112."),
    dict(type="meerkeuze",
         vraag="Wat doe je als iemand zich verslikt en nog kan hoesten?",
         opties=["je laat hem hoesten",
                 "je geeft slagen op de rug",
                 "je legt hem plat op de rug",
                 "je geeft meteen water erbij"],
         antwoord=0,
         uitleg="Hoesten is de sterkste manier om het voorwerp los te krijgen. Pas als dat niet meer lukt, geef je slagen tussen de schouderbladen."),
    dict(type="meerkeuze",
         vraag="Wat doe je bij een brandwonde?",
         opties=["koel met lopend water",
                 "wrijf er boter over erbij",
                 "prik de blaar open erbij",
                 "leg er ijs rechtstreeks op"],
         antwoord=0,
         uitleg="Koel tien tot twintig minuten met lauw lopend water. Geen ijs, geen zalf, geen blaar openmaken."),
    dict(type="meerkeuze",
         vraag="Welke letsels aan botten, spieren en gewrichten bestaan er?",
         opties=["een botbreuk",
                 "een verstuiking",
                 "een kneuzing",
                 "een brandwonde"],
         antwoord=[0, 1, 2],
         uitleg="Een brandwonde is een wonde van de huid. De vierde in dit rijtje is een ontwrichting."),
    dict(type="meerkeuze",
         vraag="Wat is een ontwrichting?",
         opties=["het bot schiet uit de kom",
                 "het bot breekt in twee stukken",
                 "de spier wordt blauw en dik",
                 "de huid gaat open en bloedt"],
         antwoord=0,
         uitleg="De gewrichtskop verlaat de gewrichtskom. Laat het gewricht zoals het is en ga naar de spoed."),
    dict(type="meerkeuze",
         vraag="Welke stappen horen bij reanimatie?",
         opties=["bel 112",
                 "start borstcompressies",
                 "zoek een AED",
                 "geef het slachtoffer water"],
         antwoord=[0, 1, 2],
         uitleg="Een bewusteloos slachtoffer krijgt nooit te drinken. De zes stappen eindigen met doorgaan tot de ambulance er is."),
    dict(type="waarofniet",
         vraag="Bij reanimatie ga je door tot de ambulance er is.",
         antwoord=True,
         uitleg="Dat is de zesde stap. Stoppen betekent dat het bloed niet meer rondgaat."),
    dict(type="waarofniet",
         vraag="Een AED mag enkel door een dokter gebruikt worden.",
         antwoord=False,
         uitleg="Een AED is voor iedereen bedoeld. Het toestel legt zelf stap voor stap uit wat je moet doen."),
    dict(type="waarofniet",
         vraag="Bij een verstuiking koel je het gewricht.",
         antwoord=True,
         uitleg="Koelen en rust houden de zwelling klein."),
    dict(type="waarofniet",
         vraag="Je mag een slachtoffer altijd eerst verplaatsen.",
         antwoord=False,
         uitleg="Verplaats alleen als er gevaar is. Verplaatsen kan een letsel erger maken."),
    dict(type="invultekst",
         vraag="Welk noodnummer bel je voor de brandweer? Een getal.",
         antwoord=["112"],
         uitleg="112, hetzelfde nummer als voor de ziekenwagen."),
    dict(type="invultekst",
         vraag="Waar staat de afkorting AED voor? Hoogstens drie woorden.",
         antwoord=["automatische externe defibrillator", "externe defibrillator"],
         uitleg="Een automatische externe defibrillator."),
    dict(type="invultekst",
         vraag="Hoe noem je het letsel waarbij een bot in twee gaat? Eén woord.",
         antwoord=["botbreuk", "een botbreuk", "fractuur"],
         uitleg="Een botbreuk."),
]
