# -*- coding: utf-8 -*-
"""Gedrag en behoeften.

Van de vakfiche ontwikkeling en pedagogisch handelen 2DU (2027), bouwsteen
pedagogisch handelen: wat gedrag is (waarneembaar, niet-waarneembaar,
reflexmatig) en welke factoren het beïnvloeden, en daarna de behoeften: de
behoeftepiramide van Maslow en de zes basisbehoeften van een kind volgens
Kind en Gezin.

Deel 1 is gedrag en wat het stuurt.
Deel 2 zijn de behoeften.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat hoort allemaal bij gedrag?",
         opties=["wat iemand doet",
                 "wat iemand zegt",
                 "wat iemand denkt",
                 "wat iemand bezit"],
         antwoord=[0, 1, 2],
         uitleg="Gedrag is alles wat een mens doet, zegt, denkt en voelt."),
    dict(type="meerkeuze",
         vraag="Welke soorten gedrag zijn er?",
         opties=["waarneembaar gedrag",
                 "niet-waarneembaar gedrag",
                 "reflexmatig gedrag",
                 "verboden gedrag"],
         antwoord=[0, 1, 2],
         uitleg="Gedrag kan zichtbaar zijn, binnenin blijven of automatisch gebeuren."),
    dict(type="meerkeuze",
         vraag="Wat is waarneembaar gedrag?",
         opties=["je kan het zien",
                 "je kan het enkel denken",
                 "het blijft binnen erbij",
                 "het is een gevoel erbij"],
         antwoord=0,
         uitleg="Lopen, praten, lachen of wegduwen: gedrag dat je kan zien of horen."),
    dict(type="meerkeuze",
         vraag="Wat is niet-waarneembaar gedrag?",
         opties=["denken en voelen",
                 "lopen en praten",
                 "springen en roepen",
                 "zwaaien naar iemand"],
         antwoord=0,
         uitleg="Denken, voelen en willen zie je niet, en toch is het gedrag."),
    dict(type="meerkeuze",
         vraag="Wat is reflexmatig gedrag?",
         opties=["het gaat automatisch",
                 "je kiest het zelf erbij",
                 "je denkt er lang over",
                 "je plant het vooraf erbij"],
         antwoord=0,
         uitleg="Je hand wegtrekken van een hete pan: het gebeurt zonder nadenken."),
    dict(type="meerkeuze",
         vraag="Welke factoren beïnvloeden gedrag?",
         opties=["biologische factoren",
                 "psychologische factoren",
                 "sociale factoren",
                 "toevallige factoren"],
         antwoord=[0, 1, 2],
         uitleg="Biologisch, psychologisch, cognitief en sociaal: samen bepalen ze het gedrag."),
    dict(type="meerkeuze",
         vraag="Wat is een biologische factor bij gedrag?",
         opties=["honger of moeheid",
                 "de mening van je vriend",
                 "de regels van de klas",
                 "het humeur van de leraar"],
         antwoord=0,
         uitleg="Het lichaam zelf: honger, dorst, moeheid, pijn of ziekte."),
    dict(type="meerkeuze",
         vraag="Wat is een sociale factor bij gedrag?",
         opties=["de mening van de groep",
                 "de hoeveelheid slaap erbij",
                 "de pijn in je buik erbij",
                 "het gewicht van je lichaam"],
         antwoord=0,
         uitleg="Wat de groep, het gezin of de cultuur verwacht, stuurt gedrag mee."),
    dict(type="meerkeuze",
         vraag="Wat is een cognitieve factor bij gedrag?",
         opties=["wat je denkt en weet",
                 "wat je lichaam voelt",
                 "wie er rond je staat",
                 "hoeveel je geslapen hebt"],
         antwoord=0,
         uitleg="Je kennis, je gedachten en wat je van een situatie begrijpt."),
    dict(type="meerkeuze",
         vraag="Waarom reageren twee kinderen anders op hetzelfde?",
         opties=["hun factoren verschillen",
                 "ze doen het met opzet",
                 "de regels verschillen erbij",
                 "het toeval beslist erbij"],
         antwoord=0,
         uitleg="Elk kind brengt een ander lichaam, een andere ervaring en een andere omgeving mee."),
    dict(type="meerkeuze",
         vraag="Wat doe je eerst als een kind moeilijk gedrag stelt?",
         opties=["je zoekt de oorzaak",
                 "je straft het meteen",
                 "je stuurt het weg erbij",
                 "je negeert het erbij"],
         antwoord=0,
         uitleg="Gedrag is een signaal. Eerst kijken wat eronder zit, dan handelen."),
    dict(type="meerkeuze",
         vraag="Wat zit vaak achter moeilijk gedrag?",
         opties=["een behoefte die niet vervuld is",
                 "gewoon vervelend willen zijn",
                 "een plan om te plagen erbij",
                 "niets in het bijzonder erbij"],
         antwoord=0,
         uitleg="Honger, moeheid, angst of te weinig aandacht komen er vaak als gedrag uit."),
    dict(type="meerkeuze",
         vraag="Wat is een behoefte?",
         opties=["iets wat je nodig hebt",
                 "iets wat je graag wil",
                 "iets wat je mooi vindt",
                 "iets wat je soms koopt"],
         antwoord=0,
         uitleg="Een behoefte is noodzakelijk; een wens is iets wat leuk zou zijn."),
    dict(type="waarofniet",
         vraag="Denken en voelen horen ook bij gedrag.",
         antwoord=True,
         uitleg="Dat is niet-waarneembaar gedrag: je ziet het niet, maar het is er wel."),
    dict(type="waarofniet",
         vraag="Reflexmatig gedrag kies je zelf.",
         antwoord=False,
         uitleg="Een reflex gebeurt automatisch, zonder dat je erover nadenkt."),
    dict(type="waarofniet",
         vraag="Honger kan het gedrag van een kind veranderen.",
         antwoord=True,
         uitleg="Een biologische factor als honger of moeheid stuurt gedrag sterk."),
    dict(type="waarofniet",
         vraag="Achter moeilijk gedrag zit nooit een behoefte.",
         antwoord=False,
         uitleg="Heel vaak zit er juist een behoefte achter die niet vervuld wordt."),
    dict(type="invultekst",
         vraag="Hoe noem je gedrag dat je kan zien? Eén woord.",
         antwoord=["waarneembaar", "waarneembaar gedrag", "zichtbaar"],
         uitleg="Waarneembaar gedrag."),
    dict(type="invultekst",
         vraag="Hoe noem je gedrag dat automatisch gebeurt? Eén woord.",
         antwoord=["reflexmatig", "reflex", "reflexmatig gedrag"],
         uitleg="Reflexmatig gedrag."),
    dict(type="invultekst",
         vraag="Hoe noem je iets wat een mens echt nodig heeft? Eén woord.",
         antwoord=["behoefte", "een behoefte", "behoeften"],
         uitleg="Een behoefte."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wie maakte de behoeftepiramide?",
         opties=["Maslow",
                 "Piaget erbij",
                 "Erikson erbij",
                 "Kohlberg erbij"],
         antwoord=0,
         uitleg="Abraham Maslow ordende de behoeften van de mens in een piramide."),
    dict(type="meerkeuze",
         vraag="Welke behoeften staan in de piramide van Maslow?",
         opties=["fysieke behoeften",
                 "zekerheid",
                 "erkenning",
                 "beloning"],
         antwoord=[0, 1, 2],
         uitleg="Fysieke behoeften, zekerheid, sociaal contact, erkenning en zelfactualisatie."),
    dict(type="meerkeuze",
         vraag="Welke behoefte staat onderaan de piramide?",
         opties=["de fysieke behoeften",
                 "de erkenning erbij",
                 "de zelfactualisatie",
                 "het erbij horen erbij"],
         antwoord=0,
         uitleg="Eten, drinken, slapen en warmte: zonder die basis komt de rest niet."),
    dict(type="meerkeuze",
         vraag="Welke behoefte staat bovenaan de piramide?",
         opties=["de zelfactualisatie",
                 "het eten en drinken",
                 "de veiligheid erbij",
                 "het erbij horen erbij"],
         antwoord=0,
         uitleg="Zelfactualisatie: worden wie je ten volle kan zijn."),
    dict(type="meerkeuze",
         vraag="Wat hoort bij zelfactualisatie?",
         opties=["worden wie je kan zijn",
                 "je talenten gebruiken",
                 "jezelf ontplooien",
                 "alles kunnen kopen"],
         antwoord=[0, 1, 2],
         uitleg="Je talenten en je mogelijkheden ten volle gebruiken."),
    dict(type="meerkeuze",
         vraag="Wat betekent de piramide van Maslow?",
         opties=["de onderste komt eerst",
                 "de bovenste komt eerst",
                 "de volgorde maakt niets uit",
                 "alles gebeurt tegelijk erbij"],
         antwoord=0,
         uitleg="Pas als de lagere behoeften vervuld zijn, komen de hogere aan de beurt."),
    dict(type="meerkeuze",
         vraag="Waarom kan een hongerig kind niet goed leren?",
         opties=["de fysieke behoefte gaat voor",
                 "het wil niet leren erbij",
                 "het is te lui erbij",
                 "het denkt aan spelen erbij"],
         antwoord=0,
         uitleg="De onderste laag van de piramide eist eerst aandacht."),
    dict(type="meerkeuze",
         vraag="Welke basisbehoeften noemt Kind en Gezin?",
         opties=["affectie",
                 "veiligheid",
                 "erkenning",
                 "beloning"],
         antwoord=[0, 1, 2],
         uitleg="Zes in totaal: lichamelijke behoeften, affectie, veiligheid, erkenning, zichzelf kundig voelen en zingeving."),
    dict(type="meerkeuze",
         vraag="Wat is affectie als basisbehoefte?",
         opties=["warmte en liefde krijgen",
                 "eten en drinken krijgen",
                 "regels en grenzen krijgen",
                 "een beloning krijgen erbij"],
         antwoord=0,
         uitleg="Een kind heeft warmte, knuffels en nabijheid nodig om te groeien."),
    dict(type="meerkeuze",
         vraag="Wat hoort bij de behoefte aan veiligheid?",
         opties=["duidelijkheid en continuïteit",
                 "elke dag iets nieuws erbij",
                 "steeds wisselende regels",
                 "telkens een andere persoon"],
         antwoord=0,
         uitleg="Veiligheid, duidelijkheid en continuïteit horen bij elkaar: vaste mensen, vaste afspraken."),
    dict(type="meerkeuze",
         vraag="Wat betekent zichzelf als kundig ervaren?",
         opties=["het kind voelt dat het kan",
                 "het kind krijgt alles cadeau",
                 "alles wordt voorgedaan erbij",
                 "niets lukt het kind erbij"],
         antwoord=0,
         uitleg="Een kind moet ervaren dat het zelf iets kan: zijn jas dichtdoen, een toren bouwen."),
    dict(type="meerkeuze",
         vraag="Hoe help je een kind zichzelf als kundig te voelen?",
         opties=["je laat het zelf proberen",
                 "je doet het altijd voor",
                 "je neemt het werk over",
                 "je zegt dat het niet lukt"],
         antwoord=0,
         uitleg="Zelf proberen, met hulp in de buurt, laat een kind zijn eigen kunnen voelen."),
    dict(type="meerkeuze",
         vraag="Wat is de behoefte aan zingeving?",
         opties=["weten waarom iets telt",
                 "weten hoeveel iets kost",
                 "weten wanneer het stopt",
                 "weten waar iets ligt erbij"],
         antwoord=0,
         uitleg="Zingeving en morele waarden: weten waarom iets belangrijk is en wat goed is."),
    dict(type="waarofniet",
         vraag="Volgens Maslow komen de fysieke behoeften eerst.",
         antwoord=True,
         uitleg="Ze staan onderaan de piramide en moeten eerst vervuld zijn."),
    dict(type="waarofniet",
         vraag="Erkenning en bevestiging is een basisbehoefte van een kind.",
         antwoord=True,
         uitleg="Het staat in de zes basisbehoeften van Kind en Gezin, en ook bij Maslow."),
    dict(type="waarofniet",
         vraag="Affectie betekent regels en grenzen geven.",
         antwoord=False,
         uitleg="Affectie is warmte en liefde; regels en grenzen horen bij veiligheid en duidelijkheid."),
    dict(type="waarofniet",
         vraag="Een kind dat honger heeft, leert even goed als een ander.",
         antwoord=False,
         uitleg="De fysieke behoefte vraagt eerst aandacht; leren komt daarna."),
    dict(type="invultekst",
         vraag="Hoe noem je de piramide met de behoeften van de mens? Eén woord.",
         antwoord=["behoeftepiramide", "de behoeftepiramide", "piramide van maslow"],
         uitleg="De behoeftepiramide van Maslow."),
    dict(type="invultekst",
         vraag="Hoe noem je de behoefte aan warmte en liefde? Eén woord.",
         antwoord=["affectie", "de affectie"],
         uitleg="Affectie."),
    dict(type="invultekst",
         vraag="Hoe noem je de hoogste behoefte in de piramide van Maslow? Eén woord.",
         antwoord=["zelfactualisatie", "de zelfactualisatie", "zelfontplooiing"],
         uitleg="Zelfactualisatie."),
]
