# -*- coding: utf-8 -*-
"""Ontwikkeling: basisbegrippen, fasen en domeinen.

Van de vakfiche ontwikkeling en pedagogisch handelen 2DU (2027), bouwsteen
ontwikkeling: ontwikkeling als combinatie van groeien, rijpen en leren, de
negen levensloopfasen, de ontwikkelingsfactoren nature, nurture en
zelfbepaling, en de ontwikkelingsdomeinen.

Deel 1 zijn groeien, rijpen, leren en de levensloopfasen.
Deel 2 zijn de ontwikkelingsfactoren en de ontwikkelingsdomeinen.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Uit welke delen bestaat ontwikkeling?",
         opties=["groeien",
                 "rijpen",
                 "leren",
                 "verhuizen"],
         antwoord=[0, 1, 2],
         uitleg="Ontwikkeling is altijd een combinatie van groeien, rijpen en leren."),
    dict(type="meerkeuze",
         vraag="Wat is groeien?",
         opties=["groter worden",
                 "iets nieuws leren erbij",
                 "klaar zijn voor iets erbij",
                 "naar school gaan erbij"],
         antwoord=0,
         uitleg="Groeien is lichamelijk: groter, zwaarder en anders van verhouding worden."),
    dict(type="meerkeuze",
         vraag="Wat is rijpen?",
         opties=["klaar worden voor iets",
                 "groter en zwaarder worden",
                 "iets nieuws oefenen erbij",
                 "naar de school gaan erbij"],
         antwoord=0,
         uitleg="Rijpen gebeurt vanzelf: het lichaam en de hersenen worden klaar voor een volgende stap."),
    dict(type="meerkeuze",
         vraag="Wat is leren?",
         opties=["door ervaring veranderen",
                 "langer worden erbij",
                 "zwaarder worden erbij",
                 "ouder worden erbij"],
         antwoord=0,
         uitleg="Leren komt van ervaring, oefening en wat de omgeving aanbiedt."),
    dict(type="meerkeuze",
         vraag="Een kind wordt tien centimeter langer. Wat is dat?",
         opties=["groeien",
                 "rijpen erbij",
                 "leren erbij",
                 "oefenen erbij"],
         antwoord=0,
         uitleg="Groter worden is groeien."),
    dict(type="meerkeuze",
         vraag="Een baby kan plots stappen zonder dat iemand het hem leerde. Wat is dat?",
         opties=["rijpen",
                 "groeien erbij",
                 "leren erbij",
                 "oefenen erbij"],
         antwoord=0,
         uitleg="Het lichaam was er klaar voor. Dat is rijpen, niet leren."),
    dict(type="meerkeuze",
         vraag="Welke levensloopfasen zijn er bij kinderen?",
         opties=["de babytijd",
                 "de peutertijd",
                 "de kleutertijd",
                 "de pensioentijd"],
         antwoord=[0, 1, 2],
         uitleg="De pensioentijd hoort bij de late volwassenheid."),
    dict(type="meerkeuze",
         vraag="Welke fase komt voor de geboorte?",
         opties=["de prenatale fase",
                 "de babytijd erbij",
                 "de peutertijd erbij",
                 "de kleutertijd erbij"],
         antwoord=0,
         uitleg="De prenatale fase loopt van de bevruchting tot de geboorte."),
    dict(type="meerkeuze",
         vraag="Hoe heet de midden-kindertijd ook?",
         opties=["de lagereschoolfase",
                 "de peutertijd erbij",
                 "de adolescentie erbij",
                 "de prenatale fase erbij"],
         antwoord=0,
         uitleg="De midden-kindertijd is de lagereschoolkindfase."),
    dict(type="meerkeuze",
         vraag="Welke fase komt na de midden-kindertijd?",
         opties=["de adolescentie",
                 "de kleutertijd erbij",
                 "de peutertijd erbij",
                 "de babytijd erbij"],
         antwoord=0,
         uitleg="Na de lagereschoolkindfase volgt de adolescentie."),
    dict(type="meerkeuze",
         vraag="Welke levensloopfasen horen bij volwassenen?",
         opties=["de vroege volwassenheid",
                 "de midden-volwassenheid",
                 "de late volwassenheid",
                 "de adolescentie erbij"],
         antwoord=[0, 1, 2],
         uitleg="De adolescentie komt voor de volwassenheid."),
    dict(type="meerkeuze",
         vraag="Hoeveel levensloopfasen zijn er?",
         opties=["negen",
                 "vijf fasen in totaal",
                 "zeven fasen in totaal",
                 "drie fasen in totaal"],
         antwoord=0,
         uitleg="Negen: prenataal, baby, peuter, kleuter, lagereschoolkind, adolescent, en de drie fasen van de volwassenheid."),
    dict(type="meerkeuze",
         vraag="Waarom deel je de levensloop in fasen?",
         opties=["elke fase heeft kenmerken",
                 "elke fase duurt even lang",
                 "elke fase is gelijk erbij",
                 "elke fase komt twee keer"],
         antwoord=0,
         uitleg="Elke fase heeft haar eigen typische ontwikkeling, behoeften en aandachtspunten."),
    dict(type="waarofniet",
         vraag="Ontwikkeling is alleen groeien.",
         antwoord=False,
         uitleg="Ontwikkeling is groeien, rijpen en leren samen."),
    dict(type="waarofniet",
         vraag="Rijpen gebeurt vanzelf, zonder oefenen.",
         antwoord=True,
         uitleg="Rijpen volgt uit de aanleg. Leren vraagt wel oefening."),
    dict(type="waarofniet",
         vraag="De adolescentie komt na de midden-kindertijd.",
         antwoord=True,
         uitleg="Na de lagereschoolkindfase volgt de adolescentie."),
    dict(type="waarofniet",
         vraag="De prenatale fase begint bij de geboorte.",
         antwoord=False,
         uitleg="De prenatale fase eindigt bij de geboorte; daarna begint de babytijd."),
    dict(type="invultekst",
         vraag="Hoe noem je de fase voor de geboorte? Hoogstens drie woorden.",
         antwoord=["prenatale fase", "de prenatale fase", "prenataal"],
         uitleg="De prenatale fase."),
    dict(type="invultekst",
         vraag="Welk deel van ontwikkeling betekent groter en zwaarder worden? Eén woord.",
         antwoord=["groeien", "het groeien", "groei"],
         uitleg="Groeien."),
    dict(type="invultekst",
         vraag="Hoe noem je de fase tussen de kindertijd en de volwassenheid? Eén woord.",
         antwoord=["adolescentie", "de adolescentie", "puberteit"],
         uitleg="De adolescentie."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Welke ontwikkelingsfactoren zijn er?",
         opties=["erfelijkheid",
                 "de omgeving",
                 "de zelfbepaling",
                 "het toeval"],
         antwoord=[0, 1, 2],
         uitleg="Nature of erfelijkheid, nurture of omgeving, en zelfbepaling."),
    dict(type="meerkeuze",
         vraag="Wat betekent nature?",
         opties=["de erfelijkheid",
                 "de omgeving erbij",
                 "de eigen keuze erbij",
                 "de school erbij"],
         antwoord=0,
         uitleg="Nature is wat je meekrijgt van je ouders: je aanleg."),
    dict(type="meerkeuze",
         vraag="Wat betekent nurture?",
         opties=["de omgeving",
                 "de erfelijkheid erbij",
                 "de eigen keuze erbij",
                 "de lengte erbij"],
         antwoord=0,
         uitleg="Nurture is alles wat de omgeving aanbrengt: opvoeding, school, vrienden, cultuur."),
    dict(type="meerkeuze",
         vraag="Wat is zelfbepaling?",
         opties=["je kiest zelf mee",
                 "je ouders kiezen erbij",
                 "je genen kiezen erbij",
                 "de school kiest erbij"],
         antwoord=0,
         uitleg="Zelfbepaling betekent dat een kind ook zelf richting geeft aan zijn ontwikkeling."),
    dict(type="meerkeuze",
         vraag="Een kind lijkt op zijn moeder. Welke factor is dat?",
         opties=["de erfelijkheid",
                 "de omgeving erbij",
                 "de zelfbepaling erbij",
                 "de school erbij"],
         antwoord=0,
         uitleg="Uiterlijke gelijkenis komt van de erfelijkheid, dus van nature."),
    dict(type="meerkeuze",
         vraag="Een kind leert thuis twee talen. Welke factor is dat?",
         opties=["de omgeving",
                 "de erfelijkheid erbij",
                 "de zelfbepaling erbij",
                 "de rijping erbij"],
         antwoord=0,
         uitleg="Wat de omgeving aanbiedt, is nurture."),
    dict(type="meerkeuze",
         vraag="Welke ontwikkelingsdomeinen zijn er?",
         opties=["de fysieke ontwikkeling",
                 "de cognitieve ontwikkeling",
                 "de morele ontwikkeling",
                 "de financiële ontwikkeling"],
         antwoord=[0, 1, 2],
         uitleg="Verder nog de socio-emotionele ontwikkeling en de persoonlijkheidsontwikkeling."),
    dict(type="meerkeuze",
         vraag="Welk ontwikkelingsdomein hoort er nog bij?",
         opties=["de persoonlijkheid",
                 "de boekhouding erbij",
                 "de aardrijkskunde erbij",
                 "de rekenvaardigheid erbij"],
         antwoord=0,
         uitleg="De persoonlijkheidsontwikkeling, beschreven door Erikson."),
    dict(type="meerkeuze",
         vraag="Wat hoort bij de fysieke ontwikkeling?",
         opties=["de motoriek",
                 "de moraal erbij",
                 "het denken erbij",
                 "de vriendschap erbij"],
         antwoord=0,
         uitleg="De fysieke ontwikkeling omvat de lichamelijke, de sensorische, de motorische en de sensomotorische ontwikkeling."),
    dict(type="meerkeuze",
         vraag="Wat hoort bij de cognitieve ontwikkeling?",
         opties=["het denken",
                 "de lengte erbij",
                 "de motoriek erbij",
                 "de emoties erbij"],
         antwoord=0,
         uitleg="De cognitieve ontwikkeling is de ontwikkeling van het denken, beschreven door Piaget."),
    dict(type="meerkeuze",
         vraag="Wat hoort bij de socio-emotionele ontwikkeling?",
         opties=["de sociale ontwikkeling",
                 "omgaan met emoties",
                 "vriendschappen maken",
                 "de lengte van het kind"],
         antwoord=[0, 1, 2],
         uitleg="De lengte hoort bij de lichamelijke ontwikkeling."),
    dict(type="meerkeuze",
         vraag="Wie beschreef de cognitieve ontwikkeling?",
         opties=["Piaget",
                 "Kohlberg erbij",
                 "Erikson erbij",
                 "Maslow erbij"],
         antwoord=0,
         uitleg="Piaget beschreef de vier stadia van het denken."),
    dict(type="meerkeuze",
         vraag="Wie beschreef de morele ontwikkeling?",
         opties=["Kohlberg",
                 "Piaget erbij",
                 "Erikson erbij",
                 "Lalonde erbij"],
         antwoord=0,
         uitleg="Kohlberg beschreef de drie stadia van het moreel handelen."),
    dict(type="waarofniet",
         vraag="Nature staat voor de omgeving.",
         antwoord=False,
         uitleg="Nature is de erfelijkheid. Nurture is de omgeving."),
    dict(type="waarofniet",
         vraag="Zelfbepaling betekent dat een kind ook zelf richting geeft.",
         antwoord=True,
         uitleg="Naast nature en nurture bepaalt het kind zelf mee hoe het zich ontwikkelt."),
    dict(type="waarofniet",
         vraag="Erikson beschreef de persoonlijkheidsontwikkeling.",
         antwoord=True,
         uitleg="Erikson werkte met conflicten per levensloopfase."),
    dict(type="waarofniet",
         vraag="De motoriek hoort bij de cognitieve ontwikkeling.",
         antwoord=False,
         uitleg="De motoriek hoort bij de fysieke ontwikkeling."),
    dict(type="invultekst",
         vraag="Welk woord staat voor erfelijkheid bij de ontwikkelingsfactoren? Eén woord.",
         antwoord=["nature", "de nature"],
         uitleg="Nature."),
    dict(type="invultekst",
         vraag="Welk woord staat voor de omgeving bij de ontwikkelingsfactoren? Eén woord.",
         antwoord=["nurture", "de nurture"],
         uitleg="Nurture."),
    dict(type="invultekst",
         vraag="Wie beschreef de persoonlijkheidsontwikkeling? Eén woord.",
         antwoord=["erikson", "erik erikson"],
         uitleg="Erikson."),
]
