# -*- coding: utf-8 -*-
"""Communiceren en actief luisteren.

Van de vakfiche ontwikkeling en pedagogisch handelen 2DU (2027), bouwsteen
pedagogisch handelen: verbale en non-verbale communicatie, lichaamstaal, de
fasen van een gesprek en de aandachtspunten bij kinderen en bij ouderen.
Daarna het luisteren: oppervlakkig, inhoudelijk en actief luisteren, en de
LSD-methode met luisteren, samenvatten en doorvragen.

Deel 1 is communiceren.
Deel 2 is luisteren.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat hoort bij non-verbale communicatie?",
         opties=["je lichaamshouding",
                 "je gezichtsuitdrukking",
                 "je stemtoon",
                 "je woordkeuze"],
         antwoord=[0, 1, 2],
         uitleg="Alles behalve de woorden zelf: houding, gezicht, stem, gebaren en afstand."),
    dict(type="meerkeuze",
         vraag="Wat is verbale communicatie?",
         opties=["de woorden die je zegt",
                 "de stand van je lichaam",
                 "de blik in je ogen erbij",
                 "de afstand tussen jullie"],
         antwoord=0,
         uitleg="Verbaal is wat je in woorden zegt of schrijft."),
    dict(type="meerkeuze",
         vraag="Waarom is lichaamstaal belangrijk?",
         opties=["ze zegt vaak meer dan woorden",
                 "ze is altijd onbelangrijk",
                 "ze is enkel voor kinderen",
                 "ze verandert nooit erbij"],
         antwoord=0,
         uitleg="Een kind dat zegt dat het goed gaat maar met gebogen hoofd zit, vertelt iets anders."),
    dict(type="meerkeuze",
         vraag="Wat doe je als woorden en lichaamstaal niet samengaan?",
         opties=["je vraagt ernaar",
                 "je gelooft enkel de woorden",
                 "je negeert het erbij",
                 "je lacht het weg erbij"],
         antwoord=0,
         uitleg="\"Je zegt dat het goed gaat, maar je kijkt verdrietig. Klopt dat?\""),
    dict(type="meerkeuze",
         vraag="Welke fasen heeft een gesprek?",
         opties=["groeten",
                 "jezelf voorstellen",
                 "kennismaken",
                 "weglopen"],
         antwoord=[0, 1, 2],
         uitleg="Groeten, jezelf voorstellen, kennismaken, het dagelijkse gesprek en afscheid nemen."),
    dict(type="meerkeuze",
         vraag="Waarmee begin je een gesprek?",
         opties=["je groet",
                 "je vertrekt erbij",
                 "je zwijgt erbij",
                 "je draait je om erbij"],
         antwoord=0,
         uitleg="Groeten is de eerste fase, en meteen ook de eerste indruk."),
    dict(type="meerkeuze",
         vraag="Waarmee eindig je een gesprek?",
         opties=["je neemt afscheid",
                 "je loopt gewoon weg",
                 "je zwijgt plots erbij",
                 "je draait je om erbij"],
         antwoord=0,
         uitleg="Afscheid nemen hoort erbij: het sluit het gesprek netjes af."),
    dict(type="meerkeuze",
         vraag="Hoe praat je het best met een jong kind?",
         opties=["korte zinnen op ooghoogte",
                 "lange zinnen van ver erbij",
                 "moeilijke woorden erbij",
                 "snel en luid praten erbij"],
         antwoord=0,
         uitleg="Zak door je knieën, kijk het kind aan en gebruik korte, duidelijke zinnen."),
    dict(type="meerkeuze",
         vraag="Hoe praat je het best met een oudere persoon?",
         opties=["rustig en duidelijk",
                 "heel snel en luid erbij",
                 "in moeilijke woorden erbij",
                 "zonder hem aan te kijken"],
         antwoord=0,
         uitleg="Rustig tempo, duidelijke woorden, en hem aankijken terwijl je praat."),
    dict(type="meerkeuze",
         vraag="Wat doe je als een oudere slechthorend is?",
         opties=["je kijkt hem aan",
                 "je roept van ver erbij",
                 "je praat sneller erbij",
                 "je zegt het maar één keer"],
         antwoord=0,
         uitleg="Door je gezicht te laten zien, kan hij meelezen op je lippen."),
    dict(type="meerkeuze",
         vraag="Wat is oogcontact in een gesprek?",
         opties=["je kijkt de ander aan",
                 "je kijkt naar de grond",
                 "je kijkt op je gsm erbij",
                 "je kijkt door het raam erbij"],
         antwoord=0,
         uitleg="Oogcontact laat zien dat je er echt bij bent."),
    dict(type="meerkeuze",
         vraag="Wat betekent kennismaken in een gesprek?",
         opties=["je leert elkaar kennen",
                 "je neemt meteen afscheid",
                 "je praat enkel over jezelf",
                 "je zegt niets erbij"],
         antwoord=0,
         uitleg="Na het voorstellen volgt de kennismaking: je vraagt en vertelt om en om."),
    dict(type="meerkeuze",
         vraag="Wat hoort bij een respectvolle begroeting?",
         opties=["je zegt goedendag",
                 "je kijkt de ander aan",
                 "je noemt zijn naam",
                 "je blijft op je gsm"],
         antwoord=[0, 1, 2],
         uitleg="Groeten, aankijken en iemand bij naam noemen maakt het persoonlijk."),
    dict(type="waarofniet",
         vraag="Lichaamstaal hoort bij de non-verbale communicatie.",
         antwoord=True,
         uitleg="Houding, gebaren en gezichtsuitdrukking zijn allemaal non-verbaal."),
    dict(type="waarofniet",
         vraag="Oogcontact maakt een gesprek onbeleefd.",
         antwoord=False,
         uitleg="Het toont net dat je aandacht hebt voor de ander."),
    dict(type="waarofniet",
         vraag="Bij een jong kind gebruik je het best korte zinnen.",
         antwoord=True,
         uitleg="Kort, duidelijk en op ooghoogte werkt het best."),
    dict(type="waarofniet",
         vraag="Verbale communicatie zijn de gebaren die je maakt.",
         antwoord=False,
         uitleg="Gebaren zijn non-verbaal; verbaal zijn de woorden."),
    dict(type="invultekst",
         vraag="Hoe noem je communicatie zonder woorden? Eén woord.",
         antwoord=["non-verbaal", "nonverbaal", "non-verbale communicatie"],
         uitleg="Non-verbale communicatie."),
    dict(type="invultekst",
         vraag="Hoe noem je de taal van je houding en je gebaren? Eén woord.",
         antwoord=["lichaamstaal", "de lichaamstaal"],
         uitleg="Lichaamstaal."),
    dict(type="invultekst",
         vraag="Hoe noem je de laatste fase van een gesprek? Eén woord.",
         antwoord=["afscheid", "afscheid nemen", "het afscheid"],
         uitleg="Afscheid nemen."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is oppervlakkig luisteren?",
         opties=["je hoort het maar half",
                 "je luistert heel goed erbij",
                 "je vraagt alles na erbij",
                 "je vat samen wat je hoort"],
         antwoord=0,
         uitleg="Je hoort de klank, maar je neemt niet echt op wat er gezegd wordt."),
    dict(type="meerkeuze",
         vraag="Wat is inhoudelijk luisteren?",
         opties=["je volgt wat er gezegd wordt",
                 "je hoort het maar half erbij",
                 "je denkt aan iets anders",
                 "je onderbreekt meteen erbij"],
         antwoord=0,
         uitleg="Je volgt de inhoud, maar je laat nog niet merken dat je luistert."),
    dict(type="meerkeuze",
         vraag="Wat is actief luisteren?",
         opties=["je toont dat je luistert",
                 "je zwijgt en kijkt weg",
                 "je denkt aan je antwoord",
                 "je onderbreekt de ander"],
         antwoord=0,
         uitleg="Je knikt, je vat samen en je vraagt door, zodat de ander merkt dat je er bent."),
    dict(type="meerkeuze",
         vraag="Waarvoor staat de LSD-methode?",
         opties=["luisteren",
                 "samenvatten",
                 "doorvragen",
                 "discussiëren"],
         antwoord=[0, 1, 2],
         uitleg="Luisteren, Samenvatten, Doorvragen."),
    dict(type="meerkeuze",
         vraag="Wat doe je bij de L van LSD?",
         opties=["je luistert actief",
                 "je vat samen erbij",
                 "je vraagt door erbij",
                 "je geeft je mening erbij"],
         antwoord=0,
         uitleg="Actief luisteren, met je houding, je ogen en kleine aanmoedigingen."),
    dict(type="meerkeuze",
         vraag="Wat doe je bij de S van LSD?",
         opties=["je vat samen",
                 "je luistert erbij",
                 "je vraagt door erbij",
                 "je zegt je mening erbij"],
         antwoord=0,
         uitleg="Je herhaalt in je eigen woorden wat je begrepen hebt."),
    dict(type="meerkeuze",
         vraag="Wat doe je bij de D van LSD?",
         opties=["je vraagt door",
                 "je vat samen erbij",
                 "je zwijgt erbij",
                 "je besluit erbij"],
         antwoord=0,
         uitleg="Je stelt open vragen en gevoelsvragen om verder te komen."),
    dict(type="meerkeuze",
         vraag="Waarom vat je samen in een gesprek?",
         opties=["je gaat na of je goed begreep",
                 "je toont dat je slim bent",
                 "je maakt het gesprek korter",
                 "je wil iets anders zeggen"],
         antwoord=0,
         uitleg="Samenvatten geeft de ander de kans om je recht te zetten."),
    dict(type="meerkeuze",
         vraag="Wat hoort bij een actieve lichaamshouding?",
         opties=["je draait je naar de ander",
                 "je knikt af en toe",
                 "je kijkt hem aan",
                 "je kruist je armen"],
         antwoord=[0, 1, 2],
         uitleg="Gekruiste armen lezen als afstand; de rest nodigt uit om verder te praten."),
    dict(type="meerkeuze",
         vraag="Wat is een open vraag?",
         opties=["ze vraagt om meer uitleg",
                 "ze vraagt ja of nee",
                 "ze vraagt een getal erbij",
                 "ze vraagt een naam erbij"],
         antwoord=0,
         uitleg="\"Hoe was dat voor jou?\" levert meer op dan \"Was dat leuk?\""),
    dict(type="meerkeuze",
         vraag="Wat is een gevoelsvraag?",
         opties=["ze peilt naar het gevoel",
                 "ze vraagt naar een datum",
                 "ze vraagt naar een getal",
                 "ze vraagt naar een naam"],
         antwoord=0,
         uitleg="\"Hoe voelde je je toen?\" laat de ander zijn gevoel benoemen."),
    dict(type="meerkeuze",
         vraag="Waarom zijn stiltes nuttig in een gesprek?",
         opties=["de ander krijgt tijd",
                 "het gesprek stopt erbij",
                 "niemand weet iets meer",
                 "de stilte is altijd pijnlijk"],
         antwoord=0,
         uitleg="Een stilte geeft de ander de ruimte om verder te denken en te spreken."),
    dict(type="meerkeuze",
         vraag="Wat zijn kleine aanmoedigingen bij het luisteren?",
         opties=["een knikje",
                 "een hm",
                 "een ja",
                 "een lange uitleg"],
         antwoord=[0, 1, 2],
         uitleg="Een knikje, een \"hm\" of een \"ja\" laat merken dat je nog mee bent."),
    dict(type="waarofniet",
         vraag="Bij actief luisteren laat je merken dat je luistert.",
         antwoord=True,
         uitleg="Met je houding, je ogen, kleine aanmoedigingen, samenvatten en doorvragen."),
    dict(type="waarofniet",
         vraag="Een open vraag kan je met ja of nee beantwoorden.",
         antwoord=False,
         uitleg="Dat is net een gesloten vraag; een open vraag vraagt om uitleg."),
    dict(type="waarofniet",
         vraag="De D van LSD staat voor doorvragen.",
         antwoord=True,
         uitleg="Luisteren, Samenvatten, Doorvragen."),
    dict(type="waarofniet",
         vraag="Stiltes moet je in een gesprek altijd meteen opvullen.",
         antwoord=False,
         uitleg="Een stilte geeft de ander net de tijd om verder te vertellen."),
    dict(type="invultekst",
         vraag="Waarvoor staat de L in de LSD-methode? Eén woord.",
         antwoord=["luisteren", "actief luisteren"],
         uitleg="Luisteren."),
    dict(type="invultekst",
         vraag="Waarvoor staat de D in de LSD-methode? Eén woord.",
         antwoord=["doorvragen", "vragen stellen"],
         uitleg="Doorvragen."),
    dict(type="invultekst",
         vraag="Hoe noem je een vraag waarop je niet met ja of nee kan antwoorden? Eén woord.",
         antwoord=["open", "open vraag", "een open vraag"],
         uitleg="Een open vraag."),
]
