# -*- coding: utf-8 -*-
"""De fysieke ontwikkeling van kinderen en adolescenten.

Van de vakfiche ontwikkeling en pedagogisch handelen 2DU (2027), bouwsteen
ontwikkeling: de lichamelijke ontwikkeling met groeicurves, de vier
groeiprincipes bij een baby en de groeispurt, de sensorische ontwikkeling van
het jonge kind, de motorische ontwikkeling met de babyreflexen en de
mijlpalen van de grove en de fijne motoriek, en de sensomotorische
ontwikkeling.

Deel 1 zijn de lichamelijke en de sensorische ontwikkeling.
Deel 2 zijn de motorische en de sensomotorische ontwikkeling.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is een groeicurve?",
         opties=["een lijn met de groei",
                 "een lijst met namen erbij",
                 "een tabel met prijzen erbij",
                 "een kaart van de school erbij"],
         antwoord=0,
         uitleg="Een groeicurve zet de lengte of het gewicht van een kind naast die van leeftijdsgenoten."),
    dict(type="meerkeuze",
         vraag="Wat lees je af van een groeicurve?",
         opties=["of de groei normaal is",
                 "of het kind slim is erbij",
                 "of het kind lief is erbij",
                 "of het kind veel slaapt erbij"],
         antwoord=0,
         uitleg="Je ziet of een kind de verwachte lijn volgt of er plots van afwijkt."),
    dict(type="meerkeuze",
         vraag="Wat staat er op een groeicurve?",
         opties=["de lengte",
                 "het gewicht",
                 "de leeftijd",
                 "het rapport"],
         antwoord=[0, 1, 2],
         uitleg="Een groeicurve zet lengte of gewicht uit tegenover de leeftijd."),
    dict(type="meerkeuze",
         vraag="Wat betekent het groeiprincipe van kop naar staart?",
         opties=["het hoofd ontwikkelt eerst",
                 "de voeten ontwikkelen eerst",
                 "alles ontwikkelt tegelijk erbij",
                 "de handen komen het eerst erbij"],
         antwoord=0,
         uitleg="Een baby heeft eerst controle over hoofd en nek, dan over de romp, dan over de benen."),
    dict(type="meerkeuze",
         vraag="Wat betekent het groeiprincipe van midden naar buiten?",
         opties=["de romp komt voor de hand",
                 "de hand komt voor de romp",
                 "de vingers komen eerst erbij",
                 "de voeten komen eerst erbij"],
         antwoord=0,
         uitleg="De ontwikkeling gaat van het midden van het lichaam naar de uiteinden toe."),
    dict(type="meerkeuze",
         vraag="Wat betekent van grof naar fijn?",
         opties=["eerst grote bewegingen",
                 "eerst de kleine bewegingen",
                 "eerst de vingers gebruiken",
                 "eerst een pen vasthouden"],
         antwoord=0,
         uitleg="Een kind grijpt eerst met de hele hand en pas later met duim en wijsvinger."),
    dict(type="meerkeuze",
         vraag="Wat is een groeispurt?",
         opties=["een snelle groeiperiode",
                 "een stilstand in de groei",
                 "een periode zonder groei",
                 "een jaar met weinig groei"],
         antwoord=0,
         uitleg="In korte tijd wordt een kind veel langer en zwaarder, vooral in de puberteit."),
    dict(type="meerkeuze",
         vraag="Wat is een gevolg van een vroege groeispurt?",
         opties=["je valt uit de toon",
                 "je groeit nooit meer erbij",
                 "je wordt altijd kleiner",
                 "je blijft even groot erbij"],
         antwoord=0,
         uitleg="Wie veel eerder groeit dan de klas, krijgt vaak opmerkingen en wordt ouder behandeld dan hij is."),
    dict(type="meerkeuze",
         vraag="Wat is een gevolg van een late groeispurt?",
         opties=["je voelt je kleiner",
                 "je bent meteen de grootste",
                 "je stopt met groeien erbij",
                 "je wordt altijd de sterkste"],
         antwoord=0,
         uitleg="Wie later groeit, voelt zich tijdelijk kleiner en jonger dan zijn leeftijdsgenoten."),
    dict(type="meerkeuze",
         vraag="Waarom kan een groeispurt moeilijk zijn voor een tiener?",
         opties=["hij valt op in de groep",
                 "hij voelt zich anders",
                 "hij wordt onhandiger",
                 "hij leert trager lezen"],
         antwoord=[0, 1, 2],
         uitleg="Het lichaam verandert sneller dan de motoriek volgt, en dat valt op. Lezen heeft er niets mee te maken."),
    dict(type="meerkeuze",
         vraag="Welke zintuigen werken al goed bij een pasgeboren baby?",
         opties=["het gehoor",
                 "de reuk",
                 "de smaak",
                 "het dieptezicht"],
         antwoord=[0, 1, 2],
         uitleg="Gehoor, reuk en smaak werken al rond de geboorte. Het zicht en het dieptezicht hebben nog maanden nodig."),
    dict(type="meerkeuze",
         vraag="Hoe ziet een pasgeboren baby?",
         opties=["nog erg onscherp",
                 "even scherp als jij",
                 "helemaal niets erbij",
                 "in alle kleuren erbij"],
         antwoord=0,
         uitleg="Een baby ziet op korte afstand en nog onscherp; het zicht ontwikkelt het laatst."),
    dict(type="meerkeuze",
         vraag="Welk zintuig gebruikt een baby om zijn moeder te herkennen?",
         opties=["de reuk",
                 "het dieptezicht erbij",
                 "de smaak van zout erbij",
                 "het kleurenzicht erbij"],
         antwoord=0,
         uitleg="Reuk en gehoor zijn vroeg klaar, dus daar herkent een baby zijn vertrouwde mensen aan."),
    dict(type="waarofniet",
         vraag="Een groeicurve vergelijkt een kind met leeftijdsgenoten.",
         antwoord=True,
         uitleg="De curve toont waar een kind zit tegenover de gemiddelde groei van zijn leeftijd."),
    dict(type="waarofniet",
         vraag="Alle kinderen hebben hun groeispurt op dezelfde leeftijd.",
         antwoord=False,
         uitleg="De ene heeft een vroege, de andere een late groeispurt."),
    dict(type="waarofniet",
         vraag="De ontwikkeling gaat van grof naar fijn.",
         antwoord=True,
         uitleg="Grote bewegingen komen voor de kleine, precieze bewegingen."),
    dict(type="waarofniet",
         vraag="Een pasgeboren baby ziet even scherp als een volwassene.",
         antwoord=False,
         uitleg="Het zicht is bij de geboorte nog onscherp en ontwikkelt in de eerste maanden."),
    dict(type="invultekst",
         vraag="Hoe noem je een periode waarin een kind heel snel groeit? Eén woord.",
         antwoord=["groeispurt", "een groeispurt", "de groeispurt"],
         uitleg="Een groeispurt."),
    dict(type="invultekst",
         vraag="Hoe noem je de lijn waarmee je de groei van een kind opvolgt? Eén woord.",
         antwoord=["groeicurve", "de groeicurve", "groeicurves"],
         uitleg="De groeicurve."),
    dict(type="invultekst",
         vraag="Welk zintuig ontwikkelt zich het laatst bij een baby? Eén woord.",
         antwoord=["zicht", "het zicht", "gezicht"],
         uitleg="Het zicht."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Welke reflexen heeft een baby?",
         opties=["de zuigreflex",
                 "de grijpreflex",
                 "de schrikreflex",
                 "de leesreflex erbij"],
         antwoord=[0, 1, 2],
         uitleg="Een leesreflex bestaat niet. Verder nog de zoekreflex en de stapreflex."),
    dict(type="meerkeuze",
         vraag="Wat doet de zuigreflex?",
         opties=["de baby zuigt meteen",
                 "de baby grijpt met de hand",
                 "de baby schrikt van geluid",
                 "de baby tilt het hoofd op"],
         antwoord=0,
         uitleg="Raak je de mond van een baby aan, dan begint hij te zuigen. Zo kan hij meteen drinken."),
    dict(type="meerkeuze",
         vraag="Wat doet de grijpreflex?",
         opties=["de hand sluit zich",
                 "de baby begint te zuigen",
                 "de baby draait het hoofd",
                 "de baby strekt de benen"],
         antwoord=0,
         uitleg="Leg je een vinger in het handje van een baby, dan sluit de hand zich eromheen."),
    dict(type="meerkeuze",
         vraag="Wat gebeurt er met de babyreflexen?",
         opties=["ze verdwijnen weer",
                 "ze blijven heel je leven",
                 "ze worden altijd sterker",
                 "ze komen later terug erbij"],
         antwoord=0,
         uitleg="De meeste babyreflexen verdwijnen in het eerste levensjaar, zodra de bewuste beweging overneemt."),
    dict(type="meerkeuze",
         vraag="Wat is grove motoriek?",
         opties=["grote bewegingen",
                 "kleine bewegingen erbij",
                 "bewegingen van de vingers",
                 "bewegingen van de ogen"],
         antwoord=0,
         uitleg="De grove motoriek zijn de grote bewegingen van armen, benen en romp: kruipen, stappen, lopen."),
    dict(type="meerkeuze",
         vraag="Wat is fijne motoriek?",
         opties=["kleine bewegingen",
                 "grote bewegingen erbij",
                 "bewegingen van de romp",
                 "bewegingen van de benen"],
         antwoord=0,
         uitleg="De fijne motoriek zijn de precieze bewegingen van de handen en de vingers."),
    dict(type="meerkeuze",
         vraag="Welke mijlpalen horen bij de grove motoriek?",
         opties=["zitten",
                 "kruipen",
                 "stappen",
                 "schrijven"],
         antwoord=[0, 1, 2],
         uitleg="Schrijven is fijne motoriek."),
    dict(type="meerkeuze",
         vraag="Welke mijlpaal komt eerst?",
         opties=["het hoofd optillen",
                 "het leren stappen erbij",
                 "het leren lopen erbij",
                 "het leren springen erbij"],
         antwoord=0,
         uitleg="Van kop naar staart: eerst het hoofd, dan rollen en zitten, dan kruipen en stappen."),
    dict(type="meerkeuze",
         vraag="Wat komt er eerst: zitten of stappen?",
         opties=["zitten",
                 "stappen erbij",
                 "beide tegelijk erbij",
                 "geen van beide erbij"],
         antwoord=0,
         uitleg="Zitten komt eerst, want de controle gaat van boven naar onder."),
    dict(type="meerkeuze",
         vraag="Welke mijlpalen horen bij de fijne motoriek?",
         opties=["met de hand grijpen",
                 "de pincetgreep",
                 "leren tekenen",
                 "leren kruipen"],
         antwoord=[0, 1, 2],
         uitleg="Kruipen is grove motoriek."),
    dict(type="meerkeuze",
         vraag="Wat is de pincetgreep?",
         opties=["duim en wijsvinger",
                 "de hele hand gebruiken",
                 "twee handen gebruiken",
                 "de voet gebruiken erbij"],
         antwoord=0,
         uitleg="Met duim en wijsvinger kan een kind kleine dingen oppakken, zoals een erwtje."),
    dict(type="meerkeuze",
         vraag="Wat is sensomotorische ontwikkeling?",
         opties=["zintuigen en beweging samen",
                 "enkel de beweging erbij",
                 "enkel de zintuigen erbij",
                 "enkel het denken erbij"],
         antwoord=0,
         uitleg="De zintuigen en de beweging werken samen: wat je ziet of hoort, stuurt wat je doet."),
    dict(type="meerkeuze",
         vraag="Wat is een voorbeeld van sensomotorisch handelen?",
         opties=["een bal zien en vangen",
                 "alleen stil blijven zitten",
                 "alleen naar een boek kijken",
                 "alleen een liedje beluisteren"],
         antwoord=0,
         uitleg="Je oog volgt de bal en je handen bewegen mee. Zintuig en beweging in één."),
    dict(type="waarofniet",
         vraag="De grove motoriek ontwikkelt zich voor de fijne motoriek.",
         antwoord=True,
         uitleg="Van grof naar fijn is een van de groeiprincipes."),
    dict(type="waarofniet",
         vraag="De babyreflexen blijven je hele leven.",
         antwoord=False,
         uitleg="De meeste verdwijnen in het eerste jaar."),
    dict(type="waarofniet",
         vraag="De pincetgreep hoort bij de fijne motoriek.",
         antwoord=True,
         uitleg="De pincetgreep is een precieze beweging van duim en wijsvinger."),
    dict(type="waarofniet",
         vraag="Een kind leert eerst stappen en daarna zitten.",
         antwoord=False,
         uitleg="Omgekeerd: eerst zitten, dan kruipen, dan stappen."),
    dict(type="invultekst",
         vraag="Hoe noem je de greep met duim en wijsvinger? Eén woord.",
         antwoord=["pincetgreep", "de pincetgreep"],
         uitleg="De pincetgreep."),
    dict(type="invultekst",
         vraag="Hoe noem je de grote bewegingen van armen, benen en romp? Hoogstens drie woorden.",
         antwoord=["grove motoriek", "grofmotoriek", "de grove motoriek"],
         uitleg="De grove motoriek."),
    dict(type="invultekst",
         vraag="Hoe noem je de reflex waarmee een baby meteen begint te zuigen? Eén woord.",
         antwoord=["zuigreflex", "de zuigreflex"],
         uitleg="De zuigreflex."),
]
