# -*- coding: utf-8 -*-
"""Feedback geven en verbindend communiceren.

Van de vakfiche ontwikkeling en pedagogisch handelen 2DU (2027), bouwsteen
pedagogisch handelen: feedback geven en ontvangen met het 4G-model en de
ik-boodschap, en daarna verbindend communiceren met de vier stappen
(waarneming, gevoel, behoefte, verzoek), de kenmerken van geweldloze
communicatie en de herstelgerichte vragen.

Deel 1 is feedback en de ik-boodschap.
Deel 2 is verbindend en herstelgericht communiceren.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is feedback?",
         opties=["je zegt wat je opvalt",
                 "je geeft een cijfer erbij",
                 "je straft iemand erbij",
                 "je zwijgt erover erbij"],
         antwoord=0,
         uitleg="Feedback is terugkoppelen wat je ziet of merkt, zodat de ander ermee verder kan."),
    dict(type="meerkeuze",
         vraag="Welke soorten feedback zijn er?",
         opties=["positieve feedback",
                 "negatieve feedback",
                 "non-verbale feedback",
                 "verplichte feedback"],
         antwoord=[0, 1, 2],
         uitleg="Feedback kan positief of negatief zijn, en verbaal of non-verbaal."),
    dict(type="meerkeuze",
         vraag="Wat is positieve feedback?",
         opties=["je benoemt wat goed gaat",
                 "je somt de fouten op",
                 "je zwijgt erover erbij",
                 "je geeft een straf erbij"],
         antwoord=0,
         uitleg="Zeggen wat goed loopt werkt even sterk als zeggen wat beter kan."),
    dict(type="meerkeuze",
         vraag="Waarvoor staat de eerste G van het 4G-model?",
         opties=["gedrag",
                 "gevoel erbij",
                 "gevolg erbij",
                 "gewenst erbij"],
         antwoord=0,
         uitleg="Eerst benoem je het gedrag dat je gezien hebt."),
    dict(type="meerkeuze",
         vraag="Waarvoor staat de tweede G van het 4G-model?",
         opties=["gevoel",
                 "gedrag erbij",
                 "gevolg erbij",
                 "gewenst erbij"],
         antwoord=0,
         uitleg="Daarna zeg je wat dat gedrag bij jou teweegbracht."),
    dict(type="meerkeuze",
         vraag="Waarvoor staat de derde G van het 4G-model?",
         opties=["gevolg",
                 "gedrag erbij",
                 "gevoel erbij",
                 "gewenst erbij"],
         antwoord=0,
         uitleg="Het gevolg: wat er door dat gedrag gebeurd is."),
    dict(type="meerkeuze",
         vraag="Waarvoor staat de vierde G van het 4G-model?",
         opties=["gewenst gedrag",
                 "het gevoel erbij",
                 "het gevolg erbij",
                 "het gedrag erbij"],
         antwoord=0,
         uitleg="Tot slot zeg je wat je graag anders zou zien."),
    dict(type="meerkeuze",
         vraag="Wat hoort in een goede feedbackboodschap?",
         opties=["het gedrag dat je zag",
                 "wat het met je deed",
                 "wat je anders wil",
                 "een oordeel over de persoon"],
         antwoord=[0, 1, 2],
         uitleg="Feedback gaat over gedrag, nooit over wie iemand is."),
    dict(type="meerkeuze",
         vraag="Wat is een ik-boodschap?",
         opties=["je spreekt over jezelf",
                 "je wijst naar de ander",
                 "je zegt wat hij fout doet",
                 "je begint met jij erbij"],
         antwoord=0,
         uitleg="\"Ik schrik als er geroepen wordt\" in plaats van \"Jij roept altijd\"."),
    dict(type="meerkeuze",
         vraag="Waarom werkt een ik-boodschap beter?",
         opties=["de ander voelt zich veiliger",
                 "hij krijgt meteen een straf erbij",
                 "hij moet zich meteen verdedigen",
                 "hij hoort enkel verwijten erbij"],
         antwoord=0,
         uitleg="Wie geen verwijt hoort, hoeft zich niet te verdedigen en kan luisteren."),
    dict(type="meerkeuze",
         vraag="Hoe begin je een ik-boodschap?",
         opties=["met ik",
                 "met jij erbij",
                 "met hij erbij",
                 "met zij erbij"],
         antwoord=0,
         uitleg="Je begint bij jezelf: wat jij ziet, voelt en nodig hebt."),
    dict(type="meerkeuze",
         vraag="Wat doe je als je feedback krijgt?",
         opties=["je luistert eerst",
                 "je vraagt wat hij bedoelt",
                 "je denkt erover na",
                 "je verdedigt je meteen"],
         antwoord=[0, 1, 2],
         uitleg="Eerst luisteren, dan navragen wat de ander juist bedoelt."),
    dict(type="meerkeuze",
         vraag="Mag je feedback geven voor de hele groep?",
         opties=["nee, liefst onder vier ogen",
                 "ja, altijd in het openbaar",
                 "ja, hoe luider hoe beter",
                 "ja, dat leert iedereen ervan"],
         antwoord=0,
         uitleg="Feedback voor de groep voelt als een afrekening; onder vier ogen komt ze aan."),
    dict(type="waarofniet",
         vraag="Feedback kan ook positief zijn.",
         antwoord=True,
         uitleg="Zeggen wat goed loopt is evengoed feedback."),
    dict(type="waarofniet",
         vraag="Een ik-boodschap begint met jij.",
         antwoord=False,
         uitleg="Ze begint met ik: wat jij ziet en voelt."),
    dict(type="waarofniet",
         vraag="De vierde G van het 4G-model is het gewenste gedrag.",
         antwoord=True,
         uitleg="Gedrag, gevoel, gevolg, gewenst gedrag."),
    dict(type="waarofniet",
         vraag="Feedback geef je het best voor de hele groep.",
         antwoord=False,
         uitleg="Onder vier ogen komt ze veel beter aan."),
    dict(type="invultekst",
         vraag="Hoe noem je een boodschap waarin je over jezelf spreekt? Eén woord.",
         antwoord=["ik-boodschap", "ikboodschap", "een ik-boodschap"],
         uitleg="Een ik-boodschap."),
    dict(type="invultekst",
         vraag="Hoeveel G's heeft het model om feedback te geven? Eén getal.",
         antwoord=["4", "vier"],
         uitleg="Vier: gedrag, gevoel, gevolg en gewenst gedrag."),
    dict(type="invultekst",
         vraag="Welk woord hoort bij de derde G van het 4G-model? Eén woord.",
         antwoord=["gevolg", "het gevolg"],
         uitleg="Het gevolg."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Welke stappen heeft verbindend communiceren?",
         opties=["de observatie",
                 "het gevoel",
                 "de behoefte",
                 "de straf"],
         antwoord=[0, 1, 2],
         uitleg="Waarneming, gevoel, behoefte en verzoek. Straffen hoort er niet bij."),
    dict(type="meerkeuze",
         vraag="Wat is de eerste stap van verbindend communiceren?",
         opties=["je zegt wat je ziet",
                 "je zegt wat je voelt",
                 "je zegt wat je nodig hebt",
                 "je doet een verzoek erbij"],
         antwoord=0,
         uitleg="Je begint bij de waarneming: wat je ziet of hoort, zonder oordeel."),
    dict(type="meerkeuze",
         vraag="Wat is de laatste stap van verbindend communiceren?",
         opties=["je doet een verzoek",
                 "je zegt wat je ziet",
                 "je zegt wat je voelt",
                 "je zwijgt verder erbij"],
         antwoord=0,
         uitleg="Je sluit af met een concreet verzoek aan de ander."),
    dict(type="meerkeuze",
         vraag="Wat is een verzoek?",
         opties=["een vraag om iets te doen",
                 "een bevel aan de ander",
                 "een straf voor de ander",
                 "een verwijt aan de ander"],
         antwoord=0,
         uitleg="Een verzoek is een vraag, geen bevel."),
    dict(type="meerkeuze",
         vraag="Wat is het verschil tussen een verzoek en een eis?",
         opties=["bij een verzoek mag nee",
                 "bij een verzoek moet het",
                 "een eis is vriendelijker",
                 "een eis vraagt om uitleg"],
         antwoord=0,
         uitleg="Als nee geen optie is, is het geen verzoek maar een eis."),
    dict(type="meerkeuze",
         vraag="Wat kenmerkt geweldloze communicatie?",
         opties=["ze is respectvol",
                 "ze is empathisch",
                 "ze is direct",
                 "ze is dwingend"],
         antwoord=[0, 1, 2],
         uitleg="Direct, doeltreffend, emotioneel, empathisch en respectvol. Dwingen hoort er niet bij."),
    dict(type="meerkeuze",
         vraag="Wat betekent empathisch communiceren?",
         opties=["je leeft je in de ander in",
                 "je denkt enkel aan jezelf",
                 "je legt je eigen eis op",
                 "je zegt wat jij wil erbij"],
         antwoord=0,
         uitleg="Je probeert te voelen hoe het voor de ander is."),
    dict(type="meerkeuze",
         vraag="Wat is een observatie in verbindend communiceren?",
         opties=["wat je ziet zonder oordeel",
                 "wat je ervan vindt erbij",
                 "wat je verwacht erbij",
                 "wat je wil opleggen erbij"],
         antwoord=0,
         uitleg="\"Je kwam tien minuten later\" in plaats van \"Je bent onbetrouwbaar\"."),
    dict(type="meerkeuze",
         vraag="Waarom benoem je je gevoel?",
         opties=["de ander begrijpt je beter",
                 "de ander krijgt schuld erbij",
                 "de ander moet zwijgen erbij",
                 "de ander moet beslissen erbij"],
         antwoord=0,
         uitleg="Door je gevoel te benoemen, weet de ander wat zijn gedrag teweegbrengt."),
    dict(type="meerkeuze",
         vraag="Welke vragen stel je bij herstelgericht werken?",
         opties=["wat is er gebeurd",
                 "wie heeft er last van",
                 "wat heb je nodig",
                 "wie krijgt de zwaarste straf"],
         antwoord=[0, 1, 2],
         uitleg="Herstelgerichte vragen zoeken herstel, geen straf."),
    dict(type="meerkeuze",
         vraag="Waarop richt herstelgericht werken zich?",
         opties=["op het herstellen van schade",
                 "op het straffen van de dader",
                 "op het vergeten van alles",
                 "op het zwijgen over alles"],
         antwoord=0,
         uitleg="Wat kapot ging tussen mensen, wordt samen hersteld."),
    dict(type="meerkeuze",
         vraag="Wat vraag je als eerste bij een conflict?",
         opties=["wat er gebeurd is",
                 "wie de schuld heeft",
                 "wie de straf krijgt",
                 "wie het luidst riep"],
         antwoord=0,
         uitleg="Eerst het verhaal, van beide kanten, voor er iets beslist wordt."),
    dict(type="meerkeuze",
         vraag="Wat is het doel van herstelgerichte vragen?",
         opties=["samen een oplossing vinden",
                 "de schuldige aanwijzen",
                 "het voorval vergeten erbij",
                 "de straf zwaarder maken"],
         antwoord=0,
         uitleg="Iedereen krijgt zijn verhaal, en samen zoek je hoe het hersteld raakt."),
    dict(type="waarofniet",
         vraag="Bij een verzoek mag de ander ook nee zeggen.",
         antwoord=True,
         uitleg="Anders is het geen verzoek maar een eis."),
    dict(type="waarofniet",
         vraag="Herstelgericht werken draait vooral om straffen.",
         antwoord=False,
         uitleg="Het draait om herstellen wat beschadigd raakte."),
    dict(type="waarofniet",
         vraag="Verbindend communiceren begint bij wat je waarneemt.",
         antwoord=True,
         uitleg="Waarneming, gevoel, behoefte, verzoek: in die volgorde."),
    dict(type="waarofniet",
         vraag="Empathisch communiceren betekent enkel aan jezelf denken.",
         antwoord=False,
         uitleg="Empathisch is je net inleven in de ander."),
    dict(type="invultekst",
         vraag="Hoe noem je communiceren in vier stappen: waarneming, gevoel, behoefte en verzoek? Hoogstens drie woorden.",
         antwoord=["verbindend communiceren", "geweldloze communicatie", "verbindende communicatie"],
         uitleg="Verbindend of geweldloos communiceren."),
    dict(type="invultekst",
         vraag="Hoe noem je een vraag waarop de ander ook nee mag zeggen? Eén woord.",
         antwoord=["verzoek", "een verzoek"],
         uitleg="Een verzoek."),
    dict(type="invultekst",
         vraag="Welke stap komt na het gevoel bij verbindend communiceren? Eén woord.",
         antwoord=["behoefte", "de behoefte", "behoeften"],
         uitleg="De behoefte."),
]
