# -*- coding: utf-8 -*-
"""De morele ontwikkeling en de persoonlijkheid: Kohlberg en Erikson.

Van de vakfiche ontwikkeling en pedagogisch handelen 2DU (2027), bouwsteen
ontwikkeling: de drie stadia van het moreel handelen volgens Kohlberg, en de
persoonlijkheidsontwikkeling volgens Erikson met het conflict en de kracht
van elke levensloopfase.

Deel 1 is Kohlberg.
Deel 2 is Erikson.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat beschrijft Kohlberg?",
         opties=["de morele ontwikkeling",
                 "de motorische ontwikkeling",
                 "de lichamelijke groei erbij",
                 "de taalontwikkeling erbij"],
         antwoord=0,
         uitleg="Kohlberg beschrijft hoe iemand leert bepalen wat juist en wat verkeerd is."),
    dict(type="meerkeuze",
         vraag="Hoeveel stadia onderscheidt Kohlberg?",
         opties=["drie",
                 "vier stadia in totaal",
                 "vijf stadia in totaal",
                 "acht stadia in totaal"],
         antwoord=0,
         uitleg="Pre-conventioneel, conventioneel en post-conventioneel."),
    dict(type="meerkeuze",
         vraag="Welke stadia onderscheidt Kohlberg?",
         opties=["het pre-conventionele",
                 "het conventionele",
                 "het post-conventionele",
                 "het operationele"],
         antwoord=[0, 1, 2],
         uitleg="Het operationele stadium komt van Piaget, niet van Kohlberg."),
    dict(type="meerkeuze",
         vraag="Wat is kenmerkend voor het pre-conventionele stadium?",
         opties=["straf en belonging tellen",
                 "de wet telt het meest erbij",
                 "eigen principes tellen erbij",
                 "de mensheid telt het meest"],
         antwoord=0,
         uitleg="In dit stadium kijkt iemand naar de gevolgen voor zichzelf: krijg ik straf of een belonging?"),
    dict(type="meerkeuze",
         vraag="Een kind doet iets niet omdat het straf krijgt. Welk stadium is dat?",
         opties=["het pre-conventionele",
                 "het conventionele erbij",
                 "het post-conventionele",
                 "het formeel-operationele"],
         antwoord=0,
         uitleg="De straf bepaalt het gedrag, dus pre-conventioneel."),
    dict(type="meerkeuze",
         vraag="Wat is kenmerkend voor het conventionele stadium?",
         opties=["de regels en de groep",
                 "het eigen belang erbij",
                 "de eigen principes erbij",
                 "het eigen gevoel erbij"],
         antwoord=0,
         uitleg="Hier tellen de regels, de wet en wat anderen van je vinden."),
    dict(type="meerkeuze",
         vraag="Iemand houdt zich aan de wet omdat het de wet is. Welk stadium is dat?",
         opties=["het conventionele",
                 "het pre-conventionele erbij",
                 "het post-conventionele erbij",
                 "het sensomotorische erbij"],
         antwoord=0,
         uitleg="De regel geldt omdat het de regel is, dus conventioneel."),
    dict(type="meerkeuze",
         vraag="Wat is kenmerkend voor het post-conventionele stadium?",
         opties=["eigen waarden wegen mee",
                 "enkel de straf telt erbij",
                 "enkel de groep telt erbij",
                 "enkel het eigen voordeel"],
         antwoord=0,
         uitleg="Iemand weegt de regel af tegen waarden als rechtvaardigheid en menselijkheid."),
    dict(type="meerkeuze",
         vraag="Iemand overtreedt een regel omdat die onrechtvaardig is. Welk stadium is dat?",
         opties=["het post-conventionele",
                 "het pre-conventionele erbij",
                 "het conventionele erbij",
                 "het sensomotorische erbij"],
         antwoord=0,
         uitleg="De eigen principes wegen zwaarder dan de regel, dus post-conventioneel."),
    dict(type="meerkeuze",
         vraag="Wat weegt mee in het pre-conventionele stadium?",
         opties=["de straf",
                 "de belonging",
                 "het eigen voordeel",
                 "de mensenrechten"],
         antwoord=[0, 1, 2],
         uitleg="Mensenrechten wegen pas in het post-conventionele stadium."),
    dict(type="meerkeuze",
         vraag="In welk stadium zit een jong kind meestal?",
         opties=["het pre-conventionele",
                 "het post-conventionele erbij",
                 "het conventionele erbij",
                 "geen enkel stadium erbij"],
         antwoord=0,
         uitleg="Een jong kind kijkt vooral naar de gevolgen voor zichzelf."),
    dict(type="meerkeuze",
         vraag="Wat weegt mee in het conventionele stadium?",
         opties=["de regels",
                 "wat anderen vinden",
                 "de wet",
                 "het eigen voordeel"],
         antwoord=[0, 1, 2],
         uitleg="Het eigen voordeel weegt in het pre-conventionele stadium."),
    dict(type="meerkeuze",
         vraag="Bereikt iedereen het post-conventionele stadium?",
         opties=["niet iedereen",
                 "wel iedereen erbij",
                 "enkel kinderen erbij",
                 "enkel ouderen erbij"],
         antwoord=0,
         uitleg="Volgens Kohlberg blijven veel mensen in het conventionele stadium."),
    dict(type="waarofniet",
         vraag="Kohlberg beschrijft drie stadia van moreel handelen.",
         antwoord=True,
         uitleg="Pre-conventioneel, conventioneel en post-conventioneel."),
    dict(type="waarofniet",
         vraag="Een kind in het pre-conventionele stadium denkt aan de wet.",
         antwoord=False,
         uitleg="Het denkt aan straf en belonging. De wet komt in het conventionele stadium."),
    dict(type="waarofniet",
         vraag="Het conventionele stadium kijkt naar regels en naar wat anderen vinden.",
         antwoord=True,
         uitleg="De groep en de regels geven de norm."),
    dict(type="waarofniet",
         vraag="Elke volwassene bereikt het post-conventionele stadium.",
         antwoord=False,
         uitleg="Niet iedereen komt daar. Veel mensen blijven in het conventionele stadium."),
    dict(type="invultekst",
         vraag="Hoeveel stadia onderscheidt Kohlberg? Een getal.",
         antwoord=["3", "drie"],
         uitleg="Drie."),
    dict(type="invultekst",
         vraag="In welk stadium van Kohlberg tellen straf en belonging? Hoogstens drie woorden.",
         antwoord=["pre-conventioneel", "het pre-conventionele", "pre conventioneel"],
         uitleg="Het pre-conventionele stadium."),
    dict(type="invultekst",
         vraag="In welk stadium van Kohlberg wegen eigen principes het zwaarst? Hoogstens drie woorden.",
         antwoord=["post-conventioneel", "het post-conventionele", "post conventioneel"],
         uitleg="Het post-conventionele stadium."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat beschrijft Erikson?",
         opties=["de persoonlijkheid",
                 "het denken erbij",
                 "de moraal erbij",
                 "de motoriek erbij"],
         antwoord=0,
         uitleg="Erikson beschrijft de persoonlijkheidsontwikkeling met een conflict per levensloopfase."),
    dict(type="meerkeuze",
         vraag="Welk conflict speelt bij een baby?",
         opties=["vertrouwen of wantrouwen",
                 "initiatief of schuld erbij",
                 "identiteit of verwarring",
                 "intimiteit of isolatie erbij"],
         antwoord=0,
         uitleg="Een baby leert of de wereld betrouwbaar is. De kracht die daaruit komt is hoop."),
    dict(type="meerkeuze",
         vraag="Welke kracht hoort bij vertrouwen tegenover wantrouwen?",
         opties=["hoop",
                 "de wil erbij",
                 "de trouw erbij",
                 "de liefde erbij"],
         antwoord=0,
         uitleg="Hoop: het vertrouwen dat het goed komt."),
    dict(type="meerkeuze",
         vraag="Welk conflict speelt bij een peuter?",
         opties=["autonomie of twijfel",
                 "identiteit of verwarring",
                 "intimiteit of isolatie erbij",
                 "integriteit of wanhoop erbij"],
         antwoord=0,
         uitleg="Autonomie tegenover twijfel en schaamte. De kracht is de wil."),
    dict(type="meerkeuze",
         vraag="Welke kracht hoort bij autonomie tegenover twijfel?",
         opties=["de wil",
                 "de hoop erbij",
                 "de zorg erbij",
                 "de trouw erbij"],
         antwoord=0,
         uitleg="De wil: zelf willen en zelf kunnen."),
    dict(type="meerkeuze",
         vraag="Welk conflict speelt bij een kleuter?",
         opties=["initiatief of schuld",
                 "autonomie of twijfel erbij",
                 "identiteit of verwarring",
                 "integriteit of wanhoop erbij"],
         antwoord=0,
         uitleg="Initiatief tegenover schuld. De kracht is doelgerichtheid."),
    dict(type="meerkeuze",
         vraag="Welk conflict speelt bij een lagereschoolkind?",
         opties=["handvaardigheid of minder",
                 "initiatief of schuld erbij",
                 "intimiteit of isolatie erbij",
                 "integriteit of wanhoop erbij"],
         antwoord=0,
         uitleg="Handvaardigheid tegenover minderwaardigheid. De kracht is competentie."),
    dict(type="meerkeuze",
         vraag="Welk conflict speelt bij een adolescent?",
         opties=["identiteit of verwarring",
                 "vertrouwen of wantrouwen",
                 "autonomie of twijfel erbij",
                 "integriteit of wanhoop erbij"],
         antwoord=0,
         uitleg="Identiteit tegenover identiteitsverwarring. De kracht is trouw."),
    dict(type="meerkeuze",
         vraag="Welke conflicten horen bij de volwassenheid?",
         opties=["intimiteit of isolatie",
                 "generativiteit of stagnatie",
                 "integriteit of wanhoop",
                 "initiatief of schuld"],
         antwoord=[0, 1, 2],
         uitleg="Initiatief tegenover schuld hoort bij de kleuter."),
    dict(type="meerkeuze",
         vraag="Welke kracht hoort bij intimiteit tegenover isolatie?",
         opties=["de liefde",
                 "de hoop erbij",
                 "de wil erbij",
                 "de zorg erbij"],
         antwoord=0,
         uitleg="Liefde: een band aangaan zonder jezelf te verliezen."),
    dict(type="meerkeuze",
         vraag="Wat is generativiteit?",
         opties=["iets doorgeven aan anderen",
                 "enkel aan jezelf denken",
                 "alles bij jezelf houden",
                 "niets willen betekenen erbij"],
         antwoord=0,
         uitleg="Zorgen voor de volgende generatie, op het werk of in het gezin. De kracht is zorg."),
    dict(type="meerkeuze",
         vraag="Welke krachten noemt Erikson bij de kinderfasen?",
         opties=["hoop",
                 "wil",
                 "doelgerichtheid",
                 "wijsheid"],
         antwoord=[0, 1, 2],
         uitleg="Wijsheid hoort bij de late volwassenheid, bij integriteit tegenover wanhoop."),
    dict(type="meerkeuze",
         vraag="Wat betekent het als een conflict opgelost is?",
         opties=["de kracht komt vrij",
                 "het kind gaat verder",
                 "de volgende fase kan",
                 "het kind blijft stilstaan"],
         antwoord=[0, 1, 2],
         uitleg="Een opgelost conflict levert de kracht van die fase op en maakt de volgende stap mogelijk."),
    dict(type="waarofniet",
         vraag="Bij Erikson hoort bij elke levensfase een conflict.",
         antwoord=True,
         uitleg="Elke fase heeft twee polen en een kracht die vrijkomt bij een goede oplossing."),
    dict(type="waarofniet",
         vraag="De kracht bij identiteit tegenover identiteitsverwarring is trouw.",
         antwoord=True,
         uitleg="Trouw: weten wie je bent en daarbij blijven."),
    dict(type="waarofniet",
         vraag="Een niet opgelost conflict heeft geen gevolgen later.",
         antwoord=False,
         uitleg="Wat in een fase niet opgelost raakt, speelt in de volgende fasen mee."),
    dict(type="waarofniet",
         vraag="Generativiteit betekent dat je alleen aan jezelf denkt.",
         antwoord=False,
         uitleg="Dat is net stagnatie. Generativiteit is zorgen voor de volgende generatie."),
    dict(type="invultekst",
         vraag="Welke kracht hoort bij het conflict van de baby bij Erikson? Eén woord.",
         antwoord=["hoop", "de hoop"],
         uitleg="Hoop."),
    dict(type="invultekst",
         vraag="Welke kracht hoort bij integriteit tegenover wanhoop? Eén woord.",
         antwoord=["wijsheid", "de wijsheid"],
         uitleg="Wijsheid."),
    dict(type="invultekst",
         vraag="Welk conflict speelt bij een adolescent volgens Erikson? Hoogstens drie woorden.",
         antwoord=["identiteit", "identiteitsverwarring", "identiteit of verwarring"],
         uitleg="Identiteit tegenover identiteitsverwarring."),
]
