# -*- coding: utf-8 -*-
"""Spelvormen, speelgoed en het begeleiden van een activiteit.

Van de vakfiche ontwikkeling en pedagogisch handelen 2DU (2027), bouwsteen
pedagogisch handelen: de spelvormen (spelen met dingen, spelen door bewegen,
creatief spelen, fantasiespelletjes, tekenen en spelen met taal), de keuze
van speelgoed per ontwikkelingsgebied en per leeftijd, en het voorbereiden,
begeleiden en afronden van een activiteit.

Deel 1 zijn de spelvormen.
Deel 2 is speelgoed kiezen en een activiteit begeleiden.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Welke spelvormen zijn er?",
         opties=["spelen met dingen",
                 "spelen door bewegen",
                 "creatief spelen",
                 "spelen met geld"],
         antwoord=[0, 1, 2],
         uitleg="Zes in totaal; verder nog fantasiespelletjes, tekenen en spelen met taal."),
    dict(type="meerkeuze",
         vraag="Wat is spelen met dingen?",
         opties=["bouwen met blokken",
                 "rennen in de tuin",
                 "een verhaal verzinnen",
                 "een liedje bedenken erbij"],
         antwoord=0,
         uitleg="Het kind onderzoekt wat het met voorwerpen kan: stapelen, sorteren, in elkaar steken."),
    dict(type="meerkeuze",
         vraag="Wat is spelen door bewegen?",
         opties=["klimmen en fietsen",
                 "blokken stapelen erbij",
                 "een tekening maken",
                 "een woordspel doen erbij"],
         antwoord=0,
         uitleg="Rennen, klimmen, springen, fietsen: het lichaam is het speelgoed."),
    dict(type="meerkeuze",
         vraag="Wat hoort bij creatief spelen?",
         opties=["knutselen",
                 "boetseren",
                 "zelf iets bouwen",
                 "een lijst afwerken"],
         antwoord=[0, 1, 2],
         uitleg="Knutselen, boetseren, bouwen: het kind maakt iets dat er nog niet was."),
    dict(type="meerkeuze",
         vraag="Wat zijn fantasiespelletjes?",
         opties=["doen alsof je iemand bent",
                 "een puzzel leggen erbij",
                 "een blad kleuren erbij",
                 "een bal trappen erbij"],
         antwoord=0,
         uitleg="Winkeltje, dokter of papa en mama spelen: het kind kruipt in een rol."),
    dict(type="meerkeuze",
         vraag="Waarom is tekenen een spelvorm?",
         opties=["het kind geeft vorm aan ideeën",
                 "het is altijd een taak erbij",
                 "het hoort bij het rekenen",
                 "het is enkel voor school"],
         antwoord=0,
         uitleg="Een kind tekent wat het denkt en voelt, lang voor het dat kan opschrijven."),
    dict(type="meerkeuze",
         vraag="Wat is spelen met taal?",
         opties=["rijmen en woordgrapjes",
                 "blokken stapelen erbij",
                 "klimmen in een boom",
                 "een puzzel leggen erbij"],
         antwoord=0,
         uitleg="Rijmpjes, versjes, moppen en zelfverzonnen woorden."),
    dict(type="meerkeuze",
         vraag="Wat leert een kind van fantasiespel?",
         opties=["zich inleven",
                 "taal gebruiken",
                 "samen afspreken",
                 "rekenen met geld"],
         antwoord=[0, 1, 2],
         uitleg="In een rol kruipen vraagt inleving, taal en onderling overleg."),
    dict(type="meerkeuze",
         vraag="Welke spelvorm past bij een peuter?",
         opties=["spelen met dingen",
                 "een gezelschapsspel",
                 "een woordpuzzel erbij",
                 "een strategiespel erbij"],
         antwoord=0,
         uitleg="Een peuter onderzoekt vooral voorwerpen: stapelen, gooien, in en uit doen."),
    dict(type="meerkeuze",
         vraag="Welke spelvorm past bij een kleuter?",
         opties=["fantasiespel",
                 "enkel rekenspel erbij",
                 "enkel een toets erbij",
                 "enkel stilzitten erbij"],
         antwoord=0,
         uitleg="De kleuter denkt symbolisch, en daar hoort doen-alsof helemaal bij."),
    dict(type="meerkeuze",
         vraag="Wat heeft een kind nodig om te spelen?",
         opties=["tijd en ruimte",
                 "een vol programma",
                 "een strenge regel",
                 "een scherm erbij"],
         antwoord=0,
         uitleg="Zonder tijd en ruimte komt spel niet op gang, hoeveel speelgoed er ook ligt."),
    dict(type="meerkeuze",
         vraag="Mag een begeleider meespelen?",
         opties=["ja, als het kind dat wil",
                 "nee, nooit erbij",
                 "ja, hij bepaalt dan alles",
                 "nee, hij kijkt enkel toe"],
         antwoord=0,
         uitleg="Meespelen mag, zolang het spel van het kind blijft."),
    dict(type="meerkeuze",
         vraag="Wat doe je als een spel vastloopt?",
         opties=["je helpt even op weg",
                 "je stopt het spel meteen",
                 "je neemt het spel over",
                 "je laat het kind alleen"],
         antwoord=0,
         uitleg="Een kleine zet is genoeg; daarna laat je het kind weer zelf verder."),
    dict(type="waarofniet",
         vraag="Fantasiespel helpt een kind zich inleven in anderen.",
         antwoord=True,
         uitleg="In een rol kruipen is oefenen in het standpunt van een ander."),
    dict(type="waarofniet",
         vraag="Tekenen hoort niet bij de spelvormen.",
         antwoord=False,
         uitleg="Tekenen is een van de zes spelvormen."),
    dict(type="waarofniet",
         vraag="Een kind heeft tijd en ruimte nodig om te spelen.",
         antwoord=True,
         uitleg="Zonder die twee komt spel niet op gang."),
    dict(type="waarofniet",
         vraag="Een begeleider mag nooit meespelen.",
         antwoord=False,
         uitleg="Meespelen mag, zolang het kind de baas blijft over zijn spel."),
    dict(type="invultekst",
         vraag="Hoe noem je spel waarbij een kind doet alsof het iemand anders is? Eén woord.",
         antwoord=["fantasiespel", "doen-alsof-spel", "rollenspel"],
         uitleg="Fantasiespel of doen-alsof-spel."),
    dict(type="invultekst",
         vraag="Hoe noem je spel met rijmpjes en woordgrapjes? Hoogstens drie woorden.",
         antwoord=["spelen met taal", "taalspel", "woordspel"],
         uitleg="Spelen met taal."),
    dict(type="invultekst",
         vraag="Wat heeft een kind vooral nodig om goed te kunnen spelen? Hoogstens drie woorden.",
         antwoord=["tijd en ruimte", "tijd", "ruimte"],
         uitleg="Tijd en ruimte."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Waarop let je bij de keuze van speelgoed?",
         opties=["de leeftijd",
                 "de veiligheid",
                 "wat het kind leert",
                 "de prijs alleen"],
         antwoord=[0, 1, 2],
         uitleg="Passend bij de leeftijd, veilig, en het spreekt een ontwikkelingsgebied aan."),
    dict(type="meerkeuze",
         vraag="Welk speelgoed past bij een baby?",
         opties=["een rammelaar",
                 "een gezelschapsspel",
                 "een bouwdoos erbij",
                 "een woordspel erbij"],
         antwoord=0,
         uitleg="Een baby ontdekt met ogen, oren, mond en handen."),
    dict(type="meerkeuze",
         vraag="Welk speelgoed past bij een kleuter?",
         opties=["een verkleedkoffer",
                 "een rammelaar erbij",
                 "een bijtring erbij",
                 "een mobiel boven bed"],
         antwoord=0,
         uitleg="De kleuter speelt graag doen-alsof, en verkleden hoort daarbij."),
    dict(type="meerkeuze",
         vraag="Welk speelgoed helpt de fijne motoriek?",
         opties=["kralen rijgen",
                 "een loopfiets erbij",
                 "een springtouw erbij",
                 "een klimrek erbij"],
         antwoord=0,
         uitleg="Kleine, precieze bewegingen van vingers en handen."),
    dict(type="meerkeuze",
         vraag="Welk speelgoed helpt de grove motoriek?",
         opties=["een bal",
                 "een puzzel erbij",
                 "een kleurboek erbij",
                 "een kralenplank erbij"],
         antwoord=0,
         uitleg="Grote bewegingen met armen, benen en heel het lichaam."),
    dict(type="meerkeuze",
         vraag="Welk speelgoed helpt de taalontwikkeling?",
         opties=["een prentenboek",
                 "een springtouw erbij",
                 "een klimrek erbij",
                 "een loopfiets erbij"],
         antwoord=0,
         uitleg="Samen een prentenboek bekijken levert woorden, zinnen en verhalen op."),
    dict(type="meerkeuze",
         vraag="Waarop let je bij de veiligheid van speelgoed?",
         opties=["geen kleine losse stukjes",
                 "de kleur van de doos",
                 "de prijs van het stuk",
                 "de naam van de winkel"],
         antwoord=0,
         uitleg="Kleine stukjes kunnen ingeslikt worden; kijk ook naar scherpe randen en stevigheid."),
    dict(type="meerkeuze",
         vraag="Wat doe je voor een activiteit begint?",
         opties=["je zet alles klaar",
                 "je kijkt de ruimte na",
                 "je legt de afspraken uit",
                 "je begint zomaar"],
         antwoord=[0, 1, 2],
         uitleg="Materiaal klaarzetten, de ruimte veilig maken en de afspraken duidelijk maken."),
    dict(type="meerkeuze",
         vraag="Wat doe je tijdens een activiteit?",
         opties=["je volgt de kinderen op",
                 "je kijkt enkel op je gsm",
                 "je laat ze alleen achter",
                 "je verlaat de ruimte erbij"],
         antwoord=0,
         uitleg="Je kijkt, helpt waar nodig en past aan als iets niet loopt."),
    dict(type="meerkeuze",
         vraag="Wat doe je na een activiteit?",
         opties=["je ruimt samen op",
                 "je bespreekt het na",
                 "je bergt het materiaal op",
                 "je laat alles liggen"],
         antwoord=[0, 1, 2],
         uitleg="Samen opruimen en even nabespreken hoort bij het afronden."),
    dict(type="meerkeuze",
         vraag="Waarom laat je kinderen mee opruimen?",
         opties=["ze leren zorg dragen",
                 "het gaat sneller voor jou",
                 "het hoort niet bij spel",
                 "het is een straf erbij"],
         antwoord=0,
         uitleg="Opruimen is geen straf maar een deel van het spel, en het leert zorg dragen."),
    dict(type="meerkeuze",
         vraag="Hoe weet je of een activiteit geslaagd was?",
         opties=["je kijkt en vraagt na",
                 "je telt het speelgoed",
                 "je kijkt op de klok",
                 "je vraagt niets erbij"],
         antwoord=0,
         uitleg="Observeren tijdens de activiteit en achteraf vragen hoe het was."),
    dict(type="meerkeuze",
         vraag="Wat doe je als een activiteit te moeilijk blijkt?",
         opties=["je past ze aan",
                 "je stopt alles meteen",
                 "je gaat gewoon door",
                 "je geeft een slecht punt"],
         antwoord=0,
         uitleg="Je maakt de opdracht kleiner of je helpt mee, zodat het toch lukt."),
    dict(type="waarofniet",
         vraag="Speelgoed voor een baby mag geen kleine losse stukjes bevatten.",
         antwoord=True,
         uitleg="Een baby stopt alles in zijn mond; kleine stukjes zijn gevaarlijk."),
    dict(type="waarofniet",
         vraag="Een prentenboek helpt de taalontwikkeling.",
         antwoord=True,
         uitleg="Samen kijken en benoemen levert woorden en zinnen op."),
    dict(type="waarofniet",
         vraag="Opruimen hoort niet bij de activiteit.",
         antwoord=False,
         uitleg="Het afronden en opruimen hoort er net bij."),
    dict(type="waarofniet",
         vraag="Je kiest speelgoed het best enkel op de prijs.",
         antwoord=False,
         uitleg="Leeftijd, veiligheid en wat het kind ermee leert tellen eerst."),
    dict(type="invultekst",
         vraag="Hoe noem je de motoriek die je traint met kralen rijgen? Eén woord.",
         antwoord=["fijne", "fijne motoriek", "fijn"],
         uitleg="De fijne motoriek."),
    dict(type="invultekst",
         vraag="Hoe noem je de motoriek die je traint met een bal? Eén woord.",
         antwoord=["grove", "grove motoriek", "grof"],
         uitleg="De grove motoriek."),
    dict(type="invultekst",
         vraag="Wat doe je samen met de kinderen na een activiteit? Eén woord.",
         antwoord=["opruimen", "samen opruimen", "afsluiten"],
         uitleg="Samen opruimen."),
]
