# -*- coding: utf-8 -*-
"""De ontwikkeling van de volwassene en de oudere.

Van de vakfiche ontwikkeling en pedagogisch handelen 2DU (2027), bouwsteen
ontwikkeling: de fysieke en de cognitieve ontwikkeling bij volwassenen en
ouderen, met uiterlijke en inwendige veroudering, primair en secundair
verouderen, de voordelen en de verliezen voor de hersenen, en het verschil
tussen ouderdomsvergeetachtigheid en dementie. Daarna de levensgebeurtenissen
die de fiche opsomt voor volwassenen en voor ouderen.

Deel 1 is het verouderen van lichaam en hersenen.
Deel 2 zijn de levensgebeurtenissen.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat hoort bij uiterlijke veroudering?",
         opties=["rimpels",
                 "grijze haren",
                 "een krommere rug",
                 "minder nierwerking"],
         antwoord=[0, 1, 2],
         uitleg="Uiterlijke veroudering zie je; de nieren hoort bij de inwendige veroudering."),
    dict(type="meerkeuze",
         vraag="Wat is inwendige veroudering?",
         opties=["organen werken minder",
                 "de huid wordt rimpelig",
                 "het haar wordt grijzer",
                 "de rug wordt krommer erbij"],
         antwoord=0,
         uitleg="Hart, longen, nieren en spijsvertering werken langzaam minder goed."),
    dict(type="meerkeuze",
         vraag="Wat is primair verouderen?",
         opties=["het gebeurt bij iedereen",
                 "het komt door roken erbij",
                 "het komt door ongelukken",
                 "het komt door een ziekte"],
         antwoord=0,
         uitleg="Primair verouderen is het natuurlijke verouderen dat niemand ontloopt."),
    dict(type="meerkeuze",
         vraag="Wat is secundair verouderen?",
         opties=["het komt door leefstijl",
                 "het gebeurt bij iedereen",
                 "het staat in de genen erbij",
                 "het begint bij de geboorte"],
         antwoord=0,
         uitleg="Secundair verouderen komt door leefstijl, ziekte en omgeving, en is deels te vermijden."),
    dict(type="meerkeuze",
         vraag="Wat verandert in de motoriek van een oudere?",
         opties=["de bewegingen worden trager",
                 "de bewegingen worden sneller",
                 "de kracht neemt sterk toe erbij",
                 "het evenwicht wordt veel beter"],
         antwoord=0,
         uitleg="Trager bewegen, minder kracht en een minder zeker evenwicht horen bij ouderdomsmotoriek."),
    dict(type="meerkeuze",
         vraag="Welke voordelen heeft ouder worden voor de hersenen?",
         opties=["meer overzicht",
                 "meer woordenschat",
                 "meer levenswijsheid",
                 "meer reactiesnelheid"],
         antwoord=[0, 1, 2],
         uitleg="De snelheid neemt juist af; overzicht, woorden en wijsheid nemen toe."),
    dict(type="meerkeuze",
         vraag="Wat neemt af bij de hersenen van een oudere?",
         opties=["de snelheid van denken",
                 "de woordenschat erbij",
                 "de levenservaring erbij",
                 "het overzicht erbij"],
         antwoord=0,
         uitleg="Een oudere denkt trager, maar weet meer en overziet beter."),
    dict(type="meerkeuze",
         vraag="Wat is ouderdomsvergeetachtigheid?",
         opties=["je vindt een woord niet",
                 "je herkent je kinderen niet",
                 "je vindt je huis niet meer",
                 "je kan niets meer onthouden"],
         antwoord=0,
         uitleg="Een naam of een woord dat even niet komt, is gewoon bij het ouder worden."),
    dict(type="meerkeuze",
         vraag="Wat is dementie?",
         opties=["de hersenen gaan achteruit",
                 "je vergeet soms een naam",
                 "je bent even verstrooid erbij",
                 "je denkt iets trager erbij"],
         antwoord=0,
         uitleg="Bij dementie gaan de hersenen blijvend achteruit en gaat het dagelijkse leven eraan."),
    dict(type="meerkeuze",
         vraag="Wat is het verschil tussen vergeetachtigheid en dementie?",
         opties=["dementie gaat verder",
                 "vergeetachtigheid is erger",
                 "dementie is heel gewoon erbij",
                 "vergeetachtigheid is blijvend"],
         antwoord=0,
         uitleg="Vergeetachtigheid hindert het dagelijkse leven niet, dementie wel."),
    dict(type="meerkeuze",
         vraag="Wat verandert er lichamelijk bij de volwassene?",
         opties=["de spierkracht daalt",
                 "het zicht gaat achteruit",
                 "het gehoor gaat achteruit",
                 "de lengte neemt sterk toe"],
         antwoord=[0, 1, 2],
         uitleg="Groeien in de lengte is al gestopt; de rest gaat traag achteruit."),
    dict(type="meerkeuze",
         vraag="Wanneer begint het verouderen?",
         opties=["al bij de jonge volwassene",
                 "pas na het pensioen erbij",
                 "pas na tachtig jaar erbij",
                 "pas bij een ziekte erbij"],
         antwoord=0,
         uitleg="Verouderen begint al in de jonge volwassenheid, alleen merk je er dan weinig van."),
    dict(type="meerkeuze",
         vraag="Waarom werkt een oudere trager maar vaak even goed?",
         opties=["ervaring vult snelheid aan",
                 "snelheid is niet nodig erbij",
                 "ervaring speelt geen rol erbij",
                 "traag werken is altijd beter"],
         antwoord=0,
         uitleg="Wat aan tempo verloren gaat, wordt opgevangen door ervaring en overzicht."),
    dict(type="waarofniet",
         vraag="Primair verouderen gebeurt bij iedereen.",
         antwoord=True,
         uitleg="Het is het natuurlijke verouderen; niemand ontloopt het."),
    dict(type="waarofniet",
         vraag="Ouder worden brengt alleen achteruitgang mee.",
         antwoord=False,
         uitleg="Woordenschat, overzicht en levenswijsheid nemen juist toe."),
    dict(type="waarofniet",
         vraag="Ouderdomsvergeetachtigheid is hetzelfde als dementie.",
         antwoord=False,
         uitleg="Vergeetachtigheid hindert het dagelijkse leven niet; dementie wel."),
    dict(type="waarofniet",
         vraag="Secundair verouderen hangt samen met de leefstijl.",
         antwoord=True,
         uitleg="Roken, voeding, beweging, ziekte en omgeving spelen mee."),
    dict(type="invultekst",
         vraag="Hoe noem je het verouderen dat bij iedereen gebeurt? Eén woord.",
         antwoord=["primair", "primair verouderen", "primaire veroudering"],
         uitleg="Primair verouderen."),
    dict(type="invultekst",
         vraag="Hoe noem je het verouderen door leefstijl en omgeving? Eén woord.",
         antwoord=["secundair", "secundair verouderen", "secundaire veroudering"],
         uitleg="Secundair verouderen."),
    dict(type="invultekst",
         vraag="Hoe noem je de ziekte waarbij de hersenen blijvend achteruitgaan? Eén woord.",
         antwoord=["dementie", "de dementie"],
         uitleg="Dementie."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Welke levensgebeurtenissen horen bij de volwassene?",
         opties=["gezinsvorming",
                 "midlifecrisis",
                 "legenestsyndroom",
                 "pensionering"],
         antwoord=[0, 1, 2],
         uitleg="Pensionering hoort bij de oudere."),
    dict(type="meerkeuze",
         vraag="Wat zijn boemerangkinderen?",
         opties=["kinderen die terugkomen",
                 "kinderen die nooit weggaan",
                 "kinderen zonder werk erbij",
                 "kinderen die ver weg wonen"],
         antwoord=0,
         uitleg="Ze waren het huis uit en komen na een tijd weer bij hun ouders wonen."),
    dict(type="meerkeuze",
         vraag="Wat is het legenestsyndroom?",
         opties=["de kinderen gaan weg",
                 "de kinderen komen terug",
                 "de ouders gaan op reis erbij",
                 "de ouders verhuizen erbij"],
         antwoord=0,
         uitleg="Het gemis en de leegte die ouders voelen als hun kinderen het huis uit zijn."),
    dict(type="meerkeuze",
         vraag="Wat is de sandwichgeneratie?",
         opties=["zorg voor twee generaties",
                 "zorg voor enkel de kinderen",
                 "zorg voor enkel de ouders",
                 "zorg voor niemand erbij"],
         antwoord=0,
         uitleg="Zij zorgt tegelijk voor haar eigen kinderen en voor haar ouder wordende ouders."),
    dict(type="meerkeuze",
         vraag="Wat is een midlifecrisis?",
         opties=["twijfel rond de middenleeftijd",
                 "twijfel bij de tiener erbij",
                 "twijfel bij de baby erbij",
                 "twijfel na het pensioen erbij"],
         antwoord=0,
         uitleg="Rond de veertig of vijftig stelt iemand zijn werk, relatie en keuzes in vraag."),
    dict(type="meerkeuze",
         vraag="Wat is gezinsvorming?",
         opties=["een eigen gezin starten",
                 "alleen blijven wonen erbij",
                 "bij de ouders blijven erbij",
                 "het huis verlaten erbij"],
         antwoord=0,
         uitleg="Samenwonen, trouwen of kinderen krijgen: een eigen gezin beginnen."),
    dict(type="meerkeuze",
         vraag="Welke levensgebeurtenissen horen bij de oudere?",
         opties=["pensionering",
                 "eenzaamheid",
                 "kleinkinderen",
                 "gezinsvorming"],
         antwoord=[0, 1, 2],
         uitleg="Gezinsvorming hoort bij de volwassene."),
    dict(type="meerkeuze",
         vraag="Wat verandert er bij een pensionering?",
         opties=["de dagindeling valt weg",
                 "het werk wordt zwaarder",
                 "het loon stijgt sterk erbij",
                 "de gezondheid verbetert erbij"],
         antwoord=0,
         uitleg="Het vaste ritme van het werk verdwijnt en moet opnieuw opgebouwd worden."),
    dict(type="meerkeuze",
         vraag="Waarom voelt een oudere zich soms eenzaam?",
         opties=["vrienden vallen weg",
                 "de agenda is te vol erbij",
                 "het huis is te klein erbij",
                 "het werk vraagt te veel tijd"],
         antwoord=0,
         uitleg="Collega's, vrienden en een partner vallen weg, en de wereld wordt kleiner."),
    dict(type="meerkeuze",
         vraag="Wat betekent afhankelijk worden voor een oudere?",
         opties=["hij heeft hulp nodig",
                 "hij kan alles nog alleen",
                 "hij wil geen bezoek meer",
                 "hij gaat zelf op reis erbij"],
         antwoord=0,
         uitleg="Voor wassen, koken of boodschappen is er hulp nodig van anderen."),
    dict(type="meerkeuze",
         vraag="Wat is rouw?",
         opties=["verdriet na een verlies",
                 "blijdschap na een feest",
                 "angst voor een examen erbij",
                 "twijfel bij een keuze erbij"],
         antwoord=0,
         uitleg="Rouwen is het verwerken van een verlies, en dat gaat bij iedereen anders."),
    dict(type="meerkeuze",
         vraag="Wat helpt een oudere bij een verhuis naar een woonzorgcentrum?",
         opties=["eigen spullen meenemen",
                 "mee beslissen",
                 "bezoek krijgen",
                 "alles achterlaten"],
         antwoord=[0, 1, 2],
         uitleg="Eigen spullen, mee kunnen beslissen en bezoek maken de stap draaglijker."),
    dict(type="meerkeuze",
         vraag="Wat doet stress met een volwassene op lange termijn?",
         opties=["het maakt hem ziek",
                 "het maakt hem sterker",
                 "het geeft hem meer tijd",
                 "het verbetert zijn slaap erbij"],
         antwoord=0,
         uitleg="Langdurige stress maakt ziek: slecht slapen, hoofdpijn, een opgebrand gevoel."),
    dict(type="waarofniet",
         vraag="Een pensionering vraagt een nieuwe dagindeling.",
         antwoord=True,
         uitleg="Het ritme van het werk valt weg en moet opnieuw ingevuld worden."),
    dict(type="waarofniet",
         vraag="Het legenestsyndroom betekent dat de kinderen terugkeren.",
         antwoord=False,
         uitleg="Dat zijn boemerangkinderen. Het legenestsyndroom is net de leegte als ze weggaan."),
    dict(type="waarofniet",
         vraag="De sandwichgeneratie zorgt voor haar kinderen en haar ouders.",
         antwoord=True,
         uitleg="Ze zit tussen twee generaties die beide zorg vragen."),
    dict(type="waarofniet",
         vraag="Rouw verloopt bij iedereen op dezelfde manier.",
         antwoord=False,
         uitleg="Rouwen is heel persoonlijk, in tempo en in vorm."),
    dict(type="invultekst",
         vraag="Hoe noem je kinderen die na het uithuizen weer bij hun ouders komen wonen? Eén woord.",
         antwoord=["boemerangkinderen", "de boemerangkinderen"],
         uitleg="Boemerangkinderen."),
    dict(type="invultekst",
         vraag="Hoe noem je het gevoel van ouders als hun kinderen het huis uit zijn? Eén woord.",
         antwoord=["legenestsyndroom", "het legenestsyndroom"],
         uitleg="Het legenestsyndroom."),
    dict(type="invultekst",
         vraag="Hoe noem je de generatie die voor haar kinderen en haar ouders zorgt? Eén woord.",
         antwoord=["sandwichgeneratie", "de sandwichgeneratie"],
         uitleg="De sandwichgeneratie."),
]
