# -*- coding: utf-8 -*-
"""Afdrukken, kopiëren en scannen.

Van de vakfiche toegepaste economie 2DU (2027): de onderdelen van een
printer en een copier, foutmeldingen, de kopieerinstellingen, de
printereigenschappen, afdrukken naar pdf, en de scanners (leespen,
handscanner, vlakbedscanner) met tekenherkenning.

Deel 1 is het toestel en het kopiëren.
Deel 2 zijn de printereigenschappen, de pdf en het scannen.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is een multifunctioneel toestel?",
         opties=["printer, scanner en copier",
                 "enkel een printer ervan",
                 "enkel een scanner ervan",
                 "een toestel voor faxen"],
         antwoord=0,
         uitleg="Eén toestel dat afdrukt, kopieert en scant."),
    dict(type="meerkeuze",
         vraag="Wat is de papierlade van een printer?",
         opties=["de bak met blad erin",
                 "het deel dat inkt geeft",
                 "het scherm met knoppen",
                 "de klep bovenaan ervan"],
         antwoord=0,
         uitleg="Vaak zijn er meerdere laden, één per formaat."),
    dict(type="meerkeuze",
         vraag="Wat is de glasplaat van een copier?",
         opties=["waar je een blad legt",
                 "waar het blad uitkomt",
                 "waar de inkt in zit",
                 "waar de stekker in gaat"],
         antwoord=0,
         uitleg="Met de bedrukte zijde naar beneden, tegen de hoek."),
    dict(type="meerkeuze",
         vraag="Wat doet de doorvoer bovenaan een copier?",
         opties=["bladen één per één nemen",
                 "de inkt bijvullen ervan",
                 "het blad nieten ervan",
                 "het blad plooien ervan"],
         antwoord=0,
         uitleg="Zo kopieer of scan je een hele stapel in één keer."),
    dict(type="invultekst",
         vraag="Hoe noem je het poeder waarmee een laserprinter afdrukt? Eén woord.",
         antwoord=["toner", "tonerpoeder"],
         uitleg="Toner."),
    dict(type="waarofniet",
         vraag="Een inkjetprinter werkt met vloeibare inkt, een laserprinter met poeder.",
         antwoord=True,
         uitleg="Daarom is een laserprinter per blad goedkoper bij veel afdrukken."),
    dict(type="waarofniet",
         vraag="Een printer kan afdrukken zonder dat er papier in de lade zit.",
         antwoord=False,
         uitleg="De opdracht blijft in de wachtrij staan tot je papier bijvult."),
    dict(type="meerkeuze",
         vraag="Wat betekent de melding papierstoring?",
         opties=["een blad zit vast",
                 "de inkt is leeg ervan",
                 "het bestand is fout",
                 "de printer staat uit"],
         antwoord=0,
         uitleg="Open de klep en trek het blad voorzichtig mee met de richting van de doorvoer."),
    dict(type="meerkeuze",
         vraag="Wat betekent de melding geen verbinding?",
         opties=["de printer is onbereikbaar",
                 "het papier is op ervan",
                 "de inkt is leeg ervan",
                 "het blad zit vast ervan"],
         antwoord=0,
         uitleg="Kijk de kabel of het netwerk na, en of de printer wel aan staat."),
    dict(type="meerkeuze",
         vraag="Wat stel je in om op beide zijden af te drukken?",
         opties=["dubbelzijdig",
                 "zwart-wit ervan",
                 "liggend ervan",
                 "verkleind ervan"],
         antwoord=0,
         uitleg="Soms heet het recto verso of duplex."),
    dict(type="meerkeuze",
         vraag="Welke kopieerinstellingen kan je kiezen?",
         opties=["het aantal exemplaren",
                 "zwart-wit of in kleur",
                 "verkleinen of vergroten",
                 "de taal van het document"],
         antwoord=[0, 1, 2],
         uitleg="Een copier leest geen taal; hij maakt een beeld van het blad."),
    dict(type="meerkeuze",
         vraag="Waarom druk je een eerste blad als proef af?",
         opties=["om fouten te zien",
                 "om papier te sparen",
                 "om de inkt te testen",
                 "om sneller te werken"],
         antwoord=0,
         uitleg="Honderd flyers met een fout erin zijn honderd flyers verloren."),
    dict(type="waarofniet",
         vraag="Dubbelzijdig afdrukken halveert het aantal bladen.",
         antwoord=True,
         uitleg="Twintig bladzijden passen dan op tien bladen."),
    dict(type="waarofniet",
         vraag="Zwart-wit afdrukken kost evenveel als in kleur.",
         antwoord=False,
         uitleg="Kleur gebruikt meerdere cassettes en is per blad duurder."),
    dict(type="invultekst",
         vraag="Hoe noem je het afdrukken op beide zijden van een blad? Eén woord.",
         antwoord=["dubbelzijdig", "recto verso", "rectoverso"],
         uitleg="Dubbelzijdig, of recto verso."),
    dict(type="meerkeuze",
         vraag="Wat is de afdrukwachtrij?",
         opties=["de lijst met opdrachten",
                 "de lade met papier ervan",
                 "de map met bestanden",
                 "de knop op de printer"],
         antwoord=0,
         uitleg="Daar kan je een opdracht die je per ongeluk startte nog annuleren."),
    dict(type="meerkeuze",
         vraag="Wat doe je bij een printer die niets doet?",
         opties=["kijken of hij aan staat",
                 "kijken of er papier in zit",
                 "de wachtrij nakijken",
                 "de inkt weggooien erbij"],
         antwoord=[0, 1, 2],
         uitleg="Eerst het eenvoudigste nakijken, daarna pas het netwerk."),
    dict(type="meerkeuze",
         vraag="Wat doet de instelling verkleinen bij kopiëren?",
         opties=["kleiner op het blad",
                 "minder bladen nemen",
                 "de inkt sparen ervan",
                 "sneller kopiëren ervan"],
         antwoord=0,
         uitleg="Twee A4 op één A4 bijvoorbeeld; dat heet ook twee op één."),
    dict(type="meerkeuze",
         vraag="Welke onderdelen heeft een printer?",
         opties=["een papierlade",
                 "een inkt- of tonercassette",
                 "een bedieningsscherm",
                 "een glasplaat met deksel"],
         antwoord=[0, 1, 2],
         uitleg="Een glasplaat heeft enkel een toestel dat ook kan scannen of kopiëren."),
    dict(type="invultekst",
         vraag="Welke melding krijg je als er een blad vastzit? Hoogstens drie woorden.",
         antwoord=["papierstoring", "een papierstoring", "papier vast"],
         uitleg="Papierstoring."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat zijn de printereigenschappen?",
         opties=["de instellingen vooraf",
                 "de prijs van de printer",
                 "het merk van de printer",
                 "de kabel naar de printer"],
         antwoord=0,
         uitleg="Het venster waar je lade, kwaliteit, kleur en dubbelzijdig kiest."),
    dict(type="meerkeuze",
         vraag="Wat stel je in met het afdrukbereik?",
         opties=["welke bladzijden",
                 "hoeveel exemplaren",
                 "welke kleur ervan",
                 "welke lade ervan"],
         antwoord=0,
         uitleg="Bijvoorbeeld enkel blad 2 tot 5, of enkel de huidige bladzijde."),
    dict(type="meerkeuze",
         vraag="Wat betekent afdrukken naar pdf?",
         opties=["een bestand maken",
                 "op papier afdrukken",
                 "de printer wissen ervan",
                 "de inkt sparen ervan"],
         antwoord=0,
         uitleg="Er komt geen blad uit. Je krijgt een bestand dat er overal hetzelfde uitziet."),
    dict(type="meerkeuze",
         vraag="Waarom stuur je een drukker liever een pdf?",
         opties=["de opmaak blijft juist",
                 "het bestand is kleiner",
                 "de drukker rekent minder",
                 "het gaat sneller ervan"],
         antwoord=0,
         uitleg="Een lettertype dat de drukker niet heeft wordt anders vervangen; in een pdf zit het mee."),
    dict(type="invultekst",
         vraag="Welk bestandstype maak je als de opmaak overal hetzelfde moet blijven? Eén woord.",
         antwoord=["pdf", "een pdf"],
         uitleg="Een pdf."),
    dict(type="waarofniet",
         vraag="Een pdf open je op elke computer, ook zonder het programma waarin hij gemaakt is.",
         antwoord=True,
         uitleg="Daarom is het de gewoonte voor een factuur of een contract."),
    dict(type="waarofniet",
         vraag="Afdrukken naar pdf gebruikt inkt.",
         antwoord=False,
         uitleg="Er komt geen papier uit het toestel; het resultaat is een bestand."),
    dict(type="meerkeuze",
         vraag="Wat doet een scanner?",
         opties=["papier digitaal maken",
                 "een bestand afdrukken",
                 "een blad kopiëren ervan",
                 "de inkt navullen ervan"],
         antwoord=0,
         uitleg="Hij maakt van een blad een bestand op de computer."),
    dict(type="meerkeuze",
         vraag="Wat is een vlakbedscanner?",
         opties=["een scanner met glasplaat",
                 "een scanner in een pen",
                 "een scanner in de hand",
                 "een scanner in een gsm"],
         antwoord=0,
         uitleg="Je legt het blad op het glas en het deksel gaat dicht."),
    dict(type="meerkeuze",
         vraag="Wat doet een leespen?",
         opties=["een regel tekst scannen",
                 "een hele bladzijde scannen",
                 "een foto afdrukken ervan",
                 "een streepje zetten ervan"],
         antwoord=0,
         uitleg="Je schuift hem over een regel en de tekst komt op de computer."),
    dict(type="meerkeuze",
         vraag="Welke scanners noemt de vakfiche?",
         opties=["de leespen",
                 "de handscanner",
                 "de vlakbedscanner",
                 "de laserprinter"],
         antwoord=[0, 1, 2],
         uitleg="Een handscanner sleep je zelf over het blad; een laserprinter scant niet."),
    dict(type="meerkeuze",
         vraag="Wat is tekenherkenning of OCR?",
         opties=["tekst herkennen in een beeld",
                 "een beeld kleiner maken",
                 "een beeld scherper maken",
                 "een bestand versturen ervan"],
         antwoord=0,
         uitleg="Zonder OCR is een scan een foto van tekst; met OCR kan je erin zoeken en kopiëren."),
    dict(type="waarofniet",
         vraag="Een gewone scan zonder tekenherkenning is een afbeelding waarin je niet kan zoeken.",
         antwoord=True,
         uitleg="De computer ziet er enkel puntjes, geen letters."),
    dict(type="waarofniet",
         vraag="Tekenherkenning werkt altijd foutloos, ook bij een slecht leesbaar handschrift.",
         antwoord=False,
         uitleg="Kijk een herkende tekst altijd na, vooral de cijfers."),
    dict(type="invultekst",
         vraag="Waarvoor staat OCR in het Nederlands? Hoogstens drie woorden.",
         antwoord=["optische tekenherkenning", "tekenherkenning", "optische karakterherkenning"],
         uitleg="Optische tekenherkenning."),
    dict(type="meerkeuze",
         vraag="Waarom scan je een factuur in?",
         opties=["ze digitaal bewaren",
                 "ze mooier maken ervan",
                 "ze kleiner afdrukken",
                 "ze doorsturen op papier"],
         antwoord=0,
         uitleg="Zo zit ze in de boekhouding en vind je ze later terug."),
    dict(type="meerkeuze",
         vraag="Wat kan je instellen bij een scan?",
         opties=["kleur of zwart-wit",
                 "de resolutie",
                 "het bestandstype",
                 "het aantal exemplaren"],
         antwoord=[0, 1, 2],
         uitleg="Exemplaren horen bij afdrukken, niet bij scannen."),
    dict(type="meerkeuze",
         vraag="Wat betekent een hoge resolutie bij een scan?",
         opties=["meer detail en groter",
                 "minder detail en kleiner",
                 "sneller en kleiner ervan",
                 "mooier en kleiner ervan"],
         antwoord=0,
         uitleg="Meer puntjes per duim geeft een scherper beeld, maar ook een zwaarder bestand."),
    dict(type="meerkeuze",
         vraag="Waarom werkt een zaak graag met gescande documenten?",
         opties=["ze nemen geen plaats in",
                 "je vindt ze terug met zoeken",
                 "je kan ze doorsturen",
                 "ze hoeven niet bewaard te worden"],
         antwoord=[0, 1, 2],
         uitleg="Bewaren moet wel: de wet zegt hoe lang je je boekhouding moet bijhouden."),
    dict(type="invultekst",
         vraag="Hoe noem je de scanner met een glasplaat en een deksel? Hoogstens drie woorden.",
         antwoord=["vlakbedscanner", "een vlakbedscanner", "flatbedscanner"],
         uitleg="Een vlakbedscanner."),
]
