# -*- coding: utf-8 -*-
"""De boekhouding van een onderneming.

Van de vakfiche toegepaste economie 2DU (2027): het belang van de boekhouding
voor de belanghebbende partijen, de indeling en de onderdelen van de
jaarrekening, en het systeem van het dubbel boekhouden met journaal en
grootboek.

Deel 1 is het nut van de boekhouding en de jaarrekening.
Deel 2 is het systeem van het dubbel boekhouden.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is boekhouden?",
         opties=["alle verrichtingen registreren",
                 "de winst van een jaar schatten",
                 "de prijzen van de goederen zetten",
                 "de klanten van een zaak tellen"],
         antwoord=0,
         uitleg="Elke aankoop, verkoop en betaling wordt genoteerd. Zo weet je wat de zaak bezit en schuldig is."),
    dict(type="meerkeuze",
         vraag="Wie heeft belang bij de boekhouding van een onderneming?",
         opties=["de zaakvoerder",
                 "de bank",
                 "de fiscus",
                 "de buurman"],
         antwoord=[0, 1, 2],
         uitleg="De zaakvoerder stuurt bij, de bank beoordeelt een lening, de fiscus controleert."),
    dict(type="meerkeuze",
         vraag="Waarom wil een bank de boekhouding zien?",
         opties=["om een lening te beoordelen",
                 "om de prijzen te controleren",
                 "om personeel aan te werven",
                 "om reclame te kunnen maken"],
         antwoord=0,
         uitleg="De cijfers tonen of de onderneming een lening kan terugbetalen."),
    dict(type="meerkeuze",
         vraag="Wat is de jaarrekening?",
         opties=["het jaarlijks financieel verslag",
                 "de rekening van een klant per jaar",
                 "het loon van de zaakvoerder ervan",
                 "de lijst van alle facturen erin"],
         antwoord=0,
         uitleg="Balans, resultatenrekening en toelichting samen."),
    dict(type="invultekst",
         vraag="Welke twee grote delen heeft de jaarrekening naast de toelichting? Hoogstens drie woorden.",
         antwoord=["balans en resultatenrekening", "balans, resultatenrekening"],
         uitleg="De balans en de resultatenrekening."),
    dict(type="waarofniet",
         vraag="Een onderneming is wettelijk verplicht een boekhouding te voeren.",
         antwoord=True,
         uitleg="De wet legt op welke boeken je bijhoudt en hoe lang je ze bewaart."),
    dict(type="waarofniet",
         vraag="Een boekhouding dient enkel om de belastingen te berekenen.",
         antwoord=False,
         uitleg="Ze dient vooral om te weten hoe de zaak ervoor staat en om te kunnen bijsturen."),
    dict(type="meerkeuze",
         vraag="Wat toont de balans?",
         opties=["het bezit en de schulden",
                 "de kosten en opbrengsten ervan",
                 "de klanten van het jaar",
                 "de lonen van het personeel"],
         antwoord=0,
         uitleg="Links wat de onderneming bezit, rechts met welk geld dat betaald is."),
    dict(type="meerkeuze",
         vraag="Wat toont de resultatenrekening?",
         opties=["de kosten en de opbrengsten",
                 "het bezit en de schulden ervan",
                 "de klanten en de leveranciers",
                 "de voorraad in het magazijn"],
         antwoord=0,
         uitleg="Het verschil tussen opbrengsten en kosten is de winst of het verlies."),
    dict(type="meerkeuze",
         vraag="Wat vind je terug in een jaarrekening?",
         opties=["de balans",
                 "de resultatenrekening",
                 "de toelichting",
                 "het uurrooster van het personeel"],
         antwoord=[0, 1, 2],
         uitleg="Drie delen. Het uurrooster hoort bij de personeelsadministratie."),
    dict(type="meerkeuze",
         vraag="Waarom is de boekhouding belangrijk voor de andere afdelingen?",
         opties=["ze levert de cijfers",
                 "ze bepaalt wie er mag werken",
                 "ze schrijft de reclameteksten",
                 "ze bestelt de goederen zelf"],
         antwoord=0,
         uitleg="Aankoop, verkoop en directie steunen op wat de boekhouding toont."),
    dict(type="meerkeuze",
         vraag="Wat is een verrichting in de boekhouding?",
         opties=["een feit met een gevolg in geld",
                 "een gesprek met een klant ervan",
                 "een plan voor het volgend jaar",
                 "een reclame op sociale media"],
         antwoord=0,
         uitleg="Een aankoop, een verkoop, een betaling: alles met een bedrag eraan."),
    dict(type="waarofniet",
         vraag="De fiscus mag de boekhouding van een onderneming controleren.",
         antwoord=True,
         uitleg="Daarom moeten de documenten een aantal jaren bewaard blijven."),
    dict(type="waarofniet",
         vraag="Een kleine zelfstandige hoeft geen enkel document bij te houden.",
         antwoord=False,
         uitleg="Ook een vereenvoudigde boekhouding vraagt een aankoop- en verkoopdagboek."),
    dict(type="invultekst",
         vraag="Hoe noem je het verschil tussen opbrengsten en kosten als het positief is? Eén woord.",
         antwoord=["winst", "de winst"],
         uitleg="Winst. Is het verschil negatief, dan is er verlies."),
    dict(type="meerkeuze",
         vraag="Wie beoordeelt met de jaarrekening of een onderneming gezond is?",
         opties=["een bank of een investeerder",
                 "de klant aan de kassa ervan",
                 "de buurman van de zaak",
                 "de postbode die langskomt"],
         antwoord=0,
         uitleg="Zij zetten er geld tegenover en willen weten hoe de zaak ervoor staat."),
    dict(type="meerkeuze",
         vraag="Waarvoor dient de toelichting bij de jaarrekening?",
         opties=["de cijfers uitleggen",
                 "de cijfers verbergen ervan",
                 "de winst groter maken",
                 "de klanten bedanken ervoor"],
         antwoord=0,
         uitleg="Ze geeft uitleg bij de posten van de balans en de resultatenrekening."),
    dict(type="meerkeuze",
         vraag="Waarvoor gebruikt een zaakvoerder de cijfers van zijn boekhouding?",
         opties=["bijsturen waar het misloopt",
                 "een investering plannen",
                 "een prijs herbekijken",
                 "het weer voorspellen"],
         antwoord=[0, 1, 2],
         uitleg="Een boekhouding kijkt terug, maar wordt vooral gebruikt om vooruit te beslissen."),
    dict(type="meerkeuze",
         vraag="Wat gebeurt er als de kosten groter zijn dan de opbrengsten?",
         opties=["er is verlies",
                 "er is winst gemaakt",
                 "de balans klopt niet",
                 "de btw vervalt dan"],
         antwoord=0,
         uitleg="Het resultaat is dan negatief. Dat verlies gaat naar het volgende boekjaar."),
    dict(type="invultekst",
         vraag="Hoe noem je het financieel verslag dat een onderneming jaarlijks neerlegt? Hoogstens drie woorden.",
         antwoord=["jaarrekening", "de jaarrekening"],
         uitleg="De jaarrekening."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat betekent dubbel boekhouden?",
         opties=["elke verrichting raakt twee rekeningen",
                 "elke verrichting wordt twee keer geteld",
                 "er zijn twee boekhouders nodig ervoor",
                 "de boekhouding wordt dubbel bewaard"],
         antwoord=0,
         uitleg="Debet bij de ene rekening, credit bij de andere, voor hetzelfde bedrag."),
    dict(type="meerkeuze",
         vraag="Wat betekent debet?",
         opties=["de linkerkant",
                 "de rechterkant ervan",
                 "het verschil ertussen",
                 "het totaal onderaan"],
         antwoord=0,
         uitleg="Debet staat links, credit staat rechts."),
    dict(type="meerkeuze",
         vraag="Wat moet in een dubbele boekhouding altijd kloppen?",
         opties=["debet is gelijk aan credit",
                 "de winst is groter dan nul",
                 "het aantal regels is even",
                 "de kas is altijd positief"],
         antwoord=0,
         uitleg="Elke boeking zet hetzelfde bedrag links en rechts. Daarom blijft het geheel in evenwicht."),
    dict(type="meerkeuze",
         vraag="Welke boeken horen bij de dubbele boekhouding?",
         opties=["het journaal",
                 "het grootboek",
                 "de inventaris",
                 "de agenda van de zaakvoerder"],
         antwoord=[0, 1, 2],
         uitleg="Journaal, grootboek en inventaris. De agenda hoort er niet bij."),
    dict(type="invultekst",
         vraag="Hoe noem je de rechterkant van een rekening? Eén woord.",
         antwoord=["credit", "de credit", "creditzijde"],
         uitleg="Credit. De linkerkant is debet."),
    dict(type="waarofniet",
         vraag="In het grootboek staan de boekingen gegroepeerd per rekening.",
         antwoord=True,
         uitleg="Zo zie je in één oogopslag het saldo van bijvoorbeeld de kas."),
    dict(type="waarofniet",
         vraag="Het journaal en het grootboek bevatten verschillende verrichtingen.",
         antwoord=False,
         uitleg="Dezelfde verrichtingen, maar anders geordend: op datum of per rekening."),
    dict(type="meerkeuze",
         vraag="Wat staat er in het journaal?",
         opties=["de boekingen op datum",
                 "de boekingen per rekening",
                 "enkel de facturen van klanten",
                 "de namen van alle werknemers"],
         antwoord=0,
         uitleg="Het journaal volgt de tijd. Het grootboek groepeert per rekening."),
    dict(type="meerkeuze",
         vraag="Wat is een rekening in de boekhouding?",
         opties=["een overzicht per soort",
                 "een factuur van een klant ervan",
                 "het bedrag op de bankrekening",
                 "de rekening van het restaurant"],
         antwoord=0,
         uitleg="Elke soort bezit, schuld, kost of opbrengst krijgt een eigen rekening."),
    dict(type="meerkeuze",
         vraag="Wat gebeurt er bij een aankoop op krediet?",
         opties=["de schuld stijgt",
                 "het geld in de kas vermindert",
                 "de voorraad vermindert ervan",
                 "de winst stijgt meteen ervan"],
         antwoord=0,
         uitleg="Je krijgt de goederen nu en betaalt later, dus de schuld aan de leverancier neemt toe."),
    dict(type="meerkeuze",
         vraag="Welke vragen stel je jezelf in het redeneerschema?",
         opties=["welke rekeningen zijn betrokken",
                 "stijgen of dalen ze",
                 "debet of credit",
                 "wie heeft de factuur getekend"],
         antwoord=[0, 1, 2],
         uitleg="Drie vragen na elkaar. Wie getekend heeft, verandert niets aan de boeking."),
    dict(type="meerkeuze",
         vraag="Hoeveel cijfers heeft een rekeningnummer op het examen?",
         opties=["5",
                 "3 in totaal",
                 "4 in totaal",
                 "6 in totaal"],
         antwoord=0,
         uitleg="Vijf cijfers. De naam van de rekening verschijnt vanzelf als je het nummer invult."),
    dict(type="waarofniet",
         vraag="Bij het redeneerschema krijg je enkel punten voor een regel die helemaal juist is.",
         antwoord=True,
         uitleg="Rekeningnummer, bedrag en de kant moeten alle drie kloppen."),
    dict(type="waarofniet",
         vraag="In het redeneerschema mag je zoveel boekingsregels gebruiken als je wil.",
         antwoord=False,
         uitleg="Je werkt zo efficiënt mogelijk, dus met een minimum aantal regels."),
    dict(type="invultekst",
         vraag="Hoe noem je het boek waarin de verrichtingen op datum staan? Eén woord.",
         antwoord=["journaal", "het journaal", "dagboek"],
         uitleg="Het journaal, ook dagboek genoemd."),
    dict(type="meerkeuze",
         vraag="Wat betekent het als een rekening een debetsaldo heeft?",
         opties=["debet is groter dan credit",
                 "credit is groter dan debet ervan",
                 "de rekening staat op nul",
                 "de rekening is afgesloten"],
         antwoord=0,
         uitleg="Het saldo staat dan links. Bij een creditsaldo is het omgekeerd."),
    dict(type="meerkeuze",
         vraag="Waarom boek je elke verrichting links en rechts?",
         opties=["er is altijd een herkomst en een bestemming",
                 "zo staat het bedrag zeker twee keer genoteerd",
                 "zo wordt de boekhouding dubbel zo groot",
                 "dat is een afspraak zonder verdere reden"],
         antwoord=0,
         uitleg="Geld komt ergens vandaan en gaat ergens heen. Het dubbel boekhouden toont beide kanten."),
    dict(type="meerkeuze",
         vraag="Wat hoort bij een boeking in het journaal?",
         opties=["de datum",
                 "het rekeningnummer",
                 "het bedrag in debet of credit",
                 "de naam van de klant altijd"],
         antwoord=[0, 1, 2],
         uitleg="De naam van de klant staat op het document, niet noodzakelijk in de boeking."),
    dict(type="meerkeuze",
         vraag="Wat is het nut van het grootboek?",
         opties=["het saldo per rekening volgen",
                 "de facturen alfabetisch leggen",
                 "de klanten een brief sturen",
                 "de voorraad fysiek tellen"],
         antwoord=0,
         uitleg="Alle boekingen van één rekening staan samen, dus het saldo is meteen zichtbaar."),
    dict(type="invultekst",
         vraag="Hoe noem je de linkerkant van een rekening? Eén woord.",
         antwoord=["debet", "de debet", "debetzijde"],
         uitleg="Debet. De rechterkant is credit."),
]
