# -*- coding: utf-8 -*-
"""De balans en de resultatenrekening.

Van de vakfiche toegepaste economie 2DU (2027): de structuur van de balans,
de beginbalans, de structuur van de resultatenrekening en het berekenen van
het bedrijfsresultaat, het financieel resultaat en het resultaat van de
onderneming.

Deel 1 is de balans.
Deel 2 is de resultatenrekening.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat staat er aan de actiefzijde van de balans?",
         opties=["wat de onderneming bezit",
                 "wat de onderneming schuldig is",
                 "de kosten van het boekjaar",
                 "de opbrengsten van het jaar"],
         antwoord=0,
         uitleg="Links staat het bezit: gebouwen, machines, voorraad, geld."),
    dict(type="meerkeuze",
         vraag="Wat staat er aan de passiefzijde van de balans?",
         opties=["waarmee het betaald is",
                 "wat de onderneming bezit ervan",
                 "de verkopen van het jaar",
                 "de voorraad in het magazijn"],
         antwoord=0,
         uitleg="Het eigen vermogen en de schulden, dus de herkomst van de middelen."),
    dict(type="meerkeuze",
         vraag="Wat is altijd waar bij een balans?",
         opties=["actief is gelijk aan passief",
                 "het actief is groter ervan",
                 "het passief is groter ervan",
                 "de winst staat links erin"],
         antwoord=0,
         uitleg="Alles wat je bezit is met iets betaald. Daarom is het totaal links gelijk aan dat rechts."),
    dict(type="meerkeuze",
         vraag="Wat zijn vaste activa?",
         opties=["bezit voor langer dan een jaar",
                 "goederen die snel verkocht raken",
                 "het geld op de bankrekening",
                 "de schulden aan de leverancier"],
         antwoord=0,
         uitleg="Een gebouw, een machine, een bestelwagen."),
    dict(type="invultekst",
         vraag="Hoe noem je de kant van de balans met het bezit? Eén woord.",
         antwoord=["actief", "het actief", "actiefzijde"],
         uitleg="Het actief, links op de balans."),
    dict(type="waarofniet",
         vraag="Het eigen vermogen hoort bij het passief.",
         antwoord=True,
         uitleg="Het is geld dat de eigenaars in de zaak lieten, dus een herkomst van middelen."),
    dict(type="waarofniet",
         vraag="Een lening op lange termijn hoort bij de vaste activa.",
         antwoord=False,
         uitleg="Een lening is een schuld en staat dus rechts, bij het passief."),
    dict(type="meerkeuze",
         vraag="Wat zijn vlottende activa?",
         opties=["bezit voor korte tijd",
                 "bezit voor meerdere jaren ervan",
                 "het kapitaal van de zaakvoerder",
                 "de schulden op lange termijn"],
         antwoord=0,
         uitleg="Voorraad, vorderingen op klanten, geld op de bank en in de kas."),
    dict(type="meerkeuze",
         vraag="Welke posten horen bij de vaste activa?",
         opties=["een gebouw",
                 "een machine",
                 "een bestelwagen",
                 "de voorraad handelsgoederen"],
         antwoord=[0, 1, 2],
         uitleg="De voorraad is een vlottend actief: ze is bedoeld om snel weer te verkopen."),
    dict(type="meerkeuze",
         vraag="Wat is het eigen vermogen?",
         opties=["het geld van de eigenaars",
                 "de schuld aan de bank ervan",
                 "de waarde van de voorraad",
                 "de omzet van het boekjaar"],
         antwoord=0,
         uitleg="Het kapitaal dat de eigenaars inbrachten, plus de winst die in de zaak bleef."),
    dict(type="meerkeuze",
         vraag="Wat is vreemd vermogen?",
         opties=["de schulden",
                 "het kapitaal van de eigenaars",
                 "de winst van het boekjaar",
                 "het bezit van de onderneming"],
         antwoord=0,
         uitleg="Geld van anderen: de bank, de leveranciers, de fiscus."),
    dict(type="meerkeuze",
         vraag="Wat is een beginbalans?",
         opties=["de balans bij de start",
                 "de balans op het einde ervan",
                 "de balans halverwege het jaar",
                 "de balans van vorig jaar ervan"],
         antwoord=0,
         uitleg="De toestand bij de start van het boekjaar. Ze is gelijk aan de eindbalans van het vorige jaar."),
    dict(type="waarofniet",
         vraag="De winst van het boekjaar staat bij het eigen vermogen op de balans.",
         antwoord=True,
         uitleg="Winst die in de zaak blijft, versterkt het eigen vermogen."),
    dict(type="waarofniet",
         vraag="De balans toont wat er tijdens het jaar verkocht is.",
         antwoord=False,
         uitleg="De balans is een momentopname. Wat er verkocht is, staat in de resultatenrekening."),
    dict(type="invultekst",
         vraag="Hoe noem je de kant van de balans met het vermogen? Eén woord.",
         antwoord=["passief", "het passief", "passiefzijde"],
         uitleg="Het passief, rechts op de balans."),
    dict(type="meerkeuze",
         vraag="Welke posten horen bij het passief?",
         opties=["het kapitaal",
                 "de schuld aan de leveranciers",
                 "een lening bij de bank",
                 "de bestelwagen van de zaak"],
         antwoord=[0, 1, 2],
         uitleg="De bestelwagen is bezit en staat links, bij de vaste activa."),
    dict(type="meerkeuze",
         vraag="Een zaak bezit voor 80000 euro en heeft 30000 euro schulden. Hoe groot is het eigen vermogen?",
         opties=["50000 euro",
                 "110000 euro samen",
                 "30000 euro ervan",
                 "80000 euro ervan"],
         antwoord=0,
         uitleg="Bezit min schulden is het eigen vermogen: 80000 min 30000 is 50000."),
    dict(type="meerkeuze",
         vraag="Waar staat de voorraad handelsgoederen op de balans?",
         opties=["bij de vlottende activa",
                 "bij de vaste activa ervan",
                 "bij het eigen vermogen",
                 "bij de schulden op lange termijn"],
         antwoord=0,
         uitleg="Ze is bedoeld om binnen het jaar verkocht te worden."),
    dict(type="meerkeuze",
         vraag="Wat lees je af op een balans?",
         opties=["wat de zaak bezit",
                 "wie de zaak gefinancierd heeft",
                 "hoe groot het eigen vermogen is",
                 "hoeveel klanten er geweest zijn"],
         antwoord=[0, 1, 2],
         uitleg="Het aantal klanten staat nergens op de balans."),
    dict(type="invultekst",
         vraag="Een zaak heeft 25000 euro bezit en 25000 euro schulden. Hoe groot is het eigen vermogen? Een getal.",
         antwoord=["0", "nul", "0 euro"],
         uitleg="Nul. Alles wat de zaak bezit, is met vreemd vermogen betaald."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is een kost?",
         opties=["wat de zaak verbruikt",
                 "wat de zaak ontvangt ervan",
                 "wat de zaak bezit in totaal",
                 "wat de zaak schuldig is"],
         antwoord=0,
         uitleg="Lonen, huur, de aankoop van handelsgoederen. Kosten verminderen het resultaat."),
    dict(type="meerkeuze",
         vraag="Wat is een opbrengst?",
         opties=["wat de zaak verdient",
                 "wat de zaak uitgeeft ervan",
                 "wat de zaak bezit in totaal",
                 "wat de zaak nog moet betalen"],
         antwoord=0,
         uitleg="Vooral de verkopen. Opbrengsten verhogen het resultaat."),
    dict(type="meerkeuze",
         vraag="Wat is het bedrijfsresultaat?",
         opties=["bedrijfsopbrengsten min bedrijfskosten",
                 "alle opbrengsten min alle kosten van het jaar",
                 "de intresten min de financiële kosten ervan",
                 "de winst na aftrek van de belastingen ervan"],
         antwoord=0,
         uitleg="Het resultaat van de gewone werking, zonder de financiële verrichtingen."),
    dict(type="meerkeuze",
         vraag="Wat is het financieel resultaat?",
         opties=["financiële opbrengsten min kosten",
                 "de verkopen min de aankopen ervan",
                 "het loon van het personeel ervan",
                 "de waarde van de voorraad ervan"],
         antwoord=0,
         uitleg="Ontvangen intresten tegenover betaalde intresten en bankkosten."),
    dict(type="invultekst",
         vraag="Hoe noem je het resultaat als de kosten groter zijn dan de opbrengsten? Eén woord.",
         antwoord=["verlies", "het verlies"],
         uitleg="Verlies. Het gaat over naar het volgende boekjaar."),
    dict(type="waarofniet",
         vraag="De resultatenrekening gaat over een periode, de balans over een moment.",
         antwoord=True,
         uitleg="De balans is een foto, de resultatenrekening is de film van het boekjaar."),
    dict(type="waarofniet",
         vraag="De aankoop van een machine is een kost in de resultatenrekening.",
         antwoord=False,
         uitleg="Een machine is een investering en staat op de balans. Enkel de afschrijving is een kost."),
    dict(type="meerkeuze",
         vraag="Wat is de omzet?",
         opties=["de verkopen van het jaar",
                 "de winst van het jaar ervan",
                 "het bezit van de zaak ervan",
                 "het kapitaal van de eigenaars"],
         antwoord=0,
         uitleg="Omzet is niet hetzelfde als winst: de kosten moeten er nog af."),
    dict(type="meerkeuze",
         vraag="Welke posten zijn kosten?",
         opties=["de lonen",
                 "de huur van het pand",
                 "de aankoop van handelsgoederen",
                 "de verkoop van handelsgoederen"],
         antwoord=[0, 1, 2],
         uitleg="De verkoop is een opbrengst, geen kost."),
    dict(type="meerkeuze",
         vraag="Hoe bereken je het resultaat van het boekjaar?",
         opties=["alle opbrengsten min alle kosten",
                 "de verkopen plus de aankopen ervan",
                 "het bezit min de voorraad ervan",
                 "het kapitaal plus de schulden ervan"],
         antwoord=0,
         uitleg="Bedrijfsresultaat en financieel resultaat samen, en daarna de belastingen eraf."),
    dict(type="meerkeuze",
         vraag="Een zaak heeft 120000 euro opbrengsten en 95000 euro kosten. Wat is het resultaat?",
         opties=["25000 euro winst",
                 "215000 euro samen",
                 "25000 euro verlies",
                 "95000 euro winst"],
         antwoord=0,
         uitleg="120000 min 95000 is 25000 euro winst."),
    dict(type="meerkeuze",
         vraag="Waar komt de winst van het boekjaar terecht op de balans?",
         opties=["bij het eigen vermogen",
                 "bij de vaste activa ervan",
                 "bij de schulden op korte termijn",
                 "bij de voorraad handelsgoederen"],
         antwoord=0,
         uitleg="Winst die in de zaak blijft, versterkt het eigen vermogen."),
    dict(type="waarofniet",
         vraag="Een onderneming kan winst maken op haar werking en toch verlies op haar financiële verrichtingen.",
         antwoord=True,
         uitleg="Daarom worden het bedrijfsresultaat en het financieel resultaat apart berekend."),
    dict(type="waarofniet",
         vraag="Omzet en winst betekenen hetzelfde.",
         antwoord=False,
         uitleg="Omzet is wat binnenkomt uit verkopen. Winst is wat overblijft als alle kosten betaald zijn."),
    dict(type="invultekst",
         vraag="Hoe noem je de opbrengst uit de verkopen? Eén woord.",
         antwoord=["omzet", "de omzet"],
         uitleg="De omzet."),
    dict(type="meerkeuze",
         vraag="Welke resultaten vraagt de vakfiche te berekenen?",
         opties=["het bedrijfsresultaat",
                 "het financieel resultaat",
                 "het resultaat van de onderneming",
                 "het resultaat van de concurrent"],
         antwoord=[0, 1, 2],
         uitleg="Drie resultaten na elkaar. Wat de concurrent doet, staat niet in jouw boekhouding."),
    dict(type="meerkeuze",
         vraag="Wat is een afschrijving?",
         opties=["de kost van slijtage",
                 "de verkoop van een machine",
                 "de aankoop van een gebouw",
                 "het verlies van een klant"],
         antwoord=0,
         uitleg="De waarde van een investering wordt over meerdere jaren als kost genomen."),
    dict(type="meerkeuze",
         vraag="Waarom is de resultatenrekening nuttig voor de zaakvoerder?",
         opties=["ze toont waar het geld heen gaat",
                 "ze toont hoeveel klanten er waren",
                 "ze toont de namen van de leveranciers",
                 "ze toont het uurrooster van het team"],
         antwoord=0,
         uitleg="Je ziet welke kosten zwaar wegen en welke opbrengsten er tegenover staan."),
    dict(type="meerkeuze",
         vraag="Welke posten zijn opbrengsten?",
         opties=["de verkoop van handelsgoederen",
                 "ontvangen intresten",
                 "een ontvangen huurgeld",
                 "een betaalde factuur van de leverancier"],
         antwoord=[0, 1, 2],
         uitleg="Een betaalde factuur van een leverancier is een kost."),
    dict(type="invultekst",
         vraag="Een zaak heeft 60000 euro opbrengsten en 72000 euro kosten. Hoe groot is het verlies? Een getal.",
         antwoord=["12000", "12000 euro"],
         uitleg="72000 min 60000 is 12000 euro verlies."),
]
