# -*- coding: utf-8 -*-
"""Eindejaarsverrichtingen registreren.

Van de vakfiche toegepaste economie 2DU (2027): de proef- en saldibalans en
het verschil tussen een voorlopige en een definitieve, de
eindejaarsverrichtingen (jaarlijkse afschrijvingen en de regularisatie van
schulden op meer dan één jaar), de overdracht van de winst of het verlies, en
het opstellen van een eenvoudige eindbalans.

Deel 1 is de proef- en saldibalans.
Deel 2 zijn de eindejaarsverrichtingen en de eindbalans.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is een proefbalans?",
         opties=["de totalen van elke rekening",
                 "de saldo's van elke rekening ervan",
                 "de balans van het volgend jaar",
                 "een overzicht van de winst ervan"],
         antwoord=0,
         uitleg="Ze telt per rekening wat er in debet en wat er in credit staat."),
    dict(type="meerkeuze",
         vraag="Wat is een saldibalans?",
         opties=["de saldo's per rekening",
                 "de totalen per rekening ervan",
                 "de winst van het boekjaar ervan",
                 "de lijst van alle klanten ervan"],
         antwoord=0,
         uitleg="Per rekening het verschil tussen debet en credit."),
    dict(type="meerkeuze",
         vraag="Waarvoor dient een proef- en saldibalans?",
         opties=["nagaan of alles klopt",
                 "de winst groter maken ervan",
                 "de klanten te woord staan",
                 "de voorraad te bestellen"],
         antwoord=0,
         uitleg="Kloppen de totalen niet, dan zit er ergens een fout in de boekingen."),
    dict(type="meerkeuze",
         vraag="Wat is het verschil tussen een voorlopige en een definitieve proef- en saldibalans?",
         opties=["de eindejaarsverrichtingen",
                 "het aantal rekeningen ervan",
                 "de naam van de onderneming",
                 "de kleur van de kolommen"],
         antwoord=0,
         uitleg="De voorlopige komt ervoor, de definitieve erna."),
    dict(type="invultekst",
         vraag="Hoe noem je de balans na alle eindejaarsverrichtingen? Hoogstens drie woorden.",
         antwoord=["eindbalans", "de eindbalans"],
         uitleg="De eindbalans."),
    dict(type="waarofniet",
         vraag="In een proefbalans is het totaal van debet gelijk aan dat van credit.",
         antwoord=True,
         uitleg="Elke boeking zette hetzelfde bedrag links en rechts, dus de totalen moeten kloppen."),
    dict(type="waarofniet",
         vraag="Een saldibalans en een proefbalans geven dezelfde cijfers.",
         antwoord=False,
         uitleg="De proefbalans geeft de totalen, de saldibalans de verschillen."),
    dict(type="meerkeuze",
         vraag="Wat doe je als debet en credit in de proefbalans niet gelijk zijn?",
         opties=["de fout opzoeken",
                 "het verschil bijtellen",
                 "de balans toch afsluiten",
                 "een nieuwe rekening maken"],
         antwoord=0,
         uitleg="Een verschil betekent dat er een boeking ontbreekt of verkeerd staat."),
    dict(type="meerkeuze",
         vraag="Welke balansen komen aan bod op het einde van het jaar?",
         opties=["de voorlopige proef- en saldibalans",
                 "de definitieve proef- en saldibalans",
                 "de eindbalans",
                 "de bestelbon"],
         antwoord=[0, 1, 2],
         uitleg="Een bestelbon is geen balans, maar een aankoopdocument."),
    dict(type="meerkeuze",
         vraag="Wat gebeurt er met de eindbalans van dit jaar?",
         opties=["ze wordt de beginbalans",
                 "ze wordt weggegooid ervan",
                 "ze wordt een factuur ervan",
                 "ze blijft ongebruikt ervan"],
         antwoord=0,
         uitleg="De eindbalans van dit boekjaar is de beginbalans van het volgende."),
    dict(type="meerkeuze",
         vraag="Welke rekeningen staan niet meer op de eindbalans?",
         opties=["de kosten en de opbrengsten",
                 "de vaste activa van de onderneming",
                 "de schulden op lange termijn",
                 "het eigen vermogen ervan"],
         antwoord=0,
         uitleg="Klasse 6 en 7 worden afgesloten. Hun verschil is het resultaat, en dat komt bij het eigen vermogen."),
    dict(type="meerkeuze",
         vraag="Wat gebeurt er bij de afsluiting van een boekjaar?",
         opties=["de boeken van het jaar sluiten",
                 "de klanten een brief sturen ervan",
                 "nieuwe facturen maken ervan",
                 "de voorraad verkopen ervan"],
         antwoord=0,
         uitleg="De resultatenrekeningen gaan naar nul en het resultaat komt op de balans."),
    dict(type="waarofniet",
         vraag="Een proef- en saldibalans is een controle en geen document voor buiten.",
         antwoord=True,
         uitleg="Ze is een tussenstap. Wat naar buiten gaat, is de jaarrekening."),
    dict(type="waarofniet",
         vraag="De eindbalans wordt opgesteld voor de eindejaarsverrichtingen.",
         antwoord=False,
         uitleg="Juist erna. Anders zouden de afschrijvingen er niet in zitten."),
    dict(type="invultekst",
         vraag="Hoe noem je het verschil tussen debet en credit van één rekening? Eén woord.",
         antwoord=["saldo", "het saldo"],
         uitleg="Het saldo."),
    dict(type="meerkeuze",
         vraag="Wat controleer je met een proef- en saldibalans?",
         opties=["of debet en credit gelijk zijn",
                 "of elke rekening een logisch saldo heeft",
                 "of er geen boeking ontbreekt",
                 "of de klanten tevreden zijn"],
         antwoord=[0, 1, 2],
         uitleg="Een kostenrekening met een creditsaldo verraadt bijvoorbeeld een fout."),
    dict(type="meerkeuze",
         vraag="De kasrekening heeft 5000 euro in debet en 3200 euro in credit. Wat is het saldo?",
         opties=["1800 euro in debet",
                 "8200 euro in debet",
                 "1800 euro in credit",
                 "3200 euro in debet"],
         antwoord=0,
         uitleg="5000 min 3200 is 1800 euro, aan de kant met het grootste totaal."),
    dict(type="meerkeuze",
         vraag="Waarom hoort een kostenrekening een debetsaldo te hebben?",
         opties=["kosten stijgen in debet",
                 "kosten stijgen in credit ervan",
                 "kosten horen bij het passief",
                 "kosten staan op de balans ervan"],
         antwoord=0,
         uitleg="Een creditsaldo op een kostenrekening is een teken dat er iets fout zit."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over de eindbalans zijn juist?",
         opties=["ze toont de toestand op het einde van het boekjaar",
                 "ze is in evenwicht",
                 "ze wordt de beginbalans van volgend jaar",
                 "ze toont de kosten van het jaar"],
         antwoord=[0, 1, 2],
         uitleg="De kosten staan in de resultatenrekening, niet op de balans."),
    dict(type="invultekst",
         vraag="Een rekening heeft 900 euro debet en 1500 euro credit. Hoe groot is het saldo? Een getal.",
         antwoord=["600", "600 euro"],
         uitleg="1500 min 900 is 600 euro, in credit."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is een eindejaarsverrichting?",
         opties=["een boeking bij de afsluiting",
                 "een verkoop in december ervan",
                 "een bestelling van januari ervan",
                 "een factuur van een klant ervan"],
         antwoord=0,
         uitleg="Ze zet de cijfers recht voor de jaarrekening wordt opgemaakt."),
    dict(type="meerkeuze",
         vraag="Waarom schrijf je een machine af?",
         opties=["ze verliest waarde",
                 "ze wordt verkocht ervan",
                 "ze gaat kapot ervan",
                 "ze staat in de weg ervan"],
         antwoord=0,
         uitleg="Je spreidt de kostprijs over de jaren dat je ze gebruikt."),
    dict(type="meerkeuze",
         vraag="Een machine kost 20000 euro en gaat 5 jaar mee. Hoeveel schrijf je lineair per jaar af?",
         opties=["4000 euro",
                 "5000 euro ervan",
                 "2000 euro ervan",
                 "20000 euro ervan"],
         antwoord=0,
         uitleg="20000 gedeeld door 5 is 4000 euro per jaar."),
    dict(type="meerkeuze",
         vraag="Waar komt de afschrijving in de boekhouding terecht?",
         opties=["bij de kosten",
                 "bij de opbrengsten ervan",
                 "bij de schulden ervan",
                 "bij de voorraad ervan"],
         antwoord=0,
         uitleg="Een kost van klasse 6. Tegelijk daalt de waarde van het actief op de balans."),
    dict(type="invultekst",
         vraag="Een bestelwagen kost 30000 euro en gaat 6 jaar mee. Hoeveel schrijf je per jaar af? Een getal.",
         antwoord=["5000", "5000 euro"],
         uitleg="30000 gedeeld door 6 is 5000 euro."),
    dict(type="waarofniet",
         vraag="Een afschrijving kost geen geld op het moment dat je ze boekt.",
         antwoord=True,
         uitleg="Het geld ging al buiten bij de aankoop. De afschrijving spreidt die uitgave over de jaren."),
    dict(type="waarofniet",
         vraag="Grond wordt afgeschreven zoals een machine.",
         antwoord=False,
         uitleg="Grond slijt niet en verliest geen waarde door gebruik, dus ze wordt niet afgeschreven."),
    dict(type="meerkeuze",
         vraag="Wat is de regularisatie van een schuld op meer dan één jaar?",
         opties=["het deel voor volgend jaar verschuiven",
                 "de hele schuld in één keer betalen",
                 "de schuld kwijtschelden ervan",
                 "de schuld verdubbelen ervan"],
         antwoord=0,
         uitleg="Het stuk dat binnen het jaar vervalt, verhuist naar de schulden op korte termijn."),
    dict(type="meerkeuze",
         vraag="Waarom verhuist dat deel van de schuld?",
         opties=["zo klopt de balans beter",
                 "zo betaal je minder ervan",
                 "zo stijgt de winst ervan",
                 "zo daalt de btw ervan"],
         antwoord=0,
         uitleg="Een lezer ziet dan meteen welke schulden binnen het jaar betaald moeten worden."),
    dict(type="meerkeuze",
         vraag="Welke eindejaarsverrichtingen noemt de vakfiche?",
         opties=["de jaarlijkse afschrijvingen",
                 "de regularisatie van schulden op meer dan een jaar",
                 "de overdracht van het resultaat",
                 "de aankoop van nieuwe goederen"],
         antwoord=[0, 1, 2],
         uitleg="Een aankoop is een gewone verrichting van tijdens het jaar."),
    dict(type="meerkeuze",
         vraag="Wat doe je met de winst van het boekjaar?",
         opties=["ze gaat over naar volgend jaar",
                 "ze wordt een kost ervan",
                 "ze verdwijnt ervan",
                 "ze wordt een schuld aan de klant"],
         antwoord=0,
         uitleg="Overgedragen winst versterkt het eigen vermogen op de balans."),
    dict(type="meerkeuze",
         vraag="Waar staat het verlies van het boekjaar op de balans?",
         opties=["bij het eigen vermogen",
                 "bij de vaste activa ervan",
                 "bij de voorraad ervan",
                 "bij de schulden op korte termijn"],
         antwoord=0,
         uitleg="Met een minteken: een verlies verkleint het eigen vermogen."),
    dict(type="waarofniet",
         vraag="De afschrijving verlaagt de boekwaarde van het actief.",
         antwoord=True,
         uitleg="Na elk jaar staat de machine voor minder op de balans."),
    dict(type="waarofniet",
         vraag="Een eindejaarsverrichting wordt niet in het journaal geboekt.",
         antwoord=False,
         uitleg="Ze is een boeking als alle andere en gaat gewoon in het journaal."),
    dict(type="invultekst",
         vraag="Hoe noem je de waarde van een machine na aftrek van de afschrijvingen? Hoogstens drie woorden.",
         antwoord=["boekwaarde", "de boekwaarde"],
         uitleg="De boekwaarde."),
    dict(type="meerkeuze",
         vraag="Een machine van 20000 euro is drie jaar afgeschreven aan 4000 euro per jaar. Wat is de boekwaarde?",
         opties=["8000 euro",
                 "12000 euro ervan",
                 "20000 euro ervan",
                 "4000 euro ervan"],
         antwoord=0,
         uitleg="3 maal 4000 is 12000, en 20000 min 12000 is 8000 euro."),
    dict(type="meerkeuze",
         vraag="Welke stappen horen bij het afsluiten van een boekjaar?",
         opties=["de voorlopige proef- en saldibalans maken",
                 "de eindejaarsverrichtingen boeken",
                 "de eindbalans opstellen",
                 "een nieuwe leverancier zoeken"],
         antwoord=[0, 1, 2],
         uitleg="In die volgorde. Daartussen komt nog de definitieve proef- en saldibalans."),
    dict(type="meerkeuze",
         vraag="Wat betekent lineair afschrijven?",
         opties=["elk jaar hetzelfde bedrag",
                 "elk jaar een kleiner bedrag",
                 "elk jaar een groter bedrag",
                 "alles in het eerste jaar"],
         antwoord=0,
         uitleg="De aankoopprijs gedeeld door het aantal jaren."),
    dict(type="meerkeuze",
         vraag="Welke activa worden afgeschreven?",
         opties=["een machine",
                 "een bestelwagen",
                 "een computer",
                 "de grond onder het gebouw"],
         antwoord=[0, 1, 2],
         uitleg="Grond slijt niet en wordt daarom niet afgeschreven."),
    dict(type="invultekst",
         vraag="Over hoeveel jaar schrijf je 15000 euro af aan 3000 euro per jaar? Een getal.",
         antwoord=["5", "vijf"],
         uitleg="15000 gedeeld door 3000 is 5 jaar."),
]
