# -*- coding: utf-8 -*-
"""Formules en functies in een rekenblad.

Van de vakfiche toegepaste economie 2DU (2027): de operatoren en de
rekenregels, de functies SOM, AFRONDEN, PRODUCT, GEMIDDELDE, MAX, MIN,
AANTAL, VANDAAG, NU, JAAR, HOOFDLETTERS, KLEINE LETTERS, LINKS, RECHTS,
HORIZ.ZOEKEN, VERT.ZOEKEN en ALS, en de relatieve, absolute en gemengde
celadressering.

Deel 1 zijn de rekenfuncties en de operatoren.
Deel 2 zijn ALS, de zoekfuncties en de adressering.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat doet de functie SOM?",
         opties=["getallen optellen",
                 "getallen aftrekken ervan",
                 "getallen sorteren ervan",
                 "getallen vermenigvuldigen"],
         antwoord=0,
         uitleg="=SOM(A1:A20) telt alles in dat bereik op."),
    dict(type="meerkeuze",
         vraag="Wat doet de functie GEMIDDELDE?",
         opties=["het gemiddelde nemen",
                 "het grootste getal nemen",
                 "het kleinste getal nemen",
                 "het aantal cellen tellen"],
         antwoord=0,
         uitleg="De som gedeeld door het aantal getallen, in één functie."),
    dict(type="meerkeuze",
         vraag="Wat doet de functie MAX?",
         opties=["het hoogste getal geven",
                 "het laagste getal geven",
                 "het aantal getallen geven",
                 "de som van de getallen"],
         antwoord=0,
         uitleg="MAX geeft het hoogste, MIN het laagste."),
    dict(type="meerkeuze",
         vraag="Wat doet de functie AANTAL?",
         opties=["de cellen met getallen tellen",
                 "de getallen bij elkaar optellen",
                 "de hoogste waarde opzoeken",
                 "de cellen leegmaken ervan"],
         antwoord=0,
         uitleg="Ze telt hoeveel cellen een getal bevatten, niet hoeveel die getallen samen zijn."),
    dict(type="invultekst",
         vraag="Welke functie gebruik je om een reeks getallen op te tellen? Eén woord.",
         antwoord=["som"],
         uitleg="SOM."),
    dict(type="waarofniet",
         vraag="=SOM(A1:A5) telt vijf cellen op.",
         antwoord=True,
         uitleg="A1, A2, A3, A4 en A5, de eerste en de laatste meegerekend."),
    dict(type="waarofniet",
         vraag="De functie PRODUCT telt de getallen op.",
         antwoord=False,
         uitleg="PRODUCT vermenigvuldigt ze met elkaar."),
    dict(type="meerkeuze",
         vraag="Wat doet =AFRONDEN(12,348;2)?",
         opties=["het geeft 12,35",
                 "het geeft 12,34 ervan",
                 "het geeft 12,00 ervan",
                 "het geeft 1234 ervan"],
         antwoord=0,
         uitleg="Het tweede getal zegt op hoeveel cijfers na de komma er afgerond wordt."),
    dict(type="meerkeuze",
         vraag="Wat doet de functie VANDAAG?",
         opties=["de datum van vandaag",
                 "de tijd van nu ervan",
                 "het jaartal ervan",
                 "de dag van de week"],
         antwoord=0,
         uitleg="Ze past zich elke dag aan, dus een factuur met VANDAAG erin verandert van datum."),
    dict(type="meerkeuze",
         vraag="Wat doet de functie NU?",
         opties=["datum en uur geven",
                 "enkel de datum geven",
                 "enkel het uur geven",
                 "de dagen tellen ervan"],
         antwoord=0,
         uitleg="VANDAAG geeft enkel de datum, NU ook het uur."),
    dict(type="meerkeuze",
         vraag="Welke functies geven één getal uit een reeks?",
         opties=["MAX",
                 "MIN",
                 "GEMIDDELDE",
                 "HOOFDLETTERS"],
         antwoord=[0, 1, 2],
         uitleg="HOOFDLETTERS werkt op tekst, niet op een reeks getallen."),
    dict(type="meerkeuze",
         vraag="Welke operatoren gebruik je in een rekenblad?",
         opties=["het sterretje om te vermenigvuldigen",
                 "het schuine streepje om te delen",
                 "het dakje om te verheffen",
                 "de letter x om te vermenigvuldigen"],
         antwoord=[0, 1, 2],
         uitleg="De letter x is voor een rekenblad gewoon tekst."),
    dict(type="waarofniet",
         vraag="Haakjes in een formule veranderen de rekenvolgorde.",
         antwoord=True,
         uitleg="=(2+3)*4 geeft 20, =2+3*4 geeft 14."),
    dict(type="waarofniet",
         vraag="Een functienaam moet je in hoofdletters typen.",
         antwoord=False,
         uitleg="Typ som(a1:a5) en het rekenblad maakt er zelf SOM(A1:A5) van."),
    dict(type="invultekst",
         vraag="Welke functie geeft het jaartal uit een datum? Eén woord.",
         antwoord=["jaar"],
         uitleg="JAAR."),
    dict(type="meerkeuze",
         vraag="Wat doet =MIN(B2:B10)?",
         opties=["het laagste getal zoeken",
                 "het hoogste getal zoeken",
                 "de getallen optellen ervan",
                 "de getallen tellen ervan"],
         antwoord=0,
         uitleg="Het kleinste getal uit dat bereik."),
    dict(type="meerkeuze",
         vraag="Waarom gebruik je een functie in plaats van alles zelf op te tellen?",
         opties=["de formule past zich aan",
                 "de formule is korter ervan",
                 "de cel wordt mooier ervan",
                 "het bestand wordt kleiner"],
         antwoord=0,
         uitleg="Wijzig je een getal in het bereik, dan verandert het totaal mee."),
    dict(type="meerkeuze",
         vraag="Wat is de rekenregel in een rekenblad?",
         opties=["eerst maal en delen",
                 "eerst plus en min ervan",
                 "altijd van links naar rechts",
                 "altijd van rechts naar links"],
         antwoord=0,
         uitleg="Eerst machten, dan maal en delen, dan plus en min. Haakjes gaan voor."),
    dict(type="meerkeuze",
         vraag="Wat hoort in een functie tussen de haakjes?",
         opties=["een bereik van cellen",
                 "een celadres",
                 "een getal",
                 "de naam van het bestand"],
         antwoord=[0, 1, 2],
         uitleg="Dat heet het argument van de functie."),
    dict(type="invultekst",
         vraag="Welke functie vermenigvuldigt de getallen in een bereik? Eén woord.",
         antwoord=["product"],
         uitleg="PRODUCT."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat doet de functie ALS?",
         opties=["tussen twee uitkomsten kiezen",
                 "een getal afronden ervan",
                 "een reeks optellen ervan",
                 "een datum invullen ervan"],
         antwoord=0,
         uitleg="Is de voorwaarde waar, dan het ene antwoord; anders het andere."),
    dict(type="meerkeuze",
         vraag="Welke drie delen heeft de functie ALS?",
         opties=["test, waar, niet waar",
                 "begin, midden, einde",
                 "rij, kolom, cel ervan",
                 "som, aantal, gemiddelde"],
         antwoord=0,
         uitleg="=ALS(A1>100;\"korting\";\"geen korting\")."),
    dict(type="meerkeuze",
         vraag="Wat is een geneste ALS?",
         opties=["een ALS in een ALS",
                 "een ALS met een som",
                 "een ALS zonder test",
                 "een ALS in een tabel"],
         antwoord=0,
         uitleg="Zo kies je tussen meer dan twee uitkomsten, bijvoorbeeld drie kortingstarieven."),
    dict(type="meerkeuze",
         vraag="Wat doet VERT.ZOEKEN?",
         opties=["iets opzoeken in een kolom",
                 "iets opzoeken in een rij",
                 "een getal afronden ervan",
                 "een rij sorteren ervan"],
         antwoord=0,
         uitleg="Ze zoekt in de eerste kolom van de tabel en geeft iets uit dezelfde rij terug."),
    dict(type="invultekst",
         vraag="Welke functie zoekt een waarde op in de eerste rij van een tabel? Hoogstens drie woorden.",
         antwoord=["horiz.zoeken", "horizontaal zoeken", "horiz zoeken"],
         uitleg="HORIZ.ZOEKEN."),
    dict(type="waarofniet",
         vraag="VERT.ZOEKEN zoekt in de eerste kolom van de tabel.",
         antwoord=True,
         uitleg="Daarom moet de kolom waarin je zoekt vooraan staan."),
    dict(type="waarofniet",
         vraag="Een geneste ALS mag maar één voorwaarde bevatten.",
         antwoord=False,
         uitleg="Juist niet: het nesten dient om meerdere voorwaarden na elkaar te testen."),
    dict(type="meerkeuze",
         vraag="Wat doet de functie HOOFDLETTERS?",
         opties=["alles in kapitalen zetten",
                 "alles klein maken ervan",
                 "de eerste letter groot maken",
                 "de tekst korter maken ervan"],
         antwoord=0,
         uitleg="KLEINE LETTERS doet het omgekeerde."),
    dict(type="meerkeuze",
         vraag="Wat geeft =LINKS(A1;3)?",
         opties=["de eerste drie tekens",
                 "de laatste drie tekens",
                 "de derde cel ervan",
                 "de derde rij ervan"],
         antwoord=0,
         uitleg="RECHTS geeft de laatste tekens."),
    dict(type="meerkeuze",
         vraag="Wat is een relatieve celverwijzing?",
         opties=["ze schuift mee bij kopiëren",
                 "ze blijft altijd staan ervan",
                 "ze verwijst naar een blad",
                 "ze verwijst naar een bestand"],
         antwoord=0,
         uitleg="Kopieer je =A1+B1 een rij lager, dan staat er =A2+B2."),
    dict(type="meerkeuze",
         vraag="Wat is waar over een absolute celverwijzing?",
         opties=["ze schuift niet mee",
                 "je schrijft ze met dollartekens",
                 "je gebruikt ze voor een vast btw-tarief",
                 "ze verandert bij elke kopie"],
         antwoord=[0, 1, 2],
         uitleg="Juist dat ze niet verandert, is het punt."),
    dict(type="meerkeuze",
         vraag="Hoe schrijf je een absolute verwijzing naar cel C2?",
         opties=["$C$2",
                 "C2$",
                 "$C2$",
                 "C$$2"],
         antwoord=0,
         uitleg="Een dollarteken voor de kolomletter en een voor het rijnummer."),
    dict(type="waarofniet",
         vraag="Een gemengde verwijzing zet de kolom of de rij vast, niet beide.",
         antwoord=True,
         uitleg="$C2 houdt de kolom vast, C$2 de rij."),
    dict(type="waarofniet",
         vraag="Dollartekens in een formule betekenen dat het om geld gaat.",
         antwoord=False,
         uitleg="Ze zetten een verwijzing vast. Geld maak je met de muntnotatie."),
    dict(type="invultekst",
         vraag="Welk teken zet een verwijzing vast in een formule? Eén woord.",
         antwoord=["dollarteken", "$", "dollar"],
         uitleg="Het dollarteken."),
    dict(type="meerkeuze",
         vraag="Waarom gebruik je een absolute verwijzing bij een btw-tarief in één cel?",
         opties=["elke formule kijkt ernaar",
                 "het tarief verandert nooit",
                 "de cel wordt beveiligd ervan",
                 "de formule rekent sneller"],
         antwoord=0,
         uitleg="Wijzigt het tarief, dan pas je één cel aan en volgen alle formules."),
    dict(type="meerkeuze",
         vraag="Welke tekstfuncties noemt de vakfiche?",
         opties=["LINKS",
                 "RECHTS",
                 "KLEINE LETTERS",
                 "AFRONDEN"],
         antwoord=[0, 1, 2],
         uitleg="AFRONDEN werkt op getallen."),
    dict(type="meerkeuze",
         vraag="Wat geeft een zoekfunctie als de waarde niet gevonden wordt?",
         opties=["een foutmelding",
                 "het getal nul ervan",
                 "een lege cel ervan",
                 "de eerste rij ervan"],
         antwoord=0,
         uitleg="Die melding kan je opvangen met een functie als ALS.FOUT."),
    dict(type="meerkeuze",
         vraag="Wanneer gebruik je ALS in een boekhoudblad?",
         opties=["korting geven boven een bedrag",
                 "een rekening kiezen naar het soort kost",
                 "betaald of niet betaald tonen",
                 "de kolommen sorteren erbij"],
         antwoord=[0, 1, 2],
         uitleg="Sorteren is geen formule maar een bewerking op het blad."),
    dict(type="invultekst",
         vraag="Welke functie kiest tussen twee uitkomsten op basis van een voorwaarde? Eén woord.",
         antwoord=["als"],
         uitleg="ALS."),
]
