# -*- coding: utf-8 -*-
"""Grafieken maken en lezen.

Van de vakfiche toegepaste economie 2DU (2027): een grafiektype kiezen bij
de boodschap, een kolom-, lijn- en staafgrafiek en een cirkeldiagram, de
grafiekelementen en de opmaak, en een grafiek met economische gegevens
kunnen uitleggen.

Deel 1 is het juiste type kiezen en de grafiek lezen.
Deel 2 zijn de elementen, de opmaak en de uitleg erbij.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is het nut van een grafiek?",
         opties=["cijfers in beeld brengen",
                 "de cijfers juister maken",
                 "de tabel korter maken ervan",
                 "de cijfers verbergen ervan"],
         antwoord=0,
         uitleg="Een beeld laat een verschil of een verloop sneller zien dan een rij getallen."),
    dict(type="meerkeuze",
         vraag="Welke grafiek gebruik je voor een evolutie in de tijd?",
         opties=["een lijngrafiek",
                 "een cirkeldiagram",
                 "een tabel ervan",
                 "een organogram"],
         antwoord=0,
         uitleg="De lijn laat zien of iets stijgt, daalt of gelijk blijft."),
    dict(type="meerkeuze",
         vraag="Welke grafiek gebruik je om delen van een geheel te tonen?",
         opties=["een cirkeldiagram",
                 "een lijngrafiek ervan",
                 "een spreidingsdiagram",
                 "een tabel met totalen"],
         antwoord=0,
         uitleg="Alle schijfjes samen zijn honderd procent."),
    dict(type="meerkeuze",
         vraag="Wat toont een kolomgrafiek?",
         opties=["waarden naast elkaar",
                 "een verloop in de tijd",
                 "delen van een geheel",
                 "de som van alles ervan"],
         antwoord=0,
         uitleg="Handig om bedragen of aantallen te vergelijken."),
    dict(type="invultekst",
         vraag="Welke grafiek gebruik je voor de omzet per maand over een jaar? Hoogstens drie woorden.",
         antwoord=["lijngrafiek", "een lijngrafiek", "lijndiagram"],
         uitleg="Een lijngrafiek: de maanden volgen elkaar op in de tijd."),
    dict(type="waarofniet",
         vraag="Een staafgrafiek heeft liggende balken, een kolomgrafiek staande.",
         antwoord=True,
         uitleg="Liggende balken zijn handig bij lange namen naast de as."),
    dict(type="waarofniet",
         vraag="Een cirkeldiagram is geschikt voor twintig categorieën.",
         antwoord=False,
         uitleg="Met te veel schijfjes leest niemand het nog. Houd het bij een handvol."),
    dict(type="meerkeuze",
         vraag="Wat staat er op de verticale as van een kolomgrafiek?",
         opties=["de waarden",
                 "de categorieën",
                 "de titel ervan",
                 "de legende ervan"],
         antwoord=0,
         uitleg="De hoogte van de kolom lees je op de verticale as af."),
    dict(type="meerkeuze",
         vraag="Wat staat er op de horizontale as van een kolomgrafiek?",
         opties=["de categorieën",
                 "de bedragen ervan",
                 "de percentages ervan",
                 "de legende ervan"],
         antwoord=0,
         uitleg="Bijvoorbeeld de maanden, de producten of de afdelingen."),
    dict(type="meerkeuze",
         vraag="Waarom moet de verticale as meestal bij nul beginnen?",
         opties=["anders lijkt het verschil groter",
                 "anders past de grafiek niet",
                 "anders klopt de legende niet",
                 "anders verdwijnt de titel ervan"],
         antwoord=0,
         uitleg="Een as die bij 90 begint, maakt van een klein verschil een hoge berg."),
    dict(type="meerkeuze",
         vraag="Wat maakt een grafiek misleidend?",
         opties=["een as die niet bij nul begint",
                 "een as met ongelijke stappen",
                 "een stuk uit de reeks weglaten",
                 "de bron van de cijfers vermelden"],
         antwoord=[0, 1, 2],
         uitleg="De bron vermelden maakt een grafiek juist betrouwbaar."),
    dict(type="meerkeuze",
         vraag="Welke grafiek kies je om twee jaren naast elkaar te zetten?",
         opties=["een kolomgrafiek",
                 "een cirkeldiagram ervan",
                 "een spreidingsdiagram",
                 "een lijngrafiek met één lijn"],
         antwoord=0,
         uitleg="Twee kolommen per categorie, één per jaar."),
    dict(type="waarofniet",
         vraag="Een grafiek zonder titel laat de lezer gissen waarover ze gaat.",
         antwoord=True,
         uitleg="De titel zegt wat er gemeten is en over welke periode."),
    dict(type="waarofniet",
         vraag="Een grafiek maakt de cijfers nauwkeuriger dan een tabel.",
         antwoord=False,
         uitleg="Een grafiek toont een beeld, een tabel de exacte waarden."),
    dict(type="invultekst",
         vraag="Hoe noem je het kader dat uitlegt welke kleur bij welke reeks hoort? Eén woord.",
         antwoord=["legende", "de legende", "legenda"],
         uitleg="De legende."),
    dict(type="meerkeuze",
         vraag="Wat is een gegevensreeks in een grafiek?",
         opties=["één rij met waarden",
                 "de titel van de grafiek",
                 "de kleur van de balken",
                 "de naam van de as ervan"],
         antwoord=0,
         uitleg="Bijvoorbeeld de omzet van 2026; een tweede reeks is die van 2027."),
    dict(type="meerkeuze",
         vraag="Welke grafiektypes noemt de vakfiche?",
         opties=["de kolomgrafiek",
                 "de lijngrafiek",
                 "het cirkeldiagram",
                 "het organogram"],
         antwoord=[0, 1, 2],
         uitleg="Een organogram is geen grafiek van cijfers maar een schema."),
    dict(type="meerkeuze",
         vraag="Wat zegt een dalende lijn over de omzet?",
         opties=["de omzet neemt af",
                 "de omzet neemt toe",
                 "de omzet blijft gelijk",
                 "de omzet is onbekend"],
         antwoord=0,
         uitleg="Hoe steiler de lijn daalt, hoe sneller de omzet terugloopt."),
    dict(type="meerkeuze",
         vraag="Wat moet een lezer uit je grafiek kunnen halen?",
         opties=["wat er gemeten is",
                 "in welke eenheid",
                 "over welke periode",
                 "wie de grafiek gemaakt heeft"],
         antwoord=[0, 1, 2],
         uitleg="De maker hoeft er niet op; de bron van de cijfers wel."),
    dict(type="invultekst",
         vraag="Hoe noem je de grafiek met staande balken? Hoogstens drie woorden.",
         antwoord=["kolomgrafiek", "een kolomgrafiek", "kolomdiagram"],
         uitleg="Een kolomgrafiek."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is een grafiekelement?",
         opties=["een onderdeel van de grafiek",
                 "een cel van het rekenblad",
                 "een rij met getallen ervan",
                 "een kleur uit het palet"],
         antwoord=0,
         uitleg="De titel, de assen, de legende, de rasterlijnen en de labels."),
    dict(type="meerkeuze",
         vraag="Welke grafiekelementen kan je aan of uit zetten?",
         opties=["de titel",
                 "de legende",
                 "de gegevenslabels",
                 "de formules"],
         antwoord=[0, 1, 2],
         uitleg="Formules staan in het blad, niet in de grafiek."),
    dict(type="meerkeuze",
         vraag="Wat is een gegevenslabel?",
         opties=["de waarde bij de balk",
                 "de naam van de as ervan",
                 "de kleur van de balk",
                 "de titel van de grafiek"],
         antwoord=0,
         uitleg="Zet het getal erbij als de precieze waarde telt."),
    dict(type="meerkeuze",
         vraag="Waarom zet je rasterlijnen in een grafiek?",
         opties=["de hoogte beter aflezen",
                 "de grafiek vullen ervan",
                 "de kleuren scheiden ervan",
                 "de titel groter maken"],
         antwoord=0,
         uitleg="Je oog volgt de lijn naar de as en leest de waarde af."),
    dict(type="invultekst",
         vraag="Hoe noem je het getal dat bij een balk geschreven wordt? Hoogstens drie woorden.",
         antwoord=["gegevenslabel", "een gegevenslabel", "label"],
         uitleg="Een gegevenslabel."),
    dict(type="waarofniet",
         vraag="Een grafiek in een rekenblad verandert mee als je de cijfers aanpast.",
         antwoord=True,
         uitleg="De grafiek kijkt naar het bereik; wijzigt een cel, dan beweegt de balk."),
    dict(type="waarofniet",
         vraag="Een grafiek bewaart haar eigen kopie van de cijfers en volgt het blad niet.",
         antwoord=False,
         uitleg="Ze volgt het blad wel; dat is net het nut ervan."),
    dict(type="meerkeuze",
         vraag="Wat is de astitel in een grafiek?",
         opties=["wat de as meet",
                 "de titel bovenaan",
                 "de naam van de reeks",
                 "de kleur van de as"],
         antwoord=0,
         uitleg="Bijvoorbeeld omzet in euro, of aantal stuks."),
    dict(type="meerkeuze",
         vraag="Waar kies je een grafiektype op?",
         opties=["naar je boodschap",
                 "naar de kleur ervan",
                 "naar het aantal cellen",
                 "naar de plaats op het blad"],
         antwoord=0,
         uitleg="Verloop in de tijd wordt een lijn, delen van een geheel een cirkel, vergelijken kolommen."),
    dict(type="meerkeuze",
         vraag="Wat betekent een piek in een lijngrafiek van de verkoop?",
         opties=["een maand met veel verkoop",
                 "een maand zonder verkoop",
                 "een fout in de formule",
                 "een lege cel in het blad"],
         antwoord=0,
         uitleg="Zoek er dan een verklaring bij: een actie, een feestdag, een grote klant."),
    dict(type="meerkeuze",
         vraag="Wat zet je bij een grafiek met cijfers van iemand anders?",
         opties=["de bron",
                 "de kleur ervan",
                 "de titel ervan",
                 "de legende ervan"],
         antwoord=0,
         uitleg="Waar de cijfers vandaan komen, en van welk jaar ze zijn."),
    dict(type="meerkeuze",
         vraag="Waarvoor dient een grafiek met twee reeksen naast elkaar?",
         opties=["een vergelijking",
                 "een cirkeldiagram",
                 "een enkele reeks",
                 "een lijst met cellen"],
         antwoord=0,
         uitleg="Twee jaren, twee afdelingen of begroot tegenover werkelijk."),
    dict(type="waarofniet",
         vraag="Een grafiek bij een jaarrekening maakt een evolutie meteen zichtbaar.",
         antwoord=True,
         uitleg="Daarom staan er in een jaarverslag grafieken naast de tabellen."),
    dict(type="waarofniet",
         vraag="Een cirkeldiagram kan percentages boven honderd tonen.",
         antwoord=False,
         uitleg="De hele cirkel is honderd procent. Komt je som hoger uit, dan zit er een fout in."),
    dict(type="invultekst",
         vraag="Hoe noem je de lijnen achter de grafiek die helpen aflezen? Hoogstens drie woorden.",
         antwoord=["rasterlijnen", "rasterlijn", "de rasterlijnen"],
         uitleg="De rasterlijnen."),
    dict(type="meerkeuze",
         vraag="Wat vertelt een cirkeldiagram van de kosten van een zaak?",
         opties=["het aandeel per kost",
                 "het verloop per maand",
                 "het verschil met vorig jaar",
                 "het totaal in euro ervan"],
         antwoord=0,
         uitleg="Welk deel van de kosten naar lonen, huur of aankopen gaat."),
    dict(type="meerkeuze",
         vraag="Wat doe je om een grafiek leesbaar te houden?",
         opties=["een duidelijke titel geven",
                 "de eenheid bij de as zetten",
                 "niet te veel reeksen tonen",
                 "zo veel kleuren mogelijk gebruiken"],
         antwoord=[0, 1, 2],
         uitleg="Veel kleuren maken het drukker, niet duidelijker."),
    dict(type="meerkeuze",
         vraag="Wat lees je af als twee kolommen bijna even hoog zijn?",
         opties=["de waarden liggen dicht",
                 "de waarden zijn gelijk",
                 "er is een fout gemaakt",
                 "de as begint niet bij nul"],
         antwoord=0,
         uitleg="Bijna even hoog is niet gelijk. Kijk naar de labels voor het echte verschil."),
    dict(type="meerkeuze",
         vraag="Wat kan je uitleggen bij een grafiek van de omzet?",
         opties=["in welke maanden het goed ging",
                 "of de omzet stijgt of daalt",
                 "welke maand het hoogst is",
                 "hoeveel winst er gemaakt is"],
         antwoord=[0, 1, 2],
         uitleg="Winst zie je niet in een omzetgrafiek: daarvoor moet je ook de kosten kennen."),
    dict(type="invultekst",
         vraag="Hoe noem je het woord dat zegt wat een as meet? Hoogstens drie woorden.",
         antwoord=["astitel", "de astitel", "asnaam"],
         uitleg="De astitel."),
]
