# -*- coding: utf-8 -*-
"""Het MAR en het redeneerschema.

Van de vakfiche toegepaste economie 2DU (2027): het efficiënt gebruiken van
het minimum algemeen rekeningstelsel, dat je op het examen ter beschikking
krijgt, en het registreren van verrichtingen volgens het redeneerschema.

Deel 1 is het MAR met zijn zeven klassen.
Deel 2 is het redeneerschema in de praktijk.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Waar staat de afkorting MAR voor?",
         opties=["minimum algemeen rekeningstelsel",
                 "maandelijkse aangifte van rekeningen",
                 "model voor administratieve registratie",
                 "manier om artikelen te registreren"],
         antwoord=0,
         uitleg="Een vaste lijst van rekeningen met hun nummer. Je krijgt hem op het examen."),
    dict(type="meerkeuze",
         vraag="Hoeveel klassen telt het MAR?",
         opties=["7",
                 "5 in totaal",
                 "9 in totaal",
                 "10 in totaal"],
         antwoord=0,
         uitleg="Zeven klassen, genummerd van 1 tot en met 7."),
    dict(type="meerkeuze",
         vraag="Wat staat er in klasse 6 van het MAR?",
         opties=["de kosten",
                 "de opbrengsten ervan",
                 "de voorraden ervan",
                 "de liquide middelen"],
         antwoord=0,
         uitleg="Klasse 6 zijn de kosten, klasse 7 de opbrengsten."),
    dict(type="meerkeuze",
         vraag="Wat staat er in klasse 7 van het MAR?",
         opties=["de opbrengsten",
                 "de kosten ervan",
                 "de schulden ervan",
                 "de vaste activa"],
         antwoord=0,
         uitleg="Daar staan onder meer de verkopen van handelsgoederen."),
    dict(type="invultekst",
         vraag="In welke klasse van het MAR staan de voorraden? Een getal.",
         antwoord=["3", "klasse 3", "drie"],
         uitleg="Klasse 3: voorraden en bestellingen in uitvoering."),
    dict(type="waarofniet",
         vraag="Je krijgt het MAR op het examen ter beschikking.",
         antwoord=True,
         uitleg="Je moet de nummers dus niet uit het hoofd kennen, maar wel vlot kunnen opzoeken."),
    dict(type="waarofniet",
         vraag="Je moet alle rekeningnummers van het MAR uit het hoofd leren.",
         antwoord=False,
         uitleg="Je krijgt het MAR. Wat telt, is dat je er snel de juiste rekening in vindt."),
    dict(type="meerkeuze",
         vraag="Wat staat er in klasse 5 van het MAR?",
         opties=["geldbeleggingen en liquide middelen",
                 "de vorderingen op lange termijn ervan",
                 "de kosten van het boekjaar ervan",
                 "de voorraad handelsgoederen ervan"],
         antwoord=0,
         uitleg="Daar vind je de kas en de bankrekening."),
    dict(type="meerkeuze",
         vraag="Welke klassen van het MAR horen bij de balans?",
         opties=["klasse 1",
                 "klasse 2",
                 "klasse 5",
                 "klasse 7"],
         antwoord=[0, 1, 2],
         uitleg="Klassen 1 tot 5 staan op de balans, klassen 6 en 7 in de resultatenrekening."),
    dict(type="meerkeuze",
         vraag="Welke rekening gebruik je voor de aankoop van handelsgoederen?",
         opties=["604 Aankopen handelsgoederen",
                 "700 Verkopen handelsgoederen ervan",
                 "440 Leveranciers van de zaak",
                 "400 Handelsdebiteuren ervan"],
         antwoord=0,
         uitleg="Een rekening uit klasse 6, want een aankoop van handelsgoederen is een kost."),
    dict(type="meerkeuze",
         vraag="Welke rekening gebruik je voor een verkoop van handelsgoederen?",
         opties=["700 Verkopen handelsgoederen",
                 "604 Aankopen handelsgoederen ervan",
                 "400 Handelsdebiteuren ervan",
                 "550 Kredietinstellingen ervan"],
         antwoord=0,
         uitleg="Klasse 7, want een verkoop is een opbrengst."),
    dict(type="meerkeuze",
         vraag="Wat betekent de rekening 400 Handelsdebiteuren?",
         opties=["wat klanten nog moeten betalen",
                 "wat je de leverancier schuldig bent",
                 "het geld op de bankrekening ervan",
                 "de voorraad in het magazijn ervan"],
         antwoord=0,
         uitleg="Een vordering op een klant, dus een vlottend actief."),
    dict(type="waarofniet",
         vraag="De rekening 440 Leveranciers is een schuld van de onderneming.",
         antwoord=True,
         uitleg="Ze staat in klasse 4, bij de schulden op ten hoogste één jaar."),
    dict(type="waarofniet",
         vraag="Klasse 2 van het MAR bevat de kosten.",
         antwoord=False,
         uitleg="Klasse 2 zijn de vaste activa. De kosten staan in klasse 6."),
    dict(type="invultekst",
         vraag="In welke klasse van het MAR staat de kasrekening? Een getal.",
         antwoord=["5", "klasse 5", "vijf"],
         uitleg="Klasse 5: geldbeleggingen en liquide middelen."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over het MAR zijn juist?",
         opties=["klasse 6 zijn de kosten",
                 "klasse 7 zijn de opbrengsten",
                 "klassen 1 tot 5 staan op de balans",
                 "er zijn tien klassen"],
         antwoord=[0, 1, 2],
         uitleg="Zeven klassen, geen tien."),
    dict(type="meerkeuze",
         vraag="Waarom werkt iedereen met hetzelfde rekeningstelsel?",
         opties=["zo zijn cijfers vergelijkbaar",
                 "zo zijn de nummers korter ervan",
                 "zo verdient de zaak meer geld",
                 "zo moet je minder boeken ervan"],
         antwoord=0,
         uitleg="De fiscus, de bank en de boekhouder lezen dan dezelfde taal."),
    dict(type="meerkeuze",
         vraag="Wat staat er in klasse 4 van het MAR?",
         opties=["vorderingen en schulden op korte termijn",
                 "de voorraden en bestellingen in uitvoering",
                 "de kosten en de opbrengsten van het jaar",
                 "het eigen vermogen van de onderneming"],
         antwoord=0,
         uitleg="Klanten en leveranciers vind je daar, net als de btw-rekeningen."),
    dict(type="meerkeuze",
         vraag="Welke rekeningen vind je in klasse 4?",
         opties=["400 Handelsdebiteuren",
                 "440 Leveranciers",
                 "de btw-rekeningen",
                 "604 Aankopen handelsgoederen"],
         antwoord=[0, 1, 2],
         uitleg="604 staat in klasse 6, bij de kosten."),
    dict(type="invultekst",
         vraag="In welke klasse van het MAR staan de opbrengsten? Een getal.",
         antwoord=["7", "klasse 7", "zeven"],
         uitleg="Klasse 7."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is de eerste vraag in het redeneerschema?",
         opties=["welke rekeningen spelen mee",
                 "hoeveel bedraagt de btw ervan",
                 "wie heeft de factuur gemaakt",
                 "wanneer wordt er betaald ervan"],
         antwoord=0,
         uitleg="Eerst de betrokken rekeningen, dan of ze stijgen of dalen, dan debet of credit."),
    dict(type="meerkeuze",
         vraag="Een onderneming koopt handelsgoederen op krediet. Welke rekening gaat in debet?",
         opties=["604 Aankopen handelsgoederen",
                 "440 Leveranciers van de zaak",
                 "700 Verkopen handelsgoederen",
                 "550 Kredietinstellingen ervan"],
         antwoord=0,
         uitleg="De kost stijgt, dus debet. De schuld aan de leverancier komt in credit."),
    dict(type="meerkeuze",
         vraag="Welke rekening komt bij een aankoop op krediet in credit?",
         opties=["440 Leveranciers",
                 "604 Aankopen handelsgoederen",
                 "400 Handelsdebiteuren ervan",
                 "570 Kassen van de zaak"],
         antwoord=0,
         uitleg="De schuld aan de leverancier stijgt, en een schuld stijgt in credit."),
    dict(type="meerkeuze",
         vraag="Een klant betaalt zijn factuur via de bank. Wat gebeurt er?",
         opties=["de bank stijgt, de klant daalt",
                 "de bank daalt, de klant stijgt",
                 "de voorraad daalt in waarde",
                 "de schuld aan de leverancier daalt"],
         antwoord=0,
         uitleg="550 in debet, 400 in credit. De vordering verdwijnt omdat ze betaald is."),
    dict(type="invultekst",
         vraag="Komt een kost die stijgt in debet of in credit? Eén woord.",
         antwoord=["debet"],
         uitleg="In debet. Kosten en bezittingen stijgen links."),
    dict(type="waarofniet",
         vraag="Een schuld stijgt in credit.",
         antwoord=True,
         uitleg="Passief, kosten en opbrengsten volgen elk hun eigen kant. Een schuld hoort rechts."),
    dict(type="waarofniet",
         vraag="Een opbrengst stijgt in debet.",
         antwoord=False,
         uitleg="Opbrengsten stijgen in credit, net als schulden en eigen vermogen."),
    dict(type="meerkeuze",
         vraag="Waar staat de letter A voor in het redeneerschema?",
         opties=["actief",
                 "aankoop ervan",
                 "afschrijving ervan",
                 "aangifte ervan"],
         antwoord=0,
         uitleg="A staat voor actief, P voor passief, K voor kosten en O voor opbrengsten."),
    dict(type="meerkeuze",
         vraag="Wat gebeurt er met de kas als de zaak contant betaalt?",
         opties=["ze daalt",
                 "ze stijgt ervan",
                 "ze blijft gelijk",
                 "ze verdwijnt ervan"],
         antwoord=0,
         uitleg="Een actief dat daalt, komt in credit. De kost of de schuld staat dan in debet."),
    dict(type="meerkeuze",
         vraag="Wat moet juist zijn om punten te krijgen voor een regel van het redeneerschema?",
         opties=["het rekeningnummer",
                 "het bedrag",
                 "de kant, debet of credit",
                 "de soort rekening, A of P"],
         antwoord=[0, 1, 2],
         uitleg="De soort rekening mag je invullen om te redeneren, maar ze wordt niet beoordeeld."),
    dict(type="meerkeuze",
         vraag="Waarom verschijnt de naam van de rekening vanzelf op het examen?",
         opties=["je vult het nummer in",
                 "je typt de naam zelf voluit",
                 "de naam staat in de vraag ervan",
                 "de naam wordt niet gevraagd ervan"],
         antwoord=0,
         uitleg="Daarom telt het nummer, niet de spelling van de naam."),
    dict(type="meerkeuze",
         vraag="Een zaak verkoopt handelsgoederen op krediet. Welke rekening gaat in debet?",
         opties=["400 Handelsdebiteuren",
                 "700 Verkopen handelsgoederen",
                 "440 Leveranciers van de zaak",
                 "604 Aankopen handelsgoederen"],
         antwoord=0,
         uitleg="De vordering op de klant stijgt. De opbrengst 700 staat in credit."),
    dict(type="waarofniet",
         vraag="Bij een verkoop op krediet staat de opbrengst in credit.",
         antwoord=True,
         uitleg="De vordering op de klant staat tegenover die opbrengst, in debet."),
    dict(type="waarofniet",
         vraag="Het bedrag in debet mag verschillen van het bedrag in credit.",
         antwoord=False,
         uitleg="Elke boeking is in evenwicht. Is ze dat niet, dan zit er een fout in."),
    dict(type="invultekst",
         vraag="Welke kant kiest een actief dat stijgt? Eén woord.",
         antwoord=["debet"],
         uitleg="Debet. Een actief dat daalt, komt in credit."),
    dict(type="meerkeuze",
         vraag="Wat doe je voor je een factuur boekt?",
         opties=["het document lezen",
                 "nagaan wat er gebeurd is",
                 "de bedragen controleren",
                 "de balans opnieuw maken"],
         antwoord=[0, 1, 2],
         uitleg="Eerst begrijpen wat er gebeurd is, dan pas het redeneerschema invullen."),
    dict(type="meerkeuze",
         vraag="Hoe boek je zo efficiënt mogelijk?",
         opties=["met zo weinig mogelijk regels",
                 "met zo veel mogelijk regels ervan",
                 "met een regel per euro ervan",
                 "met twee boekingen per factuur"],
         antwoord=0,
         uitleg="De fiche vraagt uitdrukkelijk een minimum aantal boekingsregels."),
    dict(type="meerkeuze",
         vraag="Welke verrichtingen raken de rekening 550 Kredietinstellingen?",
         opties=["een klant betaalt via overschrijving",
                 "je betaalt een leverancier via de bank",
                 "de bank rekent kosten aan",
                 "je koopt goederen op krediet aan"],
         antwoord=[0, 1, 2],
         uitleg="Een aankoop op krediet raakt de bank pas op het moment dat je betaalt."),
    dict(type="meerkeuze",
         vraag="Wat geldt er voor de totalen van een boeking?",
         opties=["debet en credit zijn gelijk",
                 "debet is altijd groter ervan",
                 "credit is altijd groter ervan",
                 "de totalen worden niet geteld"],
         antwoord=0,
         uitleg="Op het examen worden ze automatisch berekend. Een verschil kost geen punten, maar wijst wel op een fout."),
    dict(type="invultekst",
         vraag="Welke letter gebruik je in het redeneerschema voor een kost? Eén letter.",
         antwoord=["K", "k"],
         uitleg="K van kosten. O staat voor opbrengsten."),
]
