# -*- coding: utf-8 -*-
"""Verkoopverrichtingen en hun documenten.

Van de vakfiche toegepaste economie 2DU (2027): de rol van de
verkoopdocumenten (prijsaanvraag, offerte, bestelbon, leverbon,
verkoopfactuur en uitgaande creditnota) en het berekenen van het bedrag van
een verkoopfactuur met handelskorting, financiële korting, doorgerekende
kosten, terugstuurbare verpakking en meerdere btw-tarieven.

Deel 1 is de documentenstroom van een verkoop.
Deel 2 is het berekenen van een verkoopfactuur.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wie stuurt de verkoopfactuur?",
         opties=["de verkoper",
                 "de klant ervan",
                 "de bank ervan",
                 "de vervoerder ervan"],
         antwoord=0,
         uitleg="Dezelfde factuur is bij de verkoper een verkoopfactuur en bij de koper een aankoopfactuur."),
    dict(type="meerkeuze",
         vraag="Wat doet de verkoper met een prijsaanvraag?",
         opties=["hij maakt een offerte",
                 "hij stuurt meteen een factuur",
                 "hij levert de goederen al",
                 "hij betaalt de klant ervan"],
         antwoord=0,
         uitleg="In de offerte zet hij prijs, hoeveelheid en voorwaarden."),
    dict(type="meerkeuze",
         vraag="Wanneer maakt de verkoper een leverbon?",
         opties=["bij de levering",
                 "bij de bestelling ervan",
                 "bij de betaling ervan",
                 "bij de aangifte ervan"],
         antwoord=0,
         uitleg="Ze gaat mee met de goederen en wordt bij ontvangst getekend."),
    dict(type="meerkeuze",
         vraag="Wanneer stuurt de verkoper een uitgaande creditnota?",
         opties=["als de klant terugstuurt",
                 "als de klant bijbestelt ervan",
                 "als de klant snel betaalt ervan",
                 "als de klant niets doet ervan"],
         antwoord=0,
         uitleg="Of bij een fout op de factuur, of bij een vergeten korting."),
    dict(type="invultekst",
         vraag="Hoe heet dezelfde factuur bij de koper? Hoogstens drie woorden.",
         antwoord=["aankoopfactuur", "de aankoopfactuur"],
         uitleg="De aankoopfactuur. Hetzelfde papier, een andere kant van de verrichting."),
    dict(type="waarofniet",
         vraag="Een verkoopfactuur levert de verkoper een opbrengst op.",
         antwoord=True,
         uitleg="De opbrengst staat in klasse 7, de vordering op de klant in klasse 4."),
    dict(type="waarofniet",
         vraag="De verkoper mag pas leveren nadat de klant betaald heeft.",
         antwoord=False,
         uitleg="Bij verkoop op krediet gebeurt de levering eerst en volgt de betaling later."),
    dict(type="meerkeuze",
         vraag="Wat is een vordering op een klant?",
         opties=["geld dat je nog krijgt",
                 "geld dat je nog betaalt ervan",
                 "geld dat in de kas zit ervan",
                 "geld van de bank geleend ervan"],
         antwoord=0,
         uitleg="Een vlottend actief, bij de handelsdebiteuren."),
    dict(type="meerkeuze",
         vraag="Welke documenten maakt de verkoper zelf?",
         opties=["de offerte",
                 "de leverbon",
                 "de verkoopfactuur",
                 "de btw-aangifte van de klant"],
         antwoord=[0, 1, 2],
         uitleg="Elke btw-plichtige doet zijn eigen aangifte."),
    dict(type="meerkeuze",
         vraag="Waarom nummert een verkoper zijn facturen doorlopend?",
         opties=["zo ontbreekt er geen",
                 "zo verkoopt hij er meer",
                 "zo betaalt hij minder btw",
                 "zo gaat het leveren vlotter"],
         antwoord=0,
         uitleg="Een doorlopende nummering maakt een ontbrekende factuur meteen zichtbaar."),
    dict(type="meerkeuze",
         vraag="Wat gebeurt er bij een verkoop met de voorraad?",
         opties=["ze vermindert",
                 "ze vermeerdert ervan",
                 "ze blijft gelijk ervan",
                 "ze verdwijnt helemaal"],
         antwoord=0,
         uitleg="De goederen gaan naar de klant."),
    dict(type="meerkeuze",
         vraag="Wat betekent een betaling op dertig dagen?",
         opties=["de klant betaalt later",
                 "de klant betaalt contant",
                 "de klant krijgt korting ervan",
                 "de klant betaalt vooraf ervan"],
         antwoord=0,
         uitleg="Een betaaltermijn. De verkoper heeft ondertussen een vordering op de klant."),
    dict(type="waarofniet",
         vraag="Een verkoopfactuur vermeldt het btw-nummer van de verkoper.",
         antwoord=True,
         uitleg="Dat is een wettelijke vermelding, net als de datum en het factuurnummer."),
    dict(type="waarofniet",
         vraag="Een offerte en een factuur zijn hetzelfde document.",
         antwoord=False,
         uitleg="Een offerte is een voorstel. Een factuur is de vraag om te betalen."),
    dict(type="invultekst",
         vraag="Hoe noem je het document waarmee de verkoper een factuur rechtzet? Hoogstens drie woorden.",
         antwoord=["creditnota", "een creditnota", "uitgaande creditnota"],
         uitleg="De uitgaande creditnota."),
    dict(type="meerkeuze",
         vraag="Wat staat er op een verkoopfactuur?",
         opties=["het factuurnummer",
                 "de datum",
                 "de btw-nummers",
                 "de kleur van de doos"],
         antwoord=[0, 1, 2],
         uitleg="Wettelijke vermeldingen. De verpakking doet er niet toe."),
    dict(type="meerkeuze",
         vraag="Waarom houdt een verkoper een kopie van elke factuur bij?",
         opties=["als bewijs",
                 "om later te leveren",
                 "om de klant te bellen",
                 "om reclame te maken"],
         antwoord=0,
         uitleg="De wet vraagt dat facturen een aantal jaren bewaard blijven."),
    dict(type="meerkeuze",
         vraag="Wat gebeurt er als een klant niet betaalt?",
         opties=["de vordering blijft openstaan",
                 "de factuur verdwijnt vanzelf",
                 "de btw vervalt dan ervan",
                 "de voorraad komt terug ervan"],
         antwoord=0,
         uitleg="Ze blijft bij de handelsdebiteuren staan tot ze betaald of afgeboekt wordt."),
    dict(type="meerkeuze",
         vraag="Welke stappen doorloopt een verkoop?",
         opties=["de offerte maken",
                 "de goederen leveren",
                 "de factuur sturen",
                 "de btw-aangifte van de klant invullen"],
         antwoord=[0, 1, 2],
         uitleg="De klant zorgt zelf voor zijn aangifte."),
    dict(type="invultekst",
         vraag="Hoe noem je in de boekhouding wat klanten nog moeten betalen? Hoogstens drie woorden.",
         antwoord=["handelsdebiteuren", "de handelsdebiteuren", "vorderingen"],
         uitleg="De handelsdebiteuren, rekening 400."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Waarop berekent de verkoper de btw?",
         opties=["op het bedrag na korting",
                 "op het bedrag voor korting",
                 "op de winst van de verkoop",
                 "op het bedrag met btw erin"],
         antwoord=0,
         uitleg="Eerst de kortingen eraf, dan de doorgerekende kosten erbij, en pas dan de btw."),
    dict(type="meerkeuze",
         vraag="Een verkoop van 2000 euro krijgt 5 procent handelskorting. Wat blijft er over?",
         opties=["1900 euro",
                 "100 euro ervan",
                 "1950 euro ervan",
                 "2100 euro samen"],
         antwoord=0,
         uitleg="5 procent van 2000 is 100, en 2000 min 100 is 1900."),
    dict(type="meerkeuze",
         vraag="Hoeveel btw aan 21 procent komt er op 1900 euro?",
         opties=["399 euro",
                 "190 euro ervan",
                 "219 euro ervan",
                 "421 euro ervan"],
         antwoord=0,
         uitleg="1900 maal 0,21 is 399 euro."),
    dict(type="meerkeuze",
         vraag="Wat zijn doorgerekende kosten op een verkoopfactuur?",
         opties=["kosten die de klant betaalt",
                 "kosten die de verkoper draagt",
                 "kosten van de bank ervan",
                 "kosten van het personeel"],
         antwoord=0,
         uitleg="Vervoer bijvoorbeeld. Ze verhogen het bedrag waarop de btw berekend wordt."),
    dict(type="invultekst",
         vraag="Hoeveel is 10 procent handelskorting op 500 euro? Een getal.",
         antwoord=["50", "50 euro"],
         uitleg="500 gedeeld door 10 is 50 euro."),
    dict(type="waarofniet",
         vraag="Terugstuurbare verpakking telt niet mee in de maatstaf van heffing.",
         antwoord=True,
         uitleg="Ze is een waarborg die je terugkrijgt, dus er komt geen btw op."),
    dict(type="waarofniet",
         vraag="De verkoper mag de btw houden die hij int.",
         antwoord=False,
         uitleg="Hij int ze voor de staat en stort ze door via zijn btw-aangifte."),
    dict(type="meerkeuze",
         vraag="Wat is de verschuldigde btw voor een verkoper?",
         opties=["de btw op zijn verkopen",
                 "de btw op zijn aankopen ervan",
                 "het verschil met de winst ervan",
                 "de btw van zijn leverancier"],
         antwoord=0,
         uitleg="De btw die hij aanrekende aan zijn klanten en moet doorstorten."),
    dict(type="meerkeuze",
         vraag="Wat betekent 2 procent korting bij betaling binnen acht dagen?",
         opties=["korting als je snel betaalt",
                 "korting bij een grote bestelling",
                 "korting op het vervoer ervan",
                 "korting bij een terugzending"],
         antwoord=0,
         uitleg="Een financiële korting. Ze gaat van de factuur af voor de btw berekend wordt."),
    dict(type="meerkeuze",
         vraag="Wat verhoogt het bedrag van een verkoopfactuur?",
         opties=["doorgerekend vervoer",
                 "verpakking die niet terugkomt",
                 "de btw",
                 "een handelskorting"],
         antwoord=[0, 1, 2],
         uitleg="Een korting verlaagt het bedrag juist."),
    dict(type="meerkeuze",
         vraag="Een factuur telt 600 euro aan 6 procent en 400 euro aan 21 procent. Hoeveel btw is dat samen?",
         opties=["120 euro",
                 "210 euro ervan",
                 "60 euro ervan",
                 "270 euro ervan"],
         antwoord=0,
         uitleg="36 euro plus 84 euro is 120 euro."),
    dict(type="meerkeuze",
         vraag="Wat doet een uitgaande creditnota met de omzet?",
         opties=["ze verlaagt de omzet",
                 "ze verhoogt de omzet ervan",
                 "ze laat de omzet gelijk",
                 "ze verdubbelt de omzet"],
         antwoord=0,
         uitleg="De verkoop wordt deels of helemaal teruggedraaid."),
    dict(type="waarofniet",
         vraag="Op een creditnota staat ook een btw-bedrag.",
         antwoord=True,
         uitleg="De btw op het teruggedraaide bedrag gaat mee terug."),
    dict(type="waarofniet",
         vraag="De handelskorting staat los van het btw-bedrag.",
         antwoord=False,
         uitleg="Ze verlaagt de maatstaf, dus wordt ook de btw kleiner."),
    dict(type="invultekst",
         vraag="Hoeveel betaalt een klant voor 500 euro goederen met 6 procent btw? Een getal.",
         antwoord=["530", "530 euro"],
         uitleg="500 plus 30 euro btw is 530 euro."),
    dict(type="meerkeuze",
         vraag="Wat is de maatstaf van heffing?",
         opties=["het bedrag waarop btw komt",
                 "het bedrag met de btw erbij",
                 "de winst van de verkoper ervan",
                 "het tarief van de btw ervan"],
         antwoord=0,
         uitleg="Het bedrag na kortingen en met de doorgerekende kosten erbij."),
    dict(type="meerkeuze",
         vraag="Welke kortingen kent de vakfiche bij een verkoopfactuur?",
         opties=["de handelskorting",
                 "de financiële korting",
                 "een korting bij een grote bestelling",
                 "een korting op het btw-tarief"],
         antwoord=[0, 1, 2],
         uitleg="Het btw-tarief ligt wettelijk vast, daar geef je geen korting op."),
    dict(type="meerkeuze",
         vraag="Waarom berekent de verkoper de btw per tarief apart?",
         opties=["de tarieven verschillen",
                 "de klanten verschillen ervan",
                 "de leveranciers verschillen",
                 "de betaaldagen verschillen"],
         antwoord=0,
         uitleg="6 procent voor het ene artikel, 21 procent voor het andere, op dezelfde factuur."),
    dict(type="meerkeuze",
         vraag="Welke gegevens heb je nodig om een verkoopfactuur te berekenen?",
         opties=["de hoeveelheid",
                 "de eenheidsprijs",
                 "het btw-tarief",
                 "de naam van de vervoerder"],
         antwoord=[0, 1, 2],
         uitleg="En de kortingen die afgesproken zijn."),
    dict(type="invultekst",
         vraag="Hoeveel bedraagt 21 procent btw op 100 euro? Een getal.",
         antwoord=["21", "21 euro"],
         uitleg="21 euro. Handig om snel mee te schatten."),
]
