# -*- coding: utf-8 -*-
"""Adjectives, adverbs, comparatives en voorzetsels.

De vakfiche geeft bij dit onderdeel zelf een voorbeeld: "In het Engels hoor
en/of zie je meestal een duidelijk verschil tussen bijvoeglijke naamwoorden
en bijwoorden. Dat kan bepalend zijn voor de betekenis van een zin. Vergelijk:
this is a lot of hard work / she has worked hard / he has hardly worked."
Die drie zinnen staan ook in deel 1.

Uit de tabel met woordsoorten horen hier bij:

    bijvoeglijke naamwoorden  plaats in de zin, vergrotende en overtreffende trap
    bijwoorden                frequente bijwoorden op -ly
    voorzetsels               frequente voorzetsels en voorzetselgroepen

Deel 1 gaat over het verschil tussen een bijvoeglijk naamwoord en een
bijwoord, en over waar ze in de zin staan. Deel 2 gaat over vergelijken en
over de voorzetsels.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Waar staat een bijvoeglijk naamwoord in het Engels meestal?",
         opties=["voor het naamwoord", "achter het naamwoord", "achteraan de zin", "voor het werkwoord"],
         antwoord=0,
         uitleg="A red car, niet a car red. Achter het naamwoord staat het alleen na koppelwerkwoorden: the car is red."),
    dict(type="waarofniet",
         vraag="Een bijvoeglijk naamwoord blijft in het Engels hetzelfde, ook als het naamwoord meervoud is.",
         antwoord=True,
         uitleg="Two red cars, niet two reds cars. In het Nederlands verandert het soms wel: een rode auto, twee rode auto's."),
    dict(type="meerkeuze",
         vraag="Welke volgorde is juist?",
         opties=["a lovely big red balloon", "a red big lovely balloon", "a big lovely red balloon", "a red lovely big balloon"],
         antwoord=0,
         uitleg="Eerst je mening, dan de grootte, dan de leeftijd en de vorm, en pas daarna de kleur. Meestal stapel je er hoogstens twee of drie op elkaar."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn bijwoorden?",
         opties=["quickly", "carefully", "easily", "careful"],
         antwoord=[0, 1, 2],
         uitleg="Careful is het bijvoeglijk naamwoord, carefully het bijwoord. Een y na een medeklinker wordt ily: easy wordt easily."),
    dict(type="invultekst",
         vraag="Maak het bijwoord bij 'happy'.",
         antwoord=["happily"],
         uitleg="De y wordt i en er komt ly bij. Zo ook bij angry en angrily."),
    dict(type="invultekst",
         vraag="Maak het bijwoord bij 'terrible'.",
         antwoord=["terribly"],
         uitleg="Bij woorden op -le valt de e weg: terrible wordt terribly, simple wordt simply."),
    dict(type="meerkeuze",
         vraag="Welke zin zegt correct dat iemand goed zingt?",
         opties=["She sings well.", "She sings good.", "She sings goodly.", "She sings a good."],
         antwoord=0,
         uitleg="Well is het bijwoord bij good. Good zegt iets over een naamwoord: she is a good singer."),
    dict(type="waarofniet",
         vraag="Het bijwoord bij 'fast' is 'fastly'.",
         antwoord=False,
         uitleg="Fast blijft fast: he runs fast. Fastly bestaat niet. Hetzelfde geldt voor hard, late en early."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'he has hardly worked'?",
         opties=["hij heeft nauwelijks gewerkt", "hij heeft hard gewerkt", "hij heeft moeilijk werk", "hij werkt nog altijd"],
         antwoord=0,
         uitleg="Hard betekent hard, maar hardly betekent nauwelijks. Hij heeft hard gewerkt is he has worked hard."),
    dict(type="meerkeuze",
         vraag="In welke zinnen staat 'hard' of 'hardly' juist gebruikt?",
         opties=["This is a lot of hard work.", "She has worked hard.", "He has hardly worked.", "She has worked hardly."],
         antwoord=[0, 1, 2],
         uitleg="She has worked hardly zou betekenen dat ze bijna niets deed, en dat is niet wat de zin wil zeggen."),
    dict(type="waarofniet",
         vraag="'Lately' betekent de laatste tijd, en niet laat.",
         antwoord=True,
         uitleg="Late is laat, lately is de laatste tijd: I haven't seen her lately. Ook hier draait de -ly de betekenis om."),
    dict(type="meerkeuze",
         vraag="Welk woord is een bijvoeglijk naamwoord, ook al eindigt het op -ly?",
         opties=["friendly", "quickly", "slowly", "loudly"],
         antwoord=0,
         uitleg="Friendly, lovely, lonely en silly zijn bijvoeglijke naamwoorden. Wil je er een bijwoord van maken, dan zeg je in a friendly way."),
    dict(type="meerkeuze",
         vraag="Welke zin over een bezoek aan de sportzaal is juist?",
         opties=["She often goes to the gym.", "She goes often to the gym.", "Often she goes the gym.", "She goes to the gym often the week."],
         antwoord=0,
         uitleg="Bijwoorden van frequentie staan voor het hoofdwerkwoord: always, usually, often, sometimes, never."),
    dict(type="meerkeuze",
         vraag="Waar staat 'always' als het werkwoord 'to be' is?",
         opties=["achter to be: he is always late", "voor to be: he always is late", "achteraan: he is late always", "vooraan: always he is late"],
         antwoord=0,
         uitleg="To be is de uitzondering. Bij alle andere werkwoorden staat het bijwoord ervoor: he always arrives late."),
    dict(type="invultekst",
         vraag="Vul het juiste woord in: drive … , the roads are icy. Kies tussen careful en carefully.",
         antwoord=["carefully"],
         uitleg="Het zegt iets over hoe je rijdt, dus je hebt een bijwoord nodig."),
    dict(type="waarofniet",
         vraag="Na een koppelwerkwoord zoals 'look' of 'smell' gebruik je een bijvoeglijk naamwoord: it smells good.",
         antwoord=True,
         uitleg="Het zegt iets over het onderwerp, niet over de handeling. Vergelijk: she looks happy tegenover she looked at me happily."),
    dict(type="meerkeuze",
         vraag="Welke zin over de smaak van de soep is juist?",
         opties=["The soup tastes delicious.", "The soup tastes deliciously.", "The soup is tasting deliciously.", "The soup tastes a delicious."],
         antwoord=0,
         uitleg="Taste is hier een koppelwerkwoord, dus komt er een bijvoeglijk naamwoord achter."),
    dict(type="meerkeuze",
         vraag="Welke woorden versterken een bijvoeglijk naamwoord?",
         opties=["very", "quite", "extremely", "much"],
         antwoord=[0, 1, 2],
         uitleg="Much versterkt geen bijvoeglijk naamwoord in een gewone zin. Bij een vergrotende trap kan het wel: much better."),
    dict(type="waarofniet",
         vraag="Je kan 'very' voor een vergrotende trap zetten: very better.",
         antwoord=False,
         uitleg="Daar gebruik je much, far of a lot: much better, far better, a lot better."),
    dict(type="meerkeuze",
         vraag="Welke zin klopt qua betekenis?",
         opties=["He works hard, so he is tired.", "He hardly works, so he is tired from work.", "He works hardly, so he earns a lot.", "He is hard working hardly today."],
         antwoord=0,
         uitleg="Hardly draait de betekenis om naar bijna niet. Let dus goed op welk van de twee er staat."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is de vergrotende trap van 'big'?",
         opties=["bigger", "more big", "biger", "biggest"],
         antwoord=0,
         uitleg="Een korte klinker met één medeklinker erachter: die medeklinker verdubbelt. Big wordt bigger, hot wordt hotter."),
    dict(type="meerkeuze",
         vraag="Bij welke woorden gebruik je 'more' in plaats van -er?",
         opties=["expensive", "interesting", "beautiful", "small"],
         antwoord=[0, 1, 2],
         uitleg="Woorden van twee of meer lettergrepen krijgen more. Korte woorden krijgen -er: smaller."),
    dict(type="invultekst",
         vraag="Schrijf de vergrotende trap van 'easy'.",
         antwoord=["easier"],
         uitleg="Twee lettergrepen maar op een y, dus toch -er: easy, easier, easiest. De y wordt i."),
    dict(type="waarofniet",
         vraag="De overtreffende trap van 'good' is 'goodest'.",
         antwoord=False,
         uitleg="Good, better, best zijn onregelmatig. Net als bad, worse, worst en little, less, least."),
    dict(type="meerkeuze",
         vraag="Wat is de overtreffende trap van 'bad'?",
         opties=["worst", "baddest", "worse", "most bad"],
         antwoord=0,
         uitleg="Bad, worse, worst. Worse is de vergrotende trap."),
    dict(type="invultekst",
         vraag="Vul aan met één woord: this book is more interesting … the other one.",
         antwoord=["than"],
         uitleg="Na een vergrotende trap komt than. Verwar het niet met then, dat daarna betekent."),
    dict(type="meerkeuze",
         vraag="Welke zin vergelijkt correct twee personen die even groot zijn?",
         opties=["She is as tall as her brother.", "She is as tall than her brother.", "She is so tall as her brother.", "She is as tall like her brother."],
         antwoord=0,
         uitleg="Zijn twee dingen gelijk, dan zeg je as ... as. Zijn ze niet gelijk, dan zeg je not as ... as."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'this test is not as hard as the last one'?",
         opties=["deze toets is makkelijker", "deze toets is even moeilijk", "deze toets is moeilijker", "deze toets was de laatste"],
         antwoord=0,
         uitleg="Not as ... as zegt dat het eerste minder is dan het tweede."),
    dict(type="waarofniet",
         vraag="Voor de overtreffende trap zet je bijna altijd 'the': she is the tallest in the class.",
         antwoord=True,
         uitleg="Best, tallest, most expensive: er hoort the voor. Bij de vergrotende trap niet."),
    dict(type="meerkeuze",
         vraag="Welke zin over oefenen en makkelijker worden is juist?",
         opties=["The more you practise, the easier it gets.", "More you practise, easier it gets.", "The more you practise, the more easy it gets.", "More you practise, the easy it gets."],
         antwoord=0,
         uitleg="Deze vaste vorm neemt twee keer the: the ... , the ... En easy krijgt -ier, niet more."),
    dict(type="meerkeuze",
         vraag="Welk voorzetsel hoort bij een uur: … seven o'clock?",
         opties=["at", "on", "in", "for"],
         antwoord=0,
         uitleg="At bij een uur, on bij een dag of een datum, in bij een maand, een seizoen of een jaar."),
    dict(type="meerkeuze",
         vraag="Bij welke tijdsaanduidingen hoort 'in'?",
         opties=["July", "2027", "the morning", "Monday"],
         antwoord=[0, 1, 2],
         uitleg="Bij een dag hoort on: on Monday. En on Monday morning, want de dag wint."),
    dict(type="invultekst",
         vraag="Vul het juiste voorzetsel in: I was born … 14 March.",
         antwoord=["on"],
         uitleg="Bij een volledige datum hoort on. Bij enkel de maand hoort in: in March."),
    dict(type="waarofniet",
         vraag="Bij 'night' hoort in het Engels 'at': I don't work at night.",
         antwoord=True,
         uitleg="At night, maar in the morning, in the afternoon en in the evening. Night is de uitzondering."),
    dict(type="meerkeuze",
         vraag="Welke zin zegt correct dat je op de bus wacht?",
         opties=["I am waiting for the bus.", "I am waiting on the bus.", "I am waiting the bus.", "I am waiting to the bus."],
         antwoord=0,
         uitleg="Wait for is vast. In het Nederlands wacht je op iets, in het Engels wacht je for."),
    dict(type="meerkeuze",
         vraag="Welke werkwoorden nemen het voorzetsel 'to'?",
         opties=["listen", "belong", "explain", "discuss"],
         antwoord=[0, 1, 2],
         uitleg="Listen to music, belong to someone, explain something to someone. Discuss neemt niets: we discussed the problem."),
    dict(type="invultekst",
         vraag="Vul het juiste voorzetsel in: she is very good … maths.",
         antwoord=["at"],
         uitleg="Good at, bad at, but interested in en afraid of. Die combinaties leer je als één geheel."),
    dict(type="waarofniet",
         vraag="Je zegt in het Engels 'I am married with him'.",
         antwoord=False,
         uitleg="Het is married to. Het voorzetsel volgt niet altijd het Nederlands, dus leer het woord en het voorzetsel samen."),
    dict(type="meerkeuze",
         vraag="Welke zin over de aankomst in een station is juist?",
         opties=["We arrived at the station at six.", "We arrived to the station at six.", "We arrived in the station at six.", "We arrived the station at six."],
         antwoord=0,
         uitleg="Arrive at bij een plaats zoals een station of een gebouw, arrive in bij een stad of een land: we arrived in London."),
    dict(type="meerkeuze",
         vraag="Welk voorzetsel past? The keys are … the table.",
         opties=["on", "in", "at", "to"],
         antwoord=0,
         uitleg="On voor een oppervlak, in voor iets wat omsloten is, at voor een punt of een plaats waar je bent: at the bus stop."),
]
