# -*- coding: utf-8 -*-
"""Modal auxiliaries, imperative en infinitive.

De vakfiche schrijft er zelf bij waarom dit thema zwaar weegt: "Modale
hulpwerkwoorden (can, may, should, could, must, ...) hebben een grote invloed
op de interpretatie." Eén woord verandert een vraag in een bevel, of een
verbod in een vrije keuze.

Uit de tabel met werkwoorden horen hier bij:

    modale hulpwerkwoorden · imperatief en infinitief
    'do' om iets te benadrukken · wederkerende werkwoorden
    onpersoonlijke werkwoorden

Deel 1 gaat over de modale hulpwerkwoorden. Deel 2 gaat over de gebiedende
wijs, de infinitief, de nadrukkelijke do en de werkwoorden zonder echt
onderwerp.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat zegt 'she can swim' over haar?",
         opties=["ze kan zwemmen", "ze mag zwemmen van iemand", "ze zal zwemmen", "ze zwemt nu"],
         antwoord=0,
         uitleg="Can gaat meestal over kunnen. Gaat het over toestemming, dan blijkt dat uit de rest van de zin: can I go now?"),
    dict(type="waarofniet",
         vraag="Een modaal hulpwerkwoord krijgt nooit een s in de derde persoon: she can, niet she cans.",
         antwoord=True,
         uitleg="Can, may, must, should, will en would blijven altijd hetzelfde. Daarna volgt de kale basisvorm."),
    dict(type="meerkeuze",
         vraag="Welke zin is de beleefdste manier om iets te vragen?",
         opties=["Could you help me, please?", "Can you help me?", "Help me.", "You must help me."],
         antwoord=0,
         uitleg="Could klinkt beleefder dan can. Nog beleefder is would you mind helping me?"),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn modale hulpwerkwoorden?",
         opties=["might", "should", "must", "want"],
         antwoord=[0, 1, 2],
         uitleg="Want is een gewoon werkwoord en neemt to: I want to go. Na een modaal hulpwerkwoord komt geen to."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'you mustn't park here'?",
         opties=["hier parkeren is verboden", "hier parkeren hoeft niet", "hier mag je parkeren", "hier parkeert bijna niemand"],
         antwoord=0,
         uitleg="Mustn't is een verbod. Hoeft niet is you don't have to."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'you don't have to come'?",
         opties=["je hoeft niet te komen", "je mag niet komen", "je moet zeker komen", "je komt beter toch"],
         antwoord=0,
         uitleg="Dit is het grote verschil met mustn't. Don't have to laat je vrij, mustn't verbiedt."),
    dict(type="waarofniet",
         vraag="'Mustn't' en 'don't have to' betekenen ongeveer hetzelfde.",
         antwoord=False,
         uitleg="Ze zijn bijna elkaars tegendeel. Mustn't is verboden, don't have to is niet nodig."),
    dict(type="invultekst",
         vraag="Vul het modale werkwoord in: you … wear a helmet here, het is verplicht.",
         antwoord=["must", "have to"],
         uitleg="Must of have to. Must klinkt alsof de spreker het zelf oplegt, have to alsof een regel het oplegt."),
    dict(type="meerkeuze",
         vraag="Hoe zet je 'I must go' in de verleden tijd?",
         opties=["I had to go", "I musted go", "I must went", "I would must go"],
         antwoord=0,
         uitleg="Must heeft geen eigen verleden tijd. Daarvoor neem je had to."),
    dict(type="meerkeuze",
         vraag="Welke zin geeft een advies?",
         opties=["You should see a doctor.", "You must see a doctor now.", "You can see a doctor.", "You will see a doctor."],
         antwoord=0,
         uitleg="Should en ought to geven raad. Must is sterker en klinkt als een verplichting."),
    dict(type="waarofniet",
         vraag="'Ought to' betekent ongeveer hetzelfde als 'should'.",
         antwoord=True,
         uitleg="Ought to is het enige modale werkwoord met to erbij. Het klinkt iets formeler."),
    dict(type="meerkeuze",
         vraag="Wat zegt 'it might rain tomorrow'?",
         opties=["het is mogelijk dat het regent", "het regent zeker", "het regent zeker niet", "het regende gisteren"],
         antwoord=0,
         uitleg="May, might en could drukken een mogelijkheid uit. Might klinkt iets onzekerder dan may."),
    dict(type="meerkeuze",
         vraag="Welke zinnen drukken een mogelijkheid uit?",
         opties=["She may be at home.", "She might call later.", "It could be true.", "She must be at home."],
         antwoord=[0, 1, 2],
         uitleg="Must be klinkt juist als een zekerheid: het zal wel zo zijn. Dat is een conclusie, geen mogelijkheid."),
    dict(type="invultekst",
         vraag="Vul het modale werkwoord in: he's been running for an hour, he … be exhausted. Je trekt een conclusie.",
         antwoord=["must"],
         uitleg="Must drukt hier geen verplichting uit maar een sterke conclusie. Het tegendeel is can't: he can't be tired already."),
    dict(type="waarofniet",
         vraag="'That can't be true' betekent dat het onmogelijk waar kan zijn.",
         antwoord=True,
         uitleg="Can't is de ontkenning van must als conclusie. Mustn't zou hier fout zijn, want dat is een verbod."),
    dict(type="meerkeuze",
         vraag="Welke zin vraagt om toestemming op een formele manier?",
         opties=["May I leave early today?", "Can I go now?", "I want to leave early.", "I will leave early."],
         antwoord=0,
         uitleg="May is formeler dan can. In spreektaal hoor je can I vaker."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'I would rather stay home'?",
         opties=["ik blijf liever thuis", "ik moet thuisblijven", "ik zou thuis kunnen blijven", "ik bleef vroeger thuis"],
         antwoord=0,
         uitleg="Would rather betekent liever. Na would rather komt de basisvorm, zonder to."),
    dict(type="waarofniet",
         vraag="Na een modaal hulpwerkwoord zet je 'to' voor het werkwoord: she can to swim.",
         antwoord=False,
         uitleg="Het is she can swim. Ought to is de enige uitzondering en heeft zijn to al vast."),
    dict(type="meerkeuze",
         vraag="Welke zin zegt correct dat iemand morgen niet zal kunnen komen?",
         opties=["She won't be able to come tomorrow.", "She won't can come tomorrow.", "She will can't come tomorrow.", "She won't could come tomorrow."],
         antwoord=0,
         uitleg="Twee modale werkwoorden na elkaar kan niet. Voor de toekomst van can gebruik je will be able to."),
    dict(type="meerkeuze",
         vraag="Welke zin hoort bij 'Je had beter je huiswerk gemaakt.'?",
         opties=["You should have done your homework.", "You should do your homework.", "You must do your homework.", "You had to do your homework."],
         antwoord=0,
         uitleg="Should have plus het deelwoord zegt wat je beter had gedaan, achteraf bekeken."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Hoe maak je in het Engels een bevel?",
         opties=["je gebruikt de kale basisvorm: close the door", "je zet you ervoor: you close the door", "je zet to ervoor: to close the door", "je zet must ervoor: must close the door"],
         antwoord=0,
         uitleg="De imperatief heeft geen onderwerp. Voor de beleefdheid zet je er please bij."),
    dict(type="meerkeuze",
         vraag="Hoe maak je een bevel ontkennend?",
         opties=["don't open the window", "not open the window", "no open the window", "open not the window"],
         antwoord=0,
         uitleg="Don't plus de basisvorm, ook als je iemand met u aanspreekt. Het Engels maakt daar geen verschil in."),
    dict(type="invultekst",
         vraag="Vul aan met één woord: … go to the cinema tonight. Je stelt iets voor aan jezelf en je vrienden.",
         antwoord=["let's"],
         uitleg="Let's is de korte vorm van let us. Het is de gebiedende wijs voor een groep waar je zelf bij hoort."),
    dict(type="waarofniet",
         vraag="De imperatief is in het Engels altijd onbeleefd.",
         antwoord=False,
         uitleg="Hij staat gewoon in instructies en recepten: mix the eggs, turn left. Met please erbij klinkt hij vriendelijk."),
    dict(type="meerkeuze",
         vraag="Wat is de infinitief van een werkwoord?",
         opties=["de basisvorm, vaak met to ervoor", "de vorm op -ing", "de derde vorm", "de vorm met een s"],
         antwoord=0,
         uitleg="To go, to be, to write. Zonder to heet het de kale infinitief."),
    dict(type="meerkeuze",
         vraag="Na welke werkwoorden komt een infinitief met to?",
         opties=["want", "decide", "hope", "enjoy"],
         antwoord=[0, 1, 2],
         uitleg="Na enjoy komt een -ing-vorm: I enjoy reading. Zo werkt het ook bij finish, avoid en mind."),
    dict(type="invultekst",
         vraag="Vul de juiste vorm in: I enjoy … books. Gebruik het werkwoord read.",
         antwoord=["reading"],
         uitleg="Na enjoy, finish, avoid en mind komt altijd de -ing-vorm."),
    dict(type="waarofniet",
         vraag="Na een voorzetsel komt in het Engels altijd de -ing-vorm: he left without saying goodbye.",
         antwoord=True,
         uitleg="Ook na before, after, instead of en good at: she is good at drawing."),
    dict(type="meerkeuze",
         vraag="Welke zin zegt correct dat iemand jou aan het lachen bracht?",
         opties=["She made me laugh.", "She made me to laugh.", "She made me laughing.", "She made that I laughed."],
         antwoord=0,
         uitleg="Na make en let komt de kale infinitief: let him go, make her wait."),
    dict(type="meerkeuze",
         vraag="Na welke werkwoorden komt de kale infinitief, dus zonder to?",
         opties=["let", "make", "must", "need"],
         antwoord=[0, 1, 2],
         uitleg="Need is een gewoon werkwoord en neemt to: I need to go. Als hulpwerkwoord in een ontkenning kan het wel kaal: you needn't worry."),
    dict(type="waarofniet",
         vraag="In de afsluiter 'I look forward to hearing from you' staat de -ing-vorm terecht.",
         antwoord=True,
         uitleg="De to in look forward to is een voorzetsel en geen infinitief, dus er komt een -ing-vorm achter. I look forward to hear from you is fout."),
    dict(type="meerkeuze",
         vraag="Wat doet de 'do' in 'I do like your new coat'?",
         opties=["hij legt nadruk op like", "hij maakt er een vraag van", "hij maakt er een ontkenning van", "hij zet de zin in de verleden tijd"],
         antwoord=0,
         uitleg="Dat heet de emphatic do. In het Nederlands zou je zeggen: ik vind je nieuwe jas echt mooi."),
    dict(type="meerkeuze",
         vraag="In welke zinnen staat een nadrukkelijke do?",
         opties=["Do sit down.", "She does look tired.", "I did tell you, honestly.", "Do you want tea?"],
         antwoord=[0, 1, 2],
         uitleg="De laatste is een gewone vraag. Bij de eerste drie kan de zin ook zonder do, en dat is precies waarom de do nadruk geeft."),
    dict(type="invultekst",
         vraag="Vul één woord in dat nadruk geeft: I … believe you, really.",
         antwoord=["do"],
         uitleg="Do, does en did kunnen in een bevestigende zin nadruk leggen. Je hoort het aan de klemtoon."),
    dict(type="meerkeuze",
         vraag="Welke zin wenst iemand correct veel plezier op een feest?",
         opties=["Enjoy yourself at the party!", "Enjoy you at the party!", "Enjoy at the party!", "Enjoy your at the party!"],
         antwoord=0,
         uitleg="Enjoy oneself, help oneself en behave oneself zijn wederkerend in het Engels."),
    dict(type="meerkeuze",
         vraag="Welke Engelse werkwoorden zijn wederkerend terwijl het Nederlands dat niet is?",
         opties=["enjoy yourself", "help yourself", "behave yourself", "wash yourself"],
         antwoord=[0, 1, 2],
         uitleg="Bij wassen is het net omgekeerd: wij zeggen zich wassen, het Engels zegt gewoon she washed."),
    dict(type="waarofniet",
         vraag="In 'it is raining' verwijst 'it' nergens naar: het staat er alleen omdat een Engelse zin een onderwerp nodig heeft.",
         antwoord=True,
         uitleg="Dat heet een onpersoonlijk it. Je vindt het ook in it is cold en in it is five o'clock."),
    dict(type="meerkeuze",
         vraag="Welke zin zegt correct dat de rit een uur duurt?",
         opties=["It takes an hour to get there.", "Takes an hour to get there.", "There takes an hour to get there.", "It take an hour to get there."],
         antwoord=0,
         uitleg="Een Engelse zin heeft altijd een onderwerp, ook als er niets te noemen valt. Dan zet je it of there."),
    dict(type="meerkeuze",
         vraag="Welke zinnen hebben een onpersoonlijk onderwerp?",
         opties=["It seems that he is right.", "There is no milk left.", "It was snowing all night.", "He is right about that."],
         antwoord=[0, 1, 2],
         uitleg="Bij de laatste zin verwijst he naar een echte persoon. Bij de andere drie verwijst het onderwerp nergens naar."),
    dict(type="waarofniet",
         vraag="'Please to sit down' is de beleefde vorm van een bevel.",
         antwoord=False,
         uitleg="Het is please sit down. De imperatief neemt nooit to."),
]
