# -*- coding: utf-8 -*-
"""Schrijven, schriftelijke interactie en literatuurbeleving.

Uit de vakfiche Engels 2 van de 2de graad doorstroomfinaliteit. Schrijven weegt
29 % van dat examen, schriftelijke interactie nog eens 29 % en
literatuurbeleving 4 %. Samen is dat 62 %, en het is meteen het stuk dat je
achter een scherm wél kan oefenen.

De fiche somt zes dingen op die je schriftelijk moet kunnen: alledaagse sociale
contacten leggen, informatie geven en vragen, je mening geven, iets uitleggen,
iets vertellen, en iemand proberen te overtuigen. Daarnaast staan er zeven
vereisten waaraan je tekst moet voldoen, en een lijstje strategieën.

Deel 1 gaat over die zes opdrachten en de vaste uitdrukkingen erbij, deel 2
over de vereisten, de strategieën en het verwoorden van je leeservaring.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Welke zin gebruik je om iemand uit te nodigen?",
         opties=["Would you like to come along on Saturday?",
                 "I am writing to complain about the noise.",
                 "Could you tell me where the station is?",
                 "I really enjoyed the first chapter."],
         antwoord=0,
         uitleg="Would you like to is de gewone, beleefde uitnodiging. 'How about coming along?' kan ook."),
    dict(type="meerkeuze",
         vraag="Welke zinnen horen bij het leggen van alledaagse sociale contacten?",
         opties=["How have you been?", "Thanks so much for having me.",
                 "It was lovely to see you again.", "The train leaves at 7.15."],
         antwoord=[0, 1, 2],
         uitleg="Belangstelling tonen, bedanken en je waardering uiten staan alle drie in de leerstof. De laatste zin geeft gewoon informatie."),
    dict(type="meerkeuze",
         vraag="Je schrijft een verslag over een uitstap. Welke schrijfopdracht is dat?",
         opties=["iets vertellen", "iemand overtuigen", "iets uitleggen", "je mening geven"],
         antwoord=0,
         uitleg="De leerstof geeft er zelf dit voorbeeld bij: je brengt verslag uit over je reis. Vertellen is gebeurtenissen weergeven."),
    dict(type="meerkeuze",
         vraag="Je legt aan een vriend uit hoe je een gerecht klaarmaakt. Welke opdracht is dat?",
         opties=["iets uitleggen", "iets vertellen", "informatie vragen", "iemand overtuigen"],
         antwoord=0,
         uitleg="De leerstof noemt precies dat voorbeeld. Bij uitleggen gaat het om de stappen en de volgorde."),
    dict(type="meerkeuze",
         vraag="Welke zin hoort bij 'iemand proberen te overtuigen'?",
         opties=["You really should join us, it will be so much fun.",
                 "The meeting starts at four.",
                 "Could you send me the form?",
                 "I felt sorry for the main character in that film."],
         antwoord=0,
         uitleg="De leerstof geeft het voorbeeld van een vriend overtuigen om mee te doen. Een aanbeveling plus een reden werkt daarvoor het best."),
    dict(type="meerkeuze",
         vraag="Je wil weten hoe je je inschrijft voor een taalstage. Welke zin past in je mail?",
         opties=["I would like to know how I can register for the course.",
                 "Register me for the course.",
                 "I am not sure this course is any good.",
                 "The course sounds interesting, doesn't it?"],
         antwoord=0,
         uitleg="Informatie vragen doe je met I would like to know, Could you tell me of I was wondering whether."),
    dict(type="waarofniet",
         vraag="'I am writing to ask about …' is een gepaste openingszin voor een formele mail.",
         antwoord=True,
         uitleg="Zo'n zin zegt meteen waarom je schrijft. De lezer weet na één regel wat je van hem wil."),
    dict(type="meerkeuze",
         vraag="Welke uitdrukkingen gebruik je om belangstelling te tonen?",
         opties=["How are you doing?", "How was your trip?",
                 "Are you feeling better now?", "I have to go, bye."],
         antwoord=[0, 1, 2],
         uitleg="Informeren naar iemands gezondheid en belangstelling tonen staan allebei in de leerstof. De laatste zin sluit juist af."),
    dict(type="meerkeuze",
         vraag="Je bedankt iemand die je een weekend heeft laten logeren. Welke zin is het meest gepast?",
         opties=["Thank you so much, I had a wonderful time.",
                 "Thanks, it was okay.",
                 "You really did not have to do all of that.",
                 "I will pay you back next time."],
         antwoord=0,
         uitleg="Gastvrijheid beantwoord je met een duidelijke dank en een reden. 'It was okay' klinkt in het Engels bijna als kritiek."),
    dict(type="waarofniet",
         vraag="Je mening geven en informatie geven zijn twee verschillende schrijfopdrachten.",
         antwoord=True,
         uitleg="Informatie geven is zeggen wat er is; je mening geven is zeggen wat jij ervan vindt. Op het examen wordt gevraagd welk van de twee je doet."),
    dict(type="meerkeuze",
         vraag="Welke zin hoort bij het geven van een standpunt over een probleem?",
         opties=["I think the school should open the library at lunchtime.",
                 "The library is open from nine to four.",
                 "Where exactly is the library?",
                 "I walked past the library this morning."],
         antwoord=0,
         uitleg="Should plus een voorstel is de gewone manier om een standpunt te formuleren. De andere zinnen melden, vragen of vertellen."),
    dict(type="meerkeuze",
         vraag="Je schrijft een reactie op een bericht van een vriend. Wat is het verschil met een gewone tekst schrijven?",
         opties=["je moet reageren op wat er in het bericht staat",
                 "je mag korter schrijven zonder aanhef",
                 "spelling telt dan niet mee",
                 "je hoeft geen structuur te gebruiken"],
         antwoord=0,
         uitleg="Dat is schriftelijke interactie: je gaat in op de ander. Een antwoord dat het bericht negeert, haalt geen punten."),
    dict(type="waarofniet",
         vraag="Bij schriftelijke interactie mag je de vragen van je correspondent onbeantwoord laten als je tekst verder mooi is.",
         antwoord=False,
         uitleg="Taakvoltooiing komt eerst: het doel wordt bereikt en je boodschap is volledig. Een onbeantwoorde vraag is een onvolledige taak."),
    dict(type="meerkeuze",
         vraag="Welke zin verontschuldigt zich én geeft een reden?",
         opties=["Sorry I missed your call, I was on the train.",
                 "Sorry.",
                 "I was on the train all afternoon.",
                 "You called me at a bad moment."],
         antwoord=0,
         uitleg="De leerstof vraagt dat je je kan verontschuldigen. Een reden erbij maakt het een volwaardige boodschap."),
    dict(type="invultekst",
         vraag="Met welk Engels werkwoord nodig je iemand uit, in 'Would you like to ... us on Saturday?' voor samen komen?",
         antwoord=["join"],
         uitleg="To join betekent zich aansluiten bij. 'Join us' is de gewone uitnodiging."),
    dict(type="meerkeuze",
         vraag="Je schrijft: 'The concert was amazing. We got there early and stood right at the front.' Welke opdracht doe je?",
         opties=["iets vertellen", "informatie vragen", "iemand overtuigen", "iets uitleggen"],
         antwoord=0,
         uitleg="Je geeft gebeurtenissen weer in de volgorde waarin ze gebeurden. Dat is vertellen."),
    dict(type="waarofniet",
         vraag="Een uitnodiging afslaan hoort niet bij de alledaagse sociale contacten.",
         antwoord=False,
         uitleg="Reageren hoort er wel degelijk bij, en een beleefd nee is een van de moeilijkste dingen in een vreemde taal: 'I'd love to, but I'm afraid I can't.'"),
    dict(type="meerkeuze",
         vraag="Welke opening past bij een informeel bericht aan een leeftijdsgenoot?",
         opties=["Hi Sam, how are things?", "Dear Sir or Madam,",
                 "To whom it may concern,", "I am writing to inform you that"],
         antwoord=0,
         uitleg="De drie andere horen bij een formele brief. Register betekent: je toon past bij wie je aanspreekt."),
    dict(type="meerkeuze",
         vraag="Je krijgt een opdracht van 120 tot 150 woorden en je schrijft er 70. Wat gebeurt er?",
         opties=["je verliest punten op taakvoltooiing",
                 "er gebeurt niets, korter is duidelijker",
                 "je verliest enkel punten op spelling",
                 "je tekst wordt niet gelezen"],
         antwoord=0,
         uitleg="De leerstof zegt het letterlijk: je respecteert de opgegeven lengte. Te kort betekent meestal ook: niet volledig uitgewerkt."),
    dict(type="waarofniet",
         vraag="Bij een schrijfopdracht mag je zelf verzinnen wat je vertelt, zolang je de opdracht uitvoert.",
         antwoord=True,
         uitleg="De inhoud moet helder, correct en ter zake zijn, maar hij hoeft niet waargebeurd te zijn. Verzin dus iets dat je met je woordenschat aankan."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Er zijn zeven dingen waarop je schrijfopdracht beoordeeld wordt. Welke hoort er zeker bij?",
         opties=["tekststructuur en samenhang", "je handschrift",
                 "het aantal alinea's", "de snelheid waarmee je schrijft"],
         antwoord=0,
         uitleg="De vereisten zijn taakvoltooiing, woordenschat, grammatica en zinsbouw, tekststructuur en samenhang, register en beleefdheid, tekstopbouw en lay-out, en spelling en leestekens."),
    dict(type="meerkeuze",
         vraag="Welke drie delen horen in een tekst met een herkenbare structuur?",
         opties=["een inleiding", "een midden", "een slot", "een bronvermelding"],
         antwoord=[0, 1, 2],
         uitleg="Inleiding, midden en slot. Een bronvermelding hoort bij een werkstuk, niet bij deze opdrachten."),
    dict(type="waarofniet",
         vraag="Er mogen nog grammaticafouten in je tekst staan.",
         antwoord=True,
         uitleg="De eis is: je beheerst de grammatica goed, fouten mogen voorkomen maar mogen de communicatie niet verstoren. Perfectie wordt niet gevraagd."),
    dict(type="meerkeuze",
         vraag="Wat wordt bedoeld met 'je vormt af en toe samengestelde zinnen'?",
         opties=["je schrijft niet enkel korte hoofdzinnen",
                 "je schrijft zo lang mogelijke zinnen",
                 "je gebruikt in elke zin een bijzin",
                 "je zet twee zinnen achter elkaar zonder leesteken"],
         antwoord=0,
         uitleg="Af en toe een because, although of which laat zien dat je meer kan dan korte losse zinnen. Alles lang maken helpt niet."),
    dict(type="meerkeuze",
         vraag="Welke woorden maken de samenhang in een Engelse tekst zichtbaar?",
         opties=["first", "however", "finally", "the"],
         antwoord=[0, 1, 2],
         uitleg="Signaalwoorden sturen je lezer door de tekst. Een lidwoord doet dat niet."),
    dict(type="waarofniet",
         vraag="Spelfouten tellen alleen mee als ze het begrip van je tekst in de weg staan.",
         antwoord=True,
         uitleg="Zo staat het bij de vereisten: spelfouten en fouten tegen leestekens staan het tekstbegrip niet in de weg. Dat is minder streng dan foutloos, maar geen vrijgeleide."),
    dict(type="meerkeuze",
         vraag="Wat is een schrijfplan met kernwoorden?",
         opties=["een lijstje van wat je in welke volgorde wil zeggen",
                 "de eerste versie van je tekst",
                 "een woordenlijst die je uit het hoofd leert",
                 "de titel en de aanhef van je brief"],
         antwoord=0,
         uitleg="De leerstof raadt het als strategie aan. Vijf kernwoorden op je kladblad houden je tekst op koers en kosten je twee minuten."),
    dict(type="meerkeuze",
         vraag="Welke vragen stel je jezelf volgens het communicatiemodel voor je begint te schrijven?",
         opties=["waarom schrijf ik?", "voor wie is mijn boodschap?",
                 "welk kanaal gebruik ik?", "hoe lang zal het duren?"],
         antwoord=[0, 1, 2],
         uitleg="De leerstof noemt ook: met wie communiceer je, en wat wil je precies vertellen. De tijd hoort er niet bij."),
    dict(type="meerkeuze",
         vraag="Je mag op het examen een online woordenboek en spellingcontrole gebruiken. Waarvoor zijn die bedoeld?",
         opties=["om te controleren en een enkel woord op te zoeken",
                 "om je hele tekst te laten vertalen",
                 "om je tekst te laten schrijven",
                 "om de opdracht te laten uitleggen"],
         antwoord=0,
         uitleg="Wie elk woord opzoekt, raakt niet klaar. Een woordenboek is een net, geen motor."),
    dict(type="waarofniet",
         vraag="Zit je vast bij het schrijven, dan stop je best met die zin en begin je aan een andere opdracht.",
         antwoord=False,
         uitleg="De leerstof geeft een betere strategie: probeer je doel te bereiken met de woorden en structuren die je wél al kent. Omschrijven mag."),
    dict(type="meerkeuze",
         vraag="Je kent het woord 'crutches' niet, maar je moet het wel zeggen. Wat doe je?",
         opties=["je omschrijft het: the sticks you walk with after you break a leg",
                 "je laat de zin weg",
                 "je schrijft het Nederlandse woord",
                 "je verzint zelf een Engels klinkend woord"],
         antwoord=0,
         uitleg="Omschrijven is een erkende strategie en toont net dat je de taal kan gebruiken. Een verzonnen woord kost je punten op woordenschat."),
    dict(type="meerkeuze",
         vraag="Wat hoort bij 'tekstopbouw en lay-out' in een schrijfopdracht?",
         opties=["een titel en duidelijke alinea's",
                 "een groot lettertype",
                 "een gekleurde achtergrond",
                 "zo weinig mogelijk witruimte"],
         antwoord=0,
         uitleg="De leerstof vraagt een duidelijk herkenbare opbouw met titel en alinea's, en een gepaste lay-out."),
    dict(type="meerkeuze",
         vraag="Je leest een gedicht en moet je eigen beleving verwoorden. Wat schrijf je?",
         opties=["waarom bepaalde beelden je raken en wat ze bij je oproepen",
                 "een samenvatting van het gedicht",
                 "wie de dichter was en wanneer hij leefde",
                 "hoeveel strofen het gedicht telt"],
         antwoord=0,
         uitleg="Literatuurbeleving is jouw ervaring en gevoel bij de tekst, niet de inhoud of de biografie van de schrijver."),
    dict(type="meerkeuze",
         vraag="Welke dingen mag je schrijven als je je beleving van een literaire tekst verwoordt?",
         opties=["waarom je je met een personage identificeert",
                 "of je zelf al iets gelijkaardigs meemaakte",
                 "waarom de stijl of de vorm je aanspreekt",
                 "hoeveel exemplaren het boek verkocht"],
         antwoord=[0, 1, 2],
         uitleg="De leerstof somt die drie zelf op, samen met waarom de tekst een bepaald gevoel bij je oproept. Verkoopcijfers zeggen niets over jouw beleving."),
    dict(type="waarofniet",
         vraag="Bij literatuurbeleving bestaat er geen fout antwoord, zolang je je mening onderbouwt met de tekst.",
         antwoord=True,
         uitleg="Het gaat om jouw ervaring. Wat wel fout kan lopen: beweren dat er iets in de tekst staat wat er niet staat."),
    dict(type="meerkeuze",
         vraag="Welke zin verwoordt een leeservaring en geen samenvatting?",
         opties=["The ending made me feel uncomfortable.",
                 "In the last chapter the brother comes home.",
                 "The story is set in Scotland in 1890.",
                 "The book has twelve chapters."],
         antwoord=0,
         uitleg="Made me feel geeft jouw gevoel weer. De drie andere zinnen beschrijven het boek van buitenaf, zonder jou erin."),
    dict(type="waarofniet",
         vraag="Literatuurbeleving weegt bij Engels 2 evenveel als schrijven.",
         antwoord=False,
         uitleg="Literatuurbeleving weegt 4 % en schrijven 29 %. Het is een klein maar makkelijk te verdienen onderdeel."),
    dict(type="invultekst",
         vraag="Hoe noem je het als je boodschap overkomt en je opdracht volledig is uitgevoerd? Eén woord.",
         antwoord=["taakvoltooiing"],
         uitleg="Taakvoltooiing staat bovenaan de lijst met vereisten. Wie de opdracht niet volledig uitvoert, verliest daar het meest."),
    dict(type="meerkeuze",
         vraag="Je hebt nog vijf minuten over na het schrijven. Wat doe je het best?",
         opties=["je tekst nalezen op werkwoordsvormen en leestekens",
                 "er nog twee alinea's bij schrijven",
                 "je tekst helemaal overschrijven",
                 "niets, langer kijken maakt het slechter"],
         antwoord=0,
         uitleg="De meeste punten liggen in fouten die je zelf ziet: een vergeten -s, een verkeerde tijd, een ontbrekende hoofdletter."),
    dict(type="meerkeuze",
         vraag="Welke fout kost je het meest bij taakvoltooiing?",
         opties=["één van de drie gevraagde punten niet behandelen",
                 "twee spelfouten maken",
                 "een komma vergeten",
                 "een paar heel korte zinnen na elkaar gebruiken"],
         antwoord=0,
         uitleg="Taakvoltooiing gaat over of je doel bereikt is en of je tekst volledig is. Een ontbrekend punt weegt zwaarder dan een spelfout."),
]
