# -*- coding: utf-8 -*-
"""De tegenwoordige tijden.

De vakfiche zet vijf vormen onder de tegenwoordige tijd:

    there is / there are · present simple · present continuous
    present perfect simple · present perfect continuous

Ze geeft er zelf een voorbeeld bij dat aantoont waarom dit meer is dan een
regeltje: "Ik woon sinds 2020 in Antwerpen." wordt in het Engels geen present
simple maar een present perfect: I have lived in Antwerp since 2020. Die zin
staat in deel 2.

Deel 1 gaat over there is en there are, de present simple en de present
continuous. Deel 2 gaat over de present perfect en het verschil met de
verleden tijd.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Welke zin over boeken op tafel is juist?",
         opties=["There are three books on the table.", "There is three books on the table.", "There are a book on the table.", "It are three books on the table."],
         antwoord=0,
         uitleg="There is bij enkelvoud, there are bij meervoud. Je kijkt naar het woord dat erachter komt."),
    dict(type="waarofniet",
         vraag="In 'there is some milk in the fridge' hoort 'is' omdat milk ontelbaar is.",
         antwoord=True,
         uitleg="Ontelbare woorden nemen de enkelvoudsvorm. Bij een opsomming kijk je naar het eerste woord: there is a knife and two forks."),
    dict(type="meerkeuze",
         vraag="Hoe schrijf je de derde persoon enkelvoud van 'to watch'?",
         opties=["watches", "watchs", "watche", "watchies"],
         antwoord=0,
         uitleg="Na een sisklank komt es: watches, misses, fixes. Zo ook bij go en do: goes, does."),
    dict(type="invultekst",
         vraag="Schrijf de derde persoon enkelvoud van 'to fly'.",
         antwoord=["flies"],
         uitleg="Een y na een medeklinker wordt ies. Staat er een klinker voor, dan blijft de y: he plays."),
    dict(type="meerkeuze",
         vraag="Welke zinnen staan in een correcte present simple?",
         opties=["She studies French.", "He does his homework.", "They live in Ghent.", "He go to school."],
         antwoord=[0, 1, 2],
         uitleg="He goes to school. De s van de derde persoon vergeten is de meest gemaakte fout in het Engels."),
    dict(type="meerkeuze",
         vraag="Welke vraag is juist?",
         opties=["Does she live here?", "Do she lives here?", "Does she lives here?", "Live she here?"],
         antwoord=0,
         uitleg="Does neemt de s over, dus het hoofdwerkwoord blijft in de basisvorm."),
    dict(type="waarofniet",
         vraag="In een ontkennende zin zeg je 'she doesn't lives here'.",
         antwoord=False,
         uitleg="Het is she doesn't live here. De s zit al in doesn't."),
    dict(type="meerkeuze",
         vraag="Wanneer gebruik je de present simple?",
         opties=["voor gewoontes en feiten", "voor wat nu bezig is", "voor iets dat net gebeurd is", "voor een plan van morgen"],
         antwoord=0,
         uitleg="I get up at seven every day. The sun rises in the east. Wat nu bezig is, is de present continuous."),
    dict(type="meerkeuze",
         vraag="Welke zin staat in een correcte present continuous?",
         opties=["She is writing a letter.", "She writing a letter.", "She is write a letter.", "She writes now a letter."],
         antwoord=0,
         uitleg="De vorm is am, is of are plus het werkwoord op -ing."),
    dict(type="invultekst",
         vraag="Schrijf de -ing-vorm van 'to sit'.",
         antwoord=["sitting"],
         uitleg="Eén korte klinker met één medeklinker erachter: die verdubbelt. Sit wordt sitting, run wordt running."),
    dict(type="meerkeuze",
         vraag="Welke -ing-vormen zijn juist geschreven?",
         opties=["writing", "lying", "beginning", "writting"],
         antwoord=[0, 1, 2],
         uitleg="Bij write valt de stomme e weg: writing. Bij lie wordt ie een y: lying."),
    dict(type="waarofniet",
         vraag="'Look! It is raining' staat terecht in de present continuous.",
         antwoord=True,
         uitleg="Het gebeurt op dit moment. It rains a lot in Belgium zou een gewoonte zijn en staat dus in de present simple."),
    dict(type="meerkeuze",
         vraag="Welk werkwoord zet je normaal niet in de -ing-vorm?",
         opties=["to know", "to walk", "to read", "to play"],
         antwoord=0,
         uitleg="Werkwoorden van weten, vinden en voelen blijven simple: I know, I believe, I want. Niet I am knowing."),
    dict(type="meerkeuze",
         vraag="Welke werkwoorden blijven meestal in de simple vorm staan?",
         opties=["understand", "belong", "like", "listen"],
         antwoord=[0, 1, 2],
         uitleg="Listen kan wel: I am listening to music. De andere drie beschrijven een toestand en geen handeling."),
    dict(type="invultekst",
         vraag="Vul de juiste vorm van to be in: they … waiting outside.",
         antwoord=["are"],
         uitleg="They neemt are. I neemt am, en he, she en it nemen is."),
    dict(type="waarofniet",
         vraag="De present continuous kan ook iets zeggen dat al afgesproken is voor later: we are meeting at six.",
         antwoord=True,
         uitleg="Bij een afspraak die vastligt, gebruik je de present continuous: I am seeing the dentist tomorrow."),
    dict(type="meerkeuze",
         vraag="Welke zin past bij 'Ik werk elke zaterdag in een winkel.'?",
         opties=["I work in a shop every Saturday.", "I am working in a shop every Saturday.", "I have worked in a shop every Saturday.", "I am work in a shop every Saturday."],
         antwoord=0,
         uitleg="Every Saturday maakt er een gewoonte van, dus present simple."),
    dict(type="meerkeuze",
         vraag="Welke vraag naar wat iemand nu doet is juist?",
         opties=["What are you doing right now?", "What do you doing right now?", "What are you do right now?", "What you are doing right now?"],
         antwoord=0,
         uitleg="In een vraag wisselen het onderwerp en de vorm van to be van plaats: are you."),
    dict(type="waarofniet",
         vraag="In de vraag 'How often are you going swimming?' staat het werkwoord in de juiste tijd.",
         antwoord=False,
         uitleg="How often vraagt naar een gewoonte, en daar hoort de present simple bij: how often do you go swimming?"),
    dict(type="meerkeuze",
         vraag="Welke zin klopt?",
         opties=["There aren't any eggs left.", "There isn't any eggs left.", "There aren't an egg left.", "There is not no eggs left."],
         antwoord=0,
         uitleg="Eggs is meervoud, dus aren't. En in een ontkenning hoort any, niet some."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Hoe vertaal je 'Ik woon sinds 2020 in Antwerpen.'?",
         opties=["I have lived in Antwerp since 2020.", "I live in Antwerp since 2020.", "I am living in Antwerp since 2020.", "I lived in Antwerp since 2020."],
         antwoord=0,
         uitleg="Iets dat vroeger begon en nu nog bezig is, staat in het Engels in de present perfect. Het Nederlands gebruikt daar de tegenwoordige tijd, en dat is een klassieke valkuil."),
    dict(type="meerkeuze",
         vraag="Waaruit bestaat de present perfect?",
         opties=["have of has plus het voltooid deelwoord", "am, is of are plus -ing", "did plus de basisvorm", "will plus de basisvorm"],
         antwoord=0,
         uitleg="I have seen, she has gone. Het voltooid deelwoord is de derde vorm van het werkwoord."),
    dict(type="invultekst",
         vraag="Vul in met één woord: she … finished her homework.",
         antwoord=["has"],
         uitleg="She, he en it nemen has. Alle andere personen nemen have."),
    dict(type="meerkeuze",
         vraag="Welk woord hoort bij een moment waarop iets begon?",
         opties=["since", "for", "ago", "during"],
         antwoord=0,
         uitleg="Since 2020, since Monday, since I was ten. For gaat over de duur: for three years."),
    dict(type="meerkeuze",
         vraag="Bij welke woorden hoort 'for' en niet 'since'?",
         opties=["two hours", "a week", "ages", "last Monday"],
         antwoord=[0, 1, 2],
         uitleg="For zegt hoe lang, since zegt vanaf wanneer. Last Monday is een moment, dus since."),
    dict(type="waarofniet",
         vraag="'I have been to London last year' is een juiste zin.",
         antwoord=False,
         uitleg="Last year is een afgelopen tijd, dus je neemt de past simple: I went to London last year."),
    dict(type="meerkeuze",
         vraag="Welke vraag over ervaring met sushi is juist?",
         opties=["Have you ever eaten sushi?", "Have you ever ate sushi?", "Did you ever eaten sushi?", "Have you never ate sushi?"],
         antwoord=0,
         uitleg="Na have komt het voltooid deelwoord: eaten. Ate is de verleden tijd."),
    dict(type="meerkeuze",
         vraag="Waar staat 'yet' meestal in de zin?",
         opties=["achteraan, in een vraag of een ontkenning", "vooraan de zin", "voor het werkwoord", "achteraan, alleen in een bevestiging"],
         antwoord=0,
         uitleg="Have you finished yet? I haven't finished yet. In een bevestigende zin gebruik je already: I have already finished."),
    dict(type="invultekst",
         vraag="Vul aan met één woord: I have … seen that film, dus ik moet het niet nog eens zien.",
         antwoord=["already"],
         uitleg="Already staat tussen have en het deelwoord. Yet hoort in een vraag of een ontkenning."),
    dict(type="waarofniet",
         vraag="'Just' betekent in 'I have just arrived' dat je nog maar net aangekomen bent.",
         antwoord=True,
         uitleg="Just, already en yet horen alle drie bij de present perfect. Just staat tussen have en het deelwoord."),
    dict(type="meerkeuze",
         vraag="Welke zin hoort bij 'Ik ben mijn sleutels kwijt, ik vind ze nu niet.'?",
         opties=["I have lost my keys.", "I lost my keys.", "I am losing my keys.", "I lose my keys."],
         antwoord=0,
         uitleg="De present perfect legt het verband met nu: het gevolg is er nog. I lost my keys zou enkel zeggen dat het gebeurde."),
    dict(type="meerkeuze",
         vraag="Welke zinnen horen in de past simple en niet in de present perfect?",
         opties=["I saw her yesterday.", "We moved house in 2019.", "She called me two hours ago.", "I have known him for years."],
         antwoord=[0, 1, 2],
         uitleg="Yesterday, in 2019 en ago noemen een afgesloten moment. For years loopt door tot nu."),
    dict(type="waarofniet",
         vraag="Bij 'when' als vraagwoord gebruik je de present perfect: when have you arrived?",
         antwoord=False,
         uitleg="When vraagt naar een precies moment in het verleden, dus past simple: when did you arrive?"),
    dict(type="meerkeuze",
         vraag="Waaruit bestaat de present perfect continuous?",
         opties=["have of has been plus -ing", "have of has plus -ing", "am, is of are been plus -ing", "had been plus -ing"],
         antwoord=0,
         uitleg="I have been waiting, she has been working. Had been plus -ing is de past perfect continuous."),
    dict(type="meerkeuze",
         vraag="Wat benadrukt 'I have been waiting for an hour'?",
         opties=["hoelang het al duurt", "dat het klaar is", "dat het morgen gebeurt", "dat het maar één keer gebeurde"],
         antwoord=0,
         uitleg="De continuous vorm legt de nadruk op de duur. Is het resultaat belangrijker, dan neem je de simple vorm."),
    dict(type="invultekst",
         vraag="Vul het ontbrekende woord in: they have … working all morning.",
         antwoord=["been"],
         uitleg="De present perfect continuous is have of has been plus de -ing-vorm."),
    dict(type="waarofniet",
         vraag="'I have been knowing her for years' is een juiste zin.",
         antwoord=False,
         uitleg="Know hoort bij de werkwoorden die niet in de -ing-vorm gaan. Het moet I have known her for years zijn."),
    dict(type="meerkeuze",
         vraag="Welke zin past bij iemand die nu vuile handen heeft?",
         opties=["I have been gardening.", "I have gardened three times.", "I garden every week.", "I will be gardening."],
         antwoord=0,
         uitleg="De continuous vorm toont een bezigheid waarvan je de sporen nog ziet. De simple vorm telt het resultaat."),
    dict(type="meerkeuze",
         vraag="Welke vraag naar hoelang iemand al Engels leert is juist?",
         opties=["How long have you been learning English?", "How long are you learning English?", "How long do you learn English?", "How long have you learn English?"],
         antwoord=0,
         uitleg="How long vraagt naar een duur die tot nu loopt, dus present perfect. Vaak in de continuous vorm."),
    dict(type="waarofniet",
         vraag="'It has been raining' betekent dat het geregend heeft en dat de straat nog nat is.",
         antwoord=True,
         uitleg="De present perfect legt altijd een verband met nu. Zonder dat verband gebruik je de past simple."),
]
