# -*- coding: utf-8 -*-
"""De verleden en de toekomende tijden.

De vakfiche zet onder de verleden tijd drie vormen:

    past simple · past continuous · past perfect simple

en onder de toekomende tijd twee:

    simple future (WILL future) · going to

Daarbij horen ook de regelmatige en de frequente onregelmatige werkwoorden
uit de tabel met woordsoorten. Die staan in deel 1, want zonder de tweede en
de derde vorm kan je geen enkele verleden tijd maken.

Deel 1 gaat over de past simple en de past continuous.
Deel 2 gaat over de past perfect en over will en going to.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Hoe maak je de past simple van een regelmatig werkwoord?",
         opties=["je zet er -ed achter", "je zet er -ing achter", "je zet did ervoor", "je zet was ervoor"],
         antwoord=0,
         uitleg="Work wordt worked, play wordt played. Did hoort alleen in vragen en ontkenningen."),
    dict(type="invultekst",
         vraag="Schrijf de past simple van 'to study'.",
         antwoord=["studied"],
         uitleg="Een y na een medeklinker wordt i en dan komt ed: studied, tried, carried. Staat er een klinker voor, dan blijft de y: played."),
    dict(type="meerkeuze",
         vraag="Welke past simple vormen zijn juist geschreven?",
         opties=["stopped", "liked", "travelled", "stoped"],
         antwoord=[0, 1, 2],
         uitleg="Bij stop verdubbelt de p. Bij like was er al een e, dus komt er alleen d bij."),
    dict(type="meerkeuze",
         vraag="Wat is de past simple van 'to buy'?",
         opties=["bought", "buyed", "boughted", "buied"],
         antwoord=0,
         uitleg="Buy, bought, bought. Net als bring, brought, brought en think, thought, thought."),
    dict(type="invultekst",
         vraag="Schrijf de past simple van 'to write'.",
         antwoord=["wrote"],
         uitleg="Write, wrote, written. De derde vorm written heb je nodig na have en had."),
    dict(type="meerkeuze",
         vraag="Welke rijen van drie vormen kloppen helemaal?",
         opties=["go, went, gone", "see, saw, seen", "take, took, taken", "drink, drunk, drank"],
         antwoord=[0, 1, 2],
         uitleg="Het is drink, drank, drunk. Eerst de verleden tijd, dan het voltooid deelwoord."),
    dict(type="waarofniet",
         vraag="In een vraag in de past simple gebruik je 'did' en blijft het werkwoord in de basisvorm.",
         antwoord=True,
         uitleg="Did you go to the party? Niet did you went. De verleden tijd zit al in did."),
    dict(type="meerkeuze",
         vraag="Welke ontkennende zin over gisteren is juist?",
         opties=["She didn't come yesterday.", "She didn't came yesterday.", "She don't came yesterday.", "She not came yesterday."],
         antwoord=0,
         uitleg="Didn't neemt de verleden tijd over, dus daarna volgt de basisvorm."),
    dict(type="waarofniet",
         vraag="Bij het werkwoord 'to be' gebruik je in een vraag ook 'did': did you was there?",
         antwoord=False,
         uitleg="To be heeft geen did nodig: were you there? Was hij daar wordt was he there?"),
    dict(type="meerkeuze",
         vraag="Welke vorm van to be hoort bij 'they' in de verleden tijd?",
         opties=["were", "was", "been", "are"],
         antwoord=0,
         uitleg="I, he, she en it nemen was. You, we en they nemen were."),
    dict(type="meerkeuze",
         vraag="Waaruit bestaat de past continuous?",
         opties=["was of were plus -ing", "had plus het deelwoord", "did plus -ing", "am of is plus -ing"],
         antwoord=0,
         uitleg="I was reading, they were playing. Am en is horen bij de tegenwoordige tijd."),
    dict(type="meerkeuze",
         vraag="Welke zin over lezen en een rinkelende telefoon is juist?",
         opties=["I was reading when the phone rang.", "I read when the phone was ringing.", "I was read when the phone rang.", "I was reading when the phone was ring."],
         antwoord=0,
         uitleg="De lange handeling staat in de past continuous, de korte die erdoorheen komt in de past simple."),
    dict(type="invultekst",
         vraag="Vul de juiste vorm van to be in: while we … waiting, it started to rain.",
         antwoord=["were"],
         uitleg="We neemt were. Na while volgt bijna altijd een past continuous."),
    dict(type="waarofniet",
         vraag="Na 'while' staat meestal de langst durende handeling, en na 'when' de korte.",
         antwoord=True,
         uitleg="While I was cooking, he arrived. Hij kwam terwijl het koken al bezig was."),
    dict(type="meerkeuze",
         vraag="Welke zin beschrijft twee dingen die tegelijk bezig waren?",
         opties=["She was cooking while he was setting the table.", "She cooked while he set the table.", "She was cooking when he set the table.", "She cooked when he was setting the table."],
         antwoord=0,
         uitleg="Twee keer de past continuous met while ertussen zegt dat allebei bezig was."),
    dict(type="meerkeuze",
         vraag="Welke zin hoort bij een achtergrond in een verhaal?",
         opties=["The sun was shining and the birds were singing.", "The sun shone and the birds sang once.", "The sun has shone and the birds have sung.", "The sun will shine and the birds will sing."],
         antwoord=0,
         uitleg="De past continuous schildert het decor. De past simple vertelt daarna wat er gebeurde."),
    dict(type="waarofniet",
         vraag="'I was knowing the answer' is een juiste zin.",
         antwoord=False,
         uitleg="Know gaat niet in de -ing-vorm, ook niet in de verleden tijd. Het moet I knew the answer zijn."),
    dict(type="meerkeuze",
         vraag="Welke vraag naar wat iemand om acht uur deed is juist?",
         opties=["What were you doing at eight o'clock?", "What did you doing at eight o'clock?", "What you were doing at eight o'clock?", "What were you do at eight o'clock?"],
         antwoord=0,
         uitleg="In een vraag wisselen were en het onderwerp van plaats."),
    dict(type="meerkeuze",
         vraag="Welk woord verraadt meteen dat je de past simple nodig hebt?",
         opties=["yesterday", "since", "already", "yet"],
         antwoord=0,
         uitleg="Yesterday, last week en ago noemen een afgesloten moment. Since, already en yet horen bij de present perfect."),
    dict(type="waarofniet",
         vraag="'Used to' zegt dat iets vroeger gewoonte was en nu niet meer: I used to play the piano.",
         antwoord=True,
         uitleg="De ontkenning is I didn't use to, zonder d, want de verleden tijd zit al in didn't."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Waaruit bestaat de past perfect simple?",
         opties=["had plus het voltooid deelwoord", "was plus het voltooid deelwoord", "have plus het voltooid deelwoord", "did plus het voltooid deelwoord"],
         antwoord=0,
         uitleg="Had is dezelfde vorm voor elke persoon: I had seen, they had seen."),
    dict(type="meerkeuze",
         vraag="Welke zin over een trein die al weg was is juist?",
         opties=["The train had already left when we arrived.", "The train has already left when we arrived.", "The train had already leave when we arrived.", "The train was already left when we arrived."],
         antwoord=0,
         uitleg="De past perfect zegt wat er nog vroeger gebeurde dan de rest van het verhaal."),
    dict(type="invultekst",
         vraag="Vul het ontbrekende woord in: by the time she called, I … already gone to bed.",
         antwoord=["had"],
         uitleg="Twee momenten in het verleden: het oudste krijgt de past perfect."),
    dict(type="waarofniet",
         vraag="De past perfect gebruik je om te tonen welk van twee dingen in het verleden het eerst gebeurde.",
         antwoord=True,
         uitleg="Zonder dat verschil in tijd volstaat de past simple. Twee keer had is dus zelden nodig."),
    dict(type="meerkeuze",
         vraag="Welke zin klopt qua volgorde in de tijd? 'When I got home, my brother had cooked dinner.'",
         opties=["hij kookte eerst en daarna kwam ik thuis", "ik kwam eerst thuis en daarna kookte hij", "we deden allebei tegelijk iets", "het is nog niet gebeurd"],
         antwoord=0,
         uitleg="De past perfect staat bij wat het eerst gebeurde. Stond er had cooked niet, dan las je het als daarna."),
    dict(type="meerkeuze",
         vraag="Welke zinnen hebben terecht een past perfect?",
         opties=["She had never seen the sea before that trip.",
                 "They had finished the test before the bell rang.",
                 "I had left my key at home, so I could not get in.",
                 "Yesterday I had walked to school."],
         antwoord=[0, 1, 2],
         uitleg="Yesterday I walked to school volstaat: er is geen tweede, later moment om mee te vergelijken."),
    dict(type="waarofniet",
         vraag="Na 'after' en 'before' is de past perfect vaak overbodig, want die woorden zeggen zelf al wat eerst kwam.",
         antwoord=True,
         uitleg="After she finished, she went home leest even helder als after she had finished. Allebei mag."),
    dict(type="meerkeuze",
         vraag="Welke zin gebruikt 'will' op de juiste manier?",
         opties=["That bag looks heavy. I'll help you.", "That bag looks heavy. I help you.", "That bag looks heavy. I am going to help you now.", "That bag looks heavy. I will to help you."],
         antwoord=0,
         uitleg="Will hoort bij een beslissing die je nu, op het moment zelf neemt. En na will komt geen to."),
    dict(type="meerkeuze",
         vraag="Wanneer gebruik je 'going to'?",
         opties=["voor een plan dat je al had", "voor een beslissing op het moment zelf", "voor een gewoonte", "voor iets dat al afgelopen is"],
         antwoord=0,
         uitleg="I'm going to study medicine zegt dat je dat al van plan was. Will klinkt spontaner."),
    dict(type="invultekst",
         vraag="Vul aan met twee woorden: look at those clouds, it … to rain. Gebruik de vorm die bij een voorspelling met bewijs hoort.",
         antwoord=["is going"],
         uitleg="Je ziet het al aankomen, dus going to. Will zou een gok zonder bewijs zijn."),
    dict(type="waarofniet",
         vraag="Na 'will' zet je het werkwoord met to ervoor: she will to come.",
         antwoord=False,
         uitleg="Het is she will come. Na will volgt de kale basisvorm, en will krijgt zelf nooit een s in de derde persoon."),
    dict(type="meerkeuze",
         vraag="Welke zin past bij een belofte?",
         opties=["I promise I won't tell anyone.", "I promise I don't tell anyone.", "I promise I am not telling anyone.", "I promise I didn't tell anyone."],
         antwoord=0,
         uitleg="Won't is de korte vorm van will not. Bij een belofte of een aanbod hoort will."),
    dict(type="meerkeuze",
         vraag="Welke zinnen kijken naar de toekomst?",
         opties=["We will see.", "She is going to move house.", "The train leaves at six tomorrow.", "He had left before noon."],
         antwoord=[0, 1, 2],
         uitleg="Bij een dienstregeling gebruik je zelfs de present simple. De laatste zin staat in de past perfect."),
    dict(type="waarofniet",
         vraag="Na 'if' en 'when' zet je in het Engels geen will: I will call you when I will arrive.",
         antwoord=False,
         uitleg="Precies daarom is die zin fout. Het moet I will call you when I arrive zijn: na when en if blijft het werkwoord in de tegenwoordige tijd."),
    dict(type="meerkeuze",
         vraag="Welke zin over regen en thuisblijven is juist?",
         opties=["If it rains, we will stay at home.", "If it will rain, we will stay at home.", "If it rains, we stay at home tomorrow.", "If it will rain, we stay at home."],
         antwoord=0,
         uitleg="In de bijzin met if staat de present simple, in de hoofdzin will."),
    dict(type="invultekst",
         vraag="Schrijf de korte vorm van 'will not'.",
         antwoord=["won't"],
         uitleg="Won't, met een o en een apostrof. Het is een van de weinige korte vormen die er helemaal anders uitziet."),
    dict(type="meerkeuze",
         vraag="Welke vorm gebruik je voor iets dat morgen bezig zal zijn?",
         opties=["will be plus -ing", "will plus het deelwoord", "going to been plus -ing", "had been plus -ing"],
         antwoord=0,
         uitleg="This time tomorrow I will be flying to Dublin. Dat heet de future continuous."),
    dict(type="waarofniet",
         vraag="'Shall' komt in het moderne Engels vooral voor in vragen zoals 'Shall I open the window?'",
         antwoord=True,
         uitleg="Shall I en shall we bieden iets aan of stellen iets voor. Voor de gewone toekomst gebruikt men will."),
    dict(type="meerkeuze",
         vraag="Welke zin hoort bij 'Ik had het boek al gelezen voor de film uitkwam.'?",
         opties=["I had already read the book before the film came out.",
                 "I have already read the book before the film came out.",
                 "I already read the book before the film was coming out.",
                 "I had already readed the book before the film came out."],
         antwoord=0,
         uitleg="Read blijft in alle drie de vormen hetzelfde geschreven, maar je spreekt de verleden tijd uit als red."),
    dict(type="meerkeuze",
         vraag="Welke vraag naar iemands verblijfplaats volgende week is juist?",
         opties=["Where will you be next week?", "Where you will be next week?", "Where will be you next week?", "Where you be will next week?"],
         antwoord=0,
         uitleg="In een vraag wisselen will en het onderwerp van plaats, net als bij de andere hulpwerkwoorden."),
]
