# -*- coding: utf-8 -*-
"""Pronouns: de zeven soorten.

De vakfiche zet zeven soorten voornaamwoorden op een rij die je moet kunnen
toepassen: persoonlijk, aanwijzend, bezittelijk, vragend, betrekkelijk,
onbepaald en wederkerend. Ze geeft er zelf een reden bij: een voornaamwoord
verwijst naar iets uit een vorige zin, en met het verkeerde voornaamwoord is
niet meer duidelijk naar wie of wat je verwijst.

Deel 1 neemt de vier soorten die naar de spreker en de dingen rondom hem
verwijzen: persoonlijk, bezittelijk, wederkerend en aanwijzend.
Deel 2 neemt de drie andere: vragend, betrekkelijk en onbepaald.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Welke zin over een bezoek aan de cinema is juist?",
         opties=["She and I went to the cinema.", "Her and me went to the cinema.", "She and me went to the cinema.", "Her and I went to the cinema."],
         antwoord=0,
         uitleg="Wie de handeling doet, staat in de onderwerpsvorm: I, you, he, she, we, they. Laat de andere persoon even weg en je hoort het: I went, niet me went."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn voorwerpsvormen van het persoonlijk voornaamwoord?",
         opties=["me", "him", "them", "they"],
         antwoord=[0, 1, 2],
         uitleg="De voorwerpsvormen zijn me, you, him, her, it, us, them. They is een onderwerpsvorm."),
    dict(type="invultekst",
         vraag="Vul het juiste voornaamwoord in: my parents called … yesterday, en het gaat over jezelf.",
         antwoord=["me"],
         uitleg="Na het werkwoord staat de voorwerpsvorm. Het onderwerp van die zin is my parents."),
    dict(type="waarofniet",
         vraag="Na een voorzetsel gebruik je in het Engels de voorwerpsvorm: this is for her.",
         antwoord=True,
         uitleg="Ook bij between you and me, en niet between you and I, hoe deftig dat laatste ook klinkt."),
    dict(type="meerkeuze",
         vraag="Waar verwijst 'it' meestal naar?",
         opties=["een ding of een dier", "een vrouw", "een groep mensen", "de spreker zelf"],
         antwoord=0,
         uitleg="Voor dieren gebruikt men it, tenzij het een huisdier met een naam is. Dan wordt het he of she."),
    dict(type="meerkeuze",
         vraag="Welke zin vraagt correct van wie een boek is?",
         opties=["Is this your book?", "Is this yours book?", "Is this you book?", "Is this your's book?"],
         antwoord=0,
         uitleg="Your staat voor een naamwoord. Yours staat alleen: is this book yours? En yours schrijf je nooit met een apostrof."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn zelfstandige bezittelijke voornaamwoorden, die alleen kunnen staan?",
         opties=["mine", "hers", "theirs", "their"],
         antwoord=[0, 1, 2],
         uitleg="Mine, yours, his, hers, ours en theirs staan alleen. Their hoort voor een naamwoord: their house."),
    dict(type="waarofniet",
         vraag="'Its' en 'it's' betekenen hetzelfde.",
         antwoord=False,
         uitleg="Its is bezittelijk: the dog wagged its tail. It's is de korte vorm van it is of it has."),
    dict(type="invultekst",
         vraag="Vul aan zonder apostrof: the cat has hurt … paw.",
         antwoord=["its"],
         uitleg="Hier gaat het over de poot van de kat, dus de bezittelijke vorm its."),
    dict(type="meerkeuze",
         vraag="Welke zin zegt correct dat je jezelf pijn deed?",
         opties=["I hurt myself.", "I hurt me.", "I hurt mineself.", "I hurt my self."],
         antwoord=0,
         uitleg="Slaat de handeling terug op het onderwerp, dan neem je de wederkerende vorm op -self of -selves."),
    dict(type="meerkeuze",
         vraag="Welke wederkerende voornaamwoorden zijn juist geschreven?",
         opties=["himself", "ourselves", "themselves", "theirselves"],
         antwoord=[0, 1, 2],
         uitleg="Theirselves en hisself bestaan niet. Het meervoud gaat op -selves: ourselves, yourselves, themselves."),
    dict(type="waarofniet",
         vraag="Je gebruikt 'by myself' om te zeggen dat je iets alleen doet.",
         antwoord=True,
         uitleg="I did it by myself betekent zonder hulp. I did it myself legt de nadruk op wie het deed."),
    dict(type="meerkeuze",
         vraag="In welke zin hoort er géén wederkerend voornaamwoord?",
         opties=["She washed and got dressed.", "He hurt himself on the stairs.", "They introduced themselves.", "I taught myself to cook."],
         antwoord=0,
         uitleg="Wash en dress zijn in het Engels niet wederkerend. Wij zeggen zich wassen, het Engels zegt gewoon she washed."),
    dict(type="meerkeuze",
         vraag="Welk aanwijzend voornaamwoord hoort bij iets dat dicht bij je is en waarvan er meer dan één is?",
         opties=["these", "this", "that", "those"],
         antwoord=0,
         uitleg="Dichtbij is this en these, veraf is that en those. Enkelvoud is this en that, meervoud these en those."),
    dict(type="invultekst",
         vraag="Vul aan met één woord: … shoes over there are mine.",
         antwoord=["those"],
         uitleg="Over there zegt dat ze ver zijn, en shoes is meervoud. Dus those."),
    dict(type="waarofniet",
         vraag="'This' en 'these' gebruik je voor iets dat ver van je weg is.",
         antwoord=False,
         uitleg="This en these zijn juist voor wat dichtbij is. Voor wat verder weg is, neem je that en those."),
    dict(type="meerkeuze",
         vraag="Waarom is deze zin onduidelijk? 'Tom told Ben that he had passed.'",
         opties=["je weet niet wie geslaagd is", "he mag niet na that staan", "told hoort er niet bij", "er ontbreekt een lidwoord"],
         antwoord=0,
         uitleg="He kan naar Tom of naar Ben verwijzen. Schrijf dan liever: Tom told Ben that Ben had passed."),
    dict(type="meerkeuze",
         vraag="Welke zin verwijst duidelijk?",
         opties=["The teachers helped the pupils, and the pupils thanked them.",
                 "The teachers helped the pupils, and they thanked them.",
                 "The teachers helped the pupils, and they thanked they.",
                 "The teachers helped the pupils, and them thanked they."],
         antwoord=0,
         uitleg="Zodra twee groepen meervoud zijn, wordt they onduidelijk. Herhaal dan het naamwoord."),
    dict(type="waarofniet",
         vraag="In het Engels heb je één woord voor jij en u: you.",
         antwoord=True,
         uitleg="You is enkelvoud én meervoud, beleefd én gewoon. Beleefdheid toon je met andere woorden, bijvoorbeeld met could you."),
    dict(type="meerkeuze",
         vraag="Welke zin over een huis met een tuin is juist?",
         opties=["The house and its garden are for sale.", "The house and it's garden are for sale.", "The house and his garden are for sale.", "The house and their garden are for sale."],
         antwoord=0,
         uitleg="Een huis is een ding, dus its. His hoort bij een man, their bij een groep."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Welk vragend voornaamwoord vraagt naar een persoon als onderwerp?",
         opties=["who", "whose", "which", "what"],
         antwoord=0,
         uitleg="Who broke the window? Whose vraagt naar de eigenaar, which naar een keuze uit een beperkte groep."),
    dict(type="meerkeuze",
         vraag="Welke vraagwoorden vragen naar een persoon of een bezit?",
         opties=["who", "whom", "whose", "where"],
         antwoord=[0, 1, 2],
         uitleg="Where vraagt naar een plaats. Whom is de voorwerpsvorm van who en klinkt formeel: to whom did you speak?"),
    dict(type="invultekst",
         vraag="Vul aan met één vraagwoord: … bag is this? Je vraagt naar de eigenaar.",
         antwoord=["whose"],
         uitleg="Whose vraagt naar het bezit. Verwar het niet met who's, de korte vorm van who is."),
    dict(type="waarofniet",
         vraag="'Which' gebruik je als er een beperkte keuze is, 'what' als de keuze open is.",
         antwoord=True,
         uitleg="Which colour do you want, red or blue? tegenover What colour do you want?"),
    dict(type="meerkeuze",
         vraag="Welke zin vraagt correct wie er vanavond komt?",
         opties=["Who's coming tonight?", "Whose coming tonight?", "Who is's coming tonight?", "Whos coming tonight?"],
         antwoord=0,
         uitleg="Who's is de korte vorm van who is. Whose is bezittelijk."),
    dict(type="meerkeuze",
         vraag="Welk betrekkelijk voornaamwoord hoort bij een persoon?",
         opties=["who", "which", "where", "when"],
         antwoord=0,
         uitleg="The woman who lives next door. Which hoort bij dingen, en that kan bij allebei."),
    dict(type="meerkeuze",
         vraag="Welke betrekkelijke voornaamwoorden kan je bij een ding gebruiken?",
         opties=["which", "that", "whose", "who"],
         antwoord=[0, 1, 2],
         uitleg="Whose kan ook bij een ding: the house whose roof is red. Who houd je voor personen."),
    dict(type="invultekst",
         vraag="Vul het betrekkelijk voornaamwoord in: the shop … sells old records is closed. Gebruik het woord voor dingen dat met wh begint.",
         antwoord=["which"],
         uitleg="That mag hier ook, maar de vraag vroeg naar het woord met wh."),
    dict(type="waarofniet",
         vraag="In de zin 'the book that I read' mag je 'that' weglaten.",
         antwoord=True,
         uitleg="Volgt er meteen een nieuw onderwerp, dan mag het betrekkelijk voornaamwoord weg: the book I read. Is het zelf het onderwerp, dan moet het blijven staan."),
    dict(type="meerkeuze",
         vraag="Welk woord hoort in de plaats van de puntjes? This is the town … I was born.",
         opties=["where", "which", "who", "whose"],
         antwoord=0,
         uitleg="Where verwijst naar een plaats, when naar een tijd en why naar een reden."),
    dict(type="meerkeuze",
         vraag="Welke zin over de dag van een ontmoeting is juist?",
         opties=["I remember the day when we met.", "I remember the day where we met.", "I remember the day which we met.", "I remember the day who we met."],
         antwoord=0,
         uitleg="Bij een tijdstip hoort when. Where hoort bij een plaats."),
    dict(type="waarofniet",
         vraag="In het Engels mag je 'what' gebruiken als betrekkelijk voornaamwoord: the film what I saw.",
         antwoord=False,
         uitleg="Dat hoor je wel in spreektaal, maar het is fout. Het moet the film that I saw of the film I saw zijn."),
    dict(type="meerkeuze",
         vraag="Welke zin over een vergeten paraplu is juist?",
         opties=["Somebody has left their umbrella.", "Somebody have left their umbrella.", "Somebody are leaving their umbrella.", "Somebody were leaving their umbrella."],
         antwoord=0,
         uitleg="Onbepaalde voornaamwoorden op -body en -one zijn enkelvoud, dus has. Their is een gewone manier geworden om iemand te bedoelen van wie je het geslacht niet weet."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn onbepaalde voornaamwoorden?",
         opties=["someone", "anything", "nobody", "himself"],
         antwoord=[0, 1, 2],
         uitleg="Himself is wederkerend. Onbepaald zijn ook everybody, everything, none en each."),
    dict(type="invultekst",
         vraag="Vul aan met één woord: there is … in the room, de kamer is leeg.",
         antwoord=["nobody", "no one"],
         uitleg="Nobody of no one. Let op: not anybody kan ook, maar dan moet er een ontkenning bij: there isn't anybody."),
    dict(type="waarofniet",
         vraag="'Everybody' vraagt in het Engels een werkwoord in het meervoud.",
         antwoord=False,
         uitleg="Everybody is grammaticaal enkelvoud: everybody is here. Al voelt het als een groep."),
    dict(type="meerkeuze",
         vraag="Welke ontkennende zin over zien is juist?",
         opties=["I didn't see anything.", "I didn't see nothing.", "I don't saw anything.", "I didn't saw nothing."],
         antwoord=0,
         uitleg="Twee ontkenningen in één zin mag niet in het Engels. Het is didn't ... anything of saw nothing."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'none of them came'?",
         opties=["niemand van hen is gekomen", "enkelen van hen zijn gekomen", "iedereen van hen is gekomen", "de meesten van hen zijn gekomen"],
         antwoord=0,
         uitleg="None is de ontkenning van all. Enkelen zijn some of them, iedereen is all of them."),
    dict(type="waarofniet",
         vraag="In vragen en ontkenningen gebruik je meestal 'anything' en niet 'something'.",
         antwoord=True,
         uitleg="Do you need anything? I don't need anything. Bied je iets aan, dan mag something: would you like something to drink?"),
    dict(type="meerkeuze",
         vraag="Welk voornaamwoord past het best? Each of the students … a laptop.",
         opties=["has", "have", "are having", "were having"],
         antwoord=0,
         uitleg="Each is enkelvoud, ook al volgt er een meervoud achter of. Dus has."),
]
