# -*- coding: utf-8 -*-
"""Woordvelden: school, werk, reizen en de samenleving.

Het tweede woordveldenthema. Uit de lijst van de vakfiche neemt dit thema:

    onderwijs en vorming · instructietaal · professionele wereld (beroepen)
    transportmiddelen · vakantie en reizen · winkels en diensten · weer
    uur en plaats · communicatie en multimedia · sport en ontspanning

Deel 1 gaat over de school en het werk, deel 2 over onderweg zijn, inkopen
doen en contact houden.

De maten, de datumnotatie en de feesten staan bij het thema over de
Engelstalige wereld, want daar gaat het over het verschil tussen Brits en
Amerikaans. Hier gaat het over de woorden zelf.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Hoe heet in het Verenigd Koninkrijk de school voor kinderen van ongeveer vier tot elf jaar?",
         opties=["primary school", "secondary school", "nursery", "college"],
         antwoord=0,
         uitleg="Daarna volgt de secondary school. Een nursery is de opvang voor de allerkleinsten."),
    dict(type="meerkeuze",
         vraag="Welke woorden horen bij het schoolleven?",
         opties=["timetable", "subject", "term", "receipt"],
         antwoord=[0, 1, 2],
         uitleg="Timetable is het lessenrooster, subject een vak en term een trimester. Een receipt is een kassabon."),
    dict(type="invultekst",
         vraag="Hoe heet in het Engels de persoon die een Britse school leidt?",
         antwoord=["headteacher", "head teacher", "the headteacher"],
         uitleg="Headteacher of head is de Britse term. In de Verenigde Staten zegt men principal."),
    dict(type="waarofniet",
         vraag="'To sit an exam' betekent dat je een examen aflegt.",
         antwoord=True,
         uitleg="Je sit an exam, en daarna pass of fail je. Moet je het overdoen, dan resit je het."),
    dict(type="meerkeuze",
         vraag="Je krijgt je punten terug en er staat 'You passed.' Wat betekent dat?",
         opties=["je bent geslaagd", "je bent gebuisd", "je moet het overdoen", "je was afwezig"],
         antwoord=0,
         uitleg="Gebuisd is to fail, overdoen is to resit en afwezig is absent."),
    dict(type="waarofniet",
         vraag="Het Engelse woord 'college' betekent altijd hetzelfde als ons woord college.",
         antwoord=False,
         uitleg="In het Verenigd Koninkrijk is een college een school na je zestiende, in de Verenigde Staten is het de universiteit. Een les bij ons heet in het Engels a lesson of a class."),
    dict(type="meerkeuze",
         vraag="In een opdracht staat: 'Tick the correct box.' Wat moet je doen?",
         opties=["het juiste vakje aankruisen", "het juiste woord onderlijnen", "het juiste woord omcirkelen", "de juiste zin overschrijven"],
         antwoord=0,
         uitleg="Onderlijnen is underline, omcirkelen is circle en overschrijven is copy."),
    dict(type="meerkeuze",
         vraag="Welke opdrachtwoorden vragen dat je zelf iets schrijft en niet alleen aanduidt?",
         opties=["summarise", "explain", "describe", "underline"],
         antwoord=[0, 1, 2],
         uitleg="Summarise is samenvatten, explain uitleggen en describe beschrijven. Underline vraagt enkel een streep."),
    dict(type="invultekst",
         vraag="In een opdracht staat 'Fill in the gaps.' Welk Nederlands woord vertaalt 'gaps' hier?",
         antwoord=["gaten", "de gaten", "hiaten", "leemtes"],
         uitleg="De gaten in een tekst invullen. Je komt de opdracht ook tegen als complete the sentences."),
    dict(type="waarofniet",
         vraag="Bij de opdracht 'Match the words with the pictures' moet je de woorden vertalen.",
         antwoord=False,
         uitleg="To match betekent bij elkaar zoeken. Je verbindt elk woord met de juiste afbeelding."),
    dict(type="meerkeuze",
         vraag="Welk beroep hoort bij iemand die leidingen en kranen herstelt?",
         opties=["a plumber", "a carpenter", "a butcher", "an engineer"],
         antwoord=0,
         uitleg="Een carpenter is een schrijnwerker, een butcher een slager en een engineer een ingenieur."),
    dict(type="meerkeuze",
         vraag="Welke woorden noemen een beroep in de gezondheidszorg?",
         opties=["nurse", "surgeon", "midwife", "solicitor"],
         antwoord=[0, 1, 2],
         uitleg="Nurse is verpleegkundige, surgeon chirurg en midwife vroedvrouw. Een solicitor is een advocaat."),
    dict(type="invultekst",
         vraag="Hoe heet in het Engels iemand die huizen verkoopt en verhuurt, met twee woorden?",
         antwoord=["estate agent", "an estate agent"],
         uitleg="In de Verenigde Staten heet dat een realtor of een real estate agent."),
    dict(type="waarofniet",
         vraag="Een 'chef' is in het Engels iemand die de leiding heeft over een bedrijf.",
         antwoord=False,
         uitleg="Een chef is een kok in een restaurant. De baas van een bedrijf is the boss, the manager of the chief executive."),
    dict(type="meerkeuze",
         vraag="Je solliciteert. Welk document stuur je met je brief mee?",
         opties=["your CV", "your timetable", "your receipt", "your licence"],
         antwoord=0,
         uitleg="CV staat voor curriculum vitae. De brief erbij heet a covering letter of in de VS a cover letter."),
    dict(type="meerkeuze",
         vraag="Welke woorden horen bij het zoeken en krijgen van werk?",
         opties=["apply for a job", "a job interview", "a salary", "a hospital"],
         antwoord=[0, 1, 2],
         uitleg="Je applies for a job, je gaat naar a job interview en je verdient a salary. Let op het voorzetsel: apply for."),
    dict(type="waarofniet",
         vraag="Wie 'part-time' werkt, werkt minder uren dan iemand die full-time werkt.",
         antwoord=True,
         uitleg="Full-time is een voltijdse baan. Werk in ploegen heet shift work."),
    dict(type="meerkeuze",
         vraag="Iemand zegt: 'I resigned last month.' Wat is er gebeurd?",
         opties=["die persoon heeft zelf ontslag genomen", "die persoon is ontslagen", "die persoon is met pensioen", "die persoon is van functie veranderd"],
         antwoord=0,
         uitleg="To resign is zelf opstappen. Ontslagen worden is to be fired of to be made redundant, en met pensioen gaan is to retire."),
    dict(type="waarofniet",
         vraag="'Work' is in het Engels meestal een ontelbaar woord: je zegt I have a lot of work.",
         antwoord=True,
         uitleg="Daarom zeg je niet 'two works'. Een afzonderlijke baan is a job, en die is wel telbaar."),
    dict(type="meerkeuze",
         vraag="Welk woord hoort er niet bij de andere drie?",
         opties=["platform", "headteacher", "pupil", "classroom"],
         antwoord=0,
         uitleg="Headteacher, pupil en classroom horen bij de school. Een platform is een perron in een station."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Je wil met de trein heen en terug. Welk ticket vraag je in het Verenigd Koninkrijk?",
         opties=["a return ticket", "a single ticket", "a season ticket", "a platform ticket"],
         antwoord=0,
         uitleg="Enkel heen is a single. In de Verenigde Staten zegt men a round trip en a one way ticket."),
    dict(type="waarofniet",
         vraag="Een 'subway' is in het Verenigd Koninkrijk hetzelfde als in de Verenigde Staten.",
         antwoord=False,
         uitleg="In de VS is een subway de metro. In het VK is een subway een tunnel voor voetgangers, en de metro van Londen heet the Underground of the Tube."),
    dict(type="meerkeuze",
         vraag="Welke woorden noemen een vervoermiddel?",
         opties=["a coach", "a ferry", "a tram", "a platform"],
         antwoord=[0, 1, 2],
         uitleg="Een coach is een touringcar en een ferry een veerboot. Een platform is het perron waar je opstapt."),
    dict(type="invultekst",
         vraag="Hoe heet in het Engels het perron waar je op de trein stapt?",
         antwoord=["platform", "the platform", "a platform"],
         uitleg="Je leest het op de borden: Platform 4 for the 9.15 to Cardiff."),
    dict(type="meerkeuze",
         vraag="Op het bord staat: 'The 10.20 to Leeds is delayed by 15 minutes.' Wat betekent dat?",
         opties=["de trein heeft een kwartier vertraging", "de trein is afgeschaft", "de trein vertrekt een kwartier vroeger", "de trein stopt niet in Leeds"],
         antwoord=0,
         uitleg="A delay is een vertraging. Afgeschaft is cancelled."),
    dict(type="waarofniet",
         vraag="'Luggage' krijgt geen meervoud-s: je zegt my luggage is heavy.",
         antwoord=True,
         uitleg="Luggage is ontelbaar, net als information en furniture. Eén stuk is a piece of luggage of a suitcase."),
    dict(type="meerkeuze",
         vraag="Welke woorden horen bij een overnachting op reis?",
         opties=["a youth hostel", "a campsite", "a bed and breakfast", "a checkout"],
         antwoord=[0, 1, 2],
         uitleg="Een youth hostel is een jeugdherberg en een campsite een camping. De checkout is de kassa in een winkel."),
    dict(type="invultekst",
         vraag="Hoe heet in het Engels het kaartje dat je op de luchthaven krijgt om aan boord te mogen, met twee woorden?",
         antwoord=["boarding pass", "a boarding pass", "boarding card"],
         uitleg="Je krijgt het als je incheckt: to check in."),
    dict(type="meerkeuze",
         vraag="Waar koop je in het Verenigd Koninkrijk kranten, tijdschriften en snoep?",
         opties=["at the newsagent's", "at the butcher's", "at the greengrocer's", "at the stationer's"],
         antwoord=0,
         uitleg="De butcher's is de slager, de greengrocer's de groentewinkel en de stationer's de papierwinkel. Let op de apostrof met s."),
    dict(type="meerkeuze",
         vraag="Je hebt iets gekocht dat stuk is. Wat vraag je in de winkel?",
         opties=["a refund", "a receipt", "a discount", "a delivery"],
         antwoord=0,
         uitleg="A refund is je geld terug. A receipt is het kassaticket dat je daarvoor nodig hebt, en a discount is een korting."),
    dict(type="waarofniet",
         vraag="De 'till' in een Britse winkel is de plaats waar je betaalt.",
         antwoord=True,
         uitleg="Till of checkout. In de Verenigde Staten zegt men vaker register of checkout."),
    dict(type="meerkeuze",
         vraag="Het regent heel fijn en heel licht. Welk woord past?",
         opties=["drizzle", "downpour", "hail", "thunder"],
         antwoord=0,
         uitleg="Een downpour is een stortbui, hail is hagel en thunder is donder."),
    dict(type="meerkeuze",
         vraag="Welke woorden beschrijven het weer?",
         opties=["mild", "freezing", "foggy", "crowded"],
         antwoord=[0, 1, 2],
         uitleg="Mild is zacht, freezing is ijskoud en foggy is mistig. Crowded betekent druk met mensen."),
    dict(type="invultekst",
         vraag="Hoe heet in het Engels de weersvoorspelling, met één woord?",
         antwoord=["forecast", "the forecast", "weather forecast"],
         uitleg="Je hoort het op de radio: and now the weather forecast for tomorrow."),
    dict(type="meerkeuze",
         vraag="Hoe laat is het als iemand zegt 'half past seven'?",
         opties=["7.30", "6.30", "7.15", "8.30"],
         antwoord=0,
         uitleg="Het Engels telt vanaf het uur dat voorbij is: half past seven is een half uur na zeven. Ons 'half acht' noemt juist het uur dat komt."),
    dict(type="waarofniet",
         vraag="'Quarter to nine' is hetzelfde uur als 9.15.",
         antwoord=False,
         uitleg="Quarter to nine is 8.45, want to betekent naar. 9.15 is quarter past nine."),
    dict(type="invultekst",
         vraag="Hoeveel weken duurt 'a fortnight'? Antwoord met een cijfer.",
         antwoord=["2", "twee", "two"],
         uitleg="A fortnight zijn twee weken. Het woord komt van fourteen nights."),
    dict(type="meerkeuze",
         vraag="Welke zin zegt dat de bakker vlak bij je is?",
         opties=["it's just around the corner", "it's miles away", "it's across the country", "it's up in the hills"],
         antwoord=0,
         uitleg="Andere plaatsbepalingen: opposite the station, next to the bank, at the end of the road."),
    dict(type="meerkeuze",
         vraag="Welke werkwoorden horen bij het internet en de telefoon?",
         opties=["to log in", "to upload", "to scroll", "to iron"],
         antwoord=[0, 1, 2],
         uitleg="Inloggen, opladen naar het internet en scrollen. To iron betekent strijken."),
    dict(type="meerkeuze",
         vraag="Welk werkwoord hoort bij 'football': you … football.",
         opties=["play", "go", "do", "make"],
         antwoord=0,
         uitleg="Bij balsporten hoort play: play tennis, play hockey. Bij sporten op -ing hoort go: go swimming, go cycling. Bij de rest hoort do: do yoga, do judo."),
]
