# -*- coding: utf-8 -*-
"""Zinsdelen, soorten zinnen en bijzinnen.

De vakfiche zet onder zinsbouw vier rijen:

    soorten zinnen        ontkennend, mededelend, vragend, bevelend, uitroepend
    enkelvoudige en       nevenschikking, onderschikking, voorwaardelijke
    samengestelde zinnen  bijzinnen (conditionals: zero en first),
                          betrekkelijke bijzinnen met that, who, whose, which,
                          when, where en why
    congruentie           overeenkomst onderwerp - persoonsvorm
    zinsdelen             onderwerp, persoonsvorm, lijdend en meewerkend voorwerp

De fiche zegt er ook bij waarom: "Je maakt je verhaal levendig door te
variëren tussen verschillende soorten zinnen."

Deel 1 gaat over de bouwstenen van één zin: de zinsdelen, de woordvolgorde,
de vijf soorten zinnen en de congruentie. Deel 2 gaat over zinnen aan elkaar
knopen: voegwoorden, bijzinnen en de conditionals zero en first.

Welk betrekkelijk voornaamwoord je kiest, staat bij het thema over de
pronouns. Hier gaat het over de bijzin als geheel.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is het onderwerp in 'My little sister reads three books a week'?",
         opties=["my little sister", "reads", "three books", "a week"],
         antwoord=0,
         uitleg="Het onderwerp is wie of wat de persoonsvorm doet. Je vindt het door te vragen: wie leest?"),
    dict(type="meerkeuze",
         vraag="Wat is de persoonsvorm in 'The children were playing outside'?",
         opties=["were", "playing", "the children", "outside"],
         antwoord=0,
         uitleg="De persoonsvorm is het werkwoord dat met het onderwerp meeverandert. Playing verandert niet mee."),
    dict(type="invultekst",
         vraag="Wat is het lijdend voorwerp in 'She wrote a long letter'? Antwoord met de Engelse woorden.",
         antwoord=["a long letter", "letter", "long letter"],
         uitleg="Het lijdend voorwerp ondergaat de handeling. Je vindt het met: wat schreef ze?"),
    dict(type="meerkeuze",
         vraag="Wat is het meewerkend voorwerp in 'He gave his friend a present'?",
         opties=["his friend", "a present", "he", "gave"],
         antwoord=0,
         uitleg="Het meewerkend voorwerp is voor wie of aan wie iets gebeurt. Je kan het ook schrijven als he gave a present to his friend."),
    dict(type="waarofniet",
         vraag="Staat het meewerkend voorwerp achter het lijdend voorwerp, dan komt er 'to' of 'for' voor.",
         antwoord=True,
         uitleg="She sent him a card, of she sent a card to him. Zonder voorzetsel staat het meewerkend voorwerp eerst."),
    dict(type="meerkeuze",
         vraag="Welke volgorde is de gewone in een Engelse mededelende zin?",
         opties=["onderwerp, persoonsvorm, rest", "persoonsvorm, onderwerp, rest", "rest, persoonsvorm, onderwerp", "onderwerp, rest, persoonsvorm"],
         antwoord=0,
         uitleg="Het Engels houdt die volgorde veel strenger vast dan het Nederlands. Daarom staat er nooit gisteren ging ik, maar yesterday I went."),
    dict(type="meerkeuze",
         vraag="Welke zin over het leuk vinden van een film is juist?",
         opties=["I like this film very much.", "I like very much this film.", "I very much like this film today here.", "I like this very much film."],
         antwoord=0,
         uitleg="Zet nooit iets tussen het werkwoord en zijn lijdend voorwerp. De bepaling komt erachter."),
    dict(type="meerkeuze",
         vraag="Welke zin heeft de bepalingen in de gewone Engelse volgorde?",
         opties=["She sang beautifully at the concert last night.",
                 "She sang last night beautifully at the concert.",
                 "She sang at the concert beautifully last night.",
                 "Last night she sang at the concert beautifully."],
         antwoord=0,
         uitleg="Eerst hoe, dan waar, dan wanneer. Het Nederlands doet het net omgekeerd, en dat hoor je meteen."),
    dict(type="waarofniet",
         vraag="In het Engels mag je na een bepaling vooraan het onderwerp en de persoonsvorm omwisselen: yesterday went I home.",
         antwoord=False,
         uitleg="Dat doet het Nederlands wel, het Engels niet. Het blijft yesterday I went home."),
    dict(type="meerkeuze",
         vraag="Welk soort zin is 'What a beautiful garden!'?",
         opties=["een uitroepende zin", "een vragende zin", "een bevelende zin", "een ontkennende zin"],
         antwoord=0,
         uitleg="Uitroepende zinnen beginnen met what a plus een naamwoord, of met how plus een bijvoeglijk naamwoord: how kind of you!"),
    dict(type="meerkeuze",
         vraag="Welke zinnen zijn uitroepend?",
         opties=["How lovely!", "What a mess!", "How fast she runs!", "How do you do it?"],
         antwoord=[0, 1, 2],
         uitleg="De laatste is een gewone vraag met een vraagteken. Bij een uitroep draait de volgorde niet om."),
    dict(type="invultekst",
         vraag="Vul aan met twee woorden: … day it is! Je roept uit dat het een prachtige dag is en er volgt nog 'a lovely'.",
         antwoord=["what a"],
         uitleg="Bij een telbaar naamwoord in het enkelvoud: what a lovely day it is! Bij how volgt meteen een bijvoeglijk naamwoord: how lovely!"),
    dict(type="meerkeuze",
         vraag="Hoe maak je van 'She plays tennis' een vraag?",
         opties=["Does she play tennis?", "Plays she tennis?", "Does she plays tennis?", "She plays tennis?"],
         antwoord=0,
         uitleg="Zonder hulpwerkwoord in de zin haal je do, does of did erbij. Daarna blijft het werkwoord kaal."),
    dict(type="waarofniet",
         vraag="Staat er al een hulpwerkwoord in de zin, dan heb je voor een vraag geen 'do' nodig.",
         antwoord=True,
         uitleg="Is she coming? Have you finished? Can he swim? Het hulpwerkwoord schuift gewoon naar voren."),
    dict(type="meerkeuze",
         vraag="Welke aanhangvraag hoort bij 'You're coming tonight, …?'",
         opties=["aren't you", "are you", "don't you", "isn't it"],
         antwoord=0,
         uitleg="Is de zin bevestigend, dan is de aanhangvraag ontkennend, en omgekeerd: you aren't coming, are you?"),
    dict(type="meerkeuze",
         vraag="Welke zin over twee mensen die samen uitgaan is juist?",
         opties=["My brother and I are going out.", "My brother and I is going out.", "My brother and me is going out.", "My brother and I am going out."],
         antwoord=0,
         uitleg="Twee onderwerpen samen zijn meervoud, dus are. Dat heet congruentie: het werkwoord past zich aan het onderwerp aan."),
    dict(type="meerkeuze",
         vraag="In welke zinnen past de persoonsvorm bij het onderwerp?",
         opties=["The news is good.", "Everybody was there.", "The police are looking for him.", "My family are big."],
         antwoord=[0, 1, 2],
         uitleg="Police staat in het Engels altijd in het meervoud. My family is big klinkt gewoner, al mag are als je de leden apart bedoelt."),
    dict(type="invultekst",
         vraag="Vul de juiste vorm in: one of my friends … coming tonight. Gebruik is of are.",
         antwoord=["is"],
         uitleg="Het onderwerp is one, niet friends. Kijk dus naar het woord voor of."),
    dict(type="waarofniet",
         vraag="Het Engels laat het onderwerp weg als het duidelijk is: is raining today.",
         antwoord=False,
         uitleg="Elke Engelse zin heeft een onderwerp nodig, behalve de imperatief. Hier moet het it is raining today zijn."),
    dict(type="meerkeuze",
         vraag="Welke zin is ontkennend en juist?",
         opties=["She doesn't want to go.", "She not wants to go.", "She doesn't wants to go.", "She wants not to go."],
         antwoord=0,
         uitleg="Voor een ontkenning zonder hulpwerkwoord haal je do, does of did erbij en zet je er not achter."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is nevenschikking?",
         opties=["twee zinnen van gelijke waarde aan elkaar knopen", "een bijzin onder een hoofdzin hangen", "een zin in tweeën knippen", "een woord vervangen door een voornaamwoord"],
         antwoord=0,
         uitleg="Bij nevenschikking kunnen allebei de delen alleen staan: I called her and she answered."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn nevenschikkende voegwoorden?",
         opties=["and", "but", "or", "because"],
         antwoord=[0, 1, 2],
         uitleg="Because is onderschikkend: het maakt van het tweede deel een bijzin die niet alleen kan staan."),
    dict(type="meerkeuze",
         vraag="Welk voegwoord past? I stayed at home … it was raining.",
         opties=["because", "but", "or", "so"],
         antwoord=0,
         uitleg="Because geeft de reden. So geeft juist het gevolg: it was raining, so I stayed at home."),
    dict(type="invultekst",
         vraag="Vul één voegwoord in dat een tegenstelling aangeeft: she was tired, … she kept working.",
         antwoord=["but", "yet"],
         uitleg="But is het gewone woord. Yet kan ook en klinkt iets formeler: she was tired, yet she kept working."),
    dict(type="waarofniet",
         vraag="'Although' en 'but' mag je in dezelfde zin samen gebruiken: although she was tired, but she kept working.",
         antwoord=False,
         uitleg="Eén tegenstelling per zin volstaat. Het is although she was tired, she kept working, of she was tired but she kept working."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn onderschikkende voegwoorden?",
         opties=["although", "unless", "while", "so"],
         antwoord=[0, 1, 2],
         uitleg="So is nevenschikkend. Onderschikkende voegwoorden zijn ook if, when, because, since en until."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'unless you hurry, you will miss the bus'?",
         opties=["als je je niet haast, mis je de bus", "als je je haast, mis je de bus", "omdat je je haast, mis je de bus", "terwijl je je haast, mis je de bus"],
         antwoord=0,
         uitleg="Unless betekent if not. Er staat dus al een ontkenning in, en je zet er geen tweede bij."),
    dict(type="waarofniet",
         vraag="Een bijzin zoals 'because it was raining' kan op zichzelf een volledige zin vormen.",
         antwoord=False,
         uitleg="Er moet een hoofdzin bij: I stayed at home because it was raining. Daaraan herken je onderschikking."),
    dict(type="meerkeuze",
         vraag="Waar staat de komma als de bijzin vooraan komt?",
         opties=["achter de bijzin: When I arrived, she was asleep.", "voor de bijzin: When, I arrived she was asleep.", "nergens, er komt geen komma", "achter het onderwerp van de hoofdzin"],
         antwoord=0,
         uitleg="Komt de bijzin achteraan, dan valt de komma meestal weg: she was asleep when I arrived."),
    dict(type="meerkeuze",
         vraag="In welke zin staat een betrekkelijke bijzin?",
         opties=["The man who lives next door is a nurse.", "The man is a nurse and he lives next door.", "The man lives next door, so he is a nurse.", "Is the man next door a nurse?"],
         antwoord=0,
         uitleg="Een betrekkelijke bijzin hangt aan een naamwoord vast en zegt er iets meer over."),
    dict(type="invultekst",
         vraag="Vul aan met één woord: this is the house … we lived for ten years. Het gaat over een plaats.",
         antwoord=["where"],
         uitleg="Where verwijst naar een plaats, when naar een tijd en why naar een reden."),
    dict(type="waarofniet",
         vraag="Een bijzin die alleen extra informatie geeft, zet je tussen komma's: my sister, who lives in Ghent, is a vet.",
         antwoord=True,
         uitleg="Zonder komma's beperkt de bijzin wie je bedoelt: my sister who lives in Ghent zou betekenen dat je meer dan één zus hebt."),
    dict(type="meerkeuze",
         vraag="Wat is het verschil tussen 'the students who worked hard passed' en 'the students, who worked hard, passed'?",
         opties=["zonder komma's slaagde alleen de groep die hard werkte",
                 "er is geen verschil in betekenis, alleen in stijl",
                 "met komma's slaagde alleen de groep die hard werkte",
                 "zonder komma's is de zin fout"],
         antwoord=0,
         uitleg="Met komma's erbij werkten ze allemaal hard en slaagden ze allemaal. Eén leesteken verandert de hele boodschap."),
    dict(type="meerkeuze",
         vraag="Hoe ziet een conditional zero eruit?",
         opties=["if plus present simple, present simple", "if plus present simple, will", "if plus past simple, would", "if plus will, present simple"],
         antwoord=0,
         uitleg="If you heat water to 100 degrees, it boils. De conditional zero is voor wat altijd waar is."),
    dict(type="meerkeuze",
         vraag="Welke zinnen zijn conditionals zero?",
         opties=["If you mix blue and yellow, you get green.",
                 "If it rains, the streets get wet.",
                 "If you press this button, the light goes on.",
                 "If it rains, we will stay at home."],
         antwoord=[0, 1, 2],
         uitleg="De laatste kijkt naar één bepaalde keer in de toekomst, dus dat is een conditional first met will."),
    dict(type="invultekst",
         vraag="Vul aan met één woord: if you study hard, you … pass. Het gaat over één keer, in de toekomst.",
         antwoord=["will"],
         uitleg="Dat is de conditional first: if plus present simple in de bijzin, en will in de hoofdzin."),
    dict(type="waarofniet",
         vraag="Na 'if' zet je in een conditional first geen will: if it will rain is fout.",
         antwoord=True,
         uitleg="De will hoort in de hoofdzin: if it rains, we will stay at home."),
    dict(type="meerkeuze",
         vraag="Welke zin is een conditional first?",
         opties=["If I miss the train, I will take the bus.",
                 "If I missed the train, I would take the bus.",
                 "If I miss the train, I take the bus every time.",
                 "If I had missed the train, I would have taken the bus."],
         antwoord=0,
         uitleg="De eerste kijkt naar een echte mogelijkheid in de toekomst. De derde is een conditional zero, want daar gaat het over elke keer."),
    dict(type="waarofniet",
         vraag="In een conditional mag de hoofdzin ook vooraan staan: we will stay at home if it rains.",
         antwoord=True,
         uitleg="De betekenis blijft dezelfde. Staat de if-zin achteraan, dan valt de komma weg."),
    dict(type="meerkeuze",
         vraag="Waarom is het goed om met verschillende soorten zinnen te werken?",
         opties=["een verhaal wordt er levendiger door",
                 "korte zinnen zijn altijd fout",
                 "lange zinnen tellen zwaarder mee",
                 "een vraag mag maar één keer per tekst"],
         antwoord=0,
         uitleg="Alleen maar korte hoofdzinnen leest hakkelend, alleen maar lange samengestelde zinnen leest zwaar. De afwisseling maakt het verschil."),
]
