# -*- coding: utf-8 -*-
"""De filosofische vaardigheden.

Van de vakfiche kunstbeschouwing en filosofie (2DO, 2027): een filosofische
vraag stellen bij een thema, argumenteren volgens de AUB-methode (bijlage 3)
en een filosofische tekst analyseren met het stappenplan (bijlage 4).

Deel 1 is de AUB-methode.
Deel 2 is het stappenplan voor een filosofische tekst.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Waarvoor staan de drie letters van de AUB-methode?",
         opties=["argument, uitleg, bijvoorbeeld",
                 "antwoord, uitleg, bewijs",
                 "aanname, uitkomst, besluit",
                 "analyse, uitleg, bespreking"],
         antwoord=0,
         uitleg="A voor je argument, U voor de uitleg erbij, B voor een voorbeeld dat het duidelijk maakt."),
    dict(type="meerkeuze",
         vraag="Wat doe je bij de A van de AUB-methode?",
         opties=["je noemt je argument",
                 "je legt het uit",
                 "je geeft een voorbeeld",
                 "je besluit het gesprek"],
         antwoord=0,
         uitleg="Je begint met: mijn argument is dat … Daarna volgt de uitleg."),
    dict(type="invultekst",
         vraag="Welke letter van AUB staat voor het voorbeeld? Eén letter.",
         antwoord=["b", "B"],
         uitleg="De B van bijvoorbeeld. Je maakt je argument concreet met een geval."),
    dict(type="meerkeuze",
         vraag="Uit welke twee stappen bestaat de U van de AUB-methode?",
         opties=["waarom het zo is en waarom dat goed of slecht is",
                 "wie het zegt en wanneer hij het precies zei",
                 "wat het kost en wat het uiteindelijk opbrengt",
                 "hoe lang het duurt en hoe vaak het gebeurt"],
         antwoord=0,
         uitleg="Eerst leg je uit waarom het zo is, dan waarom dat goed of slecht is."),
    dict(type="waarofniet",
         vraag="De B van de AUB-methode mag een zelfbedacht voorbeeld zijn.",
         antwoord=True,
         uitleg="De bijlage zegt het letterlijk: gebruik je eigen fantasie of zoek informatie op het internet."),
    dict(type="meerkeuze",
         vraag="Met welke woorden begin je de uitleg volgens de bijlage?",
         opties=["want of omdat",
                 "stel je voor",
                 "mijn argument is",
                 "het is onderzocht"],
         antwoord=0,
         uitleg="Want of omdat. Stel je voor hoort bij de B, mijn argument is bij de A."),
    dict(type="meerkeuze",
         vraag="Welke zinaanzetten horen volgens de bijlage bij de B?",
         opties=["stel je voor",
                 "het is onderzocht dat",
                 "een voorbeeld hiervan is",
                 "mijn argument is dat"],
         antwoord=[0, 1, 2],
         uitleg="Drie manieren om een voorbeeld aan te brengen. De laatste hoort bij de A."),
    dict(type="invultekst",
         vraag="Welk woord past bij de U van AUB? Eén woord.",
         antwoord=["omdat", "want", "uitleg"],
         uitleg="Want of omdat. De U staat voor de uitleg bij je argument."),
    dict(type="meerkeuze",
         vraag="Waarom is enkel een argument noemen niet genoeg?",
         opties=["de ander begrijpt het niet",
                 "het klinkt te kort",
                 "het klinkt te lang",
                 "het is niet toegelaten"],
         antwoord=0,
         uitleg="Zonder uitleg en voorbeeld blijft het een bewering. De AUB-methode maakt het een argument."),
    dict(type="waarofniet",
         vraag="De AUB-methode geeft je het juiste standpunt.",
         antwoord=False,
         uitleg="Ze geeft de vorm waarin je een standpunt verdedigt. Welk standpunt je kiest, blijft aan jou."),
    dict(type="meerkeuze",
         vraag="Wat vraagt de fiche bij een filosofische positie?",
         opties=["argumenten voor en tegen",
                 "enkel argumenten voor",
                 "enkel argumenten tegen",
                 "enkel een eigen mening"],
         antwoord=0,
         uitleg="Je formuleert argumenten voor en tegen een positie. Zo zie je beide kanten."),
    dict(type="meerkeuze",
         vraag="Waarom moet je ook argumenten tegen je eigen standpunt kunnen bedenken?",
         opties=["zo weet je wat je weerlegt",
                 "zo klinkt je antwoord langer",
                 "zo verlies je het gesprek",
                 "zo mag je van gedacht veranderen"],
         antwoord=0,
         uitleg="Een standpunt dat de tegenargumenten niet kent, staat zwak. Juist daarom vraagt de fiche beide."),
    dict(type="waarofniet",
         vraag="Een voorbeeld moet volgens de bijlage altijd uit onderzoek komen.",
         antwoord=False,
         uitleg="Het mag ook zelfbedacht zijn: de bijlage noemt je eigen fantasie naast informatie van het internet."),
    dict(type="meerkeuze",
         vraag="Welke onderdelen heeft een volledig argument volgens AUB?",
         opties=["de bewering",
                 "de reden erachter",
                 "een voorbeeld erbij",
                 "de naam van een filosoof"],
         antwoord=[0, 1, 2],
         uitleg="Bewering, reden en voorbeeld. Een filosofennaam mag erbij, maar hoort niet in de methode."),
    dict(type="meerkeuze",
         vraag="Iemand zegt: dat is gewoon zo. Wat ontbreekt?",
         opties=["de uitleg en het voorbeeld",
                 "enkel het argument zelf",
                 "enkel de conclusie ervan",
                 "enkel de vraag erachter"],
         antwoord=0,
         uitleg="Hij beweert iets zonder het te onderbouwen. De U en de B ontbreken volledig."),
    dict(type="invultekst",
         vraag="Hoeveel stappen heeft de AUB-methode? Een cijfer.",
         antwoord=["3", "drie"],
         uitleg="Drie: argument, uitleg, bijvoorbeeld."),
    dict(type="waarofniet",
         vraag="De AUB-methode geldt volgens de fiche ook bij ethische vraagstukken.",
         antwoord=True,
         uitleg="De fiche vraagt uitdrukkelijk om bij een ethisch vraagstuk een argument volgens AUB te formuleren."),
    dict(type="meerkeuze",
         vraag="Wat is de eerste filosofische vaardigheid van de fiche?",
         opties=["een filosofische vraag stellen",
                 "een tekst samenvatten in enkele zinnen",
                 "een filosoof citeren bij je antwoord",
                 "een boek kiezen om je voor te bereiden"],
         antwoord=0,
         uitleg="Bij een aangebracht thema zelf een filosofische vraag formuleren. Daarna komen argumenteren en tekstanalyse."),
    dict(type="meerkeuze",
         vraag="Welke vragen bij het thema geld zijn filosofisch?",
         opties=["maakt geld gelukkig",
                 "mag rijkdom onbeperkt zijn",
                 "is armoede onrechtvaardig",
                 "wanneer kwam de euro er"],
         antwoord=[0, 1, 2],
         uitleg="Drie vragen die fundamenteel en open zijn. De laatste is een weetvraag."),
    dict(type="meerkeuze",
         vraag="Waarom heet de methode AUB?",
         opties=["de letters zijn een geheugensteun",
                 "ze komt uit Brussel en omstreken",
                 "ze is heel hoffelijk geformuleerd",
                 "ze komt uit het Latijn van vroeger"],
         antwoord=0,
         uitleg="Argument, uitleg, bijvoorbeeld. De drie beginletters vormen samen een woord dat je onthoudt."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Hoeveel stappen heeft het stappenplan voor een filosofische tekst?",
         opties=["drie",
                 "twee in totaal",
                 "vier in totaal",
                 "vijf in totaal"],
         antwoord=0,
         uitleg="Globaal en oriënterend lezen, grondig lezen, en reflectie."),
    dict(type="meerkeuze",
         vraag="Wat doe je in stap 1 van het stappenplan?",
         opties=["de tekst in zijn geheel lezen",
                 "onbekende woorden opzoeken",
                 "kritiek formuleren",
                 "een samenvatting maken"],
         antwoord=0,
         uitleg="Eerst de hele tekst doorlezen om de structuur te zien. Dat heet oriënterend lezen."),
    dict(type="invultekst",
         vraag="Wat duid je in stap 1 in elke alinea aan? Eén woord.",
         antwoord=["kernzin", "de kernzin", "kernzinnen"],
         uitleg="Een kernzin per alinea. Zo zie je de rode draad van de tekst."),
    dict(type="meerkeuze",
         vraag="Waarop let je volgens stap 1?",
         opties=["de indeling in alinea's",
                 "de signaalwoorden",
                 "de kernbegrippen die terugkomen",
                 "de prijs van het boek"],
         antwoord=[0, 1, 2],
         uitleg="Drie aanwijzingen voor de structuur. De prijs van het boek staat er niet bij."),
    dict(type="waarofniet",
         vraag="In stap 2 lees je de tekst zorgvuldig opnieuw.",
         antwoord=True,
         uitleg="Grondig lezen: je moet achteraf met eigen woorden kunnen uitleggen hoe de auteur zijn stelling verdedigt."),
    dict(type="meerkeuze",
         vraag="Wat doe je volgens stap 2 met moeilijke zinnen?",
         opties=["je ontleedt ze",
                 "je slaat ze over",
                 "je schrijft ze over",
                 "je leest ze luidop"],
         antwoord=0,
         uitleg="Ontleden, onbekende woorden opzoeken, vragen noteren en verbanden aanduiden."),
    dict(type="meerkeuze",
         vraag="Welke verbanden duid je volgens stap 2 aan?",
         opties=["opsommingen",
                 "voorbeelden",
                 "de stelling en de argumenten",
                 "de jaartallen"],
         antwoord=[0, 1, 2],
         uitleg="Drie soorten verbanden uit de bijlage. Jaartallen staan er niet bij."),
    dict(type="invultekst",
         vraag="Wat maak je aan het einde van stap 2? Eén woord.",
         antwoord=["samenvatting", "een samenvatting", "samenvatten"],
         uitleg="Een samenvatting in enkele zinnen. Dat is de toets of je de tekst echt begrepen hebt."),
    dict(type="meerkeuze",
         vraag="Wat doe je in stap 3 van het stappenplan?",
         opties=["je denkt na over wat je zelf vindt",
                 "je leest de hele tekst nog eens door",
                 "je zoekt de onbekende woorden op",
                 "je duidt de kernzinnen aan"],
         antwoord=0,
         uitleg="De reflectie: welke kritiek heb je, welke tegenvoorbeelden vind je, verschil je van mening?"),
    dict(type="waarofniet",
         vraag="In stap 3 laat je kritiek op de tekst beter achterwege.",
         antwoord=False,
         uitleg="De bijlage vraagt er juist naar: wat zit je dwars, welke tegenvoorbeelden vind je?"),
    dict(type="meerkeuze",
         vraag="Welke vragen stel je volgens stap 3?",
         opties=["welke tegenvoorbeelden vind ik",
                 "welke kritiek heb ik",
                 "hoe zou de auteur antwoorden",
                 "hoeveel bladzijden zijn er"],
         antwoord=[0, 1, 2],
         uitleg="Drie reflectievragen van de bijlage. Het aantal bladzijden doet niet mee."),
    dict(type="meerkeuze",
         vraag="Waarom vraagt stap 3 hoe de auteur je kritiek zou beantwoorden?",
         opties=["zo toets je je eigen bezwaar",
                 "zo kan je de auteur bellen",
                 "zo vermijd je kritiek",
                 "zo blijf je bij je mening"],
         antwoord=0,
         uitleg="Misschien had de auteur je bezwaar al voorzien. Dan is je kritiek zwakker dan je dacht."),
    dict(type="waarofniet",
         vraag="Het stappenplan vraagt volgens de bijlage om de tekst slechts één keer te lezen.",
         antwoord=False,
         uitleg="Minstens twee keer: eerst oriënterend, dan grondig. Daarna volgt pas de reflectie."),
    dict(type="meerkeuze",
         vraag="Wat is een signaalwoord?",
         opties=["een woord dat een verband aangeeft",
                 "een woord dat vaak terugkomt",
                 "een woord uit een vreemde taal",
                 "een woord van de auteur zelf"],
         antwoord=0,
         uitleg="Woorden als daarom, toch, bovendien of kortom. Ze wijzen hoe de delen samenhangen."),
    dict(type="meerkeuze",
         vraag="In welke stap hoort het opzoeken van een onbekend woord?",
         opties=["in stap 2",
                 "in stap 1",
                 "in stap 3",
                 "in geen enkele stap"],
         antwoord=0,
         uitleg="Bij het grondig lezen. In stap 1 kijk je alleen naar de grote lijn."),
    dict(type="invultekst",
         vraag="In welke stap staat de reflectie? Een cijfer.",
         antwoord=["3", "drie", "stap 3"],
         uitleg="Stap 3. Daar denk je na over wat je er zelf van vindt."),
    dict(type="waarofniet",
         vraag="Volgens stap 3 moet je je eigen overtuiging soms bijstellen.",
         antwoord=True,
         uitleg="De bijlage vraagt dat letterlijk: als er een meningsverschil is, pas dan je eigen overtuiging aan?"),
    dict(type="meerkeuze",
         vraag="Welke stap sluit je af met een samenvatting in enkele zinnen?",
         opties=["stap 2",
                 "stap 1",
                 "stap 3",
                 "geen enkele"],
         antwoord=0,
         uitleg="Na het grondig lezen. Stap 1 sluit af met de kernzinnen per alinea."),
    dict(type="meerkeuze",
         vraag="Welke drie vaardigheden vraagt de fiche?",
         opties=["een vraag stellen",
                 "argumenteren met AUB",
                 "een tekst analyseren",
                 "een filosoof citeren"],
         antwoord=[0, 1, 2],
         uitleg="Die drie staan er. Citeren mag, maar is geen aparte vaardigheid."),
    dict(type="meerkeuze",
         vraag="Waarom staan die vaardigheden ook bij lichaam en geest en bij mens en dier?",
         opties=["je past ze toe op elk thema",
                 "ze gelden enkel daar",
                 "ze zijn daar anders",
                 "ze zijn daar eenvoudiger"],
         antwoord=0,
         uitleg="De fiche vraagt bij elk thema een vraag, een argument en een tekstanalyse. Zo blijven de vaardigheden niet in de lucht hangen."),
]
