# -*- coding: utf-8 -*-
"""Soorten vragen en de kenmerken van de filosofische vraag.

Van de vakfiche kunstbeschouwing en filosofie (2DO, 2027): het onderscheid
tussen een weetvraag, een meningsvraag en een filosofische vraag (denkvraag),
en de vijf kenmerken van de filosofische vraag: fundamenteel, meerduidig,
niet-empirisch op te lossen, open en universeel.

Deel 1 zijn de drie soorten vragen.
Deel 2 zijn de vijf kenmerken.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Welke drie soorten vragen onderscheidt de fiche?",
         opties=["weet-, menings- en denkvraag",
                 "open, gesloten en halfopen vraag",
                 "korte, lange en moeilijke vraag",
                 "goede, foute en vreemde vraag"],
         antwoord=0,
         uitleg="Een weetvraag, een meningsvraag en een filosofische vraag, die de fiche ook denkvraag noemt."),
    dict(type="meerkeuze",
         vraag="Wat is een weetvraag?",
         opties=["ze heeft één juist antwoord",
                 "ze heeft meerdere antwoorden",
                 "ze heeft geen antwoord",
                 "ze heeft een lang antwoord"],
         antwoord=0,
         uitleg="Je kan het opzoeken of nameten: hoe hoog is de Mont Blanc, wanneer viel de muur?"),
    dict(type="waarofniet",
         vraag="Een meningsvraag vraagt naar wat iemand vindt.",
         antwoord=True,
         uitleg="Wat is je lievelingskleur? Iedereen mag iets anders antwoorden en niemand heeft ongelijk."),
    dict(type="meerkeuze",
         vraag="Welke zijn weetvragen?",
         opties=["hoe hoog is de Everest",
                 "wanneer begon de oorlog",
                 "hoeveel inwoners heeft Gent",
                 "wat is rechtvaardigheid"],
         antwoord=[0, 1, 2],
         uitleg="Drie vragen met één opzoekbaar antwoord. De vierde is filosofisch."),
    dict(type="invultekst",
         vraag="Welke vraag heeft precies één juist antwoord? Eén woord.",
         antwoord=["weetvraag", "weet", "een weetvraag"],
         uitleg="Een weetvraag. Je lost ze op met een boek, een meting of een zoekmachine."),
    dict(type="meerkeuze",
         vraag="Wat is een filosofische vraag volgens de fiche ook?",
         opties=["een denkvraag",
                 "een weetvraag",
                 "een meningsvraag",
                 "een strikvraag"],
         antwoord=0,
         uitleg="De fiche zet denkvraag naast filosofische vraag. Je komt er door te denken, niet door op te zoeken."),
    dict(type="meerkeuze",
         vraag="Welke zijn meningsvragen?",
         opties=["wat is de leukste sport",
                 "welk boek vind je het mooist",
                 "welke film koos jij",
                 "wat is geluk eigenlijk"],
         antwoord=[0, 1, 2],
         uitleg="Drie keer wordt een smaak gevraagd. De laatste vraag gaat over het begrip zelf en is filosofisch."),
    dict(type="waarofniet",
         vraag="Een filosofische vraag en een meningsvraag zijn hetzelfde.",
         antwoord=False,
         uitleg="Bij een mening volstaat wat je vindt. Bij een filosofische vraag moet je je antwoord beargumenteren."),
    dict(type="meerkeuze",
         vraag="Wat scheidt een filosofische vraag van een meningsvraag?",
         opties=["ze vraagt om argumenten",
                 "ze vraagt om een smaak",
                 "ze vraagt om een getal",
                 "ze vraagt om een bron"],
         antwoord=0,
         uitleg="Je mag niet zomaar iets vinden. Je moet uitleggen waarom, en je antwoord kan weerlegd worden."),
    dict(type="meerkeuze",
         vraag="Wat is dit: hoeveel mensen wonen in België?",
         opties=["een weetvraag",
                 "een meningsvraag",
                 "een filosofische vraag",
                 "een denkvraag"],
         antwoord=0,
         uitleg="Eén juist antwoord, op te zoeken in de statistieken."),
    dict(type="meerkeuze",
         vraag="Wat is dit: mag een computer straffen uitspreken?",
         opties=["een filosofische vraag",
                 "een weetvraag over computers",
                 "een meningsvraag over computers",
                 "geen van die drie soorten"],
         antwoord=0,
         uitleg="Het gaat over rechtvaardigheid en verantwoordelijkheid. Opzoeken kan je het antwoord niet."),
    dict(type="invultekst",
         vraag="Welke vraag vraagt naar een smaak of voorkeur? Eén woord.",
         antwoord=["meningsvraag", "mening", "een meningsvraag"],
         uitleg="Een meningsvraag. Wat de ene mooi vindt, vindt de andere lelijk, en daar is geen twist over mogelijk."),
    dict(type="waarofniet",
         vraag="Een weetvraag kan je volgens de fiche niet opzoeken.",
         antwoord=False,
         uitleg="Opzoeken of nameten kan je ze juist wel. Dat is precies wat haar een weetvraag maakt."),
    dict(type="meerkeuze",
         vraag="Wat is dit: wat is tijd?",
         opties=["een filosofische vraag",
                 "een weetvraag over tijd",
                 "een meningsvraag over tijd",
                 "een rekenvraag over tijd"],
         antwoord=0,
         uitleg="Hoe laat het is, is een weetvraag. Wat tijd is, houdt filosofen al eeuwen bezig."),
    dict(type="meerkeuze",
         vraag="Welke vragen zijn filosofisch?",
         opties=["wat is vrijheid",
                 "mag je altijd liegen",
                 "bestaat er een ziel",
                 "hoeveel dagen heeft maart"],
         antwoord=[0, 1, 2],
         uitleg="Drie vragen die je niet kan opzoeken en die om argumenten vragen. De vierde is een weetvraag."),
    dict(type="waarofniet",
         vraag="Een vraag kan afhankelijk van de formulering van soort veranderen.",
         antwoord=True,
         uitleg="Hoe laat is het, is een weetvraag; wat tijd eigenlijk is, is filosofisch. Zelfde woord, ander soort vraag."),
    dict(type="meerkeuze",
         vraag="Waarom is het onderscheid tussen die drie vragen nuttig?",
         opties=["je weet hoe je ze aanpakt",
                 "je weet hoe lang ze duurt",
                 "je weet wie ze stelde",
                 "je weet wat ze kost"],
         antwoord=0,
         uitleg="Een weetvraag zoek je op, een meningsvraag beantwoord je zelf, een filosofische vraag onderzoek je met argumenten."),
    dict(type="meerkeuze",
         vraag="Een leerling vraagt of straf nodig is om te leren. Welke vraag is dat?",
         opties=["een filosofische vraag",
                 "een weetvraag over straf",
                 "een meningsvraag over straf",
                 "een rekenvraag over straf"],
         antwoord=0,
         uitleg="Ze gaat over wat goed is en vraagt om argumenten. Opzoeken kan je het antwoord niet."),
    dict(type="invultekst",
         vraag="Welk ander woord gebruikt de fiche voor de filosofische vraag? Eén woord.",
         antwoord=["denkvraag", "denk", "een denkvraag"],
         uitleg="Denkvraag. Het woord zegt het al: je komt er al denkend."),
    dict(type="meerkeuze",
         vraag="Welke stap zet de fiche na het soort vraag bepalen?",
         opties=["de kenmerken benoemen",
                 "de vraag opzoeken",
                 "de vraag wegnemen",
                 "de vraag vertalen"],
         antwoord=0,
         uitleg="Daarna komen de vijf kenmerken: fundamenteel, meerduidig, niet-empirisch, open en universeel."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Hoeveel kenmerken heeft de filosofische vraag volgens de fiche?",
         opties=["vijf",
                 "drie in totaal",
                 "vier in totaal",
                 "zeven in totaal"],
         antwoord=0,
         uitleg="Fundamenteel, meerduidig, niet-empirisch op te lossen, open en universeel."),
    dict(type="meerkeuze",
         vraag="Wat betekent het kenmerk fundamenteel?",
         opties=["ze raakt de grond van de zaak",
                 "ze is heel moeilijk te stellen",
                 "ze is heel oud en bekend",
                 "ze is heel lang geformuleerd"],
         antwoord=0,
         uitleg="Ze gaat niet over een detail maar over de basis: wat is kennis, wat is recht, wat is een mens?"),
    dict(type="waarofniet",
         vraag="Een filosofische vraag is meerduidig: ze kan op meerdere manieren begrepen worden.",
         antwoord=True,
         uitleg="Wat is vrijheid? Dat kan over keuze, over wet of over verlangen gaan. Eerst moet je het begrip verhelderen."),
    dict(type="meerkeuze",
         vraag="Welke kenmerken noemt de fiche?",
         opties=["open",
                 "universeel",
                 "meerduidig",
                 "meetbaar"],
         antwoord=[0, 1, 2],
         uitleg="Meetbaar is net het tegendeel: een filosofische vraag is niet-empirisch op te lossen."),
    dict(type="invultekst",
         vraag="Welk kenmerk zegt dat de vraag voor iedereen geldt? Eén woord.",
         antwoord=["universeel", "universele"],
         uitleg="Universeel: de vraag geldt overal en voor elke mens, niet enkel hier en nu."),
    dict(type="meerkeuze",
         vraag="Wat betekent niet-empirisch op te lossen?",
         opties=["geen meting beslist",
                 "geen mens weet het",
                 "geen boek bestaat erover",
                 "geen taal past erbij"],
         antwoord=0,
         uitleg="Je kan de vraag niet met een proef of een meting beslechten. Je komt er met argumenten."),
    dict(type="meerkeuze",
         vraag="Wat betekent het kenmerk open?",
         opties=["er is geen eindantwoord",
                 "er is één eindantwoord",
                 "er is geen vraag",
                 "er is geen argument"],
         antwoord=0,
         uitleg="Elk antwoord roept weer nieuwe vragen op. Daarom blijven filosofen al eeuwen aan dezelfde vragen bezig."),
    dict(type="waarofniet",
         vraag="Een filosofische vraag heeft volgens de fiche één sluitend antwoord.",
         antwoord=False,
         uitleg="Ze is open. Dat betekent niet dat elk antwoord even goed is: argumenten blijven wegen."),
    dict(type="meerkeuze",
         vraag="Welke vraag is fundamenteel?",
         opties=["wat is kennis",
                 "wie schreef dat boek",
                 "wanneer begon de les",
                 "hoeveel kost dat boek"],
         antwoord=0,
         uitleg="Ze raakt de grond van alle weten. De drie andere zijn weetvragen over details."),
    dict(type="meerkeuze",
         vraag="Welke kenmerken maken dat een vraag niet opzoekbaar is?",
         opties=["niet-empirisch op te lossen",
                 "open",
                 "meerduidig",
                 "universeel"],
         antwoord=[0, 1, 2],
         uitleg="Die drie houden de vraag open voor discussie. Universeel zegt enkel dat ze overal geldt."),
    dict(type="invultekst",
         vraag="Welk kenmerk zegt dat er geen eindantwoord is? Eén woord.",
         antwoord=["open", "openheid"],
         uitleg="Open. Een filosofische vraag blijft openstaan voor nieuwe argumenten."),
    dict(type="waarofniet",
         vraag="Dat een vraag universeel is, betekent dat ze overal gesteld kan worden.",
         antwoord=True,
         uitleg="Wat goed is of wat de dood betekent, kan in elke cultuur en in elke tijd gevraagd worden."),
    dict(type="meerkeuze",
         vraag="Waarom moet je eerst de begrippen in een filosofische vraag verhelderen?",
         opties=["de vraag is meerduidig",
                 "de vraag is te lang",
                 "de vraag is te oud",
                 "de vraag is verboden"],
         antwoord=0,
         uitleg="Wie over vrijheid spreekt, moet zeggen welke vrijheid hij bedoelt. Anders praten twee mensen langs elkaar."),
    dict(type="meerkeuze",
         vraag="Mag een rechter een robot zijn? Welke kenmerken heeft die vraag?",
         opties=["fundamenteel",
                 "niet-empirisch",
                 "open",
                 "meetbaar"],
         antwoord=[0, 1, 2],
         uitleg="Ze raakt de grond van rechtvaardigheid, is niet te meten en blijft open. Meetbaar is ze zeker niet."),
    dict(type="waarofniet",
         vraag="Een filosofische vraag hoeft volgens de fiche niet fundamenteel te zijn.",
         antwoord=False,
         uitleg="Fundamenteel staat net bij de vijf kenmerken. Een vraag over een detail is geen filosofische vraag."),
    dict(type="meerkeuze",
         vraag="Welke vraag is niet filosofisch, ook al klinkt ze diep?",
         opties=["hoeveel soorten geluk kent men",
                 "wat is geluk eigenlijk precies",
                 "bestaat er zoiets als vrije wil",
                 "wat maakt een daad echt goed"],
         antwoord=0,
         uitleg="Een aantal soorten tellen is opzoekwerk. De drie andere vragen om argumenten."),
    dict(type="meerkeuze",
         vraag="Waarom is openheid geen zwakte van de filosofie?",
         opties=["het gesprek blijft doorgaan",
                 "het antwoord doet niet ter zake",
                 "elk antwoord is gelijk",
                 "niemand hoeft te denken"],
         antwoord=0,
         uitleg="Zonder eindantwoord blijven mensen hun opvattingen toetsen. Dat is net de winst."),
    dict(type="invultekst",
         vraag="Welk kenmerk zegt dat de vraag de grond van de zaak raakt? Eén woord.",
         antwoord=["fundamenteel", "fundamentele"],
         uitleg="Fundamenteel. De vraag gaat over de basis en niet over een detail."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over de vijf kenmerken kloppen?",
         opties=["ze horen samen bij één vraag",
                 "ze helpen vragen te herkennen",
                 "ze staan alle vijf op de fiche",
                 "één kenmerk volstaat altijd"],
         antwoord=[0, 1, 2],
         uitleg="Eén kenmerk volstaat niet: een meningsvraag is ook open, maar niet fundamenteel of universeel."),
    dict(type="meerkeuze",
         vraag="Hoe maak je van een weetvraag een filosofische vraag?",
         opties=["vraag naar het begrip zelf",
                 "vraag naar een cijfer",
                 "vraag naar een bron",
                 "vraag naar een datum"],
         antwoord=0,
         uitleg="Niet hoeveel mensen gelukkig zijn, maar wat geluk is. Zo verschuift de vraag naar de filosofie."),
]
