# -*- coding: utf-8 -*-
"""Woordvelden: de mens, de gezondheid en het dagelijkse leven.

De vakfiche somt tweeëntwintig woordvelden op die op het examen aan bod kunnen
komen. Dit thema neemt de velden die over de mens zelf gaan en over wat hij
dagelijks doet: familie, gevoelens, gezondheid en lichaamsdelen, eten en
drinken, kleding en accessoires, de woning, de dagelijkse bezigheden, de
persoonlijke voorwerpen, en kleuren, vormen en materialen. De velden over
school, werk, reizen en de samenleving staan in het volgende thema.

De fiche zegt er zelf bij dat woordenschat nooit een doel op zich is: je hebt
ze nodig om een tekst te begrijpen en om zelf iets te schrijven. De vragen
hieronder zetten de woorden daarom zoveel mogelijk in een zin.

Deel 1: de mens, zijn familie, zijn gevoelens en zijn lichaam.
Deel 2: eten, kleren, het huis en de dag.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat betekent 'un beau-père' in een Franse tekst?",
         opties=["een schoonvader of een stiefvader", "een grootvader",
                 "een peter", "een zwager"],
         antwoord=0,
         uitleg="Beau- en belle- voor een familienaam betekent aangetrouwd: beau-père, belle-mère, beau-frère, belle-sœur. In de praktijk dekt het ook de nieuwe partner van je ouder."),
    dict(type="meerkeuze",
         vraag="Welke woorden duiden familieleden aan?",
         opties=["une nièce", "un cousin", "une tante", "un voisin"],
         antwoord=[0, 1, 2],
         uitleg="Un voisin is een buurman en dus geen familie. Une nièce is een nicht als kind van je broer of zus, une cousine een nicht als kind van je oom of tante."),
    dict(type="invultekst",
         vraag="Vul het Franse woord in voor grootmoeder: ma … habite à Liège.",
         antwoord=["grand-mère"],
         uitleg="Grand-mère en grand-père, met een streepje. Mamie en papy zijn de koosnamen."),
    dict(type="waarofniet",
         vraag="'Les parents' betekent in het Frans altijd alleen de vader en de moeder.",
         antwoord=False,
         uitleg="Les parents zijn de ouders, maar un parent kan ook een familielid in het algemeen zijn: j'ai des parents en Bretagne."),
    dict(type="meerkeuze",
         vraag="Welk gevoel drukt 'être inquiet' uit?",
         opties=["ongerust zijn", "boos zijn", "blij zijn", "verveeld zijn"],
         antwoord=0,
         uitleg="Inquiet of inquiète. Je m'inquiète pour toi is ik maak me zorgen om jou. Ne t'inquiète pas betekent maak je geen zorgen."),
    dict(type="meerkeuze",
         vraag="Welke woorden beschrijven een gevoel?",
         opties=["triste", "en colère", "déçu", "mince"],
         antwoord=[0, 1, 2],
         uitleg="Mince betekent slank en beschrijft een lichaam, niet een gevoel. Déçu is teleurgesteld."),
    dict(type="invultekst",
         vraag="Vul in wat 'bang' betekent: j'ai … des araignées.",
         antwoord=["peur"],
         uitleg="Avoir peur de, bang zijn van. Let op: in het Frans heb je angst, je bent ze niet."),
    dict(type="waarofniet",
         vraag="'Avoir honte' betekent zich schamen.",
         antwoord=True,
         uitleg="Net als avoir peur en avoir faim is het een uitdrukking met avoir waar het Nederlands een ander werkwoord gebruikt."),
    dict(type="meerkeuze",
         vraag="Je leest 'elle s'est cassé le bras'. Wat is er gebeurd?",
         opties=["ze heeft haar arm gebroken", "ze heeft haar arm verstuikt",
                 "ze heeft haar arm verbrand", "ze heeft haar arm geschaafd"],
         antwoord=0,
         uitleg="Se casser le bras. Merk op dat het Frans het lidwoord le gebruikt waar wij haar zeggen: bij lichaamsdelen is dat de regel."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn lichaamsdelen?",
         opties=["le genou", "l'épaule", "la cheville", "la poêle"],
         antwoord=[0, 1, 2],
         uitleg="Une poêle is een pan. Le genou is de knie, l'épaule de schouder, la cheville de enkel."),
    dict(type="invultekst",
         vraag="Vul in: j'ai mal à la … , ik heb hoofdpijn. Eén woord.",
         antwoord=["tête"],
         uitleg="Avoir mal à plus het lichaamsdeel: j'ai mal à la tête, au ventre, aux dents."),
    dict(type="meerkeuze",
         vraag="Hoe zeg je in het Frans dat je keelpijn hebt?",
         opties=["J'ai mal à la gorge.", "J'ai mal au cou.",
                 "J'ai mal à la bouche.", "J'ai mal à la langue."],
         antwoord=0,
         uitleg="La gorge is de keel, le cou is de hals van buiten. La langue is de tong."),
    dict(type="waarofniet",
         vraag="Een 'ordonnance' is in het Frans het voorschrift dat je van de dokter meekrijgt.",
         antwoord=True,
         uitleg="Une ordonnance geef je af bij de apotheek, la pharmacie. Un médicament is het geneesmiddel zelf."),
    dict(type="meerkeuze",
         vraag="Wat is 'une infirmière'?",
         opties=["een verpleegkundige", "een apotheker", "een tandarts", "een huisarts"],
         antwoord=0,
         uitleg="Un infirmier of une infirmière. De apotheker is le pharmacien, de tandarts le dentiste, de huisarts le médecin généraliste."),
    dict(type="meerkeuze",
         vraag="Drie van deze zinnen zeggen dat iemand zich niet goed voelt. Welke zegt het omgekeerde?",
         opties=["Il est malade.", "Elle ne se sent pas bien.",
                 "Il a de la fièvre.", "Elle est en pleine forme."],
         antwoord=3,
         uitleg="Être en pleine forme is net het omgekeerde: in topvorm zijn. De la fièvre is koorts."),
    dict(type="waarofniet",
         vraag="'Les cheveux' en 'les chevaux' betekenen in het Frans hetzelfde.",
         antwoord=False,
         uitleg="Les cheveux zijn haren, les chevaux zijn paarden. Eén letter verschil en een heel ander beeld in de zin."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'être fatigué'?",
         opties=["moe zijn", "ziek zijn", "verkouden zijn", "gewond zijn"],
         antwoord=0,
         uitleg="La fatigue is de vermoeidheid. Verkouden is enrhumé, gewond is blessé."),
    dict(type="meerkeuze",
         vraag="Drie van deze uitdrukkingen gebruiken avoir waar wij 'zijn' zeggen. Welke gebruikt être?",
         opties=["avoir faim", "avoir soif", "avoir froid", "être content"],
         antwoord=3,
         uitleg="Honger, dorst en kou heb je in het Frans. Content is een echt bijvoeglijk naamwoord en gaat dus wel met être."),
    dict(type="invultekst",
         vraag="Vul in: j'ai … , ik heb dorst. Eén woord.",
         antwoord=["soif"],
         uitleg="Avoir soif. Avoir faim is honger hebben, avoir sommeil slaap hebben."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'il a quinze ans'?",
         opties=["hij is vijftien jaar", "hij heeft vijftien broers",
                 "hij woont er vijftien jaar", "hij werkt er vijftien uur"],
         antwoord=0,
         uitleg="Je leeftijd heb je in het Frans: avoir quinze ans. Il est quinze ans bestaat niet."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is 'un repas'?",
         opties=["een maaltijd", "een recept", "een restaurant", "een bord"],
         antwoord=0,
         uitleg="Les trois repas de la journée. Une recette is een recept, une assiette een bord."),
    dict(type="meerkeuze",
         vraag="Welke woorden horen bij het ontbijt?",
         opties=["le pain", "la confiture", "le café", "le poulet"],
         antwoord=[0, 1, 2],
         uitleg="Le poulet is kip en hoort bij het warme eten. La confiture is confituur."),
    dict(type="invultekst",
         vraag="Vul het Franse woord voor groenten in: je mange beaucoup de … . Eén woord in het meervoud.",
         antwoord=["légumes"],
         uitleg="Les légumes. Les fruits zijn het fruit, la viande het vlees, le poisson de vis."),
    dict(type="waarofniet",
         vraag="'Une entrée' is in een Frans restaurant het voorgerecht.",
         antwoord=True,
         uitleg="L'entrée, le plat, le dessert. In het Engels betekent entrée in Amerika net het hoofdgerecht, en dat maakt het verwarrend."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'être au régime'?",
         opties=["op dieet zijn", "op reis zijn", "op kot zijn", "op tijd zijn"],
         antwoord=0,
         uitleg="Un régime is een dieet. Het woord betekent daarnaast ook een politiek regime, maar in een tekst over eten gaat het over het eerste."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn kledingstukken?",
         opties=["une chemise", "un pantalon", "une jupe", "une ceinture"],
         antwoord=[0, 1, 2],
         uitleg="Une ceinture is een riem en hoort bij de accessoires. Une chemise is een hemd, une jupe een rok."),
    dict(type="invultekst",
         vraag="Vul in: je porte des … noires. Het Franse woord voor schoenen, in het meervoud.",
         antwoord=["chaussures"],
         uitleg="Les chaussures zijn vrouwelijk, vandaar noires met een e en een s. Les chaussettes zijn de kousen."),
    dict(type="waarofniet",
         vraag="'Porter' betekent in het Frans zowel dragen in je handen als dragen aan je lijf.",
         antwoord=True,
         uitleg="Elle porte une valise en elle porte une robe rouge. Voor kleren kan ook être en: elle est en robe."),
    dict(type="meerkeuze",
         vraag="Welke kleuren veranderen in het Frans nooit van vorm, ook niet in het meervoud?",
         opties=["marron", "orange", "kaki", "vert"],
         antwoord=[0, 1, 2],
         uitleg="Kleuren die eigenlijk de naam van een ding zijn, blijven onveranderd: des chaussures marron, des murs orange. Vert volgt wel gewoon: des murs verts."),
    dict(type="meerkeuze",
         vraag="Wat is 'le verre' als materiaal?",
         opties=["glas", "ijzer", "hout", "leer"],
         antwoord=0,
         uitleg="Le verre is zowel het glas waaruit je drinkt als het materiaal. Le fer is ijzer, le bois hout, le cuir leer."),
    dict(type="meerkeuze",
         vraag="Drie van deze woorden zijn kamers in een huis. Welk woord is dat niet?",
         opties=["la cuisine", "la salle de bains", "la chambre", "l'immeuble"],
         antwoord=3,
         uitleg="Un immeuble is een appartementsgebouw, dus geen kamer. La chambre is de slaapkamer, le salon de woonkamer."),
    dict(type="invultekst",
         vraag="Vul het Franse woord voor keuken in: elle prépare le repas dans la … .",
         antwoord=["cuisine"],
         uitleg="La cuisine is de keuken en ook de kookkunst: la cuisine française. Cuisiner is koken."),
    dict(type="waarofniet",
         vraag="'Un appartement' schrijf je in het Frans met één p, net als het Engelse apartment.",
         antwoord=False,
         uitleg="Het Frans heeft dubbele p en één enkele t: appartement. Het Engelse apartment heeft net één p. Een klassieke spelvalstrik."),
    dict(type="meerkeuze",
         vraag="Wat is 'le rez-de-chaussée'?",
         opties=["het gelijkvloers", "de eerste verdieping", "de kelder", "de zolder"],
         antwoord=0,
         uitleg="Le premier étage is bij ons de eerste verdieping, dus de laag boven het gelijkvloers. La cave is de kelder, le grenier de zolder."),
    dict(type="meerkeuze",
         vraag="Drie van deze werkwoorden beschrijven wat je 's morgens doet. Welk hoort bij de avond?",
         opties=["se lever", "se laver", "s'habiller", "se coucher"],
         antwoord=3,
         uitleg="Se coucher is gaan slapen en hoort bij de avond. De drie andere zijn wederkerende werkwoorden van het ochtendritueel."),
    dict(type="invultekst",
         vraag="Vul in: je me … à sept heures, ik sta om zeven uur op. Eén werkwoordsvorm.",
         antwoord=["lève"],
         uitleg="Se lever krijgt een accent grave zodra de klemtoon erop valt: je me lève, maar nous nous levons."),
    dict(type="waarofniet",
         vraag="'Faire la vaisselle' betekent de was doen in de wasmachine.",
         antwoord=False,
         uitleg="Dat is faire la lessive. Faire la vaisselle is de afwas doen, en faire le ménage is kuisen. Faire doet in het Frans het meeste huishoudelijke werk."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'ranger sa chambre'?",
         opties=["zijn kamer opruimen", "zijn kamer schilderen",
                 "zijn kamer huren", "zijn kamer verlaten"],
         antwoord=0,
         uitleg="Ranger is op zijn plaats zetten. Une rangée is een rij, en dat helpt om het woord te onthouden."),
    dict(type="meerkeuze",
         vraag="Drie van deze voorwerpen draag je gewoonlijk bij je. Welk blijft thuis?",
         opties=["un portefeuille", "des clés", "un parapluie", "un canapé"],
         antwoord=3,
         uitleg="Un canapé is een zetel en blijft thuis. Un portefeuille is een portefeuille, des clés zijn sleutels."),
    dict(type="meerkeuze",
         vraag="Wat is 'une serviette' in een tekst over de badkamer?",
         opties=["een handdoek", "een spiegel", "een kraan", "een douche"],
         antwoord=0,
         uitleg="Une serviette is een handdoek en aan tafel een servet. Un miroir is een spiegel, un robinet een kraan."),
]
