# -*- coding: utf-8 -*-
"""Schrijven, schriftelijke interactie en leesbeleving.

Uit de vakfiche Frans 2, onderdeel "Schrijven, spreken en interactie". Op het
digitale examen maak je twee schrijfopdrachten. De fiche somt op wat je
schriftelijk moet kunnen: alledaagse sociale contacten leggen, informatie
geven en vragen, je mening geven, iets vertellen, iets uitleggen en iemand
proberen te overtuigen. Daarbovenop vraagt ze dat je bij een literaire tekst in
het Frans je eigen ervaring en gevoelens verwoordt.

Het spreken en het gesprek laten we hier liggen: die vragen een stem en een
gesprekspartner. Wat je hier oefent — de bouw van een mail, de taalhandelingen
en de toon — draagt het schrijfexamen én de voorbereiding van je spreekopdracht,
want de fiche geeft er dezelfde strategieën bij.

Deel 1 gaat over de taalhandelingen: wat wil je met je tekst bereiken.
Deel 2 gaat over de vorm: de bouw van een mail, de toon, het nalezen en wat je
schrijft over een tekst die je gelezen hebt.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Je stuurt een mail naar de gemeente om te vragen hoe je vrijwilliger kan worden. Welke taalhandeling is dat?",
         opties=["informatie vragen", "je mening geven", "iets vertellen", "iemand overtuigen"],
         antwoord=0,
         uitleg="Dat is net het voorbeeld dat de vakfiche zelf geeft. Informatie vragen en geven staat er als een aparte taalhandeling in."),
    dict(type="meerkeuze",
         vraag="Welke zinnen vragen in het Frans om informatie?",
         opties=["Pourriez-vous me dire si …", "Je voudrais savoir …",
                 "J'aimerais avoir des renseignements sur …", "Je ne suis pas d'accord avec vous."],
         antwoord=[0, 1, 2],
         uitleg="De laatste geeft een mening. Des renseignements is het gewone woord voor inlichtingen, en dat woord is op een examen goud waard."),
    dict(type="invultekst",
         vraag="Vul het Franse woord voor inlichtingen in: je voudrais des … sur le stage.",
         antwoord=["renseignements"],
         uitleg="Un renseignement is een inlichting. Une information kan ook, maar renseignements klinkt in een aanvraag natuurlijker."),
    dict(type="meerkeuze",
         vraag="Je schrijft een reactie onder een discussie op sociale media. Welke taalhandeling past daarbij?",
         opties=["je mening geven", "iets uitleggen", "informatie vragen", "iemand begroeten"],
         antwoord=0,
         uitleg="De fiche geeft dat voorbeeld zelf: je reageert op een discussie op sociale media. Daar zeg je wat je ervan vindt."),
    dict(type="meerkeuze",
         vraag="Welke uitdrukkingen leiden je mening in?",
         opties=["à mon avis", "je trouve que", "selon moi", "il paraît que"],
         antwoord=[0, 1, 2],
         uitleg="Il paraît que betekent naar het schijnt, en dat is net géén eigen mening maar iets van horen zeggen."),
    dict(type="waarofniet",
         vraag="Na 'je pense que' in een bevestigende zin komt in het Frans een subjonctif.",
         antwoord=False,
         uitleg="Je pense qu'il a raison, met de indicatif: je stelt iets vast. Pas in de ontkenning komt de twijfel erbij: je ne pense pas qu'il ait raison."),
    dict(type="meerkeuze",
         vraag="Je beschrijft in een mail hoe een ongeval gebeurd is. Welke taalhandeling is dat?",
         opties=["iets vertellen", "iets uitleggen", "iemand overtuigen", "je verontschuldigen"],
         antwoord=0,
         uitleg="De fiche noemt dat voorbeeld letterlijk bij vertellen, naast het verslag van een reis of een activiteit."),
    dict(type="meerkeuze",
         vraag="In welke tijd vertel je in het Frans meestal wat er gebeurd is?",
         opties=["de passé composé, met de imparfait voor de achtergrond",
                 "de futur simple, met de présent voor de achtergrond",
                 "de présent, met de conditionnel voor de achtergrond",
                 "de subjonctif, met de impératif voor de achtergrond"],
         antwoord=0,
         uitleg="De passé composé geeft de gebeurtenissen die elkaar opvolgen, de imparfait het decor eromheen: il pleuvait quand la voiture a glissé."),
    dict(type="invultekst",
         vraag="Vul aan met het werkwoord dat 'uitleggen' betekent: je vais vous … comment ça marche.",
         antwoord=["expliquer"],
         uitleg="Expliquer, une explication. Na vais komt de infinitief, dus geen vervoegde vorm."),
    dict(type="meerkeuze",
         vraag="Je geeft in een blogbericht tips om vlotter in te slapen. Welke taalhandeling is dat?",
         opties=["iets uitleggen", "informatie vragen", "iemand begroeten", "je waardering uiten"],
         antwoord=0,
         uitleg="Ook dat voorbeeld staat in de fiche. Uitleggen is: de ander aan het eind iets laten kunnen wat hij eerst niet kon."),
    dict(type="meerkeuze",
         vraag="Je probeert een castingbureau te overtuigen om je inschrijving te aanvaarden. Wat hoort dan zeker in je tekst?",
         opties=["argumenten waarom zij er beter van worden", "een opsomming van je gevoelens",
                 "een verhaal over je laatste vakantie", "een vraag naar hun openingsuren"],
         antwoord=0,
         uitleg="Overtuigen is niet hetzelfde als vragen. Je neemt het standpunt van de ander in en toont waarom je voorstel voor hém interessant is."),
    dict(type="meerkeuze",
         vraag="Welke woorden kondigen in een overtuigende tekst een argument aan?",
         opties=["d'abord", "de plus", "enfin", "malheureusement"],
         antwoord=[0, 1, 2],
         uitleg="D'abord, de plus, enfin zetten je argumenten op een rij. Malheureusement drukt spijt uit en is geen argument."),
    dict(type="waarofniet",
         vraag="Bij de alledaagse sociale contacten hoort volgens de vakfiche ook 'je waardering uiten'.",
         antwoord=True,
         uitleg="De fiche somt op: begroeten, aanspreken, afscheid nemen, iets voorstellen, bedanken, uitnodigen, je verontschuldigen, reageren op verontschuldigingen, je waardering uiten."),
    dict(type="meerkeuze",
         vraag="Welke zin nodigt iemand uit op een formele manier?",
         opties=["Nous serions heureux de vous accueillir le 12 mai.",
                 "Viens donc, ça va être génial !",
                 "Tu passes samedi ou pas ?",
                 "On se voit là-bas, hein."],
         antwoord=0,
         uitleg="De conditionnel serions en de vous-vorm maken de zin formeel. De drie andere horen bij vrienden."),
    dict(type="invultekst",
         vraag="Vul het werkwoord in dat 'bedanken' betekent: je vous … de votre réponse.",
         antwoord=["remercie"],
         uitleg="Remercier quelqu'un de quelque chose. Je vous remercie d'avance is de vaste formule aan het eind van een vraag."),
    dict(type="waarofniet",
         vraag="Een schrijfopdracht van het examen beoordeelt alleen of je grammatica juist is.",
         antwoord=False,
         uitleg="De fiche vraagt of de communicatie helder, gepast en vlot is. Een foutloze tekst die niet bij de ontvanger past, haalt zijn doel niet."),
    dict(type="meerkeuze",
         vraag="Wat is volgens de fiche een schrijfplan?",
         opties=["een lijstje kernwoorden dat je vooraf maakt",
                 "de volledige tekst die je eerst in het Nederlands schrijft",
                 "het aantal woorden dat je moet halen",
                 "de lijst werkwoorden die je gaat gebruiken"],
         antwoord=0,
         uitleg="Maak een schrijf- of spreekplan met kernwoorden, staat er. Twee minuten plannen scheelt tien minuten zoeken terwijl je schrijft."),
    dict(type="meerkeuze",
         vraag="Drie van deze vragen horen bij het communicatiemodel. Welke hoort er niet bij?",
         opties=["waarom schrijf ik", "voor wie is mijn boodschap", "welk kanaal gebruik ik", "hoeveel tijd heb ik nog"],
         antwoord=3,
         uitleg="De fiche somt op: waarom, voor wie, met wie, wat precies, en via welk kanaal. De klok hoort daar niet bij."),
    dict(type="waarofniet",
         vraag="Zit je vast bij het schrijven, dan raadt de fiche aan om je doel te bereiken met de woorden die je wél kent.",
         antwoord=True,
         uitleg="Letterlijk: laat je niet ontmoedigen, maar probeer je doel te bereiken met de woorden en structuren die je wél al kent. Omschrijven is een vaardigheid, geen nederlaag."),
    dict(type="meerkeuze",
         vraag="Je kent het woord 'une perceuse' niet, maar je moet het beschrijven. Wat doe je?",
         opties=["je omschrijft het: un outil pour faire des trous",
                 "je laat de hele zin weg uit je tekst",
                 "je schrijft het Nederlandse woord in je Franse tekst",
                 "je vervangt het door een woord met een andere betekenis"],
         antwoord=0,
         uitleg="Omschrijven met wat je kent is precies de strategie die de fiche vraagt. Een Nederlands woord in je tekst telt als een gat."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Uit welke delen bestaat een verzorgde Franse mail, in volgorde?",
         opties=["aanhef, reden van je bericht, inhoud, slotformule",
                 "inhoud, aanhef, slotformule, reden van je bericht",
                 "slotformule, aanhef, inhoud, reden van je bericht",
                 "reden van je bericht, slotformule, aanhef, inhoud"],
         antwoord=0,
         uitleg="Eerst de aanhef, dan één zin waarom je schrijft, dan de inhoud, dan het slot. Die ene zin met de reden vergeten mensen het vaakst."),
    dict(type="meerkeuze",
         vraag="Welke zinnen zeggen aan het begin van een mail waarom je schrijft?",
         opties=["Je vous écris au sujet de …", "Je me permets de vous contacter pour …",
                 "Suite à votre annonce, …", "Je vous remercie d'avance."],
         antwoord=[0, 1, 2],
         uitleg="De laatste hoort aan het eind, niet aan het begin. De drie andere kondigen je onderwerp aan."),
    dict(type="invultekst",
         vraag="Vul aan: je vous écris au … de votre annonce. Eén woord dat 'onderwerp' betekent.",
         antwoord=["sujet"],
         uitleg="Au sujet de betekent in verband met. Let op het lidwoord dat erachter komt: au sujet de la formation, au sujet du stage."),
    dict(type="waarofniet",
         vraag="In een formele Franse mail hou je de hele tekst in de vous-vorm aan, ook de werkwoorden in de laatste zin.",
         antwoord=True,
         uitleg="Halfweg omslaan naar tu is een van de opvallendste fouten op een schrijfexamen. Kies vooraf en blijf erbij."),
    dict(type="meerkeuze",
         vraag="Je schrijft aan een vriendin dat je haar bericht hebt gelezen. Welke aanhef past?",
         opties=["Salut Léa,", "Madame,", "Chère Madame,", "Monsieur le Directeur,"],
         antwoord=0,
         uitleg="Salut of Coucou bij vrienden, Cher of Chère plus de voornaam als het iets verzorgder mag. De drie andere horen bij onbekenden."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'Cher Monsieur' tegenover 'Monsieur' in een brief?",
         opties=["Cher Monsieur veronderstelt dat je de persoon al kent",
                 "Cher Monsieur is altijd formeler dan Monsieur",
                 "Cher Monsieur gebruik je alleen bij vrouwen",
                 "Er is geen enkel verschil tussen de twee"],
         antwoord=0,
         uitleg="Cher is een nuance warmer en veronderstelt een band. Ken je de persoon niet, dan schrijf je gewoon Madame, Monsieur."),
    dict(type="waarofniet",
         vraag="'Je vous prie d'agréer, Madame, mes salutations distinguées' is de aanhef waarmee een formele brief begint.",
         antwoord=False,
         uitleg="Het is net de lange, deftige afsluiting, helemaal onderaan. Opvallend: de aanhef komt er middenin terug, en dat hoort zo."),
    dict(type="meerkeuze",
         vraag="Je schrijft over een gedicht dat je gelezen hebt. Wat vraagt de vakfiche precies?",
         opties=["dat je in het Frans je eigen ervaring en gevoelens verwoordt",
                 "dat je het gedicht woord voor woord naar het Nederlands vertaalt",
                 "dat je de naam en het geboortejaar van de dichter noemt",
                 "dat je het rijmschema van elke strofe benoemt"],
         antwoord=0,
         uitleg="De fiche vraagt je leesbeleving: waarom iets je aanspreekt, of je je herkent in een personage, welk gevoel de tekst oproept."),
    dict(type="meerkeuze",
         vraag="Welke zinnen verwoorden je gevoel bij een verhaal?",
         opties=["Ce personnage me ressemble beaucoup.",
                 "Cette histoire m'a beaucoup touché.",
                 "La fin m'a surpris parce que …",
                 "Le livre compte deux cent dix pages."],
         antwoord=[0, 1, 2],
         uitleg="Het aantal bladzijden is een feit over het boek, geen beleving. De drie andere zeggen wat de tekst met jou deed."),
    dict(type="invultekst",
         vraag="Vul aan: cette histoire m'a beaucoup … . Eén voltooid deelwoord dat 'geraakt' betekent.",
         antwoord=["touché", "touchée"],
         uitleg="Toucher betekent letterlijk aanraken en in deze zin ontroeren. Ook émue of ému kan, maar touché is het gewoonste."),
    dict(type="meerkeuze",
         vraag="Waarom raadt de fiche aan je taal aan te passen aan de ontvanger?",
         opties=["omdat een gepaste toon je boodschap beter laat aankomen",
                 "omdat de regels van de grammatica anders veranderen",
                 "omdat je anders te weinig woorden schrijft",
                 "omdat elke ontvanger een ander dialect spreekt"],
         antwoord=0,
         uitleg="Respecteer de beleefdheidsconventies en gebruik de juiste toon, staat er. Dezelfde inhoud mist zijn doel als de toon ernaast zit."),
    dict(type="waarofniet",
         vraag="De fiche vraagt uitdrukkelijk dat je je tekst grondig naleest voor je hem indient.",
         antwoord=True,
         uitleg="Lees je tekst grondig na: is de communicatie helder, gepast en vlot? Dat is de laatste strategie in de lijst."),
    dict(type="meerkeuze",
         vraag="Waarop let je het best als je je Franse tekst naleest?",
         opties=["of de werkwoorden overeenkomen met hun onderwerp",
                 "of de bijvoeglijke naamwoorden het juiste geslacht hebben",
                 "of je overal dezelfde aanspreekvorm hebt aangehouden",
                 "of je tekst evenveel alinea's telt als de opdracht"],
         antwoord=[0, 1, 2],
         uitleg="Accord van het werkwoord, accord van het bijvoeglijk naamwoord en de aanspreekvorm: daar gaan de meeste punten verloren."),
    dict(type="meerkeuze",
         vraag="Je mag op het examen een spellingcontrole gebruiken. Wat vindt die controle níét?",
         opties=["een woord dat juist gespeld is maar niet past",
                 "een woord met een ontbrekend accent",
                 "een dubbele medeklinker te veel",
                 "een letter die je vergeten bent"],
         antwoord=0,
         uitleg="Schrijf je mère waar je mer bedoelt, dan staat er een bestaand woord en zwijgt de controle. Daarom blijft nalezen nodig."),
    dict(type="invultekst",
         vraag="Vul de slotformule aan die letterlijk 'hartelijk' betekent en in de meeste mails past. Eén woord.",
         antwoord=["Cordialement", "cordialement"],
         uitleg="Cordialement is de veiligste keuze: niet te stijf, niet te familiair. Bien cordialement kan ook."),
    dict(type="waarofniet",
         vraag="Je mag in een Franse schrijfopdracht sms-afkortingen gebruiken als je aan een leeftijdsgenoot schrijft.",
         antwoord=False,
         uitleg="Ook een losse tekst blijft geschreven taal op een examen. Je mag een losse toon aanslaan, maar bjr en koi29 kosten punten."),
    dict(type="meerkeuze",
         vraag="Je schrijft een mail om je te verontschuldigen dat je een afspraak gemist hebt. Welke zin past het best?",
         opties=["Je suis vraiment désolé de ne pas avoir pu venir.",
                 "Je ne suis pas venu, c'est comme ça.",
                 "Vous auriez dû me rappeler avant.",
                 "Ce n'était pas si important, finalement."],
         antwoord=0,
         uitleg="Een verontschuldiging neemt het zelf op zich. De drie andere schuiven het weg, en dat is net het omgekeerde van wat gevraagd wordt."),
    dict(type="meerkeuze",
         vraag="Hoe reageer je gepast als iemand zich bij jou verontschuldigt?",
         opties=["Ce n'est pas grave, ne vous inquiétez pas.",
                 "Je vous remercie d'avance.",
                 "Je voudrais des renseignements.",
                 "Veuillez agréer mes salutations."],
         antwoord=0,
         uitleg="Reageren op verontschuldigingen staat als aparte vaardigheid in de fiche. Ce n'est pas grave of il n'y a pas de mal."),
    dict(type="waarofniet",
         vraag="Een schrijfopdracht waarbij je op een bericht van iemand anders antwoordt, heet schriftelijke interactie.",
         antwoord=True,
         uitleg="Interactie is reageren op wat de ander schrijft of zegt. De fiche vraagt dat je daarbij ingaat op de ander en interesse toont."),
    dict(type="meerkeuze",
         vraag="Je antwoordt op een mail met drie vragen erin. Wat is de veiligste aanpak?",
         opties=["alle drie de vragen beantwoorden, in dezelfde volgorde",
                 "alleen de vraag beantwoorden die je het best kent",
                 "de vragen samenvatten in één algemene zin",
                 "de vragen in je antwoord woord voor woord herhalen"],
         antwoord=0,
         uitleg="Speel in op wat je gesprekspartner schrijft, zegt de fiche. Een vraag overslaan is op een examen een rechtstreeks puntenverlies."),
]
