# -*- coding: utf-8 -*-
"""Passé composé, imparfait en plus-que-parfait.

De vakfiche somt bij de tijden van de indicatif op: présent, passé récent,
passé composé, imparfait, plus-que-parfait, futur proche en futur simple. Dit
thema neemt de drie verleden tijden en de congruentieregel die eraan vasthangt:
het voltooid deelwoord met être komt overeen met het onderwerp.

Het verschil tussen de passé composé en de imparfait is het moeilijkste stuk
van het Franse werkwoord voor een Nederlandstalige, omdat het Nederlands die
twee niet uit elkaar houdt. Ik liep kan allebei zijn. Daarom staat hier niet
alleen hoe je de vormen maakt, maar vooral wanneer je welke kiest.

Deel 1: de passé composé, met être of avoir, en de overeenkomst.
Deel 2: de imparfait, de keuze tussen de twee, en de plus-que-parfait.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Uit welke twee delen bestaat de passé composé?",
         opties=["een hulpwerkwoord in de présent plus een voltooid deelwoord",
                 "de stam van het werkwoord plus een eigen uitgang",
                 "het werkwoord aller plus een infinitief",
                 "venir de plus een infinitief"],
         antwoord=0,
         uitleg="J'ai mangé, je suis parti. Avoir of être in het heden, en daarachter het participe passé."),
    dict(type="meerkeuze",
         vraag="Hoe maak je het voltooid deelwoord van een werkwoord op -er?",
         opties=["je vervangt -er door -é", "je vervangt -er door -i",
                 "je vervangt -er door -u", "je laat het werkwoord ongewijzigd"],
         antwoord=0,
         uitleg="Parler wordt parlé, manger wordt mangé. Werkwoorden op -ir geven -i, en veel werkwoorden op -re geven -u."),
    dict(type="invultekst",
         vraag="Zet in de passé composé: hier, j'… mangé au restaurant. Eén woord.",
         antwoord=["ai"],
         uitleg="Manger gaat met avoir: j'ai mangé. De meeste werkwoorden gaan met avoir."),
    dict(type="meerkeuze",
         vraag="Welke voltooide deelwoorden zijn juist gevormd?",
         opties=["fini (finir)", "vendu (vendre)", "pris (prendre)", "faisé (faire)"],
         antwoord=[0, 1, 2],
         uitleg="Faire geeft fait, niet faisé. Onregelmatige deelwoorden leer je als woordjes: être geeft été, avoir geeft eu, voir geeft vu."),
    dict(type="meerkeuze",
         vraag="Welke werkwoorden gaan in de passé composé met 'être'?",
         opties=["aller", "venir", "naître", "manger"],
         antwoord=[0, 1, 2],
         uitleg="Een vaste groep werkwoorden van beweging en verandering gaat met être, plus alle wederkerende. Manger hoort bij de grote avoir-groep."),
    dict(type="waarofniet",
         vraag="Alle wederkerende werkwoorden gaan in de passé composé met être.",
         antwoord=True,
         uitleg="Je me suis levé, elle s'est dépêchée, nous nous sommes vus. Daar is geen enkele uitzondering op."),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: zij is vertrokken?",
         opties=["Elle est partie.", "Elle a parti.",
                 "Elle est parti.", "Elle a partie."],
         antwoord=0,
         uitleg="Partir gaat met être, en met être komt het deelwoord overeen met het onderwerp: elle est partie, met een e."),
    dict(type="invultekst",
         vraag="Vul aan: elles sont … , zij zijn aangekomen, van arriver. Eén woord.",
         antwoord=["arrivées"],
         uitleg="Met être past het deelwoord zich aan: vrouwelijk meervoud geeft arrivées, met een e en een s."),
    dict(type="waarofniet",
         vraag="Het voltooid deelwoord na 'avoir' komt overeen met het onderwerp van de zin.",
         antwoord=False,
         uitleg="Na avoir blijft het deelwoord onveranderd: elles ont mangé. Alleen met être komt het overeen met het onderwerp."),
    dict(type="meerkeuze",
         vraag="Welke zinnen hebben een juiste overeenkomst van het deelwoord?",
         opties=["Ils sont venus hier.", "Elle est née en 2008.",
                 "Nous sommes restés une heure.", "Elles ont parties tôt."],
         antwoord=[0, 1, 2],
         uitleg="De laatste zin mengt twee fouten: partir gaat met être, en na avoir zou het deelwoord toch niet veranderen."),
    dict(type="meerkeuze",
         vraag="Hoe ontken je 'j'ai mangé'?",
         opties=["Je n'ai pas mangé.", "Je n'ai mangé pas.",
                 "Je ne pas ai mangé.", "Je n'ai pas mangé pas."],
         antwoord=0,
         uitleg="Ne en pas sluiten alleen het hulpwerkwoord in, niet het hele geheel. Het deelwoord blijft erbuiten."),
    dict(type="invultekst",
         vraag="Vul het voltooid deelwoord van 'voir' in: j'ai … ce film. Eén woord.",
         antwoord=["vu"],
         uitleg="Voir geeft vu, boire geeft bu, lire geeft lu, pouvoir geeft pu. Een hele rij korte deelwoorden op -u."),
    dict(type="waarofniet",
         vraag="Het voltooid deelwoord van 'être' is 'eu'.",
         antwoord=False,
         uitleg="Eu hoort bij avoir: j'ai eu peur. Van être is het été: j'ai été malade. En être gaat zelf met avoir, wat tegenstrijdig lijkt maar zo is."),
    dict(type="meerkeuze",
         vraag="Welk hulpwerkwoord hoort bij 'descendre' in 'elle est descendue'?",
         opties=["être, omdat descendre hier een beweging zonder voorwerp is",
                 "avoir, want descendre gaat altijd met avoir",
                 "aller, als hulpwerkwoord van beweging",
                 "faire, omdat er een handeling in zit"],
         antwoord=0,
         uitleg="Descendre, monter, sortir, rentrer en passer gaan met être als ze alleen staan, en met avoir zodra er een lijdend voorwerp bij komt: elle a descendu la valise."),
    dict(type="meerkeuze",
         vraag="Drie van deze paren uit de être-groep zijn elkaars tegengestelde. Welk paar hoort niet samen?",
         opties=["aller en venir", "entrer en sortir", "monter en descendre", "naître en rester"],
         antwoord=3,
         uitleg="Naître hoort bij mourir. Rester staat op zichzelf in de lijst. De paren onthouden helpt om de hele groep te kennen."),
    dict(type="invultekst",
         vraag="Vul het hulpwerkwoord in: nous … rentrés tard hier soir. Eén woord.",
         antwoord=["sommes"],
         uitleg="Rentrer zonder lijdend voorwerp gaat met être: nous sommes rentrés. Met een voorwerp wordt het nous avons rentré la voiture."),
    dict(type="waarofniet",
         vraag="'Il a monté les valises' en 'il est monté' hebben allebei een juist hulpwerkwoord.",
         antwoord=True,
         uitleg="Les valises is een lijdend voorwerp, dus avoir. Zonder voorwerp is monter een beweging, dus être."),
    dict(type="meerkeuze",
         vraag="Waarvoor gebruik je de passé composé?",
         opties=["voor afgelopen gebeurtenissen die de verhaallijn vooruitduwen",
                 "voor een toestand die in het verleden bleef duren",
                 "voor een gewoonte uit het verleden",
                 "voor een beschrijving van het decor van een verhaal"],
         antwoord=0,
         uitleg="De drie andere horen bij de imparfait. De passé composé zet de gebeurtenissen op een rij: il est entré, il a regardé, il est parti."),
    dict(type="meerkeuze",
         vraag="Drie van deze tijdsbepalingen kondigen een passé composé aan. Welke kondigt een imparfait aan?",
         opties=["hier", "soudain", "l'année dernière", "tous les jours"],
         antwoord=3,
         uitleg="Tous les jours wijst op een gewoonte en dus op de imparfait. De drie andere wijzen op een afgerond moment."),
    dict(type="invultekst",
         vraag="Vul het deelwoord van 'prendre' in: elle a … le train de huit heures. Eén woord.",
         antwoord=["pris"],
         uitleg="Prendre geeft pris, mettre geeft mis, écrire geeft écrit. Deelwoorden op -is en -it komen vaak samen voor."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Van welke vorm vertrek je om de imparfait te maken?",
         opties=["de nous-vorm van de présent, zonder -ons",
                 "de infinitief, zonder de uitgang -er of -ir",
                 "het voltooid deelwoord van hetzelfde werkwoord",
                 "de je-vorm van de présent, zonder de uitgang"],
         antwoord=0,
         uitleg="Nous parlons geeft de stam parl-, en daar komt -ais, -ais, -ait, -ions, -iez, -aient bij. Nous finissons geeft finiss-, dus je finissais."),
    dict(type="meerkeuze",
         vraag="Welke rij geeft de uitgangen van de imparfait?",
         opties=["-ais, -ais, -ait, -ions, -iez, -aient",
                 "-e, -es, -e, -ons, -ez, -ent",
                 "-ai, -as, -a, -ons, -ez, -ont",
                 "-rais, -rais, -rait, -rions, -riez, -raient"],
         antwoord=0,
         uitleg="De laatste rij is de conditionnel, die de r van de infinitief behoudt. De derde is de futur simple."),
    dict(type="invultekst",
         vraag="Zet in de imparfait: quand j'étais petit, je (jouer) dehors. Eén werkwoordsvorm.",
         antwoord=["jouais"],
         uitleg="Nous jouons geeft jou-, dus je jouais. Een gewoonte uit het verleden vraagt altijd de imparfait."),
    dict(type="waarofniet",
         vraag="Avoir, aller en faire hebben in de imparfait alle drie een onregelmatige stam.",
         antwoord=False,
         uitleg="Ze bouwen alle drie keurig op hun nous-vorm: j'avais, j'allais, je faisais. Être is het enige werkwoord met een echt onregelmatige stam: j'étais."),
    dict(type="meerkeuze",
         vraag="Waarvoor gebruik je de imparfait?",
         opties=["voor het decor, een gewoonte of een toestand in het verleden",
                 "voor een gebeurtenis die op één bepaald moment afliep",
                 "voor iets dat vandaag of morgen nog moet gebeuren",
                 "voor een bevel of een vraag aan iemand anders"],
         antwoord=0,
         uitleg="Il faisait beau, j'avais dix ans, nous allions souvent à la mer. Geen begin en geen einde: de tijd loopt gewoon door."),
    dict(type="meerkeuze",
         vraag="Welke tijdsbepalingen kondigen meestal een imparfait aan?",
         opties=["souvent", "chaque été", "d'habitude", "tout à coup"],
         antwoord=[0, 1, 2],
         uitleg="Tout à coup wijst op een plotse gebeurtenis en dus op de passé composé. De drie andere wijzen op herhaling of gewoonte."),
    dict(type="meerkeuze",
         vraag="'Je lisais quand le téléphone a sonné.' Waarom staan er twee verschillende tijden in?",
         opties=["lezen was aan de gang, de telefoon ging op één moment",
                 "lezen gebeurde na het telefoontje",
                 "lezen is een gewoonte, bellen niet",
                 "het is een fout; beide moeten in dezelfde tijd staan"],
         antwoord=0,
         uitleg="De imparfait is de achtergrond, de passé composé de gebeurtenis die erin valt. Dat patroon komt in bijna elk verhaal voor."),
    dict(type="invultekst",
         vraag="Vul in de imparfait aan: il … beau ce jour-là, het was mooi weer. Eén werkwoordsvorm.",
         antwoord=["faisait"],
         uitleg="Nous faisons geeft fais-, dus il faisait. Het weer in een verhaal staat bijna altijd in de imparfait."),
    dict(type="waarofniet",
         vraag="Het Nederlandse 'ik las' kan in het Frans zowel een imparfait als een passé composé zijn.",
         antwoord=True,
         uitleg="Je lisais als het aan de gang was, j'ai lu als het af is. Het Nederlands dwingt je niet te kiezen, het Frans wel."),
    dict(type="meerkeuze",
         vraag="Welke zinnen zouden in het Frans in de imparfait staan?",
         opties=["Elke zomer gingen we naar zee.",
                 "Hij was tien jaar toen hij verhuisde.",
                 "Het regende de hele dag.",
                 "Gisteren ben ik naar de tandarts geweest."],
         antwoord=[0, 1, 2],
         uitleg="De laatste is één afgerond feit op een bepaalde dag: hier, je suis allé chez le dentiste. De drie andere zijn gewoonte, leeftijd en decor."),
    dict(type="meerkeuze",
         vraag="Hoe maak je de plus-que-parfait?",
         opties=["het hulpwerkwoord in de imparfait plus het voltooid deelwoord",
                 "het hulpwerkwoord in de présent plus het voltooid deelwoord",
                 "de stam plus de uitgangen van de futur",
                 "aller in de imparfait plus de infinitief"],
         antwoord=0,
         uitleg="J'avais mangé, j'étais parti. Wat de passé composé is voor het heden, is de plus-que-parfait voor het verleden."),
    dict(type="invultekst",
         vraag="Zet in de plus-que-parfait: quand je suis arrivé, il … déjà parti. Eén woord.",
         antwoord=["était"],
         uitleg="Partir gaat met être, en in de plus-que-parfait staat dat être in de imparfait: il était parti."),
    dict(type="meerkeuze",
         vraag="Wat drukt de plus-que-parfait uit?",
         opties=["iets dat al gebeurd was voor een ander moment in het verleden",
                 "iets dat net gebeurd is op het ogenblik dat je spreekt",
                 "iets dat straks zal gebeuren, kort na dit moment",
                 "een gewoonte die in het verleden bleef doorgaan"],
         antwoord=0,
         uitleg="Twee lagen in het verleden: quand il est arrivé, le train était déjà parti. Het vertrek ligt vóór de aankomst."),
    dict(type="waarofniet",
         vraag="In de plus-que-parfait komt het deelwoord met être nog altijd overeen met het onderwerp.",
         antwoord=True,
         uitleg="Elles étaient parties. De congruentieregel hangt aan être vast, niet aan de tijd waarin être staat."),
    dict(type="meerkeuze",
         vraag="Welke volgorde van gebeurtenissen klopt in 'Il m'a dit qu'il avait perdu ses clés'?",
         opties=["eerst de sleutels kwijt, daarna het zeggen",
                 "eerst het zeggen, daarna de sleutels kwijt",
                 "allebei tegelijk",
                 "allebei in de toekomst"],
         antwoord=0,
         uitleg="De plus-que-parfait zet de ene gebeurtenis een stap verder terug in de tijd. Dat is precies waarvoor hij dient."),
    dict(type="meerkeuze",
         vraag="Welke zinnen gebruiken de plus-que-parfait correct?",
         opties=["Elle avait oublié son parapluie.", "Nous étions déjà sortis de la salle.",
                 "Ils s'étaient levés très tôt ce matin-là.", "J'ai avais mangé."],
         antwoord=[0, 1, 2],
         uitleg="De laatste stapelt twee hulpwerkwoorden op. Er mag er maar één staan, en het moet in de imparfait staan."),
    dict(type="invultekst",
         vraag="Vul aan: nous … fini quand ils sont arrivés. Het hulpwerkwoord in de imparfait, één woord.",
         antwoord=["avions"],
         uitleg="Finir gaat met avoir, dus nous avions fini. Wij waren al klaar toen zij aankwamen."),
    dict(type="waarofniet",
         vraag="'Avait' en 'était' zijn allebei vormen van de futur simple.",
         antwoord=False,
         uitleg="Het zijn vormen van de imparfait: il avait van avoir, il était van être. Zie je er een van voor een voltooid deelwoord staan, dan lees je een plus-que-parfait."),
    dict(type="meerkeuze",
         vraag="Je leest in een verhaal: 'Il pleuvait. Soudain, une voiture a freiné.' Welk verband leggen de twee tijden?",
         opties=["de regen is het decor, het remmen de gebeurtenis",
                 "de regen begon pas na het remmen van de auto",
                 "de twee dingen staan helemaal los van elkaar",
                 "allebei zijn het gewoontes die zich herhaalden"],
         antwoord=0,
         uitleg="De imparfait schildert, de passé composé vertelt. Wie dat patroon herkent, leest een Frans verhaal veel sneller."),
    dict(type="meerkeuze",
         vraag="Drie van deze vormen zijn voltooide deelwoorden. Welke is een persoonsvorm?",
         opties=["allé", "fait", "venu", "allez"],
         antwoord=3,
         uitleg="Allez is de vous-vorm van aller. Allé is het deelwoord. De fiche noemt dat onderscheid zelf als voorbeeld bij het lezen."),
]
