# -*- coding: utf-8 -*-
"""Voornaamwoorden: COD, COI, y en en, en de plaats die ze innemen.

De vakfiche zet onder pronoms zeven soorten op een rij: persoonlijk (sujet,
COD, COI, tonique, y en en), aanwijzend, bezittelijk, vragend, betrekkelijk
(qui, que, dont, où), wederkerend en onbepaald. Ze vraagt er uitdrukkelijk
de plaats bij: waar het voornaamwoord in de zin staat, en wat er gebeurt als
er twee samenkomen (le/la/les + lui/leur + y + en).

De fiche legt zelf uit waarom dit onderdeel voor het lézen zo zwaar weegt: een
voornaamwoord verwijst naar iets uit een vorige zin, en wie niet ziet waarnaar,
leest de samenhang van de tekst niet meer. Daarom staan de zinsdelen erbij:
onderwerp, persoonsvorm, lijdend voorwerp (COD) en meewerkend voorwerp (COI).

Deel 1: de persoonlijke voornaamwoorden, COD en COI, y en en.
Deel 2: de betrekkelijke, aanwijzende, bezittelijke en onbepaalde.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Welke rij geeft de onderwerpsvormen van het persoonlijk voornaamwoord?",
         opties=["je, tu, il, elle, on, nous, vous, ils, elles",
                 "me, te, le, la, nous, vous, les",
                 "moi, toi, lui, elle, nous, vous, eux, elles",
                 "me, te, lui, nous, vous, leur"],
         antwoord=0,
         uitleg="De tweede rij is COD, de derde is de toniques, de vierde is COI. Alleen de eerste kan voor een vervoegd werkwoord staan als onderwerp."),
    dict(type="meerkeuze",
         vraag="Wat is het lijdend voorwerp (COD) in 'Marie achète le livre'?",
         opties=["le livre", "Marie", "achète", "er is er geen"],
         antwoord=0,
         uitleg="Het COD antwoordt op de vraag qui of quoi na het werkwoord: elle achète quoi ? Le livre."),
    dict(type="invultekst",
         vraag="Vervang het lijdend voorwerp: Marie achète le livre wordt Marie … achète. Eén woord.",
         antwoord=["l'"],
         uitleg="Le wordt l' voor een klinker: Marie l'achète. Het voornaamwoord springt vóór het werkwoord, anders dan in het Nederlands."),
    dict(type="waarofniet",
         vraag="Het lijdend voorwerp staat in het Frans vóór het vervoegde werkwoord zodra het een voornaamwoord wordt.",
         antwoord=True,
         uitleg="Je vois Pierre wordt je le vois, niet je vois le. Dat is precies omgekeerd aan het Nederlands, en het blijft de valkuil nummer één."),
    dict(type="meerkeuze",
         vraag="Welke rij geeft de vormen van het meewerkend voorwerp (COI)?",
         opties=["me, te, lui, nous, vous, leur", "me, te, le, la, nous, vous, les",
                 "moi, toi, lui, eux", "le, la, l', les"],
         antwoord=0,
         uitleg="Lui en leur zijn de herkenbare COI-vormen: lui voor één persoon, leur voor meerdere. Ze gelden voor mannelijk en vrouwelijk allebei."),
    dict(type="meerkeuze",
         vraag="Hoe weet je dat een werkwoord een COI vraagt en geen COD?",
         opties=["er staat à voor de persoon in de volle zin",
                 "het werkwoord staat in de verleden tijd",
                 "de persoon staat vooraan in de zin",
                 "het werkwoord eindigt op -er"],
         antwoord=0,
         uitleg="Parler à quelqu'un, téléphoner à quelqu'un, répondre à quelqu'un. Die à verraadt het COI, en dus lui of leur."),
    dict(type="invultekst",
         vraag="Vervang het meewerkend voorwerp: je téléphone à mes parents wordt je … téléphone. Eén woord.",
         antwoord=["leur"],
         uitleg="Téléphoner à is COI, en meerdere personen geven leur. Nooit leurs: het voornaamwoord krijgt geen s."),
    dict(type="meerkeuze",
         vraag="Welke zinnen gebruiken lui of leur correct?",
         opties=["Je lui parle tous les jours.", "Elle leur a répondu hier.",
                 "Nous lui téléphonons ce soir.", "Je lui vois à l'école."],
         antwoord=[0, 1, 2],
         uitleg="Voir vraagt geen à, dus daar hoort je le vois of je la vois. De drie andere werkwoorden gaan wel met à."),
    dict(type="meerkeuze",
         vraag="Wat vervangt 'y' in een Franse zin?",
         opties=["een plaats, of een groep met à die geen persoon is",
                 "altijd een persoon die het meewerkend voorwerp is",
                 "een hoeveelheid die al genoemd is",
                 "het onderwerp van de vorige zin"],
         antwoord=0,
         uitleg="Je vais à Paris wordt j'y vais. Je pense à mon examen wordt j'y pense. Gaat het over een persoon, dan blijft het à lui of à elle."),
    dict(type="meerkeuze",
         vraag="Wat vervangt 'en' in een Franse zin?",
         opties=["een groep die met de, du, de la of des begint",
                 "een plaats waar je naartoe gaat",
                 "de persoon tot wie je spreekt",
                 "een werkwoord in de infinitief"],
         antwoord=0,
         uitleg="Je mange du pain wordt j'en mange. Je viens de Paris wordt j'en viens. En is de tegenhanger van y."),
    dict(type="invultekst",
         vraag="Vervang de hoeveelheid: j'ai trois frères wordt j'… ai trois. Eén woord.",
         antwoord=["en"],
         uitleg="Bij en blijft het getal staan: j'en ai trois. Zonder dat getal zou de zin onvolledig zijn."),
    dict(type="waarofniet",
         vraag="Y en en staan in het Frans altijd achter het vervoegde werkwoord.",
         antwoord=False,
         uitleg="Ze staan er net voor: j'y vais, j'en veux. Staat er een infinitief, dan gaan ze daarvoor: je vais y aller, je veux en prendre."),
    dict(type="meerkeuze",
         vraag="Twee voornaamwoorden in één zin: wat is de juiste volgorde in 'il me le donne'?",
         opties=["me komt voor le", "le komt voor me",
                 "ze mogen in elke volgorde staan", "er mogen er geen twee samen staan"],
         antwoord=0,
         uitleg="De volgorde is me, te, se, nous, vous — dan le, la, les — dan lui, leur — dan y — dan en. Dus il me le donne, maar il le lui donne."),
    dict(type="meerkeuze",
         vraag="Welke zinnen met twee voornaamwoorden staan in de juiste volgorde?",
         opties=["Je te le dis.", "Il le lui a donné.", "Elle nous en parle.", "Je lui le donne."],
         antwoord=[0, 1, 2],
         uitleg="De laatste moet je le lui donne zijn: le komt vóór lui. Bij te en nous is het net omgekeerd."),
    dict(type="waarofniet",
         vraag="Na een voorzetsel zoals avec of chez gebruik je in het Frans gewoon je, tu en il.",
         antwoord=False,
         uitleg="Daar komen de tonische vormen: chez moi, avec lui, sans eux. Je gebruikt ze ook om te benadrukken (moi, je pense que non) en als een voornaamwoord alleen staat."),
    dict(type="invultekst",
         vraag="Vul de tonische vorm in: je viens avec … , ik kom met jou. Eén woord.",
         antwoord=["toi"],
         uitleg="Na een voorzetsel kan tu niet: het wordt toi. Net zo avec moi, avec lui, avec elles."),
    dict(type="waarofniet",
         vraag="In de bevelende zin 'donne-le-moi' staan de voornaamwoorden achter het werkwoord.",
         antwoord=True,
         uitleg="Bij een bevestigend bevel springen ze erachter met streepjes, en me wordt moi. In de ontkenning staat alles weer vooraan: ne me le donne pas."),
    dict(type="meerkeuze",
         vraag="Wat is het verschil tussen 'on' en 'nous'?",
         opties=["on wordt als enkelvoud vervoegd, nous als meervoud",
                 "on is vrouwelijk, nous is mannelijk",
                 "on bestaat alleen in de verleden tijd",
                 "on kan geen onderwerp zijn van een zin"],
         antwoord=0,
         uitleg="On va au cinéma betekent in de spreektaal wij gaan, maar het werkwoord blijft in de hij-vorm staan. On kan ook men betekenen."),
    dict(type="meerkeuze",
         vraag="Welke zinnen met wederkerende voornaamwoorden zijn juist?",
         opties=["Je me lève tôt.", "Tu te souviens de lui ?",
                 "Nous nous dépêchons.", "Il se lave les mains de lui."],
         antwoord=[0, 1, 2],
         uitleg="De laatste zin stapelt twee keer hetzelfde op. Il se lave les mains volstaat."),
    dict(type="meerkeuze",
         vraag="'Les élèves se sont écrit toute l'année.' Wat betekent dat se hier?",
         opties=["ze schreven aan elkaar", "ze schreven aan zichzelf",
                 "ze werden geschreven", "ze lieten iemand schrijven"],
         antwoord=0,
         uitleg="Een wederkerend werkwoord kan ook wederkerig zijn: ils se parlent, ils se voient, ils se sont écrit. De context beslist."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Welke vier betrekkelijke voornaamwoorden noemt de vakfiche met name?",
         opties=["qui, que, dont, où", "qui, quoi, quel, quand",
                 "ce, cet, cette, ces", "le, la, les, leur"],
         antwoord=0,
         uitleg="Qui, que, dont en où. Met die vier bouw je zowat elke betrekkelijke bijzin op B1-niveau."),
    dict(type="meerkeuze",
         vraag="Wanneer gebruik je 'qui' in een betrekkelijke bijzin?",
         opties=["als het voornaamwoord het onderwerp van de bijzin is",
                 "als het voornaamwoord het lijdend voorwerp is",
                 "als er een plaats bedoeld wordt",
                 "als er bezit bedoeld wordt"],
         antwoord=0,
         uitleg="L'homme qui parle: qui doet de handeling. Direct na qui komt dus een vervoegd werkwoord."),
    dict(type="invultekst",
         vraag="Vul aan: le livre … je lis est passionnant. Het voornaamwoord dat lijdend voorwerp is.",
         antwoord=["que", "qu'"],
         uitleg="Na que komt een onderwerp: le livre que je lis. Na qui komt meteen een werkwoord: le livre qui est sur la table."),
    dict(type="waarofniet",
         vraag="'Qui' verkort voor een klinker tot qu', net zoals 'que' dat doet.",
         antwoord=False,
         uitleg="Qui blijft altijd qui: l'homme qui arrive. Alleen que verkort: le film qu'il regarde. Dat verschil helpt je de twee uit elkaar te houden."),
    dict(type="meerkeuze",
         vraag="Wanneer gebruik je 'dont'?",
         opties=["als er in de bijzin een de hoort bij het werkwoord of het naamwoord",
                 "als de bijzin een plaats aangeeft",
                 "als de bijzin een tijd aangeeft",
                 "als het voornaamwoord het onderwerp is"],
         antwoord=0,
         uitleg="Le film dont je parle, want parler de. La fille dont le père est médecin, want le père de la fille."),
    dict(type="meerkeuze",
         vraag="Welke zinnen met dont zijn juist gebouwd?",
         opties=["C'est le livre dont j'ai besoin.", "Voici l'ami dont je t'ai parlé.",
                 "C'est la ville dont il vient.", "C'est la maison dont j'habite."],
         antwoord=[0, 1, 2],
         uitleg="Habiter gaat niet met de maar met à of dans, dus daar hoort où: la maison où j'habite. De drie andere werkwoorden vragen wel de."),
    dict(type="meerkeuze",
         vraag="Waarvoor gebruik je 'où' in een betrekkelijke bijzin?",
         opties=["voor een plaats en ook voor een tijdstip",
                 "alleen voor een plaats, nooit voor een tijd",
                 "alleen voor een persoon",
                 "alleen in een vraagzin"],
         antwoord=0,
         uitleg="Le pays où je suis né, maar ook le jour où il est parti. Dat tweede gebruik verrast veel lezers."),
    dict(type="invultekst",
         vraag="Vul aan: c'est le jour … tout a changé. Eén woord.",
         antwoord=["où"],
         uitleg="Bij een tijdstip gebruikt het Frans où en niet que. Le jour que is spreektaal en telt op een examen als fout."),
    dict(type="waarofniet",
         vraag="'Ce qui' en 'ce que' verwijzen naar een heel idee en niet naar één naamwoord.",
         antwoord=True,
         uitleg="Je ne comprends pas ce qu'il veut. Il est parti, ce qui m'a surpris: ce qui slaat op de hele vorige zin."),
    dict(type="meerkeuze",
         vraag="Welke vormen zijn zelfstandige bezittelijke voornaamwoorden?",
         opties=["le mien", "la tienne", "les leurs", "leur"],
         antwoord=[0, 1, 2],
         uitleg="Leur hoort voor een naamwoord: leur maison. Le mien, la tienne en les leurs staan alleen: ce livre est le mien."),
    dict(type="meerkeuze",
         vraag="Hoe antwoord je op 'C'est ta voiture ?' met een bezittelijk voornaamwoord?",
         opties=["Oui, c'est la mienne.", "Oui, c'est le mien.",
                 "Oui, c'est ma.", "Oui, c'est mienne."],
         antwoord=0,
         uitleg="Voiture is vrouwelijk, dus la mienne. Het voornaamwoord volgt het geslacht van het ding, niet van de eigenaar."),
    dict(type="invultekst",
         vraag="Vul aan: ce sac n'est pas le mien, c'est … , het is het zijne. Twee woorden.",
         antwoord=["le sien"],
         uitleg="Le sien voor een mannelijk ding, la sienne voor een vrouwelijk. Ook hier beslist het ding, niet de eigenaar."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn aanwijzende voornaamwoorden die alleen kunnen staan?",
         opties=["celui", "celle", "ceux", "cette"],
         antwoord=[0, 1, 2],
         uitleg="Cette hoort voor een naamwoord: cette maison. Celui, celle, ceux en celles staan alleen: celui de Marie, celle que je préfère."),
    dict(type="meerkeuze",
         vraag="'Quel est ton livre préféré ? — Celui de Camus.' Wat doet celui hier?",
         opties=["het vervangt het woord livre dat al genoemd is",
                 "het vervangt de naam Camus",
                 "het vraagt naar een keuze",
                 "het geeft een bevel"],
         antwoord=0,
         uitleg="Celui staat voor le livre en voorkomt dat je het woord herhaalt. Daarom komt er altijd iets achter: celui de, celui qui, celui-ci."),
    dict(type="waarofniet",
         vraag="'Ça' is de verzorgde schrijftaalvorm en 'cela' hoort in de spreektaal thuis.",
         antwoord=False,
         uitleg="Het is net omgekeerd: ça va ? is ongedwongen, cela est vrai is verzorgde geschreven taal. In een examentekst kan je allebei tegenkomen."),
    dict(type="meerkeuze",
         vraag="Drie van deze woorden zijn onbepaalde voornaamwoorden. Welk woord is vragend?",
         opties=["quelqu'un", "personne", "rien", "lequel"],
         antwoord=3,
         uitleg="Lequel is vragend: lequel préfères-tu ? Quelqu'un is iemand, personne is niemand, rien is niets."),
    dict(type="invultekst",
         vraag="Vul aan: il n'y a … dans la salle, er is niemand in de zaal. Eén woord.",
         antwoord=["personne"],
         uitleg="Personne vervangt pas in de ontkenning: il n'y a personne, en niet il n'y a pas personne. Hetzelfde geldt voor rien en jamais."),
    dict(type="meerkeuze",
         vraag="Welke vraag is correct gesteld met een vragend voornaamwoord?",
         opties=["Qui a téléphoné ?", "Que a téléphoné ?",
                 "Quoi a téléphoné ?", "Lequel a téléphoné des ?"],
         antwoord=0,
         uitleg="Qui vraagt naar een persoon en kan onderwerp zijn. Que en quoi vragen naar een ding: que fais-tu ? of tu fais quoi ?"),
    dict(type="waarofniet",
         vraag="'Lequel' past zich aan in geslacht en getal: laquelle, lesquels, lesquelles.",
         antwoord=True,
         uitleg="J'hésite entre ces deux robes. Laquelle préfères-tu ? Met à en de wordt het auquel en duquel."),
    dict(type="meerkeuze",
         vraag="Je leest: 'Sophie a rencontré Paul. Elle lui a tout raconté.' Wie vertelde wat aan wie?",
         opties=["Sophie vertelde alles aan Paul", "Paul vertelde alles aan Sophie",
                 "Sophie vertelde alles aan zichzelf", "iemand anders vertelde het aan hen"],
         antwoord=0,
         uitleg="Elle is het onderwerp en slaat terug op Sophie. Lui is COI en slaat op Paul. Precies dit soort terugzoeken vraagt de fiche bij het lezen."),
]
