# -*- coding: utf-8 -*-
"""Woordvelden: school, werk, reizen en de samenleving.

Het tweede deel van de tweeëntwintig woordvelden uit de vakfiche: onderwijs en
vorming, de professionele wereld en de beroepen, transportmiddelen, vakantie en
reizen, winkels en diensten, het weer, landen en nationaliteiten, communicatie
en multimedia, cijfers, gewichten, maten en hoeveelheden, uur en plaats, en de
instructietaal.

Die laatste is makkelijk over het hoofd te zien en toch de belangrijkste van
allemaal: de instructietaal is het Frans van de opdrachten zelf. Wie niet weet
wat cochez, reliez of soulignez betekent, verliest punten op vragen waarvan hij
het antwoord kende. Daarom staat ze hier vooraan in deel 2.

Deel 1: school, werk en de wereld rond je.
Deel 2: de instructietaal, de cijfers, het uur en het weer.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is 'une matière' in een tekst over school?",
         opties=["een vak", "een les", "een leerkracht", "een klaslokaal"],
         antwoord=0,
         uitleg="Ma matière préférée, c'est l'histoire. Une leçon is een les, un enseignant een leerkracht, une salle de classe een lokaal."),
    dict(type="meerkeuze",
         vraag="Welke woorden horen bij het schoolleven?",
         opties=["un bulletin", "un horaire", "une interrogation", "un chantier"],
         antwoord=[0, 1, 2],
         uitleg="Un chantier is een werf. Un bulletin is een rapport, un horaire een uurrooster, une interrogation een toets."),
    dict(type="invultekst",
         vraag="Vul in: j'ai réussi mon … , ik ben geslaagd voor mijn examen. Eén woord.",
         antwoord=["examen"],
         uitleg="Réussir un examen is slagen, rater of échouer is buizen. Passer un examen betekent het afleggen, niet slagen."),
    dict(type="waarofniet",
         vraag="'Passer un examen' betekent in het Frans dat je geslaagd bent.",
         antwoord=False,
         uitleg="Passer betekent alleen dat je het examen aflegt. Geslaagd is réussir, en die twee verwisselen is een valse vriend."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'un stage'?",
         opties=["een stage of een cursus van enkele dagen", "een toneelstuk",
                 "een trap in een gebouw", "een examenperiode"],
         antwoord=0,
         uitleg="Un stage en entreprise is een bedrijfsstage, un stage de tennis een tenniskamp. Un stagiaire is de stagiair."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn beroepen?",
         opties=["un boulanger", "une avocate", "un plombier", "un bâtiment"],
         antwoord=[0, 1, 2],
         uitleg="Un bâtiment is een gebouw. Un boulanger is een bakker, une avocate een advocate, un plombier een loodgieter."),
    dict(type="invultekst",
         vraag="Vul in: elle travaille comme … dans une école, ze werkt als leerkracht. Eén woord, vrouwelijk.",
         antwoord=["enseignante", "institutrice", "professeure"],
         uitleg="Na comme komt er geen lidwoord: elle travaille comme enseignante. In het Nederlands zeggen we dat ook zo."),
    dict(type="waarofniet",
         vraag="'Un emploi' en 'un travail' betekenen allebei werk.",
         antwoord=True,
         uitleg="Un emploi is eerder de betrekking, un travail het werk zelf. Chercher un emploi is een baan zoeken, être au chômage is werkloos zijn."),
    dict(type="meerkeuze",
         vraag="Wat is 'un entretien d'embauche'?",
         opties=["een sollicitatiegesprek", "een arbeidsovereenkomst",
                 "een loonbriefje", "een vergadering met collega's"],
         antwoord=0,
         uitleg="Embaucher is aanwerven. Un entretien is een gesprek, ook bij de dokter of op school."),
    dict(type="meerkeuze",
         vraag="Welke woorden zijn vervoermiddelen?",
         opties=["un car", "un camion", "un avion", "un carnet"],
         antwoord=[0, 1, 2],
         uitleg="Un carnet is een boekje of een rittenkaart. Un car is een reisbus, un camion een vrachtwagen, un avion een vliegtuig."),
    dict(type="meerkeuze",
         vraag="Hoe zeg je in het Frans dat je met de trein gaat?",
         opties=["en train", "au train", "sur le train", "de train"],
         antwoord=0,
         uitleg="En voor vervoermiddelen waar je in zit: en train, en voiture, en avion. À voor vervoer waar je op zit: à pied, à vélo, à cheval."),
    dict(type="invultekst",
         vraag="Vul in: je viens à l'école à … , ik kom met de fiets. Eén woord.",
         antwoord=["vélo"],
         uitleg="À vélo, want je zit erop. Je vindt ook en vélo in modern Frans, maar à vélo blijft de vorm die op een examen altijd juist is."),
    dict(type="waarofniet",
         vraag="'Un car' is in het Frans een gewone personenwagen.",
         antwoord=False,
         uitleg="Un car is een reisbus of een schoolbus. Een personenwagen is une voiture, en in het Frans van Québec ook un char."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'un aller-retour'?",
         opties=["een heen-en-terugticket", "een omweg",
                 "een vertraging", "een overstap"],
         antwoord=0,
         uitleg="Un aller simple is enkel heen. Une correspondance is de overstap, un retard de vertraging."),
    dict(type="meerkeuze",
         vraag="Drie van deze woorden horen bij een verblijf op reis. Welk woord hoort er niet bij?",
         opties=["une auberge de jeunesse", "une chambre d'hôte",
                 "un camping", "une agence pour l'emploi"],
         antwoord=3,
         uitleg="Une agence pour l'emploi is een arbeidsbureau. Une auberge de jeunesse is een jeugdherberg, une chambre d'hôte een gastenkamer."),
    dict(type="waarofniet",
         vraag="Namen van nationaliteiten schrijf je in het Frans met een kleine letter als ze een bijvoeglijk naamwoord zijn.",
         antwoord=True,
         uitleg="Un étudiant belge met een kleine letter, maar un Belge als het een zelfstandig naamwoord is. In het Engels staat alles met een hoofdletter."),
    dict(type="meerkeuze",
         vraag="Welke vorm is juist: hij komt uit Frankrijk?",
         opties=["Il vient de France.", "Il vient de la France.",
                 "Il vient du France.", "Il vient à France."],
         antwoord=0,
         uitleg="Bij vrouwelijke landen gebruik je de zonder lidwoord: de France, de Belgique. Bij mannelijke landen wordt het du: du Portugal, du Canada."),
    dict(type="invultekst",
         vraag="Vul aan: j'habite … Belgique. Eén woord dat 'in' betekent bij een vrouwelijk land.",
         antwoord=["en"],
         uitleg="En bij vrouwelijke landen en bij landen die met een klinker beginnen: en France, en Italie, en Iran. Au bij mannelijke: au Maroc."),
    dict(type="meerkeuze",
         vraag="Drie van deze woorden horen bij winkels en diensten. Welk woord hoort bij de school?",
         opties=["la caisse", "une réduction", "la livraison", "la récréation"],
         antwoord=3,
         uitleg="La récréation is de speeltijd op school. La caisse is de kassa, une réduction een korting, la livraison de levering."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'un portable' in een Franse tekst over communicatie?",
         opties=["een gsm of een draagbare computer", "een postpakket",
                 "een televisietoestel", "een afstandsbediening"],
         antwoord=0,
         uitleg="Un portable is meestal de gsm, soms de laptop. Een Belg zegt un GSM, iemand uit Québec un cellulaire."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Een examenopdracht zegt 'cochez la bonne réponse'. Wat moet je doen?",
         opties=["het juiste antwoord aankruisen", "het juiste antwoord opschrijven",
                 "het juiste antwoord onderlijnen", "het juiste antwoord doorstrepen"],
         antwoord=0,
         uitleg="Cocher is aankruisen. Deze woorden kennen is punten waard op vragen waarvan je het antwoord al wist."),
    dict(type="meerkeuze",
         vraag="Welke opdrachtwoorden vragen dat je zelf iets schrijft?",
         opties=["complétez", "rédigez", "décrivez", "cochez"],
         antwoord=[0, 1, 2],
         uitleg="Cocher is aankruisen en vraagt geen tekst. Compléter is aanvullen, rédiger opstellen, décrire beschrijven."),
    dict(type="invultekst",
         vraag="Een opdracht zegt 'soulignez le verbe'. Wat moet je met dat werkwoord doen? Eén woord in het Nederlands.",
         antwoord=["onderlijnen", "onderstrepen"],
         uitleg="Souligner, van ligne, lijn. Barrer is doorstrepen, entourer is omcirkelen."),
    dict(type="waarofniet",
         vraag="'Reliez' in een opdracht betekent dat je twee dingen met elkaar moet verbinden.",
         antwoord=True,
         uitleg="Relier is verbinden, zoals bij een sleepvraag waar je linkerkolom en rechterkolom aan elkaar koppelt."),
    dict(type="meerkeuze",
         vraag="Wat vraagt een opdracht die begint met 'justifiez votre réponse' ?",
         opties=["leg uit waarom je dat antwoord geeft",
                 "schrijf je antwoord in het Nederlands",
                 "kies een antwoord uit de lijst",
                 "verbeter het antwoord van de vorige vraag"],
         antwoord=0,
         uitleg="Justifier is verantwoorden. Meestal wil men dat je het stukje tekst aanwijst waar het antwoord op steunt."),
    dict(type="meerkeuze",
         vraag="Welke getallen zijn in het Frans van Frankrijk juist geschreven?",
         opties=["soixante-dix", "quatre-vingts", "quatre-vingt-dix", "septante-cinq"],
         antwoord=[0, 1, 2],
         uitleg="Septante bestaat wel, maar in België en Zwitserland, niet in Frankrijk. Let ook op: quatre-vingts met een s, maar quatre-vingt-dix zonder."),
    dict(type="invultekst",
         vraag="Schrijf het getal 80 voluit in het Frans zoals men het in Frankrijk zegt.",
         antwoord=["quatre-vingts"],
         uitleg="Vier maal twintig. De s valt weg zodra er nog een getal achter komt: quatre-vingt-trois."),
    dict(type="waarofniet",
         vraag="Het Frans gebruikt net als het Engels een punt als decimaalteken: 3.5.",
         antwoord=False,
         uitleg="Het Frans schrijft een komma, net als het Nederlands: 3,5, uitgesproken als trois virgule cinq."),
    dict(type="meerkeuze",
         vraag="Wat is 'une livre' in een tekst over gewicht?",
         opties=["een pond, ongeveer een halve kilo", "een kilogram",
                 "een gram", "een ton"],
         antwoord=0,
         uitleg="Une livre met een e is een pond. Un livre zonder e is een boek. Het geslacht maakt hier het hele verschil."),
    dict(type="meerkeuze",
         vraag="Welke woorden duiden een hoeveelheid aan?",
         opties=["beaucoup de", "un peu de", "assez de", "parce que"],
         antwoord=[0, 1, 2],
         uitleg="Parce que is een voegwoord. Na een hoeveelheid komt altijd de zonder lidwoord: beaucoup de travail, un peu d'eau."),
    dict(type="invultekst",
         vraag="Vul aan: il y a beaucoup … travail. Eén woord.",
         antwoord=["de"],
         uitleg="Na een hoeveelheid valt het lidwoord weg: beaucoup de, trop de, assez de, peu de. Beaucoup du travail is fout."),
    dict(type="meerkeuze",
         vraag="Hoe zeg je in het Frans dat het kwart over drie is?",
         opties=["trois heures et quart", "trois heures moins le quart",
                 "trois heures et demie", "quart après trois"],
         antwoord=0,
         uitleg="Et quart is kwart over, moins le quart is kwart voor, et demie is half. Let op: drie uur en half is bij ons half vier."),
    dict(type="waarofniet",
         vraag="'Quatorze heures trente' betekent in het Frans half twee in de namiddag.",
         antwoord=False,
         uitleg="Quatorze heures is veertien uur, dus quatorze heures trente is half drie. Uurroosters tellen tot vierentwintig; in een gesprek zegt men deux heures et demie."),
    dict(type="meerkeuze",
         vraag="Drie van deze uitdrukkingen geven een plaats aan. Welke geeft een oorzaak?",
         opties=["à côté de", "en face de", "au milieu de", "à cause de"],
         antwoord=3,
         uitleg="À cause de geeft een oorzaak. À côté de is naast, en face de tegenover, au milieu de in het midden van."),
    dict(type="meerkeuze",
         vraag="Wat betekent 'il fait doux' in een weerbericht?",
         opties=["het is zacht weer", "het regent lichtjes",
                 "het is zonnig en warm", "er staat weinig wind"],
         antwoord=0,
         uitleg="Doux is zacht. Il fait frais is fris, il fait lourd is drukkend, il fait un temps de chien is hondenweer."),
    dict(type="meerkeuze",
         vraag="Drie van deze zinnen beschrijven het weer correct. Welke zin is fout?",
         opties=["Il pleut.", "Il neige.", "Il fait du vent.", "Il est froid."],
         antwoord=3,
         uitleg="Het weer gaat met il fait of met een eigen werkwoord: il fait froid, niet il est froid. Il est froid zou over een persoon of een ding gaan."),
    dict(type="invultekst",
         vraag="Vul in: demain, il va … , morgen gaat het regenen. Eén werkwoord in de infinitief.",
         antwoord=["pleuvoir"],
         uitleg="Pleuvoir, il pleut, il a plu. Na aller komt de infinitief: il va pleuvoir."),
    dict(type="waarofniet",
         vraag="'Le temps' betekent in het Frans zowel het weer als de tijd.",
         antwoord=True,
         uitleg="Quel temps fait-il ? gaat over het weer, je n'ai pas le temps over de tijd. De context maakt het altijd duidelijk."),
    dict(type="meerkeuze",
         vraag="Wat is 'une prévision' in een weerbericht?",
         opties=["een voorspelling", "een waarschuwing",
                 "een meting", "een herhaling"],
         antwoord=0,
         uitleg="Les prévisions météo zijn de weersverwachtingen. Prévoir is voorzien of voorspellen."),
    dict(type="meerkeuze",
         vraag="Drie van deze woorden horen bij multimedia en communicatie. Welk woord hoort er niet bij?",
         opties=["un écran", "un mot de passe", "une pièce jointe", "une étagère"],
         antwoord=3,
         uitleg="Une étagère is een rek. Un écran is een scherm, un mot de passe een wachtwoord, une pièce jointe een bijlage bij een mail."),
]
