# -*- coding: utf-8 -*-
"""Soorten zinnen, bijzinnen en si-zinnen.

De rubriek Zinsbouw van de vakfiche: de zes soorten zinnen (mededelend,
vragend, bevelend, uitroepend, ontkennend en bevestigend), de enkelvoudige en
de samengestelde zin, de nevenschikkende en onderschikkende bijzinnen, de
betrekkelijke bijzinnen met qui, que, dont en où, en de voorwaardelijke zinnen
met si plus indicatif présent en si plus indicatif imparfait. Daarbij komen de
frequente voegwoorden (donc, comme, pour que) en de voorzetsels bij
geografische namen en vervoermiddelen.

De si-zin is het stuk dat op een examen het vaakst terugkomt en waar het
Nederlands je in de steek laat: wij zeggen als ik tijd had, zou ik komen, maar
het Frans heeft voor elk van de twee delen een vaste tijd.

Deel 1: de soorten zinnen, de vraag en de ontkenning.
Deel 2: de bijzinnen, de si-zinnen en de voegwoorden.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Welke soorten zinnen somt de vakfiche op?",
         opties=["mededelend, vragend, bevelend", "uitroepend, ontkennend, bevestigend",
                 "enkelvoudig en samengesteld", "lang, kort en middellang"],
         antwoord=[0, 1, 2],
         uitleg="De lijst noemt de zes soorten én het onderscheid tussen enkelvoudige en samengestelde zinnen. De lengte van een zin is geen soort."),
    dict(type="meerkeuze",
         vraag="Hoeveel manieren heeft het Frans om een vraag te stellen?",
         opties=["drie: met de toon, met est-ce que, en met omkering",
                 "één: alleen met est-ce que",
                 "twee: met de toon en met een vraagwoord",
                 "vier, maar alleen in de spreektaal"],
         antwoord=0,
         uitleg="Tu viens ? Est-ce que tu viens ? Viens-tu ? De eerste is spreektaal, de derde de meest verzorgde."),
    dict(type="meerkeuze",
         vraag="Welke vraagzinnen zijn juist gebouwd?",
         opties=["Est-ce que tu viens ?", "Viens-tu ?",
                 "Tu viens ?", "Est-ce que viens-tu ?"],
         antwoord=[0, 1, 2],
         uitleg="De laatste stapelt est-ce que en de omkering op elkaar. Je kiest er één van de twee."),
    dict(type="invultekst",
         vraag="Maak een vraag met omkering van 'vous partez'. Twee woorden met een streepje.",
         antwoord=["Partez-vous", "partez-vous"],
         uitleg="Werkwoord eerst, dan het voornaamwoord, met een streepje ertussen. Dat heet l'inversion."),
    dict(type="waarofniet",
         vraag="Bij de omkering komt er in het Frans nooit een extra letter tussen het werkwoord en het voornaamwoord.",
         antwoord=False,
         uitleg="Eindigt het werkwoord op een klinker, dan komt er een t tussen om twee klinkers te scheiden: a-t-il raison, parle-t-elle, va-t-on."),
    dict(type="meerkeuze",
         vraag="Welke vraagwoorden vragen naar een reden of een manier?",
         opties=["pourquoi", "comment", "de quelle façon", "combien"],
         antwoord=[0, 1, 2],
         uitleg="Combien vraagt naar een hoeveelheid. Pourquoi is waarom, comment is hoe."),
    dict(type="meerkeuze",
         vraag="Hoe maak je van 'il parle' een ontkennende zin?",
         opties=["Il ne parle pas.", "Il parle ne pas.",
                 "Il ne pas parle.", "Il pas parle ne."],
         antwoord=0,
         uitleg="Ne en pas sluiten het vervoegde werkwoord in. In de spreektaal valt de ne vaak weg: il parle pas."),
    dict(type="meerkeuze",
         vraag="Drie van deze combinaties zijn echte Franse ontkenningen. Welke is dat niet?",
         opties=["ne … jamais", "ne … plus", "ne … rien", "ne … toujours"],
         antwoord=3,
         uitleg="Toujours is net het tegenovergestelde van een ontkenning. Ne … jamais is nooit, ne … plus is niet meer, ne … rien is niets."),
    dict(type="invultekst",
         vraag="Vul aan: je ne mange … de viande, ik eet geen vlees meer. Eén woord.",
         antwoord=["plus"],
         uitleg="Ne … plus betekent niet meer. Let ook op de de: na een ontkenning verdwijnt het lidwoord."),
    dict(type="waarofniet",
         vraag="Om te zeggen dat je niemand ziet, schrijf je in het Frans 'je ne vois pas personne'.",
         antwoord=False,
         uitleg="Personne vervangt pas: je ne vois personne. Allebei zetten is een dubbele ontkenning. Hetzelfde met rien: je ne comprends rien."),
    dict(type="meerkeuze",
         vraag="Waar staan ne en pas in een samengestelde tijd?",
         opties=["rond het hulpwerkwoord", "rond het voltooid deelwoord",
                 "rond de hele werkwoordsgroep", "allebei achter het deelwoord"],
         antwoord=0,
         uitleg="Je n'ai pas mangé. Het deelwoord staat erbuiten. Bij rien is dat ook zo: je n'ai rien vu."),
    dict(type="meerkeuze",
         vraag="Drie van deze zinnen zijn uitroepende zinnen. Welke is een vraag?",
         opties=["Quelle belle journée !", "Comme c'est beau !",
                 "Que c'est gentil !", "Est-ce que c'est beau ?"],
         antwoord=3,
         uitleg="De laatste is een vraag. Quel, comme en que leiden alle drie een uitroep in."),
    dict(type="invultekst",
         vraag="Vul aan: … belle maison ! Eén uitroepwoord dat bij een naamwoord hoort.",
         antwoord=["Quelle", "quelle"],
         uitleg="Maison is vrouwelijk, dus quelle. Let op: in een uitroep komt er geen lidwoord bij: quelle belle maison, niet quelle une belle maison."),
    dict(type="waarofniet",
         vraag="In het Frans staat er een spatie voor een uitroepteken en een vraagteken.",
         antwoord=True,
         uitleg="Quelle idée ! Comment vas-tu ? Dat geldt ook voor de dubbele punt en de puntkomma. Het is een echte spellingregel, geen slordigheid."),
    dict(type="meerkeuze",
         vraag="Wat is het verschil tussen een enkelvoudige en een samengestelde zin?",
         opties=["een samengestelde zin heeft meer dan één persoonsvorm",
                 "een samengestelde zin is langer dan tien woorden",
                 "een samengestelde zin heeft altijd een vraagteken",
                 "een samengestelde zin heeft geen onderwerp"],
         antwoord=0,
         uitleg="Elke persoonsvorm maakt een eigen zinsdeel. Il mange is enkelvoudig, il mange quand il a faim is samengesteld."),
    dict(type="meerkeuze",
         vraag="Drie van deze zinsdelen staan met name in de vakfiche. Welk zinsdeel niet?",
         opties=["onderwerp (sujet)", "persoonsvorm (verbe conjugué)",
                 "lijdend voorwerp (COD)", "bijwoordelijke bepaling van plaats"],
         antwoord=3,
         uitleg="De fiche noemt er vier: sujet, verbe conjugué, COD en COI. Bepalingen van plaats staan niet in die lijst."),
    dict(type="waarofniet",
         vraag="Het werkwoord komt in het Frans overeen met het onderwerp van de zin.",
         antwoord=True,
         uitleg="L'accord du verbe avec le sujet. Les élèves parlent, l'élève parle. Dat is de eerste regel in de rubriek congruentie."),
    dict(type="meerkeuze",
         vraag="Welke zin heeft een juiste overeenkomst tussen onderwerp en werkwoord?",
         opties=["Les enfants jouent dans le jardin.", "Les enfants joue dans le jardin.",
                 "L'enfant jouent dans le jardin.", "Les enfant jouent dans le jardin."],
         antwoord=0,
         uitleg="Meervoudig onderwerp, meervoudig werkwoord, meervoudig naamwoord. Alles moet meebewegen."),
    dict(type="meerkeuze",
         vraag="Welke woordvolgorde is in het Frans de gewone?",
         opties=["onderwerp, werkwoord, voorwerp", "werkwoord, onderwerp, voorwerp",
                 "voorwerp, onderwerp, werkwoord", "onderwerp, voorwerp, werkwoord"],
         antwoord=0,
         uitleg="Marie mange une pomme. Het Frans houdt die volgorde veel strakker aan dan het Nederlands, dat het werkwoord achteraan kan zetten."),
    dict(type="meerkeuze",
         vraag="Waarom staat 'je le vois' met het voorwerp vóór het werkwoord?",
         opties=["omdat een voornaamwoord als voorwerp altijd vooraan komt",
                 "omdat de zin een vraag is",
                 "omdat het werkwoord onregelmatig is",
                 "omdat de zin in de verleden tijd staat"],
         antwoord=0,
         uitleg="Een volledig voorwerp blijft achteraan: je vois Pierre. Zodra het een voornaamwoord wordt, springt het naar voren."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is het verschil tussen een nevenschikkende en een onderschikkende bijzin?",
         opties=["een nevengeschikte zin kan alleen staan, een ondergeschikte niet",
                 "een nevengeschikte zin is korter dan een ondergeschikte",
                 "een nevengeschikte zin staat altijd vooraan",
                 "een nevengeschikte zin heeft geen werkwoord"],
         antwoord=0,
         uitleg="Il pleut et je reste: twee zinnen die elk op zichzelf kunnen bestaan. Je reste parce qu'il pleut: het tweede deel hangt aan het eerste vast."),
    dict(type="meerkeuze",
         vraag="Welke voegwoorden zijn nevenschikkend?",
         opties=["mais", "et", "donc", "parce que"],
         antwoord=[0, 1, 2],
         uitleg="Parce que maakt een ondergeschikte zin. Mais, ou, et, donc, or, ni en car zijn de zeven nevenschikkende voegwoorden van het Frans."),
    dict(type="invultekst",
         vraag="Vul het voegwoord in dat 'omdat' betekent: je reste … il pleut. Twee woorden.",
         antwoord=["parce que", "parce qu'"],
         uitleg="Parce que staat altijd in het midden van de zin. Wil je de reden vooropzetten, dan gebruik je comme: comme il pleut, je reste."),
    dict(type="waarofniet",
         vraag="'Comme' aan het begin van een zin kan in het Frans een reden aangeven.",
         antwoord=True,
         uitleg="Comme il pleuvait, nous sommes restés. De fiche noemt comme zelf als voorbeeld van een frequent voegwoord."),
    dict(type="meerkeuze",
         vraag="Welke voegwoorden geven een tijd aan?",
         opties=["quand", "dès que", "pendant que", "pour que"],
         antwoord=[0, 1, 2],
         uitleg="Pour que geeft een doel en vraagt bovendien de subjonctif. Quand is wanneer, dès que is zodra, pendant que is terwijl."),
    dict(type="invultekst",
         vraag="Vul aan: je travaille … gagner ma vie, om mijn brood te verdienen. Eén woord.",
         antwoord=["pour"],
         uitleg="Pour plus infinitief als het onderwerp hetzelfde blijft. Verandert het onderwerp, dan wordt het pour que plus subjonctif."),
    dict(type="meerkeuze",
         vraag="Wat is het verschil tussen 'pour' en 'pour que'?",
         opties=["pour gaat met een infinitief, pour que met een subjonctif",
                 "pour gaat met een subjonctif, pour que met een infinitief",
                 "pour is verleden tijd, pour que toekomst",
                 "er is helemaal geen verschil"],
         antwoord=0,
         uitleg="Je travaille pour réussir, maar je travaille pour que mes enfants réussissent. Twee onderwerpen vragen pour que."),
    dict(type="meerkeuze",
         vraag="Welke betrekkelijke bijzinnen zijn juist gebouwd?",
         opties=["la fille qui chante", "le film que j'ai vu",
                 "la ville où je suis né", "le livre qui je lis"],
         antwoord=[0, 1, 2],
         uitleg="De laatste moet le livre que je lis zijn: er komt een onderwerp achter, dus que en niet qui."),
    dict(type="invultekst",
         vraag="Vul het betrekkelijk voornaamwoord in: voilà la maison … j'ai grandi. Eén woord.",
         antwoord=["où"],
         uitleg="Grandir dans une maison, dus een plaats, dus où. Dont zou alleen kunnen als het werkwoord de vroeg."),
    dict(type="meerkeuze",
         vraag="Hoe ziet een si-zin eruit die over een echte mogelijkheid gaat?",
         opties=["si plus présent, dan futur in het andere deel",
                 "si plus imparfait, dan conditionnel in het andere deel",
                 "si plus futur, dan présent in het andere deel",
                 "si plus conditionnel, dan imparfait in het andere deel"],
         antwoord=0,
         uitleg="S'il fait beau, j'irai à la mer. Als het echt kan gebeuren, gebruik je présent plus futur."),
    dict(type="meerkeuze",
         vraag="Hoe ziet een si-zin eruit die over iets onwerkelijks gaat?",
         opties=["si plus imparfait, dan conditionnel in het andere deel",
                 "si plus présent, dan futur in het andere deel",
                 "si plus conditionnel, dan conditionnel in het andere deel",
                 "si plus futur, dan conditionnel in het andere deel"],
         antwoord=0,
         uitleg="Si j'avais le temps, je viendrais. Ik heb de tijd niet, dus het blijft bij een gedachte."),
    dict(type="invultekst",
         vraag="Vul aan: si j'avais de l'argent, je … une voiture, van acheter. Eén werkwoordsvorm.",
         antwoord=["achèterais", "acheterais"],
         uitleg="Na si plus imparfait komt de conditionnel in het andere deel. Nooit een conditionnel ná si zelf."),
    dict(type="waarofniet",
         vraag="Na 'si' mag in het Frans nooit een futur of een conditionnel staan.",
         antwoord=True,
         uitleg="Si je serais of si j'aurai is altijd fout. Na si staat een présent of een imparfait; de andere tijd komt in het tweede deel."),
    dict(type="meerkeuze",
         vraag="Drie van deze si-zinnen zijn correct. Welke zin is fout?",
         opties=["Si tu veux, nous partirons.", "Si tu voulais, nous partirions.",
                 "S'il pleut, je reste à la maison.", "Si tu voudrais, nous partirions."],
         antwoord=3,
         uitleg="De laatste zet een conditionnel na si, en dat kan niet. Si tu voulais is de juiste vorm."),
    dict(type="meerkeuze",
         vraag="Drie van deze uitdrukkingen horen bij vervoer waar je in zit. Welke hoort er niet bij?",
         opties=["en voiture", "en train", "en avion", "à pied"],
         antwoord=3,
         uitleg="À pied, à vélo en à cheval gaan met à, want je zit erop of je gaat op eigen kracht. De rest gaat met en."),
    dict(type="invultekst",
         vraag="Vul aan: ils voyagent … Portugal cette année. Eén woord bij een mannelijk land.",
         antwoord=["au"],
         uitleg="Bij mannelijke landen wordt à + le samen au: au Portugal, au Maroc, au Canada. Bij vrouwelijke blijft het en."),
    dict(type="waarofniet",
         vraag="Bij steden gebruikt het Frans 'en': j'habite en Bruxelles.",
         antwoord=False,
         uitleg="Bij steden is het altijd à: à Bruxelles, à Paris, à Liège, à Montréal. Alleen bij landen en streken hangt het van het geslacht af."),
    dict(type="meerkeuze",
         vraag="Welke voorzetselgroepen noemt de vakfiche zelf als voorbeeld?",
         opties=["grâce à", "à cause de", "en face de", "pour que"],
         antwoord=[0, 1],
         uitleg="De fiche noemt grâce à en à cause de met name. En face de bestaat wel maar staat niet in de lijst, en pour que is een voegwoord."),
    dict(type="waarofniet",
         vraag="'Il pleut, donc je prends mon parapluie' is een onderschikking, want donc hangt het tweede deel aan het eerste vast.",
         antwoord=False,
         uitleg="Het is een nevenschikking: allebei de delen kunnen op zichzelf staan. Donc is een nevenschikkend voegwoord, net als mais en et."),
    dict(type="meerkeuze",
         vraag="Waarom helpt het bij het lezen om de persoonsvormen in een lange zin te tellen?",
         opties=["zo zie je hoeveel delen de zin heeft en waar ze beginnen",
                 "zo weet je in welke tijd de zin staat",
                 "zo vind je het onderwerp van de tekst",
                 "zo kan je de klemtoon bepalen"],
         antwoord=0,
         uitleg="Elke persoonsvorm hoort bij een eigen onderwerp. Een zin van vier regels met drie persoonsvormen valt zo in drie leesbare stukken uiteen."),
]
