# -*- coding: utf-8 -*-
"""De kunstvormen.

Van de vakfiche kunstbeschouwing en filosofie (2DO, 2027): architectuur en
design, audiovisuele kunsten (film, fotografie, videokunst), beeldende kunsten
(schilderkunst, beeldhouwkunst), literatuur en podiumkunsten (dans, theater,
muziek).

Deel 1 zijn de vijf vormen en hun onderverdeling.
Deel 2 is het thuisbrengen van voorbeelden.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Hoeveel kunstvormen onderscheidt de vakfiche?",
         opties=["vijf",
                 "drie in totaal",
                 "zeven in totaal",
                 "negen in totaal"],
         antwoord=0,
         uitleg="Vijf: architectuur en design, audiovisuele kunsten, beeldende kunsten, literatuur en podiumkunsten."),
    dict(type="meerkeuze",
         vraag="Welke horen bij de beeldende kunsten?",
         opties=["schilderkunst",
                 "beeldhouwkunst",
                 "tekenkunst",
                 "danskunst"],
         antwoord=[0, 1, 2],
         uitleg="De beeldende kunsten maken een blijvend beeld. Dans hoort bij de podiumkunsten."),
    dict(type="invultekst",
         vraag="Bij welke kunstvorm hoort film? Eén woord.",
         antwoord=["audiovisuele", "audiovisueel", "audiovisuele kunsten"],
         uitleg="De audiovisuele kunsten: film, fotografie en videokunst."),
    dict(type="meerkeuze",
         vraag="Welke horen bij de podiumkunsten?",
         opties=["dans",
                 "theater",
                 "muziek",
                 "fotografie"],
         antwoord=[0, 1, 2],
         uitleg="Drie kunsten die zich voor een publiek voltrekken. Fotografie is audiovisueel."),
    dict(type="waarofniet",
         vraag="Architectuur staat volgens de fiche samen met design als één kunstvorm.",
         antwoord=True,
         uitleg="Zo staat het er: architectuur en design. Beide geven vorm aan iets wat ook gebruikt wordt."),
    dict(type="meerkeuze",
         vraag="Welke kunstvorm werkt met taal?",
         opties=["de literatuur",
                 "de beeldende kunst",
                 "de podiumkunst",
                 "de audiovisuele kunst"],
         antwoord=0,
         uitleg="Literatuur: romans, verhalen, gedichten, toneelteksten. Haar materiaal is het woord."),
    dict(type="meerkeuze",
         vraag="Welke drie horen bij de audiovisuele kunsten?",
         opties=["film",
                 "fotografie",
                 "videokunst",
                 "beeldhouwkunst"],
         antwoord=[0, 1, 2],
         uitleg="De fiche noemt die drie. Beeldhouwkunst hoort bij de beeldende kunsten."),
    dict(type="waarofniet",
         vraag="Fotografie hoort volgens de fiche bij de beeldende kunsten.",
         antwoord=False,
         uitleg="Ze staat bij de audiovisuele kunsten, naast film en videokunst."),
    dict(type="meerkeuze",
         vraag="Wat hebben de podiumkunsten gemeen?",
         opties=["ze gebeuren in de tijd",
                 "ze laten een voorwerp na",
                 "ze hangen in een museum",
                 "ze bestaan uit woorden"],
         antwoord=0,
         uitleg="Een voorstelling duurt en is daarna voorbij. Een schilderij blijft hangen."),
    dict(type="meerkeuze",
         vraag="Waarom staat design bij de kunstvormen?",
         opties=["het geeft vorm aan voorwerpen",
                 "het kost altijd veel geld",
                 "het hangt in een museum",
                 "het is altijd heel oud"],
         antwoord=0,
         uitleg="Een stoel of een affiche kan vormgegeven zijn met dezelfde zorg als een schilderij."),
    dict(type="invultekst",
         vraag="Bij welke kunstvorm hoort een roman? Eén woord.",
         antwoord=["literatuur", "de literatuur"],
         uitleg="De literatuur. Haar bouwsteen is de taal."),
    dict(type="waarofniet",
         vraag="Eén werk kan tot meerdere kunstvormen horen.",
         antwoord=True,
         uitleg="Een opera is muziek, theater én vormgeving. Een film heeft ook literatuur nodig voor het scenario."),
    dict(type="meerkeuze",
         vraag="Welke kunstvormen laten een tastbaar werk na?",
         opties=["de beeldende kunsten",
                 "de architectuur",
                 "het design",
                 "de podiumkunsten"],
         antwoord=[0, 1, 2],
         uitleg="Drie vormen maken iets wat blijft staan. Een voorstelling is na het applaus voorbij."),
    dict(type="meerkeuze",
         vraag="Waarom is de indeling in kunstvormen nuttig?",
         opties=["ze ordent wat je ziet",
                 "ze bepaalt de kwaliteit",
                 "ze bepaalt de prijs",
                 "ze bepaalt de periode"],
         antwoord=0,
         uitleg="Wie weet met welke vorm hij te doen heeft, weet ook welke richtvragen hij kan stellen."),
    dict(type="waarofniet",
         vraag="Videokunst en film zijn volgens de fiche dezelfde kunstvorm.",
         antwoord=False,
         uitleg="Ze staan als aparte onderdelen binnen dezelfde kunstvorm. Videokunst is meestal voor een zaal, niet voor een bioscoop."),
    dict(type="meerkeuze",
         vraag="Welke kunstvorm bouwt mee aan de ruimte waarin mensen leven?",
         opties=["de architectuur",
                 "de literatuur",
                 "de podiumkunst",
                 "de audiovisuele kunst"],
         antwoord=0,
         uitleg="Een gebouw is kunst die je binnengaat. Daarom krijgt architectuur eigen richtvragen in de fiche."),
    dict(type="meerkeuze",
         vraag="Welke kunstvorm heeft een uitvoerder nodig naast de maker?",
         opties=["de podiumkunst",
                 "de beeldende kunst",
                 "het design",
                 "de architectuur"],
         antwoord=0,
         uitleg="Een partituur of een toneeltekst wordt pas kunst als iemand ze uitvoert."),
    dict(type="invultekst",
         vraag="Bij welke kunstvorm hoort beeldhouwkunst? Twee woorden.",
         antwoord=["beeldende kunsten", "de beeldende kunsten", "beeldende kunst"],
         uitleg="De beeldende kunsten, samen met de schilderkunst."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over de kunstvormen kloppen?",
         opties=["ze overlappen soms",
                 "elke vorm heeft eigen middelen",
                 "de fiche noemt er vijf",
                 "ze staan in een rangorde"],
         antwoord=[0, 1, 2],
         uitleg="Er is geen rangorde: geen enkele vorm staat boven een andere."),
    dict(type="meerkeuze",
         vraag="Waarom krijgen beeldende kunst en architectuur eigen richtvragen?",
         opties=["ze hebben eigen middelen",
                 "ze zijn het oudste",
                 "ze zijn het duurste",
                 "ze zijn het bekendste"],
         antwoord=0,
         uitleg="Bijlage 1 en 2 van de fiche geven voor elk een eigen lijst bouwstenen, materialen en technieken."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Een bronzen ruiterbeeld op een plein. Welke kunstvorm?",
         opties=["de beeldende kunst",
                 "de architectuur",
                 "de podiumkunst",
                 "de audiovisuele kunst"],
         antwoord=0,
         uitleg="Beeldhouwkunst, en dus beeldende kunst. Het plein zelf is wel architectuur."),
    dict(type="meerkeuze",
         vraag="Een ballet in de opera. Welke kunstvorm?",
         opties=["de podiumkunst",
                 "de beeldende kunst",
                 "de literatuur",
                 "het design"],
         antwoord=0,
         uitleg="Dans is een podiumkunst. Het decor erbij is vormgeving."),
    dict(type="invultekst",
         vraag="Bij welke kunstvorm hoort een gedicht? Eén woord.",
         antwoord=["literatuur", "de literatuur"],
         uitleg="De literatuur. Ook een lied heeft een tekst, maar dan komt muziek erbij."),
    dict(type="meerkeuze",
         vraag="Welke voorbeelden zijn audiovisuele kunst?",
         opties=["een kortfilm",
                 "een fotoreeks",
                 "een videoinstallatie",
                 "een gedichtenbundel"],
         antwoord=[0, 1, 2],
         uitleg="Drie werken met beeld en vaak geluid. Een bundel is literatuur."),
    dict(type="waarofniet",
         vraag="Een stadhuis uit de zestiende eeuw is architectuur.",
         antwoord=True,
         uitleg="Het is een gebouw met vormgeving en een functie. Dat maakt het architectuur."),
    dict(type="meerkeuze",
         vraag="Een affiche voor een festival. Welke kunstvorm ligt het dichtst?",
         opties=["het design",
                 "de literatuur",
                 "de podiumkunst",
                 "de beeldhouwkunst"],
         antwoord=0,
         uitleg="Grafische vormgeving hoort bij architectuur en design: iets wat vormgegeven is én gebruikt wordt."),
    dict(type="meerkeuze",
         vraag="Welke voorbeelden zijn podiumkunst?",
         opties=["een concert",
                 "een toneelstuk",
                 "een dansvoorstelling",
                 "een schilderij"],
         antwoord=[0, 1, 2],
         uitleg="Drie kunsten die voor een publiek plaatsvinden. Een schilderij hangt stil aan een muur."),
    dict(type="waarofniet",
         vraag="Een striptekening is volgens de fiche een podiumkunst.",
         antwoord=False,
         uitleg="Ze hoort bij de beeldende kunsten, en met de tekst erbij raakt ze aan de literatuur."),
    dict(type="meerkeuze",
         vraag="Een fresco op een kerkmuur. Welke kunstvorm?",
         opties=["de schilderkunst",
                 "de architectuur",
                 "de beeldhouwkunst",
                 "de audiovisuele kunst"],
         antwoord=0,
         uitleg="Het is geschilderd, dus beeldende kunst. De kerk eromheen is architectuur."),
    dict(type="meerkeuze",
         vraag="Waarom noemt men een film een samengestelde kunstvorm?",
         opties=["meerdere kunsten komen samen",
                 "er werken veel mensen aan",
                 "ze duurt lang",
                 "ze kost veel geld"],
         antwoord=0,
         uitleg="Beeld, muziek, tekst en vormgeving zitten in één werk. Dat maakt de analyse rijker."),
    dict(type="invultekst",
         vraag="Bij welke kunstvorm hoort een woonhuis van een architect? Eén woord.",
         antwoord=["architectuur", "de architectuur"],
         uitleg="De architectuur. Bijlage 2 van de fiche geeft er de eigen middelen van vormgeving bij."),
    dict(type="waarofniet",
         vraag="Een kunstvorm bepalen is volgens de fiche een stap in de analyse.",
         antwoord=True,
         uitleg="Het is de eerste ordening. Daarna volgen de periode, de stroming, de inhoud en de context."),
    dict(type="meerkeuze",
         vraag="Een geluidswerk zonder beeld in een museumzaal. Waar hoort het best?",
         opties=["bij de muziek",
                 "bij de schilderkunst",
                 "bij de literatuur",
                 "bij de architectuur"],
         antwoord=0,
         uitleg="Muziek is een podiumkunst, ook als er niemand op een podium staat. De fiche laat zulke grensgevallen toe."),
    dict(type="meerkeuze",
         vraag="Welke voorbeelden zijn beeldende kunst?",
         opties=["een olieverfdoek",
                 "een marmeren buste",
                 "een houtsnede",
                 "een filmscenario"],
         antwoord=[0, 1, 2],
         uitleg="Drie werken die je als beeld ziet. Een scenario is een tekst en dus literatuur."),
    dict(type="waarofniet",
         vraag="Een stoel van een ontwerper valt volgens de fiche buiten de kunstvormen.",
         antwoord=False,
         uitleg="Design staat juist wel bij de kunstvormen. Of die stoel ook kunst is, beredeneer je met de criteria."),
    dict(type="meerkeuze",
         vraag="Waarom is het soms moeilijk één kunstvorm aan te wijzen?",
         opties=["de vormen lopen door elkaar",
                 "de fiche is onduidelijk",
                 "de kunstenaar verzwijgt het",
                 "het museum beslist het"],
         antwoord=0,
         uitleg="Een installatie met beeld, geluid en voorwerpen raakt aan drie vormen tegelijk. Benoem er dan meerdere."),
    dict(type="meerkeuze",
         vraag="Een luisterspel op de radio. Welke kunsten komen samen?",
         opties=["literatuur en muziek",
                 "architectuur en design",
                 "schilderkunst en dans",
                 "fotografie en beeldhouwkunst"],
         antwoord=0,
         uitleg="Een tekst wordt gespeeld met geluid en muziek. Beeld komt er niet aan te pas."),
    dict(type="meerkeuze",
         vraag="Welke stap volgt in de analyse na de kunstvorm?",
         opties=["de periode en de stroming",
                 "de prijs van het werk",
                 "de naam van de eigenaar",
                 "de plaats in het museum"],
         antwoord=0,
         uitleg="De fiche vraagt daarna om met bronmateriaal de periode en de stroming te bepalen."),
    dict(type="invultekst",
         vraag="Bij welke kunstvorm hoort videokunst? Eén woord.",
         antwoord=["audiovisuele", "audiovisueel", "audiovisuele kunsten"],
         uitleg="De audiovisuele kunsten, naast film en fotografie."),
    dict(type="meerkeuze",
         vraag="Een kunstenaar laat dansers bewegen tussen zijn beelden. Hoe benoem je dat werk?",
         opties=["beeldende kunst en podiumkunst",
                 "enkel als beeldende kunst",
                 "enkel als podiumkunst",
                 "enkel als architectuur"],
         antwoord=0,
         uitleg="Twee vormen tegelijk. De fiche laat toe meerdere vormen te benoemen bij één werk."),
]
