# -*- coding: utf-8 -*-
"""De richtvragen en de middelen van vormgeving.

Van de vakfiche kunstbeschouwing en filosofie (2DO, 2027): het analyseren van
beeldende kunst en architectuur met de richtvragen (hoe en waarmee, wat,
waarvoor, wie waar en wanneer) en de middelen van vormgeving uit bijlage 1
(beeldende kunst) en bijlage 2 (architectuur).

Deel 1 zijn de middelen bij beeldende kunst.
Deel 2 zijn de middelen bij architectuur en de richtvragen.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Welke drie groepen middelen noemt bijlage 1?",
         opties=["bouwstenen, materiaal, technieken",
                 "inhoud, functie en de context",
                 "tijd, ruimte en de kunstenaar",
                 "vorm, kleur en het lichtcontrast"],
         antwoord=0,
         uitleg="Bouwstenen, materiaal en technieken. Vorm, kleur en licht zijn bouwstenen binnen de eerste groep."),
    dict(type="meerkeuze",
         vraag="Welke horen bij de bouwstenen van beeldende kunst?",
         opties=["vorm",
                 "compositie",
                 "kleur",
                 "olieverf"],
         antwoord=[0, 1, 2],
         uitleg="Vorm, compositie, symmetrie, kleur, licht en ruimte zijn bouwstenen. Olieverf is materiaal."),
    dict(type="waarofniet",
         vraag="Een compositiegrondvorm kan horizontaal, verticaal, diagonaal of een driehoek zijn.",
         antwoord=True,
         uitleg="Zo staat het in bijlage 1. De grondvorm is de lijn waarlangs de figuren geschikt staan."),
    dict(type="meerkeuze",
         vraag="Welke soorten symmetrie noemt bijlage 1?",
         opties=["symmetrisch en asymmetrisch",
                 "warm en koud van kleur",
                 "hol en bol van vorm",
                 "licht en donker van toon"],
         antwoord=0,
         uitleg="Symmetrisch, asymmetrisch, verspreid, overall en centraal. Warm en koud is kleurcontrast."),
    dict(type="invultekst",
         vraag="Welke kleuren noemt men primair? Noem er één.",
         antwoord=["rood", "geel", "blauw"],
         uitleg="Rood, geel en blauw. Door mengen krijg je de secundaire en dan de tertiaire kleuren."),
    dict(type="meerkeuze",
         vraag="Welke kleurcontrasten noemt bijlage 1?",
         opties=["licht-donker",
                 "warm-koud",
                 "complementair",
                 "primair-secundair"],
         antwoord=[0, 1, 2],
         uitleg="Drie contrasten van de bijlage. Primair en secundair zijn soorten kleuren, geen contrast."),
    dict(type="waarofniet",
         vraag="Bijlage 1 onderscheidt eigen schaduw van slagschaduw.",
         antwoord=True,
         uitleg="Eigen schaduw zit op het voorwerp zelf, slagschaduw valt ernaast op de grond of de muur."),
    dict(type="meerkeuze",
         vraag="Welk perspectief kijkt van heel laag naar boven?",
         opties=["het kikvorsperspectief",
                 "het vogelperspectief",
                 "het lijnperspectief",
                 "het kleurperspectief"],
         antwoord=0,
         uitleg="Als een kikker in het gras: de figuren torenen boven je uit. Van bovenaf is het vogelperspectief."),
    dict(type="meerkeuze",
         vraag="Welke drie dimensies noemt bijlage 1 bij ruimte?",
         opties=["hoogte, breedte, diepte",
                 "vorm, kleur, licht",
                 "steen, klei, brons",
                 "warm, koud, neutraal"],
         antwoord=0,
         uitleg="Hoogte, breedte en diepte. Daarnaast staat het perspectief als apart middel."),
    dict(type="invultekst",
         vraag="Welk perspectief kijkt van bovenaf naar beneden? Eén woord.",
         antwoord=["vogelperspectief", "vogel", "het vogelperspectief"],
         uitleg="Het vogelperspectief. Van heel laag naar boven is het kikvorsperspectief."),
    dict(type="waarofniet",
         vraag="Materiaal en techniek zijn volgens bijlage 1 hetzelfde middel.",
         antwoord=False,
         uitleg="Materiaal is waarmee, techniek is hoe. Olieverf is materiaal, een collage maken is een techniek."),
    dict(type="meerkeuze",
         vraag="Welke materialen noemt bijlage 1 bij beeldhouwkunst?",
         opties=["steen",
                 "klei",
                 "brons",
                 "olieverf"],
         antwoord=[0, 1, 2],
         uitleg="Steen, klei, brons, hout, ivoor en moderne materialen. Olieverf hoort bij de schilderkunst."),
    dict(type="meerkeuze",
         vraag="Welke techniek hoort bij driedimensionaal werk?",
         opties=["boetseren",
                 "fresco maken",
                 "een affiche drukken",
                 "een still maken"],
         antwoord=0,
         uitleg="Hakken, boetseren, construeren en las- en kleeftechnieken. De drie andere zijn tweedimensionaal."),
    dict(type="waarofniet",
         vraag="Een fresco is volgens bijlage 1 een techniek van de beeldhouwkunst.",
         antwoord=False,
         uitleg="Het is schilderen op natte kalk aan de muur, dus een techniek van de schilderkunst."),
    dict(type="meerkeuze",
         vraag="Welke kleurgebruiken noemt bijlage 1?",
         opties=["expressief",
                 "symbolisch",
                 "impressief",
                 "complementair"],
         antwoord=[0, 1, 2],
         uitleg="Cerebraal, impressief, expressief en symbolisch. Complementair is een contrast."),
    dict(type="meerkeuze",
         vraag="Wat betekent symbolisch kleurgebruik?",
         opties=["de kleur staat voor iets",
                 "de kleur is zoals in de natuur",
                 "de kleur toont een gevoel",
                 "de kleur is koel gekozen"],
         antwoord=0,
         uitleg="Blauw voor Maria, rood voor het martelaarschap. De kleur draagt een betekenis."),
    dict(type="invultekst",
         vraag="Welk kleurgebruik toont vooral het gevoel van de maker? Eén woord.",
         antwoord=["expressief", "expressieve", "expressief kleurgebruik"],
         uitleg="Expressief kleurgebruik. De kleur volgt de emotie en niet de werkelijkheid."),
    dict(type="meerkeuze",
         vraag="Welke vormen noemt bijlage 1 als bouwsteen?",
         opties=["hoekig",
                 "rond",
                 "hol en bol",
                 "warm"],
         antwoord=[0, 1, 2],
         uitleg="Hoekig, rond, vierkant, kegel, hol, bol, tweedimensionaal en driedimensionaal. Warm hoort bij kleur."),
    dict(type="meerkeuze",
         vraag="Een werk met een driehoekige schikking van drie figuren. Welk middel?",
         opties=["de compositie",
                 "de kleur",
                 "het licht",
                 "het materiaal"],
         antwoord=0,
         uitleg="De compositiegrondvorm is een driehoek. Een veelgebruikte schikking in de renaissance."),
    dict(type="meerkeuze",
         vraag="Waarom staan de middelen van vormgeving in een bijlage?",
         opties=["je mag ze op het examen gebruiken",
                 "ze horen niet bij de leerstof",
                 "ze zijn enkel voor de leraar",
                 "ze gelden enkel voor muziek"],
         antwoord=0,
         uitleg="De fiche verwijst er bij de richtvraag hoe en waarmee naar. Het is de woordenlijst voor je analyse."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Welke compositiegrondvormen noemt bijlage 2 bij architectuur?",
         opties=["centraalbouw en langsbouw",
                 "horizontaal en verticaal",
                 "hol en bol",
                 "warm en koud"],
         antwoord=0,
         uitleg="Centraalbouw is rond om een midden, langsbouw is langwerpig. Horizontaal en verticaal gelden bij beeldende kunst."),
    dict(type="meerkeuze",
         vraag="Welke soorten symmetrie noemt bijlage 2 bij architectuur?",
         opties=["symmetrisch",
                 "asymmetrisch",
                 "statisch en dynamisch",
                 "verspreid en overall"],
         antwoord=[0, 1, 2],
         uitleg="Verspreid en overall staan bij de beeldende kunst, niet bij architectuur."),
    dict(type="invultekst",
         vraag="Hoe noemt bijlage 2 een gebouw in één kleur? Eén woord.",
         antwoord=["monochroom", "monochrome"],
         uitleg="Monochroom. Met meerdere kleuren is het polychroom."),
    dict(type="meerkeuze",
         vraag="Wat betekent polychroom?",
         opties=["in meerdere kleuren",
                 "in één kleur",
                 "zonder kleur",
                 "met weinig licht"],
         antwoord=0,
         uitleg="Veel kleuren, zoals bij een gevel met gekleurde baksteen of een beschilderd interieur."),
    dict(type="waarofniet",
         vraag="Bijlage 2 noemt bij ruimte het onderscheid open, gesloten en omsloten.",
         antwoord=True,
         uitleg="Het gaat over de verhouding binnen en buiten: hoe open een gebouw naar zijn omgeving staat."),
    dict(type="meerkeuze",
         vraag="Welke constructietechnieken noemt bijlage 2?",
         opties=["dragende constructie",
                 "hangende constructie",
                 "skeletbouw",
                 "boetseren"],
         antwoord=[0, 1, 2],
         uitleg="Drie technieken van de architectuur. Boetseren hoort bij de beeldhouwkunst."),
    dict(type="meerkeuze",
         vraag="Welke materialen noemt bijlage 2 als niet-natuurlijk?",
         opties=["beton en staal",
                 "natuursteen en hout",
                 "klei en ivoor",
                 "steen en been"],
         antwoord=0,
         uitleg="Baksteen, beton, glas en staal zijn gemaakt door mensen. Natuursteen en hout komen uit de natuur."),
    dict(type="waarofniet",
         vraag="Natuursteen en hout zijn volgens bijlage 2 niet-natuurlijke materialen.",
         antwoord=False,
         uitleg="Juist wel natuurlijk. Baksteen, beton, glas en staal zijn de niet-natuurlijke."),
    dict(type="invultekst",
         vraag="Welke bouwtechniek draagt met een geraamte in plaats van met muren? Eén woord.",
         antwoord=["skeletbouw", "skelet", "de skeletbouw"],
         uitleg="Skeletbouw. Daardoor kan de wand helemaal uit glas bestaan."),
    dict(type="meerkeuze",
         vraag="Welke woorden noemt bijlage 2 bij structuur en textuur?",
         opties=["grof en gepolijst",
                 "warm en koud",
                 "hoog en breed",
                 "open en gesloten"],
         antwoord=0,
         uitleg="Opengewerkt, grof, ruw en gepolijst. Het gaat over hoe het oppervlak aanvoelt en oogt."),
    dict(type="waarofniet",
         vraag="Bijlage 2 laat het licht buiten de middelen van vormgeving.",
         antwoord=False,
         uitleg="Natuurlijk licht, lichtinval en reflectie staan er juist bij. Waar het licht binnenvalt, bepaalt hoe een ruimte voelt."),
    dict(type="meerkeuze",
         vraag="Welke vier richtvragen noemt de fiche?",
         opties=["hoe en waarmee",
                 "wat",
                 "waarvoor",
                 "hoeveel"],
         antwoord=[0, 1, 2],
         uitleg="Hoe en waarmee, wat, waarvoor, en wie waar en wanneer. Hoeveel staat er niet bij."),
    dict(type="meerkeuze",
         vraag="Welke richtvraag gaat over de middelen van vormgeving?",
         opties=["hoe en waarmee",
                 "wat",
                 "waarvoor",
                 "wie en wanneer"],
         antwoord=0,
         uitleg="Hoe en waarmee leidt naar de bouwstenen, het materiaal en de techniek uit de bijlagen."),
    dict(type="meerkeuze",
         vraag="Welke richtvraag gaat over de inhoud?",
         opties=["wat",
                 "hoe en waarmee",
                 "waarvoor",
                 "wie en wanneer"],
         antwoord=0,
         uitleg="De vraag wat brengt je bij het onderwerp van de kunstuiting."),
    dict(type="invultekst",
         vraag="Welke richtvraag leidt naar de functie van een werk? Eén woord.",
         antwoord=["waarvoor"],
         uitleg="Waarvoor. De vier richtvragen zijn hoe en waarmee, wat, waarvoor, en wie waar en wanneer."),
    dict(type="waarofniet",
         vraag="De richtvragen gelden volgens de fiche voor beeldende kunst en architectuur.",
         antwoord=True,
         uitleg="Zo staat het er: je analyseert een kunstuiting uit de beeldende kunst en architectuur aan de hand van richtvragen."),
    dict(type="meerkeuze",
         vraag="Een gevel in één kleur, streng symmetrisch, met zuilen. Welke middelen benoem je?",
         opties=["kleur, symmetrie, vorm",
                 "techniek, prijs, maker",
                 "tijd, ruimte, functie",
                 "onderwerp, titel, eigenaar"],
         antwoord=0,
         uitleg="Monochroom is kleur, streng symmetrisch is symmetrie, zuilen horen bij de vorm en de constructie."),
    dict(type="meerkeuze",
         vraag="Waarom beantwoord je de vier richtvragen in volgorde?",
         opties=["je gaat van zien naar begrijpen",
                 "zo gaat de analyse sneller",
                 "zo blijft de analyse korter",
                 "zo staat het in de regels"],
         antwoord=0,
         uitleg="Eerst wat je ziet, dan wat het betekent, dan waarvoor het diende en ten slotte waar het thuishoort."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over de bijlagen kloppen?",
         opties=["ze geven de woorden voor je analyse",
                 "er is een lijst per kunstvorm",
                 "je gebruikt ze bij hoe en waarmee",
                 "ze geven de periode van het werk"],
         antwoord=[0, 1, 2],
         uitleg="De bijlagen zeggen niets over periodes. Daarvoor kijk je naar de stromingen."),
    dict(type="meerkeuze",
         vraag="Een kerk met veel licht door hoge glasramen. Welk middel uit bijlage 2?",
         opties=["de lichtinval",
                 "de textuur",
                 "het materiaal",
                 "de symmetrie"],
         antwoord=0,
         uitleg="Natuurlijk licht, lichtinval en reflectie staan bij licht. Dat is bij een gotische kerk het sterkste middel."),
]
