# -*- coding: utf-8 -*-
"""De vragen voor "De woordsoorten op een rij" (🚀 Boost doorstroom, Nederlands).

Uit het morfologisch domein van allebei de vakfiches: zelfstandig naamwoord,
bijvoeglijk naamwoord, lidwoord (bepaald, onbepaald, ontkennend), voegwoord,
voorzetsel, telwoord, bijwoord, tussenwerpsel, en de voornaamwoorden,
zelfstandig en bijvoeglijk gebruikt.

Deel 1 zijn de woordsoorten buiten het voornaamwoord en het werkwoord. Deel 2
is helemaal voor de voornaamwoorden, want dat zijn er acht soorten en ze lijken
op elkaar.
"""

DEEL1 = [
    dict(
        type="meerkeuze",
        vraag="In 'De oude molen draaide traag', welke woordsoort is 'oude'?",
        opties=[
            "een bijvoeglijk naamwoord",
            "een zelfstandig naamwoord",
            "een bijwoord",
            "een telwoord",
        ],
        antwoord=0,
        uitleg="'Oude' zegt iets over het zelfstandig naamwoord 'molen'. Dat is precies wat een bijvoeglijk naamwoord doet.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke woorden zijn lidwoorden?",
        opties=["de", "een", "geen", "die"],
        antwoord=[0, 1, 2],
        uitleg="Het Nederlands heeft er drie soorten: bepaald (de, het), onbepaald (een) en ontkennend (geen). 'Die' is een aanwijzend voornaamwoord.",
    ),
    dict(
        type="invultekst",
        vraag="Welk soort lidwoord is 'geen'?",
        antwoord=["ontkennend", "een ontkennend lidwoord"],
        uitleg="'Geen boek' is de ontkenning van 'een boek'. Daarom krijgt het een eigen naam.",
    ),
    dict(
        type="waarofniet",
        vraag="'De' en 'het' zijn bepaalde lidwoorden.",
        antwoord=True,
        uitleg="Ze wijzen naar iets dat de lezer al kent. 'Een' laat het juist open.",
    ),
    dict(
        type="meerkeuze",
        vraag="In 'Oei, dat deed pijn!' is 'oei' een:",
        opties=["tussenwerpsel", "bijwoord", "voegwoord", "voorzetsel"],
        antwoord=0,
        uitleg="Een tussenwerpsel drukt een gevoel of een geluid uit en staat los van de zinsbouw.",
    ),
    dict(
        type="meerkeuze",
        vraag="In 'De sleutel lag onder de mat', welk woord is het voorzetsel?",
        opties=["onder", "de", "sleutel", "lag"],
        antwoord=0,
        uitleg="Een voorzetsel geeft een verhouding aan in plaats, tijd of richting: onder, na, door, tegen.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je een woord dat zinnen of zinsdelen verbindt, zoals 'en', 'maar' en 'omdat'?",
        antwoord=["voegwoord", "een voegwoord"],
        uitleg="Nevenschikkende voegwoorden zijn en, maar, of, want, dus. Onderschikkende zijn omdat, hoewel, als, dat.",
    ),
    dict(
        type="waarofniet",
        vraag="'Drie' is een telwoord en 'veel' een bijvoeglijk naamwoord.",
        antwoord=False,
        uitleg="'Veel' is ook een telwoord, een onbepaald telwoord. Bepaalde telwoorden noemen een exact aantal, onbepaalde niet.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke woorden zijn voorzetsels?",
        opties=["op", "onder", "tussen", "snel"],
        antwoord=[0, 1, 2],
        uitleg="'Snel' is een bijwoord: het zegt hoe iets gebeurt, niet waar iets zich bevindt.",
    ),
    dict(
        type="meerkeuze",
        vraag="In 'Hij loopt snel', welke woordsoort is 'snel'?",
        opties=[
            "een bijwoord",
            "een bijvoeglijk naamwoord",
            "een voorzetsel",
            "een tussenwerpsel",
        ],
        antwoord=0,
        uitleg="Het zegt iets over het werkwoord 'loopt'. In 'de snelle loper' zegt hetzelfde woord iets over een naamwoord en is het bijvoeglijk.",
    ),
    dict(
        type="waarofniet",
        vraag="Een bijvoeglijk naamwoord zegt altijd iets over een werkwoord.",
        antwoord=False,
        uitleg="Het zegt iets over een zelfstandig naamwoord. Een woord dat iets over een werkwoord zegt, is een bijwoord.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is het verschil tussen een bepaald en een onbepaald lidwoord?",
        opties=[
            "een bepaald lidwoord wijst naar iets bekends, een onbepaald niet",
            "een bepaald lidwoord staat voor een meervoud, een onbepaald voor een enkelvoud",
            "een bepaald lidwoord wordt altijd beklemtoond",
            "een bepaald lidwoord komt alleen in bijzinnen voor",
        ],
        antwoord=0,
        uitleg="'Ik zag de hond' veronderstelt dat je weet welke hond. 'Ik zag een hond' niet.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je het woord dat een persoon, dier, ding of begrip benoemt?",
        antwoord=["zelfstandig naamwoord", "een zelfstandig naamwoord", "substantief"],
        uitleg="Je herkent het aan het lidwoord dat je ervoor kan zetten: de vrijheid, het paard, een idee.",
    ),
    dict(
        type="meerkeuze",
        vraag="In 'Gelukkig regende het niet', welke woordsoort is 'gelukkig'?",
        opties=[
            "een bijwoord",
            "een bijvoeglijk naamwoord",
            "een tussenwerpsel",
            "een voegwoord",
        ],
        antwoord=0,
        uitleg="Het zegt iets over de hele zin, niet over een naamwoord. In 'een gelukkig kind' is hetzelfde woord wel bijvoeglijk.",
    ),
    dict(
        type="waarofniet",
        vraag="Een tussenwerpsel staat los van de rest van de zinsbouw.",
        antwoord=True,
        uitleg="Haal 'och' of 'hé' weg en de zin blijft gewoon staan. Bij de andere woordsoorten gaat dat niet.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welk woord in 'Er stonden veertien fietsen in het rek' is een telwoord?",
        opties=["veertien", "fietsen", "rek", "stonden"],
        antwoord=0,
        uitleg="Een bepaald telwoord noemt een precies aantal. Onbepaalde telwoorden zijn woorden als veel, weinig, enkele.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke van deze woorden zijn bijwoorden?",
        opties=["gisteren", "daar", "nauwelijks", "groen"],
        antwoord=[0, 1, 2],
        uitleg="Bijwoorden zeggen iets over tijd, plaats, mate of manier. 'Groen' hoort bij een naamwoord en is bijvoeglijk.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarom is het nuttig om woordsoorten te kunnen benoemen?",
        opties=[
            "omdat spellingregels vaak van de woordsoort afhangen",
            "omdat elke zin evenveel woordsoorten moet bevatten",
            "omdat woordsoorten de lengte van een tekst bepalen",
            "omdat een tekst zonder bijwoorden onleesbaar is",
        ],
        antwoord=0,
        uitleg="Of je 'de gekleurde muur' of 'de muur is gekleurd' schrijft, hangt af van hoe het woord gebruikt wordt.",
    ),
    dict(
        type="meerkeuze",
        vraag="In 'Ik wacht al een half uur op de bus', welk woord is een voorzetsel?",
        opties=["op", "al", "half", "wacht"],
        antwoord=0,
        uitleg="'Op de bus' is een voorzetselgroep. 'Al' en 'half' zijn hier bijwoord en bijvoeglijk naamwoord.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke woordsoort ontbreekt in 'kat sliep op mat'?",
        opties=[
            "de lidwoorden",
            "de voorzetsels",
            "de werkwoorden",
            "de zelfstandige naamwoorden",
        ],
        antwoord=0,
        uitleg="'De kat sliep op de mat' is de gewone Nederlandse zin. Zonder lidwoorden klinkt hij als telegramstijl.",
    ),
]

DEEL2 = [
    dict(
        type="meerkeuze",
        vraag="In 'Hij wast zich elke ochtend', wat is 'zich'?",
        opties=[
            "een wederkerend voornaamwoord",
            "een wederkerig voornaamwoord",
            "een bezittelijk voornaamwoord",
            "een aanwijzend voornaamwoord",
        ],
        antwoord=0,
        uitleg="De handeling keert terug naar het onderwerp zelf: hij wast zichzelf.",
    ),
    dict(
        type="meerkeuze",
        vraag="In 'De twee broers groetten elkaar', wat is 'elkaar'?",
        opties=[
            "een wederkerig voornaamwoord",
            "een wederkerend voornaamwoord",
            "een onbepaald voornaamwoord",
            "een betrekkelijk voornaamwoord",
        ],
        antwoord=0,
        uitleg="Wederkerig betekent over en weer: de ene groet de andere én omgekeerd. Daarvoor heb je minstens twee personen nodig.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je woorden als 'mijn', 'jouw' en 'hun'?",
        antwoord=["bezittelijk voornaamwoord", "bezittelijke voornaamwoorden"],
        uitleg="Ze zeggen bij wie iets hoort. Let op: 'hun' als bezittelijk voornaamwoord is correct, 'hun' als onderwerp niet.",
    ),
    dict(
        type="waarofniet",
        vraag="'Deze' en 'die' zijn aanwijzende voornaamwoorden.",
        antwoord=True,
        uitleg="Ze wijzen iets aan: deze en dit voor wat dichtbij is, die en dat voor wat verder weg staat.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke woorden zijn persoonlijke voornaamwoorden?",
        opties=["ik", "hem", "wij", "mijn"],
        antwoord=[0, 1, 2],
        uitleg="'Mijn' zegt van wie iets is en is dus bezittelijk. De drie andere vervangen een persoon.",
    ),
    dict(
        type="meerkeuze",
        vraag="In 'Het boek dat ik gisteren las, was spannend', wat is 'dat'?",
        opties=[
            "een betrekkelijk voornaamwoord",
            "een aanwijzend voornaamwoord",
            "een onderschikkend voegwoord",
            "een vragend voornaamwoord",
        ],
        antwoord=0,
        uitleg="Het verwijst terug naar 'het boek' én begint tegelijk een bijzin. Dat dubbele werk doet alleen een betrekkelijk voornaamwoord.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je 'wie', 'wat' en 'welke' als je er een vraag mee stelt?",
        antwoord=["vragend voornaamwoord", "vragende voornaamwoorden"],
        uitleg="Ze staan vooraan in een vraagzin en vervangen datgene waarnaar je vraagt.",
    ),
    dict(
        type="waarofniet",
        vraag="'Men' is een persoonlijk voornaamwoord.",
        antwoord=False,
        uitleg="'Men' is onbepaald, net als iemand, niemand, iedereen en alles. Het noemt geen bepaalde persoon.",
    ),
    dict(
        type="meerkeuze",
        vraag="Vergelijk 'Mijn fiets staat buiten' met 'De mijne staat buiten'. Wat is het verschil?",
        opties=[
            "in de eerste zin is het voornaamwoord bijvoeglijk gebruikt, in de tweede zelfstandig",
            "in de eerste zin is het voornaamwoord bezittelijk, in de tweede persoonlijk",
            "in de tweede zin ontbreekt het voornaamwoord helemaal",
            "in de tweede zin staat een aanwijzend voornaamwoord",
        ],
        antwoord=0,
        uitleg="Bijvoeglijk gebruikt staat het voornaamwoord bij een naamwoord. Zelfstandig gebruikt vervangt het dat naamwoord.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke soorten voornaamwoorden noemt de vakfiche?",
        opties=["wederkerend", "wederkerig", "betrekkelijk", "bijwoordelijk"],
        antwoord=[0, 1, 2],
        uitleg="De fiche noemt er acht: wederkerend, wederkerig, onbepaald, persoonlijk, bezittelijk, betrekkelijk, aanwijzend en vragend. Bijwoordelijk staat er niet bij.",
    ),
    dict(
        type="waarofniet",
        vraag="Een betrekkelijk voornaamwoord begint een bijzin.",
        antwoord=True,
        uitleg="'De man die belde' en 'het huis dat leegstaat': na het betrekkelijk voornaamwoord volgt telkens een bijzin.",
    ),
    dict(
        type="meerkeuze",
        vraag="In 'Wie heeft dat raam opengezet?', wat is 'wie'?",
        opties=[
            "een vragend voornaamwoord",
            "een betrekkelijk voornaamwoord",
            "een onbepaald voornaamwoord",
            "een persoonlijk voornaamwoord",
        ],
        antwoord=0,
        uitleg="In 'de man wie ik zag' zou 'wie' betrekkelijk zijn. Hier begint het een vraag, dus is het vragend.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je 'me' in de zin 'Ik was me elke ochtend'?",
        antwoord=["wederkerend voornaamwoord", "wederkerend", "een wederkerend voornaamwoord"],
        uitleg="In de eerste en tweede persoon zien wederkerende voornaamwoorden eruit als persoonlijke: me, je, ons. Kijk naar wat ze doen, niet naar hun vorm.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is het verschil tussen een wederkerend en een wederkerig voornaamwoord?",
        opties=[
            "wederkerend keert terug naar één onderwerp, wederkerig gaat over en weer",
            "wederkerend gebruik je in de verleden tijd, wederkerig in de tegenwoordige",
            "wederkerend hoort bij een bijzin, wederkerig bij een hoofdzin",
            "wederkerend is enkelvoud, wederkerig is altijd meervoud",
        ],
        antwoord=0,
        uitleg="'Ze wasten zich' betekent: elk zichzelf. 'Ze wasten elkaar' betekent: de een de ander.",
    ),
    dict(
        type="waarofniet",
        vraag="'Elkaar' kan je zonder betekenisverschil vervangen door 'zich'.",
        antwoord=False,
        uitleg="'Ze sloegen elkaar' en 'ze sloegen zich' zeggen iets heel anders. Wederkerig en wederkerend zijn niet uitwisselbaar.",
    ),
    dict(
        type="meerkeuze",
        vraag="In 'Die van mij is groter', hoe is 'die' gebruikt?",
        opties=[
            "zelfstandig, want het vervangt een naamwoord",
            "bijvoeglijk, want het staat bij een naamwoord",
            "als voegwoord, want het verbindt twee zinnen",
            "als bijwoord, want het zegt iets over 'groter'",
        ],
        antwoord=0,
        uitleg="Het aanwijzend voornaamwoord staat hier alleen en vervangt bijvoorbeeld 'fiets'. Dat heet zelfstandig gebruikt.",
    ),
    dict(
        type="meerkeuze",
        vraag="In welke zinnen staat een aanwijzend voornaamwoord?",
        opties=[
            "Dat huis staat al jaren te koop.",
            "Deze wil ik graag hebben.",
            "Zulke schoenen zijn veel te duur.",
            "Wie belt er zo laat nog aan?",
        ],
        antwoord=[0, 1, 2],
        uitleg="Dat, deze en zulke wijzen aan. 'Wie' stelt een vraag en is dus vragend.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarom staat er 'Ik zag hem gisteren' en niet 'Ik zag hij gisteren'?",
        opties=[
            "omdat het voornaamwoord hier geen onderwerp is",
            "omdat 'hij' geen bestaand voornaamwoord is",
            "omdat de zin in de verleden tijd staat",
            "omdat er een voorzetsel in de zin staat",
        ],
        antwoord=0,
        uitleg="Persoonlijke voornaamwoorden hebben twee vormen: een onderwerpsvorm (hij, zij, wij) en een andere vorm (hem, haar, ons).",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarom zijn verwijswoorden in een tekst meestal voornaamwoorden?",
        opties=[
            "omdat een voornaamwoord een naamwoord vervangt dat eerder stond",
            "omdat voornaamwoorden altijd vooraan de zin staan",
            "omdat voornaamwoorden de spelling vereenvoudigen",
            "omdat voornaamwoorden nooit van vorm veranderen",
        ],
        antwoord=0,
        uitleg="Net daarom hoef je 'de burgemeester van onze gemeente' niet in elke zin te herhalen: 'hij' volstaat.",
    ),
    dict(
        type="meerkeuze",
        vraag="In 'Er staat iemand aan de deur', wat is 'iemand'?",
        opties=[
            "een onbepaald voornaamwoord",
            "een persoonlijk voornaamwoord",
            "een aanwijzend voornaamwoord",
            "een wederkerend voornaamwoord",
        ],
        antwoord=0,
        uitleg="Het gaat om een persoon die niet nader bepaald wordt. Net als niemand, iedereen, alles en men.",
    ),
]
