# -*- coding: utf-8 -*-
"""🚀 Boost doorstroom — Gedrag, interactie en ecosystemen.

Biologie, de koppen "Gedrag en interactie" en "Materie- en energiestromen" van
de vakfiche natuurwetenschappen 2de graad doorstroom. Deel 1 gaat over gedrag,
communicatie en de interacties tussen organismen. Deel 2 gaat over het
ecosysteem zelf: biotische en abiotische factoren, de kringlopen, de
voedselrelaties en wat er gebeurt als het evenwicht verstoord raakt.
"""

DEEL1 = [
    dict(
        type="meerkeuze",
        vraag="Wat is aangeboren gedrag?",
        opties=[
            "gedrag dat een dier vertoont zonder het ooit geleerd te hebben",
            "gedrag dat een dier van zijn ouders heeft afgekeken",
            "gedrag dat een dier pas als volwassene kan vertonen",
            "gedrag dat een dier alleen in gevangenschap vertoont",
        ],
        antwoord=0,
        uitleg="Aangeboren gedrag ligt vast in het erfelijk materiaal. Een spin die haar eerste web bouwt, heeft dat van niemand gezien.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke vormen van aangeleerd gedrag zijn het? Kruis alles aan wat juist is.",
        opties=["conditioneren", "trial-and-error", "imitatie", "baltsgedrag"],
        antwoord=[0, 1, 2],
        uitleg="Conditioneren, met vallen en opstaan leren en nabootsen zijn manieren waarop een dier iets leert. Baltsgedrag hoort bij het aangeboren gedrag rond de voortplanting.",
    ),
    dict(
        type="waarofniet",
        vraag="Inprenting gebeurt in een korte, vaste periode kort na de geboorte.",
        antwoord=True,
        uitleg="Jonge ganzen volgen wat ze in hun eerste uren zien bewegen. Die periode is kort, en wat er dan geleerd wordt, blijft.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een hond kwijlt bij het geluid van de voerbak, nog voor hij eten ziet. Hoe heet dat?",
        opties=["conditioneren", "inprenting", "gewenning", "imponeergedrag"],
        antwoord=0,
        uitleg="Het dier koppelt een prikkel die eerst niets betekende aan een gevolg. Dat is conditioneren.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je het leren waarbij een dier stopt met reageren op een prikkel die telkens weer zonder gevolg blijft?",
        antwoord="gewenning",
        uitleg="Vogels die eerst wegvliegen voor een vogelverschrikker blijven na een tijd gewoon zitten. Dat heet gewenning.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is de functie van baltsgedrag?",
        opties=[
            "een partner van dezelfde soort aantrekken en overtuigen",
            "een roofdier uit de buurt van het nest wegjagen",
            "de grens van het eigen territorium duidelijk maken",
            "de rangorde binnen een groep opnieuw vastleggen",
        ],
        antwoord=0,
        uitleg="Balts hoort bij de voortplanting. Kleur, zang of dans tonen aan een mogelijke partner dat het dier gezond is en bij de juiste soort hoort.",
    ),
    dict(
        type="waarofniet",
        vraag="Imponeergedrag is een vorm van conflictgedrag waarbij het meestal niet tot een echt gevecht komt.",
        antwoord=True,
        uitleg="Door zich groter of luider voor te doen, lost een dier het conflict op zonder zich te verwonden. Dat is voor beide dieren voordeliger.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke vorm van communicatie gebruikt een mier die een geurspoor achterlaat?",
        opties=["chemische communicatie", "visuele communicatie", "auditieve communicatie", "sensitieve communicatie"],
        antwoord=0,
        uitleg="Een geurstof is een chemisch signaal. Mieren leggen er een spoor mee naar een voedselbron.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke voorbeelden horen bij visuele communicatie? Kruis alles aan wat juist is.",
        opties=[
            "de kleurenpracht van een pauwenstaart",
            "de dans van een honingbij",
            "het opzetten van de haren bij een kat",
            "het blaffen van een hond bij de deur",
        ],
        antwoord=[0, 1, 2],
        uitleg="Alles wat je moet zien om het te begrijpen, is visueel. Blaffen hoor je, dus dat is auditieve communicatie.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je de interactie waarbij het ene organisme voordeel heeft en het andere er schade van ondervindt?",
        antwoord="parasitisme",
        uitleg="Een parasiet leeft op of in een gastheer en haalt daar voedsel uit. De gastheer verzwakt, maar gaat meestal niet meteen dood.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is mutualisme?",
        opties=[
            "beide organismen hebben voordeel bij hun samenleven",
            "het ene organisme heeft voordeel, het andere merkt er niets van",
            "het ene organisme heeft voordeel, het andere lijdt schade",
            "beide organismen ondervinden schade van hun samenleven",
        ],
        antwoord=0,
        uitleg="Een bij haalt nectar en de bloem wordt bestoven: allebei winnen ze. Bij commensalisme wint er maar één zonder dat de ander iets merkt.",
    ),
    dict(
        type="waarofniet",
        vraag="Bij commensalisme hebben beide organismen even veel voordeel.",
        antwoord=False,
        uitleg="Bij commensalisme heeft er maar één voordeel; de ander ondervindt er niets van, niet in het goede en niet in het slechte.",
    ),
    dict(
        type="meerkeuze",
        vraag="Twee soorten vogels eten precies hetzelfde zaad op hetzelfde veld. Welke interactie is dat?",
        opties=["concurrentie", "predatie", "mutualisme", "commensalisme"],
        antwoord=0,
        uitleg="Ze strijden om dezelfde beperkte bron. Dat is concurrentie, en die kan ook tussen dieren van dezelfde soort spelen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is antibiose?",
        opties=[
            "het ene organisme maakt een stof die een ander organisme remt of doodt",
            "het ene organisme eet een ander organisme helemaal op",
            "twee organismen leven zo dicht samen dat ze niet meer zonder elkaar kunnen",
            "twee organismen wisselen van voedselbron zodra het er te druk wordt",
        ],
        antwoord=0,
        uitleg="Een schimmel die een antibioticum maakt, houdt bacteriën bij zich weg. Dat is antibiose, en daar komt ook ons woord antibioticum vandaan.",
    ),
    dict(
        type="waarofniet",
        vraag="Bij predatie hebben beide organismen voordeel.",
        antwoord=False,
        uitleg="Bij predatie doodt het ene organisme het andere en eet het op. Het is net de interactie waarbij één partij alles verliest.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarom lopen de aantallen van een prooi en een roofdier vaak met een vertraging achter elkaar aan?",
        opties=[
            "veel prooi laat de roofdieren toenemen, en veel roofdieren laten de prooi weer afnemen",
            "prooi en roofdier planten zich precies op hetzelfde moment van het jaar voort",
            "roofdieren verhuizen elk seizoen mee met de prooidieren naar een ander gebied",
            "de prooidieren eten de jongen van de roofdieren op zodra die te talrijk worden",
        ],
        antwoord=0,
        uitleg="Het is een terugkoppeling, net als bij hormonen. De twee aantallen golven om elkaar heen, en dat is het dynamisch evenwicht.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke uitspraken over symbiose zijn juist? Kruis alles aan wat juist is.",
        opties=[
            "twee soorten leven nauw met elkaar samen",
            "mutualisme is er een vorm van",
            "ze kan voor één of voor beide partners voordelig zijn",
            "ze bestaat alleen tussen dieren onderling",
        ],
        antwoord=[0, 1, 2],
        uitleg="Symbiose is het nauwe samenleven van twee soorten. Ook planten, schimmels en bacteriën doen eraan mee; denk aan korstmossen of aan mycorrhiza.",
    ),
    dict(
        type="waarofniet",
        vraag="Taakverdeling binnen een mierenkolonie is een vorm van gedrag dat de hele groep ten goede komt.",
        antwoord=True,
        uitleg="Werksters, soldaten en een koningin doen elk iets anders. Samen is de kolonie daardoor veel sterker dan elke mier apart.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je het gedrag waarbij een dier zijn eigen gebied afbakent en verdedigt?",
        antwoord="territoriumgedrag",
        uitleg="Door te zingen, te geuren of te dreigen houdt een dier soortgenoten uit zijn gebied. Zo verzekert het zich van voedsel en een nestplaats.",
    ),
    dict(
        type="meerkeuze",
        vraag="Hoe kan een interactie tussen organismen onze gezondheid beïnvloeden?",
        opties=[
            "nuttige darmbacteriën houden ziekteverwekkers op afstand",
            "roofdieren in de natuur maken ons immuun voor infecties",
            "concurrentie tussen planten levert ons extra vitamines op",
            "baltsgedrag van vogels zuivert de lucht die wij inademen",
        ],
        antwoord=0,
        uitleg="Ons microbioom leeft met ons samen. Zolang dat evenwicht standhoudt, krijgen ziekteverwekkers weinig ruimte; raakt het verstoord, dan wel.",
    ),
]

DEEL2 = [
    dict(
        type="meerkeuze",
        vraag="Wat is een ecosysteem?",
        opties=[
            "alle organismen in een gebied samen met hun niet-levende omgeving",
            "alle dieren van één soort die in hetzelfde gebied leven",
            "alle planten die in een gebied dezelfde bodem gebruiken",
            "alle organismen op aarde die van elkaar afhankelijk zijn",
        ],
        antwoord=0,
        uitleg="Een ecosysteem is het geheel van de levende gemeenschap en haar omgeving, met alle wisselwerkingen ertussen.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke factoren zijn abiotisch? Kruis alles aan wat juist is.",
        opties=["de temperatuur", "de hoeveelheid licht", "de zuurtegraad van de bodem", "de begrazing door schapen"],
        antwoord=[0, 1, 2],
        uitleg="Abiotisch betekent niet-levend: temperatuur, licht, water, bodem. Begrazing komt van levende wezens en is dus biotisch.",
    ),
    dict(
        type="waarofniet",
        vraag="Betreding, begrazing en bemesting zijn biotische factoren.",
        antwoord=True,
        uitleg="Ze gaan alle drie uit van levende wezens die het gebied gebruiken. Daarom staan ze bij de biotische factoren.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke rol spelen de producenten in een ecosysteem?",
        opties=[
            "ze maken met fotosynthese energierijke stoffen uit energiearme",
            "ze eten planten en geven de energie door aan de roofdieren",
            "ze breken dood materiaal af tot stoffen die planten weer opnemen",
            "ze houden de aantallen van de consumenten in evenwicht",
        ],
        antwoord=0,
        uitleg="Planten, algen en sommige bacteriën vangen lichtenergie op en leggen die vast in glucose. Alle andere schakels leven van wat zij maken.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je de organismen die dood organisch materiaal afbreken tot minerale stoffen?",
        antwoord="reducenten",
        uitleg="Bacteriën en schimmels zijn de reducenten. Zonder hen zou de materiekringloop vastlopen en bleven de voedingsstoffen in dode resten zitten.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarom is een voedselweb een betere voorstelling dan één voedselketen?",
        opties=[
            "de meeste soorten eten van meer dan één soort en worden door meer dan één soort gegeten",
            "een voedselketen toont alleen planten en laat de dieren volledig weg",
            "een voedselweb geeft precies weer hoeveel energie er in elke schakel zit",
            "een voedselketen is alleen bruikbaar voor ecosystemen in het water",
        ],
        antwoord=0,
        uitleg="In werkelijkheid lopen de ketens door elkaar. Een web toont die vertakkingen, en daarmee ook hoe een verstoring zich verspreidt.",
    ),
    dict(
        type="waarofniet",
        vraag="In een piramide van biomassa zit er in elke hogere schakel minder materie dan in de schakel eronder.",
        antwoord=True,
        uitleg="Bij elke stap gaat er energie verloren als warmte en wordt er materie verademd. Daarom kan de top maar klein zijn.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke processen horen samen in de koolstofkringloop? Kruis alles aan wat juist is.",
        opties=[
            "de fotosynthese van planten",
            "de celademhaling van planten en dieren",
            "het afbreken van dood materiaal door reducenten",
            "het verdampen van water uit de oceaan",
        ],
        antwoord=[0, 1, 2],
        uitleg="Fotosynthese legt koolstof vast, celademhaling en afbraak geven hem weer vrij als koolstofdioxide. Verdamping hoort bij de waterkringloop.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat gebeurt er met de energie in een ecosysteem?",
        opties=[
            "ze stroomt in één richting en gaat stap voor stap als warmte verloren",
            "ze draait net als de materie in een gesloten kringloop rond",
            "ze blijft volledig bewaard in de lichamen van de organismen",
            "ze neemt bij elke stap in de voedselketen juist toe",
        ],
        antwoord=0,
        uitleg="Materie draait rond, energie niet. Ze komt binnen als licht en verlaat het systeem uiteindelijk als warmte.",
    ),
    dict(
        type="invultekst",
        vraag="Welk proces zet energierijke stoffen weer om in energiearme en maakt daarbij energie vrij?",
        antwoord="celademhaling",
        uitleg="Bij de celademhaling wordt glucose met zuurstofgas afgebroken tot koolstofdioxide en water. De vrijgekomen energie gebruikt de cel voor haar werk.",
    ),
    dict(
        type="meerkeuze",
        vraag="Welke rol spelen bacteriën in de stikstofkringloop?",
        opties=[
            "ze zetten stikstof om in vormen die planten kunnen opnemen",
            "ze halen stikstof uit het water en slaan die op in de bodem",
            "ze breken stikstof af tot koolstofdioxide en water",
            "ze maken stikstof aan uit koolstof en zuurstofgas",
        ],
        antwoord=0,
        uitleg="Stikstofgas uit de lucht kunnen planten niet gebruiken. Bacteriën, onder meer in wortelknolletjes, zetten het om in nitraten die wel opneembaar zijn.",
    ),
    dict(
        type="waarofniet",
        vraag="De waterkringloop staat volledig los van de koolstofkringloop.",
        antwoord=False,
        uitleg="Ze grijpen in elkaar. Water is grondstof voor de fotosynthese en komt vrij bij de celademhaling, dus de twee kringlopen raken elkaar voortdurend.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarom is biodiversiteit belangrijk voor een ecosysteem?",
        opties=[
            "hoe meer soorten, hoe beter het systeem een verstoring kan opvangen",
            "hoe meer soorten, hoe sneller alle voedingsstoffen opgebruikt raken",
            "hoe meer soorten, hoe minder energie er van de zon nodig is",
            "hoe meer soorten, hoe korter de voedselketens worden",
        ],
        antwoord=0,
        uitleg="Valt er één soort weg, dan kan een andere haar rol gedeeltelijk overnemen. In een soortenarm systeem ontbreekt die reserve.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een meer krijgt jarenlang te veel mest binnen. Wat gebeurt er? Kruis alles aan wat juist is.",
        opties=[
            "de algen vermeerderen zich sterk",
            "er dringt minder licht door tot in de diepte",
            "het zuurstofgehalte daalt wanneer de algen afsterven",
            "de biodiversiteit in het meer neemt toe",
        ],
        antwoord=[0, 1, 2],
        uitleg="Dat is eutrofiëring. De algenbloei maakt het water troebel, en de afbraak van de dode algen slorpt de zuurstof op. Soorten verdwijnen in plaats van erbij te komen.",
    ),
    dict(
        type="waarofniet",
        vraag="Reducenten maken de materiekringloop rond.",
        antwoord=True,
        uitleg="Zij zetten dode resten weer om in minerale stoffen. Planten nemen die op, en zo begint de kringloop opnieuw.",
    ),
    dict(
        type="meerkeuze",
        vraag="Wat is het effect van klimaatverandering op een ecosysteem?",
        opties=[
            "soorten verschuiven of verdwijnen omdat hun leefomstandigheden veranderen",
            "alle soorten passen zich even snel aan en er verandert niets wezenlijks",
            "de voedselketens worden vanzelf langer en daardoor steviger",
            "de kringlopen van materie vallen helemaal stil bij hogere temperaturen",
        ],
        antwoord=0,
        uitleg="Temperatuur en neerslag horen bij de abiotische factoren. Veranderen ze, dan verschuiven de leefgebieden, en soorten die niet mee kunnen, verdwijnen.",
    ),
    dict(
        type="waarofniet",
        vraag="Een consument van de eerste orde eet andere dieren.",
        antwoord=False,
        uitleg="De consumenten van de eerste orde zijn juist de planteneters. Wie díé opeet, is een consument van de tweede orde.",
    ),
    dict(
        type="meerkeuze",
        vraag="Waarom zijn er in een ecosysteem veel meer planten dan toproofdieren?",
        opties=[
            "bij elke stap in de keten gaat het grootste deel van de energie verloren",
            "planten planten zich altijd sneller voort dan dieren dat kunnen",
            "toproofdieren hebben veel minder voedsel nodig dan planteneters",
            "planten hebben geen vijanden en kunnen dus ongestoord groeien",
        ],
        antwoord=0,
        uitleg="Van de energie in een schakel komt maar een klein deel in de volgende terecht. Daardoor kan de top van de piramide maar weinig dieren dragen.",
    ),
    dict(
        type="invultekst",
        vraag="Hoe noem je de niet-levende factoren van een ecosysteem, zoals licht, temperatuur en bodem?",
        antwoord="abiotische factoren",
        uitleg="Abiotische factoren bepalen wat er in een gebied kan leven. Samen met de biotische factoren maken ze het ecosysteem.",
    ),
    dict(
        type="meerkeuze",
        vraag="Een bos verliest door ziekte bijna al zijn bomen. Wat is het gevolg voor het ecosysteem?",
        opties=[
            "de voedselrelaties en de kringlopen raken verstoord, en veel soorten verdwijnen mee",
            "de overige soorten nemen gewoon de plaats van de bomen in, en er verandert weinig",
            "de energiestroom wordt groter omdat er meer licht op de bodem valt",
            "de reducenten verdwijnen als eerste omdat ze geen bomen meer hebben",
        ],
        antwoord=0,
        uitleg="De bomen zijn de belangrijkste producenten en bepalen de hele structuur. Vallen ze weg, dan verliezen veel soorten tegelijk hun voedsel en hun schuilplaats.",
    ),
]
