# -*- coding: utf-8 -*-
"""Cultuur en cultuuruitingen.

Van de vakfiche sociale en gedragswetenschappen (2DO, 2027), onderdeel
sociale wetenschappen: het begrip cultuur aan de hand van de zeven
cultuuruitingen, en culturen vergelijken: westers en niet-westers, de
dominante cultuur en subculturen, en jongerenculturen.

Deel 1 zijn de cultuuruitingen.
Deel 2 is het vergelijken van culturen.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is cultuur in de sociale wetenschappen?",
         opties=["alles wat een groep deelt en doorgeeft",
                 "kunst en muziek van een land",
                 "de taal die een land spreekt",
                 "de godsdienst van een groep mensen"],
         antwoord=0,
         uitleg="Breder dan kunst: ook gewoontes, kennis, rituelen, symbolen, taal en waarden en normen."),
    dict(type="meerkeuze",
         vraag="Welke cultuuruitingen noemt de vakfiche?",
         opties=["rituelen",
                 "symbolen",
                 "waarden en normen",
                 "inkomen"],
         antwoord=[0, 1, 2],
         uitleg="Zeven uitingen: gebruiken en gewoontes, kennis, kunstuitingen, rituelen, symbolen, taal, en waarden en normen."),
    dict(type="invultekst",
         vraag="Hoeveel cultuuruitingen noemt de vakfiche? Eén getal.",
         antwoord=["7", "zeven"],
         uitleg="Zeven. Samen beschrijven ze wat een cultuur is."),
    dict(type="meerkeuze",
         vraag="Een trouwfeest met een vast verloop. Welke cultuuruiting is dat?",
         opties=["een ritueel",
                 "een symbool",
                 "een vorm van kennis",
                 "een gewoonte zonder meer"],
         antwoord=0,
         uitleg="Een ritueel is een handeling met een vaste vorm en een betekenis erachter."),
    dict(type="waarofniet",
         vraag="Taal is volgens de vakfiche een cultuuruiting.",
         antwoord=True,
         uitleg="Ze draagt de hele cultuur: wie de taal leert, leert ook de gewoontes en de waarden erachter."),
    dict(type="meerkeuze",
         vraag="Een vlag of een logo. Welke cultuuruiting is dat?",
         opties=["een symbool",
                 "een ritueel met betekenis",
                 "een vorm van kennis",
                 "een gewoonte van een groep"],
         antwoord=0,
         uitleg="Een symbool staat voor iets anders. De betekenis spreekt enkel binnen die cultuur vanzelf."),
    dict(type="meerkeuze",
         vraag="Wat is het verschil tussen een waarde en een norm?",
         opties=["een waarde is een ideaal",
                 "een waarde is een regel",
                 "een norm is een gevoel",
                 "een norm is een gewoonte"],
         antwoord=0,
         uitleg="Een waarde is wat je belangrijk vindt, bijvoorbeeld eerlijkheid. De norm is de regel die eruit volgt: je liegt niet."),
    dict(type="invultekst",
         vraag="Hoe noem je de regel die uit een waarde volgt? Eén woord.",
         antwoord=["norm", "een norm", "de norm"],
         uitleg="Een norm. Uit de waarde respect volgt de norm dat je iemand laat uitspreken."),
    dict(type="meerkeuze",
         vraag="Op tijd komen. Welke cultuuruiting is dat?",
         opties=["een gebruik of gewoonte",
                 "een ritueel met betekenis",
                 "een symbool van een groep",
                 "een vorm van kennis"],
         antwoord=0,
         uitleg="Gebruiken en gewoontes verschillen sterk per cultuur. Wat hier te laat heet, is elders op tijd."),
    dict(type="waarofniet",
         vraag="Cultuur is volgens de vakfiche aangeboren.",
         antwoord=False,
         uitleg="Je leert ze, door socialisatie. Daarom kan ze ook veranderen en doorgegeven worden."),
    dict(type="meerkeuze",
         vraag="Welke uitingen zijn kunstuitingen?",
         opties=["muziek",
                 "schilderkunst",
                 "dans",
                 "een handdruk"],
         antwoord=[0, 1, 2],
         uitleg="Kunstuitingen zijn één van de zeven. Een handdruk is een gebruik of een ritueel."),
    dict(type="meerkeuze",
         vraag="Wat hoort onder kennis als cultuuruiting?",
         opties=["wat een groep weet en doorgeeft",
                 "wat een kind op school leert",
                 "wat in boeken staat",
                 "wat wetenschappelijk bewezen is"],
         antwoord=0,
         uitleg="Ook praktische kennis telt mee: hoe je iets kweekt, bouwt of bereidt."),
    dict(type="waarofniet",
         vraag="Een gebaar betekent in elke cultuur hetzelfde.",
         antwoord=False,
         uitleg="Een duim omhoog betekent niet overal goedkeuring. Daarom lees je een gebaar altijd in zijn context."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over cultuur kloppen?",
         opties=["ze wordt aangeleerd",
                 "ze wordt doorgegeven",
                 "ze verandert in de tijd",
                 "ze is overal hetzelfde"],
         antwoord=[0, 1, 2],
         uitleg="De eerste drie staan in de fiche. Culturen verschillen juist sterk van elkaar."),
    dict(type="meerkeuze",
         vraag="Een begrafenis met een vaste volgorde van handelingen. Welke uiting is dat?",
         opties=["een ritueel",
                 "een symbool van een groep",
                 "een vorm van kennis",
                 "een kunstuiting van een groep"],
         antwoord=0,
         uitleg="Rituelen markeren overgangen in een leven: geboorte, huwelijk, dood."),
    dict(type="waarofniet",
         vraag="Waarden en normen horen volgens de vakfiche bij de cultuuruitingen.",
         antwoord=True,
         uitleg="Ze zijn er een van de zeven, en meteen de kern: ze sturen het gedrag van iedereen in de groep."),
    dict(type="meerkeuze",
         vraag="Waarom verandert een cultuur in de loop van de tijd?",
         opties=["mensen nemen dingen over",
                 "cultuur ligt vast bij de geboorte",
                 "cultuur hangt van het weer af",
                 "cultuur hangt van de wet af"],
         antwoord=0,
         uitleg="Contact met andere groepen, nieuwe techniek en nieuwe ideeën doen een cultuur schuiven."),
    dict(type="meerkeuze",
         vraag="Wat betekent het dat cultuur een gedeeld geheel is?",
         opties=["een groep deelt ze samen",
                 "iedereen ter wereld deelt ze",
                 "ze is privé per persoon",
                 "ze wordt opgelegd door de wet"],
         antwoord=0,
         uitleg="Juist het delen maakt het cultuur. Wat één persoon alleen doet, is een gewoonte van die persoon."),
    dict(type="invultekst",
         vraag="Welke cultuuruiting is een vlag? Eén woord.",
         antwoord=["symbool", "een symbool"],
         uitleg="Een symbool staat voor iets anders: een land, een club of een idee."),
    dict(type="meerkeuze",
         vraag="Waarom staat cultuur in de fiche onder socialisatie?",
         opties=["cultuur wordt zo doorgegeven",
                 "cultuur is daar een deel van",
                 "cultuur gaat over de school",
                 "cultuur gaat over de wet"],
         antwoord=0,
         uitleg="Socialisatie is het doorgeven van waarden, normen en andere cultuuruitingen. Zonder cultuur valt er niets door te geven."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is een dominante cultuur?",
         opties=["de cultuur van de meerderheid",
                 "de cultuur van de regering",
                 "de cultuur met de meeste kunst",
                 "de cultuur met de oudste wortels"],
         antwoord=0,
         uitleg="Zij bepaalt de gangbare waarden en normen in een samenleving. Daarnaast bestaan er subculturen."),
    dict(type="meerkeuze",
         vraag="Wat is een subcultuur?",
         opties=["een groep met eigen gewoontes",
                 "een cultuur uit een ander land",
                 "een cultuur van vroeger",
                 "een cultuur zonder taal"],
         antwoord=0,
         uitleg="Een subcultuur deelt veel met de dominante cultuur maar heeft eigen symbolen, taal of gewoontes."),
    dict(type="invultekst",
         vraag="Hoe noem je de cultuur van jongeren met eigen muziek en kledij? Eén woord.",
         antwoord=["jongerencultuur", "jongerenculturen"],
         uitleg="Een jongerencultuur. Ze is vaak tijdelijk en verandert snel."),
    dict(type="meerkeuze",
         vraag="Welke vergelijkingen noemt de vakfiche?",
         opties=["westers en niet-westers",
                 "dominant en subcultuur",
                 "jongerenculturen",
                 "rijk en arm"],
         antwoord=[0, 1, 2],
         uitleg="Drie manieren om culturen naast elkaar te zetten. Rijk en arm staat niet in de fiche."),
    dict(type="waarofniet",
         vraag="Een subcultuur staat volgens de vakfiche altijd tegenover de dominante cultuur.",
         antwoord=False,
         uitleg="Ze kan ernaast bestaan zonder verzet. Alleen een tegencultuur zet zich uitdrukkelijk af."),
    dict(type="meerkeuze",
         vraag="Waarom is westers tegenover niet-westers een grove indeling?",
         opties=["binnen elke groep verschilt veel",
                 "er zijn te weinig landen",
                 "de talen zijn gelijk",
                 "de godsdiensten zijn gelijk"],
         antwoord=0,
         uitleg="Japan en Marokko zijn allebei niet-westers en lijken amper op elkaar. Zo'n indeling is enkel een eerste houvast."),
    dict(type="meerkeuze",
         vraag="Welke kenmerken worden vaak aan westerse culturen toegeschreven?",
         opties=["nadruk op het individu",
                 "nadruk op zelfstandigheid",
                 "nadruk op prestatie",
                 "nadruk op de grootfamilie"],
         antwoord=[0, 1, 2],
         uitleg="De nadruk op de grootfamilie hoort eerder bij culturen waar de groep voorgaat."),
    dict(type="invultekst",
         vraag="Hoe noem je de cultuur van de meerderheid in een samenleving? Eén woord.",
         antwoord=["dominant", "dominante", "dominante cultuur"],
         uitleg="De dominante cultuur. Zij levert de gangbare waarden en normen."),
    dict(type="meerkeuze",
         vraag="Een groep skaters met eigen kledij, taal en plekken. Wat is dat?",
         opties=["een subcultuur",
                 "de dominante cultuur",
                 "een niet-westerse cultuur",
                 "een ritueel van een groep"],
         antwoord=0,
         uitleg="Eigen symbolen en gewoontes binnen een grotere samenleving: dat is een subcultuur."),
    dict(type="waarofniet",
         vraag="Iemand kan tegelijk bij de dominante cultuur en bij een subcultuur horen.",
         antwoord=True,
         uitleg="Dat is zelfs de regel. Je deelt de taal en de wetten en daarnaast de gewoontes van je eigen groep."),
    dict(type="meerkeuze",
         vraag="Waarom verandert een jongerencultuur sneller dan de dominante cultuur?",
         opties=["ze draait om onderscheid",
                 "ze heeft minder leden",
                 "ze heeft geen symbolen",
                 "ze heeft geen taal"],
         antwoord=0,
         uitleg="Zodra iedereen iets overneemt, verliest het zijn onderscheidende kracht en zoekt de groep iets nieuws."),
    dict(type="meerkeuze",
         vraag="Waarmee vergelijk je volgens de fiche twee culturen?",
         opties=["met de cultuuruitingen",
                 "met het aantal inwoners",
                 "met het inkomen per hoofd",
                 "met de oppervlakte"],
         antwoord=0,
         uitleg="De zeven uitingen vormen het raster: taal, rituelen, symbolen, waarden en normen, en zo verder."),
    dict(type="waarofniet",
         vraag="Een cultuur beoordelen vanuit je eigen cultuur heet etnocentrisme.",
         antwoord=True,
         uitleg="De eigen gewoontes als de normale nemen. Het tegendeel is proberen te kijken vanuit die andere cultuur."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over subculturen kloppen?",
         opties=["ze hebben eigen symbolen",
                 "ze bestaan binnen een grotere cultuur",
                 "je kan er zelf bij gaan horen",
                 "ze hebben een eigen wet"],
         antwoord=[0, 1, 2],
         uitleg="Een eigen wet hebben ze niet: ze vallen onder dezelfde wetten als iedereen."),
    dict(type="meerkeuze",
         vraag="Een jongere draagt kledij die zijn ouders lelijk vinden. Wat gebeurt hier?",
         opties=["hij toont bij welke groep hij hoort",
                 "hij verlaat de dominante cultuur",
                 "hij verwerpt alle normen",
                 "hij verandert van taal"],
         antwoord=0,
         uitleg="Kledij is een symbool. Het verschil met de ouders is net wat het bruikbaar maakt."),
    dict(type="waarofniet",
         vraag="Culturen blijven onaangeroerd als mensen met elkaar in contact komen.",
         antwoord=False,
         uitleg="Ze beïnvloeden elkaar: eten, muziek en woorden reizen mee. Een groep die gewoontes overneemt, doet aan acculturatie."),
    dict(type="meerkeuze",
         vraag="Wat is een cultuurschok?",
         opties=["verwarring in een vreemde cultuur",
                 "een ruzie tussen twee groepen",
                 "een verbod op een gewoonte",
                 "een snelle verandering in een land"],
         antwoord=0,
         uitleg="Wat vanzelf sprak, klopt plots niet meer. Veel mensen maken dat mee bij een verhuis naar een ander land."),
    dict(type="meerkeuze",
         vraag="Waarom is het nuttig om cultuuruitingen te kennen bij een vergelijking?",
         opties=["je vergelijkt dan punt per punt",
                 "je kan er een score op zetten",
                 "je kan er landen mee rangschikken",
                 "je kan er gedrag mee voorspellen"],
         antwoord=0,
         uitleg="Zonder raster blijft een vergelijking bij een indruk. Met de zeven uitingen wordt ze systematisch."),
    dict(type="invultekst",
         vraag="Hoe noem je het beoordelen van een andere cultuur vanuit de jouwe? Eén woord.",
         antwoord=["etnocentrisme", "etnocentrisch"],
         uitleg="Etnocentrisme. Het staat tegenover cultuurrelativisme, waarbij je een gewoonte in haar eigen context bekijkt."),
    dict(type="meerkeuze",
         vraag="Twee landen vieren allebei nieuwjaar maar op een andere dag. Wat zie je?",
         opties=["hetzelfde ritueel, andere invulling",
                 "hetzelfde symbool in twee landen",
                 "dezelfde kennis in twee landen",
                 "dezelfde taal in twee landen"],
         antwoord=0,
         uitleg="De functie is gelijk, de vorm verschilt. Zo vergelijk je culturen aan de hand van een uiting."),
]
