# -*- coding: utf-8 -*-
"""De socio-emotionele ontwikkeling en de gehechtheid.

Van de vakfiche sociale en gedragswetenschappen (2DO, 2027): de sociale
ontwikkeling met haar mijlpalen, de emotionele ontwikkeling, wat gehechtheid
is en hoe ze groeit, de veilige en de drie onveilige hechtingspatronen, en de
gevolgen scheidingsangst en angst voor vreemden.

Deel 1 zijn de sociale ontwikkeling en de mijlpalen.
Deel 2 is de gehechtheid.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Waaruit bestaat de socio-emotionele ontwikkeling?",
         opties=["de sociale en de emotionele",
                 "de sociale en de morele kant",
                 "de emotionele en de morele kant",
                 "de sociale en de fysieke kant"],
         antwoord=0,
         uitleg="Twee kanten in één domein: omgaan met anderen, en omgaan met je eigen gevoelens."),
    dict(type="meerkeuze",
         vraag="Wat is een mijlpaal in de sociale ontwikkeling?",
         opties=["een stap die de meeste kinderen zetten",
                 "een fout die veel jonge kinderen maken",
                 "een vaste leeftijd voor iets nieuws",
                 "een proef bij de dokter op het consult"],
         antwoord=0,
         uitleg="Zoals de eerste glimlach of het samen spelen. De orde ligt vrij vast, de leeftijd niet."),
    dict(type="invultekst",
         vraag="Hoe noem je de eerste glimlach naar een gezicht rond zes weken? Twee woorden.",
         antwoord=["sociale glimlach", "de sociale glimlach"],
         uitleg="De sociale glimlach is gericht aan iemand. Daarvoor lacht een baby ook, maar niet naar iemand."),
    dict(type="meerkeuze",
         vraag="Twee peuters spelen naast elkaar met eigen speelgoed. Hoe heet dat?",
         opties=["parallel spel",
                 "samen spel",
                 "rollenspel met elkaar",
                 "spel met een regel erbij"],
         antwoord=0,
         uitleg="Parallel spel komt voor het samen spelen. Ze kijken naar elkaar maar spelen nog apart."),
    dict(type="waarofniet",
         vraag="Een kleuter kan al echt samen spelen met een rol voor elk kind.",
         antwoord=True,
         uitleg="In de kleutertijd komt het doen-alsof-spel met rollen: winkeltje, dokter, gezin."),
    dict(type="meerkeuze",
         vraag="Welke mijlpalen horen bij de sociale ontwikkeling van een baby?",
         opties=["de sociale glimlach",
                 "de eigen naam herkennen",
                 "de armpjes strekken om opgenomen te worden",
                 "leren fietsen zonder steunwieltjes"],
         antwoord=[0, 1, 2],
         uitleg="De eerste drie gaan over contact met anderen. Fietsen hoort bij de motoriek."),
    dict(type="invultekst",
         vraag="Welke groep wordt in de adolescentie het belangrijkst? Eén woord.",
         antwoord=["peergroep", "leeftijdsgenoten", "de peergroep"],
         uitleg="De peergroep, de leeftijdsgenoten. Het gezin blijft belangrijk maar krijgt een andere plaats."),
    dict(type="meerkeuze",
         vraag="Wat hoort bij de emotionele ontwikkeling?",
         opties=["leren omgaan met je gevoelens",
                 "leren omgaan met je vrienden",
                 "leren omgaan met de regels",
                 "leren omgaan met je lichaam"],
         antwoord=0,
         uitleg="Gevoelens leren herkennen, benoemen en sturen. Dat loopt het hele leven door."),
    dict(type="waarofniet",
         vraag="Een baby van twee maanden kan zijn eigen gevoelens al benoemen.",
         antwoord=False,
         uitleg="Hij voelt wel, maar heeft er geen woorden voor. Benoemen komt pas met de taal, in de peutertijd."),
    dict(type="meerkeuze",
         vraag="Een peuter krijgt een woedebui. Wat zegt dat over zijn ontwikkeling?",
         opties=["hij kan zijn gevoel nog niet sturen",
                 "hij heeft geen gevoelens van zichzelf",
                 "hij is niet veilig gehecht aan iemand",
                 "hij heeft een achterstand opgelopen"],
         antwoord=0,
         uitleg="Het gevoel is er wel, de rem nog niet. Die komt pas met de rijping van de hersenen."),
    dict(type="meerkeuze",
         vraag="Welke mijlpalen horen bij de kleutertijd?",
         opties=["samen spelen met rollen",
                 "een vriendje kiezen",
                 "beurt leren afwachten",
                 "lid worden van een jeugdbeweging"],
         antwoord=[0, 1, 2],
         uitleg="De eerste drie passen bij vier of vijf jaar. Een jeugdbeweging komt meestal later."),
    dict(type="meerkeuze",
         vraag="Wat betekent prosociaal gedrag?",
         opties=["gedrag dat anderen helpt",
                 "gedrag dat anderen schaadt",
                 "gedrag dat regels volgt",
                 "gedrag dat opvalt in een groep"],
         antwoord=0,
         uitleg="Helpen, delen, troosten. Het tegengestelde is antisociaal gedrag."),
    dict(type="waarofniet",
         vraag="De socio-emotionele ontwikkeling stopt na de adolescentie.",
         antwoord=False,
         uitleg="Ze loopt door: een relatie, ouder worden en afscheid nemen vragen allemaal nieuwe stappen."),
    dict(type="meerkeuze",
         vraag="Waarom is de peergroep in de adolescentie zo belangrijk?",
         opties=["ze helpt bij het zoeken naar jezelf",
                 "ze vervangt de ouders volledig",
                 "ze geeft regels zonder straf",
                 "ze zorgt voor minder conflicten"],
         antwoord=0,
         uitleg="Spiegelen aan leeftijdsgenoten hoort bij het vormen van een identiteit. De ouders blijven wel nodig."),
    dict(type="meerkeuze",
         vraag="Een kind van acht troost een vriendje dat gevallen is. Wat zie je?",
         opties=["prosociaal gedrag",
                 "antisociaal gedrag",
                 "parallel spel",
                 "een woedebui"],
         antwoord=0,
         uitleg="Het kind ziet het gevoel van een ander en doet er iets mee. Dat vraagt perspectief nemen."),
    dict(type="waarofniet",
         vraag="Mijlpalen komen bij het ene kind later dan bij het andere.",
         antwoord=True,
         uitleg="De spreiding is groot, dus één late mijlpaal zegt weinig. Pas als er meerdere uitblijven, kijkt men verder."),
    dict(type="meerkeuze",
         vraag="Wat is emotieregulatie?",
         opties=["je gevoel kunnen sturen",
                 "je gevoel kunnen verbergen",
                 "je gevoel kunnen benoemen",
                 "je gevoel kunnen uiten bij een ander"],
         antwoord=0,
         uitleg="Niet onderdrukken maar sturen: rustig worden, uitstellen, een andere uitweg zoeken."),
    dict(type="meerkeuze",
         vraag="Welke fase brengt de grootste stap in de emotieregulatie?",
         opties=["de kleutertijd",
                 "de babytijd",
                 "de prenatale fase",
                 "de late volwassenheid"],
         antwoord=0,
         uitleg="Met de taal komt het benoemen, en daarmee het sturen. Daarom helpt het kleuters als je hun gevoel benoemt."),
    dict(type="invultekst",
         vraag="Hoe noem je gedrag dat anderen schaadt? Eén woord.",
         antwoord=["antisociaal", "antisociaal gedrag"],
         uitleg="Antisociaal gedrag staat tegenover prosociaal gedrag. Het is een gevolg van mislukte socialisatie."),
    dict(type="meerkeuze",
         vraag="Waarom hangt de sociale ontwikkeling samen met het denken?",
         opties=["je moet een ander kunnen begrijpen",
                 "je moet goed kunnen tellen",
                 "je moet veel woorden kennen",
                 "je moet goed kunnen onthouden"],
         antwoord=0,
         uitleg="Perspectief nemen is een cognitieve stap. Zonder die stap blijft samenwerken moeilijk."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is gehechtheid?",
         opties=["een duurzame band met een verzorger",
                 "een gevoel van veiligheid thuis",
                 "een vriendschap met een kind",
                 "een gewoonte in een gezin"],
         antwoord=0,
         uitleg="Een band die blijft, ook als de verzorger even weg is. Ze ontstaat in het eerste levensjaar."),
    dict(type="meerkeuze",
         vraag="Waaruit groeit gehechtheid vooral?",
         opties=["uit antwoorden op signalen",
                 "uit het aantal uren samen",
                 "uit het aantal verzorgers",
                 "uit de leeftijd van de ouder"],
         antwoord=0,
         uitleg="Een baby huilt en er komt troost. Die herhaling bouwt het vertrouwen op, niet de klok."),
    dict(type="invultekst",
         vraag="Hoe noem je de hechting waarbij een kind durft te verkennen? Eén woord.",
         antwoord=["veilig", "veilige", "veilige hechting"],
         uitleg="Veilige hechting: de verzorger is een veilige haven om naar terug te keren."),
    dict(type="meerkeuze",
         vraag="Een kind speelt rustig, kijkt af en toe of mama er nog is en gaat verder. Welke hechting is dat?",
         opties=["veilige hechting",
                 "angstig-vermijdende hechting",
                 "angstig-ambivalente hechting",
                 "gedesorganiseerde hechting"],
         antwoord=0,
         uitleg="Verkennen én terugkeren is het beeld van veilige hechting."),
    dict(type="waarofniet",
         vraag="De vakfiche onderscheidt drie vormen van onveilige hechting.",
         antwoord=True,
         uitleg="Angstig-vermijdend, angstig-ambivalent en gedesorganiseerd of gedesoriënteerd."),
    dict(type="meerkeuze",
         vraag="Een kind negeert zijn moeder als ze terugkomt. Welke hechting is dat?",
         opties=["angstig-vermijdend",
                 "veilige hechting",
                 "angstig-ambivalente hechting",
                 "gedesorganiseerde hechting"],
         antwoord=0,
         uitleg="Het kind lijkt onverschillig, maar van binnen is er wel spanning. Het heeft geleerd dat vragen weinig oplevert."),
    dict(type="meerkeuze",
         vraag="Welke vormen van onveilige hechting noemt de vakfiche?",
         opties=["angstig-vermijdend",
                 "angstig-ambivalent",
                 "gedesorganiseerd",
                 "zelfstandig-vermijdend"],
         antwoord=[0, 1, 2],
         uitleg="Drie vormen. Zelfstandig-vermijdend bestaat niet als term."),
    dict(type="invultekst",
         vraag="Welke hechting wisselt tussen vastklampen en wegduwen? Vul in: angstig-...",
         antwoord=["ambivalent", "ambivalente"],
         uitleg="Angstig-ambivalent: het kind wil troost en weert ze tegelijk af, omdat de reactie onvoorspelbaar was."),
    dict(type="meerkeuze",
         vraag="Een kind vertoont bij de terugkeer van zijn ouder bevriezen en verwarring. Welke hechting is dat?",
         opties=["gedesorganiseerd",
                 "veilige hechting",
                 "angstig-vermijdende hechting",
                 "angstig-ambivalente hechting"],
         antwoord=0,
         uitleg="Er is geen vaste strategie: de verzorger is tegelijk de bron van troost en van angst."),
    dict(type="waarofniet",
         vraag="Scheidingsangst wijst er altijd op dat een kind onveilig gehecht is.",
         antwoord=False,
         uitleg="Juist omgekeerd: scheidingsangst is een normaal gevolg van hechting. Het kind weet dat de verzorger bestaat."),
    dict(type="meerkeuze",
         vraag="Rond welke leeftijd komt de angst voor vreemden?",
         opties=["rond acht maanden",
                 "rond twee maanden",
                 "rond drie jaar",
                 "rond vijf jaar"],
         antwoord=0,
         uitleg="Samen met de persoonspermanentie. Het kind herkent nu wie vertrouwd is en wie niet."),
    dict(type="meerkeuze",
         vraag="Welke gevolgen van hechting noemt de vakfiche?",
         opties=["scheidingsangst",
                 "angst voor vreemden",
                 "veilig durven verkennen",
                 "leren stappen"],
         antwoord=[0, 1, 2],
         uitleg="Drie gevolgen van een band. Stappen hoort bij de motoriek."),
    dict(type="waarofniet",
         vraag="Een kind kan zich aan meer dan één persoon hechten.",
         antwoord=True,
         uitleg="Aan beide ouders, aan grootouders, aan een vaste begeleider. Wel meestal met één hoofdfiguur."),
    dict(type="meerkeuze",
         vraag="Waarom durft een veilig gehecht kind verder weg te spelen?",
         opties=["het weet dat het kan terugkeren",
                 "het voelt geen angst",
                 "het merkt de afstand niet",
                 "het kijkt niet naar zijn ouder"],
         antwoord=0,
         uitleg="De veilige haven maakt verkennen mogelijk. Angst is er wel, maar ze blokkeert niet."),
    dict(type="meerkeuze",
         vraag="Welke houding van een verzorger helpt veilige hechting?",
         opties=["voorspelbaar reageren",
                 "warm reageren",
                 "signalen opmerken",
                 "altijd meteen ingrijpen"],
         antwoord=[0, 1, 2],
         uitleg="Voorspelbaar, warm en afgestemd. Altijd meteen ingrijpen laat een kind niets zelf oplossen."),
    dict(type="waarofniet",
         vraag="Een hechtingspatroon ligt na het eerste jaar voorgoed vast.",
         antwoord=False,
         uitleg="Het is taai maar niet onveranderlijk. Een nieuwe vaste band kan het beeld bijsturen."),
    dict(type="meerkeuze",
         vraag="Hoe onderzocht men hechting klassiek?",
         opties=["met een scheiding en hereniging",
                 "met een vragenlijst voor de ouders",
                 "met een test bij de dokter zelf",
                 "met een gesprek met het kind zelf"],
         antwoord=0,
         uitleg="De vreemde-situatieproef van Ainsworth. Hoe het kind reageert bij de hereniging zegt het meest."),
    dict(type="invultekst",
         vraag="Hoe noem je de angst van een baby als zijn verzorger weggaat? Eén woord.",
         antwoord=["scheidingsangst", "de scheidingsangst"],
         uitleg="Scheidingsangst begint rond acht maanden en wordt in de peutertijd weer minder."),
    dict(type="meerkeuze",
         vraag="Waarom is de hechting belangrijk voor de latere ontwikkeling?",
         opties=["ze vormt het beeld van relaties",
                 "ze bepaalt de intelligentie",
                 "ze bepaalt de motoriek",
                 "ze bepaalt het karakter volledig"],
         antwoord=0,
         uitleg="Wie leert dat anderen betrouwbaar zijn, gaat later met dat beeld een relatie in. Vastleggen doet ze niets."),
    dict(type="meerkeuze",
         vraag="Een baby huilt en wordt soms getroost en soms genegeerd. Welke hechting ligt voor de hand?",
         opties=["angstig-ambivalent",
                 "veilige hechting",
                 "angstig-vermijdende hechting",
                 "gedesorganiseerde hechting"],
         antwoord=0,
         uitleg="Onvoorspelbaarheid maakt een kind waakzaam: het klampt zich vast om maar zeker te zijn."),
]
