# -*- coding: utf-8 -*-
"""De morele ontwikkeling volgens Kohlberg.

Van de vakfiche sociale en gedragswetenschappen (2DO, 2027): de morele
ontwikkeling per levensfase en de drie stadia van Kohlberg, met het stadium
bepalen uit een voorbeeld.

Deel 1 zijn de morele ontwikkeling en het pre-conventionele stadium.
Deel 2 zijn het conventionele en het post-conventionele stadium.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Waarover gaat de morele ontwikkeling?",
         opties=["goed en kwaad",
                 "kennen en begrijpen van zaken",
                 "voelen en omgaan met anderen",
                 "groeien en rijpen van het lichaam"],
         antwoord=0,
         uitleg="Het gaat over wat je juist of fout vindt, en vooral over waaróm je dat vindt."),
    dict(type="meerkeuze",
         vraag="Hoeveel stadia onderscheidt Kohlberg?",
         opties=["drie",
                 "vier stadia na elkaar",
                 "vijf stadia na elkaar",
                 "acht stadia na elkaar"],
         antwoord=0,
         uitleg="Pre-conventioneel, conventioneel en post-conventioneel. Piaget had er vier voor het denken."),
    dict(type="invultekst",
         vraag="Welk stadium van Kohlberg komt eerst? Vul in: het ...-conventioneel stadium",
         antwoord=["pre"],
         uitleg="Het pre-conventioneel stadium: goed is wat geen straf oplevert."),
    dict(type="meerkeuze",
         vraag="Waar kijkt Kohlberg naar om het stadium te bepalen?",
         opties=["de reden achter het antwoord",
                 "het antwoord zelf, juist of fout",
                 "de leeftijd van de persoon",
                 "het gedrag op dat moment zelf"],
         antwoord=0,
         uitleg="Twee mensen kunnen hetzelfde doen om een heel andere reden. De redenering bepaalt het stadium."),
    dict(type="waarofniet",
         vraag="Kohlberg gebruikte verhaaltjes met een moeilijke keuze om het stadium te bepalen.",
         antwoord=True,
         uitleg="Het bekendste is het dilemma van Heinz, over een man die medicijnen steelt voor zijn zieke vrouw."),
    dict(type="meerkeuze",
         vraag="Een kind steelt niet omdat het bang is voor straf. Welk stadium is dat?",
         opties=["het pre-conventionele",
                 "het conventionele stadium",
                 "het post-conventionele stadium",
                 "het formeel-operationele stadium"],
         antwoord=0,
         uitleg="Straf en beloning sturen het gedrag. Er is nog geen regel of beginsel in het spel."),
    dict(type="meerkeuze",
         vraag="Welke redenen horen bij het pre-conventionele stadium?",
         opties=["ik word anders gestraft",
                 "ik krijg er iets voor terug",
                 "ik wil geen last krijgen",
                 "het is tegen de wet"],
         antwoord=[0, 1, 2],
         uitleg="Alles draait om de gevolgen voor jezelf. De wet noemen hoort bij het conventionele stadium."),
    dict(type="invultekst",
         vraag="Wat stuurt het gedrag in het pre-conventionele stadium? Twee woorden.",
         antwoord=["straf en beloning", "beloning en straf"],
         uitleg="Goed is wat beloond wordt, fout is wat gestraft wordt. Het kind kijkt naar het gevolg, niet naar de regel."),
    dict(type="meerkeuze",
         vraag="Bij welke levensfase hoort het pre-conventionele stadium meestal?",
         opties=["de kindertijd",
                 "de adolescentie",
                 "de vroege volwassenheid",
                 "de late volwassenheid"],
         antwoord=0,
         uitleg="Vooral bij kleuters en jonge lagereschoolkinderen. Maar een volwassene kan er ook in terugvallen."),
    dict(type="waarofniet",
         vraag="Iedereen doorloopt de drie stadia van Kohlberg volledig.",
         antwoord=False,
         uitleg="Veel mensen blijven in het conventionele stadium. Het post-conventionele bereikt lang niet iedereen."),
    dict(type="meerkeuze",
         vraag="Een kleuter deelt zijn koek omdat hij er een snoepje voor krijgt. Welk stadium is dat?",
         opties=["het pre-conventionele",
                 "het conventionele stadium",
                 "het post-conventionele stadium",
                 "het concreet-operationele stadium"],
         antwoord=0,
         uitleg="Delen om er iets voor terug te krijgen is ruilen. De ander telt nog niet mee als persoon."),
    dict(type="meerkeuze",
         vraag="Waarom noemt Kohlberg dit stadium pre-conventioneel?",
         opties=["de regels tellen nog niet mee",
                 "er zijn nog geen gevoelens bij",
                 "er wordt nog niet nagedacht",
                 "er is nog geen taal voor nodig"],
         antwoord=0,
         uitleg="Conventies zijn afspraken en regels. In dit stadium kijkt het kind enkel naar het gevolg voor zichzelf."),
    dict(type="waarofniet",
         vraag="De morele ontwikkeling staat volgens de vakfiche los van de cognitieve ontwikkeling.",
         antwoord=False,
         uitleg="Ze hangen samen: je kan pas over een beginsel redeneren als je abstract kan denken."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken kloppen over de stadia van Kohlberg?",
         opties=["de orde ligt vast",
                 "een stadium overslaan gaat niet",
                 "de reden telt, niet de daad",
                 "de leeftijd bepaalt het stadium"],
         antwoord=[0, 1, 2],
         uitleg="De leeftijd zegt weinig: twee mensen van dertig kunnen in een ander stadium zitten."),
    dict(type="meerkeuze",
         vraag="Een kind gehoorzaamt enkel als de juf kijkt. Welk stadium is dat?",
         opties=["het pre-conventionele",
                 "het conventionele stadium",
                 "het post-conventionele stadium",
                 "het sensomotorische stadium"],
         antwoord=0,
         uitleg="Zonder toezicht is er geen gevolg, en dus geen reden om zich in te houden."),
    dict(type="waarofniet",
         vraag="Wie in het pre-conventionele stadium zit, kan zich moeilijk in een ander verplaatsen.",
         antwoord=True,
         uitleg="Het eigen gevolg staat voorop. Dat past bij het egocentrisme dat Piaget in dezelfde jaren beschrijft."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken kloppen over een moreel dilemma?",
         opties=["er is geen goed antwoord",
                 "je moet je keuze uitleggen",
                 "beide keuzes kosten iets",
                 "er is altijd één juist antwoord"],
         antwoord=[0, 1, 2],
         uitleg="Beide keuzes botsen met iets dat je belangrijk vindt. Juist daarom toont de uitleg het stadium."),
    dict(type="meerkeuze",
         vraag="In het dilemma van Heinz steelt een man medicijnen voor zijn zieke vrouw. Wat vraagt Kohlberg?",
         opties=["of het mag, en waarom",
                 "of de man gestraft moet worden",
                 "of de vrouw beter wordt",
                 "of de apotheker gelijk heeft"],
         antwoord=0,
         uitleg="Het antwoord ja of nee zegt niets. De uitleg erbij zegt alles over het stadium."),
    dict(type="invultekst",
         vraag="Hoe noem je een verhaal met een moeilijke morele keuze? Twee woorden.",
         antwoord=["moreel dilemma", "een moreel dilemma"],
         uitleg="Een moreel dilemma dwingt je te kiezen en je keuze uit te leggen."),
    dict(type="meerkeuze",
         vraag="Een peuter weet nog niet dat slaan pijn doet bij een ander. Wat ontbreekt?",
         opties=["het perspectief nemen",
                 "de taal om het te zeggen",
                 "de motoriek om het te laten",
                 "de kennis van de regel"],
         antwoord=0,
         uitleg="Zonder je in een ander te verplaatsen, kan er geen moreel oordeel ontstaan. Dat komt pas later."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Waar kijkt iemand in het conventionele stadium naar?",
         opties=["de regels en de groep",
                 "de straf en de beloning",
                 "zijn eigen beginselen",
                 "zijn eigen voordeel ervan"],
         antwoord=0,
         uitleg="Goed is wat de groep of de wet verwacht. De eigen voordelen tellen minder."),
    dict(type="meerkeuze",
         vraag="Een jongen rookt niet omdat zijn vrienden dat stom zouden vinden. Welk stadium is dat?",
         opties=["het conventionele",
                 "het pre-conventionele stadium",
                 "het post-conventionele stadium",
                 "het formeel-operationele stadium"],
         antwoord=0,
         uitleg="Wat de groep ervan vindt, geeft de doorslag. Dat is kenmerkend voor het conventionele stadium."),
    dict(type="invultekst",
         vraag="Welk stadium van Kohlberg is het laatste? Vul in: het ...-conventioneel stadium",
         antwoord=["post"],
         uitleg="Het post-conventioneel stadium. Daar staan eigen beginselen boven de regel."),
    dict(type="meerkeuze",
         vraag="Welke redenen horen bij het conventionele stadium?",
         opties=["het staat zo in de wet",
                 "zo hoort het nu eenmaal",
                 "anders ben ik geen goede vriend",
                 "anders word ik gestraft"],
         antwoord=[0, 1, 2],
         uitleg="De wet, de gewoonte en de verwachting van anderen. Straf hoort bij het eerste stadium."),
    dict(type="waarofniet",
         vraag="Veel volwassenen blijven volgens Kohlberg in het conventionele stadium.",
         antwoord=True,
         uitleg="De regels en de wet volgen is voor de meeste mensen voldoende. Daar is ook niets mis mee."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken kenmerken het post-conventionele stadium?",
         opties=["eigen beginselen wegen zwaar",
                 "een regel kan je afwegen",
                 "rechtvaardigheid gaat voor",
                 "de straf weegt het zwaarst"],
         antwoord=[0, 1, 2],
         uitleg="Wie hier zit, weegt een regel af tegen een beginsel als rechtvaardigheid of menselijke waardigheid."),
    dict(type="meerkeuze",
         vraag="Iemand betoogt tegen een wet die hij onrechtvaardig vindt. Welk stadium is dat?",
         opties=["het post-conventionele",
                 "het pre-conventionele stadium",
                 "het conventionele stadium",
                 "het sensomotorische stadium"],
         antwoord=0,
         uitleg="De wet wordt niet zomaar gevolgd maar afgewogen tegen een hoger beginsel."),
    dict(type="invultekst",
         vraag="Welk stadium hoort bij wie regels volgt omdat het zo hoort? Vul in: het ... stadium",
         antwoord=["conventioneel", "conventionele"],
         uitleg="Het conventionele stadium. Conventies zijn afspraken, regels en gewoontes."),
    dict(type="meerkeuze",
         vraag="Twee mensen stelen niet. De een uit angst voor de politie, de ander omdat hij eerlijkheid belangrijk vindt. Wat is juist?",
         opties=["ze zitten in een ander stadium",
                 "ze zitten in hetzelfde stadium",
                 "geen van beide heeft een stadium",
                 "het stadium hangt van de buit af"],
         antwoord=0,
         uitleg="Dezelfde daad, een andere reden. De eerste is pre-conventioneel, de tweede post-conventioneel."),
    dict(type="waarofniet",
         vraag="Het post-conventionele stadium betekent dat je alle regels mag overtreden.",
         antwoord=False,
         uitleg="Het betekent dat je een regel kan afwegen tegen een beginsel, niet dat regels er niet meer toe doen."),
    dict(type="meerkeuze",
         vraag="Waarom hoort het post-conventionele stadium niet bij een kind?",
         opties=["het vraagt abstract denken",
                 "het vraagt veel geduld",
                 "het vraagt een goed geheugen",
                 "het vraagt een rijpe motoriek"],
         antwoord=0,
         uitleg="Over een beginsel redeneren vraagt het formeel-operationele denken van Piaget, dus vanaf de adolescentie."),
    dict(type="meerkeuze",
         vraag="Een meisje helpt haar zus omdat ze vindt dat je familie helpt. Welk stadium is dat?",
         opties=["het conventionele",
                 "het pre-conventionele stadium",
                 "het post-conventionele stadium",
                 "het pre-operationele stadium"],
         antwoord=0,
         uitleg="Zo hoort het in een gezin: ze volgt de verwachting van haar rol. Dat is conventioneel."),
    dict(type="waarofniet",
         vraag="Kohlberg vond dat je het stadium afleest uit de daad en niet uit de uitleg.",
         antwoord=False,
         uitleg="Precies omgekeerd. De daad zegt niets, de redenering erachter wel."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken horen bij het post-conventionele stadium?",
         opties=["een wet kan onrechtvaardig zijn",
                 "menselijke waardigheid gaat voor",
                 "regels zijn afspraken die je kan wegen",
                 "ik doe het omdat het nu eenmaal zo hoort"],
         antwoord=[0, 1, 2],
         uitleg="De eerste drie wegen een beginsel af tegen de regel. De laatste zin is conventioneel."),
    dict(type="meerkeuze",
         vraag="Wat leert de vakfiche over de orde van de stadia?",
         opties=["ze volgen elkaar vast op",
                 "je kan er eentje overslaan",
                 "je kiest zelf de volgorde",
                 "de orde verschilt per cultuur"],
         antwoord=0,
         uitleg="Zoals bij Piaget ligt de orde vast en het tempo niet. Een stadium overslaan kan niet."),
    dict(type="waarofniet",
         vraag="Een volwassene kan in een lastige situatie terugvallen op een lager stadium.",
         antwoord=True,
         uitleg="Onder druk of angst gaat het eigen gevolg vaak weer voorop. Dat maakt de theorie niet minder bruikbaar."),
    dict(type="meerkeuze",
         vraag="Waarom is het conventionele stadium nuttig voor een samenleving?",
         opties=["de meeste mensen volgen de regels",
                 "iedereen denkt dan hetzelfde",
                 "er is dan geen wet meer nodig",
                 "er is dan geen straf meer nodig"],
         antwoord=0,
         uitleg="Een samenleving werkt doordat mensen zich aan afspraken houden, ook zonder toezicht."),
    dict(type="meerkeuze",
         vraag="Een adolescent begint de regels van thuis in vraag te stellen. Wat gebeurt er?",
         opties=["hij groeit naar een volgend stadium",
                 "hij valt terug naar straf en beloning",
                 "hij verliest zijn morele besef",
                 "hij blijft in hetzelfde stadium staan"],
         antwoord=0,
         uitleg="Een regel bevragen hoort bij de overgang van het conventionele naar het post-conventionele denken."),
    dict(type="invultekst",
         vraag="Hoe heet het bekendste dilemma van Kohlberg? Eén naam.",
         antwoord=["Heinz", "heinz", "dilemma van Heinz"],
         uitleg="Het dilemma van Heinz: een man steelt een duur medicijn voor zijn doodzieke vrouw."),
    dict(type="meerkeuze",
         vraag="Waarom is de theorie van Kohlberg bekritiseerd?",
         opties=["ze weegt rechtvaardigheid het zwaarst",
                 "ze heeft veel te veel stadia na elkaar",
                 "ze kijkt enkel naar jonge kinderen",
                 "ze meet enkel het gedrag van buitenaf"],
         antwoord=0,
         uitleg="Critici zoals Gilligan vinden dat zorgen voor elkaar even zwaar weegt als rechtvaardigheid."),
]
