# -*- coding: utf-8 -*-
"""Socialisatie: wat ze is, waarvoor ze dient en in welke vormen.

Van de vakfiche sociale en gedragswetenschappen (2DO, 2027): het begrip
socialisatie, het belang ervan voor het individu en voor de samenleving, de
drie niveaus (primair, secundair, tertiair) en de vormen acculturatie,
anticiperende socialisatie en enculturatie.

Deel 1 zijn het begrip en het belang.
Deel 2 zijn de niveaus en de vormen.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is socialisatie?",
         opties=["cultuur leren en doorgeven",
                 "vrienden maken in een groep",
                 "je aanpassen aan een wet",
                 "lid worden van een vereniging"],
         antwoord=0,
         uitleg="Waarden, normen en andere cultuuruitingen worden doorgegeven en overgenomen."),
    dict(type="meerkeuze",
         vraag="Wat wordt er volgens de vakfiche doorgegeven bij socialisatie?",
         opties=["waarden",
                 "normen",
                 "andere cultuuruitingen",
                 "erfelijke aanleg"],
         antwoord=[0, 1, 2],
         uitleg="Drie dingen. Erfelijke aanleg krijg je mee bij de geboorte, die wordt niet aangeleerd."),
    dict(type="invultekst",
         vraag="Welk begrip is het doorgeven van waarden en normen? Eén woord.",
         antwoord=["socialisatie", "de socialisatie"],
         uitleg="Socialisatie loopt het hele leven door, niet enkel in de kindertijd."),
    dict(type="meerkeuze",
         vraag="Wat levert socialisatie op voor het individu?",
         opties=["aanpassing aan de omgeving",
                 "een hoger inkomen",
                 "een betere gezondheid",
                 "een vaste sociale positie"],
         antwoord=0,
         uitleg="Je leert wat kan en wat niet, zodat je in je omgeving kan functioneren."),
    dict(type="waarofniet",
         vraag="Socialisatie zorgt er volgens de vakfiche voor dat een cultuur blijft bestaan.",
         antwoord=True,
         uitleg="Dat is het belang voor de samenleving: zonder doorgeven sterft een cultuur met haar dragers."),
    dict(type="meerkeuze",
         vraag="Wat is prosociaal gedrag?",
         opties=["gedrag dat anderen helpt",
                 "gedrag dat de wet volgt",
                 "gedrag dat opvalt in een groep",
                 "gedrag dat anderen nadoet"],
         antwoord=0,
         uitleg="Delen, helpen, troosten. Het is een gevolg van geslaagde socialisatie."),
    dict(type="meerkeuze",
         vraag="Welke gevolgen van socialisatie voor het individu noemt de fiche?",
         opties=["aanpassing aan de omgeving",
                 "prosociaal gedrag",
                 "antisociaal gedrag",
                 "een hogere intelligentie"],
         antwoord=[0, 1, 2],
         uitleg="Aanpassing, met prosociaal gedrag als gunstige en antisociaal gedrag als ongunstige kant."),
    dict(type="invultekst",
         vraag="Hoe noem je gedrag dat ingaat tegen de normen van een groep? Eén woord.",
         antwoord=["antisociaal", "antisociaal gedrag"],
         uitleg="Antisociaal gedrag schaadt anderen. Het tegengestelde is prosociaal gedrag."),
    dict(type="meerkeuze",
         vraag="Een kind leert thuis dat je dankjewel zegt. Wat gebeurt hier?",
         opties=["socialisatie",
                 "rijping van het gedrag",
                 "groei van het lichaam",
                 "erfelijkheid van het karakter"],
         antwoord=0,
         uitleg="Een norm wordt doorgegeven in het gezin. Dat is de kern van socialisatie."),
    dict(type="waarofniet",
         vraag="Socialisatie stopt volgens de vakfiche na de kindertijd.",
         antwoord=False,
         uitleg="Ze loopt door: een nieuwe job, een nieuw land of een nieuwe rol vraagt telkens nieuwe normen."),
    dict(type="meerkeuze",
         vraag="Waarom is socialisatie nodig voor een samenleving?",
         opties=["anders verdwijnen de afspraken",
                 "anders verdwijnt de wet",
                 "anders groeit de bevolking niet",
                 "anders verdwijnt de taal direct"],
         antwoord=0,
         uitleg="Een samenleving leeft van gedeelde waarden en normen. Elke generatie moet ze opnieuw leren."),
    dict(type="meerkeuze",
         vraag="Wat betekent het dat socialisatie tweerichtingsverkeer is?",
         opties=["ook jongeren geven iets door",
                 "iedereen leert hetzelfde",
                 "de wet werkt in twee richtingen",
                 "het gaat even snel in beide zin"],
         antwoord=0,
         uitleg="Kinderen leren hun ouders bijvoorbeeld werken met nieuwe toestellen. Doorgeven gaat niet enkel naar beneden."),
    dict(type="waarofniet",
         vraag="Een kind neemt alles over wat het via socialisatie meekrijgt.",
         antwoord=False,
         uitleg="Het kiest en weegt, zeker in de adolescentie. Daarom verandert een cultuur ook."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over socialisatie kloppen?",
         opties=["ze duurt een leven lang",
                 "ze gaat via meer dan één groep",
                 "ze geeft cultuur door",
                 "ze is erfelijk bepaald"],
         antwoord=[0, 1, 2],
         uitleg="De eerste drie staan in de fiche. Socialisatie is juist het tegengestelde van erfelijk."),
    dict(type="meerkeuze",
         vraag="Iemand verhuist naar een ander land en leert daar hoe het eraan toegaat. Wat gebeurt hier?",
         opties=["socialisatie op latere leeftijd",
                 "rijping van het gedrag",
                 "erfelijke aanpassing",
                 "een verandering van karakter"],
         antwoord=0,
         uitleg="Socialisatie is niet aan een leeftijd gebonden. Hier gaat het bovendien om acculturatie."),
    dict(type="waarofniet",
         vraag="Prosociaal gedrag is volgens de vakfiche een gevolg van socialisatie.",
         antwoord=True,
         uitleg="Wie geleerd heeft wat de groep verwacht, helpt en deelt. Mislukt dat, dan ligt antisociaal gedrag dichterbij."),
    dict(type="meerkeuze",
         vraag="Waarom verschilt socialisatie per gezin?",
         opties=["elk gezin heeft eigen waarden",
                 "elk gezin heeft dezelfde wet",
                 "elk gezin heeft dezelfde taal",
                 "elk gezin heeft dezelfde school"],
         antwoord=0,
         uitleg="Binnen dezelfde cultuur legt het ene gezin de nadruk op zelfstandigheid, het andere op samen zijn."),
    dict(type="meerkeuze",
         vraag="Wat is het verschil tussen socialisatie en opvoeding?",
         opties=["socialisatie is breder",
                 "opvoeding is breder",
                 "ze betekenen hetzelfde",
                 "opvoeding duurt langer"],
         antwoord=0,
         uitleg="Opvoeding is bewust en gericht; socialisatie gebeurt ook ongemerkt, via vrienden, media en de buurt."),
    dict(type="invultekst",
         vraag="Hoe noem je gedrag dat anderen helpt? Eén woord.",
         antwoord=["prosociaal", "prosociaal gedrag"],
         uitleg="Prosociaal gedrag: delen, helpen en troosten."),
    dict(type="meerkeuze",
         vraag="Waarom hoort cultuur in de fiche samen met socialisatie?",
         opties=["socialisatie geeft cultuur door",
                 "cultuur is een soort socialisatie",
                 "ze betekenen hetzelfde",
                 "cultuur vervangt socialisatie"],
         antwoord=0,
         uitleg="Cultuur is wat doorgegeven wordt, socialisatie is hoe dat gebeurt."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Welk niveau van socialisatie speelt in het gezin?",
         opties=["de primaire socialisatie",
                 "de secundaire socialisatie",
                 "de tertiaire socialisatie",
                 "de anticiperende socialisatie"],
         antwoord=0,
         uitleg="De primaire socialisatie is de eerste en de diepste: ze legt de basis in de vroege kindertijd."),
    dict(type="meerkeuze",
         vraag="Welke niveaus van socialisatie noemt de vakfiche?",
         opties=["primair",
                 "secundair",
                 "tertiair",
                 "finaal"],
         antwoord=[0, 1, 2],
         uitleg="Drie niveaus. Een finale socialisatie bestaat niet als term."),
    dict(type="invultekst",
         vraag="Welk niveau van socialisatie speelt op school? Eén woord.",
         antwoord=["secundair", "secundaire"],
         uitleg="De secundaire socialisatie: school, vrienden en werk, buiten het gezin."),
    dict(type="meerkeuze",
         vraag="Welk niveau hoort bij de media?",
         opties=["de tertiaire socialisatie",
                 "de primaire socialisatie",
                 "de secundaire socialisatie",
                 "de anticiperende socialisatie"],
         antwoord=0,
         uitleg="De tertiaire socialisatie loopt via media en andere kanalen zonder rechtstreeks contact."),
    dict(type="waarofniet",
         vraag="De primaire socialisatie is volgens de vakfiche de diepste.",
         antwoord=True,
         uitleg="Wat je in je eerste jaren leert, voelt later als vanzelfsprekend. Daarom weegt ze het zwaarst."),
    dict(type="meerkeuze",
         vraag="Wat is acculturatie?",
         opties=["gewoontes overnemen",
                 "de eigen cultuur volledig verliezen",
                 "een nieuwe cultuur uitvinden",
                 "een cultuur opleggen aan anderen"],
         antwoord=0,
         uitleg="Het gebeurt bij contact tussen culturen, bijvoorbeeld na een verhuis of door migratie."),
    dict(type="meerkeuze",
         vraag="Welke vormen van socialisatie noemt de vakfiche?",
         opties=["acculturatie",
                 "anticiperende socialisatie",
                 "enculturatie",
                 "collectivisatie"],
         antwoord=[0, 1, 2],
         uitleg="Drie vormen. Collectivisatie hoort niet in deze lijst thuis."),
    dict(type="invultekst",
         vraag="Hoe noem je het opgroeien in je eigen cultuur? Eén woord.",
         antwoord=["enculturatie"],
         uitleg="Enculturatie is de cultuur van je eigen groep binnenkrijgen, zonder dat je het merkt."),
    dict(type="meerkeuze",
         vraag="Een student leest alles over een job die hij later wil doen. Welke vorm is dat?",
         opties=["anticiperende socialisatie",
                 "acculturatie van een groep",
                 "enculturatie van een groep",
                 "primaire socialisatie"],
         antwoord=0,
         uitleg="Hij neemt de normen van een rol over nog voor hij die rol heeft. Dat is anticiperen."),
    dict(type="waarofniet",
         vraag="Enculturatie en acculturatie betekenen volgens de vakfiche hetzelfde.",
         antwoord=False,
         uitleg="Enculturatie is je eigen cultuur binnenkrijgen, acculturatie is een andere cultuur overnemen."),
    dict(type="meerkeuze",
         vraag="Een gezin uit Marokko viert in België Sinterklaas mee. Welke vorm is dat?",
         opties=["acculturatie",
                 "enculturatie",
                 "anticiperende socialisatie",
                 "primaire socialisatie"],
         antwoord=0,
         uitleg="Gewoontes van de nieuwe omgeving komen erbij. Acculturatie betekent niet dat de eigen cultuur verdwijnt."),
    dict(type="meerkeuze",
         vraag="Waarom noemt men de school secundaire socialisatie?",
         opties=["ze komt na het gezin",
                 "ze is minder belangrijk",
                 "ze duurt korter",
                 "ze is minder diep"],
         antwoord=0,
         uitleg="Secundair betekent hier tweede in de tijd, niet tweederangs."),
    dict(type="waarofniet",
         vraag="De drie niveaus van socialisatie kunnen tegelijk werken.",
         antwoord=True,
         uitleg="Een tiener krijgt thuis, op school en via zijn gsm tegelijk boodschappen. Die spreken elkaar soms tegen."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over anticiperende socialisatie kloppen?",
         opties=["ze gaat over een toekomstige rol",
                 "ze gebeurt voor de rol begint",
                 "ze maakt de overgang makkelijker",
                 "ze gebeurt altijd in het gezin"],
         antwoord=[0, 1, 2],
         uitleg="Ze gebeurt net zo goed via vrienden, stages of media. Het gezin is er niet voor nodig."),
    dict(type="meerkeuze",
         vraag="Een kind doet zijn oudere broer na die naar het middelbaar gaat. Welke vorm is dat?",
         opties=["anticiperende socialisatie",
                 "acculturatie van een groep",
                 "enculturatie van een groep",
                 "tertiaire socialisatie"],
         antwoord=0,
         uitleg="Hij oefent een rol die hij nog niet heeft. Zo wordt de overgang later minder groot."),
    dict(type="waarofniet",
         vraag="Tertiaire socialisatie vraagt rechtstreeks contact met mensen.",
         antwoord=False,
         uitleg="Juist niet: ze loopt via media en andere kanalen op afstand. Daarin verschilt ze van de eerste twee niveaus."),
    dict(type="meerkeuze",
         vraag="Waarom kan socialisatie tot spanning leiden bij jongeren?",
         opties=["de niveaus spreken elkaar tegen",
                 "er is maar één niveau",
                 "de school geeft geen normen",
                 "het gezin geeft geen normen"],
         antwoord=0,
         uitleg="Thuis geldt iets anders dan in de vriendengroep of online. De jongere moet daar zelf een weg in vinden."),
    dict(type="meerkeuze",
         vraag="Wat gebeurt er met de rol van instituties doorheen de tijd?",
         opties=["ze verschuift",
                 "ze blijft altijd gelijk",
                 "ze verdwijnt volledig",
                 "ze wordt wettelijk vastgelegd"],
         antwoord=0,
         uitleg="De kerk had vroeger veel meer invloed, de media veel minder. De fiche vraagt die verschuiving uit te leggen."),
    dict(type="invultekst",
         vraag="Welke vorm van socialisatie bereidt je voor op een rol die nog komt? Eén woord.",
         antwoord=["anticiperend", "anticiperende", "anticiperende socialisatie"],
         uitleg="Anticiperende socialisatie: je neemt de normen van een rol over voor je ze hebt."),
    dict(type="meerkeuze",
         vraag="Waarom verschilt de socialisatie van een tiener nu van die van zijn grootouders?",
         opties=["de instituties zijn verschoven",
                 "de levensfasen zijn veranderd",
                 "de erfelijkheid is veranderd",
                 "de rijping is veranderd"],
         antwoord=0,
         uitleg="Media wegen zwaarder, de kerk minder, en school duurt langer. De fiche noemt dat verandering in tijd en ruimte."),
]
