# -*- coding: utf-8 -*-
"""Het zelfconcept en de invloed ervan op het gedrag.

Van de vakfiche sociale en gedragswetenschappen (2DO, 2027): zelfbeeld,
zelfwaardering, self-efficacy en body-image, met telkens hun invloed op het
gedrag, en de vier soorten zelfbeeld.

Deel 1 zijn het zelfconcept en het zelfbeeld.
Deel 2 zijn zelfwaardering, self-efficacy en body-image.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Welke delen horen bij het zelfconcept?",
         opties=["het zelfbeeld",
                 "de zelfwaardering",
                 "de self-efficacy",
                 "het temperament"],
         antwoord=[0, 1, 2],
         uitleg="Vier delen: zelfbeeld, zelfwaardering, self-efficacy en body-image. Temperament hoort bij de persoonlijkheid."),
    dict(type="meerkeuze",
         vraag="Wat is het zelfbeeld?",
         opties=["wat je denkt dat je bent",
                 "wat je waard vindt dat je bent",
                 "wat je denkt te kunnen",
                 "wat je van je lichaam vindt"],
         antwoord=0,
         uitleg="Het zelfbeeld beschrijft: ik ben verlegen, ik ben goed in tekenen. Of je dat goed vindt, is zelfwaardering."),
    dict(type="invultekst",
         vraag="Welk deel van het zelfconcept gaat over je lichaam? Twee woorden, in het Engels.",
         antwoord=["body image", "body-image"],
         uitleg="Het body-image: hoe je over je eigen lichaam denkt en voelt."),
    dict(type="meerkeuze",
         vraag="Welke soorten zelfbeeld noemt de vakfiche?",
         opties=["positief zelfbeeld",
                 "negatief zelfbeeld",
                 "vertekend zelfbeeld",
                 "geleend zelfbeeld"],
         antwoord=[0, 1, 2],
         uitleg="Vier soorten: positief, negatief, vertekend en realistisch. Een geleend zelfbeeld bestaat niet."),
    dict(type="waarofniet",
         vraag="Een vertekend zelfbeeld kan zowel onderschatting als overschatting zijn.",
         antwoord=True,
         uitleg="Beide kanten wijken af van de werkelijkheid. Allebei geven ze problemen."),
    dict(type="meerkeuze",
         vraag="Iemand kan goed rekenen maar zegt dat hij er niets van kan. Welk zelfbeeld is dat?",
         opties=["vertekend zelfbeeld",
                 "realistisch zelfbeeld",
                 "positief zelfbeeld",
                 "neutraal zelfbeeld"],
         antwoord=0,
         uitleg="Vertekend door onderschatting. Het beeld klopt niet met wat hij werkelijk kan."),
    dict(type="meerkeuze",
         vraag="Iemand weet waar hij goed in is en waar niet. Welk zelfbeeld is dat?",
         opties=["realistisch zelfbeeld",
                 "vertekend zelfbeeld",
                 "negatief zelfbeeld",
                 "neutraal zelfbeeld"],
         antwoord=0,
         uitleg="Een realistisch zelfbeeld klopt met de werkelijkheid. Dat is niet hetzelfde als een positief zelfbeeld."),
    dict(type="invultekst",
         vraag="Hoe noem je het beeld dat niet klopt met de werkelijkheid? Eén woord.",
         antwoord=["vertekend", "vertekend zelfbeeld"],
         uitleg="Een vertekend zelfbeeld, door onderschatting of door overschatting."),
    dict(type="meerkeuze",
         vraag="Een leerling met een negatief zelfbeeld geeft bij een moeilijke oefening snel op. Wat zie je?",
         opties=["de invloed op het gedrag",
                 "de invloed op het lichaam",
                 "de invloed op de kennis",
                 "de invloed op de regels"],
         antwoord=0,
         uitleg="Het zelfbeeld stuurt wat je durft proberen. Juist daarom vraagt de fiche naar die invloed."),
    dict(type="waarofniet",
         vraag="Het zelfconcept ligt volgens de vakfiche van jongs af vast.",
         antwoord=False,
         uitleg="Het groeit in contact met anderen en kan veranderen, al gaat dat traag."),
    dict(type="meerkeuze",
         vraag="Waar komt het zelfbeeld van een kind vooral vandaan?",
         opties=["uit reacties van anderen",
                 "uit zijn erfelijke aanleg",
                 "uit zijn eigen lichaam",
                 "uit zijn schoolresultaten"],
         antwoord=0,
         uitleg="Een kind leest in de ogen van anderen wie het is. Daarom wegen opmerkingen van ouders en leerkrachten zwaar."),
    dict(type="meerkeuze",
         vraag="Iemand denkt dat hij alles kan en bereidt zich niet voor. Welk zelfbeeld is dat?",
         opties=["vertekend door overschatting",
                 "realistisch en positief",
                 "negatief en vertekend",
                 "realistisch maar negatief"],
         antwoord=0,
         uitleg="Ook overschatting is vertekend. Het leidt tot te weinig voorbereiding en dus tot ontgoocheling."),
    dict(type="waarofniet",
         vraag="Een positief zelfbeeld is altijd hetzelfde als een realistisch zelfbeeld.",
         antwoord=False,
         uitleg="Positief kan ook te positief zijn. Realistisch betekent dat het beeld klopt, niet dat het gunstig is."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over het zelfbeeld kloppen?",
         opties=["het beschrijft wie je denkt te zijn",
                 "het stuurt je gedrag",
                 "het groeit in contact met anderen",
                 "het is bij iedereen realistisch"],
         antwoord=[0, 1, 2],
         uitleg="De eerste drie staan in de fiche. Een vertekend zelfbeeld laat zien dat de vierde niet klopt."),
    dict(type="meerkeuze",
         vraag="In welke fase verandert het zelfbeeld het sterkst?",
         opties=["de adolescentie",
                 "de babytijd",
                 "de peutertijd",
                 "de midden volwassenheid"],
         antwoord=0,
         uitleg="De jongere vergelijkt zich volop met anderen en zoekt wie hij is. Daarom schommelt het beeld dan het meest."),
    dict(type="waarofniet",
         vraag="Het zelfbeeld van een kleuter is vaak te positief.",
         antwoord=True,
         uitleg="Een kleuter denkt dat hij alles kan. Pas in de lagere school gaat hij zich met anderen vergelijken."),
    dict(type="meerkeuze",
         vraag="Waarom hoort het zelfconcept bij persoonlijkheid en gedrag?",
         opties=["het stuurt wat je doet",
                 "het bepaalt je temperament",
                 "het bepaalt je karakter",
                 "het bepaalt je afkomst"],
         antwoord=0,
         uitleg="Wat je van jezelf denkt, bepaalt wat je probeert en wat je uit de weg gaat."),
    dict(type="meerkeuze",
         vraag="Een jongere laat zich niet meer zien in de turnles. Welk deel van het zelfconcept speelt hier?",
         opties=["het body-image",
                 "de self-efficacy",
                 "de zelfwaardering",
                 "het realistische zelfbeeld"],
         antwoord=0,
         uitleg="Hoe je over je lichaam denkt, stuurt hier het gedrag. Vaak hangt er ook zelfwaardering aan vast."),
    dict(type="invultekst",
         vraag="Hoe noem je het geheel van zelfbeeld, zelfwaardering, self-efficacy en body-image? Eén woord.",
         antwoord=["zelfconcept", "het zelfconcept"],
         uitleg="Het zelfconcept is het hele beeld dat je van jezelf hebt."),
    dict(type="meerkeuze",
         vraag="Waarom helpt het om een kind te prijzen voor zijn inzet en niet voor zijn talent?",
         opties=["inzet kan het zelf sturen",
                 "talent is niet belangrijk",
                 "inzet is makkelijker te zien",
                 "talent verandert te snel"],
         antwoord=0,
         uitleg="Wie geprezen wordt om inzet, leert dat hij iets kan veranderen. Dat versterkt de self-efficacy."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is zelfwaardering?",
         opties=["hoeveel je jezelf waard vindt",
                 "wat je denkt dat je bent",
                 "wat je denkt te kunnen",
                 "wat je van je lichaam vindt"],
         antwoord=0,
         uitleg="Het zelfbeeld beschrijft, de zelfwaardering beoordeelt. Dat zijn twee verschillende dingen."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over self-efficacy kloppen?",
         opties=["het is geloof dat je iets kan",
                 "het verschilt per taak",
                 "het groeit door te slagen",
                 "het is hetzelfde als zelfwaardering"],
         antwoord=[0, 1, 2],
         uitleg="Self-efficacy is het vertrouwen dat je een bepaalde taak aankan. Zelfwaardering gaat over je waarde als persoon."),
    dict(type="invultekst",
         vraag="Hoe noem je het geloof dat je een taak aankan? Twee woorden, in het Engels.",
         antwoord=["self efficacy", "self-efficacy"],
         uitleg="Self-efficacy, een begrip van Bandura. Het is taakgebonden, niet algemeen."),
    dict(type="meerkeuze",
         vraag="Een leerling durft een moeilijke oefening aan omdat het vorige keer lukte. Wat zie je?",
         opties=["een hoge self-efficacy",
                 "een hoge zelfwaardering",
                 "een positief body-image",
                 "een realistisch zelfbeeld"],
         antwoord=0,
         uitleg="Een eerdere ervaring van slagen is de sterkste bron van self-efficacy."),
    dict(type="waarofniet",
         vraag="Self-efficacy kan hoog zijn voor het ene vak en laag voor het andere.",
         antwoord=True,
         uitleg="Ze is taakgebonden. Iemand kan vol vertrouwen zijn in taal en bang zijn voor wiskunde."),
    dict(type="meerkeuze",
         vraag="Welke invloed heeft een lage zelfwaardering op het gedrag?",
         opties=["minder durven proberen",
                 "meer risico's nemen",
                 "sneller beslissen",
                 "meer hulp aanbieden"],
         antwoord=0,
         uitleg="Wie zichzelf weinig waard vindt, stelt zich minder bloot aan de kans om te falen."),
    dict(type="meerkeuze",
         vraag="Welke bronnen voeden de self-efficacy?",
         opties=["eerder zelf geslaagd zijn",
                 "iemand anders zien slagen",
                 "aanmoediging krijgen",
                 "je lengte en gewicht"],
         antwoord=[0, 1, 2],
         uitleg="Eigen ervaring weegt het zwaarst, daarna het voorbeeld van anderen en de aanmoediging."),
    dict(type="invultekst",
         vraag="Welk deel van het zelfconcept beoordeelt of je jezelf waard vindt? Eén woord.",
         antwoord=["zelfwaardering", "de zelfwaardering"],
         uitleg="De zelfwaardering. Het zelfbeeld beschrijft alleen."),
    dict(type="meerkeuze",
         vraag="Wat is body-image?",
         opties=["hoe je over je lichaam denkt",
                 "hoe je lichaam er echt uitziet",
                 "hoe gezond je lichaam is",
                 "hoe sterk je lichaam is"],
         antwoord=0,
         uitleg="Het is een beeld in je hoofd, en dat kan ver van de werkelijkheid liggen."),
    dict(type="waarofniet",
         vraag="Het body-image van iemand klopt altijd met hoe zijn lichaam er werkelijk uitziet.",
         antwoord=False,
         uitleg="Het kan sterk vertekend zijn. Dat speelt onder meer bij eetstoornissen."),
    dict(type="meerkeuze",
         vraag="Waarom staat het body-image in de adolescentie onder druk?",
         opties=["het lichaam verandert snel",
                 "het lichaam groeit niet meer",
                 "de zelfwaardering verdwijnt",
                 "de self-efficacy verdwijnt"],
         antwoord=0,
         uitleg="Een snel veranderend lichaam, plus het vergelijken met leeftijdsgenoten en met beelden online."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over zelfwaardering kloppen?",
         opties=["ze beoordeelt jezelf",
                 "ze stuurt wat je durft",
                 "ze kan schommelen",
                 "ze is per taak verschillend"],
         antwoord=[0, 1, 2],
         uitleg="Per taak verschillend is juist de self-efficacy. De zelfwaardering is algemener."),
    dict(type="waarofniet",
         vraag="Een hoge self-efficacy helpt om door te zetten bij tegenslag.",
         antwoord=True,
         uitleg="Wie gelooft dat het kan lukken, probeert langer door. Dat is het grote nut van self-efficacy."),
    dict(type="meerkeuze",
         vraag="Een jongere eet nauwelijks omdat ze zichzelf te zwaar vindt terwijl ze mager is. Wat speelt hier?",
         opties=["een vertekend body-image",
                 "een hoge self-efficacy",
                 "een hoge zelfwaardering",
                 "een realistisch zelfbeeld"],
         antwoord=0,
         uitleg="Het beeld in haar hoofd klopt niet met haar lichaam. Dat is een vertekend body-image."),
    dict(type="meerkeuze",
         vraag="Hoe kan een leerkracht de self-efficacy van een leerling verhogen?",
         opties=["kleine haalbare stappen geven",
                 "steeds moeilijkere taken geven",
                 "minder feedback op het werk geven",
                 "meer toetsen in een week afnemen"],
         antwoord=0,
         uitleg="Elke gelukte stap is een ervaring van slagen, en die voedt het vertrouwen het sterkst."),
    dict(type="waarofniet",
         vraag="Zelfwaardering en self-efficacy betekenen volgens de vakfiche hetzelfde.",
         antwoord=False,
         uitleg="Zelfwaardering gaat over je waarde als persoon, self-efficacy over of je een taak aankan."),
    dict(type="meerkeuze",
         vraag="Waarom beïnvloeden sociale media het zelfconcept van jongeren?",
         opties=["ze vergelijken zich met beelden",
                 "ze lezen er minder door",
                 "ze slapen er slechter door",
                 "ze bewegen er minder door"],
         antwoord=0,
         uitleg="Het gaat hier om de vergelijking: bewerkte beelden worden de maatstaf voor het eigen lichaam."),
    dict(type="meerkeuze",
         vraag="Een man van 60 vindt zichzelf waardevol ondanks een mislukt project. Wat zie je?",
         opties=["een stevige zelfwaardering",
                 "een hoge self-efficacy",
                 "een positief body-image",
                 "een vertekend zelfbeeld"],
         antwoord=0,
         uitleg="Zijn waarde als persoon hangt niet aan één resultaat. Dat is een stevige zelfwaardering."),
    dict(type="invultekst",
         vraag="Welk deel van het zelfconcept is taakgebonden? Twee woorden, in het Engels.",
         antwoord=["self efficacy", "self-efficacy"],
         uitleg="Self-efficacy verschilt per taak: hoog voor koken, laag voor spreken in het openbaar."),
    dict(type="meerkeuze",
         vraag="Waarom vraagt de vakfiche telkens naar de invloed op het gedrag?",
         opties=["het stuurt wat je doet",
                 "het is heel goed meetbaar",
                 "het ligt vanaf de geboorte vast",
                 "het is volledig erfelijk bepaald"],
         antwoord=0,
         uitleg="Het blijft niet in je hoofd: het bepaalt wat je probeert, vermijdt en volhoudt."),
]
