# -*- coding: utf-8 -*-
"""Het functiebegrip en de eerstegraadsfunctie.

Van de vakfiche wiskunde 2DOB (2027): het begrip functie met domein, beeld en
nulwaarde, de vier voorstellingswijzen (woorden, tabel, grafiek, voorschrift),
en de eerstegraadsfunctie met haar richtingscoëfficiënt, haar snijpunt met de
y-as en het verband met recht evenredige grootheden.

Deel 1 is het functiebegrip en het lezen van een grafiek.
Deel 2 is de eerstegraadsfunctie.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is een functie?",
         opties=["elke x krijgt juist een y",
                 "elke y krijgt meerdere x ervan",
                 "x en y hangen niet samen",
                 "er zijn altijd twee beelden"],
         antwoord=0,
         uitleg="Een verband waarbij elk getal uit het domein precies één beeld heeft."),
    dict(type="meerkeuze",
         vraag="Hoe noem je f(3) bij een functie f?",
         opties=["het beeld van 3",
                 "het domein van 3",
                 "de nulwaarde ervan",
                 "de richtingscoëfficiënt"],
         antwoord=0,
         uitleg="f(3) is het beeld van 3, dus de y-waarde die bij x is 3 hoort."),
    dict(type="meerkeuze",
         vraag="Hoe kan je een functie voorstellen?",
         opties=["met een woordelijke beschrijving",
                 "met een tabel",
                 "met een grafiek",
                 "met een alfabetische lijst"],
         antwoord=[0, 1, 2],
         uitleg="In woorden, in een tabel, in een grafiek of met een voorschrift."),
    dict(type="meerkeuze",
         vraag="Wat is het domein van een functie?",
         opties=["alle x-waarden die mogen",
                 "alle y-waarden die eruit komen",
                 "enkel de positieve getallen",
                 "het punt waar de grafiek nul is"],
         antwoord=0,
         uitleg="Het domein is de verzameling x-waarden waarvoor de functie bestaat."),
    dict(type="meerkeuze",
         vraag="Wat is het bereik van een functie?",
         opties=["alle y-waarden die voorkomen",
                 "alle x-waarden die mogen, samen",
                 "de waarde van f in nul alleen",
                 "het snijpunt met de x-as"],
         antwoord=0,
         uitleg="Het bereik is wat er aan beelden uit de functie komt."),
    dict(type="waarofniet",
         vraag="Een verticale rechte mag de grafiek van een functie maar in één punt snijden.",
         antwoord=True,
         uitleg="Dat is de verticale-lijntest. Anders zou één x twee beelden hebben."),
    dict(type="invultekst",
         vraag="Hoe noem je de x-waarde waar de grafiek de x-as snijdt? Eén woord.",
         antwoord=["nulwaarde", "nulpunt"],
         uitleg="De nulwaarde. Daar is f(x) gelijk aan nul."),
    dict(type="meerkeuze",
         vraag="Voor f(x) is 2x plus 1, wat is f(4)?",
         opties=["9",
                 "8 in totaal",
                 "6 in totaal",
                 "12 in totaal"],
         antwoord=0,
         uitleg="2 maal 4 is 8, en 8 plus 1 is 9."),
    dict(type="waarofniet",
         vraag="Bij een functie kan één x-waarde twee verschillende beelden hebben.",
         antwoord=False,
         uitleg="Dan is het geen functie. Twee x-waarden met hetzelfde beeld mag wel."),
    dict(type="meerkeuze",
         vraag="Wat lees je af op de verticale as van een functiegrafiek?",
         opties=["het beeld",
                 "het domein ervan",
                 "de nulwaarde ervan",
                 "de eenheid van x"],
         antwoord=0,
         uitleg="Op de y-as staan de beelden, op de x-as de originelen."),
    dict(type="meerkeuze",
         vraag="Wat is het voordeel van een voorschrift boven een tabel?",
         opties=["je kan elke x invullen",
                 "je ziet de getallen meteen staan",
                 "je hoeft niet te rekenen ervoor",
                 "een tabel heeft geen eenheden"],
         antwoord=0,
         uitleg="Een tabel geeft enkel de waarden die erin staan, een voorschrift werkt voor elke x."),
    dict(type="meerkeuze",
         vraag="Welke gegevens kan je uit een functiegrafiek halen?",
         opties=["de nulwaarden",
                 "waar de functie stijgt",
                 "het hoogste punt",
                 "de naam van de onderzoeker"],
         antwoord=[0, 1, 2],
         uitleg="Nulwaarden, stijgen en dalen, extrema en het teken lees je rechtstreeks af."),
    dict(type="invultekst",
         vraag="Voor f(x) is x kwadraat, wat is f(min 3)? Een getal.",
         antwoord=["9", "negen"],
         uitleg="Min 3 in het kwadraat is 9. Een kwadraat is nooit negatief."),
    dict(type="meerkeuze",
         vraag="Wat betekent het als f(2) gelijk is aan 0?",
         opties=["2 is een nulwaarde",
                 "de functie bestaat niet in 2",
                 "het beeld van 0 is 2 ervan",
                 "de grafiek raakt de y-as daar"],
         antwoord=0,
         uitleg="De grafiek gaat door het punt (2, 0) en dus door de x-as."),
    dict(type="waarofniet",
         vraag="Twee verschillende x-waarden mogen hetzelfde beeld hebben.",
         antwoord=True,
         uitleg="Bij f(x) is x kwadraat hebben 2 en min 2 beide het beeld 4."),
    dict(type="waarofniet",
         vraag="Het domein van elke functie is heel de reële rechte.",
         antwoord=False,
         uitleg="Bij een breuk valt de waarde weg die de noemer nul maakt, bij een wortel de negatieve getallen."),
    dict(type="meerkeuze",
         vraag="Hoe schrijf je het punt met x is 1 en y is 5?",
         opties=["(1, 5)",
                 "(5, 1) in die orde",
                 "1 maal 5, als product",
                 "x1y5, aan elkaar"],
         antwoord=0,
         uitleg="Eerst de x, dan de y. De orde omwisselen geeft een ander punt."),
    dict(type="meerkeuze",
         vraag="Wat staat er in een tabel bij een functie?",
         opties=["een rij x met hun beeld",
                 "een lijst van alle domeinen",
                 "een grafiek in cijfers gezet",
                 "een formule zonder letters"],
         antwoord=0,
         uitleg="Boven de x-waarden, onder hun beelden. Handig, maar nooit volledig."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over het domein zijn juist?",
         opties=["het zijn de x-waarden",
                 "bij een breuk mag de noemer niet nul zijn",
                 "bij een wortel mag wat eronder staat niet negatief zijn",
                 "het domein is altijd eindig"],
         antwoord=[0, 1, 2],
         uitleg="Een domein is zelden eindig: meestal zijn het alle getallen op enkele uitzonderingen na."),
    dict(type="invultekst",
         vraag="Hoe noem je de x-waarde waarvan je het beeld neemt? Eén woord.",
         antwoord=["origineel", "argument"],
         uitleg="Het origineel. Zijn beeld is de bijhorende y-waarde."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is het voorschrift van een eerstegraadsfunctie?",
         opties=["f(x) is ax plus b",
                 "f(x) is ax kwadraat plus b",
                 "f(x) is a gedeeld door x",
                 "f(x) is b alleen, zonder x"],
         antwoord=0,
         uitleg="Met a niet gelijk aan nul. Haar grafiek is een rechte."),
    dict(type="meerkeuze",
         vraag="Welke vorm heeft de grafiek van een eerstegraadsfunctie?",
         opties=["een rechte",
                 "een parabool ervan",
                 "een hyperbool ervan",
                 "een cirkel rond nul"],
         antwoord=0,
         uitleg="Altijd een rechte. Daarom volstaan twee punten om ze te tekenen."),
    dict(type="meerkeuze",
         vraag="Wat zegt de richtingscoëfficiënt a?",
         opties=["hoe steil de rechte loopt",
                 "waar de rechte de y-as snijdt",
                 "hoe lang de rechte is ervan",
                 "hoeveel nulwaarden er zijn"],
         antwoord=0,
         uitleg="Ze geeft de stijging per stap van 1 naar rechts."),
    dict(type="meerkeuze",
         vraag="Wat betekent b in f(x) is ax plus b?",
         opties=["het beeld van 0",
                 "de stijging per stap ervan",
                 "de nulwaarde van de functie",
                 "de hoek met de x-as"],
         antwoord=0,
         uitleg="b is f(0), dus het snijpunt met de y-as."),
    dict(type="invultekst",
         vraag="Wat is de richtingscoëfficiënt van f(x) is 3x min 2? Een getal.",
         antwoord=["3", "drie"],
         uitleg="Drie. Per stap van 1 naar rechts gaat de rechte 3 omhoog."),
    dict(type="waarofniet",
         vraag="Een eerstegraadsfunctie met een negatieve richtingscoëfficiënt is dalend.",
         antwoord=True,
         uitleg="Bij elke stap naar rechts zakt de rechte. Het teken van a beslist."),
    dict(type="waarofniet",
         vraag="Een eerstegraadsfunctie kan twee nulwaarden hebben.",
         antwoord=False,
         uitleg="Een schuine rechte snijdt de x-as precies één keer."),
    dict(type="meerkeuze",
         vraag="Wanneer is een eerstegraadsfunctie stijgend?",
         opties=["als a positief is",
                 "als b positief is, altijd",
                 "als a gelijk is aan nul",
                 "als de nulwaarde positief is"],
         antwoord=0,
         uitleg="Het teken van a beslist. b schuift de rechte enkel op of neer."),
    dict(type="meerkeuze",
         vraag="Hoe bereken je de richtingscoëfficiënt uit twee punten?",
         opties=["het verschil in y door het verschil in x",
                 "het verschil in x door het verschil in y ervan",
                 "de som van de y-waarden, gedeeld door twee",
                 "het product van de twee x-waarden ervan"],
         antwoord=0,
         uitleg="De stijging gedeeld door de horizontale verplaatsing."),
    dict(type="meerkeuze",
         vraag="Wat is de richtingscoëfficiënt van de rechte door (0, 1) en (2, 7)?",
         opties=["3",
                 "6 in totaal",
                 "2 in totaal",
                 "0,5 in totaal"],
         antwoord=0,
         uitleg="7 min 1 is 6, en 6 gedeeld door 2 is 3."),
    dict(type="meerkeuze",
         vraag="Welke functies zijn van de eerste graad?",
         opties=["f(x) is 2x plus 5",
                 "f(x) is min x",
                 "f(x) is 0,5x min 3",
                 "f(x) is x kwadraat plus 1"],
         antwoord=[0, 1, 2],
         uitleg="De laatste is van de tweede graad: haar grafiek is een parabool."),
    dict(type="meerkeuze",
         vraag="Wat is de nulwaarde van f(x) is 2x min 6?",
         opties=["3",
                 "min 6 in totaal",
                 "6 in totaal",
                 "min 3 in totaal"],
         antwoord=0,
         uitleg="2x min 6 is 0 geeft 2x is 6, dus x is 3."),
    dict(type="meerkeuze",
         vraag="Wat is een recht evenredig verband?",
         opties=["f(x) is ax, met b nul",
                 "f(x) is ax plus b, met b niet nul",
                 "f(x) is a gedeeld door x ervan",
                 "f(x) is ax kwadraat ervan"],
         antwoord=0,
         uitleg="De grafiek gaat dan door de oorsprong: dubbel zoveel x geeft dubbel zoveel y."),
    dict(type="waarofniet",
         vraag="De grafiek van f(x) is ax gaat door de oorsprong.",
         antwoord=True,
         uitleg="f(0) is 0, dus het punt (0, 0) ligt op de rechte."),
    dict(type="waarofniet",
         vraag="Bij een omgekeerd evenredig verband is de grafiek een rechte.",
         antwoord=False,
         uitleg="Dat is een hyperbool. Daar blijft het product van x en y gelijk."),
    dict(type="invultekst",
         vraag="Wat is f(0) voor f(x) is min 2x plus 7? Een getal.",
         antwoord=["7", "zeven"],
         uitleg="Zeven. In nul blijft enkel b over."),
    dict(type="meerkeuze",
         vraag="Wat kan je uit f(x) is min 3x plus 4 meteen afleiden?",
         opties=["de functie is dalend",
                 "de grafiek snijdt de y-as in 4",
                 "de rechte zakt 3 per stap",
                 "de grafiek is een parabool"],
         antwoord=[0, 1, 2],
         uitleg="a is min 3 en b is 4. Een parabool hoort bij de tweede graad."),
    dict(type="meerkeuze",
         vraag="Hoe teken je de grafiek van een eerstegraadsfunctie het snelst?",
         opties=["twee punten en een lat",
                 "vijf punten en een kromme lijn",
                 "enkel de nulwaarde ervan",
                 "een tabel van tien waarden"],
         antwoord=0,
         uitleg="Twee punten bepalen een rechte. Een derde punt is een handige controle."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over de richtingscoëfficiënt zijn juist?",
         opties=["positief betekent stijgend",
                 "negatief betekent dalend",
                 "nul geeft een horizontale rechte",
                 "ze geeft het snijpunt met de y-as"],
         antwoord=[0, 1, 2],
         uitleg="Het snijpunt met de y-as is b, niet a."),
    dict(type="invultekst",
         vraag="Wat is de nulwaarde van f(x) is x plus 5? Een getal.",
         antwoord=["-5", "min 5", "min vijf"],
         uitleg="x plus 5 is 0 geeft x is min 5."),
]
