# -*- coding: utf-8 -*-
"""Gelijkvormigheid en schaalverandering.

Van de vakfiche wiskunde 2DOB (2027): gelijkvormigheid en de
gelijkvormigheidsfactor, schaal als verhouding, het effect van
schaalverandering op lengte, oppervlakte en volume, en de
gelijkvormigheidskenmerken van driehoeken.

Deel 1 is de schaalverandering.
Deel 2 zijn de gelijkvormige driehoeken.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat betekent het dat twee figuren gelijkvormig zijn?",
         opties=["zelfde vorm, andere grootte",
                 "zelfde grootte, andere vorm",
                 "zelfde vorm en grootte",
                 "andere vorm en grootte"],
         antwoord=0,
         uitleg="Alle hoeken zijn gelijk en alle zijden staan in dezelfde verhouding."),
    dict(type="meerkeuze",
         vraag="Wat is de gelijkvormigheidsfactor?",
         opties=["de verhouding van de lengtes",
                 "de verhouding van de hoeken",
                 "het verschil van de lengtes",
                 "de som van de lengtes"],
         antwoord=0,
         uitleg="Je deelt een lengte van de nieuwe figuur door de overeenkomstige lengte van de oude."),
    dict(type="invultekst",
         vraag="Een figuur van 3 cm wordt 12 cm. Wat is de gelijkvormigheidsfactor? Een getal.",
         antwoord=["4", "vier"],
         uitleg="12 gedeeld door 3 is 4. Alle lengtes worden vier keer zo groot."),
    dict(type="meerkeuze",
         vraag="Met welke factor verandert de oppervlakte bij een gelijkvormigheidsfactor 3?",
         opties=["met 9",
                 "met 3 in totaal",
                 "met 6 in totaal",
                 "met 27 in totaal"],
         antwoord=0,
         uitleg="De oppervlakte gaat met het kwadraat van de factor: 3 maal 3 is 9."),
    dict(type="meerkeuze",
         vraag="Met welke factor verandert het volume bij een gelijkvormigheidsfactor 3?",
         opties=["met 27",
                 "met 9 in totaal",
                 "met 3 in totaal",
                 "met 6 in totaal"],
         antwoord=0,
         uitleg="Het volume gaat met de derde macht: 3 maal 3 maal 3 is 27."),
    dict(type="waarofniet",
         vraag="Bij een dubbele lengte wordt de oppervlakte vier keer zo groot.",
         antwoord=True,
         uitleg="2 in het kwadraat is 4. Het volume wordt dan acht keer zo groot."),
    dict(type="invultekst",
         vraag="Met welke factor verandert het volume bij een dubbele lengte? Een getal.",
         antwoord=["8", "acht"],
         uitleg="2 maal 2 maal 2 is 8. De derde macht van de factor."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over schaalverandering kloppen?",
         opties=["lengte gaat met de factor",
                 "oppervlakte met het kwadraat",
                 "volume met de derde macht",
                 "alles gaat met de factor"],
         antwoord=[0, 1, 2],
         uitleg="Juist niet alles met dezelfde factor. Dat is de klassieke misvatting bij dit onderwerp."),
    dict(type="waarofniet",
         vraag="Bij een dubbele lengte wordt het volume ook dubbel zo groot.",
         antwoord=False,
         uitleg="Het wordt acht keer zo groot. Dit is precies het soort uitspraak dat de vakfiche laat weerleggen."),
    dict(type="meerkeuze",
         vraag="Een maquette op schaal 1 op 50. Hoe groot is een gebouw van 4 cm op de maquette?",
         opties=["2 meter",
                 "20 meter",
                 "50 centimeter",
                 "4 meter"],
         antwoord=0,
         uitleg="4 cm maal 50 is 200 cm, dus 2 meter."),
    dict(type="meerkeuze",
         vraag="Een kaart op schaal 1 op 25 000. Hoeveel is 4 cm in het echt?",
         opties=["1 kilometer",
                 "100 meter",
                 "10 kilometer",
                 "25 kilometer"],
         antwoord=0,
         uitleg="4 maal 25 000 is 100 000 cm, en dat is 1 000 meter of 1 kilometer."),
    dict(type="invultekst",
         vraag="Een plan op schaal 1 op 100. Hoeveel meter is 3 cm in het echt? Een getal.",
         antwoord=["3", "drie"],
         uitleg="3 maal 100 is 300 cm, dus 3 meter."),
    dict(type="waarofniet",
         vraag="Bij een schaal hoort altijd een eenheid, zoals centimeter.",
         antwoord=False,
         uitleg="Een schaal is een verhouding: 1 op 50 geldt in welke eenheid je ook meet."),
    dict(type="meerkeuze",
         vraag="Een figuur wordt vergroot met factor 2. Welke uitspraken kloppen?",
         opties=["elke lengte verdubbelt",
                 "de oppervlakte wordt vier keer zo groot",
                 "het volume wordt acht keer zo groot",
                 "de hoeken worden dubbel zo groot"],
         antwoord=[0, 1, 2],
         uitleg="De hoeken blijven juist gelijk. Lengte gaat met de factor, oppervlakte met het kwadraat, volume met de derde macht."),
    dict(type="meerkeuze",
         vraag="Een vierkant van 2 cm zijde wordt vergroot met factor 4. Wat is de nieuwe oppervlakte?",
         opties=["64 vierkante centimeter",
                 "16 vierkante centimeter",
                 "32 vierkante centimeter",
                 "8 vierkante centimeter"],
         antwoord=0,
         uitleg="De zijde wordt 8 cm, dus de oppervlakte 64. Of: 4 maal 4 maal de oude oppervlakte van 4."),
    dict(type="waarofniet",
         vraag="Bij een gelijkvormigheidsfactor kleiner dan 1 wordt de figuur kleiner.",
         antwoord=True,
         uitleg="Een factor van een half halveert elke lengte. De oppervlakte wordt dan een vierde."),
    dict(type="meerkeuze",
         vraag="Welke grootheden veranderen bij een schaalverandering?",
         opties=["de lengte",
                 "de oppervlakte",
                 "het volume",
                 "de hoeken"],
         antwoord=[0, 1, 2],
         uitleg="De hoeken blijven juist gelijk. Dat is de kern van gelijkvormigheid."),
    dict(type="meerkeuze",
         vraag="Een blikje wordt in alle richtingen dubbel zo groot. Hoeveel meer inhoud?",
         opties=["acht keer",
                 "twee keer zoveel",
                 "vier keer zoveel",
                 "zes keer zoveel"],
         antwoord=0,
         uitleg="Het volume gaat met de derde macht van de factor: 2 maal 2 maal 2 is 8."),
    dict(type="meerkeuze",
         vraag="Een foto wordt op dubbele breedte afgedrukt, met dezelfde vorm. Hoeveel inkt is er nodig?",
         opties=["vier keer zoveel",
                 "twee keer zoveel",
                 "acht keer zoveel",
                 "evenveel"],
         antwoord=0,
         uitleg="De inkt volgt de oppervlakte, en die gaat met het kwadraat van de factor."),
    dict(type="meerkeuze",
         vraag="Waarom gebruiken grote dieren dikkere botten dan kleine?",
         opties=["gewicht groeit sneller dan doorsnede",
                 "hun botten zijn van zwakker materiaal",
                 "ze bewegen veel trager dan kleine",
                 "ze leven een stuk langer dan kleine"],
         antwoord=0,
         uitleg="Het gewicht gaat met de derde macht, de doorsnede van een bot met het kwadraat. Een mooi gevolg van schaalverandering."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat betekent het gelijkvormigheidskenmerk HH bij driehoeken?",
         opties=["twee hoeken zijn gelijk",
                 "twee zijden zijn gelijk",
                 "alle zijden zijn gelijk",
                 "één hoek is gelijk"],
         antwoord=0,
         uitleg="Twee gelijke hoeken volstaan: de derde volgt dan automatisch, want de som is 180 graden."),
    dict(type="meerkeuze",
         vraag="Waarom volstaan twee gelijke hoeken om gelijkvormigheid te besluiten?",
         opties=["de derde hoek volgt eruit",
                 "de zijden zijn dan gelijk",
                 "de omtrek is dan gelijk",
                 "de oppervlakte is dan gelijk"],
         antwoord=0,
         uitleg="De hoekensom van een driehoek is altijd 180 graden, dus de derde hoek ligt vast."),
    dict(type="invultekst",
         vraag="Hoeveel graden is de hoekensom van een driehoek? Een getal.",
         antwoord=["180", "honderdtachtig"],
         uitleg="180 graden. Daarom volstaat het kenmerk HH."),
    dict(type="meerkeuze",
         vraag="Welke gelijkvormigheidskenmerken noemt de vakfiche?",
         opties=["HH",
                 "ZHZ",
                 "ZZZ",
                 "ZZH met een scherpe hoek"],
         antwoord=[0, 1, 2],
         uitleg="HH, ZHZ, ZZZ en het geval met een rechte hoek van 90 graden. Een scherpe hoek volstaat niet."),
    dict(type="waarofniet",
         vraag="Bij gelijkvormige driehoeken staan de overeenkomstige zijden in dezelfde verhouding.",
         antwoord=True,
         uitleg="Precies dat laat je de onbekende zijde berekenen met een verhoudingsgelijkheid."),
    dict(type="meerkeuze",
         vraag="Twee driehoeken zijn gelijkvormig met factor 2. De eerste heeft een zijde van 5 cm. Wat is de overeenkomstige zijde?",
         opties=["10 centimeter",
                 "7 centimeter",
                 "2,5 centimeter",
                 "25 centimeter"],
         antwoord=0,
         uitleg="5 maal 2 is 10. Alle lengtes gaan met de factor."),
    dict(type="meerkeuze",
         vraag="In twee gelijkvormige driehoeken zijn de zijden 4 en 6. De tweede zijde van de kleine is 3. Hoe lang is de overeenkomstige?",
         opties=["4,5 centimeter",
                 "5 centimeter",
                 "2 centimeter",
                 "9 centimeter"],
         antwoord=0,
         uitleg="De factor is 6 gedeeld door 4, dus 1,5. En 3 maal 1,5 is 4,5."),
    dict(type="invultekst",
         vraag="De zijden zijn 2 en 10. Wat is de gelijkvormigheidsfactor? Een getal.",
         antwoord=["5", "vijf"],
         uitleg="10 gedeeld door 2 is 5."),
    dict(type="waarofniet",
         vraag="Twee driehoeken met gelijke hoeken hebben altijd dezelfde oppervlakte.",
         antwoord=False,
         uitleg="Ze zijn gelijkvormig, maar niet gelijk. De oppervlakte gaat met het kwadraat van de factor."),
    dict(type="meerkeuze",
         vraag="Welke gegevens volstaan om gelijkvormigheid van twee driehoeken te besluiten?",
         opties=["twee gelijke hoeken",
                 "drie zijden in verhouding",
                 "twee zijden in verhouding met de hoek ertussen",
                 "twee zijden in verhouding alleen"],
         antwoord=[0, 1, 2],
         uitleg="HH, ZZZ en ZHZ volstaan. Twee zijden zonder de ingesloten hoek volstaat niet."),
    dict(type="meerkeuze",
         vraag="Welk kenmerk hoort bij twee zijden in verhouding met de ingesloten hoek gelijk?",
         opties=["ZHZ",
                 "HH van de hoeken",
                 "ZZZ van de zijden",
                 "geen enkel kenmerk"],
         antwoord=0,
         uitleg="Zijde, hoek, zijde: de hoek moet tussen de twee zijden liggen."),
    dict(type="waarofniet",
         vraag="Bij het kenmerk ZHZ moet de hoek tussen de twee zijden liggen.",
         antwoord=True,
         uitleg="Ligt de hoek er niet tussen, dan volstaat het kenmerk niet."),
    dict(type="meerkeuze",
         vraag="Een stok van 1 m geeft een schaduw van 1,5 m, een boom een schaduw van 12 m. Hoe hoog is de boom?",
         opties=["8 meter",
                 "18 meter",
                 "12 meter",
                 "6 meter"],
         antwoord=0,
         uitleg="De driehoeken zijn gelijkvormig: 12 gedeeld door 1,5 is 8, en 1 maal 8 is 8 meter."),
    dict(type="meerkeuze",
         vraag="Waarom zijn de twee driehoeken bij de schaduwmeting gelijkvormig?",
         opties=["de zonnestralen vallen gelijk in",
                 "de twee schaduwen zijn even lang",
                 "de twee hoogtes zijn even groot",
                 "de twee oppervlaktes zijn even groot"],
         antwoord=0,
         uitleg="Dezelfde hoek met de grond en beide keren een rechte hoek: dat is het kenmerk HH."),
    dict(type="invultekst",
         vraag="Een stok van 2 m geeft 3 m schaduw. Hoeveel meter schaduw geeft een boom van 10 m? Een getal.",
         antwoord=["15", "vijftien"],
         uitleg="De verhouding is 3 op 2, dus 10 maal 1,5 is 15 meter."),
    dict(type="waarofniet",
         vraag="Gelijkvormige driehoeken hebben dezelfde omtrek.",
         antwoord=False,
         uitleg="De omtrek gaat met de gelijkvormigheidsfactor mee. Alleen de hoeken blijven gelijk."),
    dict(type="meerkeuze",
         vraag="Welke stappen hoort bij het oplossen met gelijkvormige driehoeken?",
         opties=["het kenmerk aanwijzen",
                 "de verhouding opstellen",
                 "de onbekende berekenen",
                 "de oppervlakte meten"],
         antwoord=[0, 1, 2],
         uitleg="De oppervlakte heb je er niet voor nodig. De vakfiche vraagt wel het kenmerk ter verklaring."),
    dict(type="meerkeuze",
         vraag="Twee driehoeken zijn gelijkvormig met factor 3. Hoeveel groter is de oppervlakte?",
         opties=["negen keer",
                 "drie keer zo groot",
                 "zes keer zo groot",
                 "even groot"],
         antwoord=0,
         uitleg="De oppervlakte gaat met het kwadraat van de factor: 3 maal 3 is 9."),
    dict(type="meerkeuze",
         vraag="Een driehoek heeft hoeken van 40 en 60 graden. Welke heeft de derde?",
         opties=["80 graden",
                 "100 graden",
                 "60 graden",
                 "40 graden"],
         antwoord=0,
         uitleg="180 min 40 min 60 is 80 graden."),
    dict(type="meerkeuze",
         vraag="Waarom vraagt de vakfiche het kenmerk te benoemen en niet enkel te rekenen?",
         opties=["het kenmerk is de verantwoording",
                 "het kenmerk is korter",
                 "het kenmerk is exacter",
                 "het kenmerk vervangt de berekening"],
         antwoord=0,
         uitleg="Zonder kenmerk weet je niet waarom de verhouding mag. Dat is de wiskundige redenering erbij."),
]
