# -*- coding: utf-8 -*-
"""Reële getallen ordenen.

Van de vakfiche wiskunde 2DOB (2027): getallen vergelijken en ordenen met de
symbolen van gelijkheid en ongelijkheid, de getallenas, de afrondingsregels en
de intervalnotatie (open, halfopen en gesloten).

Deel 1 zijn vergelijken, ordenen en afronden.
Deel 2 zijn de getallenas en de intervallen.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Welk symbool betekent kleiner dan of gelijk aan?",
         opties=["het teken met een streepje eronder",
                 "het teken helemaal zonder streepje",
                 "het isgelijkteken met twee strepen",
                 "het ongelijkteken met een schrap"],
         antwoord=0,
         uitleg="Het streepje onder het ongelijkteken voegt de gelijkheid toe. Zonder streepje is het strikt kleiner."),
    dict(type="meerkeuze",
         vraag="Welk getal is het kleinste?",
         opties=["min 5",
                 "min 2",
                 "het getal 0",
                 "het getal 3"],
         antwoord=0,
         uitleg="Bij negatieve getallen is het getal met de grootste cijferwaarde het kleinste."),
    dict(type="invultekst",
         vraag="Rond 3,476 af op twee cijfers na de komma. Een getal.",
         antwoord=["3,48", "3.48"],
         uitleg="Het derde cijfer is een 6, dus het tweede gaat van 7 naar 8."),
    dict(type="meerkeuze",
         vraag="Rond 12,3449 af op één cijfer na de komma.",
         opties=["12,3",
                 "12,4 afgerond",
                 "12,35 afgerond",
                 "12,0 afgerond"],
         antwoord=0,
         uitleg="Het tweede cijfer na de komma is een 4, dus je rondt naar beneden af. Dat de cijfers erna groter zijn, doet niet mee."),
    dict(type="waarofniet",
         vraag="Bij afronden kijk je enkel naar het eerste cijfer dat wegvalt.",
         antwoord=True,
         uitleg="Is dat 5 of meer, dan rond je naar boven af. De cijfers daarachter spelen geen rol."),
    dict(type="meerkeuze",
         vraag="Welke getallen zijn groter dan min 1?",
         opties=["min 0,5",
                 "het getal 0",
                 "het getal 2",
                 "min 3"],
         antwoord=[0, 1, 2],
         uitleg="Drie getallen liggen rechts van min 1 op de getallenas. Min 3 ligt links."),
    dict(type="meerkeuze",
         vraag="Welke rij staat van klein naar groot?",
         opties=["min 2, min 0,5, 0, 1,5",
                 "min 0,5, min 2, 0, 1,5",
                 "0, min 0,5, min 2, 1,5",
                 "1,5, 0, min 0,5, min 2"],
         antwoord=0,
         uitleg="Van links naar rechts op de getallenas. De laatste rij staat net omgekeerd."),
    dict(type="invultekst",
         vraag="Welk getal ligt precies tussen 4 en 7? Een getal.",
         antwoord=["5,5", "5.5"],
         uitleg="Het gemiddelde van 4 en 7: 11 gedeeld door 2 is 5,5."),
    dict(type="waarofniet",
         vraag="Min 10 is groter dan min 3.",
         antwoord=False,
         uitleg="Hoe verder naar links op de getallenas, hoe kleiner. Min 10 is dus kleiner."),
    dict(type="meerkeuze",
         vraag="Welk getal ligt het dichtst bij 2 derde?",
         opties=["0,67",
                 "het getal 0,6",
                 "het getal 0,7",
                 "het getal 0,75"],
         antwoord=0,
         uitleg="2 gedeeld door 3 is 0,6666… Daarvan is 0,67 de beste benadering van de vier."),
    dict(type="meerkeuze",
         vraag="Wat is 0,375 als breuk?",
         opties=["3 achtsten",
                 "3 vierden",
                 "1 derde",
                 "3 vijfden"],
         antwoord=0,
         uitleg="375 duizendsten vereenvoudigd tot 3 achtsten. Deel teller en noemer door 125."),
    dict(type="waarofniet",
         vraag="Een getal van de ene vorm naar de andere omzetten mag volgens de vakfiche niet met ICT.",
         antwoord=False,
         uitleg="De vakfiche vraagt dat juist wel: je zet met ICT een reëel getal om van de ene vorm naar de andere."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over afronden kloppen?",
         opties=["5 of meer rondt naar boven",
                 "minder dan 5 rondt naar beneden",
                 "je kijkt naar het eerste wegvallende cijfer",
                 "je rondt altijd naar boven af"],
         antwoord=[0, 1, 2],
         uitleg="Altijd naar boven afronden zou de resultaten systematisch te groot maken."),
    dict(type="meerkeuze",
         vraag="Rond 1 999 af op honderdtallen.",
         opties=["2 000",
                 "1 900 afgerond",
                 "1 000 afgerond",
                 "2 100 afgerond"],
         antwoord=0,
         uitleg="Het tientalcijfer is 9, dus het honderdtal gaat van 19 naar 20 honderdtallen."),
    dict(type="invultekst",
         vraag="Welk symbool gebruik je voor strikt groter dan? Een teken.",
         antwoord=[">", "groter dan"],
         uitleg="Het teken zonder streepje eronder. Mét streepje betekent groter dan of gelijk aan."),
    dict(type="waarofniet",
         vraag="De uitspraak dat 3 kleiner dan of gelijk aan 3 is, is waar.",
         antwoord=True,
         uitleg="De gelijkheid zit in het symbool, dus de uitspraak klopt. Met strikt kleiner zou ze fout zijn."),
    dict(type="meerkeuze",
         vraag="Welke getallen liggen tussen 1 en 2?",
         opties=["1,5",
                 "de wortel van 2",
                 "7 vijfden",
                 "het getal 2,5"],
         antwoord=[0, 1, 2],
         uitleg="De wortel van 2 is ongeveer 1,41 en 7 vijfden is 1,4. Alleen 2,5 valt erbuiten."),
    dict(type="meerkeuze",
         vraag="Waarom zet je breuken naar de decimale vorm om voor je ze vergelijkt?",
         opties=["zo zie je de orde meteen",
                 "zo zijn ze exacter",
                 "zo zijn ze korter",
                 "zo zijn ze rationaal"],
         antwoord=0,
         uitleg="Twee kommagetallen vergelijk je cijfer per cijfer. Let wel: afronden maakt het minder exact."),
    dict(type="meerkeuze",
         vraag="Welke vergelijking is juist?",
         opties=["min 0,5 is groter dan min 1,5",
                 "min 1,5 is groter dan min 0,5",
                 "min 1,5 is gelijk aan min 0,5",
                 "min 1,5 is groter dan nul"],
         antwoord=0,
         uitleg="Min 0,5 ligt rechts van min 1,5 op de getallenas en is dus groter."),
    dict(type="meerkeuze",
         vraag="Een winkel rondt elke prijs naar boven af op 5 cent. Wat gebeurt er met het totaal?",
         opties=["het wordt systematisch hoger",
                 "het blijft gemiddeld gelijk",
                 "het wordt systematisch lager",
                 "het verandert helemaal niet"],
         antwoord=0,
         uitleg="Wie altijd naar boven afrondt, telt bij elke prijs iets te veel. Daarom bestaat de regel van 5 of meer."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is een open interval?",
         opties=["de grenzen horen er niet bij",
                 "de grenzen horen er wel bij",
                 "er is maar één grens",
                 "er zijn geen grenzen"],
         antwoord=0,
         uitleg="Bij een open interval zijn de grenswaarden zelf uitgesloten. Je noteert ze met gewone haakjes."),
    dict(type="meerkeuze",
         vraag="Wat is een gesloten interval?",
         opties=["de grenzen horen erbij",
                 "de grenzen horen er niet bij",
                 "er is geen bovengrens",
                 "er is geen ondergrens"],
         antwoord=0,
         uitleg="Beide grenswaarden zitten in de verzameling. Je noteert ze met vierkante haakjes naar binnen."),
    dict(type="invultekst",
         vraag="Hoe noem je een interval waarvan één grens erbij hoort en één niet? Eén woord.",
         antwoord=["halfopen", "halfgesloten", "halfopen interval"],
         uitleg="Halfopen of halfgesloten. De vakfiche noemt beide woorden."),
    dict(type="meerkeuze",
         vraag="Welke soorten intervallen noemt de vakfiche?",
         opties=["open",
                 "halfopen of halfgesloten",
                 "gesloten",
                 "dubbel"],
         antwoord=[0, 1, 2],
         uitleg="Die drie staan er. Een dubbel interval bestaat niet als begrip."),
    dict(type="waarofniet",
         vraag="De oplossingenverzameling van een ongelijkheid kan je als interval noteren.",
         antwoord=True,
         uitleg="De vakfiche vraagt dat uitdrukkelijk, en ook om ze op een getallenas voor te stellen."),
    dict(type="meerkeuze",
         vraag="Welk interval hoort bij x groter dan 3?",
         opties=["van 3 open tot plus oneindig",
                 "van 3 gesloten tot plus oneindig",
                 "van min oneindig tot 3",
                 "van 0 tot 3"],
         antwoord=0,
         uitleg="Strikt groter, dus 3 zelf valt erbuiten: open aan de kant van 3."),
    dict(type="meerkeuze",
         vraag="Welk interval hoort bij x kleiner dan of gelijk aan 5?",
         opties=["van min oneindig tot 5 gesloten",
                 "van min oneindig tot 5 open",
                 "van 5 tot plus oneindig",
                 "van 0 tot 5 gesloten"],
         antwoord=0,
         uitleg="Het isgelijkteken zit erin, dus 5 hoort erbij: gesloten aan de kant van 5."),
    dict(type="invultekst",
         vraag="Hoort de grens bij een open interval erbij? Antwoord met ja of nee.",
         antwoord=["nee", "neen", "niet"],
         uitleg="Nee. Bij een gesloten interval wel."),
    dict(type="waarofniet",
         vraag="Aan de kant van oneindig staat een interval altijd open.",
         antwoord=True,
         uitleg="Oneindig is geen getal, dus het kan nooit tot de verzameling horen."),
    dict(type="meerkeuze",
         vraag="Hoe stel je een gesloten interval voor op een getallenas?",
         opties=["met volle bolletjes aan de grenzen",
                 "met open bolletjes aan de grenzen",
                 "met pijlen aan beide zijden",
                 "met een stippellijn"],
         antwoord=0,
         uitleg="Een vol bolletje betekent dat de grens meedoet, een open bolletje dat ze dat niet doet."),
    dict(type="meerkeuze",
         vraag="Welke getallen horen bij het gesloten interval van 2 tot 5?",
         opties=["het getal 2",
                 "het getal 3,5",
                 "het getal 5",
                 "het getal 5,5"],
         antwoord=[0, 1, 2],
         uitleg="Beide grenzen horen erbij en alles ertussen. 5,5 ligt erbuiten."),
    dict(type="meerkeuze",
         vraag="Welke getallen horen bij het open interval van 0 tot 1?",
         opties=["het getal 0,5",
                 "het getal 0,99",
                 "het getal 0,01",
                 "het getal 1"],
         antwoord=[0, 1, 2],
         uitleg="Alles tussen 0 en 1, maar de grenzen zelf niet. Dus 1 valt erbuiten."),
    dict(type="waarofniet",
         vraag="Een interval kan volgens de vakfiche ook maar één getal bevatten.",
         antwoord=False,
         uitleg="Een interval is een aaneengesloten stuk van de getallenas met twee grenzen. Eén getal is een verzameling, geen interval."),
    dict(type="meerkeuze",
         vraag="Een temperatuur ligt tussen min 2 en 8 graden, grenzen meegerekend. Welk interval?",
         opties=["gesloten van min 2 tot 8",
                 "open van min 2 tot 8",
                 "halfopen van min 2 tot 8",
                 "gesloten van 0 tot 8"],
         antwoord=0,
         uitleg="Grenzen meegerekend betekent gesloten aan beide zijden."),
    dict(type="invultekst",
         vraag="Welk soort haakjes hoort bij een open grens? Antwoord rond of vierkant.",
         antwoord=["rond", "ronde", "rond haakje"],
         uitleg="Ronde haakjes voor een open grens, vierkante voor een gesloten grens."),
    dict(type="meerkeuze",
         vraag="Waarom is de intervalnotatie handig bij een ongelijkheid?",
         opties=["ze toont de oplossing in één blik",
                 "ze is korter dan een tekening",
                 "ze geldt enkel voor gehele getallen",
                 "ze vervangt de berekening"],
         antwoord=0,
         uitleg="Je ziet meteen waar de oplossingen beginnen en eindigen, en of de grenzen meedoen."),
    dict(type="waarofniet",
         vraag="Bij x strikt groter dan 0 hoort het getal nul tot de oplossingen.",
         antwoord=False,
         uitleg="Strikt groter sluit de grens uit. Met groter dan of gelijk aan mag nul wel mee."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over de getallenas kloppen?",
         opties=["rechts is groter",
                 "elk reëel getal heeft er een plaats",
                 "ze loopt in beide richtingen door",
                 "ze bevat enkel gehele getallen"],
         antwoord=[0, 1, 2],
         uitleg="Juist alle reële getallen liggen erop. Dat is waarom de reële getallen nodig waren."),
    dict(type="meerkeuze",
         vraag="Een korting geldt vanaf 50 euro. Welk interval hoort bij het bedrag?",
         opties=["gesloten vanaf 50",
                 "open vanaf 50",
                 "gesloten tot 50",
                 "open tot 50"],
         antwoord=0,
         uitleg="Vanaf 50 betekent dat 50 zelf meedoet. Vanaf meer dan 50 zou open zijn."),
    dict(type="meerkeuze",
         vraag="Welk verschil maakt het woord strikt in een ongelijkheid?",
         opties=["de grens valt weg",
                 "de grens komt erbij",
                 "het interval wordt groter",
                 "er verandert niets"],
         antwoord=0,
         uitleg="Strikt groter dan 3 sluit 3 uit. Groter dan of gelijk aan 3 neemt 3 mee."),
]
