# -*- coding: utf-8 -*-
"""Stelsels van twee eerstegraadsvergelijkingen.

Van de vakfiche wiskunde 2DOB (2027): een stelsel van twee
eerstegraadsvergelijkingen in twee onbekenden algebraïsch en grafisch oplossen,
met de combinatiemethode, de substitutiemethode en de gelijkstellingsmethode,
en het verband met snijdende, evenwijdige en samenvallende rechten.

Deel 1 is het algebraïsch oplossen.
Deel 2 zijn de grafische betekenis en de vraagstukken.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is een stelsel van twee vergelijkingen?",
         opties=["twee vergelijkingen die samen gelden",
                 "twee vergelijkingen na elkaar",
                 "twee onbekenden in één vergelijking",
                 "twee oplossingen van één vergelijking"],
         antwoord=0,
         uitleg="Je zoekt de waarden die aan beide vergelijkingen tegelijk voldoen."),
    dict(type="meerkeuze",
         vraag="Welke methodes noemt de vakfiche om een stelsel algebraïsch op te lossen?",
         opties=["de combinatiemethode",
                 "de substitutiemethode",
                 "de gelijkstellingsmethode",
                 "de discriminantmethode"],
         antwoord=[0, 1, 2],
         uitleg="Die drie staan er. De discriminant hoort bij tweedegraadsvergelijkingen."),
    dict(type="invultekst",
         vraag="Welke methode vervangt een onbekende door een uitdrukking? Eén woord.",
         antwoord=["substitutie", "substitutiemethode", "substitueren"],
         uitleg="De substitutiemethode: je maakt één letter vrij en vult die in de andere vergelijking in."),
    dict(type="meerkeuze",
         vraag="Wat doe je bij de combinatiemethode?",
         opties=["optellen of aftrekken",
                 "je vervangt één onbekende door een uitdrukking",
                 "je stelt de twee rechterleden aan elkaar gelijk",
                 "je tekent de twee rechten in een assenstelsel"],
         antwoord=0,
         uitleg="Door slim op te tellen of af te trekken valt één onbekende weg."),
    dict(type="meerkeuze",
         vraag="Los op: x plus y is 10 en x min y is 2.",
         opties=["x is 6 en y is 4",
                 "x is 4 en y is 6",
                 "x is 8 en y is 2",
                 "x is 5 en y is 5"],
         antwoord=0,
         uitleg="Tel op: 2x is 12, dus x is 6. Dan is y 4."),
    dict(type="invultekst",
         vraag="x plus y is 12 en x min y is 4. Wat is x? Een getal.",
         antwoord=["8", "acht"],
         uitleg="Tel op: 2x is 16, dus x is 8. En y is dan 4."),
    dict(type="waarofniet",
         vraag="Bij de combinatiemethode valt één onbekende weg.",
         antwoord=True,
         uitleg="Dat is precies de bedoeling: je houdt één vergelijking met één onbekende over."),
    dict(type="meerkeuze",
         vraag="Los op: y is 2x en x plus y is 9.",
         opties=["x is 3 en y is 6",
                 "x is 6 en y is 3",
                 "x is 4,5 en y is 4,5",
                 "x is 2 en y is 7"],
         antwoord=0,
         uitleg="Vul y is 2x in: x plus 2x is 3x is 9, dus x is 3 en y is 6."),
    dict(type="meerkeuze",
         vraag="Los op: 2x plus y is 11 en y is 3.",
         opties=["x is 4",
                 "x is 7 in totaal",
                 "x is 5,5 in totaal",
                 "x is 8 in totaal"],
         antwoord=0,
         uitleg="Vul y is 3 in: 2x plus 3 is 11, dus 2x is 8 en x is 4."),
    dict(type="invultekst",
         vraag="3x plus y is 17 en y is 2. Wat is x? Een getal.",
         antwoord=["5", "vijf"],
         uitleg="3x plus 2 is 17, dus 3x is 15 en x is 5."),
    dict(type="waarofniet",
         vraag="De oplossing van een stelsel noteer je als één enkel getal.",
         antwoord=False,
         uitleg="Het is een koppel: eerst de x, dan de y. De vakfiche noemt dat de koppelvoorstelling."),
    dict(type="meerkeuze",
         vraag="Wat is een strijdig stelsel?",
         opties=["het heeft geen oplossing",
                 "het heeft één oplossing",
                 "het heeft oneindig veel oplossingen",
                 "het heeft twee oplossingen"],
         antwoord=0,
         uitleg="De oplossingenverzameling is leeg. Grafisch zijn het twee evenwijdige rechten die niet samenvallen."),
    dict(type="meerkeuze",
         vraag="Wat is een onbepaald stelsel?",
         opties=["het heeft oneindig veel oplossingen",
                 "het heeft geen enkele oplossing",
                 "het heeft precies één oplossing",
                 "het heeft precies twee oplossingen"],
         antwoord=0,
         uitleg="De twee vergelijkingen zeggen hetzelfde. Grafisch vallen de rechten samen."),
    dict(type="waarofniet",
         vraag="Een stelsel met precies één oplossing heet een strijdig stelsel.",
         antwoord=False,
         uitleg="Dat heet een bepaald stelsel. Strijdig betekent juist dat er geen oplossing is."),
    dict(type="waarofniet",
         vraag="Een strijdig stelsel heeft als oplossingenverzameling de lege verzameling.",
         antwoord=True,
         uitleg="Zo staat het op de vakfiche. Er is geen enkel koppel dat aan beide vergelijkingen voldoet."),
    dict(type="meerkeuze",
         vraag="Welke soorten stelsels noemt de vakfiche?",
         opties=["bepaald",
                 "strijdig",
                 "onbepaald",
                 "kwadratisch"],
         antwoord=[0, 1, 2],
         uitleg="Drie soorten, elk met hun grafische betekenis. Kwadratisch hoort bij de tweede graad."),
    dict(type="meerkeuze",
         vraag="Los op: x plus y is 5 en 2x plus 2y is 10.",
         opties=["oneindig veel oplossingen",
                 "geen oplossing",
                 "x is 5 en y is 0",
                 "x is 2,5 en y is 2,5"],
         antwoord=0,
         uitleg="De tweede vergelijking is het dubbele van de eerste. Een onbepaald stelsel."),
    dict(type="meerkeuze",
         vraag="Los op: x plus y is 5 en x plus y is 7.",
         opties=["geen oplossing",
                 "oneindig veel oplossingen",
                 "x is 6 en y is 0",
                 "x is 1 en y is 6"],
         antwoord=0,
         uitleg="Dezelfde som kan niet 5 en 7 zijn. Een strijdig stelsel."),
    dict(type="meerkeuze",
         vraag="Welke methode kies je bij y is 3x min 1 en y is x plus 5?",
         opties=["de gelijkstellingsmethode",
                 "de combinatiemethode",
                 "de discriminantmethode",
                 "geen enkele methode"],
         antwoord=0,
         uitleg="Beide keren staat y alleen. Stel de rechterleden gelijk: 3x min 1 is x plus 5."),
    dict(type="meerkeuze",
         vraag="Los op: y is 3x min 1 en y is x plus 5.",
         opties=["x is 3 en y is 8",
                 "x is 2 en y is 5",
                 "x is 8 en y is 3",
                 "x is 1 en y is 2"],
         antwoord=0,
         uitleg="3x min 1 is x plus 5 geeft 2x is 6, dus x is 3 en y is 8."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat betekent de oplossing van een stelsel grafisch?",
         opties=["het snijpunt van twee rechten",
                 "de top van een parabool",
                 "het snijpunt met de y-as",
                 "de hoek tussen twee rechten"],
         antwoord=0,
         uitleg="Het punt dat op beide rechten ligt, voldoet aan beide vergelijkingen."),
    dict(type="meerkeuze",
         vraag="Welke grafiek hoort bij een strijdig stelsel?",
         opties=["twee evenwijdige rechten",
                 "twee snijdende rechten",
                 "twee samenvallende rechten",
                 "een parabool en een rechte"],
         antwoord=0,
         uitleg="Evenwijdig en niet samenvallend: ze ontmoeten elkaar nergens."),
    dict(type="meerkeuze",
         vraag="Welke grafiek hoort bij een onbepaald stelsel?",
         opties=["twee samenvallende rechten",
                 "twee evenwijdige rechten",
                 "twee snijdende rechten",
                 "twee kruisende rechten"],
         antwoord=0,
         uitleg="Ze liggen precies op elkaar, dus elk punt is een oplossing."),
    dict(type="invultekst",
         vraag="Hoeveel snijpunten hebben twee evenwijdige, niet samenvallende rechten? Een getal.",
         antwoord=["0", "nul", "geen"],
         uitleg="Geen enkel. Daarom is het stelsel strijdig."),
    dict(type="waarofniet",
         vraag="Twee rechten met dezelfde richtingscoëfficiënt zijn evenwijdig.",
         antwoord=True,
         uitleg="Verschilt ook hun snijpunt met de y-as, dan vallen ze niet samen en is het stelsel strijdig."),
    dict(type="meerkeuze",
         vraag="Twee rechten hebben dezelfde richtingscoëfficiënt en hetzelfde snijpunt met de y-as. Welk stelsel?",
         opties=["onbepaald",
                 "strijdig van aard",
                 "bepaald van aard",
                 "geen stelsel"],
         antwoord=0,
         uitleg="Ze zijn dezelfde rechte, dus elk punt is een oplossing."),
    dict(type="meerkeuze",
         vraag="Twee rechten hebben een verschillende richtingscoëfficiënt. Welk stelsel?",
         opties=["bepaald",
                 "strijdig van aard",
                 "onbepaald van aard",
                 "geen stelsel"],
         antwoord=0,
         uitleg="Verschillende richting betekent dat ze ergens snijden: precies één oplossing."),
    dict(type="invultekst",
         vraag="Hoeveel oplossingen heeft een bepaald stelsel? Een getal.",
         antwoord=["1", "een", "één"],
         uitleg="Precies één koppel. Grafisch het ene snijpunt."),
    dict(type="waarofniet",
         vraag="Een stelsel grafisch oplossen mag volgens de vakfiche met ICT.",
         antwoord=True,
         uitleg="De fiche vraagt het zelfs: je lost stelsels grafisch op, met en zonder ICT."),
    dict(type="meerkeuze",
         vraag="Twee abonnementen: 20 euro plus 2 per uur, en 10 euro plus 4 per uur. Wanneer kosten ze gelijk?",
         opties=["na 5 uur",
                 "na 10 uur",
                 "na 15 uur",
                 "na 2 uur"],
         antwoord=0,
         uitleg="20 plus 2x is 10 plus 4x geeft 10 is 2x, dus x is 5."),
    dict(type="meerkeuze",
         vraag="Welk abonnement is bij veel uren het voordeligst?",
         opties=["dat met het laagste uurtarief",
                 "dat met de laagste vaste prijs",
                 "beide zijn gelijk",
                 "dat met de hoogste vaste prijs"],
         antwoord=0,
         uitleg="Bij veel uren weegt het uurtarief het zwaarst. Het snijpunt zegt waar de omslag ligt."),
    dict(type="invultekst",
         vraag="Twee getallen hebben som 20 en verschil 4. Wat is het grootste? Een getal.",
         antwoord=["12", "twaalf"],
         uitleg="x plus y is 20 en x min y is 4, dus 2x is 24 en x is 12."),
    dict(type="waarofniet",
         vraag="Een vraagstuk met twee onbekenden los je met één vergelijking op.",
         antwoord=False,
         uitleg="Dan blijft het onbepaald. Je hebt evenveel vergelijkingen als onbekenden nodig."),
    dict(type="meerkeuze",
         vraag="Twaalf stukken fruit, appels en peren. Er zijn 4 peren meer dan appels. Hoeveel appels?",
         opties=["4 appels",
                 "6 appels",
                 "8 appels",
                 "2 appels"],
         antwoord=0,
         uitleg="a plus p is 12 en p is a plus 4, dus 2a plus 4 is 12 en a is 4."),
    dict(type="meerkeuze",
         vraag="Welke stappen horen bij een vraagstuk met een stelsel?",
         opties=["twee onbekenden benoemen",
                 "twee vergelijkingen opstellen",
                 "het stelsel oplossen",
                 "de top berekenen"],
         antwoord=[0, 1, 2],
         uitleg="Een top hoort bij een parabool. De vakfiche vraagt wel het antwoord terug in de context te plaatsen."),
    dict(type="meerkeuze",
         vraag="Waarom controleer je je oplossing in beide vergelijkingen?",
         opties=["ze moet aan beide voldoen",
                 "één vergelijking volstaat",
                 "dat is verplicht",
                 "zo mag je afronden"],
         antwoord=0,
         uitleg="Een koppel dat maar aan één vergelijking voldoet, is geen oplossing van het stelsel."),
    dict(type="waarofniet",
         vraag="Grafisch oplossen is even nauwkeurig als algebraïsch oplossen.",
         antwoord=False,
         uitleg="Een snijpunt lees je af en dat is zelden exact. Algebraïsch krijg je de precieze waarden."),
    dict(type="meerkeuze",
         vraag="Twee kaarsen: de eerste is 20 cm en brandt 2 cm per uur, de tweede 14 cm en brandt 1 cm per uur. Wanneer zijn ze gelijk?",
         opties=["na 6 uur",
                 "na 3 uur",
                 "na 10 uur",
                 "na 14 uur"],
         antwoord=0,
         uitleg="20 min 2x is 14 min x geeft 6 is x. Beide zijn dan 8 cm."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over stelsels kloppen?",
         opties=["ze kunnen geen oplossing hebben",
                 "ze kunnen oneindig veel oplossingen hebben",
                 "ze kunnen precies één oplossing hebben",
                 "ze hebben altijd twee oplossingen"],
         antwoord=[0, 1, 2],
         uitleg="Strijdig, onbepaald of bepaald. Twee oplossingen bestaat niet bij een stelsel van eerstegraadsvergelijkingen."),
    dict(type="meerkeuze",
         vraag="Waarom is het nuttig het soort stelsel te benoemen?",
         opties=["je weet wat je antwoord betekent",
                 "je weet hoe lang het duurt",
                 "je weet welke app je nodig hebt",
                 "je weet de richtingscoëfficiënt"],
         antwoord=0,
         uitleg="Komt er 0 is 5 uit, dan is het stelsel strijdig en is dat je antwoord, geen rekenfout."),
]
