# -*- coding: utf-8 -*-
"""Verbanden tussen twee grootheden.

Van de vakfiche wiskunde 2DOB (2027): het spreidingsdiagram, de trendlijn, de
correlatiecoëfficiënt en haar betekenis, en het onderscheid tussen samenhang
en oorzakelijk verband.

Deel 1 is het spreidingsdiagram en de trendlijn.
Deel 2 is de correlatie en het verschil met causaliteit.
"""

DEEL1 = [
    dict(type="meerkeuze",
         vraag="Wat is een spreidingsdiagram?",
         opties=["een punt per meetpaar",
                 "een staaf per categorie ervan",
                 "een lijn door de tijd heen",
                 "een cirkel met partjes erin"],
         antwoord=0,
         uitleg="Elk punt heeft twee waarden: een op de x-as en een op de y-as."),
    dict(type="meerkeuze",
         vraag="Waarvoor gebruik je een spreidingsdiagram?",
         opties=["een verband tussen twee grootheden zien",
                 "de verdeling van een categorie tonen ervan",
                 "het verloop van een getal in de tijd tonen",
                 "het aantal gegevens in een klasse tellen"],
         antwoord=0,
         uitleg="Je ziet meteen of de punten een richting hebben."),
    dict(type="meerkeuze",
         vraag="Wat is een trendlijn?",
         opties=["een rechte die het patroon volgt",
                 "een lijn door alle punten heen",
                 "de rand van de puntenwolk ervan",
                 "een lijn van links naar rechts onderaan"],
         antwoord=0,
         uitleg="Ze loopt zo dicht mogelijk bij alle punten, zonder er per se door te gaan."),
    dict(type="meerkeuze",
         vraag="Wat zie je in een spreidingsdiagram bij een positief verband?",
         opties=["de punten stijgen",
                 "de punten dalen ervan",
                 "de punten liggen in een cirkel",
                 "de punten liggen op een rij verticaal"],
         antwoord=0,
         uitleg="Hoe hoger x, hoe hoger y. De trendlijn stijgt dan."),
    dict(type="invultekst",
         vraag="Hoe noem je de wolk punten in een spreidingsdiagram? Hoogstens drie woorden.",
         antwoord=["puntenwolk", "een puntenwolk"],
         uitleg="De puntenwolk. Haar vorm verraadt het verband."),
    dict(type="waarofniet",
         vraag="Een trendlijn hoeft niet door alle punten te gaan.",
         antwoord=True,
         uitleg="Ze volgt het patroon. Door alle punten gaan lukt meestal niet eens."),
    dict(type="waarofniet",
         vraag="Een spreidingsdiagram toont een verloop in de tijd.",
         antwoord=False,
         uitleg="Dat doet een lijndiagram. Een spreidingsdiagram zet twee grootheden tegen elkaar."),
    dict(type="meerkeuze",
         vraag="Wat zie je bij een negatief verband?",
         opties=["hoe hoger x, hoe lager y",
                 "hoe hoger x, hoe hoger y ook",
                 "x en y blijven altijd gelijk",
                 "de punten liggen allemaal samen"],
         antwoord=0,
         uitleg="De trendlijn daalt. Meer schermtijd en minder uren slaap, bijvoorbeeld."),
    dict(type="meerkeuze",
         vraag="Wat betekent een puntenwolk zonder richting?",
         opties=["er is geen verband",
                 "er is een sterk verband",
                 "de gegevens zijn fout gemeten",
                 "de twee assen staan verwisseld"],
         antwoord=0,
         uitleg="De punten liggen verspreid. Dan is er geen lineair verband te zien."),
    dict(type="meerkeuze",
         vraag="Wat lees je uit een spreidingsdiagram?",
         opties=["de richting van het verband",
                 "hoe sterk het verband is",
                 "of er uitschieters zijn",
                 "hoeveel procent iets is"],
         antwoord=[0, 1, 2],
         uitleg="Richting, sterkte en uitschieters. Een percentage lees je er niet uit."),
    dict(type="meerkeuze",
         vraag="Waarvoor dient een trendlijn?",
         opties=["een voorspelling doen",
                 "de punten mooier tekenen",
                 "de uitschieters wegwerken",
                 "de assen van naam voorzien"],
         antwoord=0,
         uitleg="Met haar vergelijking schat je een y bij een x die je niet gemeten hebt."),
    dict(type="meerkeuze",
         vraag="Wat is het risico van voorspellen ver buiten de gemeten waarden?",
         opties=["het verband kan daar anders zijn",
                 "de trendlijn wordt dan te kort",
                 "de punten verdwijnen van de grafiek",
                 "de eenheden veranderen daarbuiten"],
         antwoord=0,
         uitleg="Buiten het bereik van je metingen weet je niet of de rechte nog klopt."),
    dict(type="waarofniet",
         vraag="Een uitschieter kan de trendlijn flink doen kantelen.",
         antwoord=True,
         uitleg="Eén punt ver weg trekt de rechte mee. Kijk dus altijd eerst naar de wolk."),
    dict(type="waarofniet",
         vraag="Een trendlijn is altijd een rechte.",
         antwoord=False,
         uitleg="Vaak wel, maar een verband kan ook krom zijn. Dan past een rechte niet goed."),
    dict(type="invultekst",
         vraag="Hoeveel waarden horen er bij elk punt van een spreidingsdiagram? Een getal.",
         antwoord=["2", "twee"],
         uitleg="Twee: een x-waarde en een y-waarde."),
    dict(type="meerkeuze",
         vraag="Hoe teken je een trendlijn het best met de hand?",
         opties=["evenveel punten boven als onder",
                 "door het hoogste en het laagste punt",
                 "van de linkerhoek naar de rechterhoek",
                 "door het eerste en het laatste punt"],
         antwoord=0,
         uitleg="Zo ligt ze zo dicht mogelijk bij de hele puntenwolk."),
    dict(type="meerkeuze",
         vraag="Welke verbanden kan een puntenwolk tonen?",
         opties=["een stijgend verband",
                 "een dalend verband",
                 "geen verband",
                 "een verband in procent"],
         antwoord=[0, 1, 2],
         uitleg="Stijgend, dalend of geen. Een percentage is geen soort verband."),
    dict(type="meerkeuze",
         vraag="In een spreidingsdiagram van lengte en schoenmaat stijgen de punten. Wat betekent dat?",
         opties=["grotere mensen, grotere maat",
                 "grotere mensen, kleinere maat",
                 "lengte en maat hangen niet samen",
                 "de meting is verkeerd gebeurd"],
         antwoord=0,
         uitleg="Een positief verband, en hier ook een dat je logisch kan verklaren."),
    dict(type="meerkeuze",
         vraag="Wat hoort bij een goed spreidingsdiagram?",
         opties=["een naam bij elke as",
                 "de eenheid erbij",
                 "een passende schaal",
                 "een lijn door elk punt"],
         antwoord=[0, 1, 2],
         uitleg="De punten verbinden hoort er niet bij. Dat zou een lijndiagram zijn."),
    dict(type="invultekst",
         vraag="Hoe noem je de rechte die het patroon van een puntenwolk volgt? Eén woord.",
         antwoord=["trendlijn", "de trendlijn", "regressielijn"],
         uitleg="De trendlijn."),
]

DEEL2 = [
    dict(type="meerkeuze",
         vraag="Wat is correlatie?",
         opties=["samenhang tussen twee grootheden",
                 "het oorzakelijk verband ertussen",
                 "het gemiddelde van twee reeksen",
                 "het verschil tussen twee metingen"],
         antwoord=0,
         uitleg="Samenhang, meer niet. Of de een de ander veroorzaakt, zegt correlatie niet."),
    dict(type="meerkeuze",
         vraag="Tussen welke waarden ligt de correlatiecoëfficiënt?",
         opties=["tussen min 1 en 1",
                 "tussen 0 en 100 procent",
                 "tussen min 100 en 100",
                 "tussen 0 en oneindig veel"],
         antwoord=0,
         uitleg="Min 1 is een perfect dalend verband, 1 een perfect stijgend, 0 geen lineair verband."),
    dict(type="meerkeuze",
         vraag="Wat betekent een correlatiecoëfficiënt van 0,9?",
         opties=["een sterk stijgend verband",
                 "een sterk dalend verband ervan",
                 "nauwelijks enig verband ervan",
                 "negentig procent van de punten"],
         antwoord=0,
         uitleg="Dicht bij 1, dus de punten liggen bijna op een stijgende rechte."),
    dict(type="meerkeuze",
         vraag="Wat betekent een correlatiecoëfficiënt van min 0,8?",
         opties=["een sterk dalend verband",
                 "een zwak stijgend verband ervan",
                 "helemaal geen verband ervan",
                 "een fout in de berekening ervan"],
         antwoord=0,
         uitleg="Het teken geeft de richting, de grootte geeft de sterkte."),
    dict(type="invultekst",
         vraag="Welke waarde van de correlatiecoëfficiënt wijst op geen lineair verband? Een getal.",
         antwoord=["0", "nul"],
         uitleg="Nul. De punten liggen dan zonder richting verspreid."),
    dict(type="waarofniet",
         vraag="Correlatie is geen causaliteit.",
         antwoord=True,
         uitleg="Samen bewegen is niet hetzelfde als elkaar veroorzaken."),
    dict(type="waarofniet",
         vraag="Een sterke correlatie bewijst dat het ene het andere veroorzaakt.",
         antwoord=False,
         uitleg="Er kan een derde factor meespelen, of het kan toeval zijn."),
    dict(type="meerkeuze",
         vraag="Wat is een derde factor?",
         opties=["iets dat beide verklaart",
                 "een derde meting van hetzelfde",
                 "de derde waarde in een reeks",
                 "een punt dat ver afligt ervan"],
         antwoord=0,
         uitleg="IJsjes en zwemongevallen stijgen samen, maar de warmte verklaart beide."),
    dict(type="meerkeuze",
         vraag="Waarom stijgen het aantal ijsjes en het aantal zwemongevallen samen?",
         opties=["het is warm weer",
                 "ijs eten maakt onvoorzichtig",
                 "zwemmen geeft zin in ijs",
                 "het is louter een rekenfout"],
         antwoord=0,
         uitleg="Het schoolvoorbeeld van een derde factor: de warmte duwt beide omhoog."),
    dict(type="meerkeuze",
         vraag="Wat kan een sterke correlatie verklaren?",
         opties=["het ene veroorzaakt het andere",
                 "een derde factor verklaart beide",
                 "het is toeval",
                 "de metingen zijn altijd fout"],
         antwoord=[0, 1, 2],
         uitleg="Drie mogelijkheden. Enkel verder onderzoek wijst uit welke het is."),
    dict(type="meerkeuze",
         vraag="Hoe kan je een oorzakelijk verband wel aantonen?",
         opties=["met een opgezet experiment",
                 "met nog meer metingen erbij",
                 "met een hogere correlatie ervan",
                 "met een mooiere grafiek ervan"],
         antwoord=0,
         uitleg="Door één ding te veranderen en de rest gelijk te houden. Dat kan een grafiek niet."),
    dict(type="meerkeuze",
         vraag="Wat betekent een correlatie van 0,1?",
         opties=["bijna geen verband",
                 "een zeer sterk verband",
                 "een dalend verband ervan",
                 "tien procent van de punten"],
         antwoord=0,
         uitleg="Dicht bij nul, dus de punten liggen bijna richtingloos."),
    dict(type="waarofniet",
         vraag="Een correlatiecoëfficiënt zegt enkel iets over een lineair verband.",
         antwoord=True,
         uitleg="Een duidelijk krom verband kan toch een correlatie dicht bij nul geven."),
    dict(type="waarofniet",
         vraag="Een correlatie van min 1 is zwakker dan een van 0,5.",
         antwoord=False,
         uitleg="Min 1 is net het sterkst mogelijke verband. Kijk naar de grootte, niet naar het teken."),
    dict(type="invultekst",
         vraag="Hoe noem je een factor die twee grootheden samen omhoog duwt? Hoogstens drie woorden.",
         antwoord=["derde factor", "een derde factor", "verstorende factor"],
         uitleg="Een derde factor. Zij verklaart beide reeksen tegelijk."),
    dict(type="meerkeuze",
         vraag="Welke uitspraken over correlatie zijn juist?",
         opties=["het teken geeft de richting",
                 "de grootte geeft de sterkte",
                 "ze bewijst geen oorzaak",
                 "ze ligt altijd boven nul"],
         antwoord=[0, 1, 2],
         uitleg="Een correlatie kan evengoed negatief zijn."),
    dict(type="meerkeuze",
         vraag="Het aantal ooievaars en het aantal geboorten stijgen samen in een land. Wat besluit je?",
         opties=["er is enkel samenhang",
                 "ooievaars brengen baby's",
                 "baby's lokken ooievaars",
                 "de cijfers zijn vervalst ervan"],
         antwoord=0,
         uitleg="Het bekendste voorbeeld van een schijnverband. Meestal zit er een derde factor achter."),
    dict(type="meerkeuze",
         vraag="Wat doe je voor je uit een grafiek een oorzaak besluit?",
         opties=["zoeken naar een verklaring",
                 "de correlatie groter maken",
                 "de uitschieters weglaten ervan",
                 "de assen van plaats wisselen"],
         antwoord=0,
         uitleg="Een verband zonder plausibele verklaring blijft een vermoeden."),
    dict(type="meerkeuze",
         vraag="Wat mag je uit een correlatiecoëfficiënt van 0,95 besluiten?",
         opties=["de punten liggen dicht bij een rechte",
                 "het verband is stijgend",
                 "voorspellen lukt hier redelijk goed",
                 "het ene veroorzaakt het andere"],
         antwoord=[0, 1, 2],
         uitleg="Sterk en stijgend, maar over oorzaak zegt dat getal niets."),
    dict(type="invultekst",
         vraag="Wat is de sterkst mogelijke waarde van een correlatiecoëfficiënt? Een getal.",
         antwoord=["1", "-1", "1 of -1", "een"],
         uitleg="1 of min 1. Dan liggen alle punten precies op een rechte."),
]
